Homebrew/brew

Library/Homebrew/extend/os/mac/hardware.rb
Library/Homebrew/hardware.rb

The oldest Apple supported hardware for Big Sur is as follows:
* MacBookAir6,1 - Haswell
* MacBookPro11,1 - Haswell
* MacPro6,1 - Ivy Bridge EP
* iMac14,4 - Haswell
* Macmini7,1 - Haswell
* MacBook8,1 - Broadwell
~~We could probably get away with specifying Ivy Bridge, but Ivy Bridge EP is the Intel Xeon version of Ivy Bridge and is actually based on the Sandy Bridge architecture. It's unclear how much this would affect compiler behavior but it's probably better to be safer here.~~
The most significant change is that bottles can now use AVX instructions.
References:
* https://support.apple.com/en-us/HT211238
* https://en.wikipedia.org/wiki/List_of_Macintosh_models_grouped_by_CPU_type#Sandy_Bridge
* https://en.wikipedia.org/wiki/Ivy_Bridge_(microarchitecture)#Ivy_Bridge-E/EN/EP/EX_features …

hardware: optimize Big Sur bottles for Ivy Bridge

---

Library/Homebrew/dev-cmd/bump-revision.rb
Library/Homebrew/test/utils/ast_spec.rb
Library/Homebrew/utils/ast.rb
Library/Homebrew/utils/bottles.rb

-----
This PR adds two functions:
- `Utils::AST.replace_formula_stanza!`
- `Utils::AST.add_formula_stanza!`
These will be useful for gradually replacing regexes (which can sometimes be unreliable)

utils: add AST helper functions for editing formulae

---

Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/strategy.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/test/livecheck/strategy/page_match_spec.rb

-----
These are the original changes seen in #9535 and they are intended to fix the issue that we've been dealing with where `open-uri` will give an error when an HTTPS URL redirects to an HTTP URL. This is primarily affecting the `Gnome` strategy (as they recently added an HTTP mirror, so the URL in the strategy frequently redirects from HTTPS to HTTP) and that's causing problems for related formulae on homebrew/core CI.
Though #9535 addresses the same issue by switching from `open-uri` to `Curl`, that PR is currently blocked while I investigate what's causing a hang in the middle of longer runs. I won't be able to return to that PR for at least a few days, so I think we should incorporate this fix to the current `open-uri` version in the interim time.
I've tried to keep the changes here …

Strategy: Manually handle redirections

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/tap_auditor.rb
Library/Homebrew/utils/shared_audits.rb

-----
This is the final (I think) step in the migration of formula/cask lists to their respective taps. Here are the three lists that are modified by this PR:
1. `GITHUB_PRERELEASE_ALLOWLIST` is being split and migrated to the homebrew/core and homebrew/cask taps
1. `GITLAB_PRERELEASE_ALLOWLIST` is being migrated to the homebrew/core and homebrew/cask taps. It's currently empty but I've migrated them so maintainers know it is an option. Alternatively, it can be deleted and re-added when (if) it's needed.
1. `GITHUB_FORK_ALLOWLIST` is being removed. This was only used for new formulae and casks, so it doesn't need to be in a list. If we want to allow a fork when adding new formulae/casks, I think we should just ignore the audit. It doesn't make sense to add to a list that will never be …

audit: migrate shared audits to taps

---

Library/Homebrew/formula.rb

-----
This PR adds the `Formula#deprecation_date` and `Formula#disable_date` methods. These will return the respective dates when they exist. If not, the methods return `nil`. This is needed for https://github.com/Homebrew/actions/pull/133 and https://github.com/Homebrew/homebrew-core/pull/67386.
I'm marking this as critical because it is blocking those other PRs. Since the PR is a simple change that only adds methods that aren't used in the codebase yet, I don't feel the full 24 hours are needed. However, I will wait to merge until I'm ready to move forward with the other PRs.

formula: add deprecation_date and disable_date methods

---

Library/Homebrew/livecheck/strategy.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/livecheck/strategy/sparkle.rb

-----
Fix regression introduced in https://github.com/Homebrew/brew/pull/10106.

Fix `Sparkle` strategy.

---

Library/Homebrew/rubocops/components_order.rb
Library/Homebrew/test/rubocops/components_order_spec.rb

-----
This PR fixes a `brew style` bug for the `on_macos` and `on_linux` checks with resource blocks.
Previously, the following would cause an error that broke `brew style` (this example is from https://github.com/Homebrew/homebrew-core/pull/67535):
```ruby
resource "cargobootstrap" do
on_macos do
if Hardware::CPU.arch == :arm64
url "https://static.rust-lang.org/dist/2020-12-23/cargo-beta-aarch64-apple-darwin.tar.gz"
sha256 "efbc0e72533d4ca7def9a985feef4b3e43d24f1f6792815bdba9125af1f8ecdf"
else
url "https://static.rust-lang.org/dist/2020-11-19/cargo-1.48.0-x86_64-apple-darwin.tar.gz"
sha256 "ce00d796cf5a9ac8d88d9df94c408e5d7ccd3541932a829eae833cc8e57efb15"
end
end
end
```
Now, this will trigger the style issue and give the following message:
```
only a url and a sha256 (in the right …
```

style: fix on_macos/on_linux resource block checks

---

Library/Homebrew/dev-cmd/bottle.rb

-----
This pull request refactors the confusing `brew bottle --merge --keep-old` logic and extracts it out into a helper function in `Utils::Bottles`.
Notable changes:
- Use `Formulary` to read the formula from `path` and get a `Formula` instance.
- This is used to get the formula's `bottle_specification`, which is easier to use and reason about than with regexes and string manipulation.
- Replaced some `unless` statements with their equivalent `if` statements.
- Removed support for old `sha1` checksums.
(This needs to be rebased after merging https://github.com/Homebrew/brew/pull/10097, which will allow this PR to be tested for any possible regressions.)

bottle: add merge_bottle_spec helper function

---

Library/Homebrew/dev-cmd/bottle.rb

bottle --merge: check for all cellars

---

Library/Homebrew/cask/installer.rb

-----
If the tap of the conflicted cask is not installed, we should just skip it. This matches the behavior of formula installation.
Without this, running `brew install dropbox` would result to install the `homebrew/cask-versions` tap.

cask/installer: do not install tap during conflict checking

---

Library/Homebrew/os/mac/sdk.rb

- This returned an error about `Language::Java::java_home`
-----
This implements feedback from https://github.com/Homebrew/brew/pull/10072.
We try to use a more sensible version check for the SDK, by querying, in order of priority:
1. `sdk_prefix/MacOSX.sdk/SDKSettings.json`
2. ~`sdk_prefix/MacOSX.sdk/SDKSettings.plist`~
3. ~`OS::Mac.sdk_version`~

os/mac/sdk: parse version from SDKSettings.json

---

Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/install.rb

Remove warning on ARM

---

Library/Homebrew/formula_auditor.rb

-----
This PR makes dependency audit more strict and prohibits using aliases (at all) in `depends_on` in homebrew-core:
```ruby
depends_on "openjdk@15"
depends_on "openjdk"
depends_on "openjdk"
```
Motivation:
- We'd like formulae to use the latest version of dependencies (when possible). When a new version of the formula appears we'd like all the depending on it formulae to start using it. So having `openjdk@15` as a dependency will not allow us making this switch (to the next `openjdk@16`) automatically and will require manual formula tuning. Also, we don't have such kind of examples in homebrew-core;
- Currently, dependency audit doesn't work for `openssl@1.1` and `python@3.9` (these are special cases when an unversioned formula is an alias to versioned one). And it was easier to make …

formula_auditor: do not allow depending on aliases

---

Library/Homebrew/cli/parser.rb
Library/Homebrew/cmd/list.rb

-----
- Fixes #10116 (part two).
- These are documented as only working on formulae, but users expect the same options (long format, reverse order or sort by modified time) to be passed to both formulae and casks in the default `brew list`. The output looks weird as they're not. Hence, constrain these to be `--formula`-only.
- This was added originally in 5adb76a5babdccd2c4edfb8752ac979ed14716ca, but disappeared later (I've not yet dug through and found why).
- This also fixes the CLI parser's handling of error messages for short options (assuming they're only a single character). Before, the error messages for this missing `--formula` option on `brew list -l` was `Error: Invalid usage: `--l` cannot be passed without `--formula`.`. ~I don't much like this code, but I'll revisit it later - …

cmd/list: Constrain `-lrt` options to formulae

---

Library/Homebrew/utils/shared_audits.rb

-----
Fixes an issue with the GitHub prerelease audit. Previously, this would fail for prereleases that were added to the exception list. Not sure how this slipped through my testing... :facepalm:

audit: fix prerelease audit

---

Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/strategy/apache.rb
Library/Homebrew/livecheck/strategy/bitbucket.rb
Library/Homebrew/livecheck/strategy/cpan.rb
Library/Homebrew/livecheck/strategy/github_latest.rb
Library/Homebrew/livecheck/strategy/gnome.rb
Library/Homebrew/livecheck/strategy/gnu.rb
Library/Homebrew/livecheck/strategy/hackage.rb
Library/Homebrew/livecheck/strategy/launchpad.rb
Library/Homebrew/livecheck/strategy/npm.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/livecheck/strategy/pypi.rb
Library/Homebrew/livecheck/strategy/sourceforge.rb
Library/Homebrew/livecheck/strategy/xorg.rb
Library/Homebrew/test/livecheck/strategy/page_match_spec.rb

-----
I'm working on extracting changes in #9535 that aren't specifically related to the migration from `open-uri` to `curl` into separate, topical PRs. This will help to minimize the number of changes in that PR, which certainly won't hurt when it comes to troubleshooting the hang we're seeing when using `curl`.
This PR modifies `PageMatch#find_versions` to accept an optional `provided_content` parameter, which allows the method to work with cached page content. When page content is provided, we don't fetch the content at the `url` (using `Strategy#page_content`).
Since the `Xorg` strategy tends to check the same x.org pages over and over for related formulae, we implemented a simple caching system to minimize the number of times we fetch these pages. As a result, `Xorg#find_versions` …

Xorg: Use PageMatch#find_versions

---

Library/Homebrew/livecheck.rb

---
`livecheck` is a replacement for `appcast`, so `:appcast` should never be needed. The `:cask_url` naming is weird, since the `url` is always the cask url. `url :url` may look weird, but at least is consistent with `url :homepage`.

Remove `:appcast` and rename `:cask_url` to `:url`.

---

Library/Homebrew/test/rubocops/caveats_spec.rb
Library/Homebrew/test/rubocops/checksum_spec.rb
Library/Homebrew/test/rubocops/components_redundancy_spec.rb
Library/Homebrew/test/rubocops/conflicts_spec.rb
Library/Homebrew/test/rubocops/dependency_order_spec.rb
Library/Homebrew/test/rubocops/deprecate_disable_spec.rb

- [?] Have you written new tests for your changes? [That's an interesting idea—writing tests for our tests]
-----
While reviewing #10118, I noticed that a lot of `context` and `it` descriptions in `test/rubocops` are somewhat incoherent
For example:
```rb
context "uses_from_macos" do
it "wrong conditional uses_from_macos order" do
```
```
Failures:
1) RuboCop::Cop::FormulaAudit::DependencyOrder uses_from_macos wrong conditional uses_from_macos order
```
This PR improves the test descriptions for the following specs:
- `test/rubocops/caveats_spec.rb`
- `test/rubocops/checksum_spec.rb`
- `test/rubocops/components_redundancy_spec.rb`
- `test/rubocops/conflicts_spec.rb`
- `test/rubocops/dependency_order_spec.rb`
- `test/rubocops/deprecate_disable_spec.rb`
Now the previous example looks like …

test/rubocops: improve test descriptions

---

completions/fish/brew.fish

-----
The `desc_cache.json` in code is from 2 years ago, but Homebrew's description cache is now `descriptions.json`.
It seems most parts of the Fish completions are very old, I'm willing to improve it a little bit, this is the first fix.

Fix description cache path in Fish completion

---

Library/Homebrew/extend/os/linux/formula.rb
Library/Homebrew/formula.rb
Library/Homebrew/test/os/linux/formula_spec.rb
Library/Homebrew/test/os/mac/formula_spec.rb

-----
`ipopt` and `libgsm` use `Formula#shared_library` to locate shared libraries:
```rb
lib.install_symlink Dir["#{libexec}/lib/#{shared_library("*")}"]
```
However, this only matches unversioned `*.so` files such as `libpord.so` but ignores versioned `*.so.*` files like `libpord.so.0`. This PR modifies `shared_library` so that it matches both.
Related:
- https://github.com/Homebrew/homebrew-core/pull/67553
- https://github.com/Homebrew/homebrew-core/search?q=shared_library
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/ipopt.rb#L54-L58
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/libgsm.rb#L48

formula: include versioned `*.so.*` libs for `shared_library("*")`

---

Library/Homebrew/cmd/list.rb
docs/Manpage.md
manpages/brew.1

-----
- It doesn't work on the `HOMEBREW_CELLAR` dir for some reason, and using `du -sh` instead (https://github.com/Homebrew/brew/pull/10131) was an extra call that we don't need.
- (I had to edit the man page manually as `brew man` gives me "Broken pipe" errors.)

cmd/list: Remove help text about `-l` displaying file sizes

---

Library/Homebrew/test/dev-cmd/bottle_spec.rb

-----
This PR reduces some code duplication in `test/dev-cmd/bottle_spec.rb`, making the tests a bit easier to read.

bottle_spec: reduce code duplication in tests

---

Library/Homebrew/extend/os/mac/hardware.rb

Partial revert of https://github.com/Homebrew/brew/pull/10092
Because newly generated bottles for Big Sur include AVX instructions, which are not allowed under Rosetta 2 https://github.com/Homebrew/homebrew-core/issues/67713

Partial revert of #10092

---

Library/Homebrew/test/dev-cmd/bottle_spec.rb
Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb

-----
(This is kind of like a part 2 of https://github.com/Homebrew/brew/pull/10140; I opened this PR separately to keep the git diff readable)
- Replaced `testball-1.0.*.bottle.json` with `#{TEST_TMPDIR}/testball-1.0.*.bottle.json` so as to not create test files in the current directory
- `stub_hash` cleanup (see section below)
- Heredoc argument cleanup (see section below)
- `.to output(...).to_stdout` - only put `<<~EOS` inside the parentheses
- `setup_test_formula` - changed the `bottle_block` parameter to a named parameter
Before:
```rb
JSON.parse(
stub_hash(
{
"name":           "hello",
"version":        "1.0",
"path":           "/home/hello.rb",
"cellar":         "any_skip_relocation",
"os":             "big_sur",
"filename":       "hello-1.0.big_sur.bottle.tar.gz", …
```

bottle_spec: more cleanup

---

Library/Homebrew/cli/args.rb
Library/Homebrew/formula_installer.rb

There's not enough bottles on Homebrew on Linux to justify this behaviour currently.
Extract `cli/args: --HEAD implies building from source` from https://github.com/Homebrew/brew/pull/10155 (thanks @Rylan12).
Closes https://github.com/Homebrew/brew/pull/10155

formula_installer: only require --build-from-source on macOS.

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb

-----
This PR adds the `--ignore-closed-prs` switch that allows a bump PR to be opened regardless of whether or not the same PR has already been opened before. See https://github.com/Homebrew/homebrew-cask/issues/93014
> the version numbers of casks change a lot, not only up, sometimes down and up again too. there are examples each day. also some contributors close perfectly fine PRs. this means the same PR cannot be sent again although it needs to be sent. i have a system that downloads each cask with a static download URL every 4 hours and the PRs it generates are guaranteed to be 100% accurate. however they often fail to send because of limitations in 'brew bump-cask-pr'. 
Resolves #9466

bump-cask-pr: ignore closed duplicate PRs

---

Library/Homebrew/cmd/search.rb
Library/Homebrew/utils/github.rb
docs/Manpage.md
manpages/brew.1

-----
add two options to `cmd/search` for whether pull requests you search are open or closed`.

search: add two options

---

Library/Homebrew/cli/args.rb
Library/Homebrew/cli/named_args.rb
Library/Homebrew/cmd/fetch.rb
Library/Homebrew/cmd/home.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/uninstall.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/cat.rb
Library/Homebrew/dev-cmd/edit.rb
Library/Homebrew/dev-cmd/style.rb

-----
refactor how to assign `only` whether `:formula` or `:cask` in commands like `cmd/fetch.rb`.

add function to define path

---

Library/Homebrew/mktemp.rb

This is a workaround for some build tools that have trouble building if the current path contains a `@`
This was originally proposed https://github.com/Homebrew/brew/pull/9007 in the context of versioned gcc formulas, but I fixed the bug upstream and we decided we didn't want to change it in brew.
Now it appears that this is also an issue with ninja (https://github.com/ninja-build/ninja/issues/1606) and it doesn't look like they're actively working on it. (They use the `@` character for another special meaning). This is currently blocking the build of `qt@5`: https://github.com/Homebrew/homebrew-core/pull/67536
Given that… I suggest we include this workaround in brew. Other that the slight effect of surprise, I don't really see a downside.

mktemp: avoid directories with @

---

Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/test/livecheck/strategy/page_match_spec.rb

-----
This is a follow-up to #10113, which made modifications to `PageMatch` to support working with cached content, as a way of being able to modify the `Xorg` strategy to use `PageMatch` internally (like other strategies). With those changes, `PageMatch` properly works with page content that's passed to `#find_versions`.
However, the issue is that `Xorg` isn't actually able to cache page content in the current state because `PageMatch` isn't passing fetched content back to it in its return hash (`match_data`). Before #10113, I had been deleting the `:content` from `match_data` (as it wasn't necessary to keep it in the hash) and I simply forgot to modify that line when modifying `PageMatch#find_versions` to support cached content.
In general, this PR makes the following changes:
* Modify …

PageMatch: Return fetched content in match_data

---

Library/Homebrew/livecheck/strategy/apache.rb
Library/Homebrew/livecheck/strategy/bitbucket.rb
Library/Homebrew/livecheck/strategy/cpan.rb
Library/Homebrew/livecheck/strategy/git.rb
Library/Homebrew/livecheck/strategy/github_latest.rb
Library/Homebrew/livecheck/strategy/gnome.rb
Library/Homebrew/livecheck/strategy/gnu.rb
Library/Homebrew/livecheck/strategy/hackage.rb
Library/Homebrew/livecheck/strategy/header_match.rb
Library/Homebrew/livecheck/strategy/launchpad.rb
Library/Homebrew/livecheck/strategy/npm.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/livecheck/strategy/pypi.rb
Library/Homebrew/livecheck/strategy/sourceforge.rb
Library/Homebrew/livecheck/strategy/xorg.rb

-----
We recently added support for a `strategy` block in `livecheck` blocks as part of expanding support for casks. Originally, this support was only added to `HeaderMatch`, `Sparkle` and `PageMatch`.
This builds on that work by adding support for `strategy` blocks to the strategies that use `PageMatch#find_versions` internally (i.e., `Apache`, `Bitbucket`, `Cpan`, `GithubLatest`, `Gnome`, `Gnu`, `Hackage`, `Npm`, `Pypi`, and `Sourceforge`). I will be updating this PR to update `Xorg` in the same fashion after #10113 is merged.
Besides those strategies, this also adds support to the `Git` strategy. I've borrowed some related code from `PageMatch#page_matches` and adapted it to the context of `Git#find_versions`. There may be room for improvement in how this is handled but this is a …

Livecheck: Extend strategy block support

---

Library/Homebrew/cmd/install.rb

We don't allow this on upgrade or reinstall so let's make `StdEnv` essentially a private, internal API.
Don't merge this until the next release will be Homebrew 2.8.0.

cmd/install: add comment to deprecate --env.

---

Library/Homebrew/cask/artifact/abstract_uninstall.rb

-----
Handle IDs like `application.com.microsoft.autoupdate2.12890014632`. https://github.com/Homebrew/homebrew-cask/pull/96872 is currently failing with 
```
Some applications are still running, add them to uninstall quit:
application.com.microsoft.autoupdate2.12890016304
```

Handle running apps in `application.<bundle_id>.<number>.<number>` format.

---

Library/Homebrew/cli/parser.rb
Library/Homebrew/test/cli/parser_spec.rb
completions/bash/brew
completions/zsh/_brew_cask
docs/Manpage.md
manpages/brew.1

-----
Rename the default cask args to use `-` instead of `_` for consistency throughout Homebrew. This will remove the need for #10139. My understanding is that the argument parser we use treats `-` and `_` the same for all arguments, so passing `--input-methoddir` is already treated the same as `--input_methoddir` (and vice versa). Consequently, I don't believe that this really changes functionality at all. Already, a user could use the `-` args if they choose. The only difference is in the documentation and wherever argument names are printed.
CC @MikeMcQuaid and @Homebrew/cask

cli/parser: use - instead of _ in cask args

---

docs/Deprecating-Disabling-and-Removing-Formulae.md
docs/Formula-Cookbook.md
docs/README.md

-----
We don't have any official documentation about deprecating, disabling, and removing formulae. I've tried to document my thought process (which I think mirrors several that of several other maintainers). This is prompted by https://github.com/Homebrew/homebrew-core/issues/66360 where @bayandin and @SMillerDev shared their thoughts. My thoughts aligned with theirs, so this PR is a conglomeration of our ideas.
I'd like to get feedback from other @Homebrew/core maintainers to make sure that everyone is on the same page about what's in the documentation. If I've written something that not everyone agrees with, we should come to a consensus to clarify expectations for all maintainers (and users).

docs: add deprecate/disable/removal documentation

---

Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/sdk.rb

- Looking into this, but it seems to already be tested elsewhere.
-----
The changes here rely on https://github.com/Homebrew/brew/pull/10129. Merge that PR before this one. (Tests will pass when that is done.)
This PR:
1. Removes `sdk_version`, as it is no longer in use (cf. https://github.com/Homebrew/brew/pull/10129#discussion_r548848473)
2. Combines the logic in https://github.com/Homebrew/brew/blob/da0d7eff9b19368735c569f5dafd8490fdd4a4c2/Library/Homebrew/os/mac/sdk.rb#L64 and https://github.com/Homebrew/brew/blob/da0d7eff9b19368735c569f5dafd8490fdd4a4c2/Library/Homebrew/os/mac/sdk.rb#L96-L101 using the behaviour of `OS::Mac.version` in Big Sur.
Since `OS::Mac.version` returns only the major version in Big Sur, we use that to populate the `sdk_paths` hash with the key-value pair …

os/{mac,mac/sdk}: refactor out sdk_version

---

.github/workflows/triage.yml

-----
I've noticed that this workflow sometimes runs on PRs when the `outdated` label is applied by the `triage-issues` workflow. See https://github.com/Homebrew/brew/pull/9300, https://github.com/Homebrew/brew/pull/9310, and https://github.com/Homebrew/brew/pull/9313 for examples.
I think that this PR will solve the issue by simply ending the run if the `outdated` label is applied.

workflows/triage: fix handling outdated PRs

---

Library/Homebrew/formula_creator.rb

-----
This fixes a style error in formulae that are generated by `brew create`
- `:PERL5LIB => ENV["PERL5LIB"]` &rarr; `PERL5LIB: ENV["PERL5LIB"]`
- `:GEM_HOME => ENV["GEM_HOME"]` &rarr; `GEM_HOME: ENV["GEM_HOME"]`

formula_creator: update hash syntax

---

Library/Homebrew/cmd/update.sh

-----
I've noticed several people recently commenting that they were surprised at how long running the `git fetch --unshallow` command took (to the point where they thought it was not working). I ran a test locally and it took over 5 minutes for me to run.
This PR adds a line to the message letting users know that the command will take a while.

update: add notice that unshallowing takes time

---

Library/Homebrew/formula_installer.rb

- This returned a `java_spec` error and a `tap-new_spec` error. `brew tests` produces these errors even when run on the master branch.
-----
Closes #10180.
This PR changes the error message when you try to install `python@3.9` and you have no CLT installed to:
```
❯ HOMEBREW_NO_AUTO_UPDATE=1 brew install python@3.9
Error: python@3.9: unable to pour bottle!
The bottle needs the Apple Command Line Tools to be installed.
You can install them, if desired, with:
xcode-select --install
You can try to install from source with e.g.
brew install --build-from-source python@3.9
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any …
```

formula_installer: improve no-bottle error message

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/dev-cmd/release-notes.rb
docs/Manpage.md
manpages/brew.1

-----
We've received some blowback due to the short turn around time between Homebrew 2.6.0 and 2.7.0. 2.7.0 was the release that disabled `brew cask` commands, so 20 days didn't seem to be quite long enough for the entire community to adapt (namely, some ansible modules weren't updated in time which is causing breakage).
My personal opinion is that 20 days was a tad short for such a major change, but that's irrelevant to this PR (to be clear, not trying to blame any one person for this, it's simply a product of the way we do releases). Regardless of that, I think there are a few places where we could do some work to increase visibility for these releases.
This PR attempts to increase visibility in two ways:
1. Add a link to the Homebrew Blog to the release notes. It's easy for a user to …

Add more links to the changelog and blog

---

Library/Homebrew/cleanup.rb

This speeds up `--prune` fairly considerably.
Before:
```console
$ hyperfine --warmup 3 'brew cleanup --prune=365'
Benchmark #1: brew cleanup --prune=365
Time (mean ± σ):     33.352 s ±  0.654 s    [User: 21.684 s, System: 6.458 s]
Range (min … max):   31.901 s … 34.096 s    10 runs
```
After:
```console
$ hyperfine --warmup 3 'brew cleanup --prune=365'
Benchmark #1: brew cleanup --prune=365
Time (mean ± σ):      6.821 s ±  0.186 s    [User: 2.225 s, System: 3.926 s]
Range (min … max):    6.578 s …  7.178 s    10 runs
```
Closes https://github.com/Homebrew/brew/pull/10177
Fixes https://github.com/Homebrew/brew/issues/10172

cleanup: don't do stale check when passing --prune.

---

Library/Homebrew/diagnostic.rb

-----
`brew doctor` will soon start to fail on `ubuntu-latest` actions runs once they migrate to Ubuntu 20.04. This has already happened to me in personal taps.
The issue is that Ubuntu 20.04 [no longer comes with Python 2](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md). Instead, the `python` executable points to Python 3.8.5.
I think there are three options:
1. Use `ubuntu-18.04` instead of `ubuntu-latest` on all our runners. This isn't a good long-term solution
1. Conditionally allow this doctor failure on CI machines to allow them to continue running
1. Disable this check (everywhere or only on Linux) (suggested to me on Slack by @sjackman)
I don't know much about Homebrew on Linux, but I think that option 3 is the best option (mainly …

doctor: disable python symlink message

---

Library/Homebrew/dev-cmd/man.rb
docs/Maintainer-Guidelines.md
docs/Manpage.md
manpages/brew.1

-----
This PR makes two documentation changes:
1. Cleanup the text around the cask options in the manpage/documentation. `brew cask` is now disabled so these options don't apply to its subcommands. Additionally, the cask options are only used in the `install`, `reinstall`, and `upgrade` commands rather than all commands that accept `--cask`.
1. Clarifies the Maintainer Guidelines by adding a chart explaining when to use squash & merge versus rebase & merge.

Documentation updates

---

Library/Homebrew/cmd/update-report.rb
manpages/brew.1

-----
fix `cmd/update-report` to show new correct tag. When I executed `brew update`,  `new_tag` was `backup/remove-popen-read-20-00-21`,  but I expected it was `2.7.1`.
<details><summary>git -C /usr/local/Homebrew tag --list --sort=-version:refname "*.*"</summary><div>
```bash
$ git -C /usr/local/Homebrew tag --list --sort=-version:refname "*.*"
2.7.1
2.7.0
2.6.2
2.6.1
2.6.0
2.5.12
--< omit >--
```
</div></details>
<details><summary>git -C /usr/local/Homebrew tag --list --sort=-version:refname</summary><div>
```bash
$ git -C /usr/local/Homebrew tag --list --sort=-version:refname
backup/remove-popen-read-20-00-21
backup/remove-popen-read-19-56-50
backup/gpg-verification-01-53-16
backup/days-19-30-23
backup/days-03-02-59
backup/days-03-02-52
backup/create-cache-00-29-47 …
```

cmd/update-report: fix to show new tag

---

Library/Homebrew/utils/curl.rb

-----
Since `curl_check_http_content` was fixed, when auditing the `mactex` cask, it will first try to download a ~4GB file since it comes from a `http://` URL. Only then will it check the `https://` URL.
The audit currently fails since the download exceeds the 600 seconds timeout of the audit.
This fixes the function to first check if the `https://` URL is reachable and only then download the `http://` URL as well. Otherwise, only the reachability of the `http://` URL is checked.

Avoid unnecessary downloads in `audit`.

---

Library/Homebrew/missing_formula.rb

When an installed formula is missing and its source has migrated
to a new tap, Homebrew warns the user about this, saying:
You can access it again by running:
brew tap new-name
And then you can install it by running:
brew cask install new-name
Unfortunately, the "brew cask install" incantation is deprecated
and the advice won't work:
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
This alters the advice to use the new "brew install --cask" notation,
fixing the advice presented to the user.
<hr>

missing_formula: fix cask installation advice on tap migration

---

docs/Formula-Cookbook.md

Correct Messaging section:
There is a missing ? in the example code:
Currently:
```
if build.with?("qt") && build.with("qt5")
odie "Options --with-qt and --with-qt5 are mutually exclusive."
end
```
There should be a ? in the second build.with:
`build.with?("qt5")
`
- [+] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [+] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [+] Have you added an explanation of what your changes do and why you'd like us to include them?
- [N/A] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [N/A] Have you …

Correct Formula Cookbook (missing ?)

---

Library/Homebrew/dev-cmd/bottle.rb

-----
This extracts out some `brew bottle --merge --write` code that doesn't have to be in the `inreplace` block and hopefully makes the original intent clearer

bottle: add `old_checksums` helper function

---

.github/workflows/tests.yml
Library/Homebrew/style.rb
manpages/brew.1

-----
This is a test PR to help prepare for the `ubuntu-latest` runners becoming `ubuntu-20.04`. As seen in https://github.com/Homebrew/brew/pull/10184, there are likely going to be a few issues. I'm opening this to try to find those now so we don't have to deal with them when our runners are actually migrated.
This PR should not be merged in its current state. It's simply for testing purposes. My plan is to modify this PR until CI passes, then revert the workflow changes before merging.

style shellcheck fixes (in preparation for ubuntu-20.04)

---

Library/Homebrew/shims/super/cc

-----
This improves superenv's build handling on systems which have both an Intel and an Apple Silicon installation of Homebrew side-by-side.
Homebrew has a hardcoded list of paths to reject from build flags like `-I` and `-L`, set to various prefixes which are known to interfere with Homebrew builds (MacPorts, Boxen Homebrew, etc.). On Apple Silicon, we currently recommend two different prefixes: `/usr/local` for Intel, and `/opt/homebrew` for Apple Silicon. Users who have two Homebrew installations will see interference between them, specifically when building things using their `/opt/homebrew` installation. Many packages' buildsystems throw `-I/usr/local/include` and `-L/usr/local/lib` to the compiler willy-nilly, even if it's not strictly necessary, and this can end up instructing …

superenv: filter out /usr/local on ARM if necessary

---

Library/Homebrew/formula_installer.rb

- Failures: `Language::Java::java_home`, `Cask::Cmd::Upgrade`, `brew tap-new` 
-----
Follow up to #10183.
This improves the error message displayed when `formula.pour_bottle?` is
false.
<details><summary>Before</summary>
<p>
❯ brew install python@3.8
Error: python@3.8: no bottle available!
The bottle needs the Apple Command Line Tools to be installed.
You can install them, if desired, with:
xcode-select --install
You can try to install from source with e.g.
brew install --build-from-source python@3.8
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
</p>
</details> …

formula_installer: tweak bottle error message

---

Library/Homebrew/formula_auditor.rb

-----
New formulae in non-core taps should be allowed to specify `patch` blocks. See https://github.com/Homebrew/brew/issues/10216 for further discussion.
I briefly looked through the tests but could not find anything that currently tests this audit anyways, so I did not change anything related to tests.
Fixes #10216

formula_auditor: prohibit patches in new core formulae only

---

Library/Homebrew/utils/git.rb

Let's avoid printing this unless `--debug` (to avoid `brew bundle check -v` outputting this).
Fixes https://github.com/Homebrew/homebrew-bundle/issues/865

utils/git: quieter git --version.

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
My brain was having a hard time parsing some of these 😅

bump-formula-pr: use `nil?`/`blank?`/`present?` in if statements

---

Library/Homebrew/cask/cask.rbi
Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/livecheck.rbi

livecheck: enable Sorbet type checking

---

Library/Homebrew/cli/args.rbi
Library/Homebrew/cmd/fetch.rb
Library/Homebrew/dev-cmd/test.rb
Library/Homebrew/rubocops/lines.rb
Library/Homebrew/test/rubocops/lines_spec.rb
Library/Homebrew/test/rubocops/urls_spec.rb
Library/Homebrew/test/support/fixtures/receipt.json
Library/Homebrew/test/version_spec.rb
Library/Homebrew/version.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

-----
devel is not used anymore.

Delete references to devel

---

Library/Homebrew/rubocops/homepage.rb

rubocops/homepage: don't attempt to auto-correct an empty string.

---

.github/workflows/sorbet.yml
.github/workflows/tests.yml
.github/workflows/vendor-gems.yml

macos-11.0 capacity is too low for us at the moment.

github/workflows: use macos-latest.

---

Library/Homebrew/livecheck/livecheck.rb

---
Fixes
```
URL:              https://central.github.com/deployments/desktop/desktop/latest/darwin
URL (processed):  https://central.github.com/deployments/desktop.git
```

Don't preprocess URL for `:header_match` strategy.

---

Library/Homebrew/cask/auditor.rb
Library/Homebrew/cask/cmd/audit.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/test/cask/cmd/audit_spec.rb

The current casks audit is very noisy in the no-op case (i.e. no errors):
https://github.com/Homebrew/brew/pull/10234/checks?check_run_id=1655630568#step:15:7
This means when there are errors and you're querying all casks it's pretty hard to quickly identify the problems.
This commit silences the `passing`, `warning` and header/summary output when you're querying all casks (rather than a specific cask or tap).
This is more consistent with `brew audit` for formulae which is silent unless there are audit failures.

audit: quieten down and make casks audit consistent with formulae.

---

Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/upgrade.rb
docs/Manpage.md
manpages/brew.1

-----
This was [decided in August](https://github.com/Homebrew/homebrew-cask/issues/88401) but recently we had another issue because of it. Understandably, some people will expect `--force` to mean “trample everything”, so we should document when that isn’t the case.

Docs: non-cask binaries are not overwritten by --force

---

Library/Homebrew/utils/github.rb

-----
A homebrew-cask user attempted to submit a bump PR but got this error because their personal access token did not have the `public_repo` scope:
```
Error: Unable to fork: Not Found!
```
This PR changes `utils/github` to check token scopes even if the token is authorized, which results in this more helpful error message:
```
Error: Your macOS keychain GitHub credentials do not have sufficient scope!
Scopes required: public_repo
Scopes present:  none
Create a personal access token:
https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.zshrc
Error: Unable to fork: Not Found!
```
The authorization check was added in https://github.com/Homebrew/brew/commit/6135da800e4f93ded3a5a331d0efa691f4822afb …

github: check token scopes even if authorized

---

Library/Homebrew/cask/dsl.rb
Library/Homebrew/checksum.rb
Library/Homebrew/cleanup.rb
Library/Homebrew/cmd/fetch.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/extend/pathname.rb
Library/Homebrew/formula.rb
Library/Homebrew/resource.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/cask/download_spec.rb
Library/Homebrew/test/checksum_spec.rb
Library/Homebrew/test/resource_spec.rb
Library/Homebrew/test/software_spec_spec.rb

We use only one sha type right now.
Needed for https://github.com/Homebrew/brew/pull/10186
-----

checksum: simplify, use only sha256

---

Library/Homebrew/brew.sh
Library/Homebrew/extend/os/mac/utils/analytics.rb
Library/Homebrew/os/mac.rb
Library/Homebrew/test/utils/analytics_spec.rb
Library/Homebrew/utils/analytics.rb

- Use default `custom-prefix` label on macOS ARM (as `/usr/local` is not the default there).
- Add architecture (or Rosetta) to analytics event label.
- Don't send minor versions on Big Sur.
- Remove defunct `HOMEBREW_OSX_VERSION` reference.

Improve submitted analytics data

---

.gitignore
.vscode/extensions.json
.vscode/settings.json
Library/Homebrew/dev-cmd/rubocop.sh
Library/Homebrew/shims/gems/rubocop
completions/internal_commands_list.txt
docs/Manpage.md
manpages/brew.1

Add a shim and a command that can be used to easily add a single directory to your `PATH` (`Library/Homebrew/shims/gems`) and have it automatically install, configure and run `rubocop` so you can use it for in-editor integrations.
CC @Rylan12 who talked about this with me. ideally we'd/you'd add a commit to this PR with the Visual Studio Code configuration to run this `rubocop`

rubocop: add shim and command.

---

docs/Python-for-Formula-Authors.md

-----
Replaces up to https://github.com/Homebrew/brew/pull/9391
This PR modifies the instructions for python resource generation using `homebrew-pypi-poet` so installing `virtualenvwrapper` or `virtualenv` isn't necessary.
Instead, we can use the builtin venv module via `python3 -m venv` to more easily and reliably find resources.
CC: @claui, @dtrodrigues, and @MikeMcQuaid

docs: update homebrew-pypi-poet instructions

---

Library/Homebrew/language/python.rb
Library/Homebrew/test/language/python_spec.rb

-----
This PR uses python's built-in `venv` to install formulae instead of the external `virtualenv`, which has dependencies and needs to be bootstrapped. The dependencies could also theoretically differ based on Python version.
Current caveat: `venv` uses `ensurepip` to install `pip` and `setuptools` using the wheels that are bundled with cpython, even if a newer one is installed, which is 20.2.3 for pip and 49.2.1 for setuptools in Python 3.9.1: https://github.com/python/cpython/blob/1e5d33e9b9b8631b36f061103a30208b206fd03a/Lib/ensurepip/__init__.py#L16-L18, https://github.com/python/cpython/tree/1e5d33e9b9b8631b36f061103a30208b206fd03a/Lib/ensurepip/_bundled
Other downstream package managers patch `ensurepip` to point to their locally managed `pip` and `setuptools`: …

python: use built-in venv instead of virtualenv when installing formulae

---

Library/Homebrew/utils/ast.rb

-----
Allows single class files with side-effects that load other classes that inherit `Formula`.
My [tap](https://github.com/kabel/homebrew-pecl) uses a `Formula` [subclass](https://github.com/kabel/homebrew-pecl/blob/main/lib/php_pecl_formula.rb) to reduce copy/paste. The `brew bottle --merge` command is failing for my bottles because the AST cannot find the class. This relaxes the constraint that a file that has a begin node (for loading my subclass) can only have a class that directly extends `Formula`. Now if the file starts with a begin node, the formula is either the only (first) class or the first that directly extends `Formula`.

utils/ast: Loose the check for Formula class node

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/utils/github.rb

-----
Related: https://github.com/Homebrew/brew/issues/9269
This PR changes the `bump-formula-pr`/`bump-cask-pr` commands to check duplicate PRs for the exact formula/cask being bumped (i.e. check if `Formula/<formula>.rb` is modified). For example, this would prevent `ansible: migrate to python@3.9` from preventing `python@3.9` bumps.

bump-*-pr: check existing PRs for exact file match

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/bump-revision.rb
Library/Homebrew/test/utils/ast_spec.rb
Library/Homebrew/utils/ast.rb
Library/Homebrew/utils/ast.rbi

-----
This PR adds the class `Utils::AST::FormulaAST`, which stores the intermediate `processed_source` and `tree_rewriter` variables that are used in editing formulae. This will make it more efficient to replace and/or add multiple stanzas such as in `brew bump-formula-pr`
Note: I plan to extract out the `self.` functions in `Utils::AST::FormulaAST` as module functions in `Utils::AST` in a future PR

utils/ast: add `FormulaAST` class

---

Library/Homebrew/livecheck/strategy/sparkle.rb

-----
Apparently Sparkle appcasts can contain releases for other platforms,  we only use this strategy for casks as far as I'm aware of, so exclude other platforms if the `os` attribute is specified.
Fixes CI failure in https://github.com/Homebrew/homebrew-cask/pull/97558.

Only select Sparkle items for macOS.

---

Library/Homebrew/livecheck.rb
Library/Homebrew/livecheck/strategy/sourceforge.rb
docs/Brew-Livecheck.md
docs/Formula-Cookbook.md
docs/README.md

-----
This is preliminary documentation for the `brew livecheck` command. At the moment, it's primarily geared toward explaining `livecheck` blocks and livecheck's strategies. I'm hoping to expand this in the near future to explain more about livecheck in general, as I feel the current documentation still assumes that the user has some existing knowledge of livecheck.
Any feedback is appreciated but here are some specific areas that I'm curious to hear about:
* Is it fine to refer to this command as "livecheck" or should it be capitalized as "Livecheck"?
* Does this make enough sense to maintainers who haven't used livecheck before? [Keep in mind the limitations of this preliminary document and the plans to expand it in the future.]
* Is this information sufficient for maintainers to be …

docs: add brew livecheck documentation

---

Library/Homebrew/cask/cmd/upgrade.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/messages.rb

-----
Hotfix for https://github.com/Homebrew/brew/issues/10290
This PR changes `upgrade_outdated_formulae` and `upgrade_outdated_casks` to return booleans, so that we can determine if and when to display formula messages (such as caveats)

upgrade: show formula caveats after casks have been updated

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/test/utils/ast/ast_spec.rb
Library/Homebrew/test/utils/ast/formula_ast_spec.rb
Library/Homebrew/utils/ast.rb

-----
Follow-up to #10279
This PR moves some general helper functions from `Utils::AST::FormulaAST` to `Utils::AST` and also splits `ast_spec.rb` into `ast/ast_spec.rb` and `ast/formula_ast_spec.rb`

utils/ast: move helper functions from `FormulaAST` to `AST`

---

Library/.rubocop.yml
Library/Homebrew/.rubocop.yml
Library/Homebrew/cask/cask.rb
Library/Homebrew/cask/config.rb
Library/Homebrew/cli/args.rbi
Library/Homebrew/lazy_object.rb

-----
Ignore and remove invalid keys when loading an existing config from a path. Also add type signatures.
Fixes https://github.com/Homebrew/homebrew-cask/issues/97992.

Ignore invalid keys when reading existing `Cask::Config`.

---

Library/Homebrew/extend/git_repository.rb
Library/Homebrew/test/utils/popen_spec.rb
Library/Homebrew/utils/git_repository.rb
Library/Homebrew/utils/popen.rb

-----
Follow-up to https://github.com/Homebrew/brew/pull/10245
This PR adds a `safe` argument to `popen_read` and `popen_write` that can then be used in `Utils.git_head`
The reason for adding this is that formulae use `safe_popen_read` to get the git head, while `Utils.git_head` currently uses `popen_read`. Since `Utils.git_head` should primarily be used by formulae, this PR adds a `safe` argument to `git_head` that has a default value of `true` (whereas the default value is `false` for `popen_read`)
I also added tests for `safe_popen_read` and `safe_popen_write` which passed with the original methods as seen in the test runs for commit 40d85ec: https://github.com/Homebrew/brew/runs/1689977863

utils/popen: add `safe` argument to `popen_read` and `popen_write`

---

Library/Homebrew/keg.rb

-----
This is weird. We're seeing some installs where formulae have no opt prefix and no linked keg record, *but* still ended up linked into the prefix. Upgrades will blow up in this case because the old symlinks won't get deleted and Homebrew will report a nonsensical error message about not being able to link over another link from the same formula!
Since the optpath is either missing or pointing to the wrong destination at this point, the checks for conflict linking above will have failed. We should instead be safe to simply blow away these conflicting symlinks and replace them with the new targets.
Sample error:
<details>
<pre>
==> Upgrading 1 outdated package:
x264 r3027_1
==> Upgrading x264 -> r3027_1
==> Downloading https://homebrew.bintray.com/bottles/x264-r3027_1.catalina.bottle.t …

Keg: allow overwriting same-formula conflicts

---

Library/Homebrew/test/utils/git_repository_spec.rb
Library/Homebrew/utils/git_repository.rb

-----
This will allow formulae to do `Utils.git_head` instead of `Utils.git_head(buildpath)`
This is useful for `cd` blocks such as:
```rb
cd "resource-cloned-from-git" do
resource_commit = Utils.git_head
end
```

utils/git_repository: use `Pathname.pwd` if no `repo` specified

---

Library/Homebrew/rubocops/components_order.rb
Library/Homebrew/test/rubocops/components_order_spec.rb

In support of https://github.com/Homebrew/homebrew-core/pull/68946. This rubocop needs a bit of a refactor but this is a quick fix to ensure that we can get openjdk working on ARM.
-----

rubocops: permit `mirror` in OS-specific resources

---

Library/Homebrew/dev-cmd/tap-new.rb

Otherwise this prints to `stderr` to ask for configuration of the branch name:
https://github.com/Homebrew/brew/pull/10323/checks?check_run_id=1701105141#step:5:51

dev-cmd/tap-new: fix output on newer versions of Git.

---

Library/Homebrew/keg.rb
Library/Homebrew/tab.rb

Previously, `brew upgrade gcc@10` could get overzealous and remove the `LinkedKeg` record for `gcc@9`. This is bad because we then think `gcc@9` is unlinked when it is not and it causes a tonne of conflicts when trying to link `gcc@9` again.
Instead, fix up the alias and versioned alias cleanup to be more precise and only delete the symlinks that point to the current `rack`,`opt_record` or `linked_keg_record` and unify the logic so it's performed consistently.
- don't `remove_old_aliases` every time we try to unlink a directory but just perform it once per `unlink` operation
- remove the linked keg record on `uninstall`
Fixes https://github.com/Homebrew/homebrew-core/issues/68866
Replaces https://github.com/Homebrew/brew/pull/10312

Keg: fix alias and versioned symlink handling.

---

docs/Homebrew-Governance.md

-----
1. Definitions
- Define `ordinary resolution` and `special resolution`.
3. General Meetings of Members
- Members may call a general meeting
4. Project Leadership Committee
- A member of the PLC may be removed
6. Project Leader
- Decisions of the Project Leader may be overruled
- The Project Leader may be removed
7. Technical Steering Committee
- Remove the long-term roadmap
- PLC members should not be appointed to the TSC
- A member of the TSC may be removed
-----
An extraordinary general meeting of the membership will be held on Thu 2021-Jan-14 20:00 UTC on Slack. The purpose of this meeting is to vote on a special resoultion to amend the governance document as per this PR. It is not necessary to attend this meeting in person. You may vote by proxy at any time in advance of this …

Amend the governance document

---

Library/Homebrew/patch.rb
Library/Homebrew/software_spec.rb

`SoftwareSpec#add_legacy_patches` and `Patch#normalize_legacy_patches` were added almost 6 years ago; let's delete them
See commit 665b14c4a44c272b46b8559836e9fdbeee5d8a46
```console
$ grep -r 'normalize_legacy_patches' Library/Homebrew
./software_spec.rb:    list = Patch.normalize_legacy_patches(list)
./patch.rb:  def self.normalize_legacy_patches(list)
```
```console
$ grep -r 'add_legacy_patches' Library/Homebrew
./software_spec.rb:  def add_legacy_patches(list)
```
-----

patch: delete legacy code

---

Library/Homebrew/keg.rb

Otherwise this can be a broken symlink which will raise an exception:
https://github.com/Homebrew/homebrew-core/runs/1704569542?check_suite_focus=true#step:6:47

keg: check that alias_match_path exists before checking the `.realpath.

---

Library/Homebrew/rubocops/components_order.rb
Library/Homebrew/test/rubocops/components_order_spec.rb

-----
Follow-up to #10320
> Refactor this to point to the actual offending methods rather than the entire block.
Also, this PR fixes the error message in that `url` and `sha256` are the minimum requirement, not `url` and `mirror`

rubocops: point to offending OS-specific block in resource blocks

---

Library/Homebrew/livecheck.rb
Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/test/formula_spec.rb
Library/Homebrew/test/livecheck/livecheck_spec.rb
Library/Homebrew/test/livecheck_spec.rb

-----
An issue that we've encountered in at least one homebrew/core formula is that `url :head` won't work in a `livecheck` block if the formula uses a `head` block. The `livecheck` block comes before the `head` block, so the `head` URL isn't defined when the `livecheck` block `#url` method is called.
In #10157, I proposed that we could resolve this issue by moving `head` blocks after `stable` blocks in formulae, so they both come before the `livecheck` block. Some Homebrew members supported this while others preferred to simply move the `livecheck` block after the `head` block. Both of these options would lead to some level of unhappiness in the end.
While discussing these options, @SeekingMeaning asked if we could modify `Livecheck#url` to simply store the symbol from the `livecheck` …

Livecheck#url: Don't convert URL symbol to string

---

Library/Homebrew/test/rubocops/text_spec.rb

-----
Continuation of https://github.com/Homebrew/brew/pull/10124
This PR improves the test descriptions of `text_spec.rb` so that the error messages are more coherent.
Before:
``RuboCop::Cop::FormulaAudit::Text When auditing formula text with `require "formula"` is present``
After:
``RuboCop::Cop::FormulaAudit::Text when auditing formula text reports an offense if `require "formula"` is present``
(I'm not sure if my extensive use of single quotes [`'`] and percent literals [`%Q(...)`] is recommended; please tell me if it isn't)

rubocops/text: improve test descriptions

---

Library/Homebrew/test/rubocops/components_order_spec.rb
Library/Homebrew/test/rubocops/files_spec.rb
Library/Homebrew/test/rubocops/homepage_spec.rb
Library/Homebrew/test/rubocops/lines_spec.rb
Library/Homebrew/test/rubocops/options_spec.rb
Library/Homebrew/test/rubocops/patches_spec.rb
Library/Homebrew/test/rubocops/urls_spec.rb
Library/Homebrew/test/rubocops/version_spec.rb

-----
Continuation of https://github.com/Homebrew/brew/pull/10124
This PR improves some test descriptions so that the error messages are more coherent
Before:
`RuboCop::Cop::FormulaAudit::ComponentsOrder no on_os_block does not fail when there is no on_os block`
After:
`RuboCop::Cop::FormulaAudit::ComponentsOrder when formula has no OS-specific blocks reports no offenses`

rubocops/*: improve test descriptions

---

Library/Homebrew/cli/parser.rb
Library/Homebrew/cmd/options.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/commands.rb
Library/Homebrew/completions.rb
Library/Homebrew/completions/bash.erb
Library/Homebrew/dev-cmd/man.rb
Library/Homebrew/test/completions_spec.rb
completions/bash/brew
completions/internal_commands_list.txt

-----
See #10223
Even though this is a draft, I wouldn't mind some feedback on the general approach.
This PR will add functionality to automatically generate shell completion files every time a user runs `brew update`.
At the moment, this only works for bash and isn't very intelligent. This PR is mainly just to show my work in progress and get feedback along the way.
Here's my vision for this. The files we provide in `completions/` should be as minimal as possible. These source out to the user-specific configurations in `completions/user/`. These are automatically generated each time the user runs `brew update`. This has the benefit of automatically creating completions for all external commands (whether or official or not) without requiring the tap maintainers to provide them.
These …

Generate bash completions automatically

---

Library/Homebrew/rubocops/extend/formula.rb
Library/Homebrew/rubocops/shared/helper_functions.rb

-----
This PR moves methods in `FormulaCop` that aren't formula-specific to `HelperFunctions` so that more generic rubocops can use them also

rubocops: move some methods from FormulaCop to HelperFunctions

---

Library/Homebrew/extend/git_repository.rb
Library/Homebrew/test/utils/git_repository_spec.rb
Library/Homebrew/utils/git_repository.rb

-----
To imitate `safe_popen_read`, calling `git_head` with a `safe` parameter of `true` should raise an error if the directory is not a Git repository or Git is unavailable

git_repository: raise error instead of returning nil if `safe`

---

Library/Homebrew/dev-cmd/man.rb
docs/Manpage.md
manpages/brew.1

-----
- This was deprecated in ec75fbc in 2016! 🗝️ 🧓🏻 :dusty_stick:

dev-cmd/man: Completely remove `--link`

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/bintray.rb
Library/Homebrew/cask/artifact/relocated.rb
Library/Homebrew/cask/cmd/upgrade.rb
Library/Homebrew/cask/config.rb
Library/Homebrew/cask/url.rb
Library/Homebrew/cli/named_args.rb
Library/Homebrew/cli/parser.rb
Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
Library/Homebrew/extend/ENV.rb
Library/Homebrew/extend/ENV.rbi
Library/Homebrew/extend/ENV/shared.rb
Library/Homebrew/extend/ENV/std.rb
Library/Homebrew/extend/ENV/super.rb
Library/Homebrew/extend/pathname.rb
Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/skip_conditions.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/system_command.rb
Library/Homebrew/unpack_strategy/zip.rb
Library/Homebrew/utils/ast.rb
Library/Homebrew/utils/git_repository.rb
Library/Homebrew/utils/github/actions.rb
Library/Homebrew/utils/inreplace.rb
Library/Homebrew/utils/pypi.rb
Library/Homebrew/utils/string_inreplace_extension.rb

-----
I think this is more readable
(Should we have a vote of 👍 or 👎?)

rubocop: require braces for Sorbet `sig`

---

Library/Homebrew/utils/pypi.rb

-----
Some python formulae may require packages that are in the global exclude list to function. Allow them to be added if they're explicitly requested.

pypi: allow packages in global exclude list if explicitly requested

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/formula.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/formula_installer_bottle_spec.rb
Library/Homebrew/test/software_spec_spec.rb
Library/Homebrew/test/support/fixtures/testball_bottle_cellar.rb
Library/Homebrew/test/utils/bottles/collector_spec.rb
Library/Homebrew/utils/bottles.rb

First draft implementation, opening the PR to show what I have already tested. I will need your help, this change is tricky.
See #9315 for discussion.
- I know that some tests are broken and the implementation is not ironed out
- I did not work on the `brew bottle --merge --keep-old` part
- I know that we will need to split this PR in two parts:
- first the reading of the old and new syntax
- create a brew release
- add the writing part
Writing part (`brew bottle --merge`):
I did not modify the `bottle.json` file content. This means I need to shift the cellar information from one level to another in the bottle hash. In fact, each `bottle.json` file has it's own cellar information, but it is not stored at the right level. So I had to manually merge the bottle hash between the multiple …

bottle: tag specific cellars

---

docs/External-Commands.md

-----
Follow up to https://github.com/Homebrew/brew/pull/10288
This PR updates the documentation around external commands and how to use the new `named_args` method.
My ultimate goal is to have completions be automatically generated based on `named_args` and to have an e.g. `brew generate-completions` command that will generate completions automatically for a tap. Given this, let me know if it's better for this PR to wait until that's ready (in order to document both at the same time).

docs: update external command documentation

---

Library/Homebrew/os/linux/glibc.rb
Library/Homebrew/os/mac/version.rbi
Library/Homebrew/version.rb
Library/Homebrew/version.rbi
Library/Homebrew/version/null.rb

-----
Notable changes:
- Added a `NullVersion` singleton class that extends `Version`
- Changed `Version::Token` to be an abstract class
- Added `version.rbi` to work around Sorbet limitation with aliases
There are a lot of `T.untyped` but this is a start, at least

version: enable Sorbet type checking

---

Library/Homebrew/os/mac/version.rb

-----
This makes it more intuitive to retrieve captures since we can use symbols instead of numbered indexes

os/mac/version: use named captures in regex

---

docs/Formula-Cookbook.md

-----
The :x11 symbol was deprecated in https://github.com/Homebrew/brew/commit/87dd13aea6691e9d5e0f3ba8d1d1f862a809212a

Replace :x11 symbol as it is no longer available

---

Library/.rubocop.yml

-----
This enforces usage of `&&` and `||` always.

rubocop: disallow and/or in favor of &&/||

---

Library/Homebrew/completions.rb
Library/Homebrew/completions/bash.erb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/ruby.rb
completions/bash/brew
docs/Manpage.md
manpages/brew.1

-----
This is a follow-up to https://github.com/Homebrew/brew/pull/10229 which adds the ability to complete files where appropriate.
A few commands (`bottle`, `ruby`, `sh`, and `style`) accept files as named arguments. This PR will now enable automatic file completion for these commands. Note that this is only available in newer versions of `bash`, so I've added a conditional making the `__brew_complete_files` a no-op unless the `compopt` command exists. I've tested using builtin `/bin/bash` (no `compopt` command so no file completions) and Homebrew's `/usr/local/bin/bash` (with `compopt` and file completions).

completions: complete files where appropriate in bash

---

Library/Homebrew/livecheck/livecheck.rb

-----
Tested with https://github.com/Homebrew/homebrew-cask/pull/98130
Before:
```console
$ brew livecheck --cask adoptopenjdk
adoptopenjdk : 15.0.1,9.1 ==> 15,36
```
After:
```console
$ brew livecheck --cask adoptopenjdk
adoptopenjdk : 15.0.1,9.1 ==> 15.0.1,9
```

livecheck: compare actual version for casks

---

docs/Shell-Completion.md

This PR suggests an alternative method for enabling ZSH completions when a framework like `oh-my-zsh` already runs `compinit` without the need to run this directly.
The benefit of using this method is that only one line of code is needed, rather than 5 lines for the currently suggested method, reducing configuration maintenance for the user. I have not included an `if` block to check for existence of the `brew` command, as this line comes directly after the command to setup brew's environment.
---

Suggest alternative method for enabling ZSH completions

---

Library/Homebrew/test/utils/git_repository_spec.rb

-----
This PR creates a new shared example group in `git_repository_spec` named `git_repository helper function` that reduces duplication of tests. This will be especially useful for when additional helper functions are added to `utils/git_repository`

git_repository_spec: group together shared examples

---

docs/Formula-Cookbook.md

-----
Allow the note to show up when searching for info about `:optional` and `:recommended`.
This does not remove the duplicate note about `option`s further down the document.
Refs https://github.com/Homebrew/homebrew-core/issues/69128#issuecomment-762777490

Clarification on the use of `:optional` and `:recommended`

---

Library/Homebrew/dev-cmd/install-bundler-gems.rb
Library/Homebrew/dev-cmd/man.rb
Library/Homebrew/dev-cmd/typecheck.rb
docs/Manpage.md
manpages/brew.1

This is better than users getting a weird error.
Partially addresses https://github.com/Homebrew/brew/issues/10210

dev-cmd: disable when broken on Apple Silicon.

---

Library/Homebrew/cmd/shellenv.sh

- Language::Java::java_home returns valid JAVA_HOME if version is specified
- Language::Java::java_home returns valid JAVA_HOME if version is not specified
- brew livecheck gives an error when no arguments are given and there's no watchlist
-----
`brew shellenv` is currently broken on fish, where it outputs the default syntax for bash/zsh, which includes constructs like `${PATH+:$PATH}` that fish doesn't support.
```
> status fish-path
/usr/local/bin/fish
> eval (brew shellenv)
fish: ${ is not a valid variable in fish.
```
~~The first problem this PR fixes is that the call to `ps` on [line 9 of `shellenv.sh`][L9] ends up using an empty variable.~~
[L9]: https://github.com/Homebrew/brew/blob/8869208/Library/Homebrew/cmd/shellenv.sh#L9
The ~~second~~ problem (potentially also affecting csh …

fix `brew shellenv` on fish

---

.gitignore
Library/.rubocop.yml
Library/Homebrew/Gemfile
Library/Homebrew/bootsnap.rb
Library/Homebrew/global.rb
Library/Homebrew/load_path.rb

> Bootsnap is a library that plugs into Ruby, with optional support for ActiveSupport and YAML, to optimize and cache expensive computations.
https://github.com/Shopify/bootsnap
For our case that translates to "repeated calls to `brew` have
reductions in the time spend `require`ing speeding up the process
boot time".
For example:
```console
$ hyperfine --warmup=2 "unset HOMEBREW_BOOTSNAP; brew info wget" "export HOMEBREW_BOOTSNAP=1; brew info wget"
Benchmark #1: unset HOMEBREW_BOOTSNAP; brew info wget
Time (mean ± σ):      2.417 s ±  0.032 s    [User: 659.0 ms, System: 855.5 ms]
Range (min … max):    2.382 s …  2.464 s    10 runs
Benchmark #2: export HOMEBREW_BOOTSNAP=1; brew info wget
Time (mean ± σ):      1.862 s ±  0.064 s    [User: 425.3 ms, System: 566.8 ms]
Range (min … max): …
```

Add HOMEBREW_BOOTSNAP to optionally use Bootsnap

---

Library/Homebrew/brew.rb
Library/Homebrew/cli/named_args.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/untap.rb
Library/Homebrew/extend/os/mac/tap.rb
Library/Homebrew/tap.rb

-----
Fixes #10303
This PR modifies the logic for when to automatically tap official taps.
As a refresher, there are two times where an official tap would be automatically tapped:
1. When running the `bundle`, `test-bot`, or `services` command and the respective repo isn't tapped
2. When `args.named.to_casks` (or other similar methods that convert named args to casks) is unable to match a name to a formula or cask. This is seen mostly when running `brew install <invalid_formula_or_cask>` or `brew uninstall <invalid_formula_or_cask>`.
Now, if a user has untapped an official tap, we will remember this in the Homebrew settings. If a user does one of the above actions that would normally tap the repo, we will first check to see whether they have already untapped the repo. If so, we assume …

Don't tap user-untapped official taps

---

Library/Homebrew/extend/git_repository.rb
Library/Homebrew/test/utils/git_repository_spec.rb
Library/Homebrew/utils/git_repository.rb

-----
This PR adds two helper functions for Git repos:
- `Utils::git_branch`, which can used instead of:
- [`shell_output("git log -1")`](https://sourcegraph.com/search?q=repo:homebrew/homebrew-core+git%28%5C%22%2C%5C+%5C%22%7C%5C+%29log&patternType=regexp)
- `shell_output("git log --format=%B -n 1 HEAD")`
- `Utils::git_commit_message`, which can used instead of:
- [`shell_output("git symbolic-ref --short HEAD").chomp`](https://sourcegraph.com/search?q=repo:homebrew/homebrew-core+git%28%5C%22%2C%5C+%5C%22%7C%5C+%29symbolic-ref&patternType=regexp)
- [`shell_output("git rev-parse --abbrev-ref HEAD").strip `](https://sourcegraph.com/search?q=repo:homebrew/homebrew-core+git%28%5C%22%2C%5C+%5C%22%7C%5C+%29rev-parse&patternType=regexp)

utils/git_repository: add `::git_branch` and `::git_commit_message`

---

Library/Homebrew/version.rb

Fixes a type error encountered when running `brew cleanup`:
```console
% brew cleanup -s
Error: Parameter 'val': Expected type T.any(String, Version), got type PkgVersion with hash 2964960359647174741
Caller: /usr/local/Homebrew/Library/Homebrew/cleanup.rb:81
Definition: /usr/local/Homebrew/Library/Homebrew/version.rb:513
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.6216/lib/types/configuration.rb:247:in `call_validation_error_handler_default'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.6216/lib/types/configuration.rb:254:in `call_validation_error_handler'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.6216/ …
```

version: fix type signature

---

Library/.rubocop.yml
Library/Homebrew/homebrew_bootsnap.rb
Library/Homebrew/load_path.rb

- rename to `homebrew_bootsnap.rb` to avoid conflicting with the `bootsnap.rb` we need to `require`
- if the `require` fails: run bundler (until we vendor this gem)

Fix HOMEBREW_BOOTSNAP setup

---

.github/workflows/tests.yml

The syntax job is quick (takes 1m) and this avoids running the long macOS job (for which we have a limited number of workers) unless it has passed.

tests: make macOS tests require a passing syntax job.

---

Library/Homebrew/cmd/cleanup.rb
docs/Manpage.md
manpages/brew.1

-----
add description about `all` to `--prune=`in `cmd/cleanup`. Because only the error message tells about `all`.

cmd/cleanup: add description about all to --prune

---

Library/Homebrew/brew.sh
Library/Homebrew/cli/args.rbi
Library/Homebrew/dev-cmd/release-notes.rb
Library/Homebrew/dev-cmd/release.rb
Library/Homebrew/release_notes.rb
Library/Homebrew/test/dev-cmd/release_spec.rb
Library/Homebrew/test/release_notes_spec.rb
Library/Homebrew/utils/github.rb
completions/bash/brew
completions/internal_commands_list.txt
docs/Manpage.md
docs/Releases.md
manpages/brew.1

-----
This PR adds a new `brew release` developer command to automate the release process. The command, by default, will simply bump the patch version number. If `--major` or `--minor` is passed, the command will bump the major and minor version numbers respectively (and reset other numbers to 0 as needed).
This PR is still _extremely_ rough (hence being marked as a draft). I'm going to immediately cancel CI because I know there are issues that I haven't yet fixed locally. However, I have a few general questions, so I figured I'd open this to track my progress.
I also plan on updating the [Release docs](https://docs.brew.sh/Releases) in this PR in the future.
Additionally, there's some overlap between this command and `brew release-notes` that I plan on extracting to a new module.
----- …

Add brew release command

---

completions/zsh/_brew

-----
#10410 fixed my previous issue #10409, however it also resulted in the `upgrade` completion to list *every* cask, not just the outdated or installed ones. I noticed the same behavior for `brew reinstall` as well. This fixes those completions to only show installed/outdated casks.
I think this PR might become unnecessary due to #10403, but I created this one anyway in case that one does not get merged soon.

Fix zsh completions for upgrade and reinstall

---

Library/Homebrew/resource_auditor.rb
Library/Homebrew/utils/curl.rb

-----
See https://github.com/Homebrew/discussions/discussions/576
Currently, specs passed to the `url` method are passed to `curl` when fetching the resource but aren't passed to `curl` when auditing the resource's url. For example, the user who opened https://github.com/Homebrew/discussions/discussions/576 needed to use the `--referrer` flag in `curl`. That meant that `brew audit --online` was failing even though the url _was_ reachable when actually running `brew install`.
This PR passes those specs on to `Utils::Curl.curl_check_http_content` to ensure that the check will pass in situations like these.

utils/curl: use specs when checking http content problems

---

Library/Homebrew/cli/parser.rb
Library/Homebrew/dev-cmd/extract.rb
Library/Homebrew/test/cask/cmd/create_spec.rb
Library/Homebrew/test/cask/cmd/edit_spec.rb
Library/Homebrew/test/cask/cmd/shared_examples/requires_cask_token.rb
Library/Homebrew/test/cli/parser_spec.rb
completions/bash/brew
docs/Manpage.md
manpages/brew.1

-----
- A friend got an error message when trying to use `brew extract` and it wasn't immediately obvious to me why. The usage banner only mentioned the "formula" argument, which they'd provided. This improves the error message when there aren't enough arguments so that others have a chance of figuring out how to use this command without having to look at the code for `extract_args`.
Before:
```
➜ brew extract --version='1.4' libftdi
Usage: brew extract [--version=] [--force] formula ...
[...]
Error: Invalid usage: this command requires a formula argument
```
After:
```
➜ brew extract --version='1.4' libftdi
Usage: brew extract [options] formula destination_tap
[...]
Error: Invalid usage: This command requires at least 2 named arguments.
```
- I don't like the "at least 2" phrasing here …

dev-cmd/extract: Improve the usage instructions

---

Library/Homebrew/homebrew_bootsnap.rb

Use one of the possible temp variables and `raise` if not.

homebrew_bootsnap: fix brew tests.

---

Library/Homebrew/test/version/parser_spec.rb
Library/Homebrew/version.rb
Library/Homebrew/version/parser.rb

-----
This PR adds four new classes for parsing version strings from `Pathname`s: `Parser`, `RegexParser`, `UrlParser`, and `StemParser`
- `Parser` is the base abstract class and currently does nothing; all it contains is an abstract `parse` method.
- (This class is useful to have if we ever need to parse version strings through means other than regular expressions.)
- `RegexParser` is a sub-class of `Parser` and uses regular expressions to extract version strings from `Pathname`s.
- This class is also abstract; sub-classes of `RegexParser` must implement the `process_spec` method.
- It accepts an optional `block` that is called to finalize the parsed version string; this is used for Boost version styles to replace underscores (`_`) with dots (`.`)
- `UrlParser` is a sub-class of …

version: add new `Version::Parser` class

---

Library/Homebrew/cli/named_args.rb

-----
Supersedes https://github.com/Homebrew/brew/pull/10393
Commands such as `brew install` should print an error if the formula/cask is found but it is unreadable
Before:
```console
$ brew install athenason/repo/bazel@1.2.1
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "athenason/repo/bazel@1.2.1".
```
After:
```console
$ brew install athenason/repo/bazel@1.2.1
Error: athenason/repo/bazel@1.2.1: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the athenason/repo tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it: …
```

named_args: raise error if formula/cask is found but unreadable

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/utils/github.rb

-----
- If the formula is deprecated because it doesn't build, raise an error.
- For example, [`openrtsp`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/openrtsp.rb) will be [disabled on 2021-11-22](https://github.com/Homebrew/homebrew-core/pull/69307); since we have not yet reached that date, it is treated as a deprecated formula (i.e. `disabled?` returns `false`, but `deprecated?` returns `true`). We shouldn't open new bump PRs for this formula because [we've already tried updating it before](https://github.com/Homebrew/homebrew-core/pull/68149#issuecomment-762520242), and future versions will most likely continue failing to build.
- Check if the formula is throttled, and if so, check if the specified new version meets the throttle requirement.
- For example, raise an …

bump-formula-pr: improvements

---

Library/Homebrew/cmd/update.sh

Specifically the warning(s):
`Failed to set filetime <unixtime> on outfile: Operation not permitted`
when the user's `.curlrc`  contains `--remote-time` and the server returned a `Last-Modified:` header, like in case of the GitHub API.
---
-----

cmd/update: suppress curl warnings in certain envs

---

Library/Homebrew/install.rb

It's possible the user's terminal emulator is running under rosetta2.
Consequently, the i86_64 version of the ruby interpreter will be used.
Likely, the right thing to do is simply install the arm64 version of the
requested package. This can be accomplished using: arch -arm64 brew ...
Fixes: #10313 
> There were numerous failures...
> Failure: Broken pipe
-----
Please help direct me to the right tests (if necessary). Also, I'm unable to test this because it does no appear that brew cares about the prefix when it's not in /opt or /usr. When I run `arch -x86_64 brew install ...` it completes successfully and does not complain. Is there a way to instruct brew to care so I can hit the codepath?

install: add workaround for rosetta2 path error to msg

---

Library/Homebrew/dev-cmd/bump.rb
Library/Homebrew/test/dev-cmd/bump_spec.rb

-----
This is a follow-up PR to increase `brew bump`'s test coverage after the refactoring PR (#10285).
Summary of changes:
* Combined repetitive logic into a single method, `retrieve_and_display_info`.
* Added a test for HEAD-only formulae.
In hindsight, I shouldn't have removed the `do not merge` label from the refactoring PR, I didn't notice the decrease in coverage until Sam mentioned it. Sorry! 😅
CC @samford

dev-cmd/bump: increase test coverage

---

Library/Homebrew/extend/ENV/shared.rb

This was only used by 2 formuale in homebrew-core.
One formula did not need the flag anymore and the flag was removed
The other formula (rogue) still needs it, the flag was directly
added to the formula.
There is no reason for us to keep this method.
-----

ENV.shared: deprecate ncurses_define

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/test/cask/audit_spec.rb

-----
This audit already exists for formulae (but not for casks): https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_auditor.rb#L688-L699
Related: https://github.com/Homebrew/homebrew-cask/pull/98719

cask/audit: disallow new cask to have token in tap_migrations.json

---

Library/.rubocop_rspec.yml
Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/test/cleanup_spec.rb
Library/Homebrew/test/spec_helper.rb

- always retry each test at least once (confusingly this means a retry count of 2 rather than 1)
- always wait at least 1 second between retries
- set a default retry metadata for integration tests rather than overriding any specified values
- use `example.run` rather than `example.run_with_retry` for integration tests because, confusingly, this avoids having the retry count be half what it should be (because the attempts increases by one for each `run_with_retry` call)
- use 4 retries for integration tests with 2**attempts*retry_wait (retry wait now being 2) to actually have more retries than before this commit (but with exponential backoff)
This should generally improve test flakiness in CI but particularly improve the cleanup test flake we've seen recently.

spec_helper: fix and improve retry logic.

---

Library/Homebrew/completions.rb
Library/Homebrew/completions/fish.erb
Library/Homebrew/test/completions_spec.rb
completions/fish/brew.fish

-----
Continuation of the work for #10223.
This PR adds the ability for `brew man` to automatically generate fish completions. Like with the bash and zsh completions, this isn't super intelligent at the moment. It doesn't know how to handle conflicting options or anything like that.
Fish completions also use descriptions. These are generated in the same way that the zsh descriptions are generated.
One thing to note for these is that they include completions for `brew bundle` and `brew services`. I briefly tried to separate these out to go into their own taps but wasn't able to get it to work quite right. I'll continue to look into it because being able to generate external completions for brew commands is probably a good idea.

Generate fish completions automatically

---

Library/Homebrew/cmd/--cache.rb
Library/Homebrew/commands.rb
Library/Homebrew/completions.rb
completions/zsh/_brew

Before:
```console
% brew --cache --cask --<TAB>
--build-from-source  -- Show the cache file used when building from source
--debug              -- Display any debugging information
--force-bottle       -- Show the cache file used when pouring a bottle
--formula            -- Only show cache files for formulae
--help               -- Show this message
--quiet              -- Make some output more quiet
--verbose            -- Make some output more verbose
```
After:
```console
% brew --cache --cask --<TAB>
--debug    -- Display any debugging information
--help     -- Show this message
--quiet    -- Make some output more quiet
--verbose  -- Make some output more verbose
```
-----

zsh: don't complete conflicting options

---

Library/Homebrew/completions/zsh.erb
completions/zsh/_brew

If we type `brew install -<TAB>` we shouldn't try to shell out to Ruby to get a list of formulae for completions, since formulae aren't allowed to start with a hyphen.
This is especially important for commands that we can't or don't already cache, such as a list of outdated formulae or installed taps. `brew link --<TAB>` before and after this pull request is a good example to showcase the speedup, or try `brew install --<TAB>` after removing your zsh completions cache in `~/.zcomp*`.
http://zsh.sourceforge.net/Doc/Release/Completion-Widgets.html#Completion-Condition-Codes
-----

zsh: add guards to speed up completions

---

Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/test/cleanup_spec.rb

I suspect this may be part of the cause of the flaky `cleanup` spec.
Also, while we're working on that, revert 3724c739f880945ec76a16ef8b9209c6440f0035 because it didn't make any different to the cleanup spec.

tests: cleanup user configuration.

---

Library/Homebrew/formula_auditor.rb

-----
delete the check whether `alias_name_major_minor` is `adoptopenjdk@1.8 ` because `adoptopenjdk` is a cask and `alias_name_major_minor` will not be `adoptopenjdk@1.8` .
```
brew search adoptopenjdk
==> Casks
adoptopenjdk
```

formula_auditor: delete adoptopenjdk condition

---

Library/.rubocop.yml
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb

cellars: write tag specific cellars

---

Library/.rubocop.yml

The " was for a previous syntax we had, but we dropped that and changed our minds.
This PR fixes the style check for the current implementation of the new bottle blocks.
-----

style: handle line too long for new bottle blocks

---

Library/Homebrew/cmd/tap.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/cmd/update-reset.sh
Library/Homebrew/cmd/update.sh
Library/Homebrew/extend/git_repository.rb
Library/Homebrew/tap.rb
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

-----
GitHub now supports renaming branches. I will open a separate issue to discuss what that means for the Homebrew project. In the meantime, it's possible that maintainers of third-party taps will rename their default branches. This PR attempts to let `brew update` handle these renamed.
GitHub recommends using the following commands to update local configurations:
```
git branch -m <old> <new>
git fetch origin
git branch -u origin/<new> <new>
```
This works okay, although it doesn't actually update `refs/remotes/origin/HEAD`. The problem is that there is no way to determine _what_ the new remote branch name is. `git ls-remote --heads origin` will list the branches that exist, but there's no way to determine which branch is the `origin/HEAD` branch. One way to handle this is to query …

Handle upstream branch renames

---

Library/Homebrew/cli/named_args.rb
Library/Homebrew/test/cli/named_args_spec.rb
Library/Homebrew/test/cmd/--cache_spec.rb
Library/Homebrew/test/cmd/home_spec.rb

-----
Related: https://github.com/Homebrew/brew/pull/10405, https://github.com/Homebrew/brew/pull/10422
This PR changes how some edge cases are handled in `named_args.rb`:
- When both the formula and the cask are unreadable, raise the `FormulaUnreadableError`
- When both the formula and the cask are present and one of them is unreadable, print the error and a warning that the readable one will be used.
<details open><summary><code>brew info</code> output when both the formula and the cask are unreadable</summary>
Before:
```console
$ brew info crunch
Error: No available formula or cask with the name "crunch".
```
After:
```console
$ brew info crunch
Error: crunch: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crunch.rb:5: syntax error, unexpected tSTRING_BEG, expecting …
```

named_args: raise or print error if both or either formula/cask unreadable

---

Library/Homebrew/completions/fish.erb
completions/fish/brew.fish

-----
Trying fish completion for `brew upgrade` results in:
```
brew upgrade Error: Calling `brew cask outdated` is disabled! Use brew outdated [--cask] instead.
Error: Calling `brew cask outdated` is disabled! Use brew outdated [--cask] instead.
Error: Calling `brew cask outdated` is disabled! Use brew outdated [--cask] instead.
```
This updates the deprecated command to properly generate the completion.

Fix fish shell completion for upgrade

---

Library/Homebrew/dev-cmd/typecheck.rb

Also, add a TODO to answer why the other error codes are suppressed.

typecheck: migrate from deprecated flag.

---

Library/Homebrew/requirements/java_requirement.rb

-----
delete the check `Formula["adoptopenjdk"]` is `latest_version_installed?` because `adoptopenjdk` is a cask and `Formula["adoptopenjdk"]` always raises `FormulaUnavailableError`

requirements/java_requirement: delete adoptopenjdk condition

---

Library/Homebrew/dev-cmd/livecheck.rb

-----
`~/.brew_livecheck_watchlist`:
```
appium
```
Before:
```console
$ brew livecheck --formulae
Warning: Treating appium as a formula. For the cask, use homebrew/cask/appium
appium : 1.20.2 ==> 1.20.2
```
```console
$ brew livecheck --casks
Warning: Treating appium as a formula. For the cask, use homebrew/cask/appium
Error: Invalid usage: No formulae or casks to check.
```
After:
```console
$ brew livecheck --formulae
appium : 1.20.2 ==> 1.20.2
```
```console
$ brew livecheck --casks
appium : 1.19.1 ==> 1.20.0
```

livecheck: fix filtering of watchlist with --formulae/--casks flag

---

Library/Homebrew/cask/audit.rb

-----
This PR changes `brew audit --cask` such that an error is raised if the `verified` parameter is present for a `url` but does not match. For example, this should give an audit error:
```rb
url "https://shining.softorino.com/shine_uploads/waltr#{version.major}mac_#{version}.dmg",
verified: "dl.devmate.com/com.softorino.waltr2/"
```
Related:
- https://github.com/Homebrew/homebrew-cask/pull/98995
- https://github.com/Homebrew/homebrew-cask/pull/98996
- https://github.com/Homebrew/homebrew-cask/pull/98997
- https://github.com/Homebrew/homebrew-cask/pull/98998
- https://github.com/Homebrew/homebrew-cask/pull/98999
- https://github.com/Homebrew/homebrew-cask/pull/99000
- https://github.com/Homebrew/homebrew-cask/pull/99001
- https://github.com/Homebrew/homebrew-cask/pull/99002
- …

cask/audit: error if `verified` does not match, regardless of `url`

---

Library/.rubocop.yml

Another rule that assumes Rails usage.

rubocop.yml: disable Rails/RakeEnvironment

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
Explicitly pass `--formula` flag to prevent cask warning in `bump-formula-pr`.
Before:
```
$ brew bump-formula-pr whistle --url https://registry.npmjs.org/whistle/-/whistle-2.6.4.tgz --no-browse -w --force
==> Downloading https://registry.npmjs.org/whistle/-/whistle-2.6.4.tgz
######################################################################## 100.0%
Warning: Cannot verify integrity of 'b2bf9da204a4c13d7f5bd734cca8504ac08cff334022120f34a058508f2d3a99--whistle-2.6.4.tgz'.
No checksum was provided for this resource.
For your reference, the checksum is:
sha256 "a6c7f1df6951d7c46d2d98f13448fc696788daf01f86ba33c56dd4d4821227d4"
==> replace /https:\/\/registry\.npmjs\.org\/whistle\/\-\/whistle\-2\.6\.3\.tgz/ with "https://registry.npmjs.org/whistle/-/whistle-2.6.4.tgz"
==> replace …
```

bump-formula-pr: pass --formula flag when auditing a bumped formula

---

Library/Homebrew/dev-cmd/prof.rb

Want to ensure that we still write profiling data even if the Homebrew command fails.

dev-cmd/prof: allow non-zero exit code.

---

Library/Homebrew/cask/config.rb
Library/Homebrew/test/cask/config_spec.rb

-----
Export a Cask object's explicit config as string for homebrew-bundle, as suggested in Homebrew/homebrew-bundle#892 for forthcoming homebrew-bundle PR. CC @Homebrew/cask for opinions.

cask/config: new method for cask.config.explicit as string

---

Library/Homebrew/homebrew_bootsnap.rb

Otherwise this prints a warning.

homebrew_bootsnap: remove deprecated option.

---

Library/Homebrew/extend/os/language/java.rb
Library/Homebrew/extend/os/mac/language/java.rb
Library/Homebrew/language/java.rb
Library/Homebrew/test/language/java_spec.rb

https://github.com/Homebrew/brew/pull/10397 incorrectly changed what `java_home` pointed to on macOS. The path is correct on Linux, but on macOS, the Java home is actually in /usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home to ensure compatibility with being linked to /Library/Java/JavaVirtualMachines per the openjdk formula caveat.
If a formula used e.g. `bin.write_jar_script` in its install block, this is what it looks like on macOS before and after this pull request.
```sh
#!/bin/bash
export JAVA_HOME="${JAVA_HOME:-/usr/local/opt/openjdk/libexec}"
exec "${JAVA_HOME}/bin/java"  -jar "/usr/local/Cellar/foo/1.0/libexec/foo.jar" "$@"
```
```sh
#!/bin/bash
export JAVA_HOME="${JAVA_HOME:-/usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home}"
exec "${JAVA_HOME}/bin/java"  -jar …
```

java: fix java_home on macOS

---

.github/ISSUE_TEMPLATE/bug.yml

- Don't require `brew update` (as we run it automatically now)
- Don't ask about `brew doctor` until after they have pasted output (and ask them if it has any `Warning` lines)

ISSUE_TEMPLATE/bug: tweak checkboxes.

---

.github/workflows/tests.yml
Library/Homebrew/homebrew_bootsnap.rb

Set this for the only tests with measurable, multi-minute improvements.
Also:  use `utils/gems` as this is more robust e.g. if we don't have a `bundler` already installed.

workflows/tests: set HOMEBREW_BOOTSNAP.

---

Library/Homebrew/cask/audit.rb

-----
We have a script which auto-adds/fixes fonts from Google Fonts to [homebrew/cask-fonts](https://github.com/Homebrew/homebrew-cask-fonts/). But those may fail `audit` due to missing `desc` stanzas, [sometimes an absurd amount](https://github.com/Homebrew/homebrew-cask-fonts/pull/3414#issuecomment-761709999). Realistically, font casks do not require descriptions, and we shouldn’t make it a requirement for them.

cask audit: do not require description for fonts

---

Library/Homebrew/hardware.rb
Library/Homebrew/os/mac/architecture_list.rb
Library/Homebrew/os/mac/mach.rb
Library/Homebrew/utils.rb

(a few pre-existing failures)
-----
The eventual goal is phasing out `ArchitectureListExtension` which only supports Intel. The extension is used in:
* `Hardware::CPU.universal_archs`. Only used in other disabled functions and not in homebrew-core so can be deprecated.
* In the `Pathname` extension method `archs`. This is private API and is macOS-only but the result is exposed in the public method `arch_for_command`, which is no longer used anywhere.

Deprecate additional arch functions

---

Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

Note that it is a no-op when using portable ruby.

env_config: update HOMEBREW_BOOTSNAP description.

---

Library/Homebrew/dev-cmd/man.rb

-----
The `brew man` command doesn't work on Apple silicon using the system ruby. However, building and using https://github.com/Homebrew/homebrew-portable-ruby does allow the `ronn` gem and therefore the `brew man` command to work. Given that this is not a supported configuration, allow the command to run on Silicon only if a user passes the `--force` flag.
Helps to address https://github.com/Homebrew/brew/issues/10210

man: allow command to run on unsupported platforms when --force is passed

---

Library/Homebrew/cask/config.rb

-----
As pointed out in [#10462 (comment)](https://github.com/Homebrew/brew/pull/10462#issuecomment-771939871), tests failed locally when languages other than `en` were enabled (sample output in #10490).
This PR fixes the `explicit_s` method to output only the languages passed as `explicit` config.
CC @EricFromCanada

cask/config: fix `explicit_s`

---

Library/Homebrew/dev-cmd/release.rb

I forgot until I started to work on the 3.0.0 release that there was an added step I would do for a major/minor release:
```
brew release-notes --markdown 2.7.0 | pbcopy
```
This would generate for 3.0.0/2.8.0 the release notes since 2.7.0 for editing down into a blog post.
Add this behaviour to `brew release` and, because we're doing it programmatically anyway, take this chance to also reject Dependabot lines and sort them for easier grouping by pull request subject.
Thanks again to @Rylan12 for creating this command, this was surprisingly easy to do 🎉 
Marking as `critical` so this makes it into 3.0.0 (meta, right?).

dev-cmd/release: output blog post release notes.

---

Library/.rubocop.yml

-----
Needed for https://github.com/Homebrew/homebrew-core/pull/70283#issuecomment-772534602
Disable the line length check for bottle digests that don't specify a cellar. This is a continuation of https://github.com/Homebrew/brew/pull/10452 where it was decided not to allow all instances of `    sha265 `. Indeed, this would allow line length violations on non-bottle lines (which would probably be fine given that these lines are likely to contain only a 64-character digest). Instead, I added a second space to make `    sha256  `. This will only exclude bottle lines that have indented tags and no cellar (which is already covered).
Here's an example of a bottle block that failed the line-length check before but now passes:
```ruby
bottle do
sha256                               arm64_big_sur: …
```

style: allow long lines for bottle digests

---

Library/Homebrew/homebrew_bootsnap.rb

From https://github.com/Homebrew/homebrew-core/pull/70310/checks?check_run_id=1823920962 this looks very broken indeed.

homebrew_bootsnap: disable on ARM.

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/rubocops.rb
Library/Homebrew/rubocops/bottle.rb
Library/Homebrew/rubocops/shared/helper_functions.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb
Library/Homebrew/test/rubocops/bottle/bottle_digest_indentation_spec.rb
Library/Homebrew/test/rubocops/bottle/bottle_format_spec.rb
Library/Homebrew/test/rubocops/bottle/bottle_order_spec.rb
Library/Homebrew/test/rubocops/bottle/bottle_tag_indentation_spec.rb
docs/Bottles.md

-----
Part 3 of https://github.com/Homebrew/brew/issues/9315
`brew style --fix homebrew/core`: https://github.com/SeekingMeaning/homebrew-core/commit/tmp-new-bottle-syntax
```console
5467 files inspected, 36416 offenses detected, 36416 offenses corrected
```
Before:
```rb
bottle do
rebuild 4
sha256 "e87da2b47386fc7e3c6f20b3ff90c4bbe37b9e0aaa884440ffa216492dbc150b" => :big_sur
sha256 "8ac02041dbec3966b6a695dfc4215b90b9e331ae6eb8c6698cbbfa0175154c9f" => :arm64_big_sur
sha256 "82e64b2008971430d160a3f564e32593e98fb55c43d7748c7deb9d6f546e1102" => :catalina
sha256 "8ca49b4797277f79e87e48ab4c6794601b64d1dde35b9eac556d4153b8237a51" => :mojave
end
```
After:
```rb
bottle do
rebuild 4
sha256 big_sur: "e87da2b47386fc7e3c6f20b3ff90c4bbe37b9e0aaa884440ffa216492dbc150b"
sha256 arm64_big_sur: …
```

rubocops: add rubocop for old bottle syntax

---

docs/Homebrew-and-Python.md

-----
This tweaks the `Homebrew-and-Python` doc to include a note about the stability of the various Python 3 formulae: we don't have a policy of guaranteeing that `/usr/local/bin/python3` (or wherever) remains at the same minor and patchlevels between upgrades, which is a frequent source of confusion for people using the Homebrewed Python with virtual environments. I think this is reasonable behavior on our part (since it's what every other system package manager does), but making an explicit note of it will give us something easy to link to when the question comes up.

docs: add a note about the stability of python 3 formulae

---

Library/Homebrew/rubocops/bottle.rb
Library/Homebrew/test/rubocops/bottle/bottle_order_spec.rb

This is causing CI failures at homebrew/core [1], so let's disable this
for now.
[1] https://github.com/Homebrew/homebrew-core/commit/01b6830646c216a80e4747154963942626ce4cbe

rubocops/bottle: disable bottle order check

---

Library/Homebrew/formula_auditor.rb

-----
The `audit_github_repository_archived` and `audit_gitlab_repository_archived` formula audits are currently skipped for deprecated formulae but not for disabled formulae.
For example, the `contacts` formula is disabled but `brew audit --online contacts` will give `GitHub repo is archived`. Seeing as deprecate and disable are related conditions, it seems like it would be similarly appropriate to skip the archived repository audits for disabled formulae as well.

formula_auditor: skip archived repository audits if disabled

---

Library/Homebrew/cmd/untap.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

Functionality added in https://github.com/Homebrew/brew/pull/9489, but without the flag.
This PR fixes that.
Closes: #10511
-----

untap: add missing --force switch

---

Library/Homebrew/software_spec.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb

-----
Follow up to #10517
This PR fixes `brew bottle` so it writes the arm bottles first (as described in #10453). I'll open a separate PR to re-enable the style rule (doing them separately makes the process easier and won't require anything nearly as involved as last time).

bottle: write bottles in correct order

---

Library/Homebrew/rubocops/bottle.rb
Library/Homebrew/test/rubocops/bottle/bottle_order_spec.rb

-----
Follow up to https://github.com/Homebrew/brew/pull/10522.
This PR re-enables the style check to ensure the bottle lines are in the correct order.
This should not be merged until #10522 has been merged and all style issues in homebrew/core and linuxbrew/core have been resolved.

style: re-enable bottle order cop

---

Library/Homebrew/cmd/--prefix.rb

- `Cask::Config#explicit` did not expect a language `en-GB`, which caused a failure.
-----
The `shared-mime-info` formula and the `mactex` cask currently install into
locations that are picked up by `brew --prefix --unbrewed`. This leads
to a very large number of files being found.
Before:
```
❯ brew --prefix --unbrewed | wc -l
206735
```
After
```
❯ brew --prefix --unbrewed | wc -l
3
```

cmd/--prefix: ignore shared-mime-info and mactex

---

docs/Releases.md

- Note that Homebrew/homebrew-core CI jobs should complete successfully before creating a release
- No code changes only required for 4 hours, 24 hours is a bit excessive/unrealistic
- Note that commented `odeprecated` code should be uncommented
- TinyLetter emails are no longer required (MailChimp does so automatically from the RSS feed)
- Note that `brew release` will output the major/minor blog post content (after #10499 is merged) instead of referencing the now-deprecated `brew release-notes`
- Note why you should not create a release on older `master` commits and provide an alternate process to handle this case
- Various style tweaks
Particularly interested in feedback from @Rylan12 and @jonchang here.
@jonchang Does this address your concerns on how to create a patch release when …

docs/Releases: update process documentation.

---

Library/Homebrew/cmd/update-report.rb

Otherwise things like `$(brew bundle list --formula)` become a bit useless as they can auto-update and then will always fail.

cmd/update-report: output to stderr when not a TTY.

---

Library/Homebrew/extend/os/mac/diagnostic.rb

-----
We use `codesign` when pouring bottles, so the development tools now need to be installed even when only consuming bottles.
Currently, `codesign` failures are non-critical (`onoe`). So a user without development tools could peform `brew install git` or `brew upgrade git` and break their `brew` installation due to a non-functional unsigned `git` binary (or one of its dependencies).
This addresses at least one scenario leading towards #10275.

os/mac/diagnostic: always require dev tools on Apple Silicon

---

Library/Homebrew/utils/github.rb

-----
- When running [`brew request-bottle`](https://github.com/Homebrew/homebrew-linux-dev/blob/master/cmd/request-bottle.rb), which uses `GitHub.open_api()` from here, users who don't have credentials in the macOS keychain (ie, Linux users) or `HOMEBREW_GITHUB_API_TOKEN` receive "Error: Not Found" from the GitHub API returning a 404.
- This is cryptic and confusing for newcomers to Linux maintenance, and potentially confusing to other folks using `open_api` where credentials are expected yet unset.
- This adds a new `MissingAuthenticationError` to handle the case where the GitHub API returns 404 and there are no creds yet API scopes are required.
Before:
```
issyl0@sky:/home/linuxbrew/.linuxbrew/Homebrew$ brew request-bottle hello
==> Dispatching request to Homebrew/linuxbrew-core for …
```

utils/github: Provide a better error message when users don't have any GitHub credentials set

---

Library/Homebrew/homebrew_bootsnap.rb

If `bootsnap` isn't available then print out an error message rather than failing all of Homebrew.

homebrew_bootsnap: fail more gracefully.

---

Library/Homebrew/utils.rb

-----
Several calls to `ohai` and `puts` were directly changed into calls to these new functions, but they don't share arity or an API. The base functions allow arbitrary number of arguments, allowing for multiline printing that covers both a title and a longer message.
Sample error:
```
Updated 1 tap (homebrew/core).
Error: wrong number of arguments (given 2, expected 1)
/usr/local/Homebrew/Library/Homebrew/utils.rb:114:in `ohai_stdout_or_stderr'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:489:in `dump'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:132:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```
The bug was introduced in …

Utils: fix *_stdout_or_stderr helpers

---

Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/test/livecheck/livecheck_spec.rb

-----
When a formula doesn't have a `livecheck` block, the `Livecheck#checkable_urls` method organizes URLs to check in order of: `head`, `stable`, and `homepage`. Checking Git tags is generally pretty reliable, so it was a good way to identify versions for as many formulae as possible without requiring manual labor early on.
Nowadays, livecheck has strategies to handle a variety of sources and we prefer to align the check with the `stable` source whenever possible. However, checking `head` first can prevent livecheck from using a checkable `stable` URL. There have been times where a formula was successfully checking `stable` by default and then a `head` URL was added to the formula, which switched the livecheck source and strategy. In these cases, we've had to add a `livecheck` block …

livecheck: check stable before head by default

---

Library/Homebrew/extend/ENV/shared.rb
Library/Homebrew/extend/ENV/std.rb
Library/Homebrew/extend/ENV/super.rb

These are still used in Homebrew/homebrew-core. The others are either
- default (Os on macOS, O2 on Linux)
- less reliable than the default (O3)
While we're here, also remove an outdated `ncurses_define` comment.

Undeprecate ENV.O1/ENV.O0

---

Library/Homebrew/utils/github.rb

I've recently tried bumping a cask version and got a recommendation to create a token with this message:
Or create a personal access token:
https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
As it was missing the workflow scope the bump failed.
```
To https://github.com/mindfulmonk/homebrew-cask.git
! [remote rejected]       bump-rekordbox-6.5.0-20210127201749 -> bump-rekordbox-6.5.0-20210127201749 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/automerge.yml` without `workflow` scope)
```
Previous pull request https://github.com/Homebrew/brew/pull/10562 
-----

Add workflow scope to github.rb

---

Library/Homebrew/compilers.rb
Library/Homebrew/extend/os/compilers.rb
Library/Homebrew/extend/os/linux/compilers.rb
Library/Homebrew/test/compiler_selector_spec.rb

Fixes #10170 by preferring gcc@5 on linux
This makes sure ENV.cc and ENV.cxx is correctly set:
If a formula does not explicitely depend on a brewed gcc,
ENV.cc is set to gcc-5 (system gcc-5 or brewed gcc-5) with this change,
even if other gcc versions are installed on the system.
-----

compilers: prefer gcc 5 on linux

---

Library/Homebrew/formula.rb
Library/Homebrew/software_spec.rb

-----
Closes #9315 (although I can unlink so that issue isn't closed until the actual deprecations are merged)
This is the last step needed to finish #9315. It prepares the deprecations for the old bottle syntax. These deprecations are commented out for now but should be uncommented for the 3.1.0 release.
CC: @iMichka

Prepare deprecations for the old bottle syntax

---

Library/Homebrew/tap.rb

Issue reproduction:
```shell
❯ git config --global clone.defaultRemoteName notorigin
❯ brew tap bazelbuild/tap
❯ brew update
❯ brew untap bazelbuild/tap
❯ echo "Apply change from PR"
❯ brew tap bazelbuild/tap
❯ brew update
❯ git config --global --unset clone.defaultRemoteName
```
Output:
```console
❯ git config --global clone.defaultRemoteName notorigin
❯ brew tap bazelbuild/tap
==> Tapping bazelbuild/tap
Cloning into '/usr/local/brew/Library/Taps/bazelbuild/homebrew-tap'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 314 (delta 7), reused 11 (delta 5), pack-reused 291
Receiving objects: 100% (314/314), 59.32 KiB | 311.00 KiB/s, done.
Resolving deltas: 100% (150/150), done.
Tapped 1 …
```

fix(tap): set clone remote name to origin explicitly

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/system_config.rb

-----
* ~~Detect OpenJDK installations~~
* Prevent `java` installation prompt from appearing on macOS (fixes #10491)
* Silence verbose `system_command` output

system_config: remove describe_java

---

Library/Homebrew/compilers.rb
Library/Homebrew/extend/os/linux/compilers.rb
Library/Homebrew/extend/os/linux/keg_relocate.rb
Library/Homebrew/extend/os/linux/linkage_checker.rb
Library/Homebrew/extend/os/linux/system_config.rb
Library/Homebrew/test/formula_installer_bottle_spec.rb
Library/Homebrew/test/formulary_spec.rb

linux: use preferred_gcc instead of gcc

---

Library/Homebrew/dev-cmd/update-maintainers.rb

-----
- I noticed this in a PR recently, maybe the maintainer didn't think they would have to run `brew man` for this? In that case there's an extra step after the PR is raised, red CI checks on the PR (which is demoralising) and potentially requires a reviewer to point this out.
- This runs `brew man` if the `README` file has a diff as part of this command. Then the user has to `git add .` and their PR is (probably) good.
- I thought at first to remind users to run `brew man` after the success message, but it was just as easy to run the update command automatically.

dev-cmd/update-maintainers: If there are changes, auto-update man pages

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/utils.rb

-----
I've been wanting to do this for a while now.
This helps with the confusion people may have with the differences between `brew update` and `brew upgrade`.
With this change, `brew update` (via `update-report`) will now report how many installed formulae and casks are outdated and points the user to `brew upgrade` to update them.

cmd/update-report: report outdated count & suggest `brew upgrade`

---

Library/Homebrew/os/mac/keg.rb

-----
Helps provide information useful for bug reports.
I've not tested this code (I don't have an Apple Silicon Mac anymore).

os/mac/keg: print stderr on codesign failure

---

Library/Homebrew/test/utils/git_spec.rb

-----
(e.g. system git on Mojave)

test/utils/git_spec: fix cherry pick test with older git

---

Library/Homebrew/development_tools.rb

Check `HOMEBREW_PREFIX/opt/#{CompilerSelector.preferred_gcc}/bin/`
rather than `HOMEBREW_PREFIX/opt/gcc/bin/`

non_apple_gcc_version: Use preferred_gcc

---

Library/Homebrew/Gemfile
Library/Homebrew/Gemfile.lock
Library/Homebrew/dev-cmd/rubocop.sh
Library/Homebrew/style.rb
Library/Homebrew/utils/rubocop.rb
Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/warning-1.1.0/lib/warning.rb

-----
This PR attempts to solve part of #10505
The idea is that we can initiate rubocop by calling [`RuboCop::CLI.new.run`](https://github.com/rubocop-hq/rubocop/blob/f919444407975f6379b3f0df582a900c0e2b8ec7/lib/rubocop/cli.rb#L31-L59) instead of using a `system` call to rubocop. Once this is done, we can selectively ignore the warnings to remove the message.
It appears that this first draft works well. I've noticed two issues, though:
1. Calling rubocop directly raises style warnings that were not raised previously. I think that this is likely due to a misconfiguration, but it is surprising.
1. Calling rubocop directly doesn't display rubocop errors. This isn't an issue for most `brew style` users, but for those who create and modify style rules, this lack of indication of a rubocop …

style: call rubocop directly

---

Library/Homebrew/rubocops/lines.rb

Suggested in https://github.com/Homebrew/homebrew-core/pull/70675#issuecomment-775092539

rubocops/lines: check for `if ENV["CI"]` usage.

---

Library/Homebrew/dev-cmd/man.rb
manpages/brew.1

-----
When using `brew man` to regenerate manpages, names with diacritics would be rendered incorrectly in the final output. This PR fixes the issue by removing diacritics/accents from the generated manpage text.
I did try getting it to render these characters properly, but for some reason that wouldn't happen despite following the `groff` syntax, on my computer.

dev-cmd/man: remove diacritics for manpage

---

.github/dependabot.yml

-----
Old dependabot-preview used to do this. I think it's better for security reasons.

dependabot: allow indirect dependency updates

---

Library/Homebrew/dev-cmd/prof.rb
docs/Manpage.md
manpages/brew.1

`brew prof` was incorrectly marked as having an optional argument, which is not correct as a bare `brew prof` will result in:
```console
% brew prof
Error: undefined method `extname' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/dev-cmd/prof.rb:30:in `prof'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```
-----

prof: needs at least 1 argument

---

Library/Homebrew/brew.sh
Library/Homebrew/download_strategy.rb
Library/Homebrew/resource.rb
Library/Homebrew/style.rb
Library/Homebrew/test/spec_helper.rb
Library/Homebrew/utils/rubocop.rb
Library/Homebrew/warnings.rb
Library/Homebrew/warnings.rbi

-----
See https://github.com/Homebrew/brew/issues/10593
Increase the default warning level to `-W1`. I've played with this a little locally, and I don't see any issues so far. My understanding is that `-W1` means that the only warnings that will be shown are those thrown using the `#warn` method. We don't use this method anywhere in Homebrew (it would likely be a bug if we did since it was being silenced), so the only potential warnings that could be shown are from other gems (e.g. `rubocop` or `rspec`). I've looked through the main commands that I think might have new warnings (including `style`, `man`, `prof`, `bump`, `tests`) and I don't detect any new warnings (the `parser/current` warning on `brew tests` is still present but is not new).
Homebrew developers can still set …

Set default ruby warning level to -W1

---

Library/Homebrew/completions.rb

-----
delete the check whether the command is `brew cask` or not  in `completions.rb`

completions: delete brew-cask check

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/cmd/gist-logs.rb
Library/Homebrew/dev-cmd/pr-pull.rb
Library/Homebrew/dev-cmd/pr-upload.rb
Library/Homebrew/dev-cmd/release.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/formula_creator.rb
Library/Homebrew/search.rb
Library/Homebrew/tap.rb
Library/Homebrew/test/search_spec.rb
Library/Homebrew/test/tap_spec.rb
Library/Homebrew/utils/github.rb
Library/Homebrew/utils/github/api.rb
Library/Homebrew/utils/shared_audits.rb
Library/Homebrew/utils/spdx.rb

-----
The `GitHub` module in `utils/github.rb` was getting too large - beyond the 600 lines style limit - and in #10518 it was decided to temporarily relax that limit, and work on splitting the module in a follow-up PR.
This PR splits the `GitHub` module in the following manner:
* `utils/github/api` - all the "access API" and credentials methods and error classes.
* `utils/github` - wrapper functions to access specific API endpoints.
As a result of this PR, changes will have to be made in some files in other repositories (including `Homebrew/homebrew-cask` and `Homebrew/homebrew-linux-dev`). I'm collecting a list of changes to make and will update it here.
See [#10518 (comment)](https://github.com/Homebrew/brew/pull/10518#issuecomment-774985742).

utils/github: split GitHub module

---

Library/Homebrew/cask/cask.rb

-----
This PR fixes equality checking for Casks.
Before:
```
➜ brew livecheck volt homebrew/cask/volt
Warning: Treating volt as a formula. For the cask, use homebrew/cask/volt
Error: undefined method `token' for #<Formulary::FormulaNamespace8375643587616545a6f8955d8b01e055::Volt:0x00007ff183b86ec0>
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:165:in `eql?'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:61:in `uniq'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:61:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/livecheck.rb:84:in `livecheck'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```
After:
```
➜ brew livecheck volt homebrew/cask/volt
Warning: Treating volt as …
```

Fix eql? in Cask::Cask

---

Library/Homebrew/dev-cmd/bump.rb
Library/Homebrew/test/utils/repology_spec.rb
Library/Homebrew/utils/repology.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

-----
This PR adds cask support for `brew bump`. Additionally, some other changes have been made:
* The earlier pagination handling for the Repology API was incorrect (used last package index rather than name), that has been fixed and confirmed to work now.
* The `--limit` flag will work only if `--formula` or `--cask` have been provided (although this can be changed).
* A `--no-pull-requests` flag has been added to prevent fetching PRs from GitHub.
Other things to handle here or in follow-up PRs:
* Distinguishing between formulae and casks with the same name (in the command output).
* Fetching all PRs first if required, to prevent GitHub API rate limiting.

dev-cmd/bump: add cask support

---

Library/Homebrew/env_config.rb
Library/Homebrew/formula_installer.rb
docs/Manpage.md
manpages/brew.1

- Remove `HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK` and make the behaviour the default. We mostly already do this since we added the need for the `--build-from-source` override on macOS. This allows us to delete some more code.
- Still fail and require `--build-from-source` when reinstalling or upgrading if failing on a formula-specific reason e.g. the CLT is not/no longer installed, you're using a non-default prefix.
Fixes #10623

Make HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK default

---

Library/Homebrew/shims/super/cc

-----
This pull request should fix a bug on Linux when attempting to use a newer `gcc` when the brewed `gcc@5` is installed and is linked into `$HOMEBREW_PREFIX/lib`.  The `determine_library_paths` method in `extend/ENV/super.rb` adds `$HOMEBREW_PREFIX/lib` to the list of the library paths, which results in `-L$HOMEBREW_PREFIX/lib` being add as a linker flag to the superenv.  This creates a problem when using newer of versions of `gcc`, because this flag causes the linker to use `$HOMEBREW_PREFIX/lib/libstdc++.so.6` and the other run time libraries from `gcc-5` instead of the versions of those libraries that come with newer version of `gcc` which we are trying to use.
This solution resolves this by inserting an additional linker flag for the directory which contains the runtime libraries …

cc: remove unneeded linker flag when building with GCC on Linux

---

Library/Homebrew/formulary.rb

-----
Fixes this `-W1` warning:
```
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47: warning: already initialized constant Formulary::FormulaNamespace05bf70582f35fd2a829a4b3b42cd7164
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47: warning: previous definition of FormulaNamespace05bf70582f35fd2a829a4b3b42cd7164 was here
```
Steps to reproduce:
```rb
Formula["hello"]
Formulary.clear_cache
Formula["hello"]
```

formulary: remove consts on cache clear

---

.github/workflows/tests.yml

`brew style` is OS independent so let's run all the `brew style` tests on Linux rather than macOS.

workflows/tests: move more macOS tests to Linux.

---

Library/Homebrew/shims/super/cc

-----
Unfortunately this commit needs to be reverted for now because of at least two problems:
1. The system GCC in CI uses (of course) the system GCC specs, which don’t add `-L$HOMEBREW_PREFIX/lib`.  ~~The test cases I used must have used `pkg-config` to find all their `LDFLAGS`, and built with no problems.  But formulae which don't do this will break.~~ In the tests I did I always had brewed gcc-5 installed because that was the cause of the conflict in the first place.  I never tested this using only the system GCC.
2. ~~What I said about the specs being added “invisibly” was almost certainly wrong - I ran `gcc-10 -dumpspecs` and the additional lines we add in post install aren’t there!  `strace` reveals that GCC is reading the right file, but I think it ignores the lines we’ve added …

cc: revert change to remove linker flag

---

Library/.rubocop.yml

-----
Using non-parenthesized regex arguments is a ruby warning with `-W2`. Adding parentheses was marked as a to-do item, so I figured I'd take care of it while working on reducing warnings.
I'm opening a homebrew/core PR to make the necessary changes there, and once that's merged through this should be good.

style: require parentheses around regex arguments

---

Library/Homebrew/download_strategy.rb

-----
Affects the test of the `container-structure-test` formula.

download_strategy: fix nounzip strategy ignoring block

---

Library/Homebrew/language/python.rb
Library/Homebrew/test/language/python/virtualenv_spec.rb

-----
`--no-user` is not a supported end-user flag in pip, and is explicitly non-documented: https://github.com/pypa/pip/issues/8977#issuecomment-706535089
https://github.com/pypa/pip/commit/87bb4f9c13d5a4f1c5b746670705ae044112f854
It was [added](https://github.com/Homebrew/brew/pull/10039) as part of building python packages from source in case a user's configuration specified `--user` installs due to the fact that you cannot do a `--user` install within a `venv`:
```
$ pip install --user foo
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
``` 
Recent versions of pip fall back to a user installation if site-packages is not writeable. Additionally, when building a formula, only the global and site pip configurations are looked at -- the …

python: stop passing no-user flag on installation

---

Library/.rubocop_rspec.yml
Library/Homebrew/test/download_strategies/curl_spec.rb
Library/Homebrew/test/os/linux/formula_spec.rb
Library/Homebrew/test/os/mac/formula_spec.rb

-----
- Inspired by my other RuboCop PR on Friday, here's another TODO dealt with.

rubocop: Enable RSpec/RepeatedExampleGroupDescription cop & fix offenses

---

Library/Homebrew/test/rubocops/bottle/bottle_format_spec.rb
Library/Homebrew/test/rubocops/text/option_declarations_spec.rb

-----
- After doing #10658, I moved onto other TODOs in that file. Enabling `RSpec/RepeatedDescription` momentarily revealed that two test descriptions had been copypasted between two similar, but not identical, tests. (Actually fixing the other offenses for that cop will be for another day!)

test/rubocops: Fix mismatched test descriptions

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/tests.yml

-----
After https://github.com/Homebrew/brew/pull/10650, there isn't a need to locally run `brew man` anymore, so this PR removes it from the Pull Request template.

PR template: remove local 'brew man' step now that it's scheduled

---

Library/Homebrew/cask/installer.rb
Library/Homebrew/cmd/uninstall.rb

-----
~~Similar to https://github.com/Homebrew/brew/pull/10284 and https://github.com/Homebrew/brew/pull/10398, this PR replaces `EnvConfig.cask_opts_` with `args.`~~
Delete references to unused `--binaries` flag

uninstall: delete references to unused `--binaries` flag

---

Library/Homebrew/test/utils/spdx_spec.rb
Library/Homebrew/utils/spdx.rb

- NOTE: ran `brew tests --online --only=utils/spdx`, not `brew tests`
-----
When running `brew audit --strict FORMULA`, it will warn you that a license is deprecated if it ends in a "+", even if it is not deprecated. When I tested an example from the [documentation](https://docs.brew.sh/License-Guidelines#complex-spdx-license-expressions) that was given as an example of a valid license (license "EPL-1.0+"), it was also showing this warning.
I found this over in https://github.com/Homebrew/homebrew-core/pull/71682, when I found that "MPL-1.1+" was incorrectly showing a deprecated SPDX license warning. Essentially, `valid_license?` in `utils/spdx.rb` removed the "+" suffix when checking for validity, but `deprecated_license?` did not, causing something like "MPL-1.1+" to be marked as valid …

utils/spdx: correctly detect non-deprecated licenses with plus

---

Library/Homebrew/cmd/info.rb

We should be able to provide info on casks even if installing
casks isn't supported on Linux.
https://github.com/Homebrew/discussions/discussions/891
-----

cmd/info: fix `brew info --cask` on Linux

---

Library/Homebrew/brew.sh
Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

- Enable it by default if you've run a developer command or set `HOMEBREW_DEVELOPER`.
- Clarify the documentation that there's various configuration in which it doesn't work.
I've rolled this out of most of GitHub's developers with no ill effects and we've enabled it in both CI and for various maintainers so it feels appropriate to have a bigger rollout. @Homebrew/brew: any thoughts?

Enable HOMEBREW_BOOTSNAP for developers

---

Library/Homebrew/dev-cmd/unbottled.rb
Library/Homebrew/extend/os/mac/utils/bottles.rb
Library/Homebrew/os/mac/xcode.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/utils/bottles.rb

-----
* Ignore bottles for older macOS versions
* Ignore disabled formulae
* Ignore formulae which can't build on the chosen macOS (due to `depends_on macos/xcode` constraints)
* Improve/fix sort description

dev-cmd/unbottled: various improvements

---

Library/Homebrew/dev-cmd/pr-upload.rb

-----
Fix a typo in `pr-upload` affecting Internet Archive. Not sure how this typo slipped in. Sigh

pr-upload: Fix a typo affecting Internet Archive

---

Library/Homebrew/homebrew_bootsnap.rb

Do a very basic developer tools check to ensure that we can compile things. We cannot use `DevelopmentTools.installed?` because this has much higher speed requirements and needs to be run before we `require` anything else.
CC @Bo98 who mentioned this

homebrew_bootsnap: require some developer tools.

---

Library/Homebrew/brew.sh
Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

Reverts Homebrew/brew#10680
This seems to be causing a lot of issues and I don't think dealing with these is worth it.

Revert "Enable HOMEBREW_BOOTSNAP for developers"

---

Library/Homebrew/dev-cmd/prof.rb

-----
The prof command does not currently work on Apple silicon
```
$ brew prof readall
Traceback (most recent call last):
7: from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/ruby-prof:23:in `<main>'
6: from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/ruby-prof:23:in `load'
5: from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/bin/ruby-prof:4:in `<top (required)>'
4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2: from /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/lib/ruby-prof.rb: …
```

dev-cmd/prof: prevent from running on Apple Silicon

---

Library/Homebrew/build.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/test/error_during_execution_spec.rb
Library/Homebrew/test/exceptions_spec.rb
Library/Homebrew/utils/fork.rb

-----
When `safe_fork` fails due to application termination rather than exist, `exitstatus` will be nil. Instead we should pass more of the object, as it has other methods like `termsig` for those cases. When you pass `ErrorDuringExecution` a `Process::Status` object, it will handle that and provide proper information on the failure, rather than choking because the passed exit status is nil.
It is unfortunately impossible to create a `Process::Status` object without using `Marshal.load`. There is no security risk though as this isn't user input.
Fixes #10661.

utils/fork: handle termsig in safe_fork

---

Library/Homebrew/brew.sh
Library/Homebrew/cmd/--prefix.rb
Library/Homebrew/prefix.sh
Library/Homebrew/test/cmd/--prefix_spec.rb
docs/Manpage.md
manpages/brew.1

This case is _really_ slow even although it's something we encourage people to run often and build systems often do. The `brew --prefix` case is really fast because it's just in Bash so: let's pull the `brew --prefix <formula>` case into Bash too.
This doesn't handle any edge-cases like `--installed` and the formula detection is pretty simple.
Also, to make this behaviour consistent, never output `Cellar` paths from the (Ruby) `brew --prefix`; we never want people relying on the Cellar paths anyway, only output them if the formula wasn't installed (where, arguably, using a Cellar path is even worse) and the speedup is worth this deviation in behaviour.
Benchmarks:
```console
$ hyperfine --min-runs=3 --warmup=1 "git checkout origin/master; brew --prefix" "git checkout speedup_brew_prefix; …
```

Speedup `brew --prefix <formula>`

---

Library/Homebrew/homebrew_bootsnap.rb
Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
Library/Homebrew/utils/gems.rb
Library/Homebrew/utils/gems.rbi

- further refactor nested conditional to make it clearer
- allow running on Linux while still excluding Apple Silicon
- only warn on `bundle install` failures

Improve Bootsnap behaviour

---

Library/Homebrew/env_config.rb
Library/Homebrew/software_spec.rb
docs/Manpage.md
manpages/brew.1

-----
Add HOMEBREW_BOTTLE_DEFAULT_DOMAIN to downloader mirror list if HOMEBREW_BOTTLE_DOMAIN is other than the default. The downloader may use the HOMEBREW_BOTTLE_DEFAULT_DOMAIN as a fallback option. (resolves #10660)

software_spec: Add HOMEBREW_BOTTLE_DEFAULT_DOMAIN as a fallback option

---

Library/Homebrew/test/utils/github_spec.rb
Library/Homebrew/utils/github.rb

-----
set default args to `def search_code` in `utils/github`

utils/github: set default args to search_code

---

Library/Homebrew/formula_auditor.rb

audit: pin glibc version to 2.23

---

.github/workflows/update-manpage.yml
Library/Homebrew/dev-cmd/man.rb

-----
This PR modifies the `--fail-if-changed` option in `brew man` to `--fail-if-not-changed` for two reasons:
* To maintain consistency with the `update-license-data` command
* The earlier option made sense when CI was supposed to detect if the contributor hadn't run `brew man` and committed the changes. Now that we've automated the process and removed the CI check, it would be good to change this functionality for use in the `update-manpage` workflow.

dev-cmd/man: modify '--fail-if-changed' to '--fail-if-not-changed'

---

Library/Homebrew/Gemfile
Library/Homebrew/Gemfile.lock
Library/Homebrew/brew.sh
Library/Homebrew/build.rb
Library/Homebrew/cleanup.rb
Library/Homebrew/config.rb
Library/Homebrew/dev-cmd/test.rb
Library/Homebrew/extend/ENV.rb
Library/Homebrew/extend/ENV/shared.rb
Library/Homebrew/extend/ENV/std.rb
Library/Homebrew/extend/ENV/super.rb
Library/Homebrew/extend/os/linux/extend/ENV/std.rb
Library/Homebrew/extend/os/linux/extend/ENV/super.rb
Library/Homebrew/extend/os/mac/extend/ENV/std.rb
Library/Homebrew/extend/os/mac/extend/ENV/super.rb
Library/Homebrew/formula_assertions.rb
Library/Homebrew/formula_info.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/global.rb
Library/Homebrew/homebrew_bootsnap.rb
Library/Homebrew/load_path.rb
Library/Homebrew/postinstall.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test.rb
Library/Homebrew/test/dev-cmd/test_spec.rb
Library/Homebrew/test/formula_info_spec.rb
Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Library/Homebrew/test/support/lib/config.rb
Library/Homebrew/utils/gems.rb
Library/Homebrew/utils/sorbet.rb

-----
This prevents random user-installed gems from breaking `brew` in various ways, including but not limited to:
* Broken native extensions of critical components, like `fileutils`, causing `brew` to not load. [#10520, #10684, many many discussions]
* Various warnings about user-installed gems that `brew` isn't responsible for. [#10649, #10675, #10688]
* Breaking-change updates of gems being used which `brew` has not been tested against. [#2984]
Prior discussion in #7681.

Prevent loading all non-Bundler gems

---

Library/Homebrew/formula_assertions.rb

There are some formulae using this method:
https://github.com/Homebrew/homebrew-core/search?q=assert_not_match&type=
-----

formula_assertions: add assert_not_match compat

---

Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Library/Homebrew/utils/gems.rb
Library/Homebrew/utils/rubocop.rb

-----
This prevents the ENV bleeding into child processes, such as system Ruby scripts invoked from formulae.

utils/gems: use Gem API rather than ENV to set paths

---

Library/Homebrew/formula_assertions.rb

-----
I think I've covered everything now.

formula_assertions: few more compat methods

---

Library/Homebrew/download_strategy.rb

-----
Now that 3.0.3 is released, let's add this comment.

download_strategy: add comment about Content-Disposition handling

---

Library/Homebrew/os/mac.rb

-----
I guess this makes `brew` sort of work on macOS 12 now.
```
Traceback (most recent call last):
14: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
13: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
12: from /usr/local/Homebrew/Library/Homebrew/global.rb:79:in `<top (required)>'
11: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
10: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
9: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_ …
```

os/mac: fix version error for prerelease macOS

---

Library/Homebrew/dev-cmd/tap-new.rb
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

- `--no-git` and `--branch` don't conflict as `--branch` is still used for the GitHub Actions branch even with `--no-git`
- fix some README markdown linting errors
- fix some YAML/GitHub Actions configuration linting errors

dev-cmd/tap-new: various tweaks.

---

Library/Homebrew/formula_installer.rb

-----
The linked_keg variable is referenced outside the block where it is defined; I think it should be the installed_keg variable.
I noticed this from a failing job in our CI system:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-one_liner-homebrew-amd64&build=1974)](https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/1974/) https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/1974/
~~~
Error: undefined method `/' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/tab.rb:111:in `for_keg'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:721:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:679:in …

formula_installer: fix typo in install_dependency

---

docs/Homebrew-and-Java.md

-----
Per the discussion at https://github.com/Homebrew/discussions/discussions/910, this PR adds a "Homebrew and Java" page that documents the use of `openjdk` or versioned alternatives by Java-based packages, as well as the ability to bring your own JDK by means of the `JAVA_HOME` environment variable.

Add initial documentation for Java-based packages

---

Library/Homebrew/brew.sh
bin/brew

-----
If `HOMEBREW_NO_ENV_FILTERING` is _not_ set, then `/usr/bin/env` already exports these. For consistency, we should be doing the same if `HOMEBREW_NO_ENV_FILTERING` is set.

Let bin/brew handle its own exporting

---

bin/brew

It's undocumented so we don't need to do the full deprecation dance here but let's give people a bit of a head up.

Deprecate HOMEBREW_NO_ENV_FILTERING

---

Library/Homebrew/rubocops/patches.rb
Library/Homebrew/test/rubocops/patches_spec.rb

-----
This PR adds autocorrection for some cops dealing with patches (this was marked as a TODO).
I'm still (i) checking if anything else can be autocorrected here (ii) working on tests for the autocorrection. Note: this PR will be affected by (or) affect #10760.

rubocops/patches: autocorrect some offenses

---

Library/Homebrew/extend/os/linux/keg_relocate.rb

This is only needed if we're not using `patchelf.rb`.
Partial fix for https://github.com/Homebrew/brew/issues/10784

linux/keg_relocate: patchelf dependency is conditional.

---

.github/workflows/tests.yml
Library/Homebrew/brew.sh
Library/Homebrew/env_config.rb
Library/Homebrew/extend/os/mac/software_spec.rb
Library/Homebrew/extend/os/on_os.rb
Library/Homebrew/extend/os/software_spec.rb
Library/Homebrew/formula_auditor.rb
Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
docs/Manpage.md
manpages/brew.1

-----
`brew audit` currently fails on macOS because `audit_deps` is not run on Linux and all auditing on homebrew-core is done on Linux.
This attempts to prevent that happening again by allowing the audit to run under `HOMEBREW_FORCE_HOMEBREW_ON_LINUX`.
This PR reverts 93362547c99d880e59d0e11f4127f01145ea5b1d which removed the conditional. This PR also restores a867e78f62c807b65ff4f80587d1a512252febf0 for `uses_for_macos` handling, with a fix for it not working due to the `:since` handling. In addition, I've added handling of `on_os` blocks.
To ensure this works, I've added a step to the Linux CI.
See: https://github.com/Homebrew/homebrew-core/pull/70826#issuecomment-789300223

Allow deps auditing to run on Linux via HOMEBREW_SIMULATE_MACOS_ON_LINUX

---

Library/Homebrew/formula_installer.rb

- ensure that `HOMEBREW_DEVELOPER` still fails when there's a bottle available but the `pour_bottle?` block fails. This is usually due to the CLT being missing (and it's removed on even patch macOS upgrades) so building from source without prompt is undesirable.
- require `--build-from-source` for dependencies that aren't already installed
- do these bottle checks before fetching dependencies (they were already done before fetching requested formulae)
Fixes #10729

formula_installer: tweak "no bottle available" logic.

---

Library/Homebrew/formula_installer.rb

-----
* Cache `compute_dependencies` calls so we don't recompute at fetch and install time.
* Avoid `compute_dependencies` calls in the `ignore_deps?` case.

formula_installer: reduce dependency expansion computations

---

Library/Homebrew/extend/os/mac/extend/ENV/super.rb
Library/Homebrew/shims/mac/super/sed

Mountain Lion isn't even supported by Homebrew anymore.
This shim hails back to Homebrew/legacy-homebrew#13787 @MikeMcQuaid
This gets picked up by `configure` scripts (which is fine during builds),
but occasionally gets [baked into binaries][fixincl], triggering:
Error: Files were found with references to the Homebrew shims directory.
This in turn causes tap maintainers to just override `SED=/usr/bin/sed` for
`configure`, which doesn't always work properly: osx-cross/homebrew-avr#230
Other instances:
* https://stackoverflow.com/questions/40357246/usr-local-library-homebrew-shims-super-sed-no-such-file-or-directory
* https://github.com/laruence/yaconf/issues/17
* https://github.com/Amar1729/homebrew-formulae/issues/1
* https://blog.logical-dice.com/articles/wp/295
[fixincl]: …

-Library/Homebrew/shims/mac/super/sed: causes more problems than what it purports to fix

---

Library/Homebrew/rubocops/uses_from_macos.rb

-----
`pcsc-lite` is keg-only on macOS because its functionality is provided by `PCSC.framework`.  However it is needed for some formula to build on Linux.  See https://github.com/Homebrew/homebrew-core/pull/72773 
cc @iMichka

add pcsc-lite to uses_from_macos

---

Library/Homebrew/rubocops/uses_from_macos.rb

macOS provides `/usr/lib/libsasl2.dylib`
-----
macOS Catalina 10.15 provides `/usr/lib/libsasl2.dylib`. I have not checked other versions of macOS.
See the companion PR https://github.com/Homebrew/homebrew-core/pull/72759 `cyrus-sasl 2.1.27 (new formula)`

rubocops: Permit uses_from_macos "cyrus-sasl"

---

Library/Homebrew/dev-cmd/test.rb
Library/Homebrew/utils/gems.rb
Library/Homebrew/utils/gems.rbi

-----
We call `Homebrew.install_bundler_gems!` during `brew test` now, so clearing these ENVs is now needed to ensure we aren't polluting the PATH with portable-ruby bin directories etc.

Don't touch PATH, GEM_HOME and GEM_PATH when testing formula

---

Library/Homebrew/prefix.sh
Library/Homebrew/test/cmd/--prefix_spec.rb

`find` should eliminate all `<formula>.rb` that are in a `Casks` directory. Fixes #10799.
Also fixes core formula shortcut path (missing a `Formula` path component).
Also fixes existing test ("errors if the given Formula doesn't exist" should _not_ pass `--installed`).

--prefix: shortlist only formulae

---

Library/Homebrew/cask/audit.rb

-----
Fixes weird audit error in https://github.com/Homebrew/homebrew-cask/pull/100975. Both adding `--compressed` as well as simply removing the user agent make `curl` succeed. Even simply removing the last `Safari ...` part from the user agent makes it succeed.
Formulae already check both user agents, so this also makes the check consistent.

Check homepage with both browser and default user agent.

---

Library/Homebrew/utils/github.rb
Library/Homebrew/utils/github/api.rb

-----
This PR aims to simplify GitHub REST API pagination.
I plan to open a follow-up PR to modify `fetch_pull_requests` to be able to retrieve all PRs from a Tap (this would be useful to pre-fetch PRs for `brew bump`). This would increase the number of methods that use pagination, so getting rid of the repetitive `(1..API_MAX_PAGES).each` loops seemed desirable.

utils/github/api: simplify pagination

---

Library/Homebrew/cask/cask_loader.rb
Library/Homebrew/cask/exceptions.rb
Library/Homebrew/cli/named_args.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/test/exceptions_spec.rb

-----
This PR aims to fix #10584, by removing auto-tapping from cask's `FromTapLoader`.
Output:
```
➜ brew info mongodb/brew/mongodb-community
Error: No available formula or cask with the name "mongodb/brew/mongodb-community".
Please tap it and then try again: brew tap mongodb/brew
➜ brew info --formula mongodb/brew/mongodb-community
Error: No available formula with the name "mongodb/brew/mongodb-community".
Please tap it and then try again: brew tap mongodb/brew
➜ brew info --cask mongodb/brew/mongodb-community
Error: Cask 'mongodb/brew/mongodb-community' is unavailable.
Please tap it and then try again: brew tap mongodb/brew
```

cask_loader: do not auto-tap in FromTapLoader

---

Library/Homebrew/dev-cmd/pr-upload.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/env_config.rb
Library/Homebrew/github_packages.rb
Library/Homebrew/software_spec.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

- Add support to `pr-upload` for GitHub Packages
- Support downloading bottles from GitHub Packages (with the correct `root_url`)

Support uploading and downloading bottles from GitHub packages

---

Library/Homebrew/formula_installer.rb

-----
This makes sure the `no bottle available!` error only appears on macOS versions we support.
Alternatively, we could add something like a `--recursive-build-from-source` flag to `brew install`, which will build dependents from source too.
Fixes #10832.

formula_installer: skip bottle check on old Macs

---

Library/Homebrew/cask/dsl.rb
Library/Homebrew/test/cask/audit_spec.rb

-----
See discussion: https://github.com/Homebrew/discussions/discussions/718
tl;dr: `url do...end` blocks currently can't handle options such as `:referrer` or `:cookies`

bugfix: Add args and options to lazy url block

---

Library/Homebrew/dev-cmd/bump.rb
Library/Homebrew/dev-cmd/livecheck.rb
Library/Homebrew/livecheck/livecheck.rb

-----
When running `livecheck` without the `--json` option, or `bump`, formulae and casks with the same name are indistinguishable in the output even when using `--full-name`, if they are from `homebrew-core` and `homebrew-cask`.
Example:
```
➜ brew livecheck volt homebrew/cask/volt --full-name
Warning: Treating volt as a formula. For the cask, use homebrew/cask/volt
volt : 0.3.7 ==> 0.3.7
volt : 0.80 ==> 0.87
```
It would be desirable to disambiguate names in such cases, unless the `--cask` option is explicitly given.
```
➜ brew livecheck homebrew/cask/volt volt                    
Warning: Treating volt as a formula. For the cask, use homebrew/cask/volt
volt (cask) : 0.80 ==> 0.87
volt : 0.3.7 ==> 0.3.7
```
I'm not sure if handling this in `livecheck` or `bump` is ideal, maybe we would …

livecheck and bump: formula/cask disambiguation

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/cmd/update.sh

-----
The output from brew update can be voluminous. To reduce what is reported, this pull request expands the `--quiet` checks in `update-report` and adds it to `update`. This follows up on https://github.com/Homebrew/brew/pull/10581#issuecomment-791670209 and seeks to partially address https://github.com/Homebrew/brew/issues/10609.

Expand quiet checks in update and update-report

---

Library/Homebrew/utils/pypi.rb

-----
When we used `virtualenv` for our Python virtual environments, the `wheel` resource from the `python@3.X` formula was pulled in automatically, so there was no need (or rarely a need) for `wheel` to be specified as a resource. Now that we use `python3 -m venv` for virtual environments, though, the `wheel` resource is no longer automatically installed in the virtual environment:
```console
$ python3 -m pip list
Package    Version
---------- -------
pip        21.0.1
setuptools 53.0.0
wheel      0.36.2
$ python3 -m venv venv
$ source venv/bin/activate
$ python3 -m pip list
Package    Version
---------- -------
pip        21.0.1
setuptools 53.0.0
```
For some more context into why `wheel` was added, see https://github.com/Homebrew/brew/pull/8059#discussion_r461064786 which points to …

update-python-resources: include wheel in resources

---

Library/Homebrew/language/python.rb

-----
The `homebrew-*` resources were used to separate resources needed for `virtualenv` from those defined in the formula. We don't use `virtualenv` anymore so there's no need to handle these differently anymore.

language/python: remove outdated "homebrew-" resource handling

---

Library/Homebrew/cask/pkg.rb
Library/Homebrew/test/cask/pkg_spec.rb

-----
Fixes a vulnerability that would allow attackers to gain write access while a directory's permissions are temporarily set to `777`.
This fix also brings a 2-7-fold speedup since all `rmdir`-related file operations are done in a single `sudo` call using a helper bash script.

Simplify package uninstallation.

---

Library/Homebrew/github_packages.rb
Library/Homebrew/software_spec.rb

This still worked but ended up always having a `/bottles-*/` part of the URL that was unnecessary when using `HOMEBREW_BOTTLE_DOMAIN`.
CC @sjackman who bumped into this.

github_packages: fix HOMEBREW_BOTTLE_DOMAIN usage.

---

Library/Homebrew/cask/pkg.rb

Unfortunately, the removal shell script introduced in #10860 does not handle paths very well that dont exist, e.g.
* [`find`](https://github.com/Homebrew/brew/pull/10860/files#diff-a8ad32ef9807334306b04d125710e7f0953b8dfbdc8435e0630509a5b939a340R120) runs before its `-exec` test, thus throws `find: "${path}": No such file or directory`
* it seem that [`/bin/rmdir`](https://github.com/Homebrew/brew/commit/1a4874dc6253f2eb2d077fbfc40ae88457a4ba40#diff-a8ad32ef9807334306b04d125710e7f0953b8dfbdc8435e0630509a5b939a340R130) is intended to break is certain cases, thus `-f` is not desired. so, if `${path}` does not exist, it'll still break, which is most likely not one of those cases.
This change reintroduces a check for existence. This way, it is ensured that there is actually a directory to be …

Fix broken rmdir script

---

Library/Homebrew/formula_creator.rb

-----
New versions of CMake know how to invoke the appropriate build tool
(i.e. `make` or `ninja`), so let's try to leave that to CMake.
This also builds out-of-tree, without having to deal with the `mkdir
"build" do` business.

formula_creator: use tool-agnostic cmake commands

---

Library/Homebrew/completions.rb
Library/Homebrew/test/completions_spec.rb
completions/zsh/_brew

-----
This PR aims to improve the ZSH completions.
Earlier, conflicts weren't handled:
```
➜ brew livecheck
zsh: do you wish to see all 9397 possibilities (4699 lines)?
➜ brew livecheck --formula
zsh: do you wish to see all 9397 possibilities (4699 lines)?
➜ brew livecheck --cask
zsh: do you wish to see all 9397 possibilities (4699 lines)?
```
Now:
```
➜ brew livecheck
zsh: do you wish to see all 9397 possibilities (4699 lines)?
➜ brew livecheck --formula
zsh: do you wish to see all 5541 possibilities (2771 lines)?
➜ brew livecheck --cask
zsh: do you wish to see all 3856 possibilities (1928 lines)?
```
Also, this fixes the problem of only one formula/cask/named argument being suggested despite a command being able to take multiple named arguments. However, it isn't smart enough yet (to …

completions: fix zsh autocompletion issues

---

.github/workflows/update-manpage.yml

-----
This PR aims to fix problems with the `update-manpage` workflow, as encountered in #10854. We should be using `git reset --hard origin/master` instead. Also replacing `git-try-push` as it does not do a `git push --force-with-lease` on the first try ([Bo98's comment](https://github.com/Homebrew/brew/pull/10854#issuecomment-799414425)).

workflows/update-manpage: fix issue

---

Library/Homebrew/formula_installer.rb

-----
If you `brew install --HEAD` then `brew reinstall` will remember that and reinstall the HEAD spec. We shouldn't warn about bottles in that scenario.

formula_installer: don't warn about bottles when active spec is HEAD

---

Library/Homebrew/cmd/gist-logs.rb
Library/Homebrew/cmd/log.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/language/node.rb
Library/Homebrew/os/linux.rb
Library/Homebrew/os/mac/xcode.rb
Library/Homebrew/rubocops.rb
Library/Homebrew/rubocops/lines.rb
Library/Homebrew/rubocops/shared/helper_functions.rb
Library/Homebrew/rubocops/shell_commands.rb
Library/Homebrew/test/language/node_spec.rb
Library/Homebrew/test/rubocops/shell_commands_spec.rb
Library/Homebrew/utils/github.rb

-----
This promotes the shell commands formula audit to a cop that can be applied to all Homebrew repositories, for security reasons.
Multiple arguments is the safer thing to do as it prevents shell injection exploits.
For example, the safety of `Utils.popen_read("git -C \"#{resource_path}\" rev-parse -q --verify HEAD")` depends solely on whether `resource_path` is trusted input - which I don't think it is as it is based on the download URL basename. One could potentially redirect a URL to one containing malicious shell code and trick a maintainer into running `brew bump-formula-pr`. Whether this is actually possible in practice is something I have not fully investigated - it's just best to make the code safe rather than depending on some behaviour in another place, and prevent new code …

Promote shell commands audit to global cop 

---

docs/Rename-A-Formula.md

brew audit --strict does not catch all the issues. The CI/CD uses "brew audit --online --new-formula" and is more thorough, catching e.g. "New formulae in homebrew/core should not have a 'bottle do'" which brew audit --strict does not.
(not applicable)
(not applicable)
(not applicable)
(not applicable)
-----
I [got got today when renaming a formula](https://github.com/Homebrew/homebrew-core/pull/73448#issuecomment-802402642). Even though `brew audit --strict` passed, the CI/CD uses `brew audit --online --new-formula`, which caught an issue that the former did not. Since the CI/CD uses the latter, the renaming docs should suggest the same.

Docs: brew audit --strict is not enough when renaming a formula

---

Library/Homebrew/utils/popen.rb

-----
`Utils.popen_read("brew", "deps", "cmake")` currently fails because it invokes an `opoo` and prints to `stderr`, causing a non-success exit code because printing to a closed `stderr` triggers a `EPIPE` (broken pipe) error.
Instead, redirect `stderr` to `/dev/null` so that it doesn't cause broken pipes.

utils/popen: redirect stderr to /dev/null rather than close

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/github_packages.rb

`skopeo` allows replacing `docker` and `oras` with a single tool that behaves in a way that's a little more intuitive for us (we build the directory structure on disk and upload that). It seems to be better at preserving our metadata, too.
Take the opportunity for writing out more metadata ourselves to split out more logic into separate functions.
While we're here, fix the `download_strategy` timeout handling for GitHub Packages.
https://github.com/orgs/Homebrew/packages/container/package/homebrew-core%2Flibev was created from this latest version.
Test download (on macOS Big Sur) with:
```console
$ rm -rf /Users/mike/Library/Caches/Homebrew/downloads/077309824b8bc095dd146c2a0ce7dd118a9777e0ff98bdd96dda791bc91e7995--libev-4.33.big_sur.bottle.tar.gz; …
```

github_packages: use skopeo.

---

Library/Homebrew/livecheck/strategy.rb
Library/Homebrew/livecheck/strategy/electron_builder.rb
Library/Homebrew/test/livecheck/strategy/electron_builder_spec.rb

-----
This PR adds an `ElectronBuilder` strategy for `livecheck`, to use with casks. It's been modelled based on the `Sparkle` strategy. If accepted, this PR will close #10866.
Update: The second commit modifies the `URL_MATCH_REGEX` to allow URLs pointing to `.atom` files, which seem to be supported by [`find-appcast`](https://github.com/Homebrew/homebrew-cask/blob/master/developer/bin/find-appcast). I'll remove this if it isn't supposed to be the case here.

livecheck/strategy: add ElectronBuilder strategy

---

Library/Homebrew/build.rb
Library/Homebrew/cask/cmd/audit.rb
Library/Homebrew/cli/args.rb
Library/Homebrew/cli/args.rbi
Library/Homebrew/cli/named_args.rb
Library/Homebrew/cli/parser.rb
Library/Homebrew/cmd/--env.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/outdated.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/test.rb
Library/Homebrew/formula_auditor.rb
Library/Homebrew/reinstall.rb
Library/Homebrew/test/cask/cmd/audit_spec.rb
Library/Homebrew/test/cli/named_args_spec.rb
Library/Homebrew/test/cli/parser_spec.rb
Library/Homebrew/upgrade.rb

-----
This implements stricter handling of CLI args by:
* Raising a NoMethodError if you call an arg method without the switch/flag being defined.
- This unveiled quite a few bugs of broken arg checks.
* Changing the switch semantics:
- Regular switches are now strictly boolean true/false, rather than being either true or nil.
- "Binary" (more like ternary) switch options (`--[no-]switch`) remain three-state: true, false or nil.
This required a number of changes elsewhere to do this. I suspect there will be more I've missed, and potentially some in other Homebrew repositories which the CI may flag.
Feel free to ask about any part of the changes and I can explain it better.

Stricter handling of CLI args

---

Library/Homebrew/dependencies.rbi
Library/Homebrew/dependencies_helpers.rb
Library/Homebrew/dependency.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/options.rb
Library/Homebrew/requirement.rb
Library/Homebrew/test/formula_spec.rb
Library/Homebrew/test/spec_helper.rb

-----
This adds opt-in caching to `Dependency.expand` and `Requirement.expand`.
This massively increases the speed of those functions, if a cache key is passed. I've adjusted `Formula#rescursive_dependencies` and `Formula#recursive_requirements` to do this if no block is passed.
This massively improves the `brew uses` runtime from ~40s on Linux to about 6s, with most of that remaining time now being the actual `Formula.to_a` file loading.
Care is needed when choosing a cache key - the block is not re-evaulated on cache hits and so the cache key should be constructed depending on what variables might require rerunning the block.
I tried to be careful to clear the cache where it might be necessary - hopefully I haven't missed an edge case.
If successful, this should also speed up the `test …

Implement caching for dependency expansion

---

Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/formula_installer.rb

-----
Responsibility of args should lie with the command itself. The args to check for here varied depending on whether it was an install, reinstall or upgrade.
If we want some sort of shared logic, I'd rather it was done in a more generic way - such as having some way to tag which options are "build flags" and iterating over those.
Fixes https://github.com/Homebrew/discussions/discussions/1104.

Remove FormulaInstaller.prevent_build_flags

---

Library/Homebrew/cmd/deps.rb
Library/Homebrew/cmd/uses.rb

Fix Cask handling in `brew deps` and `brew uses`.

---

Library/Homebrew/cask/audit.rb

-----
Some `livecheck`s work using the auto-detected strategy, but we don't have a way to *know* the difference between a missing `livecheck` block and implicitly using the auto-detected strategy.
For now, casks with an existing `appcast` are still skipped.

Make `livecheck` audit mandatory for versioned casks.

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/dev-cmd/bump.rb
Library/Homebrew/tap.rb
Library/Homebrew/test/tap_spec.rb
Library/Homebrew/utils/github.rb

-----
Fixes #10881
This PR adds a `Tap#remote_repo` method to extract the remote repository name from the tap remote url. This should be used instead of `Tap#full_name` for methods in the `Utils::GitHub` module so that those methods can be used on taps that use non-standard urls.

utils/github: handle non-standard tap remotes

---

.github/workflows/tests.yml
Library/Homebrew/cask/audit.rb
Library/Homebrew/cask/auditor.rb
Library/Homebrew/cask/cmd/audit.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/test/cask/cmd/audit_spec.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

-----
This PR changes how `brew audit` outputs cask audit summaries.
By default, `brew audit` will not output any `passed` messaging unless `--verbose` is passed or there was only one named argument. Warnings will still be shown.
If the `--display-failures-only` flag is passed, warnings will also be silenced.
I added the `--display-failures-only` flag to the `brew audit` calls in the `tests` workflow. I don't think there's a benefit to seeing the huge number of warnings in this situation. Warnings don't block CI here, so there's no point in showing them as it makes it harder to read when there are failures.

audit: limit non-failure cask output

---

Library/Homebrew/download_strategy.rb

-----
Follow up to #10922
I noticed that these were added separately in #10891 and should also be reverted before the new tag.

CurlGitHubPackagesDownloadStrategy: revert allowing timeouts

---

Library/Homebrew/extend/ENV/super.rb

-----
Building `automake` fails with `autoconf` 2.70+, when `autoconf` is used with
macOS `m4`. It therefore makes sense for `autoconf` to depend on brewed `m4`.
However, without the change proposed here, the setting of the `M4`
environment variable in superenv breaks the `automake` build.
Related: https://github.com/Homebrew/homebrew-core/pull/73797

extend/ENV/super: remove M4

---

Library/Homebrew/formula.rb

-----
I'm hoping to add ldflags to `std_go_args` in the near future. However there is a problem: multiple ldflags must be passed as one parameter.
In many formulae we have something like `*std_go_args, "-ldflags", ...`. If I were to add ldflags to `std_go_args` then they would be overriden by the later `-ldflags` in formulae, even if the individual flags don't overlap. The same applies vice versa if `std_go_args` comes after a formula's `-ldflags`.
This pull request paves the way to support adding ldflags to `std_go_args` by supporting a `ldflags` parameter.
Currently, this provides little value until I add some standard ldflags. But since I want to avoid breaking existing formulae builds for a few days, the plan I have is:
1. Add basic `ldflags` parameter to `std_go_args`.
2. Wait for …

formula: add ldflags parameter to std_go_args

---

Library/Homebrew/cli/named_args.rb

-----
Previously, `kegs` would be an empty array instead of raising an error, so an empty array of kegs would be found successfully instead of falling back to looking for a cask.

Fix `uninstall --force` for casks.

---

Library/Homebrew/formula_installer.rb

-----
Perhaps resolves some confusion in Homebrew/homebrew-core#73825.
The deprecation and disabled messages currently only print _after_ the dependencies and requirements have been satisfied. I think it's better to instead print them earlier, so we don't send people to install the `osxfuse` Cask to only later inform them that the formula is deprecated or disabled.

formula_installer: move deprecation/disabled checking earlier

---

.github/workflows/sorbet.yml
.github/workflows/spdx.yml
.github/workflows/update-manpage.yml
.github/workflows/vendor-gems.yml

-----
This PR enables commit signing for BrewTestBot in workflows, using the `setup-commit-signing` action. (See #10672)

workflows: enable commit signing for BrewTestBot

---

Library/Homebrew/test.rb

-----
`--debug` is interactive because it activates Debrew, so it's annoying to have that be under a time bomb.

test: don't apply timeout with --debug

---

Library/Homebrew/cask/artifact/abstract_uninstall.rb

-----
This PR fixes #10859.
The uninstall step (which happens before upgrading) may require the password too, so it wasn't the case that the password warning was shown after the prompt – it just wasn't shown before the uninstall step.

cask: add password warning for pkg uninstall

---

.github/workflows/tests.yml

-----
This is regularly broken and needs work to make it work offline only.

workflows/tests: disable cask-versions audit test

---

Library/Homebrew/cli/named_args.rb

-----
Revert https://github.com/Homebrew/brew/pull/10934 and also ignore `FormulaOrCaskUnavailableError` when `--force` is passed.

Fix `uninstall --force` for casks and still ignore non-existent formulae/casks.

---

Library/Homebrew/cmd/update-report.rb

-----
An additional `--quiet` check that excludes reporting of tagged releases and relevant online links. Revision changes are still reported. Builds on https://github.com/Homebrew/brew/pull/10844.

Add additional quiet check in update-report

---

Library/Homebrew/bundle_version.rb
Library/Homebrew/test/bundle_version_spec.rb

---
Fixes audit failure in https://github.com/Homebrew/homebrew-cask/pull/102748.

Fix `BundleVersion` comparison when one part is `nil`.

---

Library/Homebrew/dev-cmd/audit.rb

-----
delete the variable  `git` in `def audit` of `dev-cmd/audit`, because it was used only once.

dev-cmd/audit: delete one variable

---

Library/Homebrew/extend/pathname.rb
Library/Homebrew/formula_cellar_checks.rb
Library/Homebrew/test/formula_installer_spec.rb

-----
This PR adds a check with `brew audit` to check for empty files that were installed, resolving #10768. This takes the approach of warning through `brew audit` rather than automatically removing said files after installation.
There may still be some false positives. I'm open to feedback on how to reduce them (I currently have a "valid" list for names and extensions that can be ignored, which is certainly not comprehensive). For reference, [this is a list of errors I get](https://gist.github.com/kthchew/584d8f5cc561990454b852003afcf24d) related to this check when I run `brew audit` on all of my installed formulae.

audit: check for installed empty files

---

Library/Homebrew/formula.rb
Library/Homebrew/mktemp.rb

-----
By default it writes to `/private/var/tmp` (different directory to `/tmp`), which we don't clean.
Instead, let's move it into `.brew_home`, which will be inside our `Mktemp` directory.
Also, adjust `Mktemp` to handle directories with restricted permissions (bazel has a few directories like that). It now fixes the permission before traversing the directory, which ensures the entire directory tree is properly removed. This is a similar practice to what we do in `cleanup` and `homebrew-test-bot`.

formula: make bazel write to .brew_home

---

Library/Homebrew/shims/super/cc

-----
This makes the behaviour consistent to regular BFD `ld`.
This may or may not fix the issues noted [here](https://github.com/Homebrew/linuxbrew-core/pull/22742#issuecomment-808976914), but I believe this change is correct to make anyway. I see no reason why `ld` should be treated differently to `ld.gold`.

shims/super/cc: don't refurbish ld.gold args

---

Library/Homebrew/os/mac/xcode.rb

-----
Extracted from #10769.
The Clang version in the beta is currently `1205.0.22.6` which does not match the original regex.

os/mac/xcode: update Clang version parsing for CLT 12.5

---

Library/Homebrew/dev-cmd/pr-automerge.rb

-----
PRs labelled with this almost always contain changes that do not require disposing of old macOS bottles. In the rare cases where they don't, a `brew pr-publish` can still be performed.

dev-cmd/pr-automerge: skip automerge for "linux to homebrew-core" by default

---

Library/Homebrew/extend/ENV.rb

-----
Keys containing `passphrase` are sensitive, this PR modifies `extend/ENV.rb` to ensure this.

extend/ENV: make 'passphrase' sensitive

---

.gitignore
Library/Homebrew/download_strategy.rb
Library/Homebrew/github_packages.rb
Library/Homebrew/sorbet/rbi/todo.rbi
Library/Homebrew/utils/gems.rb

Instead of the deprecated json-schema.
Also:
- `utils/gems`: add dependencies to `LOAD_PATH`.
- `download_strategy`: use `GitHubPackages` constant.
- import fixes from #10947 and add `mediaType` comment.
- tweak package name (remove `homebrew-` prefix) and output URL when uploaded
Example uploaded package in https://github.com/orgs/Homebrew/packages/container/package/core/libev

github_packages: use json_schemer gem.

---

Library/Homebrew/extend/ENV/super.rb

-----
`[g]libtoolize` looks for `m4` using the environment variable `M4`. When
that isn't set, it looks for `m4` in `PATH`.
However, when `libtool` is a build dependency but `m4` is not, `m4` will
not be found in `PATH`. Since `M4` is currently not set in the
environment by superenv, this causes some builds to fail.
Closes https://github.com/Homebrew/homebrew-core/pull/73932.
See also #10921.

extend/ENV/super: set `M4` for `libtool`

---

Library/Homebrew/dev-cmd/pr-upload.rb
Library/Homebrew/github_packages.rb

Fix GitHub Packages for Linux and third-party taps.
- Copy all architecture images using `skopeo copy --all`
---
-----

pr-upload: Fix GitHub Packages for Linux and third-party taps

---

Library/Homebrew/cmd/list.rb

-----
This has the added benefit of making the indentation in the output of
`brew list` uniform between formulae and casks. Also, you can now do
`brew ls -l` rather than `brew ls -l --formula`.
~~One disadvantage to this is that `brew ls -l --cask`, for example, will
return an error. I'll have to look into fixing that.~~ Fix should be up shortly
once `brew tests` is done running.
Follow-up to #10899. See, in particular, https://github.com/Homebrew/brew/pull/10899#discussion_r598659321.

cmd/list: always use `ls` when no named args are passed

---

Library/Homebrew/cask/artifact/abstract_artifact.rb
Library/Homebrew/test/cask/cmd/uninstall_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-script-user-relative.rb

-----
**Changes Summary**
Allow Casks to use uninstall script path with `~` as an alias for `HOME`.
Originally discussed here: https://github.com/Homebrew/homebrew-cask/issues/99043#issuecomment-780233940
**Notes on Checks**
Cannot run `brew typecheck` on M1 Mac
Similarly, 1 failure in `brew tests` due to Rosetta layer
```console
expected "macOS 11.2, Rosetta, non-/usr/local" to include "macOS 11.2, non-/usr/local"
```
**Before Feature: New Testcase result `--only cask/cmd/uninstall`**
```console
Finished in 14.62 seconds (files took 1.99 seconds to load)
11 examples, 1 failure
Failed examples:
rspec ./test/cask/cmd/uninstall_spec.rb:103 # Cask::Cmd::Uninstall when Casks use script path with `~` as `HOME` can still uninstall them
11 examples, 1 failure
Took 17 seconds
Tests Failed
``` …

cask uninstall script: allow tilde expansion to '$HOME'

---

Library/Homebrew/formula_auditor.rb

-----
See https://github.com/Homebrew/homebrew-core/pull/73982
This allows the `all` keyword to be used instead of a version number in the allowlist. This will cause the audit to be ignored for all versions of the formula.
CC @carlocab and @tschoonj

audit: allow all minor versions in new gnome version scheme

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/cleanup.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/pr-upload.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/extend/pathname.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/formulary.rb
Library/Homebrew/github_packages.rb
Library/Homebrew/global.rb
Library/Homebrew/tab.rb
Library/Homebrew/test/tab_spec.rb
Library/Homebrew/utils/bottles.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

- Write a subset of the tab required for bottles as an annotation.
- Add option on new bottle creation to skip writing tab into bottle and instead add it (and other useful metadata) to bottle JSON.
- Read formula information and tab from bottle JSON.
- Write prettier JSON to disk.
- Don't write `HEAD` to tab; this duplicates `HOMEBREW_VERSION`.
- Allow `brew bottle` to use `--json` to generate JSON files from a local bottle file.

github_packages: write tab.

---

Library/Homebrew/github_packages.rb

Translate Homebrew tab.arch to OCI platform.architecture.
-----
OCI `platform.architecture` is a closed vocabulary, and x86-64 is called `amd64`.

github_packages: Translate tab.arch to OCI

---

Library/Homebrew/github_packages.rb

This custom type will allow better display in GitHub Packages.

github_packages: update mediaType.

---

.github/workflows/tests.yml

These are just too error-prone. They shouldn't be re-enabled until our CI is setup such that it's impossible for any changes to be merged into homebrew-cask if these are failing.

workflows/tests: remove cask taps audit.

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/pr-pull.rb
Library/Homebrew/dev-cmd/pr-upload.rb
Library/Homebrew/test/utils_spec.rb
Library/Homebrew/utils.rb

-----
This PR adds a `--committer` option to `brew bottle`, `brew pr-pull` and `brew pr-upload` to specify the committer name  and email address. The intention is to use this for `BrewTestBot` creating commits on CI, where the user dispatching the workflow is the commit author.

Allow specifying committer for some `dev-cmd`s

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/cask/dsl.rb
Library/Homebrew/cask/url.rb
Library/Homebrew/cask/url.rbi
Library/Homebrew/test/cask/audit_spec.rb

-----
Allows using nested `url do` blocks in order to allow fetching a chain of URLs for retrieving the final URL.
See https://github.com/Homebrew/homebrew-cask-versions/pull/10620 for examples.
Also, skip auditing URLs using `url do` unless running with `--online`.

Implement nested `url do` API.

---

Library/Homebrew/cmd/fetch.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/formulary.rb
Library/Homebrew/github_packages.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/utils/bottles.rb

- Simplify and improve the GitHub Packages bottle download logic to be more idiomatic (and allow easier removal if GitHub ever drops the special header requirement).
- Make use of the tabs uploaded to GitHub Packages manifests by downloading, parsing and installing them (based on the bottle checksum). This will allow adding `brew bottle --only-json-tab` in future to stop building tabs into our bottles (making them more reproducible as the e.g. timestamps in our current bottles guarantee non-reproducibility).
- `utils/bottles`: remove unused method
- `download_strategy`: fix whitespace.
For testing use `HOMEBREW_BOTTLE_DOMAIN=https://ghcr.io/v2/Homebrew/core brew fetch git-delta` and `HOMEBREW_BOTTLE_DOMAIN=https://ghcr.io/v2/Homebrew/core brew reinstall git-delta`.

GitHub Packages Tab download

---

Library/Homebrew/cmd/vendor-install.sh

Let's default to using GitHub for portable Ruby and fall back to Bintray (because Bintray is going away).

cmd/vendor-install: use GitHub for portable Ruby.

---

Library/Homebrew/github_packages.rb

> After merging this PR, we are unable to use `skopeo` to copy the resulting OCI image.
```console
$ brew pr-upload --no-commit --github-org=brewsci
…
Error: Failure while executing; `/usr/local/bin/skopeo copy --all oci:seqkit--0.15.0 docker://ghcr.io/brewsci/bio/seqkit:0.15.0` exited with 1. Here's the output:
Getting image list signatures
Copying 2 of 2 images in list
Copying image sha256:68fa14405fdf83b46275c18c66705a55456b8ba4294a97367164f9182000d3de (1/2)
time="2021-04-01T16:10:37-07:00" level=fatal msg="Error initializing image from source oci:seqkit--0.15.0:: unsupported docker v2s2 media type: \"\""
$ skopeo copy --all oci:seqkit--0.15.0 oci:seqkit--0.15.0.copy
Getting image list signatures
Copying 2 of 2 images in list
Copying image …
```

Revert "github_packages: update mediaType."

---

Library/Homebrew/github_packages.rb
Library/Homebrew/software_spec.rb

Rename `sh.brew.bottle.checksum` to `sh.brew.bottle.digest` for consistency with the OCI descriptor spec. See https://github.com/opencontainers/image-spec/blob/master/descriptor.md#properties

github_packages: Rename sh.brew.bottle.digest

---

Library/Homebrew/cask/denylist.rb
Library/Homebrew/test/cask/denylist_spec.rb

-----
See  [homebrew-cask#102986](https://github.com/Homebrew/homebrew-cask/pull/102986)
Since Audacity is no longer "too difficult to download programmatically", this hard block should be removed.

Remove Audacity block

---

docs/Common-Issues.md

-----
Some of my builds were failing, but it appeared not to be happening for others, so I reinstalled everything as a last-ditch effort to fix it.  This worked and if these instructions were here it would have saved me a day or two. I think they might help someone else trying to fix their install and mention a useful approach to debugging problems: look at the issues for similar projects.
My solution, however, is buried in the issues of other repositories. I think this may help people overcome other problems and would be useful to mention here. See:
<https://github.com/railwaycat/homebrew-emacsmacport/issues/237>
<https://github.com/d12frosted/homebrew-emacs-plus/issues/292#issuecomment-778648261>
A hint that reinstalling XCode might be overkill: …

Common-Issues.md: reinstallation instructions for localized build failures

---

.github/workflows/sorbet.yml
.github/workflows/spdx.yml

-----
We should be using `origin_branch` to avoid a repeat of #10981.

workflows/{sorbet,spdx}: use origin_branch with git-try-push

---

Library/Homebrew/github_packages.rb

Remove `mediaType: "application/vnd.docker.distribution.manifest.list.v2+json"`
previously needed for correct multi-arch display in GitHub Packages UI.
-----
The current image index is non-conforming, because they contain `mediaType: "application/vnd.docker.distribution.manifest.list.v2+json"`, whereas their actual `mediaType` is `application/vnd.oci.image.index.v1+json`.
See https://github.com/opencontainers/image-spec/blob/master/image-index.md#image-index-property-descriptions
`mediaType: "application/vnd.docker.distribution.manifest.list.v2+json"` was used as a workaround for a GitHub Packages display issue. See the comment below.

write_image_index: Remove Docker mediaType

---

Library/Homebrew/github_packages.rb

If `HOMEBREW_FORCE_HOMEBREW_ON_LINUX` is set then we don't want to try to `brew install` or it will try and install from source (which takes too long).

github_packages: odie on missing skopeo.

---

Library/Homebrew/extend/os/linux/development_tools.rb
Library/Homebrew/os/linux/glibc.rb

-----
I would like to include the Glibc version that was used to build the bottle on Linux, so that the end-user system can verify that it has a sufficient Glibc version installed (either provided by the host or brewed) to use that bottle.

build_info: Add glibc_version for Linux

---

Library/Homebrew/cask/pkg.rb
Library/Homebrew/cask/utils/rmdir.sh
Library/Homebrew/shims/linux/super/make
Library/Homebrew/shims/mac/super/ruby
Library/Homebrew/shims/mac/super/xcrun
Library/Homebrew/shims/scm/git
Library/Homebrew/shims/utils.sh
Library/Homebrew/style.rb
Library/Homebrew/test/cask/pkg_spec.rb

-----
Don't skip broken symlinks and check `-d` instead of `-e` to avoid calling `find` on non-directories.
Includes and closes https://github.com/Homebrew/brew/pull/10882.

Speed up `pkg` uninstallation and only call `find` on directories.

---

Library/Homebrew/development_tools.rb
Library/Homebrew/extend/os/linux/development_tools.rb
Library/Homebrew/github_packages.rb

-----
I would like to include the CPU family architecture that was targeted by the bottle, so that the end-user system can verify that it has a sufficient CPU to use that bottle.
Linux currently targets bottles at `core2`, but we may one day increase that requirement to for example make use of AVX instructions.
Bottles for macOS 10.14 Mojave and up for example target `nehalem`.
See https://github.com/Homebrew/brew/blob/e265664518ad8c2b99ff15694f5f8fc13705a56b/Library/Homebrew/extend/os/mac/hardware.rb#L7
and https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures
and https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

build_info: Add oldest_cpu_family

---

Library/Homebrew/github_packages.rb

-----
Add `"com.github.package.type": "homebrew_bottle"` to the image index annotations.
Add `sh.brew.tab` to the image manifest. The tab is needed to install the package using the SHA-256 of the single-architecture image. See for example the SHA-256 of the single-architecture images advertised under the `OS / Arch` tab of the multi-architecture image at https://github.com/orgs/brewsci/packages/container/package/bio/seqkit-mediatype-docker
Move CPU variant from `platform.variant` to `sh.brew.cpu.variant`. Setting `platform.variant` requires specifying the `--platform` option to the Docker client: `docker pull --platform=linux/amd64/core2`. That's useful if providing multiple images for `linux/amd64` for different CPU variants, but the default `linux/amd64` image should not have …

OCI annotation improvements and move platform.variant

---

docs/Homebrew-on-Linux.md

In very limited environments, Homebrew manual install fails with :
```
/root/.linuxbrew/Homebrew/Library/Homebrew/cmd/shellenv.sh: line 9: /bin/ps: No such file or directory
```
This has to be fixed by explicitly provisioning `ps` command on the system, since Brew 2.4.7 (see `c1666676`).
---
- ~~Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).~~
- ~~Have you successfully run `brew style` with your changes locally?~~
- ~~Have you successfully run `brew typecheck` with your changes locally?~~
- ~~Have you successfully run `brew tests` with your changes locally?~~
-----

doc: adds missing required `procps` package

---

Library/Homebrew/build.rb
Library/Homebrew/cxxstdlib.rb
Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/test/cxxstdlib_spec.rb

- remove usage on macOS as we don't care about it there
- don't error out on incompatibility but still store stdlib on Linux
- remove (now) unused methods
@Bo98 @sjackman @fxcoudert I believe this is what we discussed/agreed but if not: shout!

Cleanup use of CxxStdlib

---

Library/Homebrew/completions/zsh.erb
completions/zsh/_brew

-----
When we introduced the completion cache mechanism for zsh about 2 years ago, we needed the path to the installed Taps for checking if the current completion cache should be invalidated. This is the relevant code: https://github.com/Homebrew/brew/blob/0ec1f04e635276a530ce58c04702146a0f59f82c/completions/zsh/_brew#L50
But as you can see, the fallback value is hardcoded and often incorrect in more and more cases as users move to `/opt/homebrew`.
The `HOMEBREW_REPOSITORY` variable is automatically defined in Homebrew scripts, but not outside of those scripts, in particular during execution of shell autocompletion scripts. As a result, the fallback is incorrect if a user has moved to `/opt/homebrew`, and the cache is invalidated and recreated on each invocation, which is slow and defeats …

fix _brew completion default cache path

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/formula_auditor.rb
Library/Homebrew/github_packages.rb
Library/Homebrew/hardware.rb
Library/Homebrew/os.rb
Library/Homebrew/software_spec.rb

- `download_strategy`: only request image index JSON for downloading the manifest for the tab
- use a shared `OS` constant for the version of `glibc` we use in CI
- fix `skoepeo` typo
- ensure that blank hash values are deleted (again) rather than just `nil` ones
- use a shared `Hardware::CPU` constant for oldest CPU we're supporting/using on Intel 64-bit
- re-add comment to `software_spec`

GitHub Packages cleanup

---

docs/Acceptable-Casks.md

-----
[Audacity can now be supported](https://github.com/Homebrew/homebrew-cask/pull/102986).

acceptable casks: audacity no longer applies

---

Library/Homebrew/formula_auditor.rb
Library/Homebrew/github_packages.rb
Library/Homebrew/os.rb

-----
- Add constant `OS::CI_OS_VERSION`.
- Rename constant `OS::GLIBC_CI_VERSION` to `OS::CI_GLIBC_VERSION`.
See https://github.com/Homebrew/brew/pull/11013#discussion_r607078338

GHCR: Add constant OS::CI_OS_VERSION

---

.github/workflows/sorbet.yml
.github/workflows/spdx.yml
.github/workflows/triage-issues.yml
.github/workflows/triage.yml
.github/workflows/update-manpage.yml
.github/workflows/vendor-gems.yml

https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
This provides enough permissions for almost everything we want to do.
When it's not enough (e.g. for `brew update-maintainers`): generate a dedicated, repo-specific token for when increased scopes are needed and setup a new organisation-wide token on the new PAT format.
---
**This may well break things. If so: please do not revert this PR but specifically revert the workflow(s) token changes that are failing.**

Use GITHUB_TOKEN more consistently.

---

Library/Homebrew/dev-cmd/bottle.rb

Don't output the complex license object but instead use the same format we use for `Formula#to_hash`.

dev-cmd/bottle: fix license output.

---

Library/Homebrew/github_packages.rb
Library/Homebrew/mktemp.rb
Library/Homebrew/software_spec.rb

`@` cannot be used in Docker image names. Use `AT` instead (which we already use in class names so has some precedent).
Make `mktemp` consistent, too.

github_packages: fix versioned bottle names.

---

Library/Homebrew/github_packages.rb
Library/Homebrew/software_spec.rb

Some versions have `+` in them.

github_packages: remove invalid docker tag characters.

---

Library/Homebrew/github_packages.rb

Given https://github.com/Homebrew/linuxbrew-core/pull/22874 we no longer need/want to allow a `linuxbrew-` repository prefix.

github_packages: don't allow `linuxbrew-` prefix.

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/formulary.rb
Library/Homebrew/github_packages.rb

- replace invalid non-ASCII characters from the descriptions
- handle invalid macOS versions on attempting to load old formulae from old bottles
- let `rubocop` auto-remove a no-longer needed `rubocop:disable`
- fix `skopeo` credentials argument

More GitHub Packages bulk upload fixes

---

Library/Homebrew/github_packages.rb

We want this to fail so don't print out the (expected) `stderr` output.

github_packages: quiet `skopeo inspect`

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/test/cask/audit_spec.rb

-----
Fix audit failures for working livechecks when running without `--online`.

Only suggest adding `livecheck` it auto-detection fails.

---

docs/Acceptable-Casks.md

Removing a linebreak in an attempt to fix the third link on https://docs.brew.sh/Acceptable-Casks such that the web page links to https://docs.brew.sh/Taps instead of https://docs.brew.sh/Taps.md
-----

Documentation: Fix link on website

---

Library/Homebrew/download_strategy.rb

-----
```console
$ curl -H 'Authorization: Bearer' https://ghcr.io/v2/brewsci/bio/adam/blobs/sha256:f6d0f054e4c33368eda8f39b60b777fd0a5dc6df585b4e138edf08f5f072c86a
{"errors":[{"code":"UNAUTHORIZED","message":"authentication token not provided"}]}
$ curl -sL -H 'Authorization: Bearer QQ==' https://ghcr.io/v2/brewsci/bio/adam/blobs/sha256:f6d0f054e4c33368eda8f39b60b777fd0a5dc6df585b4e138edf08f5f072c86a | file -
/dev/stdin: gzip compressed data, was "adam-bottle.tar", last modified: Mon Mar 15 14:37:35 2021, from Unix
```

GHCR: Authorization bearer requires a token

---

.github/workflows/tests.yml
Library/Homebrew/dev-cmd/tests.rb

-----
cache `brew tests`(parallel tests) log on ci.
Fixes https://github.com/Homebrew/brew/issues/10507

cache parallel tests log on ci

---

Library/Homebrew/github_packages.rb

Needed for `picat` and `srmio`.

github_packages: rewrite more invalid versions.

---

Library/Homebrew/github_packages.rb
Library/Homebrew/software_spec.rb

After this `HOMEBREW_BOTTLE_DOMAIN=https://ghcr.io/v2/linuxbrew/core` will work as expected.
While we're here, do a bit of cleanup of constant usage; we don't want some of these leaking outside the `GitHubPackages` class.
In doing so `docker://` will continue to work for `ghcr.io` but won't work for arbitrary other Docker hosts; this isn't something we want to support yet.

Fix Linuxbrew URL handling

---

Library/Homebrew/brew.sh
Library/Homebrew/cmd/vendor-install.sh
Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

Now that all bottles (without existing `sha256` mismatches) have been uploaded to GitHub Packages make it the default download location.
Will give this a few days testing before we make a tag and make this default for everyone.
No migration has been done for Linuxbrew packages yet; those will be done after we have fully migrated over Homebrew.

Default download to GitHub Packages

---

Library/Homebrew/github_packages.rb

This is hardcoded to Homebrew but we've started uploading bottles to the Linuxbrew org.

github_packages: fix "Uploaded to" organisation.

---

Library/Homebrew/dev-cmd/tests.rb

-----
delete needless `" "` from a option of `parallel_args`  in `dev-cmd/tests`

tests: fix a option bug

---

Library/Homebrew/formula_auditor.rb

formula auditor: skip uses_from_macos audit for linux-only formula

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/unbottled.rb
Library/Homebrew/extend/os/mac/utils/bottles.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb
Library/Homebrew/utils/bottles.rb

Now that Bintray is going away we have:
- migrated to GitHub Packages (which is content-addressable storage)
- plan to migrate to `brew bottle --only-json-tab` which means we will sometimes generate bottles with identical checksums
- plan to migrate `bottle :unneeded` to be shared bottles (which reduces the need for `mirror`s , too)
This doesn't actually ever generate these bottles but does allow them to be manually created and poured.

Support `all: SHA256` bottles.

---

Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/service.rb
Library/Homebrew/test/formula_installer_spec.rb
Library/Homebrew/test/formula_spec.rb
Library/Homebrew/test/service_spec.rb

-----
This is a very rough first draft of an idea I've been thinking about for a while that might eventually one day allow services on linux.
EDIT: This would currently need something like this in a formula instead of the current plist blocks:
```
service do
arguments [ "#{HOMEBREW_PREFIX}/opt/beanstalkd/bin/beanstalkd" ]
error_path "#{HOMEBREW_PREFIX}/var/log/beanstalkd.error.log"
log_path "#{HOMEBREW_PREFIX}/var/log/beanstalkd.log"
working_dir "#{HOMEBREW_PREFIX}/var"
keep_alive true
run_at_load true
end
```

formula: allow plists to be generated

---

Library/Homebrew/cask/cmd/info.rb
Library/Homebrew/cask/cmd/list.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/outdated.rb
Library/Homebrew/cmd/tap-info.rb
Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
Library/Homebrew/formula.rb
Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/cask/cmd/list_spec.rb
Library/Homebrew/test/cmd/outdated_spec.rb
Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Library/Homebrew/utils/github/api.rb

- remove `cellar` because it's no longer global
- remove `prefix` because it's no longer customisable
- add `cellar` for each bottle tag
- fix `url` for GitHub Packages. This will fix the formulae.brew.sh URLs being broken (https://formulae.brew.sh/api/formula/hello.json)
- Use `JSON.pretty_generate` globally as it's dramatically more human readable for very little difference in space (and we've used it a few other places already)

`Formula#bottle_hash`: various fixes/updates.

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/formula.rb
Library/Homebrew/software_spec.rb

They don't need escaped like the Bintray ones did.
Fixes https://github.com/Homebrew/brew/issues/11090 (but note this may require the cache entry to be cleared and the package to be redownloaded).

Fix GitHub Packages filenames.

---

Library/Homebrew/software_spec.rb

-----
Before:
```
➜ brew reinstall asciiquarium
"asciiquarium--1.1_1.catalina.bottle.tar.gz"
==> Downloading https://ghcr.io/v2/homebrew/core/asciiquarium/manifests/1.1_1
Already downloaded: /Users/nanda/Library/Caches/Homebrew/downloads/38390234a9d3a8145387f34a82fb783681260f9acf16ff6b37314ab95e4471d1--asciiquarium-1.1_1.bottle_manifest.json
"asciiquarium--1.1_1.catalina.bottle.tar.gz"
==> Downloading https://ghcr.io/v2/homebrew/core/asciiquarium/blobs/sha256:9bf092861aad33c28e8f7
Already downloaded: /Users/nanda/Library/Caches/Homebrew/downloads/6de61a44e803723a045e349e55211e67d5bb4e69efd59ea0c771cb2b126b8f96--asciiquarium--1.1_1.catalina.bottle.tar.gz
==> Reinstalling asciiquarium
"asciiquarium--1.1_1.catalina.bottle.tar.gz"
==> Pouring asciiquarium--1.1_1.catalina.bottle.tar.gz …
```

software_spec: remove debug statement

---

Library/Homebrew/completions/zsh.erb

-----
Now, `brew search` requires a text or regex argument. The `__brew_casks()` completion function was using `brew search --cask` to build a list of casks, resulting in errors like this (when trying to regenerate the cache for e.g. after `brew up`):
```
brew install asciiUsage: brew search, -S [options] text|/regex/ [...]
Perform a substring search of cask tokens and formula names for text. If
text is flanked by slashes, it is interpreted as a regular expression. The
search for text is extended online to homebrew/core and homebrew/cask.
--formula, --formulae        Search online and locally for formulae.
--cask, --casks              Search online and locally for casks.
--desc                       Search for formulae with a description
matching text and casks with a name
matching text. …
```

completions/zsh: fix `__brew_casks()`

---

Library/Homebrew/dev-cmd/pr-upload.rb
Library/Homebrew/github_packages.rb

-----
We need this to support any sort of workflow for adding bottles to an existing tag, including `brew dispatch-build-bottle`.

github_packages: support --keep-old

---

Library/Homebrew/bintray.rb

-----
In #11092, the `filename` was changed to use the one from GitHub Packages, but the logic in Bintray wasn't updated to reflect this. As a result, bottle downloads are failing as reported in Homebrew/homebrew-core#74878. Here's a [run](https://github.com/Homebrew/homebrew-core/runs/2307931714?check_suite_focus=true) showing the filenames used. I'm assuming formulae updated within the last ~3 hours would have to be rebottled.
I'm unsure if anything's wrong here, please feel free to commit to this branch if this is incorrect.

bintray: fix filename for bottle uploads

---

Library/Homebrew/dev-cmd/bottle.rb

Fixes:
Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Fix the error message:
`brew style --fix` does nothing for this issue
-----

bottle: no need to set cellar anymore

---

Library/Homebrew/dev-cmd/bottle.rb

-----
`BottleSpecification#cellar` returns the Cellar for the host OS, and this information will not exist if we are dealing with a bottle for another OS version. This leads to the default prefix always being used, which is incorrect behaviour.
This led to Cellar mismatch errors when uploading with `--keep-old` with the bottle block already written as `:any` or `:any_skip_relocation`. I don't know what further impacts this may have had, if any.
To fix the issue, I've used the `bottle_cellar` local variable which had already been prepared with the correct information.

dev-cmd/bottle: fix incorrect Cellar value in JSON

---

Library/Homebrew/dev-cmd/bottle.rb

-----
The fix for #11090 in bd3f1d2 changed the bottle json content but the downloader still expects bottles at the old location.
Bottle publishers that are using the dev-cmd/bottle json to publish to bintray-like repositories are getting the wrong file path.

bottle: Restore old filename for non-GitHub package URLs

---

Library/Homebrew/formula_installer.rb

-----
This caused cleanup to be run on latest versions of formulae that had a version scheme set.

formula_installer: fix version scheme not being set in the tab

---

Library/Homebrew/software_spec.rb

- assign the `version` for the `resource` before the `downloader` is created
- fix the reference to `Bintray`

software_spec: GitHub Packages/Bintray fixes.

---

.github/workflows/doctor.yml
Library/Homebrew/dev-cmd/dispatch-build-bottle.rb

Update Big Sur runner labels

---

Library/Homebrew/brew.sh

-----
When running a preinstall update, the envs from the previous brew instance are inherited. Since `HOMEBREW_BOTTLE_DOMAIN` is guaranteed to be set at this point due to the block of code I have now removed, the new updated brew instance will inherit this and see it as a custom domain.
Setting it here is however unnecessary. `EnvConfig` has its own default system which we can use. It is already set up to default to `HOMEBREW_BOTTLE_DEFAULT_DOMAIN`.
Unfortunately, this won't do anything to help those who are updating from old versions, since the env is set prior to the update. Only some custom handling would help combat that.
Partially fixes #11123.

brew.sh: remove problematic HOMEBREW_BOTTLE_DOMAIN export

---

Library/Homebrew/dev-cmd/tap-new.rb

-----
Fixes #11121.
Before:
```
➜ brew tap-new this/isn.tvalid
Error: undefined local variable or method `tap_name' for Homebrew:Module
/usr/local/Homebrew/Library/Homebrew/dev-cmd/tap-new.rb:39:in `tap_new'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```
After:
```
➜ brew tap-new this/isn.tvalid
Error: Invalid tap name 'this/isn.tvalid'
```

tap-new: fix invalid tap name message

---

Library/Homebrew/formula.rb

-----
This PR is to fix a bug in this previous PR:
https://github.com/Homebrew/brew/pull/11092
With bottles not hosted on GitHub (e.g. third-party taps and their own hosting solutions), the output from `brew info --json=v1 <formula>` has incorrect values for the bottle file URLs. Example:
```
...
"bottle": {
"stable": {
"rebuild": 0,
"root_url": "https://<domain>/homebrew/bottles",
"files": {
"catalina": {
"cellar": "/usr/local/Cellar",
"url": "https://<domain>/homebrew/bottles/",
"sha256": "..."
}
}
}
},
...
```
This still should function correctly for the GitHub case due to the function it is calling having a special conditional specifically for the GitHub case:
https://github.com/Homebrew/brew/blob/d81a047544c431ab733f21d8ebd028a44341bfa6/Library/Homebrew/software_spec.rb#L456

Fix regression with bottle URLs in `brew info` JSON output

---

bin/brew

-----
repair a comment of when we set `CI` in `bin/brew` because  we use `GitHub Actions`

bin/brew: add GitHub Actions as default ci

---

Library/Homebrew/.simplecov

-----
delete `SimpleCov::add_not_loaded_files` because of private method and repair `.simplecov`

.simplecov: delete private method

---

Library/Homebrew/cask/utils.rb
Library/Homebrew/dev-cmd/create.rb
Library/Homebrew/test/dev-cmd/create_spec.rb

-----
When creating cask definitions with `brew create`, use the `--set-name` argument for the `name` and automatically generate the `token` from it according to the [docs](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#converting-the-simplified-name-to-a-token), as implied by the current command documentation.
Also, drop `x86_64` before detecting the version number, which can be mistakenly caught by [this line](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/version.rb#L413).

create: improve cask token & version generation

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/pr-upload.rb

-----
`IO.read` can allow arbitrary command execution. Since we know we only want to read files, `File.read` is safer here for security.
The usage of `IO.read` in the cases here weren't particularly exploitable - they mostly required there to be JSON files in the working directory with maliciously crafted filenames. Not knowing what's in your working directory when running `brew pr-upload` or `brew bottle --merge` isn't a situation I expect anyone to ever be in and it would require some extreme levels of social engineering to trick someone into thinking a funky looking JSON file is ok. A formula file with a maliciously crafted name should also never get any further than the CI, where exploits have negligible impact due to the fact you can just run arbitrary Ruby code.

Use File.read over IO.read

---

.github/workflows/tests.yml
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/utils/bottles.rb

- test them in `brew test-bot` (before we do so in homebrew/core)
- don't fail if we cannot find the tab/install receipt in a bottle
- cache listing the files in a bottle so we don't do it more times than necessary
- fix resolution of version and formula names from a bottle if we're getting them from a bottle without a tab/install receipt
This will need to be in a tagged release before we can ship tab-less bottles to users.

Better handle `brew bottle --only-json-tab` bottles

---

Library/Homebrew/dev-cmd/bottle.rb

-----
Because `INSTALL_RECEIPT.json` can get rewritten in `Keg#replace_locations_with_placeholders`, it can appear in the `changed_files` section of the tab.
This causes errors when pouring bottles without this file present (`--only-json-tab`).

dev-cmd/bottle: fix INSTALL_RECEIPT appearing in changed_files

---

Library/Homebrew/settings.rb

`safe_system` always outputs what it's running which isn't necessary in this case.

settings: use quieter `system_command!`

---

Library/Homebrew/build.rb

-----
https://reproducible-builds.org/docs/source-date-epoch/
This allows more reproducible builds by using a standardised environment variable to set the build date/time.
This env is set to the timestamp of the last git commit to the formula file, or the file's mtime if we don't have a tap.

build: set SOURCE_DATE_EPOCH

---

Library/Homebrew/formula.rb
Library/Homebrew/resource.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/utils/bottles.rb

-----
If we are using a non-GHCR `HOMEBREW_BOTTLE_DOMAIN`, then we can't use the download strategy `mirror` system as the URLs etc will all be different.
Instead we have to catch the error and reconstruct the URL before sending another fetch.

software_spec: fix bottle domain fallback handling

---

Library/Homebrew/livecheck/strategy/sparkle.rb

-----
Always take the first (i.e. latest) item. From what I've seen it is more likely that the `BundleVersion#version` (most often build number) of an older item is higher rather than a newer item being for a legitimate older version (i.e. a patch update for a previous major version).

Always take first item in `Sparkle` strategy.

---

Library/Homebrew/brew.sh

-----
While we fixed the cause of the bug in 3.1.2, we unfortunately need to add this workaround if we want to actually fix the problem for those updating from <3.1.2.
The bug was caused because auto-update passes envs from the old instance into the new instance, including both `$HOMEBREW_BOTTLE_DOMAIN` and `$HOMEBREW_BOTTLE_DEFAULT_DOMAIN`. At this point `$HOMEBREW_BOTTLE_DOMAIN` will have been set to `$HOMEBREW_BOTTLE_DEFAULT_DOMAIN` or the user's provided value. Brew 3.1.2 adjusted this so the former case never happens.
This PR adds a check for this case to handle old auto-updates, that is if the passed `$HOMEBREW_BOTTLE_DOMAIN` is equal to the passed `$HOMEBREW_BOTTLE_DEFAULT_DOMAIN`, and unsets `$HOMEBREW_BOTTLE_DOMAIN` in that scenario.
This workaround applies to anyone updating …

brew.sh: add workaround for old auto-updates

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/test/unpack_strategy_spec.rb
Library/Homebrew/unpack_strategy/tar.rb
Library/Homebrew/utils/bottles.rb
Library/Homebrew/utils/tar.rb

- `dev-cmd/bottle`: improve reproducibility and add more comments explaining what's being done. Setting a consistent owner/group results in more consistent bottles.
- Use long/readable `tar` flags consistently.
- `utils/bottles`: tweak/improve some of the API.
- `bottle`: remove GitHub Packages bulk upload logic.

Bottle reproducibility tweaks

---

Library/Homebrew/dev-cmd/bottle.rb

-----
If this causes any issues in GitHub Packages, it should be fixed elsewhere to use `local_filename`. I don't see anything that would break though.
Fixes #11136.

dev-cmd/bottle: revert filename in JSON to use single dash always

---

Library/Homebrew/dev-cmd/bottle.rb

`--uid` doesn't exist on old BSD tar e.g. Mojave and below.
Reverts Homebrew/brew#11165

Revert "dev-cmd/bottle: set uid/gid."

---

Library/Homebrew/rubocops/patches.rb

-----
- The autocorrections here before (from #10777) were leading to changes like:
```
➜ brew style --fix brewsci/science/beetl
Formula/beetl.rb:15:11: C: [Corrected] GitHub patches should use the full_index parameter: https://github.com/BEETL/BEETL/commit/ba47b6f9.patch?full_index=1
url "https://github.com/BEETL/BEETL/commit/ba47b6f9.patch"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
➜ git diff
diff --git a/Formula/beetl.rb b/Formula/beetl.rb
index bbd049aa..7ec6d7bc 100644
--- a/Formula/beetl.rb
+++ b/Formula/beetl.rb
@@ -12,7 +12,7 @@ class Beetl < Formula
patch do
-      url "https://github.com/BEETL/BEETL/commit/ba47b6f9.patch"
+      url https://github.com/BEETL/BEETL/commit/ba47b6f9.patch?full_index=1
sha256 "63b67f3282893d1f74c66aa98f3bf2684aaba2fa9ce77858427b519f1f0280 …
```

rubocops/patches: Fix quoting of the patch `url` when autocorrecting

---

Library/Homebrew/livecheck/strategy/sparkle.rb

-----
The first item is not necessarily the latest, so sort the items by date first. Secondly, sort by version in case some versions were released at the same time.
Fixes breakage introduced by https://github.com/Homebrew/brew/pull/11146.

Always take latest item in `Sparkle` strategy.

---

Library/Homebrew/rubocops/patches.rb

-----
This PR removes the autocorrection added for some patch `url`s in #10777 until we have a method of also updating the `sha256`s.

rubocops/patches: remove autocorrection of some `url`s

---

Library/Homebrew/rubocops/patches.rb
Library/Homebrew/test/rubocops/patches_spec.rb

Only `.diff` URLs return output comparable to the diffs from `git diff --full-index`. While the extra metadata from `.patch` is nice, the instability of the patch contents is undesirable. This has caused issues with patch contents changing over time, for example in https://github.com/Homebrew/homebrew-core/issues/43156 and https://github.com/Homebrew/homebrew-core/pull/72297.
I'll coordinate getting this into homebrew/core and linuxbrew/core but it will take a little while.
-----

rubocops/patches: GitLab patches should use .diff

---

Library/Homebrew/cmd/search.rb
docs/Manpage.md
manpages/brew.1

-----
`brew search`, `brew search --formula`, and `brew search --formula --cask` without any named arguments were properly deprecated, disabled, and removed (removal happened in #11075). However, `brew search --cask` on its own never displayed any message warning that it would be removed. In version 3.1.0, it was removed and hasn't worked since. However, there was a discussion opened recently (https://github.com/Homebrew/discussions/discussions/1303) where a user wasn't aware of the breaking change.
Since this has already been broken since 3.1.0, I opted to deprecate immediately so we can remove it sooner. I wouldn't be opposed to disabling it in this PR, instead, as it's already not functional (just with a less clear error message and no instructions that point to `brew casks`).

search: properly deprecate `brew search --cask`

---

Library/Homebrew/extend/os/linux/formula.rb
Library/Homebrew/formula.rb

-----
About 40 formulae set `CMAKE_INSTALL_RPATH` to `lib` or `opt_lib`, but
this breaks bottle relocatability.
The correct solution is to use `@loader_path/../lib`, but this is macOS
specific, so it requires some OS-specific logic. Rather than replicating
this logic over many formulae, we may as well define a helper method for
it.
See https://github.com/Homebrew/homebrew-core/issues/75458.

formula: add rpath helper method

---

.github/workflows/tests.yml

-----
We currently run `brew style homebrew/core` twice in the `tap syntax (Linux)` workflow, but both times the Homebrew/linuxbrew-core repo is checked. THis PR adds `HOMEBREW_SIMULATE_MACOS_ON_LINUX=1` to the second `brew style` call so that Homebrew/homebrew-core is checked.

workflows/tests: simulate macOS for `brew style homebrew-core`

---

.github/workflows/tests.yml

@MikeMcQuaid this should fix the issue from https://github.com/Homebrew/brew/pull/11167#issuecomment-823488919
This change will bump the Codecov action from `1.4.0` to `1.4.1`
-----

Bump Codecov action to 1.4.1

---

Library/Homebrew/rubocops/patches.rb
Library/Homebrew/test/rubocops/patches_spec.rb

-----
Follow up to https://github.com/Homebrew/brew/pull/10760
This PR re-enables the GitLab patch URL check. This will need to wait to be merged until https://github.com/Homebrew/homebrew-core/pull/74023 and https://github.com/Homebrew/linuxbrew-core/pull/22752 are merged.

style: re-enable GitLab patch URL check

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

-----
`issue_body` is now an invalid key (in favour of using WYSIWYG `textarea`s). So `issue_body: false` needs to be removed completely in order for the forms to work 🤗.
> <img width="351" alt="Screenshot 2021-04-20 at 17 03 52" src="https://user-images.githubusercontent.com/1469659/115429464-55022800-a1fb-11eb-8c91-99b3d34f0da5.png">

Remove `issue_body` from YAML issue forms

---

Library/Homebrew/shims/mac/super/pod2man

This shim was originally added in 5c973bad7422cf7f335e952a91ddfa2273aa2e4f to workaround a missing
`/usr/bin/pod2man`. It's now unfortunately resulting in using an older `pod2man` on newer macOS versions.
Instead, let's use `/usr/bin/pod2man` if it's available and, if not, work backwards to find the newest available version that is available.

pod2man: use newer pod2man.

---

Library/Homebrew/shims/mac/super/pod2man

- prioritise the first `pod2man` in the `PATH` if possible. This shim was created to handle the case where there isn't one but, if there is, we want to allow e.g. using a `pod2man` dependency to override the use of the system version
- make `/usr/bin/pod2man` lower priority but still prioritise it over a Homebrew-installed `pod2man` that's not in the `PATH` unless it doesn't exist.

pod2man: further tweak logic.

---

Library/Homebrew/brew.sh
Library/Homebrew/cmd/casks.sh
Library/Homebrew/cmd/formulae.sh
Library/Homebrew/cmd/update.sh
Library/Homebrew/cmd/vendor-install.sh
Library/Homebrew/dev-cmd/rubocop.sh
Library/Homebrew/shims/mac/super/ruby
Library/Homebrew/shims/scm/git
Library/Homebrew/style.rb
bin/brew

A new version of `shellcheck` (I think?) brought us so new warnings and errors.
To fix:
- pass `--source-path` so we don't need to stop `shellcheck` trying to read sourced files every time
- disable some more warnings/errors we don't care about fixing

Fix shellcheck failures

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/formula_auditor.rb
Library/Homebrew/resource_auditor.rb
Library/Homebrew/utils/curl.rb

-----
Implements https://github.com/Homebrew/brew/issues/11183 (CC @cdayjr). The two new messages are (for example):
```
❯ brew audit --online some-test-formula
some-test-formula:
* The homepage URL https://example.com/some-nonexistent-homepage is not reachable (HTTP status code 404)
* Stable: The zip/tarball URL https://example.com/some-nonexistent-thing/unknown-0.1.tar.gz is not reachable (HTTP status code 404)
```
(formerly did not mention "homepage" or "zip/tarball")

audit: specify which URL has a content problem in problem message

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/pr-upload.rb

Generate `all: $SHA256` bottles if:
- all generated bottles have the same cellar
- all generated bottles have the same checksum
In this case, on `brew bottle --merge --write`: delete all the non-`all` bottles (and their JSON) and upload only the single one that's necessary.

dev-cmd/{bottle,pr-upload}: generate, upload `all: $SHA256` bottles.

---

.github/workflows/tests.yml
Library/Homebrew/commands.rb
Library/Homebrew/official_taps.rb
docs/Manpage.md
manpages/brew.1

Make `brew alias`, `brew autoupdate` and `brew command-not-found-init` official commands. This means we:
- make sure we don't break their style with `brew style` changes
- autotap them when you run the command and they aren't installed
- include them in the manpage
CC @bfontaine and @DomT4 for your 👍🏻 (don't want to do it without) and @Homebrew/maintainers for general thoughts.
This would also solidify the "external command taps in the @Homebrew org are official external commands" loose policy (with the exceptions being homebrew/formula-analytics,homebrew/portable-ruby and `brew homebrew/linux-dev which no users and most maintainers shouldn't care about)

More official Homebrew taps

---

Library/Homebrew/settings.rb

-----
This often happens when running multiple dev commands in parallel since it tries to lock the `.git/config` file, so check if the current value is already correct.

Avoid “Failure while executing; `git config --replace-all homebrew.devcmdrun true` exited with 255.” error.

---

.github/workflows/tests.yml

Make more of the longer (i.e. >5m) jobs require the `syntax` job to have completed. These jobs are so much quicker than the macOS job so that this will not slow down the overall CI run while avoiding the run of some jobs if `syntax` fails.

github/workflows/tests: add more `needs: syntax`

---

Library/Homebrew/cmd/update-reset.sh

update-reset.sh: Fix `shellcheck` style errors

---

Library/Homebrew/cmd/vendor-install.sh

-----
related https://github.com/Homebrew/brew/pull/11178

Vendor install.sh bash style fixes

---

Library/Homebrew/dev-cmd/unbottled.rb

-----
In #11077 (more specifically 6b5213286c389abe2706e67c1a60f0c9ed376ddd), the `exact:` keyword argument was renamed to `no_older_versions:`. However, we didn't rename every place that used it, and this broke the `brew unbottled` command.

Unbottled: fix use of invalid argument

---

Library/Homebrew/formula_cellar_checks.rb
Library/Homebrew/service.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb
Library/Homebrew/test/service_spec.rb

Audit: make sure service commands exist

---

Library/Homebrew/upgrade.rb

-----
`build_from_source_formulae` is a list of `full_name` strings.

upgrade: fix broken dependents never being built from source

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/pr-upload.rb

This should make it easier to debug `all:` bottle upload failures.
While we're here, remove the weird `_` that ended up at the end of a method name.

dev-cmd: add more --verbose bottle, pr-upload output.

---

Library/Homebrew/completions.rb
Library/Homebrew/test/completions_spec.rb
completions/fish/brew.fish
docs/Manpage.md

-----
Quoting myself from #10123:
> Propsed design:
> - brew install --formula should only lists available formulae, while brew install --cask should only lists available casks.
> - brew install (without specifying --formula or --cask) should list all formulae and casks available.
(`brew install` is only an example, it applies to all commands accepting both `--formula` and `--cask`.)
I implemented it locally before the shell completion becomes auto generated. This is a rough remake, but definitely better than writing all the things by hand.
https://user-images.githubusercontent.com/44045911/110425186-e8b1e600-80de-11eb-834b-ca3b7036c2c1.mov
Unfortunately I'm only familiar with writing Fish completions, I will try to implement it in Bash and Zsh, either in the future or this PR.

Conditional formulae and casks completion for Fish

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/dev-cmd/bottle.rb

Rely more heavily on the `Bottle::Filename` class rather than hacking around things manually.
Without this the rebuilding bottles workflow is broken for `all:` bottles.

dev-cmd/bottle: improve filename handling.

---

Library/Homebrew/service.rb
Library/Homebrew/test/service_spec.rb

-----
This should fix https://github.com/Homebrew/discussions/discussions/1372 the audit accidentally broke the PLIST generation because the test wasn't good enough to catch the expected format. That should be fixed now.

services: fix array being flattened

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb

For :all bottle blocks in linuxbrew-core, we are going to remove the bottle
block completely before rebottling.
In linuxbrew-core, we use --keep-old to keep the macOS sha lines.
I am not sure why this exception was written initially, but it
now prevents bottling these formulae, because we have no bottle block
and use --keep-old.
I think it's safe to just skip this check, when there is no bottle block
the old_checksum can just directly return nil.
-----

bottle: do not fail on missing bottle block

---

Library/Homebrew/debrew.rb
Library/Homebrew/debrew/irb.rb
Library/Homebrew/formula_versions.rb
Library/Homebrew/formulary.rb
Library/Homebrew/ignorable.rb

-----
Currently when formula methods are deprecated, that formula becomes unreadable. This causes problems with anything that uses `formula_at_revision`, such as the version/revision audit. Notably, with the cellar line deprecation, a massive amount of historical formulae versions are no longer readable.
This PR introduces the functionality to try ignore such errors and continue loading the formula, using the same system as we use to ignore exceptions in Debrew.
This started as an experimental proof of concept based on a Slack discussion, but does seem to work without issues.
Alternatives include:
* Keeping a list of removed or modified formula API permanently.
* Using `method_missing` (this does not work however for the `cellar` situation).

Introduce Ignorable module and provide the facility to try and ignore errors when loading historical formulae

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/pr-pull.rb
Library/Homebrew/dev-cmd/pr-upload.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb

-----
This allows additional root_url specs to be provided with a custom root_url when `brew bottle` updates a formula. This addresses the feature request raised in #5424. Specifically, it makes it easier to support private taps that may need additional authentication to fetch artifacts.
As an alternative to this, I considered implementing a flag to accept a complete replacement bottle ERB template. This had the advantage of simplifying maintenance of this functionality from a homebrew maintainer perspective, while allowing for further arbitrary customizations of the bottle block. On the other hand, if the bottle template is likely to change significantly, users of this functionality could wind up with automated processes generating broken formulae until they update their bottle template, …

dev-cmd/bottle: Support adding root_url specs to bottle spec

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/bump-cask-pr.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/dev-cmd/pr-upload.rb

Run `Homebrew.install_bundler_gems!` a bit earlier for some developer commands to avoid printing gem installation output in the middle of normal developer command output.

dev-cmd: run Homebrew.install_bundler_gems! earlier.

---

docs/Formula-Cookbook.md

-----
- Using the previous syntax, `brew audit --strict` fails because this uses the old Ruby hash syntax.
- Spotted in https://github.com/Homebrew/homebrew-core/pull/76462/files#r624691935.

docs/Formula-Cookbook: Fix outdated HEAD hash syntax

---

Library/Homebrew/cask/dsl/caveats.rb

The current behavior of the `depends_on_java` stanza has 3 shortcomings:
1. The caveat is hardcoded to treat a dependency on Java `11` as a dependency on the *latest* Java. That is no longer a correct assumption, as Java 16 is the latest version. 
2. When a caveat lists a specific version (without the `+` quantifier), Homebrew advises users to install that version of `adoptopenjdk` from `cask-versions`. However, `cask-versions` only has `adoptopenjdk8`, not the full array of versions (8-16, etc.). Only the `adoptopenjdk/openjdk` tap has the full array. 
3. The caveat doesn't handle an array of versions (e.g., `depends_on_java ["8", "11"]`) particularly gracefully. The URL it constructs outputs the array instead of per-version URLs (i.e., `adoptopenjdk["8", "11"]` instead of …

Improve suggestions for depends_on_java

---

Library/Homebrew/build.rb
Library/Homebrew/dev-cmd/extract.rb
Library/Homebrew/extend/pathname.rb
Library/Homebrew/formula_creator.rb
Library/Homebrew/formulary.rb
Library/Homebrew/test/completions_spec.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb
Library/Homebrew/test/formulary_spec.rb
Library/Homebrew/test/pathname_spec.rb
Library/Homebrew/test/tab_spec.rb
Library/Homebrew/test/tap_spec.rb

-----
The original purpose of this method was for pre-2.1 Rubies which did not have such a method.
Nowadays, this was actively breaking things:
* Passing an "open arg" without an offset was broken and causes errors.
* Passing an offset is useless and non-functional because overwriting was blocked.
* Performing `Pathname#write(string, mode: "a")` was also incorrectly blocked.

extend/pathname: limit `write` override to a refinement 

---

.github/workflows/update-manpage.yml
Library/Homebrew/completions/bash.erb
Library/Homebrew/completions/fish.erb
Library/Homebrew/completions/zsh.erb
Library/Homebrew/dev-cmd/generate-man-completions.rb
Library/Homebrew/dev-cmd/man.rb
Library/Homebrew/manpages/brew.1.md.erb
Library/Homebrew/test/dev-cmd/generate-man-completions_spec.rb
completions/bash/brew
completions/fish/brew.fish
completions/internal_commands_list.txt
completions/zsh/_brew
docs/Manpage.md
manpages/README.md
manpages/brew.1

-----
This PR renames `brew man` to ~`brew generate-manpages`~ `brew generate-man-completions`, to hopefully avoid confusion between the developer command to (re-)generate manpages and `man brew`.

Rename `brew man` to `brew generate-man-completions`

---

Library/Homebrew/rubocops/uses_from_macos.rb

-----
This is not provided by macOS. See https://github.com/Homebrew/homebrew-core/pull/76528.

rubocops/uses_from_macos: remove openlibm

---

Library/Homebrew/dev-cmd/bottle.rb

-----
Follow up to #11293
As mentioned in https://github.com/Homebrew/brew/pull/11293#issuecomment-832232012 (and seen in https://github.com/Homebrew/homebrew-core/pull/76617), the changes to the handling of bottle rebuild values broke for new formulae. This is because `FormulaVersions#formula_at_revision` returns `nil` if the formula doesn't exist at the given ref (`origin/HEAD`). Since that's the case for new formulae, `nil` was returned and the fallback to zero was never encountered. This PR adds a final fallback so that no matter what, the bottle rebuild will end up being zero if not set before.

bottle: properly set rebuild for new formulae

---

Library/Homebrew/download_strategy.rb

-----
Closes #8607.
Do taps use download strategies? If so, I'll need to make some changes since shallow clones are allowed for third-party taps.

Stop using shallow clones

---

Library/Homebrew/utils/ruby.sh

-----
`command -a` is invalid.
(This doesn't cover the concerns I had under env filtering - it's just something else I noticed when trying to workaround with a symlink to `/usr/bin`.)

utils/ruby.sh: fix Ruby path searching

---

Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/os/mac/keg.rb

-----
This implements `RPATH` relocation on macOS.
I've tested this successfully locally, but I've gated this behind `HOMEBREW_RELOCATE_RPATHS` for now so that I can test this with various formulae in an external tap when this is merged.
Using a bottled `hello`, built with the appropriate `LDFLAGS` to create an `LC_RPATH` entry:
```
❯ otool -l ./hello | rg -A2 LC_RPATH
cmd LC_RPATH
cmdsize 48
path @@HOMEBREW_PREFIX@@/opt/llvm/lib (offset 12)
```
After pouring the bottle:
```
❯ otool -l $(brew --prefix hello)/bin/hello | rg -A2 LC_RPATH
cmd LC_RPATH
cmdsize 40
path /usr/local/opt/llvm/lib (offset 12)
```
See #11329.

extend/os/mac/keg_relocate: implement `RPATH` relocation

---

Library/Homebrew/dev-cmd/bump.rb

-----
`brew bump` works without any named arguments, but the condition to check for an empty array of formulae and casks was incorrect. This PR fixes the issue.

dev-cmd/bump: fix empty array check

---

Library/Homebrew/service.rb

-----
The `service` DSL needs access to some more formula methods such as `libexec` and `opt_libexec` which weren't added earlier.
Here's a list of all methods/variables used (some are formula-specific) which I found by `grep`ping and `awk`ing, may not be entirely accurate:
```
#{var}                                259
#{opt_bin}                            174
#{etc}                                 67
#{HOMEBREW_PREFIX}                     60
#{opt_sbin}                            37
#{opt_libexec}                         15
#{postgresql_log_path}                 11
#{sbin}                                 9
#{datadir}                              9
#{bin}                                  7
#{postgresql_datadir}                   7
#{ENV["HOME"]}                          6
#{opt_prefix} …
```

service: delegate more path methods

---

Library/Homebrew/cleaner.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/extend/ENV/shared.rb
Library/Homebrew/extend/os/linux/keg_relocate.rb
Library/Homebrew/extend/os/mac/development_tools.rb
Library/Homebrew/extend/os/mac/extend/ENV/shared.rb
Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/language/perl.rb
Library/Homebrew/language/python.rb
Library/Homebrew/os/mac.rb
Library/Homebrew/tab.rb
Library/Homebrew/test/language/perl/shebang_spec.rb
Library/Homebrew/test/tab_spec.rb

-----
See #11227 and #11275.
Commits are split to make it easier to review.

Use versioned Perl shebangs on macOS and support replacing shebangs during relocation

---

Library/Homebrew/release_notes.rb
Library/Homebrew/test/release_notes_spec.rb

-----
I noticed in the [release notes for 3.1.4](https://github.com/Homebrew/brew/releases/tag/3.1.4) that some lines have an author name but no pull request. As of this writing, the release notes start with the following markdown code (reproduce with `brew ruby -rrelease_notes -e 'puts ReleaseNotes.generate_release_notes("3.1.3", "3.1.4", markdown: true)'`):
~~~
- [upgrade: fix broken dependents never being built from source](https://github.com/Homebrew/brew/pull/11263) (@Bo98)
- [Update maintainers, manpage and completions.](https://github.com/Homebrew/brew/pull/11261) (@Homebrew)
- [Allow man and prof Apple Silicon](https://github.com/Homebrew/brew/pull/11256) (@dtrodrigues)
- [Interesting-Taps-and-Forks.md: add gromgit/fuse](https://github.com/Homebrew/brew/pull/11255) (@gromgit)
- …

release_notes: append #PR to markdown link text

---

Library/Homebrew/os/mac.rb

-----
It was a nice experiment, but it seems a lot of extra modules are missing: `/System/Library/Perl/Extras/5.28`.

os/mac: use perl 5.18 on Catalina

---

Library/Homebrew/system_command.rb

-----
Apparently interrupts can happen between the rescue block ending and the thread actually ending.

system_command: fix rare scenario of interrupt being reported to stderr

---

Library/Homebrew/rubocops/shared/helper_functions.rb
Library/Homebrew/rubocops/shell_commands.rb
Library/Homebrew/test/rubocops/shell_commands_spec.rb

-----
Invoking the shell in `exec` causes the process to be detached from `brew`, which causes problems when running `pkill` in formula tests.

rubocops/shell_commands: add cop for shell metacharacters in `exec`

---

Library/.rubocop.yml
Library/Homebrew/rubocops.rb
Library/Homebrew/rubocops/io_read.rb
Library/Homebrew/rubocops/shell_commands.rb
Library/Homebrew/test/rubocops/io_read_spec.rb
Library/Homebrew/test/rubocops/shell_commands_spec.rb

-----
See the test spec file for examples of where this does/doesn't apply.

Add cop for IO.read usage

---

Library/Homebrew/extend/os/mac/keg_relocate.rb

-----
Running `brew bottle` changes dylib IDs, install names, and rpaths into
placeholders for the bottle, creates a bottle tarball, and then changes
the placeholders back to their correct values.
With my refactoring in #11358, the behaviour of this relocation changed:
dylib IDs would no longer be changed back from placeholders into their
correct values after the creation of the bottle tarball.

extend/os/mac/keg_relocate: fix post-bottling dylib ID relocation

---

Library/Homebrew/extend/os/mac/keg_relocate.rb

-----
It's not being used, and it breaks formulae when it is.
Plus do some extra refactoring.

extend/os/mac/keg_relocate: remove `HOMEBREW_RELOCATE_METAVARS`

---

Library/Homebrew/rubocops/text.rb
Library/Homebrew/test/rubocops/text_spec.rb

`SYMROOT` is only a valid argument when `-project` is used.
xcodebuild has other uses than building Xcode projects.
-----
Here is an example of the current behavior incorrectly falling an audit for correct usage of xcodebuild https://github.com/Homebrew/homebrew-core/pull/76696 due to not using `SYMROOT`
Here is the output from xcodebuild if you pass `SYMROOT` when not passing `-project`
```
xcodebuild
-quiet
-create-xcframework
-output
SPIRVCross.xcframework
-library
External/build/Intermediates/XCFrameworkStaging/Release/Platform/libSPIRVCross.a
SYMROOT=External/build/Latest
error: invalid argument 'SYMROOT=External/build/Latest'.
```

audit: Remove SYMROOT

---

Library/Homebrew/extend/os/mac/caveats.rb
Library/Homebrew/test/caveats_spec.rb
bin/brew

-----
We currently filter out `TMUX`, but this breaks displaying some caveats. This also enables an alias I use (improved by @Rylan12 -- thanks Rylan):
brew alias fzp='!id="$(gh pr list -L200 -R github.com/Homebrew/homebrew-core | TMUX=$HOMEBREW_TMUX fzf-tmux -p "90%,50%" --multi | cut -f1)"; [ -n "$id" ] && brew pr-publish --autosquash $id'
Alternatively, we could just stop filtering `TMUX` entirely. I've patched `bin/brew` locally to do that, but I don't know how we feel about adding more env variables to our whitelist. In particular, `TMUX` was mentioned in #1753 but never added, so I assume there's a reason for that.
Or, if we don't want to define `HOMEBREW_TMUX`, we should just remove the caveat that relies on it.

Fix `TMUX` env variable filtering

---

Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/os/mac/keg.rb
Library/Homebrew/os/mac/mach.rb

-----
Keeping dangling `RPATH`s is a security risk, and is bad for build
reproducibility.
-----
I'm tempted to remove all `RPATH`s referencing non-existent directories, but I don't know if that will break anything.
Note that delegating `delete_rpath` doesn't work here. See https://github.com/Homebrew/ruby-macho/issues/355.

extend/os/mac/keg_relocate: remove `RPATH`s rooted in build directory

---

Library/Homebrew/utils/pypi.rb

-----
The `pipgrip` formula was recently bumped in `homebrew/core`, and I hadn't upgraded it locally. When I tried running `brew update-python-resources`, I was thrown off by the error until I realised that it was because I hadn't upgraded.
```
➜ brew update-python-resources pympress
==> Retrieving PyPI dependencies for "pympress==1.5.3"...
Error: Unable to determine dependencies for "pympress==1.5.3" because of a failure when running
`/usr/local/Cellar/pipgrip/0.6.8/bin/pipgrip --json --no-cache-dir pympress==1.5.3`.
Please update the resources for "pympress" manually.
```
This PR modifies the method to use `Formula["pipgrip"].opt_bin` instead of `bin`, to prevent this from happening.
```
➜ brew update-python-resources pympress
==> Retrieving PyPI dependencies for "pympress==1.5.3"... …
```

utils/pypi: use `opt_bin` for pipgrip

---

Library/Homebrew/test/download_strategies/curl_spec.rb
Library/Homebrew/utils/curl.rb
Library/Homebrew/utils/spdx.rb

-----
Closes #10528.
The primary issue that these changes fix is that the initial request sent to determine if a server supports range (partial) requests isn't a `HEAD` request. If the server doesn't support range requests, this downloads the entire file. Another request (the one that is actually meant to download the file) follows and downloads the entire file a second time. A minimal fix would be to add the `--head` flag to the first request, as suggested by @wilkmaciej.
The way that `curl_download` currently checks for range request support is a bit strange. It sends a range request asking for the first byte of the content and checks for the presence of the `Content-Range` header. The proper way to check for range request support is to send a normal (i.e., not range) `HEAD` request to …

Fix range requests with `curl`

---

Library/Homebrew/extend/os/mac/keg_relocate.rb

-----
Homebrew/homebrew-core#77263 revealed two bugs. One in `ruby-macho`,
which turns out to be unable to delete duplicated `RPATH`s. This was
fixed with `ruby-macho` 2.5.1.
The second, which this PR fixes, is in our handling of duplicate
`RPATH`s. Since we iterate over each `RPATH`, attempting to relocate the
first duplicate fails since it will no longer exist after having
relocated the original.
Unblocks Homebrew/homebrew-core#77263.

extend/os/mac/keg_relocate: fix relocation of duplicate `RPATH`s

---

Library/Homebrew/cask/cmd/upgrade.rb

-----
remove casks with `installer manual:` from `outdated_casks` when `brew upgrade`.
Fixes https://github.com/Homebrew/homebrew-cask/issues/105622

remove installer manual casks from upgraded casks

---

Library/Homebrew/tap.rb

-----
Closes #11364.
I elected to use the `--template` flag rather than the `GIT_TEMPLATE_DIR` environment variable because it has higher precedence and seemed more appropriate for this use.

Override user-set default git template for taps

---

Library/Homebrew/formula.rb
Library/Homebrew/test/formula_spec.rb

-----
See https://github.com/Homebrew/brew/issues/11302
This PR adds two symbols that can be passed to `pour_bottle?` as shortcuts for commonly used `pour_bottle?` blocks:
- `:default_prefix_required`: for when the bottle only works in the default prefix but relocation detection doesn't find any problematic paths (right now this would apply only to `ocaml`). Using this symbol is a shortcut for:
```ruby
pour_bottle? do
reason <<~EOS
The bottle needs to be installed into #{Homebrew::DEFAULT_PREFIX}.
EOS
satisfy { HOMEBREW_PREFIX.to_s == Homebrew::DEFAULT_PREFIX }
end
```
- `:clt_required`: for when the CLT is needed for bottles (right now this would be used by the `gcc` and `python` formulae). Using this symbol is a shortcut for:
```ruby
pour_bottle? do
reason <<~EOS
The bottle needs the …
```

formula: add preset `pour_bottle?` symbols

---

Library/Homebrew/os/mac/xcode.rb

Added link to Apple's page with latest version of XCode for each macOS release to the message that suggest downloading latest version.
Test fails on my machine but it's only a string in the XCode file, and Ruby's syntax checker doesn't complain about it - the failing test is 
`rspec ./test/cmd/--version_spec.rb:7 # brew --version prints the Homebrew's version`
so completely unrelated.
-----

Improved Command Lines Tool update instructions

---

docs/Formula-Cookbook.md

-----
From what I have read, Formula options were removed a while ago. Documentation still contains many references/examples for using options.
These references can be confusing and misleading for new brew users.
This change is my first brew pull request (it is very small) - proposing a change that removes a reference to options in the FormulaCookbook documentation.
only 1 file has changes - docs/FormulaCookbook.md
I changed the `odie` example code snippet beginning ~ line 413
The new snippet is modified/minified from the `odie` usage in the cfr-decompiler formula ~ line 39
Here is where I initially read about options being removed - https://github.com/Homebrew/homebrew-core/issues/31510

removed option reference from 'odie' example code snippet in documentation FormulaCookbook markdown file

---

Library/Homebrew/dev-cmd/pr-publish.rb

-----
See the Disscusions:  https://github.com/Homebrew/discussions/discussions/1492
Add a `--branch` param for `pr-publish`.
So that we could trigger github action with `pr-publish` in a tap(Third Party Repository) without using `master` as default branch.
And for keeping `homebrew-core` work normally, the default is set to `master`, so no need to change the github actions in `homebrew-core`.

feat: add branch param

---

Library/Homebrew/formula_installer.rb

If a formula is installed as a dependency (or not on request) then don't output its caveats.
Inspired by conversation in https://github.com/Homebrew/brew/pull/11367.
Closes https://github.com/Homebrew/brew/pull/11367

formula_installer: don't output caveats for dependencies.

---

Library/Homebrew/formula.rb
Library/Homebrew/test/formula_spec.rb
docs/Bottles.md

-----
Let's rename `reason` to `requirement` so the preset symbol can just be
`:clt`. See Homebrew/homebrew-core#77509.
This leads to the easier to parse (IMHO)
```ruby
pour_bottle? requirement: :clt
```

formula: tweak preset `pour_bottle?` symbols

---

Library/Homebrew/livecheck/strategy/sparkle.rb

-----
This PR should fix #11419, at least on Intel Macs. The `Sparkle` strategy used in `livecheck` blocks currently uses `nokogiri` to extract content. On updates to this (vendored) gem, users would see errors on running `brew livecheck` for some Casks.
This PR ensures `Homebrew.install_bundler_gems!` is run before `require "nokogiri"` in the `Sparkle` strategy.
(Note: This will unfortunately not fix the issue on ARM Macs, as pointed out in https://github.com/Homebrew/discussions/discussions/1299#discussioncomment-706030. We might have to move away from `nokogiri` or find some other solution for that issue.)

livecheck/strategy/sparkle: install bundler gems

---

Library/Homebrew/dev-cmd/update-maintainers.rb

-----
Use require "dev-cmd/generate-man-completions" instead of require "dev-cmd/man".
I missed changing this when renaming `brew man` to `brew generate-man-completions`.

dev-cmd/update-maintainers: fix require

---

Library/Homebrew/caveats.rb
Library/Homebrew/service.rb
Library/Homebrew/test/service_spec.rb

service: ensure environment variables are prefixed in command

---

Library/Homebrew/cli/named_args.rb
Library/Homebrew/cmd/link.rb
Library/Homebrew/cmd/list.rb
Library/Homebrew/cmd/unlink.rb
Library/Homebrew/dev-cmd/linkage.rb
Library/Homebrew/test/cli/named_args_spec.rb

-----
Closes #11224.
Currently, if the `head` and `stable` versions of a formula are both installed, it isn't possible to link the `head` version of the formula. This PR adds the `--HEAD` flag to link the `head` version of a formula.
I had to revise the link command to use `to_formulae_and_casks(only: :formula, method: :kegs)` rather than `to_kegs` (which calls `to_formulae_and_casks(only: :formula, method: :keg)` to get both the `head` and `stable` kegs. I may have inadvertently created an issue if multiple non-head kegs can be installed. My modifications make the `link` command attempt to link any non-head kegs unless `--HEAD` is given.
I would appreciate it if a maintainer weighed in on this.

Add `brew link --HEAD`

---

Library/Homebrew/dev-cmd/extract.rb

-----
Formula filenames are required to be lowercase, so the `brew extract` command should downcase the version before using it to construct the filename. I noticed this while performing `brew extract tbb@2020`, which has [version 2020_U3](https://github.com/Homebrew/homebrew-core/blob/754d838326a1fff4e281176de155c3b734b2abac/Formula/tbb%402020.rb#L5) and resulted in a formula with filename `tbb@2020_U3.rb`

extract: use downcased version in filename

---

Library/Homebrew/cmd/install.rb
Library/Homebrew/formula.rb
Library/Homebrew/test/formula_spec.rb

-----
At the moment, installing the `head` version of a formula with `brew install --HEAD` uninstalls the `stable` version of the formula if it is installed. This is obviously undesirable if you want to have the `head` and `stable` versions of a formula installed simultaneously.
This behavior seemed odd when I first discovered it, but it's actually the product of `brew install` uninstalling any kegs that have older versions than the one being installed. The `stable` keg is obviously older than the `head` keg, so it's uninstalled.
This PR changes `brew install` so that it doesn't do any clean-up if `--HEAD` is given.

Don't uninstall `stable` keg with `--HEAD`

---

Library/Homebrew/formula_auditor.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb

-----
As recently discussed in https://github.com/Homebrew/brew/pull/11440#issuecomment-849354045, our docs state that "[Filenames should be all lowercase](https://github.com/Homebrew/brew/blame/3.1.9/docs/Formula-Cookbook.md#L346)". This adds an audit to complain about formula names with uppercase letters and a test.

audit: complain about uppercase formula names

---

Library/Homebrew/rubocops/components_order.rb

components_order: allow keg_only in on_macos/on_linux blocks

---

Library/Homebrew/dependency.rb
Library/Homebrew/requirement.rb

-----
Fixes #11453
Before, `Dependency::expand` would cache the expanded dependencies based on the dependent's name. This doesn't work for formulae and casks that share a name (e.g. `julia`, `mkvtoolnix`, and `r`) because the cached dependencies from the formula might be used and not recalculated for the cask (and vice-versa).
In #11453, when neither `--formula` nor `--cask` were passed, the formulae were evaluated first and the dependents of the `julia`, `mkvtoolnix`, and `r` _formuae_ were cached. Then, when the casks were evaluated, the cached dependents from the corresponding formulae were used for those three.
Now, the key used in the cache to identify the dependencies for a given dependent has been changed to include the class name of the root dependent, removing conflicts. For …

dependency: don't merge formula and cask cache in `::expand`

---

Library/Homebrew/formula.rb

These flags include basic compiler optimization flags without which software can get built completely unoptimized.
While the shims appear to add their own optimization flag on macOS (at least, based on my ARM testing), they do not in the default Linux build which results in CMake packages like LLVM being built without optimizations. This both results in a very large bottle and exceedingly bad performance.
This seems like the best fix to me, as the shims already seem to have the necessary logic to *re-map* optimization flag levels to what Homebrew prefers for platforms like macOS, and so leaving CMake alone to just do its thing seems like the cleanest solution. But I'm open to other suggested fixes if needed.
I will note that without this, LLVM and any other CMake-built software on Linux …

Stop overriding CMake's release compile flags.

---

Library/Homebrew/livecheck/strategy/gnome.rb

-----
This PR updates the `Gnome`strategy for `livecheck` to handle the [new GNOME versioning scheme](https://discourse.gnome.org/t/new-gnome-versioning-scheme/4235) in addition to the older one. Some discussion to provide context is in Homebrew/homebrew-core#78278.
One thing that I had an issue with is how the `Version` objects are displayed in the debug output:
```
40.1.1 => #<Version:0x00007fed9ace3530 @version="40.1.1", @detected_from_url=false, @tokens=[#<Version::NumericToken 40>, #<Version::NumericToken 1>, #<Version::NumericToken 1>]>
```
This is because I've used the `major` and `minor` methods, which tokenise the version string. It would be great if we can avoid showing the tokens in the output.

livecheck/strategy/gnome: handle new GNOME versioning

---

Library/Homebrew/software_spec.rb

-----
Example: `autoconf@2.69` has the same bottle digest for Big Sur and Catalina but the `preferred_perl` in the tab differs.

software_spec: fix wrong tab being fetched when bottle isn't unique

---

Library/Homebrew/formula.rb
manpages/brew.1

-----
Follow up to #11438. See https://github.com/Homebrew/brew/pull/11438#issuecomment-851481188
`Version`s can be compared to each other using so using `.sort_by(&:version)` works fine. `HeadVersion`s, though, cannot be compared in this way. Instead, the latest version is found by checking the time the tab was modified (done in `Formula#latest_head_version`).
Since `.sort_by(&:version)` on and array of HEAD kegs just returns the same array (of which all items except for the last were selected for cleanup), it is arbitrary which HEAD version doesn't get selected for cleanup.
Instead of sorting the HEAD keg array, I've chosen to just remove the latest HEAD keg as found using `Formula#latest_head_version`. This is essentially the same behavior that existed prior to #11438.
Here's the net …

formula: reject only the latest head keg when cleaning up

---

Library/Homebrew/diagnostic.rb

Detect half-baked core taps that show up on a fairly regular basis (e.g. #11465, https://github.com/Homebrew/brew/issues/11243).
A half-baked tap wouldn't have a complete Git config, and is always somewhere below `HOMEBREW_REPOSITORY`, so any Git operation would refer to the Brew repo instead. We simply need to test for any of:
1. Empty tap origin
2. Empty tap HEAD
3. Tap HEAD == Brew HEAD
-----

diagnostic: add check for broken taps

---

Library/Homebrew/utils/tar.rb

-----
While running `brew bump-cask-pr ...` I have seen a tar validation issue a few times.
For example:
```make
==> Verifying checksum for 'f4a5f395b90a4e7a31973a859427284a3c6bec550dbc480a3c588bb68d3dd978--helix-core-server.tgz'
Warning: Cannot verify integrity of 'f4a5f395b90a4e7a31973a859427284a3c6bec550dbc480a3c588bb68d3dd978--helix-core-server.tgz'.
No checksum was provided for this resource.
For your reference, the checksum is:
sha256 "9a1f528f92568531785b1f125e60a48e84b1a958f9e1d74dfc6e61c060e08721"
Error: /Users/cho-m/Library/Caches/Homebrew/downloads/f4a5f395b90a4e7a31973a859427284a3c6bec550dbc480a3c588bb68d3dd978--helix-core-server.tgz is not a valid tar file!
```
The problem seems to be that the validation of tar file depends on regex `/.*\.`, which means that a directory must …

utils/tar: fix validation for tar without directory or extensions

---

Library/Homebrew/formula_auditor.rb

Prevent upgrading them to version 7.11 or newer, as they were
relicensed to an incompatible license.
---
-----
Output:
```
➜ brew audit --strict elasticsearch
elasticsearch:
* Elasticsearch and Kibana were relicensed to a non-open-source license from version 7.11. They must not be upgraded to version 7.11 or newer.
Error: 1 problem in 1 formula detected
```

formula_auditor: add audit for elasticsearch and kibana

---

Library/Homebrew/formula_installer.rb

-----
Currently, if a user has the `stable` version of a formula with build dependencies installed, they'll get an error if they try to install the `head` version of that formula. Build dependencies are currently pruned if the latest version of the formula is installed. This is the case if the `stable` version of the formula is installed and up to date.
I've made changes to not prune build dependencies during the installation of the `head` version. Let me know if you can think of any unintended consequences I might have missed.
If you want to reproduce this issue, run these (htop is very fast to build from source):
```
brew install htop
brew unlink htop
brew install --HEAD htop
```

Install build dependencies for `head` when `stable` is installed

---

Library/Homebrew/dev-cmd/vendor-gems.rb
Library/Homebrew/utils.rb
Library/Homebrew/utils/gems.rb

I didn't add a test for this as I wasn't sure we wanted to be running a full bundle install for a single test, let me know if there's a good way to test this.
---
11b3266fd fix(vendor-gems): redirect bundler stdout to stderr
When running brew commands and interpreting the output, e.g. running
`brew livecheck --json`, it's necessary to stop other programs Homebrew
happens to execute from writing logging output to stdout. Most programs
don't do this, but `bundle install` does seem to.
To reproduce the issue you can run:
```shell
git -C "$(brew --prefix)" clean -ffdx Library/Homebrew/vendor
stdout=$(HOMEBREW_FORCE_VENDOR_RUBY=1 brew livecheck --newer-only --json --cask $(brew --repo homebrew/cask)/Casks/grid.rb)
echo "^^^ was stderr, >>> is stdout: $stdout"
```
If you run it without this …

fix(vendor-gems): redirect bundler stdout to stderr

---

Library/Homebrew/livecheck/strategy.rb
Library/Homebrew/livecheck/strategy/page_match.rb

-----
This is a recreation of #9535, as that PR somehow lost its association with the related branch in my fork and the PR stopped reflecting new pushes.
This migrates `brew livecheck` from `open-uri` to `Utils::Curl`, as `Curl` is used throughout brew for network requests and livecheck is the only place where `open-uri` is used (outside of a vendored gem).
* Replaces `URI.parse(url).open` in `Livecheck::Strategy#page_content` with `#curl_with_workarounds`. Strategies use `#page_content` to fetch a page, so this effectively replaces `open-uri` in livecheck with `Utils::Curl`.

Livecheck: Replace OpenURI#open with Curl

---

Library/Homebrew/cmd/info.rb
Library/Homebrew/formula.rb
Library/Homebrew/test/formula_spec.rb

-----
This PR adds the `Formula#to_bottle_hash` method to be used to create bottle JSON files for #11426.
This will be used in Homebrew/formulae.brew.sh to create the `/api/bottles` API.
Click these links for gists showing the output of this method (when converted to JSON) is for these formulae: [`hello`](https://gist.github.com/Rylan12/bf0adea0d317697a8f16dfc12637ab1c), [`youtube-dl`](https://gist.github.com/Rylan12/5756038a327159cf7f449f44f7406de2)

formula: add `to_recursive_bottle_hash` method

---

Library/Homebrew/os/mac/version.rb

-----
Homebrew is a tool millions of developers rely on every day, and its imperative macOS 12 support is added as quickly as possible. I was going to open an issue on GitHub, but as the homebrew output explicitly stated not to do that and instead try making a PR, I decided to take a crack at it. 
Right now macOS 12 somewhat works, but 
1. requires you to build things from source 
2. dependencies fail to install as it attempts to grab the bottle 
Once all dependencies are installed for a specific formula, `brew install -s` still works as expected

Add macOS 12 (Monterey) support

---

Library/Homebrew/rubocops/uses_from_macos.rb

-----
This PR allows using of `uses_from_macos "git"`
See https://github.com/Homebrew/homebrew-core/pull/78926#discussion_r647348605

rubocops: allow uses_from_macos "git"

---

Library/Homebrew/shims/super/cc

-----
The shim currently does not handle `--sysroot=` and `-isysroot=` flags
correctly. For example, the LLVM build passes `--sysroot=.`, and this is
incorrectly parsed by the shim.

shims/super/cc: fix `sysroot` flag handling

---

Library/Homebrew/dev-cmd/generate-man-completions.rb
Library/Homebrew/manpages/brew.1.md.erb
docs/Formula-Cookbook.md
docs/Manpage.md
manpages/brew.1

-----
Closes https://github.com/Homebrew/brew/issues/11489
This PR adds the [terminology table](https://docs.brew.sh/Formula-Cookbook#homebrew-terminology) from the Formula Cookbook to the manpage. I've chosen to add it toward the bottom in a `TERMINOLOGY` section. I chose the bottom because I felt that the command descriptions should be first, but if there's a better place for it I can move.
I've also converted from table format to list format because tables don't seem to be doable in the manpage (or, at least, `ronn` doesn't convert them).
At the moment, this just copies directly from the formula cookbook but this can be converted to its own list if we think that makes more sense.

docs: add terminology to manpage

---

Library/Homebrew/extend/os/mac/keg_relocate.rb

-----
While this should never be necessary for per-OS bottles, this could be useful for `:all` bottles where the OS it was built on could use a Perl version that doesn't exist on all macOS versions.

os/mac/keg_relocate: add fallback to default Perl version when using tab

---

Library/Homebrew/dev-cmd/unbottled.rb

-----
* Fix `ArchRequirement` comparison. Closes #11456.
* Move bottle tag check to after the requirement check, so that a formula that depends on x86_64 but has an `:all` bottle will now print "doesn't support this macOS" rather than "already bottled".

dev-cmd/unbottled: fix arch requirement handling

---

Library/Homebrew/formula.rb

-----
This PR makes some improvements to the `Formula#to_recursive_bottle_hash` method. This is a private method that is not publicly disclosed (as of the next tag) so these changes should be okay.
The changes add a `pkg_version`, and `rebuild` item to the bottle. It also modifies the way that dependencies are represented so that they match the top level completely (except for the missing `dependencies` field).
This means that a basic example now looks like this:
```json
{
"name": "foo",
"pkg_version": "1.2.3_1",
"rebuild": 0,
"bottles": {
"big_sur": {
"url": "https://example.com"
}
},
"dependencies": [
{
"name": "bar",
"pkg_version": "5.6.7",
"rebuild": 3,
"bottles": {
"big_sur": {
"url": "https://example.com"
}
}
}
]
}
```
Links to example gists: …

formula: improve `to_recursive_bottle_hash`

---

Library/Homebrew/cask/installer.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/messages.rb

-----
- Both formulae and casks can have caveats, but only formulae caveats were shown at the end of a bulk install/upgrade/reinstall operation via `Homebrew.messages.record_caveats`. This fixes that to show Cask caveats too, for consistency (scrolling up all of the multi-formulae-and-casks output to see caveats is time-consuming and users might miss them).
- In doing this I had to change how `Messages#record_caveats` works since the cask name is just a string, not an object.
- Fixes #11421.
----
Before:
```
➜ brew install macfuse kube-linter gh
==> Caveats
You must reboot for the installation of macfuse to take effect.
==> Downloading https://github.com/osxfuse/osxfuse/releases/download/macfuse-4.1.2/macfuse-4.1.2.dmg
Already downloaded: …
```

cask/installer: Add Cask caveats to the end-of-operation summary

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/tap-new.rb

Running `brew test-bot --only-tap-syntax` fails on `ubuntu-latest` if any casks are added later to the tap, since casks are macOS only.
See [github.com/ncruces/homebrew-tap](https://github.com/ncruces/homebrew-tap) for my custom tap. I've fixed this in `main` by adding this line (which prevents `brew test-bot --only-tap-syntax` from running on `ubuntu-latest`, but still runs it on `macos-latest`, which should be enough to ensure correctness).
The [`casks-not-supported`](https://github.com/ncruces/homebrew-tap/pull/4) branch reverts the change, and causes the [failure](https://github.com/ncruces/homebrew-tap/runs/2773518480?check_suite_focus=true).
This was my best attempt for a fix, but I'm open to suggestions and doing the necessary leg work to get them through.
-----

brew tap-new: tests.yml workflow fails with casks

---

Library/Homebrew/download_strategy.rb

-----
Local bottles should also extend the `Pourable` module so that the `==> Pouring hello--2.10.big_sur.bottle.tar.gz` message shows up as expected.
This does mean that the output of an install command on a bottle file path is a bit more verbose, but I think it looks better overall:
Before:
```console
$ brew install /Users/rylanpolster/Library/Caches/Homebrew/downloads/e0395c201b40d07f50d44b84fccab28bb89bb292929894555688f6510f583a4c--hello--2.10.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/hello/2.10: 11 files, 165.7KB
```
After:
```console 
$ brew install /Users/rylanpolster/Library/Caches/Homebrew/downloads/e0395c201b40d07f50d44b84fccab28bb89bb292929894555688f6510f583a4c--hello--2.10.big_sur.bottle.tar.gz
==> Pouring hello--2.10.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/hello/2.10: 11 …
```

LocalBottleDownloadStrategy: extend Pourable

---

Library/Homebrew/livecheck/strategy.rb

-----
Some casks are depending on `user_agent: :fake`, like `hopper-debugger-server`, `keycue` or `hook` (after merging https://github.com/Homebrew/homebrew-cask/pull/106972). When running `livecheck` on them, the fake UA will not affect the request for fetching the version and therefore fail.
```
curl: (22) The requested URL returned error: 403 
Error: hopper-debugger-server: Unable to get versions
curl: (22) The requested URL returned error: 403 Forbidden
Error: keycue: Unable to get versions
```
This PR changes `page_content(url)` livecheck strategy to try both user agents (`:default` and `:browser`). The changes are analogue to https://github.com/Homebrew/brew/commit/b9741dd1e69f5a3dd59005ef4f89a63867347e3a. It basically wraps the existing code inside an `each` loop.
With this PR …

Try getting page content with both headers

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/test/cask/audit_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/discontinued.rb
Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-skip.rb
Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/url-unversioned.rb
Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/version-latest.rb

-----
`brew audit --cask --online` is incorrectly failing for discontinued casks in Homebrew/homebrew-cask#107275 and Homebrew/homebrew-cask-versions#11181. This is because `Cask::Audit#check_livecheck_version` doesn't account for all of the skip conditions for casks (only `livecheck.skip?` and `version.latest?`, not `discontinued?` or `url.unversioned?`). As a result, `#check_livecheck_version` runs livecheck in some scenarios where it should be skipped and this predictably fails.
This PR modifies `#check_livecheck_version` to respect cask skip conditions by using `Livecheck::SkipConditions#skip_information`. This ensures the audit uses the same skip conditions as `brew livecheck`.
This also adds related tests, as this particular logic wasn't tested before. As expected, these tests fail …

Cask::Audit: Handle livecheck skip conditions

---

Library/Homebrew/requirement.rb

-----
Pardon me for the PR title since I can't write a better one.
I was experimenting with Homebrew to see if I can get it to run on Ruby 2.7 (I know this may sound stupid). Turns out most functions work, except for this:
```
$ brew info suspicious-package --debug
Error: Cask 'suspicious-package' definition is invalid: can't modify frozen String: "MacOSRequirement"
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:241:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:238:in `depends_on'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/suspicious-package.rb:19:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:61:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:61:in `config=' …
```

Fix potential modifications to frozen string

---

Library/Homebrew/formula_installer.rb

-----
Restrict usage of the formula file from the bottle. Should fix https://github.com/Homebrew/brew/pull/11468#issuecomment-860627703.
Formulae which require files from `lib` in the Tap could probably not get `post_install` to work if installing them without tapping the Tap.

formula_installer: restrict use of Formula from Keg

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/os/mac/diagnostic.rb

We don't want to complain about either Intel or ARM installations of Homebrew in `brew doctor` so check for/allow both.

diagnostic: hide some warnings on Apple Silicon.

---

.github/workflows/tests.yml
Library/Homebrew/formula_auditor.rb
Library/Homebrew/resource_auditor.rb

-----
This PR is intended to exclude `ResourceAuditor#audit_version` from being run as part of `brew audit` on CI, with the exception of new formulae. This audit will give a `version 1.2.3 is redundant with version scanned from URL` error when the version specified in a formula (e.g., `version "1.2.3"`) is the same as the `Version` detected from the `url`.
Under certain circumstances, the version audit can become a problem on Homebrew/brew and Homebrew/homebrew-core CI:
* Homebrew/brew CI will fail because of this audit if a PR modifies the `Version` parsing logic in a way that it fixes parsing for core formulae that previously needed to use `version` to specify the correct version. This scenario is a challenge because we can't remove `version` from these formulae until the …

Exclude version audit on CI

---

Library/Homebrew/test/version_spec.rb
Library/Homebrew/version.rb

-----
The version for the `luajit-openresty` formula is currently parsed from the `stable` URL (`https://github.com/openresty/luajit2/archive/refs/tags/v2.1-20210510.tar.gz`) as `20210510` instead of `2.1-20210510` (see Homebrew/homebrew-core#78791). This should have used `version` to specify the full version that wasn't being properly parsed when the formula was added but that wasn't addressed at the time. [Other formulae with a similar version format run into the same parsing issue and they use `version` because of it.]
We could simply add `version "v2.1-20210510"` to `luajit-openresty` (doing what formulae with a similar version format have done) but I figured it would be better to support this version format internally (i.e., fixing this issue for both existing and future formulae …

Version: Add parser for additional hyphenated filenames

---

Library/Homebrew/formulary.rb
Library/Homebrew/test/formulary_spec.rb

-----
This PR adds some new functionality to `Formulary` to allow for refs to be mapped to each other. This mapping is set up using `Formulary::map` and is then used to substitute the reference passed to `Formulary::factory`. For example:
```ruby
Formulary.factory "foo"        # error
Formulary.map "foo", to: "bar" # setup mapping
Formulary.factory "foo"        # returns the bar formula
```
At the moment, this is not used anywhere internally, but would be used in Homebrew/json if merged. Originally, I had opted to [monkey patch `Formulary` to look for cached bottles](https://github.com/Homebrew/homebrew-json/pull/6) and was a bit unwilling to add it to Homebrew/brew because it felt too specific to that tap. However, I rethought the process a bit over the weekend and am now planning on …

Formulary: map formula names to local bottle paths

---

Library/Homebrew/formula_installer.rb

The keg formula isn't present in some old bottles. Use the tap
formula as a fallback when this is the case.
---
---
A few formulae in `linuxbrew-core` were bottled over 3-4 years ago, and their bottles do not seem to contain the `.brew` directory within the prefix. This PR adds a fallback to use the tap formula in such cases (rescuing from `FormulaUnavailableError` seems to do the trick). These formulae will be rebottled after the core merging, but it may still be a problem for external taps with old bottles.
CC @iMichka

formula_installer: add fallback to use tap formula

---

Library/Homebrew/formula_auditor.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb

-----
This PR adds a couple of more checks for conflict audit:
- a formula shouldn't conflict with itself
- if a formula conflicts with another one, the second formula should have a conflict with the first one
We have several formulae (23 when I've check it last time) with asymmetric `conflicts_with` statement. PR for them are coming

Improve conflicts audit

---

Library/Homebrew/cask_dependent.rb
Library/Homebrew/cmd/untap.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/dependency.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/formulary.rb
Library/Homebrew/installed_dependents.rb
Library/Homebrew/tap.rb
Library/Homebrew/test/formulary_spec.rb

-----
This PR allows homebrew/core to be untapped if the `HOMEBREW_UNTAP_HOMEBREW_CORE` environment variable is set. We may want to consider merging this variable with `HOMEBREW_BOTTLE_JSON`. For now, I separated them because they are technically for different things (and I wasn't sure about a name). Happy to do whatever we think is best here.
Now, `Formulary` will throw a `CoreTapFormulaUnavailableError` when it can't find a formula under the conditions that homebrew/core is untapped and the environment variable is set.
`CoreTapFormulaUnavailableError` is a subclass of `TapFormulaUnavailableError` which is a subclass of `FormulaUnavailableError`. Therefore, anytime `CoreTapFormulaUnavailableError` is thrown it will still be caught by any `rescue FormulaUnavailableError` blocks. However, …

Allow for homebrew/core to be untapped

---

Library/Homebrew/dev-cmd/release.rb
Library/Homebrew/release_notes.rb
Library/Homebrew/test/release_notes_spec.rb

This was failing for me locally so I've made some fixes:
- remove the `markdown` flag (as it's the only path now)
- refactor the generation to not use intermediate variables
- discard more weird cases rather than erroring
- exclude @Homebrew changes (e.g. from bots) because we don't care about  these in the release notes

release_notes: refactor/cleanup.

---

.github/workflows/tests.yml
.gitignore
Library/Homebrew/.rspec_parallel
Library/Homebrew/Gemfile
Library/Homebrew/Gemfile.lock
Library/Homebrew/dev-cmd/tests.rb

**tl;dr** This pull request proposes configuring tooling to automatically detect and track flaky tests. As I understand it, this has historically required manual effort for Homebrew maintainers. By automating the process, we hopefully reduce the time that maintainers have to spend on the thankless and laborious task of manually identifying flaky tests. 🤞
/cc @MikeMcQuaid for review
_No. I don't think this is applicable to this pull request, but if it is, please let me know._ :bow:
At a high-level, setting things up works as follows:
1. Enhance the test suite to emit JUnit XML test reports.
This is accomplished in e163eb8650cb38d03829cd8aa537a3f32af3682f. Please see the commit message for details.
2. Enhance the CI workflow to send those test reports to …

Automatically detect and track flaky tests

---

Library/Homebrew/livecheck/strategy/sparkle.rb

-----
avoid `brew livecheck` error when `pubDate` of item is null in `Sparkle::item_from_content`.
related with https://github.com/Homebrew/homebrew-cask/issues/105918

repair pubDate statement in livecheck

---

Library/Homebrew/utils/github.rb

-----
Address the issue reported in https://github.com/Homebrew/brew/pull/11556#issuecomment-864462191
I propose to obtain the remote url using `git remote get-url --push origin` in the dry-run mode when `no-fork` is specified, and set it to "FORK_URL" when `no-fork` is not used.
CC @cho-m

utils/github.rb: fix dry-run message

---

Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/extend/os/mac/utils/bottles.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/os.rb
Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/version.rb
Library/Homebrew/os/mac/xcode.rb
Library/Homebrew/test/os/mac/diagnostic_spec.rb
Library/Homebrew/test/utils/bottles/collector_spec.rb

-----
#11557 needs to know if a Sparkle feed item's `minimumSystemVersion` (a macOS version like `12.0.0`) is a prerelease version. `OS::Mac` has a `#prerelease?` method but it can seemingly only be used to check the macOS version of the execution environment, like `OS::Mac.prerelease?`. We need to be able to do `OS::Mac::Version.new("12.0.0").prerelease?`, which isn't currently supported.
This PR moves the `#outdated_release?` and `#prerelease?` methods to `OS::Mac::Version` and simply calls the `::Version` methods in the related `OS::Mac` methods. This allows for both `OS::Mac.prerelease?` and `OS::Mac::Version.new("12.0.0").prerelease?`.
It would be nice to be able to remove these methods from `OS::Mac` while still being able to access them like `OS::Mac.prerelease?`. I couldn't get …

OS::Mac: Move version methods into ::Version

---

Library/Homebrew/test/utils/github_spec.rb

-----
Artifacts in PR https://github.com/Homebrew/homebrew-core/pull/51971 has expired which causes a couple of failed in `github_spec`. 
This PR updates the Pull Request id that we use in tests.
I think we'll need to come up with better solution.
```
Failures:
1) GitHub::get_artifact_url gets an artifact link
Failure/Error:
url = described_class.get_artifact_url(
described_class.get_workflow_run("Homebrew", "homebrew-core", 51971, artifact_name: "bottles"),
)
GitHub::API::Error:
No matching workflow run found for these criteria!
Commit SHA:   869200eb8281d8c399a978476ac868a30edf5e28
Branch ref:   bibutils-6.9
Pull request: 51971
Workflow:     tests.yml
2) GitHub::get_artifact_url fails to find artifacts that don't exist
Failure/Error:
expect {
described_class.get_artifact_url( …
```

github_spec: Fix failed test due to expired artifacts

---

Library/Homebrew/dev-cmd/typecheck.rb

-----
Tapioca generated RBI file conflicts with RBI file provided by Sorbet. And since Sorbet covers `did_you_mean` I've disabled RBI generation for this gem.
See https://github.com/Homebrew/brew/pull/11589

typecheck: do not generate RBI file for did_you_mean

---

Library/Homebrew/cleaner.rb

Arch-specific build tool formulae (https://github.com/Homebrew/homebrew-core/pull/79874) install their info files in `#{info}/<arch>` to avoid conflicts with the main tool formulae.
However, the info cleaner only removes `#{info}/dir`, so each tool's bottle includes `#{info}/<arch>/dir`, which causes install-time conflicts.
This PR fixes that by deleting all `dir`s under `#{info}`.
Before (`#{info}/dir`):
```
==> Cleaning
[...]
==> Fixing /usr/local/Cellar/grep/3.6/bin/ggrep permissions from 755 to 555
rm /usr/local/Cellar/grep/3.6/share/info/dir
==> Finishing up
```
After (`#{info}/dir`) -- no change:
```
==> Cleaning
[...]
==> Fixing /usr/local/Cellar/grep/3.6/bin/ggrep permissions from 755 to 555
rm /usr/local/Cellar/grep/3.6/share/info/dir
==> Finishing up
```
Before …

cleaner: recursively delete info `dir`s

---

Library/Homebrew/test/utils/github_spec.rb

-----
Fix issue mentioned in #11592 with newer artifact number from recent run.
Blocking some other PRs here.
---
Note that there are some `brew tests` that always fail for me, which I am ignoring in final checkbox:
- Testing on Rosetta causes issues for `Utils::Analytics::os_arch_prefix_ci`
- `HOMEBREW_GITHUB_API_TOKEN` being set causes failure in `brew tap-info`

test/utils/github_spec: fix artifact number

---

Library/Homebrew/cli/args.rbi
Library/Homebrew/dev-cmd/dispatch-build-bottle.rb

-----
This is going to be needed soon, when I merge dispatch workflows into one.
Companion PR: https://github.com/Homebrew/homebrew-core/pull/80015

dispatch-build-bottle: support self-hosted Linux and unified workflow

---

Library/Homebrew/formula.rb

-----
Currently, we copy `config.log` and `CMakeCache.txt` from the root of
the source tree into the the logs generated by the build. This has three
shortcomings:
1. These files are not necessarily found where we look. This is often
the case with a CMake build, but can occur with an Autotools build
as well (e.g. GCC, or any other out-of-tree build).
2. There may be several of these files scattered throughout the build
tree. This occurs, for example, when the build itself invokes
`configure` or `cmake` as part of the build process.
3. We don't copy `CMakeOutput.log` or `CMakeError.log`, which are
usually more informative about what happened during the CMake
invocation. It is not sufficient to add them to the array of log
files that we copy because these are never found at the source root, …

formula: capture build logs more comprehensively

---

Library/Homebrew/default_prefix.rb

-----
This should fix the doctor complaining on Linux in `homebrew-core`:
```
Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```
Above snippet taken from (somewhat companion) PR: https://github.com/Homebrew/homebrew-core/pull/80082
The `DEFAULT_PREFIX` should not be set to the macOS one when setting `HOMEBREW_FORCE_HOMEBREW_ON_LINUX`.
Since we have stricter env var (`HOMEBREW_SIMULATE_MACOS_ON_LINUX`), then …

default_prefix: set macOS default prefix on Linux if simulating it

---

Library/.rubocop.yml
Library/Homebrew/cask/audit.rb
Library/Homebrew/rubocops/cask/stanza_grouping.rb
Library/Homebrew/rubocops/cask/stanza_order.rb
docs/Acceptable-Casks.md
docs/Cask-Cookbook.md
docs/FAQ.md

-----
Fixes Homebrew/homebrew-cask#107626
Some old URLs still remaining inside documentation, audit, etc.

docs: fix cask doc urls to use docs.brew.sh

---

Library/Homebrew/search.rb

-----
Fixes https://github.com/Homebrew/brew/issues/11606.
Currently the search can return duplicate formulae due to https://github.com/Homebrew/brew/pull/11565. Because in [this line](https://github.com/homebrew/brew/blob/master/Library/Homebrew/search.rb#L90) the results of `fuzzy_search` are simply appended, formulae can be added a second time to the result list.
This PR changes this by adding the additional results, only if they're not already in the list.
Before:
```
brew search delta
==> Formulae
delta                               git-delta                           xdelta                              zdelta                              zdelta                              xdelta
==> Casks
deltachat …
```

Fix duplicate formulae in search results

---

Library/Homebrew/livecheck/strategy/sparkle.rb

-----
Helps close Homebrew/homebrew-cask#107112 
The issue in the above PR was that the `bartender` Cask Sparkle feed included a macOS Monterey-only (Beta) release, which shows up in `livecheck`. The only way to identify this variant would be to check the `sparkle:minimumSystemVersion` (or `livecheck` a different url/strategy):
```xml
<item>
<title>Version 4.1.0</title>
<sparkle:minimumSystemVersion>12.0.0</sparkle:minimumSystemVersion>
<sparkle:releaseNotesLink>https://macbartender.com/B2/updates/4-1-00/rnotes.html</sparkle:releaseNotesLink>
<pubDate>June 11, 2021 09:45:00 +0000</pubDate>
<enclosure url="https://macbartender.com/B2/updates/4-1-00/Bartender%204.zip" sparkle:version="41000" sparkle:shortVersionString="4.1.0" length="10447378" type="application/octet-stream" …
```

livecheck/strategy/sparkle: check minimumSystemVersion for compatibility

---

Library/Homebrew/language/python.rb
Library/Homebrew/test/language/python/virtualenv_spec.rb

-----
A user may wish to use two use two brew-installed Python packages
together. For example, one might want to `import numpy` when using
`jupyterlab` or `ptpython`.
Currently, the only ways to do this I'm aware of is with some hacking of
`PYTHONPATH` or the creation of `.pth` files in a formula's prefix.
A better solution is to allow the virtualenvs that `brew` creates to
have access to system site-packages by default, so that `import numpy`
inside `ptpython` or `jupyterlab` just works.
Partially resolves Homebrew/homebrew-core#76950.
-----
As a bonus, I think we should no longer need to resource `wheel` in any formula, since the `wheel` from the global environment which we ship with Python should be usable after this change.

language/python: create venvs with access to system site packages

---

.github/workflows/tests.yml
Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/test/spec_helper.rb

BuildPulse is trying to find flaky tests for us but, given the previous model of using `rspec-retry`, it would rarely find them. Instead, let's try to always rerun `brew tests` multiple times, report to BuildPulse each time (by moving the reporting logic into `brew tests`) and disable `rspec-retry` when using BuildPulse.
While we're here, let's enable `rspec-retry` locally so we don't have flaky tests biting maintainers/contributors there.
CC @jasonrudolph for thoughts

Tweak BuildPulse/`rspec-retry` logic

---

Library/Homebrew/formula_auditor.rb

Now we have `all:` bottles and Bintray is going away for `mirror`s: let's bottle everything in Homebrew/homebrew-core.
Note: this will fail for now until we've finished bottling these.
Depends on https://github.com/Homebrew/homebrew-core/issues/75943

formula_auditor: don't allow `bottle :unneeded` in core.

---

Library/Homebrew/bundle_version.rb
Library/Homebrew/unversioned_cask_checker.rb

-----
This is a follow-up to #11599, where I said I would replace use of `nokogiri` for XML parsing with `rexml` in parts of brew outside of the `Sparkle` livecheck strategy. These changes are generally a straightforward shift from `nokogiri` methods to `rexml` methods.
One notable difference is that `rexml` requires you to access attribute values using square bracket syntax instead of a method (like `#attr` in `nokogiri`).`rexml` has an `#attribute` method but it returns the full attribute (e.g., `a="b"`). We can't use a safe navigation operator in this context, so it was necessary to create an intermediate variable to be able to guard against `nil` values.
If we had more code doing this, I would say that we could probably just extend `rexml` to add an `attr` method that's just a wrapper …

Replace Nokogiri with REXML

---

docs/Acceptable-Formulae.md

-----
This PR adds a quote from [State of Software Security report](https://www.veracode.com/blog/research/announcing-state-software-security-v11-open-source-edition) to emphasise once again why it's important to use dependencies from Homebrew instead of having them vendored.

Acceptable-Formulae: add a quote from Veracode report

---

Library/Homebrew/formula_support.rb

We'll no longer need this DSL so let's move towards deprecation.

formula_support: deprecate `bottle :unneeded`/`:disabled` in 3.3.0

---

Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/reinstall.rb

`Error: Invalid usage: not (yet) working on Apple Silicon or Rosetta 2!`
-----
This Pull request adds the `-g` or `--git` option to the `brew reinstall` command.
I've had several instances where I do this:
```
brew install flashrom
brew install flashrom --build-from-source
brew test flashrom
brew reinstall flashrom --build-from-source --git --debug
brew uninstall flashrom
brew install flashrom --build-from-source --git --debug
```
I've found it very useful to when doing a `reinstall` to be able to pass the git option to avoid the uninstall:
```
brew install flashrom
brew install flashrom --build-from-source
brew test flashrom
brew reinstall flashrom --build-from-source --git --debug
brew test flashrom
```
I'm going to fire up a clean install to test this on intel.

reinstall: add support for the --git option

---

Library/Homebrew/diagnostic.rb

-----
repair `Diagnostic#Checks::check_deleted_formula` because `Keg. all` names will have duplicate names if we have installed the same software with different versions.

fix duplicate keg names in `Keg.all` names

---

Library/Homebrew/extend/ENV/super.rb
Library/Homebrew/shims/super/cc

-----
Some formulae are able to detect the features of the runtime CPU, and
execute code accordingly. This typically entails 1) the detection of
features of the build-time CPU in order to determine the targets that
the compiler can generate code for, and 2) generating code for the
targets that the compiler can support.
Our filtering of optimization flags can cause misdetection of compiler
features, leading to failed builds [1], and miscompilation even when the
build does not fail [2].
Let's try to fix this by allowing formulae to declare
`ENV.runtime_cpu_detection` which skips the filtering of `-march` and
related flags.
I've also skipped the filtering of the optimisation
level, since it seems to me that if upstream maintainers have gone to
the lengths of writing code that detects runtime …

superenv: handle formulae with runtime CPU detection

---

Library/Homebrew/rubocops/lines.rb

-----
This is implements the first audit discussed in #11608. (Second audit is in progress.)

rubocops/lines: check allowlist for use of `ENV.runtime_cpu_detection`

---

Library/Homebrew/cli/args.rbi
Library/Homebrew/dev-cmd/dispatch-build-bottle.rb

@MikeMcQuaid asked to rename this flag.
-----

dispatch-build-bottle: rename --wheezy to --linux-wheezy

---

Library/Homebrew/extend/os/mac/keg.rb
Library/Homebrew/formula_cellar_checks.rb
Library/Homebrew/keg.rb

-----
This implements the second audit discussed in #11608.
~~I've only done this on macOS for now, since I make use of `Keg#mach_o_files`, but I wanted to get feedback on the approach here before doing something more generic.~~

formula_cellar_checks: check for `cpuid` instruction when needed

---

Library/Homebrew/formula.rb

-----
A number of formulae use a variant of `Time.now` to generate the build
time of the formula. Let's define a method to make sure that:
1. it uses `SOURCE_DATE_EPOCH` whenever available; and,
2. it uses `utc`.
Both should help with build reproducibility.
See Homebrew/homebrew-core#80608.

formula: add a `time` method for use as the build time

---

Library/Homebrew/formula_cellar_checks.rb

-----
The output format of `objdump` on Mojave is different from newer
versions of macOS, so I've adjusted the relevant audit to account for
this difference.

formula_cellar_checks: fix cpuid instruction check on Mojave

---

bin/brew

-----
This will support https://github.com/Homebrew/homebrew-services/pull/350 so systemd can use `DBUS_SESSION_BUS_ADDRESS`

brew: add `DBUS_SESSION_BUS_ADDRESS` copy

---

Library/Homebrew/completions/fish.erb
completions/fish/brew.fish

Wherever in the file the function __fish_brew_suggest_diagnostic_checks is called, the name has a trailing 's' (plural 'checks'), whereas the function definition uses 'check' in singular. Changing the function name to match the callsites.
-----
Closes #11676

Fix typo in brew doctor completion function name

---

Library/Homebrew/extend/ENV/super.rb

-----
This makes `ENV.O{1,0}` behave like `ENV.deparallelize`.
This should also allow us to build libgcrypt's jitter entropy collector,
which we currently disable because it interacts poorly with our compiler
shims. See #11201 for a previous attempt at this.

extend/ENV/super: allow `O{1,0}` to accept a block

---

Library/Homebrew/dev-cmd/pr-pull.rb

-----
This PR adds a `--no-bottle` option to `pr-pull` and `pr-publish`. This can be convenient when we want to rebase and merge a PR (and ensure commits are signed) without downloading bottles.
A use case for this would include PRs such as Homebrew/homebrew-core#80302 where we didn't add the syntax only label, since some of the changes weren't autocorrected and modified logic in e.g. `test` blocks.
Signatures do not persist when using the GitHub UI "Rebase and merge" button, and `--no-upload` would still download the bottles. This option prevents downloading the bottles when we simply want to rebase and merge.

`brew pr-pull`: handle label for merging without bottles

---

Library/.rubocop.yml
Library/Homebrew/dev-cmd/typecheck.rb

-----
- It was renamed in https://github.com/sorbet/sorbet/commit/4ea6842988c6ec33dc8a39439b7b1d4742921f0e which is included in the ancient version we're using.

dev-cmd/typecheck: `error-white-list` renamed to `isolate-error-code`

---

Library/Homebrew/cmd/install.rb

Otherwise if there's no search results then there's no indication what was being searched for:
```
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

cmd/install: output missing formula name.

---

Library/Homebrew/cmd/fetch.rb
Library/Homebrew/formula.rb
Library/Homebrew/software_spec.rb

-----
It would be useful for maintainers to be able to easily fetch bottles for different OSes.
Not sure if the implementation itself is fine but it works.

fetch: add --bottle-tag flag

---

docs/Acceptable-Formulae.md

docs: don't allow patches for linux formula either

---

Library/Homebrew/dev-cmd/bottle.rb

These can be changed on macOS but not on Linux so we need to make them consistent in both places for `all:` bottles to have consistent checksums.
I investigated adding to `cleaner.rb` to fix these symlink permissions on installation but it seems it already happens by default when extracting so there's no need.

dev-cmd/bottle: fixup macOS symlink permissions.

---

Library/Homebrew/commands.rb
completions/bash/brew
completions/fish/brew.fish
completions/internal_commands_list.txt
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

-----
This PR makes two minor changes:
* It removes the default alias for `brew diy` (`configure`) which no longer exists.
* It adds `lc` as a default alias for `livecheck`, similar to `tc` for `typecheck`. The reason I'm proposing this (rather than using `brew alias` just for myself) is because there are 7 `l*` commands and 4 `li*` commands, so at least 4 characters (i.e. `liv<TAB>`) are required to autocomplete to `livecheck`. I think users of `livecheck` would like having a short alias like `lc`, which is convenient and unambiguous (to my knowledge).

commands: remove `diy`, add `lc` alias for `livecheck`

---

Library/Homebrew/bottle_api.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/update.sh
Library/Homebrew/formula.rb

-----
Follow-up to https://github.com/Homebrew/brew/pull/11648
This PR does three things to improve the way JSON bottles are handled:
1. `BottleAPI::fetch_bottles` only downloads dependency bottles if no up-to-date version of the formula is installed locally. This means we don't need to spend time downloading bottles for all dependencies if they will never be used.
2. Automatic Homebrew updates (i.e. `brew update --preinstall`), no longer fetches `homebrew/core` (as long as `HOMEBREW_JSON_CORE` is set). Running `brew update` manually _will_ still fetch `homebrew/core`.
3. `brew info` now shows the most recent version information if `HOMEBREW_JSON_CORE` is set rather than the version that exists in the tap.

Improvements to JSON bottle handling

---

Library/Homebrew/cask_dependent.rb
Library/Homebrew/installed_dependents.rb

-----
Fixes https://github.com/Homebrew/brew/issues/11501
stop the warning of the build dependency formula when we uninstall a cask.

installed_dependents: reject build formula

---

Library/Homebrew/version.rb

-----
`version.rb` currently checks for both cases of "rc" in version number suffixes, but only lowercase "p". This adds uppercase "P" to the list, allowing it to properly parse versions like `4.4.2-P1`, which is the [current release](https://downloads.isc.org/isc/dhcp/4.4.2-P1/dhcp-4.4.2-P1-RELNOTES) of [`isc-dhcp`](https://github.com/Homebrew/homebrew-core/pull/81175).

version: check for both cases in suffix

---

Library/Homebrew/cmd/update-report.rb

-----
Follow-up to https://github.com/Homebrew/brew/pull/11715
Auto updates with `HOMEBREW_DEVELOPER` set will throw an error because `HOMEBREW_UPDATE_BEFORE_HOMEBREW_CORE` and `HOMEBREW_UPDATE_AFTER_HOMEBREW_CORE` are unset. This error is ignored unless `HMEBREW_DEVELOPER` is set so I didn't notice it during my testing.

update-report: don't try to report Homebrew/core if not needed

---

Library/Homebrew/formula.rb

-----
Follow-up to https://github.com/Homebrew/brew/pull/11715
If `HOMEBREW_JSON_CORE` is set, `brew cleanup` fails:
```console
$ brew cleanup
Error: no implicit conversion of nil into String
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:350:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:350:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:350:in `+'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2351:in `versioned_prefix'
/usr/local/Homebrew/Library/Homebrew/formula.rb:597:in `prefix'
/usr/local/Homebrew/Library/Homebrew/formula.rb:524:in `latest_version_installed?' …
```

formula: fix `latest_version_installed?` for `HOMEBREW_JSON_CORE`

---

Library/Homebrew/cmd/update-report.rb

-----
Follow-up to https://github.com/Homebrew/brew/pull/11729
We also need to check whether it's a preinstall update (i.e. that `--preinstall` was passed). Otherwise, homebrew/core will still be updated and its updates won't be listed in the output because they'll be ignored by `HOMEBREW_JSON_CORE` presence.

update-report: still report homebrew/core changes if they are updated

---

Library/Homebrew/cask/quarantine.rb
Library/Homebrew/diagnostic.rb

-----
There is a problem with the current way of checking`xattr` command, which is simply running `xattr` no args and checking if it prints an error. But on macOS 12 beta3, the `xattr` command with no args would print an error, so the `-h` command is appended to fix this check.
This type of detection does not affect the previous version and does not require additional unit tests.

cmd/doctor: repair `xattr` not find

---

Library/Homebrew/cmd/search.rb

-----
I often find myself checking Repology to quickly reference how other
package managers handle certain things, so it seems useful to be able to
do so with `brew search`.
While we're here, let's fix the query URL for MacPorts.

cmd/search: add repology

---

Library/Homebrew/utils/github/api.rb

-----
When using the GitHub API, if the API request limit is exceeded, the user would be prompted to create an API token even if one already exists. This will change it only ask for a new API token if one doesn't already exist.
Also, support for `gho_` tokens are added as the GitHub command line tool (`gh`) uses OAuth and may place that token in the keychain for git to use, and then subsequently being retrieved by Homebrew via `git credential-osxkeychain get`.

GitHub/API: Don't ask for a PAT if one already exists

---

Library/Homebrew/dev-cmd/extract.rb
Library/Homebrew/test/dev-cmd/extract_spec.rb

Deprecated syntax can happen when stepping back in time, so we shouldn't start by blocking everything that doesn't meet current Homebrew syntax standards. Closes #11593.
Before:
```bash
$ brew extract -d -v --version=14.15.1 node@14 gromgit/tmp
==> Searching repository history
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
==> Trying 14.17.3 from revision f90d04c against desired 14.15.1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node@14.rb
[...] …
```

extract: ignore syntax errors during load

---

Library/Homebrew/dev-cmd/pr-automerge.rb
Library/Homebrew/dev-cmd/pr-publish.rb

-----
It's too easy to forget to, and the consequences of forgetting to pass
`--autosquash` are worse (i.e. almost always permanent) than forgetting
to pass `--no-autosquash` (i.e. just do `pr-publish --no-autosquash`
when your command fails).
See the discussion at Homebrew/homebrew-core#80717.

dev-cmd/pr-publish: pass `--autosquash` by default

---

Library/Homebrew/livecheck/strategy/sourceforge.rb

-----
This allows a `livecheck` block to check the RSS feed for a given path in a SourceForge project (e.g., `https://sourceforge.net/projects/example/rss?path=/directory`).
For example, the check for `ttfautohint` is currently failing because it's part of the `freetype` project and the latest `stable` archive for `ttfautohint` has been pushed out of the main RSS feed. Restricting the RSS feed to only the `ttfautohint` directory works as expected but, without this modification, the `Sourceforge` strategy currently modifies the URL back to the main RSS URL.
We can simply use `strategy :page_match` in a `livecheck` block (as we've been doing) but I figured it would be better to address this issue, so we don't have to override the strategy in these instances. If/when this is merged, I'll …

Sourceforge: Do not modify RSS URLs

---

Library/Homebrew/formula_cellar_checks.rb

-----
The `check_binary_arches` audit will fail any formula that produces
universal binaries. We have a handful of formulae in Homebrew/core that
do this (see any formula that does `ENV.permit_arch_flags`, for
example). Moreover, some third party taps may have their own formulae
that build universal binaries.
I've updated the check so that it ignores a formula that produces
universal binaries whenever the formula is in the appropriate allowlist.
We'll need to create one in Homebrew/core for the handful of formulae
that do (expectedly) build universal binaries.
If we don't want to maintain an allowlist, we can easily modify this to
pass over any formulae that builds compatible universal binaries.
I've also fixed the spacing of the error this audit produces whenever
there is more than one …

formula_cellar_checks: handle universal binaries in `check_binary_arches`

---

Library/Homebrew/formula_installer.rb

-----
`FormulaInstaller` calls `audit_installed` at install time, which
invokes methods in `FormulaCellarChecks`. One of these methods makes a
call to `tap_audit_exception` (cf. #11750), but this method isn't
visible in `FormulaInstaller`.
Instead of trying to replicate the logic of `tap_audit_exception` in
`FormulaAuditor` (or trying to initialise an instance of one to make the
call to `FormulaAuditor`'s implementation of it), let's just implement a
stub that assumes an exception always exists.
I'll need to think a bit about whether this is the right fix for this,
but currently the missing method error is blocking PRs in Homebrew/core,
so let's go with this for now. [1]
[1] e.g. Homebrew/homebrew-core#81388, Homebrew/homebrew-core#81582

formula_installer: add `tap_audit_exception` stub

---

Library/Homebrew/formula.rb

-----
A few Rust-related formulae in homebrew/core need to override aspects of `std_cargo_args` and this is currently more painful than it needs to be.
`git-series` can't use the `--locked` flag until the next version is released and this has been the case since late 2019. As it stands, it uses manually-defined args instead of `std_cargo_args`: `system "cargo", "install", "--root", prefix, "--path", "."`
`gnirehtet` sets different `--root` and `--path` values, so it also uses manually-defined args: `system "cargo", "install", "--locked", "--root", libexec, "--path", "relay-rust"`
These two formulae don't inherit from `std_cargo_args`, so the formulae would need to be manually updated if/when that array is updated in the future.
---
`dprint` takes a different approach, doing a naive …

Formula: Allow configuration of std_cargo_args

---

Library/Homebrew/bottle_api.rb

-----
I noticed that the error message when a bottle isn't available for the given OS could be improved by adding the name of the formula that's missing the bottle. Otherwise, if working with multiple formulae, it is not clear which is missing.

BottleAPI: include formula name in error message

---

Library/Homebrew/brew.sh

I am not sure why we also checked for HOMEBREW_FORCE_HOMEBREW_ON_LINUX.
If the minimum curl version needs to be changed, we should introduce
specific env variables for each case that needs it, instead of
asking for HOMEBREW_FORCE_HOMEBREW_ON_LINUX to be set too (which is not the case
in the linuxbrew-core repo for example)
-----

brews.sh: change HOMEBREW_MINIMUM_CURL_VERSION only for debian 7

---

Library/Homebrew/brew.sh

-----
When checking whether `HOMEBREW_AUTO_UPDATE_SECS` have passed since the latest fetch to determine whether to run a preinstall update or not, we currently check when `.git/FETCH_HEAD` in the homebrew/core tap was last updated. However, with `HOMEBREW_JSON_CORE`, homebrew/core won't be fetched on preinstall updates meaning its `FETCH_HEAD` file won't reflect new updates. THis means the modification time of `FETCH_HEAD` is not actually a measure of when the last update was run but is, instead, a measure of how long ago the user manually ran `brew update`. Additionally, if they untap homebrew/core, this check will never be hit.
Instead, check the homebrew/brew repo because it is necessary for all Homebrew installations and is really what's being updated here (i.e. not the taps).

Use Homebrew/brew when checking `HOMEBREW_AUTO_UPDATE_SECS`

---

Library/Homebrew/cmd/search.rb
Library/Homebrew/extend/os/mac/search.rb
Library/Homebrew/search.rb

-----
apply `formula` and `cask` options to `brew search --desc`, because `brew search --desc --formula` return `formula` and `cask` result.
Fixes https://github.com/Homebrew/brew/issues/11765

repair to apply `--formula` and `--cask` options to `brew search  --desc`

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/env_config.rb
Library/Homebrew/github_packages.rb

-----
Supersedes https://github.com/Homebrew/brew/pull/11339
Partially addresses https://github.com/Homebrew/brew/issues/11287
Allow using a private registry mirroring the common URL for blobs and bottles (https://ghcr.io/v2/homebrew/core). This feature worked before when the Homebrew packages registry was Bintray and this PR makes sure it works as before.
Usage example with Artifactory:
1. Create a remote Docker repository in Artifactory proxies https://ghcr.io. In my example, I named it `brew-remote`.
2. Populate `HOMEBREW_REGISTRY_ACCESS_TOKEN` environment variable with Artifactory access token and HOMEBREW_ARTIFACT_DOMAIN with a URL to Artifactory repository:
```
export HOMEBREW_REGISTRY_ACCESS_TOKEN=<artifactory-access-token>
export …
```

Add support for private registry

---

Library/Homebrew/env_config.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
docs/Manpage.md
manpages/brew.1

It no longer works under GitHub Packages and `HOMEBREW_ARTIFACT_DOMAIN` must be used instead.
Fixes https://github.com/Homebrew/brew/issues/11209

Remove HOMEBREW_BOTTLE_DOMAIN

---

Library/Homebrew/livecheck/strategy/electron_builder.rb

This change allows a query parameter to be passed to a URL to a livecheck block using the `electron_builder` strategy.
This allows the livecheck in https://github.com/Homebrew/homebrew-cask/pull/109152 to return the correct version, as a query parameter of `noCache=true` or similar needs to be passed to consistently return the latest version.
There may be a better regex to allow the query parameter in the URL.
---

livecheck: allow query parameter in electron_builder strategy url

---

Library/Homebrew/dev-cmd/bump.rb
Library/Homebrew/livecheck.rb
Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/skip_conditions.rb
Library/Homebrew/rubocops/livecheck.rb
Library/Homebrew/test/livecheck/livecheck_spec.rb
Library/Homebrew/test/livecheck/skip_conditions_spec.rb
Library/Homebrew/test/livecheck_spec.rb
docs/Brew-Livecheck.md

-----
I took a brief detour today to expand the `livecheck` block DSL to allow us to inherit livecheck information from another formula/cask (e.g., `url`, `regex`, etc.). This should work as expected for referenced formulae/casks regardless of whether they contain a `livecheck` block or simply use livecheck's default.
For example, we have various formulae in homebrew/core that use the same check as `sqlite` (e.g., `dbhash`, `lemon`, `sqldiff`, `sqlite-analyzer`) and we simply duplicate these `livecheck` blocks. If a change is made to the `sqlite` formula's `livecheck` block, it has to be manually replicated in each of the related formulae. Ideally, a change in the `sqlite` `livecheck` block would automatically be reflected in the related formulae and that's part of the goal of this …

livecheck: allow inheriting from a formula/cask

---

Library/Homebrew/cask/cask.rb
Library/Homebrew/cask/cmd/upgrade.rb
Library/Homebrew/cmd/outdated.rb

-----
Adds an additional flag `--skip-unversioned` for running brew outdated or upgrade. It skips casks that are given `version :latest`
Some documentation updates including within the terminal command outputs would also require updating.
Some of the areas I have added the flag as parameters may be superfluous at the moment.

adds an option to skip unversioned casks in outdated and upgrade command

---

Library/Homebrew/livecheck/strategy/apache.rb
Library/Homebrew/livecheck/strategy/bitbucket.rb
Library/Homebrew/livecheck/strategy/cpan.rb
Library/Homebrew/livecheck/strategy/electron_builder.rb
Library/Homebrew/livecheck/strategy/extract_plist.rb
Library/Homebrew/livecheck/strategy/git.rb
Library/Homebrew/livecheck/strategy/github_latest.rb
Library/Homebrew/livecheck/strategy/gnome.rb
Library/Homebrew/livecheck/strategy/gnu.rb
Library/Homebrew/livecheck/strategy/hackage.rb
Library/Homebrew/livecheck/strategy/header_match.rb
Library/Homebrew/livecheck/strategy/launchpad.rb
Library/Homebrew/livecheck/strategy/npm.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/livecheck/strategy/pypi.rb
Library/Homebrew/livecheck/strategy/sourceforge.rb
Library/Homebrew/livecheck/strategy/sparkle.rb
Library/Homebrew/livecheck/strategy/xorg.rb
Library/Homebrew/test/livecheck/strategy/electron_builder_spec.rb
Library/Homebrew/test/livecheck/strategy/page_match_spec.rb

-----
This PR intends to simplify early returns in a `livecheck` block's `strategy` block. Acceptable return types differ between strategies and it's currently necessary to keep these in mind when using `next` to return early from a `strategy` block.
For example, `PageMatch` (and the strategies that use it internally) will accept a string or array of strings from a `strategy` block, so it's necessary to use something like `next ""` or `next []` when doing an early return.
A recent homebrew/cask PR got me thinking about this because it used a `HeaderMatch` `strategy` block, which can only return a string but will also accept `nil`. Handling a `nil` value means that we can use `next` (with no argument) to return early from a `strategy` block and have the strategy take care of what should …

livecheck: allow nil return from strategy blocks

---

.gitignore
.sublime/homebrew.sublime-project
Library/Homebrew/dev-cmd/edit.rb

-----
Code very similar to this was removed in c6b6fc678e66668b08d31e7a55950768e0e4d687 because we had, at the time, moved away from the model where the Homebrew prefix was the repository. Now that we've actually moved back to that model, we've re-inherited exactly the same problems that inspired the original code.
In place of the original code, which specified the list of files to open in `cmd/edit`, this PR adds a Sublime Text project file and opens that with `brew edit` instead. That limits the code changes significantly, with the majority of the diff being indent-related. I've left a comment at the top of the Sublime project file to indicate how it was authored.
A similar PR to this was previously open in #10710. This version addresses Mike's comments in the original version.

edit: enable Sublime Text project view

---

Library/Homebrew/release_notes.rb

Otherwise if `git log` fails (e.g. due to missing `origin/HEAD` in my case) then it will generate a release with empty release notes.

release_notes: use `safe_popen_read`.

---

Library/Homebrew/cmd/shellenv.sh
Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

-----
Make `brew shellenv` idempotent. This implementation simply a new environment variable `HOMEBREW_SHELLENV_SET` to avoid duplicate initialization.
```console
$ /home/linuxbrew/.linuxbrew/bin/brew shellenv
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}";
export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}";
export HOMEBREW_SHELLENV_SET="/home/linuxbrew/.linuxbrew${HOMEBREW_SHELLENV_SET+:$HOMEBREW_SHELLENV_SET}";
$ eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
$ …
```

cmd/shellenv.sh: make `brew shellenv` idempotent

---

Library/Homebrew/cmd/outdated.rb

-----
Fix this:
```console
$ sw_vers
ProductName:	macOS
ProductVersion:	11.5
BuildVersion:	20G71
$ brew outdated --cask --json --greedy
Error: wrong number of arguments (given 4, expected 5)
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:143:in `outdated_info'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:153:in `block in json_info'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:134:in `map'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:134:in `json_info'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:72:in `outdated'
/usr/local/Homebrew/Library/Homebrew/brew.rb:131:in `<main>'
```

Fix brew outdated --cask --json --greedy

---

Library/Homebrew/download_strategy.rb

-----
Followup https://github.com/Homebrew/brew/pull/11766
Currently when `HOMEBREW_ARTIFACT_DOMAIN` is configured and `HOMEBREW_DOCKER_REGISTRY_TOKEN` is not, a default `QQ==` access token is used to authenticate with private registries.
This PR change this behavior: If `HOMEBREW_ARTIFACT_DOMAIN` is configured, always use the token configured in `HOMEBREW_DOCKER_REGISTRY_TOKEN`, even if empty.

Allow anonymous access in private registries

---

Library/Homebrew/cli/named_args.rb
Library/Homebrew/test/cli/named_args_spec.rb
Library/Homebrew/test/support/fixtures/receipt.json

-----
Closes #11741.
Currently, `resolve_latest_keg` has the following behavior:
- If only one keg exists (HEAD or stable), return that keg.
- Otherwise, return the latest stable keg.
This behavior doesn't handle the case where there are multiple HEAD kegs, but no stable kegs. This PR adds the following behavior to `resolve_latest_keg`:
- If there are HEAD kegs but no stable kegs, return the latest HEAD keg.

`resolve_latest_keg` should return the latest HEAD keg when no stable kegs exist

---

Library/Homebrew/exceptions.rb

I got the following error message:
Install Clang or run `brew install gcc`.Alternatively, remove the flag to attempt bottle installation.
A space is missing after the period. This change ensures a space to be inserted.
-----

Insert space

---

Library/Homebrew/api/analytics.rb
Library/Homebrew/api/bottle.rb
Library/Homebrew/api/cask.rb
Library/Homebrew/api/formula.rb
Library/Homebrew/api/versions.rb
Library/Homebrew/utils/analytics.rb

-----
Follow-up to https://github.com/Homebrew/brew/pull/11831
Fixes https://github.com/Homebrew/brew/pull/11831#issuecomment-895408324
It seems that using `alias` inside of a module that uses `module_function` does not work. Instead, define the functions directly within the module's metaclass. This means that the `alias` call actually works and the aliased functions can actually be called.
TBH I don't totally understand why `module_function` doesn't work as I thought it just copied all of the methods over to the metaclass. I still don't really understand metaclasses, though, so there might be a good reason.
Here's a model of what happened before:
```ruby
module Foo
module_function
def bar
"Hello, world!"
end
alias hello bar
end
Foo.bar   # => "Hello, world!"
Foo.hello # => NoMethodError: …
```

api: fix generic api path functions

---

Dockerfile

```
Dockerfile: run as user: linuxbrew
This commit refactors the Dockerfile in order to resolve build errors
caused by attempting to execute `brew` commands as the root user. We
need to create the `/home/linuxbrew/.linuxbrew` folder prior to copying
the local directory into `/home/linuxbrew/.linuxbrew/Homebrew` (and
ensure the appropriate user owns it), as failing to do so will create
`/home/linuxbrew/.linuxbrew` with root user and group ownership, causing
the subsequent `mkdir` command called in the second `RUN` instruction to
fail.
closes #11802
```
-----
There are additional improvements that the container image could still benefit from, namely:
* **Avoiding cloning `homebrew/homebrew-core` via `git`**. This causes the build to hang for some time (on the order of several minutes; I …

Dockerfile: run as user: linuxbrew

---

Library/Homebrew/formula.rb

-----
We have a handful of of formulae that do `std_cmake_args.reject` to
override some of the flags (e.g. emscripten, icemon, ortp, qt, klee,
watchman).
Let's try to simplify some of this code by allowing these formulae to
override these flags by passing arguments to `std_cmake_args`.
While we're here, let's update the type signature of `std_cargo_args`.

formula: allow `std_cmake_args` to take parameters

---

Library/Homebrew/brew.rb

-----
`GEM_HOME` and `GEM_PATH` are already set here, so setting up the gem environment here is not necessary and causes issues due to the assumption that `standalone/load_path` is run first. This fixes stackprof not working.
This could be refined further so that we don't allow `GEM_*` bleeding and instead insert the relevant directory into the load path via a Ruby command arg (like we do for intergration tests), to ensure better consistency in runtime behaviour between `brew prof` runs and regular env-filtered runs. That is however an extension of this PR rather than an alternative solution.
Closes https://github.com/Homebrew/brew/pull/11799

brew.rb: remove gem setup for stackprof

---

Library/Homebrew/formula_cellar_checks.rb

This is needed by [Lima](https://github.com/Homebrew/homebrew-core/pull/82723), which installs non-native binaries for supporting ARM-on-Intel / Intel-on-ARM emulation.
See https://github.com/Homebrew/homebrew-core/pull/82723#issuecomment-893232417
-----

New allow list: mismatched_binary_allowlist

---

Library/Homebrew/dev-cmd/typecheck.rb

-----
Now that sorbet works on Apple Silicon, allow the `typecheck` command to run.
Thanks @Bo98!
Closes #10210

typecheck: allow `typecheck` command to run on Apple Silicon

---

Dockerfile

-----
```
Dockerfile: remove extraneous permission modification commands
These are no longer necessary due to the fact that the second `RUN`
instruction runs as the `linuxbrew` user (as of commit
77afe94446e78e688ebde7a5e2b1249fc0a4afcd).
```
-----

Dockerfile: remove extraneous permission modification commands

---

Library/Homebrew/cli/named_args.rb

-----
Context for this change is [here](https://github.com/Homebrew/brew/pull/11824/files#r684843341).

Add revision secondary sort to `resolve_latest_keg`

---

Library/Homebrew/formula_auditor.rb
Library/Homebrew/resource_auditor.rb

-----
This PR adds an audit to ensure that the correct default branch for a Git repository is specified for `head` when using `--strict --online`. For `main` and other alternatives, we need to explicitly specify the default branch using `branch:`, as the default is `master`.
Adding an audit will ensure this is checked in PRs to add new formulae.
I haven't written a test for this audit as it would require network access (and use a real repository URL), but I'd be happy to add one if that's preferable.
(CC @vladimyr)

resource_auditor: add audit for HEAD default branch

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
If one sets `HOMEBREW_FORCE_HOMEBREW_ON_LINUX` it is unnecessary to specially create new remote to check out `homebrew/core`, it should already be the default.

bump-formula-pr: use default remote if forcing Homebrew on Linux

---

Dockerfile

-----
```
Dockerfile: use relative paths when in the /home/linuxbrew directory
Because the `WORKDIR` instruction specifies the home directory of the
`linuxbrew` user, there is no need to use absolute paths to reference
paths within the home directory, nor is there a need to call `cd` (this
is actually an anti-pattern [0]) to move into a subdirectory before
creating folders.
[0]: https://github.com/hadolint/hadolint/wiki/DL3003
```
-----

Dockerfile: use relative paths when in the /home/linuxbrew directory

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml

… reporting
-----
Regarding previous discussions on mirror sites https://github.com/Homebrew/discussions/discussions/1906, we have created a discussion https://github.com/Homebrew/discussions/discussions/1917 for mirror maintainers to update mirror information. And then, in this PR, we modified the issue templates to remind our users to see if the issue is related to the mirror sites. Now users could post issues to the best-fit place when they find Homebrew mirrors are not working.
cc @MikeMcQuaid for review, thanks!

.github/ISSUE_TEMPLATE/bug.yml: add instructions for mirror sites bug reporting

---

Library/Homebrew/extend/os/mac/diagnostic.rb

-----
This covers the case where the user has CLT 12.0-12.4 on Big Sur and is setting up the build env via non-build-from-source means (e.g. `bottle :unneeded`). We no longer support those versions of the CLT and they will throw errors if used.

os/mac/diagnostic: check min CLT version on env setup

---

Library/Homebrew/extend/os/linux/formula.rb
Library/Homebrew/formula.rb

-----
This method takes an optional array of `Pathnames`s or `Strings`s and
extracts the native slice from the specified universal binary. If no
parameter is supplied, this is done on all compatible universal binaries
in a formula's keg.
`deuniversalize_machos` is a no-op on Linux.
I still need to look into a) error handling, and b) whether using this
method requires codesigning on ARM.
I've also added signatures to the methods in `extend/os/linux/formula`.

formula: add `deuniversalize_machos` method

---

Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/strategy/apache.rb
Library/Homebrew/livecheck/strategy/bitbucket.rb
Library/Homebrew/livecheck/strategy/cpan.rb
Library/Homebrew/livecheck/strategy/electron_builder.rb
Library/Homebrew/livecheck/strategy/extract_plist.rb
Library/Homebrew/livecheck/strategy/git.rb
Library/Homebrew/livecheck/strategy/github_latest.rb
Library/Homebrew/livecheck/strategy/gnome.rb
Library/Homebrew/livecheck/strategy/gnu.rb
Library/Homebrew/livecheck/strategy/hackage.rb
Library/Homebrew/livecheck/strategy/header_match.rb
Library/Homebrew/livecheck/strategy/launchpad.rb
Library/Homebrew/livecheck/strategy/npm.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/livecheck/strategy/pypi.rb
Library/Homebrew/livecheck/strategy/sourceforge.rb
Library/Homebrew/livecheck/strategy/sparkle.rb
Library/Homebrew/livecheck/strategy/xorg.rb
Library/Homebrew/test/livecheck/strategy/page_match_spec.rb

-----
Livecheck's strategies all contain a `#find_versions` method that takes input (e.g., a `url`, `regex`, `cask`, etc.) and uses it to identify versions from a source. All of the strategies except for `ExtractPlist` expect that a URL will be provided. `ExtractPlist` is an exception (in many unfortunate ways), as it expects a cask instead of a URL.
When `ExtractPlist` was created, a `cask` parameter was added to every `#find_version` method. This is because livecheck uses all the possible arguments when it calls the method, regardless of the strategy (i.e., it doesn't cater the arguments to what the strategy expects). If a strategy didn't have the `cask` parameter but a named `cask` argument was provided, Ruby would give an error.
Ideally, a given `#find_versions` method should only be …

Refactor #find_versions parameters in strategies

---

Dockerfile

-----
This broke the CI in the test-bot repo: https://github.com/Homebrew/homebrew-test-bot/pull/653#issuecomment-900950998
cc @dawidd6 @sudoforge

Dockerfile: revert #11818 and #11819

---

Library/Homebrew/download_strategy.rb

-----
`meta[:headers]` should be an array of strings - not an array of arrays of strings.

download_strategy: fix error when using custom headers with a redirect

---

Library/Homebrew/livecheck/strategy.rb
Library/Homebrew/livecheck/strategy/apache.rb
Library/Homebrew/livecheck/strategy/bitbucket.rb
Library/Homebrew/livecheck/strategy/cpan.rb
Library/Homebrew/livecheck/strategy/git.rb
Library/Homebrew/livecheck/strategy/github_latest.rb
Library/Homebrew/livecheck/strategy/gnome.rb
Library/Homebrew/livecheck/strategy/gnu.rb
Library/Homebrew/livecheck/strategy/hackage.rb
Library/Homebrew/livecheck/strategy/launchpad.rb
Library/Homebrew/livecheck/strategy/npm.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/livecheck/strategy/pypi.rb
Library/Homebrew/livecheck/strategy/sourceforge.rb
Library/Homebrew/livecheck/strategy/xorg.rb
Library/Homebrew/test/livecheck/strategy/apache_spec.rb
Library/Homebrew/test/livecheck/strategy/bitbucket_spec.rb
Library/Homebrew/test/livecheck/strategy/cpan_spec.rb
Library/Homebrew/test/livecheck/strategy/github_latest_spec.rb
Library/Homebrew/test/livecheck/strategy/gnome_spec.rb
Library/Homebrew/test/livecheck/strategy/gnu_spec.rb
Library/Homebrew/test/livecheck/strategy/hackage_spec.rb
Library/Homebrew/test/livecheck/strategy/launchpad_spec.rb
Library/Homebrew/test/livecheck/strategy/npm_spec.rb
Library/Homebrew/test/livecheck/strategy/pypi_spec.rb
Library/Homebrew/test/livecheck/strategy/sourceforge_spec.rb
Library/Homebrew/test/livecheck/strategy/xorg_spec.rb

-----
Some of livecheck's strategies generate a URL and/or regex from the provided `url` in their `#find_versions` methods. In the future, we'll need to be able to access the URL that a strategy generates [before/without running `#find_versions`] as part of content caching (i.e., not fetching a URL more than once in a given run).
This PR extracts the URL/regex generating code in related strategies into `#generate_input_values` methods, which takes a URL string and returns a hash containing generated values. Not only is this necessary for the future caching feature, this setup also allows us to test this code. Up to this point, we haven't been able to write related tests because `#find_versions` makes a network request and I won't be working on stubbing these requests until later (i.e., …

livecheck: move url/regex generation into methods

---

Library/Homebrew/formula.rb

-----
Based on feedback from #11756.

formula: make `extract_macho_slice_from` private

---

Library/Homebrew/livecheck/strategy/page_match.rb

-----
Casks with a `livecheck` block using `PageMatch` but not using `#regex` are currently failing (see #11882) because I recently introduced code in `PageMatch#find_versions` that returns early when a regex isn't provided. I had tested this change on homebrew/core, where all the related `strategy` blocks use `#regex` and pass it into the `strategy` block (i.e., `do |page, regex|`), but I didn't test it on homebrew/cask.
This PR fixes the issue by updating the condition to require either a regex or `strategy` block. I'll create a follow-up PR to add a related test and maybe modify `PageMatch#find_versions`'s parameters (making `regex` nilable again) but I wanted to push out this fix in the interim time.

PageMatch#find_versions: Fix return conditions

---

Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/test/livecheck/strategy/page_match_spec.rb

-----
This is a follow-up to #11888, where I modified the early return conditions for `PageMatch#find_versions` to allow a `strategy` block to [temporarily] act as a substitution for a `regex`. That PR was a fix for an issue affecting some casks that don't follow established patterns, so I wanted to get it merged quickly. This PR contains related changes that I would have handled in #11888 if I had more time.
This adds a test to ensure that `PageMatch#find_versions` works when a block is provided but a regex isn't. I've added comments to explain that this is temporary and the pattern in the test shouldn't be followed.
Similarly, I've updated related method signatures and documentation comments to reflect that the `regex` parameter is technically nilable for now. The method signature …

PageMatch: Expand #find_versions tests

---

Library/Homebrew/tap_auditor.rb

-----
For core formulae, `Formula#full_name` is the same as `Formulae#name`, but this is not true for other taps. The formula names that need to go in the exception lists are the short names (because this is what we compare them to during the audit and changing this adds backwards incompatibility). I think this makes sense because the lists are per-tap so short names are sufficient.
`TapAuditor` also checks to make sure that every formula listed in an exception list actually exists in that tap. This is done by comparing each entry to `Tap#formula_names`. There is a problem here because `Tap#formula_names` returns the full name of each formula in the tap. For core formulae, `Formula#full_name` is the same as `Formulae#name`, but this is not true for other taps. Therefore, adding an audit …

tap_auditor: use short names when checking exception lists

---

Library/Homebrew/formula_auditor.rb

If the download url is using brewed curl, use that too for the homepage check.
Ideally one would introduce the "using: :homebrew_curl" stanza for the homepage
line in the DSL, but it is easier to implicitely use the same logic
for homepages and url's and define the "using:" only once.
-----

formula_auditor: use brewed curl for homepage check when needed

---

Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
Library/Homebrew/unversioned_cask_checker.rb

- [] Have you successfully run `brew tests` with your changes locally?
-----
Adds the ability for unversioned_cask_checker to look inside `info.plist` files within quick look plugins.
This also allows the extract_plist livecheck strategy to look inside the plugin file also.

unversioned_cask_checker: check for versions in qlplugins

---

Library/Homebrew/dev-cmd/typecheck.rb

-----
The problem with it was solved in Sorbet 0.5.9051.

dev-cmd/typecheck: stop suppressing error 5067

---

Library/Homebrew/sandbox.rb

-----
This disconnects the sandbox from directly accessing the parent terminal.
Due to the wide range of formulae we have and how some of the tests we have can be pretty picky on the terminal, particularly for those that do things like manually setting `TERM`, changing the `winsize` or doing some fancy things in `expect`, I can't give 100% assurances this will be regression free but it does seem the work on a couple that I tried. It's very much possible nothing will break and I'm being overly cautious - there's just too much variation for me to guarantee anything.
**In the event someone feels the need to revert this quickly, but the only thing breaking is (multiple) tests, I suggest a partial revert by adding a kwarg to conditionally disable this for tests (but not builds/postinstall) …

sandbox: start sandbox in a pseudoterminal

---

Library/Homebrew/cask/cask.rb
Library/Homebrew/cli/named_args.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/outdated.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/untap.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/cmd/update.sh
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/extend/os/mac/tap.rb
Library/Homebrew/formula.rb
Library/Homebrew/formulary.rb
Library/Homebrew/tap.rb
Library/Homebrew/test/api/bottle_spec.rb
Library/Homebrew/test/formulary_spec.rb

-----
Follow-up to https://github.com/Homebrew/brew/pull/11859
Now that this variable allows formulae _and_ casks to be installed from the API, the old name doesn't quite fit.
I'd like to do this now before I ask maintainers to start to try this stuff out so that no one (except me) has to make any changes to their environments. Since this is currently undocumented, it shouldn't be a big issue for us.

Rename `HOMEBREW_JSON_CORE` to `HOMEBREW_INSTALL_FROM_API`

---

docs/Formula-Cookbook.md

-----
Couldn't find this info before.

Mention `bump-formula-pr` in update section

---

Library/Homebrew/cleanup.rb
Library/Homebrew/env_config.rb

-----
This allows users to set `HOMEBREW_NO_CLEANUP_FORMULAE` to a
comma-separated list of formula that `brew` will refuse to clean with
`brew cleanup`.
We currently allow a less granular version of this with
`HOMEBREW_NO_INSTALL_CLEANUP`. All this changes is how much control
users have over what is and isn't cleaned.
Fixes #11924.

cleanup: allow users to specify formulae to skip cleaning

---

Library/Homebrew/formula_creator.rb

-----
It is consistent with the go formulae practices we are doing in the homebrew-core
This is [the article reference](https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/) for shrinking the binary (thanks @bayandin)

create(go): add `-s -w` ldflags to reduce the artifact size

---

Library/Homebrew/upgrade.rb

upgrade: fetch all formulae before installing

---

Library/Homebrew/cask/cmd/upgrade.rb
Library/Homebrew/cleanup.rb
Library/Homebrew/cmd/migrate.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/migrator.rb
Library/Homebrew/upgrade.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

-----
Currently, a dry run of `brew upgrade` only lists which dependents of the given packages will be auto-upgraded. This adds a list of dependencies to be auto-upgraded to the output.
Before:
```
$ brew upgrade -n nghttp2 harfbuzz
==> Would upgrade 2 outdated packages:
nghttp2 1.43.0 -> 1.44.0
harfbuzz 2.8.1 -> 2.9.0
==> Would upgrade 4 dependents:
unbound 1.13.1 -> 1.13.2, gnupg 2.3.1_1 -> 2.3.2, pango 1.48.5 -> 1.48.9, gtk+3 3.24.29 -> 3.24.30
==> No currently broken dependents found!
Warning: If they are broken by the upgrade they will also be upgraded or reinstalled.
```
After:
```
$ brew upgrade -n nghttp2 harfbuzz
==> Would upgrade 2 outdated packages:
nghttp2 1.43.0 -> 1.44.0
harfbuzz 2.8.1 -> 2.9.0
==> Would upgrade 3 dependencies for nghttp2:
openssl@1.1 1.1.1k -> 1.1.1l, cmake …
```

upgrade: list upgradeable dependencies on dry run

---

docs/Cask-Cookbook.md
docs/Formula-Cookbook.md
docs/Homebrew-linuxbrew-core-Maintainer-Guide.md

-----
Replaces `$(brew --repository)/Library/Taps/homebrew/homebrew-cask` with `$(brew --repo homebrew/cask)`

docs: use `brew --repository` shorthand in Cask Cookbook

---

Library/Homebrew/utils/curl.rb

-----
Using a browser or `wget`, opening https://www.crushftp.com/early10/CrushFTP10.zip sets some cookies and then redirects to https://www.crushftp.com/CrushFTP10.zip
Using `curl` or attempting to directly download https://www.crushftp.com/CrushFTP10.zip fails because it requires the cookies that are set by https://www.crushftp.com/early10/CrushFTP10.zip
As seen in https://github.com/Homebrew/homebrew-cask/pull/109237, these cookies can be set for `brew install` but `brew audit` still fails. This can be fixed by adding `--cookie-jar /dev/null` to the `curl` arguments, which makes the cookies persist even after a redirect.
Additionally, I've added a `retry` to `download_strategy.rb` that makes it unnecessary to set cookies in https://github.com/Homebrew/homebrew-cask/pull/109237.

curl: echo any cookies received on a redirect

---

Library/Homebrew/cli/args.rbi
Library/Homebrew/cmd/--cache.rb
Library/Homebrew/extend/os/mac/utils/bottles.rb
Library/Homebrew/fetch.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula.rbi
Library/Homebrew/software_spec.rb
Library/Homebrew/utils/bottles.rb

-----
This can be tested by opening a formula, deleting/commenting out the bottle sha256 for your macOS version, and then running `brew fetch --bottle-tag=<different macOS tag> <formula name>`

fetch: fix `--bottle-tag` when unbottled on host system

---

Library/Homebrew/sandbox.rb
Library/Homebrew/test/sandbox_spec.rb

-----
This should improve compatibility with some tests sensitive to the terminal size in the non-tty (CI) environment, such as `oakc`.

sandbox: fallback to tput for winsize

---

Library/Homebrew/rubocops/lines.rb
Library/Homebrew/test/rubocops/text/miscellaneous_spec.rb

This will be reimplemented in https://github.com/Homebrew/brew/pull/11955 but this allows us to merge the homebrew-core changes before that PR is merged.
Closes https://github.com/Homebrew/brew/pull/11946

rubocops/lines: remove OS.mac?/OS.linux? check.

---

Library/Homebrew/formula_installer.rb

-----
Fix a singular reference to how a maximum macOS requirement used to be specified. (xref: Homebrew/brew#662)

formula_installer: update syntax of maximum macOS check

---

Library/Homebrew/env_config.rb

Fix #11974
brew use bat's default config path not $HOMEBREW_BAT_CONFIG_PATH
-----

edit: update $HOMEBREW_BAT_CONFIG_PATH default

---

Library/Homebrew/cask/cmd/upgrade.rb
Library/Homebrew/cask/installer.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/messages.rb
Library/Homebrew/test/messages_spec.rb

-----
`Messages` isn't marked as a private API, should I maintain backwards compatibility?

messages: record cask installations

---

Library/Homebrew/livecheck/strategy.rb

-----
When I originally migrated livecheck to `curl`, the errors we were encountering typically started with `curl: ` and a number in parentheses before the error message (e.g., `curl: (60) SSL certificate problem: certificate has expired`). However, `curl` produces some errors that don't adhere to this format.
In some cases, the error message doesn't include a leading number in parentheses. Additionally, some errors can include multiple messages. For example:
```
curl: option --something: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```
With this in mind, it's necessary to loosen the regex that's used to identify curl error messages and to use `#scan` to collect all of the error message lines in `stderr`. Otherwise we incorrectly miss certain error messages …

Strategy: Improve curl error message finding

---

Library/Homebrew/utils/shared_audits.rb

-----
Not sure if this check does anything with change, or if it is a no-op.
The existing check has a problem where CI runner timezone can impact behavior of prerelease output. `Date.parse` will ignore the time/timezone and parse the date portion.
For example, https://github.com/Homebrew/homebrew-core/pull/83805

audit: gitlab prerelease check keep time/zone

---

Library/Homebrew/style.rb

-----
set `shellcheck disable` to avoid the warning message about `HOMEBREW_CORE_REPOSITORY` of `brew style`.
```bash
In /usr/local/Homebrew/Library/Homebrew/brew.sh line 341:
HOMEBREW_CORE_REPOSITORY="${HOMEBREW_LIBRARY}/Taps/homebrew/homebrew-core"
^----------------------^ SC2034: HOMEBREW_CORE_REPOSITORY appears unused. Verify use (or export if used externally).
```

require latest shellcheck version

---

Library/Homebrew/extend/os/mac/caveats.rb
Library/Homebrew/test/caveats_spec.rb

This might be an oversimplification, but should resolve issues with multi-word arguments, eg:
> Or, if you don't want/need a background service you can just run:
/opt/homebrew/opt/nginx/bin/nginx -g daemon off;
fails, but 
> Or, if you don't want/need a background service you can just run:
/opt/homebrew/opt/nginx/bin/nginx -g 'daemon off;'
succeeds
-----

Wrap mac 'brew info' multi-word service command parameters in single quotes

---

Library/Homebrew/api.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/livecheck/strategy.rb
Library/Homebrew/test/utils/curl_spec.rb
Library/Homebrew/utils/curl.rb

-----
`Utils::Curl#curl_args` seems like it intends to accept `:connect_timeout`, `:max_time`, and `:retry_max_time` options but the code that adds arguments for these values uses variables that aren't defined in this scope (`connect_timeout`, `max_time`, and `retry_max_time` respectively). The related code gives an error like ```NameError (undefined local variable or method `connect_timeout' for main:Object)``` when these options are provided to `#curl_args`.
~This PR updates this code to use the `options` value for each of these, so this will work as intended. This also modifies the inline conditions to ensure these values are numeric, as a non-numeric value would cause `#round` (and `curl`) to error.~
After discussion, this PR updates `#curl_args` to use named parameters instead of …

Curl: Fix #curl_args options

---

Library/Homebrew/sandbox.rb

-----
Fixes https://github.com/Homebrew/brew/issues/11984
This PR switches from the current method of using `raw!` and then `cooked!` to reset the Sandbox TTY to just using `raw` which automatically restores the original TTY state (and also is the recommended method in the [docs](https://docs.ruby-lang.org/en/2.2.0/IO.html#method-i-raw)). Using this approach the TTY state should always be properly restored, including the `echonl` and `istrip` flags that are not currently reset in all cases.

Restore original TTY state after Sandbox

---

Library/Homebrew/extend/ENV/super.rb
Library/Homebrew/extend/os/linux/extend/ENV/super.rb
Library/Homebrew/extend/os/mac/extend/ENV/super.rb

This allows us to stop repeatedly hardcoding this on macOS/Linux in formulae.

ENV/super: add `shims_path` helper method.

---

.github/release.yml

-----
This will make https://github.com/Homebrew/brew/releases/tag/3.2.11 more like what we had before where dep updates were excluded.

Exclude bot commits from new release notes

---

Library/Homebrew/formula.rb
Library/Homebrew/formula_support.rb
Library/Homebrew/rubocops/lines.rb
Library/Homebrew/rubocops/shared/helper_functions.rb
Library/Homebrew/test/rubocops/text/on_os_conditionals_spec.rb

Recommend the use of `on_macos` and `on_linux` unless we're in `def install`, `def post_install` or `test do` in which case recommend `OS.mac?` and `OS.linux?` instead.
TODO: 
Fixes https://github.com/Homebrew/brew/issues/11687

rubocops/lines: recommend on_os/OS.os? based on context.

---

Library/Homebrew/rubocops/lines.rb

Exclude and comment the cases the autocorrect currently doesn't work.
Follow-up from #11955.

rubocops/lines: add some OS cop comments/exceptions.

---

Library/Homebrew/formula_installer.rb

-----
Fix for #11989
#11940 and #11963 cause the method `compute_dependencies` to be invoked before any formulae have been installed, so dependencies must be recomputed at installation.

install, upgrade: recompute dependencies before installation

---

Library/Homebrew/rubocops/uses_from_macos.rb
Library/Homebrew/test/support/helper/spec/shared_examples/formulae_exist.rb

Revert "rubocops: allow uses_from_macos `openssl@3`"

---

Library/Homebrew/os/mac/pkgconfig/12/expat.pc
Library/Homebrew/os/mac/pkgconfig/12/libcurl.pc
Library/Homebrew/os/mac/pkgconfig/12/sqlite3.pc

-----
These still had Big Sur version info. Updated to match the version info as of SDK build 21A5304f.
Needed for `brew tests` to pass on Monterey.

os/mac/pkgconfig/12: update version info
