Homebrew/brew

.github/workflows/triage.yml

-----
This helps prevent double comments/approvals when performing two actions in quick succession. This includes opening a PR with a label already assigned as this issues two events.

workflows/triage: limit concurrent runs

---

Library/Homebrew/extend/os/mac/diagnostic.rb

-----
These tests always failed on new macOS versions since `brew (re)install` outputs a prerelease macOS warning to stderr. Given `brew tests` is useful for us in verifying that `brew` is working correctly on a new macOS, this is more annoying than useful.
Needed for `brew tests` to pass on Monterey.

test/cmd/(re)install_spec: don't fail on prerelease macOS

---

Library/Homebrew/install.rb
Library/Homebrew/upgrade.rb

-----
Fix for #11900
The `prelude` method checks if the formula has already been installed, so it should be invoked before printing any install or upgrade messages.

install, upgrade: don't print message if formula already installed

---

Library/Homebrew/formula_auditor.rb

This will enable https://github.com/Homebrew/homebrew-core/pull/84910 which will enable https://github.com/Homebrew/brew/pull/12008.

formula_auditor: allow uses_from_macos for aliases.

---

Library/Homebrew/os.rb

-----
This will allow us to replace code like
```ruby
os = if OS.mac?
"Darwin"
else
"Linux"
end
```
with a call to `OS.uname`. Doing
```bash
rg '= (if )?OS\.(mac|linux)\?'
```
returns about 70 matches, so there are probably at least a handful of
formulae that could be simplified by this.
Idea for a follow-up: add an audit that disallows hardcoding `/[Dd]arwin/` or `/[Ll]inux/` in string literals.

os: add `uname` method

---

Library/Homebrew/service.rb
Library/Homebrew/test/service_spec.rb

This enables services to be run with the "Interactive" `ProcessType` value; in particular, this avoids performance issues such as skipping when playing music in `mpd`. See this previous PR, which added `ProcessType` for the old `plist` method:
https://github.com/Homebrew/homebrew-core/pull/19410
The `ProcessType` plist key was lost in the conversion to the service DSL,
so this is just reinstating it:
https://github.com/Homebrew/homebrew-core/commit/483ad1fdfa29f10441b5de4386173e68f4b11555
I was experiencing music skipping in `mpd` and confirmed that adding the "Interactive" `ProcessType` in a custom plist resolved it.
The possible values are as described in the [launchd manpage](https://www.manpagez.com/man/5/launchd.plist/). I didn't see any [analogous …

Add process_type to service DSL

---

Library/Homebrew/cli/named_args.rb
Library/Homebrew/cmd/list.rb

-----
solve  https://github.com/Homebrew/brew/issues/11983

brew list shows cask without option

---

Library/Homebrew/formula_installer.rb
Library/Homebrew/install.rb
Library/Homebrew/upgrade.rb

install, upgrade: check if formula can be installed before fetching

---

Library/Homebrew/cmd/vendor-install.sh

-----
PR #11070 drops the support for users to download `portable-ruby` from `HOMEBREW_BOTTLE_DOMAIN`. Users cannot use geolocalized mirrors to speed up downloading and only packages host on GitHub are supported. (Ref https://github.com/tuna/issues/issues/1224#issuecomment-917467113 and https://github.com/tuna/mirror-web/pull/292#issuecomment-917622256)
This PR takes the URL from `HOMEBREW_ARTIFACT_DOMAIN` back and adds the URL from `HOMEBREW_ARTIFACT_DOMAIN` (as documented for this environment variable).
This implementation may be a bit tricky to use the `eval` statement to expand an array from the name.
```bash
read -r -a VENDOR_URLs <<< "$(eval "echo "\$\{${VENDOR_NAME}_URLs[@]\}"")"
```
------
Some tests:
- Unset `HOMEBREW_ARTIFACT_DOMAIN` and `HOMEBREW_BOTTLE_DOMAIN`:
```console
$ …
```

cmd/vendor-install.sh: allow download vendors from `HOMEBREW_ARTIFACT_DOMAIN` and `HOMEBREW_BOTTLE_DOMAIN`

---

Library/Homebrew/os/linux.rb
Library/Homebrew/sorbet/rbi/todo.rbi

-----
Sorbet could end having both `os/mac` and `os/linux` in memory, so this return could have gotten mistaken for `MacOS::Version::NULL`. This shouldn't change a thing at runtime but clears up a TODO item in the Sorbet RBI.

os/linux: fix Version::NULL type mixup

---

Library/Homebrew/install.rb
Library/Homebrew/upgrade.rb

-----
In #12024, I moved `rescue FormulaInstallationAlreadyAttemptedError` to `Upgrade.install_formula` but also should have moved `formula_installer.check_installation_already_attempted`

install, upgrade: fix installation attempt check

---

Library/Homebrew/extend/os/mac/software_spec.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_auditor.rb
Library/Homebrew/language/perl.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/os/mac/formula_spec.rb
Library/Homebrew/test/os/mac/software_spec_spec.rb

-----
Hopefully fixes CI. Kinda rushed this so not tested.
TODO: adjust any `uses_from_macos_elements` checks to also consider the case where the element is a hash (e.g. `"dep" => :build`).

Set uses_from_macos_elements in all cases

---

Library/Homebrew/cli/args.rbi
Library/Homebrew/dev-cmd/bump-revision.rb

-----
Add a flag to write the changes made by `brew bump-revision` without committing them. This is the same concept as the `--write` switch in `brew bump-formula-pr`. This would be useful when we need to bump the revision but also do other things in the formula, such as migrating some dependencies.
While the changes work, I couldn't get `brew typecheck` to pass locally. I'm getting
```
dev-cmd/bump-revision.rb:70: Method write? does not exist on Homebrew::CLI::Args https://srb.help/7003
70 |        unless args.write?
^^^^^^^^^^^
```
I tried to update the RBI files but that didn't solve the issue. Actually, no change I made in the `bump_revision_args` block were reflected in the errors raised by `brew typecheck`.

bump-revision: add --write switch

---

Library/Homebrew/dev-cmd/extract.rb
Library/Homebrew/sorbet/rbi/todo.rbi

-----
This was needed as a temporary measure due to some dependency-related deprecation. `DependencyCollector::Compat` no longer exists so this monkey patch is never invoked and can be removed.

dev-cmd/extract: remove old DependencyCollector::Compat handling

---

Library/Homebrew/rubocops/uses_from_macos.rb

It makes more sense to use the unversioned formulae with `uses_from_macos` because macOS isn't shipping multiple versions of this.
If you wish to e.g. pin to a specific version you can do that by specifying the dependency directly in an `os_linux` block.

rubocops/uses_from_macos: remove versioned aliases.

---

Library/Homebrew/brew.sh
Library/Homebrew/utils/ruby.sh
bin/brew
docs/Installation.md

-----
Implement `which` in a more elegant way using the `bash` built-in command `type -P`. We define the function `which` in `brew.sh` to avoid using the `/usr/bin/which` by mistake.
BTW, `type -P` command is only available in `bash`, and `zsh` does not support `type -P`. Besides, the behaviors of `type -p` on `bash` and `zsh` are different.
On `bash`:
```console
$ type -ap python3
/home/linuxbrew/.linuxbrew/bin/python3
/usr/bin/python3
$ type -aP python3
/home/linuxbrew/.linuxbrew/bin/python3
/usr/bin/python3
```
On `zsh`:
```console
$ type -ap python3
python3 is /home/linuxbrew/.linuxbrew/bin/python3
python3 is /usr/bin/python3
$ type -aP python3
type: bad option: -P
```
We need `bash` to run `brew`.
Ref #12027, Homebrew/install#575.

brew.sh: alias `which` as `type -P`

---

Library/Homebrew/rubocops/lines.rb

rubocops/lines: be less strict about `OS.{mac,linux}?` in taps.

---

.github/workflows/docker.yml
.github/workflows/doctor.yml
.github/workflows/sorbet.yml
.github/workflows/spdx.yml
.github/workflows/tests.yml
.github/workflows/triage.yml
.github/workflows/update-man-completions.yml
.github/workflows/vendor-gems.yml

-----
All of these could potentially be `write` in some scenario (e.g. vendor gem update). This is unnecessary so it's best play a bit safer and reduce these to the minimum possible permissions.
Tests workflow might need tweaking but I think the rest are correct.

workflows: reduce GITHUB_TOKEN permissions

---

Library/Homebrew/style.rb
Library/Homebrew/utils/shfmt.sh

-----
I refactor some functions in `utils/shfmt.sh` in #12044 to reuse code fragments and improve code readability.
And adding exit code of `run_shfmt` to `brew style` is needed in CI tests.

style: add shfmt exit status to `brew style`

---

Library/Homebrew/exceptions.rb
Library/Homebrew/test/cli/named_args_spec.rb

-----
The backtrace for the internal error for `FormulaUnreadableError` is the much more useful one.

exceptions: set backtrace for FormulaUnreadableError

---

Library/Homebrew/shims/super/cc
Library/Homebrew/test/bash_spec.rb

-----
Should fix errors like this one:
```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5: 3: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5: [[: not found
```
I don't know if there is any special reason we run this particular shim via plain sh.
Found here: https://github.com/Homebrew/homebrew-core/pull/85282/checks?check_run_id=3624010217
Bug introduced in: https://github.com/Homebrew/brew/pull/12044

shims/super/cc: run in bash shell

---

Library/Homebrew/extend/os/mac/missing_formula.rb
Library/Homebrew/test/missing_formula_spec.rb

-----
The reasons for disallowing `texlive` on macOS have been irrelevant for many years now and we have a PR to add it: https://github.com/Homebrew/homebrew-core/pull/83738.

missing_formula.rb: don't disable texlive

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/extend/os/linux/software_spec.rb
Library/Homebrew/extend/os/mac/utils/bottles.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb
Library/Homebrew/test/software_spec/bottle_spec.rb
Library/Homebrew/test/utils/bottles/collector_spec.rb
Library/Homebrew/utils/bottles.rb

-----
Goals:
* Stronger typing (rather than passing around hashes everywhere)
* Less confusing names (e.g. `checksum_for` returning cellar information)
* Remove relics from old bottle spec DSL.
Additions:
* `BottleSpecification#tag_specification_for`
- For a given tag, returns a new `TagSpecification` object containing the actual tag (since it may choose an older OS), the checksum and the cellar value.
* `Utils::Bottles::Collector#specification_for`
- Backend for the above.
* Add `tag` parameter to `BottleSpecification#compatible_locations?` (default: tag for user's OS)
- `Bottle#compatible_locations?` now uses this internally.
* Add `tag` parameter to `BottleSpecification#skip_relocation?` (default: tag for user's OS)
- `Bottle#skip_relocation?` now uses this internally.
* …

Revamp APIs around bottle specifications

---

Library/Homebrew/cmd/--cache.rb
Library/Homebrew/cmd/fetch.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb

-----
`Formula#bottle` has a quirk where it returns nil if a bottle with an incompatible location is found, while `bottle_for_tag` does not do this.
Fixes #12099.

formula_installer: fix error if a compatible bottle was not found

---

Library/Homebrew/cmd/outdated.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_cellar_checks.rb
Library/Homebrew/tab.rb

-----
This PR should fix the issues that `HOMEBREW_INSTALL_FROM_API` brought to HEAD formulae. Now, `brew install --HEAD`, `brew outdated --fetch-HEAD`, `brew upgrade --fetch-HEAD` should all work as expected.
CC @carlocab (if you could confirm that this fixes your issue I'd appreciate it, sorry I didn't get to fixing it earlier)

install: fix `HEAD` installations with `HOMEBREW_INSTALL_FROM_API`

---

Library/Homebrew/formula_cellar_checks.rb

-----
Currently, if formula `foo` ships both universal and non-native
binaries and `foo` is on both allowlists, then `brew audit --strict`
errors out with an empty error message:
❯ brew audit --strict foo
foo:
*
Error: 1 problem in 1 formula detected
Let's fix this (admittedly obscure) corner case by returning early when
a formula is present on both allowlists.

formula_cellar_checks: fix edge case handling in `check_binary_arches`

---

Library/Homebrew/rubocops/all.rb
Library/Homebrew/rubocops/extend/formula.rb
Library/Homebrew/rubocops/shared/helper_functions.rb

-----
The warning appeared again after load ordering changes caused by gem updates (`rubocop-sorbet` now loads `parser/current`).

rubocops: silence parser warning

---

Library/Homebrew/cask/cmd/upgrade.rb
Library/Homebrew/cmd/upgrade.rb

-----
The `upgrade_casks` method already has parameters for `greedy_latest` and `greedy_auto_updates` but they were unused.

upgrade: use `greedy_*` method parameters

---

Library/Homebrew/cask/installer.rb

-----
In the string ``"`--skip-cask-deps` is set; skipping installation of #{@cask}"``, `@cask` should be `cask_or_formula` because `cask_or_formula` is the dependency that's being skipped.

install: fix --skip-cask-deps message

---

Library/Homebrew/brew.sh
docs/Homebrew-on-Linux.md
docs/Installation.md

-----
In the installer ([Homebrew/install](https://github.com/Homebrew/install)), we only officially support three default prefixes (`/usr/local`, `/opt/homebrew` and `/home/linuxbrew/.linuxbrew`). The prefix `~/.linuxbrew` is only available in interactive mode. Discussed in Homebrew/install#582 and Homebrew/install#583, we would not support the non-default prefixes in our official installer (including `~/.linuxbrew` https://github.com/Homebrew/install/pull/583#issuecomment-927826916).
For users who wants non-default prefixes or don't have `sudo` privillages, they should use the [Untar-anywhere](https://docs.brew.sh/Installation#untar-anywhere) / [Alternative-installation](https://docs.brew.sh/Homebrew-on-Linux#alternative-installation) methed …

brew.sh: remove annoying prompts when homebrew/core not tapped

---

Library/Homebrew/cxxstdlib.rb

-----
As of 04abc51, `CompatibilityError` and `include CompilerConstants` can be deleted.

cxxstdlib: delete unused CompatibilityError class

---

Library/Homebrew/cmd/log.rb

-----
add `--formula` and `--cask` options to `brew log`

add formula and cask options to cmd `brew log`

---

Library/Homebrew/style.rb

If you do `brew style --fix .` in `HOMEBREW_REPOSITORY` it behaves very weirdly and uses the incorrect rules. If this is passed, assume that people want the same behaviour as `brew style --fix`.
While we're here, do some argument naming and code cleanup.

style: better handle HOMEBREW_REPOSITORY.

---

Library/Homebrew/development_tools.rb
Library/Homebrew/extend/os/linux/development_tools.rb
Library/Homebrew/extend/os/mac/development_tools.rb
Library/Homebrew/extend/os/mac/extend/ENV/shared.rb
Library/Homebrew/extend/os/mac/hardware.rb
Library/Homebrew/os/linux/glibc.rb
Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/sdk.rb
Library/Homebrew/os/mac/xcode.rb
Library/Homebrew/os/mac/xcode.rbi
Library/Homebrew/sorbet/rbi/upstream.rbi

-----
```
Redefining the existing method DevelopmentTools.custom_installation_instructions as a method alias https://srb.help/5037
35 |    alias custom_installation_instructions installation_instructions
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
```diff
-alias custom_installation_instructions installation_instructions
+def custom_installation_instructions
+  installation_instructions
+end
```
-----
```
Expected T::Boolean but found T.nilable(Pathname) for method result type https://srb.help/7005
29 |    end
^^^
```
```diff
def installed?
-  locate("clang") || locate("gcc")
+  locate("clang").present? || locate("gcc").present?
end
```
-----
```
This code is unreachable https://srb.help/7006
21 |    return false if MacOS::Xcode.version && MacOS::Xcode.version < …
```

development_tools: add type signatures

---

Library/Homebrew/build.rb
Library/Homebrew/build_environment.rb
Library/Homebrew/test/build_environment_spec.rb

-----
Cleaned up `ENV.userpaths!` call that got missed.
- Deprecated https://github.com/Homebrew/brew/commit/d6957a3acb9b524d84c377028867aea2d7d1f0af
- Disabled https://github.com/Homebrew/brew/commit/d73351251cb90fcc353557e6dfd4497a6ad83aef
- Deleted https://github.com/Homebrew/brew/commit/30a65342e8ee21fb07908309fb76bd994f7ab773

build: delete post_superenv_hacks

---

Library/Homebrew/unpack_strategy/zstd.rb

-----
Before extracting `.tar.zst` file (and some other file formats), we copy it to an extraction directory: https://github.com/Homebrew/brew/blob/9b42a104ee51fd2c45f91a72fc18bbad73b1aa5a/Library/Homebrew/unpack_strategy/zstd.rb#L29-L30
After extracting it, we have two files in the directory — `.tar` and original `.tar.zst`. 
Current logic assumes that the first file in this directory is `.tar` file:
https://github.com/Homebrew/brew/blob/9b42a104ee51fd2c45f91a72fc18bbad73b1aa5a/Library/Homebrew/unpack_strategy/tar.rb#L62-L65
But it's not always true for `Pathname#children`; thus in some cases, we're trying to untar the original file (`.tar.zst`) instead of `.tar` (like in https://github.com/Homebrew/homebrew-core/pull/86195).
~~This PR makes sure we're trying to untar exactly the `.tar` …

unpack_strategy/tar: fix zst subextraction

---

Library/Homebrew/rubocops/extend/formula.rb
Library/Homebrew/rubocops/urls.rb

-----
For the sources which we mandate HTTPS for, allow a plain HTTP mirror to be used, as long as the HTTPS version is present and is higher in the mirror list.

rubocops/urls: allow plain HTTP mirrors

---

Library/Homebrew/brew.sh
Library/Homebrew/cmd/update.sh
Library/Homebrew/development_tools.rb
Library/Homebrew/env_config.rb
Library/Homebrew/extend/os/mac/development_tools.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
Library/Homebrew/utils/curl.rb
docs/Manpage.md
manpages/brew.1

-----
The final step. Must be merged after #12166.

Install and use Homebrew's `ca-certificates` on macOS <= 10.15.5

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/resource.rb
Library/Homebrew/software_spec.rb

-----
We've not been able to provide a HTTP mirror for this, so the second best solution is to pass `--insecure` while downloading, so it can indeed be downloaded when system CA certs are broken.

Use --insecure to download `ca-certificates` source where necessary

---

Library/Homebrew/resource_auditor.rb

-----
We need brewed curl for functional HTTPS support, but can't currently install curl from source because there's HTTPS everywhere.

resource_auditor: restore curl HTTP mirror auditing

---

Library/Homebrew/dev-cmd/install-bundler-gems.rb
Library/Homebrew/dev-cmd/vendor-gems.rb

-----
remove `require "formula"` because it is not needed to execute the commands.

remove useless `require 'formula'`

---

Library/Homebrew/dependency.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/formulary.rb

-----
See https://github.com/Homebrew/brew/issues/12326
Before, third-party formulae that had a `depends_on "homebrew/core/foo"` line wouldn't work as expected. This PR fixes the way that they are handled.
- Now, `homebrew/core` won't be automatically tapped
- Dependencies can be installed correctly
-----
I don't think this is fully correct yet. At the moment, any time `Dependency#to_formula` is called on a core formula that isn't installed already, its bottle will be downloaded. I'm not 100% sure that this is what we want, though, because there may be some cases where we'd rather it to just fail. I thought this through more clearly a while back but I can't remember exactly what I decided.
Also, this means that bottles will be downloaded unecessarily for core formulae that _are_ …

Handle `depends_on "homebrew/core/foo"` for `HOMEBREW_INSTALL_FROM_API`

---

Library/Homebrew/diagnostic.rb

-----
Fixes https://github.com/Homebrew/brew/issues/12356
I could have sworn I fixed this in #12333 but I must have made some change and forgotten to test it out fully. Either way, this should fix the `check_deleted_formulae` check in `brew doctor` so that if `HOMEBREW_INSTALL_FROM_API` is set, kegs with their tap set to `homebrew/core` and kegs with a blank tap but which are available via the API won't be listed as being deleted.
This also raised another interesting issue which is that installing with `HOMEBREW_INSTALL_FROM_API` (when `homebrew/core` isn't tapped) leaves the `tap` entry in `INSTALL_RECEIPT.json` blank. This should probably be changed to be `homebrew/core`. However, since people have been using it, it's probably too late to not have the blank tap condition here.
I'm way …

Fix `brew doctor` with `HOMEBREW_INSTALL_FROM_API`

---

Library/Homebrew/formula_auditor.rb

-----
A resource can do `using: :homebrew_curl`, but, without this change, the
audit will still use system `curl`. This fails quite predictably.
Needed for Homebrew/homebrew-core#88330.

formula_auditor: respect `using: :homebrew_curl` in resources too

---

Library/Homebrew/formula_installer.rb
Library/Homebrew/test/spec_helper.rb

-----
This prevents output spam that results from `fetch_dependencies`. For example, `aom` depends on `jpeg-xl` which depends on `openexr`. When all three formulae are outdated and about to be upgraded, `openexr` gets fetched three times: once for `aom`, once more for `jpeg-xl`, and again for itself.

install, upgrade: fetch each formula only once

---

Library/Homebrew/os/linux/elf.rb

-----
Currently, if a library was not found via `ldd` then all dependents of the broken formula in question also report that they are missing a library, even if the dependent doesn't explicitly define the library as "needed".
While this may sound useful, this is inconsistent to the behaviour on macOS and is confusing when (for example) `brew linkage --test codequery` reports missing libraries when `qt@5` is what actually has the broken library linkage and only `qt@5` requires a revision bump to fix.

os/linux/elf: don't report missing libraries to dependents

---

docs/Cask-Cookbook.md

This change causes `livecheck` to return a nicer error if no match is found from the regex.
- [] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
-----

docs: cask-cookbook update livecheck blocks

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/test/cask/audit_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/discontinued-reference.rb
Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-skip-reference.rb
Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/url-unversioned-reference.rb
Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/version-latest-reference.rb

-----
`Cask::Audit#check_livecheck_version` was never updated to handle a referenced cask in a `livecheck` block (e.g., `cask "other-cask"`). As a result, this audit will wrongly give an error like `Version '1.2.3' differs from '' retrieved by livecheck.` in this scenario (e.g., Homebrew/homebrew-cask#113621, Homebrew/homebrew-cask#113622).
This PR ensures that a referenced cask is handled by the audit and it won't error when the referenced check provides a good version. I'll have to remember to keep this logic up to date when related changes are made in livecheck, like we do with `#livecheck_result` in `brew bump`.

Cask::Audit: Handle referenced cask in livecheck

---

Library/Homebrew/livecheck/strategy/apache.rb
Library/Homebrew/test/livecheck/strategy/apache_spec.rb

-----
The `stable` URL for the `apache-spark` formula is currently `https://dlcdn.apache.org/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz`. The path in this URL is one of the expected formats that we see in URLs that the `Apache` strategy already supports (albeit not in the form of a query string parameter).
The `stable` archive from `dlcdn.apache.org` is also available using the typical `https://www.apache.org/dyn/closer.lua?path=spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz` URL and the formula already uses `https://archive.apache.org/dist/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz` as the mirror.
With that in mind, the `Apache` strategy can easily support `dlcdn.apache.org` URLs through a simple change to the `URL_MATCH_REGEX`. This PR makes this change and expands related …

Apache: Support additional mirror/backup URLs

---

docs/Cask-Cookbook.md

---
The docs currently state that you should use `verified:` if the "hostnames of `url` and `homepage` differ". An example of where this is not true is if the `homepage` is `https://example.com` and the `url` is `https://download.example.com`. Adding `verified:` here will get flagged by `brew audit`, despite the hostnames being different. It seems the comparison is actually based on the apex domain, not the hostname.

Improve `verified:` docs in cask cookbook

---

Library/Homebrew/dev-cmd/bottle.rb

-----
Hopefully fixes the issue seen in https://github.com/Homebrew/homebrew-core/commit/d42d3a9ee407e487c4e474d8918e31f8010e2efb.

dev-cmd/bottle: don't gen `all` bottles if a bottle spec already exists

---

Library/Homebrew/dev-cmd/bottle.rb

-----
`bottle_hash["formula"]["pkg_version"] == formula.pkg_version.to_s` was always true in a version bump PR merge, as `formula` referred to the formula file post-bump. To fix this, check the latest origin/HEAD.
Should fix https://github.com/Homebrew/brew/pull/12387#issuecomment-962745603.

dev-cmd/bottle: fix pkg_version comparison on merge

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/dev-cmd/audit.rb
manpages/brew.1

-----
This fixes an issue where `brew audit --cask --new-cask` did not run the [`check_token_conflicts`](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/cask/audit.rb#L479) check as it should have. This was because at some point in the past, `args.token_conflicts?` started returning `true`/`false` instead of `true`/`nil`. Since `false.nil?` is `false` but `false.blank?` is `true`, this wasn't triggering properly. There are a few other implied audit rules that likely were affected as a result of this. that I've fixed here, too.

`dev-cmd/audit`: fix cask arg handling

---

.vscode/extensions.json
.vscode/settings.json
Library/Homebrew/utils/shfmt.sh

-----
Apply autofix by from `shellcheck` and customized `shfmt` (`utils/shfmt.sh`) on save or on demand for shell scripts on VS Code.
Screencast:

.vscode: auto fix shell script code style on save or on demand

---

.gitignore
.shellcheckrc
Library/Homebrew/style.rb

-----
Use `.shellcheckrc` to disable unneeded check SC2310-SC2312 globally.

.shellcheckrc: disable unneeded check SC2310-SC2312 globally

---

Library/Homebrew/keg_relocate.rb
Library/Homebrew/test/keg_relocate/relocation_spec.rb

-----
This fixes an issue with keg relocation where something like `-I/usr/local/Cellar` would not be relocated (and also not deemed necessary of relocation) because of the `-I` prefix. Homebrew treats this as the path `I/usr/local/Cellar` which it determines isn't equal to the cellar path that needs relocation. This means that placeholders aren't placed in text files and also means that strings like that won't be detected to determine whether the bottle is relocatable.
Per suggestion from @carlocab, I've modified the path regex to allow for either `-I`, `-L`, or `-isystem` to appear in front of the path. `-B` was also suggested as a possible exception, but I left it off for now pending further discussion. Another option is to allow any `-\w+` prefixes, but this is harder to code (because …

`Keg::Relocation`: allow `-F`, `-I`, `-L`, `-isystem` prefixes

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb

-----
This shortens the commit message for cask bump PRs such that
```
Update dotnet from 5.0.10,0a1577a6-a7f1-4da0-ae64-9003ff8badb5:3b3a9291a0bdcb5591afab9e842272db to 5.0.11,f241f934-a4cc-400a-8d03-a5ab50c25fea:1c8600ad088a42b157c073454e80039a
```
becomes `Update dotnet from 5.0.10 to 5.0.11`

bump-cask-pr: use version substring before comma unless they match

---

.github/workflows/tests.yml
Library/Homebrew/dependency_collector.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/extend/os/mac/dependency_collector.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/utils/svn.rb

-----
This fixes two similar issues:
- ever since the [Let's Encrypt CA expiry](https://github.com/Homebrew/brew/issues/12161), the built-in `svn` on macOS 10.14 and earlier is unable to access repositories hosted on SourceForge (i.e. svn.code.sf.net) and possibly others, so the `subversion` formula needs to always be installed before attempting to download and build from source any formula that gets its source from SVN. (Also, if a formula URL is marked with `trust_cert: true`, any unknown or outdated certificate errors will still be ignored.)
- macOS's built-in `curl` doesn't (yet) properly handle TLS 1.3 connections, so for installing from source any formulae using such sites (e.g. xiph.org) that are marked with `using: :homebrew_curl`, brewed `curl` needs to be installed first. …

formula_installer: always pre-install formulae required for fetching sources

---

Library/Homebrew/extend/ENV/std.rb
Library/Homebrew/extend/os/mac/extend/ENV/std.rb

One of the more curious bugs, if you use `-Wl,-headerpad_max_install_names` on linux, it tries to link a library named `eaderpath_max_install_names` in, which causes all kinds of weird havoc.
Most notably, gtester inside glib fails to run for bizarre reasons. `-Wl,-headerpad_max_install_names` is not an option anywhere outside macos anyway, so move it to macos only and avoid the heartache of extremely weird bugs.
-----

Do not pass -Wl,-headerpad_max_install_names on linux

---

Library/Homebrew/system_command.rb
Library/Homebrew/test/system_command_spec.rb
Library/Homebrew/utils/github.rb

-----
When `HOMEBREW_GITHUB_API_TOKEN` is set and user runs `brew bump-{cask,formula}-pr`, the GitHub token is printed on the console in Git push output.
`SystemCommand` uses `redact_secrets` already; this PR adds secret redaction to stdout/stderr as well, and then changes `GitHub.create_bump_pr` to use `system_command!` for executing the Git push.
Some questions to consider:
- Do we want to switch over all of the stuff in `create_bump_pr` (or all functions in `utils/github.rb`) to use `system_command[!]` instead? Any particular reason to prefer one of `system_command[!]` or `[safe_]system` over another here?
- Do we want to have a flag to toggle secret redaction for stdout/stderr (is there a case where we do need to print secret stuff to stdout/stderr with `SystemCommand`)? If so, what …

GitHub.create_bump_pr: don't leak GitHub token if set via environment variable

---

Library/Homebrew/brew.sh
Library/Homebrew/cmd/vendor-install.sh

Since `HOMEBREW_PROCESSOR` is populated using `uname -m`, this will
register as `Intel` even when a native ARM install is running under
Rosetta.
Let's work around this by checking `sysctl -n machdep.cpu.brand_string`.
On my Intel machine:
❯ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
On Apple Silicon:
brew@HMBRW-A-001-M1-001 ~ % sysctl -n machdep.cpu.brand_string
Apple M1
brew@HMBRW-A-001-M1-001 ~ % arch -x86_64 sysctl -n machdep.cpu.brand_string
Apple M1
The case of a Rosetta installation of Homebrew is already handled below
the proposed change.
Fixes Homebrew/discussions#2434.

vendor-install: handle native ARM running under Rosetta

---

Library/Homebrew/dev-cmd/bump.rb

-----
Further reduce unnecessary GitHub API calls during long `brew bump` runs by skipping formulae whose livecheck doesn't return a version.

bump: skip PR check if livecheck does not return a version

---

Library/Homebrew/cli/named_args.rb
Library/Homebrew/cmd/list.rb

-----
Show a more accurate error message when running `brew list <formula>` with a non-installed formula.
Before:
```
$ brew list zorba
Error: No available formula or cask with the name "zorba". Did you mean zork?
```
After:
```
$ brew list zorba
Error: No such keg: /usr/local/Cellar/zorba
$ brew list does-not-exist
Error: No available formula with the name "does-not-exist".
```

list: raise NoSuchKegError if formula exists but isn't installed

---

Library/Homebrew/utils/shfmt.sh

-----
Copyed from output of https://github.com/Homebrew/brew/runs/4175574091 (false positive):
```diff
*** /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/vendor-install.sh	2021-11-11 08:16:31.123776054 +0000
--- /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/.vendor-install.sh.temp	2021-11-11 08:18:29.438048778 +0000
***************
*** 17,19 ****
if [[ "${HOMEBREW_PROCESSOR}" == "Intel" &&
!         "$(sysctl -n machdep.cpu.brand_string)" != "Apple"* ]] ||
--- 17,19 ----
if [[ "${HOMEBREW_PROCESSOR}" == "Intel" &&
!      "$(sysctl -n machdep.cpu.brand_string)" != "Apple"* ]] ||
shfmt.sh: Fixable bad styles detected in file "/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/vendor-install.sh", run `brew style --fix` to apply. Formatter exited with code 4.
``` …

utils/shfmt.sh: improve shell formatter usage

---

Library/Homebrew/rubocops/text.rb

-----
Idea from here: https://github.com/Homebrew/homebrew-core/pull/89377#discussion_r748841562
This is not tested though.

rubocops/text: forbid "go get" only in install method

---

Library/Homebrew/linkage_checker.rb

Trying to `dlopen` some Qt libraries causes Ruby to crash.
This reverts commit 0191a275ccc3e1a9377c956751bbc1c4ba7b0cea.

Revert "linkage_checker: check variable references with dlopen"

---

Library/Homebrew/deprecate_disable.rb

The rationale is that a checksum mismatch is a huge security issue.
This means that the current source file, but maybe the initial one,
might have been compromised.
In the case upstream does not respond quickly to clarify what happened,
or fails to respond, we can now rev-bump the formula, disable and unbottle it,
making sure we stop delivering the potentially malicious code
Further improvements:
- Add the url of the project in the error message to redirect users to
the closed pull request where we disabled this, to centralize the discussion
and avoid the opening of multiple new issues
- Add a warning on brew-update that something is fishy upstream
-----

disable: allow to disable due to checksum mismatch

---

Library/Homebrew/utils/pypi.rb

-----
For example, this makes excluding `ipython` from `jupyterlab` also exclude unused dependencies, not just `ipython`.
`pipgrip --tree jupyterlab`
<details>
```
jupyterlab (3.2.3)
├── ipython (7.29.0)
│   ├── appnope (0.1.2)
│   ├── backcall (0.2.0)
│   ├── decorator (5.1.0)
│   ├── jedi>=0.16 (0.18.0)
│   │   └── parso<0.9.0,>=0.8.0 (0.8.2)
│   ├── matplotlib-inline (0.1.3)
│   │   └── traitlets (5.1.1)
│   ├── pexpect>4.3 (4.8.0)
│   │   └── ptyprocess>=0.5 (0.7.0)
│   ├── pickleshare (0.7.5)
│   ├── prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 (3.0.22)
│   │   └── wcwidth (0.2.5)
│   ├── pygments (2.10.0)
│   ├── setuptools>=18.5 (58.5.3)
│   └── traitlets>=4.2 (5.1.1)
├── jinja2>=2.1 (3.0.3)
│   └── markupsafe>=2.0 (2.0.1)
├── jupyter-core (4.9.1)
│   └── traitlets (5.1.1)
├── …
```

update-python-resources: skip dependencies of excluded packages

---

Library/Homebrew/utils/github/actions.rb

-----
GitHub Actions annotations also suport a "notice" annotation type. You
can also set the title of an annotion, and the set `endLine` and
`endColumn` parameters.
See https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions
I plan to use `title` and `end_line` in particular in `test-bot`.

utils/github/actions: support notices and new annotation parameters

---

Library/Homebrew/test/utils/github/actions_spec.rb
Library/Homebrew/utils/github/actions.rb

-----
An annotation is pretty useless if you don't specify a file to place the
annotation on, so let's just require it.

utils/github/actions: make `file` a mandatory argument

---

Library/Homebrew/cask_dependent.rb
Library/Homebrew/cmd/deps.rb
Library/Homebrew/utils/topological_hash.rb

-----
For example: [`brew deps --digraph watchman`](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A%20%20%22watchman%22%20-%3E%20%22boost%22%0A%20%20%22watchman%22%20-%3E%20%22fmt%22%0A%20%20%22watchman%22%20-%3E%20%22folly%22%0A%20%20%22watchman%22%20-%3E%20%22gflags%22%0A%20%20%22watchman%22%20-%3E%20%22glog%22%0A%20%20%22watchman%22%20-%3E%20%22libevent%22%0A%20%20%22watchman%22%20-%3E%20%22openssl%401.1%22%0A%20%20%22watchman%22%20-%3E%20%22pcre%22%0A%20%20%22watchman%22%20-%3E%20%22python%403.10%22%0A%20%20%22boost%22%20-%3E%20%22icu4c%22%0A%20%20%22folly%22%20-%3E%20%22boost%22%0A%20%20%22folly%22%20-%3E%20%22double-conversion%22%0A%20%20%22folly%22%20-%3E%20%22fmt%22%0A%20%20%22folly%22%20-%3E%20%22gflags%22%0A%20%20%22folly%22%20-%3E%20%22glog%22%0A%20%20%22folly%22%20- …

deps: add `--graph` and `--dot` switches

---

Library/Homebrew/cask/dsl/version.rb
Library/Homebrew/test/cask/dsl/version_spec.rb
docs/Cask-Cookbook.md

-----
`csv` will replace `before_colon` and `after_colon` (https://github.com/Homebrew/homebrew-cask/issues/95207)
> Example:
>
> `version` | `version.csv[0]` | `version.csv[1]` | `version.csv[2]`
> -- | -- | -- | --
> `123,456,789` | `123` | `456` | `789`
> `:` is a special character, and (unless I’m misremembering) it has given us trouble in the past. It’s used in highly specific cases, and those can be handled by multiple `,`.

cask: add `#csv` to version DSL

---

Library/Homebrew/cmd/--cache.rb
Library/Homebrew/cmd/outdated.rb

-----
The commands affected by this are: `brew --cache` and `brew outdated`

Add missing `--formulae/--casks` aliases for `--formula/--cask`

---

Library/Homebrew/cmd/migrate.rb
Library/Homebrew/formulary.rb

-----
For example, this makes `brew info ark` print `Warning: Use velero instead of deprecated ark` 
`brew info homebrew/core/ark` already prints this message because the string `homebrew/core/ark` matches the regex that maps to `TapLoader`, which is where the message is printed from.

Print warning if given old short name of renamed formula

---

Library/Homebrew/dev-cmd/unbottled.rb

-----
Related to Homebrew/homebrew-test-bot#705, and I believe this doesn't conflict with #12325, which also modifies `dev-cmd/unbottled`. This allows the `brew unbottled` command to work for formulae in 3rd-party taps.
~~~
$ brew unbottled osrf/simulation/gazebo9
==> Populating dependency tree...
==> :catalina bottle status
gazebo9: ready to bottle
~~~
~~~
$ brew unbottled osrf/simulation/gazebo9
==> Populating dependency tree...
==> :catalina bottle status
gazebo9: unbottled deps: ignition-cmake0 ignition-math4
~~~

dev-cmd/unbottled: don't skip non-core formulae

---

Library/Homebrew/formula_auditor.rb

-----
We have a bunch of formulae in homebrew-core that are supposed to be updated simultaneously (like `git` and `git-gui`, `python@3.9` and `python-tk@3.9` and recently added `libnghttp2` and `nghttp2`) and usually, we keep this requirement as a comment in formulae and check it manually during a PR review.
I propose adding a list (`synced_versions_formulae.json`) of such formulae to homebrew-core and an audit for checking those particular formulae have the same version.
The current version of `synced_versions_formulae.json` will look like this:
```json
[
["cmake", "cmake-docs"],
["etl", "synfig"],
["fizz", "folly", "wangle", "watchman"],
["git", "git-credential-libsecret", "git-gui"],
["ilmbase", "openexr@2"],
["imath", "openexr"],
["libnghttp2", "nghttp2"],
["libqalculate", …
```

formula_auditor: add audit for formulae with synced versions

---

Library/Homebrew/cli/args.rbi
Library/Homebrew/dev-cmd/linkage.rb
Library/Homebrew/linkage_checker.rb

-----
There was a previous discussion about making `brew linkage --test` fail
for unrequested dependencies (#9172). I'm not sure what the outcome of
that was, but it still seems like a good idea to try to help us find
cases of opportunistic linkage as they happen rather than when they
cause CI failures in another PR sometime later.
Let's do this by adding a `--strict` flag to `brew linkage --test`. My
intention is for `brew linkage --test --strict` failures to be warnings
rather than errors in CI, which should mitigate some of the concerns
about doing this that were raised in #9172.

linkage: add `--strict` flag to detect opportunistic linkage

---

Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/strategy/apache.rb
Library/Homebrew/livecheck/strategy/bitbucket.rb
Library/Homebrew/livecheck/strategy/cpan.rb
Library/Homebrew/livecheck/strategy/electron_builder.rb
Library/Homebrew/livecheck/strategy/extract_plist.rb
Library/Homebrew/livecheck/strategy/git.rb
Library/Homebrew/livecheck/strategy/github_latest.rb
Library/Homebrew/livecheck/strategy/gnome.rb
Library/Homebrew/livecheck/strategy/gnu.rb
Library/Homebrew/livecheck/strategy/hackage.rb
Library/Homebrew/livecheck/strategy/header_match.rb
Library/Homebrew/livecheck/strategy/launchpad.rb
Library/Homebrew/livecheck/strategy/npm.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/livecheck/strategy/pypi.rb
Library/Homebrew/livecheck/strategy/sourceforge.rb
Library/Homebrew/livecheck/strategy/sparkle.rb
Library/Homebrew/livecheck/strategy/xorg.rb
Library/Homebrew/test/livecheck/strategy/electron_builder_spec.rb
Library/Homebrew/test/livecheck/strategy/extract_plist_spec.rb
Library/Homebrew/test/livecheck/strategy/sparkle_spec.rb

-----
This PR modifies cask-related livecheck strategies (i.e., `ElectronBuilder`, `ExtractPlist`, `Sparkle`) to allow passing a regex into a `strategy` block, when appropriate. These strategies were outliers that explicitly rejected a regex even if a `strategy` block was used, forcing any regex to be inlined in the `strategy` block (instead of being defined using `#regex`).
With these changes, all `strategy` blocks will be able to accept a regex, further simplifying the mental model. This also helps to better align the various `find_versions` and `versions_from_*` methods across strategies (this will be further improved in a later PR).

Allow passing a regex in all livecheck `strategy` blocks

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb

-----
`--write` is deprecated, so it should say `--write-only` instead.

bump-cask-pr: replace `--write` with `--write-only` in help text

---

Library/Homebrew/dev-cmd/pr-upload.rb
Library/Homebrew/github_packages.rb

-----
The environment variable `HOMEBREW_FORCE_HOMEBREW_ON_LINUX` is not used anymore (1cc7ca3), so let's deprecate <code>&#8209;&#8209;github&#8209;org</code>. This doesn't affect bottle uploads because the GitHub org is already inferred from `root_url`.

pr-upload: deprecate `--github-org=`

---

Library/Homebrew/dev-cmd/extract.rb

-----
Attempting to extract Ghostscript 9.21 gives an error because it has the old bottle sha256 format.
```sh-session
> brew tap-new $USER/local-tap
> brew extract --version=9.21 ghostscript $USER/local-tap
Error: ghostscript: undefined method `[]' for nil:NilClass
```

extract: remove bottle blocks

---

Library/Homebrew/formula.rb

-----
We have a number of formulae (at least `archiver`, `buildkit`, `docker-ls`, `forcecli`, `go-jira`, `go-jsonnet`, but I have not finished looking) that build binaries that are not named the same as the formula.
Right now these formulae don't use `std_go_args` so that they can set a custom file output name with `-o`. Another option that I think I might've seen is specifying `std_go_args` and then adding an `-o=...` term anyways (the last value of this flag takes precedence).
This PR allows for the output file name to be specified if needed. The default is still `name`, so behavior should remain unchanged if this argument is not provided.
I picked the argument name `output` but am open to any other ideas if a different name would make more sense.

formula: allow optional output path in std_go_args

---

Library/Homebrew/dev-cmd/cat.rb
Library/Homebrew/utils.rb

-----
Fallback to `cat` when `HOMEBREW_BAT` set but `bat` is not installed.
```console
$ brew uninstall bat
$ export HOMEBREW_CAT=1
$ brew cat bat      
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/bat /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bat.rb` exited with 1.
```
This version:
```console
$ brew cat bat
Warning: Command `bat` is not installed, falling back to `cat`.
class Bat < Formula
desc "Clone of cat(1) with syntax highlighting and Git integration"
...
```

dev-cmd/cat: auto-install `bat` when running `brew cat ...` with `HOMEBREW_BAT` set

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/bump.rb
Library/Homebrew/dev-cmd/cat.rb
Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/github_packages.rb
Library/Homebrew/style.rb
Library/Homebrew/test/utils/git_spec.rb
Library/Homebrew/utils.rb
Library/Homebrew/utils/git.rb

-----
Reusing common functions, see https://github.com/Homebrew/brew/pull/12465#discussion_r755055468 and https://github.com/Homebrew/brew/pull/12465#discussion_r755159862.
New tests need?

utils: add method `ensure_formula_installed!`

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/brew.rb
Library/Homebrew/cleanup.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/dev-cmd/pr-pull.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/env_config.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/install.rb
Library/Homebrew/manpages/brew.1.md.erb
Library/Homebrew/upgrade.rb
docs/Manpage.md
manpages/brew.1

There's a few bits of functionality that Homebrew has changed over the years, makes sense as a sensible default but some people find really annoying:
- automatically running `brew update`
- automatically running `brew cleanup`
- automatically upgrading outdated dependents
- automatically reinstalling broken dependents
For each of these: let's improve the documentation of the commands whose behaviour is changed and the environment variables themselves.

Improve documentation of some environment variables

---

Library/Homebrew/brew.sh
Library/Homebrew/cleanup.rb
Library/Homebrew/env_config.rb
Library/Homebrew/upgrade.rb
docs/Manpage.md
manpages/brew.1

Output hints for disabling automatic `brew update`, `brew cleanup` and `brew upgrade`/`brew reinstall` of dependents. Also provide a `HOMEBREW_NO_ENV_HINTS` to disable this messaging.
Extracted from https://github.com/Homebrew/brew/pull/12413.
@Homebrew/maintainers interested again in your thoughts on this implementation. Since the last one I've added:
- some warnings when these variables are set
- the `HOMEBREW_NO_ENV_HINTS` variable

Output environment variable hints.

---

Library/Homebrew/extend/os/mac/extend/ENV/super.rb

-----
By "archive" I mean the generation of `.a` files, like static libraries.
`ZERO_AR_DATE` tells Apple's tools to set the timestamp within these archives to 0.

ENV/super: enable deterministic archive generation

---

Library/Homebrew/rubocops/lines.rb

-----
These seem more natural, and I don't think we need to be able to mock
service blocks on other OSs.
See Homebrew/homebrew-core#90091.

rubocops/lines: allow `OS.foo?` in `service` blocks

---

Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/strategy.rb
Library/Homebrew/livecheck/strategy/header_match.rb
Library/Homebrew/livecheck/strategy/page_match.rb
Library/Homebrew/test/livecheck/livecheck_spec.rb

-----
Initial swing at addressing #12341. Has `livecheck` use brewed curl if it's using the `:stable` (formula), `:url` (cask) or `:homepage` URL and the download URL specifies `using: :homebrew_curl`, e.g. https://github.com/Homebrew/homebrew-core/pull/88835.

livecheck: use brewed curl if called for by download URL

---

Library/Homebrew/upgrade.rb

-----
We upgrade dependents of upgraded formulae to make sure that an upgrade
doesn't break anything. However, this reasoning applies only when a
dependent is bottled, since attempting a source build is just as likely
to break things, if not more.
I've opted not to restrict this to, say, users only on outdated versions
of macOS in order to cleanly handle other cases where this change should
also apply: Linux, or current versions of macOS in a non-default prefix.

upgrade: don't upgrade unbottled dependents of upgraded formulae

---

Library/Homebrew/cmd/shellenv.sh

This is a more simple way to support running the `brew` command inside of a PowerShell session that is not a child process of a regular Unix shell session (e.g. where existing environment variables are not inherited). It is useful in case one wants to have a dedicated shell profile setup for PowerShell in Apple Terminal, iTerm, or other terminal emulators.
It is as simple as running `brew shellenv | Invoke-Expression` at the beginning of a PowerShell session or by adding the same command to the [PowerShell `$PROFILE` file](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.2#the-profile-variable).
To automate this, the following command can be run once to finish the setup inside of a PowerShell session:
```powershell …
```

Add shellenv template for PowerShell

---

Library/Homebrew/rubocops/lines.rb

-----
PyOxidizer downloads pre-built versions of Rust and Python, and embeds
this Python into the binaries it produces.
This goes against a number of our packaging policies, so let's make sure
formulae in Homebrew/core don't do this.
See Homebrew/homebrew-core#90025.

rubocops/lines: disallow `pyoxidizer` as a build/runtime dependency

---

Library/Homebrew/service.rb
Library/Homebrew/test/service_spec.rb

-----
This adds basic cron support, allowing parts of a cron statement to be either a number or `*`. After this all service run types are implemented.

service: add basic cron support

---

Library/Homebrew/extend/ENV/super.rb
Library/Homebrew/extend/os/linux/extend/ENV/super.rb
Library/Homebrew/extend/os/mac/extend/ENV/super.rb

-----
`@public` is not a valid YARD [tag](https://www.rubydoc.info/gems/yard/file/docs/Tags.md)
Fixes https://github.com/Homebrew/rubydoc.brew.sh/runs/4369650006?check_suite_focus=true#step:7:8
cc @MikeMcQuaid

Remove unknown YARD tags

---

.github/ISSUE_TEMPLATE/bug.yml

-----
Submitting bug reports hasn't worked for a while because of the missing
`label`.
My editor complained about `labels` needing to be an array, so I've made
that one too. It was also complaining about the missing label property
for the checkboxes, so I guess it knows what it's talking about here.
See https://github.com/Homebrew/discussions/discussions/2526#discussioncomment-1731168

bug.yml: fix missing `label` property

---

Library/Homebrew/upgrade.rb

-----
Requires approval of #12483.
This skips _both_ the outdated and broken linkage check. We could potentially keep the broken linkage part if desired.

upgrade: skip dependent check on core versioned formulae

---

Library/Homebrew/utils/ruby.sh

utils/ruby.sh: fix error with older Bash

---

Library/Homebrew/cmd/shellenv.sh

With reference to PR  #12494, it turns out that for the preview version of PowerShell, the executable file name is different (due to parallel symlink in `/usr/local/bin/pwsh-preview` right next to `/usr/local/bin/pwsh` of the current version).
This patch is going to fix this.

Add support for PowerShell-preview package to shellenv

---

Library/Homebrew/utils/github.rb

Given a formula with a broken build, if you install it locally with `brew install path/to/formula.rb`, when the build fails, Homebrew will attempt to [search for open issues on the tap](https://github.com/Homebrew/brew/blob/073c4177b5d2f3c869181fb6eaab2bfa33d368ce/Library/Homebrew/exceptions.rb#L489); but in this case `formula.tap` is `nil` and `tap.full_name` would raise a `NoMethodError` yielding this output:
```
$ brew install ./erg.rb
Error: Failed to load cask: ./erg.rb
Cask 'erg' is unreadable: wrong constant name #<Class:0x00007fd89b246cd0>
Warning: Treating ./erg.rb as a formula.
==> Downloading https://github.com/square/erg/archive/v1.1.1.tar.gz
Already downloaded: /Users/lail/Library/Caches/Homebrew/downloads/54e3fce84302901d76d50b53aa7fe760cfcf81c9842a232d6b29e771de6ec9c5--erg-1 …
```

Bypass searching for open Issues when failing to install a formula without a tap

---

Library/Homebrew/download_strategy.rb

The PR that added this #8622 didn't actually resolve the problem because you see the warning when the `@ref_type` you've specified is a `:revision` and you haven't specified a `:branch` or `:tag`.
The output looks like this:
```
==> Checking out revision 3b3527f5050270cf1acd280691b09b5abe130e73
Note: switching to '3b3527f5050270cf1acd280691b09b5abe130e73'
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:
git switch -c <new-branch-name>
Or undo this operation with:
git switch -
Turn off …
```

Silence the detachedHead warning when ref_type is a revision

---

Library/Homebrew/test/utils/analytics_spec.rb
manpages/brew.1

On M1 running from a rosetta terminal - the code puts a ", Rosetta" in the analytics string.
Can repro by running from a rosetta emulated terminal (eg alacritty). This fixes it!
-----

Fix analytics_spec.rb test to pass when run from M1

---

.github/workflows/tests.yml
.github/workflows/vendor-gems.yml

-----
This is no longer necessary and actually breaks things when run on `macos-11`.

workflows: remove outdated Xcode switch

---

Library/Homebrew/exceptions.rb
Library/Homebrew/formulary.rb

-----
Before:
```
$ brew install https://raw.githubusercontent.com/nginx/homebrew-unit/master/Formula/unit.rb
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of unit formula file from an arbitrary URL is unsupported!  (UsageError)
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of unit formula file from an arbitrary URL is unsupported!  (UsageError)
```
After:
```
$ brew install https://raw.githubusercontent.com/nginx/homebrew-unit/master/Formula/unit.rb
Error: Invalid usage: Non-checksummed download of unit formula file from an arbitrary URL is unsupported! `brew extract` or `brew create` and …
```

Fix error message duplication for installation from URL

---

docs/Xcode.md

This PR is mostly an excuse to test `setup-homebrew`.

docs/Xcode: fix CLT method name

---

Library/Homebrew/cmd/shellenv.sh

-----
Some setups (e.g. a default `tmux` session) will result in a user
starting multiple nested login shells. This is a problem for the way we
currently handle `shellenv` because a login shell invokes
`/usr/libexec/path_helper` which will prepend the contents of
`/etc/paths` and `/etc/paths.d` to `PATH`. In particular, the second
login shell will place `brew` further down the `PATH` than desired in a
non-`/usr/local` prefix, since `brew shellenv` will no longer produce
output the second time around.
Let's fix this by replacing the check that `brew` is in `PATH` with a
check that `${HOMEBREW_PREFIX}/bin` precedes `/usr/bin` in `PATH`.
Fixes #11851
Fixes #11883
Fixes Homebrew/discussions#2547.
See also:
- Homebrew/discussions#2237
- …

shellenv: check that Homebrew's prefix precedes `/usr/bin`

---

Library/Homebrew/brew.sh
Library/Homebrew/tap.rb

-----
There's an even older remote we used, Linuxbrew/homebrew-core, which redirects to Homebrew/linuxbrew-core. Some users who installed a long time ago may still have Linuxbrew/homebrew-core as a git origin as we never migrated them to Homebrew/linuxbrew-core and simply relied on GitHub's redirect feature. Those users simply faced their linuxbrew-core install no longer receiving updates when we should have been migrating them.
See https://github.com/Homebrew/discussions/discussions/2624.

Fix linuxbrew-core migration not applying to Linuxbrew/homebrew-core

---

Library/Homebrew/rubocops/uses_from_macos.rb

-----
gcore has been removed from homebrew-core.

rubocops/uses_from_macos: remove gcore

---

Library/Homebrew/formula.rb
Library/Homebrew/formula_support.rb

-----
For inclusion in the JSON API.

formula: add keg_only_reason to formula hash

---

Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/test/livecheck/livecheck_spec.rb

-----
Some formulae/casks contain duplicate checkable URLs or contain URLs that become duplicates after `#preprocess_url` is used. With the former, a formula's `stable` and `head` URLs can be the same if they both use the Git repository. With the latter, a formula's `homepage` and `stable` URLs are different but `#preprocess_url` can return the same Git repository URL for each (which can also be a duplicate of the `head` URL).
The `fabric-completion` formula is a worst case scenario, as it contains both of these conditions but the repository has no tags. By default, livecheck would needlessly check the repository three times (i.e., no versions are found so livecheck tries the next URL, which happens to be the same URL). [That said, I added a `skip` `livecheck` block in the past when I …

Livecheck: Avoid duplicate URLs

---

Library/Homebrew/Gemfile
Library/Homebrew/Gemfile.lock

-----
This is mostly to prevent Dependabot picking 7.0 since that requires Ruby 2.7.

Gemfile: restrict activesupport version range

---

Library/.rubocop.yml

-----
Some Rails cops use `ActiveRecordHelper` which contains a cache checksum that involves checksuming a Rails database schema. This involves an amount of file traversal as it tries to find this schema, which can be slow.
For _cached_ `brew style` runs on Homebrew/core, disabling these cops speeds up execution time by over 50%.

.rubocop.yml: selectively enable Rails cops

---

.github/dependabot.yml

-----
This is documented as being the default but it doesn't seem to be that way. 🤷‍♂️

dependabot.yml: lockfile-only versioning strategy

---

Library/Homebrew/cmd/vendor-install.sh

Extends what has been done in https://github.com/Homebrew/brew/pull/11766 to the portable-ruby installer;
because it was already taking `$HOMEBREW_ARTIFACT_DOMAIN` into account but not `$HOMEBREW_DOCKER_REGISTRY_TOKEN`, so we had 401 errors when installing homebrew.
-----

Take `$HOMEBREW_DOCKER_REGISTRY_TOKEN` into account when installing portable-ruby

---

Library/Homebrew/sorbet/rbi/upstream.rbi

-----
This was merged upstream a while ago.

sorbet/rbi/upstream.rbi: remove old workaround

---

Library/Homebrew/formula.rb
Library/Homebrew/test/formula_spec.rb

-----
remove `os_os` methods from `formula.rb` because of # TODO

remove on_os from formula

---

Library/Homebrew/formula.rb
Library/Homebrew/test/formula_spec.rb

This is causing `post_install` failures. Spotted in
Homebrew/homebrew-core#91763.
This reverts commit fc7462acd5ffb7cc393d2b56b989e96112ade896.

Revert "remove on_os from formula"

---

docs/Common-Issues.md

-----
Moved the documents from https://github.com/Homebrew/homebrew-cask/tree/HEAD/doc/reporting_bugs to common homebrew docs.
CC @Homebrew/cask

docs: add common cask issues

---

Library/Homebrew/cask/utils/quarantine.swift
Library/Homebrew/cask/utils/trash.swift

-----
The following PR modernizes the swift scripts in Library/Homebrew/cask/utils (trash.swift and quarantine.swift), by using features that are Swift-like, such as guard statements. 
The functionality and usage of the 2 scripts remains the same

Modernize swift scripts in Library/Homebrew/cask/utils

---

Library/Homebrew/cmd/autoremove.rb

-----
Checks if the removable formulae *after* removing cask dependancies, preventing output like this:
```
$ brew autoremove
==> Uninstalling 0 unneeded formulae:
```

autoremove: Return when not removing

---

Library/Homebrew/extend/os/linux/linkage_checker.rb

libnss_nis.so.2 in glibc@2.13 has linkage to libnss_files.so.2.
-----
Fix the error
```console
$ brew linkage --test glibc@2.13
Unwanted system libraries:
/lib/x86_64-linux-gnu/libnss_files.so.2
```
https://github.com/Homebrew/homebrew-core/runs/4676492184?check_suite_focus=true#step:7:67

Allow linkage to libnss_files.so.2 on Linux

---

Library/Homebrew/extend/os/linux/keg_relocate.rb

Patching the dynamic linker of Glibc breaks it.
-----
See PR
- https://github.com/Homebrew/homebrew-core/pull/92329

Patch neither glibc nor glibc@* using patchelf

---

.github/workflows/tests.yml
Library/Homebrew/dev-cmd/bump.rb
Library/Homebrew/test/dev-cmd/bump_spec.rb
Library/Homebrew/test/spec_helper.rb
Library/Homebrew/test/utils/repology_spec.rb
Library/Homebrew/utils/repology.rb

This seems to be required even with TLSv1.3 support now.
Also, while we're here, improve the error handling/output.

repology: always use Homebrew curl.

---

Library/Homebrew/cmd/autoremove.rb

-----
Closes https://github.com/Homebrew/brew/issues/12660
`autoremove` not only cask's formulae but also cask's formulae's formulae

repair cask formulae autoremove

---

Library/Homebrew/cli/parser.rb
Library/Homebrew/cmd/update.sh
Library/Homebrew/help.rb
Library/Homebrew/test/formatter_spec.rb
Library/Homebrew/utils/formatter.rb
manpages/brew.1

-----
Fixes https://github.com/Homebrew/brew/issues/12671
This fixes the issue with `brew help cleanup` by using a non-breaking space between `brew --cache` to ensure that a line never starts with `--cache`. I think this is a unique enough situation that fixing the problem here instead of in our parser logic is acceptable.

Fix `brew help cleanup` text

---

Library/Homebrew/livecheck/strategy.rb

-----
This is a recreation of #12647, as I was encountering persistent CI failures that I didn't think were related to the committed changes (based on what I saw in testing). Digging into this further, it turned out that the failures were, in fact, due to the `#curl_args` commit where I used `#uniq` on the returned array. My intention was to avoid having options duplicated between `args` and `extra_args` (e.g., including `--silent` twice), simply for the sake of tidiness, but this approach causes problems because some options can be used more than once (e.g., `--header`).
Unfortunately, I modified the related branch, so I couldn't re-open the previous PR. That said, this PR is the same as the last one but I've dropped the `#curl_args` commit.
---
Currently, only …

Strategy: Add --silent flag to DEFAULT_CURL_ARGS

---

Library/Homebrew/utils/pypi.rb

Rather than failing if it isn't installed: install it if needed.

utils/pypi: ensure pipgrip is installed.

---

Library/Homebrew/dev-cmd/bump.rb
Library/Homebrew/utils/repology.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

This enables the simplification of https://github.com/Homebrew/actions/blob/master/bump-formulae/main.rb and exposing this workflow to more Homebrew users.
CC @dawidd6 @samford @chenrui333 @carlocab for thoughts and feedback

dev-cmd/bump: add switch to open pull requests.

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/cmd/install.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/install.rb

Allows you to avoid the `Keg::ConflictError` recommending that you invoke `brew link --overwrite` in scenarios when you know that that's how you'd proceed anyway.
-----
I didn't see a test in [formula_spec.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/formula_spec.rb) that exercised the `Keg::ConflictError` error — that I could copy and adapt. [keg_spec.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/keg_spec.rb) already covers the logic of the `overwrite` option.
I validated this change by doing:
```
brew uninstall git
touch /usr/local/bin/git
brew install --overwrite git
```

Add flag `--overwrite` to `brew install` to govern the keg-linking step

---

docs/Manpage.md

Simple typofix in docs/Manpage.md
595: directores -> directories
-----

Fix typo in docs/Manpage.md

---

Library/Homebrew/cmd/shellenv.sh
manpages/brew.1

-----
Follow-up to #12728, I forgot that `docs/Manpage.md` was generated automatically and that the "actual" typo was in `cmd/shellenv.sh`. This PR rectifies the error in the right place.

cmd/shellenv.sh: fix typo

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb

this script always get `inreplace failed` on cask like firefox because the
default sha256 is replaced twice
-----

bump-cask-pr: avoid replacing sha256 twice on multilang cask

---

README.md

They've provided our DNS for free for a while so let's give them a shout-out.

README: add DNSimple as a sponsor.

---

Library/Homebrew/extend/os/mac/keg_relocate.rb

-----
Upon reflection, I realised that this is probably a bug in `ruby-macho`,
and should be fixed there instead.
Needs https://github.com/Homebrew/ruby-macho/pull/362.
This reverts commit e8b5eb7e42c925b7cc10c78a029b8c70e4d7965b.

Revert "extend/os/mac/keg_relocate: fix relocation of duplicate `RPATH`s"

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb

Otherwise Cellar gets cluttered with useless files.
Fixes https://github.com/Homebrew/brew/issues/12744.

dev-cmd/bottle: clean up intermediate tar

---

docs/Deprecating-Disabling-and-Removing-Formulae.md

This is based on the discussion at Homebrew/homebrew-core#91368.
A few reasons why we don't want to deprecate formulae that have
dependents:
1. This results in displaying warning messages to (at least some) users
that they can't do anything about.
2. `test-bot` does not test deprecated formulae, so we risk breaking
dependent formulae when one of its dependencies is not tested.
3. It is much harder to commit to a disable date for formulae with
dependents because we don't know when we'll be able to wean
dependents off of a deprecated formula.
I think it's important to have a disable date in mind when we deprecate
formulae. Otherwise, we might end up leaving formulae deprecated
indefinitely. This is bad because it teaches users to not take
deprecation warnings seriously.

Update documentation on deprecating and disabling formulae

---

Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/formula_installer.rb

-----
ruby-macho chokes on changing duplicate RPATHs, so we need to strip the
duplicates before trying to relocate them.
This continues #11405. We need this to unblock
Homebrew/homebrew-core#91224.
While we're here, let's get rid of `HOMEBREW_RELOCATE_RPATHS`. We've
been using it for nearly a year with essentially no problems (barring
`pdnsrec`), so I think it is safe to do unconditionally.

extend/os/mac/keg_relocate: fix duplicate RPATH handling

---

README.md

Follow-up to #12731
This adds DNSimple's dark mode logo and sets up the README to [switch between using the light and dark logos based on the GitHub theme](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/).
Before on dark mode:
After on dark mode:
It would probably also be good to do this for MacStadium and maybe Substack, but I don't know where the right images would be located.

Adapt DNSimple logo to system appearance

---

Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/os/mac/keg.rb
Library/Homebrew/os/mac/mach.rb

-----
This will allow us to avoid keeping track of the number of `RPATH`s
while trying to delete duplicates.
See discussion at #12745.

os/mac/keg: use `MachOFile#delete_rpath` instead of `MachO::Tools`

---

Library/Homebrew/test/cmd/services_spec.rb

Was broken by https://github.com/Homebrew/homebrew-services/pull/443

test/cmd/services_spec: fix test.

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

Currently, `brew bump-formula-pr` errors out without a proper message
when `--version` isn't specified and the formula's version cannot be parsed
from the URL. We fix this by returning early from `check_new_version` when the
detected version is Version::NULL.
See https://github.com/Homebrew/homebrew-core/pull/93497#issuecomment-1017968277 for context.
---

dev-cmd/bump-formula-pr: fix for undetectable version

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

Fix a regression from 8b1fcc7c5c18ec970c30e712ab283d7703694523.
Only if `version.nil?` is `Version.detect` used, so we can
only use `version.null?` after that. (Otherwise, it's a string.)
```
Error: undefined method `null?' for "X.Y.Z":String
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:440:in `check_new_version'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:131:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```
-----

dev-cmd/bump-formula-pr: fix undefined method null error

---

Library/Homebrew/cleanup.rb

Reverts Homebrew/brew#12758
Fixes https://github.com/Homebrew/brew/issues/12788

Revert "cleanup: check if symlinks are readable."

---

Library/Homebrew/dev-cmd/bump.rb

-----
This PR proposes to avoid checking Repology for versioned formulae when `brew bump`ing them. 
Currently, `brew bump`'s Repology output for a versioned formula shows the latest version for the corresponding non-versioned formula. This leads to incorrect PRs like https://github.com/Homebrew/homebrew-core/pull/94115, https://github.com/Homebrew/homebrew-core/pull/94113, https://github.com/Homebrew/homebrew-core/pull/94110, etc. For example:
```
➜ brew bump traefik@1
==> traefik@1
Current formula version:  1.7.34
Latest livecheck version: 1.7.34
Latest Repology version:  2.6.0
Open pull requests:       none
```
With these changes, we have:
```
➜ brew bump traefik@1
==> traefik@1
Current formula version:  1.7.34
Latest livecheck version: 1.7.34
Latest Repology version:  not found
Open …
```

`brew bump`: don't use Repology for versioned formulae

---

Library/Homebrew/rubocops/text.rb
Library/Homebrew/test/rubocops/text_spec.rb

-----
When building Rust packages that provide libraries but no executable binaries, `cargo install` doesn't do anything; you need to use `cargo build` and install any libraries manually. See e.g. rust-lang/cargo#8294.
Unfortunately, Homebrew's Rubocop "use `"cargo", "install", *std_cargo_args`" rule, as currently written, blocks all invocations of `cargo build`. This is blocking homebrew/homebrew-core#94091 and will prevent formulas for being created for any library-only Rust packages that use `cargo` to build.
This commit changes that rule to allow invocations of `cargo build` that use the `--lib` argument (`--lib` specifies to Cargo that a package's library targets should be built). This will enable library packages to be built, while retaining the "use `"cargo", "install", …

Formula: Allow `cargo build` when building libraries

---

Library/Homebrew/test/utils/shebang_spec.rb
Library/Homebrew/utils/shebang.rb

-----
In https://github.com/Homebrew/homebrew-core/pull/94202, we encountered a bug where `rewrite_shebang` wasn't actually rewriting any shebang due to a misspelled filename. This change prevents this class of bugs by erroring when no replacement occurs.
This is my first PR here, so any feedback is greatly appreciated 😄

shebang: raise error if no rewriting

---

docs/Interesting-Taps-and-Forks.md

Add brew formulae from Cloudflare github. It provides a formulae of Cloudflare apps but also
maintains other such as curl and nginx + http/3 support might be interesting to users.
-----

docs: Add cloudflare/homebrew-cloudflare

---

Library/Homebrew/rubocops/text.rb
Library/Homebrew/test/rubocops/text_spec.rb

-----
This currently no longer applies, because we might sometimes need an
older `setuptools` than the one shipped with a Python formula.
This is needed for Homebrew/homebrew-core#93964.

rubocops/text: remove `setuptools` audit

---

Library/Homebrew/cask/dsl/caveats.rb

-----
Some casks will fail to install with a `Bad CPU type in executable`
error on Apple Silicon. See Homebrew/homebrew-cask#118638.
This error can be quite confusing, so let's add a way to help users know
that they need to install Rosetta to use or even install a cask.

cask/dsl/caveats: add `:requires_rosetta`

---

Library/Homebrew/test/utils/shell_spec.rb
Library/Homebrew/utils/shell.rb

Since the `fish_add_path` command modifies a universal Fish variable (which is automatically persisted to a file) it's unnecessary to run it again every time a new shell is opened.

Recommend interactive usage of `fish_add_path`

---

docs/Adding-Software-to-Homebrew.md

The existing title is not in title case according to our reference
style guide.

docs: fix style

---

Library/Homebrew/dev-cmd/pr-publish.rb
Library/Homebrew/dev-cmd/pr-pull.rb
docs/Adding-Software-to-Homebrew.md

-----
This allows dispatching the publish workflow via the GitHub UI to have
the exact same behaviour as doing `brew pr-publish`.
Closes Homebrew/homebrew-core#94704.

pr-{publish,pull}: autosquash by default

---

Library/Homebrew/formula_auditor.rb

-----
Occasionally, we get PRs that attempt to add a dependency on a formula
in an external tap in homebrew/core (e.g. Homebrew/homebrew-core#94791).
We don't actually have an audit that disallows that. We should have one.

formula_auditor: disallow external tap dependencies in core

---

Library/Homebrew/brew.rb
Library/Homebrew/commands.rb

- I may have missed some, as there are 26 pages of results for `
- I couldn't think of any general enough tests for this that don't basically just duplicate the logic, but I'm open to writing one if needed.
- I get some nondeterministic errors both with my code and with the current master code, that differ between runs. This may relate at least in part to me running this on an M1 mac. Some errors were timeouts. Wasn't able to check/compare many times because it takes about 5 minutes to run the full suite.
- EDIT: But the CI tests pass! 🎉 
-----
This adds a simple check: if the command being used is `brew cask`, it exits early with a helpful error message instructing them to use `brew <command> --cask` instead.
Fixes #12707
See https://github.com/Homebrew/discussions/discussions/902 for …

Add helpful error message when attempting to run `brew cask`

---

Library/Homebrew/service.rb
Library/Homebrew/test/service_spec.rb

-----
This change adds a MacOS launchctl configuration to services that allows providing the `LaunchOnlyOnce` boolean flag.
```
LaunchOnlyOnce <boolean>
This optional key specifies whether the job can only be run once and only once.  In other words, if the job cannot be safely
respawned without a full machine reboot, then set this key to be true.
```
**NOTE**: this is MacOS only, if there's a way to provide this for systemd that'd be awesome!
Issue: https://github.com/abiosoft/colima/issues/96

service: launch only once

---

Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/software_spec.rb

To-do list:
-----
This PR implements part 1 of https://github.com/Homebrew/brew/issues/10846.  The goal here is replace references to the build prefix in a binary with users's prefix if the new prefix is of equal or shorter length to the build prefix.  If the prefix is shorter, strings which contain it are padded with null characters to make it the same length as the build prefix.
There are several things which I think need to be added to this PR, for which feedback would be greatly appreciated:
1) Proper error handling.  There are at least two scenarios where we might want raise an exception:<br>
a) The patched binary is not the same length as the original.  The way the code is written right now makes this unlikely, but we still might want something in case of a weird fluke.<br>
b) There …

Binary patching of build prefixes

---

Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/software_spec.rb

Revert "Binary patching of build prefixes"

---

Library/Homebrew/utils.rb

Otherwise `brew deps --graph` will fail to launch Firefox on Linux (and probably all other browsers or utilities that rely on DBus for IPC).
Fixes https://github.com/Homebrew/brew/issues/12881.
-----

utils: add DBus session address to browser env

---

docs/Formula-Cookbook.md

docs: document `service` block

---

Library/.rubocop_cask.yml

-----
- This was a TODO from 2020 (2b029b2744c1a008b17c588313963051a291f13c). I can't find `.rubocop.yml` in any Cask taps in the Homebrew org anymore.

git rm Library/.rubocop_cask.yml

---

Library/Homebrew/dev-cmd/dispatch-build-bottle.rb

-----
- The cores are now merged (:tada:), so the Linux core tap is `homebrew-core` not `linuxbrew-core`, everything core should have switched over, this should be safe to remove.

dev-cmd/dispatch-build-bottle: Stop replacing `linuxbrew-core`

---

Library/Homebrew/dev-cmd/bump.rb

-----
- I got frustrated when I fixed the build and test failures for https://github.com/Homebrew/homebrew-core/pull/95430 only to have the audit step say it was a pre-release.
- Repology can list versions that are GitHub pre-releases. Pre-release versions of software are things we don't generally want to ship: there's an audit specifically for that.
- This fixes `brew bump` to not mark a Repology version as the newest if the formula's livecheck strategy is `GithubLatest`. If the livecheck doesn't exist, or its update strategy is something other than `GithubLatest`, Repology's reported package version is respected.

dev-cmd/bump: Ignore Repology if the livecheck uses `GithubLatest`

---

Library/Homebrew/compat/cask.rb
Library/Homebrew/compat/formula.rb

Part of https://github.com/Homebrew/brew/issues/11292
Do not merge until the next tag will be 3.4.0.

formula, cask: deprecate use of Enumerable methods e.g. `each`.

---

Library/Homebrew/cask/dsl/version.rb
Library/Homebrew/cli/named_args.rb
Library/Homebrew/cmd/list.rb
Library/Homebrew/dev-cmd/bump-cask-pr.rb
Library/Homebrew/dev-cmd/pr-automerge.rb
Library/Homebrew/dev-cmd/pr-publish.rb
Library/Homebrew/dev-cmd/pr-pull.rb
Library/Homebrew/dev-cmd/pr-upload.rb
Library/Homebrew/formula_support.rb

Do not merge until the next tag will be 3.4.0.

Deprecations, disables, deletions for 3.4.0

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/env_config.rb
Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
Library/Homebrew/test/cmd/update-report_spec.rb

This avoids reading formula files that the user hasn't explicitly
installed which both speeds up `brew update` and improves the security.
https://github.com/Homebrew/brew/pull/12911 deprecates the use of `Enumerable` methods on `Formula`.
Part of https://github.com/Homebrew/brew/issues/11292
Do not merge until the next tag will be 3.4.0.

update-report: default HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED to on.

---

Library/Homebrew/.simplecov

I have no idea what this is going to do to our coverage metrics but it's supported by Ruby >=2.5 so let's give it a go.

simplecov: enable branch coverage.

---

Library/Homebrew/compat/formula.rb
Library/Homebrew/formula.rb
Library/Homebrew/test/formula_spec.rb

Reverts Homebrew/brew#12912
CC @carlocab FYI
We still need this for e.g. `test do` blocks.

Revert "formula: remove `OnOS`."

---

Library/Homebrew/test/cask/dsl/version_spec.rb

No idea why these didn't fail before now?

cask/dsl/version_spec: remove deprecated specs.

---

Library/Homebrew/upgrade.rb

- [ x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x ] Have you successfully run `brew style` with your changes locally?
- [ x] Have you successfully run `brew typecheck` with your changes locally?
- [ x] Have you successfully run `brew tests` with your changes locally?  Though unclear since terminal line endings get mixed up?
-----
The motivation for this is: if I update "x" brew might update seemingly unrelated apps (that aren't even dependencies), try and clarify why it …

try to clarify why it is upgrading dependents

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/env_config.rb
Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
Library/Homebrew/test/cmd/update-report_spec.rb

Reverts Homebrew/brew#12910
Haven't decided whether to revert this yet or not but given the number of complaints so far: I'm getting tempted to do so before the 3.4.0 release.

Revert "update-report: default HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED to on."

---

Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/test/keg_relocate/grep_spec.rb

Following up on the suggestion in https://github.com/Homebrew/brew/pull/12534#issuecomment-1041341701, I want to use this PR just to add a method for using `grep` to find null characters in files to identify binaries.  There are two things I want to add to this:

Add binary grep method to keg_relocate

---

docs/Cask-Cookbook.md

From `cask.rb`:
```
def caskroom_path
@caskroom_path ||= Caskroom.path.join(token)
end
```

Cask-Cookbook: fix `caskroom_path` description

---

Library/Homebrew/unpack_strategy/zip.rb

-----
This is necessary for some Linux systems where there is no system unzip.

unpack_strategy/zip: allow unzip formula to be used

---

docs/Tips-N'-Tricks.md

-----
This is a documentation-only change, so testing and `brew typecheck` are definitely not necessary, and I don’t think `brew style` is relevant either.
Affects https://docs.brew.sh/Tips-N'-Tricks#pre-download-a-file-for-a-formula
Writing the long flag here helps the user understand what the command does. The short flag is more appropriate for interactive use of `brew`.

In Tips and Tricks doc, expand `-s` flag

---

Library/Homebrew/github_packages.rb

-----
Instead of gunzipping the entire file in memory (potentially several GB), do 64KB blocks and feed that into the SHA256 digester.
A little slower but significantly more memory efficient.

github_packages: fix OOM with large bottles

---

Library/Homebrew/keg_relocate.rb

`codesign_patched_binary` does not live in `extend/os/mac/keg_relocate` so a generic method cannot be put in `keg_relocate`.

Revert "keg_relocate.rb: create generic codesign_patched_binary"

---

Library/Homebrew/utils/github.rb

-----
- I wrote this as part of https://github.com/issyl0/homebrew-maintenance-utils/blob/main/cmd/find-invalid-head-branches.rb, as I needed to check if a branch exists on a repo, and thought I'd properly add it in case it's useful to others.

utils/github: Add a `branch_exists?` method

---

Library/.rubocop.yml

-----
- The usage in the `xmlsectool` formula went away in https://github.com/Homebrew/homebrew-core/commit/76618ad7fca31ed7c5a7c1f8a4c688662bbacc64.
- If I revert the changes in that commit and run `brew style --only="Naming/InclusiveLanguage" xmlsectool`, RuboCop reports an offense and suggests an alternative term.

rubocop: Remove an allowlist entry for `blacklist` usage

---

Library/Homebrew/test/spec_helper.rb

-----
This fixes a situation where the output of `brew tests` will modify the `stty` attributes of the terminal and also cause test output to appear garbled with mishandled newlines.
Not entirely sure why this happens - I can't reproduce it outside of `brew tests` - but we should be doing this safe handling anyway, and we already to it for stdout and stderr.

test/spec_helper: prevent stdin trashing

---

Library/Homebrew/test/os/mac/dependency_collector_spec.rb

-----
There should be no condition after d0de6ac24960140f16d969cc0abce164393e9009.

test/os/mac/dependency_collector_spec: fix svn test on older macOS

---

Library/Homebrew/formula_installer.rb

-----
- Fixes #12965.
- For a formula with an architecture requirement and a user requesting `--only-dependencices` to be installed, this now proceeds to install the formula dependencies regardless of the requested formula architecture because the formula itself will never be installed.
- The way dependencies and requirements are computed, the `depends_on :arch` is still a dependency, so it's in the list of formula dependencies to check and potentially install. Hence, we have to remove from the list the dependent from `recursive_requirements` with the same name as the formula so that there are no confusing unsatisfied requirements for the named formula when we don't need it to be installed.
- I thought about why this might be, maybe it's because we can't guarantee that formula …

formula_installer: Fix `--only-dependencies` formula arch handling

---

Library/Homebrew/cleanup.rb

-----
Shows total disk space freed on cleanup. Currently, `Cleanup.disk_cleanup_size` is only incremented during dry runs, and total disk space freed is only shown if `Cleanup.disk_cleanup_size` is not zero. This PR moves the `@disk_cleanup_size` update out of the `dry_run` check, and removes the bizarre provision to negate the update, since `disk_usage` is invariable equal to `path.disk_usage`, and thus `@disk_cleanup_size += disk_usage - path.disk_usage` never does anything.
I could not find any explanation / could not imagine a reason why this was done in the first place; please enlighten me if there  actually was a reason for this. In any case, the redundant/useless code should be removed.
I was motivated to make this change after running `brew cleanup`, seeing a bunch of files …

Show total disk space freed on cleanup.

---

Library/Homebrew/extend/pathname.rb
Library/Homebrew/linkage_checker.rb
Library/Homebrew/os/linux/elf.rb

-----
An executable that links against `@rpath`-prefixed dylibs must include at least one `LC_RPATH`. This will prevent issues like the one resolved in https://github.com/Homebrew/homebrew-core/pull/91485.
Caveats:
1. This won't find executables that have only recursive dylib dependencies with @rpath prefixes.
1. This makes no attempt to resolve `@rpath`, `@executable_path` or `@loader_path` dylibs, or to verify the correctness of any `LC_RPATH` entries, or to otherwise simulate dlopen logic.
1. Weakly-linked dylibs are still excluded from the search for broken linkage.
1. I am not fluent in Ruby. 😊
The scope is narrow in order to focus on this particular problem. It is meant only as a sanity check.

linkage: display executables with missing rpath

---

Library/Homebrew/cmd/uses.rb
Library/Homebrew/description_cache_store.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/dev-cmd/unbottled.rb
Library/Homebrew/formula.rb
Library/Homebrew/tap.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

Add some `--all` flags we'll eventually migrate to to ensure that we'll eventually require their usage to read all formulae. Where we need to do stuff later, add some comments.

Update uses of `Formula.all`/`Cask::Cask.all`

---

Library/Homebrew/linkage_checker.rb

-----
This test is causing some rebuilds due to failed linkage upon upgrade.
That's a problem because rebuilds won't fix the problem that the `RPATH`
check identifies.

linkage_checker: restrict `RPATH` test to `--strict`

---

Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/test/keg_relocate/grep_spec.rb

We discussed here: https://github.com/Homebrew/brew/pull/12940/files#r818284011 that it is much simpler to use `grep` to check if an individual file contains null bytes than to iterate over all files in the keg.  We are only interested in checking files which we already know contain prefixes, which we can pass in as an argument.  This method could also be useful in the future if we need to determine if files are binaries in other situations.
I also reverted `each_unique_file_matching` back to its original state.  If we think it's better to still have a generic `each_unique_file` method that is called by `each_unique_file_matching`, that's totally fine with me.  At the moment only `each_unique_file_matching` would need to call `each_unique_file`, but it's possible some future methods could …

Use simpler method to detect binaries

---

Library/Homebrew/formula_installer.rb

-----
remove `attr_writer` from `FormulaInstaller` because the `attr_writer` was removed from `test-bot` after the PR https://github.com/Homebrew/homebrew-test-bot/pull/792

remove useless attr_writer from `FormulaInstaller`

---

Library/Homebrew/software_spec.rb
Library/Homebrew/test/software_spec/bottle_spec.rb

This is a relatively minor change that extract the code we currently use to get the cellar from the tag from `compatible_locations?` into its own method so we can call it directly, and refactors `compatible_locations?` to use that method, to avoid redundant code.  Basic unit tests have also been added for both methods.  More complex testing may be difficult without more refactoring because `HOMEBREW_CELLAR` and `HOMEBREW_PREFIX` are constants that I didn't see an obvious way to override.

Add tag_to_cellar method

---

Library/Homebrew/service.rb
Library/Homebrew/test/service_spec.rb

- [ x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ x] Have you successfully run `brew style` with your changes locally?
- [ x] Have you successfully run `brew typecheck` with your changes locally?
- [ x] Have you successfully run `brew tests` with your changes locally?
-----
This PR is related to the kill command that I'm …

Added Service#keep_alive? method

---

Library/Homebrew/shims/linux/super/ninja
Library/Homebrew/shims/mac/super/ninja
Library/Homebrew/shims/super/ninja

-----
We do it for Make so we should start doing it for Ninja too now.

shims: enable cc arg refurbishment for ninja

---

docs/Cask-Cookbook.md

-----
Closes https://github.com/Homebrew/brew/issues/12998
add `arm64` to `depend_on` information in `docs/Cask-Cookbook.md`

add arm64 info to Cask-Cookbook.md

---

Library/Homebrew/cmd/deps.rb

-----
closes https://github.com/Homebrew/brew/issues/13009
repair `dot_code` in `cmd/dep` to show `CaskDependent` name

`cmd/deps`: repair `dot_code`

---

Library/Homebrew/formula_auditor.rb

-----
* Fix audit not being run at all due to always-false condition (`@build_stable`).
* Don't fail audit if versioned alias would clash with a versioned formula (e.g. we for a few days had `go@1.17` as a formula while the main `go` formula was also still 1.17).
* Allow versioned aliases with the name of another alias (e.g. `kubectl` is an alias of `kubernetes-cli`, so allow - but not require - `kubectl@1.23` to exist).

formula_auditor: fix versioned alias audit

---

Library/Homebrew/formula_installer.rb
Library/Homebrew/keg.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/keg_relocate/binary_relocation_spec.rb

Now that we've merged https://github.com/Homebrew/brew/pull/12890, we can narrow the focus of this PR only to what is necessary to enable binary patching.  I've written a new unit test `keg_relocate/binary_relocation_spec.rb` to test `relocate_build_prefix`, which is by far the most complicated part of the PR.  This should help us avoid breaking this method in the future.   I'm not sure how practical it is implement useful unit tests for the other changes but they're not as complex.

Binary patching of build prefixes 

---

Library/Homebrew/utils/github/api.rb

Ensure that recommended URL matches "scopes required" list. Closes #13030.

github_api: fix PAT URL

---

Library/Homebrew/style.rb

---
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Revert Homebrew/brew#13044.  In that PR, @MikeMcQuaid commented:  
> Passing on this. Will review additional parameters to `brew test-bot` if desired.
then closed the PR by merging its proposed changes.  Given the above, I suspect this was an accident, hence this PR to revert said changes.  
(Note:  Regarding unchecked boxes in the PR header above:  apologies; I unfortunately don't have a working machine capable of running Homebrew that I can complete those steps on at the moment.  I made this PR via GitHub's web interface.)

Revert "Enable .rubocop.yml in taps"

---

Library/Homebrew/extend/os/linux/diagnostic.rb

-----
This should fix https://github.com/Homebrew/brew/issues/13039. Right now on Linux, we run `check_linuxbrew_core` unconditionally. The core tap is absent when installing from API so this leads to a fatal error. Instead, adjust `check_linuxbrew_core` to skip/ignore missing core tap when installing from API.

diagnostic: skip linuxbrew-core tap check when installing from API

---

Library/Homebrew/rubocops/lines.rb
Library/Homebrew/rubocops/shared/helper_functions.rb

This wasn't correctly flagging the use of `on_os` in `test do` as invalid.

rubocops: fix `OnOs` block checks.

---

Library/Homebrew/rubocops/uses_from_macos.rb

The macOS SDK contains headers for Berkeley DB (1.8-era).
I believe people with our Berkeley DB installed are getting errors compiling OpenJDK as the newer header is shadowing the older one in the SDK.
To fix this, we should make it keg only.

rubocops/uses_from_macos: allow keg only berkeley-db

---

Library/Homebrew/dev-cmd/unbottled.rb

-----
`qt@5` was showing up as requiring macOS even though it is already bottled on Linux:
```console
❯ brew unbottled --tag=linux qt@5
==> Populating dependency tree...
==> :x86_64_linux bottle status
qt@5: requires macOS
```
With change:
```console
❯ brew unbottled --tag=linux qt@5
==> Populating dependency tree...
==> :x86_64_linux bottle status
qt@5: already bottled
```
Some other checks that should be unchanged:
```console
❯ brew unbottled --tag=linux objc-codegenutils
==> Populating dependency tree...
==> :x86_64_linux bottle status
objc-codegenutils: requires macOS
❯ brew unbottled --tag=linux root
==> Populating dependency tree...
==> :x86_64_linux bottle status
root: already bottled
❯ brew unbottled --tag=linux dark-mode
==> Populating dependency tree...
==> :x86_64_linux bottle …
```

dev-cmd/unbottled: ignore versioned macos when checking linux

---

Library/Homebrew/extend/os/mac/search.rb

-----
related to https://github.com/Homebrew/brew/issues/13028
repair Homebrew::Search::Extension.search_casks to use Cask.full_name instead of Tap.cask_tokens for fuzzy_search
1. before
```bash
brew search  docker-compose
==> Formulae
docker-compose                                                                       docker-compose-completion                                                            docker-completion
If you meant "docker-compose" specifically:
It was migrated from homebrew/cask to homebrew/core.
```
2. after
```bash
brew search  docker-compose
==> Formulae
docker-compose                                                                       docker-compose-completion                                                            docker-completion
==> Casks
docker-toolbox
If …
```

repair cask's fuzzy_search in `search_casks`

---

Library/Homebrew/dev-cmd/pr-pull.rb
Library/Homebrew/test/dev-cmd/pr-pull_spec.rb

pr-pull: allow casks to be pulled

---

Library/Homebrew/cmd/fetch.rb

-----
This is to fix #13088 by passing `prefer_loading_from_api: true` when calling `to_formulae_and_casks`. I am following what I found in `Library/Homebrew/cmd/install.rb` and this solves the issue in my testing; however I know there are larger discussions happening around overall support for `HOMEBREW_INSTALL_FROM_API` so I'm happy to incorporate any additional changes that are needed.

set `prefer_loading_from_api: true` for `brew fetch`

---

docs/Homebrew-Governance.md
docs/Homebrew-Leadership-Responsibilities.md
docs/README.md

This is imported from the private repository agreed upon by the PL, PLC and TSC.
This should not be merged until it is voted upon and approved by the members in/by the Homebrew AGM.

Update Homebrew's governance documentation.

---

Library/Homebrew/tap.rb

when a private repository is tapped
-----
Return earlier if git credential helper is already used. Resolves #13097.

Don't print set git credential cache message if a helper exists

---

Library/Homebrew/extend/os/mac/extend/ENV/super.rb

-----
This will hopefully be a catch-all to fix all SDK-related issues prior to Mojave. (Needs testing.)
See #13098 for prior discussion.
I wonder if the `ac_*` hacks further down will be needed after this fix, but I've not touched them to be on the safe side.

ENV/super: always set HOMEBREW_DEVELOPER_DIR regardless of macOS version

---

Library/Homebrew/download_strategy.rb

An alternative to Homebrew/brew#13108 for fixing Homebrew/homebrew-cask#121725, but I think it makes sense to make both changes.
We currently parse query strings `https://example.com/download.php?file=foo-1.0.tar.gz` to extract the file extension.
This is not always correct. Sometimes you have scenarios like `https://example.com/file=foo-1.0.tar.gz?host=elsewhere.com` where it'll think `elsewhere.com` is the basename.
It's impossible to tell really how a URL should be parsed, so what I've done is alter the behaviour of URL parsing in the scenario where we've already followed redirects and checked headers. This means we have checked for and did not find a `Content-Disposition` so we are safe to follow what browsers do: take the basename, ingoring the query string.
Keep the original …

download_strategy: ignore query strings when parsing resolved URLs

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/test/utils/github_spec.rb
Library/Homebrew/utils/github.rb
Library/Homebrew/utils/github/api.rb

The previous method of searching based on PR branch was very fragile - it was already known to be broken when a PR was submitted with the `master` branch as a source, and it has today broken entirely for some reason (likely an issue on GitHub's side).
I've rewritten it to now be much more reliable. Or at least it seems to work a lot better from the very low sample size of PRs I've tested.
Although ideally this would go through the usual 24 hour review period (and maybe refactoring to avoid the `Metrics/ModuleLength` exception), I'm expediting this since our merge process over at homebrew-core is currently completely broken.

utils/github: rewrite get_workflow_run using GraphQL

---

Library/Homebrew/test/utils/github_spec.rb
Library/Homebrew/utils/github.rb

Follow up adter #13124
I made the choice to convert the pr variable to an integer
at the very end and adjust the tests.
It would be maybe more consistent to work with an integer
everywhere, but this needs a more careful analysis and we
are in a hurry to fix the homberew-core upload CI
> Fixes:
2022-04-11T20:19:34.1395885Z [31mError:[0m : Variable $pr of type Int! was provided invalid value
2022-04-11T20:19:34.1398279Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github/api.rb:261:in `open_graphql'
2022-04-11T20:19:34.1399774Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/github.rb:310:in `get_workflow_run'
2022-04-11T20:19:34.1403699Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:418:in `block (4 levels) in pr_pull' …

utils/github.rb: convert pr to integer

---

Library/Homebrew/extend/os/mac/keg.rb
Library/Homebrew/keg.rb
Library/Homebrew/os/mac/keg.rb

Move codesign_patched_binary to extend/os/mac/keg.rb

---

Library/Homebrew/dev-cmd/bump.rb
Library/Homebrew/utils/repology.rb

-----
macOS 12.3's shipping curl now supports TLS 1.3, so we can skip installing the curl formula in that case.

bump: resume checking for TLS 1.3 support

---

Library/Homebrew/dev-cmd/edit.rb

-----
arrange the error message of `brew edit --cask` like one of `brew edit --formula`
- before PR
```bash
$ brew edit --cask atomm
Usage: brew edit [options] [formula|cask ...]
Open a formula or cask in the editor set by EDITOR or HOMEBREW_EDITOR,
or open the Homebrew repository for editing if no formula is provided.
--formula, --formulae        Treat all named arguments as formulae.
--cask, --casks              Treat all named arguments as casks.
--print-path                 Print the file path to be edited, without
opening an editor.
-d, --debug                      Display any debugging information.
-q, --quiet                      Make some output more quiet.
-v, --verbose                    Make some output more verbose.
-h, --help                       Show this message.
Error: …
```

arrange error message of 'brew edit --cask'

---

Library/Homebrew/cask/cmd/install.rb
Library/Homebrew/cask/cmd/reinstall.rb
Library/Homebrew/cask/installer.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/test/cask/cmd/list_spec.rb
Library/Homebrew/test/cask/cmd/reinstall_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/local-caffeine.rb

-----
- The `brew uninstall` command has `--zap`, so let's make `brew reinstall` have parity here for a better user experience.
- It feels weird that to get my new reinstall test to pass I had to add `--zap` to `cask/cmd/install.rb`, not `cask/cmd/reinstall.rb` to get the tests to pass. But the `brew reinstall --cask caffeine --zap` command worked fine all the time. The CLI argument parser from the test run was complaining about not knowing what `zap` was. As a result, `--zap` now shows up as a switch in `brew install --help` which I'm not 100% convinced is the desired UX. But I've edited the description accordingly to specify that it will only work on `reinstall` operations (and `--zap` on `install` is a no-op).
- Fixes #12983.
----
```
issyl0 at pictor in /opt/homebrew on …
```

cask/reinstall: Support `--zap` for entirely purging cask files

---

Library/Homebrew/version/null.rb

-----
Alias the `MacOS.version.outdated_release?` method so it can be used in formulae, i.e. https://github.com/Homebrew/homebrew-core/pull/99023#discussion_r849000378.

null.rb: alias outdated_release? to allow formulae usage

---

Library/Homebrew/cmd/list.rb

list: output only if installed casks are passed

---

Library/Homebrew/formula_cellar_checks.rb
Library/Homebrew/formula_installer.rb

-----
This fixes two complementary errors I've seen recently:
- `formula_installer.rb`: when running `brew reinstall`, `reinstall.rb` checks for the existing keg via its opt prefix and backs it up to `#{path}.reinstall` if it exists. But if for some reason that opt prefix symlink is missing, the installer will happily overwrite the existing keg in-place… until it attempts to create the ".brew" folder, which throws `Error: File exists @ dir_s_mkdir - /usr/local/Cellar/<formula>/<version>/.brew`. Swapping `mkpath` for `mkdir` avoids the error.
- `formula_cellar_checks.rb`: some bottles that have been around for a while (e.g. `yajl`) lack the ".brew" directory, which causes `check_cpuid_instruction` to complain with `Error: No such file or directory @ rb_sysopen - …

formula_installer: handle unexpected .brew presence/absence

---

Library/Homebrew/service.rb
Library/Homebrew/test/service_spec.rb
docs/Formula-Cookbook.md

-----
This adds the last remaining features to services before we can deprecate plist usage.

service: add sockets and keepalive variants

---

Library/Homebrew/cmd/update-report.rb

-----
This outputs the old and new version numbers along with the version hashes when they are different otherwise it outputs the old message. This was first proposed in issue #12760.
```
$ brew update    
Updated Homebrew from 3.3.9 (db648bcde) to 3.3.11 (249b0439e).
...
==> Homebrew was updated to version 3.3.11
The changelog can be found at:
https://github.com/Homebrew/brew/releases/tag/3.3.11
```
Closes #12760

Display old and new version numbers when updating Homebrew

---

.github/codeql/codeql-config.yml
.github/workflows/codeql-analysis.yml
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/rubocops/homepage.rb
Library/Homebrew/rubocops/urls.rb

-----
- https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning
- I just joined the Code Scanning team at work and I figured I'd test out the actual product in the real world by seeing what things it points out for Homebrew, a reasonably large Ruby project.
- This adds a config file to exclude `Library/Homebrew/vendor` as we can't fix problems within gems. :-)

workflows: Add Code Scanning action, fix up failures

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/livecheck/strategy.rb
Library/Homebrew/test/utils/curl_spec.rb
Library/Homebrew/utils/curl.rb

-----
This work was originally part of #9535 and then #10834 (a recreation of the former PR) but I've refactored the methods to make them a bit more general purpose here. While working on migrating livecheck to curl, it became apparent that there are a few areas in brew where similar code exists to parse curl output.
The intention of this PR is to provide methods for working with curl output in a standardized way, so we can avoid unnecessary code duplication. Notable changes are as follows:
* Adds `parse_curl_output` and `parse_curl_head` methods to parse curl output (a string containing response head(s) and/or the final response body). The code in these methods is partly taken from existing code in brew, as the aim is to replace existing code with these methods. The main difference is …

Curl: Add methods to parse response

---

Library/Homebrew/dependency.rb
Library/Homebrew/extend/os/linux/keg_relocate.rb

-----
This should fixes #13040.

Skip build deps to avoid downloading bottles

---

Library/Homebrew/extend/os/linux/keg_relocate.rb

Only noticed this subtle behavioural change after merging. Let's restore the old comparison behaviour to avoid any unintended consequences (and use `.major` rather than `.to_i` to make it more obvious).

extend/os/linux/keg_relocate: restore checking only GCC major versions

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
Exposes CLI flags from `update-python-resources` so they can be used in `bump-formula-pr`:
- `brew update-python-resources --package-name` -> `brew bump-formula-pr --python-package-name`
- `--extra-packages` -> `--python-extra-packages`
- `--exclude-packages` -> `--python-exclude-packages`
Original PR changes (outdated)
<details>
- Add support for HOMEBREW_PIPGRIP_ADDITIONAL_DEPENDENCIES which will be
propagated into PIPGRIP_ADDITIONAL_DEPENDENCIES when calling pipgrip
pipgrip 0.8.0 adds support for the `PIPGRIP_ADDITIONAL_DEPENDENCIES` environment variable which can be used to pass additional dependency information into pipgrip. When using the homebrew dev tools (`update-python-resources` and `bump-formula-pr`) this cannot be propagated into pipgrip due to the env var filtering …

bump-formula-pr: expose update-python-resources CLI flags

---

Library/Homebrew/tap_constants.rb

-----
This PR allows using `_` in cask names. 
`_` still is not allowed for homebrews tap casks, should we allow it or we'd like to be a bit more strict about it?
Fixes https://github.com/Homebrew/brew/issues/13168

tap_constants: allow to use underscore in cask names

---

Library/Homebrew/cli/parser.rb

-----
I just stumbled on this randomly and it looks like sorbet/sorbet#498 got resolved so the type checking should work as intended now. This specific case only seems to show up once in the codebase.
It looks like this small change actually helped uncover a small bug. Essentially, since this check was being skipped, the `caller_locations` method call on line 124 of the `cli/parser.rb` file was able to grab the right command name during testing. This is used in turn to create the usage banner.
```Ruby
@command_name = caller_locations(2, 1).first.label.chomp("_args").tr("_", "-")
```
Now it borks the tests in `test/cmd/help_spec.rb` because Sorbet is running extra checks and those caller locations have been added to the stack. It still works correctly when you use the app normally though. …

cli/parser: Re-enable Sorbet Type Checking

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/utils/curl.rb
Library/Homebrew/utils/spdx.rb

-----
When its `try_partial` argument is `true`, `#curl_download` makes a `HEAD` request before downloading the file using `#curl`. Currently `try_partial` defaults to `true`, so any `#curl_download` call that doesn't explicitly specify `try_partial: false` will make a `HEAD` request first. This can potentially involve several requests if the URL redirects, so it can be a bit of unnecessary overhead when a partial download isn't needed.
Partial downloads are generally only useful when we're working with larger files, however there's currently only one place in brew where `#curl_download` is used and this is the case: `CurlDownloadStrategy`. The other `#curl_download` calls are fetching smaller [text] files and don't need to support partial downloads.
This PR changes the default …

`#curl_download`: default `try_partial` to `false`

---

Library/Homebrew/livecheck/strategy.rb
Library/Homebrew/utils/curl.rb

-----
The default redirection maximum for `curl` is 50 but we should use something more reasonable in livecheck. It's rare but a misconfigured server with an endless redirection loop will hit the 50 redirection limit. Unfortunately, we've encountered this in the wild (e.g., the server for `getmail` and `memtester` endlessly redirects at the moment), so it's not an idle concern. This PR basically adds `--max-redirs 5` to `Livecheck::Strategy::DEFAULT_CURL_ARGS` to enforce a more reasonable redirection maximum.
To be clear, the `max_iterations` logic in `#parse_curl_output` (which was previously found in `Strategy#page_content`) doesn't restrict the number of redirections that `curl` follows. At the point the `curl` output is being parsed, the requests have already been made and …

`Strategy`: Add `--max-redirs` to `DEFAULT_CURL_ARGS`

---

Library/Homebrew/utils/curl.rb

-----
This PR fixes headers check in `url_protected_by_cloudflare? and `url_protected_by_incapsula?` methods.
```
$ brew audit linode-cli --online --git --skip-style --verbose
Error: undefined method `match?' for #<Hash:0x00007fd81a9de668>
/usr/local/Homebrew/Library/Homebrew/utils/curl.rb:205:in `url_protected_by_cloudflare?'
/usr/local/Homebrew/Library/Homebrew/utils/curl.rb:268:in `curl_check_http_content'
/usr/local/Homebrew/Library/Homebrew/formula_auditor.rb:469:in `audit_homepage'
/usr/local/Homebrew/Library/Homebrew/formula_auditor.rb:845:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/formula_auditor.rb:840:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_auditor.rb:840:in `audit' …
```

utils/curl: fix headers check for protected urls

---

Library/Homebrew/utils/curl.rb

-----
The `max_iterations` value in `#parse_curl_output` is only intended to prevent its `while` loop from potentially turning into an endless loop. This should only come into play in exceptional circumstances but the current default value (5) is low enough that we're seeing it under normal circumstances.
`#parse_curl_output` isn't intended to restrict the number of redirections (this should be done using the `--max-redirs` option in `curl) but it's effectively doing this in rare cases due to the low `max_iterations` default. This is a problem because `curl` can successfully return a response only to have `#parse_curl_output` error in relation to `max_iterations`.
Originally the code in `#parse_curl_output` was used in the context of livecheck, where it's not a huge issue if a check …

`#parse_curl_output`: increase default `max_iterations`

---

Library/Homebrew/searchable.rb

Fix #13203 which occurs when searching cask descriptions.
---

searchable: flatten array before matching

---

Library/Homebrew/extend/os/mac/search.rb

-----
Results in searching a list of tokens from official Homebrew cask taps and fully-qualified tokens from other taps, matching the list when searching formulae. Fixes #13193.

search: drop Homebrew cask tap names from list

---

Library/Homebrew/os/mac/pkgconfig/12/libcurl.pc
Library/Homebrew/os/mac/pkgconfig/12/libffi.pc
Library/Homebrew/os/mac/pkgconfig/12/sqlite3.pc
Library/Homebrew/test/os/mac/pkgconfig_spec.rb

We're now actively building using the 12.3 SDK and will be using a runner with the 12.3 OS installed (the ephemeral one) from tomorrow afternoon.
Unfortunately we don't handle minor SDK versions, and this is one of the first times this has ever changed for something as potentially backwards ABI incompatible as curl. But we don't really test/support older minor versions anyway. And Apple don't either by not keeping an SDK for them.

os/mac/pkgconfig/12: update for macOS 12.3

---

Library/Homebrew/dev-cmd/pr-pull.rb
Library/Homebrew/test/dev-cmd/pr-pull_spec.rb

pr-pull: add checksum update clause

---

Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/skip_conditions.rb
Library/Homebrew/test/dev-cmd/livecheck_spec.rb
Library/Homebrew/test/livecheck/skip_conditions_spec.rb

-----
I find the space before the colon mildly irritating and saw no reason to keep it, but if there is one feel free to close this PR.

Remove space before colon in `livecheck` output

---

Library/Homebrew/rubocops/cask/homepage_url_trailing_slash.rb

Fix Rubocop trailing `/` bug

---

.github/workflows/docker.yml

When we published the ubuntu22.04 image, it wasn't attached to this repository and so it was hidden away in the masses of the org-wide packages.
I've linked the image to the repository manually, but it looks like GitHub looks for and points to documentation on OCI metadata when auto-linking: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
So that there's one less thing to do in the future, might as well add those?
I also forgot to create a Docker Hub repository (since unlike GCR, you need to go do that yourself on the website), but I'll do that and push locally so it should work for 3.4.10.

workflows/docker: add OCI metadata

---

Library/Homebrew/cleaner.rb
Library/Homebrew/test/cleaner_spec.rb

Still cleans `info/dir` and `info/<arch>/dir` files.
Fixes https://github.com/Homebrew/homebrew-core/issues/100190

Keep `info/#{f.name}/dir` files in cleaner

---

.github/workflows/docker.yml
Dockerfile

As per discussion on Slack, I think we can make the switch now rather than wait some arbitrary length of time.
I've also disabled fail-fast so that if a image upload fails in the future, we don't stop the other uploads halfway unnecessarily.

workflows/docker: base homebrew/brew on 22.04

---

Library/Homebrew/cask/installer.rb
Library/Homebrew/test/cask/cask_loader/from__path_loader_spec.rb
Library/Homebrew/test/cask/installer_spec.rb

-----
The problem occurred when calling `brew reinstall` on a cask with an out of date caskfile as described in issue #10833.
To solve the problem `Cask::Installer#uninstall_existing_cask` has been changed to catch a possible `CaskInvalidError` when trying to load outdated caskfiles using `Cask::CaskLoader#load`.
Fixes #10833.

Allow casks with outdated caskfiles to be reinstalled

---

Library/Homebrew/dev-cmd/tests.rb

-----
This updates the `brew tests --changed` option to support changed test files. Before it would only run tests that correspond to changed library files but wouldn't run tests on changed test files. It also ignores Ruby files that lack the `*_spec.rb` ending in the test folder like fixtures.
The reason that I made it another method was because the linter was yelling at me about a long block and, to be honest, I agree that it's more readable.

'brew tests --changed' supports changed test files

---

Library/Homebrew/utils/curl.rb

-----
This PR fixes an audit error for non-utf-8 URL content.
An example (spotted in https://github.com/Homebrew/homebrew-core/pull/100559):
```
$ brew audit opencsg --online --skip-style --verbose
Error: invalid byte sequence in UTF-8
/usr/local/Homebrew/Library/Homebrew/utils/curl.rb:299:in `gsub'
/usr/local/Homebrew/Library/Homebrew/utils/curl.rb:299:in `curl_check_http_content'
/usr/local/Homebrew/Library/Homebrew/formula_auditor.rb:469:in `audit_homepage'
/usr/local/Homebrew/Library/Homebrew/formula_auditor.rb:845:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/formula_auditor.rb:840:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_auditor.rb:840:in `audit' …
```

utils/curl: force utf-8 encoding for text content

---

Library/Homebrew/extend/os/linux/extend/ENV/super.rb

-----
From discussion in Homebrew/homebrew-core#99630 to avoid issues when trying to prioritize keg_only linkage for "drop-in" libraries (e.g. `libpq`, `luajit-openresty`, `jpeg-turbo`, ...)
Didn't see anyone open PR for it yet. Can discuss further if there are any odd scenarios to consider.
Will still require new bottles to update problematic RPATHs.

superenv: prioritize dependencies' `opt_lib` in Linux rpath

---

Library/Homebrew/cmd/link.rb
Library/Homebrew/diagnostic.rb

The output of `brew doctor` can mention the command `brew diy`, which was removed in [this PR](https://github.com/Homebrew/brew/pull/11719). It's better to remove this output to avoid confusing users. I replaced the text "...deleted or installed with \`brew diy\`" with "...deleted or installed manually", since manual installation of a program is usually what will lead to this message, but if you think something else would be better, let me know.
- no, as far as I'm aware this change doesn't need a test
-----

Remove mentions of nonexistent command `brew diy`

---

Library/Homebrew/test/utils/curl_spec.rb
Library/Homebrew/utils/curl.rb

-----
Before `#parse_curl_output` was introduced and related methods were updated to use it, `#url_protected_by_cloudflare?` and `#url_protected_by_incapsula?` were checking a string of all the headers from a response and using a regex to check related header values.
However, when `#curl_http_content_headers_and_checksum` was updated to use `#parse_curl_output` internally, the `:headers` value became a hash generated by `#parse_curl_response`. The `#url_protected_by_*` methods were updated in #13198 to work with the hash value but this wasn't able to fully replicate the previous behavior because `#parse_curl_response` was only keeping the last instance of a given header (maintaining pre-existing behavior). This is an issue for these methods because they check `Set-Cookie` headers and …

`parse_curl_response`: Handle duplicate headers

---

Library/Homebrew/cli/args.rbi
Library/Homebrew/cmd/tap.rb
Library/Homebrew/tap.rb
Library/Homebrew/test/tap_spec.rb

Enable this option to delete `homebrew.forceautoupdate` git config option
-----
Unlike what the issue described, using `--force-auto-update` will add the `homebrew.forceautoupdate` git config option for a installed tap, so I only add a new option to delete this value.
Resolves #13246

Add `--no-force-auto-update` option to `brew tap`

---

Library/Homebrew/cask/cmd/install.rb
Library/Homebrew/test/cask/installer_spec.rb

Don't print Cask installed error message when `--quiet` is used

---

Library/Homebrew/github_packages.rb

-----
Upstream made a change that broke our publish workflow. The change appears to be a regression rather than anything that's solvable on our side.
I think ideally this will be pinned to tagged releases, but we are using features newer than the latest.

github_packages: pin image spec schema

---

.github/dependabot.yml
.github/workflows/vendor-gems.yml
Library/Homebrew/Gemfile
Library/Homebrew/Gemfile.lock
Library/Homebrew/vendor/bundle/bundler/setup.rb

This links `sorbet-static` with `sorbet-runtime`, creating an equality constraint that should allow Dependabot to update both at the same time without the special handling we do.
The gem itself is otherwise empty and contains nothing.

Use sorbet-static-and-runtime gem

---

Library/Homebrew/cask/caskroom.rb
Library/Homebrew/cask/cmd/uninstall.rb
Library/Homebrew/cask/cmd/zap.rb
Library/Homebrew/cli/named_args.rb

When casks are unreadable (e.g. have invalid syntax, the cask file cannot be found) then it's not been possible to uninstall them, list them or perform any operation which iterates through all casks.
Handle these various cases by falling back to creating a `Cask::Cask` object using just the name/token and latest installed version on disk.
This provides enough functionality to be able to verbosely list these casks, not error on listing and, most importantly, uninstall/reinstall them.
Fixes https://github.com/Homebrew/homebrew-cask/issues/62223

Fix handling unreadable casks

---

Library/Homebrew/Gemfile
Library/Homebrew/Gemfile.lock
Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/test/livecheck/livecheck_spec.rb

-----
At the moment, `#use_homebrew_curl?` can only be true for a `homepage` or `stable`/cask `url` with `using: :homebrew_curl`. If the checked URL differs from these URLs, livecheck won't use brewed curl. This limitation prevents livecheck from using brewed curl for a `livecheck` block URL that's a string literal (not a symbol for a `#checkable_url` like `:stable`, `:head`, `:url`). `libzip` was the original formula referenced in the related brew issue and it meets this criterion, so it doesn't appear to be handled by the existing `#use_homebrew_curl?` implementation.
Additionally, the existing behavior can cause livecheck to unnecessarily use brewed curl for a completely different website (e.g., `cubelib`, `otf2`). For example, if the `stable` URL has `using: :homebrew_curl` and the …

Livecheck: Use Homebrew curl based on root domain

---

Library/Homebrew/style.rb

This allows removing documentation explaining them.

style: use long shfmt arguments.

---

Library/Homebrew/cask/cask.rb
Library/Homebrew/cask/installer.rb
Library/Homebrew/test/cask/cask_spec.rb
Library/Homebrew/test/cask/cmd/upgrade_spec.rb
Library/Homebrew/test/cask/installer_spec.rb

-----
This PR is related to issue #11513 where `version :latest` casks would always be reinstalled when the `--greedy` or `--greed-latest` flags were passed to `brew upgrade` regardless of whether or not the casks had been updated.
Basically the idea is to store a sha256 hash of the original download file every time a `version :latest` cask is installed. Then, before upgrading casks `cask#outdated?` is queried which internally compares the new and old sha of `version :latest` casks to see if they should be updated. As far as I can see, the first download used to check the sha should be cached so it shouldn't need to be downloaded again before installing it.
The sha is stored in a file called `LATEST_DOWNLOAD_SHA256` in the `.metadata/` cask subdirectory. If there is no previous sha …

Only upgrade :latest casks when --greedy and the cask has been updated

---

Library/Homebrew/Gemfile
Library/Homebrew/Gemfile.lock
Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/test/livecheck/livecheck_spec.rb

Revert "Livecheck: Use Homebrew curl based on root domain"

---

Library/Homebrew/exceptions.rb

Fix an issue where if a failing command argument reported to BuildError contains a backslash, it was not being escaped.
The effect is cosmetic and not a security issue. It only affects how the command is printed to console. After this change, such commands should more correctly reflect how the command would look if entered into a command line.
Fixes https://github.com/Homebrew/brew/security/code-scanning/6.

exceptions: handle backslash in args for BuildError

---

Library/Homebrew/test/rubocops/patches_spec.rb

Fixes https://github.com/Homebrew/brew/security/code-scanning/2 (2).
Fixes https://github.com/Homebrew/brew/security/code-scanning/3 (3).
Fixes https://github.com/Homebrew/brew/security/code-scanning/4 (4).
Fixes https://github.com/Homebrew/brew/security/code-scanning/5 (5).
These are tests, and the inputs are controlled by a fixed array in the same file, so this is not a security issue or even a possible bug. Nevertheless, silencing those alerts is trivial here.

test/rubocops/patches: silence CodeQL alerts

---

Library/Homebrew/env_config.rb
Library/Homebrew/test/download_strategies/curl_spec.rb

bottle URLs are treated differently than any other URL.
this change clarifies the resulting URLs in the manpage.
closes #13222
-----

docs: clarify application of HOMEBREW_ARTIFACT_DOMAIN

---

Library/Homebrew/brew.sh
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/cmd/update.sh
Library/Homebrew/env_config.rb
Library/Homebrew/test/completions_spec.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

- Rename use of "preinstall" to "auto update". The original "preinstall" naming came from the fact that we used to only auto-update before `brew install` but now that it's many commands: this is more confusing than useful.
- Add `HOMEBREW_NO_UPDATE_REPORT_ONLY_INSTALLED` and remove `HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED`; the latter is now the default and the prior provides an opt-out for better output, performance and avoiding reading potentially untrusted formulae.
- Add `HOMEBREW_UPDATE_FORMULA_VERSION_CHECKS` and don't check formula versions by default for better performance by default.
CC @boblail for thoughts.

Improve updating behaviour

---

Library/Homebrew/test/download_strategies/curl_github_packages_spec.rb

Constants should never be overridden in tests without using `stub_const`. Otherwise, the constant will leak into other tests and potentially break them.
The constant also needs to be replaced before the first invokation of strategy's constructor, since it is there that the constant is used.

test/download_strategies/curl_github_packages: fix bad const override

---

Library/Homebrew/utils/github.rb

We had an issue where a CI run contained multiple artifacts of the same name: https://github.com/Homebrew/homebrew-core/actions/runs/2352886523
This is the first time I've ever seen it happen, so the issue is perhaps very rare or was the result of a temporary issue, but in such cases I believe taking the last artifact is more correct than taking the first, given the last one should have a higher ID number and thus have been created most recently.

utils/github: take last artifact rather than first

---

Library/Homebrew/test/utils/curl_spec.rb
Library/Homebrew/utils/curl.rb

-----
The response from a URL protected by Cloudflare may only provide a relevant cookie on the first response but `#curl_http_content_headers_and_checksum` only returns the headers of the final response. In this scenario, `#curl_check_http_content` isn't able to properly detect the protected URL and this is surfaced as an error instead of skipping the URL (see https://github.com/Homebrew/homebrew-cask/pull/124277).
This PR resolves the issue by including the array of response hashes in the return value from `#curl_http_content_headers_and_checksum`, so we can check all the responses in `#curl_check_http_content`.
Besides that, this also renames the `:status` key in the return hash from `#curl_http_content_headers_and_checksum` to `:status_code`. This aligns the key name with the return …

Curl: Check all responses for protected cookies

---

Library/Homebrew/os/mac/xcode.rb

The current pattern matching `/clang-(\d+\.\d+\.\d+(\.\d+)?)/, 1` in the `detect_clang_version` method fails to fully match the new clang version string `"1316.0.21.2.5"` introduced with CLT 13.4, which lead to a false report of outdated CLT.
With this rewritten regex `/clang-(\d+(\.\d+)+)/, 1`, we have a more robust pattern matching enabled.
-----

Fix detect_clang_version version extraction

---

Library/Homebrew/test/cask/quarantine_spec.rb
Library/Homebrew/test/spec_helper.rb

When this fails, it was pretty much impossible to figure out why as it just says "audit failed".
Compare stdout and stderr to try get those dumped too.

test/cask/quarantine: improve audit test output

---

Library/Homebrew/brew.sh
Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/xcode.rb

Building for El Capitan on a system that's not El Capitan is always going to be a hack. Aim here is to keep that to a minimum.

os/mac: allow fake El Capitan setup for Portable Ruby builds

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb

-----
Related to issue seen in Homebrew/homebrew-cask#112638
The Cask language SHAs in non-running hardware (e.g. ARM for Intel users) are not updated via `bump-cask-pr`.
Needs some more testing (and maybe some refactoring) before merge.
---
**EDIT:** Does not deal with issue where `bump-cask-pr` fails when `cask.language` uses a language block with different key and return value (e.g. `en != en-US` like in `openoffice`).
The problem is that `cask.language` returns the "called" output of language block while `cask.languages` returns a list of the keys.
One solution: run same `cask.language` logic (for this approach, it may be good to refactor so to allow `fetch_cask(tmp_cask)` to avoid reloading cask):
```diff
--- a/Library/Homebrew/dev-cmd/bump-cask-pr.rb
+++ …
```

bump-cask-pr: bump language checksums in non-running hardware

---

Library/Homebrew/version.rb

Noticed this while using a Version constant over at Homebrew/portable-ruby.
We modify `@tokens` the first time `tokens` is called, so let's make sure that happens before the object is frozen.

version: tokenize prior to freezing

---

Library/Homebrew/exceptions.rb

Discovered while testing a release workflow for Homebrew/portable-ruby.
```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:98:in `did_you_mean': undefined method `fuzzy_search' for Formula:Class (NoMethodError)
from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:142:in `to_s'
from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:168:in `message'
from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:168:in `rescue in <main>'
from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:145:in `<main>'
```

exceptions: fix did_you_mean error in some scenarios

---

Library/Homebrew/cli/named_args.rb

-----
I stumbled across a case where I could not uninstall a cask because the caskfile was invalid (I had installed the test variant of `font-ibm-plex-mono` that uses the git spare checkout logic).
The exception being returning was [CaskInvalidError](https://github.com/Homebrew/brew/blob/6f06236bca93f354120f1d367d66cb7bbf4ddf82/Library/Homebrew/cask/exceptions.rb#L195-L202)
Because there was no `Rescue` for the exception, I was being presented an error.
```
==> brew uninstall font-ibm-plex-mono
Error: Cask 'font-ibm-plex-mono' definition is invalid: 'url' stanza failed with: unknown keyword: only_paths
```
After this change the same logic for unreadable casks is applied in these cases.

named_args: handle additional cask exception

---

Library/Homebrew/cask/quarantine.rb

We use 10.10+ features in the quarantine script, but in some scenarios Swift can default to a 10.9 compatibility mode.

cask/quarantine: fix quarantine not working under some setups

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/description_cache_store.rb
Library/Homebrew/env_config.rb
Library/Homebrew/test/cmd/update-report_spec.rb
Library/Homebrew/test/description_cache_store_spec.rb
Library/Homebrew/utils.rb
docs/Manpage.md
manpages/brew.1

Otherwise users can get confused.

cmd/update-report: use better wording when appropriate.

---

Library/Homebrew/livecheck/strategy/sparkle.rb
Library/Homebrew/test/livecheck/strategy/sparkle_spec.rb

-----
This is a follow-up to #13357, where I added the ability to optionally pass all `Sparkle` `items` into a `strategy` block. That was necessary to be able to filter (or sort) items in a `strategy` block. This PR adds `sparkle:channel` information to the `Item` struct, so we can access it in a `strategy` block and use it for filtering.
These changes are geared toward omitting `beta` channel items in the Sparkle feed for the `graphicconverter` cask (see Homebrew/homebrew-cask#124613). The `strategy` block will be very simple but these changes were necessary to make it technically possible:
```ruby
strategy :sparkle do |items|
items.find { |item| item.channel.nil? }&.nice_version
end
```
Basically, Sparkle items without a channel (i.e., `item.channel == nil`) are implicitly on the …

Sparkle: Provide channel information in Item

---

docs/Formula-Cookbook.md

-----
[Fix](https://docs.brew.sh/Formula-Cookbook#variables-for-directory-locations)es #13367.

Fix #13367 (Document missing shell `_function` and `_completion` variables)

---

Library/Homebrew/cask/installer.rb

-----
This removes the `.metadata/DOWNLOAD_SHA256` file in each cask folder when uninstalling casks. This file was preventing a full uninstall and the presence of the almost empty cask folder would cause the uninstalled cask to continue to show up in `brew list`.

Remove download sha file from .metadata dir when uninstalling casks

---

Library/Homebrew/cask/cask.rb
Library/Homebrew/test/cask/cask_spec.rb

-----
Following the merge of https://github.com/Homebrew/brew/pull/13275 calling `brew outdated --greedy-latest` or `brew upgrade --greedy-latest` was also upgrading other outdated casks (that aren't `version :latest`). This change now ignores casks that are `auto_updates true` but not `version :latest` when using the `--greedy-latest` flag.
BEFORE:
```
==> brew outdated --greedy-latest 
firefox (100.0.1) != 100.0.2
firefox-developer-edition (latest) != latest
font-bebas-neue (latest) != latest
font-josefin-sans (latest) != latest
font-karla (latest) != latest
font-merriweather-sans (latest) != latest
font-nanum-gothic (latest) != latest
```
AFTER:
```
==> brew outdated --greedy-latest
firefox-developer-edition (latest) != latest
font-bebas-neue (latest) != latest
font-josefin-sans …
```

cask: fix greedy outdated command

---

Library/Homebrew/livecheck/strategy/git.rb

-----
The `tags_only_debian` code in livecheck's `Git` strategy was originally introduced in Homebrew/homebrew-livecheck#131 when livecheck was in a less mature state and relied more on internal special-casing like this (i.e., while we worked to add appropriate `livecheck` blocks). This logic only has the potential to be beneficial when a formula/cask doesn't contain a `livecheck` block but I would argue that we shouldn't be making assumptions in the strategy around whether tags with a `debian/` prefix should be matched or omitted. The answer depends upon the context of a given formula/cask and should be handled with a `livecheck` block, as we do with other situations like this.
Besides that, the `tags_only_debian` logic expects that the tags have already been filtered to only include …

Git: Remove tags_only_debian logic

---

Library/Homebrew/livecheck/strategy/git.rb

-----
In a past discussion, it was preferred that we use `system_command` in livecheck's `Git` strategy instead of `Open3.capture3` but it wasn't feasible at the time because we couldn't prevent `#system_command` from printing certain output. I resolved the `SystemCommand` shortcoming long ago in Homebrew/brew#10066, so this finally migrates the `Git` strategy to `system_command`.
I did comparative runs without/with these changes across formulae/casks using the `Git` strategy and didn't observe any issues (i.e., everything works the same as before). I tested known error conditions (e.g., a missing repository, a repository with no tags) and the behavior remains the same.
-----
This should be the last bit of `Git` rework before the forthcoming PR to expand support of cached content in …

Git: Use system_command instead of Open3.capture3

---

Library/Homebrew/cli/parser.rb
Library/Homebrew/test/cli/parser_spec.rb

-----
I was looking at the parser and I was surprised to see that there is a `:required_for` option available for both `switch` and `flag`. Unlike `:depends_on` this option is not used anywhere so I figured it could be removed.

Remove unused parser option required_for

---

Library/Homebrew/livecheck/livecheck.rb

-----
It was mentioned in #13395 that skip messages are printed when livecheck's `--newer-only` option is used and there's currently no way to avoid this. That issue suggested an `--ignore-skipped` option but we agreed that it's simpler to update livecheck's behavior to omit skip messages when the `--newer-only` option is used. [If a user also wants to omit error messages (i.e., only printing newer formulae/casks), they can use `--newer-only --quiet`.]
This PR implements the aforementioned change and also brings the JSON output in line by making the `--newer-only` and `--quiet` options apply to `--json` runs. This gives users a bit of control over the JSON output without having to manually filter it themselves.
Resolves #13395.

livecheck: update --newer-only and --quiet behavior

---

Library/Homebrew/sandbox.rb

A sandbox change in macOS 12.3 means that `file-write-setugid` is no longer covered by the wildcard `file-write*` permission.

sandbox: allow file-write-setugid

---

Library/Homebrew/livecheck/strategy/electron_builder.rb
Library/Homebrew/livecheck/strategy/extract_plist.rb
Library/Homebrew/livecheck/strategy/sparkle.rb

-----
livecheck's `ElectronBuilder`, `ExtractPlist`, and `Sparkle` strategies did not support a regex when they were originally created but I added support for a regex when a `strategy` block is also provided (#12449). At the time, I forgot to add the `regex` value to the `match_data` hash, so this PR updates these strategies accordingly.
Besides that, this adds missing documentation comments (e.g., `# @param regex [Regexp, nil] a regex for use in a strategy block`) and makes other small comment tweaks.

livecheck: update default match_data

---

Library/Homebrew/dev-cmd/extract.rb

These lines now error since 3.5.0 so let's just strip them out like we do for bottle blocks.
Fixes #13405.

dev-cmd/extract: strip out old bottle disable reasons

---

Library/Homebrew/cmd/update-report.rb

-----
Currently new formulae, new casks and renamed formulae are never displayed even when the `HOMEBREW_UPDATE_REPORT_ALL_FORMULAE` environment variable is set. This is because it is unable to enter the unless statement on line 545.
Additionally, I removed checks for `report_all` when the key is
:R, :A or :AC in `ReporterHub#dump_formula_or_cask_report` because
that check is made redundant by the check in `ReporterHub#dump` on line 545.

Fix bug in brew update when displaying all formulae

---

Library/Homebrew/livecheck/strategy/gnome.rb
Library/Homebrew/test/livecheck/strategy/gnome_spec.rb

-----
The `Gnome` strategy's default regex uses the `+` form of the standard regex for matching versions like 1.2.3. However, with the switch to the new version scheme, some packages had a release that omits a minor and patch (i.e., `40` instead of `40.0`). The default regex fails to match versions like this but the looser `*` form will match both. [When creating regexes, we generally start with the `+` form and only switch to the looser `*` form when it's necessary and contextually-appropriate.]
This also updates the default version filtering logic that's applied to versions using the old GNOME version scheme (below version 40). Outside of the refactoring changes, this also filters out versions where the patch number is 90+, as these are also unstable.
Comparing the output without/with …

Gnome: Update default regex and version filtering

---

Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
completions/zsh/_brew

Now that we support an array of runners, there is no reason to make `--macos` and `--linux` mutually exclusive.

dev-cmd/dispatch-build-bottle: remove --macos and --linux conflict

---

Library/Homebrew/formulary.rb
Library/Homebrew/test/formulary_spec.rb

-----
This PR fixes a few issues that I've found with #12936 and adds some more tests.
First, I realized that the preset reason symbols for `deprecate!` and `disable!` aren't encoded into the JSON API in the same way that the preset symbols for `keg_only` and `cellar` are, so I added a method to handle those properly.
Also, the `caveats` method doesn't work as-is, so this PR attempts to fix it.

Formulary Improvements with `HOMEBREW_INSTALL_FROM_API`

---

Library/Homebrew/brew.rb
Library/Homebrew/brew.sh
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/commands.rb
Library/Homebrew/dev-cmd/unbottled.rb

-----
This PR modifies the handling of developer commands with `HOMEBREW_INSTALL_FROM_API`. I've vetted every developer command and separated those that will still work with `HOMEBREW_INSTALL_FROM_API` set so that only those are forbidden. This means that developers can have it set and still run things like `brew irb`, `brew style`, `brew typecheck`, `brew pr-automerge`, etc.
The list mostly comes from [this comment](https://github.com/Homebrew/brew/pull/12936#discussion_r816027220) with the only changes being that `brew pr-automerge` and `brew unbottled` both seem to work with `HOMEBREW_INSTALL_FROM_API` even though they weren't on that list.
I also added a check in `brew install` and `brew reinstall` to make sure that you can't pass `--build-from-source` as this isn't currently …

Allow more developer commands with `HOMEBREW_INSTALL_FROM_API`

---

Library/Homebrew/cask/audit.rb

-----
If a cask with a Sourceforge URL has a `discontinued` caveat, the audits are failing when the livecheck block is omitted. `discontinued` casks should not have livecheck blocks. This PR checks for `cask.discontinued?` and returns early in the audit if true.
Fixes current CI failure for https://github.com/Homebrew/homebrew-cask/pull/125791

cask/audit: skip additional livecheck audit when cask is discontinued

---

docs/Formula-Cookbook.md

Update [directory locations list](https://docs.brew.sh/Formula-Cookbook#variables-for-directory-locations) to cover all the non-private ones. This would help everyone know what directory identifiers can be depended on in formulae.

Formula-Cookbook.md: added missing dirs

---

Library/Homebrew/cmd/outdated.rb

-----
According to the description, `brew outdated --greedy` shows outdated casks. However, the command does casks and formulae actually.
I repair the command to show only casks.

repair `brew outdated --greedy` to show only casks

---

Library/Homebrew/cask/cask_loader.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/cmd/update.sh
Library/Homebrew/formulary.rb

-----
This PR modifies `Formulary` and `Cask::CaskLoader` so that when `HOMEBREW_INSTALL_FROM_API` is set, formulae and casks are always loaded from the API first (if they're available on the API), regardless of whether homebrew/core and homebrew/cask are tapped. Now, if you have an outdated homebrew/core tap that doesn't have the latest version for a formula, the newer version from the API will always be loaded instead of the outdated version from the tap.
I also modified `brew update` to not even try to update homebrew/core and homebrew/cask when `HOMEBREW_INSTALL_FROM_API` is set. Before, these taps were only skipped on auto-updates. I think this makes the most sense since `HOMEBREW_INSTALL_FROM_API` basically says "ignore the core and cask taps" everywhere else. However, if we think …

Always prefer loading from API when `HOMEBREW_INSTALL_FROM_API` is set

---

Library/Homebrew/dev-cmd/livecheck.rb
Library/Homebrew/env_config.rb

-----
Currently the default path for `brew_livecheck_watchlist` doesn't work at all and the environment variable `HOMEBREW_LIVECHECK_WATCHLIST` doesn't get expanded so it only works with absolute paths. This PR sets a correct default path and expands the path before using it.
Is there some way to expand environment variables in a path too since that's currently not possible with `File#expand_path`? That would be nice to have as well.
Fixes #13453.

livecheck: fix path to livecheck watchlist

---

Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

-----
Follow up to #13453. The default values for our other environment
variables are typically wrapped in backticks, so let's do the same here
for consistency.
Closes #13455.

env_config: clean up default text for `HOMEBREW_LIVECHECK_WATCHLIST`

---

.github/workflows/triage.yml

This PR switches the token used in the triage workflow to a newly generated one with `public_repo` and `read:org` scopes (the old one had only `public_repo`). This will allow the workflow to recognize those who have set their membership to private as Homebrew members.
See https://github.com/Homebrew/brew/pull/13454#issuecomment-1162524571

workflows/triage: use PAT with read:org to indentify private members

---

Library/Homebrew/cask/dsl.rb

-----
The `Cask::DSL#discontinued?` method is expected to return a boolean value (`true`/`false`) but it will return `nil` for any casks without a `caveats` block. `nil` is still falsy but this PR ensures that the method will properly return a boolean value in this scenario.

Cask: Ensure `#discontinued?` returns a boolean

---

Library/Homebrew/cask/cask.rb
Library/Homebrew/cask/dsl.rb
Library/Homebrew/livecheck/livecheck.rb
Library/Homebrew/livecheck/strategy/extract_plist.rb
Library/Homebrew/unversioned_cask_checker.rb

-----
This allows a custom url to be passed to livecheck when using the `:extract_plist` strategy. 
This is useful in edge cases that meet a couple of criteria:
- There is no version information available utilising the other livecheck methods
- There is an unversioned download link that points to the latest version
- There is a versioned download link available that we can use for download
At the moment in these cases we are limited to using the unversioned url OR using the versioned url and skipping the livecheck.
An example of a cask that is currently not functioning as intended is the [`speedify` cask](https://github.com/Homebrew/homebrew-cask/blob/43eadfc/Casks/speedify.rb).

livecheck: allow custom url in extract_plist strategy

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
As mentioned in #13471, the existing `bump-formula-pr` regexes expect a `url` string to only be followed by a newline. However, `url` also accepts a `specs` hash, which can appear after the `url` string. For example:
```ruby
url "https://www.example.com/1.2.3.tar.gz", using: :homebrew_curl
```
This commit modifies the regexes to capture anything after the `url` string and before the newline. This works for the aforementioned example, where the trailing hash is on the same line, but it won't work if the hash appears on a subsequent line. For example:
```ruby
url "https://www.example.com/1.2.3.tar.gz",
using: :homebrew_curl
```
I spent some time trying to create a regex that would also work for the latter case but didn't meet with success (my brain is a bit too tired tonight). Since …

bump-formula-pr: handle url with specs hash

---

Library/Homebrew/cmd/update-report.rb

This handles this being unset when using `brew update --quiet`.
CC @dkav @apainintheneck let me know if this is what you expected to be changed.
Fixes #13467

update-report: always write non-blank lattesttag.

---

Library/Homebrew/formula_cellar_checks.rb
Library/Homebrew/utils/ast.rb

-----
move the check whether the formula includes `ENV.runtime_cpu_detection` to `utils/ast`.

move check ENV.runtime_cpu_detection to `utils/ast`

---

Library/Homebrew/brew.sh
Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

From write-up in https://github.com/Homebrew/brew/pull/13469 this isn't working as needed for the relevant user.
Reverts https://github.com/Homebrew/brew/pull/13466 and https://github.com/Homebrew/brew/pull/13447

Remove HOMEBREW_FORCE_BREWED_SSH

---

Library/Homebrew/cask/cask_loader.rb
Library/Homebrew/cask/caskroom.rb
Library/Homebrew/cask/exceptions.rb

~This PR uses the new `/api/cask-source.json` endpoint to make loading casks using the API must faster. This is super noticeable in `brew outdated` when you have casks installed. Now, there's only one file to download that only needs to update whenever there's a new version available.~
~This PR depends on https://github.com/Homebrew/formulae.brew.sh/pull/654~
Cleanup `Cask::Caskroom::casks` so that it defaults to using a plain `Cask::CaskLoader::load` call. This will more reliably load the most up-to-date version of the cask without needing an extra `if Homebrew::EnvConfig.install_from_api?` call. `::load` uses nearly the same order to check for available casks to load:
1. Check API (if `HOMEBREW_INSTALL_FROM_API` is set)
2. Check `homebrew/cask`
3. Check other taps
4. Load from the …

Cleanup `Cask::Caskroom::casks`

---

Library/Homebrew/cask/dsl.rb
Library/Homebrew/extend/on_system.rb
Library/Homebrew/formula.rb
Library/Homebrew/resource.rb
Library/Homebrew/software_spec.rb

This PR is a follow-up to https://github.com/Homebrew/brew/pull/13451 which used several `include OnSystem` calls in various places around Homebrew. However, these call included all `on_{system}` methods, even when the `on_macos` and `on_linux` methods weren't needed (i.e. for casks). This PR creates two sub-modules of `OnSystem` called `WithOnLinuxMethod` and `WithoutOnLinuxMethod`. These are the modules that can be imported, and depending on which one is imported, the `on_{macos,linux}` methods will or won't be defined.
Currently, an error is thrown if you try to `include OnSystem`, forcing you to choose one of the following:
```ruby
include OnSystem::WithOnLinuxMethod
include OnSystem::WithoutOnLinuxMethod
```
However, another option is to not error if no sub-module is specified and …

`OnSystem`: provide `::MacOSAndLinux` and `::MacOSOnly`

---

Library/Homebrew/ast_constants.rb
Library/Homebrew/rubocops/components_order.rb
Library/Homebrew/test/rubocops/components_order_spec.rb
manpages/brew.1

This changes the components order cop to properly check `on_intel`, `on_arm` and `on_{macos_version}` blocks in addition to `on_macos` and `on_linux`. This PR has been broken off of https://github.com/Homebrew/brew/pull/13493 because some changes are needed before we can start migrating homebrew/core to use the new `on_{system}` blocks.

Update `components_order` cop to check other `on_{system}` methods

---

Library/Homebrew/cmd/update.sh

The fetching of repositories is done in a parallel fashion. We however pipe all failures into a single file which each parellel fetch routine will read, write and even delete. This leads to race conditions, so let's make this failure file per-repository instead.
Fixes errors like `cat: /opt/homebrew/.git/TMP_FETCH_FAILURES: No such file or directory` seen in #13504. This issue _does not_ cause any fetch to fail - it only causes the errors reported by `git` to not be displayed so you still have an underlying issue to address if you are hitting this.

cmd/update.sh: fix race condition reporting fetch failures

---

Library/Homebrew/extend/on_system.rb

This PR fixes a bug that I found when investigating Linux dependencies for some formulae. It turns out that evaluating an `on_{macos_version}` block while on Linux will throw an error because `MacOS.version` is `nil`. Instead, we need to just `return false` early if we're currently on Linux (simulating or not) and we've reached a macOS version check.

Fix `on_{macos_version}` blocks on Linux

---

Library/Homebrew/cask/cmd/upgrade.rb

-----
This is a fresh take on #13312
Outputs have been added for when a specific cask is requested to be upgraded via its token and the upgrade will not proceed because - 
1. the shasum of the downloaded artifact matches the currently installed package, or
2. the currently installed version is already the latest version

cask: add statements when direct cask upgrades won't be installed

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
Encountered an [issue](https://github.com/Homebrew/homebrew-core/pull/105086#issuecomment-1174043240) where using `bump-formula-pr` on [openrct2 0.4.0](https://github.com/Homebrew/homebrew-core/blob/2ff6bee848109af7558dd55f8fc96007e2373cc8/Formula/openrct2.rb) also modified the URL for its "title-sequences" resource, which happened to contain the text of the formula's tag. This modifies the search regex to check for a double quote after the tag, which solves for this particular case.

bump-formula-pr: more precise tag/version replacement

---

Library/Homebrew/cmd/update-report.rb

-----
Eight minor updates to update-report:
- Update x_repository_version variable names to x_tag to eliminate unnecessary variables and for consistency
- Resolve `latesttag` not being updated if message section is skipped. This is an update on pull request #13470 and reverts part of 92a4238
-  Expand output excluded by quiet
- Adds a feature to highlight release notes for versions changes other than x.x.0
- Print version number in messages
- Report new_tag even when old_tag blank
- Highlight new revision message
- Add new line after donate message

update-report: various updates

---

Library/Homebrew/keg.rb

-----
Some formulae (e.g. `luv`) have a `lib/lua/5.1` subdirectory inside
their keg. Before this change, the `5.1` subdirectory is symlinked into
`HOMEBREW_PREFIX`.
This can result in `luarocks` installing things into a formula's keg,
which we don't want.
Let's fix that by making sure that `brew link` creates these
subdirectories instead of symlinking them. We already do this for
subdirectories of `share/lua`:
https://github.com/Homebrew/brew/blob/8dd96ae8bacb4f7eb3ef476af63470e3702aee35/Library/Homebrew/keg.rb#L430

keg: create subdirectories of `lib/lua` instead of symlinks

---

Library/Homebrew/test/cask/cmd/list_spec.rb

-----
The lazy evaluation in `let()` was failing to reset `MacOS#full_version` to the original_macos_version. This meant that all tests that were run after this one automatically had `MacOS#version` monterey which caused some of the tests to fail if you were running a different macOS version.
This might not be noticeable on macOS monterey because that is the default version it will get set to accidentally. I came across this on my old iMac which is running catalina. To give an example of a failing test case `brew tests --seed=52182` was failing before but all tests pass now.
@Bo98 Thanks for helping me debug this.

cask/cmd/list_spec.rb: fix leaky version variable

---

Library/Homebrew/resource.rb

-----
`#stage` takes an optional `target` argument, which specifies the
location in which to unpack the `resource`.
Passing relative paths to `#stage`, as in
```ruby
resource("foo").stage "bar"
```
does not work, because this calls `Pathname("bar").install` inside the
temporary directory that the contents of the resource are unpacked to.
This means that passing a relative path to `#stage` has the unintended
effect of moving files around inside a temporary directory the formula
has no access to.
Let's fix that by keeping track of the original working directory before
`#stage` was called and prepending this to `target` whenever `target` is
a relative path.

resource: support relative paths as `targets` of `#stage`

---

Library/Homebrew/language/python.rb

-----
About 25 formula in homebrew/core pass `--install-lib` to `python3` in
addition to `*setup_install_args` in order to ensure that all files are
installed into the formula's prefix rather than into a `site-packages`
directory in Python's keg.
Let's simplify these formulae by also adding the appropriate
`--install-lib` flag to `setup_install_args`.

language/python: add `--install-lib` to `setup_install_args`

---

Library/Homebrew/test/utils/ruby_check_version_script_spec.rb
Library/Homebrew/utils/ruby_check_version_script.rb

Don't use ActiveSupport methods and add a test to make sure this doesn't regress.
Fixes #13559

utils/ruby_check_version_script: fix and test.

---

Library/Homebrew/dev-cmd/update-test.rb

When testing a commit not on `master` and `master` has since been updated since the branching, then `brew update` will perform a rebase of those commits onto the latest master since a fast-forward is not possible.
This behaviour is correct but the end commit cannot be predicted by `brew update-test`. The hash of the commits after a rebase will change, so the test will always fail when it's trying to look for the original commit hash under this scenario.
Since the commit hash is not known ahead of time in a rebase scenario, the fix here is to simply avoid testing scenarios where a rebase will be required. That means not testing an update from the HEAD of `origin/master` but instead from the `git merge-base` of the current HEAD and the HEAD of `origin/master`.
This does mean losing some …

dev-cmd/update-test: test against merge-base rather than latest master

---

Library/Homebrew/rubocops/uses_from_macos.rb

-----
This would be nice to have for the `circumflex` formula so that `depends_on "less" if MacOS.version <= :big_sur` could be replaced with `uses_from_macos "less", since: :monterey` (https://github.com/Homebrew/homebrew-core/pull/105577)
In addition, the `modules` formula could use this too to replace `on_linux { depends_on "less" }`

rubocops: allow uses_from_macos "less"

---

Library/Homebrew/linkage_checker.rb

-----
Currently, `brew linkage` reports linkage with system frameworks only if
they can be found on the file system. This results in this linkage not
being reported on Big Sur and newer, where system libraries are stored
in the dyld cache instead.
Let's fix that by avoiding silently ignoring system frameworks by moving
them out of `#harmless_broken_link?`. We retain the behaviour desired
from 7228e60da51392b20d55e0c087b2082b86fb3bbf by deferring checking if a
broken library is actually a system framework to just before we add it
to `@broken_dylibs`.
To see how this changes the behaviour of `brew linkage`, here's an
example with this change:
❯ brew linkage neovim
System libraries:
/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
/usr/lib/libSystem.B.dylib …

linkage_checker: report linkage with system frameworks

---

Library/Homebrew/service.rb
Library/Homebrew/test/service_spec.rb

-----
This is the second part of a two-part contribution, with the [first one being here](https://github.com/Homebrew/homebrew-services/pull/485). All the important info can be found there too. =] The existing automated tests should already cover the changes, although I did have to update the `expect()` stuff.

Added support for running services fully backgrounded on macOS

---

Library/Homebrew/formulary.rb

-----
This solves a recurrent issue where various brew commands (e.g. doctor, cleanup) would print the following stack trace:
Error: uninitialized constant Formulary::DeprecateDisable
Did you mean?  DeprecatedOption
/opt/homebrew/Library/Homebrew/formulary.rb:269:in `convert_to_deprecate_disable_reason_string_or_symbol'
/opt/homebrew/Library/Homebrew/formulary.rb:171:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:139:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:139:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:139:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:519:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:510:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:296:in `get_formula' …

Require deprecate_disable module in formulary

---

Library/Homebrew/software_spec.rb
Library/Homebrew/test/software_spec_spec.rb

In order to make formulae with `on_{system}` blocks easier to read, we'd like to keep patches and resources where they're supposed to go (i.e. below dependencies) even if they are only present on some system configurations. However, since only one of each `on_{system}` block is allowed, we need to next the `on_{system}` block within the `patch` or `resource` block as is done in this example:
```ruby
patch do
on_high_sierra :or_newer do
url "https://raw.githubusercontent.com/Homebrew/formula-patches/eed63e836e/alure/unistd.patch"
sha256 "7852a7a365f518b12a1afd763a6a80ece88ac7aeea3c9023aa6c1fe46ac5a1ae"
end
end
```
When the condition isn't met (in this example when `MacOS.version < :high_sierra`), this is the same as an empty `patch do; end` block which is not currently allowed. This PR …

Ignore empty `patch` blocks

---

Library/Homebrew/extend/os/linux/extend/ENV/super.rb
Library/Homebrew/shims/super/cc

This PR should fix most of the issues we were hitting in https://github.com/Homebrew/homebrew-portable-ruby/pull/156.  The root of the problem is that we can't mix headers from the system `glibc` with `glibc@2.13` and the only way to guarantee this is to use `-nostdinc` and add the paths to the GCC headers with `-isystem` flags.

Add flags to superenv when building with glibc@2.13

---

docs/Cask-Cookbook.md

Removing an outdated reference to Travis bot from Cask Cookbook.
-----

Remove reference to Travis bot

---

Library/Homebrew/api/formula.rb

-----
This is to fix #13583 by using `--time-cond "<date>"` instead of `--header "If-Modified-Since: <date>"` when refreshing the cached Formula API. This prevents older versions of `curl` (such as the Apple-supplied `curl` in macOS Big Sur) from writing a zero-byte .json file. My change will also skip the mtime comparison and overwrite the cache file if the cache file is empty, in order to automatically fix this issue on affected systems.

use --time-cond when caching the formula api json

---

Library/Homebrew/Gemfile
Library/Homebrew/Gemfile.lock

This might stop Dependabot from bumping dependencies that don't work with Ruby 2.6, a list which will only grow - it's a lot more than just ActiveSupport now.

Gemfile: denote minimum Ruby

---

Library/Homebrew/brew.rb

This came up in https://github.com/Homebrew/homebrew-bundle/issues/1108 wherein a user had unwittingly untapped some official taps that get automatically tapped on first use and couldn't figure out why they couldn't use the associated command.
⚠️ I'm not really sure how best to test this. I think I could add something [here](https://github.com/Homebrew/brew/blob/ee93d7e08dbdc52d932572007bee0f5fb1d75cbe/Library/Homebrew/test/cmd/bundle_spec.rb#L4) that runs an empty check, then untaps the homebrew/bundle tap, then checks for an error when it runs the empty check again.

Instruct user to tap untapped official tap when running its commands

---

Library/Homebrew/formula.rb

Since `ignore_missing_libraries` raises and error when called on macOS, generating the variations hash for formulae that use this inside an `on_linux` block fails. This PR adds a condition so that if `Homebrew::SimulateSystem.os` is set to `:linux` (i.e. we're currently simulating Linux for the purposes of the variations hash), we just return instead of failing.

Allow `ignore_missing_libraries` when simulating Linux on macOS

---

docs/FAQ.md

FAQ: Remove reference to `--enable-bar` that does not exist

---

Library/Homebrew/ast_constants.rb
Library/Homebrew/rubocops/components_order.rb
Library/Homebrew/test/rubocops/components_order_spec.rb

This PR is a follow-up to https://github.com/Homebrew/brew/pull/13529 that adds `on_system` to the component order list and also modifies the order of the various `on_{system}` components.
For now, I went with the following order:
- `on_macos`
- `on_ventura`
- `on_monterey`
- ...
- `on_el_capitan`
- `on_system :linux, macos:`
- `on_linux`
- `on_arm`
- `on_intel`
My thinking is that we should keep all OS-related blocks together and move from macOS to Linux. This keeps all of the macOS-only blocks together and has the combo `on_system` blocks in the middle. Then, the two arch-related blocks are together and move from ARM to Intel.
---
This works great for dependencies, but looks a little weird in cases such as [`alure`](https://github.com/Homebrew/homebrew-core/blob/736dbebd122d756cfcbcf415c …

Add `on_system` to and reorder component order cop

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
If in a formula `tag` matches `version`, then bump-formula-pr with `--version` argument fails:
```
% brew bump-formula-pr --version 2022-07-22  --debug exploitdb              
...
==> replace /2022-07-12(?=")/ with "2022-07-22"
==> replace "d84f857e94f91c71fcb93041483f661d29023c1e" with "46346f8944f5d01e09a8ed3d78e34cf759697b47"
==> replace "version \"2022-07-12\"" with "version \"2022-07-22\""
Error: inreplace failed
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/exploitdb.rb:
expected replacement of "version \"2022-07-12\"" with "version \"2022-07-22\""
/opt/homebrew/Library/Homebrew/utils/inreplace.rb:89:in `inreplace_pairs'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:311:in `bump_formula_pr'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
``` …

bump-formula-pr: even more precise tag replacement

---

Library/Homebrew/cmd/update.sh
Library/Homebrew/download_strategy.rb
Library/Homebrew/utils/github/api.rb

-----
This PR cleans up GitHub headers:
- Replaces `Accept: application/vnd.github.v3` header with `Accept: application/vnd.github` [ref ](https://docs.github.com/en/rest/overview/media-types)
> Note: In the past, we recommended including v3 in your Accept header. This is no longer required and will have no impact on your API requests.
- Removes `Accept: application/vnd.github.antiope-preview+json` header [ref](https://developer.github.com/changes/2020-10-01-graduate-antiope-preview/)
> The antiope preview is now an official part of the API. These preview headers are no longer required. The Checks API endpoints no longer require the antiope preview header.

Clean up GitHub headers

---

Library/Homebrew/formulary.rb
Library/Homebrew/test/formulary_spec.rb

This PR modifies `Formulary` to include the data in the variations hash when loading a formula from the API. This means that we now load formulae with the correct dependencies, etc on all platforms, not just the one that generated the JSON output.
Also, in this PR, I fixed an issue where dependencies could be duplicated. If a formula called `uses_from_macos "ruby"`, `ruby` would be listed in both the `uses_from_macos` and `dependencies` section of the formula's JSON info (on Linux). This means that it's added as a dependency twice. Now, we all names in `dependencies` and `*_dependencies` before adding and, if they dep is listed under `uses_from_macos`, we let the `uses_from_macos` method determine whether to add it as a dep or not.

Use `variations` hash when installing from the API

---

Library/Homebrew/cmd/update.sh

-----
Git's fsmonitor daemon will prevent our update lock file from being
released if it is running before a `brew update`.
Let's fix that by stopping it whenever necessary so our update lock is
released upon completion.
Fixes #13521.

cmd/update: stop Git's fsmonitor when needed

---

Library/Homebrew/formula_auditor.rb

- Permit glibc 2.27, 2.31, or 2.35
- https://github.com/Homebrew/brew/issues/13619
- `The glibc version must be 2.35` should have read `The glibc version must be 2.23`.
-----
-----
> The glibc version must be 2.23, as this is the version used by our CI on Linux. Glibc is for users who have a system Glibc with a lower version, which allows them to use our Linux bottles, which were compiled against system Glibc on CI.

audit_glibc: Permit glibc 2.27, 2.31, or 2.35 and fix the error message

---

Library/Homebrew/formula_auditor.rb

-----
Closes #12748.
This will probably require a bunch of changes in Homebrew/core.

formula_auditor: audit for deprecated dependencies

---

Library/Homebrew/dependency_collector.rb
Library/Homebrew/download_strategy.rb

-----
Bazaar is no longer maintained, and Breezy seems to be a drop-in
replacement.
I've tested the commands used in the download strategy and they seem to
work.
We need this in order to properly deprecate the `bazaar` formula.
See Homebrew/homebrew-core#106848.

download_strategy: replace `bazaar` with `breezy`

---

Library/Homebrew/extend/os/linux/keg_relocate.rb

-----
This should help keep bottles that require GCC working when
Homebrew/homebrew-core#106755 is merged.
This only works on freshly-poured bottles. Previously installed bottles
will still break on systems with a host GCC older than GCC 11.
-----
I've marked this as draft since this isn't ready to merge yet. For one thing, this line probably needs explanation in a comment. But I've opened this to suggest a potential way to minimise the pain of breaking all these Linux bottles for the GCC 12 migration.
As noted above, this fix only applies for bottles poured after `brew` includes this change. If desired, we could add a check to `brew doctor` that recommends a `brew install foo` if `foo` would benefit from having their `RPATH` fixed up by this change.

keg_relocate (linux): prepend `gcc/lib/current` to `RPATH` when needed

---

Library/Homebrew/dev-cmd/pr-pull.rb
Library/Homebrew/utils/github.rb

This change will prevent us having to run some long running builds
multiple times and to rely on luck to get things merged without conflicts.
The check takes less than 30 seconds on my local setup.
-----

pr-pull: check for conflicts with long running builds

---

Library/Homebrew/dev-cmd/pr-pull.rb

-----
Error: tried to create Proc object without a block
Do not report this issue until you've run `brew update` and tried again.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:372:in `proc'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:372:in `pr_check_conflicts'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:439:in `block in pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:429:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:429:in `pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Process completed with exit code 1.
https://github.com/Homebrew/homebrew-core/runs/7634004090?check_suite_focus=true#step:10:15

pr-pull: fix typo

---

Library/Homebrew/official_taps.rb

-----
- This is needed for https://github.com/Homebrew/brew/pull/13603 because `Homebrew/homebrew-versions` is deprecated (legitimately), but `OFFICIAL_CASK_TAPS` spits out `versions` as a repo, which could then be interpreted as `Homebrew/versions` rather than `Homebrew/cask-versions` which it actually is.

official_taps: Refer to `Homebrew/homebrew-cask-versions` properly

---

Library/Homebrew/rubocops/components_order.rb
Library/Homebrew/rubocops/dependency_order.rb
Library/Homebrew/rubocops/extend/formula.rb
Library/Homebrew/test/rubocops/dependency_order_spec.rb

https://github.com/Homebrew/homebrew-core/pull/107194
-----
`brew audit` should check `depends_on` order in `on_linux` and co.
`homebrew/core/hurl` has:
```rb
on_linux do
depends_on "openssl@1.1"
depends_on "pkg-config" => :build
end
```
but it should be:
```rb
on_linux do
depends_on "pkg-config" => :build
depends_on "openssl@1.1"
end
```

Check dependency order in on_system methods

---

Library/Homebrew/official_taps.rb

-----
- These weren't in `OFFICIAL_CASK_TAPS` but they probably should be given they're active repos in the Homebrew org.
- Related conversation: https://github.com/Homebrew/brew/pull/13603#discussion_r936895145.

official_taps: Add `cask-fonts`, `cask-drivers` taps

---

Library/Homebrew/cmd/update-report.rb

-----
When GCC 12 ships (Homebrew/homebrew-core#106755) ships, most (all?)
Linux bottles that depend on GCC will break.
Let's fix that by using the same trick for handling divergent formula
revisions when migrating formulae from linuxbrew-core (#11982). We set
the recorded `version_scheme` to -1, which spoofs the formula being
outdated. When `brew upgrade` installs GCC 12, the broken formulae will
have their bottles reinstalled too.
This works because the reinstallation will also rewrite the existing
RPATHs to point to the new version of GCC instead (#13631). This should
handle most of the breakage.

update-report: migrate GCC recursive dependents

---

Library/Homebrew/cli/args.rbi
Library/Homebrew/dev-cmd/contributions.rb
Library/Homebrew/test/dev-cmd/contributions_spec.rb

-----
- Before each AGM it's currently a manual process for a PLC member to search commit logs and GitHub to figure out who contributed to Homebrew, so who should remain a member.
- I noticed that [looking at commits for a user](https://github.com/Homebrew/homebrew-core/commits?author=issyl0&since=2022-01-01&until=2023-01-01) would not count `Co-Authored-By`, which happens a lot now there's an autosquash action on PRs in `Homebrew/homebrew-core`, say if someone fixed a formula's build or tests or whatever and then the PR got auto-merged.
- Here's `brew contributions` that uses `git log` to be able to go back through all time or a specific time period (`--from`, `--to`). It's up to individual PLC discretion for "activity", but it does at least go some way to automating the data retrieval. …

dev-cmd/contributions: Retrieve a user's repo contributions over time

---

Library/Homebrew/utils/ruby.sh

Currently, Portable Ruby just gets installed everytime and overrides the choice.

utils/ruby.sh: fix `HOMEBREW_USE_RUBY_FROM_PATH` on non-latest macOS

---

Library/Homebrew/dev-cmd/pr-pull.rb

The previous refactorings broke the conflict check.
Go back to the initially proposed syntax to fill the hashes/arrays,
which is more readable, and which works (the proc syntax does not seem to work for our purpose here)
Remove space before the error message, else only the first line of the output has 2 spaces
and this looks weird
-----

pr-pull: fix check conflicts

---

docs/Formula-Cookbook.md
manpages/brew.1

Now that we require the use of `on_{system}` blocks in homebrew/core, we should document them. This PR adds a section to the formula cookbook with information on how to use the `on_{system}` blocks and also how to use `if` statements to check the same conditions inside `def install` and `test do`

Add `on_{system}` methods to formula cookbook

---

Library/Homebrew/default_prefix.rb
Library/Homebrew/extend/on_system.rb
Library/Homebrew/extend/os/linux/keg_relocate.rb
Library/Homebrew/formula_auditor.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/resource_auditor.rb
Library/Homebrew/simulate_system.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/simulate_system_spec.rb
Library/Homebrew/test/software_spec_spec.rb

Follow-up to https://github.com/Homebrew/brew/pull/13599
This PR moves the handling of `HOMEBREW_SIMULATE_MACOS_ON_LINUX` into `SimulateSystem`. Since the env var is accomplishing the same thing as simulating using the `SimulateSystem` methods, it makes sense to handle it in the same place instead of needing to have separate conditionals for the two possible ways of simulating. When `HOMEBREW_SIMULATE_MACOS_ON_LINUX` is set, we assume that we're simulating a generic macOS version, so `Homebrew::SimulateSystem.os` returns `:macos`. I've also set it up so that simulations set up using `SimulateSystem` methods take precedence over the environment variable, but `Homebrew::SimulateSystem.clear` will not clear the simulation since the env var is still set.
In this PR, if the env var is set …

Move `HOMEBREW_SIMULATE_MACOS_ON_LINUX` handling to `SimulateSystem`

---

Library/Homebrew/extend/os/linux/keg_relocate.rb

-----
I don't think this is needed anymore. We probably needed this when we
used `patchelf` to do `RPATH` rewriting, but this is no longer the case.

linux/keg_relocate: remove patchelf exemption

---

Library/Homebrew/cmd/update-report.rb

-----
`recursive_dependencies` includes build and test dependencies as well,
which means that we're doing this for too many formulae.

update-report: reset `version_scheme` only for runtime dependents

---

docs/Acceptable-Formulae.md
docs/Linux-CI.md

docs: document CI versions of Ubuntu

---

Library/Homebrew/formula.rb
Library/Homebrew/test/formula_spec.rb
Library/Homebrew/utils/inreplace.rb

-----
WIP to ensure not only build command failures tell users of `--HEAD` to make a pull request

brew.rb: tell users to fix head issues with inreplace

---

Library/Homebrew/cmd/search.rb

-----
`brew search` doesn't include package descriptions in the output, so even when a package matches, it is hard to tell if it does what is needed. In the proposal to add package descriptions into `search -v` output https://github.com/Homebrew/brew/issues/11932 I've discovered that there is a separate `brew desc` search command that does exactly this. So per discussion https://github.com/Homebrew/brew/issues/11932#issuecomment-909189260 this is the PR that adds hint to use `brew desc` if `search` is supplied with `--verbose`.
(hit this problem again today and forgot about `desc` already)

`brew search --verbose` to tell about `brew desc`

---

Library/Homebrew/rubocops/cask/constants/stanza.rb
Library/Homebrew/test/support/fixtures/cask/Casks/arch-arm-only.rb
Library/Homebrew/test/support/fixtures/cask/Casks/invalid/invalid-two-arch.rb
Library/Homebrew/test/support/fixtures/cask/Casks/multiple-versions.rb

This PR temporarily removes the rule that the `arch` stanza must immediately follow the `sha256` stanza. We haven't decided yet where the best place for this to go is, so let's not require anything specific for now to give us more flexibility. I'm working on a rubocop PR that will re-add this (among other related changes), so this is just temporary while we start to add `arch` stanzas and figure out the preferred styling.

Remove `arch` from cask stanza ordering temporarily

---

Library/Homebrew/extend/on_system.rb

This PR fixes a bug I found in the `arch` and `on_arch_conditional` DSLs. Passing `nil` or leaving an arg blank is allowed in the `arch` method, but was mistakenly not allowed in the `on_arch_conditional` method. This causes a problem in a small number of casks (e.g. `studio-3t`) that call `on_arch_conditional` with only one of the arches.

Fix `nil` handling in `arch` cask DSL

---

Library/Homebrew/extend/os/linux/extend/ENV/super.rb
Library/Homebrew/extend/os/linux/linkage_checker.rb

-----
This adds GCC's runtime lib directory to the RPATH of every build on
Linux (unconditionally!).
This is useful for three things:
1. It fixes versioned GCC linkage for formulae that users build from
source instead of pouring from a bottle. We currently only handle
bottle installs. See #13633.
2. It helps minimise the GCC dependency explosion. When a formula has a
Linux-only GCC dependency, then all its dependents that link with
some GCC runtime library (typically `libstdc++`) must, before this
change, also adopt a GCC dependency. This is a consequence of our
injecting GCC's runtime library directory into RPATH only when a
formula is built with GCC (this is done through the specs file). We
can avoid the need to do this by always injecting this path instead.
3. This enables us to …

linux/super: add unversioned GCC lib directory to RPATH

---

Library/Homebrew/dev-cmd/rubocop.sh

It's not reliable enough to just check for the binary.

dev-cmd/rubocop: use bundle check.

---

bin/brew

Further support for brew services; `systemctl --user` falls back to
XDG_RUNTIME_DIR if no DBUS daemon is available, so make it available in the brew environment.
This will help resolve Homebrew/homebrew-services#496.

brew: add XDG_RUNTIME_DIR copy

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb

Fixes https://github.com/Homebrew/brew/issues/13687
The current logic for replacing the `sha256` stanza for other arches is to do a text replace of `Hardware::CPU.intel?` to `true` or `false` in the cask. However, this doesn't work for casks that use the `arch` DSL since they don't call this method. Instead, we want to use `SimulateSystem` to simulate being on the other arch. However, we can't fully switch to this yet because we're only about halfway through the migration at the moment and casks currently use _both_ `arch` and `if Hardware::CPU.intel?`. So, for now, we should stick to the existing method but _also_ set `SimulateSystem.arch` in order to get the best of both worlds. Once we are done with the migration, we can remove the non-`SimulateSystem` method.

`bump-cask-pr`: fix `sha256` replacement with `arch`

---

Library/Homebrew/mktemp.rb

Fixes `--debug-symbols`. An incorrectly named variable means existing directory is never removed
so new directory can't be copied in. This occurred during a refactoring of the `--debug-symbols` code (very unfortunately).
@MikeMcQuaid sorry I missed this bug.
-----

fix debug-symbols

---

Library/Homebrew/extend/ENV/super.rb
Library/Homebrew/extend/os/linux/extend/ENV/super.rb

-----
When Homebrew/homebrew-core#107517 is merged, builds will no longer be
able to find `python@3.9` as `python3`. This is also what is likely to
happen to `python@3.10` when we add a `python@3.11`.
This is likely to break many builds, so let's make sure they can keep
finding a `python3` for formulae that don't have a dependency on the
latest Python3.
This is arguably something we should've done earlier: it also means that
builds that go looking for an unversioned `python` end up finding our
Python3 (whenever present in the build environment) instead of, say,
`/usr/bin/python` which is typically Python2.

ENV/super: add Python's `libexec/"bin"` directory when applicable

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/cask/auditor.rb
Library/Homebrew/cask/cmd/audit.rb
Library/Homebrew/test/cask/audit_spec.rb

-----
Since often upstreams suggest people disable quarantine instead of fixing their broken signatures, we should probably check if the signature is valid in the audit.

cask: add audit for incorrect signing

---

Library/Homebrew/dev-cmd/test.rb

-----
Occasionally, a new version of Rust will cause failures in dependents.
See, for example, Homebrew/homebrew-core#107818.
This change will allow us to get a fuller backtrace in CI, which will
also make it easier to submit bug reports upstream.
Without this change, recovering a full backtrace requires installing the
new version of Rust and rebuilding the failing formula from source. Both
these steps can be skipped if we set `RUST_BACKTRACE` when retrying a
failing test.
I'm not sure if this is the right place to put this. However, it's much
nicer to only do this when retrying the test, so I've put it here.

dev-cmd/test: set `RUST_BACKTRACE` when retrying

---

Library/Homebrew/cmd/list.rb

-----
This is just a small change to make sure `brew ls` works when the cellar doesn't exist. This can happen after an install or if the user only has casks installed not formulae.
To test this change I renamed the cellar folder and then made sure all of the normal `brew ls` commands worked as expected.
```shell
~ ❯❯❯ brew ls
==> Casks
slack		virtualbox
~ ❯❯❯ brew ls --formula
~ ❯❯❯ brew ls --cask
slack		virtualbox
~ ❯❯❯ brew ls --full-name
slack                                    virtualbox
~ ❯❯❯ brew ls --versions
slack 4.27.154
virtualbox 6.1.36,152435
~ ❯❯❯ brew ls --versions --multiple
~ ❯❯❯ brew ls --pinned
~ ❯❯❯ brew ls sdlkfsdkfj
Error: No available formula with the name "sdlkfsdkfj".
~ ❯❯❯ brew ls fish                                                           ✘ 1
Error: No such …
```

Update `brew ls` to work when the cellar doesn't exist

---

Library/Homebrew/cask/audit.rb

-----
I really hope this is the last fix to the signing audit. All my tests were with app files so I didn't catch this.

Cask: fix signing audit using unexpected pkg method

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb

Fixes https://github.com/Homebrew/brew/issues/13713
This PR modifies `bump-cask-pr` to be able to handle all of the forms of `sha256` that we currently or are planning on supporting. This includes `sha256 :no_check`, `sha256 "..."`, `sha256` in `on_arm`/`on_intel`, and `sha256 arm: "...". intel: "..."`.
Before, we only tried to find the `sha256` of other arches when the text `if Hardware::CPU.intel?` was present. Now that we've removed that, we need to have a more reliable check. We now replace the `version`, switch to the opposite arch, reload the cask, and then compare the `url`. If the `urls` are different, this means the `sha256` will be different and we can handle that.
In the future, once all `if Hardware::CPU.intel?` calls are removed (plus some extra time for third party taps to …

Fix multi-arch cask `sha256` updates

---

Library/Homebrew/formula_auditor.rb
Library/Homebrew/tap_auditor.rb

-----
We have an audit that checks each formula's dependency tree for multiple
versions of the same software. We have an allowlist that allows us to
ignore this audit, but this allowlist requires each formula with a
conflict in its dependency tree to be listed there.
Here, I propose the reverse: if formula `foo` appears in the
`versioned_formula_dependent_conflicts_allowlist`, then all its
dependents will not fail the versioned dependencies conflict because of
a conflict with formula `foo`.
I'd like to do this in the case of `python`, where I think the versioned
dependencies conflict check hurts us more than helps us. Versioned
dependency conflicts are most problematic in the case of libraries with
the same install name but incompatible ABIs. This is almost never a
problem with Python: …

formula_auditor: create a versioned formula dependent conflict allowlist

---

Library/Homebrew/cleanup.rb

-----
`cleanup_path` already handles the dry-run logic, and also includes
those paths in the summary of space freed by `brew cleanup`.
Before this change:
❯ brew cleanup --dry-run
Would remove: /Users/carlocab/Library/Caches/Homebrew/bootsnap (2,401 files, 41.9MB)
After this change:
❯ brew cleanup --dry-run
Would remove: /Users/carlocab/Library/Caches/Homebrew/bootsnap (2,401 files, 41.9MB)
==> This operation would free approximately 41.9MB of disk space.

cleanup: use `cleanup_path` more consistently

---

Library/Homebrew/extend/os/linux/formula.rb
Library/Homebrew/formula.rb

-----
There are about 10 formulae which need a bit more flexibility from
`#rpath`. Most of them use `Pathname#relative_path_from`, so we can
replace those instances with a call to `#rpath` instead once `#rpath`
knows how to handle this.

formula: add optional `source` and `target` args to `#rpath`

---

Library/Homebrew/formula_auditor.rb

-----
I am removing `glib-utils` in (1) Homebrew/homebrew-core#108307, and all
`glib-utils` dependencies in (2) Homebrew/homebrew-core#108497.
This audit prevents me from proceeding with (1) without rebuilding all
the formulae modified in (2). I don't think that is needed, so I'd like
to exempt `glib-utils` from the rename audit instead.
To give you a clearer idea of how I plan to do this, this is the order
of events:
1. Merge this change.
2. Merge Homebrew/homebrew-core#108307.
3. Merge Homebrew/homebrew-core#108497.
4. Revert this change.
This should allow us to get rid of `glib-utils` and its accompanying
hacks without having to rebuild dozens of formulae needlessly.

formula_auditor: skip rename audit for `glib-utils`

---

Library/Homebrew/missing_formula.rb

PostgreSQL is being renamed to always be a versioned formula so handle when people type `brew install postgresql`.
Companion PR: https://github.com/Homebrew/homebrew-core/pull/107726

missing_formula: message for postgres rename.

---

Library/Homebrew/extend/os/linux/diagnostic.rb

-----
This complements my other two GCC-on-Linux PRs (#13631, #13633), however
they are both reliant on bottles eventually being (re-)poured.
Let's try to speed that up by returning an error message from `brew doctor`
whenever a user has formulae installed that would benefit from a `brew reinstall`.

linux/diagnostic: add check for versioned GCC linkage

---

Library/Homebrew/formula_auditor.rb

-----
As we've seen, allowing Linux-only dependencies on GCC results in its
dependency tree growing out of control to the point of being extremely
painful to maintain.
Let's stop this situation from getting worse by:
- failing a `--strict` audit when there is a Linux-only GCC dependency.
This also prevents new formulae from having such a dependency.
- failing any audit whenever a formula that did not previously have a
Linux-only GCC dependency picks one up
If a future formula update causes a formula to fail to build on Linux
because it needs a newer GCC when it previously did not, then we should
not bottle it. We can bottle this hypothetical formula when our bottling
distribution includes a new enough version of GCC.

formula_auditor: audit for Linux-only dependencies on GCC

---

Library/Homebrew/dev-cmd/linkage.rb
Library/Homebrew/extend/os/linux/linkage_checker.rb
Library/Homebrew/linkage_checker.rb

`brew linkage --test` checks more than just "unusably broken".
Things like unwanted system dependencies and unexpectedly present libraries are issues worth flagging, but they are typically formula code issues and not fixable by simply reinstalling. So triggering a reinstall for those issues is a waste of time.
This PR adds a test parameter to `LinkageChecker#broken_library_linkage?`, so that we can scope some checks to only `brew linkage --test` rather than every place which calls that method (like `upgrade.rb`).

linkage_checker: don't reinstall formula on some linkage failures

---

Library/Homebrew/extend/os/linux/linkage_checker.rb

This was due to be disabled in 3.6.0.
But we've now shipped glibc 2.35 so using libcrypt.so.1 is now a broken configuration. I'm opening this PR to discuss the possibility of disabling this earlier. Note that this is something which is shown to only users of `brew linkage` - i.e. it's for formula maintainers and not end users.
**Requires #13739**

linkage_checker: disable libcrypt.so.1 linkage

---

Library/Homebrew/extend/os/linux/linkage_checker.rb

This is a trickier one as we're far too late deprecating this (I did not know it was going to be removed from our Glibc formula) so really should be disabling this by now...
Interested in thoughts on what the deprecation schedule should look like here.

linkage_checker: deprecate libnsl.so.1 linkage

---

Library/Homebrew/formula_auditor.rb

The necessary PRs in Homebrew/homebrew-core have been merged. See:
- Homebrew/homebrew-core#108307
- Homebrew/homebrew-core#108497
This reverts commit 6ca02b22bb27a45525fa62c6fba9902039152fcc.

Revert "formula_auditor: skip rename audit for `glib-utils`"

---

Library/Homebrew/rubocops/cask/ast/cask_block.rb
Library/Homebrew/rubocops/cask/constants/stanza.rb
Library/Homebrew/rubocops/cask/extend/node.rb
Library/Homebrew/test/support/fixtures/cask/Casks/multiple-versions.rb

This PR updates the cask stanza grouping rubocop to treat `on_{system}` blocks as being part of their own group. This doesn't add them to the list of stanzas since I want their position to be variable, but it does mean that when they're right after each other, they'll be treated as a standalone group. I think it's important not to restrict their exact position since something they may contain only stanzas that belong toward the top of the cask file (e.g. `version`) and sometimes they may contain stanzas that belong farther down (e.g. `url` or artifacts) or both. I think that the blocks should have the flexibility to go where it makes most sense for them to be depending on what the contents are.
This PR is needed for https://github.com/Homebrew/homebrew-cask/pull/130261

Include `on_{system}` blocks as stanzas in rubocop

---

Library/Homebrew/rubocops/cask/on_system_conditionals.rb
Library/Homebrew/rubocops/cask/on_system_conditionals.rbi
Library/Homebrew/test/rubocops/cask/on_system_conditionals_spec.rb

This PR updates the cask rubocops to enforce two new style rules:
1. Use `on_intel` and `on_arm` instead of `if Hardware::CPU.intel?` or `if Hardware::CPU.arm?`
2. Use `sha256 arm: "...", intel: "..."` instead of on_arch blocks if the `sha256` stanza is the only one inside both on_arch blocks
This PR will need to wait for the taps to be updated which may take some time. Before the taps can be updated, we need to wait for https://github.com/Homebrew/brew/pull/13702 to be merged and tagged.

Update cask rubocops to use on_arch blocks and `sha256 arm:, intel:`

---

Library/Homebrew/dependency_collector.rb
Library/Homebrew/development_tools.rb
Library/Homebrew/extend/os/dependency_collector.rb
Library/Homebrew/extend/os/linux/dependency_collector.rb
Library/Homebrew/extend/os/linux/development_tools.rb
Library/Homebrew/extend/os/linux/formula.rb
Library/Homebrew/extend/os/linux/linkage_checker.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/os/linux/glibc.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/installed_dependents_spec.rb

Right now this is done through the gcc@5 formula.
See https://github.com/Homebrew/homebrew-core/blob/9692318ca653f58857fec12136381c9cec290aa9/Formula/gcc%405.rb#L33
This is fragile because when we will migrate to ~gcc@7~ `gcc@11`
we have to think about migrating this line.
Also, not having the right glibc version results in a non-functional brew
installation on an older Linux: the glibc installation needs
to be done by brew, and not by a workaround in a specific formula
-----
- https://github.com/Homebrew/brew/issues/13619

install glibc/gcc automatically if too old.

---

Library/Homebrew/formula_auditor.rb

-----
The GCC dependency check is adding a couple of minutes to our
`tap_syntax` jobs. Let's fix that by moving the check into a separate
method so we can exclude it from `tap_syntax`.

formula_auditor: refactor GCC dependency check into separate method

---

Library/Homebrew/extend/os/linux/dependency_collector.rb

linux/dependency_collector: bump maximum_tree_depth.

---

Library/Homebrew/extend/os/linux/diagnostic.rb
Library/Homebrew/os/linux/elf.rb

-----
Fixes #13762.
There's still a bug in the GCC linkage check, but I'll need a bit more
time to work on a fix. This at least makes sure `brew doctor` will not
return the error in the issue linked above.

linux/diagnostic: fix `rpath` returning `nil`.

---

Library/Homebrew/formula_auditor.rb

-----
The Git log is required only when `--strict` is not passed. This check
should still run with one of `--strict` or `--git`, but currently
passing `--strict` also requires `--git` in order to run this check.
This will still not be done during `tap_syntax` jobs after this change.

formula_auditor: require `--git` only if not `--strict` in `audit_gcc_dependency`

---

Library/Homebrew/cask/artifact/abstract_artifact.rb
Library/Homebrew/cask/artifact/abstract_flight_block.rb
Library/Homebrew/cask/artifact/abstract_uninstall.rb
Library/Homebrew/cask/artifact/installer.rb
Library/Homebrew/cask/artifact/pkg.rb
Library/Homebrew/cask/artifact/relocated.rb
Library/Homebrew/cask/artifact/stage_only.rb
Library/Homebrew/cask/cask.rb
Library/Homebrew/test/cask/cmd/list_spec.rb

In order to use the JSON API to load casks without having their files locally, we need to properly list the artifacts for each cask. Currently, the JSON data includes a poorly maintained list of artifacts, but the entries aren't labeled and aren't always complete (e.g. for `installer` artifacts). This PR updates the `artifacts` JSON object so that every artifact item includes a `type` key that corresponds to the DSL key that was used to declare that artifact, and an `args` key that corresponds to a list of arguments that were passed to the artifact method. This will allow us to reconstruct the cask using only the JSON data.
Like with `post_install` in formulae, the various `preflight` and `postflight` blocks will not really be included in this hash since we have to way of encoding the …

Include dsl key in cask artifact hash

---

Library/Homebrew/diagnostic.rb

Otherwise, this just dies with `Error: No available tap homebrew/core.`.

diagnostic: automatically tap homebrew/core.

---

Library/Homebrew/cmd/deps.rb

This makes more sense but will also be useful in `brew test-bot`.

cmd/deps: return failing exit code on circular dependencies.

---

Library/Homebrew/shims/gems/rubocop

Instead, figure out where `$HOMEBREW_PREFIX/bin` should be and use that.

shims/gems/rubocop: handle when `brew` isn't in PATH.

---

Library/Homebrew/extend/os/linux/dependency_collector.rb

Brewed GCC is required for `libgcc_s.so.1` if either the host Glibc or GCC is too old.
-----
- <https://github.com/Homebrew/brew/issues/13619>

gcc_dep_if_needed: Install GCC if Glibc is too old

---

Library/Homebrew/cleanup.rb
Library/Homebrew/test/cleanup_spec.rb

-----
Inside a given `site-packages` directory, `*.pyc` files live in
`__pycache__` directories. These are created by the Python interpreter
when a module is imported in order to speed up future access to the
imported module.
These can be left behind when formulae are uninstalled, which results in
erroneous success in importing the modules they were originally compiled
for.
Let's fix that by cleaning these up. In the top-level `__pycache__`
directory, we use the `Pathname#prune?` extension in order to determine
whether a `*.pyc` file is old enough to clean up. In other directories,
we clean them up when they are all that remains in a given module's
tree.
Removing these `*.pyc` files will make `python3` regenerate them when
required, so deleting them is relatively safe. The worst …

cleanup: handle Python `site-packages` directories

---

Library/Homebrew/extend/os/linux/install.rb

-----
As part of the migration we need to update the links in `HOMEBREW_PREFIX/lib` from pointing `gcc@5` to pointing to `gcc@11`.  In https://github.com/Homebrew/homebrew-core/pull/108816 the approach was to revision bump both `gcc@5` and `gcc@11` to swap which version has the symlinks.
Since all we are doing is moving around symlinks, it should not be necessary to recompile anything. Here I have added a method `symlink_gcc_libs` which will automatically adds the symlinks from the `opt_prefix` of whichever version of GCC is used in CI to `HOMEBREW_PREFIX/lib`.  This has several advantages:
1) Aside from a one-off revision bump to remove these symlinks in `gcc@5`, no revision bumping of `gcc` will ever be necessary again for future migrations.
2) These symlinks will not be removed if …

Automatically add symlinks from gcc cellar to HOMEBREW_PREFIX/lib

---

Library/Homebrew/utils.rb

[TextWrangler](https://www.barebones.com/support/textwrangler/updates.html) has long since been relegated to the 32-bit dustbin, and its `edit` command has been replaced with [`bbedit`](https://www.barebones.com/products/bbedit/benefitscommand.html).

utils: prefer BBEdit over TextWrangler

---

Library/Homebrew/cmd/deps.rb

It appears the requirement was originally imposed in #9414 because only the `--installed` logic checked for `--formula` or `--cask`. But with the addition of `named_args`, that check is done automatically. 
Fixes #13592.

cmd/deps: drop `--installed` requirement for `--formula`/`--cask`

---

Library/Homebrew/formula_auditor.rb

Also favour `.any?` over `.each / break` for a minor syntax improvement.

formula_auditor: use symbols for spec iteration

---

Library/Homebrew/build_environment.rb
Library/Homebrew/cask_dependent.rb
Library/Homebrew/dependencies.rb
Library/Homebrew/dependency_collector.rb
Library/Homebrew/extend/module.rb
Library/Homebrew/formula.rb
Library/Homebrew/options.rb
Library/Homebrew/requirement.rb
Library/Homebrew/resource.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/build_environment_spec.rb
Library/Homebrew/test/cleaner_spec.rb
Library/Homebrew/test/formula_spec.rb
Library/Homebrew/test/livecheck/livecheck_spec.rb
Library/Homebrew/test/requirement_spec.rb
Library/Homebrew/test/requirements_spec.rb
Library/Homebrew/test/resource_spec.rb
Library/Homebrew/test/service_spec.rb
Library/Homebrew/test/support/fixtures/failball.rb
Library/Homebrew/test/support/fixtures/testball.rb
Library/Homebrew/test/support/fixtures/testball_bottle.rb
Library/Homebrew/test/support/fixtures/testball_bottle_cellar.rb

This PR implements safety mechanisms to avoid hitting the unsupported behaviour of modifying a formula's definition (e.g. adding a dependency) after the first instance has been created. Note that you will still have the ability to do so if such changes are applied to only that particular instance of the formula (typically involving private API). Only changes to the global definition on the class-level is prevented, as those would have an undefined effect on existing instances.
Each commit can be separated into a separate PR, but the order matters as each commit depends on the previous one.
Details on each one, in reverse order:
* 22ccede2d8342f5fe9232f3e173bcfdae12c61bc - Freeze formula definition once first instance is created
- What this does is call `self.class.freeze` at the …

Freeze formula definition once first instance is created

---

Library/Homebrew/resource.rb
Library/Homebrew/software_spec.rb

Fixes https://github.com/Homebrew/homebrew-core/pull/109417
Previously the `version` variable was lazily set. Now it'll be set when either `url` or `version` is set.

resource: determine version before freezing

---

Library/Homebrew/formula.rb

-----
Followup to #13536 
Fixes the error seen in https://github.com/Homebrew/homebrew-core/pull/109486.
Some binaries apparently don't react well to an extra empty `''` appended to their invocation, so let's not pass that in the case of `shell_parameter_format: :none`.
(@Rylan12)

generate_completions: fix `shell_parameter_format: :none`

---

Library/Homebrew/dev-cmd/pr-pull.rb
Library/Homebrew/test/utils/github_spec.rb
Library/Homebrew/utils/github.rb

The search API has a rate limit of 30 per minute. This is far too small for something invoked on every merge in both Homebrew/core and Homebrew/cask.
Instead let's not use the search API at all and use the Issues REST API.
As a bonus: add a check to avoid an unnecessary `GitHub.get_pull_request_changed_files` REST API call when there is no long PRs to check.

dev-cmd/pr-pull: avoid expensive search API calls

---

Library/Homebrew/extend/os/linux/linkage_checker.rb

-----
This is causing warnings all over Homebrew/homebrew-core.
For example, there are dozens of warnings about this in the following CI
run: https://github.com/Homebrew/homebrew-core/runs/8116257943?check_suite_focus=true

linux/linkage_checker: remove `gcc` from `undeclared_deps`

---

Library/Homebrew/formula_auditor.rb

-----
This fixes #13772.
There is an audit for versioned formulae that makes sure an unversioned formula of the same name exists already. This ignores that check when we explicitly removed the unversioned formula by checking if it was renamed first.
Also, there is no need to check for `formula.tap` because `formula.core_formula?` guarantees the presence of `formula.tap`.

Ignore renamed formulae when checking for unversioned formulae

---

Library/Homebrew/cmd/fetch.rb

-----
See discussion at Homebrew/homebrew-test-bot#826.
Note: `--retry` does not currently work when fetching bottles. That was true before this change as well. It would be nice to fix that, but that's for another PR.

cmd/fetch: `--retry` with exponential backoff.

---

.github/workflows/codeql-analysis.yml
.github/workflows/docker.yml
.github/workflows/maintainers-man-completions.yml
.github/workflows/spdx.yml
.github/workflows/tests.yml
.github/workflows/triage-issues.yml
.github/workflows/triage.yml
Library/Homebrew/os.rb
Library/Homebrew/test/compiler_selector_spec.rb
Library/Homebrew/test/formula_installer_bottle_spec.rb
Library/Homebrew/test/formulary_spec.rb
Library/Homebrew/test/unpack_strategy/zstd_spec.rb

- Change `LINUX_CI_OS_VERSION` from `Ubuntu 16.04` to `Ubuntu 22.04`
- Change `LINUX_GLIBC_CI_VERSION` from `2.23` to `2.35`
- Change `LINUX_GCC_CI_VERSION` from `5.0` to `11.0`
- Change `LINUX_PREFERRED_GCC_FORMULA` from `gcc@5` to `gcc@11`
- Build the Docker image `ghcr.io/homebrew/ubuntu22.04:master`
-----
-----
- https://github.com/Homebrew/brew/issues/13619

Update LINUX_CI_OS_VERSION to Ubuntu 22.04

---

Library/Homebrew/rubocops/lines.rb
Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
Library/Homebrew/test/rubocops/lines/generate_completions_spec.rb
Library/Homebrew/test/rubocops/lines_spec.rb

-----
related to #13536 
needs https://github.com/Homebrew/homebrew-core/pull/105707
cc @Rylan12 
I have achieved to implement a preliminary RuboCop, but I will appreciate any feedback, since I'm sure there's room for improvement.
The Cop is able to correct
```
(bash_completion/"foo").write Utils.safe_popen_read(bin/"foo", "completions", "bash")
```
but I have been unable to come up with a solution to get and replace with all shells whilst only walking the AST once.
The Cop also warns for the 
```
output = Utils.safe_popen_read(bin/"foo", "completion", "bash")
(bash_completion/"foo").write output
```
pattern, but has no corrector, as discussed in #13536.
Please feel free to push any commits improving my implementation 😄

rubocop: generate_completions DSL

---

Library/Homebrew/brew.rb

See https://github.com/Homebrew/brew/issues/13794
This PR updates `brew.rb` so that users who have set `HOMEBREW_DEVELOPER` and `HOMEBREW_INSTALL_FROM_API` are allowed to run any developer command. This restriction was originally put in place to combat users trying to run commands that required homebrew/core to be installed without it installed (or with a super old version). However, now that `brew update` will keep homebrew/core up to date for developers, I think it's safe to remove for these people.

Allow developers to use dev commands and `HOMEBREW_INSTALL_FROM_API`

---

.github/workflows/tests.yml
Library/Homebrew/brew.sh

Note that this is not a 3.6.0 blocker given it only applies on `master` pushes anyway.
I've not tested if printing to stderr breaks anything in `Homebrew/test-bot`. I hope not.
Closes https://github.com/Homebrew/brew/pull/13806 (added by @MikeMcQuaid)

Add messaging for `homebrew/ubuntu16.04:master` image deprecation

---

Library/Homebrew/test/dev-cmd/audit_spec.rb

The intention here is clearly to check if the strings are equal rather than interpret it as a regex pattern.
Fixes https://github.com/Homebrew/brew/security/code-scanning/7 (:153).
Fixes https://github.com/Homebrew/brew/security/code-scanning/8 (:199).

test/dev-cmd/audit_spec: use `eq` instead of `match`

---

Library/Homebrew/formula_installer.rb

Fixes https://github.com/Homebrew/brew/issues/13824
We already block `--build-from-source` when installing with `HOMEBREW_INSTALL_FROM_API`, but a source install can still be triggered in certain cases (as seen in https://github.com/Homebrew/brew/issues/13824). As soon as we know that this is going to happen, let's fail with an appropriate error message.
Now:
```console
linuxbrew@7c5642691995:~/homebrew$ brew install gcc
Warning: Building glibc from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/linuxbrew/homebrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/linuxbrew/homebrew)
Error: Unable to build glibc from source with HOMEBREW_INSTALL_FROM_API.
```

Don't fallback to building from source with `HOMEBREW_INSTALL_FROM_API`

---

Library/Homebrew/extend/os/linux/install.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/install.rb

We should be creating these symlinks after these formulae are installed, and before we cache the linkage, instead of just before anything is installed. It is still worthwhile checking beforehand, just in case something has broken between `brew` invocations.
Fixes #13836.

Create GCC and glibc symlinks after install is complete

---

Library/Homebrew/cask/artifact/relocated.rb

-----
Fixes the bug:
```console
% brew readall --eval-all homebrew/cask
Error: Invalid cask: /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/touchosc-editor.rb
Cask 'touchosc-editor' definition is invalid: invalid 'artifact' stanza: Parameter 'target': Expected type String, got type Pathname with value #<Pathname:/Users/jonchang/...upport/TouchOSCEditor/layouts>
Caller: /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10175/lib/types/private/methods/call_validation.rb:117
Definition: /opt/homebrew/Library/Homebrew/cask/artifact/relocated.rb:48
Error: Invalid cask: /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/ilya-birman-typography-layout.rb
Cask 'ilya-birman-typography-layout' definition is invalid: invalid 'artifact' stanza: Parameter …
```

cask/artifact/relocated: widen type

---

Library/Homebrew/formula_auditor.rb

The SSPL is not an open-source license, but it is recognised by SPDX.
See Homebrew/homebrew-core#109801.

formula_auditor: disallow SSPL.

---

Library/Homebrew/api/formula.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/formulary.rb

Closes https://github.com/Homebrew/brew/issues/13856
This PR modifies `Formulary` to handle loading formulae from their alias names via the API. Like the non-api method, I've added a separate `AliasAPILoader` to handle the additional steps that are necessary when loading from an alias.
In order for this to work best, I've added an `all_aliases` method to `API::Formula`. Since retrieving this information requires going through the entire collection of API formulae (including all of their data) I've linked this to `all_formulae`. So calling one of these methods will load both typical formulae and aliases into their respective instance variables, allowing us to cache both at the same time and eliminate the need to go through a second time.
Finally, this also fixes the issue @MikeMcQuaid …

Load formulae from their aliases using the API

---

Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/formulary.rb
Library/Homebrew/tab.rb

This PR adds a `loaded_from_api` item to a formula's `Tab`. Whether the formula was loaded from the API or not is determined by checking the formula namespace to see if it starts with `FormulaNamespaceAPI` which would only be the case when loading from the API. This change will allow us to check whether formulae were installed from the API or not which could be helpful for debugging or other things like that.
I'd also like to note this for casks somehow too, but I'm not totally sure what the best way to do that is. Maybe put it in `config.json` somehow?

Include `loaded_from_api` key in `Tab`

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/env_config.rb
Library/Homebrew/resource.rb
Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi

-----
Alternative to #13868.
Resolves Homebrew/glibc-bootstrap#6
Closes #13868

resource: automatic determine mirrors for `glibc-bootstrap` and PyPI resources

---

docs/Installation.md

-----
This feature is added in https://github.com/Homebrew/install/pull/628, but I forgot to document it here.

docs: document `HOMEBREW_INSTALL_FROM_API` usage in installation

---

Library/Homebrew/formulary.rb

Fixes #13883.
This broke in e8f2d8f6c5b8d53075b7500ba26ccaae79a7bcd1 in a non-obvious way. `CoreTap.instance.alias_dir/ref` where `ref` is an absolute path will just return `ref` itself, but after that commit meant it was lowercased which breaks on case-sensitive systems.
I've tweaked the code to explicitly check if we are using an absolute path `ref` to make the code not rely on weird side effects like that.

formulary: fix error with absolute alias paths

---

Library/Homebrew/extend/os/linux/compilers.rb
Library/Homebrew/extend/os/linux/dependency_collector.rb
Library/Homebrew/extend/os/linux/formula.rb
Library/Homebrew/extend/os/linux/install.rb
Library/Homebrew/os.rb

See Homebrew/homebrew-core#110917 for rationale. Ubuntu 22.04 ships with the GCC 11 compiler, but actually has GCC 12 runtime libraries, causing various formulae to fail under GCC 11 libraries when built using Ubuntu 22.04.
Really we should also change how we detect whether a system is "too old" to compare the runtime library rather than the compiler. With this change, we still don't install anything if the host is running GCC 11 runtime libraries, which isn't correct. The changes necessary to address that are larger however so I'd like to defer that change to 3.6.3 (that particular issue is pre-existing anyway).

Use GCC 12 for runtime libraries

---

Library/Homebrew/linkage_checker.rb

-----
When `dyld` is not able to find a library at its install name, it
attempts to find it inside its default search path.
This means that for libraries we ship that are also provided by the
system (e.g. `libc++`), `brew linkage` can fail even if the formula
still works (i.e. `brew test` succeeds).
Given this, it makes sense to attempt to `dlopen` the library first
before deciding the linkage is broken. This will be useful when we ship
Homebrew/homebrew-core#106925, which will move the install location of
`libc++`, causing `brew linkage` to fail for any formula that links with
that `libc++`.
Those formulae that link with LLVM's `libc++` will fall back to Apple's
`libc++`, which is why we see multiple `brew test`s succeed even when
`brew linkage` failed in the LLVM PR linked above.
This …

linkage_checker: ignore broken linkage with LLVM libc++.

---

Library/Homebrew/extend/os/linux/system_config.rb

Otherwise we'll just see:
```
glibc: N/A
gcc@11: N/A
```

extend/os/linux/system_config: support gcc 12 & keg-only glibc

---

Library/Homebrew/extend/os/linux/development_tools.rb

extend/os/linux/development_tools: handle no /usr/bin/gcc

---

Library/Homebrew/formula.rb

Fixes https://github.com/Homebrew/brew/issues/13891
It turns out that we don't separate test dependencies from runtime dependencies in the fromula JSON API like we do for build and other types of dependencies. This means that there's no way to differentiate between test and runtime deps when loading a formula from the API. This PR adds a new `test_dependencies` element to the JSON API and moves the test dependencies there from the `dependencies` element.

Separate test from runtime dependencies in `Formula#to_hash`

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/formula_auditor.rb
Library/Homebrew/utils/curl.rb
Library/Homebrew/utils/shared_audits.rb

Checks GitHub API if homepage 404s during `brew audit --online`

---

Library/Homebrew/formulary.rb
Library/Homebrew/test/formulary_spec.rb

Follow up to https://github.com/Homebrew/brew/pull/13895
Now that the `test_dependencies` element has made it into the formulae.brew.sh API, we should load those dependencies when loading formulae from the API.

Include test deps when loading a formula from the API

---

Library/Homebrew/extend/os/linux/keg_relocate.rb

-----
There are no more formulae in Homebrew/core that have a runtime
dependency on GCC (see Homebrew/homebrew-core#110883), so there is no
more need to retain linkage with GCC through a versioned path.

linux/keg_relocate: clean up GCC RPATH fix.

---

Library/Homebrew/extend/ENV/std.rb

-----
The compiler used to a build a formula is typically not needed during
the test.
This will allow us to get rid of some `:test` dependencies, which were
added to prevent `brew` from throwing a `CompilerSelectionError` because
the formula declares `fails_with` the default compiler.
This also helps us get more accurate results from `brew linkage` in
cases of unintended linkage with the compiler used to build.
Fixes #11795.

extend/ENV/std: ignore `fails_with` during `brew test`.

---

Library/Homebrew/formula_auditor.rb

-----
This audit is mistakenly passing for formulae where
`variations_dependencies` is an empty array. We can fix that by checking
for `nil` instead.
See Homebrew/homebrew-core#111280.

formula_auditor: fix false negatives in `audit_gcc_dependency`

---

.github/workflows/sorbet.yml
.github/workflows/tests.yml
.github/workflows/vendor-gems.yml
Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
Library/Homebrew/dev-cmd/tap-new.rb
README.md

- use macOS 12 or Ubuntu 22.04 wherever appropriate
- don't append `(Linux)` to job names
- use specific Ubuntu 22.04 and Ubuntu 18.04 jobs
We may want to consider more Ubuntu 18.04 jobs in future, too.

Cleanup and fix CI jobs

---

Library/Homebrew/brew.sh

This is not used anymore, we are building on ubuntu 16.04 for our portable packages: https://github.com/Homebrew/homebrew-portable-ruby
-----

brew: remove HOMEBREW_ON_DEBIAN7

---

Library/Homebrew/extend/os/linux/linkage_checker.rb
Library/Homebrew/hardware.rb

Add system loader filename and arch tag for proper builds and bottling.

Enable Linux AArch64 support

---

Library/Homebrew/formula_auditor.rb
Library/Homebrew/test/cmd/install_spec.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb
Library/Homebrew/test/download_strategies/git_spec.rb
Library/Homebrew/test/formula_spec.rb

The default `init.defaultbranch` has changed from `master` to `main` in Xcode 14.
This PR fixes the following:
* Formula auditor had a hardcoded `origin/master` in the version/revision downgade audits. I've changed this to `origin/HEAD`. The corresponding test has also been updated to do this.
* Various Git download strategy tests (like `--HEAD` tests) failed because we (intentionally as far as I know?) default to `master` if no branch is specified, but our test git repo could have been created with any branch on `git init`. I've adjusted the tests to explicitly create a repo with `master`.
* `dev-cmd/bottle` tests failed because the regex comparisons had a hardcoded `master`. I took the easier option and just made our test repos use `master` too rather than figure out some branch regex. …

Support non-master init.defaultbranch

---

Library/Homebrew/os/mac/xcode.rb

As is pretty much standard now, 14.0 RC/final removed the Ventura SDK, but the 14.1 betas do have it. As such, we need to now require Xcode 14.1 on Ventura.
(Side note: I've not updated `latest_stable` on Monterey from 13.4 yet. This is intentional due to the regular reports of GCC breakages, which is fixed in 14.1, as well as our own issues such as #13863, which all means we really shouldn't promote it as the recommended version yet - but hopefully we can for Xcode 14.1 by the time it releases in a couple weeks)

os/mac/xcode: require Xcode 14.1 on Ventura

---

Library/Homebrew/formula.rb

Match the behaviour of regular BuildErrors by printing the error before throwing.

formula: fix inreplace errors not being printed

---

Library/Homebrew/cmd/update-reset.sh
Library/Homebrew/cmd/update.sh

Otherwise, a global `core.symlinks = false` setting, likely in a WSL context, breaks Aliases and any other places that use symlinks.
Also enforce consistency in `git config` settings.
Ref: https://github.com/Homebrew/homebrew-core/issues/112539

update*: enforce sane symlinks setting

---

Library/Homebrew/formula.rb

-----
Setting `target` to a path outside `HOMEBREW_PREFIX` is not portable,
and will be invalid for some Homebrew installations.
If we want to add an `rpath` outside of `HOMEBREW_PREFIX`, we should
just use the absolute path instead.
See discussion at Homebrew/homebrew-core#110520.

formula: ensure `rpath` is passed a valid `target`

---

Library/Homebrew/cli/args.rbi
Library/Homebrew/cmd/readall.rb
Library/Homebrew/extend/os/linux/readall.rb
Library/Homebrew/readall.rb
completions/bash/brew
completions/fish/brew.fish
completions/zsh/_brew
docs/Manpage.md
manpages/brew.1

This PR updates `brew readall` to simulate other OS configurations. This will hopefully help us reduce errors in formulae and casks that don't appear in the OS versions we test with in CI.
I've also added a `--no-simulate` flag to `brew readall` to opt-out of this if desired, but if we think it's better just to force this everywhere then I can remove it.
Of course, this does make `brew readall` a lot slower (which might be a reason to include the `--no-simulate` flag):
```console
$ hyperfine 'brew readall --eval-all --no-simulate' 'brew readall --eval-all'
Benchmark 1: brew readall --eval-all --no-simulate
Time (mean ± σ):      7.690 s ±  0.074 s    [User: 6.970 s, System: 0.690 s]
Range (min … max):    7.560 s …  7.824 s    10 runs
Benchmark 2: brew readall --eval-all
Time (mean ± σ): …
```

Simulate all OS/arch combinations in `brew readall`

---

Library/Homebrew/cask/artifact/stage_only.rb
Library/Homebrew/cask/artifact_set.rb
Library/Homebrew/cask/cmd/abstract_command.rb
Library/Homebrew/cask/cmd/install.rb
Library/Homebrew/cask/dsl.rb
Library/Homebrew/cask/dsl/container.rb
Library/Homebrew/cask/dsl/version.rb
Library/Homebrew/cli/parser.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/system_command.rb
Library/Homebrew/test/utils/user_spec.rb
Library/Homebrew/utils/gems.rb

This adds preliminary support for Ruby 3 to be used in `brew`, given we'll certainly be using it at some point in the future, we just haven't fully decided when and how.
It applies compatibility fixes, largely around kwarg changes, to allow basic operations to work. By basic operations I mean:
* `brew config`
* `brew install (-s) hello`
* `brew readall homebrew/core` and `brew readall homebrew/cask`
Though a lot of other things seem to work fine - I had no issues with `brew doctor`, `brew info`, etc once the above were fixed.
This PR does not:
* allow brew to be launched under Ruby 3 unaided. You will need to `cp -r vendor/bundle/ruby/2.6.0/gems vendor/bundle/ruby/3.1.0/gems` or similar first. We should commit vendored gems for 2.7-3.1 (or whatever versions we care about), but I don't …

Preliminary compatibility fixes for Ruby 3

---

Library/Homebrew/cmd/update.sh

-----
repair for `We need to handle download errors of the formula.json and cask.json files` in https://github.com/Homebrew/brew/issues/13794

add error log of download `formula.json`

---

Library/Homebrew/download_strategy.rb

-----
In order to install `getmail` brewed curl must be used, because older curl versions (like curl 7.79.1 on my macOS Monterey) can't follow the redirect properly.
I am aware that this might not be that relevant, because I've just deprecated `getmail` in https://github.com/Homebrew/homebrew-core/pull/113253, but this might be helpful to make brew more robust and predictable.
I therefore use download strategy `:homebrew_curl` in the Formula, but in `resolve_url_basename_time_file_size` the non-brewed curl is still used.
While the actual downloading in `_curl_download` is overloaded in the `HomebrewCurlDownloadStrategy` class, `curl_output` isn't, so the non-brewed on from `CurlDownloadStrategy` is used.
Overload `curl_output` in `HomebrewCurlDownloadStrategy` too.
- Checkout …

Fix curl_output for curl download strategy

---

Library/Homebrew/Gemfile.lock
Library/Homebrew/utils/gems.rb

This regressed when updating to Bundler 2 because we needed a list of supported platforms and trying to add the ARM Linux platforms would make the resolver hang (perhaps due to the consideration needed for Sorbet not supporting those platforms). This appears to be fixed in 2.3.24, or at least it is for me.
`brew typecheck` continues to be unsupported on those platforms but that's ok and has always been that way. At least `brew bottle` etc will now work again, which I know is being used.
The list of supported platforms here should now match the list of supported platforms we support for `brew install`.

Restore ARM Linux support when installing gems

---

docs/Homebrew-on-Linux.md

For years, certain packages have had issues executing under WSL 1. It has gotten worse under newer `binutils` versions after https://github.com/bminor/binutils-gdb/commit/74e315dbfe5200c473b226e937935fb8ce391489. It has progressed so far that even `/usr/bin/gzip` on Ubuntu 22.04 is broken, as seen in https://github.com/orgs/Homebrew/discussions/3790 (Ubuntu has recently fixed the issue, but it took a few months and isn't in fresh 22.04 installs yet).
For this reason, I propose formally dropping WSL 1 support. This does not involve any code changes and is purely a documentation change, so this doesn't actually change anything from our part nor does this force anything on existing users who have got it working. I've updated the documentation to say that Homebrew runs on WSL 2 specifically, …

docs: discontinue WSL 1 support; recommend WSL 2

---

Library/Homebrew/resource_auditor.rb

-----
The existing logic in `#audit_head_branch` for identifying the `HEAD` branch in a Git repository will give an ```undefined method `[]' for nil:NilClass``` error when a repository doesn't provide this reference. Expected output from `git ls-remote --symref <repository> HEAD` is as follows:
```
ref: refs/heads/master  HEAD
1a8f9ac700873d1a08de31a17a2fd654245d5085  HEAD
```
However, I encountered this error for a repository (`http://elinks.cz/elinks.git`, `head` in the `elinks` formula) with the following output (i.e., where no symref is provided for HEAD):
```
f86be659718c0cd0a67f88b42f07044c23d0d028  HEAD
```
This PR resolves the error by modifying the related logic to account for a `nil` value.
-----
It's technically possible to go further than this and add some logic to check all …

ResourceAuditor: Fix #audit_head_branch error

---

Library/Homebrew/os/mac/version.rb
docs/Installation.md

- macOS 13 RC has been shipped, and will soon be on our CI. 
- Release date is set to 24th October, so we can start abottling!

Mark macOS Ventura as supported

---

Library/Homebrew/rubocops/components_order.rb

-----
It's sometimes necessary to have a `livecheck` block in an `on_macos` or `on_linux` block. For example, a formula may be disabled on macOS but not on Linux (e.g., `ntfs-3g`). In that scenario, we only want a `livecheck` block to apply to Linux, so livecheck will automatically skip the formula as disabled on macOS.
While this setup works on a technical level, `brew style` will give an `on_linux cannot include livecheck` offense. This PR addresses the issue by adding `livecheck` to `on_system_allowed_methods` in the `ComponentsOrder` Rubocop.
This also updates `on_system_allowed_methods` to use the order in `FORMULA_COMPONENT_PRECEDENCE_LIST`, which may make it a bit easier for formula maintainers to read at a glance. If there was a particular reason for the existing order, I can …

Allow livecheck method in on_system blocks

---

Library/Homebrew/utils/gems.rb

It has long been an issue that macOS system Ruby incorrectly picks the SDKROOT when a newer SDK than the running OS is released. It's why we have this shim: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/shims/mac/super/ruby. It's also why we usually quickly require portable Ruby on older macOS versions despite being otherwise compatible.
Since it's probably too soon to require Portable Ruby on Monterey, let's try to actually fix the issue by setting the SDKROOT when installing gems.
Note that `utils/gems` is the first file to load so by design it cannot use code defined elsewhere in `brew`, other than the envs exported by `brew.sh`.

utils/gems: set SDKROOT for macOS system Ruby

---

Library/Homebrew/test/diagnostic_checks_spec.rb
Library/Homebrew/test/spec_helper.rb
Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.arm64_ventura.bottle.tar.gz

- fix `check_for_config_scripts` test, no idea why this wasn't working
- don't autoretry tests if `focus` or `byebug` are enabled
- add a ARM64 Ventura bottle symlink

macOS Ventura (and related) test fixes

---

Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb

Otherwise in some configurations (e.g. https://github.com/Homebrew/brew/pull/13975) some tests will fail.

integration_test: fix Bundler deprecation.

---

Library/Homebrew/formula.rb
Library/Homebrew/formulary.rb

Closes https://github.com/Homebrew/brew/issues/14029
This PR adds the stable checksum (if it exists) to the JSON API. This also updates the formula API loader to load this value if it exists. This will allow commands like `brew unpack` to be run even with `HOMEBREW_INSTALL_FROM_API` set. I think this can be valuable for maintainers to effectively maintain while having `HOMEBREW_INSTALL_FROM_API` set.

Add stable checksum to the JSON API

---

Library/Homebrew/os/linux/kernel.rb
docs/Homebrew-on-Linux.md

* Glibc 2.26+ (we use 2.35) require Linux kernel 3.2 or later - see https://sourceware.org/pipermail/libc-announce/2017/000017.html.
* Remove GCC requirement given I don't think it matters for bottles (we install GCC ourselves if too old) and is probably wrong for the build-from-source case.
- Everything besides `glibc` is relocatable, with that now supporting it's own bootstrapped GCC.
- For non-x86_64 platforms which don't use the bootstrap, the minimum GCC is 6.2.
- Given this, we could remove compiler support for < GCC 6 from `brew`, though we perhaps want to wait until the end of the `gcc@5` deprecation period, which is no earlier than 9th December.
* Remove libxcrypt-compat requirement given we don't use libcrypt.so.1 anymore.

Update Linux requirements

---

Library/Homebrew/os/mac/xcode.rb

Gives information about what is being updated, downloaded, etc. Else the updater is quite silent and it's hard to tell what's going on and when it will complete.
Example with the `--verbose` flag:
```
% softwareupdate --all --install --force --verbose
Software Update Tool
Finding available software
Downloading macOS Ventura 13.0
Password: 
Downloading: 65.02%
```
This feature is documented in `softwareupdate --help`; i.e.:
```
% softwareupdate --help
usage: softwareupdate <cmd> [<args> ...]
** Manage Updates:
-l | --list		List all appropriate update labels (options:  --no-scan, --product-types)
-d | --download		Download Only
-i | --install		Install
<label> ...	specific updates
-a | --all		All appropriate updates
-R | --restart		Automatically restart (or shut down) if required to complete …
```

Suggest `--verbose` for `softwareupdate --all ...`

---

Library/Homebrew/cask/artifact/relocated.rb
Library/Homebrew/cask/url.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/utils/git.rb
docs/Cask-Cookbook.md

-----
Continuing #13232 since it got closed for going stale. Sorry for vanishing and not finishing this off last time round!
The first five commits on this branch are the same as the commits in #13232, but rebased onto master to ensure they still work with changes made since I originally opened the #13232.
The following two commits (b11df3bef825417b4d67ed9b5639f206e20851bf and 2d68e27d7b1f15f52e88909280777a38ec287d75) rename `only_paths` to `only_path` (and make it a string rather than an array), which means we can automatically apply the `only_path` prefix to artifact sources ([as discussed](https://github.com/Homebrew/homebrew-cask-fonts/pull/5758/files#r910515049)).
The final commit documents installing cask artifacts via git repositories.

Support git partial clones with sparse checkouts (take 2)

---

Library/Homebrew/extend/os/mac/diagnostic.rb

2.6.10 got backported to 11.7.1 and 12.6.1.
We'll bump the minimum when enough people have updated - it's been less than 24 hours.

os/mac/diagnostic: allow Ruby 2.6.10 on < Ventura

---

Library/Homebrew/brew.sh
Library/Homebrew/standalone/load_path.rb
Library/Homebrew/utils/gems.rb

As #14036 shows, we cannot trust the contents of this directory won't break things. We do not need anything that base Ruby does not provide, so there's no need to allow the possibility to use, for example, updated versions of RubyGems.
Fixes #14036.

Remove sitedir from LOAD_PATH

---

Library/Homebrew/dev-cmd/unbottled.rb

dev-cmd/unbottled: fix --dependents erroring

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

`--version` is not allowed (with a confusing message IMO) if the version specified matches the one auto-detected from the URL.
This makes sense, but there is a case where we might want to change the formatting of the version, so let's make the check a strict string comparison.
Example use case: icu4c where it detects "68-1" from the URL, but we change that to read "68.1".

dev-cmd/bump-formula-pr: allow --version for version formatting changes

---

Library/Homebrew/os/mac/xcode.rb

With macOS Ventura, Apple have changed this tool to force-upgrade macOS Monterey installs to macOS Ventura, without any ability to Ctrl+C cancel once it starts downloading. This behaviour cannot be opted out of, unless you manually check the list and install updates individually.
This is an extremely invasive thing to recommend for just updating the CLT, so we should recommend users to use System Preferences instead.

os/mac/xcode: do not recommend `softwareupdate` CLI

---

docs/Shell-Completion.md

The currently suggested configuration for **Oh My Zsh** users breaks **completions** on **non-login** shells as `~/.zprofile` is only executed for login shells. This is further evidenced in Homebrew/brew.sh#900
Fixes https://github.com/Homebrew/brew.sh/issues/900
This PR rewords the suggested configuration to address this issue and keep the alternate simple configuration option for **Oh My Zsh** users.
-----

Fix Oh-My-Zsh suggested completions configuration

---

Library/.rubocop.yml

-----
- As of RuboCop v0.67.0 (quite some time ago!), this rule allows `_` by default as it commonly denotes "this argument is unused". This is not set upstream in `AllowedNames`, the code [ignores underscores](https://github.com/rubocop/rubocop/commit/4bc7d8c1bc14109525ec370cd5b338a9470bed84#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed) entirely.
- In the default RuboCop configs the method names `to` and `io` are [allowed by default](https://github.com/rubocop/rubocop/blob/41a8249b3595cc8656b823d50b2abe38206fd09a/config/default.yml#L2794). But we weren't inheriting those allowed names correctly from the upstream configuration. This fixes that so that we get future enhancements automatically for this particular cop allowlist.

rubocop: Deal with some TODOs for `Naming/MethodParameterName`

---

Library/Homebrew/cask/artifact/relocated.rb

Would be good to get in before the next tag since this regressed since the last.
Should fix #14052.
Should fix https://github.com/Homebrew/homebrew-cask/issues/134356.

cask/artifact/relocated: don't evaluate URL on creation

---

Library/Homebrew/cask/audit.rb

-----
This should prevent situations where we forget to update the macOS dependency if there is a new version required upstream

cask: audit for minimal OS version in sparkle feeds

---

Library/Homebrew/cmd/search.rb

When `stdout` is not a TTY then using `ohai` is a bit unpleasant as it prevents using pipes to do cool things with the output.
Fixes https://github.com/Homebrew/brew/issues/14067 (kinda)

cmd/search: better handle non-TTY output.

---

.devcontainer/on-create-command.sh

-----
- My Codespaces workflow sometimes involves `gh cs ssh` for a terminal and tmux and vim (for better or for worse).
- I tried this on a `Homebrew/brew` Codespace and got the below error. But it felt weird following that instruction to the letter and bloating the Docker image which we by default keep minimal.
- If we didn't have prebuilds setup, this install would increase creation time by quite a bit. But since we do (for the main branch at least), [the `onCreateCommand` is included in those prebuilds](https://docs.github.com/en/codespaces/prebuilding-your-codespaces/about-github-codespaces-prebuilds#the-prebuild-process), so creation time of `Homebrew/brew` Codespaces in most cases should continue to be near instant.
----
Before:
```shell
❯ gh cs ssh
? Choose codespace: …
```

.devcontainer/on-create-command: Add `openssh-server` (for `gh cs ssh`)

---

Library/Homebrew/dev-cmd/tests.rb
bin/brew

Some hacks to get `brew tests` to play nice.

tests: fix under GitHub Codespaces.

---

Library/Homebrew/test/rubocops/formula_desc_spec.rb

-----
- In 2017 almost to the day, I made my first set of contributions to Homebrew. They added a RuboCop rule for ensuring that formula descriptions can't end in a full stop apart from "etc.". https://github.com/Homebrew/brew/pull/3411
- Back then I was asked to write tests for those additions, but for some reason I didn't - lack of time or confidence, who knows!
- Tonight, five years later (!), someone asked me how long I'd been contributing to Homebrew, so I rediscovered that first PR and I was embarrassed by past Issy. So here are some tests for those RuboCops.
😳 😬

test/rubocops/formula_desc: Add some tests I should have written in 2017

---

Library/Homebrew/cask/dsl/caveats.rb

-----
On macOS Ventura, the System Preferences App was updated to System Settings.
This PR updates the navigation path displayed by the `unsigned_accessibility` caveat to reflect these changes.

caveats: Update message displayed by unsigned_accessibility

---

Library/Homebrew/rubyext/rubygems/defaults/operating_system.rb

This is a direct copy paste from what is being proposed upstream, so what's here will eventually become default behaviour.
Might cover #14083, I don't know - this is a completely blind fix but it makes sense to try anyway.

rubyext: align workaround with upstream

---

Library/Homebrew/dev-cmd/prof.rb
Library/Homebrew/rubocops/class.rb
Library/Homebrew/rubocops/components_order.rb
Library/Homebrew/rubocops/components_redundancy.rb
Library/Homebrew/rubocops/conflicts.rb
Library/Homebrew/rubocops/extend/formula.rb
Library/Homebrew/rubocops/formula_desc.rb
Library/Homebrew/rubocops/homepage.rb
Library/Homebrew/rubocops/lines.rb
Library/Homebrew/rubocops/options.rb
Library/Homebrew/rubocops/patches.rb
Library/Homebrew/rubocops/text.rb
Library/Homebrew/rubocops/urls.rb
Library/Homebrew/rubocops/uses_from_macos.rb
Library/Homebrew/style.rb

So we really are passing the disable options everywhere.

style: use HOMEBREW_RUBY_EXEC_ARGS, fix some cops erroring with empty formula body

---

.gitignore
Library/Homebrew/Gemfile
Library/Homebrew/utils/gems.rb

This PR:
* Removes the Ruby >= 2.7 restriction on `brew install-bundler-gems`.
* ~~Modifies `brew vendor-gems` to vendor for both 2.6 and 3.1. It will install 3.1 if you are running 2.6 and find 2.6 if you are running 3.1. It will then run `bundle install` and `bundle pristine` for both these versions.~~
- ~~`brew vendor-gems` as a result from the changes can now be the first port of call when bootstrapping for a new Ruby. From an existing working Ruby, you can modify the command to pick up (for example) Ruby 3.2 and run `brew vendor-gems` on the old Ruby to install the necessary gems for `brew` to run on the new Ruby.~~
* ~~Adds the vendored gems for Ruby 3.1.~~

Allow gem installation on Rubies other than 2.6

---

.devcontainer/on-create-command.sh

Add some debugging information to be able to customise the prebuild/not cases for this script.
Also, handle `zsh-autosuggestions` not being available for Ubuntu 18.04.

devcontainer/on-create-command: fix Ubuntu 18.04, add debugging.

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/utils/github.rb
Library/Homebrew/utils/github/api.rb

-----
move two methods (`github_last_commit` and `multiple_short_commits_exist` ) from `download_storategy` to `utils/github` because of `# TODO`.

move two methods from download_strategy to utils/github

---

Library/Homebrew/requirement.rb
Library/Homebrew/requirements/macos_requirement.rb

We store requirements in a set which means we strip out any duplicate requirements.
However, this was too strict for macOS requirements, as the uniqueness checks did not consider different comparators and versions.
This meant that:
```
depends_on macos: :mojave
depends_on maximum_macos: :big_sur
```
would incorrectly be combined to only one of them - usually the first.
Now with the changes in this PR, macOS requirements will only be combined if they are truly identical (e.g. if `depends_on macos: :mojave` appeared twice).

Allow multiple macOS requirements

---

Dockerfile

It's a small dependency and makes it easier to do scripting.

Dockerfile: install jq.

---

.devcontainer/on-create-command.sh

`CODESPACES_PREBUILD_TOKEN` has been unset as it breaks other things.

devcontainer/on-create-command: fix prebuild handling.

---

Library/Homebrew/rubocops/uses_from_macos.rb

- see https://github.com/Homebrew/homebrew-core/pull/115411
-----

uses_from_macos: add mandoc to allowed list

---

Library/Homebrew/cask/cmd/install.rb

-----
Fixes the following error, when running `brew install` <cask> `--dry-run`:
~~~ sh
> brew install <cask> --dry-run
==> Would install 1 cask:
<cask>
Error: uninitialized constant Cask::Cmd::Install::CaskDependent
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:94:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:93:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:93:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:192:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
~~~

Fix `install` <cask> `--dry-run`

---

Library/Homebrew/extend/os/mac/hardware/cpu.rb

-----
On MacBook Air with M2 chip `brew config` return `dunno` family (while `arm_blizzard_avalanche` is expected):
```
$ brew config | grep CPU
CPU: octa-core 64-bit dunno
```
And here's the corresponding `sysctl -A` output:
```
% sysctl -A | grep hw.cpufamily
hw.cpufamily: -634136515
```
It looks like some signed int32 overflow happens somewhere for `0xda33d83d`, which causes it to return a negative number.
These changes will also affect CPU family detection for `ARMv8.2-A (Monsoon, Mistral)` (https://en.wikipedia.org/wiki/Apple_A11) and for `ARMv8.0-A (Twister)` (https://en.wikipedia.org/wiki/Apple_A9 / https://en.wikipedia.org/wiki/Apple_A9X). They are used in iPhones only, so I don't think it will affect anything real.

CPU: fix M2 family detection

---

Library/Homebrew/missing_formula.rb
Library/Homebrew/test/missing_formula_spec.rb

-----
When playing around with brew a few days ago I realized that one of the reasons that `brew search` and `brew info` can be slow sometimes for me is because of the following `git log` command in `MissingFormula.deleted_reason`.
https://github.com/Homebrew/brew/blob/b683bebd24b5003b47e722116eb2a0989e1e7111/Library/Homebrew/missing_formula.rb#L157-L159
```sh
$ time brew info unknown_formula
Error: No available formula with the name "unknown_formula".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
________________________________________________________
Executed in    9.96 secs    fish           external
usr time    8.72 secs   13.84 millis    8.71 secs
sys time    1.03 secs    2.77 millis    1.02 secs
$ pwd …
```

Speed up `deleted_reason` method

---

Library/Homebrew/utils/gems.rb

This allows switching between portable and system Ruby without having to manually reinstall the gem.
This wasn't an issue previously under Bundler as we used a shim which had its own shebang. And under Bundler 1, our PATH priority was different in that it never actually used the installed executable and used the one that shipped with Ruby instead (albeit still the newly installed core Bundler lib files).
This fix does not affect existing installs, so anybody who updated in the last 8 hours will have the issue if they switch Rubies in the future. This will eventually fix itself when we next update Bundler, which I'll probably do when 2.3.27 is released at the end of the month just to make sure.

utils/gems: use env shebang when installing gems

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
- "Append" is the wrong word for the `--message` arg description since the `bump-formula-pr --message` gets added at the start.

dev-cmd/bump-{cask,formula}-pr: `args.message` is before the default

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/test/diagnostic_checks_spec.rb

- Some of these are currently failing globally on GitHub Actions.
- Some(/all?) of these predate our use of the macOS sandbox, environment filtering, PATH filtering and pushing users much harder to use bottles instead of building from source
- I haven't seen a case for a long time where any of these actually debugged a user issue. If/when this happens: we can add a given check back.
- This should allow us to dramatically reduce the amount of cleanup that `brew test-bot` needs to do on GitHub Actions.
Fixes https://github.com/Homebrew/brew/issues/14175

diagnostic: remove some checks.

---

bin/brew

A similar fix is already present on line 6.
-----

fix: allow running bin/brew with SHELLOPTS=nounset

---

.github/workflows/doctor.yml
Library/Homebrew/brew.sh

-----
We used to need this because the GitHub runner process was running under
Rosetta. GitHub Actions has supported native M1 runners for a few months
now, so I think it's time to remove this.

brew.sh: remove `HOMEBREW_CHANGE_ARCH_TO_ARM`

---

.github/workflows/docs.yml
.github/workflows/tests.yml
docs/.mdl_style.rb
docs/Adding-Software-to-Homebrew.md
docs/Brew-Test-Bot.md
docs/Common-Issues-for-Core-Contributors.md
docs/Deprecating-Disabling-and-Removing-Formulae.md
docs/Homebrew-Governance-Archives.md
docs/Homebrew-Leadership-Responsibilities.md
docs/Homebrew-and-Python.md
docs/Homebrew-homebrew-core-Maintainer-Guide.md
docs/Maintainers-Avoiding-Burnout.md
docs/Rakefile
docs/governance/2021-agm-minutes.md
docs/vale-styles/Homebrew/README.md

-----
An attempt at having CI test for issues with YARD's rubydoc generation. Doesn't currently work because I'm unsure of how to get bundler working. (Next step after that would be to add Markdown formatting checks [using `mdl`](https://github.com/Homebrew/brew/pull/12431#discussion_r750327605) now that it's shipped a release with [this fix](https://github.com/markdownlint/markdownlint/pull/394), although it now [requires Ruby 2.7](https://github.com/markdownlint/markdownlint/releases/tag/v0.12.0).)

CI: check yard & mdl output

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/test/utils/curl_spec.rb
Library/Homebrew/utils/curl.rb

-----
Update base URL when there is an absolute location, so that following
relative locations are considered relative to the new base.
Consider below cURL output for https://example_one.com:
HTTP/1.1 302 Moved Temporarily
Location: https://example_two.com
HTTP/1.1 302 Moved Temporarily
Location: /foo/
HTTP/1.1 200 OK
The final URL should be https://example_two.com/foo/ rather than
https://example_one.com/foo/.
Fixes #13721

Curl: Fix following redirections when base changes

---

Dockerfile

It's currently installed by default on 16.04 but not 18.04+.
`gpg-agent` is something else and does not install `gpg`.

Dockerfile: install gpg

---

Library/Homebrew/diagnostic.rb

-----
I was running `brew doctor` in my local machine when it returned a warning that my installation has uncommitted changes
```
Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f
Uncommitted files:
?? Formula/pingu.rb
```
There was a formula that I started working on but I never actually completed it and it had just been sitting uncommitted. The suggested `git stash` command saves any modified files, but it doesn't include new files, which resulted in `git clean -d -f` deleting the file without being …

doctor: add -u flag to suggested git stash command

---

Library/Homebrew/livecheck/strategy/sparkle.rb
Library/Homebrew/test/livecheck/strategy/sparkle_spec.rb

-----
In attempting to [bump TextExpander to the latest available release](https://github.com/Homebrew/homebrew-cask/pull/134073) I found that the latest versions weren't being detected by livecheck. This is because due to [a prior change](https://github.com/Homebrew/brew/pull/10273) we (correctly) attempt to filter the OS down to just macOS. Unfortunately, the filter was a bit too aggressive. This adds the new observed value from the TextExpander Sparkle feed.
```
$ date -u '+%FT%T%z' && xmlstarlet sel -t -v '//rss//channel//item//enclosure/@*[name()="url" or name()="sparkle:version" or name()="sparkle:shortVersionString" or name()="sparkle:os"]' <(curl --location --silent https://textexpander.com/appcast/TextExpander-macOS.xml)
2022-10-22T17:07:06+0000 …
```

livecheck/strategy/sparkle.rb: Add `macos` to the candidate `os` values list

---

Library/Homebrew/dev-cmd/bump.rb

-----
This should fix issues like one seen in https://github.com/Homebrew/homebrew-core/pull/116956 when the Repology version is greater than the one we get from Livecheck and the strategy is different than GithubLatest.
Basically if we define a livecheck block, I think we want the Livecheck to be the top priority over Repology.
If we don't define the livecheck block, then Repology data should be equal to what Livecheck returns.

dev-cmd/bump: don't use Repology version if livecheckable

---

Library/Homebrew/livecheck/strategy/electron_builder.rb
Library/Homebrew/test/livecheck/strategy/electron_builder_spec.rb

-----
The `ElectronBuilder` strategy uses `YAML#safe_load` to parse YAML content and this [limits deserialization to appropriate classes](https://ruby-doc.org/stdlib-2.6.10/libdoc/psych/rdoc/Psych.html#method-c-safe_load). We [recently encountered a `Tried to load unspecified class: Time` error](https://github.com/Homebrew/homebrew-cask/pull/137011) when using the `ElectronBuilder` strategy on a `latest-mac.yml` file containing `releaseDate: 2022-12-01T02:02:46.419Z`.
The electron-builder YAML files we usually encounter use single quotes around the `releaseDate` value to ensure it's treated as a string (e.g., `releaseDate: '2022-10-12T17:55:26.718Z'`) and this is what we do in `electron_builder_spec.rb`. The aforementioned YAML file doesn't use single quotes around the value, so it's …

ElectronBuilder: Allow Date/Time deserialization

---

Library/Homebrew/dev-cmd/audit.rb

-----
Enables the `--[no-]signing` flag for auditing casks.
Should fix the error on - https://github.com/Homebrew/homebrew-cask/pull/137074

dev-cmd/audit: enable --[no-]signing flag for audits

---

Library/Homebrew/caveats.rb
Library/Homebrew/test/caveats_spec.rb

-----
Followup of https://github.com/Homebrew/brew/pull/14113, after this is released the formula in core can drop the last plist references.

caveats: print sudo in caveats if service requires it

---

Library/Homebrew/cmd/desc.rb
Library/Homebrew/description_cache_store.rb
Library/Homebrew/descriptions.rb

Ensure that the cache store is populated if we pass `--eval-all`.
Fixes https://github.com/Homebrew/brew/issues/14010

cmd/desc: fix searching.

---

Library/Homebrew/dev-cmd/bump.rb

-----
Follow-up to: https://github.com/Homebrew/brew/pull/14190
Before:
```
Mon 05 Dec 16:16:05 ➜  Library/Homebrew stash master ✓  brew bump cortex --open-pr
==> cortex
Current formula version:  1.13.1
Latest livecheck version: 1.14.0
Latest Repology version:  present only in Homebrew
Open pull requests:       cortex 1.14.0 (https://github.com/Homebrew/homebrew-core/pull/117195)
cortex was not bumped to the Repology version because it's livecheckable.
```
After:
```
Mon 05 Dec 16:16:19 ➜  Library/Homebrew master ✗  brew bump cortex --open-pr
==> cortex
Current formula version:  1.13.1
Latest livecheck version: 1.14.0
Latest Repology version:  present only in Homebrew
Open pull requests:       cortex 1.14.0 (https://github.com/Homebrew/homebrew-core/pull/117195)
```
Basically the output …

dev-cmd/bump: check if Repology output is a version first

---

Library/Homebrew/dev-cmd/create.rb
Library/Homebrew/test/dev-cmd/create_spec.rb

-----
`brew create --formula` prompts for a name if none is provided. This adds the same prompt to `brew create --cask`.

dev-cmd/create: also prompt for name with `--cask`

---

Library/Homebrew/brew.rb

-----
This is just a cleanup of `brew prof` which isn't working correctly right now.
First off there is an error when using `brew prof` that is caused by check to make sure this file is never loaded by `require`. I added an exception so that `ruby-prof` can load it fixing the following error message.
```
$ brew prof ls
/usr/local/Homebrew/Library/Homebrew/brew.rb:10:in `<top (required)>': /usr/local/Homebrew/Library/Homebrew/brew.rb must not be loaded via `require`. (RuntimeError)
from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/bin/ruby-prof:291:in `load'
from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-prof-1.4.3/bin/ruby-prof:291:in `block in run'
from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ru …
```

Cleanup `brew prof`

---

Library/Homebrew/formula_installer.rb

This outputs headers for fetching to be consistent with those for installation.
Fixes #14170

formula_installer: output fetching headers.

---

Library/Homebrew/language/python.rb
Library/Homebrew/test/language/python/virtualenv_spec.rb

-----
Exploring a way to make virtualenv'd formulae's manpages easier to link.
WIP as still need to test.
Also considering if worth adding or not. Currently about 8-9 formulae may use this to help link the manpages (`streamlink` is 9th but it is using wrong path in formula). Looking at adding for `urlwatch` which has `man1/5/7` and there are probably others.
Could also add helper for shell completions but not sure how common venv installed completions are yet.

language/python: optionally link manpages

---

Library/.rubocop.yml
Library/Homebrew/.rubocop.yml

-----
This should handle the problem brought up in https://github.com/Homebrew/brew/pull/14163#issuecomment-1342906045 where the `MoveToExtendOS` cop was linting taps which is not what we want.

Only use OS cop internally

---

docs/Acceptable-Casks.md

-----
Adds documentation that should clear up https://github.com/Homebrew/brew/issues/14253. I didn't want it to just be about signing because there could be other reasons that would block users from using the app.

docs: Document that casks should pass GateKeeper

---

Library/Homebrew/language/python.rb
Library/Homebrew/test/language/python/virtualenv_spec.rb

-----
While debugging https://github.com/Homebrew/homebrew-core/pull/117779 locally, I noticed that a significant portion of the time was spent re-installing `setuptools` and other `install dependencies`.
When we run `pip install /path/to/dep`, it will basically always require `setuptools` and `wheel` as a build dependency. Some packages require more, such as `zipp` that needs `packaging-22.0 setuptools-65.6.3 setuptools_scm-7.0.5 tomli-2.0.1 typing-extensions-4.4.0`.
The current code is reinstalling these dependencies over and over again for every single dependency due to the `--no-binary` flag, which is really wasteful.
By passing `--use-feature=no-binary-enable-wheel-cache` it will not download any binaries from pypi but instead it will use the local cached setuptools and wheel …

Allow pip to use the local wheel cache while installing dependencies

---

Library/Homebrew/language/python.rb
Library/Homebrew/test/language/python/virtualenv_spec.rb

---
This was accidentally dropped in #14239, but it's still needed: https://github.com/Homebrew/brew/pull/14239#issuecomment-1358926865

python: reinstate pip's `--no-binary`

---

Library/Homebrew/formula.rb

-----
If a formula-level `livecheck` block doesn't exist, then the `Homebrew::Livecheck::Constants` module is never included and so it isn't possible to access these constants from a resource's `livecheck` block. This PR includes the module irrespective of the existence of a formula-level `livecheck` block.
I wasn't able to fix this by just including `Homebrew::Livecheck::Constants` in `resource.rb` (the `livecheck` method in the `Resource` class specifically, not a Ruby expert) so I went with this instead.

Fix access to `livecheck` constants in formulae

---

Library/Homebrew/utils/github/api.rb

-----
Now that GitHub has a versioned API, explicitly pass the API version in requests: https://docs.github.com/en/rest/overview/api-versions?apiVersion=2022-11-28

add explicit version for GitHub API

---

Library/Homebrew/dev-cmd/audit.rb

-----
`brew audit` doesn't work as expected when users pass in formula/cask paths so we are deprecating it.

Deprecate path args to audit cmd

---

Library/Homebrew/formula.rb

-----
NOTE: Open to other suggestions as not familiar with popen code path and if there is any odd behavior of outputting stderr.
Added this as currently trying to debug failing `generate_completions_from_executable` on CI is difficult since popen defaults to sending stderr to /dev/null which is where most failing commands end up outputting failures
https://github.com/Homebrew/brew/blob/0e56c86c89b572f2daf26270fab26782f3cf2b51/Library/Homebrew/utils/popen.rb#L53
This leads to hard to figure out failures without locally retesting, e.g.: 
- https://github.com/Homebrew/homebrew-core/pull/116583#issuecomment-1356761947
- https://github.com/Homebrew/homebrew-core/pull/118475#issuecomment-1357753530

formula: show stderr by default when generating completions

---

Library/Homebrew/cmd/formulae.sh
Library/Homebrew/items.sh

-----
Workaround for removing errors output in #14254. Will need API usage for actual completion support, but haven't had chance to look into this.
EDIT: Updated to allow completion from cached JSON to fix #14254
Haven't tested on `HOMEBREW_INSTALL_FROM_API` setup, but seemed to work when I changed Taps in following line to invalid directory:
https://github.com/Homebrew/brew/blob/884c4bec14073314ac6e8e9a6a64bc3b26161ab6/Library/Homebrew/items.sh#L21
---
e.g. changing above to `Taps2` and trying without this PR:
```console
❯ brew formulae
find: /opt/homebrew/Library/Taps2: No such file or directory
❯ brew info find: /opt/homebrew/Library/Taps2: No such file or directory
find: /opt/homebrew/Library/Taps2: No such file or directory
brew
```
with PR:
```console
❯ brew formulae
❯ brew info …
```

items.sh: return early when no Taps directory

---

Library/Homebrew/cask/audit.rb

This PR improves the audit that checks the minimum macOS version in casks. Now, the audit displays symbols instead of version numbers when explaining what's wrong. Ultimately, the `depends_on` line uses the OS symbol instead of the number, so it's better to just list that instead of forcing the user to convert between version numbers and symbols.
Also, the edge case where a cask specifies 10.16 as the minimum version has been handled. Now, 10.16 is treated as `:big_sur`.
For context, see https://github.com/Homebrew/homebrew-cask/pull/138579

Improve minimum macOS version audit for casks

---

Library/Homebrew/cask/audit.rb

-----
This is a continuation of #14297 - where the cask doesn't specify a minimum `depends_on` the audit was erroring out with a type error. This now returns an appropriate message.
Related: https://github.com/Homebrew/homebrew-cask/pull/138667

cask/audit: improve sparkle minimum version audit

---

Library/Homebrew/rubocops/cask/on_system_conditionals.rb
Library/Homebrew/rubocops/shared/on_system_conditionals_helper.rb
Library/Homebrew/test/rubocops/cask/on_system_conditionals_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-depends-on-macos-failure.rb

This PR expands the existing suite of rubocops that enforce the use of `on_system` blocks over `if` statements. Now, the style checks will catch more cases that slipped through before.
Most importantly, this PR adds the ability to check for `if MacOS.version` conditionals in casks. This is the last major step needed before we can switch the cask API loading to JSON files instead of from source.
Big thanks to @bevanjkay and @p-linnane for doing most of the work to get the cask repos switched over.
---
I know that there is one formula (`vtk`) that is still in the process of being updated. Once https://github.com/Homebrew/homebrew-core/pull/119246 is merged, though, this PR should be ready.
I'm going to mark this PR as `critical` so we get the checks in ASAP and don't risk new changes being …

Expand `on_system` rubocops

---

Library/Homebrew/cask/audit.rb

-----
This further iterates on #14298. Rather than stating `nil` when a cask doesn't have a minimum OS defined, this produces a clearer message.
This also changes references to "minimal OS" to "minimum OS". This is more familiar in common parlance, and aligns with [Apple's documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/minimumosversion).

cask/audit: improve handling `nil` in sparkle

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
followup of #14285
current issue
```
Error: Calling brew audit [path ...] is deprecated! Use brew audit [name ...] instead.
```

audit: use `full_name` for `formula`/`cask` audit

---

Library/Homebrew/cask/artifact/abstract_uninstall.rb
Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-launchctl-wildcard.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-zap-launchctl-wildcard.rb

-----
This is an initial attempt to allow wildcard entries in Cask's `uninstall launchctl` stanza. 
The code takes the list of launchctl services provided in the uninstall stanza, and when it finds an `*` it will search the loaded system `launchctl` items to find any that match, and then pass them to the existing system for uninstalling. There may well be a more efficient/effective way to do this, however I just wanted to get the ball rolling here.
This will likely require new tests to be written, I have little knowledge on unit testing so some guidance here would be great.
https://github.com/Homebrew/homebrew-cask-drivers/pull/3104
https://github.com/Homebrew/homebrew-cask/issues/79661

cask/artifact/abstract_uninstall: allow wildcard entries for launchctl

---

Library/Homebrew/cask/cask.rb

This PR updates the cask JSON API's `container` entry to be actual JSON instead of just a ruby `#inspect` string.
Before:
```json
{
"container": "{:type=>:naked}"
}
```
After:
```json
{
"container": {
"type": "naked"
}
}
```
---
This is technically a breaking API change, but I can't imagine anyone is using the current system since it's in this weird format. If we get a complaint, we can revert. I'm marking this as `critical` since it is blocking the next step in the API project (loading casks directly from the API).

Use JSON instead of `#inspect` to include cask container in API

---

Library/Homebrew/extend/os/mac/diagnostic.rb

-----
This check was added in four years ago in https://github.com/Homebrew/brew/pull/5614. We were seeing problems at the time with users not being able to download packages correctly when running BitDefender (https://github.com/Homebrew/brew/issues/4579 and https://github.com/Homebrew/brew/issues/5558).
Those issues were apparently resolved by BitDefender and we got an issue in mid 2020 asking us to remove the check since it was no longer necessary (https://github.com/Homebrew/brew/issues/7452). Since that point we haven't received anymore issues or complaints related to BitDefender in either the main `brew` repo or in the discussions (I just searched for `bitdefender` in both places).
Also, anecdotally, I haven't had any problems using `brew` and `BitDefender` at the same time on my …

Remove bitdefender diagnostic check

---

docs/Acceptable-Casks.md
docs/Acceptable-Formulae.md
docs/Cask-Cookbook.md
docs/Common-Issues.md
docs/FAQ.md
docs/Formula-Cookbook.md
docs/_config.yml

Fixes #14283 by adding a [Kramdown `{:toc}`](https://kramdown.gettalong.org/converter/html.html#toc) to some of the longer docs pages, which inserts a linked list of headers. The `toc_levels` config setting manages which header levels are included.
An alternative implementation using https://github.com/allejo/jekyll-toc is also possible, but as that would involve editing the Liquid template, it would end up being shown before the page's initial heading unless some CSS to push it off into a [sticky sidebar](https://shaharkadmiel.github.io/Sticky-TOC-Sidebar/) were also developed.

docs: add Table of Contents to selected pages

---

.gitignore
Library/Homebrew/brew.rb
Library/Homebrew/dev-cmd/prof.rb
Library/Homebrew/test/dev-cmd/prof_spec.rb

-----
This PR fixes `brew prof` again. There were two problems.
1. `brew prof` was not working with the latest version of the `ruby-prof` gem since it now requires Ruby >= 2.7 ([source](https://github.com/ruby-prof/ruby-prof/blob/5d9ca2d9cf64fdba345f2afb6c5a8f86f87e7461/CHANGES#L6-L19)). Specifying the version was enough to fix that.
2. `brew prof --stackprof` hasn't been working for a bit and the problem was related to not being able to require the gem after installing it locally and then shelling out to brew again. By requiring the `rubygems` gem we are able to pick up the `GEM_HOME` and `GEM_PATH` environment variables that we set during the gem installation/setup process.
I also added some integration tests to make sure we get notified if these gems start failing again. I'm not sure …

cmd/prof: Fix gem errors

---

.github/workflows/tests.yml

Previously, we ran it 5 times (4 on Linux, 1 on macOS) which burned up our GitHub Actions token rate limit much quicker than is necessary.

workflows/tests: only `brew tests --online` twice.

---

Library/Homebrew/cli/parser.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/extend/os/linux/parser.rb
Library/Homebrew/test/cli/parser_spec.rb

-----
This fixes #14314.
1. Validate options before constraint violations. This allows us to error out when --cask is passed on Linux before getting a constraint violation when --cask and --formula are set.
2. Skip printing the help page when --cask is passed on Linux. The help pages don't usually mention anything useful related to casks only running on MacOS so it's just better to skip them IMO.
3. I added some regression tests.
```
/u/l/Homebrew (better-error-cask-on-linux|✚2) $ brew install -n --cask postman
Error: Invalid usage: Casks are not supported on Linux
/u/l/Homebrew (better-error-cask-on-linux|✚2) [1]$ brew install -n --cask --formula postman
Error: Invalid usage: Casks are not supported on Linux
/u/l/Homebrew (better-error-cask-on-linux|✚2) [1]$ brew install -n postman …
```

cli/parser: Better error message for cask on linux

---

Library/Homebrew/Gemfile
Library/Homebrew/Gemfile.lock
Library/Homebrew/cask/artifact/abstract_flight_block.rb
Library/Homebrew/cask/cask.rb
Library/Homebrew/test/cask/cask_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/conditional-flight.rb

This PR updates the cask JSON API to include the Ruby source for `*flight` blocks. This will allow us to execute those blocks when loading casks from the API. See https://github.com/Homebrew/brew/pull/14304 for more discussion on this.
---
Marking as critical since this needs to get through `formulae.brew.sh` to unblock #14304

Include `*flight` block source in cask API

---

.gitignore
Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source.rb
Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/code_helpers.rb
Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/source_location.rb
Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib/method_source/version.rb

Fixes #14329
The `method_source` gem should be vendored to allow `brew info --json` to work on casks without needing to install all gems. The gem is relatively small so I don't think there is a big concern with vendoring it in.

Vendor `method_source` gem

---

Library/Homebrew/cask/cask_loader.rb
Library/Homebrew/dev-cmd/edit.rb

Before this change, this would fail every time, even when available on disk (which was not the case for formulae).
With this change, it will attempt to find it from a tap on disk and only fail if it cannot be found in any.
Open to feedback from @Rylan12 and others on approach, this may not be the best one.

dev-cmd/edit: handle editing with `install_from_api`.

---

Library/Homebrew/brew.sh

This fix is required for ARM Linux where Homebrew Portable Ruby is not available.
Without this fix, after auto-update, `brew` is restarted with cleaned-up path.
This causes it to not find user installed Ruby by RVM or rbenv, causing brew to fail.
-----

Restoring the original `PATH` after update

---

Library/Homebrew/api.rb
Library/Homebrew/api/cask.rb
Library/Homebrew/api/formula.rb
Library/Homebrew/cask/cask_loader.rb
Library/Homebrew/cmd/update.sh
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/github_packages.rb
Library/Homebrew/test/api/cask_spec.rb
Library/Homebrew/test/api/formula_spec.rb
Library/Homebrew/test/api_spec.rb

This PR updates the method for loading casks when `HOMEBREW_INSTALL_FROM_API` is set. Now, casks are loaded directly from the JSON API in the same way that formulae are. I've started to test this out locally and haven't had any issues so far (outside of the ones listed below).
It's worth noting that the old `cask-source` API is still being used to write the cask source to the `.metadata` folder. This is similar to the way that formula bottles also contain the formula file, except that the source for casks are retrieved using the API rather than a bottle.
Also, a nice little side effect of this PR is that `brew edit` now works for casks with `HOMEBREW_INSTALL_FROM_API` (while the taps are installed, of course)
---
Here are some known issues:
- Casks with `{uninstall_,}{pre,post}flight` …

Load casks from the JSON API with `HOMEBREW_INSTALL_FROM_API`

---

Library/Homebrew/cask/installer.rb

I encountered this when installing `microsoft-edge`.
Perhaps `HOMEBREW_INSTALL_FROM_API` related CC @Rylan12

cask/installer: ensure config_path exists.

---

Library/Homebrew/cli/parser.rb
Library/Homebrew/test/cli/parser_spec.rb

-----
This fixes https://github.com/Homebrew/brew/issues/14341.
This adds back in the ability to run dev commands with the `--cask` option on Linux. The approach here is to check whether the command is in the `dev-cmd/` folder and then skip the checks if it is. We could also approach this on a command-by-command basis by passing some sort of option to the parser's constructor but I think this is cleaner.
This will only affect 7 dev commands.
```
$ git grep 'switch "--cask"' -- '/usr/local/Homebrew/Library/Homebrew/dev-cmd'
Library/Homebrew/dev-cmd/audit.rb:      switch "--cask", "--casks",
Library/Homebrew/dev-cmd/bump.rb:      switch "--cask", "--casks",
Library/Homebrew/dev-cmd/cat.rb:      switch "--cask", "--casks",
Library/Homebrew/dev-cmd/create.rb:      switch "--cask", …
```

Allow --cask for linux dev cmds

---

Library/Homebrew/cask/dsl/container.rb
Library/Homebrew/test/cask/dsl/container_spec.rb

-----
This PR fixes one of two warnings in YARD generation: https://github.com/Homebrew/rubydoc.brew.sh/actions/runs/3889710173/jobs/6638203664#step:7:24
It will result in `Cask::DSL::Container`'s attributes and allowed `initialize` arguments correctly appearing in the documentation at https://rubydoc.brew.sh/Cask/DSL/Container.html
It seems that the purpose of `Cask::DSL::Container#pairs` is to summarize the other attributes of `Container`. However, it is set independently of the other attributes, and thus would need to be updated if the other attributes change. This diff instead makes `pairs` a derived property, which inspects the state of the instance's attributes to determine its output.
The tests I've written verify that `to_yaml` and `to_s` are the same before and after this change. …

Make Cask::DSL::Container#pairs a derived property (and fix YARD warning)

---

Library/Homebrew/cask/cask_loader.rb

Fixes https://github.com/Homebrew/homebrew-cask/issues/139214
This PR handles `depends_on arch:` lines correctly. The API contains a larger JSON object that can't be passed directly to the `depends_on` method, so we have to extract the arch symbol from that object.

Fix `depends_on arch:` when loading casks from API

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/test/utils/gzip_spec.rb
Library/Homebrew/test/utils_spec.rb
Library/Homebrew/utils.rb
Library/Homebrew/utils/gzip.rb
Library/Homebrew/utils/gzip.rbi

-----
Introduce a new `reproducible_gzip` helper function which can be used by formulae. The inputs and outputs of this function are the same as `Utils.gzip`. However, the resulting gz file produced by `reproducible_gzip` has its `mtime` set to `SOURCE_DATE_EPOCH`.
This allows for gz files produced at different times, on different CI instances or end user machines, and with different operating systems to still have the same checksum.
So far, I have identified five formulae in `homebrew-core` that the bottles probably only differ due to different mtimes in gzipped files (either manpages or data files). Introducing this usage in those instances should allow an `all` bottle to be built.
Notes and other considerations:
- As noted in the comment in `Utils.reproducible_gzip`, this currently …

utils: add reproducible_gzip helper function

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/system_config.rb

Because anyone can forget they're on a different branch, and wonder why `brew update` isn't pulling in the latest changes (https://github.com/orgs/Homebrew/discussions/4105#discussioncomment-4658869).

show/check Homebrew branch

---

.github/workflows/docs.yml
Library/Homebrew/extend/ENV.rb

-----
This is a follow-up to https://github.com/Homebrew/brew/pull/14354#issuecomment-1379304944 that resolves the remaining YARD error and enables `--fail-on-warning` to the `docs` action. It does so by using YARD's [parse](https://rubydoc.info/gems/yard/file/docs/Tags.md#parse) directive to register `ENV` as a class. While `ENV` is not actually a class, this is a [common](https://rubydoc.info/stdlib/core/ENV) [workaround](https://ruby-doc.org/core-3.1.0/ENV.html) in ruby documentation.
While it would make more sense to place the `@!parse` directive near the `extend` invocation at the end of the file, YARD seems to be picky about where directives can go: a `class`/`module` declaration, a `def`, the top of the file, or in isolation. (The last one meaning that the directive is followed by …

Fix remaining YARD exception, enable --fail-on-warning

---

Library/Homebrew/brew.sh
Library/Homebrew/env_config.rb
Library/Homebrew/test/env_config_spec.rb
docs/Manpage.md
manpages/brew.1

This doesn't need to be nearly as often for HOMEBREW_INSTALL_FROM_API users because we're getting the latest information from the API when needed rather than just at `brew update` time.

Change HOMEBREW_INSTALL_FROM_API update frequency

---

Library/Homebrew/cmd/formulae.sh
Library/Homebrew/cmd/update.sh
Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

This allows HOMEBREW_INSTALL_FROM_API functionality to be disabled and will stick around once HOMEBREW_INSTALL_FROM_API is made the default behaviour.

Add HOMEBREW_NO_INSTALL_FROM_API

---

Library/Homebrew/rubocops/caveats.rb
Library/Homebrew/test/rubocops/caveats_spec.rb

-----
Formula caveats text appears on formulae.brew.sh but escape characters, as used in ANSI escape codes, should not appear in HTML (see https://github.com/Homebrew/formulae.brew.sh/pull/680, https://github.com/Homebrew/homebrew-core/pull/120530). This PR adds a RuboCop to disallow escape characters in the caveats text.

rubocops/caveats: Disallow ANSI escape codes

---

Library/Homebrew/cask/artifact/moved.rb

-----
Fixes `brew install --cask` behavior when it tries to `mkdir` even if the directory (e.g. /Applications) already exists.
Also see this comment: https://github.com/Homebrew/brew/commit/e09eaf5b3144983b792ff71167274f8da2cd356c#r32244581

cask: don't attempt to make a directory that already exists.

---

Library/Homebrew/cask/artifact/moved.rb
Library/Homebrew/test/cask/artifact/app_spec.rb

-----
`brew uninstall --cask` during the backup step incorrectly checks parent of the source directory (`target`) for write-ability instead of the destination directory (`source`).

cask: fix writability check backing up an artifact

---

Library/Homebrew/cask/artifact/moved.rb

-----
Currently `brew install --cask` assumes that `sudo` has write access  to the caskroom. This is not necessarily true: a system administrator may override the default sudo user via the runas_default setting in sudoers. This user may be defined to have sufficient privileges to write to the system directory for installation but restricted from writing to Homebrew's locations.
A performance enhancement would be to change unconditional `cp -pR` to try commands (in order):
1. ~~`mv`~~ _It's better to use `cp` as the resulting file will be owned by the user that has writability in the parent's directory_
2. `cp -cpR`
3. `cp -pR`
However, the benefit might be marginal: on my system (MBP M1 Pro) copying Xcode.app with the `-c` takes ~1min vs ~2min without it.

cask: don't assume that sudo has write access to the caskroom

---

Library/Homebrew/options.rb
Library/Homebrew/test/options_spec.rb

-----
`Options` objects are converted to a string in some circumstances but this produces output like `#<Options:0x0000000102592c90>`.
For example, formulae.brew.sh contains analytics entries with incomprehensible names like `adns #<Options:0x0000000102592c90>` (see Homebrew/formulae.brew.sh#679). This shortcoming is apparent when compared to other entries like `adns --HEAD`.
The `Option` class has a `#to_s` method that returns the `flag`, so this PR simply adds an `Options#to_s` method that calls `#to_s` on each `Option` object in `@options` and joins them using spaces. This should produce more useful output when an `Options` object is converted to a string (e.g., `--first --second`).
I've added a simple test for this but it currently doesn't test options like `--first=1` (see below). …

Options: Add #to_s method

---

Library/Homebrew/test/cmd/search_spec.rb
Library/Homebrew/test/dev-cmd/bump_spec.rb
Library/Homebrew/test/dev-cmd/prof_spec.rb
Library/Homebrew/test/utils/repology_spec.rb

These are absurdly flaky right now so let's disable them.
CC @dawidd6 in case there's other stuff related to e.g. autobump.

some needs_network specs: temporarily disable.

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/test/cask/audit_spec.rb

Longer-term solution is described [here](https://github.com/Homebrew/brew/issues/14365#issuecomment-1398214354).
Resolves #14365.
CC @MikeMcQuaid
-----

Permit multiple `uninstall` stanzas in casks (short-term fix)

---

Library/Homebrew/cmd/install.rb

-----
This resolves #14361.
The idea here is to facilitate scripting by always failing whenever a package is not installed successfully. This is
how the upgrade and reinstall commands work but not install because we also search for similar package names before terminating.
The only thing to consider here is if anyone relies on the current behavior which would return success if the package didn't exist but a package with a similar name does exist. I can't see how this behavior would be useful for scripting or something you could consistently rely on so I think it's probably fine to change that behavior.
```
/u/l/Homebrew (fail-on-pkg-not-found-in-install|✔) $ HOMEBREW_NO_AUTO_UPDATE=1 brew install -n virtualsox
Warning: No available formula with the name "virtualsox". Did you mean …
```

cmd/install: fail when pkg not found

---

Library/Homebrew/dev-cmd/bump-cask-pr.rb
Library/Homebrew/dev-cmd/bump.rb
Library/Homebrew/utils/github.rb

-----
This fixes #14336 where we found out that the `brew bump` command was failing when there already existed a closed PR that tried to update the package to the same version. This recommended passing the `--force` flag which the `brew bump` command doesn't allow. This is expected behavior in `bump-formula-pr` that wasn't addressed in `brew bump`. The change here is to check for closed PRs in the `brew bump` command first and not allow users to force any PRs from that command because it's a convenience command for `brew bump-cask-pr` and `brew bump-formula-pr`. It also adds the closed PR check to `brew bump-cask-pr` to match the formula version of the same command.
The reason why we don't want people bumping packages that have a closed PR is because that means it was either already …

Add closed PR check to bump cmds

---

Library/Homebrew/rubocops/lines.rb
Library/Homebrew/test/rubocops/text/miscellaneous_spec.rb

-----
1. `llvm-g{cc,++}` has been gone for a long time. We don't need to check for this anymore.
2. Also check for calling the compiler as `cc`, `c89`, `c99`, or `c++`.

rubocops/lines: update hard-coded compiler check

---

Library/Homebrew/search.rb
Library/Homebrew/tap.rb

Fixes https://github.com/Homebrew/brew/issues/14009
This (long overdue) PR fixes `brew search` for `HOMEBREW_INSTALL_FROM_API`. Now, `brew search` will use the API to generate its list of formula/cask names if the user has set `HOMEBREW_INSTALL_FROM_API` _and_ the respective homebrew/core or homebrew/cask tap is not installed.

Fix `brew search` for `HOMEBREW_INSTALL_FROM_API`

---

Library/Homebrew/brew.sh

Test `HOMEBREW_INSTALL_FROM_API` on `HOMEBREW_DEV_CMD_RUN` and `HOMEBREW_DEVELOPER` folks who haven't run a `HOMEBREW_DEVELOPER_COMMAND`.
The next step after this will be to make this functionality the default for everyone.
Want this to be tested a bit before the next major/minor tag but don't want to merge this just yet.

brew.sh: test `HOMEBREW_INSTALL_FROM_API` on developers.

---

Library/.rubocop_rspec.yml
Library/Homebrew/test/exceptions_spec.rb
Library/Homebrew/test/formula_free_port_spec.rb
Library/Homebrew/test/patching_spec.rb

-----
Another follow-up to https://github.com/Homebrew/brew/pull/14408
The cop [documentation](https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecleakyconstantdeclaration) makes a pretty compelling case for this one, and it only requires touching three test files to enable.

Enable RSpec/LeakyConstantDeclaration

---

Library/Homebrew/brew.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/dev-cmd/edit.rb
Library/Homebrew/formula_installer.rb

- flip the messaging to refer to `HOMEBREW_NO_INSTALL_FROM_API` where relevant
- remove some duplicate checks
- better scope checks to just core tap formulae
Extracted from #14412

HOMEBREW_INSTALL_FROM_API: various improvements.

---

Library/Homebrew/extend/ENV/shared.rb

`version_suffix` exists (or doesn't) depending on the GCC formula being available and not loaded from the API.

extend/ENV/shared: use `try`.

---

Library/Homebrew/Gemfile
Library/Homebrew/Gemfile.lock
Library/Homebrew/test/spec_helper.rb
Library/Homebrew/test/system_command_spec.rb

-----
Per the [suggestion](https://github.com/Homebrew/brew/pull/14419/files#r1086642346) of @MikeMcQuaid, this PR removes `rspec-wait`. The test dependency [dates](https://github.com/Homebrew/brew/pull/725/files#diff-09713da39d1e96f1440269271cc7435a3f25b835a0b21c80a34d2accbe986cc2R136) to at least 2016, but since there is now a [built-in](https://github.com/Homebrew/brew/commit/4bc174cc628010daac0a9605f0e62363042583b0) timeout mechanism, I converted the existing use of `wait` to that style instead. (I confirmed that I was able to induce a test failure with a sufficiently low `timeout` value.)

Refactor away rspec-wait

---

Library/.rubocop_rspec.yml
Library/Homebrew/test/formula_installer_bottle_spec.rb
Library/Homebrew/test/keg_spec.rb

-----
Last follow-up to https://github.com/Homebrew/brew/pull/14408 that pertains to enabling `.rubocop_rspec.yml` cops with zero-to-few violations.

Enable RSpec/NoExpectationExample

---

Library/.rubocop_rspec.yml
Library/Homebrew/test/exceptions_spec.rb
Library/Homebrew/test/formula_free_port_spec.rb
Library/Homebrew/test/patching_spec.rb

Reverts Homebrew/brew#14418
See https://github.com/Homebrew/brew/pull/14424#issuecomment-1404344739

Revert "Enable RSpec/LeakyConstantDeclaration"

---

Library/Homebrew/cmd/update.sh

- Use `HOMEBREW_CASK_REPOSITORY` more consistently
- Skip auto-updating homebrew-core for `HOMEBREW_DEVELOPER` too (without explicit `brew update`)
- Also skip auto-updating homebrew-cask

cmd/update: tweak API update behaviour.

---

Library/Homebrew/cask/artifact/stage_only.rb

This is what's passed from the JSON API.
Fixes https://github.com/Homebrew/brew/issues/14433

cask/artifact/stage_only: allow string argument.

---

Library/Homebrew/cask/cask.rb
Library/Homebrew/test/cask/cmd/list_spec.rb

This is required to support multiple languages when installing from the API. I'll open another PR to update the API loading once this gets through formulae.brew.sh.

Add `languages` to cask API

---

Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

-----
OS X Lion (10.8) was released in 2011, and support ended in 2014. Seeing as this is also 3 versions older than the oldest version of macOS (OS X El Capitan (10.11)) we support, it's time to remove this.

docs: Remove Lion reference

---

Library/Homebrew/cli/parser.rb

-----
- Fixes #14438.
- For the command `brew install --cask racket`, a user was reporting the behaviour where despite `--cask` in the command, they were getting output about the `racket` formula having been renamed:
```
$ brew install --cask racket
Warning: Use minimal-racket instead of deprecated racket
==> Downloading https://mirror.racket-lang.org/installers/8.7/racket-8.7-x86_64-macosx-cs.
==> Installing Cask racket
[...]
racket was successfully installed!
```
- The "instead of deprecated ..." messaging comes from the `TapLoader` class `formula_name_path` method, so _something_ must be assuming that everything is initially a formula before _later_ learning from further args parsing that there's a `--cask` qualifier to scope to only casks.
- There are always `@formula_options` and …

cli/parser: Don't treat args with `--cask` as formulae

---

Library/Homebrew/extend/string.rb
Library/Homebrew/global.rb
Library/Homebrew/rubocops/conflicts.rb
Library/Homebrew/rubocops/extend/formula.rb
Library/Homebrew/rubocops/formula_desc.rb
Library/Homebrew/rubocops/patches.rb

-----
This is a slight extension of https://github.com/Homebrew/brew/pull/14452
`Library/Homebrew/extend/string.rb` is just a wrapper of `active_support/core_ext/object/blank`, which is already [required](https://github.com/Homebrew/brew/blob/10845a1122b916dc91d04f00a4d8b7b888d52654/Library/Homebrew/global.rb#L15) in `global.rb`.
It's also required in a few files in `Library/Homebrew/rubocops`, but none of them appear to use `blank?`.

Remove redundant String extension

---

Library/Homebrew/brew.sh
Library/Homebrew/commands.rb

-----
Closes: https://github.com/Homebrew/brew/issues/14465 (I think)

brew.sh: add missing dev-cmd aliases

---

Library/Homebrew/version.rb

-----
The character class `[.-v]` is interpreted as all the characters between `.` and `v`, which is clearly not what is intended here.
Here's an example of what this fixes. Before:
❯ brew ruby -e 'puts Version.detect("https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0-rc1/llvm-project-16.0.0rc1.src.tar.xz")'
6.0.0rc1
After:
❯ brew ruby -e 'puts Version.detect("https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0-rc1/llvm-project-16.0.0rc1.src.tar.xz")'
16.0.0rc1
The problem here is that `1` is a match for `/[.-v]/`.
❯ brew ruby -e 'puts /[.-v]/.match("1")'
1

version: fix bad regexps in version parsers

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/brew.rb
Library/Homebrew/brew.sh
Library/Homebrew/env_config.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/os.rb
docs/Installation.md
docs/Manpage.md
manpages/brew.1

When either being in a non-default prefix or being on an unsupported macOS version we expect most things to be built from source. In that environment, do not allow `HOMEBREW_INSTALL_FROM_API` to be set.
Fixes #14475

Don't allow HOMEBREW_INSTALL_FROM_API when building from source

---

Library/Homebrew/os.rb

-----
`HOMEBREW_PREFIX` is a Pathname; `HOMEBREW_DEFAULT_PREFIX` and `HOMEBREW_MACOS_ARM_DEFAULT_PREFIX` are strings.
```rb
/u/l/Homebrew (master|✔) $ brew irb
==> Interactive Homebrew Shell
Example commands available with: `brew irb --examples`
irb(main):001:0> HOMEBREW_PREFIX
=> #<Pathname:/usr/local>
irb(main):002:0> HOMEBREW_DEFAULT_PREFIX
=> "/usr/local"          
irb(main):003:0> HOMEBREW_PREFIX == HOMEBREW_DEFAULT_PREFIX
=> false                 
irb(main):004:0> HOMEBREW_PREFIX.to_s == HOMEBREW_DEFAULT_PREFIX
=> true   
```
This became obvious to me after https://github.com/Homebrew/brew/pull/14480 got merged in and `HOMEBREW_INSTALL_FROM_API` stopped working for me. It was because the `ISSUES_URL` variable wasn't getting set and that is used in `OS.unsupported_configuration?`. …

OS: Fix supported prefix check

---

Library/Homebrew/brew.sh

Ensure that we handle this a bit more correctly so it's unset more often.

brew.sh: fix HOMEBREW_INSTALL_FROM_API logic.

---

Library/Homebrew/api.rb
Library/Homebrew/test/api/cask_spec.rb

Rather than failing every time we fail to update (breaking most usage while offline) instead only fail if we cannot obtain the JSON and we don't have a valid local file we can use.
Also tweak the timeout and retry logic and values to make a bit more sense in this context and not be so noisy when offline.
Fixes #14451
Fixes #14455
Fixes #14462
Fixes #14489

api: warn rather than fail if we've got a cached version.

---

Library/Homebrew/api.rb

Looks like this debug line (at least I'm assuming) made it through by accident.

`Homebrew::API::fetch_file_source`: remove debug line

---

Library/Homebrew/cmd/update.sh

Follow-up to #14491
Increase the max-time for the `formula.json` and `cask.json` file downloads to 10 to bring it in line with the one set in `Homebrew::API`

`update`: increase max time for API JSON updates

---

Library/Homebrew/tap.rb
Library/Homebrew/utils/tty.rb

This helps fixes problems with a fresh install on ARM Linux. When brew is relaunched with filtered PATH, it cannot find user installed Ruby.
- [ x Have you added an explanation of what your changes do and why you'd like us to include them?
-----

Making core tap install an in-process call

---

Library/Homebrew/api.rb

Follow-up to https://github.com/Homebrew/brew/pull/14491
We want to actually use the old JSON file if we're falling back. Currently, we "fall back" by returning nothing which causes `CaskLoader` to assume that the API is not a viable option and skipping to loading from taps if they're available. Instead, we want to warn and then use the old version.
I think this will help with the weird cask loading errors we've been seeing. My best theory at the moment is that they happen when the API download fails and then it accidentally falls back to the taps.
---
I think this will close https://github.com/Homebrew/brew/issues/14483

Fix JSON file download failure fallback

---

Library/Homebrew/cask/cask.rb
Library/Homebrew/cask/cask_loader.rb
Library/Homebrew/cask/installer.rb

Fixes https://github.com/Homebrew/brew/issues/14478
Fixes https://github.com/Homebrew/brew/issues/14504
This PR fixes the cask unavailable error that has appeared recently. Essentially, in cases where we don't fetch the cask source, we don't end up writing anything to the `.metadata` cask file. The `upgrade` logic requires loading the old cask from this location. This PR will write the JSON information to this location and allow that to be used to load installed casks.

Fix cask not found error when upgrading certain casks

---

completions/bash/brew

-----
1. I propose to use HOMEBREW_CACHE and HOMEBREW_REPOSITORY if they're set in the environment already in `__brew_complete_commands` function.
2. I propose to consider doing this outside of the `__brew_complete_commands` function when the script is sourced.
```
$ time for i in {1..300}; do a=${HOMEBREW_CACHE:-$(brew --cache)}; done
real    0m0.064s
user    0m0.023s
sys     0m0.039s
$ time for i in {1..300}; do a=$(brew --cache); done
real    0m10.005s
user    0m3.448s
sys     0m4.929s
```

brew Bash completions: use HOMEBREW cache and repo env vars

---

Library/Homebrew/cask/cask.rb
Library/Homebrew/cask/cask_loader.rb

This PR fixes some more issues with loading artifacts from the cask JSON API. Now, boolean values (e.g. [`sudo: true`](https://github.com/Homebrew/homebrew-cask/blob/7e620eb67d8b9f275c99a1bda878de98a56ed84c/Casks/finch.rb#L17)) are left as-is instead of being converted to strings first. This also updates the `HOMEBREW_PREFIX` replacement logic to skip replacement of the first argument (i.e. destination) of `Relocated` artifact stanzas. This is okay to do because we should never be relocating a file from outside the cask's staging directory during the install. However, other parameters (e.g. `target`) will still have the prefix replaced as usual. This fixes issues such as in [`dotnet-sdk`](https://github.com/Homebrew/homebrew-cask/blob/7e620eb67d8b9f275c99a1bda878de98a56ed84c/Casks/dotnet-s …

Don't convert boolean and blank values to strings in cask artifacts API

---

Library/Homebrew/system_config.rb

Fixes https://github.com/Homebrew/brew/issues/14508
Now, use a different method for formatting the time. Also, let's convert to UTC since that will help compare the JSON file to others cross-timezones.

Fix error when showing `brew config` JSON update time

---

Library/Homebrew/cask/cmd/upgrade.rb

Follow up to https://github.com/Homebrew/brew/pull/14506
We should show a better error message in this case. Now, it shows:
```console
$ brew upgrade --cask emacs
==> Upgrading 1 outdated package:
Error: The cask 'emacs' was not properly installed and cannot be upgraded. To fix this, run:
brew reinstall --cask --force emacs
```
I would have liked to actually fix this so no alternate command is needed, but I think that would end up being too much work and too janky so this is the second best option.

Add error message with instructions for the missing cask file

---

.github/workflows/tests.yml
Library/Homebrew/brew.sh
Library/Homebrew/cmd/formulae.sh
Library/Homebrew/cmd/update.sh
Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/env_config.rb
docs/Installation.md
docs/Manpage.md
manpages/brew.1

- remove all places we check the flag so it's a no-op now
- flip the messaging to refer to `HOMEBREW_NO_INSTALL_FROM_API` where relevant
- adjust the documentation
Do not merge until we're sure the next tag will be 4.0.0.
Fixes https://github.com/Homebrew/brew/issues/13794

HOMEBREW_INSTALL_FROM_API: make the default for everyone.

---

docs/Homebrew-Governance.md
docs/New-Maintainer-Checklist.md

These PRs were all approved by the majority of the PLC and the majority of them approved by the majority of the TSC. They are being put here for a members vote, ideally before the AGM.
- Replace some "Owners" with "billing managers" and "moderators"
- Now that GitHub has more granular roles available such as "billing managers" and "moderators": let's tighten up our security posture by only have 3 folks who need to be "Owners" rather than 10.
- Max two PLC terms
- We discussed this one year terms last year but this seems a better solution. Given we refresh maintainers, TSC and the Project Leader yearly: this seems more consistent, responsive and fair. Note this would only apply to candidates for the PLC from 2024.
- Tweak nomination rules
- Do not require any nomination: any member can run …

Homebrew-Governance: import merged PRs from homebrew-governance-private

---

Library/Homebrew/cask/cask_loader.rb

-----
The idea here is to make it easier to debug any cask loading problems in the future. We already have similar logging in place in `Formulary`.
- extend Context to get `debug?` method
- create `FromDefaultTapPathLoader` to handle expected loading option
- Note: This is a common case and it allows it to be logged as well.
- log cask loader used when --debug
Without `--debug`:
```
$ brew install -n --cask 1password
==> Would install 1 cask:
1password
```
With `--debug`:
```
$ brew install -n --cask "$(brew --repo)/Library/Taps/homebrew/homebrew-cask/casks/1password.rb" --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/casks/1password.rb
==> Would install 1 cask:
1password
```
``` …
```

Adds logging to cask loader

---

Library/Homebrew/cmd/doctor.rb

---
I'm often running `brew doctor` and want to only see output when something is wrong, so this allows passing `--quiet` to silence a successful doctor check
Before:
```console
$ brew doctor
Your system is ready to brew.
```
After:
```console
$ brew doctor -q
```

cmd/doctor: respect `--quiet`

---

Library/Homebrew/cask/cask_loader.rb

Follow-up to #14503
As pointed out by @apainintheneck, now that booleans are fixed in the JSON they're actually being converted _back_ to strings by our parser. Lets fix this by only attempting to reverse-parse elements that are already strings and leaving everything else (i.e. booleans) as-is. This shouldn't be a problem because all of the things that get pushed through `to_h_string_gsubs` will end up being a string in the JSON which means it will also go back through `from_h_string_gsubs`

Properly load booleans from the API

---

Library/Homebrew/brew.rb
Library/Homebrew/brew.sh
Library/Homebrew/commands.rb
Library/Homebrew/dev-cmd/edit.rb

This should hopefully make the developer experience much better without requiring anyone to actually set `HOMEBREW_NO_INSTALL_FROM_API`. Now, when anyone runs a command that _requires_ the taps to be checked out, we internally set `HOMEBREW_NO_INSTALL_FROM_API` which will ensure that those taps are available and (if necessary) up to date.
Fixes https://github.com/Homebrew/brew/issues/14519

Set `HOMEBREW_NO_INSTALL_FROM_API` for certain commands

---

Library/Homebrew/extend/time.rb

This was lost in #14502.
Unfortuately this method _is_ used in third-party taps so compatibility needs to be kept, or a deprecation path introduced.
Given the extremely trivial nature of supporting it, I've just restored the alias. If anyone feels strongly about deprecating, submit a PR to do so - you could maybe even move it to the mostly forgotten `compat` folder too.

extend/time: restore rfc3339 method

---

Library/Homebrew/cmd/gist-logs.rb
Library/Homebrew/utils/github/api.rb

-----
- This 404 error is from GitHub, and GitHub doesn't give us any more informations about scopes for the gist endpoint (for some reason). But we can safely assume, as it happens a lot, that "Error: Not Found" (404) is because the user hasn't granted their `HOMEBREW_GITHUB_API_TOKEN` the `gist` scope.
- Fixes https://github.com/Homebrew/brew/issues/13988.
Before:
```shell
$ HOMEBREW_GITHUB_API_TOKEN=<token_without_gist_scope> brew gist-logs -p logrotate
Error: Not Found
```
After:
```shell
❯ HOMEBREW_GITHUB_API_TOKEN=<token_without_gist_scope> brew gist-logs logrotate
Error: Your GitHub API token likely doesn't have the `gist` scope.
Create a GitHub personal access token:
https://github.com/settings/tokens/new?scopes=gist&description=Homebrew
echo 'export …
```

cmd/gist-logs: On 404, the PAT probably needs more permissions

---

Library/Homebrew/brew.sh

-----
`brew bump` relies on `livecheck`, which we don't want to query the API
for.
Also, some small refactoring:
1. Declare the list of commands we want to set
`HOMEBREW_NO_INSTALL_FROM_API` for as an array.
2. Only check against this list when the command being run is a
developer command, to avoid checking the list when we know we're not
running a dev command.

brew.sh: add `bump` to `HOMEBREW_NO_INSTALL_FROM_API` commands

---

Library/Homebrew/completions/bash.erb
completions/bash/brew

-----
* (updated) `__brewcomp_words_include()`: simplified
* (removed) `__brewcomp_prev()`: unused.
* `__brewcomp()`: 
* changed `list="${list}${s}${sep}"` to `list+="${s}${sep}"` (to speed things up)
* replaced `&& continue; action` with `|| action`

Bash completions: clean up basic functions

---

Library/Homebrew/formulary.rb

-----
Respect `HOMEBREW_BOTTLE_DOMAIN` when installing from API. This will cause downloading from `HOMEBREW_BOTTLE_DOMAIN` first when falling back to the default bottle domain if fail.

formulary: respect `HOMEBREW_BOTTLE_DOMAIN` when installing from API

---

Library/Homebrew/completions/bash.erb
completions/bash/brew

-----
* Use the `HOMEBREW_REPOSITORY` variable when it is set.
* Change `taps="${taps} ${dir}"` to `taps+=" ${dir}"`, as the latter is significantly faster.

Bash completions: speed up Tap completions

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/extend/os/dev-cmd/bottle.rb
Library/Homebrew/extend/os/linux/dev-cmd/bottle.rb
Library/Homebrew/extend/os/mac/dev-cmd/bottle.rb

-----
move methods in `dev-cmd/bottle` to extend/os because of `#todo`.

move `dev-cmd/bottle` methods to extend/os

---

Library/Homebrew/brew.sh

brew.sh: declare commands that call `auto-update` as an array

---

docs/New-Maintainer-Checklist.md

We've tweaked these and have separate ops/security vaults now so let's mention it here.

New-Maintainer-Checklist: clarify 1Password groups.

---

Library/Homebrew/utils/github.rb

-----
Probably want someone more familiar with API to make sure.
I think the list is in order from oldest run to newest run.
---
Specifically saw an issue when merging https://github.com/Homebrew/homebrew-core/pull/121077, which had 2 runs due to dropping a commit. The wrong `bottles.zip` was uploaded https://github.com/Homebrew/homebrew-core/commit/0eac6644fcca6da3664c2c7742b81bb2d38a61a8
---
Similar issue in https://github.com/Homebrew/homebrew-core/pull/116350. Due to PR getting closed and re-opened, there were 2 runs. The 1st run with only a single bottle got uploaded https://github.com/Homebrew/homebrew-core/commit/089612840765a3db2db07ef511002b6bebe3e7c8 rather than 2nd run with all bottles.
---
<details>
<summary><tt>gh api graphql</tt> example</summary>
```console
❯ gh api graphql …
```

utils/github: get artifact from last run

---

docs/Cask-Cookbook.md

-----
`version :latest` should only be used If the `url` is unversioned and there is no way to add a `livecheck`. If the `url` is unversioned and a `livecheck` is possible, a cask should still always versioned.
Also added the `:extract_plist` strategy since this is preferable to not having a version.

Tweak `version :latest` docs.

---

Library/Homebrew/api.rb
Library/Homebrew/cmd/update.sh

-----
#14516 may be caused by a slow network because the curl timeout is too short (10 seconds for 19M Bytes).
This PR export increase the JSON_API_MAX_TIME to 30 seconds, instead of #14566

increase `JSON_API_MAX_TIME`

---

Library/Homebrew/dev-cmd/bump-unversioned-casks.rb

-----
Once all casks have a `livecheck`, this command can be removed completely.
Most casks which are processed by this command currently can use the `:extract_plist` strategy instead.

Ignore livecheckable casks in `bump-unversioned-casks`.

---

Library/Homebrew/api.rb
Library/Homebrew/cmd/update.sh

Instead of forcefully killing the download after the timeout, only kill it if the speed has been < 100 bytes/s for that time period. This will cover slow connections better.
Some UX improvements very much worth making after this (separate PRs):
* Display progress bar if download is taking a while
* Option to disable the Ruby download (so `brew update` only) so that brew is at least usable on slow/patchy connections.

Use --speed-time over --max-time for API downloads

---

Library/Homebrew/env_config.rb
bin/brew
docs/Manpage.md
manpages/brew.1

-----
`HOMEBREW_BAT_CONFIG_PATH` should respect [`BAT_CONFIG_PATH`](https://github.com/sharkdp/bat#configuration-file), in the same way that `HOMEBREW_BAT_THEME` [reflects](https://github.com/Homebrew/brew/pull/13385/files#diff-a8ebbe0466e56bdb9c7ebc74d5ffbd383b8c0902fcb5146cb1960e3d69dadeb1R78) `BAT_THEME`.
Previous, for context:
https://github.com/Homebrew/brew/pull/7488
https://github.com/Homebrew/brew/pull/11975
https://github.com/Homebrew/brew/pull/13385

Fix `HOMEBREW_BAT_CONFIG_PATH`

---

Library/Homebrew/dev-cmd/cat.rb

-----
"cat" is short for "concatenate" (and not "dump to stdout"), so it seems
a little silly for `brew cat` to not be able to concatenate
formulae/casks.
Let's fix that.

dev-cmd/cat: accept multiple formula/cask arguments

---

Library/Homebrew/utils/github.rb

-----
Fixes #14582
With fine-granted PATs, we cannot search both PRs and issues so I fix fetch_pull_requests to search only pullrequests.
I confirmed #14582 is fixed. `brew bump-formula-pr anatawa12/core/vrc-get --url https://github.com/anatawa12/vrc-get/archive/0.1.7.tar.gz --no-fork --force` works well in my env.
I think it's impossible to write tests without PATs. How should I write tests?
-----
brew tests failires:
```
Failures:
1) pkg-config returns the correct version for libcurl
Failure/Error: expect(pc_version("libcurl")).to eq(version)
expected: "7.85.0"
got: "7.84.0"
(compared using ==)
2) pkg-config returns the correct version for sqlite3
Failure/Error: expect(pc_version("sqlite3")).to eq(version)
expected: "3.39.5"
got: "3.39.4"
(compared using ==)
Finished in 28.57 seconds …
```

fix(utils/github): failure with fine-granted api tokens

---

Library/Homebrew/api.rb
Library/Homebrew/brew.sh
Library/Homebrew/cmd/update.sh

This avoids duplication and potentially allows it to be used for various other `curl` calls.

brew.sh: move shared curl speed limit settings here.

---

Library/Homebrew/api.rb
Library/Homebrew/brew.sh
Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

This sets the default and allows customising how often we try to download files from the API.
This does not affect `brew update` as we want to always check every time on an explicit call.
@Bo98 @Rylan12 @carlocab Feel free to push directly to this PR and merge as desired. I will be unlikely to be able to make any more code changes here until Monday and would like to land this (or something like it) as soon as possible before then to allow it to bake.

Add HOMEBREW_API_AUTO_UPDATE_SECS

---

Library/Homebrew/dev-cmd/edit.rb
Library/Homebrew/utils.rb

-----
When you don't have `EDITOR` or `HOMEBREW_EDITOR` configured `brew edit` printed a double warning.
This silences the first of those.
```
/u/l/Homebrew (master|✔) $ brew edit
Warning: Using code because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR,
or HOMEBREW_EDITOR to your preferred text editor.
Editing /usr/local/Homebrew
Warning: Using code because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR,
or HOMEBREW_EDITOR to your preferred text editor.
/u/l/Homebrew (stop-double-warning-in-edit|✔) $ brew edit
Editing /usr/local/Homebrew
Warning: Using code because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR,
or HOMEBREW_EDITOR …
```

cmd/edit: stop double warning

---

Library/Homebrew/formula_creator.rb

-----
Similar to CMake changes. This uses Meson's standard workflow which we have started to use in core formulae.

formula_creator: use tool-agnostic meson commands

---

Library/Homebrew/api.rb
Library/Homebrew/cask/cask.rb
Library/Homebrew/cask/cask_loader.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/formula.rb
Library/Homebrew/formulary.rb
Library/Homebrew/test/formula_spec.rb
completions/zsh/_brew

We should allow `brew info --json=v2` even without the taps installed. We can just pass the downloaded JSON file along without needing to regerate the data using `#to_h` on the formulae and casks. I've tested this locally without homebrew/core or homebrew/cask and it seems to work with an without `--variations`, with `--installed`, and with `--all --eval-all`.
One thing to note: when you run `brew info --json` it will merge in the correct OS variations which I think makes the most sense since someone running that command probably cares about what's currently on their system. `brew info --json --variations`, however, will return the complete with-variations JSON file. This is consistent with the way things work with `HOMEBREW_NO_INSTALL_FROM_API`.
Also, while we're at it, let's fully …

Allow `brew info --json=v2` without taps with JSON API

---

Library/Homebrew/completions/bash.erb
completions/bash/brew

-----
Use HOMEBREW_CELLAR if it is set instead of always calling `brew --cellar`.

Bash completions: use HOMEBREW_CELLAR, if set

---

Library/Homebrew/cask/cask.rb

This is a partial fix for #14595. It doesn't cover `android-commandlinetools`, but that's the only instance I can find that would still be affected.
This will fix all the other cases, like `android-platform-tools`. A partial fix is worthwhile because there are some popular casks affected (`android-platform-tools` averages 500 installs a day), and is lower risk of causing any other issues (a full fix is likely something much more substantial, such as evaluating a cask source with a fake prefix).

cask: replace Caskroom in API for relocated artifacts

---

Library/Homebrew/livecheck/livecheck_version.rb
Library/Homebrew/test/livecheck/livecheck_version_spec.rb

-----
Some leftover Cask colon versioning.

livecheck_version: only split on commas in cask version

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/brew.sh
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/env_config.rb
Library/Homebrew/extend/os/mac/tap.rb
Library/Homebrew/tap.rb

Don't automatically tap these when running a developer command that's not using the API.
Fixes #14606

Improve homebrew/{core,cask} autotapping.

---

Library/Homebrew/formula.rb

Very simple and obvious fix for https://formulae.brew.sh/formula/gcc@5 outputting a requirement of:
> Maximum_maximum_maximum_maximum_maximum_maximum_maximum_maximum_maximum_maximum_maximum_maximum_maximum_macos <= 10.13 (build)

formula: fix `to_hash` tampering with requirement names

---

Library/Homebrew/formulary.rb
Library/Homebrew/test/formulary_spec.rb

I initially thought #14535 to be a weird thing with the Cocoapods formula, but it actually has far greater scope than anticipated. Even with the `on_arm` stuff removed, any macOS prior to `since` still didn't work properly.
The cause was our dependency deduplication going on here. There is nothing to deduplicate on macOS however (`uses_from_macos` is no-op and we don't pass `since` as we do variations instead) so the fix is trivial: don't try to deduplicate on macOS!
Test included.
Fixes #14535.

formulary: fix uses_from_macos handling on macOS

---

Library/Homebrew/api.rb
Library/Homebrew/api/analytics.rb
Library/Homebrew/api/cask.rb
Library/Homebrew/api/formula.rb
Library/Homebrew/env_config.rbi

-----
This enables typing for all the files that I could find under `Homebrew::API`

Enabling typing in Homebrew::API module

---

Library/Homebrew/dev-cmd/contributions.rb

-----
- Part of #13642.
- `BrewTestBot` adds `Signed-off-by` for who approved PRs (https://github.com/Homebrew/brew/blob/1cf53b4281e7bc22a8d7fc915fc6ba4576f8ef88/Library/Homebrew/dev-cmd/pr-pull.rb#L91-L93).
- Let's count these too, at least until we can get PR approvals from the GitHub API.

dev-cmd/contributions: Count commit signoffs, too
