- Library/Homebrew/os.rb
-----
Allow either default prefix on macOS arm64.
> Also show issues URL on macOS arm64

- Library/Homebrew/linkage_checker.rb
-----
The linkage check currently does nothing to check the validity of
variable-referenced libraries (prefixed with an `@`).
We could rectify that by mimicking the dynamic linker in looking up the
variable-referenced library, but this could get quite complicated.
Instead, let's let the linker do the hard work by checking if we can
`dlopen` libraries and bundles that contain variable linkage. The
`dlopen` will fail if the linker cannot resolve the variable reference.
There are at least two disadvantages to this approach relative to the
alternative suggested above:
1. This doesn't work for binary executables.
2. This doesn't identify which variable references are broken.
It's still better than not checking them at all, which is what we do
currently, and saves us from having to carry around …
> linkage_checker: check variable references with dlopen

- docs/Acceptable-Formulae.md
> docs/Acceptable-Formulae: specify the list of supported platforms

- Library/Homebrew/dev-cmd/tap-new.rb
> tap-new: add `--github-packages` switch

- Library/Homebrew/cli/named_args.rb
- Library/Homebrew/cmd/migrate.rb
- Library/Homebrew/uninstall.rb
-----
```sh-session
> git checkout master
> brew migrate ark
Warning: Use velero instead of deprecated ark
Error: No such keg: /usr/local/Cellar/velero
> git checkout migrate
> brew migrate ark
Error: No such keg: /usr/local/Cellar/ark
```
> Print given argument instead of rename if matching keg not found

- docs/FAQ.md
> FAQ: document `HOMEBREW_NO_CLEANUP_FORMULAE`

- Library/Homebrew/formula.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/service.rb
- Library/Homebrew/test/formula_installer_spec.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/test/service_spec.rb
-----
Allows brew to generate systemd unit timers
> service: add timer support for systemd

- Library/Homebrew/upgrade.rb
Fixes Homebrew/discussions#2567.
> upgrade: fix undefined method error

- docs/.mdl_ruleset.rb
- docs/.mdl_style.rb
- docs/.mdlrc
- docs/Adding-Software-to-Homebrew.md
- docs/Common-Issues.md
- docs/External-Commands.md
- docs/FAQ.md
- docs/Gemfile
- docs/Gemfile.lock
- docs/Gems,-Eggs-and-Perl-Modules.md
- docs/Homebrew-and-Python.md
- docs/Homebrew-on-Linux.md
- docs/Installation.md
- docs/Rakefile
- docs/Shell-Completion.md
- docs/Troubleshooting.md
- docs/Xcode.md
-----
The second instalment of a rework of the docs. Includes adding the `mdl` gem for Markdown linting, which can be added to CI once the remaining .md files are completed.
> Docs: updates for section 1, add mdl files

- README.md
- docs/New-Maintainer-Checklist.md
We're moving to OpenCollective currently.
> Remove some SFC references.

- Library/Homebrew/formula_auditor.rb
> formula_auditor: fix error with formulae without taps

- SECURITY.md
> Formatting consistency.

- Library/Homebrew/.rubocop.yml
- Library/Homebrew/cmd/install.rb
- Library/Homebrew/cmd/tap.rb
- Library/Homebrew/dev-cmd/pr-automerge.rb
- Library/Homebrew/dev-cmd/pr-publish.rb
- completions/bash/brew
- completions/fish/brew.fish
- completions/zsh/_brew
- docs/Manpage.md
- docs/Releases.md
- manpages/brew.1
> Fix disabled args appearing in documentation.

- docs/Common-Issues.md
> docs/Common-Issues.md: fix variable notation

- Library/Homebrew/cli/args.rbi
- Library/Homebrew/dev-cmd/bump-revision.rb
- Library/Homebrew/test/utils/ast/formula_ast_spec.rb
- Library/Homebrew/utils/ast.rb
-----
I've added an option to `bump-revision` to completely remove a bottle block after bumping. If bumping to invalidate a previous version of the formula so that it will build from source, the out-of-date bottle block will cause errors since https://github.com/Homebrew/brew/pull/10640 was merged.
~~I've opened this as a draft pull request, since the `remove_stanza` method that I added to `utils/ast` leaves trailing whitespace behind (see the `brew style` complaint about the unit test that I added). I recently used this branch to remove bottles from 36 formulae in https://github.com/osrf/homebrew-simulation/pull/1742, and I used `brew style --fix osrf/simulation` before each commit due to the trailing whitespace. Does anyone have suggestions about how to fix this in `utils/ast`?~~
An …
> bump-revision: add --remove-bottle-block option

- Library/Homebrew/brew.sh
> brew.sh: tweak lsb_release parameters.

- Library/Homebrew/cmd/cleanup.rb
- completions/fish/brew.fish
- completions/zsh/_brew
- docs/Manpage.md
- manpages/brew.1
> cmd/cleanup.rb: description style tweak

- Library/Homebrew/style.rb
-----
Fixes #12662.
See https://github.com/Homebrew/brew/issues/12662#issuecomment-1004112403 for more details.
> style: use short flags for `patch` command for compatibility

- docs/Adding-Software-to-Homebrew.md
- docs/How-To-Open-a-Homebrew-Pull-Request.md
- docs/Updating-Software-in-Homebrew.md
-----
Replaces https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md and finishes migrating cask docs to the general Homebrew docs.
CC @Homebrew/cask
> docs: document how to add/update casks

- Library/Homebrew/install.rb
> install: respect pins when auto-upgrading

- Library/Homebrew/formula.rb
-----
This is the log file generated when using `meson`.
> formula: also capture `meson-log.txt`

- Library/Homebrew/cleanup.rb
Fixes https://github.com/Homebrew/brew/issues/11641
> cleanup: check if symlinks are readable.

- Library/Homebrew/sandbox.rb
> sandbox: handle SIGTTOU and SIGTTIN to avoid hangs

- Library/Homebrew/rubocops/homepage.rb
> Fix for GitHub url ends with ‘.git’ check 

- Library/Homebrew/cask/exceptions.rb
> cask/exceptions: fix reinstall cask messaging.

- Library/Homebrew/os/mac/xcode.rb
> os/mac/xcode: support Xcode 13.2.1

- .github/ISSUE_TEMPLATE/config.yml
We get a fair few installation bugs filed on this repository so hopefully this will redirect them.
> ISSUE_TEMPLATE/config: add Homebrew/install.

- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/test/dev-cmd/audit_spec.rb
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>
-----
> formula_auditor: new formulas should not define a revision

- Library/Homebrew/cask_dependent.rb
- Library/Homebrew/dependency.rb
- Library/Homebrew/installed_dependents.rb
-----
closes https://github.com/Homebrew/brew/issues/12749
> ignore dependencies of build-time-dependency

- docs/Cask-Cookbook.md
-----
Add `monterey` to the list of available macOS release symbols.
> docs/Cask-Cookbook.md: add macOS release symbol

- Library/Homebrew/brew.sh
- Library/Homebrew/development_tools.rb
- Library/Homebrew/extend/os/mac/development_tools.rb
> debian7: force usage of brewed ca-certificates

- Library/Homebrew/dev-cmd/bottle.rb
-----
delete `bottle` `"prefix"` key because of the comment.
> delete bottle deprecate key

- Library/Homebrew/os/mac/xcode.rb
> os/mac/xcode: support Xcode 13.3

- docs/Homebrew-Governance.md
-----
- I tried to set up the Project Leader election in OpaVote and couldn't find "Schultz Condorcet" in the list of methods. Let's save the next person who does this a click by specifying its alternative name that _is_ in OpaVote, "beatpath".
> docs/Homebrew-Governance: Schultz Condorcet aka Beatpath

- Library/Homebrew/cmd/list.rb
-----
Add support for long listing of casks with `brew list --cask -l`, full Caskroom path listings with `brew list --cask -v`, and include cask versions when running `brew list --versions`.
> list: support long, verbose and version listing of casks

- README.md
Point to organisation discussions instead.
> README: update discussions.

- Library/Homebrew/dev-cmd/audit.rb
> dev-cmd/audit: fix error with --installed

- Library/Homebrew/download_strategy.rb
Fixes Homebrew/homebrew-cask#121725.
> download_strategy: strip query string from basename

- Library/Homebrew/formula_installer.rb
- Library/Homebrew/keg_relocate.rb
- Library/Homebrew/software_spec.rb
- Library/Homebrew/test/keg_relocate/binary_relocation_spec.rb
> Binary patching of build prefixes

- Library/Homebrew/dev-cmd/tests.rb
-----
This option allows the user to run tests on only the files that have been changed in comparison with the master branch. It slots in between the `brew tests` and `brew tests --only=filename` dev commands.
Resolves #13146.
> Added --changed option to "brew tests" dev cmd

- Library/Homebrew/dev-cmd/pr-automerge.rb
> pr-automerge: allow users to specify a workflow for pr-publish

- .github/workflows/docker.yml
- Dockerfile
-----
As recently proposed on Slack. Let's build our image on Jammy too.
> workflows/docker: add 22.04

- Library/Homebrew/rubocops/uses_from_macos.rb
-----
https://github.com/Homebrew/homebrew-core/pull/99367
> uses_from_macos: allow libxcrypt

- Library/Homebrew/formula_installer.rb
> formula_installer: add check for HOMEBREW_RELOCATE_BUILD_PREFIX

- Library/Homebrew/cmd/info.rb
> cmd/info: use `Formula.all`

- Library/Homebrew/cmd/update.sh
- Library/Homebrew/test/completions_spec.rb
> Document the `--quiet` flag on `brew update`

- Library/Homebrew/github_packages.rb
> github_packages: add comment for image-spec pin

- Library/Homebrew/os/mac/sdk.rb
Fixes https://github.com/orgs/Homebrew/discussions/3238.
We don't support modified Xcode versions, but I will however agree that adjusting the logic as so makes more sense.
> os/mac/sdk: use unversioned SDK if matching version isn't found

- Library/Homebrew/livecheck/livecheck.rb
Fixes an issue where some host checks could be tricked due to the use of `host.ends_with?`. This is a bug, but it is not a security issue.
Fixes https://github.com/Homebrew/brew/security/code-scanning/1.
> livecheck: improve host checks to instead check domains

- Library/Homebrew/os/mac/xcode.rb
> os/mac/xcode: support Xcode 13.4

- Library/Homebrew/cli/named_args.rb
Need to ensure we're using the installed caskfile when it's requested and readable.
Follow-up from https://github.com/Homebrew/brew/pull/13289 addressing https://github.com/Homebrew/brew/pull/13289#discussion_r884853652
> named_args: better handle keg-like casks.

- Library/Homebrew/livecheck/strategy/sparkle.rb
- Library/Homebrew/test/livecheck/strategy/sparkle_spec.rb
-----
It's sometimes necessary to work with all the items in a Sparkle feed to be able to correctly identify the newest version (e.g., https://github.com/Homebrew/homebrew-cask/pull/124613#issuecomment-1142363624) but livecheck's `Sparkle` strategy only passes the `item` it views as newest into a `strategy` block.
This PR updates the `Sparkle` strategy to optionally pass all items into a `strategy` block, so we can manipulate them (e.g., filtering, sorting). This is enabled by naming the first argument of the strategy block `items` instead of `item`. `Sparkle` `strategy` blocks where the first argument is `item` will continue to work as expected.
This necessarily updates `#item_from_content` (now `items_from_content`) to return all items. I've decided to move the sorting out of …
> Sparkle: Pass all items into strategy block

- Library/Homebrew/software_spec.rb
> software_spec: handle nil manifests_annotations.

- docs/Formula-Cookbook.md
> Document missing shell `_function` and `_completion` variables

- Library/Homebrew/dev-cmd/cat.rb
- Library/Homebrew/env_config.rb
- bin/brew
- docs/Manpage.md
- manpages/brew.1
> dev-cmd/cat: support setting bat theme via environment variable

- Library/Homebrew/os/mac/version.rb
- Library/Homebrew/requirements/macos_requirement.rb
As of 3.5.0, it's no longer possible to run Homebrew there.
> os/mac/version: remove Yosemite.

- Library/Homebrew/extend/os/mac/diagnostic.rb
- Library/Homebrew/os/mac/pkgconfig/13/expat.pc
- Library/Homebrew/os/mac/pkgconfig/13/libcurl.pc
- Library/Homebrew/os/mac/pkgconfig/13/libedit.pc
- Library/Homebrew/os/mac/pkgconfig/13/libexslt.pc
- Library/Homebrew/os/mac/pkgconfig/13/libffi.pc
- Library/Homebrew/os/mac/pkgconfig/13/libxml-2.0.pc
- Library/Homebrew/os/mac/pkgconfig/13/libxslt.pc
- Library/Homebrew/os/mac/pkgconfig/13/ncurses.pc
- Library/Homebrew/os/mac/pkgconfig/13/ncursesw.pc
- Library/Homebrew/os/mac/pkgconfig/13/sqlite3.pc
- Library/Homebrew/os/mac/pkgconfig/13/uuid.pc
- Library/Homebrew/os/mac/pkgconfig/13/zlib.pc
- Library/Homebrew/os/mac/version.rb
- Library/Homebrew/os/mac/xcode.rb
- Library/Homebrew/test/os/mac/pkgconfig_spec.rb
- Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.ventura.bottle.tar.gz
> Preliminary macOS 13 (Ventura) support

- Library/Homebrew/language/node.rb
> language/node: also strip postpack

- Library/Homebrew/utils/shfmt.sh
-----
Make `brew style --fix *.sh` work for in-place fixing. See also #13290.
> utils/shfmt.sh: allow long shfmt arguments

- Library/Homebrew/utils/ruby.sh
- Library/Homebrew/utils/ruby_check_version_script.rb
-----
This should allow some testing with ruby 2.7 before macOS actually switches.
> utils: allow developers to differ in ruby versions

- Library/Homebrew/dev-cmd/bottle.rb
> bottle.rb: make GCC relocatable again

- bin/brew
Fixes https://github.com/Homebrew/brew/issues/13548
> bin/brew: never use HOMEBREW_PATH from users.

- bin/brew
It has been more than a few days.
> bin/brew: remove GITHUB_ACTIONS_HOMEBREW_MACOS_SELF_HOSTED.

- Library/Homebrew/dev-cmd/pr-pull.rb
- Library/Homebrew/utils/github.rb
> github/pr-pull: fix/improve parameters

- Library/Homebrew/dev-cmd/pr-pull.rb
https://github.com/Homebrew/homebrew-core/pull/106755#issuecomment-1206460655
> pr-pull: fix PRs conflicting with themselves

- Library/Homebrew/cleanup.rb
- Library/Homebrew/cmd/install.rb
- Library/Homebrew/cmd/reinstall.rb
- Library/Homebrew/cmd/upgrade.rb
-----
This makes `brew install` and co. run the monthly automatic cleanup ~before any formulae~ after all packages are installed so that there isn't a wall of text in the middle of the install/upgrade output.
> Run periodic cleanup after installing all packages

- Library/Homebrew/cask/cask.rb
- Library/Homebrew/cask/cask_loader.rb
-----
Closes https://github.com/Homebrew/brew/issues/13628
> check whether token is multiple tap's name

- Library/Homebrew/language/python.rb
- Library/Homebrew/test/language/python/shebang_spec.rb
-----
Needed for Homebrew/homebrew-core#107517.
> language/python: use versioned Python name in `detected_python_shebang`

- Library/Homebrew/cask/cmd/info.rb
- Library/Homebrew/cmd/info.rb
- Library/Homebrew/test/cask/cmd/info_spec.rb
- Library/Homebrew/test/missing_formula_spec.rb
- Library/Homebrew/utils.rb
> info: highlight package name

- Library/Homebrew/build_environment.rb
- Library/Homebrew/cmd/--env.rb
- Library/Homebrew/exceptions.rb
- Library/Homebrew/formula.rb
-----
Fixes the issue reported after https://github.com/Homebrew/brew/pull/13623
> build_environment: add proper types to dump() and fix inreplace error

- Library/Homebrew/cask/audit.rb
-----
Fixes the audit being run on all artifacts instead of only the selected.
> Cask: fix signing audit checking all artifacts

- Library/Homebrew/formula.rb
> Fix caching in Formula#runtime_installed_formula_dependents

- Library/Homebrew/Gemfile
Hopefully will aid Dependabot.
> Gemfile: stricter Ruby version requirement

- Library/Homebrew/cleanup.rb
-----
This is related to #13729 but as @carlocab already mentioned that specific bug might be caused by something else. Either way it got me to reevaluate some of the autoremove logic and I found a bug related to `HOMEBREW_NO_CLEANUP_FORMULAE`.
Essentially what was happening was we were only ignoring the formulae listed in `HOMEBREW_NO_CLEANUP_FORMULAE` but not their dependencies. This PR changes the logic to ignore all of that.
For example, I have `ghostscript` installed. I modified the tab file to indicate that it wasn't installed on request. That would normally make it and its dependencies candidates for `autoremove` as you can see below.
```shell
$ brew autoremove --dry-run
==> Would autoremove 10 unneeded formulae:
fontconfig
freetype
ghostscript
jbig2dec
jpeg-turbo
libidn
libpng …
```
> Ignore HOMEBREW_NO_CLEANUP_FORMULAE deps in `brew autoremove`

- bin/brew
It's been deprecated for a long time. Add a disabling message to be nice (that we'll remove in future).
---
This should probably wait for the next major/minor release, to be a bit nicer.
> bin/brew: remove HOMEBREW_NO_ENV_FILTERING.

- README.md
> README: add Mercedes-Benz Group.

- Library/Homebrew/cask/dsl/version.rb
- Library/Homebrew/compat/cask.rb
- Library/Homebrew/compat/formula.rb
- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/dev-cmd/pr-upload.rb
The next release will be 3.6.0.
> Remove odisabled for 3.6.0

- Library/Homebrew/compilers.rb
- Library/Homebrew/dependency_collector.rb
- Library/Homebrew/development_tools.rb
- Library/Homebrew/extend/os/linux/compilers.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/github_packages.rb
- Library/Homebrew/keg_relocate.rb
- Library/Homebrew/os.rb
- Library/Homebrew/test/compiler_selector_spec.rb
- Library/Homebrew/test/formula_spec.rb
- docs/Linux-CI.md
Extracted from https://github.com/Homebrew/brew/pull/13577
Let's merge this first to slim the diff on https://github.com/Homebrew/brew/pull/13577
> glibc related cleanup

- Library/Homebrew/formula.rb
- Library/Homebrew/tap.rb
- Library/Homebrew/test/formula_spec.rb
`brew audit` is really slow. Trying to optimise that here.
> formula: try optimise `versioned_formulae_names`

- Library/Homebrew/cask/audit.rb
-----
If an app is unsigned, the signature check should not fail.
> Improve error message for failed signature check.

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/cask/auditor.rb
- Library/Homebrew/test/cask/audit_spec.rb
-----
This puts the cask audits more in line with formula and allows us to select a single one at a time later.
> Cask: automatically add cask audits

- Library/Homebrew/extend/os/linux/dependency_collector.rb
- Library/Homebrew/extend/os/linux/formula.rb
- Add more early return checks
- Move to a recursive approach for more readability and avoiding a counter that we need to bump
- Perform more caching
- Keep class variable usage isolated into specific methods
> extend/os/linux: improve glibc, gcc dependency handling.

- Library/Homebrew/utils/ruby.sh
Otherwise it just picks up from `/usr/bin/ruby` all the time.
> util/ruby.sh: fix HOMEBREW_USE_RUBY_FROM_PATH to actually use user's PATH

- Library/Homebrew/resource.rb
https://github.com/Homebrew/brew/pull/13791#pullrequestreview-1093863890
> resource: style tweak

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
Fixes https://github.com/Homebrew/brew/issues/13773
This PR cleans up the handling of multiple hashes for bumping casks. Here is the approach that I've taken: first, check if the current hash is `:no_check`. If it's not, go through each arch/language configuration one at a time (e.g. Intel en, ARM en, Intel fr, ARM fr) to find the new hash values and add them to the replacement pairs. Then, we use `.uniq` on the replacement pairs to remove duplicates before applying each replacement. I think this is a simpler way to handle both arch and language differences in the same place.
> bump-cask-pr: cleanup handling of multiple hashes

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/cask/auditor.rb
- Library/Homebrew/test/cask/audit_spec.rb
Reverts Homebrew/brew#13746
CI is broken consistently on `master` and in PRs.
> Revert "Cask: automatically add cask audits"

- Library/Homebrew/cmd/fetch.rb
-----
This makes the code substantially easier to understand. Follow-up to #13807.
> cmd/fetch: rename `fetch_failed` to `fetch_tries`.

- Library/Homebrew/brew.rb
- Library/Homebrew/brew.sh
Needed for Ubuntu 22.04.
Companion to https://github.com/Homebrew/actions/pull/305
Perhaps needed for https://github.com/Homebrew/homebrew-core/pull/108590
> brew: improve Docker detection.

- .github/workflows/sponsors-maintainers-man-completions.yml
- Library/Homebrew/dev-cmd/update-sponsors.rb
- Library/Homebrew/utils/github.rb
- README.md
- fix name
- use correct command
Used the wrong branch format last PR so couldn't test inline there
> sponsors-maintainers-man-completions: various fixes.

- Library/Homebrew/formula_auditor.rb
-----
Fixes Homebrew/homebrew-core#110178.
> formula_auditor: fix false positive in `audit_gcc_dependency`.

- Library/Homebrew/dev-cmd/audit.rb
-----
This should avoid situations like in https://github.com/Homebrew/homebrew-core/pull/111680
> Audit: complain if no targets are found

- docs/Brew-Livecheck.md
#
This PR aims to update the documentation for `brew livecheck` (after https://github.com/Homebrew/brew/pull/13613 is merged).
@samford and @nandahkrishna, kindly have a look and let me know if we need to update some other documentation as well.
> Update documentation for `brew livecheck`

- Library/Homebrew/service.rb
- Library/Homebrew/test/service_spec.rb
-----
Should fix https://github.com/Homebrew/homebrew-services/issues/508
> service: use default.target on Linux

- Library/Homebrew/extend/os/mac/keg.rb
-----
This should fix #13903. I don't have an ARM machine at the moment so would appreciate some more eyes on this. Regarding test coverage, I'm not sure this is currently covered by existing tests. If we do want to add tests for this change, I'd be happy to add some if someone can point me to where/which file the tests should be added in.
> extend/os/mac: ensure writable file for codesign

- Library/Homebrew/os/mac/pkgconfig/13/expat.pc
- Library/Homebrew/os/mac/pkgconfig/13/libcurl.pc
- Library/Homebrew/os/mac/pkgconfig/13/libexslt.pc
- Library/Homebrew/os/mac/pkgconfig/13/libxslt.pc
- Library/Homebrew/os/mac/pkgconfig/13/sqlite3.pc
Will check again with RC but I don't expect much changes.
> os/mac/pkgconfig/13: update for beta 9 SDK

- Library/Homebrew/brew.rb
- Library/Homebrew/diagnostic.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formula_installer.rb
- docs/Homebrew-on-Linux.md
- docs/Installation.md
We're still getting a non-trivial number of issues from configurations we don't support and don't plan to.
Let people know that we know their experience will not be good and what to expect if they file issues.
> Strengthen "don't create issues" language

- Library/Homebrew/extend/os/mac/diagnostic.rb
- Library/Homebrew/os/mac.rb
- Library/Homebrew/os/mac/xcode.rb
Will bump Monterey to Xcode 14.1 after stable release.
> Ventura RC version bumps

- docs/Installation.md
> docs: Fix minor version typo

- Library/Homebrew/cask/cask_loader.rb
-----
I've taken an interest in speeding up large `brew info` dumps (for my GUI client again).
Profiling with `time brew prof --stackprof -- info --json=v2 --eval-all`, I found:
- `Cask#os_versions` took up a large portion of the total time
- Cask processing took 49% overall when the [`"versions"` key was evaluated](https://github.com/Homebrew/brew/blob/560f5717ad4dc1e3feed9f3c0b7c84aa1498b84c/Library/Homebrew/cask/cask.rb#L239), compared to 12% when skipped (by commenting it out)
-  `CaskLoader.for` took up [about 45% of the cask processing time](https://user-images.githubusercontent.com/16456186/198201309-1d5e9646-f0b9-416e-b661-2b80a4ef1a01.png)
- This is time spent determining how to load the cask, not actually loading it
- `FromURILoader.can_load?` and `FromContentLoader.can_load?` …
> Improve performance of `brew info` by caching compiled regexes

- .devcontainer/devcontainer.json
- .devcontainer/on-create-command.sh
- .devcontainer/ubuntu18.04/devcontainer.json
- .gitignore
Should be useful for getting a development environment setup quickly.
> Add VSCode devcontainers

- .devcontainer/on-create-command.sh
- fix permissions
- install more gems/formulae
- remove system shellcheck that won't be used
> devcontainer/on-create-command: do more stuff.

- .devcontainer/on-create-command.sh
This doesn't take any longer and nice to have it cached.
> devcontainer/on-create-command: install Sorbet.

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/cask/dsl/depends_on.rb
> fix: allow sparkle without a macOS version

- Library/Homebrew/cask/audit.rb
> Fix: Sparkle audit prior to el_capitan

- docs/Acceptable-Casks.md
- docs/Cask-Cookbook.md
> docs: Bump various OS versions

- Library/Homebrew/PATH.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/linuxbrew-core-migration.rb
> minor typo fixes

- Library/Homebrew/formula.rb
- Library/Homebrew/service.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/test/service_spec.rb
> Service: add method to define a root requirement

- Library/Homebrew/dev-cmd/generate-man-completions.rb
- Library/Homebrew/dev-cmd/update-maintainers.rb
- Library/Homebrew/manpages.rb
- Library/Homebrew/manpages.rbi
-----
- add `manpages.rb`
- move several methods from `dev-cmd/generate-man-completions.rb` to `manpages.rb`
> Add manpages.rb

- .devcontainer/on-create-command.sh
- .github/workflows/tests.yml
- Library/Homebrew/dev-cmd/tests.rb
- Library/Homebrew/development_tools.rb
- Library/Homebrew/extend/os/linux/dependency_collector.rb
- Library/Homebrew/extend/os/linux/development_tools.rb
- Library/Homebrew/extend/os/linux/formula.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/tap.rb
- Library/Homebrew/test/caveats_spec.rb
- Library/Homebrew/test/cmd/tap-info_spec.rb
- Library/Homebrew/test/dev-cmd/audit_spec.rb
- Library/Homebrew/test/formula_installer_bottle_spec.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/test/formulary_spec.rb
- Library/Homebrew/test/installed_dependents_spec.rb
- Library/Homebrew/test/language/perl/shebang_spec.rb
- Library/Homebrew/test/language/python/shebang_spec.rb
- Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
- Library/Homebrew/test/tab_spec.rb
- Library/Homebrew/test/tap_spec.rb
This will need some fixes before it can be merged.
Feel free to push to this PR!
> tests: test on Ubuntu 18.04.

- .devcontainer/on-create-command.sh
- Library/Homebrew/style.rb
We were missing a few here so add them. Also, fix the changes in `on-create-command.sh` that this catches.
> style: check more shell scripts.

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature.yml
We get a non-trivial number of issues on Homebrew/brew that either:
- ignore `brew doctor` checkboxes
- are for a specific formula only
Let's try to direct these cases for people to do the right thing.
> Improve issue templates

- Library/Homebrew/env_config.rb
- docs/Manpage.md
- manpages/brew.1
-----
Had some issues fixing the previous PR, so opening a new one. Thank you @EricFromCanada for the advice on doing this the right way!
> docs: Fix env variable typo

- Library/Homebrew/cache_store.rb
- Library/Homebrew/formula.rb
-----
Should restore generation of https://rubydoc.brew.sh/Formula.
> rubydoc: fixes for output

- docs/Cask-Cookbook.md
- docs/Formula-Cookbook.md
-----
The next instalment of a rework of the docs. Note the added sections for syntax that's been recently added and updates for links to examples within `homebrew/core`.
> Docs: update Cookbooks

- Library/Homebrew/dev-cmd/unbottled.rb
- Library/Homebrew/hardware.rb
Minimally tested but seems to work.
> dev-cmd/unbottled: simulate target tag

- README.md
-----
- This was launched yesterday, we were early adopters. I (independently, zero pressure from my employer) think there's benefit in a centralized vulnerability reporting mechanism that's closer to the code and easier for researchers to find.
> README: Switch from HackerOne to GitHub for vulnerability reporting

- Library/Homebrew/.rubocop_todo.yml
-----
- What it says on the tin.
> rubocop_todo: Clean up deleted paths & excludes without offenses

- .github/workflows/doctor.yml
-----
This workflow hasn't been set up to run on our ephemeral runners. Let's
fix that.
> workflows/doctor: use ephemeral runners

- .github/workflows/doctor.yml
-----
Based on discussion from #14172.
I'm not sure if this works, but CI should tell us.
> workflows/doctor: skip unnecessary steps

- Dockerfile
I've used this with success in an update to `setup-homebrew` I've been working on to support GitHub file commands, so let's try it.
Package is very light. A couple of binaries and a library.
> Dockerfile: install acl

- docs/Adding-Software-to-Homebrew.md
- docs/Brew-Test-Bot-For-Core-Contributors.md
- docs/Common-Issues-for-Core-Contributors.md
- docs/Common-Issues.md
- docs/External-Commands.md
- docs/Formula-Cookbook.md
- docs/Homebrew-Leadership-Responsibilities.md
- docs/Homebrew-brew-Maintainer-Guide.md
- docs/Homebrew-homebrew-cask-Maintainer-Guide.md
- docs/Homebrew-homebrew-core-Maintainer-Guide.md
- docs/Homebrew-on-Linux.md
- docs/How-to-Create-and-Maintain-a-Tap.md
- docs/Maintainer-Guidelines.md
- docs/New-Maintainer-Checklist.md
- docs/README.md
- docs/Releases.md
- docs/Troubleshooting.md
- docs/Updating-Software-in-Homebrew.md
- docs/governance/2019-moss-track-iii-grant-nomination.md
-----
In this season finale of reworking the docs: the Maintainers section, mostly. (Previously: #12431, #12505, #14023, #14140, #14152)
> docs: update Maintainers section

- docs/Homebrew-Leadership-Responsibilities.md
The PLC/TSC agreed this change in the private repository.
> Homebrew-Leadership-Responsibilities: import changes.

- Library/Homebrew/api/formula.rb
If we can't parse the file: it's corrupt. Try again up to 3 times before bailing.
Fixes #14211
> api/formula: handle JSON file corruption.

- Library/Homebrew/formula.rb
-----
Add support for generating Python Click completions.
Ref: https://click.palletsprojects.com/en/8.1.x/shell-completion/#enabling-completion
> Click will output it when called with `_{PROG_NAME}_COMPLETE` set to `{shell}_source`. `{PROG_NAME}` is the executable name in uppercase with dashes replaced by underscores. The built-in shells are `bash`, `zsh`, and `fish`.
Note that Click doesn't support macOS Bash (needs 4.4+) and will fail if generation is attempted there.
-----
Particular formulae that could use this:
- [`hatch`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/hatch.rb#L231-L232)
- [`pipenv`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pipenv.rb#L75-L78)
- [`ykman`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ykman.rb#L97-L9 …
> formula: add support for generating click shell completions

- docs/Acceptable-Casks.md
Swapped logic of rejection from work to failure and added an example
-----
> docs: Fix wrong condition for an app rejection

- .github/ISSUE_TEMPLATE/bug.yml
This probably won't work but gives us a stronger reason to ignore this.
> ISSUE_TEMPLATE/bug: nudge people to discussions.

- Library/Homebrew/dev-cmd/audit.rb
-----
This comments out the deprecations added in #14285 so that they can be enabled when we put out another minor or major release.
> Comment out path args deprecation

- .github/workflows/build-pkg.yml
- .gitignore
- Library/Homebrew/style.rb
- package/scripts/postinstall
- package/scripts/preinstall
-----
This should massively simplify the install for macOS users.
> feature: generate macOS pkg files

- Library/Homebrew/extend/os/linux/system_config.rb
-----
This should make it easier to determine issues with WSL kernels
> SystemConfig: show WSL version if available on Linux

- docs/Homebrew-Governance.md
This facilitates the distribution of a slate of candidates and their bios and intentions.
-----
> Governance: Adds PLC candidate expectations

- Library/Homebrew/cmd/search.rb
> search.rb: Update Fedora URL

- Library/Homebrew/formula.rb
> Add PYTHONDONTWRITEBYTECODE to common_stage_test_env.

- docs/License-Guidelines.md
-----
Link was broken, found the most current one. Unfortunately, it's a versioned link...
> docs: Fixes broken link to SPDX expressions docs

- Library/Homebrew/cmd/update.sh
Fixes https://github.com/Homebrew/brew/issues/14335
> cmd/update.sh: use GitHub API token if available.

- Library/Homebrew/diagnostic.rb
- Library/Homebrew/system_config.rb
> Revert "show/check Homebrew branch"

- Library/Homebrew/cask/installer.rb
- Library/Homebrew/extend/os/mac/utils/analytics.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/test/utils/analytics_spec.rb
- Library/Homebrew/utils/analytics.rb
-----
Starting the work that was open for GSoC but is not part of GSoC
Closes https://github.com/Homebrew/gsoc/issues/46
TODO:
> analytics: optionally duplicate to InfluxDB

- Library/Homebrew/caveats.rb
- Library/Homebrew/extend/on_system.rb
- Library/Homebrew/formula_cellar_checks.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/service.rb
- Library/Homebrew/service.rbi
- Library/Homebrew/test/dev-cmd/audit_spec.rb
- Library/Homebrew/test/formula_installer_spec.rb
- Library/Homebrew/test/service_spec.rb
-----
Closes: https://github.com/Homebrew/brew/issues/14352
Merge after: https://github.com/Homebrew/homebrew-services/pull/536
> Allow defining service run command per platform

- Library/Homebrew/dev-cmd/vendor-gems.rb
Hopefully fixes CI (untested).
> dev-cmd/vendor-gems: set SDKROOT for older macOS

- Library/Homebrew/cask/cask_loader.rb
These are mapped to generic versions in `cask/cask.rb` so we need to map them back for them to be correct.
Fixes https://github.com/Homebrew/brew/issues/14410
> cask_loader: fixup artifacts/caveats from JSON API.

- .devcontainer/on-create-command.sh
- Library/Homebrew/rubocops/files.rb
- ensure that homebrew/core is always tapped
- make RuboCop stop complaining about permissions
> Improve Codespaces behaviour

- Library/Homebrew/brew.rb
- Library/Homebrew/dev-cmd/edit.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/install.rb
- Tell people what to do to resolve this
- Tweak the instruction ordering to be consistent elsewhere
Fixes https://github.com/Homebrew/brew/issues/14430
> install: better error when using API and --HEAD.

- docs/_config.yml
> docs: mention Linux on site description

- docs/Formula-Cookbook.md
-----
Clarifying the dependency values that. are not allowed in `homebrew-core`.
Related to https://github.com/Homebrew/homebrew-core/pull/122295
> docs: Clarify dependency values

- Library/Homebrew/test/utils/analytics_spec.rb
- Library/Homebrew/utils/analytics.rb
> analytics: stop sending analytics in tests

- Library/Homebrew/completions/bash.erb
- completions/bash/brew
-----
Apply changes implemented in #14467 to the right file (Library/Homebrew/completions/bash.erb) so that they persist. Changes to completions/bash/brew were generated by `brew generate-man-completions`
CC @MikeMcQuaid and @Rylan12
> Refix bash completions 1

- Library/Homebrew/cask/cmd/install.rb
- Library/Homebrew/extend/os/cask/cmd/install.rb
- Library/Homebrew/extend/os/linux/cask/cmd/install.rb
-----
move `Cask::cmd::install#install_casks` to extend/os because of `#todo`.
> apply `extend/os` to `Cask::cmd::install#install_casks`

- Library/Homebrew/cmd/info.rb
> cmd/info: generate `--json=v2` from local taps.

- .github/workflows/tests.yml
- Library/Homebrew/brew.sh
- Library/Homebrew/cmd/formulae.sh
- Library/Homebrew/cmd/update.sh
- Library/Homebrew/dev-cmd/tests.rb
- Library/Homebrew/env_config.rb
- docs/Installation.md
- docs/Manpage.md
- manpages/brew.1
Reverts Homebrew/brew#14412
Reverts https://github.com/Homebrew/brew/pull/14384
> Revert "HOMEBREW_INSTALL_FROM_API: make the default for everyone."

- Library/Homebrew/cask/cask.rb
- Library/Homebrew/cmd/deps.rb
- Library/Homebrew/cmd/desc.rb
- Library/Homebrew/cmd/info.rb
- Library/Homebrew/cmd/options.rb
- Library/Homebrew/cmd/readall.rb
- Library/Homebrew/cmd/search.rb
- Library/Homebrew/cmd/uses.rb
- Library/Homebrew/dev-cmd/audit.rb
- Library/Homebrew/dev-cmd/generate-man-completions.rb
- Library/Homebrew/dev-cmd/livecheck.rb
- Library/Homebrew/dev-cmd/typecheck.rb
- Library/Homebrew/dev-cmd/unbottled.rb
- Library/Homebrew/dev-cmd/update-license-data.rb
- Library/Homebrew/extend/os/linux/linkage_checker.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/rubocops/components_order.rb
- Library/Homebrew/test/caveats_spec.rb
- Library/Homebrew/test/formula_installer_spec.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/utils.rb
> Revert "Add deprecations and disables"

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/cask/auditor.rb
- Library/Homebrew/cask/cmd/audit.rb
- Library/Homebrew/dev-cmd/audit.rb
- Library/Homebrew/test/cask/audit_spec.rb
- Library/Homebrew/test/cask/cmd/audit_spec.rb
> Pass `only` and `except` to cask audits.

- README.md
We'll probably announce 4.0.0 here too.
> README: add Mastodon link.

- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/formula_text_auditor.rb
-----
This should help finding outdated patches in Homebrew/core. I couldn't get the API to work using the `GitHub::API` class so posting here for help with that.
> audit: check for closed issues in comments

- Library/Homebrew/dev-cmd/update-test.rb
- Library/Homebrew/extend/os/dev-cmd/update-test.rb
- Library/Homebrew/extend/os/linux/dev-cmd/update-test.rb
-----
move the `dev-cmd/update-test` method to `extend/os` because of `# TODO`
> apply `extend/os` to `dev-cmd/update-test`

- Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
> Fix duration calculation in `bump-unversioned-casks`.

- Library/Homebrew/formulary.rb
> formulary: fix git clone handling for API formulae

- Library/Homebrew/env_config.rb
- docs/Manpage.md
- manpages/brew.1
We've reducing this in https://github.com/Homebrew/formulae.brew.sh/pull/752
> env_config: reduce api_auto_update_secs.

- Library/Homebrew/.rubocop.yml
- Library/Homebrew/brew.sh
- Library/Homebrew/env_config.rb
- docs/Manpage.md
- manpages/brew.1
Add another case to update once an hour when developer commands have been run.
> Further adjust `HOMEBREW_AUTO_UPDATE_SECS`

- Library/Homebrew/utils/analytics.rb
We've deleted the old data and added a new bucket with a new (write-only) token.
> analytics: update token.

- Library/Homebrew/test/cask/cask_loader/from_api_loader_spec.rb
-----
Just thought it'd be nice to have some basic tests here since we're now all in on the API. I wrote it up in such a way that doesn't need the network either.
> cask: add FromAPILoader tests

- Library/Homebrew/formula_installer.rb
Fixes Homebrew/homebrew-core#121939.
> formula_installer: fix resource fetching for source builds under API

- README.md
Let's put things users are more likely to care about nearer the top.
> README: rearrange.

- package/scripts/postinstall
> package: fix ARM name and owner of prefix

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/download_strategy.rb
- Library/Homebrew/unpack_strategy.rb
- Library/Homebrew/unpack_strategy/uncompressed.rb
> Revert "Fix permissions before moving extracted files."

- Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
-----
Avoid errors in casks which cannot be updated anyways.
> Ignore discontinued casks in `bump-unversioned-casks`.

- Library/Homebrew/diagnostic.rb
> Use `OFFICIAL_CASK_TAPS` constant.

- Library/Homebrew/utils/analytics.rb
This enables easier usage in `brew formula-analytics`.
> utils/analytics: tweaks constants.

- Library/Homebrew/cask/audit.rb
-----
This should extend our auditing to the last remaining signed artifact
> cask: audit for correct signing of pkg installers

- Library/Homebrew/cask/audit.rb
-----
I saw @miccal change this a bunch of times. Let's audit for it. Please let me know if I got the logic right.
> cask: audit if sparkle livecheck needs multipart version

- Library/Homebrew/cmd/update-report.rb
- Library/Homebrew/dev-cmd/update-test.rb
- Library/Homebrew/extend/os/linux/dev-cmd/update-test.rb
-----
These need to be after the original module/class definitions for the monkey-patching to work correctly.
> extend/os: clean up requires

- Library/Homebrew/download_strategy.rb
- Library/Homebrew/unpack_strategy.rb
- Library/Homebrew/unpack_strategy/uncompressed.rb
-----
Extracted from https://github.com/Homebrew/brew/pull/14735.
> Add signatures for extraction functions.

- Library/Homebrew/dev-cmd/contributions.rb
-----
- Turns out in my head a few days ago I was overcomplicating this. I had a brainwave while in the shower.
- Some refactoring so that we call `totals` to sum up the hash of hashes less, since the grand total numbers are now used in multiple places.
> dev-cmd/contributions: CSV output of totals per maintainer

- Library/Homebrew/dev-cmd/contributions.rb
> dev-cmd/contributions: Order the CSV by highest contributions total

- Library/Homebrew/cask/audit.rb
-----
Resolves:
```
$ brew audit --eval-all                                                                                           [master|⚑6]
vde:
* fully scope test system calls, e.g. system "#{bin}/vde_switch"
Error: Return value: Expected type String, got type NilClass
Caller: /opt/homebrew/Library/Homebrew/cask/auditor.rb:68
Definition: /opt/homebrew/Library/Homebrew/cask/audit.rb:123
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:303:in `call_validation_error_handler' …
```
> Fixed type error in 'brew audit'

- Library/Homebrew/dev-cmd/cat.rb
Fixes #14815.
CC @gromgit @EricFromCanada @apainintheneck for messaging thoughts.
> dev-cmd/cat: improve error message.

- Library/Homebrew/service.rb
- Library/Homebrew/test/service_spec.rb
-----
This is the PR for #14612. If this sort of change seems reasonable then I can update the docs and add tests for this change.
> dedicated `run_at_load` property

- Library/Homebrew/cmd/update-report.rb
- Library/Homebrew/env_config.rb
- Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi
- docs/Manpage.md
- manpages/brew.1
It's not worth supporting this option any longer given the API constraints.
> Note that `brew update` will only report all without API.

- Library/Homebrew/cask/dsl/caveats.rb
- Library/Homebrew/cask/info.rb
- Library/Homebrew/cask/list.rb
- Library/Homebrew/cmd/cleanup.rb
- Library/Homebrew/dependency.rb
- Library/Homebrew/extend/os/cleanup.rb
- Library/Homebrew/extend/os/linux/cleanup.rb
- Library/Homebrew/extend/os/linux/cmd/update-report.rb
- Library/Homebrew/extend/os/linux/keg.rb
- Library/Homebrew/extend/os/mac/cleanup.rb
- Library/Homebrew/startup/bootsnap.rb
- Library/Homebrew/test/support/helper/integration_mocks.rb
- Library/Homebrew/test/utils/repology_spec.rb
- Library/Homebrew/utils/popen.rb
-----
- This was done through the `brew typecheck --suggest-typed --update` command.
> sorbet: Bump more files to `typed: true`

- Library/Homebrew/cask/audit.rb
This reverts commit 7497f805ba92186121bd170b504e6bdf2dea1407.
-----
Attempt nr 2 at https://github.com/Homebrew/brew/pull/14774. This time with more testing done
> cask: retry audit for correct signing of pkg installers

- Library/Homebrew/test/extend/array_spec.rb
-----
Fixing master with `brew style --fix`
> brew style --fix

- Library/Homebrew/cmd/--cache.rb
- Library/Homebrew/cmd/--prefix.rb
- Library/Homebrew/cmd/commands.rb
- Library/Homebrew/cmd/deps.rb
- Library/Homebrew/cmd/desc.rb
- Library/Homebrew/cmd/doctor.rb
- Library/Homebrew/cmd/fetch.rb
- Library/Homebrew/cmd/info.rb
- Library/Homebrew/cmd/install.rb
- Library/Homebrew/cmd/list.rb
- Library/Homebrew/cmd/log.rb
- Library/Homebrew/cmd/options.rb
- Library/Homebrew/cmd/outdated.rb
- Library/Homebrew/cmd/reinstall.rb
- Library/Homebrew/cmd/search.rb
- Library/Homebrew/cmd/tap-info.rb
- Library/Homebrew/cmd/upgrade.rb
- Library/Homebrew/cmd/uses.rb
- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/utils.rb
-----
Following through on https://github.com/Homebrew/brew/pull/14880#discussion_r1125251114 and enabling typing in this folder.
> Enable typing in cmd/

- Library/Homebrew/cask/artifact/abstract_uninstall.rb
-----
This reverts the splat changes to https://github.com/Homebrew/brew/pull/14769 which potentially caused issues in https://github.com/Homebrew/homebrew-cask-drivers/pull/3341#issuecomment-1458172880
Since we now suppress splat errors, the above changes aren't needed to maintain type checking in the file.
> Revert splat changes to AbstractUninstall

- Library/Homebrew/build.rb
- Library/Homebrew/cask/cask.rb
- Library/Homebrew/cask/cask_loader.rb
- Library/Homebrew/cask/dsl.rb
- Library/Homebrew/cask/dsl/base.rb
- Library/Homebrew/cli/named_args.rb
- Library/Homebrew/extend/on_system.rbi
- Library/Homebrew/os/linux.rb
- Library/Homebrew/os/mac.rb
-----
What it says the tin: this enables typing in a few more files
> Enable typing in a few more files

- Library/Homebrew/debrew.rb
-----
Fix exception in debug mode:
```
NameError: undefined local variable or method `e' for Debrew:Module
```
> debrew: fix undefined variable

- Dockerfile
We need all of these in various homebrew/core workflows.
> Dockerfile: `apt-get install` more useful things

- Library/Homebrew/cask/uninstall.rb
- Library/Homebrew/dev-cmd/audit.rb
- Library/Homebrew/dev-cmd/bottle.rb
- Library/Homebrew/dev-cmd/bump-cask-pr.rb
- Library/Homebrew/dev-cmd/cat.rb
- Library/Homebrew/dev-cmd/extract.rb
- Library/Homebrew/dev-cmd/pr-publish.rb
- Library/Homebrew/dev-cmd/pr-pull.rb
- Library/Homebrew/dev-cmd/sh.rb
- Library/Homebrew/dev-cmd/tap-new.rb
- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/test/extend/kernel_spec.rb
- Library/Homebrew/utils/git.rb
-----
What it says on the tin ☝️
> Enable types for most dev commands

- Library/Homebrew/test/utils/spdx_spec.rb
> Simplify SPDX test.

- Dockerfile
-----
Needed for Homebrew/homebrew-core#125556.
> Dockerfile: fix installation of `gh`, et al.

- .github/workflows/tests.yml
Needed for merge queue to merge.
> workflows/tests: also run update-tests for merge_group.

- Library/Homebrew/utils/gzip.rb
-----
Follow-up to https://github.com/Homebrew/brew/pull/14316#discussion_r1119586267.
> utils/gzip: don't mark API as private

- Library/Homebrew/cmd/postgresql-upgrade-database.rb
This is useful for non-contributor users but won't be installed if they don't have homebrew/core tapped (the default).
> cmd/postgresql-upgrade-database: import from homebrew/core.

- Library/Homebrew/cmd/update-reset.sh
- Library/Homebrew/cmd/update.sh
The shims _Should Not Fail_, but [when bugs happen](https://github.com/orgs/Homebrew/discussions/4331), they just cause confusing errors.
> update*: check shim output

- Library/Homebrew/formulary.rb
This is used in this file.
Fixes https://github.com/Homebrew/homebrew-services/issues/562
> formulary: require service.

- .github/workflows/triage-issues.yml
This PR wasn't automatically opened due to GitHub downtime?
> triage-issues.yml: update to match main configuration

- Library/Homebrew/unversioned_cask_checker.rb
-----
Needed for https://github.com/Homebrew/homebrew-cask/pull/143972.
> Handle more artifacts in livecheck `:extract_plist` strategy.

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
> dev-cmd/bump-cask-pr: fix `sha265` typo

- Library/Homebrew/unversioned_cask_checker.rb
---
Also consider version of `.app`s containing installers.
> Include screen savers in `:extract_plist` strategy.

- Library/Homebrew/livecheck/strategy/apache.rb
- Library/Homebrew/livecheck/strategy/bitbucket.rb
- Library/Homebrew/livecheck/strategy/cpan.rb
- Library/Homebrew/livecheck/strategy/electron_builder.rb
- Library/Homebrew/livecheck/strategy/extract_plist.rb
- Library/Homebrew/livecheck/strategy/git.rb
- Library/Homebrew/livecheck/strategy/github_latest.rb
- Library/Homebrew/livecheck/strategy/gnome.rb
- Library/Homebrew/livecheck/strategy/gnu.rb
- Library/Homebrew/livecheck/strategy/hackage.rb
- Library/Homebrew/livecheck/strategy/header_match.rb
- Library/Homebrew/livecheck/strategy/json.rb
- Library/Homebrew/livecheck/strategy/launchpad.rb
- Library/Homebrew/livecheck/strategy/npm.rb
- Library/Homebrew/livecheck/strategy/page_match.rb
- Library/Homebrew/livecheck/strategy/pypi.rb
- Library/Homebrew/livecheck/strategy/sourceforge.rb
- Library/Homebrew/livecheck/strategy/sparkle.rb
- Library/Homebrew/livecheck/strategy/xml.rb
- Library/Homebrew/livecheck/strategy/xorg.rb
- Library/Homebrew/livecheck/strategy/yaml.rb
-----
This is a slight improvement over `T.untyped` block arguments.
> Add types to block params

- docs/governance/2023-agm-minutes.md
-----
- We held the 2023 AGM in February. Let's document the high-level talking points in a public place like we did for previous years.
> docs/governance/2023-agm-minutes: Add brief summary of talking points

- Library/Homebrew/api.rb
- Library/Homebrew/api/cask.rb
- Library/Homebrew/cask/cask.rb
- Library/Homebrew/cask/installer.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/test/api/cask_spec.rb
- Library/Homebrew/test/api_spec.rb
- Library/Homebrew/test/support/fixtures/cask/everything-systemsettings-caveats.json
- Library/Homebrew/test/support/fixtures/cask/everything.json
-----
This adds the Ruby source paths to the API, so we can determine the link after sharding the repos.
> Add source paths to API.

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
Contributors and maintainers usually strike through the message after checking `resource` blocks for updates. Let's add a checkbox to make it easier to update the status.
> dev-cmd/bump-formula-pr: add a checkbox for resource updates

- .github/workflows/build-pkg.yml
-----
Also, replace the `>` with `>>` to avoid running into potentially
confusing bugs in case we add more things to `GITHUB_OUTPUT` before this
line.
> workflows/build-pkg: fix actionlint error

- Library/Homebrew/dev-cmd/update-maintainers.rb
-----
This should fix ``Error: undefined method `slice!' for #<Hash:0x0000000003c557a8>`` from https://github.com/Homebrew/brew/actions/runs/4659983623/jobs/8247503227#step:6:74.
> dev-cmd/update-maintainers: fix undefined method

- Library/Homebrew/cask/audit.rb
---
Fixes audit failure in https://github.com/Homebrew/homebrew-cask/pull/144966.
> Fix codesign audit paths.

- Library/Homebrew/cmd/fetch.rb
- Library/Homebrew/dev-cmd/audit.rb
-----
Same as https://github.com/Homebrew/brew/pull/15056, but for `audit`.
> Allow running `audit` for different architecture.

- Library/Homebrew/cask/audit.rb
> Fix repo audit for discontinued casks.

- Library/Homebrew/cask/artifact/abstract_artifact.rb
- Library/Homebrew/cask/artifact/keyboard_layout.rb
- Library/Homebrew/cask/artifact/vst3_plugin.rb
- Library/Homebrew/cask/artifact/vst_plugin.rb
- docs/Cask-Cookbook.md
-----
- mention KeyboardLayout in the sort order
- remove redundant `english_name` for KeyboardLayout
- capitalize VST/VST3 in output
- expand the list of artifacts that `target:` works with (#15103)
> cask/artifact: fix up some definitions

- Library/Homebrew/cask/audit.rb
-----
Seems like signature verification [is occasionally failing](https://github.com/Homebrew/homebrew-cask/pull/145059#issuecomment-1507351629).
Over many trials I’ve settled on this `spctl` method as the most reliable method to check if an app or binary is signed and notarised. Haven’t tried extensively on PKGs but it should work the same. Submitting the PR seemed the most efficient way to make the suggestion and allow others to try it.
Add `-vv` to see details. Example output:
```
/Volumes/Garmin Express/Install Garmin Express.pkg: accepted
source=Notarized Developer ID
origin=Developer ID Installer: Garmin International (72ES32VZUA)
```
> audit.rb: Check for signature with sptcl

- Library/Homebrew/extend/os/linux/diagnostic.rb
> Don't use deprecated `Kernel#shell_profile`.

- Library/Homebrew/diagnostic.rb
-----
Resolves https://github.com/Homebrew/brew/issues/15245
Confirmed with `brew doctor`
> Fix 'undefined method git_default_origin_branch?'

- Library/Homebrew/formula_auditor.rb
-----
See discussion at Homebrew/homebrew-core#128954.
> formula_auditor: remove issue comment audit

- Library/Homebrew/dev-cmd/audit.rb
-----
Emitting annotations currently produces:
Error: no implicit conversion of Symbol into Integer
The issue is that `problem` is an `Array` of problems which we need to
handle individually.
> dev-cmd/audit: fix audit annotations

- .github/workflows/tests.yml
Hopefully fixes broken file viewing.
> workflows/tests: fix Codecov root dir

- Library/Homebrew/download_strategy.rb
> download_strategy: Fix the timeout value.

- Library/Homebrew/cask/url.rb
-----
Fixes the failure for `vlc-nightly` in https://github.com/Homebrew/brew/pull/15326.
> Fix type for nested `url` blocks.

- Library/Homebrew/cask/download.rb
- Library/Homebrew/downloadable.rb
Fixes Homebrew/homebrew-cask#146287.
> Fix DownloadError erroring itself

- Library/Homebrew/github_runner_matrix.rb
-----
1. Use the maximum timeout possible for GitHub-hosted macOS runners
2. When using a short timeout, use an even shorter timeout on ARM
runners.
Our ARM runners are typically at least twice as fast as our Intel
runners on any given job. So, if it takes an ARM runner over half the
timeout to complete a job, it's almost certain that the Intel runner
will not complete the job within the timeout.
Setting an even shorter timeout on the ARM runners will help us abandon
jobs that are unlikely to be completed within the timeout well before we
hit the requested timeout.
> github_runner_matrix: improve macOS timeout handling

- Library/Homebrew/download_strategy.rb
> remove auth header on cask url redirection on CurlDownloadStrategy

- Library/Homebrew/extend/os/mac/utils/bottles.rb
- Library/Homebrew/fetch.rb
- Library/Homebrew/utils/bottles.rb
-----
This is a better version of #15381, and addresses feedback from there.
Also reverts #15381.
> fetch: better typechecking fix

- Library/Homebrew/cmd/--cache.rb
- Library/Homebrew/cmd/fetch.rb
- Library/Homebrew/fetch.rb
-----
See discussion at #15382.
> fetch: remove use of `args` from CLI parser

- Library/Homebrew/cask/upgrade.rb
Otherwise it's tricky to debug any reported issues.
> cask/upgrade: improve error backtraces

- Library/Homebrew/dev-cmd/audit.rb
-----
Fixes CI since `homebrew/cask-drivers` is now empty.
> Don't fail auditing empty tap.

- Library/Homebrew/cask/artifact/moved.rb
- Library/Homebrew/cask/artifact/symlinked.rb
- Library/Homebrew/cask/utils.rb
- Library/Homebrew/test/cask/artifact/app_spec.rb
- Library/Homebrew/test/cask/utils_spec.rb
-----
Fixes https://github.com/Homebrew/homebrew-cask/pull/147086#issuecomment-1546322878.
> Use `sudo` for symlinks if necessary.

- Library/Homebrew/cask/upgrade.rb
-----
Closes https://github.com/Homebrew/brew/issues/15427.
> Don't special-case message for outdated casks that aren't installed.

- Library/Homebrew/cask/cask.rb
-----
Default output is huge, so simplify this similar to what `Formula#inspect` does.
> Simplify `Cask#inspect`.

- Library/Homebrew/bundle_version.rb
- Library/Homebrew/test/bundle_version_spec.rb
-----
Fixes https://github.com/Homebrew/brew/issues/15436.
> Fix `BundleVersion` comparison.

- bin/brew
> bin/brew: add all `GITHUB_*` vars to env allowlist

- Library/Homebrew/dependency_collector.rb
- Library/Homebrew/test/dependency_collector_spec.rb
- Library/Homebrew/unpack_strategy/rar.rb
-----
```
~ % brew style    
Inspecting 1169 files
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................. …
```
> Download Strategy Dependency Missing Case

- Library/Homebrew/formulary.rb
Addresses regression in https://github.com/Homebrew/brew/pull/15396.
Fixes https://github.com/Homebrew/homebrew-core/issues/131284
Fixes https://github.com/Homebrew/homebrew-core/issues/131287
Fixes https://github.com/Homebrew/homebrew-bundle/issues/1205
Fixes https://github.com/Homebrew/brew/issues/15454
> formulary: use a lot more `.presence`.

- Library/Homebrew/cmd/deps.rb
- Library/Homebrew/cmd/uses.rb
- Library/Homebrew/dependencies_helpers.rb
- Library/Homebrew/dependency.rb
This PR adds a flag to the `brew deps` cmd to mirror the `--installed` flag inversely
The motivation of this small change is to be able to filter only "new" dependencies during the installation for formulae. Currently, there is no way to achieve this… Using the [missing](https://github.com/binury/brew/blob/ce1949605ecfbc5297866b7500f4449809b329d7/Library/Homebrew/cmd/missing.rb#L28-L47) cmd is very helpful but is _not recursive_ and will only report direct dependencies. (`brew deps --direct --missing` is the equivalent) With this flag in `deps` there is also interop with graph/tree outputs.
Due to the "strict handling of CLI args" (#10880) DependenciesHelpers module being shared between deps and uses, it was necessary to define the flag in both modules to prevent the exception in …
> Add brew deps `--missing` arg

- Library/Homebrew/test/download_strategies/curl_spec.rb
- Library/Homebrew/utils/curl.rb
-----
CI is broken because `example.com` doesn't return an `Accept-Ranges` header anymore. We shouldn't actually `curl` it anyways in tests.
> Fix failing test.

- Library/Homebrew/cask/migrator.rb
-----
Fixes the error reported in https://github.com/Homebrew/homebrew-cask/pull/147432.
> Fix wrong token in `Cask::Migrator`.

- Library/Homebrew/utils/curl.rb
---
Only check `destination.exist? && supports_partial` condition once.
> Simplify `curl_download`.

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/dev-cmd/audit.rb
- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/tap_auditor.rb
-----
Make `brew audit` only output the same problem once in case of `--os=all --arch=all`.
> Clean up `brew audit` output.

- Library/Homebrew/cmd/--cache.rb
- Library/Homebrew/cmd/fetch.rb
-----
Fixes https://github.com/Homebrew/brew/issues/15474.
> Fix wrong method in `--cache` and `fetch`.

- Library/Homebrew/github_packages.rb
-----
We still regularly see upload failures here, so let's adjust this to see
if we can try to reduce these.
> github_packages: adjust upload retries

- Library/Homebrew/utils/github/api.rb
-----
Fixes
Error: no implicit conversion of nil into String
https://github.com/Homebrew/homebrew-test-bot/actions/runs/5113802196/jobs/9193401244#step:11:11
> utils/github/api: fix nil implicit conversion error

- Library/Homebrew/cmd/leaves.rb
-----
closes https://github.com/Homebrew/brew/issues/15558
> remove cask's depencies from brew/leaves

- Library/Homebrew/rubocops/shared/desc_helper.rb
- Library/Homebrew/test/rubocops/cask/desc_spec.rb
- Library/Homebrew/test/rubocops/desc_spec.rb
-----
Opening this for discussion regarding usage of emojis in `desc` stanza. This is in reference to https://github.com/Homebrew/homebrew-core/pull/134198.
> rubocops: add emoji audit

- bin/brew
-----
It's been almost a year since this change was made and we are definitely in 2023.
> bin/brew: remove `HOMEBREW_NO_ENV_FILTERING` error

- Library/Homebrew/formula_auditor.rb
-----
This supports the use of `*-staging` branches in the future for projects
similar to the OpenSSL migration (e.g. Python migration). We already
have branch protections set for these branches, so it makes sense to
keep using them with the supporting code.
> formula_auditor: make OpenSSL audit exception generic

- Library/Homebrew/dev-cmd/pr-publish.rb
-----
This will make it easier to merge PRs that require the large runner to
upload the built bottles.
> pr-publish: request a large runner for appropriately labelled PRs

- Library/Homebrew/download_strategy.rb
> download_strategy: move HOMEBREW_ARTIFACT_DOMAIN hack

- Library/Homebrew/cmd/postgresql-upgrade-database.rb
Because of PATH filtering etc.
> cmd/postgresql-upgrade-database: fix brew not being found

- Library/Homebrew/extend/ENV/super.rb
-----
This is based on feedback from #15613.
> extend/ENV/super: add comment for `OPENSSL_NO_VENDOR`

- Library/Homebrew/cmd/update.sh
If those folks have this tapped and explicitly run `brew update`: let's update it for them.
> cmd/update: update homebrew/core and homebrew/cask with devcmdrun.

- Library/Homebrew/dev-cmd/generate-cask-api.rb
- Library/Homebrew/dev-cmd/generate-formula-api.rb
These will be consumed in https://github.com/Homebrew/brew/pull/15629.
Part of https://github.com/Homebrew/brew/issues/14897
> dev-cmd/generate-*-api: generate tap migrations JSON.

- Library/Homebrew/cmd/update.sh
- Library/Homebrew/test/formulary_spec.rb
- Library/Homebrew/test/os/mac/formula_spec.rb
- Library/Homebrew/test/software_spec_spec.rb
Fix the master of brew being used in brew PRs.
> cmd/update: adjustments for setup-homebrew in brew CI

- Library/Homebrew/formula_auditor.rb
> formula_auditor: fix macOS system dependency false positive

- Library/Homebrew/utils/analytics.rb
> analytics: use new AWS based influxdb

- Library/Homebrew/brew.sh
-----
Fixes https://github.com/Homebrew/brew/issues/15669
> brew.sh: record OS version for non-debian linux

- Library/Homebrew/os/mac/mach.rb
-----
We don't want to call `uniq` on this because this breaks our handling of
duplicate rpaths.
> os/mac/mach: report duplicate rpaths

- Library/Homebrew/exceptions.rb
I guess someone did mot see it.
_Change made in GitHub editor… mot locally._
-----
> Corrects an uncaught spelling error

- Library/Homebrew/rubocops/lines.rb
> rubocops/lines: simplify PyoxidizerCheck

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
- Library/Homebrew/dev-cmd/bump-formula-pr.rb
> dev-cmd/bump-*-pr: avoid installing gems when unneeded.

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
Good catch by @Bo98 in https://github.com/Homebrew/brew/pull/15701#discussion_r1266620925
> dev-cmd/bump-cask-pr: fix install_bundler_gems! logic.

- Library/Homebrew/cask/url.rb
- Library/Homebrew/download_strategy.rb
- docs/Cask-Cookbook.md
-----
See https://github.com/Homebrew/brew/issues/15590 for explanation.
Fixes #15590
> Cask support multiple headers

- Library/Homebrew/formula.rb
-----
`install_libdir` is sometimes passed a `Pathname`.
> formula: fix typechecking error in `std_cmake_args`

- Library/Homebrew/formula.rb
- Library/Homebrew/test/utils/inreplace_spec.rb
- Library/Homebrew/utils/inreplace.rb
- Library/Homebrew/utils/string_inreplace_extension.rb
-----
Should resolve https://machomebrew.slack.com/archives/CTHMNNM7H/p1690052213635069?thread_ts=1689992575.141279&cid=CTHMNNM7H
cc @p-linnane
> Strict type string_inreplace_extension

- Library/Homebrew/extend/os/mac/keg_relocate.rb
- Library/Homebrew/os/mac/mach.rb
-----
This implements the TODO that I left as a comment from #15722.
In order to simplify the handling of deleting an absolute rpath that has
a relative duplicate (or vice-versa, i.e., a relative rpath with an
absolute duplicate), we relocate all rpaths first in one pass and then
delete the duplicates in a separate pass.
We currently rely on some lower-level (but still public) methods from
ruby-macho since the standard `#delete_rpath` method changes the order
in which rpaths are resolved. We can switch back to using
`#delete_rpath` when Homebrew/ruby-macho#555 is merged and released.
> extend/os/mac/keg_relocate: improve rpath handling

- Library/Homebrew/formula.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/test/formulary_spec.rb
-----
Resolves https://github.com/Homebrew/brew/issues/15730
Also addresses feedback in https://github.com/Homebrew/brew/pull/15741/files#r1271866720
> Fix type error when running 'brew doctor'

- .github/workflows/build-pkg.yml
Continuing https://github.com/Homebrew/brew/pull/14708 from @TETRA2000 in a branch PR (so the job we're changing will actually be run).
Fixes https://github.com/Homebrew/install/issues/739
> Add package signing configuration for GitHub Actions

- Library/Homebrew/cmd/install.rb
> cmd/install: add missing require.

- CONTRIBUTING.md
- docs/Acceptable-Casks.md
- docs/Adding-Software-to-Homebrew.md
- docs/vale-styles/Homebrew/Terms.yml
Use new scope syntax and fix errors.
> docs/vale-styles: fix configuration.

- Library/Homebrew/extend/os/mac/keg_relocate.rb
- Library/Homebrew/os/mac/mach.rb
-----
We now have the new release of ruby-macho (#15758), so we can now
finish off the remaining work from #15731.
> Implement ruby-macho TODOs

- Library/Homebrew/brew.sh
- docs/Installation.md
https://github.com/Homebrew/brew/pull/15765#issuecomment-1652856355
This reverts commit d9bc51f8171b49486a871a8bb12a2629df28a519.
> Revert "brew.sh: don't set `HOMEBREW_NO_INSTALL_FROM_API` automatically."

- docs/Homebrew-homebrew-core-Maintainer-Guide.md
-----
Let's get this written down now before I forget how to do this.
> docs: add documentation for staging branches

- docs/Installation.md
While we're here, also make the ARM prefix first.
Won't be merged until we have a new Homebrew release with an installer uploaded.
> docs/Installation: document macOS .pkg installer.

- Library/Homebrew/extend/ENV/super.rb
-----
Having this would have been, or would be, useful on multiple occassions:
- Homebrew/homebrew-core#94724
- Homebrew/homebrew-core#136551
- #15372
I think it's time that we added this back.
> extend/ENV/super: add `ENV.O3`

- .vscode/extensions.json
- .vscode/settings.json
- Use more modern and more useful extensions
- Use the Ruby language server as not doing so is deprecated
> Improve VSCode extensions/settings

- .github/workflows/build-pkg.yml
- package/resources/CONCLUSION.rtf
- package/resources/WELCOME.rtf
- use the system font instead of Helvetica
- cleanup font definitions
- add extra newline to `CONCLUSION.rtf` to next steps not showing up without a click
- add actual hyperlinks to `CONCLUSION.rtf`
Fixes #15793
> package/resources: improve text output.

- Library/Homebrew/formula.rb
-----
Resolves https://github.com/Homebrew/homebrew-core/actions/runs/5712062077/job/15474938229?pr=137880#step:3:6143
> Widen paths type in Formula#inreplace

- bin/brew
Rather than having increasingly involved workarounds that require other variables to be set.
Closes #15822
> bin/brew: require HOME to be set.

- Library/Homebrew/os/mac/mach.rb
-----
This is just a recipe for infinite loops. Plus, recursive references are
likely to be invalid, so we don't really gain much by attempting to
resolve them.[^1] (But we could if we made the logic here much more
complicated.)
Fixes a CI failure seen at Homebrew/homebrew-core#138323.
[^1]: See, for example, embree/embree#455.
> os/mac/mach: avoid recursively resolving rpaths

- Library/Homebrew/cask/migrator.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/test/dev-cmd/test_spec.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/utils/inreplace.rb
- Library/Homebrew/utils/inreplace.rbi
-----
Revised attempt at https://github.com/Homebrew/brew/pull/15807, this time including tests and explicit block forwarding
cc @bayandin
> Make inreplace a purely static method v2

- Library/Homebrew/os/mac/mach.rb
> os/mac/mach: fix rpath deletion of fat machos

- Library/Homebrew/ast_constants.rb
- Library/Homebrew/cask/cache.rb
- Library/Homebrew/cmd/--cache.rb
- Library/Homebrew/cmd/--repository.rb
- Library/Homebrew/cmd/analytics.rb
- Library/Homebrew/cmd/autoremove.rb
- Library/Homebrew/cmd/cleanup.rb
- Library/Homebrew/cmd/commands.rb
- Library/Homebrew/cmd/completions.rb
- Library/Homebrew/cmd/config.rb
- Library/Homebrew/cmd/docs.rb
- Library/Homebrew/cmd/help.rb
- Library/Homebrew/default_prefix.rb
- Library/Homebrew/extend/cachable.rb
- Library/Homebrew/extend/os/cleanup.rb
- Library/Homebrew/extend/os/linux/dev-cmd/update-test.rb
- Library/Homebrew/extend/os/parser.rb
- Library/Homebrew/extend/predicable.rb
- Library/Homebrew/formula_free_port.rb
- Library/Homebrew/livecheck/constants.rb
- Library/Homebrew/source_location.rb
- Library/Homebrew/tap_constants.rb
- Library/Homebrew/test/support/lib/default_prefix.rb
- Library/Homebrew/test/utils/repology_spec.rb
- Library/Homebrew/utils/rubocop.rb
-----
Bumping the typedness of a few files that are easily upgraded. (This is mostly immaterial, although it found an unnecessary cast in `Library/Homebrew/cmd/--cache.rb` as a result.)
> Turn up the types

- Library/Homebrew/brew.sh
> brew.sh: fix shellcheck warning.

- Library/Homebrew/service.rb
Follow-up to https://github.com/Homebrew/brew/pull/15875 based on https://github.com/Homebrew/homebrew-core/pull/139680#discussion_r1295770047
> service: handle quoting in service file, too.

- Library/Homebrew/brew.sh
---
Fixes `brew style` on macOS: https://github.com/Homebrew/brew/issues/15876#issuecomment-1680594277
> brew.sh: disable shellcheck warning

- Library/Homebrew/dependency.rb
- Library/Homebrew/dependency_collector.rb
An improved take on #15907 as per https://github.com/Homebrew/brew/pull/15919#discussion_r1307655865.
> dependency: consider bounds when comparing macOS deps

- Library/Homebrew/cmd/deps.rb
- docs/Manpage.md
- manpages/brew.1
https://github.com/Homebrew/brew/pull/15892#issuecomment-1698659908
> cmd/deps: fix documentation and handling of formula_options.

- docs/Brew-Livecheck.md
- docs/Cask-Cookbook.md
- add or update example code and links
- relocate and rework the Conditional Statements section to match how system versions and architectures are now handled in homebrew/cask
- replace macOS symbols table with link to [MacOSVersion class documentation](https://rubydoc.brew.sh/MacOSVersion.html)
- integrate most of the `livecheck` stanza section into the `brew livecheck` page and fill in a few gaps (cc @samford)
> docs: rework Cask-Cookbook to match current practice

- Library/.rubocop.yml
- Library/Homebrew/cmd/fetch.rb
- Library/Homebrew/download_strategy.rb
These were also easily fixed, already fixed or incorrect and non-controversial.
> Cleanup various TODOs

- Library/Homebrew/formula_auditor.rb
-----
Ref https://github.com/Homebrew/homebrew-core/pull/141362
> audit_file: check formula path

- Library/Homebrew/utils/github/artifacts.rb
Needed after https://github.com/Homebrew/brew/pull/15940
> utils/github/artifacts: fix missing Utils::Curl reference.

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/resource_auditor.rb
-----
Hopefully this fixes recent `homebrew/core` and `homebrew/cask` CI failures.
> Fix more `Utils::Curl` usage

- Library/Homebrew/utils/github.rb
> utils/github: fully scope curl usage.

- Library/Homebrew/formula_auditor.rb
See also
https://github.com/Homebrew/homebrew-core/pull/139538
-----
> terraform: add audit for relicensing

- Library/Homebrew/formula.rb
-----
remove useless `require` https://github.com/Homebrew/brew/pull/15934#discussion_r1314062686
> remove useless require from `Formula`

- Library/Homebrew/global.rb
- Library/Homebrew/test/download_strategies/curl_spec.rb
> chore: update safari UA to the latest

- Library/Homebrew/os/mac/pkgconfig/13/libcurl.pc
- Library/Homebrew/os/mac/pkgconfig/14/libcurl.pc
> os/mac/pkgconfig: update for macOS 14 RC SDK

- docs/Rakefile
This link works but it's failing CI.
> docs/Rakefile: fix broken link.

- Library/Homebrew/manpages/brew.1.md.erb
- docs/Manpage.md
- manpages/brew.1
> manpage: note env files do not support expansion.

- Library/Homebrew/cli/named_args.rb
-----
This will make the output clearer for `brew edit --print-path`.
Related to #16015
> cli/named_args: expand paths in #to_paths

- .github/workflows/pkg-installer.yml
- Library/Homebrew/brew.sh
This intermediate state got missed during a previous refactoring PR.
> workflows/pkg-installer: fix filename.

- Library/Homebrew/startup/bootsnap.rb
> standalone/bootsnap: relax restrictions

- Library/Homebrew/download_strategy.rb
-----
The [pypy3.9](https://formulae.brew.sh/formula/pypy3.9) and [pypy3.10](https://formulae.brew.sh/formula/pypy3.10) formulae each have a branch set for their Mercurial-based `head` URLs, but it turns out those have been ignored until now. This adds support for `tag:`, `revision:`, and `branch:` for Mercurial repository URLs, with which you can:
1. add e.g. `branch: "dev"` to a `head` URL after `using: :hg` and it will work, e.g.: `brew fetch --HEAD pypy3.10; hg branch --cwd $(brew --cache --HEAD pypy3.10)` should print "py3.10" instead of "default"
2. set a formula to fetch a release directly from a Mercurial tag, e.g.:
```
url "https://hg.sr.ht/~breakfastquay/rubberband", using: :hg,
tag:      "v3.3.0",
revision: "55367f2e76c9"
```
> download_strategy: support Mercurial tags/branches

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
> dev-cmd/bump-formula-pr: fix specs passing under Ruby 3

- Library/Homebrew/dev-cmd/vendor-gems.rb
> dev-cmd/vendor-gems: git add Gemfile.lock

- docs/Interesting-Taps-and-Forks.md
-----
I guess a tap made by  is interesting enough.
> docs/Interesting-Taps-and-Forks: add `apple/apple`

- Library/Homebrew/extend/os/mac/hardware/cpu.rb
- Library/Homebrew/test/hardware/cpu_spec.rb
-----
Sources:
- https://github.com/OpenMathLib/OpenBLAS/pull/4315/files
- https://github.com/Tencent/ncnn/blob/master/src/cpu.cpp
> Add M3 processors

- Library/Homebrew/utils/gems.rb
-----
This should resolve potential errors resulting from https://github.com/Homebrew/brew/pull/16320
> Bump VENDOR_VERSION in gems.rb

- Library/Homebrew/dev-cmd/create.rb
- docs/Acceptable-Casks.md
- docs/Adding-Software-to-Homebrew.md
- docs/Cask-Cookbook.md
-----
This PR does the following:
* Modifies the cask template used for the `create` command
* Rearranges the list of reasons for cask rejection to align with their observed frequency
* Adds `livecheck` and `zap` to the list of required stanzas
* Provides guidance for situations where a zap stanza is not necessary
* Updates the example casks in the documentation to include ones containing all required stanzas
Closes #16342.
> create: modify cask template

- Library/Homebrew/cleaner.rb
For https://github.com/Homebrew/brew/pull/16355#issuecomment-1860642797
-----
Needed by:
- https://github.com/Homebrew/homebrew-core/pull/157617
> cleaner: remove *.tbd

- .vscode/settings.json
VSCode keeps trying to change this file so: let's let it.
> vscode/settings: update shellcheck.

- Library/Homebrew/utils/pypi.rb
Sometimes the Python dependency tree will be impacted by the exact version of Python being used (most commonly relating to functionality provided/missing from stdlibs like `importlib-metadata` and `tomllib`)
-----
> utils/pypi: use python from formula

- Library/Homebrew/os/mac/pkgconfig/14/libcurl.pc
- Library/Homebrew/os/mac/pkgconfig/14/sqlite3.pc
> os/mac/pkgconfig/14: update for 14.2

- Library/Homebrew/dev-cmd/bottle.rb
- Library/Homebrew/download_strategy.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/software_spec.rb
- Library/Homebrew/test/bottle_filename_spec.rb
- Library/Homebrew/utils.rb
Intentionally lenient - no existing formula across any tap should notice any change here.
> Add consistent path validation

- Library/Homebrew/cask/audit.rb
-----
Allow more fine-grained control for excluding audits. For example, https://github.com/Homebrew/homebrew-cask/pull/163887 shouldn't use `ci-skip-livecheck` to skip the homepage audit when there isn't even a livecheck anymore.
> Split `https_availability` audit.

- docs/Homebrew-Governance.md
These are changes that were made in the [private repository mirror](https://github.com/Homebrew/homebrew-governance-private/blob/master/Homebrew-Governance.md) and either voted on by members already (where they were changes) or were agreed clarifications on existing policy.
CC @Homebrew/plc FYI
> docs/Homebrew-Governance: import changes.

- Library/Homebrew/brew.sh
- bin/brew
- Check for directory existing and directory being readable separately and print appropriate messages for each
- Make error messages more consistent
> Improve working directory error messages

- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/test/dev-cmd/audit_spec.rb
Separate this into two methods so we can have separate skips for each.
> formula_auditor: split `audit_revision_and_version_scheme`.

- package/scripts/postinstall
-----
Fixes https://github.com/orgs/Homebrew/discussions/5052.
> package/scripts/postinstall: fix permissions of `opt`

- Library/Homebrew/cmd/vendor-install.sh
The logic in #16495 wasn't quite right.
> cmd/vendor-install: fix some elses.

- Library/Homebrew/extend/os/mac/hardware/cpu.rb
- Library/Homebrew/hardware.rb
-----
This PR adds a check for virtualization, so we no longer have to use the `ENV["HOMEBREW_GITHUB_ACTIONS"]` hack to work around CI failures.
> hardware/cpu: add `virtualized?` check

- Library/Homebrew/cmd/vendor-install.sh
-----
Minor wording fix related to https://github.com/Homebrew/brew/pull/16495.
> cmd/vendor-install: adjust wording

- docs/Homebrew-brew-Maintainer-Guide.md
-----
https://github.com/Homebrew/brew/actions/runs/7596213836/job/20689665591?pr=16512
> docs/Maintainer-Guide: Fix BuildPulse links

- docs/Querying-Brew.md
-----
Per https://github.com/Homebrew/brew/pull/16531#discussion_r1466816033
> docs: drop example that requires `--eval-all`

- Library/Homebrew/cmd/list.rb
- Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
- Library/Homebrew/dev-cmd/generate-man-completions.rb
- Library/Homebrew/dev-cmd/update-license-data.rb
- Library/Homebrew/dev-cmd/update-maintainers.rb
- Library/Homebrew/dev-cmd/update-sponsors.rb
-----
Resolves https://github.com/Homebrew/brew/pull/16562#issuecomment-1920347184
I also audited the remaining commands, since this is the second failure of this shape
cc @Bo98
> Add SystemCommand::Mixin to all commands using system_command

- README.md
A corporate donor recently wasn't able to find a clear way to contact a Homebrew person to talk about a possible donation. They eventually found the OC contact us page, which is the best way to contact the PLC short without having a GitHub account and posting on an issue or Discussions.
Let's highlight the donations questions contact form specifically in this area that is the landing target for the donations link on https://brew.sh.
---
-----
> Point corporate donors toward our OC contact form

- Library/Homebrew/cask/cask_loader.rb
- Library/Homebrew/formulary.rb
-----
Fixes https://github.com/Homebrew/brew/issues/16628.
> Stop following recursive tap migrations.

- docs/Cask-Cookbook.md
* N/A
-----
This fixes what seems like a typo in the cask cookbook.
> Cookbook: the deleted → be deleted

- Library/Homebrew/cask/cask_loader.rb
- Library/Homebrew/cask/exceptions.rb
-----
Remove specific loaders for the default tap in favour of a single `FromNameLoader`.
> Simplify `CaskLoader` further.

- Library/Homebrew/dependency.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/software_spec.rb
> Refactor and add type signature for `uses_from_macos`.

- docs/Acceptable-Formulae.md
Resulting from discussion in https://github.com/Homebrew/homebrew-core/pull/162352
> Acceptable-Formulae: update static library guidance.

- Library/Homebrew/formula_auditor.rb
> Fix duplicate quotes in dependency audit.

- Library/Homebrew/formula_creator.rb
The proper fix for #16675.
-----
> formula_creator: Fix GitHub parsing when name doesn't match URL

- Library/Homebrew/tap.rb
-----
Fixes https://github.com/Homebrew/brew/issues/16682.
> Fix `Tap#alias_table` when using the API.

- Library/Homebrew/formula_creator.rb
-----
As discussed in https://github.com/Homebrew/brew/pull/16692#issuecomment-1950247639.
> formula_creator: remove `ENV.deparallelize` suggestion

- .devcontainer/on-create-command.sh
This has been broken for quite some time.
> devcontainer: fix creation error

- Library/Homebrew/cmd/readall.rb
- Library/Homebrew/tap.rb
-----
Extracted from https://github.com/Homebrew/brew/pull/16710 for easier review.
> Support `Tap#formula_files` when using API.

- Library/Homebrew/diagnostic.rb
- Library/Homebrew/tap.rb
-----
Extracted from https://github.com/Homebrew/brew/pull/16710 for easier review.
> Support `Tap#cask_files` when using API.

- Library/Homebrew/utils/pypi.rb
-----
This fixes the resource detection when formula has Python packages that are not compatible with current aliased python formula, e.g. `awscli`
Also switch to `opt_libexec` path to ignore Python formula patch version and revision bump differences.
---
Originally hit when working on https://github.com/Homebrew/homebrew-core/pull/163705, e.g.
```console
❯ brew update-python-resources awscli
==> Retrieving PyPI dependencies for "https://github.com/aws/aws-cli/archive/refs/tags/2.15.22.tar.gz
==> Retrieving PyPI dependencies for excluded ""...
Error: Unable to determine metadata for "https://github.com/aws/aws-cli/archive/refs/tags/2.15.22.tar.gz" because of a failure when running
`/opt/homebrew/opt/python@3.12/bin/python3 -m pip install -q --no-deps --dry-run --ignore-installed --report …
```
> utils/pypi: use python from formula for non-pypi url metadata

- Library/Homebrew/api/formula.rb
- Library/Homebrew/cleanup.rb
- Library/Homebrew/diagnostic.rb
- Library/Homebrew/exceptions.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/tap_constants.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/test/formulary_spec.rb
-----
Re-reverts https://github.com/Homebrew/brew/pull/16684 and fixes https://github.com/Homebrew/homebrew-core/issues/162946.
Also depends on the fix in https://github.com/Homebrew/brew/pull/16688.
> Reapply "Refactor `Formulary::loader_for`."

- Library/Homebrew/deprecate_disable.rb
-----
Will be used for: https://github.com/Homebrew/homebrew-cask/pull/167590
And cases for where the cask no longer meets the "acceptable casks" criteria.
> deprecate_disable: add `no_longer_meets_criteria` deprecate/disable reason

- Library/Homebrew/cmd/tap.rb
- Library/Homebrew/tap.rb
-----
Fixes https://github.com/Homebrew/brew/issues/16761.
> Only show installed taps in `brew tap` output.

- Library/Homebrew/tap.rb
> Add signature for `Tap#config`.

- Library/Homebrew/tap.rb
> Actually return `super` in `CoreTap#remote`.

- Library/Homebrew/tap.rb
> Actually cache `Tap` methods.

- Library/Homebrew/cli/named_args.rb
-----
Don't show migration/rename warning while checking if a cask exists.
> Don't warn while checking for conflicting casks.

- Library/Homebrew/tap.rb
- Library/Homebrew/test/tap_spec.rb
-----
Only allow `Symbol`s for keys and booleans as values.
> Simplify `TapConfig`.

- Library/Homebrew/tap.rb
> Actually clear all tap caches.

- Library/Homebrew/extend/os/mac/diagnostic.rb
> Emit more specific error text on outdated Xcode

- Library/Homebrew/cleaner.rb
- Library/Homebrew/extend/os/linux/cleaner.rb
- Library/Homebrew/extend/os/mac/cleaner.rb
> cleaner: add types

- Library/Homebrew/cleanup.rb
- Library/Homebrew/test/cleanup_spec.rb
This allows dry-run to display any directories that will be removed as a result of previous removal steps.
-----
Just to make `--dry-run` closer to actual removals.
> cleanup: track removed links & dirs during dry-run

- Library/Homebrew/cask/cask_loader.rb
-----
Missed in https://github.com/Homebrew/brew/pull/16839.
> Actually remove `FromDefaultNameLoader`.

- Library/Homebrew/utils/github.rb
Only an issue in certain call paths.
> utils/github: fix variable scope

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
For now, restrict to partial version excluding the last part, i.e. version with major.minor.patch will result in attempting to replace any occurrences of "/#{major}.#{minor}/" or "/v#{major}.#{minor}/".
This should take care of common situations like GNOME, KDE, and SourceForge URLs. It should also help with URLs like `util-linux`.
It may result in incorrect replacements if URL has partial version based on another versioning scheme like the API version or if there are some equivalent numbers in URL that happen to match
-----
Could go stricter or looser in restrictions. Not sure if any incorrect replacements yet.
This won't handle formulae like:
- `mysql` - https://cdn.mysql.com/Downloads/MySQL-8.3/mysql-boost-8.3.0.tar.gz
- `rtf2latex2e` - …
> dev-cmd/bump-formula-pr: replace partial version in URL

- Library/Homebrew/test/utils/github_spec.rb
> test/utils/github_spec: filter further to fix test failure

- Library/Homebrew/cask/cask.rb
- Library/Homebrew/test/api/cask_spec.rb
- Library/Homebrew/test/cask/cask_spec.rb
- Library/Homebrew/test/support/fixtures/cask/everything.json
Fixes https://github.com/Homebrew/homebrew-cask/issues/169430
> Fix cask source checksum handling

- Library/Homebrew/dev-cmd/bump.rb
Fixes https://github.com/Homebrew/brew/issues/16913
> dev-cmd/bump: handle no formula tap case.

- Library/Homebrew/extend/os/mac/formula_cellar_checks.rb
- Library/Homebrew/formula_cellar_checks.rb
> formula_cellar_checks: add more types

- Library/Homebrew/utils/github/api.rb
fix #16978
regex suggested by @Bo98
I confirmed that this fix works by running `brew bump-formula-pr` locally with `$HOMEBREW_GITHUB_API_TOKEN` set to my fine-grained PAT, and it worked:
<details><summary>logs</summary>
```console
brew bump-formula-pr \
--no-audit \
--no-browse \
--no-fork \
--message "scripts 0.5.1" \
--tag "v0.5.1" \
--revision "$(git rev-parse HEAD)" \
--force \
bartekpacia/homebrew-tools/scripts
==> replace /tag:(\s+")v0.5.0(?=")/ with "tag:\\1v0.5.1\\2"
==> replace "a8de90aae81ac40a479ab65b2298412478acb297" with "6b5ff905e880bcc4002a992c0034dfe6bc525419"
==> Skipping `brew audit`
M	Formula/scripts.rb
Switched to a new branch 'bump-scripts-0.5.1'
[bump-scripts-0.5.1 ed068eb] scripts 0.5.1
1 file changed, 1 insertion(+), 1 deletion(-)
remote:
remote: Create a pull …
```
> make fine-grained PATs work as $HOMEBREW_GITHUB_API_TOKEN

- Library/Homebrew/cleanup.rb
* Bottle manifests are difficult to determine whether they're outdated so we will now only remove them when the formula is up-to-date. When up-to-date, we will get the latest manifest version and compare like that.
* For bottles themselves, adjust formula version check to use `pkg_version` as this is actually how it was always parsed and we were never checking the right one.
> cleanup: handle some edge cases

- Library/Homebrew/deprecate_disable.rb
> deprecate_disable: add unsigned reason

- Library/Homebrew/brew.rb
We don't want to print the report/do not report messages for these.
Thanks @cho-m for spotting this in https://github.com/Homebrew/brew/pull/17003#discussion_r1550247790
> brew.rb: restore old runtime error handling.

- docs/Homebrew-homebrew-core-Maintainer-Guide.md
> docs: update info as `linux-only` labels are automerged

- Library/Homebrew/github_runner_matrix.rb
-----
Also, we don't build for Big Sur anymore, so remove the special case for
Big Sur timeouts here.
> github_runner_matrix: support GitHub-hosted M1 macOS runners

- Library/Homebrew/cask/list.rb
- Library/Homebrew/cask/pkg.rb
- Library/Homebrew/cleanup.rb
- Library/Homebrew/cli/parser.rb
- Library/Homebrew/cmd/leaves.rb
- Library/Homebrew/commands.rb
- Library/Homebrew/diagnostic.rb
- Library/Homebrew/manpages.rb
- Library/Homebrew/os/mac/mach.rb
- Library/Homebrew/service.rb
- Library/Homebrew/tap.rb
-----
Some add'l conversions that I missed in https://github.com/Homebrew/brew/pull/16807
I also discovered via https://github.com/Homebrew/brew/pull/17030 that this style is required for `strict` typing
> Prefer numbered block params over proc conversion, cont'd

- docs/Adding-Software-to-Homebrew.md
Aligns examples with preferences observed by current maintainers.
-----
Aligns examples with preferences observed by current maintainers.
`brew typecheck` on arm64 led me to this bug https://github.com/sorbet/sorbet/issues/6778.
> docs: update examples of good commit summaries

- Library/Homebrew/cask/info.rb
- Library/Homebrew/cmd/info.rb
- Library/Homebrew/cmd/tap-info.rb
-----
Fixes https://github.com/Homebrew/brew/issues/17050
> cmd, cask: info prints whether installed

- docs/Python-for-Formula-Authors.md
* Reapply dropped commit in https://github.com/Homebrew/brew/pull/16643
* Change bindings example as `protobuf` no longer has any
* Remove `name "foo"` in example
* Replace `Language::Python.setup_install_args` example with `pip`
* Add some hints for CMake and autotools scripts given common issue of incorrect Python selection due to allowing multiple Python deps
* Add note that `.pth` files should be avoided due to contamination
-----
> docs(Python): reapply suggestions and update outdated info

- docs/Installation.md
-----
To match documentation in https://github.com/Homebrew/install?tab=readme-ov-file#install-homebrew-on-macos-or-linux
> docs/Installation: use HEAD similar to install repo README.md

- Library/Homebrew/exceptions.rb
- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/system_command.rb
- Library/Homebrew/utils/formatter.rb
-----
Follow-up to https://github.com/Homebrew/brew/pull/17128 with some more internal APIs.
> Explicitly mark non-public APIs.

- Library/Homebrew/formula.rb
- Library/Homebrew/language/node.rb
---
This reverts commit abf8df38661c4b60f122336d3db3a1a810d3a0e8.
Trying #17116 again after re-scoping to the `install` block (which was the original intention)
Sanity check:
```console
brew reinstall -s helm gitlab-ci-local && brew test helm gitlab-ci-local
```
> Reapply "formula: configure git/npm to ignore .brew_home"

- Library/Homebrew/os/linux/kernel.rb
> os/linux/kernel: enable strict typing

- Library/Homebrew/checksum.rb
> checksum: enable strict typing

- Library/Homebrew/cmd/nodenv-sync.rb
- Library/Homebrew/cmd/pyenv-sync.rb
- Library/Homebrew/cmd/rbenv-sync.rb
-----
If a user already has an existing version installed, let's avoid
deleting it.
> cmd/*-sync: avoid clobbering existing user installations

- Library/Homebrew/extend/ENV/shared.rb
- Library/Homebrew/test/ENV_spec.rb
> Remove unused private method.

- Library/Homebrew/utils/analytics.rb
https://github.com/Homebrew/brew/pull/17154#discussion_r1581102553 was ignored by auto-merge, whoops.
> utils/analytics: revert a test-bot analytics change.

- Library/Homebrew/utils/gzip.rb
> utils/gzip: enable strict typing

- Library/Homebrew/cleanup.rb
- Library/Homebrew/cli/named_args.rb
- Library/Homebrew/cmd/info.rb
- Library/Homebrew/cmd/leaves.rb
- Library/Homebrew/cmd/update-report.rb
- Library/Homebrew/dev-cmd/bottle.rb
- Library/Homebrew/diagnostic.rb
- Library/Homebrew/extend/os/linux/cmd/update-report.rb
- Library/Homebrew/extend/os/mac/formula_cellar_checks.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/install.rb
- Library/Homebrew/keg.rb
- Library/Homebrew/linkage_checker.rb
- Library/Homebrew/migrator.rb
- Library/Homebrew/reinstall.rb
- Library/Homebrew/tab.rb
- Library/Homebrew/test/formula_installer_bottle_spec.rb
- Library/Homebrew/test/formula_installer_spec.rb
- Library/Homebrew/test/installed_dependents_spec.rb
- Library/Homebrew/test/utils/autoremove_spec.rb
- Library/Homebrew/upgrade.rb
- Library/Homebrew/utils/autoremove.rb
- Library/Homebrew/utils/bottles.rb
> Document `Tab.for_keg` and use `Keg#tab` where possible.

- Library/Homebrew/brew.sh
When doing an `install`, `outdated` or `upgrade` and referring to a formula or cask in a specific tap: you probably want to get the latest version of that formula/cask more often than the default 1 or 24 hours.
Let's check for arguments for these commands that look appropriate and auto-update every 5 minutes in that case.
> brew.sh: auto-update 3rd-party taps more often.

- docs/Formula-Cookbook.md
-----
I have checked some of the above despite this being doc-only (so no actual tests, sorry), since I don't want to anger the bot that will read this first.
> Cookbook document what `Operation not permitted` means

- Library/Homebrew/cmd/leaves.rb
-----
Follow-up to #17168.
Fixes #17199.
> cmd/leaves: fix an `undefined method` error

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/test/cask/cask_loader/from_api_loader_spec.rb
-----
This PR removes a few audit exceptions and one final reference to Homebrew/cask-versions.
> various: remove remaining Homebrew/cask-versions references

- docs/Cask-Cookbook.md
-----
This suggests some documentation improvements for `token` selection for versioned/development channel casks.
> docs/cask-cookbook: token examples for versioned/development casks

- Library/Homebrew/dev-cmd/generate-cask-api.rb
-----
Generate `cask_canonical.json` for [formulae.brew.sh](http://formulae.brew.sh/) alongside `formula_canonical.json`.
> cmd/generate-cask-api: include cask renames

- Library/Homebrew/formula.rb
- Library/Homebrew/software_spec.rb
- Library/Homebrew/sorbet/rbi/parlour.rbi
-----
Follow-up to https://github.com/Homebrew/brew/pull/17211.
> Add `resource` signature.

- Library/Homebrew/cask/installer.rb
- Library/Homebrew/env_config.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/env_config.rbi
- Library/Homebrew/tap.rb
- Library/Homebrew/test/cask/installer_spec.rb
- Library/Homebrew/test/formula_installer_spec.rb
- Library/Homebrew/test/tap_spec.rb
-----
This is the inverse of `HOMEBREW_FORBIDDEN_TAPS`.
> env_config: add `HOMEBREW_ALLOWED_TAPS`

- Library/Homebrew/tap.rb
-----
Per this suggestion: https://github.com/Homebrew/brew/pull/17227#discussion_r1590630520
CC: @MikeMcQuaid
> tap: update core tap --force messaging

- Library/Homebrew/github_runner_matrix.rb
-----
This is needed after Homebrew/ci-orchestrator#13.
> github_runner_matrix: support orchestrator long build queues

- Library/Homebrew/install.rb
Reverts Homebrew/brew#6464
Fixes https://github.com/Homebrew/brew/issues/17267
> Revert "Create '.keepme' files in directories"

- Library/Homebrew/tap.rb
-----
Matching these for consistency.
> tap: adjust font cask path

- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/utils/github.rb
> various: fix minor typos

- .github/workflows/docker.yml
> Add Ubuntu 24.04 Docker image

- Library/Homebrew/messages.rb
- Library/Homebrew/test/messages_spec.rb
> messages: enable strict typing

- .devcontainer/devcontainer.json
- .devcontainer/ubuntu18.04/devcontainer.json
I added all extensions from `.vscode/extensions.json` to `devcontainer.json` so that they are preinstalled in **Codespace**
> Added a list of extensions to pre-install in Codespaces

- Library/Homebrew/utils/gems.rb
Take two at https://github.com/Homebrew/brew/pull/17304 with the correct variable name this time.
Fixes #17276.
> utils/gems: use BUNDLE_USER_CACHE instead of BUNDLE_CACHE_PATH.

- Library/Homebrew/cleanup.rb
- Library/Homebrew/cmd/uninstall.rb
- Library/Homebrew/env_config.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/env_config.rbi
- docs/Manpage.md
- manpages/brew.1
Reverts Homebrew/brew#17364
Reverting this until we have more discussion during the week.
> Revert "Revert "Enable HOMEBREW_AUTOREMOVE by autoremove_default""

- Library/Homebrew/sbom.rb
This breaks the possibility for some `:all` bottle creation if they reference a non-`:all` bottle as a dependency.
Instead, omit this information in the bottle and generate it only at install time.
> sbom: fix dependency bottle information in SBOM.

- Library/Homebrew/style.rb
It feels nice to also be running this as part of `brew style` checks and, indirectly, `brew test-bot` tap syntax checks.
> style: run actionlint.

- Library/Homebrew/os/mac.rb
Thanks @Bo98 for suggesting this approach in https://github.com/Homebrew/brew/pull/17376#issuecomment-2135164831
Closes #17375.
Closes #17376 (as it replaces it).
> os/mac: fix fetching Linux bottles on macOS

- Library/Homebrew/style.rb
- docs/.rubocop.yml
- docs/Brew-Livecheck.md
- docs/External-Commands.md
Extracted from https://github.com/Homebrew/brew/pull/17482
> docs: fix `brew style`

- docs/Homebrew-Governance.md
-----
- [The Open Collective Foundation is dissolving](https://opencollective.com/foundation/updates/announcement-we-are-dissolving-open-collective-foundation-at-the-end-of-this-year).
- So we spent the money that we had in the 501(c)3 that it was holding.
- Tell people to submit future expenses to the 501(c)6.
> Homebrew-Governance: Our 501(c)3 is empty

- Library/Homebrew/dev-cmd/bottle.rb
- Library/Homebrew/github_packages.rb
> bottle/github_packages: include path_exec_files, all_files.

- Library/Homebrew/dev-cmd/bottle.rb
- Library/Homebrew/github_packages.rb
Reverts Homebrew/brew#17518
Bottle publishing is failing.
> Revert "bottle/github_packages: include path_exec_files, all_files."

- Library/Homebrew/formula_auditor.rb
-----
This is not relevant information for third-party taps and requires network requests to `endoflife.date` so it's best to avoid them in this case.
Closes https://github.com/Homebrew/brew/issues/17531
CC: @colindean
> formula_auditor: scope eol check to core tap

- docs/Gems,-Eggs-and-Perl-Modules.md
Noticed this while reading the docs, thought I might as well open a quick PR.
> docs/Gems,-Eggs-and-Perl-Modules: fix typo.

- Library/Homebrew/brew.rb
- Library/Homebrew/cmd/command.rb
- Library/Homebrew/cmd/options.rb
Clarify it is a `brew` command.
Fixes #17627
> Improve "unknown command" error

- Library/Homebrew/dev-cmd/extract.rb
> extract: Fix missing '--git-revision' in the usage banner

- Library/Homebrew/unpack_strategy/dmg.rb
-----
- I missed this in #17636, whoops.
> unpack_strategy/dmg: Convert to Sorbet `typed: strict`

- .github/workflows/vendor-gems.yml
-----
See also: Homebrew/actions#562.
> workflows/vendor-gems: handle input string more robustly

- .github/maintainers.json
- Library/Homebrew/dev-cmd/update-maintainers.rb
- Library/Homebrew/startup/config.rb
This will no longer be needed or used after the merge of https://github.com/Homebrew/homebrew-test-bot/pull/1142
> Remove maintainers.json

- Library/Homebrew/global.rb
Fixes https://github.com/Homebrew/brew/issues/17723
> global: fix require order.

- Library/Homebrew/sandbox.rb
- Library/Homebrew/test/sandbox_spec.rb
> sandbox: deny signal to other processes

- .github/workflows/tests.yml
-----
Like https://github.com/Homebrew/homebrew-core/pull/177326.
> workflows/tests: enable attestations

- Library/Homebrew/global.rb
Fixes https://github.com/Homebrew/brew/pull/17730#issuecomment-2227430748
> global: more require ordering fixes.

- Library/Homebrew/dev-cmd/bottle.rb
> dev-cmd/bottle: add missing require.

- Library/Homebrew/dev-cmd/pr-publish.rb
Seen in https://github.com/Homebrew/homebrew-core/actions/runs/9930266134/job/27428795730.
> dev-cmd/pr-publish: add missing require

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
Fixes https://github.com/Homebrew/homebrew-core/actions/runs/9931895403/job/27432438142#step:6:716.
> dev-cmd/bump-formula-pr: fix missing `require`

- Library/Homebrew/cmd/tap.rb
-----
Fixes https://github.com/orgs/Homebrew/discussions/5492
> cmd/tap: add missing require

- Library/Homebrew/formula.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/sandbox.rb
> Add deny_signal method

- Library/Homebrew/utils/analytics.rb
The regex stopped at the first newline.
> utils/analytics: fix handling of newlines

- docs/How-To-Open-a-Homebrew-Pull-Request.md
Add links to Manpage for the commands `bump-formula-pr` and `bump-cask-pr`.
-----
> Update How-To-Open-a-Homebrew-Pull-Request.md: add links to Manpage

- docs/Brew-Livecheck.md
Add examples for modifying version information, as there is no information about this in the documentation.
- https://github.com/homebrew/brew/issues/10866#issuecomment-804090944
- https://github.com/Homebrew/homebrew-cask/blob/5d2fa32d67e525794d765f2b7927159b447a1d41/Casks/e/evernote.rb#L41-L48
- GitHub code search for: [`"strategy :electron_builder do"`](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+%22strategy+%3Aelectron_builder+do%22&type=code)
-----
> Update Brew-Livecheck.md: add examples for modify version information

- Library/Homebrew/attestation.rb
- Library/Homebrew/cmd/install.rb
- Library/Homebrew/cmd/reinstall.rb
- Library/Homebrew/cmd/upgrade.rb
- Library/Homebrew/test/attestation_spec.rb
-----
Note: This bug only affects `brew upgrade gh ...`.
The `Homebrew::CLI::NamedArgs` class often returns frozen arrays so this one cannot be easily modified in-place here. We just overwrite it instead.
I also updated the `brew reinstall` command logic to match for consistency.
```console
$ brew upgrade gh --verbose --debug
...
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gh
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gh
Error: can't modify frozen Array: [#<Formula gh (stable) /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/g/gh.rb>]
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:139:in `delete'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:139:in `run' …
```
> Avoid frozen array errors in `brew upgrade`

- Library/Homebrew/download_strategy.rb
Sounds like this bug has been going on for a while unreported.
When projects are moved to the Attic, `closer.lua` will redirect to a HTML page by default. We're however not a web browser so instead we should check `in_attic` that Apache provides and for those projects redirect to `archive.apache.org` where the original source tarball remains available.
https://github.com/Homebrew/homebrew-core/pull/178118
> download_strategy: fix handling of Apache projects moved to Attic

- Library/Homebrew/cask/dsl/caveats.rb
-----
Closes https://github.com/Homebrew/brew/issues/17843
Related: https://github.com/Homebrew/brew/pull/17659
> cask/dsl/caveats: fix conditional

- Library/Homebrew/cmd/--repository.sh
- Library/Homebrew/test/cmd/--repository_spec.rb
> cmd/--repository: fix homebrew- prefix handling

- Library/Homebrew/utils/github/api.rb
> utils/github/api: handle systems with misconfigured NSS

- Library/Homebrew/cli/named_args.rb
Let's make these more tightly scoped instead.
Improved version of https://github.com/Homebrew/brew/pull/17809
> cli/named_args: improve missing_formula requires.

- Library/Homebrew/livecheck/livecheck.rb
Indeed 2 lines edited in the `Livecheck.rb` file even if I am not familar with rb code
When trying a head-only formula, version is a string (git tag or equiv) and cannot been build as Version for comparison (fails when creating Version from string)
Not exactly, just using one of my sandbox formula available here:
(https://github.com/sazriel26/homebrew-sandbox/blob/HEAD/Formula/harview.rb)
```
1334 files inspected, no offenses detected
```
```
No errors! Great job.
```
-----
> [livecheck] Help to check head only formulae

- Library/Homebrew/attestation.rb
-----
This fixes the attestation error reported in https://github.com/Homebrew/homebrew-core/issues/178345 and https://github.com/Homebrew/homebrew-core/issues/177384#issuecomment-2251979030, wherein users with a custom bottle domain set (e.g. for third-party mirrors) fail to verify backfilled attestations due to `bottle.url` not being the expected value.
We correct this by recomputing the expected upstream mirror URL and hashing that instead; this has no security implications, as we do this after already verifying the signature on the bottle itself and are merely matching the mirrored filename to the expected subject.
> attestation: handle mirrored bottles correctly

- Library/Homebrew/dev-cmd/release.rb
Trying to make a new release and bumped into this 🤦🏻
> dev-cmd/release: add missing require.

- Library/Homebrew/upgrade.rb
Apply the previous fix in #17799 to the dependent upgrade scenario by deduplicating the code.
Fixes #17906.
> upgrade: fix missed upgrades when an alias is changed to a formula

- Library/Homebrew/extend/ENV/super.rb
- Library/Homebrew/extend/os/mac/extend/ENV/super.rb
- Library/Homebrew/shims/super/cc
> shims/super/cc: pass `-ld_classic` if needed for `-dead_strip_dylibs`

- Library/Homebrew/data/schemas/sbom.spdx.schema.3.json
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/sbom.rb
- Library/Homebrew/test/formula_installer_spec.rb
- Library/Homebrew/test/sbom_spec.rb
This is a core part of our CI now. We don't want the remote end changing under us randomly. Vendor it properly with CI testing.
> Vendor SBOM schema

- Library/Homebrew/cask/artifact/installer.rb
- Library/Homebrew/cask/artifact/installer.rbi
- Library/Homebrew/cask/upgrade.rb
- Library/Homebrew/test/cask/dsl_spec.rb
> Revert "Make Cask::Artifact::Installer typesafe"

- Library/Homebrew/formula_name_cask_token_auditor.rb
> formula_name_cask_token_auditor: use `typed: strict`

- Library/Homebrew/api/download.rb
> download: use `typed: strict`

- Library/Homebrew/extend/io.rb
> extend/io: use `typed: strict`

- .devcontainer/devcontainer.json
- .devcontainer/ubuntu18.04/devcontainer.json
-----
Follow-up to <https://github.com/Homebrew/brew/pull/18026>
This PR updates the dev containers to use the new extensions added recently to the VS Code configuration
> Update dev container recommended extensions

- Library/Homebrew/cleaner.rb
> cleaner: use `typed: strict`

- Library/.rubocop.yml
- Library/Homebrew/cask/cask_loader.rb
- Library/Homebrew/cask/url.rb
- Library/Homebrew/cmd/home.rb
- Library/Homebrew/dev-cmd/tests.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/source_location.rb
- Library/Homebrew/version.rb
-----
Mostly, this consists of removing unnecessary use of `T.unsafe`. I'll add comments for the exceptions.
> Minor type safety improvements

- Library/Homebrew/macos_version.rbi
- Library/Homebrew/os/mac/mach.rbi
- Library/Homebrew/rubocops/shared/helper_functions.rbi
- Library/Homebrew/utils/service.rbi
These ones appear to not fail when removed.
> Remove some unnecessary `include Kernel`

- Library/Homebrew/upgrade.rb
- Library/Homebrew/upgrade.rbi
> upgrade: remove `module_function`

- Library/Homebrew/api/analytics.rb
> api/analytics: use `typed: strict`

- Library/Homebrew/cmd/list.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/cmd/list.rbi
- Library/Homebrew/test/sorbet/tapioca/compilers/args_spec.rb
-----
This is useful for keeping track of formulae installed from source while contributing to taps such as homebrew/core
> cmd/list: add `--poured-from-bottle` and `--built-from-source`

- Library/Homebrew/formula_auditor.rb
-----
Seen at Homebrew/homebrew-core#182065.
https://github.com/Homebrew/homebrew-core/actions/runs/10522724092/job/29156069899?pr=182065#step:3:44
> formula_auditor: fix typechecking failure

- docs/Homebrew-on-Linux.md
-----
`NOTICE` is not one of GitHub's keywords - https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
Went with closest option `NOTE`.
> docs: use NOTE rather than NOTICE

- Library/Homebrew/dev-cmd/bottle.rb
> dev-cmd/bottle: use default tar when bottling `gnu-tar`

- Library/Homebrew/brew.sh
-----
We don't need these, so let's remove them.
> brew.sh: remove some shellcheck disables

- Library/Homebrew/utils/github.rb
> utils/github: a few more simplifications

- Library/Homebrew/utils/helpers.sh
-----
I don't think we need this.
> utils/helpers.sh: remove a shellcheck disable

- Library/Homebrew/utils/github/api.rb
-----
Our updating sponsors/maintainers/etc workflow is broken.
Let's add some debug output to help me fix it.
> utils/github/api: add debug output for `open_graphql`

- Library/Homebrew/utils/github.rb
This fixes the failure in our sponsorships workflow.
> utils/github: fix sponsorships GraphQL query

- Library/Homebrew/brew.sh
- Library/Homebrew/cmd/shellenv.sh
Reverts Homebrew/brew#18188
This needs to wait a bit before we can roll it out again.
> Revert "cmd/shellenv: improve for newer macOS using `/usr/libexec/path_helper`"

- Library/Homebrew/list.sh
- Library/Homebrew/utils/helpers.sh
> list.sh: support column output

- Library/Homebrew/github_packages.rb
> github_packages: use full license only if within limit

- .github/workflows/tests.yml
> Fix macOS update-test name

- Library/Homebrew/formula_installer.rb
-----
relates to https://github.com/Homebrew/brew/issues/17297 https://github.com/Homebrew/brew/issues/17998
> Enable strict typing in FormulaInstaller

- Library/Homebrew/cmd/shellenv.sh
> shellenv: silence errors from writing to `HOMEBREW_PATHS_FILE`

- Library/Homebrew/software_spec.rb
> software_spec: fix invalid manifest handling

- Library/Homebrew/formula_installer.rb
> formula_installer: fix fetch call

- Library/Homebrew/cli/named_args.rb
-----
Let's also show users the right way to silence this message.
Follow-up to #18330.
> cli/named_args: update `package_conflicts_message`

- .github/workflows/sponsors-maintainers-man-completions.yml
https://github.com/Homebrew/brew/actions/runs/11012718453/job/30579518221#step:6:106
> sponsors-maintainers-man-completions: fix unbound variable

- Library/Homebrew/test/support/lib/startup/config.rb
-----
Two bytes should hopefully be plenty.
> tests: add an extra byte of randomness

- docs/Cask-Cookbook.md
-----
Had to ban `shotcut`'s upstream for abuse, so I'd prefer us to switch this example to a less hostile upstream.
> Cask-Cookbook: update `verified` example

- Library/Homebrew/PATH.rb
-----
Based on https://sorbet.org/docs/stdlib-generics#implementing-the-enumerable-interface
> PATH: `typed: strict`

- Library/Homebrew/unpack_strategy/dmg.rb
> unpack_strategy/dmg: more UID handling fixes

- Library/Homebrew/tap.rb
> tap: restore old `repo` key

- Library/Homebrew/shims/super/cc
-----
This will prevent my editor from trying to read this file as shell
script and getting the syntax highlighting all wrong.
> shims/super/cc: add modeline for vim-like editors

- Library/Homebrew/os/linux/elf.rb
> os/linux/elf: fix arch compat check on ppc

- Library/Homebrew/extend/os/mac/keg.rb
- Library/Homebrew/keg.rb
-----
The follow-up to https://github.com/Homebrew/brew/pull/18517, removing the remaining removable constants.
> Remove removable constants

- Library/Homebrew/test/utils/github_spec.rb
-----
This does the same as dcba7f356d (#15619) and unblocks CI.
> test/utils/github_spec: fix artifact URL test

- Library/Homebrew/extend/kernel.rb
Fixes https://github.com/orgs/Homebrew/discussions/5674
> extend/kernel: fix error on early deprecations

- Library/Homebrew/language/java.rb
-----
Updating docs at https://rubydoc.brew.sh/Language/Java.html for methods we typically use in formulae.
> language/java: document public API

- .github/workflows/codeql-analysis.yml
- .github/workflows/docs.yml
- .github/workflows/rubydoc.yml
-----
Fixes https://github.com/Homebrew/brew/security/code-scanning/32
Fixes https://github.com/Homebrew/brew/security/code-scanning/33
Fixes https://github.com/Homebrew/brew/security/code-scanning/42
> workflows: fix `artipacked` warning

- Library/Homebrew/cask/config.rb
- Library/Homebrew/test/cask/config_spec.rb
-----
solved `# todo` in https://github.com/Homebrew/brew/blob/4.4.3/Library/Homebrew/cask/config.rb#L195 because of https://github.com/Homebrew/homebrew-bundle/pull/1476
> remove Cask::Config.explicit_s

- Library/Homebrew/language/python.rb
-----
Previous logic would add dependencies that were unnecessary to `homebrew_deps.pth` file like:
* `uses_from_macos "libxml2"` - brew has bindings, but macOS does not. This is pretty common dependency due to `lxml` (which only needs C library).
* Recursive dependencies that aren't "connected" via python bindings. If `a` depends on  `b` depends on `c`, then even if `c` has python bindings, they are unnecessary if `b` doesn't have bindings. 
* This doesn't handle case where `b` and `c` have bindings but `b` doesn't use `c`'s bindings. However, this situation is more tedious to deal with so ignoring for now.
The extra dependencies makes it harder to create `all` bottles.
> language/python: reduce dependencies added to pth file

- Library/Homebrew/cmd/shellenv.sh
Reverts Homebrew/brew#18326
Fixes https://github.com/Homebrew/brew/issues/18643
@notfirefox sorry 😭
> Revert "cmd/shellenv: set `XDG_DATA_DIRS` on Linux"

- docs/Installation.md
-----
We only support devices running macOS on officially supported hardware. We encounter way too many issues from people using OpenCore Legacy Patcher, so let's note that it is unsupported.
> Installation: note that OpenCore is not supported

- Library/Homebrew/extend/os/mac/diagnostic.rb
-----
`nvram` vars are case-sensitive. 
```
% brew doctor check_for_opencore
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
Warning: You have booted macOS using OpenCore Legacy Patcher.
We do not provide support for this configuration.
...
```
> os/mac/diagnostic: fix case of OpenCore check

- Library/Homebrew/extend/os/mac/hardware/cpu.rb
- Library/Homebrew/test/hardware/cpu_spec.rb
> Add M4 processor

- Library/Homebrew/cask/caskroom.rb
- Library/Homebrew/cask/config.rb
- Library/Homebrew/cask/list.rb
- Library/Homebrew/rubocops/cask/constants/stanza.rb
- Library/Homebrew/rubocops/cask/mixin/cask_help.rb
- Library/Homebrew/rubocops/cask/shared_filelist_glob.rb
-----
- Let’s see what goes 💥.
> sorbet: Bump some Cask files to `typed: strict`

- Library/Homebrew/formula.rb
-----
Forgot to expose this in `Formula#inreplace`
> formula: expose inreplace global parameter

- Library/Homebrew/cmd/developer.rb
The handling of `HOMEBREW_UPDATE_TO_TAG` was incorrect as it implied it also enabled developer mode whereas the opposite was true.
> cmd/developer: fix HOMEBREW_UPDATE_TO_TAG handling.

- Library/Homebrew/extend/os/mac/hardware/cpu.rb
- Library/Homebrew/test/hardware/cpu_spec.rb
-----
Sources:
- https://github.com/AsahiLinux/docs/wiki/Codenames
- MacOSX15.2.sdk from Xcode 15.2 RC
> os/mac/hardware/cpu: add M4 Pro/Max

- bin/brew
> bin/brew: fix prioritisation of system env files

- .github/workflows/actionlint.yml
- .github/workflows/autogenerated-files.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/docs.yml
- .github/workflows/pkg-installer.yml
- .github/workflows/rubydoc.yml
- .github/workflows/sponsors-maintainers-man-completions.yml
- .github/workflows/tests.yml
- .github/workflows/vendor-gems.yml
-----
This helps with transparency and they get updated by Dependabot.
> workflows: use full version numbers

- .github/dependabot.yml
-----
We don't use this anywhere anymore.
> dependabot: remove lock-threads

- Library/Homebrew/Gemfile
- Library/Homebrew/Gemfile.lock
- Library/Homebrew/vendor/bundle/bundler/setup.rb
- Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/base64-0.2.0/LICENSE.txt
- Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/base64-0.2.0/lib/base64.rb
-----
I'm sure this will need more work, but wanted to get it kicked off.
> Vendor `base64` for Ruby 3.4

- Library/Homebrew/rubocops/cask/no_overrides.rb
- Library/Homebrew/rubocops/caveats.rb
- Library/Homebrew/test/cask/cask_loader_spec.rb
- Library/Homebrew/test/support/helper/cmd/brew-verify-undefined.rb
- Library/Homebrew/test/utils/ruby_check_version_script_spec.rb
> chore: fix typos

- Library/Homebrew/rubocops/cask/ast/cask_block.rb
- Library/Homebrew/rubocops/cask/desc.rb
- Library/Homebrew/rubocops/cask/homepage_url_styling.rb
- Library/Homebrew/rubocops/cask/mixin/on_url_stanza.rb
- Library/Homebrew/rubocops/cask/no_overrides.rb
- Library/Homebrew/rubocops/cask/on_system_conditionals.rb
- Library/Homebrew/rubocops/cask/url_legacy_comma_separators.rb
- Library/Homebrew/rubocops/install_bundler_gems.rb
- Library/Homebrew/rubocops/no_fileutils_rmrf.rb
-----
- I thought I already did these, but obviously not.
> Bump more RuboCops to Sorbet `typed: strict`

- Library/Homebrew/hardware.rb
-----
For M1 Pro/Max, some M2 Pro, and assorted configurations in x86_64.
> hardware: recognize 10 cores as deca

- docs/How-To-Open-a-Homebrew-Pull-Request.md
- [N/A] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [N/A] Have you successfully run `brew style` with your changes locally?
- [N/A] Have you successfully run `brew typecheck` with your changes locally?
-----
> Fix typo ("a new formulae" should be "a new formula")

- Library/Homebrew/utils/github.rb
- Library/Homebrew/utils/github/api.rb
-----
The key `type` is not included in the response, making the log look weird.
> utils/github: fix GraphQL error log

- Library/Homebrew/cmd/fetch.rb
- Library/Homebrew/utils/tty.rb
-----
Tracking Issue: https://github.com/Homebrew/brew/issues/18278
> Use full terminal height for concurrent output.

- Library/Homebrew/cmd/fetch.rb
-----
Tracking Issue: https://github.com/Homebrew/brew/issues/18278
> Print concurrent download errors.

- Library/Homebrew/vendor/portable-ruby-arm64-linux
> Add arm64 Linux build for Portable Ruby

- Library/Homebrew/dev-cmd/pr-upload.rb
- completions/fish/brew.fish
- completions/zsh/_brew
- docs/Manpage.md
- manpages/brew.1
These are not mutually exclusive under GitHub Packages.
> dev-cmd/pr-upload: allow --keep-old with --upload-only

- .github/workflows/schemas.yml
- .github/workflows/sorbet.yml
- .github/workflows/spdx.yml
- .github/workflows/sponsors-maintainers-man-completions.yml
- .github/workflows/vendor-gems.yml
-----
Switches to `ssh: true` for all commit signing in Homebrew/brew.
WIP.
> ci: switch to SSH signing everywhere

- docs/Rakefile
-----
- Part of https://github.com/Homebrew/brew/issues/19214.
- So we don't forget to add it to new docs we write.
> Enforce that all docs have `last_review_date` frontmatter

- Library/Homebrew/cmd/info.rb
> Revert "cmd/info: only display keg info if tap matches"

- Library/Homebrew/diagnostic.rb
Duplicate names across taps are a real pain to deal with, so let's warn the user.
Sample output:
```
% brew doctor
...
Warning: The following formulae have the same name as core formulae:
gromgit/boneyard/httping
gromgit/boneyard/multitail
gromgit/tools/lsdvd
gromgit/new-life/abcm2ps
dhth/tap/prs
int128/kubelogin/kubelogin
You will need to use their full names throughout Homebrew.
```
> diagnostics: add formula/cask dup check

- Library/Homebrew/diagnostic.rb
> diagnostic: recommend untap where possible

- Library/Homebrew/dev-cmd/update-python-resources.rb
Also favor Homebrew API over manual string comparison.
Resolves https://github.com/orgs/Homebrew/discussions/5967.
> update-python-resources: work on bare formula

- Library/Homebrew/diagnostic.rb
Followup to #19323. Resolves #19372.
> diagnostic: fix call to missing_dependencies

- Library/Homebrew/formula.rb
-----
Resolves https://github.com/Homebrew/brew/pull/19323/files#r1970356232
> fix: Revert breaking type change in Formula#std_npm_args

- Library/Homebrew/caveats.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/keg.rb
- Library/Homebrew/rubocops/lines.rb
- Library/Homebrew/test/caveats_spec.rb
- Library/Homebrew/test/utils/shell_spec.rb
- Library/Homebrew/utils/shell.rb
- docs/Shell-Completion.md
> Add PowerShell (pwsh) completion support

- Library/Homebrew/formula.rb
-----
Fixes https://github.com/Homebrew/brew/pull/19407#issuecomment-2694083829
> formula: remove `pwsh` from default completion shells

- Library/Homebrew/formula.rb
- docs/Formula-Cookbook.md
> docs: add a bit more information about `std_*_args` to Formula Cookbook

- Library/Homebrew/cmd/tap.rb
> cmd/tap: don't stacktrace on user error

- Library/Homebrew/diagnostic.rb
> diagnostic: enforce user_path_1 prerequisite

- .github/workflows/docker.yml
-----
Follow-up to #19480. Tags were being serialised in the wrong format.
This fixes that.
> workflows/docker: fix publishing Docker images (again)

- docs/Installation.md
-----
The post installation steps is missing a couple critical chars to make it functional (once path to brew install directory is updated).
> Fix typo in Installation.md

- docs/Common-Issues.md
This new part of documentation has been added in order to provide users a way to identify curl related issues which may or may not be caused by their workstation.
Fixes https://github.com/Homebrew/brew/issues/19216
> Add possible curl issues

- Library/Homebrew/brew.sh
- Library/Homebrew/bundle/commands/cleanup.rb
- Library/Homebrew/bundle/installer.rb
- Library/Homebrew/dev-cmd/tap-new.rb
- Library/Homebrew/test/bundle/commands/cleanup_spec.rb
- Library/Homebrew/test/spec_helper.rb
- docs/Common-Issues.md
- docs/Tips-N'-Tricks.md
Let's just call it `brew bundle` from now on as it's a normal command.
Also, fix a reference to "Homebrew Services" while we're here.
> Cleanup some missing references to Homebrew Bundle.

- Library/Homebrew/bundle/brew_services.rb
- Library/Homebrew/bundle/bundle.rb
- Library/Homebrew/test/bundle/brew_services_spec.rb
- Library/Homebrew/test/bundle/bundle_spec.rb
`brew services` is now always "installed".
> bundle: remove services_installed?

- Library/Homebrew/bundle/bundle.rb
- Library/Homebrew/bundle/commands/cleanup.rb
- Library/Homebrew/bundle/vscode_extension_dumper.rb
- Library/Homebrew/bundle/vscode_extension_installer.rb
- Library/Homebrew/cmd/bundle.rb
- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/test/bundle/commands/cleanup_spec.rb
- Library/Homebrew/test/bundle/vscode_extension_installer_spec.rb
- completions/fish/brew.fish
- completions/zsh/_brew
- docs/Manpage.md
- manpages/brew.1
We've had requests for this in Homebrew/bundle a few times so let's implement it both for there and for `brew edit`.
Tested on my machine with `cursor` and working as expected.
> Look for VSCode variants

- Library/Homebrew/shims/super/cc
> shims/super/cc: add comment for optimisation flag handling

- Library/Homebrew/formula_auditor.rb
> homepage audit: fix for gnu.org and nongnu.org

- Library/Homebrew/github_runner_matrix.rb
-----
This will help us avoid losing bottles on version bumps.
Also, let's do the same on Intel macOS 15 and newer. This is essentially
a simpler version of #18363. Instead of trying to use complicated
criteria or a DSL, let's just run the build on Intel macOS 15 if the
formula already has a `:sequoia` bottle.
> github_runner_matrix: deploy arm64 Linux runners on PRs with `:arm64_linux` bottles

- Library/Homebrew/bundle/dumper.rb
> Add brew_dumper.rb to dumper.rb file

- Library/Homebrew/test/bundle/commands/check_spec.rb
- Library/Homebrew/test/bundle/whalebrew_installer_spec.rb
See https://github.com/Homebrew/brew/actions/runs/14055694149/job/39354629119?pr=19597
> test/bundle: add more missing requires.

- Library/Homebrew/bundle/mac_app_store_checker.rb
- Library/Homebrew/test/bundle/commands/check_spec.rb
More missing requires that need added.
See https://github.com/Homebrew/brew/actions/runs/14061959609/job/39374858850?pr=19602
> test/bundle/commands/check_spec: add missing requires.

- Library/Homebrew/formula_creator.rb
> create: use GitHub project URL if homepage is empty

- docs/Support-Tiers.md
-----
Fixing the header above the examples.
> docs/Support-Tiers: update unsupported config examples

- .github/workflows/schemas.yml
- .github/workflows/sorbet.yml
- .github/workflows/spdx.yml
- .github/workflows/sponsors-maintainers-man-completions.yml
- .github/workflows/vendor-gems.yml
-----
Now that we've removed all the GPG code, this is a no-op.
> workflows: remove no-op ssh signing value

- Library/Homebrew/formula.rb
-----
The sentence needs a verb.
> formula: fix warning message grammar

- .github/workflows/docker.yml
- .github/workflows/tests.yml
- Library/Homebrew/attestation.rb
- Library/Homebrew/brew.rb
- Library/Homebrew/diagnostic.rb
- Library/Homebrew/exceptions.rb
- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/extend/os/linux/diagnostic.rb
- Library/Homebrew/extend/os/mac/diagnostic.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/install.rb
- Library/Homebrew/os.rb
- Library/Homebrew/utils/formatter.rb
Now that we have this nice URL let's reference it to allow our other messages to be a bit shorter/kinder.
I may have missed some places: shout if you can think of any more.
Fixes https://github.com/Homebrew/brew/issues/19248
> Link to Support Tiers in diagnostic/error messages

- Library/Homebrew/bundle/brew_installer.rb
- Library/Homebrew/test/bundle/brew_installer_spec.rb
- Library/Homebrew/test/bundle/commands/check_spec.rb
- Library/Homebrew/test/bundle/skipper_spec.rb
Add missing test coverage, requires, fix a TODO and remove `needs_macos` from some cask tests.
> test/bundle: add additional test coverage.

- Library/Homebrew/cask/audit.rb
-----
As seen in https://github.com/Homebrew/homebrew-cask/pull/207161 - when a Cask has an implied dependencies to unpack the container (the linked case a `7z` file requires `p7zip` to unpack), the installer method correctly installs the required dependency. `brew audit` has audits that manually unpack the container, which bypasses the check. 
This PR adds a check for any dependencies that are required to unpack the primary container.
I considered adding a check that would uninstall these dependencies after the audit (if required), but this should be picked up by `brew autoremove`.
-----
I'm making the assumption that only formula are being installed here.
> cask/audit: install container deps

- Library/Homebrew/bundle/commands/exec.rb
- Library/Homebrew/test/bundle/brew_services_spec.rb
- Library/Homebrew/test/bundle/commands/exec_spec.rb
This is quite hard to write tests for.
I tried I kept it integration-style (but not actually an integration test) because:
* It matches what the other exec tests do
* The order of operations is quite important
* It tests the actual API people use: `brew exec --services`
> bundle: add tests for `exec --services`

- Library/Homebrew/bundle/commands/exec.rb
- Library/Homebrew/test/bundle/commands/exec_spec.rb
> bundle: handle simultaneous `exec --services` better

- docs/Support-Tiers.md
-----
Went to change "setup" to "set up", but found this wording to be clearer.
> Support-Tiers: minor rewording

- README.md
> docs(readme): added shield and license link

- Library/Homebrew/extend/os/mac/diagnostic.rb
- Library/Homebrew/extend/os/mac/hardware/cpu.rb
- docs/Installation.md
- docs/Support-Tiers.md
-----
Clarifying OCLP support now that we have Support Tiers.
> docs: clarify OCLP support status

- docs/Installation.md
- docs/Support-Tiers.md
-----
Clarify OCLP tiers more based off #19748. Also fixes up some other wording.
> Support-Tiers: clarify OCLP tiers based on CPU generation

- Library/Homebrew/debrew.rb
Ruby 3.4 is dropping this as a default gem.
> debrew: migrate away from mutex_m

- Library/Homebrew/mktemp.rb
> mktemp: drop include FileUtils

- Library/Homebrew/api.rb
-----
We're vendoring this now for Ruby 3.4.
> api: remove TODO comment

- .github/workflows/pkg-installer.yml
-----
Explicitly declaring default permissions.
> workflows/pkg-installer: set default permissions

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/dev-cmd/bump.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/bump.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/bump_formula_pr.rbi
- Library/Homebrew/utils/github.rb
Reverts Homebrew/brew#19213
See errors discussed in Homebrew/brew#19213
> Revert "bump: bump synced formula together"

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/dev-cmd/bump.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/bump.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/bump_formula_pr.rbi
- Library/Homebrew/utils/github.rb
-----
Follow up to https://github.com/Homebrew/brew/pull/19213 and https://github.com/Homebrew/brew/pull/19797
@botantony Would you mind seeing if the changes work for you?
> bump: bump synced formula together (v2)

- Library/Homebrew/cmd/bundle.rb
- completions/bash/brew
- completions/fish/brew.fish
- completions/zsh/_brew
- docs/Manpage.md
- manpages/brew.1
This allows another way to pass `--services` to `brew bundle`.
> Add `HOMEBREW_BUNDLE_SERVICES` variable to `brew bundle`

- docs/Brew-Bundle-and-Brewfile.md
Felt some wording could be improved based on suggestions from @lukehefson.
> docs/Brew-Bundle-and-Brewfile: a couple of tweaks.

- Library/Homebrew/brew.sh
- Library/Homebrew/env_config.rb
- docs/Manpage.md
- manpages/brew.1
Continuation of https://github.com/Homebrew/brew/pull/19038 with suggestion applied.
Closes https://github.com/Homebrew/brew/pull/19038
Fixes https://github.com/Homebrew/brew/issues/19037
> Change default temp on Linux to /var/tmp.

- docs/Installation.md
> docs/installation: replace `Tips N' Tricks` with `Tips and Tricks`

- Library/Homebrew/bundle/adder.rb
- Library/Homebrew/bundle/commands/check.rb
- Library/Homebrew/bundle/skipper.rb
- Library/Homebrew/bundle/whalebrew_dumper.rb
- Library/Homebrew/extend/os/linux/bundle/skipper.rb
- Library/Homebrew/head_software_spec.rb
- Library/Homebrew/software_spec.rb
- Library/Homebrew/test/head_software_spec_spec.rb
> Bump some files to Sorbet `typed: strict`

- .github/workflows/docker.yml
Fixes Docker workflow error on release tags
> workflows/docker: fix release push

- Library/Homebrew/cmd/bundle.rb
-----
Fixes https://github.com/Homebrew/brew/issues/19861
> Setting `HOMEBREW_ASK` to nil in case it was set before, fixes #19861

- .github/dependabot.yml
-----
There's usually overlap between these PR's, resulting in conflicts that have to be fixed once one is merged. Let's group them to avoid this.
> dependabot: Group RSpec updates

- Library/Homebrew/standalone/init.rb
> standalone/init: cleanup respond_to? check

- Library/Homebrew/cmd/services.rb
Asked by Mike in #19863.
I don't really have a strong opinion on the default so feel free to edit this PR and adjust.
> cmd/services: change --max-wait default

- Library/Homebrew/cask/installer.rb
We previously would output `HOMEBREW_FORBIDDEN_CASKS` for both when it was used and when `HOMEBREW_FORBID_CASKS` was set.
> cask/installer: output the correct environment variable.

- Library/Homebrew/utils/github.rb
This may help with debugging why this has failed.
> utils/github: improve PR creation error message.

- Library/Homebrew/cmd/upgrade.rb
-----
In the PR https://github.com/Homebrew/brew/pull/19892 - running the ask command for cask upgrades was not scoped to the `--ask` argument. This PR fixes that case.
> cmd/upgrade: only ask about cask upgrade with `--ask`

- Library/Homebrew/cask/artifact/abstract_uninstall.rb
> Revert "cask/artifact/abstract_uninstall: fix `trash_paths`"

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
Fixes https://github.com/Homebrew/brew/issues/19969
https://github.com/Homebrew/homebrew-core/pull/223863 was successfully opened using this branch.
> bump-formula-pr: fix case when only `url` is provided

- docs/FAQ.md
-----
This is causing CI to fail.
> docs/FAQ: fix broken link

- docs/Support-Tiers.md
> feat: add clarification of macOS patches in Support-Tiers

- Library/Homebrew/extend/pathname.rb
> Revert "feat: allow env for write_jar_script"

- Library/Homebrew/test/cmd/casks_spec.rb
- Library/Homebrew/test/cmd/formulae_spec.rb
- Library/Homebrew/test/cmd/list_spec.rb
- Library/Homebrew/test/cmd/setup-ruby_spec.rb
- Library/Homebrew/test/cmd/shellenv_spec.rb
This should help ensure that these don't regress.
> test/cmd: add more shell tests.

- Library/Homebrew/cmd/vendor-install.sh
We were previously ignoring the exit code most of the time. When the download fails, we don't want to commit the temporary path to cache and force the user to manually `rm` to retry.
> cmd/vendor-install: fix exit code handling for curl

- Library/Homebrew/macos_version.rb
- Library/Homebrew/os/mac/pkgconfig/26/bzip2.pc
- Library/Homebrew/os/mac/pkgconfig/26/expat.pc
- Library/Homebrew/os/mac/pkgconfig/26/libcurl.pc
- Library/Homebrew/os/mac/pkgconfig/26/libedit.pc
- Library/Homebrew/os/mac/pkgconfig/26/libexslt.pc
- Library/Homebrew/os/mac/pkgconfig/26/libffi.pc
- Library/Homebrew/os/mac/pkgconfig/26/libxml-2.0.pc
- Library/Homebrew/os/mac/pkgconfig/26/libxslt.pc
- Library/Homebrew/os/mac/pkgconfig/26/ncurses.pc
- Library/Homebrew/os/mac/pkgconfig/26/ncursesw.pc
- Library/Homebrew/os/mac/pkgconfig/26/sqlite3.pc
- Library/Homebrew/os/mac/pkgconfig/26/uuid.pc
- Library/Homebrew/os/mac/pkgconfig/26/zlib.pc
- Library/Homebrew/os/mac/xcode.rb
- Library/Homebrew/test/cask/cask_spec.rb
- Library/Homebrew/test/github_runner_matrix_spec.rb
- Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.arm64_tahoe.bottle.tar.gz
- Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.tahoe.bottle.tar.gz
Pending:
* Information on Darwin versioning (are we skipping Darwin 25?)
* Information on Apple Clang versioning
* Library versions in macOS 26 SDK
* Do we need to release a new ruby-macho for new load commands?
* Beta 1 to be released so I can test this
> Preliminary macOS 26 (Tahoe) support

- Library/Homebrew/cmd/update.sh
This should allow any repositories that change from `master` to `main` to be automatically migrated by `brew update` without requiring manual intervention or displaying errors to the user.
Tested locally and seems to be playing nicely with https://github.com/MikeMcQuaid/homebrew-main-test. Renaming `master` to `main` there transparently updates and errored previously.
Take 2 of https://github.com/Homebrew/brew/pull/19196
Part of https://github.com/Homebrew/brew/issues/17296
Needed to migrate any official taps or this repository.
CC @Homebrew/maintainers would appreciate some heavy review here just because of how 💀 mistakes with auto-updating are. Recommending reviewing with no whitespace changes visible (https://github.com/Homebrew/brew/pull/20073/files?w=1)
> cmd/update: attempt migration from `master` to `main` branch.

- .vscode/mcp.json
-----
This PR provides our new MCP server when opening the workspace in VS Code.
> Add MCP server VS Code config

- Library/Homebrew/test/spec_helper.rb
Fixes https://github.com/Homebrew/brew/issues/20114
-----
> Replace hardlinks with symlinks for `brew tests`

- Library/Homebrew/requirements/xcode_requirement.rb
> requirements: set `typed: strict`

- Library/Homebrew/formula_creator.rb
- Library/Homebrew/test/formula_creator_spec.rb
-----
Adds tests for GitHub parsing section, to ensure that PRs that touch it like #20025 don't break things.
> formula_creator: test GitHub repo call for archive|releases URLs

- Library/Homebrew/bundle/brew_dumper.rb
- Library/Homebrew/bundle/checker.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/bundle/brew_dumper.rbi
Reverts Homebrew/brew#20145
See https://github.com/Homebrew/brew/pull/20149
> Revert "Make some of the `bundle` commands Sorbet `typed: true`"

- .github/workflows/tests.yml
- Library/Homebrew/cask/audit.rb
- Library/Homebrew/cask/auditor.rb
- Library/Homebrew/dev-cmd/audit.rb
- Library/Homebrew/dev-cmd/generate-cask-ci-matrix.rb
- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/test/cask/audit_spec.rb
- docs/Cask-Cookbook.md
I expect CI will fail here which will reveal the formulae and/or casks that need renamed.
Fixes https://github.com/Homebrew/brew/issues/17560
> audit: ensure that official formula and cask names don't conflict.

- Library/Homebrew/cmd/update-report.rb
- Library/Homebrew/test/cmd/update-report_spec.rb
This parses Homebrew's API JSON data to display descriptions for new formulae and casks if available.
While we're here also add tests for ReporterHub.
Fixes https://github.com/Homebrew/brew/issues/20162
> cmd/update-report: display descriptions for new formulae and casks.

- Library/Homebrew/cmd/upgrade.rb
> upgrade pin nil value 

- Library/Homebrew/install.rb
- Library/Homebrew/upgrade.rb
-----
moved `install_formula(fi)` out of each as it was before the refactoring
> Correcting refine ask option dependency

- docs/Formula-Cookbook.md
- docs/Homebrew-homebrew-core-Maintainer-Guide.md
- docs/How-To-Open-a-Homebrew-Pull-Request.md
Adjust documentation accordingly.
> docs: homebrew-core's default branch is now `main`

- .github/ISSUE_TEMPLATE/bug.yml
- Library/Homebrew/diagnostic.rb
Let's still continue to tell people to not file some issues but allow them to file others.
While we're here, let's me a bit more chill with the language here.
> Provide more leeway to file Tier 2/3 issues.

- Library/Homebrew/cmd/update.sh
Otherwise we are switching to `main` but after having only fetched `refs/remotes/origin/master` and not `refs/remotes/origin/main`, which I've found can be stale reference to an old commit (somehow??).
I've also fixed an issue where we were attempting to delete master on every repository after it does it on one.
> cmd/update: ensure we update remote main ref

- Library/Homebrew/PATH.rb
- Library/Homebrew/bundle/commands/exec.rb
- Library/Homebrew/cmd/--env.rb
- Library/Homebrew/dependencies.rbi
- Library/Homebrew/dev-cmd/sh.rb
- Library/Homebrew/extend/ENV.rbi
-----
Just offering some suggestions for https://github.com/Homebrew/brew/pull/20128
> Refactor exec.rb type fixes

- Library/Homebrew/download_strategy.rb
-----
As indicated in https://github.com/Homebrew/brew/pull/20137#issuecomment-3001285474, a cached download could be invalidated if querying a URL returns a redirect to a login page. This attempts to avoid the issue by skipping the invalidation logic if the final response has a `Content-Type` starting with "text", which implies that the response is a webpage instead of a regular file.
> download_strategy: preserve cache upon text response

- Library/Homebrew/cmd/bundle.rb
-----
https://github.com/Homebrew/brew/pull/20209#discussion_r2186099917
> Retain the old `brew bundle --brews` flag for compatibility

- Library/Homebrew/cmd/bundle.rb
Addresses https://github.com/orgs/Homebrew/discussions/6292.
> bundle: --file and --global should conflict

- Library/Homebrew/download_queue.rb
Print simpler output when not running in a TTY.
Fixes https://github.com/Homebrew/brew/issues/20290
> download_queue: improve non-TTY output.

- Library/Homebrew/on_system.rb
- Library/Homebrew/readall.rb
-----
Noticed a tiny type error in `Readall.valid_tap?`, and figured I'd enable strict typing in `OnSystem` while I was in the vicinity.
> Fix type error in Readall.valid_tap?

- Library/Homebrew/formula_cellar_checks.rb
- Library/Homebrew/service.rb
- Library/Homebrew/test/service_spec.rb
-----
Resolves https://github.com/Homebrew/brew/issues/20320
> Reduce shape variations in Homebrew::Service

- Library/Homebrew/cask/cask_loader.rb
- Library/Homebrew/download_strategy.rb
- Library/Homebrew/formulary.rb
We get regularly nudged with warnings to make this change to: I did.
> Fix URI parser warning

- Library/Homebrew/extend/kernel.rb
This was a private API so there's no need to deprecate it.
> extend/kernel: remove ensure_formula_installed!

- Library/Homebrew/dev-cmd/pr-pull.rb
- Library/Homebrew/dev-cmd/tap-new.rb
- Library/Homebrew/diagnostic.rb
- Library/Homebrew/tap.rb
> Enable strict typing in Tap

- Library/Homebrew/extend/pathname.rb
Let's make this consistent with the rest of this file.
> extend/pathname: fix another type error.

- Library/Homebrew/data/spdx/spdx_exceptions.json
- Library/Homebrew/data/spdx/spdx_licenses.json
- Library/Homebrew/utils/spdx.rb
-----
`raw.githubusercontent.com` is currently broken so we revert the false change from #20397. Also use the `refs/tags` URL to fetch SPDX data so that this doesn't regress (at least for now).
> Revert "spdx: update license data."

- Library/Homebrew/formula.rb
- Library/Homebrew/shims/super/cc
-----
Fixes https://github.com/Homebrew/brew/commit/718b82560a3c9c61391dddf582d28b648c143e2a#commitcomment-163850325.
> formula: improve log filename handling

- .github/dependabot.yml
-----
Testing to see if these are breaking Dependabot for us.
> dependabot: remove cooldowns

- Library/Homebrew/build.rb
- Library/Homebrew/formulary.rb
Noticed these when perusing the test-bot output from a third-party tap.
> Fix some test-bot failures/bad output

- Library/Homebrew/diagnostic.rb
> diagnostic: fix `check_cask_environment_variables` check

- Library/Homebrew/diagnostic.rb
> diagnostic: fix error on verbose

- Library/Homebrew/api.rb
- Library/Homebrew/brew.rb
- Library/Homebrew/dev-cmd/tests.rb
Was thinking about this a bit and feels a bit nicer to DRY this up.
Follow-up from https://github.com/Homebrew/brew/pull/20520
> Refactor Homebrew::API.fetch_api_files! to not take arguments.

- Library/Homebrew/cmd/update-report.rb
- Library/Homebrew/extend/os/mac/extend/ENV/std.rb
- Library/Homebrew/extend/os/mac/extend/ENV/super.rb
- Library/Homebrew/extend/os/mac/formula.rb
- Library/Homebrew/os/linux/glibc.rb
- Library/Homebrew/os/mac.rb
- Library/Homebrew/services/formulae.rb
- Library/Homebrew/settings.rb
> Miscellaneous `typed: strict`

- Library/.rubocop.yml
-----
Following @Rylan12's amazing work in https://github.com/Homebrew/brew/pull/20566, we no longer make use of refinements, let's keep it that way.
> Enable Sorbet/Refinement

- Library/Homebrew/keg_only_reason.rb
- Library/Homebrew/locale.rb
> keg_only_reason locale: `typed: strict`

- docs/MCP-Server.md
> [!NOTE]
> This is just a documentation update. 😉 
-----
Hello! 👋 I added a table documenting each of the available MCP server tools (see [here](https://github.com/ivy/brew/blob/7358c96dbb5776f9df8f95f03d023ba7c5b2c1d5/docs/MCP-Server.md#available-tools)) based on `Library/Homebrew/mcp_server.rb` so future readers can get a clear idea without further digging.
Very excited to give the MCP server a try! 🙌
> Document MCP server capabilities

- Library/Homebrew/manpages/brew.1.md.erb
- docs/Manpage.md
- manpages/brew.1
-----
This was functionality was removed in https://github.com/Homebrew/brew/pull/20414 and the opt-out is undocumented, so probably should remove any mentions of it in the docs.
> Remove docs saying that installing from a file is allowed

- docs/How-to-Create-and-Maintain-a-Tap.md
We don't really tell people actually how to create a tap here so let's provide more commands and output to help them.
While we're here, also fix some bad references to `repo` that weren't updated when they should have been and let VSCode autoformat the Markdown.
> How-to-Create-and-Maintain-a-Tap: improve docs.

- Library/Homebrew/os/mac/pkgconfig/26/sqlite3.pc
- Library/Homebrew/os/mac/xcode.rb
> os/mac: updates for Xcode/macOS 26 RC

- Library/Homebrew/os/mac/keg.rb
- Library/Homebrew/os/mac/mach.rb
- Library/Homebrew/os/mac/sdk.rb
- Library/Homebrew/os/mac/xcode.rb
> os/mac/*: `typed: strict`

- Library/Homebrew/cmd/shellenv.sh
This is faster at both execution and `eval`ing than the existing version and aids caching.
Fixes https://github.com/Homebrew/brew/issues/20671
> cmd/shellenv: echo path helper command rather than run it.

- Library/Homebrew/github_runner_matrix.rb
-----
Opening as draft to prepare to deploy Tahoe runner in CI when we feel comfortable.
The change here is not user-facing and thus independent of #20681.
> github_runner_matrix: deploy Tahoe runner in CI

- Dockerfile
- Library/Homebrew/os.rb
-----
Exploring changes needed for this.
> Migrate Linux CI to GCC 12

- .github/workflows/tests.yml
- Library/Homebrew/dev-cmd/generate-cask-ci-matrix.rb
- Library/Homebrew/dev-cmd/tap-new.rb
-----
Will need the actionlint change from https://github.com/Homebrew/brew/pull/20736.
> various: migrate Intel to Sequoia

- docs/Acceptable-Casks.md
- docs/Acceptable-Formulae.md
We've discussed this internally a bit so let's publicly document it.
> docs/Acceptable-*: clarify stance on adult content.

- Library/Homebrew/cask/artifact/abstract_artifact.rb
-----
solve the TODO comment `# TODO: Replace class var @@sort_order with a class instance var.`
> replace sort_order with class instance var

- Library/Homebrew/cask/artifact.rb
- Library/Homebrew/cask/cask.rb
- Library/Homebrew/dev-cmd/generate-cask-ci-matrix.rb
- Library/Homebrew/extend/os/linux/cask/installer.rb
-----
This should allow CI on ubuntu, just need to think of a way to test it.
> feat: offer ubuntu for eligable casks

- Library/Homebrew/formula_auditor.rb
See https://github.com/Homebrew/homebrew-core/pull/246341.
> formula_auditor: add liquibase to RELICENSED_FORMULAE_VERSIONS

- Library/Homebrew/download_strategy.rb
Add a space before "Last-Modified" in the message:
```patch
-Cached modified time 2025-09-25T23:06:34+03:00 is beforeLast-Modified header: 2025-09-30T20:39:37+00:00
+Cached modified time 2025-09-25T23:06:34+03:00 is before Last-Modified header: 2025-09-30T20:39:37+00:00
```
> Typo: add a space between the words of two strings

- Library/Homebrew/cmd/update.sh
-----
`brew update` fails if user does not have `<cache-dir>/Homebrew/api/internal` directory.
See https://github.com/orgs/Homebrew/discussions/6448
> cmd/update.sh: create directory for `executables.txt`

- Library/Homebrew/cask_dependent.rb
- Library/Homebrew/cleanup.rb
- Library/Homebrew/cmd/install.rb
- Library/Homebrew/cmd/leaves.rb
- Library/Homebrew/cmd/outdated.rb
- Library/Homebrew/cmd/reinstall.rb
- Library/Homebrew/dependency.rb
- Library/Homebrew/diagnostic.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/installed_dependents.rb
- Library/Homebrew/test/cmd/leaves_spec.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/test/migrator_spec.rb
- Library/Homebrew/test/support/helper/formula.rb
- Library/Homebrew/test/utils/autoremove_spec.rb
- Library/Homebrew/utils/autoremove.rb
> Revert "Revert "Revert "Use installed keg formula files when referencing installed formulae/dependencies"""

- Library/Homebrew/utils/bottles.rb
-----
This is needed for @@HOMEBREW_PERL@@ to work
- https://github.com/Homebrew/brew/issues/20023
- https://github.com/orgs/Homebrew/discussions/6415
One thing is that it won't use versioned Perl path since the `built_on` in tab is still wrong.
Could do something like following if it matters
```ruby
tab.built_on = DevelopmentTools.build_system_info
```
However the versioned Perl path is less useful for plain scripts as it breaks across macOS upgrades. It is more useful when Perl modules are required as compiled modules are incompatible with different Perl versions.
---
e.g. `lesspipe` without PR:
```console
❯ head -1 $(brew --prefix lesspipe)/bin/vimcolor
#!/opt/homebrew/opt/perl/bin/perl
```
after PR:
```console
❯ head -1 $(brew --prefix lesspipe)/bin/vimcolor
#!/usr/bin/perl
```
--- …
> utils/bottles: fix all bottle tab
