Homebrew/brew

Library/Homebrew/dependency_collector.rb, Library/Homebrew/formula.rb, Library/Homebrew/formulary.rb, Library/Homebrew/test/formulary_spec.rb
These are the last parts that were never read from the API.
For requirements, the following are not supported at this time (and are ignored gracefully):
* Codesign requirement
* Any custom requirement class, such as those in glibc (we should consider moving those to brew at some point)
After this PR, apart from the above exceptions, the output of `to_hash` should be identical between one built from API and one built from Ruby source without the aid from the API-specific code (which is now deleted).
=> formulary: support requirements, aliases etc from API

Library/Homebrew/dev-cmd/edit.rb, Library/Homebrew/test/dev-cmd/edit_spec.rb, docs/FAQ.md
-----
I was very confused why `brew install` was seemingly ignoring the changes I did through `brew edit`, only to find out after quite some time that it doesn't use the local git repository/formula anymore unless a flag is provided: [#14473](https://github.com/Homebrew/brew/issues/14473#issuecomment-1411925939)
This PR:
- Adds a line regarding `HOMEBREW_NO_INSTALL_FROM_API` to `brew install` help documentation
- Correct a (now misleading) FAQ entry on how to edit a formula, adding `HOMEBREW_NO_INSTALL_FROM_API=1` flag to the `brew install` snippet.
=> Update documentation for `brew install` and FAQ regarding `HOMEBREW_NO_INSTALL_FROM_API`

Library/Homebrew/system_command.rb, Library/Homebrew/test/system_command_spec.rb
Using /usr/bin/env as a frontend for the actual command prevents sudoers from restricting allowed commands and configuring detailed command environment.
-----
=> sudo: pass env variables without /usr/bin/env

Library/Homebrew/cask/cask.rb
Needs a leading slash to avoid `File.expand.path` complaining about non-absolute home.
See https://github.com/Homebrew/formulae.brew.sh/actions/runs/4176240259/jobs/7232266415#step:4:24
=> cask/cask: fix non-absolute home error.

Library/Homebrew/prefix.sh
I noticed we already do this in `formulae.sh`:
https://github.com/Homebrew/brew/blob/2a417f14163aacfb4ffcb754fe9dea71c46f6ad0/Library/Homebrew/cmd/formulae.sh#L14-L22
So it makes sense to do in `prefix.sh` if we want to keep the speed advantages there too.
If the JSON file is corrupt or missing, it will still fallback to prefix.rb as before where a download will occur.
=> prefix.sh: support API mode

Library/Homebrew/test/cask/cask_spec.rb
macOS CI failure in #14627 wasn't actually a rate limit failure.
=> test/cask/cask_spec: fix test

Library/Homebrew/cask/installer.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/tap.rb, Library/Homebrew/utils/analytics.rb
After untapping a cask tap with API mode enabled, cask installs would end in an error:
```
Error: No available tap homebrew/cask.
/usr/local/Homebrew/Library/Homebrew/tap.rb:219:in `config'
/usr/local/Homebrew/Library/Homebrew/tap.rb:737:in `read_or_set_private_config'
/usr/local/Homebrew/Library/Homebrew/tap.rb:213:in `private?'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:113:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:110:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:185:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
When installing a …
=> Fix analytics handling when core/cask taps are untapped

bin/brew
-----
We inherit some variables from the user's environment but prefix them
with `HOMEBREW_`. This is the case for (1) variables documented in the
manpage and also for some (2) variables used internally by `brew`.
We currently treat both types identically, but we should not. In
particular, we allow users to override type (1), but we don't want to do
this for type (2).
This was partially fixed in f4103e5d61526cfbf7f31540ba45ec171adc452e,
but that fix did not go far enough. Some variables that the user should
not be allowed to override can still be overridden.
This change completes the partial fix and refactors the code so that
we're less likely to mistakenly conflate the two types of variables in
the future.
=> bin/brew: refine generation of `HOMEBREW_*` env vars

Library/Homebrew/cask/audit.rb, Library/Homebrew/test/cask/audit_spec.rb, Library/Homebrew/test/support/fixtures/cask/Casks/version-colon.rb
-----
Add audit for cask versions containing colons or slashes.
Also improve the test matcher to produce more meaningful error messages.
Closes https://github.com/Homebrew/homebrew-cask/issues/95207.
=> Add audit for versions containing colons or slashes.

docs/Homebrew-on-Linux.md, docs/Manpage.md
Capability removed via https://github.com/Homebrew/install/pull/702
=> docs: no more homedir installs

Library/Homebrew/requirements/codesign_requirement.rb, Library/Homebrew/requirements/macos_requirement.rb, Library/Homebrew/requirements/xcode_requirement.rb
-----
Enables typing in `Requirement` subclasses, using a mix of `T.bind`, splat argument fixes, and class instantiation errors.
=> Enable typing in Requirement classes

Library/Homebrew/upgrade.rb, Library/Homebrew/upgrade.rbi
-----
This enabled typing in the `Homebrew::Upgrade` module
=> Enable typing in Homebrew::Upgrade

Library/Homebrew/test/utils/analytics_spec.rb, Library/Homebrew/utils/analytics.rb
Now that this is ready: let's roll it out to everyone in 4.0.0.
Do not merge until we've done some final testing.
=> analytics: report to InfluxDB by default.

Library/Homebrew/cmd/analytics.rb, docs/Manpage.md, manpages/brew.1
Be more explicit about when Google Analytics is disabled and when the is used or not.
=> cmd/analytics: note Google Analytics differences.

Library/Homebrew/api.rb, Library/Homebrew/api/cask.rb, Library/Homebrew/test/api/cask_spec.rb, Library/Homebrew/test/api_spec.rb
GitHub's raw endpoint is proving hilariously unreliable for us here.
Fixes https://github.com/Homebrew/homebrew-cask/issues/141436
=> api: use formulae.brew.sh for cask-source API again.

Library/Homebrew/tap.rb, Library/Homebrew/test/tap_spec.rb
=> tap: return the default_remote if not installed.

Library/Homebrew/utils/analytics.rb
Need to ensure we call the correct methods to avoid duplicates.
Also, clean up the data we send.
=> utils/analytics: cleanup reporting.

Library/Homebrew/cli/args.rbi, Library/Homebrew/dev-cmd/contributions.rb
-----
- This gives users of this command a `--csv` option to pass to... you guessed it, generate a CSV that's `pbcopy`able elsewhere, for more granular breakdowns of where a person contributed.
- Inspiration was taken from the mockup in https://github.com/Homebrew/brew/issues/13642#issuecomment-1254535251 but without the extra dependency of the TerminalTable gem.
- Always print a condensed "total contributions" sentence.
Output:
```
$ brew contributions issyl0
The user issyl0 has made 1201 contributions in all time.
$ brew contributions issyl0 --csv
user,repo,commits,coauthorships,signoffs
issyl0,brew,331,13,0
issyl0,core,473,24,326
issyl0,cask,4,0,0
issyl0,aliases,0,0,0
issyl0,autoupdate,1,0,0
issyl0,bundle,14,2,0 …
```
=> dev-cmd/contributions: CSV output of queried repos; shorter sentence

Library/Homebrew/cmd/update.sh
This makes it clearer what site cannot be accessed.
Fixes https://github.com/Homebrew/install/issues/737
=> cmd/update.sh: provide full JSON URL.

Library/Homebrew/completions/bash.erb, completions/bash/brew
-----
Bash completions: test if POSIX mode is enabled, print an error message and exit out.
Fixes Homebrew/brew#14643
The check itself is written in POSIX-compliant manner.
The message is written to standard error.
I think this check shouldn't return a non-zero exit code, but I'm open to suggestions / opinions.
=> Bash completions: warn and exit if POSIX mode detected

Library/Homebrew/api.rb
Fixes the `HOMEBREW_NO_AUTO_UPDATE` part of #14663.
`File.touch` always modifies the file, even if it already exists, because it refreshes mtime etc.
=> api: avoid unnecessary file write operation

Library/.rubocop.yml, Library/Homebrew/rubocops/cask/extend/node.rb, Library/Homebrew/rubocops/cask/mixin/cask_help.rb, Library/Homebrew/rubocops/cask/mixin/cask_help.rbi, Library/Homebrew/rubocops/cask/mixin/on_desc_stanza.rb, Library/Homebrew/rubocops/cask/mixin/on_desc_stanza.rbi, Library/Homebrew/rubocops/cask/mixin/on_homepage_stanza.rb, Library/Homebrew/rubocops/cask/mixin/on_homepage_stanza.rbi, Library/Homebrew/rubocops/cask/mixin/on_url_stanza.rb, Library/Homebrew/rubocops/cask/mixin/on_url_stanza.rbi, Library/Homebrew/rubocops/components_order.rb, Library/Homebrew/rubocops/dependency_order.rb, Library/Homebrew/rubocops/extend/formula.rb, Library/Homebrew/rubocops/lines.rb, Library/Homebrew/rubocops/platform.rb, Library/Homebrew/rubocops/shared/desc_helper.rb, Library/Homebrew/rubocops/shared/desc_helper.rbi, Library/Homebrew/rubocops/shared/helper_functions.rb, Library/Homebrew/rubocops/shared/helper_functions.rbi, Library/Homebrew/rubocops/shared/on_system_conditionals_helper.rb, Library/Homebrew/rubocops/text.rb, Library/Homebrew/rubocops/urls.rb, Library/Homebrew/sorbet/config
-----
This changes enables typing for everything under `Library/Homebrew/rubocops`.
The most significant change here is probably enabling `--enable-experimental-requires-ancestor` [flag](https://sorbet.org/docs/requires-ancestor) in sorbet. Since the feature "is experimental and might be changed or removed without notice", i've put every use of `requires_ancestror` in an `rbi` file, so that the runtime does depend on a potentially breaking change. (However, since `sorbet-runtime` appears to be vendored, this may be overkill.)
=> Enable typing in rubocops

Library/Homebrew/test/utils/analytics_spec.rb
A couple of them check the tags, which are cached.
=> test/utils/analytics_spec: fix flaky test

Library/Homebrew/utils/analytics.rb
Otherwise when it's `false` it's being turned into a `true` value.
=> utils/analytics: make on_request a proper boolean.

Library/Homebrew/extend/os/linux/linkage_checker.rb
-----
We have noticed in https://github.com/Homebrew/homebrew-core/pull/123264 that `libquadmath.so.0` is also provided by GCC.  This is primarily used by Fortran applications (in which case `libquadmath.so.0` is provided by brewed GCC), but on occasion C or C++ programs link to this as well and `brew audit` should allow linkage to the system version of this library.
=> linkage_checker: add libquadmath

Library/Homebrew/dev-cmd/prof.rb
-----
Small changes to provide better errors when using `brew prof`.
1. Provide an error message when the command is unknown.
2. Suggest running the command again with `--` if there is an invalid option which might have been meant for a subcommand.
```
/u/l/Homebrew (master|✔) $ brew prof updat
Error: undefined method `extname' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/dev-cmd/prof.rb:30:in `prof'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
```
/u/l/Homebrew (master|✔) [1]$ brew prof list -r
Usage: brew prof [--stackprof] command [...]
Run Homebrew with a Ruby profiler. For example, brew prof readall.
--stackprof                  Use stackprof instead of ruby-prof (the
default).
-d, --debug                      Display any debugging information.
-q, --quiet …
```
=> cmd/prof: improve error messages

docs/FAQ.md
There is no `HOMEBREW_NO_INSTALL_WITH_API`; it should be `HOMEBREW_NO_INSTALL_FROM_API`.
-----
=> docs/FAQ: fix HOMEBREW_NO_INSTALL_FROM_API mention

Library/Homebrew/cmd/--version.sh
This is more confusing than helpful if it's untapped for API usage.
=> cmd/--version: don't always output homebrew/core.

.github/workflows/tests.yml, Library/Homebrew/.rspec_parallel, Library/Homebrew/.simplecov, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/test/cmd/search_spec.rb, Library/Homebrew/test/cmd/services_spec.rb, Library/Homebrew/test/dev-cmd/bump_spec.rb, Library/Homebrew/test/dev-cmd/prof_spec.rb, Library/Homebrew/test/os/mac/pkgconfig_spec.rb, Library/Homebrew/test/spec_helper.rb, Library/Homebrew/test/support/quiet_progress_formatter.rb, Library/Homebrew/test/utils/analytics_spec.rb
- Extract update tests into a separate test.
- Make `brew tests --online` run only once in its own job. This job could be made non-required to fight flakiness.
- Split up the various macOS runs into several steps now that we have more parallel macOS workers available.
- Cleanup some flaky tests.
=> workflows/tests: faster, more reliable tests.

.github/workflows/tests.yml
This is only run on macOS for some reason but no harm in caching on both.
Should speed things up, as mentioned in https://github.com/Homebrew/brew/pull/14660#issuecomment-1434822376
=> workflows/tests: cache update-test's bundler.

.github/workflows/tests.yml, Library/Homebrew/.simplecov, Library/Homebrew/dev-cmd/tests.rb
- Never bother to do `brew cleanup` after `brew install`
- Skip `brew test-bot --only-cleanup-before` in more places it's not needed
- Move `brew config`/`brew doctor` into the default formula run (through `brew test-bot --only-setup`)
- Install `buildpulse-test-reporter` rather than letting `brew tests` do it
- Improve the formatting of the `brew tests` step
- Further shorten the code coverage filenames
- Don't output BuildPulse results upload status unless failed
=> More tweaks to testing output and speed

completions/bash/brew
Fixes https://github.com/Homebrew/brew/issues/14643
-----
-----
The test for POSIX mode introduced in https://github.com/Homebrew/brew/pull/14669 rely on bash features introduced in 4.2 which is head of 3.2.57, the default available on macOS.
```
+++ [[ brew != @(*~|*.bak|*.swp|\#*\#|*.dpkg*|*.rpm@(orig|new|save)|Makefile*) ]]
+++ [[ -f /opt/homebrew/etc/bash_completion.d/brew ]]
+++ [[ -r /opt/homebrew/etc/bash_completion.d/brew ]]
+++ . /opt/homebrew/etc/bash_completion.d/brew
++++ test -v POSIXLY_CORRECT
bash: test: -v: unary operator expected
++++ test -o posix
++++ complete -o bashdefault -o default -F _brew brew
```
I think that it's reasonable to assume that anyone attempting to source this bash completion will be attempting to source it from bash so maintaining strict POSIX …
=> completions/bash/brew: Fix testing for POSIX mode in bash >= 3.2.57

.github/workflows/tests.yml
The latest GitHub images unsurprisingly don't have Homebrew/core installed anymore.
=> workflows/tests: fix failing CI when Homebrew/core not present

Library/Homebrew/brew.rb, Library/Homebrew/cmd/install.rb, Library/Homebrew/cmd/reinstall.rb, Library/Homebrew/cmd/upgrade.rb, Library/Homebrew/diagnostic.rb, Library/Homebrew/formula_installer.rb
We warn sometimes when we tell people to build from source and it's not supported but we don't actually warn non-developers when invoking the various install commands so: let's start doing so.
While we're here, also update the existing messaging to reflect the fact we're on Mastodon now too and we don't want maintainers being individually bothered about errors either.
I've tried to balance having messages here vs. having them be so long at the beginning of installation that they will be missed or be overly obnoxious.
Feedback welcome!
=> Warn more when building from source

Library/.rubocop.yml
-----
This PR removes some redundant `.rubocop.yml` entries (which reviewers can confirm with `rubocop --show-cops`). It also enables two cops that were disabled due to linked issues that have since been fixed, and which also do not trigger violations (`Layout/RescueEnsureAlignment` and `Style/AccessModifierDeclarations`).
=> Remove redundant rubocop configs

Library/Homebrew/api.rb, Library/Homebrew/api/cask.rb, Library/Homebrew/api/formula.rb, Library/Homebrew/brew.sh, Library/Homebrew/cmd/casks.sh, Library/Homebrew/cmd/formulae.sh, Library/Homebrew/cmd/update-report.rb, Library/Homebrew/cmd/update.sh, Library/Homebrew/formula_path.sh, Library/Homebrew/prefix.sh, Library/Homebrew/test/api_spec.rb
This follows on from the `brew --prefix` API improvements to get rid of the shell out to Ruby and read a file that gets generated on the Ruby side during an API auto-update.
There's a few parts here:
* The generated files are placed in `HOMEBREW_CACHE_API/parsed`.
* They are only generated in Ruby, so we need `brew update-report` to try invoke that post-update.
* `brew update` deletes the parsed files after an update to signal they should be regenerated. The Ruby auto-update signals back a boolean.
* It regenerates only when necessary to avoid unnecessary file writes (which matters for sandboxed use).
I've also:
* Updated `brew casks` to support the API (it previously only read local taps).
* Added shell-side support for API aliases in `brew --prefix` (for #14663).
* Added support for …
=> Further improvements to API handling in shell

Library/.rubocop.yml, Library/Homebrew/.rubocop.yml, Library/Homebrew/cmd/install.rb, Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/formula.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/lazy_object.rb, Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb, Library/Homebrew/test/dev-cmd/audit_spec.rb, Library/Homebrew/test/exceptions_spec.rb, Library/Homebrew/test/patching_spec.rb, Library/Homebrew/test/spec_helper.rb, Library/Homebrew/utils/github.rb
-----
- Part of #14685.
- Clean up some old excludes that are no longer necessary, add in-line disables for some other rules and entirely disable some rules.
=> rubocop: Clean up some `Exclude`s

Library/Homebrew/cask/audit.rb, Library/Homebrew/download_strategy.rb, Library/Homebrew/unpack_strategy.rb, Library/Homebrew/unpack_strategy/uncompressed.rb
-----
Permissions need to be fixed before moving extracted files in order to be able to remove them later.
Fixes the CI failure in https://github.com/Homebrew/homebrew-cask-drivers/pull/3296.
=> Fix permissions before moving extracted files.

Library/Homebrew/dev-cmd/contributions.rb
-----
- For annual "has this person contributed enough", we focus on the main Homebrew repos: brew, core and cask. Let's make that easier than `--repositories=brew,core,cask`.
=> dev-cmd/contributions: Add `--repositories=primary` to scan only `brew,core,cask`

Library/Homebrew/cask/cmd/upgrade.rb, Library/Homebrew/cmd/outdated.rb
-----
- Fixes https://github.com/Homebrew/brew/issues/14682.
=> cmd/(outdated,upgrade): Document `-g` as a shorter `--greedy` for Casks

Library/Homebrew/formulary.rb
We never change this value in `formula.json` so ignore it for security.
=> formulary: use default bottle root_url.

Library/Homebrew/formula.rb, Library/Homebrew/formulary.rb, Library/Homebrew/test/formulary_spec.rb
=> Support `link_overwrite` and `conflicts_with` in API

Library/.rubocop.yml, Library/Homebrew/.rubocop.yml
-----
- Found on my travels through https://github.com/Homebrew/brew/issues/14685.
- Clean up non-existent files/dirs from excludes.
- `Naming/PredicateName` allows `is_a?` by default.
- ~The `test` dir is a default exclude for `Style/Documentation`.~
=> rubocop: Some more config cleanup

Library/Homebrew/utils/gzip.rb
-----
This allows us to bottle formulae whose source modified time is indeed
`0`.
Needed for Homebrew/homebrew-core#123724.
=> utils/gzip: set `mtime = 1` when `mtime == 0`.

Library/Homebrew/.rubocop.yml, Library/Homebrew/cmd/install.rb, Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/formula.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/livecheck/livecheck.rb, Library/Homebrew/rubocops/lines.rb, Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb, Library/Homebrew/test/dev-cmd/audit_spec.rb, Library/Homebrew/test/spec_helper.rb, Library/Homebrew/utils/github.rb
-----
- Part of https://github.com/Homebrew/brew/issues/14685.
- These are arbitrary length limits that had a load of disables in code.
- The limits were only increasing over time rather than decreasing.
- Fixing the problematic code to be shorter would take a long time for questionable gain since the problem has been around so long.
=> rubocop: Entirely disable `Metrics` cops

Library/Homebrew/api.rb
-----
Resolves #14707. Basically it respects `--quiet` when loading cask and formula JSON from the API. This applies globally.
```rb
/u/l/Homebrew (master|✚1) $ brew irb
==> Interactive Homebrew Shell
Example commands available with: `brew irb --examples`
irb(main):001:0> Context.current.quiet?
=> false
irb(main):002:0> Homebrew::API::Formula.all_formulae; nil
==> Downloading https://formulae.brew.sh/api/formula.json
############################################################################################################################################################################ 100.0%
=> nil
irb(main):003:0> Context.current.instance_variable_set(:@quiet, true)
=> true
irb(main):004:0> Context.current.quiet?
=> true
irb(main):005:0> Homebrew::API::Cask.all_casks; nil
=> nil
``` …
=> api: respect --quiet

docs/Gems,-Eggs-and-Perl-Modules.md, docs/Homebrew-and-Python.md, docs/How-to-Build-Software-Outside-Homebrew-with-Homebrew-keg-only-Dependencies.md
Intended change: for brew docs https://docs.brew.sh/Homebrew-and-Python#python-3y to say `$(brew --prefix python)/libexec/bin` instead of `$(brew --prefix)/opt/python/libexec/bin` in order to be more robust to edge cases from package installation issues.
`brew --prefix python` errors out when the python package is not installed, so using that instead of `brew --prefix` prevents python package installation issues from silently breaking, for example, shell env scripts that add this to $PATH.
See https://github.com/orgs/Homebrew/discussions/3596#discussioncomment-5050569
-----
=> docs: improve some `$(brew --prefix)` usage

Library/.rubocop.yml, Library/Homebrew/.rubocop.yml
=> rubocop.yml: disable more metrics.

Library/Homebrew/unversioned_cask_checker.rb
-----
An `:extract_plist` `livecheck` on a cask containing 
```ruby
pkg "OverDrive-Mac-Installer-Version-#{version.major_minor}.pkg"
```
will only look for packages matching the major and minor version. This makes a `livecheck` useless when e.g. 1.3.0 is released. So when no packages are able to be globbed, glob any packages instead.
=> Look for all packages if specified packages are not found.

Library/Homebrew/livecheck/livecheck.rb
-----
Extracting versions from a `.plist` always requires the unchanged URL for a given cask.
Fixes CI failure in https://github.com/Homebrew/homebrew-cask/pull/141646.
=> Don't preprocess URL for `:extract_plist` strategy.

Library/Homebrew/dev-cmd/contributions.rb, Library/Homebrew/tap.rb, Library/Homebrew/utils/github.rb, Library/Homebrew/utils/github/api.rb
-----
- Using `git log` was brittle with name changes and email address changes for contributors over the years unless we made a Git `mailmap` file which brings with it its own updatedness overhead.
- Let's use the GitHub commits API (importantly _not_ the search API) so that we can give it a username and it will return contributions associated with every email address on that user's account: https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-commits--parameters.
- This is quite significantly slower, but it's worth it for correctness especially when we get to all maintainers' contributions (in a separate PR).
- The list commits API does not (yet? 🤔) support filtering by trailers or commit "committer"s, just authors.
----
For some context: I am lucky enough to have …
=> dev-cmd/contributions: Use GitHub APIs for commit author info

Library/Homebrew/cli/args.rbi, Library/Homebrew/dev-cmd/contributions.rb
-----
- Part of #13642.
- With `brew contributions maintainers`, this will output a list of stats (across the specified time period, or all time) for people in the "maintainers" team on GitHub.
- This assumes that their Git committer details are the same as their name is set to on GitHub. There's a TODO here to work out how to do this better.
- Show an error message if trying to generate a CSV for the full maintainer list, since I haven't worked out how to best show all of that info yet (or even how best to show only the totals across everything for every user) in that format.
=> dev-cmd/contributions: Stats for all maintainers

Library/Homebrew/dev-cmd/contributions.rb
-----
- Was this a bad merge conflict resolution, or me not paying enough attention another time?
=> dev-cmd/contributions: Correctly order the trailers method args

Library/Homebrew/utils/github/api.rb
-----
- The `API_MAX_PAGES` value is 50, so for pages 1 to 50, the `paginate_rest` method was making an API call even if there was no data past, for example, page 8.
- This made `brew contributions --user=issyl0` take 11 minutes, since we made 50 API calls _per repo_ even if it was unnecessary, burning down our API allowance.
- Instead, stop looping if we detect that there's no data in `result`.
- This probably needs more testing for other parts of Homebrew that rely on `paginate_rest` and the different shapes of data it outputs.
Before:
```
❯ time brew contributions --user=issyl0          
issyl0 contributed 1233 times in all time.
brew contributions --user=issyl0  33.90s user 26.27s system 8% cpu 11:41.11 total
```
After:
```
❯ time brew contributions --user=issyl0
issyl0 contributed …
```
=> utils/github/api: Smarter pagination in `paginate_rest`

Library/Homebrew/cask/audit.rb
Reverts Homebrew/brew#14747
This change is currently causing cask CI audits to be broken.
The `message` variable is being defined before the `result` is available and causing audits to error out.
I'm about to start work, so don't have time to fix, but reverting this for now should get things going again.
```
- exception while auditing wine-devel: undefined method `merged_output' for "\e[32mpassed\e[0m":String
```
=> Revert "cask: audit for correct signing of pkg installers"

Library/Homebrew/dev-cmd/contributions.rb, Library/Homebrew/utils/github.rb
-----
- I missed the date filtering off the original implementation of the author API query - oops. This gives parity with the `git log` implementation.
- Also reduce verbosity of `brew contributions --verbose` a little since it annoyed me.
=> utils/github: Add date filtering to the commit author API query

Library/Homebrew/brew.sh, Library/Homebrew/dev-cmd/generate-cask-api.rb, Library/Homebrew/dev-cmd/generate-formula-api.rb, Library/Homebrew/test/dev-cmd/generate-cask-api_spec.rb, Library/Homebrew/test/dev-cmd/generate-formula-api_spec.rb
These replace the similar scripts in formulae.brew.sh.
Part of #14730.
See also https://github.com/Homebrew/formulae.brew.sh/pull/776
=> Add generate-{cask,formula}-api commands

Library/Homebrew/dev-cmd/generate-cask-api.rb, Library/Homebrew/dev-cmd/generate-formula-api.rb
=> dev-cmd/generate-*-api: don't use same constant name.

Library/Homebrew/utils.rb
It's been deprecated. Make VSCode first because it's what we recommend.
Fixes https://github.com/Homebrew/brew/issues/14776
=> which_editor: remove Atom.

Library/Homebrew/api.rb, Library/Homebrew/brew.rb, Library/Homebrew/global.rb
This was mentioned in a random comment. While we're here, make some helper functions to query this a bit more nicely elsewhere when we do it.
=> api: don't download files as root when Homebrew's not owned by root.

Library/Homebrew/extend/os/mac/extend/ENV/super.rb
I'm aware this is not meant to happen but: sometimes it does and the lack of handling produces a subpar error.
=> os/mac/extend/ENV/super: handle nil sdk.

Library/Homebrew/cask/artifact/abstract_artifact.rb, Library/Homebrew/cask/artifact/abstract_uninstall.rb, Library/Homebrew/cask/artifact/installer.rb, Library/Homebrew/cask/artifact/installer.rbi, Library/Homebrew/cask/artifact/relocated.rb, Library/Homebrew/cask/artifact/stage_only.rb, Library/Homebrew/cask/artifact_set.rb, Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb, Library/Homebrew/utils/splat.rb
-----
Enables typing in `Cask::Artifact`. In this PR, i've introduced a new util module, `Utils::Splat`, which allows a file to be typed by wrapping splat calls to Ruby core/std library methods. Initially, it has a single method, a `Process.kill` wrapper. It's admittedly a potentially clumsy abstraction – bringing together a bunch of methods whose only unifying factor is accepting splat arguments, but we could refactor it as necessary (though I think it will mostly be lower-level CLI-wrapped methods like `system`).
=> Enable typing in Cask::Artifact

Library/Homebrew/test/.rubocop.yml, Library/Homebrew/test/unpack_strategy_spec.rb, Library/Homebrew/unpack_strategy.rb
-----
Reverts https://github.com/Homebrew/brew/pull/14729.
Now uses `u+w` instead of only `+w` to fix permissions only for extracted directories.
=> Revert "Revert "Fix permissions before moving extracted files.""

Library/Homebrew/brew.sh, Library/Homebrew/dev-cmd/audit.rb
=> Scope `HOMEBREW_NO_INSTALL_FROM_API` to core formulae in `brew audit`

Library/Homebrew/cask/cask.rb, Library/Homebrew/cask/cask_loader.rb, Library/Homebrew/test/cask/cmd/list_spec.rb
=> cask: support url specs in API

Library/Homebrew/completions.rb, Library/Homebrew/test/completions_spec.rb, completions/bash/brew
-----
I propose to cache names of `brew doctor` checks the first time the list of the checks is obtained. Also, reuse `_brew_doctor` function for `brew dr` (and, hence, remove `_brew_dr` function which is a duplicate of `_brew_doctor`).
It seems that some work has been done for Bash completions to be generated "automatically" using `brew generate-man-completions`. Not sure how this PR is going to affect that effort, so tagging in @Rylan12.
=> Bash completions: cache names of 'doctor' checks

Library/Homebrew/cmd/info.rb
Fall back to default location.
Fixes https://github.com/Homebrew/brew/issues/14796
=> cmd/info: handle casks with API.

Library/Homebrew/dev-cmd/generate-cask-api.rb, Library/Homebrew/dev-cmd/generate-formula-api.rb
Print which formula/cask has issues.
=> generate-*-api: better errors

Library/Homebrew/livecheck/strategy.rb, Library/Homebrew/livecheck/strategy/json.rb, Library/Homebrew/livecheck/strategy/page_match.rb, Library/Homebrew/test/livecheck/strategy/json_spec.rb, docs/Brew-Livecheck.md
-----
This adds a generic `Json` strategy to livecheck that requires a `strategy` block to operate. This is primarily intended as a replacement for existing `strategy` blocks in formulae/casks that use `JSON#parse`, as it allows us to internalize/standardize that boilerplate while improving error-handling.
Additionally, future strategies that parse JSON data can use the `Json#find_versions` method instead of having to reinvent the wheel (similar to how we currently have a number of strategies that leverage `PageMatch#find_versions`).
Resolves #13992, as we reduced the scope of that issue to simply deal with adding a `Json` strategy (`Xml` will be added in a separate PR and we do not intend to add strategies for HTML/XHTML, due to our `nokogiri` policy).
-----
When we simply need to grab …
=> livecheck: Add `Json` strategy

Library/Homebrew/cask/cask.rb
This generally shouldn't happen but it's probably acceptable for casks under the minimum macOS.
There are a few cases I see this happen but for above the minimum macOS. The fix here still covers them, but I'll open a change to `readall` to catch that there as I don't think the cask should be called valid in those scenarios.
=> cask: handle nil URLs

Library/Homebrew/dev-cmd/contributions.rb, Library/Homebrew/test/search_spec.rb, Library/Homebrew/utils/github.rb
-----
- The search APIs don't have that high a rate limit but we shouldn't need to worry about that too much because, to get counts, the JSON response comes with a `total_count` number.
=> dev-cmd/contributions: Count PR reviews since they're super important

Library/Homebrew/cask/cask_loader.rb
I noticed that the tap is not set for casks when they are loading via their contents and the API. This means that things like `brew info --github --cask vlc` don't work as expected (I noticed this when looking at #14797).
I'm not 100% sure this is the right way to handle this, though. Is there a better refactoring of the cask loader stuff that handles `tap` more universally? CC @Bo98 and @apainintheneck since I think you've touched this recently (and I'm not sure how this affects https://github.com/Homebrew/brew/pull/14713)
=> Set tap for casks when loading from contents via API

Library/Homebrew/utils/github.rb
-----
- Tiny cleanup.
- It's Ruby style convention that methods that return only booleans end with a question mark.
- And I noticed that the GitHub code search API no longer returns a leading `/` on a file's `path` anymore, so we don't need the `delete_prefix("/")` workaround from 2020.
=> utils/github: Tiny improvements, boolean methods end in `?` and remove unnecessary `.delete_prefix("/")`

Library/Homebrew/readall.rb
A cask without a URL is currently a valid cask. I don't understand this (except when under minimum macOS, though even then we probably shouldn't...) but maybe someone can explain if there's a valid use case for that.
=> readall: reject casks with no URL

Library/Homebrew/extend/os/linux/system_config.rb, Library/Homebrew/os.rb, Library/Homebrew/os/linux.rb, Library/Homebrew/utils.rb
-----
In WSL, `xdg-open` is not available -- `wslview` is. So, added `wsl?` and `wsl_version` methods to `OS::Linux` to conditionally set `PATH_OPEN`
Additional "require" statements:
- `require "PATH"` in utils.rb: needed by `PATH.new` in `which`
- `require "utils"` in linux.rb: needed by `which` in `os_version`
- `require "version"` in os.rb: needed by `sig { returns(Version) }`
To test, execute `brew docs`
=> Use 'wslview' instead of 'xdg-open' on Windows

Library/Homebrew/dev-cmd/contributions.rb, Library/Homebrew/utils/github.rb
-----
- Now `brew contributions --from=2023-02-23 --to=2023-02-26` works to limit the results for reviews. I forgot this in the original implementation (#14813), again, ugh.
=> dev-cmd/contributions: Support date ranges in PR reviews query

Library/Homebrew/dev-cmd/contributions.rb
-----
- Signoffs were just a stopgap until we implemented getting "real" reviews for a user via the GitHub API. They were a suboptimal way of getting reviews because they only really exist in Homebrew/homebrew-core where BrewTestBot adds signoffs for each maintainer who reviewed the PR.
=> dev-cmd/contributions: Stop counting signoffs now we have "real" reviews

Library/Homebrew/livecheck/strategy.rb
-----
When the `Json` strategy was introduced, I forgot to also ensure that it's only treated as usable (in `Strategy#from_url`) if a `livecheck` block uses `strategy :json`. As a result, `Json` is incorrectly treated as a usable strategy for all formulae/casks that contain a `strategy` block.
Since all of these `livecheck` blocks specify a strategy, this bug doesn't meaningfully impact livecheck's behavior (i.e., these checks continue to use their explicitly-specified strategy). The only practical difference is that `Json` incorrectly appears in the list of usable strategies in livecheck's verbose JSON output.
This PR modifies `Strategy#from_url` to address this issue. The easiest way to enforce this rule involved passing in the `@strategies` key (a symbol) into the `select` block, so we …
=> Strategy#from_url: Amend conditions for Json

Library/Homebrew/cask/audit.rb
-----
If there is a functional livecheck, a cask should not use `version :latest`. If the livecheck has `skip`, it should still be allowed as documentation why it cannot be versioned.
Fixes the remaining CI issue in https://github.com/Homebrew/homebrew-cask/pull/141646.
=> Allow `version :latest` if `livecheck` is `skip`.

Library/.rubocop.yml, Library/Homebrew/dev-cmd/edit.rb
- Stop `brew style` from complaining e.g. https://github.com/Homebrew/homebrew-cask/pull/141893 CC @cho-m 
- Fix message reference in `brew edit`
=> More Formula/Casks sharding fixes

Library/Homebrew/cask/auditor.rb, Library/Homebrew/test/cask/cmd/audit_spec.rb, Library/Homebrew/test/support/fixtures/cask/Casks/with-many-languages.rb
-----
This PR adds a flag `--[no-]sample-languages` to cask auditing. We have a couple of casks that contain a lot of languages (Firefox is upwards of 50) - this causes CI to timeout because it takes too long to download and audit every available binary.
This change would enable us to optionally add a flag `--sample-languages` to grab a subset of 10 languages at random for testing.
I am yet to write tests, but will do so ASAP.
Related Cask PR: https://github.com/Homebrew/homebrew-cask/pull/141357
CC: @p-linnane
=> cask/auditor: only audit 10 languages by default on casks with many languages

Library/Homebrew/dev-cmd/contributions.rb
-----
- The `reviewed-by` filter retrieved all reviews for a user, including those they'd added to their own PRs. Since it's impossible to click the "approve" button on one's own PR, filter this to `review:approved` to get "further project goals" kinds of reviews.
- Suggested in https://github.com/Homebrew/brew/pull/14813#discussion_r1118696385.
- Shorten a variable name so I didn't have to split the `count_issues` call onto multiple lines since the indentation looked funky when I tried it.
=> dev-cmd/contributions: Only count approving reviews

.github/workflows/tests.yml, Library/Homebrew/cmd/update-reset.sh
-----
Currently, doing `brew update-reset homebrew/core` does nothing (not
even return an error). If you want to `update-reset` a given tap, you
must do (the equivalent of)
brew update-reset "$(brew --repository owner/tap_name)"
This isn't very intuitive, so let's do a bit more work in argument
parsing so that the user can just pass a tap name instead of a path to a
tap.
Passing a path to a tap is also still supported.
=> cmd/update-reset: improve arg parsing

Library/Homebrew/dev-cmd/sh.rb, Library/Homebrew/extend/kernel.rb, Library/Homebrew/test/utils/shell_spec.rb, Library/Homebrew/utils/shell.rb
I know that we're outside our normal deprecation cycle but: these are totally broken with the API and it doesn't make sense to support them only for non-core formulae.
See https://github.com/Homebrew/homebrew-core/pull/124137 where we've removed these.
=> Deprecate `preferred_shell` and `shell_profile`.

Library/Homebrew/cask/cmd/upgrade.rb
-----
This reference to the versions variable is unnecessary. It was changed recently as a part of https://github.com/Homebrew/brew/pull/14778.
It is causing the following errors:
- https://github.com/Homebrew/homebrew-cask/issues/142050
- https://github.com/Homebrew/homebrew-cask/issues/142129
It [originally didn't reference a `versions` variable at all](https://github.com/Homebrew/brew/pull/14778/files?diff=unified&w=0#diff-6bdc1759a32b388be1e2ac3e350a817c9dcc7f097037f7092f1cb015175407c0)(look at line 124) and no other versions variable exists in the same file.
```sh
/u/l/Homebrew (master|✔) [2]$ grep -i versions '/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb'
ofail "Not upgrading #{count} `installer manual` #{::Utils.pluralize("cask", versions.count)}."
```
A similar line …
=> cask/cmd/upgrade: fix missing versions variable

Library/.rubocop.yml, Library/Homebrew/.rubocop.yml
-----
- `Style/DocumentationMethod` is only targetting a single file in `Library/Homebrew/`, so move it to that config file.
- Go the other way for `Style/BlockDelimiters`.
=> rubocop: Consolidate more rules into the right files

Library/Homebrew/formula.rb, Library/Homebrew/test/formula_spec.rb
-----
This PR fixes alias loading for formulae installed via an alias (when outdated homebrew-core repo is present)
Steps to reproduce:
```bash
$ brew install python
$ cd `brew --repo homebrew/core`
$ # Checkout to older revision with different python alias target (pre https://github.com/Homebrew/homebrew-core/commit/d6e43416761a9b65eb7e2318444ea70da76a5e49)
$ git checkout 1ac08d3d7f3e77a50cd369d47bfe8a3f1684776d # Thu Feb 9 13:29:05 2023 +0000
```
```
$ brew outdated
python@3.11 (3.11.2_1) < python@3.10 (3.10.10)
```
=> formula: fix alias loading

docs/Tips-N'-Tricks.md
Following on from https://github.com/Homebrew/brew/pull/14779, removed the Atom editor plugin because GitHub has archived the Atom project(s).
-----
=> Docs: Tips and Tricks - Remove Atom editor plugin

Library/Homebrew/.rubocop.yml, Library/Homebrew/livecheck/strategy.rb, Library/Homebrew/livecheck/strategy/sparkle.rb, Library/Homebrew/livecheck/strategy/xml.rb, Library/Homebrew/test/livecheck/strategy/xml_spec.rb, docs/Brew-Livecheck.md
-----
This adds a generic `Xml` strategy to livecheck that requires a `strategy` block to operate. The XML-parsing code is taken from the existing approach in the `Sparkle` strategy. As such, `Sparkle` has been updated to use the `Xml#parse_xml` method instead.
Unlike the `Json` strategy, we don't currently have any `strategy` blocks in first-party taps that manually parse XML. However, we had [a user request support for something like this](https://github.com/Homebrew/brew/issues/13991) and I was already working on an `Xml` strategy (as a way of extracting the XML-parsing code from `Sparkle` into something general-purpose), so here we are.
Future strategies that parse simple XML data can potentially use the `Xml#find_versions` method (similar to how we have strategies that leverage …
=> livecheck: Add Xml strategy

Library/Homebrew/dev-cmd/tests.rb
The current message doesn't really tell much - let's print stderr (assuming errors go there).
=> dev-cmd/tests: better output for BuildPulse failures

Library/Homebrew/cmd/update-report.rb
If we're installing from the API: we cannot use Git to check for differences in
packages so instead use `{formula,cask}_names.txt` to do so.
The first time this runs: we won't yet have a base state
(`{formula,cask}_names.before.txt`) to compare against so we don't output
anything and just copy the files for next time.
Fixes https://github.com/Homebrew/brew/issues/14706
=> Show New/Deleted Formulae/Casks from `brew update`

Library/.rubocop.yml, Library/Homebrew/cmd/uses.rb, Library/Homebrew/completions.rb, Library/Homebrew/manpages.rb, Library/Homebrew/test/api/cask_spec.rb, Library/Homebrew/test/api_spec.rb
-----
I would like us to enable the `Style/OpenStructUse` cop. The official RuboCop [docs](https://docs.rubocop.org/rubocop/cops_style.html) cite "performance, version compatibility, and potential security issues", but an add'l issue in this repo is that it [breaks](https://sorbet.run/#%23%20typed%3A%20true%0A%0Afoo%20%3D%20OpenStruct.new%0Afoo%5B%3Aa%5D%20%3D%20'a'%0Afoo.a) typechecking.
=> Enable Style/OpenStructUse cop

Library/Homebrew/livecheck/strategy/json.rb, Library/Homebrew/test/livecheck/strategy/json_spec.rb
-----
After working on the `Xml` strategy, I came back to the `Json` strategy to make a few changes to better align the two. For example, the `Xml` strategy provides a `#parse_xml` method that only includes the parsing logic, so other strategies can selectively use this method if that's all they need (instead of `Xml#find_versions`). This PR modifies the `Json` strategy to provide a similar `Json#parse_json` method.
This also renames the `simple_content*` variables in `json_spec` to `content_simple*`, to align the variable name with the naming convention used in the `Xml` strategy (e.g., `content_version_text`, `content_version_attr`, `content_simple`, etc.). This doesn't make a functional difference but is a little more tidy/predictable.
I've also tweaked a few tests to use …
=> Json: Add #parse_json method and tidy up tests

Library/Homebrew/cmd/update.sh
-----
We set `core.fsmonitor` to `false` in #13586 because Git's fsmonitor
daemon prevented the release of our locks, resulting in errors for some
users reported in #13521.
However, the fix from #13586 set `core.fsmonitor` to `false` too often.
This is not needed for taps, or when `HOMEBREW_REPOSITORY` is different
from `HOMEBREW_PREFIX`. The issue in #13521 stems from the fsmonitor
daemon preventing the release of our locks, so there is no need to
prevent the daemon from monitoring repositories that don't contain our
lock files.
=> cmd/update.sh: limit setting `core.fsmonitor` to `false`

Library/.rubocop.yml
-----
- We've disabled metrics cops for method length and complexity since we were fighting them a lot and the numbers were arbitrary and growing. It feels like these RSpec metrics numbers are arbitrary too.
=> rubocop: Disable RSpec metrics cops

Library/Homebrew/os.rb
-----
This is a fix for WSL systems that don't have `wslview` but do have `xdg-open`. Related to #14822
=> os.rb: fix for WSL systems without wslview

Library/.rubocop.yml, Library/Homebrew/.rubocop.yml, Library/Homebrew/test/utils/spdx_spec.rb
=> rubocop: Alphabetise, remove config that's default, in-line some disables

Library/Homebrew/dev-cmd/contributions.rb, Library/Homebrew/utils/github.rb
-----
- The GitHub list commits API now supports this filtering (https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-commits--parameters), because I wrote it. :-)
- Authoring a commit and committing a commit are two separate concepts: author is the person who wrote the code and, in old parlance, the committer is the person who applied the patch (remember when we sent patches to mailing lists?).
- In practice for us in Homebrew, this occurs when we make a change in GitHub's web editor, or, more obviously, when BrewTestBot pushes `homebrew-core` commits from users (then, `BrewTestBot` is the `committer`).
TODO:
Example:
```
❯ brew contributions --repos=primary --user=issyl0 --csv
issyl0 contributed 1626 times in …
```
=> dev-cmd/contributions: Count the number of commits a user committed

Library/Homebrew/.rubocop.yml, Library/Homebrew/livecheck/strategy.rb, Library/Homebrew/livecheck/strategy/electron_builder.rb, Library/Homebrew/livecheck/strategy/yaml.rb, Library/Homebrew/test/livecheck/strategy/electron_builder_spec.rb, Library/Homebrew/test/livecheck/strategy/yaml_spec.rb, docs/Brew-Livecheck.md
-----
This adds a generic `Yaml` strategy to livecheck that requires a `strategy` block to operate. The YAML-parsing code is taken from the existing approach in the `ElectronBuilder` strategy.
We don't currently have any `strategy` blocks in first-party taps that manually parse YAML. However, creating a generic `Yaml` strategy allows us to simplify `ElectronBuilder` (and any future strategy that works with YAML) while making it easy to create custom `Yaml` `strategy` blocks in formulae/casks as needed.
-----
This updates `ElectronBuilder` to use `Yaml#find_versions`, as the only code unique to that strategy is to restrict regex usage and use default version-finding logic when a `strategy` block isn't provided. This is similar to how we have various strategies that use …
=> livecheck: Add Yaml strategy

Library/Homebrew/livecheck/livecheck.rb
-----
I forgot to add the new `Json`, `Xml`, and `Yaml` strategies to the list of strategies where `#preprocess_url` should be skipped and this is [causing issues for a user in their tap](https://github.com/orgs/Homebrew/discussions/4299). This is unfortunately another bug that wasn't surfaced when I tested all the related checks in our first-party taps.
In the not-too-distant future, I plan to rework how we use `#preprocess_url`. It only manipulates Git URLs at this point, so it arguably makes sense to move it into the `Git` strategy as part of some refactoring of how certain strategy `#match` methods work. Long story short, once that's done we won't have to worry about special-casing strategies with regard to `#preprocess_url`.
=> livecheck: Skip #preprocess_url for new strategies

Library/Homebrew/dev-cmd/contributions.rb, Library/Homebrew/test/utils/github_spec.rb, Library/Homebrew/utils/github.rb
-----
- The usage of this in `brew contributions` wasn't correct for a user with 5 authored commits to homebrew/cask that had been committed by other people, the numbers would turn out as 5 authored, 5 committed when they should be 5 authored, 0 committed.
- I decided to do this properly by getting the SHAs for author and committer and determine the differences between the two arrays. This also accounts for when authored commits are 0, or committed commits, or both.
- Add tests, because I don't want to fix this a third time!
-----
Before:
```
issyl0 at pictor in /opt/homebrew on master
❯ brew contributions --user=issyl0 --csv
issyl0 contributed 1688 times in all time.
user,repo,author,committer,coauthorships,reviews,total
issyl0,brew,402,149,13,144,708
issyl0,core,473,73,24,357,927 …
```
=> utils/github: Fix double counting of author/committer numbers

Library/Homebrew/.rubocop.yml, Library/Homebrew/test/cask/cask_spec.rb, Library/Homebrew/test/cask/cmd/install_spec.rb, Library/Homebrew/test/cask/cmd/uninstall_spec.rb, Library/Homebrew/test/compiler_selector_spec.rb, Library/Homebrew/test/dev-cmd/bottle_spec.rb, Library/Homebrew/test/download_strategies/curl_github_packages_spec.rb, Library/Homebrew/test/download_strategies/curl_post_spec.rb, Library/Homebrew/test/download_strategies/curl_spec.rb, Library/Homebrew/test/resource_spec.rb, Library/Homebrew/test/utils/autoremove_spec.rb, Library/Homebrew/test/utils/user_spec.rb
-----
- Part of https://github.com/Homebrew/brew/issues/14685.
- The fixes here all seemed reasonable, with some minimal tweaks for line length and less floatiness. Apart from `test/dev-cmd/bottle_spec.rb` where RuboCop wanted to do some ridiculously floaty indentation and there wasn't an obvious alternative place to break the lines, so I opted for in-line disables instead.
=> rubocop: Enable `Layout/MultilineMethodCallIndentation` & fix offenses

Library/.rubocop.yml
-----
- "Deal with" might be ambitious wording, since I enabled one and disabled two others, but hey!
-----
- Enable `RSpec/MessageSpies` with the "receive" style.
- This matches the code we already have, rather than autocorrecting everything to `have_received`.
- Intentionally disable `RSpec/{DescribeClass,StubbedMock}`
- These had a lot of offenses that were marked as "try to enable".
- A lot of the "describe class" ones were for tests for cmds or dev-cmds, `brew typecheck` or `brew --env`, and the cop would only pass if I changed these "describe"s to `BrewTypecheck` or `Brew__Env` which seemed unhelpful.
- The usefulness of the stubbed mocks cop is [disputed](https://github.com/rubocop/rubocop-rspec/issues/1271), and fixing the offenses (not autocorrectable) would involve us doing a …
=> rubocop: Deal with `RSpec` cop TODOs

Library/Homebrew/rubocops/cask/desc.rb, Library/Homebrew/rubocops/cask/url_legacy_comma_separators.rb
-----
- I suspect these were copy-pasted from other cops, like I did in https://github.com/Homebrew/brew/pull/14886#discussion_r1125569999.
- The "forwardable" require is unnecesary if the cop doesn't `extend Forwardable` and use `def_delegator`.
- The "uri" require is unnecessary if the cop doesn't call `URI` methods.
=> rubocops/cask: Clean up unnecessary `require`s

Library/Homebrew/dev-cmd/irb.rb
-----
This makes it easier to load casks in repl sessions and matches what we already do with formulae.
=> irb: add cask monkey patch

Library/.rubocop.yml, Library/Homebrew/.rubocop.yml
-----
- Part of https://github.com/Homebrew/brew/issues/14685.
- rubocop: Trim `Style/BlockDelimiters` exclude paths without offenses
- rubocop: Move `AllowedMethods` inheritance to the cop it's used in
- rubocop: Switch to Cask-specific `Style/ClassVars` in-line disables
=> rubocop: Trim exclude paths without offenses; move some more config

Library/Homebrew/cmd/update-report.rb
-----
Resolves an error introduced in https://github.com/Homebrew/brew/commit/2451d017f9ebbf6b3f5fd79f15e048d2c109145a#diff-05ec45190dab3db11df80b2c154648c8023837fa34917dce9d1bcde0acf9c005L282
If you have a few minutes and you're willing to untap `core`, you should be able to repro with:
```
$ brew untap homebrew/core; HOMEBREW_NO_INSTALL_FROM_API=1 brew update-report
Untapping homebrew/core...
Untapped 3 commands and 6552 formulae (15,331 files, 710.4MB).
==> Tapping homebrew/core
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 1429703, done.
remote: Counting objects: 100% (318/318), done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 1429703 (delta 190), reused 268 (delta 161), pack-reused 1429385
Receiving objects: …
```
=> Fix "undefined local variable" error in update-report

Library/Homebrew/dev-cmd/typecheck.rb, Library/Homebrew/sorbet/custom_generators/tty.rb, Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi, Library/Homebrew/utils/tty.rb, Library/Homebrew/utils/tty.rbi
-----
- Sort of. It's not via Parlour, because I read the docs and all it says about dynamically generating things is "of course it's better to do that", no examples. I tried my best, but Bo's work on `attr.rb` was mind-boggling.
- Instead, let's add a simple but functional generator script that I actually understand, as an alternative to maintaining these RBI files for dynamic methods manually, or as an alternative to skipping them entirely, so that we can get rid of some use of `srb rbi hidden-definitions` since that's deprecated.
- Follow up to #14651.
-----
- Feel free to throw this away if this isn't the direction we want to go or if it's rubbish and/or not the Proper Way - no hard feelings! ❤️
=> sorbet: Autogenerate the RBI file for `utils/tty.rb`

Library/Homebrew/dev-cmd/cat.rb, Library/Homebrew/test/dev-cmd/cat_spec.rb
When `brew cat formula|cask` fails, add suggestion to use `brew info --github formula|cask` instead. This gives a workaround for API users that don't have taps locally for `homebrew/core` and `homebrew/cask`.
This builds on changes from #14824 which addressed #14815
=> when `brew cat` fails, suggest `brew info --github`

Library/Homebrew/lock_file.rb
-----
I ran into the same issue reported in https://github.com/Homebrew/brew/issues/11530 (somehow my `ulimit -n` was only 256), but I found the error message a bit confusing, and it took me a while to find the recommendation to adjust `ulimit -n`. I've added a `rescue Errno::EMFILE` around the offending call in `lock_file.rb` and added an `onoe` message  that recommends using `ulimit -n` to increase the maximum number of open files.
~~~
$ brew upgrade osrf/simulation/gz-sim7 --debug
...
==> Upgrading osrf/simulation/gz-sim7
7.3.0 -> 7.4.0 
Error: Consider using `ulimit -n` to increase the maximum number of open files allowed on this system.
Error: Too many open files @ rb_sysopen - /usr/local/var/homebrew/locks/gz-physics6.formula.lock …
=> lock_file: better message if too many open files

.github/workflows/tests.yml
-----
- These are deprecated and going away in less than a month. Today was another scheduled brownout from GitHub (https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/), and they've been unmarked as "required" checks in the branch protections because the images are unavailable and the jobs were failing.
=> ci: Move from Ubuntu 18.04 to Ubuntu 20.04 Actions runners

Library/Homebrew/api.rb, Library/Homebrew/dev-cmd/unbottled.rb, Library/Homebrew/requirements/macos_requirement.rb, Library/Homebrew/requirements/xcode_requirement.rb
-----
Closes #14563.
This PR fixes some issues with `MacOSRequirement` handling and related `brew info`/`brew unbottled` output on Linux. I have not (yet) added tests but would be happy to if we feel that it is important to add some for these cases.
Prior to this PR, on Linux:
```
linuxbrew@0e6abcd7b4ed:~/.linuxbrew/Homebrew$ brew info tart
...
==> Requirements
Build: Xcode >= 14.1 ✔
Required: arm64 architecture ✘, macOS ✔, macOS ✘
...
linuxbrew@0e6abcd7b4ed:~/.linuxbrew/Homebrew$ brew unbottled --tag big_sur tart
==> Populating dependency tree...
==> :big_sur bottle status
tart: requires Linux
```
After this PR, on Linux:
```
linuxbrew@0e6abcd7b4ed:~/.linuxbrew/Homebrew$ brew info tart
...
==> Requirements
Build: Xcode >= 14.1 (on macOS) ✔
Required: arm64 architecture ✘, macOS >= 12 (or …
```
=> Fix `{MacOS,Xcode}Requirement` handling and improve output

Library/Homebrew/extend/kernel.rb, Library/Homebrew/global.rb, Library/Homebrew/livecheck/strategy.rb, Library/Homebrew/test/utils_spec.rb, Library/Homebrew/utils.rb
-----
Relates to https://github.com/Homebrew/brew/issues/10508
This removes `ActiveSupport` `String` inflections. The performance impact is minimal, bc most of the time was spent in requiring `i18n`, which remains as a transitive require (I prefer to pull these out one at a time).
=> Remove ActiveSupport String inflections

.gitignore, .irb_config, Library/Homebrew/brew_irbrc, Library/Homebrew/dev-cmd/irb.rb
-----
This resolves #14832.
It adds the two things mentioned in the original issue.
1. https://github.com/Homebrew/brew/pull/14892/commits/11a0ea18335cf1901e5e21c964493e2a233cc058 The ability to pass `--debug` and `--quiet` to IRB without it choking.
```rb
/u/l/Homebrew (irb-improvements|✔) $ brew irb --debug
==> Interactive Homebrew Shell
Example commands available with: `brew irb --examples`
irb(main):001:0> Context.current
=> #<Context::ContextStruct:0x00007fc8229a6220 @debug=true, @quiet=false, @verbose=false>
irb(main):002:0> exit
/u/l/Homebrew (irb-improvements|✔) $ brew irb --quiet
==> Interactive Homebrew Shell
Example commands available with: `brew irb --examples`
irb(main):001:0> Context.current
=> #<Context::ContextStruct:0x00007f8a6da71b98 @debug=false, @quiet=true, …
```
=> `brew irb` improvements

Library/Homebrew/download_strategy.rb
---
160e7da779 download_strategy: handle incorrectly quoted filename* headers
Some servers erroneously double-quote the filename in the filename*
header. This is (as far as I can tell from the spec) a bug in the
server, and should be fixed there.
In general though using `""` as the filename seems like behaviour worth
handling in brew anyway, as there may be other places where the parser
returns an empty string.
Co-authored-by: Mike McQuaid <mike@mikemcquaid.com>
<br/>
=> download_strategy: handle incorrectly quoted filename* headers

Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
This should allow maintainers to quickly spot important information about a release (if it's on GitHub)
=> bump-formula-pr: add release notes if found

Library/.rubocop.yml, Library/Homebrew/cask/download.rb, Library/Homebrew/cleaner.rb, Library/Homebrew/cmd/deps.rb, Library/Homebrew/cmd/fetch.rb, Library/Homebrew/diagnostic.rb, Library/Homebrew/extend/kernel.rb, Library/Homebrew/formula.rb, Library/Homebrew/formula_text_auditor.rb, Library/Homebrew/os/linux.rb, Library/Homebrew/os/mac.rb, Library/Homebrew/os/mac/sdk.rb, Library/Homebrew/os/mac/xcode.rb, Library/Homebrew/readall.rb, Library/Homebrew/resource.rb, Library/Homebrew/software_spec.rb, Library/Homebrew/utils/formatter.rb
-----
- This was a TODO. So I did _some of_ it. Not gone through all of them yet, but this is a significantly shorter list.
=> rubocop: Trim `Naming/MethodParameterName` allowlist

Library/Homebrew/github_packages.rb
-----
I propose we try `skopeo`'s built-in mechanism for retrying the process of copying the artifacts and see if that finally helps in our bottles publishing workflow from homebrew-core.
=> github_packages: retry skopeo copy 5 times

Library/Homebrew/formula_text_auditor.rb, Library/Homebrew/utils/formatter.rb
-----
- Three characters is the RuboCop limit for parameter names, but more descriptive is good.
- Requested in https://github.com/Homebrew/brew/pull/14922#pullrequestreview-1330848594, but the automerge was too quick for me to get to it.
=> Make `str` variable names longer

Library/Homebrew/dev-cmd/cat.rb
If `brew cat --cask/--formula` fails, suggest `brew info --github --cask/--formula` instead of just `brew info --github`
Previous discussion/PR #14902
@muescha @MikeMcQuaid FYI
=> include `--cask` or `--formula` in `brew info --github` suggestion

Library/Homebrew/github_packages.rb
-----
I hope this isn't going too far. Another failures (that aren't handled by `skopeo`, see https://github.com/Homebrew/homebrew-core/pull/125152#issuecomment-1461207051) have been seen recently:
https://github.com/Homebrew/homebrew-core/actions/runs/4370167585/jobs/7644794677
https://github.com/Homebrew/homebrew-core/actions/runs/4370971036/jobs/7646393927
=> github_packages: additional retry of skopeo copy with backoff

Library/Homebrew/description_cache_store.rb, Library/Homebrew/search.rb
-----
Resolves https://github.com/Homebrew/brew/issues/14938
https://github.com/Homebrew/brew/pull/14916 converted `search` from a mixin to a singleton method. This broke for classes that implement a `private` `select` method.
=> Fix DescriptionCacheStore searching

Library/Homebrew/test/dev-cmd/irb_spec.rb
-----
This was caused by the irb spec which I forgot to update while working on this command a few days ago. Note that $HOME is set during the test setup so will always be correct.
```
/u/l/Homebrew (master|✔) $ git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
/u/l/Homebrew (master|✔) $ brew tests --only=dev-cmd/irb
Randomized with seed 26142
1 process for 1 spec, ~ 1 spec per process
..
Took 5 seconds
/u/l/Homebrew (master|✔) $ git status
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
Library/Homebrew/test/.brew_irb_history
nothing added to commit but untracked files present (use "git add" to track)
```
```
/u/l/Homebrew …
```
=> Cleanup irb history file in tests

Library/Homebrew/cask/metadata.rb, Library/Homebrew/cask/metdata.rbi, Library/Homebrew/dev-cmd/bump-formula-pr.rb, Library/Homebrew/dev-cmd/bump-unversioned-casks.rb, Library/Homebrew/dev-cmd/irb.rb, Library/Homebrew/dev-cmd/pr-automerge.rb, Library/Homebrew/dev-cmd/pr-upload.rb, Library/Homebrew/dev-cmd/prof.rb, Library/Homebrew/dev-cmd/ruby.rb, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/diagnostic.rb, Library/Homebrew/extend/os/mac/extend/ENV/std.rb, Library/Homebrew/extend/os/mac/extend/ENV/super.rb, Library/Homebrew/formula_assertions.rb, Library/Homebrew/formula_assertions.rbi, Library/Homebrew/keg_relocate.rb, Library/Homebrew/language/python.rb, Library/Homebrew/language/python.rbi, Library/Homebrew/test.rb, Library/Homebrew/unlink.rb, Library/Homebrew/utils/analytics.rb, Library/Homebrew/utils/autoremove.rb, Library/Homebrew/utils/curl.rb, Library/Homebrew/utils/curl.rbi, Library/Homebrew/utils/formatter.rb, Library/Homebrew/utils/formatter.rbi, Library/Homebrew/utils/github/api.rb, Library/Homebrew/utils/github/api.rbi, Library/Homebrew/utils/repology.rb, Library/Homebrew/utils/repology.rbi
-----
This is a mix of files with typing enabled (we're down to <100 files outside of  the `sorbet`/`test`/`vendor` dirs that are `typed: false`, so i'm chipping away at these when i have a few cycles to spare)
=> Enable typing in a few more files

Library/Homebrew/api.rb, Library/Homebrew/brew.sh, Library/Homebrew/global.rb
Instead of doing so literally whenever we query for a formula, Instead do so only when we're in an auto-updateable command.
This better fits the existing behaviour while still updating when it's most important to do so.
Fixes https://github.com/Homebrew/brew/issues/14901
=> Auto-update from the API less often

Library/.rubocop.yml
-----
- We got rid of the RSpec-related excludes in #14920. I should have got rid of this comment too.
=> rubocop: Remove comment about RSpec from `Style/BlockDelimiters` config

Library/.rubocop.yml, Library/Homebrew/build.rb, Library/Homebrew/build_environment.rb, Library/Homebrew/caveats.rb, Library/Homebrew/cleaner.rb, Library/Homebrew/cleanup.rb, Library/Homebrew/cmd/deps.rb, Library/Homebrew/cmd/fetch.rb, Library/Homebrew/cmd/gist-logs.rb, Library/Homebrew/cmd/info.rb, Library/Homebrew/debrew.rb, Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/dev-cmd/test.rb, Library/Homebrew/diagnostic.rb, Library/Homebrew/extend/kernel.rb, Library/Homebrew/extend/os/mac/system_config.rb, Library/Homebrew/fetch.rb, Library/Homebrew/formula_pin.rb, Library/Homebrew/install.rb, Library/Homebrew/options.rb, Library/Homebrew/os/mac.rb, Library/Homebrew/rubocops/components_order.rb, Library/Homebrew/system_config.rb, Library/Homebrew/tab.rb, Library/Homebrew/test/caveats_spec.rb, Library/Homebrew/test/formula_installer_bottle_spec.rb, Library/Homebrew/upgrade.rb, Library/Homebrew/utils/analytics.rb, Library/Homebrew/utils/bottles.rb, Library/Homebrew/version.rb
-----
- The most blast radius change here is "f" => "formula". I ran `brew typecheck` which caught some occurrences I hadn't picked up, I ran `brew tests` which caught some more, and I ran `brew style` which caught even more. Worth a second set of eyes though?
=> rubocop: Further trim `Naming/MethodParameterName` allowlist

Library/Homebrew/env_config.rb
-----
Noticed this while reviewing https://github.com/Homebrew/brew/pull/14950.
=> Check `CUSTOM_IMPLEMENTATIONS` for all variables.

Library/Homebrew/unpack_strategy/dmg.rb
-----
This error is pretty much impossible to reproduce and only happens rarely on CI.
My naive guess is that mounting a DMG on CI is slow sometimes meaning we try finding files which aren't mounted yet. Not sure if that's actually how `hdiutil` works but we'll see.
Fail in both cases, so we actually see if retrying fixes this or not.
=> Retry if DMG BOM is empty.

Library/Homebrew/download_strategy.rb
-----
Most of the time, a fresh repository init / clone includes a `.git/info` directory. However, if a custom git [template directory](https://git-scm.com/docs/git-init#_template_directory) is used, and that template doesn't include an `info` directory, the `.git/info` directory will be missing from the new repository checkout. That causes the sparse checkout download strategy to fail when it tries to write to `.git/info/sparse-checkout` (https://github.com/Homebrew/homebrew-cask-fonts/issues/6961). This change ensures the directory exists before writing that file.
I was able to reproduce the crash in https://github.com/Homebrew/homebrew-cask-fonts/issues/6961 by installing the font, deleting the `.git/info` directory, then reinstalling the font. After applying this change, I was unable …
=> Create .git/info dir if it doesn't exist

Library/Homebrew/cask/installer.rb
-----
This output is way too verbose.
An artifact refers to a cask, which in turn refers to a tap, which in turn has a list of all casks_files in this tap.
When e.g. installing `font-sauce-code-pro-nerd-font` there are 28 artifacts, each of which prints every single font cask file path since these are contained in the `Font#inspect -> Cask#inspect -> Tap#inspect` output.
=> Remove artifact debug output.

Library/.rubocop.yml, Library/Homebrew/utils/pypi.rb
-----
- With RuboCop 1.48.1 this no longer reports offenses and applies bugged autocorrections for `attr`s with Sorbet `sig`s, so we can enable it.
=> rubocop: Enable `Style/AccessorGrouping` and autofix offenses

Dockerfile
Some of these packages are only available on newer versions.
Regression from https://github.com/Homebrew/brew/pull/14968
=> Dockerfile: fix build of Ubuntu 18.04 image.

Library/Homebrew/extend/kernel.rb, Library/Homebrew/test/extend/kernel_spec.rb, Library/Homebrew/test/utils_spec.rb, Library/Homebrew/utils.rb
-----
`capture_stderr` appears to be unused as of https://github.com/Homebrew/brew/pull/6534/files#diff-26cf784bce69883e02a2c58db0c9666d7e626c488675b48fe344e909fa34f5d7L23
The [two](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bottle.rb#L730) [instances](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/pr-pull.rb#L430) of `parse_author!` were already in the `Utils` namespace, so I relocated that method.
=> Minor Kernel cleanup

Library/Homebrew/env_config.rb, Library/Homebrew/sorbet/custom_generators/env_config.rb
-----
Fixes error in https://github.com/Homebrew/brew/pull/14977.
=> Fix `env_config` generator.

.github/workflows/tests.yml
This will enable the GitHub Merge Queue. Don't bother running online tests as they aren't required, use up the rate limit and are flaky.
=> workflows/tests: enable merge group builds.

Library/.rubocop.yml, Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/extend/os/mac/keg_relocate.rb, Library/Homebrew/tab.rb, Library/Homebrew/test/support/lib/startup/config.rb, Library/Homebrew/test/tab_spec.rb
-----
Following up on https://github.com/Homebrew/brew/pull/14826 this removes `OpenStruct` use in `Tap` (and enables typing). I don't have direct experience with `Tap` though, so this PR should be reviewed by a critical eye by someone who does.
=> Remove OpenStruct use in Tab

docs/Formula-Cookbook.md
-----
Previous syntax is invalid
=> Fix keep_alive sample code in formula cookbook

Library/Homebrew/cmd/nodenv-sync.rb, Library/Homebrew/cmd/rbenv-sync.rb
Add these commands to ease use of Homebrew's bottles with `rbenv` and `nodenv`.
I've had a lot of people request this over the years and it's worked well for me for a long time.
I could see people extending these to support other languages or version managers so perhaps we want a more generic name.
Migrated from https://github.com/Homebrew/homebrew-core/pull/125503
Marking as `critical` as already went through some rounds of review over there.
=> cmd/{rb,nod}env-sync: add new commands.

Library/Homebrew/dev-cmd/contributions.rb
-----
- It's possible to hide your contribution graph and not be searchable on GitHub. Let's make sure `brew contributions` and other things that may eventually use `count_issues` don't fall over when they encounter this scenario.
=> dev-cmd/contributions: Don't fall over if a user's profile is private

Library/Homebrew/github_packages.rb
-----
Quick follow-up to https://github.com/Homebrew/brew/pull/14981
I think `GitHubPackages` uses `Tab`, but doesn't have sufficient tests or type annotations to have been caught automatically.
If this is a concern, we could potentially define a compatibility layer in `Tab`, something like this (maybe with an `odeprecated` message):
```ruby
def []=(key, value)
self.send("#{key}=", value)
end
def [](key)
self.send(key)
end
```
This PR should probably be manually tested by someone who understands both `GitHubPackages` uses `Tab` before going in.
=> Update GitHubPackages for new Tab implementation

Library/Homebrew/github_packages.rb
Reverts Homebrew/brew#14983 because bottle publishing is failing with `undefined method arch for Hash` (https://machomebrew.slack.com/archives/CTHMNNM7H/p1678921676329519).
=> Revert "Update GitHubPackages for new Tab implementation"

Library/Homebrew/download_strategy.rb, Library/Homebrew/download_strategy.rbi, Library/Homebrew/patch.rb, Library/Homebrew/pkg_version.rb, Library/Homebrew/pkg_version.rbi, Library/Homebrew/style.rb, Library/Homebrew/utils/git.rb, Library/Homebrew/utils/github.rb
-----
I think `Github.last_commit` has been busted since https://github.com/Homebrew/brew/pull/14112/files#diff-0b87a525dc494bc971692d4384fa8f200851cc433dbfb297e513b6c7b5ba07efR684 bc it did not thread `version` into the method (and the file wasn't typed). This fixes that oversight, enables typing, and also updates a few more nearby files to enable typing.
=> Fix GitHub.last_commit and enable more typing

Library/Homebrew/cask/audit.rb, Library/Homebrew/test/utils/curl_spec.rb, Library/Homebrew/utils/curl.rb
-----
- Fixes #14607.
- Some casks have URL arguments like "referer" (spelled wrong, that's intentional in the HTTP spec).
- The audit for one such cask, `iThoughtsX`, was failing because the "referer" wasn't getting passed through to cURL so the access would 404.
TODO:
----
Before:
```
❯ brew audit --cask --online --appcast --signing 'ithoughtsx'
[...]
audit for ithoughtsx: failed
- The binary URL https://cdn.toketaware.com?download=iThoughtsX.zip is not reachable (HTTP status code 404)
- Version '9.2.0' differs from '9.3.0' retrieved by livecheck.
- Version '9.2.0' differs from '9.3.0' retrieved by livecheck.
Error: 2 problems in 1 cask detected
```
After:
```
❯ brew audit --cask --online --appcast --signing 'ithoughtsx'
[...]
audit for ithoughtsx: failed
- Version '9.2.0' differs from …
```
=> cask/audit: Pass a URL's `referer` through to cURL

Library/Homebrew/locale.rb, Library/Homebrew/test/locale_spec.rb, docs/Cask-Cookbook.md
-----
The locale module has been parsing locale strings in the wrong format. The correct format is "language-script-region" instead of "language-region-script". This wrong format broke the system language parsing.
```shell
> defaults read -g AppleLanguages
(
"zh-Hans-CN"
)
```
Besides the real output above, you can also refer to: https://en.wikipedia.org/wiki/IETF_language_tag#Syntax_of_language_tags.
=> Fix locale parsing

Library/Homebrew/cask/artifact/abstract_uninstall.rb, Library/Homebrew/cask/dsl/caveats.rb, Library/Homebrew/os/mac/xcode.rb, Library/Homebrew/test/support/fixtures/cask/everything.json, docs/Cask-Cookbook.md
"System Preferences" has been renamed to "System Settings" on Ventura. Privacy and security settings have moved, too. This PR makes sure these changes are reflected. (Some adjustments were already made in #14092.)
-----
All but one of `brew tests` passed locally. Though unrelated to this change, I don't know why this one failed (it failed on `master` too):
```
Failures:
1) brew bottle builds a bottle for the given Formula
Failure/Error:
expect { brew "bottle", "--no-rebuild", "testball" }
.to output(/testball--0\.1.*\.bottle\.tar\.gz/).to_stdout
.and not_to_output.to_stderr
.and be_a_success
expected block to not output to stderr, but output "tar: Could not open extended attribute file: Permission denied\ntar: Could not open extended attribute file: Permission denied\ntar: Could not open …
```
=> Update path to system settings on Ventura

Library/Homebrew/utils/github/actions.rb
-----
Needed for https://github.com/Homebrew/actions/pull/336, see @Bo98's comment:
> Escaping works differently now so this doesn't work. The new way to do it is:
> 
> ```
> {name}<<{delimiter}
> {value}
> {delimiter}
> ```
> 
> For security reasons `delimiter` must be randomly generated and unique to each run (e.g. UUID v4). It should also be something that doesn't appear in the `message`. It may be worth having a new method in `Homebrew/brew`.
> 
> See https://github.com/actions/toolkit/blob/b00a9fd033f4b30f2355acd212f531ecbbb9b38f/packages/core/src/file-command.ts#L27-L47 for an example implementation in JavaScript.
=> utils/github/actions: add `format_multiline_string` method

Library/Homebrew/utils/github/actions.rb
-----
As pointed out in https://github.com/Homebrew/brew/pull/15002#discussion_r1141081780, we don't really need the `Error` class as we're not rescuing from it anywhere. Let's avoid having unnecessary code 😅.
=> utils/github/actions: remove `Error` class

.github/workflows/tests.yml
-----
fixes #14692
~~I can't confirm if these changes work as they are related to cache which I can't test in my fork.~~
=> CI: use actions/cache@v3

Library/Homebrew/extend/pathname.rb
`install-info` is not shipped with macOS Ventura and some Linux distros. This commit uses `install-info` from `texinfo` formula if it is not available in `/usr/bin`.
See: https://github.com/Homebrew/discussions/discussions/4306
-----
=> Use `install-info` from `texinfo` if not available in `/usr/bin`

Library/Homebrew/caveats.rb, Library/Homebrew/test/caveats_spec.rb
-----
- This was pointed out by Carlo in https://github.com/Homebrew/brew/issues/14925#issuecomment-1473303922, it annoyed me the moment I saw it too, and it was a very quick fix.
- The caveats items are joined by "\n" before being displayed, so the extra `\n` here when generating the `keg_only_text` meant that there were two blank lines which looked weird. This `keg_only_text` method is only used here so it doesn't affect anywhere else we show the `keg_only` message, if there are any other places.
-----
Before:
```
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew info socket_vmnet
[...]
==> Caveats
socket_vmnet requires root privileges so you will need to run
`sudo /opt/homebrew/opt/socket_vmnet/socket_vmnet` or `sudo brew services start socket_vmnet`.
You should be certain that you trust any …
```
=> caveats: Remove extra blank line between `keg_only` and other caveats

Library/Homebrew/cask/cask.rb, Library/Homebrew/cask/cask_loader.rb
This was just a temporary workaround while we
waited for the API to regenerate the JSON content.
-----
This is just a follow-up to changing the prefix placeholder for casks in https://github.com/Homebrew/brew/pull/14615. It should be fine now since it's been around a month since the original PR and the API JSON gets reloaded for users every day or so. There is an edge case where someone is on the most recent brew version but has a really old `cask.json` file but I doubt that's worth worrying about.
=> cask: remove old prefix placeholder

Library/Homebrew/dev-cmd/pr-pull.rb
-----
Needed for Homebrew/homebrew-core#125556. Without this, `pr-pull`
attempts to cherry-pick commits from the PR branch onto the PR branch,
and then gets upset that nothing happened.
See https://github.com/Homebrew/homebrew-core/actions/runs/4461335852/jobs/7835095294#step:10:40
=> pr-pull: add `--no-cherry-pick` flag

Library/Homebrew/dev-cmd/contributions.rb
-----
Pluralize the contribution statement appropriately
```
$ brew contributions --user dtrodrigues --from 2023-03-15T01:00:00Z --to 2023-03-15T02:00:00Z --repositories=core
dtrodrigues contributed 1 times between 2023-03-15T01:00:00Z and 2023-03-15T02:00:00Z.
```
After:
```
$ brew contributions --user dtrodrigues --from 2023-03-15T01:00:00Z --to 2023-03-15T02:00:00Z --repositories=core
dtrodrigues contributed 1 time between 2023-03-15T01:00:00Z and 2023-03-15T02:00:00Z.
```
=> dev-cmd/contributions: appropriately pluralize contribution statement

Library/Homebrew/cask/cmd/install.rb, Library/Homebrew/cask/installer.rb, Library/Homebrew/cmd/info.rb, Library/Homebrew/cmd/tap-info.rb, Library/Homebrew/cmd/update-report.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/dev-cmd/contributions.rb, Library/Homebrew/diagnostic.rb, Library/Homebrew/extend/kernel.rb, Library/Homebrew/install.rb, Library/Homebrew/tap.rb, Library/Homebrew/test/utils_spec.rb, Library/Homebrew/upgrade.rb, Library/Homebrew/utils.rb
-----
This adds an argument, `include_count`, to the `pluralize` util which includes the value of `count` in the string returned by the function.
=> Add include_count parameter to pluralize util

Library/Homebrew/cask/installer.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/test/utils/analytics_spec.rb, Library/Homebrew/utils/analytics.rb
- roll InfluxDB token (we need to report to a new bucket to fix implicit schema)
- adjust various parameters
- separate default tags and fields
- send more fields and fewer tags (tags should have low cardinality)
- use `--data-binary` to match InfluxDB documentation
- use hour precision for greater InfluxDB performance
- pass through tap name, formula/cask name, options separately
- pass `devcmdrun` as a tag
- avoid sending very high-cardinality OS_VERSION values
=> analytics: improve InfluxDB cardinality

Library/Homebrew/unpack_strategy/dmg.rb
-----
Retrying works, so remove the explicit error.
Saw it here: https://github.com/reitermarkus/dotfiles/actions/runs/4408439611/jobs/7859591762#step:3:12561
=> Remove explicit error for empty BOM retry.

Library/Homebrew/rubocops/cask/ast/cask_block.rb, Library/Homebrew/rubocops/cask/ast/stanza.rb, Library/Homebrew/rubocops/cask/extend/node.rb
-----
Not sure if this fixes anything for the other PRs, but it should at least make tests behave more consistently when using only a single stanza.
=> Fix `toplevel_stanzas`.

Library/Homebrew/keg.rb, Library/Homebrew/mktemp.rb, Library/Homebrew/options.rb, Library/Homebrew/options.rbi, Library/Homebrew/os/linux/elf.rb, Library/Homebrew/os/linux/elf.rbi, Library/Homebrew/os/mac/mach.rb, Library/Homebrew/os/mac/mach.rbi
-----
Here are five more files that are fairly straightforward to enable typing in (there are only ~33 non-test files with typing disabled after this change).
=> Enable more typing

Library/Homebrew/formula_auditor.rb
-----
- Fixes #14996.
- The API JSON is generated with a `/usr/local` Homebrew prefix, but frequently now users have `/opt/homebrew` as their prefix. Since formulae `keg_only` reasons are generated by the API, this can lead to the confusing messaging that follows:
```
socket_vmnet is keg-only, which means it was not symlinked into /opt/homebrew,
because /usr/local/bin is often writable by a non-admin user.
```
- With this change, that formula as it is now will fail `brew audit`, prompting to remove the prefix reference.
```
❯ HOMEBREW_NO_INSTALL_FROM_API=1 brew audit --strict socket_vmnet
socket_vmnet:
* `keg_only` reason should not include `HOMEBREW_PREFIX` as it provides confusing output.
Error: 1 problem in 1 formula detected
```
=> formula_auditor: Having `HOMEBREW_PREFIX` in `keg_only` reasons is bad

Library/Homebrew/cmd/update-report.rb
New formulae/casks were shown as removed and vice versa.
Fixes #15036
=> cmd/update-report: fix ordering.

Library/.rubocop.yml, Library/Homebrew/dev-cmd/pr-pull.rb, Library/Homebrew/utils/github.rb
-----
- Core RuboCop didn't want this shortening upstreamed, but that's OK!
=> rubocop: Remove the final `Naming/MethodParameterName` exceptions: `pr`

.github/workflows/docker.yml, .github/workflows/tests.yml, Dockerfile, docs/Linux-CI.md
This is too slow to be building every time and we're long past the deprecation date.
We talked about pushing some sort of error script here. Anyone is welcome to do that as a one-off but we need to remove this image.
Fixes https://github.com/Homebrew/brew/issues/14661
=> docker: stop building Ubuntu 16.04 image.

Library/Homebrew/cask/cask.rb, Library/Homebrew/cmd/fetch.rb, Library/Homebrew/dev-cmd/bump-cask-pr.rb, Library/Homebrew/formula.rb, Library/Homebrew/readall.rb
-----
Add `--arch` flag for `brew fetch` to allow testing ARM cask downloads in CI. Also add `ensure` before all `Homebrew::SimulateSystem.clear`s.
=> Allow fetching for different arch.

Library/Homebrew/cask/dsl.rb, Library/Homebrew/cask/dsl/base.rb
-----
This passes the `arch` variable from casks to `flight` blocks. Unblocks https://github.com/Homebrew/homebrew-cask/pull/143791
=> cask/dsl: pass #{arch} to flight blocks

Library/Homebrew/cleanup.rb, Library/Homebrew/test/cleanup_spec.rb
-----
Enables typing in `Homebrew::Cleanup`. This mainly involves converting a refinement to a static utils module. The refinement was limited to a single file so it isn't too messy to refactor. I also added `sig`s to the converted methods to add confidence.
=> Enable typing in Homebrew::Cleanup

Library/Homebrew/extend/ENV/super.rb, Library/Homebrew/extend/os/mac/extend/ENV/shared.rb, Library/Homebrew/extend/os/mac/extend/ENV/std.rb, Library/Homebrew/extend/os/mac/extend/ENV/super.rb, Library/Homebrew/shims/super/cc
-----
Invoking `ld` with `-undefined dynamic_lookup` emits a warning starting
Xcode 14:
ld: warning: -undefined dynamic_lookup may not work with chained fixups
Chained fixups is a linker optimisation that results in faster binary
load times, and is enabled by default starting Xcode 13 when the target
is macOS 12 or newer.
However, this interacts poorly with `-undefined dynamic_lookup`, and
Xcode will disable chained fixups when it is invoked with this flag
starting Xcode 14.3. Until then, we may be shipping binaries that are
broken in subtle ways, so let's disable chained fixups when necessary
instead.
I patterned the changes here after the handling of `-no_weak_imports`.
The only difference is that we need to check the flags that were passed
to the linker first to see if we do need to …
=> Pass `-no_fixup_chains` to linker when required

.github/workflows/tests.yml
-----
Now the steps that say they run on all taps are after the one where we set up all taps. This might have been done on purpose before for performance reasons though. I'm not sure.
=> CI: Add audit steps for formulae and casks

Library/Homebrew/extend/os/linux/formula.rb, Library/Homebrew/extend/os/mac/formula.rb, Library/Homebrew/formula.rb, Library/Homebrew/search.rb
-----
Resolves #15053.
The idea here is that formulas that are only available on one OS should only show up in the search results for the platform.
=> search: show results by platform

Library/Homebrew/Gemfile, Library/Homebrew/Gemfile.lock, Library/Homebrew/dev-cmd/irb.rb, Library/Homebrew/dev-cmd/prof.rb
Let's resolve the intermittent issues we've seen when various installed on demand gems cannot be installed by including them all in the Gemfile.
=> Vendor more gems

Library/Homebrew/extend/os/formula.rb
-----
This allows `Formula#valid_platform?` to work correctly on MacOS. It was left out of #15072 by accident. This meant MacOS only formulae were left out of search results.
```
/u/l/Homebrew (search-by-platform|✔) $ brew search xmount
==> Casks
mounty
/u/l/Homebrew (search-by-platform|✚1) $ brew search chisel
==> Formulae
chisel
```
```
/u/l/Homebrew (search-by-platform|✚1) $ brew search xmount
==> Formulae
xmount
/u/l/Homebrew (search-by-platform|✚1) $ brew search chisel
Error: No formulae or casks found for "chisel".
```
=> formula: add missing extend/os require

Library/Homebrew/rubocops/components_order.rb, Library/Homebrew/rubocops/lines.rb, Library/Homebrew/rubocops/shared/on_system_conditionals_helper.rb, Library/Homebrew/test/rubocops/components_order_spec.rb
-----
- The formula part of #14017.
- Previously this components order cop only checked for correct stanza order inside `on_*` blocks and at the top-level. This commit extends this cop to also check for correct stanza order inside `head` and `resource` blocks. This is a positive change since it standardizes the order in all of the places, making formulae more readable.
-----
TODO:
- https://github.com/Homebrew/homebrew-core/pull/126705
=> rubocops: Detect unordered stanzas in non-`on_*` blocks in formulae

Library/Homebrew/rubocops/lines.rb, Library/Homebrew/rubocops/shared/on_system_conditionals_helper.rb
-----
This reverts commit b4cd90a3cc47bc2f94e4449fa99b37445b878a5f.
This should never have been merged but I didn't realise I hadn't backed it out of #15060 before it was approved and I merged it.
We had a multi-person discussion and it was decided against in https://github.com/Homebrew/homebrew-core/pull/126705#discussion_r1149545828.
=> Revert "Allow `resource` blocks to include `on_*` blocks or conditionals"

Library/Homebrew/dev-cmd/bump-cask-pr.rb, Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
When using bump-*-pr commands on taps with custom remote, an error message will appear:
```
Error: Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}]
```
I found that it is caused by wrong `repo` argument when requesting GitHub API: the remote url of the repo is passed, not the full name of the repo. So GitHub cannot find it and returns back an error.
=> bump-*-pr: fix an issue when using on taps with custom remote

Library/Homebrew/dev-cmd/pr-automerge.rb, Library/Homebrew/dev-cmd/pr-publish.rb
-----
This will be made the default by Homebrew/homebrew-core#127021.
Additionally, branch protection rules will make it so that attempting to
push to master will fail, so we may as well not have to carry this flag
around.
=> dev-cmd/pr-*: remove `--commit-bottles-to-pr-branch`

Library/Homebrew/cmd/install.rb, Library/Homebrew/install.rb
Previous #15042 doesn't pass the flag all the way to `FormulaInstaller.new`
-----
=> Fix `brew install --skip-post-install`

Library/Homebrew/dev-cmd/tests.rb
-----
We're seeing BuildPulse failures again on some PRs so let's use `system_command` again for now. Ref: #15100, #15101, #15102.
```
==> Sending test results to BuildPulse
env: parse error on field "GithubRunID" of type "uint": strconv.ParseUint: parsing "4569488695": value out of range
Error: Failure while executing; `/usr/bin/env /home/linuxbrew/.linuxbrew/opt/buildpulse-test-reporter/bin/buildpulse-test-reporter submit /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/junit --account-id 1503512 --repository-id 53238813` exited with 1. Here's the output:
<buildpulse> Current version: BuildPulse Test Reporter 0.24.2 (linux Homebrew go1.20.1)
<buildpulse> Initiating `submit`
<buildpulse> Received args: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/junit --account-id …
```
=> dev-cmd/tests: temporary fix for BuildPulse failure

docs/Cask-Cookbook.md
Add mention of the `keyboard_layout` stanza, added in https://github.com/Homebrew/brew/pull/15061. This also rearranges the artifact stanza table to more closely follow their preferred order.
=> docs: mention `keyboard_layout` for casks

Library/Homebrew/download_strategy.rb, Library/Homebrew/livecheck/strategy.rb
This has caused a regression: https://github.com/Homebrew/brew/pull/15089#issuecomment-1490945405
Reverts Homebrew/brew#15089
Closes https://github.com/Homebrew/brew/pull/15096
=> Revert "Remove `--request GET` workaround for HEAD requests."

.github/workflows/tests.yml, Library/Homebrew/Gemfile, Library/Homebrew/dev-cmd/install-bundler-gems.rb, Library/Homebrew/dev-cmd/prof.rb, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/dev-cmd/vendor-gems.rb, Library/Homebrew/utils/gems.rb
Fixes portable-ruby CI.
These two were also native gems so this speeds up the overall install a little.
=> Split prof gems into their own group

Library/Homebrew/debrew.rb, Library/Homebrew/dev-cmd/update-test.rb, Library/Homebrew/ignorable.rb, Library/Homebrew/ignorable.rbi, Library/Homebrew/sorbet/rbi/upstream.rbi
-----
Enables typing for the `Ignorable` and `Debrew` files.
Restores the upstream.rbi file to include type definitions that are necessary but not in our version of sorbet. (They're a pair of private methods, so pretending them with `T.unsafe(self)` doesn't work.)
=> Enable typing in Ignorable

Library/Homebrew/install.rb
-----
Currently, doing `brew install --only-dependencies` with an unlinked
formula does nothing and returns a message saying the formula is already
installed but just not linked.
I think that we should just install the dependencies as requested here
instead of complaining that the formula isn't linked.
Before:
❯ brew unlink adplug
Unlinking /usr/local/Cellar/adplug/2.3.3... 8 symlinks removed.
❯ brew install --only-dependencies adplug
Warning: adplug 2.3.3 is already installed, it's just not linked.
To link this version, run:
brew link adplug
After:
❯ brew install --only-dependencies adplug
==> Fetching dependencies for adplug: libbinio
==> Fetching libbinio
==> Downloading https://ghcr.io/v2/homebrew/core/libbinio/manifests/1.5
[snip]
See Homebrew/homebrew-core#127133 for additional …
=> install: check for `--only-dependencies` flag earlier

Library/Homebrew/dev-cmd/tap-new.rb
-----
- Fixes #15126.
- We forgot about this workflow when we bumped the versions of our actual workflows in #14692.
=> dev-cmd/tap-new: Use `actions/cache@v3` as v1 is very deprecated

Library/Homebrew/cmd/postgresql-upgrade-database.rb, Library/Homebrew/dependencies.rb, Library/Homebrew/dependencies.rbi, Library/Homebrew/extend/object.rbi, Library/Homebrew/extend/os/linux/dev-cmd/update-test.rb, Library/Homebrew/extend/os/linux/diagnostic.rb, Library/Homebrew/extend/os/linux/hardware/cpu.rb, Library/Homebrew/extend/os/mac/diagnostic.rb, Library/Homebrew/extend/os/mac/hardware/cpu.rb, Library/Homebrew/extend/os/mac/keg.rb, Library/Homebrew/extend/predicable.rb, Library/Homebrew/extend/predicable.rbi, Library/Homebrew/extend/time.rb, Library/Homebrew/livecheck/strategy.rb, Library/Homebrew/utils/pypi.rb
-----
Enables typing in some `extend` files and elsewhere. After this change, ~15 non-test files will remain untyped.
=> Enable types in extensions, etc.

Library/Homebrew/service.rb, Library/Homebrew/test/service_spec.rb
-----
This is a very bad bug that snuck in after #15007. Essentially, it didn't come up during testing because of a bug in my testing script. The `Service#run` handles strings by turning them into arrays. The string argument gets turned into an array internally but we skip that to preserve all args in the `@run_params` variable. That means that we have to handle strings when deserializing too.
This affects 58 services by my count and makes the services impossible to install correctly since the path deserialization doesn't work at all.
```
appium
arangodb
artifactory
asimov
auditbeat
automysqlbackup
bazarr
beanstalkd
bitcoin
bitlbee
black
blazegraph
carrot2
cassandra-reaper
chronograf
clash
clipper
code-server
collector-sidecar
couchdb-lucene
couchdb
daemontools
davmail
docuum
filebeat …
```
=> service: handle string run cmd

Library/Homebrew/dev-cmd/livecheck.rb, Library/Homebrew/formula.rb, Library/Homebrew/livecheck/strategy/apache.rb, Library/Homebrew/livecheck/strategy/bitbucket.rb, Library/Homebrew/livecheck/strategy/cpan.rb, Library/Homebrew/livecheck/strategy/electron_builder.rb, Library/Homebrew/livecheck/strategy/github_latest.rb, Library/Homebrew/livecheck/strategy/gnome.rb, Library/Homebrew/livecheck/strategy/gnu.rb, Library/Homebrew/livecheck/strategy/hackage.rb, Library/Homebrew/livecheck/strategy/launchpad.rb, Library/Homebrew/livecheck/strategy/npm.rb, Library/Homebrew/livecheck/strategy/pypi.rb, Library/Homebrew/livecheck/strategy/sourceforge.rb, Library/Homebrew/livecheck/strategy/xorg.rb, Library/Homebrew/sandbox.rb, Library/Homebrew/system_command.rb
-----
`T.unsafe` around a class/module should be unnecessary now that we [suppress](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/sorbet/config#L5) splat errors. In this case, I was able to remove the wrapper around every match for `git grep -E 'T.unsafe\([[:upper:]]'` without introducing any errors.
=> Remove useless T.unsafe wrappers

.github/workflows/sorbet.yml
-----
An attempt to fix https://github.com/Homebrew/brew/pull/15119
I'm not sure how to kick off a test for this workflow, and I have issues with tapioca locally that I'm still attempting to resolve `Bundler::LockfileError: You must use Bundler 2 or greater with this lockfile.`)
=> Include prof gem group in sorbet workflow

.github/workflows/sorbet.yml, .github/workflows/tests.yml, Library/Homebrew/Gemfile, Library/Homebrew/dev-cmd/install-bundler-gems.rb, Library/Homebrew/dev-cmd/prof.rb, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/dev-cmd/vendor-gems.rb, Library/Homebrew/utils/gems.rb
Reverts Homebrew/brew#15112
Reverts https://github.com/Homebrew/brew/pull/15134
This broke the Sorbet workflow (was fixed, reverting here too as this will break it) and the Vendor Gems workflow (still broken https://github.com/Homebrew/brew/actions/runs/4600329850/jobs/8137146086). The latter prevents any gem updates.
CC @Bo98 and @dduugg FYI.
=> Revert "Split prof gems into their own group"

Library/Homebrew/rubocops/cask/url.rb, Library/Homebrew/test/rubocops/cask/url_spec.rb
-----
- Fixes #15108.
- These were [being fixed manually](https://github.com/Homebrew/homebrew-cask/pull/144179#issuecomment-1489857249), so let's make a RuboCop for any further occurrences since this is [a good rule to enforce](https://github.com/Homebrew/homebrew-cask/pull/80965#issuecomment-616232313).
=> rubocops/cask: Ensure that "verified" URLs with paths end with "/"

Library/Homebrew/commands.rb
-----
A comment here would help the reader to understand the need for this splitting logic, which is not so straightforward.
Addresses review comment in https://github.com/Homebrew/brew/pull/15146#discussion_r1157361656.
Also, apply the same logic to shell commands. This was missed in #15146.
=> commands: explain change in command description splitting

Library/Homebrew/dev-cmd/unbottled.rb, Library/Homebrew/extend/os/mac/readall.rb, Library/Homebrew/requirements/macos_requirement.rb, Library/Homebrew/test/version_spec.rb, Library/Homebrew/version.rb, Library/Homebrew/version/head.rb
-----
As a follow-up to https://github.com/Homebrew/brew/pull/15131#discussion_r1156203167 this PR adds `Version#compare`. It may seem like a minor thing, but IMHO this is much easier for the reader to follow along with (which is also why I'm not in turn calling `public_send` within `compare`). I'm open to alternative method names here, e.g. `compare?` is probably more in line with Ruby idioms.
Since version.rb was already overly long, I've also moved `HeadVersion` to a new file and moved it under the `Version` namespace (consistent with how `NullVersion` is structured). There is only a single reference to `HeadVersion`, which is already within `Version`, so I don't believe other changes are necessary.
cc @carlocab
=> Add Version#compare

Library/Homebrew/tap.rb
We should be using the API unless specifically requested not to.
Fixes #15153.
=> tap: remove some CoreTap installed? checks.

Library/Homebrew/dev-cmd/typecheck.rb, Library/Homebrew/dev-cmd/unpack.rb, Library/Homebrew/dev-cmd/update-sponsors.rb, Library/Homebrew/dev-cmd/vendor-gems.rb, Library/Homebrew/sorbet/rbi/upstream.rbi, Library/Homebrew/utils/github.rb
-----
Enables types in the remaining dev commands. (After this change, only five non-test `typed: false` files will remain.)
=> Enable types in dev-cmd

Library/Homebrew/tap.rb
(hmm, I skipped opening an issue first)
(Don't know why but `brew tests` failed even on `master` locally. Perhaps due to I didn't overwrite the old version ruby provided by macOS)
-----
Perhaps since commit f280ce069 (Support loading formulae/casks from subdirectories, 2023-02-24), now `tap.formula_file?(file)` is too loose.
As reported and discussed in https://github.com/Homebrew/homebrew-test-bot/issues/897, in a third-party cask tap (no formulae provided, hence no `Formula` directory), even cask files locating in `Cask` directory pass `tap.formula_file?(file)`.  I think that's wrong because a ruby file cannot both be a formula and a cask.
This PR adds a condition borrowed from `tap.cask_file?(file)` to `tap.formula_file(file)` to ensure formula files and cask files are disjoint.
I have …
=> Tighten `tap.formula_file?(file)` and `tap.formula_files` to not detect cask file as formula

docs/How-To-Organize-AGM.md
The PLC and members workshopped and reviewed this based on past AGMs, especially the 2023 meeting.
-----
=> Import doc "How To Organize AGM" from homebrew-governance-private

Library/Homebrew/cask/upgrade.rb, Library/Homebrew/dev-cmd/bump-cask-pr.rb, Library/Homebrew/env_config.rb, Library/Homebrew/env_config.rbi
-----
Fix #15097, where discussion can be found. 
Alternatively, this option could be modified to include all greedy options.
=> Add HOMEBREW_GREEDY option

.github/workflows/docs.yml, Library/Homebrew/.yardopts, Library/Homebrew/utils/inreplace.rb, Library/Homebrew/yard/templates/default/docstring/html/setup.rb
-----
- Consolidate yard config under `.yardopts`
- Enable typing in yard extension
- Fix output warning:
```
$ yard doc                                                                                                       9:45:02  ☁  master ☂⚑ ⚡ ✭
[warn]: In file `utils/inreplace.rb':54: Cannot resolve link to bin from text:
...{bin}...
Files:         498
Modules:       139 (   28 undocumented)
Classes:       481 (   56 undocumented)
Constants:     402 (  299 undocumented)
Attributes:    261 (  116 undocumented)
Methods:      3396 ( 1467 undocumented)
```
`Inreplace.inreplace` before:
`Inreplace.inreplace` after:
=> Minor YARD improvements

Library/Homebrew/download_strategy.rb, Library/Homebrew/test/download_strategies/curl_github_packages_spec.rb, Library/Homebrew/test/download_strategies/curl_post_spec.rb, Library/Homebrew/test/download_strategies/curl_spec.rb, Library/Homebrew/utils/curl.rb
-----
@samford, I hope you didn't start on the `curl_head` method yet.
This re-adds the `--request GET` workaround, but now `--head` is tried first and a retry with `--request GET` is only done if we didn't get a `Content-Disposition` header, which is the only relevant header containing the resolved filename of a download.
=> Add `curl_head` method.

.github/workflows/tests.yml, Library/Homebrew/cask/audit.rb, Library/Homebrew/cask/auditor.rb, Library/Homebrew/cask/cmd/audit.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/test/cask/audit_spec.rb, Library/Homebrew/test/cask/cmd/audit_spec.rb, Library/Homebrew/test/cask/quarantine_spec.rb
-----
- Fixes #15074.
- Deprecate `brew audit --display-failures-only` for Casks. The default behaviour for formulae is to only display failures, so let's make Casks behave the same way since all the warnings are noisy.
- Only show warnings (less important errors, I guess, now) for Casks if `--strict` (or `--new-cask` which implies `--strict`) is used in `brew audit`.
=> audit: Make `--display-failures-only` the default for Casks

.github/workflows/sponsors-maintainers-man-completions.yml
-----
I *think* this should actually fix the failure seen in https://github.com/Homebrew/brew/actions/runs/4651602426/jobs/8231313421. `origin_branch` falls back to `branch`. This means that the `git-try-push` step will now push to and rebase on the same remote branch. (Previously, it rebased on `master`, not the branch to push to.)
Note that this also means the branch `${{ steps.update.outputs.branch }}` (`sponsors-maintainers-man-completions` or PR branch) will not be rebased onto `origin/master`.
=> workflows/sponsors-maintainers-man-completions: fix git-try-push failure

.github/workflows/tests.yml, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/dev-cmd/style.rb, Library/Homebrew/style.rb
-----
- I remember making these changes as part of the RuboCop bump Dependabot PR (#15136), but I must have not actually pushed them. Odd.
=> dev-cmd/style: Properly clean up the `--display-cop-names` option

.github/workflows/tests.yml, Library/Homebrew/Gemfile, Library/Homebrew/dev-cmd/install-bundler-gems.rb, Library/Homebrew/dev-cmd/prof.rb, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/dev-cmd/typecheck.rb, Library/Homebrew/dev-cmd/vendor-gems.rb, Library/Homebrew/utils/gems.rb
Reland this so we can release a new portable Ruby, this time fixing `brew typecheck --update` to install all gems.
Obsoletes the fix in #15134 so we shouldn't need to reland that.
=> Revert "Revert "Split prof gems into their own group"" 

Library/Homebrew/os/mac/xcode.rb
-----
The one shown on the Wikipedia [^1] seems to be wrong. I can confirm the actual version locally.
[^1]: https://en.wikipedia.org/wiki/Xcode#Xcode_11.0_-_14.x_(since_SwiftUI_framework)_2
=> os/mac/xcode: fix Clang version for Xcode 14.3

Library/Homebrew/github_runner_matrix.rb
=> github_runner_matrix: fix dependent runner assignment

Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/extend/os/dev-cmd/bottle.rb, Library/Homebrew/extend/os/linux/dev-cmd/bottle.rb, Library/Homebrew/extend/os/mac/dev-cmd/bottle.rb
This commit includes `--no-mac-metadata` `--no-acls` and `--no-xattrs` in `default_tar_args` for `brew bottle` command.
Although `default_tar_args` is only active when `--only-json-tab` is not passed, in which case we don't require reproducible bottles, it is nonetheless beneficial to "regularize" tarball creation. In particular, this resolves a sporadic `brew tests
--only=dev-cmd/bottle:20` failure (see
https://github.com/orgs/Homebrew/discussions/4376 and https://github.com/Homebrew/brew/pull/14997).
Furthermore, with `gnu tar`, `--no-acls` and `--no-xattrs` are default flags. As for "mac metadata", although I couldn't find official documentation, this post (https://superuser.com/a/61188) shares some info:
- Resource forks (resource forks have been extended attributes since 10.4)
- …
=> Don't save mac metadata/extended attributes for `brew bottle`

Library/Homebrew/completions/fish.erb, completions/fish/brew.fish
-----
Updating fish completions to remove expensive `brew list` calls
=> Update fish completions

.github/actionlint-matcher.json, .github/actionlint.yaml, .github/workflows/actionlint.yml
-----
This will help us avoid future actionlint errors in our workflows.
- workflows: add actionlint workflow
- Add actionlint error for testing WIP
=> workflows: add actionlint workflow

Library/Homebrew/locale.rb, Library/Homebrew/test/cask/dsl_spec.rb, Library/Homebrew/test/locale_spec.rb
-----
As I mentioned in #15146, two `Cask::DSL` tests failed on my local machine, even on `master`. `git bisect` suggested that it was #14998 that introduced those failures. It turned out that the tests here could fail under certain locale settings, like this one below:
```console
$ defaults read -g AppleLanguages
(
"en-GB",
"zh-Hans-SG"
)
```
This is not actually a regression. With the aforementioned locale settings, an explicit `let(:languages) { ["en"] }` setting would result in locales being considered in the following order: `en`, `en-GB`, `zh-Hans-SG`. For each of them, the `detect` method from `Locale` is called, with `locale_groups` as `[["zh"], ["en-US"]]`, the list of locales defined in the test cask.
https://github.com/Homebrew/brew/blob/5c56cb73c6e278d180fd1daeaec2d4d9f7fc734e/ …
=> test/cask/dsl_spec: fix test for certain locale settings

Library/Homebrew/rubocops/cask/ast/cask_block.rb, Library/Homebrew/rubocops/cask/ast/stanza.rb, Library/Homebrew/rubocops/cask/stanza_grouping.rb, Library/Homebrew/test/rubocops/cask/stanza_grouping_spec.rb
-----
- A variant of this was an ancient TODO from 2018 (with `if/else` conditionals).
- Now in 2023 we have `on_*` blocks within Casks that are very common.
- The most common stanzas present inside `on_*` blocks are `version`, `sha256` and `url`. So I feel like it's worth keeping a consistent style for these inside and outside `on_*` blocks?
- Companion PRs to auto-fix the Cask taps offenses are linked below.
=> rubocop/cask: Check for correct stanza grouping within `on_*` blocks

.github/workflows/sponsors-maintainers-man-completions.yml
-----
This prevents running the jobs on tags. It can be dangerous to force-push a tag, even though previous workflow runs actually failed.
Example of previous failure: https://github.com/Homebrew/brew/actions/runs/4657211778/jobs/8241583576
=> workflows/sponsors-maintainers-man-completions: only run on branches

Library/Homebrew/test/rubocops/cask/stanza_grouping_spec.rb
-----
- This test tests nothing. And the TODO comment is wrong (https://github.com/Homebrew/brew/pull/15211/files#r1164491120).
- We _could_ fix it, but it's a very edgy edge case which pertains to `livecheck` blocks which currently don't have stanza grouping or ordering cop support. If we decide in the future to add these, we can add this back too (provided I remember).
- Also I think I may have got confused with the stanza grouping vs. stanza ordering cops when writing this, rendering this test more useless.
=> Delete a Cask RuboCop test for an edge case that is not fixed

docs/Cask-Cookbook.md
-----
Continues #15085 by replacing mention of `appcast` in the Homebrew Cask docs with an explanation of the `:sparkle` strategy for `livecheck`. Also throws in a brief description of `:extract_plist` for good measure.
=> docs: deprecate `appcast`

Library/Homebrew/cask/cask.rb, Library/Homebrew/test/support/fixtures/cask/caffeine.json, Library/Homebrew/test/support/fixtures/cask/everything.json
-----
Fixes #15227.
This was originally used by the API but was replaced months ago by `SimulateSystem`. Essentially, it's only current use was in the `Cask::Cask#to_h` method but is not used internally at all when creating cask instances from the API JSON.
It was added to brew in https://github.com/Homebrew/brew/pull/11915 and added to the `formulae.brew.sh` website in https://github.com/Homebrew/formulae.brew.sh/pull/539. The use in the `formulae.brew.sh` website was later removed in https://github.com/Homebrew/formulae.brew.sh/commit/b5704d4e26835d07c8aa5bbcb7ed25ac2a08a405 so the only remaining references are in the main brew repo.
The `Cask::Cask#os_versions` method was only called in `Cask::Cask#to_h` to create the `versions` field in the JSON representation. It is not referenced at …
=> cask: remove os_versions

Library/Homebrew/github_packages.rb
This will reduce the number of requests necessary to ascertain the size of formulas' bottle archives for analysis purposes.
Currently, getting the size of each bottle requires 1 request for the formula.json and followed by N requests per formula-version, which for most formulae is 7— more than 47k requests!
After this change, size retrieval can ascertain all bottle sizes for a formula-version in a single request, at the cost of one additional request per formula-version if that formula-version has not been rebuilt since this change was introduced.
To start, size retrieval will incur an additional request per package. Over the next few weeks and months, the retrieval will go a lot faster as all new and updated packages will require only one request.
-----
=> Add bottle file size to GHP manifest annotations

Library/Homebrew/dev-cmd/bump-formula-pr.rb, Library/Homebrew/utils/github.rb
Introduced in #15032. create_bump_pr fails as `git_origin` was renamed to `origin_url`
```
/opt/homebrew/Library/Homebrew/utils/github.rb:579:in `create_bump_pr'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:215:in `bump_cask_pr'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
-----
Fixes #15245.
=> fix: fix undefined 'git_origin_branch' methods

Library/Homebrew/github_packages.rb
-----
According to [^1] [^2], image manifest annotations need to be a string-string map.
This should fix the errors seen in Homebrew/homebrew-core#128517, Homebrew/homebrew-core#128558, et al.
[^1]: https://github.com/opencontainers/image-spec/blob/2879913ce4bc229704bf0d67b280929007b06b94/schema/image-manifest-schema.json#L35
[^2]: https://github.com/opencontainers/image-spec/blob/2879913ce4bc229704bf0d67b280929007b06b94/schema/defs-descriptor.json#L22
=> github_packages: fix bottle manifest schema violation

Library/Homebrew/system_command.rb
-----
Closes https://github.com/Homebrew/brew/issues/15179.
=> Pass TTY width to `Open3`.

Library/Homebrew/cask/utils.rb
-----
I noticed in profiling `brew prof --stackprof -- help` that a significant amount (> 8%) of the time was spent in `require "yaml"`:
I removed the require statement, though the realized gain was closer to 5.5%. Before:
```
$ hyperfine "brew help"
Benchmark 1: brew help
Time (mean ± σ):      1.057 s ±  0.090 s    [User: 0.216 s, System: 0.145 s]
Range (min … max):    1.003 s …  1.306 s    10 runs
```
After:
```
$ hyperfine "brew help"
Benchmark 1: brew help
Time (mean ± σ):     998.5 ms ±  25.1 ms    [User: 202.6 ms, System: 132.8 ms]
Range (min … max):   967.1 ms … 1043.2 ms    10 runs
```
Note that I can't test for the absence of `YAML` in global_spec (like we do for `I18n` and `ActiveSupport::Inflector`) bc the test infra itself includes `YAML`.
Also, I couldn't actually find …
=> Remove yaml require for 5% init speedup

Library/Homebrew/download_strategy.rb
Fixes the core issue causing #15235.
* Don't erroneously run `URI.decode_www_form_component` over the whole URL - only run that on query string parts and run other URI unescape methods on the path part
* Don't rely on error-prone regexes or Pathname ascending when we can split it properly into an array from the URI parser
=> download_strategy: fix bad unescaping in basename parsing

.github/workflows/autogenerated-files.yml, .github/workflows/sponsors-maintainers-man-completions.yml, .github/workflows/tests.yml
GitHub's [cache action](https://github.com/actions/cache) is now at version 3, and version 1 is very deprecated.
=> actions/cache@v3 for GitHub Actions

Library/Homebrew/dev-cmd/bump-cask-pr.rb
-----
Currently, if a cask has `sha256` set to `:no_check` attempting to run `brew bump-cask-pr --sha256 [new_sha]` will be unsuccessful as `bump-cask-pr` will try to replace `no_check` rather than `:no_check`. 
This PR adds an additional case to `bump_cask_pr` that handles the situation where `sha256 :no_check` is replaced by an actual checksum. Fixes https://github.com/Homebrew/homebrew-cask/issues/145362.
=> Fix bump-cask-pr handling of sha256 :no_check

Library/Homebrew/dev-cmd/audit.rb
These are now all errors so the code can be simplified.
=> dev-cmd/audit: remove unused warnings key.

Library/.rubocop.yml
-----
As the remaining un-typed files were removed in https://github.com/Homebrew/brew/pull/15201 and https://github.com/Homebrew/brew/pull/15273, this PR enables a cop that requires files to be typed. The configuration is taken from `Sorbet/FalseSigil` above it, with the exception of excluding all `Homebrew/test` files.
=> Enable Sorbet/TrueSigil cop

Library/Homebrew/cask/audit.rb, Library/Homebrew/test/cask/audit_spec.rb
-----
Followup to https://github.com/Homebrew/brew/pull/15219. Expanding the signing and notarisation requirement to binaries seems like a natural progression. I haven’t checked how many casks this affects, but casks with raw binaries are a minority compared to ones with apps.
=> Cask audit: check binary signature and notarisation

Library/Homebrew/dev-cmd/pr-automerge.rb
-----
PRs with the `pre-release` label are always not ready for merge, so let's skip them by default.
See also: Homebrew/homebrew-core#128906.
=> dev-cmd/pr-automerge: skip PRs with `pre-release` label

Dockerfile
-----
apt installs an ancient `gh` that is missing some important flags. In
particular, we probably do want the `--match-head-commit` flag for the
extra security it gives us.
See Homebrew/homebrew-core#128951 and Homebrew/homebrew-core#128959.
If we don't want Homebrew `gh` installed all the time in our image, then
we could maybe do `brew install gh` at the start of every publish job.
=> Dockerfile: install newer gh

Library/Homebrew/formula.rb
-----
`to_hash` currently assumes that a keg's formula came from a tap. However, if any keg came from an arbitrary formula file (e.g. `~/Desktop/unrar.rb`), it won't have an associated tap and a command like `brew info --installed --json=v2` will return "undefined method 'path' for nil:NilClass". This change causes the above command to generate a value for `ruby_source_path` only if a tap is associated, e.g.:
```
"ruby_source_checksum": {
"sha256": "3ea62d262bd704dc416e8df336f1e399e3c7012a5f8b7d55b39ec290f5cd95b4"
},
"ruby_source_path": null
```
=> formula: consider arbitrary formula source paths

Library/Homebrew/download_strategy.rb
-----
Enabling the fsmonitor isn't useful for these repositories. Moreover,
disabling them will get rid of the warning shown from trying to copy
sockets from a repo watched by the fsmonitor.
=> download_strategy: disable Git fsmonitor

Library/Homebrew/formulary.rb, Library/Homebrew/test/formulary_spec.rb
-----
We set a placeholder for the home directory when generating API JSON so we should substitute the actual home directory back in when printing caveats locally. This allows people to use `Dir.home` in caveats and have it display correctly no matter the platform or operating system.
```sh
/u/l/H/L/T/h/homebrew-core (master|✔) $ awk '
is_caveats(), is_end()
function is_caveats() {
if ($1 == "def" && $2 == "caveats") {
END_INDENT = get_indent()
return 1
} else {
return 0
}
}
function is_end() {
return NF == 1 && $1 == "end" && get_indent() == END_INDENT
}
function get_indent() {
match($0, /^ */)
return RLENGTH
}' (find . -name '*.rb') |
grep 'Dir.home'
return unless File.exist?("#{Dir.home}/.emscripten")
#{Dir.home}/.config/redshift/redshift.conf
```
`Dir.home` is used in two caveats …
=> formulary: sub home placeholder in caveats

Library/Homebrew/dev-cmd/pr-pull.rb, Library/Homebrew/git_repository.rb
-----
Fixes:
Error: no implicit conversion of GitRepository into String
when doing `brew pr-pull --autosquash`. See [1].
I contemplated implementing only `#to_s`, but we've historically used
these as `Pathname`s, and `Pathname` defines `#to_str`.
[1] https://github.com/Homebrew/homebrew-core/actions/runs/4784638305/jobs/8506369135#step:10:54
=> git_repository: implement `#to_s`

Library/Homebrew/completions/fish.erb, completions/fish/brew.fish
-----
Regression introduced (partly) in https://github.com/Homebrew/brew/pull/15174.
Before:
```
Wed 19 Apr 11:37:15 ➜  .linuxbrew/Homebrew master ✓  brew rm ls: cannot access '/home/linuxbrew/.linuxbrew/Caskroom': No such file or directory
ansible          freetype                   kompose       libuv               mpdecimal        shared-mime-info 
ansible-lint     fribidi                    krb5          libva               msgpack          shellcheck       
```
After:
```
Wed 19 Apr 11:37:56 ➜  .linuxbrew/Homebrew fish-linux-cask ✓  brew rm spice-protocol
ansible          freetype                   kompose       libuv               mpdecimal        shared-mime-info 
```
Plus:
```
Wed 19 Apr 11:37:56 ➜  .linuxbrew/Homebrew fish-linux-cask ✓  brew outdated --cask --verbose 
Error: …
```
=> completions/fish: fix cask references for Linux

Library/Homebrew/utils/gems.rb
This should fix cases where we remove vendored gems.
=> utils/gems: run `bundle clean` when install not required

Library/Homebrew/utils/pypi.rb
-----
This is both a performance and correctness improvement: it replaces our use of `pipgrip` for Python dependency collection with `pip`'s (new) built-in `--report` and `--dry-run` functionality, which produces a conceptually similar dependency report in JSON.
Performance wise, this results in about a 20% improvement in local testing over the `pipgrip` based implementation. This is probably mostly tied to not using the Poetry resolver (which is what `pipgrip` uses).
Correctness wise, this uses the same resolution logic and library (`resolvelib`) that `pip` uses, meaning that it exactly matches what users will actually see when they `pip install` a package. Poetry (and therefore `pipgrip`) use their own resolution algorithm, which can sometimes produce discrepancies versus the …
=> utils/pypi: replace `pipgrip` with `pip`'s built in dependency resolution

.github/actionlint.yaml, .github/workflows/build-pkg.yml, .github/workflows/sorbet.yml, .github/workflows/tests.yml, .github/workflows/vendor-gems.yml, Library/Homebrew/dev-cmd/tap-new.rb
-----
Now that the `macos-13` runner image is available, let's switch to it so that we have the tests run on the latest macOS.
Alternatively, for some of the `tests` workflows, we may consider adding an additional `macos-13` matrix job instead of switching from `macos-12` to it.
=> workflows: run on `macos-13`

Library/Homebrew/download_strategy.rb
Fixes #15302
Prior to #15117, if `curl --head` failed for any reason, `brew install` would've installed previously-downloaded bottles.
If that was an unintended side-effect of #15117, then this PR restores the previous behavior.
If it was intended, is there a way to `brew install` a bottle from the filesystem — i.e. a no-network install provided that the given bottle matches the formula's expectations?
------
=> Install cached bottles if `curl --head` fails

Library/Homebrew/dev-cmd/bump-cask-pr.rb
-----
Convert the URL parameter back to a string after checking it for validity. Otherwise, attempting to update the URL errors out with "no implicit conversion of URI::HTTPS into String". (introduced in #15088)
=> bump-cask-pr: convert URL back to string

Library/Homebrew/github_runner_matrix.rb, Library/Homebrew/test/github_runner_matrix_spec.rb
-----
This makes our dependent tests run on a GitHub macOS runner if
compatible with the requested timeout.
This will also allow builds on a GitHub runner on macOS if requested
with the environment variable `HOMEBREW_MACOS_BUILD_ON_GITHUB_RUNNER`.
This environment variable will need to be set in the workflow as
appropriate (e.g. when requested by a label).
=> github_runner_matrix: test dependents on GitHub runners

Library/Homebrew/github_runner_matrix.rb
-----
These come with some pre-installed software that we probably want to
clean up first.
=> github_runner_matrix: cleanup GitHub macOS runner

Library/.rubocop.yml
-----
- Part of #15297. Specifically, [bullet point three of Mike's suggestion](https://github.com/Homebrew/brew/issues/15297#issuecomment-1519579881). After this, I'll start chipping away at switching cops on.
- `EnabledByDefault` is a feature of RuboCop that enables all cops even those marked `Enabled: false` in core RuboCop.
- I went through and disabled all the cops with offenses from this config change. This way we can do a piecemeal approach to enabling cops with offenses, while getting the benefits of the new cops with no offenses.
- It is intentional that `brew style` comes back green here and there are no code style fixes.
-----
- I was going to put these in alphabetical order, but it's probably not worth it. Once we've moved sufficiently many of these to `Enabled: true`, if …
=> rubocop: Set `EnabledByDefault: true`, disabling cops with offenses

Library/Homebrew/dev-cmd/bump.rb
-----
If a cask has `version :latest` is not livecheckable and repology returns a version, `brew bump` will replace `version :latest` with the repology version. This is not desired as it will reversion casks that were unversioned on purpose. 
e.g. 
```
==> autodesk-fusion360
Current cask version   :  latest
Latest livecheck version: latest
Latest Repology version:  2.0.15509
Open pull requests:       none
Closed pull requests:     none
```
=> `brew bump`: modify versioning logic

Library/Homebrew/api/formula.rb, Library/Homebrew/cmd/migrate.rb, Library/Homebrew/cmd/update-report.rb, Library/Homebrew/formula.rb, Library/Homebrew/formulary.rb, Library/Homebrew/install.rb, Library/Homebrew/keg.rb, Library/Homebrew/migrator.rb, Library/Homebrew/tap.rb, Library/Homebrew/test/formula_spec.rb, Library/Homebrew/test/keg_spec.rb, Library/Homebrew/test/migrator_spec.rb
Supporting formula renames in the API is fairly trivial. We have `oldname` data already  so we can create a `formula_renames` structure from that information.
There was one catch however: the API only supports one oldname. But in homebrew/core we have formulae which have multiple renames, typically from merging multiple formulae into one. Since the API only supported a single oldname, we  would only have a partial set of data and thus not fully fix the issue.
So I tried to add support for multiple oldnames properly here too. It's not a huge redo - mostly just making things use arrays instead. I've also adjusted the migrator to handle it better - it now actually merges rather than just pick a random one, but otherwise functions the same way.
=> Support multiple oldnames for formulae & support formula renames in API

Library/Homebrew/github_runner_matrix.rb, Library/Homebrew/test/dev-cmd/determine-test-runners_spec.rb, Library/Homebrew/test/github_runner_matrix_spec.rb
-----
This will allow us to remove handling of this in our workflow files in
Homebrew/core.
=> github_runner_matrix: remove `HOMEBREW_LINUX_CLEANUP`

Library/Homebrew/utils/pypi.rb
-----
This is just another small QoL improvement to the PyPI helpers: we now normalize the package name that gets returned in `pypi_info`, which means that PyPI resource names are now consistent and a little easier to search for throughout formulae that are updated with `update-python-resources`.
=> pypi: normalize name in `pypi_info`

Library/Homebrew/dev-cmd/determine-test-runners.rb, Library/Homebrew/test/dev-cmd/determine-test-runners_spec.rb
-----
The extra timeout on Intel Big Sur doesn't seem to be set, so I'm adding
this so I can have a closer look.
=> determine-test-runners: add debug output

Library/Homebrew/cask/artifact/abstract_uninstall.rb, Library/Homebrew/cask/artifact/keyboard_layout.rb, Library/Homebrew/cask/artifact/pkg.rb, Library/Homebrew/cask/pkg.rb, Library/Homebrew/sorbet/rbi/parlour.rbi, Library/Homebrew/system_command.rb, Library/Homebrew/test/cask/artifact/pkg_spec.rb, Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb, Library/Homebrew/test/cask/dsl/shared_examples/staged.rb, Library/Homebrew/test/cask/pkg_spec.rb, Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-script-app.rb, Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-script-user-relative.rb, Library/Homebrew/test/support/helper/cask/never_sudo_system_command.rb, Library/Homebrew/test/system_command_spec.rb
With sudoers one may override default sudo user. This mostly works provided the admin configured the replacement appropriately. However there are exceptions that absolutely must be run by root such as /usr/sbin/installer and, under certain circumstances, /bin/launchctl.
-----
=> sudo: explicitly specify the root user where necessary

Library/Homebrew/livecheck/livecheck.rb, Library/Homebrew/livecheck/strategy/launchpad.rb, Library/Homebrew/livecheck/strategy/sparkle.rb, Library/Homebrew/livecheck/strategy/xml.rb
-----
#15326 will set `HOMEBREW_SORBET_RUNTIME` by default for dev commands or when `HOMEBREW_DEVELOPER` is set. This PR addresses issues that I encountered while running `brew livecheck` across all of our first-party formulae/casks with the Sorbet runtime enabled. There may be other issues that haven't been surfaced yet but this covers the existing ones, at least.
The existing way of passing values to `#find_versions` methods in strategies leads to type issues when the Sorbet runtime is enabled. We've also recently talked about moving away from nilable args when we can specify a default value but this doesn't work if we pass in a `nil` value (like we're currently doing).
These changes aim to address both of those areas by better controlling which arguments we're passing to …
=> Livecheck: Fixes for Sorbet runtime

Library/Homebrew/rubocops/service.rb, Library/Homebrew/test/rubocops/service_spec.rb
-----
This is a follow-up to #15154. In addition to `bin`, the `service` block can also reference other cellar paths like `libexec`. They don't work with the API either, as reported in https://github.com/orgs/Homebrew/discussions/4459.
Violations are already corrected in Homebrew/homebrew-core#129736 and Homebrew/homebrew-core#129737.
=> rubocops/service: check for more cellar paths

Library/Homebrew/diagnostic.rb, Library/Homebrew/test/diagnostic_checks_spec.rb
-----
- Part of https://github.com/Homebrew/brew/issues/15339.
- If the user doesn't have `HOMEBREW_DEVELOPER` or `HOMEBREW_NO_INSTALL_FROM_API` set but does have `homebrew/core` or `homebrew/cask` taps installed this can cause problems with installing outdated software.
- Hence, warn them in `brew doctor` if they have one or both of these taps installed, with an instruction for how to remove them.
This looks like:
```
Warning: You have an unnecessary local Cask tap.
This can cause problems installing up-to-date casks.
Please remove it by running:
brew untap homebrew/cask
Warning: You have an unnecessary local Core tap!
This can cause problems installing up-to-date formulae.
Please remove it by running:
brew untap homebrew/core
```
=> diagnostic: Check for unnecessary Core and Cask taps

Library/Homebrew/download_strategy.rb
-----
livecheck's `Git` strategy uses `DownloadStrategyDetector#detect` in its `#match?` method to check if a URL is a Git repository. This has historically worked fine but I've recently seen a `can't modify frozen String` error for a few formulae (percona-toolkit, schroedinger, squid) in relation to the in-place `sub` call in `BazaarDownloadStrategy`'s initializer.
Other download strategies use a `@url = @url.sub(...)` pattern to avoid this issue, so this PR resolves the issue by using the same approach in `BazaarDownloadStrategy`.
=> BazaarDownloadStrategy: Replace in-place sub

Library/Homebrew/cmd/update-report.rb
-----
This fixes the following error:
```console
$ brew update
Warning: No remote 'origin' in /usr/local/Homebrew/Library/Taps/foo/homebrew-bar, skipping update!
Error: HOMEBREW_UPDATE_BEFORE_FOO_HOMEBREW_BAR is unset!
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:361:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:187:in `new'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:187:in `block in output_update_report'
/usr/local/Homebrew/Library/Homebrew/tap.rb:748:in `block (2 levels) in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:747:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:747:in `block in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:746:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:746:in `each' …
```
=> cmd/update-report: do not fail when tap has no origin

Library/Homebrew/github_packages.rb
-----
Erroring out in the middle of uploading multiple bottles results in a
state that is tedious to recover from.
Let's try to avoid these situations by performing checks for all the
bottles first before trying to upload any.
Also, the retry behaviour in [`publish_commit_bottles.yml`](https://github.com/Homebrew/homebrew-core/blob/3241035b2a61866995bbad3264d354d5c30644dc/.github/workflows/publish-commit-bottles.yml#L431-L443) is often
successful after the second try, so it's likely we're not waiting long
enough in between retries here. Let's fix that by retrying with
exponential backoff instead of adding a fixed interval after each
failure.
=> github_packages: improve upload error handling

Library/Homebrew/extend/os/mac/dev-cmd/bottle.rb
```
Inspecting 1173 files
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................... …
```
=> bottle: some tar flags are not supported on Mojave

Library/Homebrew/brew.sh, Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
I've been doing this personally for a few months and not hit any bugs. We already do this for `brew tests`.
It will allow us to:
- remove manual type checks from all developer commands (Sorbet does a better job with these)
- better surface bugs
- better surface type signatures
- get closer to being able to enable this by default for everyone
=> Enable Sorbet by default for Homebrew developers and developer commands.

Library/Homebrew/brew.sh, Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
Reverts Homebrew/brew#15326
This is causing some breakage in homebrew-core:
https://github.com/Homebrew/homebrew-core/actions/runs/4892972572/jobs/8735383323?pr=130235
https://github.com/Homebrew/homebrew-core/actions/runs/4892972572/jobs/8735365498?pr=130235
Plus: https://github.com/Homebrew/brew/issues/15366
=> Revert "Enable Sorbet by default for Homebrew developers and developer commands."

Library/Homebrew/brew.sh, Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
Along with some fixes for failures in Homebrew/core. See discussion at #15368.
This reverts commit e49cd331dba71b1ced341f1838c7651ecff46a38.
=> Revert "Revert "Enable Sorbet by default for Homebrew developers and developer commands.""

Library/Homebrew/brew.sh, Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
This reverts commit 8c059bba279f4b72b783fca91746d14b6286e6fc, reversing changes made to f71b3d37abcc9cd12b0c8a621bc3712c00db8ec1.
Fixes breakage starting dependent testing:
```
Run brew determine-test-runners --dependents --eval-all "$TESTING_FORMULAE"
Error: Return value: Expected type String, got type NilClass
Caller: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:627
Definition: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:655
```
=> Revert "Merge pull request #15369 from carlocab/sorbet-runtime"

Library/Homebrew/cask/dsl.rb, Library/Homebrew/livecheck.rb, Library/Homebrew/test/livecheck_spec.rb
=> Type `livecheck.rb`.

Library/Homebrew/github_runner_matrix.rb
-----
This prevents situations where the Intel runners have a 360 minute
timeout but the ARM runners only have 45 minutes.
See Homebrew/homebrew-core#130284.
=> github_runner_matrix: align Intel and ARM timeouts

Library/Homebrew/rubocops/cask/ast/cask_block.rb, Library/Homebrew/rubocops/cask/ast/stanza.rb, Library/Homebrew/rubocops/cask/extend/node.rb, Library/Homebrew/rubocops/cask/mixin/cask_help.rb, Library/Homebrew/rubocops/cask/no_overrides.rb, Library/Homebrew/rubocops/cask/stanza_grouping.rb, Library/Homebrew/rubocops/cask/stanza_order.rb, Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi, Library/Homebrew/test/rubocops/cask/shared_examples/cask_cop.rb, Library/Homebrew/test/rubocops/cask/stanza_order_spec.rb
-----
- Follow-up to #15211 to fix more TODOs but in a different cop.
-----
- Now that we detect correct stanza _grouping_ within `on_*` blocks in Casks, correct stanza _ordering_ in `on_*` blocks was the next logical step. For example, `url` has to come after `version` and `sha256` in an `on_macos` or `on_intel` block for consistency with the top-level stanza order we enforce elsewhere.
- Still not doing the nested `on_os` inside `on_arch`, that felt excessive for an edge case that isn't present in more than a few real Casks we have. I removed the test with that specific TODO. If anyone feels strongly I can look at it again, though.
=> rubocops/cask: Check for correct stanza order within `on_*` blocks

Library/Homebrew/brew.sh, Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
-----
We need to exclude any command that might read `lsyncd` on Linux while
simulating macOS. This seems like all of them.
This reverts commit bcf94f6e27d26a6844ee1fa7af73333321015987.
=> Revert "Revert "Merge pull request #15369 from carlocab/sorbet-runtime""

Library/Homebrew/cask/artifact/installer.rb, Library/Homebrew/test/cask/artifact/installer_spec.rb, Library/Homebrew/test/cask/installer_spec.rb
-----
Allow easy copy-pasting to open the installer.
=> Make manual installers easier to open.

Library/Homebrew/bundle_version.rb
-----
Makes `item.short_version` in `livecheck`s behave more similar to what it would look like in the default case.
=> Always remove build from `short_version`.

Library/Homebrew/extend/os/mac/utils/bottles.rb, Library/Homebrew/utils/bottles.rb
https://github.com/Homebrew/homebrew-core/actions/runs/4915420737/jobs/8777887066?pr=130438#step:5:27
=> utils/bottles: fix typechecking error

Library/Homebrew/brew.sh, Library/Homebrew/cmd/shellenv.sh
These were introduced by typos and an incorrect assumption on the last update of #15358. The last commit had been tested with a parameter, but had not been re-tested *without* parameter.
A stray `}` had crept into the parameterless version of `HOMEBREW_SHELL_NAME` and because we had not `shift`ed the arguments, `$1` was `shellenv`, resulting in always outputting the POSIX-style configuration.
Apologies for the error.
=> Fix small errors in `brew shellenv`

Library/Homebrew/livecheck/strategy/github_latest.rb, Library/Homebrew/test/livecheck/strategy/github_latest_spec.rb
-----
Part of https://github.com/Homebrew/brew/pull/15260
This is just the API switch to make sure we don't have to scrape HTML anymore.
=> feat: use API for GitHub latest release strategy

Library/Homebrew/brew.sh, Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
This reverts commit cca98d5637d847548791b5afb16a5c609de2cb58, reversing changes made to c0f8068573bbf886fdc78d3f9daca54d53e7e49e.
Scheduled regeneration has been broken, along with some formula issues
https://github.com/Homebrew/formulae.brew.sh/actions/runs/4918509948/jobs/8784938224
https://github.com/Homebrew/homebrew-core/actions/runs/4917875779/jobs/8784981260?pr=130477#step:4:516
=> Revert "Merge pull request #15377 from carlocab/sorbet-runtime-take2"

Library/Homebrew/download_strategy.rb, Library/Homebrew/livecheck/strategy.rb, Library/Homebrew/test/download_strategies/curl_spec.rb, Library/Homebrew/utils/curl.rb
-----
https://github.com/Homebrew/brew/pull/15099 seems to be stalled, so I'm adding the `curl_head` usage here. Also switch to `curl_output` instead of directly calling `curl_with_workarounds`.
=> Use `curl_headers` and `curl_output` for `Livecheck` strategies.

Library/Homebrew/livecheck/strategy.rb, Library/Homebrew/utils/curl.rb
-----
`Strategy#page_headers` was modified to call `#curl_headers` but wasn't updated to work with the new return value, so all `HeaderMatch` checks currently fail with an ```undefined method `success?' for nil:NilClass``` error. This would have been caught if it was tested on any existing `HeaderMatch` check.
I was wrapping up my review of #15351 after testing the changes, identifying issues, and working on potential fixes but it was merged before I was able to submit it. This PR aims to explain the issues and provide fixes.
-----
This updates `Strategy#page_headers` to work with the new return value, which will be a hash from `#parse_curl_output` when the request succeeds.
I've removed the `result.assert_success!` call in `#curl_headers` and added a default `nil` return because the …
=> Strategy#page_headers: Update for #curl_headers

Library/Homebrew/cmd/update-report.rb
=> cmd/update-report: don't invoke external diff tools

.github/workflows/build-pkg.yml
-----
This prevents the workflow from being run in a fork.
=> workflows/build-pkg: only run on Homebrew-owned repos

docs/New-Maintainer-Checklist.md
and makes some minor adjustments to wordings to clarify actions to be taken when.
---
-----
=> Adds a TOC to the maintainer checklist

Library/Homebrew/formula_installer.rb, Library/Homebrew/tab.rb
This is a nearly 5 year old bug that only revealed itself now that we've tightened up typing and validation in `version.rb` (for the better IMO - empty string versions do not make sense, can hide genuine bugs, have indeterminate behaviour in terms of comparisons, and fails to satisfy any `Version#null?` check).
This did _not_ affect bottles installed from GitHub Packages, so most users were unaffected.
Fixes #15401.
=> tab: fix typing of versions

Library/Homebrew/cleanup.rb
This was technically caused in my case by local work, but `pr-pull` is a real world example of where this will genuinely happen (we perhaps should move that to a separate subdirectory in the cache at some point).
=> cleanup: fix version error for cache items without a version

Library/Homebrew/test/version_spec.rb, Library/Homebrew/version.rb
-----
Mentioned this here: https://github.com/Homebrew/brew/pull/15402#discussion_r1190824114
=> Improve `#to_str` and `#to_json` for `Version::NULL`.

Library/Homebrew/cask/installer.rb, Library/Homebrew/cask/quarantine.rb, Library/Homebrew/cask/upgrade.rb
-----
In #15138, `revert_upgrade()` was declared with a positional parameter for `predecessor`, but it's called with a named parameter. This fixes that inconsistency, and adds some explicit type declarations to all other function signatures I added or changed in #15138 to rule out similar errors.
Fixes the immediate errors in #15406 and https://github.com/orgs/Homebrew/discussions/4498. However, this code is only triggered when an upgrade is reverted, so the root cause of both is probably some other error.
=> Fix typing on revert_upgrade().

Library/Homebrew/simulate_system.rb
-----
Fixes
Error: Cannot simulate :ventura :intel while already simulating :macos.
See https://github.com/Homebrew/homebrew-core/actions/runs/4974116510/jobs/8900390980#step:4:24.
=> simulate_system: fix `tap_syntax` job errors

Library/Homebrew/formula.rb, Library/Homebrew/formula.rbi, Library/Homebrew/formula_installer.rb, Library/Homebrew/formulary.rb
Extracted from https://github.com/Homebrew/brew/pull/15225.
=> Add `Formula#loaded_from_api?`.

.github/workflows/tests.yml, Library/Homebrew/dev-cmd/generate-cask-api.rb, Library/Homebrew/dev-cmd/generate-formula-api.rb
-----
As discussed in https://github.com/Homebrew/brew/pull/15404#issuecomment-1545301705.
There are two reasons for this:
- Makes it easier to run this command as a sanity check without having to create a temporary directory
- Is somewhat faster since you don't have to write thousands of files
This is on my old iMac but I think it illustrates the point either way.
```
~/tmp-test $ hyperfine 'brew generate-cask-api' 'brew generate-cask-api -n'
Benchmark 1: brew generate-cask-api
Time (mean ± σ):     23.148 s ±  0.702 s    [User: 10.490 s, System: 8.594 s]
Range (min … max):   21.857 s … 23.968 s    10 runs
Benchmark 2: brew generate-cask-api -n
Time (mean ± σ):     11.704 s ±  0.233 s    [User: 9.186 s, System: 1.844 s]
Range (min … max):   11.299 s … 12.133 s    10 runs
Summary
'brew …
```
=> dev-cmd/generate-*-api: add dry run option

Library/Homebrew/caveats.rb, Library/Homebrew/formula.rb, Library/Homebrew/formula_cellar_checks.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/formulary.rb, Library/Homebrew/rubocops/service.rb, Library/Homebrew/service.rb, Library/Homebrew/test/caveats_spec.rb, Library/Homebrew/test/formula_installer_spec.rb, Library/Homebrew/test/formula_spec.rb, Library/Homebrew/test/formulary_spec.rb, Library/Homebrew/test/rubocops/service_spec.rb, Library/Homebrew/test/service_spec.rb, Library/Homebrew/utils/service.rb, Library/Homebrew/utils/service.rbi, docs/Formula-Cookbook.md
-----
Fixes #15175.
Basically, this adds the following DSL to the service block to support service files with custom names.
```rb
service do
plist_name "name"
service_name "name"
end
```
These two new methods can be used with or without the rest of the normal service block methods. It is also backwards compatible so the previous redefine-the-plist_name-method strategy will still work (but of course that doesn't work with the API which is the whole point here).
For more details allow me to plagiarize the first commit message.
```
The main thing is that this DSL allows us to provide an
interface that can be serialized to the JSON API.
Changes:
- Homebrew::Service
- Adds `#service_name` and `#plist_name` methods
- Each is now included in the `#serialize` method as well
- Eval block on …
```
=> Custom service name

Library/Homebrew/service.rb
While #15455 makes future versions of Homebrew ignore the error, the problem still exists that there was a breakage in our JSON API that the error was flagging - the contents of `service` was incorrectly producing different results on different OS versions. This fixes the core issue, without requiring a new release (which takes up to 24 hours to roll out by default).
Fixes Homebrew/homebrew-core#131295.
=> service: fix API compatibility break

Library/Homebrew/service.rb, Library/Homebrew/test/service_spec.rb
-----
Allows us to replace e.g. `working_dir Dir.home` with `working_dir "~"` so we eventually don't need to stub `ENV["HOME"]` when generating the API anymore.
=> Expand `service` paths.

Library/Homebrew/livecheck/strategy/bitbucket.rb, Library/Homebrew/test/livecheck/strategy/bitbucket_spec.rb
-----
In some cases, the `Bitbucket` strategy currently matches versions from tag tarball links on a project's `downloads/?tab=tags` page. It appears that Bitbucket now uses a hash as the filename on this page instead of the tag name, so the existing regex no longer matches.
This adds an alternative regex to match versions from the tag name element (e.g., `<td class="name">example-1.2.3</td>`), which will fix version matching in this scenario.
Affected formulae are `mvnvm`, `uru`, `when`, and `x265`. All but `uru` are currently falling back to checking the Git tags from their `head` URL. With this change, the `uru` check works again and the others return to using the `Bitbucket` strategy (since it returns a version).
For what it's worth, now that Bitbucket has dropped Mercurial support, …
=> Bitbucket: Fix tag match

bin/brew
-----
~~It seems https://github.com/Homebrew/brew/pull/15447 broke actually passing through those variables on `GITHUB_ACTIONS`, since `CI` is not set by default.~~
Nevermind, `CI` is actually set. Still, I think it makes more sense to guard the `GITHUB_*` variables by `GITHUB_ACTIONS` rather than `CI`.
=> Guard `GITHUB_*` variables by `GITHUB_ACTIONS`.

Library/Homebrew/extend/os/mac/keg_relocate.rb
-----
Stuff built by CMake evades this check because CMake normalises
`/private/tmp` (which is the default `HOMEBREW_TEMP`) to `/tmp`. See
https://gitlab.kitware.com/cmake/cmake/-/issues/23251.
Let's fix that my taking this into account when `HOMEBREW_TEMP` is
`/private/tmp`.
=> keg_relocate: fix check for paths rooted in build directory

Library/Homebrew/macos_version.rb
-----
The probably last usage of this is fixed by https://github.com/Homebrew/homebrew-core/pull/131773 anyways, but this is how it should be done so the constant works properly when used in `rescue` statements.
=> Fix `MacOSVersionError` deprecation.

.github/workflows/tests.yml, Library/Homebrew/cmd/readall.rb, Library/Homebrew/readall.rb
-----
Add `--os` and `--arch` flags to `readall`, so it is consistent with `fetch`, `--cache` and `audit`.
`--no-simulate` will be deprecated, as it will become the default again once we have changed CI to run with `--os=all --arch=all`.
=> Add `--os` and `--arch` flags to `readall`.

Library/Homebrew/cmd/casks.sh, Library/Homebrew/cmd/formulae.sh, Library/Homebrew/items.sh
I'm not sure if this is an elegant solution but it gives an identical output to when `HOMEBREW_NO_INSTALL_FROM_API` is set, regardless of whether `homebrew/core` or `homebrew/cask` are tapped. Feel free to make any improvements.
Closes #15229
-----
=> Fix `brew formulae` and `brew casks` when the API is used

Library/Homebrew/utils/github/api.rb
-----
Introduce the ability to discover tokens stored by the GitHub CLI. The changes to the `GitHub::API` are relatively straightforward; the current implementation will only discover the `gh` command from the `gh` formula.
=> Discover GitHub tokens stored by the GitHub CLI

.github/workflows/doctor.yml, Library/Homebrew/github_runner_matrix.rb, Library/Homebrew/test/dev-cmd/determine-test-runners_spec.rb, Library/Homebrew/test/github_runner_matrix_spec.rb
-----
This should no longer be needed after Homebrew/ci-orchestrator@845d26ccc03ffebb06c39d0b9ce81134e8a6688b.
=> github_runner_matrix: remove `GITHUB_RUN_ATTEMPT`

Library/Homebrew/unpack_strategy/zip.rb
-----
If we already have `unzip` in `PATH`, let's skip trying to load the
`unzip` formula.
=> unpack_strategy/zip: avoid loading formulae unnecessarily

Library/Homebrew/utils/github/api.rb
-----
This is causing errors in third-party taps after
Homebrew/homebrew-test-bot#934.
Fixes Homebrew/discussions#4546.
=> utils/github/api: avoid loading `gh`

Dockerfile
-----
This makes sure that the system `umask` is the same as the one on macOS.
Fixes Homebrew/homebrew-core@155e3ab5a88fb373342db5af0bc42499c5124402.
=> Dockerfile: set default `umask`

Library/Homebrew/utils/github.rb
-----
We currently use the search API to check for duplicate pull requests,
but this is not very reliable. Our `autobump.yml` workflow routinely
opens [duplicate pull requests](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+author%3ABrewTestBot+is%3Aunmerged+in%3Acomments+Duplicate) because the search API often returns
incorrect results.
We can make this more reliable by using the Pulls API instead.
Unfortunately, querying the Pulls API is very slow (~10s vs less than a
second for the search API), so let's limit its usage to calls made
inside CI, which should help @BrewTestBot avoid opening duplicate PRs.
(Most recent dupes were authored by @BrewTestBot.)
=> utils/github: use Pulls API to check open pull requests on CI

.github/actionlint.yaml, .github/workflows/actionlint.yml
-----
This is no longer needed after Homebrew/homebrew-core#132722.
This reverts commit f729127fae6a12e173f55a59ef90a72c7cf18141.
=> actionlint.yaml: remove workaround for `macos-13`

Dockerfile
=> Dockerfile: set umask in `common-session-noninteractive` too

Library/.rubocop.yml
-----
- This proved sufficiently controversial in the comments of https://github.com/Homebrew/brew/issues/15297.
- Closes #15297.
- There are too many cops in this list that _don't_ make sense for us.
- For the few that do (with many thanks to Bo for going in depth to figure them out!), we can selectively enable them without using `EnabledByDefault` and a whole load of `Enabled: false` (I might do this in the future).
=> rubocop: Revert PR 15312, unset `EnabledByDefault`

Library/Homebrew/test/utils/pypi_spec.rb, Library/Homebrew/utils/pypi.rb
-----
This is another quality of life improvement to our handling of Python packages, unlocked by the switch to `pip install --report --dry-run` from a few weeks ago: `pip install` can accept arbitrary distribution URLs, meaning that we no longer require the top-level to be a `pythonhosted` URL in order to auto-bump its dependencies using `update-python-resources`.
This should result in automation for a handful of formulae that previously required manual resource updating. More indirectly, it improves `brew-pip-audit`'s ability to bulk audit Python packages present in Homebrew formulae, resulting in more automated vulnerability fix PRs as well.
=> PyPI: Handle non-`pythonhosted` formula URLs

Library/Homebrew/cask/quarantine.rb
The problem is that the branch attempts a write which throws but also returns right after, which causes the calling code to miss executing the branch to acquire permissions [1]. This change makes it so that the write is attempted, and if it fails, `app_management_permissions_granted` will return false to the caller, which will end up executing `Utils.gain_permissions_remove(target, command: command)`.
This fixes the issue of cask upgrades/reinstalls to failing due to permissions [2]. It's worth noting though, the prompt for allowing App Management permissions does not seem to occur, so that's something else to be investigated.
1. https://github.com/Homebrew/brew/blob/f7d86ff9bc166cf59a4cdec3520d45eec9a49e75/Library/Homebrew/cask/artifact/moved.rb#L170-L172
2. …
=> cask/quarantine: fix exception not being caught

Library/Homebrew/test/utils/pypi_spec.rb, Library/Homebrew/utils/pypi.rb
=> Revert "PyPI: Handle non-`pythonhosted` formula URLs"

.github/workflows/tests.yml
We're not actually testing the latest homebrew-cask at the moment, because homebrew-cask is preinstalled on GitHub Actions macOS images and a simple `brew tap` won't update it.
Maybe `setup-homebrew` should update it. This is a safer fix for now since I need it for #15522, and we had `update-reset` here before so shouldn't be controversial.
=> workflows/tests: update homebrew-cask

Library/Homebrew/macos_version.rb, Library/Homebrew/os/mac.rb, Library/Homebrew/os/mac/pkgconfig/14/expat.pc, Library/Homebrew/os/mac/pkgconfig/14/libcurl.pc, Library/Homebrew/os/mac/pkgconfig/14/libedit.pc, Library/Homebrew/os/mac/pkgconfig/14/libexslt.pc, Library/Homebrew/os/mac/pkgconfig/14/libffi.pc, Library/Homebrew/os/mac/pkgconfig/14/libxml-2.0.pc, Library/Homebrew/os/mac/pkgconfig/14/libxslt.pc, Library/Homebrew/os/mac/pkgconfig/14/ncurses.pc, Library/Homebrew/os/mac/pkgconfig/14/ncursesw.pc, Library/Homebrew/os/mac/pkgconfig/14/sqlite3.pc, Library/Homebrew/os/mac/pkgconfig/14/uuid.pc, Library/Homebrew/os/mac/pkgconfig/14/zlib.pc, Library/Homebrew/os/mac/xcode.rb, Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.arm64_sonoma.bottle.tar.gz, Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.sonoma.bottle.tar.gz
=> Preliminary macOS 14 (Sonoma) support

Library/Homebrew/utils/gems.rb
We use `Gem::Specification.find_all_by_name("bundler", "2.3.26")` to check if Bundler is already installed, so we aren't reinstalling it unnecessarily.
However it turns out Rubygems has some feature that to be smart and ignores the version you provide and instead reads what `Gemfile.lock` in your working directory uses.
We don't want this behaviour, so override that behaviour by setting `BUNDLER_VERSION` before invoking the install procedure.
=> utils/gems: fix bundler sometimes unnecessarily reinstalling

docs/_config.yml
This slightly speeds up generation and it's no longer needed as of https://github.com/Homebrew/brew.sh/pull/957.
=> docs/config: remove jekyll-feed.

Library/Homebrew/formula_auditor.rb
-----
This happens when CI runs on an event that isn't a pull request (e.g.
push, merge_group).
=> formula_auditor: handle `head_info` being `nil`

Library/Homebrew/download_strategy.rb
-----
Appears to fix https://github.com/Homebrew/brew/issues/15537. I don't know why that crash started showing up with git 2.41.0, but this does appear to fix it.
While trying to reproduce the bug I noticed that some sparse checkouts did cause a git crash and others didn't. It turned out that the ones that worked were using "cone" mode, whereas homebrew is currently using non-cone mode. Cone mode is a bit less flexible — for instance it doesn't let you exclude top-level files, and it only lets you select directories not individual files. However, the git documentation lists a long series of [problems with non-cone mode](https://git-scm.com/docs/git-sparse-checkout#_internalsnon_cone_problems), and concludes by saying "non-cone mode is deprecated. Please switch to using cone mode."
This …
=> Use "cone" mode for sparse checkouts

Library/Homebrew/cmd/info.rb, Library/Homebrew/utils/analytics.rb
This screen scrapes GitHub Packages download counts from HTML for a core formula.
It's useful when figuring out the difference between our analytics numbers (which people can opt-out of) and our bottle downloads (which people cannot due to the way GitHub Packages works).
=> cmd/info: add (undocumented) --github-packages-downloads option.

Library/Homebrew/github_packages.rb
-----
Some bottles are quite large, and the copies can make us run out of
space rather quickly. Let's try to avoid that by using hard links
instead of copies.
One case worth thinking about that I don't handle here: what if the source and destination live in different file systems?
=> github_packages: create hard link instead of copying

Library/Homebrew/formula_installer.rb
In certain cases the wrong, resolved file path is used in the postinstall stage. Confusingly, when this happened postinstall would actually just be skipped silently without any warnings unless you had `--debug` so the issue was easy to miss and could have been an issue for some time.
The build stage uses `specified_path` so the fix here is to be consistent with the rest of FormulaInstaller and do the same with postinstall.
Fixes https://github.com/Homebrew/homebrew-core/issues/130672.
=> formula_installer: fix postinstall using incorrect formula file

Library/Homebrew/formula.rb
We check if `on_os` is used on class level, but it might be used on instance-level like in caveats.
Fixes #15014.
=> formula: fix variations not being generated for instance on_os usage

Library/Homebrew/github_packages.rb
-----
`FileUtils.cp` overwrites its destination when the destination already
exists, while `FileUtils.ln` throws `EEXIST`. To restore the old
behaviour, let's set `force: true`.
This fixes recent CI failures in Homebrew/core.[^1]
[^1]: For example: https://github.com/Homebrew/homebrew-core/actions/runs/5313853638/jobs/9620314048#step:8:158
=> github_packages: call `ln` with `force`

Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/formula_auditor.rb
-----
1. Adjust audit so that it ignores conflicts only for `brew audit --tap`.
This is useful because it prevents us from trying to migrate a formula
to `openssl@3` before all its dependencies have also been migrated.
2. Exempt only PRs that target a branch called
`openssl-migration-staging`.
=> formula_auditor: adjust deps audit for a staging branch

Library/Homebrew/cmd/leaves.rb
-----
Resolves an issue with `brew leaves` introduced in PR https://github.com/Homebrew/brew/pull/15573:
```
❯ brew leaves
Error: uninitialized constant Homebrew::CaskDependent
/opt/homebrew/Library/Homebrew/cmd/leaves.rb:40:in `block in leaves'
/opt/homebrew/Library/Homebrew/cmd/leaves.rb:39:in `each'
/opt/homebrew/Library/Homebrew/cmd/leaves.rb:39:in `flat_map'
/opt/homebrew/Library/Homebrew/cmd/leaves.rb:39:in `leaves'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
=> cmd/leaves: add missing cask dependency

Library/Homebrew/brew.sh, Library/Homebrew/cmd/update.sh
As discussed in #15342.
Bump commands largely abstract away the concept of git commands, so it's a better user experience to take on the role of auto-updating these git clones. Bump commands are great for being largely accessible for regular users to cross the gap and make their first contributions to Homebrew (and potentially their first open source contribution entirely), so the less frustration and manual work required there the better.
Previously, the user would have to set `HOMEBREW_NO_INSTALL_FROM_API` for these to update and we are moving towards discouraging this more in favour of smart handling (like #15564).
=> Allow bump commands to auto-update core tap clones

Library/Homebrew/cmd/postinstall.rb, Library/Homebrew/formula.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/formulary.rb, Library/Homebrew/test/formula_spec.rb
The process of forking to run postinstall is fairly slow. There's probably things we could do to improve that, but it's a little complex given it's a compound of causes.
However, forking isn't always strictly necessary. By moving responsibility of etc/var file installs away from the forked process, and making that forked process scoped to only running `Formula#post_install` and the paraphernalia around it, we can check ahead of time whether a process fork is even necessary. That is, whether a `post_install` is even defined in the formula in question.
The "pouring" stage of `brew install hello` took about 2 seconds for me before this change. After this change, it's effectively instant. (If testing locally prior to merging, you will need `HOMEBREW_NO_INSTALL_FROM_API=1` until the changes …
=> Significantly improve install speeds with smarter postinstall detection

Library/Homebrew/api.rb, Library/Homebrew/brew.sh, Library/Homebrew/cli/args.rb, Library/Homebrew/cli/named_args.rb, Library/Homebrew/cli/parser.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/dev-cmd/test.rb, Library/Homebrew/exceptions.rb
This lays some groundwork for better `HOMEBREW_NO_INSTALL_FROM_API` commands by scoping it to just the part that resolves CLI arguments.
Implemented only for `brew test` in this PR. Maybe should be a draft PR since I've not tested the feasability of it for other commands yet, but it seems to work much better already for `brew test` and fixes some of the issues described in #15049.
Idea is we delete `NO_INSTALL_FROM_API_COMMANDS` and replace that with uses of this (+ `Homebrew.without_api` blocks for more complex use cases like we already do in `brew audit`).
=> Better scoping for no-api commands

Library/Homebrew/cmd/update.sh
Probably seldomly used but when doing the bump auto-update tweaks I noticed that passing `--merge` and `--simulate-from-current-branch` to `brew update` will error once reaching `brew update-report` becuse update-report doesn't support these flags.
=> cmd/update.sh: fix some flags throwing errors on update report

Library/Homebrew/brew.sh
The intention here was:
* `HOMEBREW_NO_INSTALL_FROM_API` users have 5 minute intervals
* `dev-cmd` users have 1 hour intervals (as they are more "at risk" of brew regressions)
* Regular users have 24 hour intervals
However the order left the `dev-cmd` case not really working as intended:
* `dev-cmd` without `HOMEBREW_NO_INSTALL_FROM_API` would still have the 24 hour interval
* `dev-cmd` with `HOMEBREW_NO_INSTALL_FROM_API` would actually increase the interval from 5 minutes to 1 hour compared to regular users.
So this swaps the order to fix that.
=> brew.sh: fix auto-update interval for dev-cmd users

Library/Homebrew/brew.sh, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/dev-cmd/bump-cask-pr.rb, Library/Homebrew/dev-cmd/bump-formula-pr.rb, Library/Homebrew/dev-cmd/bump-revision.rb, Library/Homebrew/dev-cmd/bump-unversioned-casks.rb, Library/Homebrew/dev-cmd/bump.rb, Library/Homebrew/dev-cmd/cat.rb, Library/Homebrew/dev-cmd/create.rb, Library/Homebrew/dev-cmd/edit.rb, Library/Homebrew/dev-cmd/extract.rb, Library/Homebrew/dev-cmd/formula.rb, Library/Homebrew/dev-cmd/generate-cask-api.rb, Library/Homebrew/dev-cmd/generate-formula-api.rb, Library/Homebrew/dev-cmd/livecheck.rb, Library/Homebrew/dev-cmd/pr-pull.rb, Library/Homebrew/dev-cmd/style.rb, Library/Homebrew/dev-cmd/update-python-resources.rb
I haven't tested absolutely everything here (e.g. `brew bottle`), but the ones I did seemed to work fine.
=> Migrate remaining no-api commands to new scoped system

Library/Homebrew/dev-cmd/create.rb, Library/Homebrew/dev-cmd/edit.rb
-----
- Fix `brew edit` error message if the formula doesn't exist (`brew create` doesn't have `--formula` argument)
- Fix `brew create` error message  if run without `--tap` argument and the default tap/cask is untapped
=> Fix error messages for brew edit and brew create

Library/Homebrew/utils/curl.rb
-----
Not all websites protected by CloudFlare have a `set-cookie` header, but at the very least, every one has a `server: cloudflare` header.
Fixes CI failure in https://github.com/Homebrew/homebrew-cask/pull/149788.
=> Simplify CloudFlare header check.

Library/Homebrew/extend/pathname.rb
Otherwise we might match binary sequences that happen to be `0A 23 21 <regular non-space character>`.
=> extend/pathname: fix `text_executable?` regex

Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
---
Quick fix for the manpage having a literal `\n\n`
=> man: fix a literal newline

docs/FAQ.md
Add a line in the FAQ explaining how brew update-reset can be used to undo changes users might have made with brew edit.
-----
I fell into [this trap](https://github.com/Homebrew/brew/issues/5108) a couple times in the past month (I just started using Hombrew). Each time i had to google the solution again, so I thought why not suggest to add this trick in the FAQ where I first learned about `brew edit`?
Not sure whether it is possible to use `brew update-reset` on a specific formula. (The man page states : "_Fetch and reset Homebrew and all tap repositories (or any specified repository) using git(1) to their latest origin/HEAD._" would I need to indicate a repository rather than the formula name?) So I kept the documentation clear about how this will revert to upstream for all …
=> Explain how to undo brew edit

Library/Homebrew/formula.rb, Library/Homebrew/tap.rb
This is needed to allow `Formula.all` to behave as expected when using the API. Let's also (immediately, because it's broken) deprecate the `CoreTap#formula_files` method.
Fixes #15122
=> Include core formulae from API in `Formula.all`.

Library/Homebrew/dependency.rb, Library/Homebrew/test/dependency_expansion_spec.rb, Library/Homebrew/test/formula_spec.rb
This allows renamed or aliased formulae dependencies to be resolved to specific formulae correctly and deduplicated.
Fixes https://github.com/Homebrew/brew/issues/15488
=> dependency: use formula name.

Library/Homebrew/cmd/nodenv-sync.rb, Library/Homebrew/cmd/pyenv-sync.rb, Library/Homebrew/cmd/rbenv-sync.rb
Similar to `rbenv-sync` and `nodenv-sync`, but for use with `pyenv`.
Python has separate formulae for minor Python versions, as such this will symlink all patch versions to the latest minor version.
Following the style in https://github.com/Homebrew/brew/pull/14972, didn't see any example tests.
=> cmd/pyenv-sync: add new command.

Library/Homebrew/test/utils/github_spec.rb
GitHub completely wipes the existance of old CI runs after a couple years.
This'll probably break again in a couple years. Maybe should mock the response or something
=> test/utils/github_spec: fix artifact URL test

Library/Homebrew/extend/ENV/super.rb
-----
Many (~60) formulae in Homebrew/core set this manually to prevent the
`openssl` Rust crate from vendoring OpenSSL.
Let's make handling this simpler by setting it globally instead.
=> extend/ENV/super: set `OPENSSL_NO_VENDOR`

Library/Homebrew/test/utils/pypi_spec.rb, Library/Homebrew/utils/pypi.rb
-----
This is take two on #15511.
From the original:
This is another quality of life improvement to our handling of Python packages, unlocked by the switch to `pip install --report --dry-run` from a few weeks ago: `pip install` can accept arbitrary distribution URLs, meaning that we no longer require the top-level to be a `pythonhosted` URL in order to auto-bump its dependencies using `update-python-resources`.
This should result in automation for a handful of formulae that previously required manual resource updating. More indirectly, it improves `brew-pip-audit`'s ability to bulk audit Python packages present in Homebrew formulae, resulting in more automated vulnerability fix PRs as well.
=> PyPI: Handle non-pythonhosted formula URLs

Library/Homebrew/tap.rb
-----
I was getting the following error until I disabled fsmonitor for taps as well:
```
% brew upgrade
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
############################################################################################################################################################### 100.0%
```
Git's fsmonitor is already disabled 
- for `HOMEBREW_PREFIX` in https://github.com/Homebrew/brew/pull/13586 …
=> tap: disable fsmonitor for third-party taps

Library/Homebrew/cmd/update.sh
unless `HOMEBREW_DEVELOPER` is set as per before.
Currently, if you do a manual `brew update` without `HOMEBREW_DEVELOPER` set, it will fetch the repo but not actually fully update it. Which is perhaps a little unusual. It also surprised people getting errors that don't actually impact anything in practice.
This PR aligns the fetch check with [the actual branch update check further down](https://github.com/Homebrew/brew/blob/f252323725b600f50817d1d3e0ad8a24979548d9/Library/Homebrew/cmd/update.sh#L740).
One slight caveat is people who do need a tap later on will have to go through a longer fetch to catch up.
=> cmd/update: don't fetch core taps on manual brew update

Library/Homebrew/build.rb, Library/Homebrew/cmd/deps.rb, Library/Homebrew/dependable.rb, Library/Homebrew/dependencies.rb, Library/Homebrew/dependencies_helpers.rb, Library/Homebrew/dependency.rb, Library/Homebrew/dependency_collector.rb, Library/Homebrew/extend/os/linux/dependency_collector.rb, Library/Homebrew/extend/os/mac/dependency_collector.rb, Library/Homebrew/formula.rb, Library/Homebrew/formula_auditor.rb, Library/Homebrew/formulary.rb, Library/Homebrew/language/perl.rb, Library/Homebrew/software_spec.rb, Library/Homebrew/test/dependency_collector_spec.rb, Library/Homebrew/test/dependency_spec.rb, Library/Homebrew/test/formulary_spec.rb, Library/Homebrew/test/os/linux/dependency_collector_spec.rb, Library/Homebrew/test/os/mac/dependency_collector_spec.rb, Library/Homebrew/test/os/mac/formula_spec.rb, Library/Homebrew/test/software_spec_spec.rb
This PR tries to tackle several of the "harder" issues involving API dependencies. Basically the stuff that required deeper refactoring rather than a hack-on fix.
There were several cases where the dependency list was incorrect. Usually this erred on the side of too many dependencies rather than too little, so hasn't seen widespread bug reports beyond a few comments here and there.
Notably:
* The dependency list had parts that varied depending on the machine that generated the API JSON rather than the consumer.
* Stable-only or HEAD-only dependencies were not correctly considered.
* `uses_from_macos "example", since: ...` did not work correctly.
This changes in this PR are:
* Removed `TapDependency` (this makes the rest of the PR a bit simpler), folding it into `Dependency`
* Refactored …
=> Refactor some dependency handling to fix various API dependency issues

Library/Homebrew/tap_auditor.rb
`tap.formula_names` etc could use API data but we don't want that when auditing on-disk JSON files.
Fixes https://github.com/orgs/Homebrew/discussions/4620.
=> tap_auditor: fix API data getting mixed in

Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/dev-cmd/bump-cask-pr.rb
If we run `brew audit --cask something` we probably only want to audit homebrew/cask and not every tap.
Related to https://github.com/orgs/Homebrew/discussions/4620.
=> dev-cmd/audit: don't audit every tap when given named packages

Library/Homebrew/formula.rb, Library/Homebrew/tap.rb, Library/Homebrew/test/formula_spec.rb
This doesn't work with the API and the single caller can be refactored to not need it instead.
Issue spotted in https://github.com/MikeMcQuaid/strap/actions/runs/5465161353/jobs/9948204604?pr=803
=> Remove `Tap#versioned_formula_files`

Library/Homebrew/api.rb, Library/Homebrew/api/cask.rb, Library/Homebrew/api/formula.rb, Library/Homebrew/cmd/update.sh, Library/Homebrew/tap.rb
Download the previously stored tap migrations files for homebrew/core and homebrew/cask from the formulae.brew.sh API.
This adds a much longer stale time (24 hours) to decide whether or not the migrations files need downloaded from the API in Ruby land. `brew update` will still update them every time.
While we're here, DRY up some code in `update.sh` too.
Requires https://github.com/Homebrew/brew/pull/15628
Fixes https://github.com/Homebrew/brew/issues/14897
=> Download `tap_migrations.json` files from the API

Library/Homebrew/cmd/update-report.rb
Nudge people who have set update-related settings to change them.
Inspired by @Bo98 pointing out we may not "get back" people who disabled the API.
It probably makes sense to hold off until 4.0.1 or later rather than 4.0.0 for this just so they get the most stable experience.
I will also add this to the 4.0.0 release notes.
=> cmd/update-report: nudge people to tweak settings.

Library/Homebrew/cmd/update-report.rb
Otherwise this can be printed incorrectly.
As reported in https://github.com/Homebrew/brew/pull/14592#issuecomment-1623578695
=> cmd/update-report: use api_auto_update_secs default.

Library/Homebrew/cask/quarantine.rb
With the update of MacOS from Monterey (12) to Ventura (13) the appearance of the System Settings has changes and the "Security & Privacy" category has been renamed to "Privacy & Security".
I am aware that currently Ventura has a very low adoption rate so this change could be premature.
-----
=> App Management message reflects new System Settings labels

Library/Homebrew/tap.rb
Otherwise command-only or cask-only taps have all its files picked up as formula files.
=> tap: fix handling of taps without formulae

Dockerfile, Library/Homebrew/cmd/update-report.rb, bin/brew
* Don't really need the `brew untap` message for CI as it's either already there in the base image or we are already warning them when they are doing a `brew tap`.
* `HOMEBREW_NO_AUTO_UPDATE` is reasonable on CI when you consider people will only be seeing this message when doing a `brew update` and in CI given you likely want a consistent state for the rest of the CI run.
Should we touch the analytics message for GitHub Actions?
=> cmd/update-report: tweak messages for CI

Library/Homebrew/exceptions.rb, Library/Homebrew/utils/github.rb
-----
- This change is useful for the "these issues are also open for this build failure" exception. Hopefully there'll be less noise on PRs with people encouraging us to fix things faster if we don't link them to WIP PRs (or any PRs at all).
- Fixes https://github.com/Homebrew/brew/issues/15608.
=> Enable `GitHub.issues_for_formula` to show only issues, only PRs, or both

Library/Homebrew/livecheck/livecheck.rb, Library/Homebrew/livecheck/strategy/extract_plist.rb
Fixes referenced formulae and casks being loaded from the API, which does not contain livecheck information.
https://github.com/Homebrew/homebrew-cask/pull/150664
=> livecheck: fix implicit no-api handling

Library/Homebrew/cmd/--cache.rb
-----
This is useful for quickly examining bottles with something like
brew fetch --bottle-tag=$tag $formula && \
tar xf "$(brew --cache --bottle-tag=$tag $formula)"
See discussion at #15632.
=> cmd/--cache: undeprecate `--bottle-tag`

docs/How-To-Open-a-Homebrew-Pull-Request.md
Tap directories for furmulae/casks have to be created manually. Add additional step into docu for creating them.
Closes #15640
=> docs: Add info about tap creation

Library/Homebrew/extend/os/mac/keg_relocate.rb, Library/Homebrew/linkage_checker.rb, Library/Homebrew/os/mac/mach.rb
-----
Adds to the logic for how `install_name`s and `rpath`s are fixed (after a build) and relocated (from bottles) on macOS, so that the installed binaries will load other Homebrew-installed dynamic libraries using relative paths instead of absolute paths. 
For example, a reference to a library with an `install_name` currently set in an executable as:
`/opt/homebrew/Cellar/<same_formula>/<same_version>/lib/lib<some_lib>.dylib` 
will be changed to something like:
`@loader_path/../lib/lib<some_lib>.dylib` 
instead, and references to libraries from dependencies are changed to:
`@loader_path/../../../../opt/<other_formula>/lib/lib<other_lib>.dylib`.
It should cover both bottled installs as well as builds from source. I've tried both—with default and custom Homebrew prefixes—and didn't run …
=> mac/keg_relocate: use relative install names

Library/Homebrew/formula_auditor.rb
Like what we already have for deprecations.
=> formula_auditor: check disabled formulae have disabled dependents

Library/Homebrew/shims/mac/super/bsdmake, Library/Homebrew/shims/mac/super/make
-----
We have a handful of formulae that use Homebrew `make` to build. Doing
this evades our compiler shims. Let's try to avoid this by allowing our
shims to support usage of Homebrew `make` by calling it as `gmake` in
the formula.
=> shims/mac: handle usage of Homebrew `make`

docs/Installation.md
-----
Fixes the link to the Apple Developer account page in the footnote, which is now giving a 404.
Not sure if the "Mac OS X" mention on the same line shouldn't also be changed to "macOS"...
=> docs/Installation: fix Apple Developer account link

Library/Homebrew/shims/mac/super/make
`xcrun --find` will always succeed here so instead do what we do for most other shims.
=> shims/mac/super/make: use standard exec routines

Library/Homebrew/formula_auditor.rb, Library/Homebrew/rubocops/lines.rb
-----
We want formulae to build with our `rust` formula instead of a random
toolchain downloaded with `rustup`.
Unfortunately, some formulae already do this, so let's gate the check
behind `--strict`. It should also prevent new formulae that build using
`rustup` from being added.
This should hopefully prevent PRs like Homebrew/homebrew-core#119832
from being merged.
=> formula_auditor: disallow non-test `rustup-init` dependencies

Library/Homebrew/cmd/cleanup.rb
I was looking for a way to suppress output in `brew cleanup` especially the `Warning: Skipping XXX: most recent version X.Y.Z not installed`. I noticed that `Homebrew::Cleanup#clean` takes a `quiet` argument, but `brew cleanup` doesn't pass one in. This PR updates `brew cleanup` to accept and forward along a `quiet` argument.
-----
=> Support `brew cleanup --quiet`

Library/Homebrew/dev-cmd/generate-cask-api.rb, Library/Homebrew/dev-cmd/generate-formula-api.rb
This needs to be in the no-API block, otherwise we're just taking in API data to generate API data.
=> generate-*-api: fix on-disk tap migrations not being used

Library/Homebrew/brew.sh, bin/brew
Fixes #14557
This commit serves as a proof-of-concept that using Homebrew bottles is possible on Fedora Silverblue and other setups where `/home` is symlinked as`/home -> var/home`. The `install.sh` script does install in `/home/linuxbrew/.linuxbrew` it just so happens that its physical location is `/var/home/linuxbrew/.linuxbrew` due to the symlink. So, all programs are actually in the correct prefix. However due to the way `bin/brew` resolves symlinks, Homebrew commands think the prefix is custom. Me and @rohanssrao have tested that this fix also works in `fedora-toolbox` and `ubuntu` containers where we symlinked `/home` ->`var/home`. The script can be found at [`silverbrew-fedora-toolbox.sh`](https://github.com/osalbahr/brew/blob/silverbrew-develop/silverbrew-fedora-toolbox.sh) and …
=> Feature: support symlinked /home

docs/Cask-Cookbook.md
-----
Replaces references to "single-quoted" strings with "double-quoted" strings to match our style guide.
=> docs/cask: replace single-quoted with double-quoted

Library/Homebrew/extend/os/mac/keg_relocate.rb
-----
Some formulae (e.g. `php`) use rpaths that reference Cellar paths
belonging to other formulae. Let's make sure these rpaths don't break by
making them use opt paths instead.
=> os/mac/keg_relocate: replace Cellar references in rpaths

Library/Homebrew/cask/cask_loader.rb, Library/Homebrew/cmd/install.rb, Library/Homebrew/cmd/update-report.rb, Library/Homebrew/dev-cmd/extract.rb, Library/Homebrew/dev-cmd/generate-cask-api.rb, Library/Homebrew/diagnostic.rb, Library/Homebrew/extend/os/mac/tap.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/formulary.rb, Library/Homebrew/tap.rb, Library/Homebrew/test/cask/cask_loader/from_tap_loader_spec.rb, Library/Homebrew/test/cask/cask_spec.rb, Library/Homebrew/test/diagnostic_checks_spec.rb, Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
* Introduce `CoreCaskTap` (closes #15597)
* Fix various tap methods (e.g. `cask_tokens`) not working on untapped Homebrew/cask under API.
* Deprecate `Tap.default_cask_tap` and `Tap.install_default_cask_tap_if_necessary` in favour of `CoreCaskTap`.
* Add `ensure_installed!` as a tap instance method for all taps. Previously exclusively a `CoreTap` class method, this method will now do the right thing given any arbitrary tap object (i.e. not install anything for core taps under API mode, but do install for other taps).
* Use new `ensure_installed!` instance method to fix various cases where core taps were being unnecessarily installed, in particular around tap migrations (probably fixes #15674)
=> Introduce CoreCaskTap class and fix cases of core taps were being unnecessarily installed

Library/Homebrew/utils/analytics.rb
=> utils/analytics: hide InfluxDB message correctly.

docs/Homebrew-on-Linux.md
Note: I'm not entirely sure if these are sufficient. I mimicked what's [in `install.sh`](https://github.com/Homebrew/install/blob/master/install.sh#L1052) and what's already listed for the remaining distros.
-----
<details>
<summary>
brew tests
</summary>
<pre>
Randomized with seed 28976
8 processes for 353 specs, ~ 44 specs per process
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................. …
=> docs: Requirements: add Arch Linux

Library/Homebrew/rubocops/uses_from_macos.rb
-----
macOS `texinfo` is left at an old version, and is not present on newer version (Ventura and later). We have migrated all of homebrew-core versions to using Homebrew's texinfo when necessary (like in https://github.com/Homebrew/homebrew-core/pull/114068 and friends), but the audit still triggers in some cases: https://github.com/Homebrew/homebrew-core/pull/135322
It's high time we stop insisting on using macOS texinfo. I actually thought I had done that already a couple of months ago :)
=> Do not insist on using macOS texinfo

Library/Homebrew/cmd/update-report.rb, Library/Homebrew/utils/analytics.rb
Take 2.
Address https://github.com/Homebrew/brew/pull/15688#issuecomment-1638725595
Fixes https://github.com/Homebrew/brew/issues/15678
=> Fix (again) InfluxDB analytics messaging

Library/Homebrew/cmd/tap.rb, completions/bash/brew, completions/fish/brew.fish, completions/zsh/_brew, docs/Manpage.md, manpages/brew.1
Not deprecating as it's broken and has been for several major versions.
=> cmd/tap: remove --list-pinned option.

Library/Homebrew/rubocops/lines.rb, Library/Homebrew/test/rubocops/lines/quictls_check_spec.rb
-----
QuicTLS is a fork of OpenSSL that adds support for QUIC. We'll probably
end up adding it to homebrew/core at some point (see
Homebrew/homebrew-core#134975), but I don't think we want to actually
use it as a dependency of any formulae in place of OpenSSL.
We ought to only allow it for software that actually require QuicTLS in
place of OpenSSL, but I'm not aware of any existing formulae that have
this requirement.
=> rubocops/lines: disallow `quictls` dependencies in homebrew/core

Library/Homebrew/diagnostic.rb
Unless we're in no API mode: we shouldn't check this.
Fixes #15696
=> diagnostic: don't complain about missing homebrew/cask.

docs/Installation.md
I shouldn't care but: the only versions where this is required are Mac OS X versions.
=> docs/Installation: fix Mac OS X reference.

Library/Homebrew/extend/api_hashable.rb
This breaks some API generation and isn't actually required.
Feels like running `brew generate-formula-api` in CI here should have caught this but didn't? Weird. Any ideas @Bo98?
=> api_hashable: remove HOMEBREW_CELLAR.

.github/workflows/tests.yml, Library/Homebrew/dev-cmd/generate-cask-api.rb, Library/Homebrew/dev-cmd/generate-formula-api.rb
- also try generating formula API on macOS
- pull more logic out of `unless args.dry_run?` in case it fails
=> dev-cmd/generate-*-api: be a bit safer.

Library/Homebrew/extend/os/mac/keg_relocate.rb
-----
Doing `change_rpath(old, new, file)` will error if `new` is already an
rpath for `file`. When this happens, `old` is no longer needed, so we
can delete it.
Fixes a build failure at shivammathur/homebrew-php#1848.
=> os/mac/keg_relocate: avoid changing to an already existing rpath

docs/FAQ.md
New installs don't tap `homebrew/core` and default to the API instead, so `brew edit foo` fails with `Error: Invalid usage: foo doesn't exist on disk.` for any formula `foo`. Add an instruction in the FAQs to run `brew tap homebrew/core` first, which fixes this issue. (See more notes below checklist.)
-----
#15693 also addresses changes to docs now that the core repos are untapped by default, but seems to focus more on those developing and contributing new formulae rather than those making quick edits to core formulae.
#15693 uses `brew tap --force homebrew/core`, while my change omits `--force`. Running without `--force` results in a warning but the command still completes successfully. I can add `--force` into the docs if desired.
Ignoring failures in `brew style` and `brew tests`, as …
=> docs/FAQ: tap homebrew/core before editing formula

README.md
-----
BuildPulse’s icon size was slightly smaller than the others. It also had a circular background but on the website they use a rounded rectangle, so updated to that. Companion to #15713.
Before:
After:
=> README.md: Normalise BuildPulse icon size

Library/Homebrew/cask/config.rb, Library/Homebrew/dev-cmd/generate-cask-api.rb, Library/Homebrew/version.rb
-----
As requested in https://github.com/Homebrew/brew/pull/15705#issuecomment-1640081358
=> Fix type errors when HOMEBREW_SORBET_RUNTIME=1

Library/Homebrew/utils/github/api.rb
-----
The order is shared with self.credentials, but during the deprecation cycle the need to adjust self.credentials_type to match was overlooked.
=> utils/github/api: fix credentials_type

Library/Homebrew/formula.rb, Library/Homebrew/language/python.rb, Library/Homebrew/test/language/python/virtualenv_spec.rb
---
This introduces a `std_pip_args` for use in homebrew-core, matching other languages. We currently have two Python-related installation methods:
1. `Language::Python.setup_install_args`, our `setup.py` shim
1. `Language::Python::Virtualenv.pip_install` for venv-based packages
The former (direct `setup.py` execution) has been deprecated for almost two years now (see [1](https://github.com/pypa/setuptools/pull/2824) and [2](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)). One replacement is to use `pip install` instead, so as we update formulae it'd be useful to easily share common pip args.
=> formula: add `std_pip_args`

Library/Homebrew/extend/os/mac/keg_relocate.rb
-----
This should fix the failures seen for `julia` in Homebrew/core.[^1]
I've detailed a better/more comprehensive fix as a `TODO` in a comments.
However, the problems that the better fix would avoid are comparatively
unlikely, so I think we can try this one out for now while I work on
implementing the said fix.
[^1]: https://github.com/Homebrew/homebrew-core/pull/135398#issuecomment-1643041541
=> os/mac/keg_relocate: avoid rpath re-ordering

Library/Homebrew/brew.sh, Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
Reverts #15385 with some tweaks:
- remove the commands that are now passing (on my machine)
- add some commands that are definitely failing (on my machine)
- provide the (temporary, undocumented) `HOMEBREW_NO_SORBET_RUNTIME` to disable Sorbet globally if needed more easily from e.g. specific GitHub Actions workflows 
Won't be merged until after 4.1.0 is out.
=> Enable HOMEBREW_SORBET_RUNTIME (sometimes)

Library/Homebrew/extend/ENV/super.rb
The block is optional, so it should be marked `T.nilable`
-----
I observed the following failure on PR [#137236](https://github.com/Homebrew/homebrew-core/pull/137236) today and thought it might be caused by this. The highlighted line in the error is an `ENV.deparallelize` with no block
```
Error: An exception occurred within a child process:
TypeError: Block parameter 'block': Expected type T.proc.params().returns(T.untyped), got type NilClass
```
=> extend/ENV/super: correct `deparallelize` signature

Library/Homebrew/formula.rb, Library/Homebrew/utils/inreplace.rb
-----
Implicit `Pathname` strings strike again:
Resolves https://github.com/Homebrew/homebrew-core/actions/runs/5628176140/job/15251794429
```
==> go build -trimpath -o=/opt/homebrew/Cellar/loki/2.8.3/bin/loki -ldflags=-s -w
Error: An exception occurred within a child process:
TypeError: Parameter 'after': Expected type T.nilable(T.any(String, Symbol)), got type Pathname with value #<Pathname:/opt/homebrew/var>
Caller: /opt/homebrew/Library/Homebrew/formula.rb:2476
Definition: /opt/homebrew/Library/Homebrew/utils/inreplace.rb:48
```
Also adds a `sig` to `Formula#inreplace` and fixes an accompanying type error.
=> Fix `inreplace` sig

Library/Homebrew/github_packages.rb
If the GitHub server returns an error when we are uploading the image index, skopeo could fall back and use a Docker distribution manifest list instead, creating a manifest that brew cannot read.
Let's force OCI format here, which will disable the fallback formats, and mean that upload operation fails if GitHub is having issues rather than letting it go and upload a bad manifest.
=> github_packages: ensure only OCI format is uploaded

Library/Homebrew/formula_creator.rb
-----
Always require a version when creating a formula, either via URL detection or with `--set-version`. Otherwise, `brew create` would create the file without a version and then fail when validating.
```
$ brew create --set-name testformula --tap ericfromcanada/test http://example.com/test.xz --no-fetch
Warning: Version cannot be determined from URL.
You'll need to add an explicit 'version' to the formula.
Error: invalid attribute for formula 'ericfromcanada/test/testformula': version (nil)
/usr/local/Homebrew/Library/Homebrew/formula.rb:298:in `validate_attributes!'
/usr/local/Homebrew/Library/Homebrew/formula.rb:223:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:484:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:484:in `get_formula' …
```
=> formula_creator: require version before creating

Library/Homebrew/formula.rb
-----
Fixes
TypeError: Parameter 'before': Expected type T.nilable(T.any(Regexp, String)), got type Pathname with value #<Pathname:/opt/homebrew/Cellar/php/8.2.8/lib/php>
Caller: /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/php.rb:207
Definition: /opt/homebrew/Library/Homebrew/formula.rb:2483
https://github.com/Homebrew/homebrew-core/actions/runs/5635089949/job/15265751616?pr=137335#step:3:1732
=> formula: fix `inreplace` typechecking error

Library/Homebrew/utils/inreplace.rb
-----
Fixes
TypeError: Parameter 'before': Expected type T.nilable(T.any(Regexp, String)), got type Pathname with value #<Pathname:/opt/homebrew/Cellar/php@8.1/8.1.21/lib/php>
Caller: /opt/homebrew/Library/Homebrew/formula.rb:2484
Definition: /opt/homebrew/Library/Homebrew/utils/inreplace.rb:48
https://github.com/Homebrew/homebrew-core/actions/runs/5635089949/job/15266014851#step:3:1737
=> utils/inreplace: fix typechecking error

Library/Homebrew/tap.rb
-----
Avoid an error when attempting to repair a freshly-created tap:
```
$ brew tap-new ericfromcanada/test
Initialized empty Git repository in /usr/local/Homebrew/Library/Taps/ericfromcanada/homebrew-test/.git/
[main (root-commit) 7465854] Create ericfromcanada/test tap
3 files changed, 90 insertions(+)
create mode 100644 .github/workflows/publish.yml
create mode 100644 .github/workflows/tests.yml
create mode 100644 README.md
==> Created ericfromcanada/test
/usr/local/Homebrew/Library/Taps/ericfromcanada/homebrew-test
When a pull request making changes to a formula (or formulae) becomes green
(all checks passed), then you can publish the built bottles.
To do so, label your PR as `pr-pull` and the workflow will be triggered.
$ brew tap --repair ericfromcanada/test 
Error: undefined …
```
=> cmd/tap: ensure remote exists before repairing

Library/Homebrew/formula.rb
---
`Pathname.present?` returns false when the directory is empty
=> formula: fix `std_pip_args` with empty prefix

Library/Homebrew/dev-cmd/pr-pull.rb
`--branch-okay` is supposed to silence the warning but it actually was making the warning always display.
Also check for `--no-cherry-pick` and `--no-commit` as those are typically passed if you are running this on the PR branch (like we are in homebrew-core).
=> dev-cmd/pr-pull: fix branch warning conditions

Library/Homebrew/cmd/--cache.rb, Library/Homebrew/cmd/info.rb, Library/Homebrew/dev-cmd/bump.rb, Library/Homebrew/extend/os/mac/formula_cellar_checks.rb, Library/Homebrew/formula.rb, Library/Homebrew/formula_auditor.rb, Library/Homebrew/formulary.rb, Library/Homebrew/livecheck/livecheck.rb, Library/Homebrew/utils/pypi.rb
-----
I found it confusing that the `Formula#build` attr could be `BuildOptions` or `Tab`, plus we've had some Formula type issues lately, so I added `sig`s for all of the `Formula` attrs.
Note that this leads to sprinkling of `T.must`s – a common cause is poor type guards (consecutive invocations of a nilable attr getter are not guaranteed to be non-nil).
=> Add types to Formula attrs

Library/Homebrew/cask/exceptions.rb, Library/Homebrew/cask/installer.rb, Library/Homebrew/cmd/install.rb, Library/Homebrew/env_config.rb, Library/Homebrew/test/cask/installer_spec.rb
-----
Resolves #15295. This is a breaking change so it might be a good idea to wait for the next minor release at the very least.
Previously, the behavior was to warn users that a cask was already installed and then skip modifying the installed version. This is different to how we handled things with formulas. For them we would upgrade any already installed formulas. This just brings casks in line with what we already do with formulas.
Changes:
- cmd/install: Upgrade already installed casks if HOMEBREW_NO_INSTALL_UPGRADE is not set
- env_config: Update wording of HOMEBREW_NO_INSTALL_UPGRADE to include casks
- remove error that was only used to alert about already installed casks
Note:
- The upgrade command for casks defaults to --greedy when you pass named casks to the command which means …
=> cmd/install: upgrade already installed casks

Library/Homebrew/cask/url.rb
=> cask/url: accept `Class` for `using`.

Library/Homebrew/formula.rb
---
From https://github.com/Homebrew/homebrew-core/pull/137583, `nushell` passes a Pathname for `path`
=> formula: fix `std_cargo_args` type error

.github/workflows/build-pkg.yml, package/scripts/postinstall
Continuing with the goals of making the installer:
- more useful
- entirely offline
Let's pre-download the API data from a `brew update` run and install it into the logged-in user's home directory.
While we're here, in the `postinstall` script:
- use longer arguments for various commands
- fix an issue with symlinking on Intel if `/usr/local/bin` doesn't already exist
- unset `bash -x` and use `-v` on more commands instead
=> pkg installer: install cached API data.

Library/Homebrew/brew.sh, docs/Installation.md
My understanding from conversations with Bo98 is that this should now work fine on both older macOS versions and non-default prefixes.
Similarly, it's super confusing when this is set automatically and you can't figure out why...
=> brew.sh: don't set `HOMEBREW_NO_INSTALL_FROM_API` automatically.

Library/Homebrew/utils/analytics.rb
I noticed this was not working for versioned formulae.
=> analytics: fix `@` in formulae names with `--github-packages-downloads`

Library/Homebrew/brew.sh, Library/Homebrew/cmd/update-report.rb, Library/Homebrew/env_config.rb
When we're automatically setting `HOMEBREW_NO_INSTALL_FROM_API` when on an old macOS version or with a non-default prefix (e.g. cases where you're going to be mostly building from source).
My initial plan was to set `HOMEBREW_AUTOMATICALLY_SET_NO_INSTALL_FROM_API` in these cases but it's used differently enough it made sense to add another internal variable instead: `HOMEBREW_INSTALL_FROM_API_UNSUPPORTED`.
At the moment this is only used to avoid printing the "You have set `HOMEBREW_NO_INSTALL_FROM_API`" message inside `brew update` but may make sense to use in other places over time.
Ideally, we'll get rid of these automatic sets of `HOMEBREW_NO_INSTALL_FROM_API` and perhaps even the variable entirely.
=> Add/use `HOMEBREW_INSTALL_FROM_API_UNSUPPORTED`

Library/Homebrew/os/mac/mach.rb
-----
We can add a small amount of logic to `#resolve_variable_name` that will
allow us to perform (limited) resolution of rpath references. This is
for informational purposes only: failing to resolve an `@rpath`
reference will not (and should not) result in `brew linkage` failures.
`dyld` will typically have more information than we do to resolve these
references, so not failing `brew linkage` when we fail to resolve an
`@rpath` reference is the right behaviour here.
As an example, before:
❯ brew linkage jpeg-turbo
System libraries:
/usr/lib/libSystem.B.dylib
@rpath-referenced libraries:
@rpath/libjpeg.8.dylib
@rpath/libturbojpeg.0.dylib
After:
❯ brew linkage jpeg-turbo
System libraries:
/usr/lib/libSystem.B.dylib
Homebrew libraries:
/usr/local/Cellar/jpeg-turbo/3.0.0/lib/libjpeg.8.dylib …
=> os/mac/mach: resolve rpaths too

Library/Homebrew/cmd/update.sh
Also, hide some spammy/unnecessary newline printing.
=> cmd/update: output more API information with `--verbose`.

Library/Homebrew/github_packages.rb, Library/Homebrew/keg_relocate.rb
This was wildly inflating our image indexes.
Also add an abort before upload if the image index is >= 4MB (assuming 1024 * 1024 bytes = MB here).
=> keg_relocate: fix all text files being marked as changed

Library/Homebrew/brew.sh, Library/Homebrew/cmd/update.sh
The existing logic in `update.sh` was both a bit hard to follow and had some edge cases. Fix this up for improving #15775.
=> `brew update` core/homebrew-cask taps properly

Library/Homebrew/brew.sh, Library/Homebrew/cmd/postinstall.rb, Library/Homebrew/commands.rb, Library/Homebrew/formula_installer.rb, completions/bash/brew, completions/fish/brew.fish, completions/internal_commands_list.txt, completions/zsh/_brew, docs/Manpage.md, manpages/brew.1
- warn if running `brew postinstall` explicitly and there's no `post_install` defined in the formula
- add a `post_install` alias for `brew postinstall` to make life easier for those jumping between `postinstall` and `post_install` in e.g. Homebrew development
- refactor `post_install` formula path logic into a new method for improved readability
- handle the JSON API `post_install` formula path case
Fixes https://github.com/Homebrew/brew/issues/15775
=> post_install: improvements and fixes.

docs/Brew-Livecheck.md
-----
The `strategy` block example for `GithubReleases` in the `brew livecheck` documentation should be using `release` inside the `#map` block. I accidentally overlooked one instance of `json` when adapting the code from the `GithubLatest` example above it, so this PR addresses the issue.
=> docs: Fix GithubReleases strategy block example

Library/Homebrew/os/linux.rb
In Linux systems where lsb_release is not available by default, `brew config` now falls back to `PRETTY_NAME` (`HOMEBREW_OS_VERSION`).
Before:
```console
$ brew config
HOMEBREW_VERSION: 4.1.2-30-gc346a5c
ORIGIN: https://github.com/Homebrew/brew
HEAD: c346a5c97adef16fcc439b53cc6e757b64b71cb4
Last commit: 14 hours ago
Core tap JSON: 29 Jul 04:16 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_EVAL_ALL: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: quad-core 64-bit skylake
Clang: N/A
Git: 2.41.0 => /bin/git
Curl: 8.2.1 => /bin/curl
Kernel: Linux 6.4.4-200.fc38.x86_64 x86_64 GNU/Linux
OS: Unknown
Host glibc: …
```
=> config: fallback to ::OS_VERSION

Library/Homebrew/language/python.rb, Library/Homebrew/test/language/python/virtualenv_spec.rb
---
Currently, `virtualenv_install_with_resources` creates a venv with a full copy of `pip`. This is pretty wasteful, since we really only need it at build time to install resources. Instead, we can:
1. Create a venv using [`--without-pip`](https://docs.python.org/3/library/venv.html#creating-virtual-environments)
2. Use `python@x.y`'s `pip` to install resources into this venv, using the [`--python` option](https://pip.pypa.io/en/stable/topics/python-option/#managing-a-different-python-interpreter)
3. Tangentially, remove all shell `activate` scripts (which admittedly doesn't save much but aren't necessary)
As a result, this saves ~7MB of disk space per venv:
```console
$ brew install black
...
==> Summary
🍺  /opt/homebrew/Cellar/black/23.7.0_1: 1,121 files, 13.5MB
$ brew reinstall -s …
```
=> python: create venv's `--without-pip`

.github/workflows/build-pkg.yml
Now that we're nuking and reinstalling Homebrew: need to install this too.
=> workflows/build-pkg: install `gh`.

Library/Homebrew/dev-cmd/livecheck.rb, Library/Homebrew/env_config.rb, Library/Homebrew/manpages/brew.1.md.erb, bin/brew, docs/Manpage.md, manpages/brew.1
For a long time people have requested some sort of configuration files for Homebrew. Now: here's the first version of that.
Similarly to how you can configure Git for a system, a repository or a user: you can configure Homebrew for a system, a prefix or a user.
The system-wide configuration file is `/etc/homebrew/brew.env`, the prefix-specific configuration file is `$HOMEBREW_PREFIX/etc/homebrew/brew.env` and the user-specific configuration file is `~/.homebrew/brew.env`.
As we need to read these files from Bash in `bin/brew` (so they can) influence functionality ASAP: they are in a simple format that Bash can read. It may be that we have more complex array or hash data in future that's configured through JSON or YAML (most likely JSON as we use it more) and stored in a …
=> Allow configuring Homebrew with `.env` files

Library/Homebrew/cmd/postgresql-upgrade-database.rb, docs/Manpage.md, manpages/brew.1
This is an out-of-band deprecation but this command is broken and we're not going to fix it so it's not really worth a deprecation cycle.
See https://github.com/orgs/Homebrew/discussions/4685 and https://github.com/Homebrew/homebrew-core/pull/138201
=> Deprecate `postgresql-upgrade-database`

Library/Homebrew/formula.rb, Library/Homebrew/utils/inreplace.rb
-----
As suggested in https://github.com/Homebrew/brew/pull/15796#discussion_r1280051286
cc @carlocab @MikeMcQuaid
=> Narrow member type of inreplace paths enumerable

Library/Homebrew/cask/cask_loader.rb, Library/Homebrew/cli/named_args.rb, Library/Homebrew/dev-cmd/edit.rb, Library/Homebrew/exceptions.rb, Library/Homebrew/formulary.rb, Library/Homebrew/test/exceptions_spec.rb, completions/bash/brew, completions/fish/brew.fish, completions/zsh/_brew, docs/Manpage.md, manpages/brew.1
-----
Addresses the issue brought up in #15664 by suggesting homebrew/core or homebrew/cask be tapped when attempting to edit a formula or cask and either repo is untapped. Also expands `edit`'s handling of tap arguments and fixes a few other related bugs.
=> dev-cmd/edit: suggest tapping core repositories if untapped

Library/Homebrew/extend/kernel.rb, Library/Homebrew/utils/repology.rb
The [Repology API](https://repology.org/api) has changed since our original implementation, but since it's been redirecting it hasn't been an issue for us until #15804 noted that packages like `bonnie++` weren't being checked by `brew bump`. With the original API scheme the fix would be to [URL-encode the plus sign characters](https://repology.org/tools/project-by?repo=homebrew&name_type=srcname&target_page=api_v1_project&name=bonnie%2B%2B), but simply updating the URL fixed it as well. 
(The current API unfortunately doesn't have the option of returning just the results for a single package in a single repository, so we've been wading through the results of every repository a given package is in, which has been slowing down the command considerably.)
```
$ brew bump --no-pull-requests …
```
=> utils/repology: update API URL

Library/Homebrew/cask/migrator.rb, Library/Homebrew/formula.rb, Library/Homebrew/utils/inreplace.rb, Library/Homebrew/utils/inreplace.rbi
-----
Small follow-up to https://github.com/Homebrew/brew/pull/15800 where I noticed `Formula` added `Utils::Inreplace` to its ancestor chain, but only referenced the namespace in one place. I think it's better to directly call the method there (line 2565):
- Humans/Sorbet can better identify the source of the `super` method
- Formula ancestor chain is simplified
- We can remove an `.rbi` file
- The `inreplace` api is more clear and consistent (`module_function`s make it unclear whether a namespace should be included or invoked statically)
=> Make `inreplace` a purely static method

package/Distribution.xml
We always require it in `install.sh` and we need it for all but the latest version of macOS so this seems a simpler compromise.
Fixes #15802
=> package/Distribution: always require CLT.

Library/Homebrew/cask/migrator.rb, Library/Homebrew/formula.rb, Library/Homebrew/utils/inreplace.rb, Library/Homebrew/utils/inreplace.rbi
`inreplace` with block doesn't work.
See https://github.com/Homebrew/brew/pull/15807#issuecomment-1664172239 and https://github.com/Homebrew/brew/pull/15807#issuecomment-1664196619
And an example of failure in homebrew-core: https://github.com/Homebrew/homebrew-core/pull/138421
Reverts Homebrew/brew#15807
=> Revert "Make `inreplace` a purely static method"

Library/Homebrew/development_tools.rb, Library/Homebrew/extend/os/linux/development_tools.rb, Library/Homebrew/extend/os/mac/development_tools.rb
-----
Fixes error seen in Homebrew/homebrew-core#138452 ([formula](https://github.com/Homebrew/homebrew-core/blob/32b17878c7f64bacfbc3153a2495594378f6afae/Formula/mbedtls.rb#L47)). `DevelopmentTools.default_compiler` can return a `Symbol` like `:clang`. Make sure its result can be fed to `DevelopmentTools.locate`.
=> development_tools: allow `Symbol`s to be `locate`d

Library/Homebrew/dev-cmd/bump.rb
-----
This is the `bump`-specific part of #15611 and a continuation of #15725. 
The bump command has been refactored to include architecture-specific livechecks. By simulating different architectures, bump now returns architecture-specific results in a unified structure. This structure is leveraged in the retrieve_and_display_info_and_open_pr method to display livecheck results and pass updated versions to bump-cask-pr.
In addition, an issue with handling duplicate PRs has been addressed. Previously, bump returned Duplicate PRs should not be opened. Use --force to override this error. when duplicate PRs were identified. This wasn't actually implemented. The bump command now passes the --force switch to brew-#{type}-pr when appropriate.
While primarily focusing on the bump command, these …
=> bump: add arch-specific support

Library/Homebrew/formulary.rb
-----
`Formulary.from_rack` [only allows `alias_path` to be a `Pathname`](https://github.com/Homebrew/brew/blob/d2863d05b33177626e66fd4be75e92bcc3f14c99/Library/Homebrew/formulary.rb#L782). Make it happy with `String`s too.
Fixes:
$ brew test openssl
Error: Parameter 'alias_path': Expected type Pathname, got type String with value "/usr/local/Homebrew/Librar...homebrew-core/Aliases/openssl"
Caller: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:113
Definition: /usr/local/Homebrew/Library/Homebrew/formulary.rb:787
=> formulary: fix type of `alias_path`

bin/brew
Try to build it using `$USER` or `$LOGNAME` and, if both are missing, just give up.
See https://github.com/Homebrew/brew/pull/15787#issuecomment-1664180839
=> bin/brew: handle missing `$HOME`.

Library/Homebrew/formula_cellar_checks.rb, Library/Homebrew/upgrade.rb
Combined with https://github.com/Homebrew/homebrew-test-bot/pull/963 this should make `brew test-bot` output a bit quieter and less annoying.
=> Make more warnings quiet with environment hints disabled.

bin/brew
-----
`eval` is a much bigger hammer than we need here, so let's try to avoid
that.
Also, we can use the builtin `read` instead of shelling out to `grep`
which will be slightly more efficient.
=> bin/brew: avoid `eval` and `grep`

Library/Homebrew/cask/audit.rb, Library/Homebrew/cask/cask_loader.rb, Library/Homebrew/cli/named_args.rb, Library/Homebrew/cmd/log.rb, Library/Homebrew/dev-cmd/create.rb, Library/Homebrew/dev-cmd/extract.rb, Library/Homebrew/dev-cmd/pr-pull.rb, Library/Homebrew/formula_creator.rb, Library/Homebrew/formula_path.sh, Library/Homebrew/formulary.rb, Library/Homebrew/readall.rb, Library/Homebrew/tap.rb, Library/Homebrew/test/cleanup_spec.rb, Library/Homebrew/test/dev-cmd/create_spec.rb, Library/Homebrew/test/formula_installer_spec.rb, Library/Homebrew/test/formula_spec.rb, Library/Homebrew/test/formulary_spec.rb, Library/Homebrew/test/support/helper/spec/shared_examples/formulae_exist.rb
- Load paths with no API when needed (e.g. for `brew edit`)
- Use no API mode for `brew log` as it's needed there
- Define sharding format for homebrew-cask and homebrew-core inside `Tap` methods
- Create new formulae/casks in location defined by these `Tap` methods
- Fix a bug in Formulary that made sharded formulae lookup less efficient (and possibly broke it for core and some API usage)
- Fix various other hardcoded Formula/Cask directory assumptions
See also https://github.com/Homebrew/homebrew-core/pull/138414
=> Various sharding fixes

Library/Homebrew/dev-cmd/bump.rb
-----
Fixes #15825
Even though the command already sets without_api that only affects how named args are loaded. In this command, we used to load many formulae and casks all at once using the API according to user settings. Now we just mandate that all loading must skip the API.
This is kind of a brute force sort of fix. Ideally, we wouldn't be wrapping so much code with the `Homebrew.with_no_api_env` block but otherwise I think we'd just be doing it in a loop which is probably worse.
=> dev-cmd/bump : stop using API to load formulae/casks

Library/Homebrew/unversioned_cask_checker.rb
-----
The signature is wrong for `Cask::Artifact::KeyboardLayout`:
Reference:
- in PR #15061 this was introduced as a wrong signature
=> unversioned_cask_checker.rb - fix signature of KeyboardLayout

Library/Homebrew/utils/pypi.rb
---
This teaches `brew update-python-resources` how to handle a formula with a git url, like [`arcade-learning-environment`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/arcade-learning-environment.rb).
Before:
```console
$ brew update-python-resources arcade-learning-environment
Error: Unable to determine metadata for "https://github.com/mgbellemare/Arcade-Learning-Environment.git" because of a failure when running
`/opt/homebrew/opt/python@3.11/bin/python3 -m pip install -q --no-deps --dry-run --ignore-installed --report /dev/stdout https://github.com/mgbellemare/Arcade-Learning-Environment.git`.
```
After:
```console
$ brew update-python-resources arcade-learning-environment
==> Retrieving PyPI dependencies …
```
=> pypi: support updating resources for git clones

Library/Homebrew/formula.rb
---
`pip` defaults to compiling bytecode for packages. But since we already [remove these when bottling](https://github.com/Homebrew/brew/blob/3eb48a828d44643b8d427f647227a277b1a4c1bf/Library/Homebrew/keg.rb#L528), let's add [`--no-compile`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-compile) to stop pip from creating these in the first place. This is also theoretically faster, but at least on my machine not too significant. For example, `brew install -s black` is 2s faster (41s before, 39s after).
Similiar motivation as https://github.com/Homebrew/brew/pull/14338, but pip doesn't respect `PYTHONDONTWRITEBYTECODE` by explicitly using [`compileall`](https://github.com/pypa/pip/blob/a19ade74a5cebbe73e8ab6e88f4123e0e2e54c06/src/pip/_internal/operations/install/wheel.py#L617)
=> formula: use pip's `--no-compile`

Library/Homebrew/extend/os/mac/keg_relocate.rb
-----
`dyld` uses the target library's install name to work out whether this
is a Framework or a dylib, which affects how `dyld` searches for the
desired library.
We should therefore avoid confusing `dyld` by including the
`*.framework` part of the install name in the target dylib, which is
what this change does.
Here's a concrete example of what this changes. Before:
❯ otool -L /usr/local/bin/python3
/usr/local/bin/python3:
@loader_path/../Python (compatibility version 3.11.0, current version 3.11.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
After:
❯ otool -L /usr/local/bin/python3
/usr/local/bin/python3:
@loader_path/../../../../Python.framework/Versions/3.11/Python (compatibility version 3.11.0, current version 3.11.0) …
=> keg_relocate: retain framework info in relocatable install names

Library/Homebrew/cmd/update-report.rb, Library/Homebrew/env_config.rb, Library/Homebrew/env_config.rbi
-----
This information is mostly noise, so added an env var to allow to silence it
closes https://github.com/orgs/Homebrew/discussions/4590
=> Allow hiding new/deleted formula/cask sections on update

docs/Formula-Cookbook.md
As suggested in https://github.com/Homebrew/brew/pull/15831#pullrequestreview-1564422381, this reorganizes how download strategies are documented for better clarity.
=> Formula Cookbook: revise download strategy docs

Library/Homebrew/cmd/update-report.rb
Clarify that the deleted formulae/casks when not using `report_all` are only those that have been deleted _and_ the user has them installed. This should avoid users glossing over this information as it is pretty relevant to them.
While we're here, refactor some of the `report_all` logic to make it easier to remove it all on the next Homebrew major/minor version.
Requesting Homebrew/brew review because want someone to check over my binary logic as I regularly fail at doing it right 😅
=> update_report: show "Delete and Installed" header.

Library/Homebrew/tap.rb
After https://github.com/Homebrew/homebrew-cask/pull/152603 is merged, for homebrew-cask, all casks should now be created in subdirectories, even if that subdirectory doesn't yet exist.
=> tap: always create new casks in subdirectory.

Library/Homebrew/rubocops/extend/formula_cop.rb
This needed to be adjusted to handle a sharded homebrew/core and repositories with formulae in the root.
=> formula_cop: fix `style_exceptions_dir` handling.

Library/Homebrew/cask/audit.rb
-----
This PR adds an audit to ensure casks are in the appropriate subdirectory.
Should help address the issue raised in https://github.com/Homebrew/homebrew-cask/pull/152603
=> cask/audit: audit for appropriate sharding directory

Library/Homebrew/cask/info.rb, Library/Homebrew/cmd/info.rb, Library/Homebrew/tap.rb, Library/Homebrew/test/cask/audit_spec.rb, Library/Homebrew/test/cask/cask_spec.rb, Library/Homebrew/test/cask/info_spec.rb, Library/Homebrew/test/cask/upgrade_spec.rb, Library/Homebrew/test/livecheck/strategy/extract_plist_spec.rb, Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-discontinued-reference.rb, Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-discontinued.rb, Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-installer-manual.rb, Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-url-unversioned-reference.rb, Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-url-unversioned.rb, Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-version-latest-reference.rb, Library/Homebrew/test/support/fixtures/cask/Casks/livecheck/livecheck-version-latest.rb, Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
- Fix cask info output being incorrect
- Improve some code referring to casks as formulae
- Move livecheck cask fixtures to not shadow existing names
- Adjust the cask tap symlinking logic to make handling outdated shadowed casks significantly easier
- Fix various flaky tests caused by casks sharding logic
- Prefer longer paths when there's multiple formulae or casks in a tap with the same name rather than always using the first
Marking as `critical` as almost all Homebrew/brew CI runs are failing most of the time without this.
=> Fix cask sharding issues

Library/Homebrew/manpages/brew.1.md.erb, docs/Formula-Cookbook.md, docs/Manpage.md, manpages/brew.1
Expand the Cookbook's terminology table to mostly match the one from the manpage, and sync their definitions.
=> Formula-Cookbook: expand terminology table

Library/Homebrew/cmd/update-report.rb
If a formulae or cask is marked as both added and deleted, we've just incorrectly detected it. Remove it from the report.
This can happen when a formula or cask is moved around in the repository e.g. with sharding.
Partial solution for https://github.com/Homebrew/brew/issues/15856
=> cmd/update-report: correctly handle added/deleted formulae/casks.

Library/Homebrew/formula_auditor.rb, Library/Homebrew/formula_versions.rb
Ensure that `FormulaVersions` correctly also looks at older paths for sharded formulae.
While we're here, also cleanup `FormulaVersions` a bit to have more signatures, cleanup dead code, make more code private, improve variable naming.
Partial solution for https://github.com/Homebrew/brew/issues/15856
=> formula_{auditor,versions}: handle sharding.

Library/Homebrew/formula_installer.rb
Had just about enough energy to get this one done tonight too.
We detect whether we want an API formula or need a Ruby source formula fairly late on (after the formula installer has been first created), so we swap the formula instance within the installer.
Unfortunately, dependencies use separate instances of the installer for their fetch and install stages so we can't rely on the `fetch` method being called like we could normally. The dependency handling should probably be refactored to not create separate instances like that as it'll eliminate these type of bugs occurring in the future (or we alternatively commit to separate fetcher and installer classes), as well as help tackle the growingly fragile amount of assumptions FormulaInstaller currently has on the way it is called (e.g. some …
=> formula_installer: use cached fetched formula instance when available

Library/Homebrew/language/node.rb, Library/Homebrew/language/node.rbi, Library/Homebrew/language/perl.rb, Library/Homebrew/language/python.rb, Library/Homebrew/test/language/node/shebang_spec.rb, Library/Homebrew/test/language/perl/shebang_spec.rb, Library/Homebrew/test/language/python/shebang_spec.rb
-----
Formulae that depend on `node` sometimes contain files that use a shebang like `#!/usr/bin/env node` and this can lead to issues when the `node` in a user's environment isn't brewed `node`.
For example, some node modules are compiled when the formula is built but if the user's `node` is a different major version than brew's `node`, the differing `NODE_MODULE_VERSION` can produce an error when certain parts of the application are used. The formula may build and test fine and the issue may only become apparent when more of the application is exercised (e.g., https://github.com/Homebrew/homebrew-core/pull/139389).
This adds a `Language::Node::Shebang` module, which allows us to use `rewrite_shebang detected_node_shebang, ...` in formulae to address this type of issue. I borrowed from …
=> node: add shebang rewriting

Library/Homebrew/env_config.rb, Library/Homebrew/env_config.rbi, Library/Homebrew/test/utils/curl_spec.rb, Library/Homebrew/utils/curl.rb, docs/Manpage.md, manpages/brew.1
-----
We're using a custom `HOMEBREW_ARTIFACT_DOMAIN` that requires some additional flags in `.curlrc`. We would like to set `HOMEBREW_CURLRC` and the value for `CURL_HOME` in `/etc/homebrew/brew.env` to support this without relying on the user's `.curlrc`.
=> Allow HOMEBREW_CURLRC to specify a path for curl `--config`

Library/Homebrew/formula_installer.rb
Based on https://github.com/Homebrew/brew/pull/15778#discussion_r1294477218
=> formula_installer: improve a comment.

docs/Acceptable-Formulae.md
=> Document the policy on static libraries

Library/Homebrew/Gemfile.lock, Library/Homebrew/utils/gems.rb, Library/Homebrew/vendor/bundle/bundler/setup.rb
With a new dependency resolver that might work a bit better for some edge cases.
We're reaching the limit of what is supported under Ruby 2.6 here too, as we now need a `BUNDLER_NO_OLD_RUBYGEMS_WARNING` to avoid warning spam. Support for Ruby 2.6 could be dropped as soon as the end of this year.
=> utils/gems: update to Bundler 2.4

Library/Homebrew/livecheck/livecheck.rb
-----
Checking multiple formulae/casks with livecheck becomes incredibly noisy when using `--newer-only`. This PR allows us to silence the `"No newer upstream versions."` output by passing `--quiet`.
=> Livecheck: allow quiet output with `--newer-only`

Library/Homebrew/service.rb
If you have a run argument with a space in it: it will need to be quoted to be passed through correctly when run as a manual command.
Will allow removing manual quoting differences e.g. in https://github.com/Homebrew/homebrew-core/blob/66ebc5d0f0c0df80d96e901b94d4bcf5bc900534/Formula/n/nginx.rb#L149-L153
Fixes #15871.
=> service: correctly quote arguments.

Library/Homebrew/cmd/update-report.rb
- unify core tapping/untapping behaviour (so we can never tap and then immediately untap)
- automatically untap homebrew-core or homebrew-cask if it's old, on the default branch and it doesn't seem to be needed
- if we think it's unneeded but it's too new: output a message instead
=> cmd/update-report: improve tap/untap behaviour.

Library/Homebrew/test/dev-cmd/livecheck_spec.rb
-----
The existing watchlist test in `test/dev-cmd/livecheck_spec.rb` will only pass if the testing environment doesn't contain a livecheck watchlist file. When a watchlist file is present, it ends up being treated as empty (formulae and casks aren't available in tests) and produces an `Invalid usage: No formulae or casks to check` error instead. We don't have to worry about a watchlist file on CI but it's a potential issue when running `brew test` locally.
This provides a bogus `HOMEBREW_LIVECHECK_WATCHLIST` value to the `#brew` call, to ensure that any watchlist file in the testing environment is not used for this test.
-----
For what it's worth, the test used to pass even if there was a watchlist file when the default location was `~/.brew_livecheck_watchlist`. This is because the home …
=> dev-cmd/livecheck: avoid watchlist in test

Library/Homebrew/utils/topological_hash.rb
-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/152726.
This is an issue that affects only casks that have a `depends_on formula` clause, and only when that formula has uninstalled test dependencies somewhere in its tree. In this situation, `brew` when installing the cask will also install the test dependencies, even though they are not needed. Not many casks have a `depends_on formula` clause, so I don't expect the issue to be very common; so far I've seen this issue when installing the casks `neovide` and `goneovim`.
I did a search for the function this commit modifies, and it seems to only be used in `upgrade.rb` and `cask/installer.rb`, which would explain why the issue was observed only when installing casks and not formulae. I tested `brew reinstall --cask neovide` with …
=> Fix cask dependency discovery

Library/Homebrew/rubocops/text.rb
-----
See https://github.com/Homebrew/homebrew-core/pull/139793
=> audit: check for cargo build only in install method

Library/Homebrew/dev-cmd/bottle.rb
This allows the correct bottling of `gnu-tar` dependencies (and `gnu-tar` itself). It also installs `gnu-tar` at a more appropriate time in the `brew bottle` command.
Needed for https://github.com/Homebrew/homebrew-core/pull/139661
=> dev-cmd/bottle: install gnu-tar before keg lock.

Library/Homebrew/dev-cmd/prof.rb
This adjusts `brew prof` to pass `setup_path: false` to `Homebrew.install_bundler_gems!` so that all of the `BUNDLE_` environment variables don't leak to the subprocess, which can have an impact on how it runs, in particular with external taps using a different set of gems (e.g. `Homebrew/formula-analytics`).
=> dev-cmd/prof: bleed less of the environment from gem installs

Library/Homebrew/api.rb
-----
A side effect of API installs being enabled on older macOS versions is that the JSON files are downloaded by the initial `brew update` when it attempts to `brew install ca-certificates`, which itself requires updated certificates. Adding `--insecure` to the curl call just in this instance avoids "curl: (60) SSL certificate problem: certificate has expired" when downloading https://formulae.brew.sh/api/formula.jws.json for the first time.
=> api: ignore HTTPS errors if required certs aren't installed

Library/Homebrew/cmd/vendor-install.sh
-----
Following https://github.com/Homebrew/brew/pull/15853, there is another place we call `curl` that can also make use of `HOMEBREW_CURLRC` to set `--config`. `HOMEBREW_ARTIFACT_DOMAIN` is used in line 48 here, so the change in `Utils::Curl` didn't have any effect.
I missed this because I didn't test installing Homebrew from scratch with this set 😅
=> Use HOMEBREW_CURLRC in vendor-install

.github/workflows/tests.yml
As-is there's a Python installed but not properly linked which breaks anything that depends on Python being installed on macOS e.g. Subversion.
=> workflows/tests: workaround GitHub Actions python issues.

Library/Homebrew/formula.rb
---
This was made the default behavior in [pip 23.1](https://github.com/pypa/pip/commit/fded808c8cab13e9fef65f3ac8256ec37a27d743#diff-eac56dce076aa027ef42fa51826df01e1b996d4e374d6c572c83af9fe4b13895R999), which all our pythons now ship.
=> formula: drop old pip feature flag

Library/Homebrew/utils/shared_audits.rb
-----
For some formulae during the homepage audit, we're getting an error: 
```
Error: GitHub API Error: Although you appear to have the correct authorization credentials, the `<org-name>` organization has an IP allow list enabled, and your IP address is not permitted to access this resource.
``` 
Ref https://github.com/Homebrew/homebrew-core/pull/140255#issuecomment-1689812120
This PR ignores this error in `SharedAudits` (while getting information about repo via API).
=> shared_audits: allow GitHub's IP not permitted error

Library/Homebrew/utils/github.rb, Library/Homebrew/utils/github/api.rb, Library/Homebrew/utils/shared_audits.rb
-----
Continuation of https://github.com/Homebrew/brew/pull/15909:
- Catch `AuthenticationFailedError` in `get_repo_license` as well.
Tested it by adding to `def self.open_rest`
```ruby
raise AuthenticationFailedError.new(
:env_token,
"Although you appear to have the correct authorization credentials, the `Shopify` organization has an IP allow list enabled, and your IP address is not permitted to access this resource.",
)
```
and running `brew audit --online --new-formula toxiproxy` (from https://github.com/Homebrew/homebrew-core/pull/140255)
=> get_repo_license: allow GitHub's IP not permitted error

Library/Homebrew/extend/os/mac/keg.rb
-----
Attempt at fixing issue mentioned in https://github.com/Homebrew/homebrew-core/issues/140244.
Due to enabling `HOMEBREW_RELOCATABLE_INSTALL_NAMES=1`, RPATH modifications are invalidating code signatures added by upstream installation script.
Possible change here to `codesign` if we detect invalid signature on Intel binary. Alternative could be on formula-by-formula basis, though harder to catch problems before distribution to users.
Snippet of debug output on `qemu`:
```
==> Changing install name in /usr/local/Cellar/qemu/8.1.0/bin/elf2dmp
from /usr/local/opt/glib/lib/libglib-2.0.0.dylib
to @loader_path/../../../../opt/glib/lib/libglib-2.0.0.dylib
/usr/bin/env codesign --verify /usr/local/Cellar/qemu/8.1.0/bin/elf2dmp
==> Changing install name in …
```
=> extend/os/mac/keg: codesign on Intel if invalid signature

docs/Brew-Test-Bot.md, docs/Homebrew-on-Linux.md
Follow-up to Homebrew/brew.sh#980, fixes Homebrew/brew.sh#981.
=> docs: use relative path for custom header images

Library/Homebrew/extend/os/linux/system_config.rb
-----
I noticed that some issue reports showed `N/A` for `glibc/etc` even though Homebrew should have installed them.
Locally tried it out on Ubuntu 20.04 container and saw similar behavior, which seems due to API usage, e.g.
```
OS: Ubuntu 20.04.6 LTS
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```
```
$ brew info glibc | grep Poured
Poured from bottle using the formulae.brew.sh API on 2023-08-27 at 04:44:30
```
I think the original goal of conditional was to avoid auto-tapping `homebrew/core`, which I guess is only an issue now when API is disabled. May need confirmation that API logic will do what is expected.
Output with change:
```
OS: Ubuntu 20.04.6 LTS
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: N/A
glibc: 2.35_1
gcc@11: …
```
=> extend/os/linux/system_config: show glibc/gcc version for API users

Library/Homebrew/dependency.rb, Library/Homebrew/dependency_collector.rb
-----
`uses_from_macos` dependencies need to indicate their OS bounds when being cached. Fixes #15907. 
```
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew info gitless glib --json | jq '.[].uses_from_macos_bounds'
[
{}
]
[
{
"since": "catalina"
},
{
"since": "catalina"
}
]
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew info glib gitless --json | jq '.[].uses_from_macos_bounds'
[
{
"since": "catalina"
},
{
"since": "catalina"
}
]
[
{}
]
```
=> dependency_collector: distinguish macOS deps by OS

Library/Homebrew/dev-cmd/contributions.rb, Library/Homebrew/test/utils/github_spec.rb, Library/Homebrew/utils/github.rb, Library/Homebrew/utils/github/api.rb, completions/fish/brew.fish, completions/zsh/_brew, docs/Manpage.md, manpages/brew.1
- more sensible/performant defaults: default to primary repositories only for the last year rather than all repositories forever
- allow specifying more than one user at a time
- output the breakdown of contributions without needing `--csv`
- add a space before the `--csv` output
- consolidate some code
- avoid counting authored commits twice, to improve performance
- retry failed GitHub API calls (this happens often when querying all maintainers)
- stop counting after we find 1000 commits for a given user to avoid excessive API queries/pagination
This was required for me to successfully generate contributions for all active maintainers without error and in a reasonably timely fashion.
=> dev-cmd/contributions: usability/performance improvements.

.github/workflows/docs.yml, docs/Adding-Software-to-Homebrew.md, docs/Formula-Cookbook.md, docs/How-To-Organize-AGM.md, docs/Installation.md, docs/Python-for-Formula-Authors.md, docs/Rakefile
-----
- We had `rake test` as a task that uses `html-proofer` to scan for broken links, but we never actually ran it in CI or anywhere before building the site.
- This will make things slower (or maybe it's taking ages because of my dodgy hotel internet connection), maybe we should only run it on a schedule as a separate job?
- Fixes https://github.com/Homebrew/brew/issues/15908.
=> workflows/docs: Check for broken links using the existing `rake test` task

Library/Homebrew/cmd/deps.rb, Library/Homebrew/cmd/info.rb, Library/Homebrew/cmd/options.rb, Library/Homebrew/cmd/uses.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/dev-cmd/livecheck.rb, Library/Homebrew/dev-cmd/unbottled.rb, Library/Homebrew/formula.rb
-----
remove ARGV from Foumula because of `#TODO` https://github.com/Homebrew/brew/blob/de50e8418458fbb547fac2ecdbeaa6d4898c0835/Library/Homebrew/formula.rb#L1949
=> remove `ARGV` from `Formula#all`

Library/Homebrew/brew.sh, Library/Homebrew/dependency_collector.rb, Library/Homebrew/resource.rb, Library/Homebrew/service.rb, Library/Homebrew/version.rb
We have no commands with Sorbet disabled and have had Sorbet enabled for developers for a decent amount of time. As a result, we can enable it for everyone who has run a developer command.
This also allows a bunch of `raise TypeError`s to be removed in favour of relying on Sorbet here instead.
=> Enable Sorbet after running a developer command

Library/Homebrew/extend/os/mac/hardware.rb
As discussed in comments, this TODO can pretty much never be done so doesn't make sense to leave as-is.
=> os/mac/hardware: remove TODO.

Library/Homebrew/formula_auditor.rb
Otherwise we have to run this separately in `brew test-bot` which is slower and more confusing.
=> formula_auditor: make Linux-only GCC dep audit non-strict.

Library/Homebrew/cask/cask_loader.rb, Library/Homebrew/cask/download.rb, Library/Homebrew/cask/installer.rb, Library/Homebrew/cmd/fetch.rb
-----
The goal here is to handle the case where a cask might have a nil url stanza because that cask is not available on the current version of macOS or the given architecture. This just moves those checks from the end of the `Cask::Installer#fetch` method to the beginning so that we don't try and download casks that are missing urls. A similar change was also applied to the `brew fetch` command.
This will now provide a helpful error message like so:
```
Error: This software does not run on macOS versions older than Big Sur.
```
Beyond that it no longer tries to run the url stanza with a nil value when loading casks from the API.
=> Handle nil cask urls caused by unsupported macOS version

Library/Homebrew/api.rb, Library/Homebrew/utils/curl.rb
This sets user-agent nicely and avoids some duplication.
=> api: use `Utils::Curl.curl_args`

Library/Homebrew/dependency.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/upgrade.rb
When we're installing a formula from a bottle, we currently always upgrade all dependencies in the dependency tree to be safe.
However, if we're installing a bottle and the `runtime_dependencies` within that bottle's tab all have older or equal versions to those already installed: we do not need to upgrade these dependencies.
This should help a lot of upgrading a lot of the time, at least for users using bottles (which is the huge majority).
The only downside or other noticeable change is that this requires us to download or attempt to download the bottle tab before we compute the dependencies at installation time.
=> Make formula upgrades more liberal based on bottle

Library/Homebrew/cask/url.rb
-----
---
b4feaf27d9 cask/url: accept Class for using in Cask::URL#initialize
https://github.com/Homebrew/brew/pull/15754 fixed `Cask::URL::DSL#initialize`, but we also need to fix `Cask::URL#initialize` as that takes the same parameters.
Error:
```
Error: Cask 'mycask' definition is invalid: 'url' stanza failed
with: Parameter 'using': Expected type T.nilable(Symbol), got type Class
with value MyCustomDownloadStrategy
Caller:
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:113
```
Refs: https://github.com/Homebrew/brew/issues/15750
<br/>
=> cask/url: accept Class for using in Cask::URL#initialize

Library/Homebrew/formula_installer.rb
Fix another way that fetching a bottle tab can fail. This pretty much only happens in CI.
Addresses https://github.com/Homebrew/homebrew-core/pull/141362#issuecomment-1705327027
CC @bayandin
=> formula_installer: handle another exception in fetch_bottle_tab.

Library/Homebrew/livecheck/livecheck.rb
-----
We now have a `gitea` formula in homebrew/core and its `stable` URL uses a dl.gitea.com tarball. Since the URL's domain is gitea.com, livecheck tries to preprocess the URL into a `.git` URL but the resulting URL doesn't work because it's not a Git repository (see https://github.com/Homebrew/homebrew-core/pull/141337).
Gitea repositories use gitea.com (with no subdomain), so `#preprocess_url` should be comparing the URI host (`dl.gitea.com`) instead of the domain (`gitea.com`). This change allows gitea.com repository URLs to continue to be preprocessed into a `.git` URL while dl.gitea.com URLs are left untouched.
This makes the same change for the other domains, as they don't use a subdomain either.
=> Livecheck#preprocess_url: compare with URI host

Library/Homebrew/formula_installer.rb, Library/Homebrew/upgrade.rb
Download the bottle manifests for the potential formulae we are going to upgrade and, if they are have all their `runtime_dependencies` versions currently met, don't try to download the bottle or upgrade the formula.
=> upgrade: more liberal formula upgrade changes.

Library/Homebrew/cask/cask_loader.rb, Library/Homebrew/formula_auditor.rb, Library/Homebrew/formulary.rb, Library/Homebrew/github_releases.rb, Library/Homebrew/resource_auditor.rb, Library/Homebrew/system_config.rb, Library/Homebrew/test/spec_helper.rb, Library/Homebrew/test/utils/curl_spec.rb, Library/Homebrew/utils/curl.rb, Library/Homebrew/utils/github/api.rb, Library/Homebrew/utils/pypi.rb, Library/Homebrew/utils/repology.rb, Library/Homebrew/utils/shared_audits.rb, Library/Homebrew/utils/shared_audits.rbi, Library/Homebrew/utils/spdx.rb
Include or use `Utils::Curl` explicitly everywhere it is used.
=> utils/curl: include or use explicitly.

Library/Homebrew/formula_installer.rb
Otherwise, we can try to pour bottles that haven't been downloaded yet.
Possible fix for #15957.
=> formula_installer: don't ignore deps when fetching and pouring bottles.

Library/Homebrew/github_packages.rb, Library/Homebrew/resource_auditor.rb
We have a bunch of versions we've been meaning to adjust to not use invalid GitHub Packages characters for a while. Let's audit for them and plan for deprecating their use in future.
Companion to https://github.com/Homebrew/homebrew-core/pull/141202
=> Audit invalid versions

Library/Homebrew/language/python.rb
"python@" is not a valid dependency, must include something after the "@"
-----
=> Fix python: detected_python_shebang python pattern

Library/Homebrew/cask/artifact/moved.rb, Library/Homebrew/cask/quarantine.rb
=> cask/quarantine: sudo correctly during tests.

Library/Homebrew/cask/audit.rb, Library/Homebrew/cask/download.rb, Library/Homebrew/cmd/fetch.rb, Library/Homebrew/dev-cmd/audit.rb
-----
Another follow-up to #15943 and #15956.
- check for cask.url in audit steps
- check for cask.version in audit steps
- check for cask.sha256 in fetch command
- stop omitting casks based on nil url in audit command
It would be nice to be able to omit casks from the audit if the os is not supported but there is not easy way to do that without updating the SimulateSystem code or refactoring how MacOSRequirement's are defined in the DSL.
At the end of the day, these changes make it so that you won't try to fetch a cask if the url or sha256 is missing (we'd expect the sha256 value to be `:no_check` if it's been omitted on purpose). It also allows the audit to accept casks with nil urls and versions since we already check for those. The problem was that we had some audit steps which …
=> Improve cask audit

Library/Homebrew/missing_formula.rb, Library/Homebrew/test/missing_formula_spec.rb
-----
This should allow for the creation of an `sshpass` formula in core. Fixes https://github.com/Homebrew/brew/issues/15879.
=> missing_formula: remove sshpass from denylist

Library/Homebrew/requirement.rb
-----
`brew deps <my custom tap>/<my custom formula>`
can blow up with 
```
Error: undefined method `[]=' for nil:NilClass
/opt/homebrew/Library/Homebrew/requirement.rb:242:in `expand'
/opt/homebrew/Library/Homebrew/dependencies_helpers.rb:43:in `recursive_includes'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:198:in `deps_for_dependent'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:208:in `block in deps_for_dependents'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:208:in `map'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:208:in `deps_for_dependents'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:148:in `deps'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
I can't provide a reproduction case at this moment, but the source of the …
=> Reset requirement cache (again) after `recursive_dependencies.map(&:to_formula)` invalidates singleton cache

Library/Homebrew/formula_auditor.rb
-----
Apply #15975 to all affected formulae.
=> formula_auditor: audit all relicensed HashiCorp formulae

Library/Homebrew/extend/os/linux/keg_relocate.rb, Library/Homebrew/extend/os/mac/keg_relocate.rb, Library/Homebrew/os/mac/keg.rb
-----
I noticed some formulae in the `osrf/simulation` tap starting taking much longer to install on macOS Intel processors after https://github.com/Homebrew/brew/pull/15903 was merged. That only adds a call to `codesign --verify` for files, which quickly returns for unsigned files, but this code-signing method is called within loops over every library that each installed dylib links against, so it is called many times. I noticed on my machine that the `osrf/simulation/gz-sim8` formula bottle pouring time has increased from 1 minute to over 6 minutes.
I believe that the methods in `os/mac/keg` are only called from two methods in `extend/os/mac/keg_relocate`. This pull request removes the calls to `codesign_patched_binary` from `os/mac/keg` and replaces that with individual calls to that …
=> Speed up keg installation with fewer code-signing calls

Library/Homebrew/dev-cmd/bump-cask-pr.rb
-----
This PR deprecates `brew bump-cask-pr --online` and makes online audits the default setting.
PRs created via bump-cask-pr skip full auditing. Occasionally, the bumped cask version does not match with the livecheck version leading to PRs that fail CI and clogging the PR queue until the livecheck version catches up.
Given that a --no-audit flag already exists, adding an --offline flag seems redundant. However, if there are any edge cases I'm missing, happy to discuss more.
=> bump-cask-pr: deprecate online flag

Library/Homebrew/os/mac/keg.rb
Fixes #15990
Fixes https://github.com/Homebrew/brew/issues/15993
=> os/mac/keg: fix `change_rpath` type signature.

Library/Homebrew/resource_auditor.rb, Library/Homebrew/test/dev-cmd/audit_spec.rb
-----
- Fixes #14537.
- When people manually add or modify PyPI resources the `Resource#name` sometimes ends up out-of-sync with the PyPI package name.
=> Add an audit for mismatched Python resource and PyPi package names

Library/Homebrew/utils/shared_audits.rb
=> utils/shared_audits: handle 404 metadata errors from GitLab API.

Library/Homebrew/exceptions.rb, Library/Homebrew/formula.rb, Library/Homebrew/test/exceptions_spec.rb
-----
We're seeing [type errors](https://github.com/Homebrew/homebrew-core/issues/142308) when building formulae that use something like `xcodebuild ..., "-arch", Hardware::CPU.arch`, since `CPU.arch` is a symbol. We've been addressing these issues by calling `#to_s` on the value but there was some talk about simply expanding the type signatures to accommodate anything that will be cast to a `String`.
There's maybe still an argument to be made for doing string conversion in formulae but expanding the type signatures will resolve a number of existing type errors if we simply want to rely on implicit type casting.
Past that, this also updates the type signature for `BuildError` to align with the `#system` signature changes, as we receive a new type error otherwise.
=> Formula, BuildError: Update type signatures

Library/Homebrew/extend/os/mac/extend/ENV/super.rb
Apple's iconv has a regression in macOS Sonoma. This unfortunately happens to be triggered in gettext's configure test. This patch bypasses the detection, aligning with previous macOS versions.
I first fixed it for gettext: https://github.com/Homebrew/homebrew-core/pull/142490
But the problem impacts many formulas depending on gettext, that borrow its detection script.
This seems like the safest path for us at this point.
=> superenv: help gettext-based configure scripts

Library/Homebrew/utils/gems.rb
As it is not supported and will error otherwise.
=> utils/gems: don't allow Sorbet to install on Sonoma's system Ruby

Library/Homebrew/dev-cmd/bump.rb
-----
When using `brew bump` with `--no-pull-requests`, omit the open & closed pull requests lines which will always be "none" and may therefore be inaccurate. 
Also added a method to always skip both head-only and disabled formulae. This fixes an issue that would occur with the command's non-argument form if a matched formula was head-only.
=> dev-cmd/bump: reduce unnecessary output

Library/Homebrew/formula.rb
This improves `brew audit --except=installed --tap=homebrew/core` times from ~45s (with #16007 applied) to ~30s.
This optimisation is not enabled for formulae with options as I'm not 100% confident caching would behave correctly here. Though that doesn't matter for Homebrew/core, and third-party taps typically are much smaller scale that `brew audit` is already quick.
=> formula: add global caching for `declared_runtime_dependencies`

Library/Homebrew/formula.rb, Library/Homebrew/tap.rb
-----
There is a check for other versioned formula with the same name in the file audit. This just memoizes all of the versioned formulae in a tap during the first call and then uses that much shorter list every time it checks for things.
Command:
```
brew prof --  audit --skip-style --except=version,installed --tap=homebrew/core
```
Before:
After:
It results in a 5-10 second speed up locally for me.
Update: It looks like we're down to ~35 seconds in this repo's CI after this change and @Bo98's change in https://github.com/Homebrew/brew/pull/16008.
=> cmd/audit: improve performance of versioned formula names

Library/Homebrew/cli/args.rb, Library/Homebrew/cmd/readall.rb, Library/Homebrew/extend/on_system.rb, Library/Homebrew/formula.rb, Library/Homebrew/readall.rb, Library/Homebrew/tap.rb, Library/Homebrew/test/formula_spec.rb
-----
Edit: We decided to keep the current behavior of running all os/arch combinations and remove the todos and deprecations.
~Removes temporary default to readall for every os/arch combination
after updating brew-test-bot and brew/cask to pass the appropriate
arguments in on CI.~
- https://github.com/Homebrew/brew/pull/15470
- https://github.com/Homebrew/brew/pull/15937#discussion_r1313889254
Also, add more constants for os/arch combinations. This allows us
to make validating all os/arch combinations the default in
`Readall.valid_tap?` which is needed to keep the same behavior
in `brew tap` that we had before. I also updated a few other
spots around the codebase to use those new constants.
~One more thing was updating the integration test. In local testing,
this didn't change the …
=> cmd/readall: clean up todos

Library/Homebrew/brew.rb, Library/Homebrew/cask/audit.rb, Library/Homebrew/cmd/install.rb, Library/Homebrew/cmd/update-report.rb, Library/Homebrew/dev-cmd/test.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/formula_versions.rb, Library/Homebrew/livecheck/livecheck.rb, Library/Homebrew/migrator.rb, Library/Homebrew/test/utils/backtrace_spec.rb, Library/Homebrew/utils.rb, Library/Homebrew/utils/backtrace.rb, Library/Homebrew/utils/repology.rb
-----
Ever since we started using this at runtime it's been polluting the backtrace output. This makes it harder to debug errors and increases the amount of info users have to paste into the box when filing an issue.
This is a very direct approach. Essentially, we strip out everything related to the `sorbet-runtime` gem whenever the top line in the backtrace is unrelated to sorbet-runtime.
The hope is that this will allow errors related to sorbet to be diagnosed easily while also reducing the backtrace size for all other types of errors.
Note: This requires gems to be set up so that the call to `Gem.paths.home` works correctly. For that reason, it must be included after `utils/gems` which is included in `standalone/load_path` already.
- Is it worth all of this extra code to have cleaner …
=> utils/backtrace: scrub sorbet-runtime from backtrace

Library/Homebrew/brew.sh, docs/Installation.md
-----
macOS Sonoma release will happen on 26 September 2023, in 5 days. We have to switch this on at some point, to be decided below. @Bo98 @MikeMcQuaid
=> Make Sonoma supported

Library/Homebrew/dev-cmd/edit.rb
=> dev-cmd/edit: make the warning easier to read

docs/Formula-Cookbook.md
-----
We ask people to check the commit style guidelines when submitting PR's, but we never updated them to state we prefer one squashed commit now. Otherwise the autosquash workflow dispatches replacement PR's, which wastes CI time.
=> docs: update commit style guidelines

Library/Homebrew/dev-cmd/audit.rb
-----
This is a test to see if this will fix some flaky checks on CI that are caused by missing formulae while auditing the core tap.
- https://github.com/Homebrew/brew/issues/16037
=> dev-cmd/audit: load formulae from files

Library/Homebrew/dev-cmd/edit.rb, Library/Homebrew/extend/pathname.rb
This PR reduces `edit.rb` complexity to solve #16015.
1. Moves to `Pathname` the logic that checks if the path is core tap, cask or formula.
2. Moves failure handler when path does not exist into separate method.
This makes the code easier to read to fix the name conflict between formula and existing directory.
-----
=> dev-cmd/edit: Move path specific functions to Pathname

Library/.rubocop.yml
=> rubocop: don't recommend minitest extension.

Library/Homebrew/cli/parser.rb
Before this change, external commands, whether official or not, cannot use the `env:` DSL for `Homebrew::CLI::Parser` without adding their environment variable to `Homebrew::EnvConfig`.
Instead, if the method is not defined, check the environment variable directly. This allows `env:` to be used as expected and allows simplifying some (new) code in e.g. `brew bundle`.
=> cli/parser: check env var directly if there's no `EnvConfig` method.

Library/Homebrew/dev-cmd/unbottled.rb
This was quite slow before, for me at least.
=> dev-cmd/unbottled: speed up dependent fetching

Library/Homebrew/cli/named_args.rb
As demonstrated in #16015, if you do `brew edit something` where `something` is both a file/directory in your working directory and a package name, there was no way to specify that you want the package without changing working directories.
This PR makes it so `--formula` and `--cask` is able to do that.
=> cli/named_args: don't interpret `--formula`/`--cask` args as paths

.devcontainer/on-create-command.sh, .github/workflows/tests.yml, Dockerfile, Library/Homebrew/Gemfile, Library/Homebrew/Gemfile.lock, Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/dev-cmd/bump-cask-pr.rb, Library/Homebrew/dev-cmd/bump-formula-pr.rb, Library/Homebrew/dev-cmd/bump-revision.rb, Library/Homebrew/dev-cmd/irb.rb, Library/Homebrew/dev-cmd/livecheck.rb, Library/Homebrew/dev-cmd/pr-upload.rb, Library/Homebrew/dev-cmd/rubocop.sh, Library/Homebrew/dev-cmd/tap-new.rb, Library/Homebrew/dev-cmd/test.rb, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/dev-cmd/typecheck.rb, Library/Homebrew/manpages.rb, Library/Homebrew/startup/bootsnap.rb, Library/Homebrew/style.rb
A full `brew install-bundler-gems` is somewhat slow. This PR splits up the gem groups further to allow faster runs in CI etc, as well as allow a base `brew install-bundler-gems --groups=` only install what we already vendor (roughly). This could be used in future PRs to bootstrap a new Ruby.
Draft because this requires #15952.
=> Further split up Gemfile into groups

Library/Homebrew/utils/gems.rb
`brew livecheck --json` can and does install gems, but Bundler output would mess up parsing the JSON output. Redirect it to stderr instead to separate it from actual command output.
=> utils/gems: redirect bundler output to stderr

Library/Homebrew/Gemfile
Should be `pr_upload` not `pr_publish`.
=> Gemfile: fix pr_upload group typo

Library/Homebrew/service.rb, Library/Homebrew/test/service_spec.rb, docs/Formula-Cookbook.md
-----
Closes #15945
This adds support for multiple named sockets to the service DSL. It also retains backwards compatibility with the previous DSL where you can declare one socket. The only change is that the default socket name is now `listeners` instead of `Listeners` to go along with lowercase Ruby symbol naming conventions.
CC: @SMillerDev
=> service: support multiple sockets in DSL

Library/Homebrew/formula.rb, Library/Homebrew/tap.rb, Library/Homebrew/utils/bottles.rb
Removing time spent on file loading etc, this makes `to_hash` as much as twice as fast for me.
This in turn improves formula API generation speed.
=> Improve performance of `Formula#to_hash`

Library/Homebrew/extend/os/mac/readall.rb, Library/Homebrew/formula.rb, Library/Homebrew/readall.rb, Library/Homebrew/test/spec_helper.rb
* Significantly improve base performance (60s -> 30s for Homebrew/core before the extra checks were added)
* Add `to_hash` check to ensure the method used for API generation (and `brew info` etc) doesn't error. This increases that 30s back up to 47s (after some optimisations) _but_ does mean we could remove the 90 second `brew generate-formula-api` call in tap_syntax checks as the other elements of that command shouldn't be affected by formula changes.
These changes affect formulae only. I have not touched casks.
=> Improve performance of `brew readall`

Library/Homebrew/service.rb, Library/Homebrew/test/service_spec.rb, docs/Formula-Cookbook.md
Reverts Homebrew/brew#16026
This changed the service socket serialization code which will make it not possible to generate valid plist files for formulae with those blocks until they update their brew version. Which is to say that the local brew code will not be up-to-date with the JSON API for non-developer users. I'll work on making it more backwards compatible after reverting.
=> Revert "service: support multiple sockets in DSL"

.github/workflows/tests.yml, .gitignore, Library/Homebrew/Gemfile, Library/Homebrew/cask/artifact/abstract_uninstall.rb, Library/Homebrew/cask/cask_loader.rb, Library/Homebrew/cmd/readall.rb, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/test/cli/named_args_spec.rb, Library/Homebrew/test/dev-cmd/irb_spec.rb, Library/Homebrew/test/rubocop_spec.rb, Library/Homebrew/test/support/helper/formula.rb, Library/Homebrew/test/test_runner_formula_spec.rb, Library/Homebrew/test/utils/ruby_check_version_script_spec.rb, Library/Homebrew/utils/gems.rb, Library/Homebrew/utils/ruby.sh, Library/Homebrew/utils/ruby_check_version_script.rb
`HOMEBREW_BOOTSNAP` is not supported for now, as it doesn't work on anything not macOS system Ruby. I will investigate this further soon.
=> Test on Ruby 3.1

Library/Homebrew/cask/artifact/abstract_uninstall.rb, Library/Homebrew/cask/artifact/pkg.rb, Library/Homebrew/cask/staged.rb, Library/Homebrew/env_config.rb, Library/Homebrew/env_config.rbi, Library/Homebrew/system_command.rb, docs/Manpage.md, manpages/brew.1
This environment variable allows telling Homebrew to use the `SUDO_USER` variable to `sudo` through that user when Homebrew (Cask) attempts to run `sudo`.
While we're here, clarify in some messaging that we're running `sudo` and that that's the password we're asking for; the specific password is configuration dependent and not the specific password for the user.
Similarly, remove the `Package installers may write to any location` output; it's kinda spammy and doesn't feel like the right place.
=> Add HOMEBREW_SUDO_THROUGH_SUDO_USER

Library/Homebrew/cmd/shellenv.sh
-----
fish's `set` doesn't modify the exit status when assigning a variable. This means that `set -q VAR; or set VAR ...` will return an exit status of 1 even if the variable is suceessfully set. By switching the commands to `! set -q VAR; and set VAR ...`, this prevents the 1 from propogating when running `eval (brew shellenv)`.
=> fix `eval (brew shellenv)` from exiting with status 1 in fish

Library/Homebrew/cli/named_args.rb
-----
Closes #16015
Before we used to evaluate all named arguments as local paths first. This means that the following could be a name conflict.
```
brew edit src
```
If there was a local file or directory named src, it would default to that. Otherwise it would search for a formula/cask with the same name and return that.
Now it will only default to the local path if the named argument starts or ends with a slash (`/`) or includes a period (`.`). This means that in the event of a name clash with a normal package name it will default to the package instead of the local file.
It also fixes an edge case where the following would be interpreted as a tap name if no local directory existed with the same name.
```
brew edit src/
```
Example:
```console
$ pwd
/Users/kevinrobell/test
$ ls
jrnl …
```
=> cli/named_args: better handle name conflicts in #to_paths

.github/workflows/build-pkg.yml, Library/Homebrew/brew.sh
- instead of setting a static `PKG_KEYCHAIN_PASSWORD` secret, generate a random password from `openssl rand` instead.
- use `PKG_APPLE_ID_EMAIL` which makes the fact it's an email a bit more obvious. I've created this new secret already and will delete the old one after this is merged.
- bump the latest supported version of macOS and update the comment in `brew.sh` to point to this.
=> workflows/build-pkg: tweak some variables.

docs/Adding-Software-to-Homebrew.md, docs/Cask-Cookbook.md, docs/External-Commands.md, docs/Formula-Cookbook.md
-----
v0.13 of the `markdownlint` gem just got released and it has a few new rules which our docs ended up failing. This fixes those linter errors so that CI is no longer red.
Rules:
MD055 - Tables: Each row must start and end with a '|'
MD057 - Tables: In the second row every column must have at least '---',
possibly surrounded with alignment ':' chars
Related to: https://github.com/Homebrew/brew/pull/16070
For the curious, this is how you can fix the MD055 linter error. It doesn't seem like this linter has a built-in fix option.
```awk
$ gawk -i inplace '
BEGIN {
cmd = "bundle exec rake lint"
while((cmd | getline line) > 0) {
split(line, arr, ":")
filename = arr[1]
if(filename !~ /\.md$/) continue
lineno = arr[2]
if(lineno !~ /^[0-9]+$/) continue
error = arr[3]
if(error !~ /^ …
```
=> Fix markdown linter errors

.github/workflows/pkg-installer.yml, Library/Homebrew/brew.sh, package/Distribution.xml, package/scripts/postinstall
- split jobs into build/test/deploy
- test package on both macOS Intel and Apple Silicon
- cleanup some argument handling
- use `HOMEBREW_MACOS_OLDEST_SUPPORTED` naming to be consistent with `brew.sh`
- note in `brew.sh` that `Distribution.xml` also needs updated (and do so)
- various other little bits of style cleanup
=> Improve building Homebrew*.pkg

Library/Homebrew/download_strategy.rb
Fixes #15169.
Partially covers #15816.
Should cover #16078.
=> download_strategy: fix mirrors not working

Library/Homebrew/version.rb
-----
The existing date version parsing regex only matches file names that have a prefix (e.g., `ltopers-v2017-04-14.tar.gz`), so it doesn't match files like `2023-09-28.tar.gz`. There are a handful of formulae that have to manually specify the version as a result (e.g., `marksman`, `sqtop`, etc.). `bootloadhid` is also affected but that's because the filename uses a dot as the prefix delimiter (e.g., `bootloadHID.2012-12-08.tar.gz`) and the regex only matches a hyphen.
This addresses these shortcomings by using `[._-]` as the prefix delimiter and making it optional.
=> Version: Improve date version parsing

Library/Homebrew/version.rb
This reverts commit 7626bdd1fd84cc5f70c4cb9f7bdf323bb771cf59.
See discussion in https://github.com/Homebrew/brew/pull/16081
=> Revert "Version: Improve date version parsing"

.github/workflows/pkg-installer.yml, package/scripts/postinstall
- test on more macOS versions and improve the test names
- add a more resilient and less disruptive version of changing `git`'s `safe.directory` configuration
=> More Homebrew `.pkg` improvements

Library/Homebrew/rubocops/text.rb, Library/Homebrew/test/rubocops/text_spec.rb
-----
- This came up in a user contribution recently so here's a RuboCop for it.
- I'm getting some weird test failures on Sonoma for some reason so I'll rely on CI for running all of `brew tests` rather than just the one I wrote.
=> rubocops/text: Declare "revision 0" in formulae as unnecessary

Library/Homebrew/startup/bootsnap.rb
I've tried it on Portable Ruby 2.6 and 3.1 and it seems to have no issues there.
I'm also trying removing the Apple Silicon restriction here. I don't have an arm64 machine so I'd appreciate if someone could try it out first.
I suspect the original issue was that the load cache didn't previously key on Ruby platform and version, so it could mix system and portable Ruby load paths together which would lead to disaster. This issue was addressed in Bootsnap 1.9.4, released January 2022.
The breakage using Bootsnap with `ruby/setup-ruby` is still a mystery, but that case wasn't restricted here anyway.
=> standalone/bootsnap: relax restrictions

Library/Homebrew/startup/bootsnap.rb
Reverts Homebrew/brew#16062
It went 💥 
https://github.com/Homebrew/brew/actions/runs/6415915221/job/17418714728?pr=16073#step:6:12
CC @Bo98
=> Revert "standalone/bootsnap: relax restrictions"

.github/workflows/tests.yml
While it is fairly safe to install a gem built on Ubuntu 20.04 on later versions like 22.04, it is _not_ safe to install a gem built on Ubuntu 22.04 on earlier versions like 20.04. The same applies to macOS too, albeit sometimes more discretely.
Easiest fix to that is to split the cache further. We probably want to re-test the initial compile once every new OS version anyway to make sure new compilers/headers/etc remain compatible.
=> workflows/tests: split gem cache per OS version

Library/Homebrew/api.rb, Library/Homebrew/development_tools.rb, Library/Homebrew/download_strategy.rb, Library/Homebrew/resource.rb
-----
Similar to the situation addressed in #15895, a system with a built-in `curl` that's too old to handle some certificates (e.g. OS X 10.11) won't be able to fetch the dependencies for compiling a newer `curl`, which is run by update.sh as part of the initial install process. That's been partially resolved by #16079 which fixes mirror support, and this PR finishes the job by:
- in *development_tools.rb*, adding two functions to wrap the task of checking if the system CA certificates or `curl` need replacing; each just checks if they're a) too old and b) haven't been replaced yet. Also added is a function for generating the insecure download warning, called by *api.rb* and *download_strategy.rb*.
- in *api.rb*, setting the flag to use `--insecure` when fetching the API files if either …
=> api: ignore HTTPS errors if minimum curl version isn't installed

.github/workflows/sorbet.yml, .github/workflows/spdx.yml, .github/workflows/sponsors-maintainers-man-completions.yml
GitHub have removed preinstalled `hub` from their images as of a couple days ago and are recommending users switch to `gh`, which will continue to be available preinstalled on all supported images.
Fixes https://github.com/Homebrew/brew/actions/runs/6425801173/job/17449002896
=> workflows: replace `hub` with `gh`

docs/Installation.md, package/scripts/postinstall, package/scripts/preinstall
- Allow specifying user through `/var/tmp/.homebrew_pkg_user.plist`
- Improve permission handling
- Correctly write API cache
- Add `preinstall` script to fail if we can't get a valid user
Reopening @nstrauss's PR from https://github.com/Homebrew/brew/pull/16073 so it can go through the full packaging CI run here.
=> Improve Mac package for enterprise install scenarios

Library/Homebrew/cmd/shellenv.sh, docs/Homebrew-on-Linux.md, docs/Manpage.md, manpages/brew.1
-----
This is a follow-up PR for Homebrew/install#809 for document update.
- Homebrew/install#808
- Homebrew/install#809
=> docs: prefer placing `shellenv` command in rcfile rather than shell profile on Linux

Library/Homebrew/cmd/fetch.rb
-----
`brew fetch` was always downloading the stable spec. This fixes that.
=> cmd/fetch: restore `--HEAD` functionality

Library/Homebrew/cli/parser.rb
-----
Each command's `args` was including both options and their descriptions. This trims them down to including just short and long options.
Before: (for e.g. `brew --cache`'s `args`)
```
==> #<Homebrew::CLI::Args named=[], remaining=[], d?=true, debug?=true, Display any debugging information.?=false, q?=false, quiet?=false, Make some output more quiet.?=false, v?=false, verbose?=false, Make some output more verbose.?=false, ...
```
After:
```
==> #<Homebrew::CLI::Args named=[], remaining=[], d?=true, debug?=true, q?=false, quiet?=false, v?=false, verbose?=false, h?=false, help?=false, os=nil, arch=nil, s?=false, build_from_source?=false, force_bottle?=false, bottle_tag=nil, HEAD?=false, formula?=false, formulae?=false, cask?=false, casks?=false>
```
=> cli/parser: depopulate commands' internal args lists

Library/Homebrew/dev-cmd/tap-new.rb
This commit enhances the publish actions script by including a step to close the pull request after
committing the changes. The existing script deletes the branch after pushing the commits, but lacks
the functionality to close the associated PR.
-----
Permissions Added:
- contents: write
- pull-requests: write
See: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
=> Add missing permissions to actions publish

Library/Homebrew/formula.rb, Library/Homebrew/formulary.rb
-----
Some formulae rely on the `using:` attribute to indicate how a resource is to be downloaded if it can't be detected via the domain name or protocol, e.g.:
- [libvorbis](https://formulae.brew.sh/formula/libvorbis)'s stable URL has `using: :homebrew_curl` as it's hosted on a TLS-1.3-only server
- [trino](https://formulae.brew.sh/formula/trino)'s stable URL has `using: :nounzip` to allow for manual hard-link-preserving decompression
- the head URLs for [abcl](https://formulae.brew.sh/formula/abcl), [global](https://formulae.brew.sh/formula/global), [nginx](https://formulae.brew.sh/formula/nginx), [objfw](https://formulae.brew.sh/formula/objfw), [squid](https://formulae.brew.sh/formula/squid) each have a `using` attribute to indicate the VCS needed to fetch their sources
This change …
=> api: add `using:` attribute to head & stable URLs

Library/Homebrew/dev-cmd/tap-new.rb
Followup to https://github.com/Homebrew/brew/pull/16097 (CC: @JameelKaisar). When a tap stores bottles in GitHub Packages, then the publish workflow requires the corresponding write permission.
The error message raised was: `level=fatal msg="copying image 1/2 from manifest list: writing blob: initiating layer upload to /v2/davidchall/hep/fastjet/blobs/uploads/ in ghcr.io: denied: installation not allowed to Write organization package"`
-----
=> Adding GHA permission for GitHub Packages

Library/Homebrew/formulary.rb
It was correctly getting the renames from the API, but it was attempting to load the new formula from an installed tap only which will fail for those with Homebrew/core untapped.
Fixes #16107
=> formulary: load from API for formula renames

Library/Homebrew/utils/gems.rb
The group was renamed and I missed this reference.
Fixes https://github.com/orgs/Homebrew/discussions/4841 and https://github.com/Homebrew/brew/pull/16105#issuecomment-1758843240
The check will soon disappear completely when Ruby 2.6 support is dropped.
=> utils/gems: fix Sonoma compatibility check

Library/Homebrew/cmd/fetch.rb
Mitigation for ghcr.io networking issues
...and also a functionality that makes sense to have given `--retry` is largely to smooth out network instability, and retrying the blobs is already supported.
=> cmd/fetch: support retrying manifest downloads

Library/Homebrew/resource_auditor.rb, Library/Homebrew/utils/curl.rb
GitHub network issue mitigation
=> Add retries to some online audit checks

Library/Homebrew/dev-cmd/unbottled.rb, completions/bash/brew, completions/fish/brew.fish, completions/zsh/_brew, docs/Manpage.md, manpages/brew.1
-----
Closes #16016
This option tries to find bottles where the bottle was removed from the formula in the past week and not added back in.
It checks the output of `git log` to see if there are any bottles that fit this criteria.
Note: This implementation does not handle renamed formula well but I assume that doesn't happen that often so having the occasional false positive is not a big deal here.
The `git log` output looks something like this for each commit.
```diff
commit 2db9033f717486f7f0c9b815165f8e75c106f4f2
Author: BrewTestBot <1589480+BrewTestBot@users.noreply.github.com>
Date:   Mon Oct 9 01:57:41 2023 +0000
chezmoi: update 2.40.1 bottle.
diff --git a/Formula/c/chezmoi.rb b/Formula/c/chezmoi.rb
index 6630a3a49f1..0e0b44ceb1e 100644
--- a/Formula/c/chezmoi.rb
+++ …
```
=> dev-cmd/unbottled: add --lost option

Library/Homebrew/dev-cmd/unbottled.rb
=> brew unbottled: skip deprecated

Library/Homebrew/formula_installer.rb
-----
A leftover from #15566: originally added in #12296, a dependency with `[:build, :test]` was assumed to be required for downloading or extracting a package's source. Now we have `:implicit`, so just check for that. This restores curl being pre-installed for any dependency with `using: :homebrew_curl` and [subversion being pre-installed if needed on macOS 10.14 and earlier](https://github.com/Homebrew/homebrew-core/pull/87527#issuecomment-947867674).
=> formula_installer: pre-install implicit dependencies

Library/Homebrew/dependency_collector.rb
-----
This addresses a rather subtle dependency bug that's best illustrated with an example. If a formula's source needs brewed curl to be downloaded, it's marked as `using: :homebrew_curl` and will show curl as an implicit dependency.
```console
$ brew deps --include-build --direct --tree --annotate libzip
libzip
├── curl  [build] [test] [implicit]
├── cmake  [build]
└── zstd 
```
Same if the formula is a dependent for another.
```console
$ brew deps --include-build --tree --annotate xlsxio
xlsxio
└── libzip 
├── curl  [build] [test] [implicit]
│   ├── pkg-config  [build]
...
├── cmake  [build]
└── zstd 
├── cmake  [build]
├── lz4 
└── xz 
```
But in some cases, curl isn't added as an implicit dependency when it should be.
```console
$ brew deps --include-build --tree --annotate libisofs …
```
=> dependency_collector: fix caching of deps requiring brewed curl

Library/Homebrew/global.rb, Library/Homebrew/test/download_strategies/curl_spec.rb
=> chore(global): update safari user-agent to latest

Library/Homebrew/cli/named_args.rb, Library/Homebrew/cli/parser.rb
-----
Closes #16123
This came up recently where an outdated formula definition caused the program to crash with an ambiguous message when a user wanted to upgrade a cask instead. Catching these errors allows them to get handled later on improving error messages and defaults. Now if the only formula with the given name is invalid it will default to using the cask unless --formula is specified.
After changes:
```console
$ brew install -n vagrant
Error: Failed to load formula: vagrant
formulae require at least a URL
Warning: Treating vagrant as a cask.
==> Would install 1 cask:
vagrant
$ brew install -n vagrant --formula
Error: formulae require at least a URL
Rerun with --verbose to see the original backtrace …
```
=> cli/parser: rescue formula specification errors

Library/Homebrew/software_spec.rb, Library/Homebrew/utils/bottles.rb
For https://github.com/Homebrew/homebrew-test-bot/pull/977
=> Implement equality functions for BottleSpecification

Library/Homebrew/dev-cmd/bump-cask-pr.rb
-----
Previously it was possible for both the version and url to be changed. This would cause the old url to be used to download the cask and check the checksum since the version and checksum were replaced in the cask first and then the url would be replaced. This meant that the resulting checksum was wrong if a url was provided and might be completely invalid if it was interpolated causing a download failure as shown in #16114.
Closes #16114
=> dev-cmd/bump-cask-pr: replace url before downloading files

Library/Homebrew/rubocops/urls.rb, Library/Homebrew/utils/shared_audits.rb
-----
followup https://github.com/mislav/bump-homebrew-formula-action/pull/53
seeing couple of issues recently in homebrew-core for the artifact urls
=> audit(github): prefer `/archive/refs/tags` urls over `/archive`

Library/Homebrew/dev-cmd/pr-upload.rb
Gem install was incorrectly inside the `unless args.upload_only?` block.
=> dev-cmd/pr-upload: fix gems not being installed with --upload-only

Library/Homebrew/cmd/setup-ruby.sh
This command, a bit like `install-bundler-gems`, is intended to be run to ensure that the next invocation of `brew` will not need to try and install Ruby or Bundler gems.
=> cmd/setup-ruby.sh: add new command.

Library/Homebrew/standalone/init.rb
Fixes issues with it trying to install gems in a sandbox.
Fixes performance concerns with `brew test-bot`.
=> standalone/init: skip initial gem install in child processes

Library/Homebrew/dev-cmd/dispatch-build-bottle.rb, Library/Homebrew/dev-cmd/pr-publish.rb
=> dev-cmd: fix GitHub.workflow_dispatch_event kwarg calls

Library/Homebrew/extend/kernel.rb
=> extend/kernel: fix `odisabled` kwargs handling

Library/Homebrew/Gemfile, Library/Homebrew/Gemfile.lock, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/dev-cmd/bump-cask-pr.rb, Library/Homebrew/dev-cmd/bump-formula-pr.rb, Library/Homebrew/dev-cmd/bump-unversioned-casks.rb, Library/Homebrew/dev-cmd/livecheck.rb, Library/Homebrew/livecheck/strategy/sparkle.rb, Library/Homebrew/livecheck/strategy/xml.rb
REXML doesn't ship with Ruby 3 (or well it sort of does as a bundled gem, but it isn't accessible through Bundler).
So we need to add it to the Gemfile here. While not strictly necessary for Ruby 2.6, let's do it everywhere for consistency.
=> Pull in REXML gem as it doesn't ship with Ruby 3

Library/Homebrew/rubocops/urls.rb
-----
This fixes the issue mentioned in https://github.com/Homebrew/brew/pull/16126#issuecomment-1780014268.
I would have added an auto-corrector, but I don't think we can choose whether the user provided a tag reference or branch reference.
=> audit(github): also permit refs/heads in GitHub URLs

docs/Shell-Completion.md
This PR updates the `fish` configuration that should be used in order for shell completions provided from `brew` to work.
As [the docs](https://fishshell.com/docs/current/completions.html) explain, with the current command completions inside `(brew --prefix)/share/fish` are appended to `fish_complete_path`, but since `fish` will use the first available file, we want `(brew --prefix)/share/fish` to be prepended instead.
Closes #16159. Given my explanation above, I think that what was happening is that [this file](https://github.com/fish-shell/fish-shell/blob/496fc03b9880891ea3da4989cee50cf7381e707c/share/completions/brew.fish) was being used instead of the "real" one vendored by `brew`.
=> fix(docs): update fish completions command

Library/Homebrew/livecheck/strategy/sparkle.rb, Library/Homebrew/test/livecheck/strategy/sparkle_spec.rb
-----
Historically, the `Sparkle` strategy's `Item` struct has only included basic values from the appcast that are commonly useful. Over time we've selectively added/surfaced more values as we've encountered outliers that require use of different values in a `strategy` block (e.g., #13368).
We now need to use `minimumSystemValue` (e.g., https://github.com/Homebrew/homebrew-cask/pull/158044), so this expands the `Item` struct to include any appcast value that we could conceivably want to use in the future. This will hopefully save us from having to make more modifications to the struct (and related tests) before we can use a previously-unused value in a `strategy` block.
I did livecheck runs with/without these changes and the [JSON] output remains the same, as expected.
-----
I will be …
=> Sparkle: Surface more Item values

Library/Homebrew/system_command.rb
This is a blind, possible fix for test flakiness surrounding `stderr` in the `system_command` tests. I was not able to reproduce the issue locally but did identify a possible cause.
The potential bad flow I've identified here:
1. Assume `ProcessTerminatedInterrupt` is received before `IO.select` signals readable streams (very narrow window that I cannot reproduce - maybe will happen in VMs)
2. On receiving this, `readable_sources` is set to all streams and `pending_interrupt` is set to true
3. We run `readable_sources.none?` to loop through and read all streams. However `none?` as it was written was guaranteed to short-circuit after the first stream as all possible paths would lead it to returning `true` (EOF on first stream will return value of `sources.any?` which will be true given we …
=> system_command: fix potential issue of stderr not being read

Library/Homebrew/utils.rb
-----
Small fix for one thing brought up in https://github.com/Homebrew/brew/issues/16134#issuecomment-1777720185.
This caused some JSON output to break recently which is not ideal.
The change here is to check if the output should be diverted to stderr based on the options passed to system. If `:out => :err` is passed, then we should send any verbose output to stderr as well.
```console
$ brew ruby -e 'Homebrew.system("ls", :out => :err)' 2>| wc -c
105
$ brew ruby -e 'Homebrew.system("ls")' | wc -c
105
```
=> utils: Homebrew.system respect stderr

Library/Homebrew/utils/gems.rb
Hopefully fixes issues when running two gem-installing commands parallel (reported on Slack).
I haven't locked around Bundler itself here. I possibly will if there's still issues.
=> utils/gems: make `.homebrew_gem_groups` writing atomic

Library/Homebrew/dev-cmd/audit.rb
This type of hash destructuring is not supported.
There's a new syntax, but it doesn't work with 2.6.
So just do `fetch` to support both for now.
=> dev-cmd/audit: fix for Ruby 3

Library/Homebrew/cask/cask.rb, Library/Homebrew/test/support/fixtures/cask/everything.json
This is provided for formulae in `installed.time` and is useful to have for casks as well as formulae so let's output it here too.
=> cask: add `installed_time` to JSON output.

Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
-----
Fixes an outdated link found in https://github.com/Homebrew/brew/pull/16177.
=> Manpage: update GitHub rate limit link

bin/brew
The CDPATH environment variable can affect the behavior of `cd`, and `cd` takes the `-P`, `-L` and `-e` flags. (I didn't know about `-e` until looking at the source) Make quietcd more robust by setting the CDPATH to ''.
I tested this change by running the following commands from a nonstandard directory, which caused some of tcsh's and perl's dependencies to be recompiled.
$ [path to brew] install tcsh
$ [path to brew] install perl
Here's a link to the source code of `cd` in a mirror of the bash repo.
https://github.com/bminor/bash/blob/ec8113b9861375e4e17b3307372569d429dec814/builtins/cd.def#L267
-----
=> [shell] Override CDPATH in brew script.

Library/Homebrew/manpages.rb
This hash deconstruction syntax is not supported in Ruby 3.
=> manpages: fix error under Ruby 3

Library/Homebrew/formula_auditor.rb
This could happen if referencing a dependency that is installed but not present in any tap.
Previously, this would crash `brew audit`.
=> formula_auditor: handle nil tap

Library/Homebrew/tap.rb
I recently got:
```console
Error: Some taps failed to update!
The following taps can not read their remote branches:
heroku/brew
This is happening because the remote branch was renamed or deleted.
Reset taps to point to the correct remote branches by running `brew tap --repair`
```
but the instructed `brew tap --repair` didn't work:
```console
$ brew tap --repair
fatal: couldn't find remote ref refs/heads/master
Error: Failure while executing; `git -C /usr/local/Homebrew/Library/Taps/heroku/homebrew-brew fetch origin` exited with 128.
```
That was because of some previous default:
```console
$ git -C /usr/local/Homebrew/Library/Taps/heroku/homebrew-brew config remote.origin.fetch
+refs/heads/master:refs/remotes/origin/master
```
=> tap: fix repair not working in some cases

Library/Homebrew/cask/audit.rb
-----
This PR adds an audit to ensure that the minimum macOS version specified in the cask matches the minimum macOS version specified by the developer. 
It does so by:
1. Hijacking `audit_livecheck_min_os` to obtain the sparkle version information.
2. Adding `audit_plist_min_os` to extract the version information from `Info.plist`.
3. Comparing the cask min_os version with the extracted value. If both a sparkle min_os and plist min_os are present, we take the larger value of the two.
Note: This will break a lot of casks.
=> cask/audit: add audit_min_os

Library/Homebrew/extend/ENV/shared.rb
In some deprecated MacOS, e.g.10.13 High Sierra, when compiling formulae with --cc=gcc-XX, homebrew will raise
> TypeError: Return value: Expected type Symbol, got type String with value "gcc-XX".
Convert "other" string to symbol to avoid this.
-----
=> Fix TypeError when building from source with gcc compiler in some MacOS version

.github/workflows/docs.yml
Matches Ruby use in rubydoc.brew.sh.
Technically speaking rubydoc.brew.sh still deploys with the EOL 2.7.4: https://pages.github.com/versions/ (and not even the latest 2.7.8!) and it's likely going to remain frozen at that. However we will need 3.1 for YARD generation, and YARD generation results are committed the repository, so as long as we don't touch the Jekyll side too much it'll probably be ok, not that the CI on this side tests that anyway.
=> workflows/docs: bump rubydoc test Ruby

Library/Homebrew/brew.sh, Library/Homebrew/extend/os/linux/cleanup.rb, Library/Homebrew/extend/os/mac/cleanup.rb, Library/Homebrew/extend/os/mac/diagnostic.rb, Library/Homebrew/utils/ruby.sh
`HOMEBREW_RUBY3` is no longer a fancy alias for `HOMEBREW_FORCE_VENDOR_RUBY` and now appropriately manages what gets passed to `ruby_check_version_script.rb`.
This means `HOMEBREW_RUBY3` is now compatible with non-x86_64 Linuxes (if you bring your own Ruby).
Also in this PR: the macOS-specific `brew doctor` Ruby version check is now disabled when running Portable Ruby. It will be removed entirely at a later date.
=> Support system Ruby 3 on Linux

Library/Homebrew/description_cache_store.rb
-----
Fixes #16188
This was caused by some refactoring of `Formula.all` a few months ago.
In this case, `--eval-all` was not propagated to the `Formula.all` command which caused a few different description related commands not to work.
Broken commands:
- `brew search --desc --eval-all TERM`
- `brew desc --search --eval-all TERM`
- `brew desc --descriptions --eval-all TERM`
These commands will fail if the cache store has not already been built locally since this specific method call is only needed when building the cache store not accessing it. The cache store file can be found at: 
```shell
"$(brew --cache)/descriptions.json"
```
Before:
```console
$ brew desc --search --eval-all test
==> Formulae
Error: Calling Formula#all without --eval-all or HOMEBREW_EVAL_ALL is disabled! There is no …
```
=> cmd/desc: fix handling of `--eval-all` with formulae

Library/Homebrew/cleanup.rb
Instead of eagerly deleting everything, only delete what isn't currently in use. Also avoid clearing `.homebrew_gem_groups`.
=> cleanup: smarter gem handling

Library/Homebrew/cask/url.rb
-----
Resolves https://github.com/Homebrew/homebrew-cask/issues/159684
The `header` parameter for `url` should allow a string or an array of strings to be passed.
=> `cask/url` headers parameter type fix

Library/Homebrew/utils/gems.rb
- Use `Tempfile.new` with a mode argument to avoid the default behaviour of creating a file with mode 0600 (only user-readable).
- Avoid writing the file if it already exists and the contents are unchanged.
=> utils/gems: improve behaviour (particularly with Ruby 3)

Library/Homebrew/utils/curl.rb
-----
Should fix the error seen in Homebrew/homebrew-core#153647 ([CI logs](https://github.com/Homebrew/homebrew-core/actions/runs/6805354565/job/18504732312?pr=153647#step:4:36)). This was introduced in e5d656bcce8 and `Digest::256` seems to be the intended one.
=> utils/curl: fix `Digest::SHA256` typo

Library/Homebrew/dependency.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/tab.rb, Library/Homebrew/test/tab_spec.rb, Library/Homebrew/upgrade.rb
Should fix `brew upgrade <pkg>` producing broken installs. We were treating two packages with the same version but different revisions as compatible (because we didn't store revision info at all). This was often incorrect and lead to several reports of broken installs.
=> Store and use revision in tab runtime dependencies

Library/Homebrew/.simplecov, Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
* Fix integration test coverage tracking not working properly (would overwrite each other as the unique ID was generated but not read) - this regressed as the fix for #14662 overcombined command names
* Fix `brew.rb` not being tracked
* Simplify integration test unique ID generation (to avoid regressing back to the state prior to #14662 too much - it will unavoidably have a little but still should be significantly shorter than before)
* Exclude `sorbet` and `yard` directories from coverage tracking - these are used in non-brew tools and are out of scope for rspec testing.
* Fix up some regexes and add some groups for livecheck etc.
* Remove RubyGems < 2.2 compatibility code. We already no longer support it: https://github.com/Homebrew/brew/blob/39c2296ffbd9c2a225d6d64b234ef5584622599a/Libr …
=> Improve coverage tracking

Library/Homebrew/formulary.rb, Library/Homebrew/test/formulary_spec.rb
-----
Fixes https://github.com/Homebrew/brew/issues/16213
Follow-up to https://github.com/Homebrew/brew/pull/16207
Supercedes https://github.com/Homebrew/brew/pull/16215
This PR fixes the `TapLoader` refactoring to properly pass the old tap to the newly created formula, even though it is referencing the new formula file. This is consistent with the old behavior. This also fixes the newly-created issue where migrating to a different non-core tap but with the same name as a core tap incorrectly chooses the core formula.
Finally, this PR adds some more tests.
CC @MikeMcQuaid, @Bo98, and @amancevice
=> Pass original tap to formula when loaded from the API via `TapLoader`

Library/Homebrew/extend/os/mac/extend/ENV/shared.rb
When redefining a method, Sorbet Runtime will not detect this properly if it does not have a type signature and the original did. This results in the new method being completely ignored and Sorbet only calling the original. I reckon is an upstream bug, but we can workaround it ourselves.
This fixes an important issue where any formulae using macOS Perl on Sonoma would not use the correct perl.
=> ENV/shared: fix macOS code not applying under HOMEBREW_SORBET_RUNTIME

Library/Homebrew/dependency.rb, Library/Homebrew/upgrade.rb
When dealing with old bottles without the revision information, we assume any revision > 0 means the formula needs installing. However we don't check whether it is already at the latest revision, so we could return `false` for `Dependency#installed?` for something that is already at the latest.
This PR makes it so `Formula#latest_version_installed?` is checked before any minimum version checking. If it's at the latest we don't need to do any further checking and can say the dependency is good. This also fixes the case where if we might downgrade a formula for some reason, we will now just call the latest version good instead of permanently calling it not installed for not being above a minimum version.
=> Don't reinstall dependency when latest already installed

Library/Homebrew/Gemfile.lock
Bundler locally didn't reject it so seems like something's odd with Dependabot. Will investigate soon, but restore for now as `unf_ext` has nothing to do with it.
https://github.com/Homebrew/brew/pull/16225#pullrequestreview-1735842152
=> Gemfile.lock: restore missing platform

.github/workflows/doctor.yml, Library/Homebrew/dev-cmd/determine-test-runners.rb, Library/Homebrew/github_runner_matrix.rb, Library/Homebrew/test/github_runner_matrix_spec.rb
Add `--all-supported` to `brew determine-test-runner` that makes it output all supported macOS runners (+ Linux if `HOMEBREW_LINUX_RUNNER` is set) rather than basing it on a supplied formula list. It is mutually exclusive to supplying a list of formulae.
Modify `brew doctor` workflow to use it.
Also:
* Supply a minimum macOS bound for GitHub-hosted runners, as they don't necessarily have the same support period as us.
* Fix arm64 timeouts when `HOMEBREW_MACOS_BUILD_ON_GITHUB_RUNNER` is set
* Simplify `--eval-all` handling since the CLI parser can make it required for us rather than needing a custom `odie`.
* Adjust some types (no more nilable arrays)
=> dev-cmd/determine-test-runner: add `--all-supported`

Library/Homebrew/cask/audit.rb, Library/Homebrew/livecheck/strategy/sparkle.rb, Library/Homebrew/test/livecheck/strategy/sparkle_spec.rb
-----
The `#livecheck_min_os` cask audit is intended to use a Sparkle feed's `minimumSystemVersion` information to ensure that the cask has a correct `depends_on macos: ...` value. It reimplements some of the logic in livecheck's `Sparkle` strategy but naively treats the first `item` in the appcast as newest and doesn't adhere to the `Sparkle` strategy's sorting/filtering.
Some appcasts are sorted from oldest to newest and some have `item`s with out-of-order `pubDate` values, so naively using the first `item` in the audit has led to incorrect audit failures at times. As one example, [this issue affected the `hyperkey` cask](https://github.com/Homebrew/homebrew-cask/pull/136777) until upstream updated the appcast to sort items from newest to oldest. This issue is also mitigated by #16013, …
=> Use Sparkle sorting/filtering in #livecheck_min_os

Library/Homebrew/standalone/init.rb
This will be problematic when running formula tests.
=> standalone/init: don't pollute environment on Ruby 3 startup

Library/Homebrew/dev-cmd/vendor-gems.rb
Trivial workaround for now that I think works.
=> dev-cmd/vendor-gems: workaround Dependabot removing lockfile platforms

Library/Homebrew/tap.rb
In a loop that's iterated nearly 7000 times, `Pathname#/` is actually quite slow. It does a lot more than one might think it does: https://github.com/ruby/ruby/blob/24fe22a5da21c9df8584a4ce6b6d1ce18ac41cc2/ext/pathname/lib/pathname.rb#L362-L402 (+ regex matching in `chop_basename`). We however don't need logic like `..` resolving.
We can turn 0.2s to 0.02s by using `File.join` and later making it `Pathname`. There's still a bit of string copying going on, meaning it can spike to 0.1s if it triggers the GC, but it's nevertheless much better than before.
=> tap: optimise `CoreTap#formula_files_by_name`

Library/Homebrew/livecheck/strategy/sparkle.rb, Library/Homebrew/livecheck/strategy/xml.rb, Library/Homebrew/test/livecheck/strategy/xml_spec.rb
-----
As discussed in https://github.com/Homebrew/brew/pull/16196#discussion_r1389066974, this refactors verbose code in the `Sparkle` strategy where we access element text into a reusable `Xml#element_text` method, replacing chained calls like `item.elements["title"]&.text&.strip&.presence` with `Xml.element_text(item, "title")`.
`#element_text` is only used to retrieve the text of a child element in the `Sparkle` strategy but it can also retrieve the text from the provided element if the `child_path` argument is omitted (i.e., `Xml.element_text(item)`). This will allow us to also avoid similar calls like `item.text.strip.presence` in the future.
=> Xml: Add #element_text method

Dockerfile
=> Dockerfile: fix default umask

.github/workflows/tests.yml, Dockerfile, Library/Homebrew/brew.sh, Library/Homebrew/utils/ruby.sh
Time to start a fire?
This will enable it in virtually all Homebrew CI, as well as any user of the Docker image.
=> Enable Ruby 3 for `HOMEBREW_DEVELOPER` and the Docker image

Dockerfile
#16242 wasn't applying to GitHub Actions.
That's because GitHub Actions force sets HOME to `/github/home`, which is a mounted directory with its own permissions. Avoid this for curl downloads by setting `XDG_CACHE_HOME` to the original home's `.cache` directory.
=> Dockerfile: set `XDG_CACHE_HOME` to fix `umask` in GitHub Actions

Library/Homebrew/brew.sh, Library/Homebrew/test/os/mac/diagnostic_spec.rb
Set it before system Ruby checks or `brew doctor` may fail.
=> brew.sh: set HOMEBREW_RUBY3 earlier

Library/Homebrew/cleanup.rb, Library/Homebrew/formula.rb
---
This should give us a nice speed up when rebuilding the same pip package multiple times (esp useful to save CI time in python version bump PRs)
Timings for `brew reinstall -s black`:
Before (no cache): 47s
After (with cache): 28s
=> formula: add `PIP_CACHE_DIR` to build env

Library/Homebrew/dev-cmd/create.rb, Library/Homebrew/formula_creator.rb
`path` attribute is used only once, and it is easier to calculate it on the fly than to update its state after different methods.
Factored out from #16238 to keep it clean.
-----
=> formula_creator: Remove `path` attr to reduce code complexity

Library/Homebrew/brew.sh
We set `HOMEBREW_DEVELOPER` within `test-bot` so we end up running a mixed 2.6 and 3.1 mode that installs and uninstalls Ruby 3 repeatedly depending on the command.
Easiest fix is to force test-bot to be Ruby 3. Stuff like `brew -v test-bot` isn't detected here but this code is going to disappear on Monday anyway.
Fixes https://github.com/Homebrew/homebrew-test-bot/issues/988
=> brew.sh: always run test-bot under Ruby 3

Library/Homebrew/tap.rb
=> tap: don't display file info for uninstalled taps

Library/Homebrew/utils/gems.rb
Per the code [comment](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/gems.rb#L15-L16), it seems I should bump this after ignoring a pair of committed vendored gems in https://github.com/Homebrew/brew/pull/16259 :
https://github.com/Homebrew/brew/pull/16259/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R102 https://github.com/Homebrew/brew/pull/16259/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R109
-----
=> Bump VENDOR_VERSION in gems.rb

Library/Homebrew/dev-cmd/create.rb, Library/Homebrew/formula_creator.rb
Sets initial values for formula fields from CLI params.
Another refactoring for code clarity to keep https://github.com/Homebrew/brew/pull/16238 minimal.
-----
=> formula_creator: move initial CLI values into constructor

Library/Homebrew/dev-cmd/bump-cask-pr.rb
=> bump-cask-pr: fix duplicate PR checking with comma versions

.github/workflows/vendor-gems.yml, .github/workflows/vendor-version.yml
The `paths:` triggers of the existing workflow was incorrect for this check.
Should catch #16269 in the future.
=> workflows: move vendor version check to separate workflow

Library/Homebrew/brew.sh, Library/Homebrew/utils/analytics.rb
If the git repo is broken, `HOMEBREW_VERSION` could be set to:
https://github.com/Homebrew/brew/blob/251a098fbf1c02ca95f53b4806e5b6da8d5e4a80/Library/Homebrew/brew.sh#L488
This causes an error in `utils/analytics` which expects `HOMEBREW_VERSION` to match a regex, and therefore breaks any formula installs. Avoid that by defaulting to "unknown" if the fallback HOMEBREW_VERSION is detected.
I've seen two reports of this in two days - not entirely sure why it's suddenly come up.
=> utils/analytics: don't fail on invalid version

Dockerfile, Library/Homebrew/brew.sh, Library/Homebrew/cleanup.rb, Library/Homebrew/cmd/vendor-install.sh, Library/Homebrew/utils/ruby.sh
This will:
- Make all macOS users use Portable Ruby (subsequent cleanup of system Ruby logic will follow later).
- Remove availability of Portable Ruby 2.6
- Allow system Ruby 3.1 to be used on Linux
This will not:
- Require system Ruby users on Linux to change their Ruby from 2.6. That is a breaking change and will follow after 4.1.23, which will likely be the final 4.1.x.
This will apply to dev-cmd users immediately once this is merged and all other users when 4.1.23 is tagged.
Draft because #16267 needs to be merged first. Consider this otherwise ready for review.
=> Enable Ruby 3 for all users

Library/Homebrew/brew.sh, Library/Homebrew/cmd/update.sh
Temporary until the next tag. Unset before spawning new brew subprocesses - the new process will pick up the correct default.
Should fix downgrades from master to 4.1.22?
=> Unset HOMEBREW_RUBY3 after updates

Library/Homebrew/formula.rb
This previously assumed a non-nil alias_path would always exist where the unresolved path exists. This is not always true with untapped core taps - e.g. if we download the Ruby source or use it from a bottle (post-install) then the we have the original file but not the aliased symlink.
Fixes some errors installing by alias, e.g.
```console
Error: An exception occurred within a child process:
FormulaUnavailableError: No available formula with the name "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/crypto++".
```
Technically speaking this means methods like `alias_name` etc will not be set in postinstall etc, but I don't think any formula uses that information and would be a bigger refactor to fix.
=> formula: fix specified_path for aliases without core tap

Library/Homebrew/extend/os/mac/unpack_strategy/zip.rb, Library/Homebrew/extend/os/mac/unpack_strategy/zip.rbi
Before:
```rb
> UnpackStrategy::Zip.ancestors
[UnpackStrategy::Zip::MacOSZipExtension, UnpackStrategy, SystemCommand::Mixin, UnpackStrategy::Zip, UnpackStrategy, Object, SystemCommand::Mixin, JSON::Ext::Generator::GeneratorMethods::Object, Kernel, BasicObject]
```
After:
```rb
> UnpackStrategy::Zip.ancestors
[UnpackStrategy::Zip::MacOSZipExtension, UnpackStrategy::Zip, UnpackStrategy, Object, SystemCommand::Mixin, JSON::Ext::Generator::GeneratorMethods::Object, Kernel, BasicObject]
```
We were skipping the generic OS `extract_to_dir` and directly going to the unpack strategy baseclass.
For some reason, this didn't happen with Sorbet Runtime enabled as it seems to break the ancestor rules (coincidentally to our favour on this occasion).
Fixes #16287.
=> unpack_strategy/zip: fix extraction issues on macOS without developer mode
