Homebrew/brew

- Library/Homebrew/brew.sh
-----
We cache the output of `git describe`, but we don't check whether the
cached value is valid.
This fixes that.
> brew.sh: fix handling of dirty git repo

- Library/Homebrew/dev-cmd/test.rb
- Library/Homebrew/exceptions.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/sandbox.rb
- Library/Homebrew/test/sandbox_spec.rb
- Library/Homebrew/utils/fork.rb
First of all: I recommend viewing the diff with "hide whitespace" enabled - the changes aren't actually that drastic.
---
We've recently received reports of the sandbox hard crashing Ruby in macOS 15 beta for some users. We've also seen related reports on OS X 10.11 after a recent Tempfile crypto RNG change in Ruby 3.3.
The sandbox used to be a `fork` + `exec` but due to security tightening over time this has increased in complexity to the point we no longer actually have an `exec` inside the top-level fork and we are now breaking the golden rule of `fork` on macOS, as stated by `man fork`:
```
CAVEATS
There are limits to what you can do in the child process.  To be totally
safe you should restrict yourself to only executing async-signal safe
operations until such time as one of the exec …
```
> Fix misuse of `fork` in sandbox causing crashes

- Library/Homebrew/test/utils/shared_audits_spec.rb
- Library/Homebrew/utils/shared_audits.rb
-----
Also clean up logic using String slices
dot example: `z.lua`
https://github.com/Homebrew/homebrew-core/blob/master/Formula/z/z.lua.rb#L4
slash example: `hz`
https://github.com/Homebrew/homebrew-core/blob/master/Formula/h/hz.rb#L4
> utils/shared_audits: GitHub urls can have '.' in repo and '/' in tag

- Library/Homebrew/tap.rb
- Library/Homebrew/test/tap_spec.rb
-----
Currently, ruby files that are not in the Cask directory are considered to be formulae if a Formula or HomebrewFormula directory doesn't exist  which doesn't make sense. We know that these should only be in a few directories so we can check for that explicitly.
Beyond that the `Tap#cask_file?` and `Tap.formula_file?` methods were only used inside update-report so it doesn't make sense to turn them into pathnames and expand things when we know that each string will be a relative path from a tap that we can just check with a regex.
This change will stop other tap changes like new commands or changes to other directories like lib/ from showing up as new formulae.
I tried opening a PR for this a long time ago but I got busy with other things and it got closed by the stale bot.
- …
> cmd/update-report: improve formula file validation

- docs/How-To-Open-a-Homebrew-Pull-Request.md
During my [submission](https://github.com/Homebrew/homebrew-core/pull/182146) I followed this guide since it is the first link, but it wasn't until we got to the end of the process that I learned I should have created a tap.
This was a great experience for me, but a waste of maintainers time. 
-----
> Add note about auditor to How-To-Open-a-Homebrew-Pull-Request.md

- Library/Homebrew/utils/github/api.rb
Let's get this ready to go since we don't want to accidentally leak
private information.
> Remove GraphQL debug output

- Library/Homebrew/utils/github.rb
-----
Let's make sure we get the opportunity to print the errors if the query
response doesn't have the form we expected it to take.
> utils/github: improve sponsorships error handling

- Library/Homebrew/brew.sh
- Library/Homebrew/cmd/shellenv.sh
-----
On macOS 14 and newer, `/usr/libexec/path_helper` supports setting a
`PATH_HELPER_ROOT` environment variable.
With this set, `path_helper` checks `$PATH_HELPER_ROOT/etc/paths` and
`$PATH_HELPER_ROOT/etc/paths.d` in the same way it checks `/etc/paths`
and `/etc/paths.d`.
We can use this to simplify management of the user's `PATH` variable
when they do `brew shellenv`. In particular, if their system supports
it, we delegate setting the `PATH` environment variable to `path_helper`
instead of our own code. We also write a default `etc/paths` file if one
is not already present.
This is nicer because it simplifies management of the user's `PATH`
variable. For example, if a user wants a keg-only formula to be in their
`PATH`, they can simply add the necessary path to `etc/paths` or …
> cmd/shellenv: improve for newer macOS using `/usr/libexec/path_helper`

- .devcontainer/devcontainer.json
-----
As pointed out in https://github.com/Homebrew/brew/commit/8b3be30a839788972a56b44a1ffacf8f7bee4053#r146048190 (thank you, @noahsettersten!), this was nested wrong. I think this fixes it? JSON is hard!
> devcontainer: Fix Codespace repository permissions

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/utils/github.rb
-----
`brew bump-formula-pr` is encountering a type error (e.g., as seen in [a recent homebrew/core autobump run](https://github.com/Homebrew/homebrew-core/actions/runs/10647361012/job/29515230778)), as the inferred return type of `GitHub#check_for_duplicate_pull_requests` doesn't align with the explicit return type of `#check_pull_requests`:
```
Error: Return value: Expected type T.nilable(T::Array[String]), got type Module with value T::Private::Types::Void::VOID
Caller: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:137
Definition: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:472 (Homebrew::DevCmd::BumpFormulaPr#check_pull_requests)
```
This addresses the issue by adding a type signature with a `void` return type to …
> Adjust typing around #check_pull_requests

- Library/Homebrew/utils/lock.sh
Fixes the syntax error introduced by an incomplete refactor in bc0f5ee
```
$ brew update
==> Updating Homebrew...
To restore the stashed changes to /usr/local/Homebrew, run:
cd /usr/local/Homebrew && git stash pop
File "<string>", line 1
import fcntl; fcntl.flock(, fcntl.LOCK_EX | fcntl.LOCK_NB)
^
SyntaxError: invalid syntax
```
Caused by missed variable rename in https://github.com/Homebrew/brew/commit/bc0f5ee62a9f410d81d9a8820083a387a82573f7
The fix finishes the refactor by completing the variable rename and brings the code base back to a (more) consistent state. 
- [✓] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [✓] Have you checked to ensure there aren't other open [Pull …
> Fix SyntaxError introduced by a refactor in bc0f5ee

- Library/Homebrew/list.sh
-----
We don't need to output an intermediate `LS_ERRORED` string to exit in
case that `ls` errors out.
> list.sh: simplify

- Library/Homebrew/list.sh
Turns out this script has never worked.
> list.sh: fix arg parsing always failing

- Library/Homebrew/formula.rb
- Library/Homebrew/utils/string_inreplace_extension.rb
-----
This allows us to get rid of a RuboCop disable, and will make formulae
easier to read.
> formula: make `audit_result` a kwarg in `inreplace`

- Library/Homebrew/dev-cmd/bottle.rb
-----
Based on https://specs.opencontainers.org/image-spec/annotations/#pre-defined-annotation-keys
> **org.opencontainers.image.created** date and time on which the image was built (string, date-time as defined by [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6)).
> dev-cmd/bottle: use iso8601 for compliance with spec

- Library/Homebrew/formula_auditor.rb
Also require licenses on non-disabled formulae
-----
I am working on adding licenses to all non-disabled formulae, so opening PR to make some license checks stricter.
The extra licenses are only some examples for now (too much effort to make exhaustive), e.g.
* `BUSL-1.1` and `Elastic-2.0` are ones we have manually rejected in Homebrew/core. For now, just reject all versions (can modify if terms change)
* `CC-BY-NC` I believe are going to be non-free due to non-commercial restriction
* Debian has `CC-BY-NC-SA` example - https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution-NonCommercial-ShareAlike_.28CC_BY-NC-SA.29
* Fedora rejects all `CC-BY-NC-*` licenses. They do allow `CC-BY-ND-x.y` for "Allowed content". See https://docs.fedoraproject.org/en-US/legal/allowed-licenses/
* …
> formula_auditor: reject more SPDX licenses

- Library/Homebrew/shims/super/cc
I've been wondering for a long time why we pass `-pipe` to C compilers systematically.
- On modern filesystems its effect is homeopathic
- it has no effect with modern clang, because the assembler is now integrated into clang, so only the linker is called as a separate, and it never supported pipes anyway
- the only other compiler we use for a few formulas is GCC, but even there the effect is marginal on modern OSes
At least, it did not hurt. Well, until clang 16 broke pipe input to the assembler: there, passing `-pipe` can make GCC actually fail to compile. See https://github.com/OpenMathLib/OpenBLAS/issues/4888 for details.
I'll be filing a bug with Apple about that (it's a regression in clang), but I don't expect it to be fixed soon. Given that `-pipe` use is historical, I think it's …
> shims/super/cc: do not pass -pipe

- Library/Homebrew/brew.sh
- Library/Homebrew/cmd/shellenv.sh
Just setting this up for when we're ready to try this again.
Reverts Homebrew/brew#18224
> cmd/shellenv: output the result of `path_helper` directly

- Library/Homebrew/brew.sh
- Library/Homebrew/list.sh
- Library/Homebrew/test/cmd/list_spec.rb
* Apply `list.sh` optimisation to `brew ls`
* Use `getopts` for parsing to support combined shorthand options (e.g. `brew list -1r` now works in the fast path)
> list.sh: improve arg parsing, support `brew ls`

- Library/.rubocop.yml
- Library/Homebrew/cleanup.rb
- Library/Homebrew/cmd/vendor-install.sh
- Library/Homebrew/standalone/init.rb
- Library/Homebrew/standalone/sorbet.rb
- Library/Homebrew/startup/bootsnap.rb
- Library/Homebrew/startup/bootsnap.rbi
- Library/Homebrew/startup/config.rb
- Library/Homebrew/startup/ruby_path.rb
The majority of the time, this isn't necessary. Bootsnap builds an incremental cache correctly.
However we get edge cases when a gem shadows a default gem only under certain gem groups and have occasionally had reports of Bootsnap randomly breaking after a while.
Let's just save ourselves the stress and more aggressively version the Bootsnap cache. Now the whole cache is invalidated whenever `Gemfile.lock` changes or Ruby is updated.
This does in turn have a benefit that `brew cleanup` is now smarter. Now that we version the cache we don't need to nuke the whole cache every time we run `brew cleanup` and can now detect what cache is stale and what isn't. As a result, I've now enabled it for periodic `brew cleanup`.
Probably unblocks at least the LoadError part of #18216.
> Invalidate Bootsnap cache on Gemfile.lock changes

- Library/Homebrew/utils/github.rb
This is mandatory for GitHub App tokens.
It seems to also work for PATs - documentation isn't exactly clear on that but I think it works.
Probably fixes https://github.com/Homebrew/actions/issues/584
> utils/github: use `x-access-token`

- Library/Homebrew/Gemfile.lock
> Revert "build(deps-dev): bump logger from 1.6.0 to 1.6.1 in /Library/Homebrew"

- .github/workflows/docker.yml
This makes it a bit more obvious in various GitHub UIs that don't display the workflow name and more consistent with `tests.yml`.
> workflows/docker: improve job names.

- Library/Homebrew/startup/bootsnap.rb
Instead of keying based on what we intend to install, key instead based on what is actually installed. Otherwise the Bootsnap cache might populate before the install changes have taken place.
> startup/bootsnap: base key on in install state rather than projection

- docs/Formula-Cookbook.md
-----
The documentation on revisions currently states that the `revision` "is inserted inserted underneath the `homepage`/`url`/`sha256` block."
However, when I follow these instructions and add a `revision` to a formula, inserting it underneath the `sha256` line (but above the `license`), the edited formula does not pass the audit:
```
$ brew audit --strict --online trivy
trivy
* line 7, col 3: `license` (line 7) should be put before `revision` (line 6)
Error: 1 problem in 1 formula detected.
```
To clarify the relevant documentation, the `license` should be listed as part of the block beneath which the `revision` must be placed.
> Docs: Add license to block preceding revision placement

- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/test/formula_auditor_spec.rb
Also add some more incompatible licenses. These are all not allowed by Fedora and have are classified as not OSI and FSF approved on SPDX.
-----
> formula_auditor: make deprecate license check non-strict in core

- Library/Homebrew/api.rb
- Library/Homebrew/dev-cmd/contributions.rb
- Library/Homebrew/standalone/init.rb
- Library/Homebrew/warnings.rb
Otherwise we're going to get spammed even more in Ruby 3.3.5, in ways that are arguably upstream bugs (`require "json"` now issues a deprecation warning for its internal code).
> Globally silence default gem warnings

- Library/Homebrew/keg.rb
-----
Could reduce chances of rmdir errors, but may not be the root cause.
> keg: avoid attempting rmdir on must exist subdirs

- Dockerfile
-----
The commands to install `gh` were changed in cli/cli#8693.
We should align what we do there to make what's happening here a bit
more transparent.
> Dockerfile: align `gh` installation with upstream documentation

- Library/Homebrew/formula_installer.rb
- Library/Homebrew/test/formula_installer_spec.rb
- Library/Homebrew/test/os/linux/formula_installer_spec.rb
- Library/Homebrew/test/os/mac/formula_installer_spec.rb
-----
(Vaguely) relates to: https://github.com/Homebrew/brew/issues/17998
It looks like these OS extensions, introduced in https://github.com/Homebrew/brew/pull/14163, were not required from `formula_installer`, so are not actually in use. I fixed that issue, and added some tests intended to prevent a regression. (I don't think I've added OS-specific tests before, so I'm not sure how the magic works, or what assumptions can be made within them, so apologies if this is a bumpy ride.)
> Use FormulaInstaller OS extensions

- Library/Homebrew/linkage_checker.rb
-----
A couple situations this helps:
* Avoid no linkage message for test dependencies, e.g. `harfbuzz`:
```
Dependencies with no linkage:
pygobject3
```
* Properly detect when a `:test`-dependency that is also an indirect dep should actually be made a direct runtime dependency.
> linkage_checker: exclude test deps from being considered runtime dep

- Library/Homebrew/utils/github/actions.rb
-----
We currently generate invalid workflow commands when we create
annotations with a `title` but no `file`. Let's fix that.
While we're here, let's improve handling of `title`s with `:`s. We
cannot use `title`s with `::` since GitHub Actions uses this as a
separator for different fields between a workflow command.
Let's also make sure `metadata` never ends in a `:` to avoid confusing
the GitHub Actions command parser about where the `::` separator is
meant to be.
> github/actions: fix annotation title handling

- Library/Homebrew/rubocops/uses_from_macos.rb
Also add `bc-gh` which is the version of bc provided by Ventura and
newer macOS. Other `bc` (GNU bc) was provided until Monterey
-----
* `gnu-getopt` is not provided by macOS. BSD getopt is, so switched DSL in https://github.com/Homebrew/homebrew-core/pull/183637
* `rpcgen` removal PR https://github.com/Homebrew/homebrew-core/pull/183671 (this could cause tests/CI to fail based on state of PRs).
* `bc-gh` added in https://github.com/Homebrew/homebrew-core/pull/183679
> rubocops/uses_from_macos: remove `gnu-getopt` and `rpcgen`

- Library/Homebrew/extend/ENV/super.rb
- Library/Homebrew/shims/super/ninja
-----
`ninja` currently doesn't respect `HOMEBREW_MAKE_JOBS` or
`ENV.deparallelize`. This change fixes that.
> shims/super/ninja: respect Homebrew parallelism

- Library/Homebrew/os/mac/pkgconfig/15/libcurl.pc
Apple removed this with the Curl 8.7.1 update (dropping the reference from `curl-config` in 8.6.0).
> os/mac/pkgconfig/15: drop NTLM_WB reference in libcurl

- Library/Homebrew/linkage_checker.rb
-----
Looking into a way to avoid Julia linkage errors since it uses its own dylib lookup logic which brew considers broken linkage.
Seemed to be easier approach rather than trying to inject unneeded RPATHs into the binary that Julia doesn't want.
Example for Julia:
```json
{
"julia": "share/julia/compiled/**/*"
}
```
Need to try out a few more things and check on Linux code path.
> linkage_checker: skip broken linkage in Julia

- Library/Homebrew/cask/cask_loader.rb
- Library/Homebrew/cask/caskroom.rb
- Library/Homebrew/cli/named_args.rb
- Library/Homebrew/exceptions.rb
- Library/Homebrew/test/cask/cask_loader_spec.rb
- Library/Homebrew/test/cli/named_args_spec.rb
- Library/Homebrew/test/exceptions_spec.rb
-----
Fixes <https://github.com/Homebrew/brew/issues/17416>
This PR uses the new cask tabs to set the correct tap when loading an installed cask.
I have added two new `CaskLoader` methods:
1. `load_installed_cask`: this method is analogous to `Formulary::from_keg`. It accepts a token and returns a cask with that token from the tap specified in the install receipt of the cask. Essentially, if `slack` was installed from `test/tap`, running `load_installed_cask("slack")` will return the `test/tap/slack` cask and _not_ the `homebrew/cask/slack` cask. Note: if a full name is passed, the tap specified in the name will be used, even if a different tap exists in the install receipt.
2. `load_from_installed_caskfile`: this method takes an installed caskfile and loads a cask from it, making sure to …
> Set correct tap when loading installed casks

- Library/Homebrew/formula.rb
-----
Closes <https://github.com/Homebrew/brew/issues/18300>
This PR simply modifies the error message shown when a formula doesn't have a URL to include the full name of the formula.
For example:
```console
$ brew readall homebrew/core
Error: Invalid formula (arm64_sequoia): /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/h/hello.rb
hello: formula requires at least a URL
```
> Include formula name in no-URL error

- Library/Homebrew/shims/super/cc
-----
Our parsing of linker flags can be easily confused by, e.g.,
-Wl,-undefined -Wl,dynamic_lookup,-dead_strip_dylibs
The current code that tries to detect these flags will erroneously
conclude that they were not passed.
This change fixes that.
> shims/super/cc: fix linker flag parsing

- Library/Homebrew/formula.rb
-----
`cargo` doesn't follow setting `HOMEBREW_MAKE_JOBS` or
`ENV.deparallelize`. Let's fix that.
> formula: make `cargo` respect Homebrew-managed parallelism

- Library/Homebrew/exceptions.rb
-----
This will allow us to set `HOMEBREW_NO_BUILD_ERROR_ISSUES` in our
workflows, which will avoid needlessly burning through our rate limit.
> exceptions: skip `#fetch_issues` is `HOMEBREW_NO_BUILD_ERROR_ISSUES` is set

- Library/Homebrew/cmd/shellenv.sh
(Unchecked steps aren't applicable here, in my opinion)
-----
This PR addresses an issue when a PATH variable with Homebrew paths is inherited, modified, and then `brew shellenv` is evaluated again. In this case, the expected behavior is that Homebrew directories should be placed at the front of the PATH. However, since `-m` (move component) isn’t specified, `fish_add_path` doesn’t modify the variable, this can, for example, cause binaries in `/usr/bin` (like XCode CLI tools' Python) to take precedence.
I encountered this in VSCode, where `eval (/opt/homebrew/bin/brew shellenv fish)` in my `config.fish` didn’t properly update the PATH, as VSCode's environment resolution already included the paths, ~~just not at the top~~. This change ensures `$HOMEBREW_PREFIX/bin` and …
> shellenv.sh / fish shell: Move Brew PATHs to front if they exist (add -m arg to fish_add_path)

- Library/Homebrew/cmd/shellenv.sh
-----
This will make the output more readable. We tend to prefer long flags
elsewhere anyway.
> cmd/shellenv: use long flags for fish

- Library/Homebrew/github_runner_matrix.rb
- Library/Homebrew/test/dev-cmd/determine-test-runners_spec.rb
- Library/Homebrew/test/github_runner_matrix_spec.rb
-----
This will allow us to avoid the loss of bottles to Homebrew/core PRs.
> Deploy Sequoia runner, 🔪 Monterey

- .github/workflows/pkg-installer.yml
Should resolve https://github.com/Homebrew/brew/actions/runs/10854929440/job/30126441752?pr=18305#logs
Perhaps due to https://github.com/Homebrew/brew/pull/18314
> Remove macos-12 from test matrix

- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/utils/github/actions.rb
-----
- only use annotations for `opoo` and `onoe` if
`HOMEBREW_GITHUB_ACTIONS` is set. This will make using `brew` less
noisy in GitHub Actions for third parties. See
Homebrew/discussions#5602.
- if we've already called `puts_annotation_if_env_set`, then we no
longer need to print the message to `$stderr`. The message from the
annotation already show up in the GitHub Actions log, so printing to
`$stderr` just leads to duplicate messages in the log.
While we're here, let's make sure to forward the `file:` and `line:`
kwargs of `puts_annotation_if_env_set` to the `Annotation` constructor.
> Limit usage of GitHub Actions Annotations

- Library/Homebrew/shims/super/cc
When using `--debug-symbols`, stripping prefixes can end up breaking debugging support. `--debug-symbols` itself gives fairly reproducible builds anyway given it builds from `HOMEBREW_CACHE` rather than randomised temporary prefix.
> shims/super/cc: don't strip prefixes with `--debug-symbols`

- Library/Homebrew/cli/named_args.rb
- Library/Homebrew/exceptions.rb
- Library/Homebrew/test/cli/named_args_spec.rb
- Library/Homebrew/test/exceptions_spec.rb
We had several places where we had `rescue NoSuchKegError` that was not catching the new `NoSuchKegFromTapError`.
We could either add `NoSuchKegFromTapError` or collapse the two into one. I chose the latter as it's the safer option for existing code compatibility.
Fixes `brew uninstall --force` being broken for taps: https://github.com/orgs/Homebrew/discussions/5607
> Fix `NoSuchKegFromTapError` handling

- Library/Homebrew/dev-cmd/generate-cask-api.rb
Aligns with the reverse we do on the other side: https://github.com/Homebrew/formulae.brew.sh/blob/20739b186d71b0ba66fabdb0f2f8172d1ceab9f8/_layouts/cask_json.json#L4
Not looked into the technical reason for it but we do it in `generate-formula-api` so let's just do it here too: https://github.com/Homebrew/brew/blob/051069c0b3f693419fc33d0cf10d7552c2e03364/Library/Homebrew/dev-cmd/generate-formula-api.rb#L54
Hopefully fixes https://github.com/Homebrew/homebrew-cask/issues/185583
> dev-cmd/generate-cask-api: fix handling of `+` characters

- Library/Homebrew/cli/named_args.rb
-----
Based on feedback from Homebrew/discussions#5602.
While users can already silence this by passing `--formula` or `--cask`
as required, I am inclined to agree that `--quiet` should probably
silence messages that are relatively low priority (of which I think this
is one).
> cli/named_args: silence `package_conflicts_message` with `--quiet`

- Library/Homebrew/style.rb
On Linux HOMEBREW_CACHE may be set to `$HOME/.cache/Homebrew`. Some systems, like Fedora Silverblue, have `/home` set up to be a symbolic link to `/var/home`. While Homebrew generally seems to work fine on Fedora Silverblue, rubocop causes the `brew style` command to emit a lot of warnings because of the symbolic link[1]. This can be resolved by looking up the real path of HOMEBREW_CACHE before passing it to rubocop.
[1] https://github.com/rubocop/rubocop/issues/6228
-----
> style: resolve symblic links in `HOMEBREW_CACHE`

- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/utils/github/actions.rb
Sorry @carlocab, just reverting this for now so it doesn't make it into the next stable release.
I want to keep these errors around for users but avoid doing the `opoo` calls when it doesn't make sense to do so.
Reverts Homebrew/brew#18329
> Revert "Limit usage of GitHub Actions Annotations"

- Library/Homebrew/resource.rb
Regression from https://github.com/Homebrew/brew/commit/ae6f43921ae0389973fe62b0f74d11ba6bbbd31b. Manifest retry treats `DownloadError` different than validity errors.
Fixes https://github.com/Homebrew/homebrew-core/issues/190870.
> resource: further fix manifest retry handling

- Library/Homebrew/os/linux/ld.rb
-----
I think this is a bug in Ruby, but I've no idea how to track it down. I
can reproduce it intermittently in a codespace when `brew install`ing a
large number of formulae.
To work around this:
- cache the return value of `brewed_ld_so_diagnostics` so that we can
limit the number of calls to `IO.popen`
- retry once when we see a `TypeError`
Closes #17828.
> os/linux/ld: harden `brewed_ld_so_diagnostics` against `TypeError`

- Library/Homebrew/search.rb
- Library/Homebrew/test/search_spec.rb
Allow `@` and `+` characters for search string.
```
brew search @11
==> Formulae
ant@1.10           go@1.17            llvm@11            mariadb@11.5
cairomm@1.14       go@1.18            mariadb@11.0       openjdk@11
cairomm@1.18       go@1.19            mariadb@11.1       openssl@1.1
clang-format@11    hdf5@1.10          mariadb@11.2       postgresql@11
gcc@11             hdf5@1.14          mariadb@11.4       spidermonkey@115
==> Casks
115                       ableton-live-suite@11     semeru-jdk-open@11
ableton-live-intro@11     corretto@11               temurin@11
ableton-live-lite@11      microsoft-openjdk@11      zulu@11
ableton-live-standard@11  paragon-extfs@11
```
```
brew search +
==> Formulae
bonnie++                  libsigc++                 mysql-connector-c++
crf++ …
```
> search: allow @ and + characters

- Library/Homebrew/cmd/shellenv.sh
Some programs like `vapigen` might not work correctly, when `XDG_DATA_DIRS` does not include `$HOMEBREW_PREFIX/share`. Instead of requiring the user to manually adjust the shell environment, we can set `XDG_DATA_DIRS` as part of `cmd/shellenv`, so that it is sufficient to run `brew shellenv` on any particular system.
-----
Fixes #18317
> cmd/shellenv: set `XDG_DATA_DIRS` on Linux

- Library/Homebrew/dev-cmd/unbottled.rb
-----
Previously was outputting only number of Linux-only and Intel-only formulae on ARM Sequoia.
This at least adds formulae bottled on older ARM but not on ARM Sequoia to count.
However, it doesn't remove Linux-only and Intel-only formulae. These should probably be removed from the total formulae.
> dev-cmd/unbottled: fix total unbottled count

- Library/Homebrew/rubocops/text.rb
-----
Since `xcodebuild` isn't part of CLT so build will fail.
Should be okay on Linux as `depends_on :xcode`/`depends_on xcode: ...` is a no-op.
Seperately, may look into either setting `DEVELOPER_DIR` or using absolute path to Xcode.app since `xcode-select --switch /Library/Developer/CommandLineTools` will cause build to fail, e.g.
```console
❯ DEVELOPER_DIR=/Applications/Xcode.app xcodebuild --help 2>&1 | head -1
Usage: xcodebuild [-project <projectname>] [[-target <targetname>]...|-alltargets] [-configuration <configurationname>] [-arch <architecture>]... [-sdk [<sdkname>|<sdkpath>]] [-showBuildSettings [-json]] [<buildsetting>=<value>]... [<buildaction>]...
~
❯ DEVELOPER_DIR=/Library/Developer/CommandLineTools xcodebuild --help 2>&1 | head -1
xcode-select: error: tool 'xcodebuild' …
```
> rubocops: `xcodebuild` needs an Xcode dependency

- Library/Homebrew/dev-cmd/bottle.rb
-----
Currently, we silently ignore cases where a formula previously had an
`:all` bottle but now no longer does.
These are most often due to (in order of likelihood):
- bottle reproducibility breakage in `brew`
- new hard-coded `/usr/local` references in text files in a bottle
The former is a bug that should be fixed, while the latter can be fixed
trivally with an `inreplace`.
Let's try to make sure we always do this by making `brew bottle` error
out so that we can catch these instances as they happen rather than
after the fact.
I haven't encountered any cases where a formula previously had an `:all`
bottle but no longer does for reasons other than the two outlined above.
If we do encouter those in the future, we can either:
- update `brew bottle` to skip this check, perhaps with a new …
> dev-cmd/bottle: improve `:all` bottle handling

- Library/Homebrew/formula_installer.rb
Regression from https://github.com/Homebrew/brew/commit/ae6f43921ae0389973fe62b0f74d11ba6bbbd31b.
Mainly affected our bottle dispatch workflows.
> formula_installer: fix manifest error handling

- Library/Homebrew/github_runner_matrix.rb
> github_runner_matrix: include 15-x86_64 with `--all-supported`

- Library/Homebrew/os/mac/pkgconfig/14/libcurl.pc
macOS 14.5 SDK has been an Xcode-exclusive SDK until now, so we never updated this pc file. CLT 16 will however include macOS 14.5 SDK so we can update this now.
While the 8.6.0 runtime supports NTLM_WB, the 8.6.0 curl-config dropped the reference to it ahead of Apple dropping it in macOS 14.6's curl 8.7.1 update, which never received a corresponding SDK. Not reporting a feature seems like the safest option.
This PR may have to wait until after the CLT is released fully.
> os/mac/pkgconfig/14: update libcurl for 14.5 SDK

- Library/Homebrew/keg.rb
Currently, `brew link` installs `*.info` files to `#{HOMEBREW_PREFIX}/share/info/dir` using the `install_info` method. However, some formulae (e.g., `Emacs`) also ship `*.info.gz` files, which are only `symlink`ed but not installed.
This PR allows `*.info.gz` files to be installed during linking in addition to the `*.info` files.
-----
> keg: Install `gzip`ed info files during linking

- .github/workflows/pkg-installer.yml
-----
This uses the `Homebrew/actions/create-or-update-issue` action added in Homebrew/actions#588 to create an issue when the publish fails for a release. It also automatically updates the issue on repeated failures, and closes the issue when the latest workflow run succeeds.
> workflows/pkg-installer: create an issue when publish fails

- .github/workflows/docker.yml
-----
When we don't care about which specific Ubuntu version to use, `homebrew/brew:master` is better than `homebrew/ubuntu22.04:master` as it allows us to implicitly rely on the default Ubuntu version.
See discussion at #18395.
> workflows/docker: publish `homebrew/brew:master`

- Library/Homebrew/test/support/lib/startup/config.rb
If you have `HOMEBREW_TEMP` set to a longer path (e.g. the user's private temporary directory rather than `/private/tmp`), Sequoia will error out on some tests when forking because the path is too long (> 104 bytes).
To improve this situation let's:
- use a shorter path for `HOMEBREW_TEMP` by appending `/brew-tests` to the existing `HOMEBREW_TEMP` used outside of tests rather than creating nested temporary directories
- use the minimal amount of randomness to avoid collisions while allowing parallel tests
- use `squeeze` to remove any double slashes in the temporary path
> Shorten `brew tests` temporary paths.

- .github/workflows/docker.yml
Extracted from #18384.
This will be merged when the next release is Homebrew >=4.4.
> docker: deprecate Ubuntu 18.04

- Library/Homebrew/brew.sh
- Library/Homebrew/tap.sh
-----
This provides a >3x speedup for `brew tap` with no arguments (i.e., when listing taps). It also makes the completion significantly faster.
```console
$ hyperfine --warmup=3 --setup 'git checkout {branch}' --parameter-list branch master,brew-tap-speedup 'brew tap'
Benchmark 1: brew tap (branch = master)
Time (mean ± σ):      1.405 s ±  0.080 s    [User: 0.561 s, System: 0.238 s]
Range (min … max):    1.332 s …  1.549 s    10 runs
Benchmark 2: brew tap (branch = brew-tap-speedup)
Time (mean ± σ):     404.1 ms ± 124.8 ms    [User: 107.9 ms, System: 200.7 ms]
Range (min … max):   308.8 ms … 693.7 ms    10 runs
Summary
brew tap (branch = brew-tap-speedup) ran
3.48 ± 1.09 times faster than brew tap (branch = master)
```
> Speed up `brew tap` for no arguments

- Library/Homebrew/env_config.rb
- Library/Homebrew/test/github_runner_matrix_spec.rb
-----
The way we handle boolean environment variables is a bit unfortunate.
For example, setting `HOMEBREW_EVAL_ALL=false` actually enables
`HOMEBREW_EVAL_ALL`.
Let's fix this by deprecating setting boolean environment variables to
common false-y values (`false`, `0`, `nil`, `no`, and `off`) so that we
can later ignore these false-y values when reading boolean environment
variables.
Note: I haven't commented out `odeprecated` because I meant to target the PR branch at #18388, but that seems to have merged just before I pushed this.
> env_config: deprecate setting boolean vars to falsy values

- Library/Homebrew/brew.sh
- Library/Homebrew/os/mac.rb
Seems like we forgot to do this for macOS 14.
Will probably merge this tomorrow to not be too eager in forcing people to install the CLT.
> os/mac: bump latest SDK version

- Library/Homebrew/dev-cmd/create.rb
This makes it easy to copy/paste the command, which needs to be run anyway.
Before.
```
Warning: Cannot verify integrity of '61668e8218397a60410a66ddbbcf622c00bcb9dcf9bfe482908d45c999e5e253--rquickshare-0.11.2.tar.gz'.
No checksum was provided.
For your reference, the checksum is:
sha256 "d7ede30aed5c61d34a242588414fc00118aa6c9abca89b66cf7bfe454e753aa3"
Please run `HOMEBREW_NO_INSTALL_FROM_API=1 brew audit --new rquickshare` before submitting, thanks.
Editing /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/r/rquickshare.rb
Warning: Using vim because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR
```
After
```
Warning: Cannot verify integrity of '61668e8218397a60410a66ddbbcf622c00bcb9dcf9bfe482908d45c999e5e …
```
> create: show audit command on the next line

- Library/Homebrew/cask/url.rb
- Library/Homebrew/test/cask/audit_spec.rb
- Library/Homebrew/test/support/fixtures/cask/Casks/booby-trap.rb
We're removing these in https://github.com/Homebrew/homebrew-cask/pull/186501 and forbidding in https://github.com/Homebrew/brew/pull/18404 so let's deprecate them too (because having functionality like this we don't allow in official taps is recipe for accidental breakage and deprecation later).
> cask/url: deprecate `url do` blocks.

- Library/Homebrew/brew.rb
- Library/Homebrew/cask/cask_loader.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/test/cask/cask_loader/from_uri_loader_spec.rb
- Library/Homebrew/test/cask/cask_spec.rb
- Library/Homebrew/test/formulary_spec.rb
We've already disabled installing casks/formulae from URLs and we regularly tell people not to install from paths so let's just deprecate this behaviour entirely.
Even Homebrew developers do not need to work this way.
Potential alternative to https://github.com/Homebrew/brew/pull/18379 or at least a companion.
> Deprecate installing casks/formulae from paths.

- Library/Homebrew/brew.rb
- Library/Homebrew/cask/cask_loader.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/test/cask/cask_loader/from_uri_loader_spec.rb
- Library/Homebrew/test/cask/cask_spec.rb
- Library/Homebrew/test/formulary_spec.rb
`brew test-bot` seems to be broken now for third-party taps.
Fixes #18433
Reverts Homebrew/brew#18409
> Revert "Deprecate installing casks/formulae from paths."

- Library/Homebrew/build.rb
- Library/Homebrew/extend/os/mac/utils/socket.rb
- Library/Homebrew/extend/os/utils/socket.rb
- Library/Homebrew/postinstall.rb
- Library/Homebrew/test.rb
- Library/Homebrew/test/support/lib/startup/config.rb
- Library/Homebrew/utils/fork.rb
- Library/Homebrew/utils/socket.rb
Alternative fix for #18424.
Closes https://github.com/Homebrew/brew/pull/18424.
I will try upstream this (though obviously in a different form since it is written in C upstream).
I went for slightly more code in order to make it a drop-in replacement and thus trivial to rip out in the future. The gist of it is just the array `pack` and using `Socket` instead of `UNIXSocket`.
> Allow sockets to use longer paths on macOS

- Library/Homebrew/test/cask/utils_spec.rb
Instead of recursively resolving the path, let's just resolve the stem.
> test/cask/utils_spec: fix test failure when HOMEBREW_TEMP is a symlink

- Library/Homebrew/cmd/list.rb
- completions/zsh/_brew
-----
Should support use case and close #18421.
> cmd/list: `-t` and `-r` support for some long options

- Library/Homebrew/style.rb
> style: skip actionlint checks if an actionlint workflow is present

- Library/Homebrew/completions.rb
- Library/Homebrew/cxxstdlib.rb
- Library/Homebrew/formula_pin.rb
> completions formula_pin: `typed: strict`, cxxstdlib: `typed: strong`

- Library/Homebrew/completions.rb
- completions/zsh/_brew
> completions: fix short option conflict in zsh completion

- Library/Homebrew/tap.rb
Follow up from #18445 that may allow us to deprecate the old name in future.
> tap: add repository key.

- Library/Homebrew/test/spec_helper.rb
- Library/Homebrew/warnings.rb
> warnings: `typed: strict`

- .github/workflows/tests.yml
-----
The containers have `homebrew/core` tapped so we don't need to wait forever for the core repo to be cloned.
The tap syntax job requires all official taps. Unlike the Ubuntu images [^1], `macos-14` has both core and cask tapped [^2] so setting up Homebrew should be faster there. We don't use the containers because the cask tap is not available by default.
[^1]: https://github.com/actions/runner-images/blob/ubuntu24/20240922.1/images/ubuntu/scripts/build/install-homebrew.sh
[^2]: https://github.com/actions/runner-images/blob/macos-14/20240923.101/images/macos/scripts/build/install-homebrew.sh#L23-L24
> workflows/tests: use the container and `macos-14` for some jobs

- Library/Homebrew/extend/pathname.rb
- Library/Homebrew/linkage_checker.rb
- Library/Homebrew/os/linux/elf.rb
- Library/Homebrew/os/mac/mach.rb
-----
Some formulae include these files, and they can't always be removed.
However, they can cause spurious linkage failures, so let's skip them
when checking for linkage. See, for example, faust at
Homebrew/homebrew-core#191308.
> linkage_checker: skip files with incompatible architectures

- Library/Homebrew/Gemfile.lock
Doesn't really matter too much but should do it anyway.
> Gemfile.lock: bump Ruby version

- Library/Homebrew/dev-cmd/vendor-gems.rb
Port over a similar fix to what we had for `brew install-bunder-gems` for a while now
> dev-cmd/vendor-gems: fix UID handling

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/test/cask/audit_spec.rb
- Library/Homebrew/test/formula_auditor_spec.rb
- Library/Homebrew/utils/shared_audits.rb
-----
This adds a shared audit for Formulae & Casks that checks the validity of deprecation/disable reasons.
> audit: audit deprecate/disable reasons

- Library/Homebrew/cmd/tap-info.rb
- Library/Homebrew/tap.rb
Copy and tweak code from Library/Homebrew/system_config.rb:110 to commit and date information. This information can be useful when debugging formulae in custom taps to ensure the tap has been correctly updated recently or to suss out important differences from one version of a tap to another.
This removes the need to ask users to run something like
git -C $(brew --repository)/Library/Taps/<tap> show -s --decorate
Close https://github.com/Homebrew/brew/issues/18381
-----
> feat(tap-info): display Git information about non-Core/non-API taps

- .github/workflows/pkg-installer.yml
- .github/workflows/sorbet.yml
- .github/workflows/tests.yml
- .github/workflows/vendor-gems.yml
- Library/Homebrew/dev-cmd/tap-new.rb
- Let's use this instead of macOS 14/latest when possible.
- Keep around macOS 13 to ensure we're still testing x86_64.
> github/workflows: use macos-15 GitHub Actions runners.

- Library/Homebrew/dev-cmd/bump.rb
-----
This PR fixes an issue when running `brew bump` with casks that use `version` stanzas containing comma-separated values.
The problem occurs when the number of components increases (e.g., `9.5,286` ==> `9.5.1,287`), since the versions are compared token by token, leading to incorrect results (e.g., `1 < 286`).
To resolve this, instances of `LivecheckVersion` are used to split the comma-separated values into individual `Version` objects.
Before:
```console
$ brew bump --cask banktivity
==> banktivity
Current cask version:     9.5,286
Latest livecheck version: unable to get versions
...
```
After:
```console
$ brew bump --cask banktivity
==> banktivity
Current cask version:     9.5,286
Latest livecheck version: 9.5.1,287
...
```
Related to …
> dev-cmd/bump: fix comparison of versions with comma-separated values

- Library/Homebrew/linkage_checker.rb
- Library/Homebrew/sorbet/rbi/upstream.rbi
-----
`dlopen`ing a library executes potentially untrusted code (e.g. if the
library has initialisers). We can avoid the `dlopen` call by asking
`libSystem` directly about whether a library can be found in the shared
cache.
Of course, the `dlopen` happens after a `ENOENT`, so the attack surface here
is relatively small. But relying on this still exposes us to a potential
TOCTOU[^1] bug. Let's avoid it entirely by skipping `dlopen` altogether.
[^1]: https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use
-----
`brew typecheck` currently returns an error. Looks like the RBI for Fiddle will need updating.
> linkage_checker: replace `Fiddle.dlopen` with `libSystem` call

- Library/Homebrew/test/unpack_strategy/directory_spec.rb
- Library/Homebrew/unpack_strategy/directory.rb
-----
Try running `cp -al` to preserve hardlinks on both macOS and Linux.
If that fails, fall back on `cp -a` which can preserve hardlinks on Linux (but not macOS) assuming target filesystem supports them.
---
Originally tried preserving hardlinks in #13154 but the situation with macOS commands was a bit of a pain (`cp` didn't work well, `rsync` was slow and had mtime issues, `cpio` was a pain to use and could lead to excessive memory as need to stdin every file, etc.).
Exploring this again to figure out a general solution for compacting bottle/install sizes in #18478. Given we now only build bottles for Ventura onward, the limitation on `cp -l` is less of an issue.
I think fallback on older macOS should be quick as `cp` will fail right away on illegal options, e.g.
```console
❯ cp -z
cp: …
```
> unpack_strategy/directory: try preserving hardlinks

- Library/Homebrew/attestation.rb
- Library/Homebrew/test/attestation_spec.rb
-----
I don't think I've seen an `InvalidAttestationError` that wasn't some
sort of network problem (e.g., rate limit, connection timeout, 503).
Let's emit a warning instead of erroring out.
Note that `MissingAttestationError` is still fatal, and that will still
produce errors in CI.
> attestion: make `InvalidAttestationError` non-fatal in CI

- Library/Homebrew/brew.sh
-----
The order matters here (in a way that I can't explain, unfortunately).
Example:
bash-3.2$ read -r FOO <nonexistent 2>/dev/null
bash: nonexistent: No such file or directory
bash-3.2$ read -r FOO 2>/dev/null <nonexistent
Fixes Homebrew/discussions#5653.
> brew.sh: fix some stderr redirections to `/dev/null`

- Library/Homebrew/sorbet/rbi/upstream.rbi
-----
These should no longer be needed after #18501.
> upstream.rbi: remove `Fiddle` constants

- Library/Homebrew/brew.rb
- Library/Homebrew/cask/migrator.rb
- Library/Homebrew/dependencies.rb
- Library/Homebrew/formula_cellar_checks.rb
- Library/Homebrew/help.rb
-----
- I had a break for a while, but inspiration struck tonight so here’s some more effort for https://github.com/Homebrew/brew/issues/17297.
> Bump more files to Sorbet `typed: strict`

- Library/Homebrew/attrable.rb
- Library/Homebrew/attrable.rbi
- Library/Homebrew/cask/metadata.rb
- Library/Homebrew/cask/metadata.rbi
- Library/Homebrew/download_strategy.rb
- Library/Homebrew/download_strategy.rbi
- Library/Homebrew/downloadable.rb
- Library/Homebrew/downloadable.rbi
- Library/Homebrew/exceptions.rb
- Library/Homebrew/exceptions.rbi
- Library/Homebrew/extend/ENV/shared.rb
- Library/Homebrew/extend/ENV/shared.rbi
- Library/Homebrew/extend/os/mac/unpack_strategy/zip.rb
- Library/Homebrew/extend/os/mac/unpack_strategy/zip.rbi
- Library/Homebrew/extend/pathname.rb
- Library/Homebrew/extend/pathname.rbi
- Library/Homebrew/os/linux/elf.rb
- Library/Homebrew/os/linux/elf.rbi
- Library/Homebrew/os/mac/mach.rb
- Library/Homebrew/os/mac/mach.rbi
-----
We've been using `requires_ancestor` in the runtime since https://github.com/Homebrew/brew/pull/18102 – let's do so consistently and clear out some unnecessary rbi files.
> Use requires_ancestor consistently

- Library/Homebrew/cask/cask.rb
- Library/Homebrew/cleanup.rb
- Library/Homebrew/diagnostic.rb
- Library/Homebrew/extend/os/mac/keg.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/install.rb
- Library/Homebrew/keg.rb
- Library/Homebrew/test/spec_helper.rb
-----
We should avoid `remove_const`, especially when redefining the removed const, as it violates normal assumptions of a "constant".
Surprisingly, there's no cop to disallow this method, except for the narrow [case](https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecremoveconst) of specs. (There is an open [issue](https://github.com/rubocop/rubocop/issues/1065) for a general `DisallowedMethods` cop, which has some code snippets, should we want to bother with a custom rule.)
> Replace removed constants with overridable methods

- Library/Homebrew/test/download_strategies/curl_github_packages_spec.rb
- Library/Homebrew/test/download_strategies/curl_post_spec.rb
- Library/Homebrew/utils/curl.rb
-----
The `curl --head --request GET` causes a full download to happen on
`curl` from 8.7.0 to 8.9.1[^1] which causes poor UX due to slow
Cask downloads that can take almost twice as long as they should.
[^1]: https://github.com/Homebrew/brew/issues/18213
> utils/curl: workaround curl bug for `--head --request GET`

- Library/Homebrew/attestation.rb
-----
Otherwise this just shows a message like
Failed to verify attestation. Retrying in 27...
which is a little vague. Let's make it clear that that refers to
seconds.
> attestation: show unit of time for retry message

- Library/Homebrew/attestation.rb
- Library/Homebrew/formula_installer.rb
-----
This is another attempt to iteratively improve the UX around operational attestation failures: it checks whether the failure is caused by a missing `attestation` subcommand, and directs the user to update `gh` as a resolution. This should be sound, since `brew upgrade gh` is exempt from the bootstrap cycle.
Example output:
```
$ brew install cowsay
==> Downloading https://formulae.brew.sh/api/formula.jws.json
###################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
###################################################### 100.0%
Warning: cowsay has been deprecated because it has an archived upstream repository! It will be disabled on 2024-11-22.
==> Downloading https://ghcr.io/v2/homebrew/core/cowsay/manif …
```
> attestation: specialize error on incompatible gh

- Library/Homebrew/tap_auditor.rb
-----
We audit all other formulae lists and this allows identifying when a removed formulae has leftover/outdated references.
In future, may want to refactor autobump handling to give it its own DSL so that we can explicitly label certain formulae as non-autobumped for a specific reason (e.g. upstream autobumps, consistently broken for last bump attempts, etc.)
> tap_auditor: check formulae names in autobump.txt

- Library/Homebrew/os/mac/pkgconfig/10.11/bzip2.pc
- Library/Homebrew/os/mac/pkgconfig/10.12/bzip2.pc
- Library/Homebrew/os/mac/pkgconfig/10.13/bzip2.pc
- Library/Homebrew/os/mac/pkgconfig/10.14/bzip2.pc
- Library/Homebrew/os/mac/pkgconfig/10.15/bzip2.pc
- Library/Homebrew/os/mac/pkgconfig/11/bzip2.pc
- Library/Homebrew/os/mac/pkgconfig/12/bzip2.pc
- Library/Homebrew/os/mac/pkgconfig/13/bzip2.pc
- Library/Homebrew/os/mac/pkgconfig/14/bzip2.pc
- Library/Homebrew/os/mac/pkgconfig/15/bzip2.pc
- Library/Homebrew/test/os/mac/pkgconfig_spec.rb
-----
Mainly since the only way to avoid bundled `bzip2` in rust formulae is via `pkg-config` - https://github.com/alexcrichton/bzip2-rs/blob/master/bzip2-sys/build.rs#L16-L23
Similar to pkgconfig file created inside `bzip2` formula based on https://gitlab.com/bzip2/bzip2/-/blob/master/bzip2.pc.in (note that we currently only ship shared libraries & pkg-config file on Linux, so using brew `bzip2` is particularly bad option on macOS).
Removed `bindir=` and `-I${includedir}` in Cflags.
---
Only added macOS 15 for initial discussion. If acceptable, can add older macOS versions.
> os/mac/pkgconfig: add bzip2.pc for rust formulae

- .github/workflows/pkg-installer.yml
-----
Followup on https://github.com/Homebrew/brew/pull/18089, I'll add the docker part again later.
> feat: add attestation to the pkg installer

- Library/Homebrew/cmd/install.rb
- Library/Homebrew/install.rb
If the intention is to overwrite any existing links, then `brew install` should go on to install over an unlinked formula
-----
> feat: Install an unlinked formula via `brew install` if `--overwrite`  is passed

- Library/Homebrew/extend/ENV/super.rb
-----
This avoids using bundled libraries for:
* `hidapi`[^1]
* `pynacl`[^2]
* `pyzmq`[^3]
The build should now fail if dependency is missing.
Essentially reverses default so now that using bundled copy is now opt-in via `ENV` modification, e.g. `ENV.delete "SODIUM_INSTALL"`
[^1]: https://github.com/trezor/cython-hidapi/blob/0.14.0.post2/setup.py#L229
[^2]: https://github.com/pyca/pynacl/blob/1.5.0/setup.py#L71-L73
[^3]: https://github.com/zeromq/pyzmq/blob/v26.2.0/CMakeLists.txt#L41-L43
> extend/ENV/super: use brew libs for some Python packages

- Library/Homebrew/cask/installer.rb
- Library/Homebrew/cmd/gist-logs.rb
- Library/Homebrew/cmd/install.rb
- Library/Homebrew/cmd/reinstall.rb
- Library/Homebrew/cmd/upgrade.rb
- Library/Homebrew/extend/os/linux/install.rb
- Library/Homebrew/install.rb
When formulae were installed as a dependency to a cask, the preinstall checks were bypassed.
This opened up various issues, such as https://github.com/Homebrew/homebrew-cask/pull/188060 but also other issues such as installing the wrong architecture or unexplained failures due to missing system requirements.
> Perform preinstall checks when a formula is installed via a cask

- Library/Homebrew/unpack_strategy.rb
-----
Otherwise the files will be unpacked with group wheel on macOS which gets copied over when running `cp -al`.
This used to be implicitly "fixed" due to `cp -pR` usage which would recreate the files.
After #18497, files that are copied via `cp -al` retain wheel group, which isn't what we want.
Was exploring another alternative in #18518 but this seems like cleaner option.
---
Probably should move the logic to `utils/` or somewhere else that can be shared to avoid code duplication. Perhaps a follow up as would be good to avoid current bottles getting installed as wheel group.
> unpack_strategy: fix unpack Dir.mktmpdir group

- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/utils/github/actions.rb
-----
Calls to `opoo` and `onoe` produce duplicate `Warning:` and `Error:`
messages in CI logs because we print something to stdout and print an
annotation. Annotations also produce `Error:` and `Warning:` lines in
the log.
Let's fix this by skipping printing the message if we've already printed
an annotation.
> extend/kernel: fix duplicate messages in GitHub Actions

- Library/Homebrew/cmd/shellenv.sh
- docs/Shell-Completion.md
-----
This PR adds the brew zsh site-functions directory to the fpath during `brew shellenv`, allowing us to enable completions in one line instead of the seven currently suggested on the [Shell Completions](https://docs.brew.sh/Shell-Completion) page.
The shell-completions documentations page states we don't do this by default because managing completions is complex. This is true, however, I still think it's fair to pick the low-hanging-fruit on behalf of the user; many installations already call `compinit` on their behalf, and by including the homebrew fpath we can give those users completions for free. Remaining users only need to call compinit (assuming they have shellenv already setup). 
If this gets accepted, I can make another PR to update the docs, suggesting users eval the …
> shellenv: Add zsh site-functions to `fpath`

- Library/Homebrew/cmd/upgrade.rb
-----
Resolves #18226
The `--build-from-source` flag can currently be used without specifying a formula by name but it doesn't behave the way you'd expect it to.
It will upgrade everything using bottles if they are available and skip building things from source. This is intentional because we want to discourage non-developers from building packages from source since the result is less predictable.
The change here is to error out in that case. It might be smarter to go through the entire deprecation cycle here just in case someone is using this in scripts.
> cmd/upgrade: require named args when upgrading from source

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/tap.rb
- Library/Homebrew/tap_constants.rb
-----
Hi there folks!
I'm currently taking care of my GitHub Action [action-homebrew-bump-formula](https://github.com/dawidd6/action-homebrew-bump-formula) and wanted to move my test formulae from separate repository to the same repository where the action is stored.
I've run into an issue, because the repository is not named _properly_ (i.e. `$USER/homebrew-$TAP`), `brew bump-formula-pr` would try to access non-existent repository named for example `dawidd6/tap`, it depends how I cloned the tap of course. I've tracked it down to this changed line. Didn't test it on homebrew-core, but I think it should work the same as for my repository.
Steps to reproduce:
1. `brew tap dawidd6/tap https://github.com/dawidd6/action-homebrew-bump-formula.git`
2. `brew bump-formula-pr --no-audit --no-browse …
> dev-cmd/bump-formula-pr: always use full git repo as tap remote

- Library/Homebrew/env_config.rb
- Library/Homebrew/formula_installer.rb
- docs/Manpage.md
- manpages/brew.1
`HOMEBREW_FORBIDDEN_LICENSES` now actually checks for valid SPDX license identifiers rather than requiring the user to guess.
When an identifier is invalid, it will be ignore and warned about instead.
> Improve/fix HOMEBREW_FORBIDDEN_LICENSES handling

- Library/Homebrew/formula.rb
- Library/Homebrew/mktemp.rb
- Library/Homebrew/unpack_strategy.rb
-----
Was looking into #18548 and thought we could avoid some duplication by adjusting `Mktemp`.
In this case, the other PR would use
```rb
Mktemp.new("homebrew-unpack").run(chdir: false) do |tmp_unpack_dir|
tmp_unpack_dir = T.must(tmp_unpack_dir.tmpdir)
```
---
This PR does restrict arguments for `Mktemp` so no longer an accept an arbitrary hash but instead takes in specific boolean parameters.
I think this is fine as it is a private API, but can restore `opts` if preferred.
> mktemp: strict type and allow `#run` without chdir

- Library/Homebrew/utils/curl.rb
-----
`#curl_http_content_headers_and_checksum` contains code that works with a `Content-Type` header in a response but it expects there to always be only one header in the response. This is normally a reasonable assumption but we've come across a server that is giving a response with multiple `Content-Type` headers in the response (https://github.com/Homebrew/homebrew-cask/pull/189072), so this produces an error and causes `brew audit` to fail when checking the URL.
This works around the issue by naively using the last `Content-Type` header in the response when there's more than one. It's not something that should normally occur but this will handle the situation when it does.
> curl: handle multiple Content-Type headers

- Library/Homebrew/test/unpack_strategy/directory_spec.rb
- Library/Homebrew/unpack_strategy.rb
- Library/Homebrew/unpack_strategy/directory.rb
-----
`mv` should preserve hardlinks and allow faster unpack on the same filesystem. A secondary pass is done with `cp` to copy over attributes onto any existing directories.
We only run this for nested unpacks as most direct Directory strategy usage is for repositories where moving files breaks existing code.
This uses `cp -pR` for non-move as some potential user reported issues could be due to Apple's `cp -l` on specific macOS versions. Can consider re-adding `cp -l` with better handling for older macOS.
---
This improves performance when pouring bottles if user has brew installed on same filesystem as `/tmp` directory (~1.2-1.4x when tested via `brew reinstall` which means direct `brew install`).
---
macOS `mv` man page says:
```
As the rename(2) call does not work across file systems, …
```
> unpack_strategy/directory: use mv for nested unpack

- Library/Homebrew/formula_installer.rb
-----
Addresses #18554. When upgrading formulae, [`check_install_sanity`](https://github.com/Homebrew/brew/blob/3291ad4fc78f33f8e9bb7ce37745d2a0e697f5fb/Library/Homebrew/formula_installer.rb#L295) is called, which seems to walk the dependency tree for a formula to create a [full list of dependencies](https://github.com/Homebrew/brew/blob/3291ad4fc78f33f8e9bb7ce37745d2a0e697f5fb/Library/Homebrew/formula_installer.rb#L369) and then - when determining the unsatisfied pinned dependencies - [filters out](https://github.com/Homebrew/brew/blob/3291ad4fc78f33f8e9bb7ce37745d2a0e697f5fb/Library/Homebrew/formula_installer.rb#L381) the dependencies tagged as `build`. A problem with this is that build dependencies might have other non-build dependencies themselves, which won't be tagged as `build` but …
> filter pinned test dependencies

- Library/Homebrew/bundle_version.rb
-----
This PR fixes an issue when comparing two `BundleVersion` objects where the `version` variables are equal and the `short_version` variables are `nil`. In this case, the result of the initial `version` comparison should be returned.
Before:
```console
$ brew livecheck --cask teamviewer
Error: teamviewer: comparison of Array with Array failed
```
After:
```console
$ brew livecheck --cask teamviewer
teamviewer: 15.58.4 ==> 15.58.4
```
> Fix `BundleVersion` comparison when `short_version` is not comparable

- docs/Homebrew-on-Linux.md
> doc: improve clarity by removing redundant word in Homebrew-on-Linux.md

- docs/Prose-Style-Guidelines.md
-----
archive.org is broken and this is causing our Documentation CI to fail. Given that this style guide doesn't exist in form we used, I'm removing this link.
> Prose-Style-Guidelines: remove archive.org link

- Library/Homebrew/rubocops/shared/url_helper.rb
* Allow http://download(s).sourceforge.net to be used as a plain HTTP mirror if the HTTPS equivalent is present
* Ban download(s).sf.net as it always does a HTTPS -> HTTP redirect
> rubocops/shared/url_helper: tweak SourceForge handling

- Library/Homebrew/utils/lock.sh
macOS 15 adds `lockf`. This allows us to remove our last dependency on `/usr/bin/ruby`.
> utils/lock: use new lockf where available

- Library/Homebrew/formula.rb
-----
This change adds support for compiler flags (`gcflags`) as standard arguments in Go builds, enabling better control over compilation behavior.
So, instead of:
```rb
*std_go_args(
ldflags: "-w -s"
) + ["-gcflags=all=-l -B -wb=false"]
```
You can pass them as arguments:
```rb
*std_go_args(
ldflags: "-w -s",
gcflags: "all=-l -B -wb=false",
)
```
> Go: Add `-gcflags` to `std_go_args`

- Library/Homebrew/extend/os/mac/keg_relocate.rb
Our dylib changes actively break the Swift formula: https://github.com/Homebrew/homebrew-core/actions/runs/11510812283/job/32043670032?pr=195510.
The Swift formulae ships with a stdlib with a dylib ID to `/usr/lib/swift`. This is intentional as it means that `-lswiftCore` will link to `/usr/lib/swift` while still providing the stdlib dylibs as an opt-in or other internal use. Upstream ship it this way in their official builds.
Ideally we'd generalise this check better, e.g. maybe any path not in `HOMEBREW_PREFIX` or the build directory? For now, I've scoped it to Swift so it doesn't impact anything except Swift.
> os/mac/keg_relocate: don't change Swift stdlib dylib IDs

- Library/Homebrew/extend/os/mac/keg_relocate.rb
- Library/Homebrew/keg_relocate.rb
```
Error: Parameter 'id': Expected type String, got type NilClass
Caller: /opt/homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:31
Definition: /opt/homebrew/Library/Homebrew/os/mac/keg.rb:6 (Keg#change_dylib_id)
```
While we're here, since runtime TypeErrors are usually an indication of insufficient static typing, fix up signatures so that the static typechecker could catch this bug in the future.
> keg_relocate: fix error when dylib_id doesn't need changing

- Library/Homebrew/livecheck/livecheck.rb
- Library/Homebrew/test/livecheck/livecheck_spec.rb
-----
Up to now, we haven't been accounting for `#url` symbol arguments in `livecheck` blocks that don't reference a checkable URL. This can either be an invalid symbol (e.g., using the `:stable` formula symbol in a cask) or a valid symbol where the referenced URL doesn't exist (e.g., using `:head` when there's no `head` URL). [Almost all of the valid symbols are required URLs but `head` is optional.]
Over the years, we've had a handful of slips where we've [used `:url` in formulae](https://github.com/Homebrew/homebrew-core/pull/195414) (when it's only valid in casks) and [`:stable` in casks](https://github.com/Homebrew/homebrew-cask/pull/189215) (when it's only valid in formulae). In this scenario, `livecheck_url_string` is `nil`, so livecheck falls back to `#checkable_urls`. `stable` …
> livecheck: error on invalid url symbol

- Library/Homebrew/test.rb
-----
Intended mainly for third-party formulae, this allows formula tests to be run with a customised timeout.
This is a private, undocumented API and subject to change.
> Add `HOMEBREW_TEST_TIMEOUT_SECS` env var

- Library/Homebrew/test/spec_helper.rb
- Clarify the comment of why we have SimpleCov special logic for parallel tests
- use a nicer ParallelTests API for checking which process to output the coverage format on
> spec_helper: improve parallel test handling.

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- No. Should I add a new test for this? It seems that this was introduced by 587f4ba11bc7be30ece7a5ceae10e3395fdf131 but the commit didn't add any new tests.
-----
The error message:
Error: Parameter 'formula': Expected type String, got type Formulary::FormulaNamespace87ec47e7f9dec2f39e30adcc9fdea28fb57606eab88d4f83e8ebec591964143c::ApacheArrow with value #<Formula apache-arrow (sta...ore/Formula/a/apache-arrow.rb>
Caller: /opt/homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:152
Definition: /opt/homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:417 (Homebrew::DevCmd::BumpFormulaPr#check_for_mirrors)
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11618/lib/types/configuration.rb:296:in `call_validation_error_handler_default' …
> dev-cmd/bump-formula-pr: fix type error

- .github/workflows/actionlint.yml
-----
Port of Homebrew/homebrew-core#195961.
See https://github.com/woodruffw/zizmor.
> workflows/actionlint: run `zizmor`

- .github/workflows/pkg-installer.yml
-----
Fixes https://github.com/Homebrew/brew/security/code-scanning/34
Fixes https://github.com/Homebrew/brew/security/code-scanning/35
Fixes https://github.com/Homebrew/brew/security/code-scanning/36
Fixes https://github.com/Homebrew/brew/security/code-scanning/37
Fixes https://github.com/Homebrew/brew/security/code-scanning/38
Fixes https://github.com/Homebrew/brew/security/code-scanning/39
> workflows/pkg-installer: fix `template-injection` warnings

- .github/workflows/vendor-version.yml
-----
Fixes https://github.com/Homebrew/brew/security/code-scanning/40
Fixes https://github.com/Homebrew/brew/security/code-scanning/41
> workflows/vendor-version: fix `template-injection` warnings

- Library/Homebrew/macos_version.rb
- Library/Homebrew/test/macos_version_spec.rb
-----
This will be used by `llvm` (and, presumably, in the future, versioned
LLVM formulae). The idea is that we will write a config file for each OS
version pointing to the correct SDKROOT so that `llvm` does not require
rebuilding/reinstalling when a user upgrades to a new major version of
macOS.
See Homebrew/homebrew-core#196094.
> macos_version: add `KERNEL_MAJOR_VERSIONS` map

- Library/Homebrew/os.rb
-----
This avoids the overhead of shelling out.
> os: use native ruby calls for `uname`

- Library/Homebrew/extend/os/linux/diagnostic.rb
Follow-up from https://github.com/Homebrew/brew/pull/18677#pullrequestreview-2406775293 due to user-reported breakage in https://github.com/Homebrew/brew/issues/18643
> os/linux/diagnostic: remove XDG_DATA_DIRS.

- Library/Homebrew/test/utils/inreplace_spec.rb
- Library/Homebrew/test/utils/string_inreplace_extension_spec.rb
- Library/Homebrew/utils/inreplace.rb
- Library/Homebrew/utils/string_inreplace_extension.rb
-----
Can replace some occurrences of:
```rb
inreplace <file> do |s|
s.sub! before, after
end
```
Also increase test coverage.
> utils/inreplace: allow non-global substitution

- Library/Homebrew/github_runner_matrix.rb
-----
We give our ARM runners half the timeout of the Intel runners because
the ARM runners are faster. However, this is no longer true for
dependent testing because we test recursive dependents on ARM but skip
them on Intel.
This means that we can often hit the timeout on ARM but have all jobs
finish on Intel. We can re-run these with the long build label, but
that's a bit wasteful of our limited long build slots.
Instead, let's just use the same timeout value across ARM and Intel
runners when testing dependents: 2 hours.
> github_runner_matrix: extend timeout for dependent tests on arm64

- Library/Homebrew/formula_auditor.rb
-----
We've discussed migrating `pkg-config` to `pkgconf` a couple times, e.g. https://github.com/Homebrew/homebrew-core/pull/194885
One of requirements is retaining compatibility with wide usage of `depends_on "pkg-config"` which seems to be best handled through an alias and this audit exception.
> formula_auditor: allow `pkg-config` alias for `pkgconf` migration

- Library/Homebrew/brew.rb
Since APFS is case-insensitive by default, Ruby will load the command file if user passes it mixed-case, but invoking it later will fail.
-----
> Downcase internal commands

- Library/Homebrew/language/python.rb
- Library/Homebrew/test/language/python/virtualenv_spec.rb
-----
Seems okay to make default. Been a couple years since I added this and haven't seen any issues with ones we've manually enabled. May as well expose the man pages if they are already installed and manually disable any that cause issues.
> language/python: link manpages by default

- Library/Homebrew/tap.rb
-----
Discovered in https://github.com/Homebrew/homebrew-cask/pull/191078
The audit fails due to a specific HTTP error, on two URLs within the one cask.
Presently, it isn't possible to pass two URLs to a single token via an array in the audit_exception list because the value isn't read.
This PR correctly parses the array.
> tap: allow an array of values for an audit exception

- Library/Homebrew/os/mac.rb
-----
We're currently returning the first match for `com.apple.dt.Xcode`,
which could be any version if a user has multiple installed.
Instead, let's try to find the newest if all our results have an
`Info.plist` that we can interrogate for the version.
Maybe resolves #18736?
For reference, on my system, before this change:
```
❯ brew ruby -e 'puts MacOS.app_with_bundle_id("com.apple.dt.Xcode")'
/Applications/Xcode-14.3.1.app
```
after this change:
```
❯ brew ruby -e 'puts MacOS.app_with_bundle_id("com.apple.dt.Xcode")'
/Applications/Xcode.app
```
> os/mac: prefer newest Xcode when searching using `mdfind`

- Library/Homebrew/extend/os/linux/hardware/cpu.rb
-----
Information taken from https://github.com/llvm/llvm-project/blob/1bf385f10291101163a346c8f075d56e1578351b/llvm/lib/TargetParser/Host.cpp
> linux/hardware/cpu: add some missing Intel CPUs

- Library/Homebrew/extend/os/linux/hardware/cpu.rb
- Library/Homebrew/test/hardware/cpu_spec.rb
-----
Follow-up to #18743.
- Add a `cpu_model` parameter on `amd_family`
- Differentiate between Zen 1 and 2, as well as Zen 3 and 4
- Add Zen 5
- While we're here, add missing families/models (both AMD and Intel) into `cpu_spec.rb`
> linux/hardware/cpu: add some missing AMD CPUs

- Library/Homebrew/cask/cask.rb
- Library/Homebrew/cask/cask.rbi
- Library/Homebrew/cask/dsl.rb
- Library/Homebrew/cask/info.rb
- Library/Homebrew/deprecate_disable.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/sorbet/rbi/dsl/formula.rbi
- Library/Homebrew/test/deprecate_disable_spec.rb
- Library/Homebrew/test/support/fixtures/cask/everything.json
-----
Addresses https://github.com/Homebrew/brew/issues/18294.
A replacement may be specified like so:
```ruby
deprecate! date: "2024-01-10", because: :repo_removed, replacement: "ffmpeg"
```
which yields something like
```console
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew info alac
==> alac: stable 0.2.0 (bottled)
Basic decoder for Apple Lossless Audio Codec files (ALAC)
https://web.archive.org/web/20150319040222/craz.net/programs/itunes/alac.html
Deprecated because it has a removed upstream repository! It will be disabled on 2025-01-10.
Consider replacing it with:
brew install ffmpeg
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/a/alac.rb
License: MIT
==> Analytics
install: 8 (30 days), 34 (90 days), 110 (365 days)
install-on-request: 8 (30 days), 34 (90 …
```
> deprecate_disable: support optional replacement parameter

- Library/Homebrew/env_config.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/env_config.rbi
- Library/Homebrew/utils/git.rb
- Library/Homebrew/utils/github.rb
-----
Our autobump workflow sets the author and committer to the user who
triggered the workflow, defaulting to @BrewTestBot for scheduled runs.
This can be confusing for maintainers when GitHub shows up as
"Unverified" because the commit is signed with @BrewTestBot's key.[^1]
Let's fix that by configuring our autobump workflow to always commit as
@BrewTestBot, so that the committer matches the GPG signature. To do
that, we need to add support for setting `GIT_COMMITTER_NAME` and
`GIT_COMMITTER_EMAIL`.
[^1]: See, for example, Homebrew/homebrew-core#197234.
> Support setting `GIT_COMMITTER_NAME` and `GIT_COMMITTER_EMAIL`

- Library/Homebrew/tap_auditor.rb
-----
Audit renames so we remove old ones that can no longer be resolved to an actual formula/alias, ~~further renames, or a tap migration.~~ EDIT: remove support for latter and instead require cleaning those old renames.
```console
❯ brew audit --tap homebrew/core --only tap_formula_lists
homebrew/core
* formula_renames.json references
formulae or casks that are not found in the homebrew/core tap.
Invalid formulae or casks: antlr@2, elasticsearch@6, gcc@5, gcc@6, gnuplot@4, perl@5.18, tomcat@7, v8@3.15, wxwidgets@3.0
Error: 1 problem in 1 tap detected.
```
> tap_auditor: check renamed formula exists

- .github/workflows/actionlint.yml
This uses `|| true` to suppress zizmor's exit code, which is being surfaced as a failure due to the workflow wide `set -e` default.
-----
> actionlint: suppress zizmor's exit code

- Library/Homebrew/extend/os/mac/diagnostic.rb
-----
This configuration is not supported. Let's make `brew doctor` complain
about it.
> os/mac/diagnostic: check for OpenCore

- docs/Acceptable-Casks.md
-----
Let's replace this with something consistent that doesn't need to be updated every year. If a cask can't be installed on the current major macOS version, we shouldn't accept it.
> Acceptable-Casks: remove outdated info

- Library/Homebrew/extend/os/mac/diagnostic.rb
> os/mac/diagnostic: fix OpenCore check

- Library/Homebrew/extend/os/linux/extend/ENV/shared.rb
- Library/Homebrew/hardware.rb
-----
On Linux, `-march=native` is added in the optflags when building from source (and not for a bottle). This works fine for the case where users install `brew` in a custom prefix on a supported architecture, but breaks the case where the user is building from source for running under Linux on an unsupported architecture for which the `-march=native` flag is not valid (I specifically ran into this issue while tinkering with `brew` under Ubuntu on RISC-V).
Introduce a new optimization flag option `none` and adjust `effective_arch` to only fall back on `:native` if running on Intel or ARM (which are not the only architectures which support `-march=native`, but it does cover all existing supported use cases and leaves room for current development/experimentation happening with `brew` on …
> shared: only fall back to -march=native on supported architectures

- Library/Homebrew/extend/os/mac/diagnostic.rb
-----
This is based on https://github.com/Homebrew/brew/pull/18765#issuecomment-2474056438.
> os/mac/diagnostic: improve OpenCore check

- Library/Homebrew/extend/os/linux/extend/ENV/shared.rb
- Library/Homebrew/hardware.rb
-----
Follow-up to https://github.com/Homebrew/brew/pull/18759. This helps catch the case of building bottles when the CPU type is `dunno` (in this case, `Hardware.oldest_cpu` returns `:dunno`).
Without this, the flag `-march=dunno` is passed when using the `cc` shim, which really doesn't work for any architecture.
> hardware: rename none optimization flags to dunno

- Library/Homebrew/utils/github.rb
-----
Resolves #18610 by implementing the suggested solution:
> Ignoring any SSO (i.e. extensions contains saml_failure) errors for that specific API call only. SAML errors for other API calls are likely genuine and should continue to error.
`extensions` doesn't appear to be present on this response when an SSO error is thrown. Instead, a check is performed to determine if the error message contains "SAML"; if so, the error is disregarded. I understand "SAML" may be too wide of a filter- please suggest a more narrow alternative if that is the case.
> fix: `too_many_open_prs()` fails without SSO access

- Library/Homebrew/test/uninstall_spec.rb
- Library/Homebrew/uninstall.rb
-----
This was discussed a while back on Slack. The idea behind this is that ignoring dependencies during `brew uninstall` makes it too easy to break things, even for developers. Those who know what they are doing can, and IMO should, always use the `--ignore-dependencies` flag.
> uninstall: don't ignore deps even for developers

- Library/Homebrew/dev-cmd/generate-cask-ci-matrix.rb
-----
CI for casks is also run on pushes to master, which should be a `syntax-only` job, in this case we shouldn't require an argument, as neither a cask token, or a PR url is available. I couldn't think of a better way to deal with this case.
> generate-cask-ci-matrix-syntax: allow no argument for syntax-only jobs

- .devcontainer/devcontainer.json
For development it feels like it makes sense to use the master image.
While we're here, let VSCode autoformat the devcontainer.json.
> devcontainer.json: use master image.

- Library/Homebrew/formula_installer.rb
-----
Since #18562, installing from source via the API doesn't download from a mirror if the original is unreachable. Re-initializing `downloadable_object` seems to fix this. (🎩 @Bo98)
Note that this only works for `brew install -s`, and not for `brew fetch -s`.
Before:
```
$ tail -n 1 /etc/hosts
127.0.0.1   ftp.gnu.org
$ brew install -s libunistring
libunistring 1.2 is already installed but outdated (so it will be upgraded).
==> Fetching libunistring
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/bcf0b597f2caa3342586ca5e0d2379b2337b7a56/Formul
Already downloaded: /Users/eric/Library/Caches/Homebrew/downloads/027cce73171392f3c59ccae026aaad023c190d1dadcce6b9ee572f6a5eb2804e--libunistring.rb
==> Downloading …
```
> formula_installer: re-enable mirror usage when installing via API

- Library/Homebrew/formula.rb
- Library/Homebrew/requirement.rb
- Library/Homebrew/standalone/sorbet.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/test/formula_validation_spec.rb
- Library/Homebrew/test/requirement_spec.rb
-----
We have a few methods marked `:final`:
```
$ git grep 'sig(:final)'
Library/Homebrew/downloadable.rb:  sig(:final) { returns(T::Boolean) }
Library/Homebrew/formula.rb:  sig(:final) {
Library/Homebrew/requirement.rb:  sig(:final) {
Library/Homebrew/requirement.rb:  sig(:final) { returns(T::Boolean) }
Library/Homebrew/requirement.rb:  sig(:final) {
```
However, per sorbet [docs](https://sorbet.org/docs/final), enforcement requires an incantation of `T::Configuration.enable_final_checks_on_hooks` setup.
I've made that change here, added a test that a specific finalized method can't be overriden, and done some other minor sorbet tuning.
> Enforce finalized sorbet methods

- Library/Homebrew/cmd/vendor-install.sh
- Library/Homebrew/download_strategy.rb
- Library/Homebrew/resource.rb
-----
Previously, [adding `--insecure` was necessary](https://github.com/Homebrew/brew/pull/12172) for curl to download the [ca-certificates .pem file](https://curl.se/ca/cacert-2024-09-24.pem) on older macOS versions. At some point since then, the way Homebrew downloads this file was changed in a way that happens to allow stock curl on macOS 10.11 & 10.12 (`curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8`) to download it during installation without needing `--insecure`.
This would have gone unnoticed, except that now adding `--insecure` actively prevents downloading from servers whose certificates rely on SNI because of a [quirk of Secure Transport](https://github.com/curl/curl/issues/998):
```
$ /usr/bin/curl --disable --cookie /dev/null --globoff …
```
> revert setting `--insecure` to download ca-certificates

- Library/Homebrew/requirement.rb
- Library/Homebrew/test/requirement_spec.rb
-----
Partial revert of https://github.com/Homebrew/brew/pull/16640/files#diff-b75efe9741aed6830d257b35e55eb243a38c7b187774b42cf26be6deef8990db
We only [enabled](https://github.com/Homebrew/brew/pull/18801) `:final` enforcement two days ago, which has caused GH Action failures, e.g. https://github.com/Homebrew/homebrew-core/actions/runs/11991937306/job/33431223236?pr=198784#step:3:322
> Remove problematic :final from Requirement sigs

- Library/Homebrew/download_strategy.rb
- Library/Homebrew/lock_file.rb
- Library/Homebrew/test/lock_file_spec.rb
-----
Saw this error here: https://github.com/reitermarkus/dotfiles/actions/runs/11988870070/job/33424635021#step:10:7165
When a download is interrupted at exactly the right time, that is after the `LockFile` object was created but before the lock file is actually created on disk, the `download_lock&.path&.unlink` step will fail.
This change ensures the `lock`/`unlock` methods themselves are never interrupted, and moves the `unlink` step into the `unlock` method as well, so we only remove the lock file if we actually hold the lock.
Also fixes another race condition which may happen if one process deletes a lock file after another already opened it.
> Fix incorrect download locking.

- Library/Homebrew/cli/named_args.rb
- Library/Homebrew/cmd/uses.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formula.rbi
- Library/Homebrew/test/cmd/uses_spec.rb
-----
Relates to https://github.com/Homebrew/brew/issues/18777
Replaces the use of `OpenStruct` in the `uses` command with a `T::Struct`. AFAICT, the OpenStruct defined all the necessary methods, so it isn't necessary to introduce add'l functionality. 
(Some other minor cleanup is included.)
> Remove OpenStruct from Uses cmd

- Library/Homebrew/formula_installer.rb
-----
Currently it's not possible to upgrade previously installed formulae that are now disabled. Let's allow that with `--force`.
> formula_installer: allow installing/upgrading disabled formulae

- Library/Homebrew/cask/artifact/abstract_uninstall.rb
- Library/Homebrew/cask/artifact/moved.rb
- Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb
I haven't been able to reproduce these but they make plausible sense at least:
```
==> Backing App 'Chromium.app' up to '/opt/homebrew/Caskroom/chromium/904870/chrome-mac/Chromium.app'
cp: /Applications/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/94.0.4591.0/settings.dat: Permission denied
```
```
==> Removing launchctl service com.docker.helper
==> Removing launchctl service com.docker.socket
Not privileged to remove service.
```
> cask: try fix a couple of permission edge cases under multi-user

- Library/Homebrew/rubocops/uses_from_macos.rb
-----
I think `jq` was added in Sequoia:
```console
❯ /usr/bin/jq --version
jq-1.6-159-apple-gcff5336-dirty
```
So could use it as dependency via `uses_from_macos "jq", since: :sequoia`
Probably not going to make formula `keg_only` so adding to UsesFromMacos rather than ProvidedByMacos given comment:
```
```
> rubocops/uses_from_macos: allow using Sequoia `jq`

- Library/Homebrew/formula_auditor.rb
-----
As we should use the actual dependency `pkgconf` rather than the alias.
Almost ready:
* https://github.com/Homebrew/homebrew-core/pull/199271
* https://github.com/Homebrew/homebrew-core/pull/199382
* https://github.com/Homebrew/homebrew-core/pull/199241
* https://github.com/Homebrew/homebrew-core/pull/199243
> formula_auditor: avoid `pkg-config` dependency in core tap

- Library/Homebrew/dev-cmd/generate-man-completions.rb
-----
The original `ronn`-based manpage generator would backdate the generated date if the target file existed. That was dropped when `ronn` was replaced with Kramdown in #16868. This change restores the idea by having `generate-man-completions` also fail if there are no changes or only the date is changed, which should eliminate the monthly automated date-updating PRs like #18846.
> generate-man-completions: also fail if only date changed

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/cask/cask.rbi
- Library/Homebrew/cask/dsl.rb
- Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
- Library/Homebrew/dev-cmd/bump.rb
- Library/Homebrew/dev-cmd/irb.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/livecheck.rb
- Library/Homebrew/livecheck/livecheck.rb
- Library/Homebrew/livecheck/skip_conditions.rb
- Library/Homebrew/resource.rb
- Library/Homebrew/rubocops/cask/no_overrides.rb
- Library/Homebrew/sorbet/rbi/dsl/cask/dsl.rbi
- Library/Homebrew/sorbet/rbi/dsl/formula.rbi
- Library/Homebrew/test/cask/audit_spec.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/test/livecheck/livecheck_spec.rb
- Library/Homebrew/test/livecheck/skip_conditions_spec.rb
- Library/Homebrew/test/livecheck_spec.rb
- Library/Homebrew/test/resource_spec.rb
- Library/Homebrew/test/rubocops/livecheck/regex_parentheses_spec.rb
- Library/Homebrew/test/rubocops/livecheck/skip_spec.rb
- Library/Homebrew/test/rubocops/livecheck/url_provided_spec.rb
- Library/Homebrew/test/rubocops/livecheck/url_symbol_spec.rb
-----
Formulae, casks, and resources have a `#livecheckable?` method that indicates whether they contain a `livecheck` block. This is intended to be read as "has a livecheckable?", not "is livecheckable?" (as livecheck can find versions for some packages/resources without a `livecheck` block). Unfortunately, correct understanding of this method's behavior [outside of documentation] relies on historical knowledge that few people possess, so this is often confusing to anyone who hasn't been working on livecheck since 2020.
In the olden days, a "livecheckable" was a Ruby file containing a `livecheck` block (originally a hash) with a filename that corresponded to a related formula. The `livecheck` blocks in livecheckable files were integrated into their respective formulae in August 2020, so …
> livecheck: clarify livecheckable language

- Library/Homebrew/cmd/update.sh
-----
Checking for `HOMEBREW_NO_INSTALL_CLEANUP` was added in #18825, but this
breaks developers by switching them to the stable branch.
Setting `HOMEBREW_NO_UPDATE_CLEANUP` when `HOMEBREW_NO_INSTALL_CLEANUP`
is set seems like a relatively recent addition, so I don't think it
hurts to just remove it. We can add it back (correctly) if there are
users that need it.
> cmd/update: avoid switching developers to `stable` branch

- Library/Homebrew/completions/bash.erb
Add Bash completion support for Homebrew aliases:
https://github.com/Homebrew/homebrew-aliases
Unfortunately I'm not familiar enough neither with Ruby, nor with Fish/Zsh 🤷🏻
Fixes https://github.com/Homebrew/homebrew-aliases/issues/91
- It somewhat exists: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/completions_spec.rb#L303-L316
-----
> feat: Add Bash completion for Homebrew aliases

- Library/Homebrew/service.rb
- Library/Homebrew/test/service_spec.rb
-----
systemd configs, like all UNIX text files, should end with a new line.
> service: end systemd configs with a new line

- Library/Homebrew/cli/named_args.rb
- Library/Homebrew/cmd/info.rb
- Library/Homebrew/cmd/reinstall.rb
- Library/Homebrew/cmd/tab.rb
- Library/Homebrew/cmd/tap.rb
- Library/Homebrew/dev-cmd/bump-cask-pr.rb
- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/dev-cmd/create.rb
- Library/Homebrew/dev-cmd/determine-test-runners.rb
- Library/Homebrew/dev-cmd/extract.rb
- Library/Homebrew/dev-cmd/pr-pull.rb
-----
- Part of https://github.com/Homebrew/brew/issues/17297
- Relates to https://github.com/Homebrew/brew/issues/18777
(I also grouped the private methods together, which is the bulk of the second commit, for ease of review.)
The code is sometimes a bit loose with conflating `Keg`s with `Formula`. I chose the path of least refactor where that came up, but it might create some hiccups as we roll this out.
> Enable strict typing in NamedArgs

- Library/Homebrew/formula.rb
- Library/Homebrew/pkg_version.rb
- Library/Homebrew/test/pkg_version_spec.rb
This required:
- adding signatures/types where missing
- ensuring that we respect the signature of `Version.new`
- remove some non-Sorbet type checks
- fixing the exception in tests
- removing some tests now caught by Sorbet
- fixing `Formula#prefix` so it works as intended with correct type usage
> pkg_version: make `typed: strict`

- Library/Homebrew/attestation.rb
- Library/Homebrew/test/attestation_spec.rb
-----
GitHub's Artifact Attestations feature began putting multiple subjects in a single bundle yesterday. This broke our assumption that each attestation has only one subject. To fix this, we generalize our search of the attestation's subject from just the first subject name to any name in the subject set.
This should fix the behavior observed in https://github.com/Homebrew/homebrew-core/issues/177384#issuecomment-2521141910 and below.
See also: https://github.blog/changelog/2024-12-04-artifact-attestations-now-support-multiple-subjects/
> attestation: handle multiple subjects

- Library/Homebrew/dev-cmd/update-maintainers.rb
-----
Currently, accented characters are sorted after the non-accented alphabet, which is why "Štefan Baebler" ends up at the end of the list. This change sorts the list of names on each letter's non-accented variant instead.
> update-maintainers: ignore accents when sorting names

- .github/workflows/docs.yml
This should allow us to make use of the GitHub merge queue to ensure that we're not merging outdated code (or breaking `master`) but avoiding the need to continually merge into/rebase PR branches.
This should be safe to merge as-is as is essentially a no-op without the merge queue enabled.
> workflows/docs: enable merge queue/group jobs.

- Library/Homebrew/cli/args.rb
- Library/Homebrew/cli/named_args.rb
- Library/Homebrew/cli/parser.rb
- Library/Homebrew/formulary.rb
-----
Relates to https://github.com/Homebrew/brew/issues/18777
I cleaned up some unnecessary `unsafe` and active-support-ish code in the CLI, to help with https://github.com/Homebrew/brew/pull/18847
Because of how the code is coupled to `Formulary`, I did the same there as well. I find the resulting code better to follow as well, there was a lot of `options` munging to avoid `nil` passing. (I think that strategy can be beneficial when used occasionally, but not so much in this specific instance.)
> Remove unsafe references from CLI and Formulary code

- Library/Homebrew/service.rb
-----
This was originally added in https://github.com/Homebrew/brew/pull/18865.
```console
$ brew ruby -e 'p "activemq".f.service.to_systemd_unit'
/usr/local/Homebrew/Library/Homebrew/service.rb:458:in `block in to_systemd_unit': uninitialized constant Utils::Service (NameError)
from /usr/local/Homebrew/Library/Homebrew/service.rb:458:in `map'
from /usr/local/Homebrew/Library/Homebrew/service.rb:458:in `to_systemd_unit'
from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11685/lib/types/private/methods/call_validation.rb:278:in `bind_call'
from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11685/lib/types/private/methods/call_validation.rb:278:in `validate_call'
from …
```
> Add missing utils/service require

- Library/Homebrew/livecheck/strategy/pypi.rb
- Library/Homebrew/test/livecheck/strategy/pypi_spec.rb
-----
Right now, pypi strategy is crawling the page for checking the latest version, but we should just use json to find out the latest version.
```
$ curl -s https://pypi.org/pypi/mkvtomp4/json | jq -r '.info.version'
2.0
```
> fix(livecheck/pypi): update to use json endpoint to query version

- Library/Homebrew/cli/args.rb
- Library/Homebrew/cli/error.rb
- Library/Homebrew/cli/parser.rb
-----
Extracts unrelated updates from https://github.com/Homebrew/brew/pull/18847 by request:
- Move error classes to a dedicated file
- Replace `cli_args` with a more idiomatic ruby implementation
> Minor CLI code improvements

- Library/Homebrew/cask/artifact/abstract_uninstall.rb
-----
This showed a confusing message when the trash path was able to be deleted using sudo since the untrashable array was updated but the check was higher up for returning early.
```
==> Trashing files:
/Users/Shared/Maxon
/Users/Shared/Red Giant
~/Library/Application Support/Maxon
~/Library/Application Support/Red Giant
~/Library/Caches/net.maxon.app-manager
~/Library/Preferences/Maxon
~/Library/Preferences/net.maxon.app-manager.plist
~/Library/Saved Application State/net.maxon.app-manager.savedState
==> Using sudo to gain ownership of path '/Users/Shared/Maxon'
==> Using sudo to gain ownership of path '/Users/Shared/Red Giant'
Warning: The following files could not be trashed, please do so manually:
==> Removing all staged versions of Cask 'maxon'
```
The warning about files not …
> cask/artifact/abstract_uninstall: handle sudo trashed paths correctly

- Library/Homebrew/livecheck/strategy/json.rb
- Library/Homebrew/livecheck/strategy/pypi.rb
- Library/Homebrew/test/livecheck/strategy/json_spec.rb
- Library/Homebrew/test/livecheck/strategy/pypi_spec.rb
-----
This is a follow-up to https://github.com/Homebrew/brew/pull/18895. We recently updated the `Pypi` strategy to use the PyPI JSON API and the default strategy behavior no longer relies on a regex, so the initial implementation didn't include regex handling. This restores support for a `livecheck` block regex by updating the `DEFAULT_BLOCK` logic to handle an optional regex. This allows us to use a regex to omit parts of the `info.version` value without having to duplicate the default block logic in a `strategy` block only to use a regex.
This isn't currently necessary for any existing formulae using the `Pypi` strategy but we have a few that needed a custom regex with the previous strategy approach, so they may need this functionality in the future. Besides that, restoring regex …
> Pypi: Restore regex support

- Library/Homebrew/dev-cmd/tap-new.rb
- Library/Homebrew/utils/github/api.rb
- Library/Homebrew/utils/uid.rb
Homebrew largely operates under the model where EUID == Homebrew owner (proxy) and UID == requesting user.
This cross-user model doesn't really work well with `brew tap-new` which does git commits. This PR fixes it so that it can read the author information of the requesting user.
Known issue (that realistically won't be fixed): on macOS, this will not work with Xcode 14.0 through 14.2. On Linux (or I guess old Homebrew Git installs on macOS too potentially) this will not work with any (potentially distro-patched) system Git <2.39 that have the safe directory changes but didn't backport `-c safe.directory` support. This however isn't a regression from the previous state where it still didn't work anyway, and can be fixed by using Homebrew git.
> dev-cmd/tap-new: improve handling of multi-user setups

- Library/Homebrew/formula.rb
…
-----
relates to:
- https://github.com/Homebrew/homebrew-core/pull/200589
- https://github.com/Homebrew/homebrew-core/pull/200591
- https://github.com/Homebrew/homebrew-core/pull/200593
- https://github.com/Homebrew/homebrew-core/pull/200595
I have also tested out for some node formulae, works good
```
/opt/homebrew/Library/Homebrew/ignorable.rb:27:in `block in raise'
RuntimeError: No universal binaries found to deuniversalize
```
> chore(formula): raise error if no universal binaries are found to deuniversalize

- .github/workflows/actionlint.yml
- .github/workflows/docker.yml
- .github/workflows/docs.yml
- .github/workflows/tests.yml
We're currently doing both which doubles the number of jobs we end up running for commits on `master`.
> github/workflows: use merge_group instead of push events.

- Library/Homebrew/cmd/list.rb
- completions/zsh/_brew
-----
Fixes https://github.com/Homebrew/brew/issues/18908#issuecomment-2532926860.
> cmd/list: support using `--full-name` with `--installed-on-request` et al.

- Library/.rubocop.yml
- Library/Homebrew/cask/config.rb
- Library/Homebrew/cli/args.rb
- Library/Homebrew/cli/args.rbi
- Library/Homebrew/cli/parser.rb
- Library/Homebrew/cmd/search.rb
- Library/Homebrew/dev-cmd/audit.rb
- Library/Homebrew/dev-cmd/bump.rb
- Library/Homebrew/dev-cmd/livecheck.rb
- Library/Homebrew/extend/os/linux/cli/parser.rb
- Library/Homebrew/extend/os/parser.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/cmd/tap_cmd.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/audit.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/bump.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/create.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/dispatch_build_bottle.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/livecheck_cmd.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/pr_automerge.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/pr_publish.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/pr_pull.rbi
- Library/Homebrew/sorbet/tapioca/compilers/args.rb
- Library/Homebrew/test/abstract_command_spec.rb
- Library/Homebrew/test/cask/upgrade_spec.rb
- Library/Homebrew/test/sorbet/tapioca/compilers/args_spec.rb
-----
Resolves https://github.com/Homebrew/brew/issues/18777
- Retains the `@table` attr that OpenStruct used, but it is now exclusively for args (not metadata like `named` and `remaining`). I'm open to renaming the attr.
- `missing_method` dispatch is removed, only defined methods are allowed
- A generic `set_arg` method is provided, to allow setting args from the parser. There is no corresponding getter, because I want to encourage explicit invocations. The usual ruby escape hatches (e.g. `instance_variable_get`) are available if needed 😞.
- Within the args class, I've replaced arg lookup methods with `@table` lookups, because the methods aren't necessarily defined. It's a bit of an eyesore, but IMO preferable to defining them unnecessarily, or using `respond_to?` guards.
> Remove OpenStruct from CLI::Args

- Library/Homebrew/cask/artifact/uninstall.rb
- Library/Homebrew/cask/utils.rb
- Library/Homebrew/github_packages.rb
- Library/Homebrew/manpages.rb
- Library/Homebrew/utils/gzip.rb
-----
Just some repo hygiene 🪥
> Namespace some top-level constants

- Library/Homebrew/cask/info.rb
- Library/Homebrew/cmd/info.rb
- Library/Homebrew/test/cask/info_spec.rb
-----
This should fix #18915 and is an attempt to fix forward so we don't have to rollback https://github.com/Homebrew/brew/pull/18847 since this seems like a minor issue.
This seems like it was a bug before the recent change to remove OpenStruct from `Homebrew::CLI::Args` but it was failing silently before. Now we pass the args to the `Cask::Info.info` method so that when they eventually reach the `Utils::Analytics.output_analytics` method they are present as expected.
Note that this error requires `HOMEBREW_NO_ANALYTICS` to not be set and `--verbose` to be passed along with `brew info CASK`.
Example error fragment:
```console
$ set -e HOMEBREW_NO_ANALYTICS
$ brew info iterm2 --cask --verbose
==> iterm2: 3.5.10 (auto_updates)
https://iterm2.com/
Installed
/usr/local/Caskroom/iterm2/3.5.4 …
```
> cask/info: send missing args after removing openstruct

- Library/Homebrew/utils/github.rb
-----
Related to issue seen while working on https://github.com/Homebrew/homebrew-core/pull/198115 and temporary alternative CODEOWNERS in https://github.com/Homebrew/homebrew-core/pull/201069
Before
```ruby
brew(main):001> GitHub.get_pull_request_changed_files("Homebrew/homebrew-core", 198115).size
=> 30
brew(main):002> GitHub.get_pull_request_changed_files("Homebrew/homebrew-core", 198115).last["filename"]
=> "Formula/l/leela-zero.rb"
```
After
```ruby
brew(main):001> GitHub.get_pull_request_changed_files("Homebrew/homebrew-core", 198115).size
=> 77
brew(main):002> GitHub.get_pull_request_changed_files("Homebrew/homebrew-core", 198115).last["filename"]
=> "Formula/z/znc.rb"
```
> utils/github: handle over 30 changed files

- .github/workflows/actionlint.yml
- .github/workflows/codeql-analysis.yml
-----
I accidentally pinned to the wrong hashes in https://github.com/Homebrew/brew/pull/18929.
> workflows: fix mis-pinned codeql-action hashes

- Library/Homebrew/formula.rb
- Library/Homebrew/test/formula_spec.rb
-----
In most cases, when running `generate_completions_from_executable` with a formula's `bin`/`sbin` executable, the resulting completion is usually intended for the executable itself.
From a quick glance, this should avoid majority of `base_name` overrides in Homebrew/core. Formulae that use `register-python-argcomplete` may still need an override (e.g. `azure-cli`, `commitizen`)
---
For non-`bin`/`sbin` executables, the original default of formula name is used as these have higher chance of being an intermediary/helper executable, e.g. `libexec/"bin/register-python-argcomplete"` (`azure-cli`) or a helper `go` script (`caddy`)
> formula: conditionally use executable name as completion name

- Library/Homebrew/cask/installer.rb
- Library/Homebrew/extend/os/cask/installer.rb
- Library/Homebrew/extend/os/linux/cask/installer.rb
- Library/Homebrew/extend/os/linux/cli/parser.rb
- Library/Homebrew/test/cli/parser_spec.rb
-----
This is the first step to allowing font (and later binary) casks to be installable on Linux.
TODO:
> feat: only block cask install on Linux

- Library/Homebrew/formula.rb
-----
Add `:clap` shell parameter format for rust binaries with the `clap_complete` crate as documented here.
- https://docs.rs/clap_complete/4.5.39/clap_complete/env/index.html
Related issue:
- https://github.com/Homebrew/homebrew-core/pull/200162
I have skipped for tests, it depends on the external one same as `:click` case.
> formula: add clap completion style

- Library/Homebrew/shims/mac/super/pkgconf
-----
Since we switched to `pkgconf`, it is possible that a build tool may use it before `pkg-config` so make sure both shims are available.
---
Not specifically likely, but just in case. Also handles running `pkgconf` directly in formula.
May want to update `pkg-config` shim later on (e.g. so actual executable is found on shim-excluded superenv's PATH rather than hardcoded).
Or perhaps seeing if `pkgconf` is willing to support the environment variables overrides as those are less intrusive in build than shim.
> shims/mac/super: add `pkgconf` symlink

- Library/Homebrew/os/mac/pkgconfig/15/expat.pc
-----
Saw failure in another PR probably from https://github.com/actions/runner-images/commit/45226c1116cdb863fcc3804d00c9aaaedb270b52
---
```console
❯ grep VERSION /Library/Developer/CommandLineTools/SDKs/MacOSX15.2.sdk/usr/include/expat_config.h
#define PACKAGE_VERSION "2.6.3"
#define VERSION "2.6.3"
```
> os/mac/pkgconfig/15: update expat version for 15.2

- .github/workflows/tests.yml
These weren't looking in the right place.
While we're here, let's name the step more descriptively, too.
> workflows/tests: fix RSpec JUnit XML filenames.

- Library/Homebrew/patch.rb
-----
Before https://github.com/Homebrew/brew/pull/18613, we used `safe_system` which would print stderr by default. After switching to `Utils.safe_popen_write`, stderr/stdout is captured in the exception and discarded.
This had caused some confusion in PRs as the resulting logs don't clearly explain failure.
Current `brew` output looks like:
```
==> Patching
==> Applying b6cf2e7222c24343b868986e867ddb7adad0bf30.patch
READ THIS: https://docs.brew.sh/Troubleshooting
```
With change, the output is shown to user, e.g.
```
==> Patching
==> Applying b6cf2e7222c24343b868986e867ddb7adad0bf30.patch
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
patching file 'src/fastnetmon.cpp'
2 out of 2 hunks failed--saving rejects to 'src/fastnetmon.cpp.rej'
patching …
```
> patch: restore output from failed patch

- Library/Homebrew/test/download_strategies/abstract_spec.rb
-----
`Mktemp.new` doesn't run anything so test was skipped.
Could use `Mktemp.new(...).run` instead but most tests already use `mktmpdir`
> test/download_strategies/abstract_spec: fix test

- .github/workflows/tests.yml
We need to do this (again) to:
- populate the cache from the latest master (so it can be used in other branches/PRs/merge groups)
- send coverage/test flakiness information to CodeCov/BuildPulse on `master` builds
> workflows/tests: run some jobs (again) on push.

- .github/dependabot.yml
-----
- A PR every day for each of `sorbet`, `sorbet-runtime` and `sorbet-static-and-runtime` is a bit much.
- Based on https://github.com/dependabot/dependabot-core/blob/6e4d9d8532939a683168e59b0620d4c2b1e33621/.github/dependabot.yml#L12-L17.
> dependabot: Group Sorbet updates together

- Library/Homebrew/cmd/tap.rb
-----
Make `brew tap -f` == `brew tap --force`.
* Current behavior is to reject `-f` with `Error: ambiguous option: -f`, however the only conflict is the disabled `--full` flag.
* Improve consistency: `tap` is the only command with a `--force` option that isn't explicitly aliased w/ `-f` (see: `git grep 'switch.*"--force"' Library/Homebrew`)
> tap command: add -f alias to --force flag

- Library/Homebrew/cask/installer.rb
- Library/Homebrew/deprecate_disable.rb
- Library/Homebrew/test/deprecate_disable_spec.rb
-----
Add more typing before working on #18661
> deprecate_disable: `typed: strict`

- Library/Homebrew/formula.rb
-----
We have received multiple bug reports from users complaining that `brew`
tells them to install the CLT when they already have Xcode installed.
See, for example, #18976.
Let's try to avoid these issues from being opened by making the error
message more explicit that we require the CLT at a specific location,
and that installing Xcode does not suffice.
> formula: update `pour_bottle?` CLT error message

- Library/Homebrew/utils/shared_audits.rb
When a formula or cask is written on the `github_prerelease_allowlist.json`, prerelease is allowed but interestingly it prohibits regular release. I think this should be also allowed too.
Here is an example.
- https://github.com/Homebrew/homebrew-cask/pull/193893
`utm@beta` cask has a version `4.6.1` but `utm` is now `4.6.3`. On my thought,  `beta`  branch should always have more up to date version than the normal branch and so it should be `4.6.3` not `4.6.1`.
---
-----
> update prerelease check to allow standard release

- Library/Homebrew/utils/shared_audits.rb
I think my previous PR broke the version check logic,
- https://github.com/Homebrew/brew/pull/19001
Here is the failed actions
- https://github.com/Homebrew/homebrew-core/actions/runs/12514067679/job/34911068323?pr=202542
- https://github.com/Homebrew/homebrew-core/actions/runs/12514611522/job/34911059619?pr=202532
and noticed that the exception should exist. 😥
---
-----
> fix prerelease check to allow standard release

- Library/Homebrew/env_config.rb
-----
Before:
```
❯ HOMEBREW_NO_ANALYTICS=0 brew formula-analytics --days-ago=2
Error: Calling HOMEBREW_NO_ANALYTICS=0 is deprecated! Use If you wish to enable HOMEBREW_NO_ANALYTICS, use HOMEBREW_NO_ANALYTICS=1
If you wish to disable HOMEBREW_NO_ANALYTICS, use HOMEBREW_NO_ANALYTICS= instead.
```
After:
```
❯ HOMEBREW_NO_ANALYTICS=0 brew formula-analytics --days-ago=2
Error: Calling HOMEBREW_NO_ANALYTICS=0 is deprecated! Use HOMEBREW_NO_ANALYTICS=1 to enable and HOMEBREW_NO_ANALYTICS= (an empty value) to disable instead.
```
> env_config: Improve the deprecated envvar message

- Library/Homebrew/livecheck/strategy/xorg.rb
- Library/Homebrew/test/livecheck/strategy/xorg_spec.rb
-----
The `mesa` formula currently uses a mesa.freedesktop.org/archive/ `stable` URL but it redirects to archive.mesa3d.org. [Upstream links to archive.mesa3d.org](https://docs.mesa3d.org/download.html) as the location to find Mesa releases, so we should update the formula URLs accordingly.
This updates the `Xorg` strategy to be able to handle archive.mesa3d.org URLs, so livecheck will continue to be able to check `mesa` without needing a one-off `livecheck` block. [This would also work for `mesalib-glw` (which has an archive.mesa3d.org `stable` URL) but that formula is deprecated.]
> Xorg: Handle archive.mesa3d.org URLs

- Library/Homebrew/cask/download.rb
- Library/Homebrew/cask/installer.rb
- Library/Homebrew/test/cask/download_spec.rb
- don't care about no checksums being defined for official casks
- don't complain about Gatekeeper being disabled on GitHub Actions as it's been globally disabled by the GitHub Actions team
> cask: fewer GitHub Actions warnings.

- Library/Homebrew/extend/ENV/super.rb
-----
Setting PKG_CONFIG_LIBDIR overrides compiled default. This helps reduce opportunistic linkage when pkg-config call finds modules installed on system but not included in a formula's dependency tree.
---
The default on Linux is:
* `#{HOMEBREW_PREFIX}/lib/pkgconfig`
* `#{HOMEBREW_PREFIX}/share/pkgconfig`
* `#{HOMEBREW_LIBRARY}/Homebrew/os/linux/pkgconfig`
Removing first 2 are needed to avoid opportunistic linkage. The final path doesn't exist.
On macOS, PKG_CONFIG_LIBDIR is:
https://github.com/Homebrew/brew/blob/e9b0285c14c77fb2ed22ad831bb727ee9ae5abd7/Library/Homebrew/extend/os/mac/extend/ENV/super.rb#L29
> extend/ENV/super: always set PKG_CONFIG_LIBDIR

- Library/Homebrew/livecheck.rb
- Library/Homebrew/livecheck/livecheck.rb
-----
This PR adds a new `livecheck` strategy, `FormulaLatest`. This will be used in formulae where the latest versions of the resources are identical to the latest version of the formula itself. For example, consider the resource `presto-cli` in `prestodb`:
```ruby
resource "presto-cli" do
...
livecheck do
strategy :formula_latest
end
end
```
This gives:
```console
➜  homebrew-core git:(master) ✗ brew lc -dvr --autobump prestodb
...
Resource:         presto-cli
livecheck block?: Yes
URL:              None
Strategies:       FormulaLatest
Strategy:         FormulaLatest
Cached?:          Yes
Matched Versions:
0.290 => #<Version:0x0000000103d81338 @version="0.290", @detected_from_url=false>
prestodb: 0.290 ==> 0.290
presto-cli: 0.290 ==> 0.290
```
Once this is merged, I'll work on …
> livecheck: allow parent formula reference in resources

- Library/Homebrew/api.rb
- Library/Homebrew/env_config.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/env_config.rbi
If set, this will update the Homebrew API formula or cask data even if `HOMEBREW_NO_AUTO_UPDATE` is set.
This is useful in cases where you want to update the cached API data but don't want to update Homebrew itself.
> Add `HOMEBREW_FORCE_API_AUTO_UPDATE`

- Library/Homebrew/brew.sh
- Library/Homebrew/env_config.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/global.rb
- Library/Homebrew/mktemp.rb
- Library/Homebrew/sandbox.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/env_config.rbi
- Library/Homebrew/startup/config.rb
- Library/Homebrew/style.rb
- Library/Homebrew/test/support/lib/startup/config.rb
- bin/brew
Allow the ability for a system administrator to use `HOMEBREW_BREW_WRAPPER` and `HOMEBREW_FORCE_BREW_WRAPPER` variables to enforce the usage of a particular `brew` command for non-trivial (e.g. `brew --prefix` is considered trivial, it doesn't need to write to the prefix) Homebrew commands.
This also introduces a `HOMEBREW_ORIGINAL_BREW_FILE` variable for some internal usage; `HOMEBREW_BREW_FILE` was being used internally for both "how should we shell out to Homebrew" and "what should we use to check permissions on Homebrew". `HOMEBREW_ORIGINAL_BREW_FILE` is now used just for the latter case.
Inspired by conversation in <https://github.com/Homebrew/homebrew-bundle/pull/1551> which suggested this was worth fixing in wider than just `brew bundle`.
> Add support for Homebrew wrappers

- .github/workflows/sponsors-maintainers-man-completions.yml
We haven't run any commands that would have modified the working directory yet so this will better handle issues with stale files.
Fixes failing CI on `master`.
> workflows/sponsors-maintainers-man-completions: force checkout.

- Library/Homebrew/brew.sh
- Library/Homebrew/env_config.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/env_config.rbi
- handle reading from variables that may not be defined yet
- fix incorrect `env_config.rbi` file entry
- avoid unnecessary handling of defined variables
- add `HOMEBREW_NO_FORCE_BREW_WRAPPER` to disable `HOMEBREW_FORCE_BREW_WRAPPER` functionality if needed
> Fix `HOMEBREW_*BREW_WRAPPER` behaviour

- bin/brew
This can fail when running `bin/brew` under `set -u`.
> bin/brew: handle unbound variable.

- .github/dependabot.yml
This should reduce the amount of PR spam we get.
If there's critical vulnerabilities: they will be updated more often.
> dependabot: update github-actions weekly.

- bin/brew
This can fail for users using `bash -u` or `set -u` in their shell so let's try to be stricter here for both them and us.
Related to https://github.com/Homebrew/brew/pull/19061
> bin/brew: don't allow unbound variables.

- Library/Homebrew/dev-cmd/tests.rb
-----
`brew tests --coverage` can fail to produce coverage information when run on a small number of tests (e.g., `--only utils/curl`). We use `ParallelTests::last_process?` in `tests/spec_helper.rb` to handle the SimpleCov output but due to the way the method is implemented, it doesn't work as expected if the number of processes is greater than one but lower than the number of cores.
For example, this is the current output for a small run (no coverage generated):
```
$ brew tests --only utils/curl --coverage
Randomized with seed 26057
1 process for 1 spec, ~ 1 spec per process
.........................................
Took 0 seconds
```
This is the output with this change (coverage generated as expected):
```
$ brew tests --only utils/curl --coverage
Randomized with seed 9280
Run …
```
> Disable parallel for small test coverage runs

- Library/Homebrew/github_packages.rb
-----
To reproduce: `brew pr-upload --no-commit --warn-on-upload-failure` in a directory with a few bottles where at least one is already uploaded to GitHub Packages.
For bottle uploads that would be skipped due to preupload_check warning about skipped uploads and returning early, the old code errored out due to JSON schema validation failure since the upload was allowed to resume:
"error"=>"value at /manifests/0/annotations/org.opencontainers.image.ref.name is not a string"
This change ensures that the upload is actually skipped if preupload_check returns no result.
> pr-upload: fix `--warn-on-upload-failure` functionality

- Library/Homebrew/cmd/update.sh
I accidentally typed `brew update --greedy` instead of `brew upgrade --greedy` and got some strange output.
This fix causes unrecognized long options to throw a usage message and exit like all the other subcommands.
Before:
```
% brew update --greedy
==> Updating Homebrew...
Usage: brew update-report [--auto-update] [--force]
The Ruby implementation of brew update. Never called manually.
[...]
```
After:
```
% brew update --greedy
Error: Unrecognized option '--greedy'
Usage: brew update, up [options]
Fetch the newest version of Homebrew and all formulae from GitHub using git(1)
and perform any necessary migrations.
[...]
```
> update.sh: reject unknown long opts

- Library/Homebrew/shims/super/cc
-----
The `cc` shim currently does not handle invocations where `--` is passed as an argument, which (conventionally) indicates that all following arguments be treated as positional (non-optional) arguments. As a result, any refurbished args may get appended after the `--` where they are erroneously treated as input file paths:
```
clang: error: no such file or directory: '-isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk'
clang: error: no such file or directory: '--sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk'; did you mean '--sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk'?
clang: error: no such file or directory: '-isystem/opt/homebrew/include'
clang: error: no such file or directory: …
```
> shims/super/cc: handle double dash in args

- Library/Homebrew/dev-cmd/unbottled.rb
---
Fixes #18993
The problem here was that it was unable to find the correct namespace.
It assumed the `MacOS` module was below the `Homebrew::DevCmd::Unbottled` class.
```sh
kevinrobell@kevinrobell-iMac ~ [1]> brew unbottled --tag arm64_sequoia --dependents -v vtk
==> Populating dependency tree...
==> :arm64_sequoia bottle status
Error: uninitialized constant Homebrew::DevCmd::Unbottled::MacOS
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/unbottled.rb:242:in `block (2 levels) in output_unbottled'
/home/kevinrobell/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/set.rb:501:in `each_key'
/home/kevinrobell/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/set.rb:501:in `each'
/home/kevinrobell/.asdf/installs/ruby/3.3.6/lib/ruby/3.3.0/delegate.rb:87:in `all?' …
```
> dev-cmd/unbottled: fix module resolution error

- Library/Homebrew/cmd/leaves.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/reinstall.rb
- Library/Homebrew/tab.rb
- Library/Homebrew/upgrade.rb
These can return `true`, `false` or `nil` so adjust the signature to note this and fix the call sites to ensure we don't accidentally pass through `nil` values when we shouldn't.
While we're here, make a `TODO` to fix this bad API up in future.
Fixes https://github.com/Homebrew/brew/issues/19076
> Fix usage of `Tab#installed_(on_request|as_dependency)`

- Library/Homebrew/brew.rb
- Library/Homebrew/build.rb
- Library/Homebrew/cask/dsl/depends_on.rb
- Library/Homebrew/cmd/update-report.rb
- Library/Homebrew/dev-cmd/test.rb
- Library/Homebrew/download_queue.rb
- Library/Homebrew/download_strategy.rbi
- Library/Homebrew/extend/os/mac/readall.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/ignorable.rb
- Library/Homebrew/migrator.rb
- Library/Homebrew/postinstall.rb
- Library/Homebrew/readall.rb
- Library/Homebrew/reinstall.rb
- Library/Homebrew/resource_auditor.rb
- Library/Homebrew/tap.rb
- Library/Homebrew/test.rb
- Library/Homebrew/test/commands_spec.rb
- Library/Homebrew/test/macos_version_spec.rb
- Library/Homebrew/test/rubocops/patches_spec.rb
- Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb
- Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
- Library/Homebrew/test/utils/inreplace_spec.rb
- Library/Homebrew/test/utils/spdx_spec.rb
- Library/Homebrew/test/utils/string_inreplace_extension_spec.rb
- Library/Homebrew/utils/fork.rb
-----
- Needed for #18842.
- [I said I’d do this “over Christmas”](https://github.com/Homebrew/brew/pull/18842#pullrequestreview-2518685547) and it’s no longer Christmas, but I’ve finally done most of it!
- The remaining failures here are as follows. Has anyone got any ideas of good comments for why these disables exist?
```
cask/artifact/abstract_artifact.rb:58:28: C: Cop/DisableComment: Add a clarifying comment to the RuboCop disable comment
@@sort_order ||= [ # rubocop:disable Style/ClassVars
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
download_strategy.rb:711:24: C: Cop/DisableComment: Add a clarifying comment to the RuboCop disable comment
def initialize(path) # rubocop:disable Lint/MissingSuper
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lazy_object.rb:13:5: C: Cop/DisableComment: Add a clarifying …
```
> Add clarifying comments to `rubocop:disable`s

- Library/Homebrew/cask/cask.rb
If we don't have permissions to read it, this will raise an exception even although this whole call chain is very tolerant of nil values.
> cask/cask: ensure plist is readable before reading.

- Library/Homebrew/cask/cask_loader.rb
- Library/Homebrew/cask/url.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/github_packages.rb
- Library/Homebrew/test/download_strategies/curl_spec.rb
- Library/Homebrew/test/utils/curl_spec.rb
- Library/Homebrew/utils/analytics.rb
- Library/Homebrew/utils/curl.rb
- Library/Homebrew/utils/github.rb
- Library/Homebrew/utils/github/api.rb
- Library/Homebrew/utils/pypi.rb
- Library/Homebrew/utils/repology.rb
- Library/Homebrew/utils/shared_audits.rb
-----
This upgrades `utils/curl.rb` to `typed: strict`, which requires a number of changes to pass `brew typecheck`. The most straightforward are adding type signatures to methods, adding type annotations (e.g., `T.let`) to variables that need them, and ensuring that methods always use the expected return type.
I had to refactor areas where we call a `Utils::Curl` method and use array destructuring on a `SystemCommand::Result` return value (e.g., `output, errors, status = curl_output(...)`), as Sorbet doesn't understand implicit array conversion. As suggested by Markus, I've switched these areas to use `#stdout`, `#stderr`, and `#status`. This requires the use of an intermediate variable (`result`) in some cases but this was a fairly straightforward substitution.
I also had to refactor …
> Curl: Use `typed: strict`

- .gitignore
-----
The current structure of `.gitignore`  requires gems to be explicitly ignored. I've found this approach has a few issues:
- [Failures](https://github.com/Homebrew/brew/actions/runs/12719887056/job/35460770945#step:8:70) when dependencies change are confusing
- Cruft accumulates when gems are no longer in the `Gemfile.lock` dependency tree (`bootsnap`, `byebug`, `colorize` appear to be just a few)
- The [list](https://github.com/Homebrew/brew/tree/master/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems) of gems to vendor is much more concise.
There's a potential new failure mode here: if a vendored gem adds a new dependency, that transitive dependency will need to be added to the `.gitignore`. I _think_ CI will catch that, though I'm not positive.
I tested this by adding gems to the …
> Restructure .gitignore gem handling

- .gitignore
Reverts Homebrew/brew#19106
This is causing CI failures and has broken the Vendor Gems workflow. Reverting to unblock CI.
> Revert "Restructure .gitignore gem handling"

- Library/Homebrew/cask/artifact/moved.rb
- Library/Homebrew/cask/config.rb
- Library/Homebrew/cask/installer.rb
- Library/Homebrew/cask/quarantine.rb
- Library/Homebrew/extend/os/cask/artifact/moved.rb
- Library/Homebrew/extend/os/cask/config.rb
- Library/Homebrew/extend/os/cask/quarantine.rb
- Library/Homebrew/extend/os/linux/cask/artifact/moved.rb
- Library/Homebrew/extend/os/linux/cask/config.rb
- Library/Homebrew/extend/os/linux/cask/installer.rb
- Library/Homebrew/extend/os/linux/cask/quarantine.rb
- Library/Homebrew/extend/os/mac/cask/artifact/moved.rb
- Library/Homebrew/extend/os/mac/readall.rb
- Library/Homebrew/os/linux.rb
- Library/Homebrew/os/mac.rb
- Library/Homebrew/test/os/linux_spec.rb
-----
This should disable quarantine on Linux, allow installing fonts and set a location for the fonts. Marking this as draft until I've had a moment to test it.
Waiting for https://github.com/Homebrew/brew/pull/18808 to be merged
> feat: allow font install on linux

- Library/Homebrew/extend/os/linux/extend/ENV/super.rb
- Library/Homebrew/shims/super/cc
-----
These are the things that I identified when playing with Portable Ruby on ARM64 Linux.
> Add support for bottling Portable Ruby for ARM64 Linux

- Library/Homebrew/diagnostic.rb
Usually, the subdirectory name is sufficient info, and the full file list is just noise.
This reduces `brew doctor` output clutter, making it easier for user to paste, and maintainers to parse.
Before:
```
$ brew doctor
[...]
Unexpected header files:
/usr/local/include/node/cppgc/allocation.h
/usr/local/include/node/cppgc/common.h
/usr/local/include/node/cppgc/custom-space.h
/usr/local/include/node/cppgc/garbage-collected.h
/usr/local/include/node/cppgc/heap.h
/usr/local/include/node/cppgc/internal/accessors.h
/usr/local/include/node/cppgc/internal/api-constants.h
/usr/local/include/node/cppgc/internal/compiler-specific.h
/usr/local/include/node/cppgc/internal/finalizer-trait.h
/usr/local/include/node/cppgc/internal/gc-info.h
/usr/local/include/node/cppgc/internal/logging.h …
```
> diagnostic: elide stray filenames in subdirs

- docs/Formula-Cookbook.md
As discussed in https://github.com/Homebrew/homebrew-core/pull/204366, this documents the specific case, where your program writes an error to stderr that needs to be checked in a test (e.g., using `assert_match` and `shell_output`):
* https://github.com/Homebrew/brew/issues/5149
> Document stderr redirection for shell_output tests

- docs/Tips-N'-Tricks.md
I brought this up several months ago and got a solution working that's been running on my work machine since early September without failure.
Possible additions:
* A statement expressing any limitations on supporting this configuration
* A statement, perhaps in a comment, limiting the tip to the idea and that it should not be an ever-growing HOWTO for every artifact hosting system.
-----
> Adds caching proxy example using HOMEBREW_ARTIFACT_DOMAIN

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
This PR allows `bump-formula-pr` to autobump resources with a livecheck block referencing the parent formula (see #19040). I haven't added tests because it seems like there are no tests anyway for `bump-formula-pr`, but I've tested that this feature works as intended on a couple formula such as:
* `prestodb`: "run of the mill" resource
* `audacious`: resource is within a `stable` block
* `erlang`: resource has mirror URLs, other non-matched resources exist
* `clang-format`: multiple such resources
Will do some more testing in a while with other formulae. Where this will not work is when the resource URL encodes the resource version in an atypical way, e.g., `4_2_2` instead of `4.2.2` – the command will warn the user to bump such resources manually. Note that `bump-formula-pr` …
> dev-cmd/bump-formula-pr: automatically bump matched-version resources

- Library/Homebrew/utils/analytics.rb
- Library/Homebrew/utils/fork.rb
- Library/Homebrew/utils/pypi.rb
- Library/Homebrew/utils/shell.rb
- Library/Homebrew/utils/spdx.rb
- Library/Homebrew/utils/tty.rb
-----
- Let’s see what goes 💥.
> Bump some `utils/` files to Sorbet `typed: strict`

- Library/Homebrew/formula_installer.rb
Quieten a few warnings, messages and caveats if we're passing `--quiet` to `brew install`.
This also quiets an incorrect "Fetching" message that was being shown when installing from a local bottle.
> formula_installer: improve quiet output.

- Library/Homebrew/dev-cmd/tests.rb
Otherwise, various integration tests will fail under some configurations.
> dev-cmd/tests: disable forcing `brew` wrapper in tests.

- Library/Homebrew/test/utils/linkage_spec.rb
- Library/Homebrew/utils/linkage.rb
-----
This PR adds `Utils::check_binary_linkage`, which is a helper-function that is already used in [some (primarily Rust-based) formulae](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-core%20def%20check_binary_linkage&type=code).
The function is more or less copied verbatim, except types are loosened to accept `String` or `Pathname`. An optional `prefix` parameter can also be set to change the filtering behavior - this flag really only exists because we have to tweak the filtering behavior a bit in the test. Maybe we can just not do any filtering and that'll be fine - but for now I've kept it as close to the original as possible.
Open to suggestions all around, but I'm a bit extra miffed about:
- Where would be the best place to put this file, and the file name. There didn't …
> utils: add check_binary_linkage function

- Library/Homebrew/utils/analytics.rb
Fixes:
Error: Parameter 'days': Expected type String, got type Integer with value 30 Caller: /opt/homebrew/Library/Homebrew/utils/analytics.rb:273 Definition: /opt/homebrew/Library/Homebrew/utils/analytics.rb:412 (Utils::Analytics.table_output)
-----
> analytics: fix type error

- Library/Homebrew/rubocops/cask/ast/stanza.rb
- Library/Homebrew/rubocops/cask/desc.rb
- Library/Homebrew/rubocops/cask/discontinued.rb
- Library/Homebrew/rubocops/cask/discontinued.rbi
- Library/Homebrew/rubocops/cask/extend/node.rb
- Library/Homebrew/rubocops/cask/homepage_url_styling.rb
- Library/Homebrew/rubocops/cask/mixin/on_desc_stanza.rb
- Library/Homebrew/rubocops/cask/mixin/on_homepage_stanza.rb
- Library/Homebrew/rubocops/cask/stanza_grouping.rb
- Library/Homebrew/rubocops/cask/url.rb
- Library/Homebrew/rubocops/cask/url_legacy_comma_separators.rb
- Library/Homebrew/rubocops/cask/variables.rb
- Library/Homebrew/sorbet/rbi/dsl/rubo_cop/cask/ast/stanza.rbi
- Library/Homebrew/sorbet/tapioca/compilers/rubocop_cask_ast_stanza.rb
-----
- This includes a new Tapioca compiler for `RuboCop::Cask::AST::Stanza` dynamic methods like `caveats?`.
> Bump more Cask RuboCops to Sorbet `typed: strict`

- Library/Homebrew/brew.rb
- Library/Homebrew/extend/kernel.rb
- hide warnings when requiring files repeatedly on a case-insensitive filesystem and add reference to Ruby bugs
- add another case to check for command require failures
- also handle commands with `-` in them
Closes https://github.com/Homebrew/brew/pull/19150
Fixes #19125
> Fix handling of case-mistyped commands

- Library/Homebrew/utils/curl.rb
> utils/curl: fix `user_agent` types

- Library/Homebrew/cask/artifact/abstract_artifact.rb
- Library/Homebrew/download_strategy.rb
- Library/Homebrew/lazy_object.rb
- Library/Homebrew/utils.rb
(Sorry I created this PR originally with `gh pr create --fill`, I didn't realise that would create a PR with empty PR body)
-----
This PR should fix the last of the rubocop violations that are reported after #18842 is merged.
> implement fixes and comments for `DisableComment` rubocop

- Library/Homebrew/dev-cmd/bottle.rb
Fixes bootstrapping new bottles on a new OS/architecture.
> dev-cmd/bottle: don't install gnu-tar when not needed

- Library/Homebrew/cmd/tap.rb
-----
Current helptext describes original functionality of `brew tap --repair`, which was removed in 56cb3325a. Replace this with decription of current functionality.
> tap command: correct helptext for --repair

- Library/Homebrew/dev-cmd/livecheck.rb
-----
When all formulae provided to `livecheck` are in `autobump.txt`, we get an uninterpretable error message, which does not help diagnose what's going on:
```
➜  Homebrew git:(master) brew lc prestodb
Usage: brew livecheck, lc [options] [formula|cask ...]
Check for newer versions of formulae and/or casks from upstream. If no formula
or cask argument is passed, the list of formulae and casks to check is taken
from HOMEBREW_LIVECHECK_WATCHLIST or ~/.homebrew/livecheck_watchlist.txt.
--full-name                  Print formulae and casks with fully-qualified
names.
--tap                        Check formulae and casks within the given
tap, specified as user/repo.
--eval-all                   Evaluate all available formulae and casks,
whether installed or not, to check them.
--installed …
```
> dev-cmd/livecheck: improve error message when all formulae are autobumped

- Library/Homebrew/cask/artifact/installer.rb
This fixes handling `sudo` and EUID when using certain `script` commands on casks e.g. adobe-creative-cloud.
> cask/artifact/installer: don't reset uid if sudo is used.

- .github/workflows/docker.yml
> docker: fix comment for ubuntu 18 deprecation

- docs/BrewTestBot-For-Maintainers.md
-----
The rebottling process didn't have any documentation.
> Add rebottling documentation in BrewTestBot-For-Maintainers.md

- Library/Homebrew/github_packages.rb
It wasn't reading from the tab correctly.
> github_packages: fix oldest CPU variant on arm64 Linux

- Library/Homebrew/test/cmd/desc_spec.rb
-----
I was recently running `brew tests` without `--online` and I noticed that there was still one formulae.brew.sh request. I narrowed it down to a `brew desc` test, so this adds `:needs_network` to that test. As expected, `brew tests` doesn't make any network requests after this change unless `--online` is used.
> tests: add missing :needs_network argument

- Library/Homebrew/formula_creator.rb
Followup to #19173, which causes `brew create` to error out on the literal `python@x.y` dependency.
Related to #19240.
> formula_creator: depend on latest python

- Library/Homebrew/cask/cask.rb
- Library/Homebrew/cask/dsl.rb
- Library/Homebrew/test/support/fixtures/cask/everything.json
This PR adds an explicit `depends_on macos` line to any cask that does not have a `depends_on macos` line already.
See <https://github.com/Homebrew/brew/pull/19121>
CC: @SMillerDev, @bevanjkay
---
Note: right now this is kind of useless because there's no way to _not_ apply the macOS depndency, but once we add a way to say that a cask works on Linux, we should include a check for that here.
I've left this as a draft for now until that is added. Feel free, also, to take this commit into #19121 if it makes sense to do this over there
> Add implicit macOS dependency to casks without explicit `depends_on` stanza

- Library/Homebrew/dev-cmd/update-python-resources.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/update_python_resources.rbi
- Library/Homebrew/test/sorbet/tapioca/compilers/args_spec.rb
- Library/Homebrew/utils/pypi.rb
This is particularly useful for third-party Python formulae that have a ton of resources, not all of which may adhere to homebrew/core's strict policies. See #19240 for context.
I've also added logic that ignores `--ignore-errors` on `homebrew/core`, although I personally think this new behavior is also useful for mainline formula creation.
*Before:* error out on a single non-conforming resource, zero resource blocks added to formula, scary stacktrace (in debug mode).
*After:* all conforming resources added, all non-conforming resources identified in comments, error message at end, `brew` exits non-zero without scary stacktrace:-
```
% brew update-python-resources --ignore-errors gromgit/test/auto-coder || echo OOPS
==> Retrieving PyPI dependencies for "auto-coder==0.1.243"...
==> …
```
> update-python-resources: add option to ignore errors

- Library/Homebrew/brew.sh
Rather than just explaining what is happening, let's explain a bit more why this is happening and how to fix it.
> brew.sh: improve HOMEBREW_FORCE_BREW_WRAPPER error message

- Library/Homebrew/livecheck.rb
- Library/Homebrew/livecheck/livecheck.rb
- Library/Homebrew/livecheck/strategy.rb
- Library/Homebrew/livecheck/strategy.rbi
- Library/Homebrew/livecheck/strategy/crate.rb
- Library/Homebrew/livecheck/strategy/header_match.rb
- Library/Homebrew/livecheck/strategy/json.rb
- Library/Homebrew/livecheck/strategy/page_match.rb
- Library/Homebrew/livecheck/strategy/sparkle.rb
- Library/Homebrew/livecheck/strategy/xml.rb
- Library/Homebrew/livecheck/strategy/yaml.rb
- Library/Homebrew/test/livecheck/strategy_spec.rb
- Library/Homebrew/test/livecheck_spec.rb
- docs/Brew-Livecheck.md
-----
livecheck currently doesn't support `POST` requests but it wasn't entirely clear how best to handle that. I initially approached it as a `Post` strategy but unfortunately that would have required us to handle response body parsing (e.g., JSON, XML, etc.) in some fashion. We could borrow some of the logic from related strategies but we would still be stuck having to update `Post` whenever we add a strategy for a new format.
Instead, this implements `POST` support by borrowing ideas from the `using: :post` and `data` `url` options found in formulae. This uses a `post_form` option to handle form data and `post_json` to handle JSON data, encoding the hash argument for each into the appropriate format. The presence of either option means that curl will use a `POST` request.
With this …
> livecheck: Add support for POST requests

- docs/BrewTestBot.md
- docs/Creating-a-Homebrew-Issue.md
- docs/FAQ.md
- docs/Homebrew-brew-Maintainer-Guide.md
- docs/Interesting-Taps-and-Forks.md
- docs/Kickstarter-Supporters.md
- docs/Maintainer-Guidelines.md
- docs/Maintainers-Avoiding-Burnout.md
- docs/Migrating-A-Formula-To-A-Tap.md
- docs/New-Maintainer-Checklist.md
- docs/Prose-Style-Guidelines.md
- docs/Querying-Brew.md
- docs/Typechecking.md
- docs/Updating-Software-in-Homebrew.md
- docs/index.md
-----
- Part of https://github.com/Homebrew/brew/issues/19214.
- Most of these were fine still, apart from:
- FAQ: `hub` is less maintained than `gh`.
- Brew-Maintainer-Guide: link to GitHub docs on commit signing via GPG or SSH.
- Interesting-Taps-and-Forks: remove outdated information about `homebrew/core` being in `Library/Taps`.
- New-Maintainer-Checklist: remove outdated information about the `@members` team.
> Review some docs

- Library/Homebrew/utils/pypi.rb
---
Noticed from our autobump job that this was inserting an extra newline and failing `brew audit`: https://github.com/Homebrew/homebrew-core/actions/runs/13216218939/job/36895781679#step:6:1106
> utils/pypi: remove extra newline when updating resources

- .github/workflows/docker.yml
-----
I noticed that `master` images have not been updated since #18912:
```console
$ docker run --pull=always --rm -it homebrew/brew:master brew --version
master: Pulling from homebrew/brew
Digest: sha256:3812ffd9b728ce3d96a2a362ef33bed420d1dc73c7d96c93a8f8d2d4f10e6281
Status: Image is up to date for homebrew/brew:master
Homebrew 4.4.11-6-geae8d1b
Homebrew/homebrew-core (git revision 9610909d254; last commit 2024-12-10)
```
That is due to images no longer being built on `master` pushes. This change restores the previous behaviour.
> workflows/docker: continue to deploy `master` images

- Library/Homebrew/formula.rb
-----
Fix "can't modify frozen String" error if bottle requires Command Line Tools when installing/updating several packages, which causes install/update process failure. The plus was here to concatenate errors until the commit https://github.com/Homebrew/brew/commit/9abfafbd408e6f2b4a0f4fc84c2970687df3a459
> Error: can't modify frozen String: "The bottle needs the Xcode Command Line Tools to be installed at /Library/Developer/CommandLineTools.\nDevelopment tools provided by Xcode.app are not sufficient.\n\nYou can install the Xcode Command Line Tools, if desired, with:\n    xcode-select --install\n"
> Fix "can't modify frozen String" error

- Library/Homebrew/livecheck/strategy.rb
-----
We discovered that the sorbet runtime does not enforce the static version of `module_function` methods: https://github.com/sorbet/sorbet/issues/8531
I'm already not a fan of `module_function` (I'd rather see a single, consistent API in use, not to mention the long tail of subtle bugs like these that I've come across over the years), so I refactored this file to use the static implementations only (which is consistent with how it's used, at least in tests).
> Refactor Livecheck::Strategy to remove module_function use

- Library/Homebrew/rubocops/blank.rb
- Library/Homebrew/rubocops/bottle.rb
- Library/Homebrew/rubocops/cask/array_alphabetization.rb
- Library/Homebrew/rubocops/checksum.rb
- Library/Homebrew/rubocops/compact_blank.rb
- Library/Homebrew/rubocops/conflicts.rb
- Library/Homebrew/rubocops/deprecate_disable.rb
- Library/Homebrew/rubocops/desc.rb
- Library/Homebrew/rubocops/extend/formula_cop.rb
- Library/Homebrew/rubocops/io_read.rb
- Library/Homebrew/rubocops/keg_only.rb
- Library/Homebrew/rubocops/lines.rb
- Library/Homebrew/rubocops/move_to_extend_os.rb
- Library/Homebrew/rubocops/negate_include.rb
- Library/Homebrew/rubocops/patches.rb
- Library/Homebrew/rubocops/presence.rb
- Library/Homebrew/rubocops/present.rb
- Library/Homebrew/rubocops/safe_navigation_with_blank.rb
- Library/Homebrew/rubocops/service.rb
- Library/Homebrew/rubocops/shared/desc_helper.rb
- Library/Homebrew/rubocops/shared/helper_functions.rb
- Library/Homebrew/rubocops/shared/homepage_helper.rb
- Library/Homebrew/rubocops/shared/on_system_conditionals_helper.rb
- Library/Homebrew/rubocops/shell_commands.rb
- Library/Homebrew/rubocops/text.rb
- Library/Homebrew/rubocops/urls.rb
- Library/Homebrew/rubocops/uses_from_macos.rb
-----
- Some of these I bumped to `typed: strict`, some of them I added intermediary type signatures to some of the methods to make my life easier in the (near, hopefully) future.
> More Sorbet `typed: strict` RuboCops

- Library/Homebrew/rubocops/lines.rb
-----
- I considered writing a cop for this, but it's not worth it: there are no `[:test, :build]` occurrences in Core and this Rust rule only applies in Core formulae.
> rubocops/lines: Clean up an old TODO

- Library/Homebrew/dev-cmd/create.rb
- Library/Homebrew/formula_creator.rb
Addresses inability to find just-created formula, see https://github.com/Homebrew/brew/pull/19244#issuecomment-2646030394 for context.
> clear core tap cache on formula creation

- Library/Homebrew/cmd/info.rb
> cmd/info: only display keg info if tap matches

- Library/Homebrew/livecheck/livecheck.rb
- Library/Homebrew/livecheck/strategy.rbi
-----
One possibility for a simpler implementation of `livecheck_find_versions_parameters ` that also does less work, as suggested in https://github.com/Homebrew/brew/pull/19293/files#r1956748748
> Simplify livecheck_find_versions_parameters

- Library/Homebrew/cask/url.rb
-----
This prevents casks whose `url` contains only `#{arch}` from passing `audit_sha256_no_check_if_unversioned`.
Examples: https://github.com/Homebrew/homebrew-cask/pull/201002, https://github.com/Homebrew/homebrew-cask/pull/201056 and https://github.com/Homebrew/homebrew-cask/pull/201064
> cask/url: remove arch placeholder when checking if unversioned

- Library/Homebrew/build.rb
- Library/Homebrew/formula.rb
Currently, existing DATA patches are subsumed into the initial Git repo created by `brew install --git`, which makes creating a new DATA patch after more fixes a tedious and error-prone process.
This PR delays DATA patch processing till after the Git repo is created, so a `git diff` at the end creates a correct and consolidated DATA patch block ready for insertion/replacement, or even migration to a proper remote patch URL.
The difference is clearly seen in `gromgit/fuse/dislocker-mac`, which has both remote and DATA patches.
Before:
```
% brew install -sig dislocker-mac
==> Fetching gromgit/fuse/dislocker-mac
==> Downloading https://github.com/Aorimn/dislocker/commit/2cfbba2c8cc07e529622ba134d0a6982815d2b30.patch?full_index=1
Already downloaded: …
```
> formula: don't include DATA patches in initial Git repo

- Library/Homebrew/rubocops/lines.rb
- Library/Homebrew/test/rubocops/text/assert_statements_spec.rb
-----
In recent homebrew-core PRs, we've been asking contributors to use `assert_path_exists` and `refute_path_exists` instead of `assert_predicate <path>, :exist?` and `refute_predicate <path>, :exist?` respectively. See for example: https://github.com/Homebrew/homebrew-core/pull/207806#discussion_r1957190206, https://github.com/Homebrew/homebrew-core/pull/206960#discussion_r1951956469, https://github.com/Homebrew/homebrew-core/pull/199951, etc.
This PR makes this suggestion an autocorrectable rubocop (in some cases). Here's an example:
```console
➜  homebrew-core git:(master) brew style --fix empty pyinvoke wllvm pulumi
Inspecting 4 files
CCCC
Offenses:
Taps/homebrew/homebrew-core/Formula/e/empty.rb:47:39: C: [Corrected] FormulaAudit/AssertStatements: Use refute_path_exists …
```
> rubocop/lines: prefer `assert_path_exists` and `refute_path_exists`

- Library/Homebrew/dependencies_helpers.rb
-----
There some inconsistency in how we use `Dependencies`/`Requirements` vs. arrays of `Dependency`/`Requirement`. For now, we'll just update the `sig` to fix https://github.com/Homebrew/brew/pull/19314#issuecomment-2667487594.
> Fix type error in DependenciesHelpers#dependents

- Library/Homebrew/diagnostic.rb
This makes the experience nicer for tap maintainers who may want to do this but without hiding the actual warnings for users.
Requires https://github.com/Homebrew/homebrew-test-bot/pull/1406 to work but not to be merged first.
> diagnostic: skip duplicate formulae and casks check inside test-bot.

- docs/Installation.md
- docs/Tips-N'-Tricks.md
Inspired by @jvns' [post][1], I realized that I've had this problem on multiple teams, where someone missed the step at the end and didn't know how to recover. Typically, I've provided a version like what I've added to the Tips 'n' Tricks page so that I didn't have to think about what OS-arch pair my users are using.
I've tested the loader added to tips and tricks with both bash and zsh and it passes both shellcheck and shfmt in posix mode.
[1]: https://mastodon.social/@b0rk@jvns.ca/113997565198024027
---
-----
> Adds post-installation steps to installation with extend version in tips

- Library/Homebrew/cask/dsl.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/keg.rb
- Library/Homebrew/livecheck/livecheck.rb
-----
The existing code for handling a `HEAD`-only formula involves two return values that can be `nil` but this isn't apparent because the related methods aren't typed. This adds type signatures to the methods and updates the livecheck code to account for `nil` return values (making it clear which methods can return `nil`). This addresses `T.must` usage in the same code in https://github.com/Homebrew/brew/pull/19323.
Besides that, this also extracts the "Unable to get versions" error message into a constant, like `NO_CURRENT_VERSION_MSG`.
> livecheck: refactor HEAD-only formula handling

- Library/Homebrew/dev-cmd/bottle.rb
-----
Fixes incorrectly marking bottles as relocatable, e.g.
https://github.com/Homebrew/homebrew-core/blob/425d4ea43d36e7d03ce894268dd42aef5236bb54/Formula/p/pkgconf.rb#L34-L36
This cannot be done for `/usr/local` as it is used outside Homebrew. Other default prefixes are Homebrew-specific.
> dev-cmd/bottle: check for prefix when not /usr/local

- Library/Homebrew/livecheck.rb
- Library/Homebrew/livecheck/strategy.rb
- Library/Homebrew/test/livecheck/strategy_spec.rb
- Library/Homebrew/test/livecheck_spec.rb
- docs/Brew-Livecheck.md
-----
I initially set the type for livecheck's `post_form` and `post_json` hashes to allow either a string or symbol key. I used string keys in the documentation, as there will inevitably be some form field names that would pose a problem for symbols (e.g., `E-mail` uses a hyphen, `1twothree` starts with a digit, etc.). However, I remembered that we can simply use quote symbols like `:"E-mail"` to handle these situations, as they have the flexibility of a string while still being a symbol.
With that in mind, this updates related type signatures to only allow symbol keys and updates documentation and tests accordingly. The documentation example contains a hyphenated form field, so it demonstrates how to handle names that don't work as a bare symbol.
> livecheck: restrict POST hashes to symbol keys

- Library/Homebrew/livecheck/livecheck.rb
- Library/Homebrew/test/livecheck/livecheck_spec.rb
-----
This refactors the `livecheck_strategy_names` method to align with Doug's `livecheck_find_versions_parameters` implementation in https://github.com/Homebrew/brew/pull/19312 (which is currently part of the `Options` PR).
> livecheck: refactor livecheck_strategy_names

- docs/Formula-Cookbook.md
-----
Some RubyDoc URL fragments in the Formula Cookbook documentation include an equals sign (`%3D`) but the `id` attributes in the current RubyDoc HTML don't include the equals sign, so the documentation CI job is failing with errors like `External link
https://rubydoc.brew.sh/Formula#revision=-class_method failed: https://rubydoc.brew.sh/Formula exists, but the hash 'revision=-class_method' does not`. This updates the URLs to remove `%3D` accordingly.
More information from another perspective: https://github.com/Homebrew/brew/pull/19362
> docs: Fix broken RubyDoc URL fragments

- Library/Homebrew/livecheck/livecheck.rb
- Library/Homebrew/livecheck/strategy/electron_builder.rb
- Library/Homebrew/livecheck/strategy/extract_plist.rb
- Library/Homebrew/livecheck/strategy/json.rb
- Library/Homebrew/livecheck/strategy/page_match.rb
- Library/Homebrew/livecheck/strategy/sparkle.rb
- Library/Homebrew/livecheck/strategy/xml.rb
- Library/Homebrew/livecheck/strategy/yaml.rb
- Library/Homebrew/test/utils_spec.rb
- Library/Homebrew/utils.rb
-----
I noticed we could shed some `T.must` use by moving the `nil` check inside the method. (This helps absolve some of the sins of https://github.com/Homebrew/brew/pull/19323)
> refactor: move nil check inside demodulize

- Library/Homebrew/caveats.rb
- Library/Homebrew/cmd/info.rb
- Library/Homebrew/cmd/list.rb
- Library/Homebrew/cmd/missing.rb
- Library/Homebrew/cmd/update-report.rb
- Library/Homebrew/cmd/uses.rb
- Library/Homebrew/dev-cmd/bump.rb
- Library/Homebrew/diagnostic.rb
- Library/Homebrew/extend/os/linux/cmd/update-report.rb
- Library/Homebrew/extend/os/linux/dependency_collector.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formula_cellar_checks.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/language/java.rb
- Library/Homebrew/language/python.rb
- Library/Homebrew/test/language/node/shebang_spec.rb
- Library/Homebrew/test/language/perl/shebang_spec.rb
- Library/Homebrew/test/language/python/shebang_spec.rb
> Enable strict typing in Formula

- Library/Homebrew/cask/upgrade.rb
- Library/Homebrew/env_config.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/env_config.rbi
A space-separated list of casks. Homebrew will act as if `--greedy` was passed when upgrading any cask on this list.
> Add `HOMEBREW_UPGRADE_GREEDY_CASKS`

- Library/Homebrew/formula.rb
- Library/Homebrew/test/formula_spec.rb
-----
Resolves https://github.com/d12frosted/homebrew-emacs-plus/issues/787
> Fix return type of Formula.build

- Library/Homebrew/formula.rb
- Library/Homebrew/resource.rb
-----
`@!attribute` is [intended](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#attribute) to inject implicit `attr_*` methods. I removed the directives where they do no represent attribute writers (e.g. they are set with `head "https://example.com/.git"` not `head = "https://example.com/.git"`
> docs: Remove misused YARD directives

- Library/.rubocop.yml
- Library/Homebrew/livecheck/livecheck.rb
- Library/Homebrew/livecheck/strategic.rb
- Library/Homebrew/livecheck/strategy.rb
- Library/Homebrew/livecheck/strategy/apache.rb
- Library/Homebrew/livecheck/strategy/bitbucket.rb
- Library/Homebrew/livecheck/strategy/cpan.rb
- Library/Homebrew/livecheck/strategy/crate.rb
- Library/Homebrew/livecheck/strategy/electron_builder.rb
- Library/Homebrew/livecheck/strategy/extract_plist.rb
- Library/Homebrew/livecheck/strategy/git.rb
- Library/Homebrew/livecheck/strategy/github_latest.rb
- Library/Homebrew/livecheck/strategy/github_releases.rb
- Library/Homebrew/livecheck/strategy/gnome.rb
- Library/Homebrew/livecheck/strategy/gnu.rb
- Library/Homebrew/livecheck/strategy/hackage.rb
- Library/Homebrew/livecheck/strategy/header_match.rb
- Library/Homebrew/livecheck/strategy/json.rb
- Library/Homebrew/livecheck/strategy/launchpad.rb
- Library/Homebrew/livecheck/strategy/npm.rb
- Library/Homebrew/livecheck/strategy/page_match.rb
- Library/Homebrew/livecheck/strategy/pypi.rb
- Library/Homebrew/livecheck/strategy/sourceforge.rb
- Library/Homebrew/livecheck/strategy/sparkle.rb
- Library/Homebrew/livecheck/strategy/xml.rb
- Library/Homebrew/livecheck/strategy/xorg.rb
- Library/Homebrew/livecheck/strategy/yaml.rb
- Library/Homebrew/resource.rb
-----
As suggested in the conversation in https://github.com/Homebrew/brew/pull/19293, this PR introduces a Livecheck::Strategy interface, to clarify what methods a strategy must implement in order to fulfill the contract of a strategy. The first five strategies (alphabetically) extend the interface for illustrative purposes. (I can extend to the remainder in a follow-up PR.)
> feat: Add interface for livecheck strategies

- Library/Homebrew/search.rb
Fixes a regression in `brew search` which prevented using a regex for the search pattern after strict typing was added to `formula.rb` in commit a81239e. Now performs fuzzy search only if input is a string.
Closes #19397
-----
> fix(search.rb): fix regex regression in search

- Library/Homebrew/brew.sh
Today if you are in developer mode then `HOMEBREW_NO_SORBET_RUNTIME`
doesn't take effect. But when doing development it's often useful to be
able to disable type-checking, so have that env var take effect even in
developer mode.
> fix: HOMEBREW_NO_SORBET_RUNTIME should work even if developer

- .github/dependabot.yml
Having a global limit of 5 Dependabot PR's in this repo causes issues when we have PR's stuck waiting on upstreams. This PR updates the config to allow us to have 10 open PR's at at time, so that we aren't missing new updates.
> dependabot: allow up to 10 open PR's

- Library/Homebrew/formula.rb
- docs/Formula-Cookbook.md
Based on discussion in #19408, update the documentation to specify that `:pwsh` must be passed explicitly and that it will translate to a "powershell" argument, as is currently supported by Go's common `github.com/spf13/cobra` module and Rust's common `clap` (with `clap_complete`) crate.
> Document pwsh shell completion

- .github/workflows/tests.yml
-----
Brownouts [have started](https://github.com/actions/runner-images/issues/11101) for Ubuntu 20.04. Let's use our Docker image instead.
> workflows/tests: use Docker image for Ubuntu 20.04

- Library/Homebrew/livecheck/strategy.rb
- Library/Homebrew/livecheck/strategy/apache.rb
- Library/Homebrew/livecheck/strategy/bitbucket.rb
- Library/Homebrew/livecheck/strategy/cpan.rb
- Library/Homebrew/livecheck/strategy/crate.rb
- Library/Homebrew/livecheck/strategy/electron_builder.rb
- Library/Homebrew/livecheck/strategy/extract_plist.rb
- Library/Homebrew/livecheck/strategy/git.rb
- Library/Homebrew/livecheck/strategy/github_latest.rb
- Library/Homebrew/livecheck/strategy/github_releases.rb
- Library/Homebrew/livecheck/strategy/gnome.rb
- Library/Homebrew/livecheck/strategy/gnu.rb
- Library/Homebrew/livecheck/strategy/hackage.rb
- Library/Homebrew/livecheck/strategy/header_match.rb
- Library/Homebrew/livecheck/strategy/json.rb
- Library/Homebrew/livecheck/strategy/launchpad.rb
- Library/Homebrew/livecheck/strategy/npm.rb
- Library/Homebrew/livecheck/strategy/page_match.rb
- Library/Homebrew/livecheck/strategy/pypi.rb
- Library/Homebrew/livecheck/strategy/sourceforge.rb
- Library/Homebrew/livecheck/strategy/sparkle.rb
- Library/Homebrew/livecheck/strategy/xml.rb
- Library/Homebrew/livecheck/strategy/xorg.rb
- Library/Homebrew/livecheck/strategy/yaml.rb
-----
…otherwise individual test runs will fail, e.g.
```
$ brew tests --only livecheck/strategy/gnome
Randomized with seed 14538
1 process for 1 spec, ~ 1 spec per process
An error occurred while loading ./test/livecheck/strategy/gnome_spec.rb.
Failure/Error: extend Strategic
NameError:
uninitialized constant Homebrew::Livecheck::Strategy::Gnome::Strategic
```
> fix: require strategic interface in each livecheck strategy

- package/scripts/postinstall
-----
Currently when running the macOS installer atop an existing installation, at the point after the installation finishes but before `postinstall` is run, the master branch hasn't had its HEAD advanced to the latest tag yet so the working directory is in a "HEAD detached at {version number}" as though you had run `git checkout {version number}`. This is why `git reset --hard` resets it to the previous tagged version.
This change has `git` find the latest tag (`git tag --list --sort="-version:refname" | head -n1`) and then resets to that tag (`git reset --hard <tag name>`). This also adds a `git clean -f -d` to clear any stray untracked files from the working directory, and no longer purges all branches other than `master`. 
Fixes #19287, alternate to #19354. Tested on both macOS ARM …
> macOS pkg installer: fix existing installation not being upgraded

- Library/Homebrew/cask/audit.rb
-----
We recently added `POST` request support to livecheck but related cask checks are failing the `livecheck_https_availability` audit (e.g., https://github.com/Homebrew/homebrew-cask/pull/204094) because it calls `validate_url_for_https_availability` which calls `Utils::Curl.curl_check_http_content` and that checks the URL using a `GET` request. Adding `POST` request support to all of those methods will take some work, so this adds a guard to skip the audit if the `livecheck` block uses `post_form` or `post_json`. This isn't ideal but it will allow us to add these `livecheck` blocks in the interim time.
> Cask: skip livecheck https audit for POST requests

- Library/Homebrew/cask/installer.rb
- Library/Homebrew/cmd/install.rb
-----
Currently, `brew install` will refuse to install a `sha256 :no_check` cask if `--require-sha` is specified, but will happily do so if said cask is a dependency of another cask. Same goes for `--no-quarantine`: it'll skip applying the quarantine attribute only for the dependent cask.
This commit fixes that by passing `require_sha` and `quarantine` when installing dependencies, plus `quiet` which was also missing. (It also reorders the args in a similar `cmd/install.rb` call to match.)
> cask/installer: pass more options to cask dependencies

- Library/Homebrew/livecheck/strategy.rb
- Library/Homebrew/test/livecheck/strategy_spec.rb
- Library/Homebrew/utils/curl.rb
-----
`Livecheck::Strategy.page_headers` uses `Utils::Curl.curl_headers` but the method only handles `HEAD` and `GET` requests. I recently added `POST` support to livecheck but forgot to update `curl_headers` in the process, so `livecheck` blocks using the `HeaderMatch` strategy along with `post_form` or `post_json` will fail because curl doesn't allow both `--head` and `--data`/`--json` arguments (e.g., https://github.com/Homebrew/homebrew-cask/pull/204216).
This addresses the issue by updating `curl_headers` to handle `POST` requests and skip the `GET` retry logic.
-----
The aforementioned `effect-house` PR also demonstrated that some servers will return an unexpected response if a `Content-Length` header isn't included in the `POST` request, so this adds the header to the `post_args` …
> curl_headers: Handle POST requests

- Library/Homebrew/keg.rb
-----
Encountered in the wild in https://github.com/Homebrew/homebrew-core/pull/210332.
> keg: fix normalize_pod2man_outputs! for non-UTF-8 manpages

- Library/Homebrew/livecheck/livecheck.rb
-----
Do not skip resource check if `strategy` is blank – this prevents proper handling of parent reference livecheck blocks. This is one of the possible fixes and I've confirmed it works, but long term we do plan to refactor the livecheck code to handle resources better (and not rely on looping through URLs).
Spotted by @cho-m in https://github.com/Homebrew/brew/commit/efeff905eb9f79efab776c2cc6c2208f24e7b8ba.
> livecheck: fix parent reference handling

- Library/Homebrew/cask/utils/rmdir.sh
-----
xref. https://github.com/orgs/Homebrew/discussions/6002, fixes https://github.com/Homebrew/homebrew-cask/issues/204284
When uninstalling a cask that was installed via a .pkg installer, the cask uninstaller's `rmdir.sh` will attempt to find orphaned symlinks in any [non-system paths](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/macos.rb#L6). So if files were installed in `/var/db`, as is done by `santa`, `rmdir.sh`'s run of `find` in that path will fail when it attempts to query the `DifferentialPrivacy`, which seems to have some super-special invisibility cloak over it.
```
$ find /var/db -mindepth 1 -maxdepth 1 -type l
find: /var/db/DifferentialPrivacy: Operation not permitted
```
Adding `|| true` suppresses errors from `find`, which allows casks like `santa` …
> rmdir: ignore unreadable path errors

- Library/Homebrew/extend/os/linux/cask/installer.rb
Otherwise, we end up preventing the use of e.g. `preflight`, `uninstall` that may all work fine on Linux.
> linux/cask/installer: use artifact denylist

- Library/Homebrew/install.rb
- improves https://github.com/Homebrew/brew/pull/19254
Added "/no" for consistency with "Y/y/yes".
-----
> install.rb: add "no" in `--ask` output

- Library/Homebrew/dev-cmd/prof.rb
-----
`--allocation_sample_rate` was renamed to `--allocation_interval` in https://github.com/jhawthorn/vernier/commit/8ffadb304f0262f7ede9f590eacefa1453b26909
> dev-cmd/prof: fix `vernier` invocation

- .github/workflows/docker.yml
-----
Follow-up to #19275. Publishing `master` images was broken because the
different matrix jobs were overwriting each other's outputs in the
`merge` job.
The fix is to pre-generate all the required data once up-front which we
do in the `generate-tags` job.
This can probably still be simplified in places, but handling different successive matrix jobs that depend on each other is rather difficult to reason about.
> workflows/docker: fix publishing `master` images

- Library/Homebrew/cask/cask.rb
- Library/Homebrew/cmd/fetch.rb
- Library/Homebrew/test/cask/cask_spec.rb
- Library/Homebrew/test/support/fixtures/cask/Casks/sha256-os.rb
-----
This allows fetching linux casks to help with CI work. It keeps downloading the macOS version though.
CC @Rylan12 any ideas?
> fix: allow fetching casks on Linux

- Library/Homebrew/services/cli.rb
- Library/Homebrew/services/commands/info.rb
- Library/Homebrew/services/commands/kill.rb
- Library/Homebrew/services/commands/list.rb
- Library/Homebrew/services/commands/restart.rb
- Library/Homebrew/services/commands/run.rb
- Library/Homebrew/services/commands/start.rb
- Library/Homebrew/services/commands/stop.rb
- Library/Homebrew/services/formula_wrapper.rb
- Library/Homebrew/services/formulae.rb
- Library/Homebrew/services/system/systemctl.rb
- Library/Homebrew/test/services/commands/restart_spec.rb
- Library/Homebrew/test/services/formula_wrapper_spec.rb
Some of the typing/`T.must` usage when moving the
Homebrew/homebrew-services code to Homebrew/brew was not quite correct.
Rather than trying to make everything `strict` and import at the same time: let's mostly loosen the typing to fix a few bugs and allow us to add more later.
Fixes https://github.com/Homebrew/homebrew-services/issues/944
Fixes https://github.com/Homebrew/brew/issues/19489
> Fix services types

- Library/Homebrew/formula.rb
This fixes some edge cases where these paths cannot be found if a keg is not linked.
> formula: use any_installed_prefix for service paths

- Library/Homebrew/download_strategy.rb
-----
I should really know better than to type double splats as hashes 😞 
Resolves https://github.com/Homebrew/brew/pull/19475#issuecomment-2726010452
> fix: DownloadStrategy meta params should be untyped

- Library/Homebrew/download_strategy.rb
-----
Before using a cached download, also check that the Content-Length header returned from the URL matches the size of the file. This should catch instances where a newer version of a cask isn't downloaded because a cask's URL doesn't change between updates, i.e. https://github.com/Homebrew/homebrew-cask/pull/204165.
Fixes https://github.com/Homebrew/homebrew-cask/issues/204166, but there's bound to be edge cases.
> download_strategy: compare cached file size to Content-Length

- Library/Homebrew/services/formula_wrapper.rb
- Library/Homebrew/test/services/formula_wrapper_spec.rb
The `brew services list` command was not correctly handling services
that had an error code status.
While the `#zero?` method returns a boolean, the `#nonzero?` method
confusingly returns self or nil. Hence a negated `#zero?` call to check
for a non-zero exit code fixes the error.
While here, `#pid?` method uses a negated `#zero?`, which is not
accurate, as a negative PID value would not be a valid PID. Hence I
changed it to use `#positive?` instead.
The tests for the `#error?` method were marked as needing systemd, but I
saw no obvious reason for that due to how they all use mocked values, so
I removed the systemd requirement.
---
Resolves this error I was getting while the `node_exporter` service had a error status:
```
$ brew services list
Error: Return value: Expected type T::Boolean, …
```
> fix(services/list): correctly handle services with an error code

- Library/Homebrew/formula_auditor.rb
-----
Related issue: Homebrew/homebrew-core#206757
There are a lot of formulae in the core repository that have `www.gnu.org` and `www.nongnu.org` homepages (`grep -o -n "www\.gnu\.org" -r . | cut -d : -f 1 | uniq -c | wc -l` gives 119 entries). Admins do not want to unblock GitHub infrastructure (https://savannah.nongnu.org/support/index.php?111187), so I think it would be better skip this check on Linux (this audit error doesn't occur on macs). If the homepage has a problem it'll be caught during tests on macOS
> Skip homepage audit for `www.gnu.org` and `www.nongnu.org` on GitHub runners

- Library/Homebrew/formula.rb
- docs/Formula-Cookbook.md
-----
A convenient way to set `-tags` flag with multiple values in std_go_args
> std_go_args: add `-tags` flag

- Library/Homebrew/rubocops/cask/constants/stanza.rb
- Library/Homebrew/test/rubocops/cask/stanza_grouping_spec.rb
- Library/Homebrew/test/rubocops/cask/stanza_order_spec.rb
- Library/Homebrew/test/support/fixtures/cask/Casks/sha256-os.rb
-----
- Because @p-linnane wanted this to be codified.
> rubocops/cask/stanza_order: Ensure `arch` and `os` are adjacent

- Dockerfile
-----
Here's a guess at fixing the arm64 Docker workflow:
This seems to be broken on Ubuntu 22.04 at the moment. The system seems
to ship a reasonably modern version (2.34.1), so I think we can make do
with that for now.
> Dockerfile: skip git-core PPA on arm64 Linux

- Library/Homebrew/extend/os/linux/hardware/cpu.rb
- Library/Homebrew/test/hardware/cpu_spec.rb
AMD K12 was an planned ARM microarchitecture that was cancelled.
Ref: https://en.wikipedia.org/wiki/List_of_AMD_CPU_microarchitectures#Nomenclature
- [x ] Have you successfully run `brew tests` with your changes locally?
> linux/hardware/cpu: fix amd_k12 reference

- Library/Homebrew/extend/os/linux/diagnostic.rb
-----
If my theory is correct, this pr should close #19500 but unfortunately I cannot test it. If someone uses Linux, please, apply this patch, delete a few kegs manually (directories like `$HOMEBREW_PREFIX/Cellar/<formula>/<version>` and try to run `brew doctor`
> fix: ignore broken kegs during gcc linkage test

- .github/workflows/docker.yml
-----
We can stop `brew doctor` from throwing an error if we set
`HOMEBREW_ARM64_TESTING`.
> workflows/docker: run `brew test-bot` on arm64 Linux builds

- Library/Homebrew/cmd/services.rb
- Library/Homebrew/services/cli.rb
- Library/Homebrew/services/commands/run.rb
- Library/Homebrew/test/services/cli_spec.rb
Like `brew services start --file` except it's not sticky (i.e. it doesn't install the file, on macOS at least).
> Support `--file` for `brew services run`

- .devcontainer/on-create-command.sh
This `chmod -t` seems to fix things on other Codespaces so let's try it here too.
> devcontainer/on-create-command: fix permissions harder.

- Library/Homebrew/bundle/cask_installer.rb
This was accidentally left in but should have been removed.
> bundle/cask_installer: remove debugging output.

- Library/Homebrew/bundle/brew_services.rb
This ensures the correct `brew` binary is always used.
> bundle/brew_services: use HOMEBREW_BREW_FILE.

- Library/Homebrew/bundle/whalebrew_dumper.rb
- Library/Homebrew/bundle/whalebrew_installer.rb
- docs/Brew-Bundle-and-Brewfile.md
- docs/index.md
This was in the (soon to be archived) Homebrew/homebrew-bundle repository's `README`. There's some good content here that doesn't cleanly fit into the `brew` manpage so let's move it here.
While we're here, let's de-emphasize `whalebrew` as it's not widely used and add commented-out deprecation warnings for its future deprecation.
> Import documentation for `brew bundle`

- Library/Homebrew/bundle/commands/exec.rb
- Library/Homebrew/test/bundle/commands/exec_spec.rb
-----
We are checking `PATH` for the command too early, since the code below
it mutates `PATH`.
Let's defer the check to later to fix this.
> bundle/exec: fix command `PATH` lookup

- Library/Homebrew/cask/download.rb
- Library/Homebrew/downloadable.rb
These are always output in CI for e.g. `brew fetch google-chrome` and are completely unactionable by the user.
Ultimately this is not disabling any security checks, it's just changing when a warning is output and unifying the logic with the other similar warning.
> cask/download: avoid some checksum warnings.

- Library/Homebrew/shims/super/cc
-----
~~We need to allow `-mcpu` and `-mtune` flags to avoid breaking builds on~~
~~arm64 macOS. See, for example, Homebrew/homebrew-core#212051.~~
Also, let's reinstate adding our own optimisation flags if the compiler
was not invoked with a conflicting optimisation flag.
> shims/super/cc: tweak optimisation flag handling for runtime CPU detection builds

- Library/Homebrew/download_strategy.rb
Follow-up to #19460, which was causing cached items to be invalidated if the server returned a Content-Length of 0.
```
$ curl -I https://github.com/snort3/libdaq/archive/refs/tags/v3.0.19.tar.gz
HTTP/2 302 
server: GitHub.com
date: Thu, 20 Mar 2025 19:24:45 GMT
content-type: text/html; charset=utf-8
content-length: 0
vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
location: https://codeload.github.com/snort3/libdaq/tar.gz/refs/tags/v3.0.19
cache-control: max-age=0, private
...
```
> download_strategy: ignore Content-Length value if zero

- Library/Homebrew/cask/quarantine.rb
If we know that we don't care about this prompt, let's allow setting a variable to avoid alarming users.
> quarantine: allow skipping the app management permissions prompt.

- Library/Homebrew/github_runner_matrix.rb
- Library/Homebrew/test/github_runner_matrix_spec.rb
-----
This will make it easier to distinguish the two jobs in the GitHub UI.
> github_runner_matrix: include arch in Linux job names

- Library/Homebrew/cmd/services.rb
Hopefully sufficient time has passed from when passing 2 args meant something completely different: https://github.com/Homebrew/homebrew-services/commit/9f7d5758d84906e59049c1366a5a0b685016e8a7
This allows one to do `brew services info --json postgresql@16 memcached` to get information on multiple services. Start and stop should work too.
> cmd/services: support passing multiple formulae

- Library/Homebrew/.rubocop.yml
- Library/Homebrew/startup/config.rb
These are all useful to be able to tell users to rely on them and we've used them long enough for it to make sense as a public API.
Relatedly, these are all used in at least some Homebrew/homebrew-core or Homebrew/homebrew-cask formulae.
While we're here, update the descriptions to be a bit more user friendly.
See https://github.com/Homebrew/brew/issues/19554 for motivation.
> Make some global variables part of the public API

- Library/Homebrew/bundle/installer.rb
```console
==> Installing Homebrew dependencies
Error: uninitialized constant Homebrew::Bundle::Skipper
/opt/homebrew/Library/Homebrew/bundle/installer.rb:49:in `block in install'
/opt/homebrew/Library/Homebrew/bundle/installer.rb:20:in `each'
/opt/homebrew/Library/Homebrew/bundle/installer.rb:20:in `install'
/opt/homebrew/Library/Homebrew/bundle/commands/install.rb:14:in `run'
/opt/homebrew/Library/Homebrew/cmd/bundle.rb:168:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Process completed with exit code 1.
```
> bundle/installer: add missing require.

- Library/Homebrew/tab.rb
It can be useful to know, if a formula's dependencies were installed from a bottle, what rebuild of the bottle was used for debugging.
> tab: add `bottle_rebuild` to `runtime_dependencies`.

- Library/Homebrew/cmd/nodenv-sync.rb
- Library/Homebrew/cmd/pyenv-sync.rb
- Library/Homebrew/cmd/rbenv-sync.rb
- Library/Homebrew/env_config.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/env_config.rbi
If this variable is set, `brew *env-sync` will only sync the exact installed versions of formulae rather than all the patch (or, for node, minor and patch) versions.
> cmd/*env-sync: add `HOMEBREW_ENV_SYNC_STRICT` mode.

- Library/Homebrew/utils/popen.rb
Blindly using args[0] misleads users when an env is passed.
Before:
```
==> go build -ldflags=-s -w -X main.version=1.64.8 -X main.commit=8b37f14 -X main.date=2025-03-17T16:54:02Z ./cmd/golangci-lint
brew: command not found: {"SHELL"=>"bash"}
Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /opt/homebrew/Cellar/golangci-lint@1/1.64.8/bin/golangci-lint completion bash` exited with 127. Here's the output:
```
After:
```
==> go build -ldflags=-s -w -X main.version=1.64.8 -X main.commit=8b37f14 -X main.date=2025-03-17T16:54:02Z ./cmd/golangci-lint
brew: command not found: /opt/homebrew/Cellar/golangci-lint@1/1.64.8/bin/golangci-lint
Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /opt/homebrew/Cellar/golangci-lint@1/1.64.8/bin/golangci-lint completion bash` exited with 127. …
```
> popen: get correct cmd name on error

- Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/dispatch_build_bottle.rbi
-----
This will make it easier to dispatch bottle builds for arm64 Linux.
> dev-cmd/dispatch-build-bottle: support arm64 Linux

- Library/Homebrew/cmd/bundle.rb
- Library/Homebrew/dev-cmd/sh.rb
- Library/Homebrew/test/utils/shell_spec.rb
- Library/Homebrew/utils/shell.rb
- bin/brew
It's both unexpected and undesirable for `brew bundle (exec|env|sh)` to filter the environment and makes these tools less useful.
Not filtering the environment, though, causes issues with the `brew bundle sh` shell. Fix this up and, while we're here, also improve the formatting for both `zsh` and `bash` (the default) to use nicer and more consistent prompts and colours.
To simplify this, consolidate some logic in a new
`Utils::Shell.shell_with_prompt` method and add tests for it and a similar notice for `brew bundle sh`.
Finally, avoid printing out the notice when `HOMEBREW_NO_ENV_HINTS` is set.
> Don't filter the environment for `brew bundle (exec|env|sh)`

- Library/Homebrew/bundle.rb
- Library/Homebrew/bundle/brew_installer.rb
- Library/Homebrew/bundle/commands/exec.rb
- Library/Homebrew/test/bundle/commands/exec_spec.rb
- docs/Brew-Bundle-and-Brewfile.md
This allows writing to e.g. `.ruby-version` files directly from the `Brewfile`, making it easy to keep these versions in sync.
> Add `version_file:` DSL to `Brewfile`

- Library/Homebrew/extend/os/linux/bundle/skipper.rb
Don't unconditionally skip Linux casks but instead check if they are supported on Linux.
Fixes https://github.com/Homebrew/brew/issues/19537
> linux/bundle/skipper: add support for Linux casks.

- Library/Homebrew/services/formula_wrapper.rb
If a service is somehow duplicated across multiple domains, this ensures that the correct output is produced.
> services: use domain target in `launchctl list` command.

- Library/Homebrew/cleanup.rb
We need to handle these slightly different as otherwise they can be cleaned up incorrectly.
> cleanup: fix handling of bottle manifest rebuilds.

- Library/Homebrew/bundle/brew_installer.rb
This doesn't make sense for consumption outside of Homebrew.
> bundle/brew_installer: strip revision number from version file.

- Library/Homebrew/extend/os/linux/cask/installer.rb
-----
The method it overrides is not `private`, so it doesn't seem like this
should be private. This causes errors when using `brew bundle` on Linux
with a `Brewfile` that contains `cask` entries.
> extend/os/linux/cask/installer: make `check_stanza_os_requirements` non-private

- Library/Homebrew/dev-cmd/create.rb
-----
The command is three clicks away if you know where to look for, but even if you know, it takes a while to discover https://docs.brew.sh/Formula-Cookbook#install-the-formula so showing it directly after create saves some time.
> create: show command to install formula for testing

- Library/Homebrew/extend/os/linux/bundle/skipper.rb
This should have been reversed in https://github.com/Homebrew/brew/pull/19599 to work as expected on Linux.
Lesson learned that I shouldn't be relying on using macOS and our CI testing for tests like this to work 🤦🏻.
Commit verified because did this on WSL where I don't have GPG signing working yet.
> linux/bundle/skipper: fix skipper logic.

- Library/Homebrew/brew.sh
- Library/Homebrew/cmd/update-if-needed.rb
- Library/Homebrew/cmd/update-if-needed.sh
- completions/bash/brew
- completions/fish/brew.fish
- completions/internal_commands_list.txt
- completions/zsh/_brew
- docs/Manpage.md
- manpages/brew.1
This uses the logic in `brew.sh` for deciding whether or not to run `brew update --auto-update` and makes it a dedicated command that can be used instead of `brew update` in scripts to be really fast in the no-op case.
`brew update` will always do at least some updating which is a nicer default but is much slower.
```console
Benchmark 1: brew update-if-needed
Time (mean ± σ):      68.6 ms ±   6.4 ms    [User: 12.0 ms, System: 12.6 ms]
Range (min … max):    44.6 ms …  84.6 ms    40 runs
Benchmark 2: brew update
Time (mean ± σ):      3.827 s ±  0.166 s    [User: 1.294 s, System: 1.173 s]
Range (min … max):    3.543 s …  4.175 s    10 runs
Summary
brew update-if-needed ran
55.81 ± 5.73 times faster than brew update
```
> Add `brew update-if-needed`

- Library/Homebrew/formula_creator.rb
My common mistake is to specify release URL, like
brew crate https://github.com/hugelgupf/p9/releases/tag/v0.3.0
which gives unpacking errors later. It should be archive instead
brew create https://github.com/hugelgupf/p9/archive/refs/tags/v0.3.0.tar.gz
Ideally we can try to autodetect the archive from release page, but erroring out if downloaded file is HTML page should be handy for early spotting other URL mistakes too.
-----
> create: check that downloaded URL is actually archive

- Library/Homebrew/dependency_collector.rb
- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/downloadable.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/resource.rb
- Library/Homebrew/retryable_download.rb
- Library/Homebrew/software_spec.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/utils/pypi.rb
-----
Resolves https://github.com/Homebrew/brew/issues/19505 by fixing the regression of undocumented Formula.url properties:
- `Formula.url` with no args now returns the url (variation on the example.txt contents in the linked issue)
- `Formual.url` now allows for additional `specs` value types` (see example2.txt in the linked issue)
> fix: Allow Formula.url with no args to get url

- Library/Homebrew/diagnostic.rb
FUSE 3 support was introduced in macFUSE 4.10.0.
Resolves #19650.
> diagnostic: allow macFUSE FUSE3 files

- Library/Homebrew/test/bundle/whalebrew_installer_spec.rb
`WhalebrewInstaller.reset!` won't reset the cache of the `WhalebrewDumper` but needs to otherwise the behaviour of these tests depends on execution order. Align with the behaviour of other installers (e.g. `cask_installer_spec`) and reset the dumper.
> test/bundle/whalebrew_installer: fix flaky test from missing resets

- Library/Homebrew/formula_creator.rb
-----
In #19623, the homepage in the GitHub repo info was checked with `empty?`, but I found that the API returns `null` for a missing homepage, which in Ruby seems to be treated as `nil`, so calling `empty?` on it fails if not set.
> Correctly handle missing homepage in GitHub API response

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/utils/github.rb
The default behaviour is too strict for unofficial taps. We can still warn elsewhere but, given the potential for false positives, let's loosen things a bit.
> dev-cmd/bump-*: only warn on duplicate PRs for official taps.

- Library/Homebrew/bundle/commands/cleanup.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/keg.rb
- Library/Homebrew/test/bundle/commands/cleanup_spec.rb
Extract the relevant logic from `formula.rb`, moving to `keg.rb` and then use this logic in `bundle/commands/cleanup.rb` to ensure that we don't say we need to uninstall formulae that should be still kept.
> bundle/commands/cleanup: correctly handle `.keepme` references.

- Library/Homebrew/brew.sh
Because we were passing it with no args, it would just invoke the help page.
> brew.sh: fix update-if-needed failing after update

- docs/Homebrew-on-Linux.md
- docs/Support-Tiers.md
-----
After https://github.com/Homebrew/install/pull/963/files merge, Homebrew is working on my Setup in Debian docker image on Apple M1. Since it's fixed, it should be reflected in the docs.
Note that I cannot test on arm32, but the PR mentioned above was only about 64-bit arch, so for 32-bit platforms, the restrictions seem to be still actual
> docs: Remove aarch64 unsupported note for Homebrew on Linux #1

- Library/Homebrew/bundle.rb
- Library/Homebrew/bundle/brew_installer.rb
- Library/Homebrew/bundle/brew_services.rb
- Library/Homebrew/bundle/commands/exec.rb
- Library/Homebrew/test/bundle/brew_services_spec.rb
We previously were trying to pass through invalid environment variable names so let's fix these up and query those instead.
> bundle: fix up formula name for environment variable.

- Library/Homebrew/development_tools.rb
- Library/Homebrew/extend/os/linux/development_tools.rb
- Library/Homebrew/extend/os/linux/system_config.rb
- Library/Homebrew/test/compiler_selector_spec.rb
- docs/Linux-CI.md
Update both the variables that dictate this and the documents that explain our GCC/glibc policies.
These should ease a later future migration to a newer GCC version.
This is based on the conversation in https://github.com/Homebrew/brew/pull/19238.
> Update Linux GCC code.

- Library/Homebrew/extend/os/linux/development_tools.rb
-----
Noticed this when running `brew style` after the the bump to Rubocop 1.75.2:
```
extend/os/linux/development_tools.rb: Style/UselessMethodDefinition has the wrong namespace - replace it with Lint/UselessMethodDefinition
extend/os/linux/development_tools.rb: Style/UselessMethodDefinition has the wrong namespace - replace it with Lint/UselessMethodDefinition
```
> os/linux/development_tools: update cop namespace

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
-----
`bump-cask-pr` was recently updated to add Linux support but the change to the `replace_version_and_checksum` logic has broken the command for casks that have on_system blocks that reference specific macOS versions (e.g., `on_monterey :or_newer` in `logi-options+`).
The previous logic only simulated the arch, so the `current_os` value on macOS was a specific version like `:sequoia`. The current logic uses generic `:macos` values, which work for `on_macos` blocks but don't work for blocks like `on_sequoia`, etc. This leads to an `undefined method 'latest?' for nil` error, as `old_cask.version` is `nil` in this scenario (i.e., none of the on_system blocks apply to `:macos`, so `version` is never set).
This updates the method to use the host OS value in `system_options` if the host is …
> bump-cask-pr: fix macOS host handling

- Library/Homebrew/cask/dsl.rb
- Library/Homebrew/dev-cmd/tests.rb
- Library/Homebrew/livecheck.rb
- Library/Homebrew/test/livecheck_spec.rb
-----
Casks now support an `os` DSL method, similar to `arch`. This makes it available in `livecheck` blocks, like we do with `arch`.
Besides that, this also adds tests for the `version` and `arch` delegate methods in the `livecheck` block DSL. This doesn't affect test coverage but it ensures that the methods work as expected in `livecheck` blocks. For what it's worth, it was necessary to use `Cask::Cask.new` in these tests, as the delegate methods don't work when using the existing `Cask::CaskLoader.load` approach (for whatever reason).
Related to https://github.com/Homebrew/homebrew-cask/pull/207471.
> Make `os` available in `livecheck` blocks

- Library/Homebrew/bundle/commands/exec.rb
- Library/Homebrew/test/bundle/commands/exec_spec.rb
Reverts Homebrew/brew#19703
Think this has caused a regression locally with `/home/linuxbrew/.linuxbrew/bin/brew services info --json`. Not seeing any error output but reverting for now to be safe.
> Revert "bundle: handle simultaneous `exec --services` better"

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
- Library/Homebrew/test/dev-cmd/bump-cask-pr_spec.rb
-----
This reworks the `SimulateSystem` args in the `bump-cask-pr` `replace_version_and_checksum` method to respect `depends_on arch` values in casks. That is to say, we shouldn't simulate Intel for a cask using `depends_on arch: :arm64` and we shouldn't simulate ARM if the cask uses `depends_on arch: :x86_64`.
In the process, this refactors how we collect/combine OS/arch values. To make this approach work predictably, I removed the logic that omits OS values matching the host OS (as `SimulateSystem` already handles this). The `[{ os:, arch: }]` hash format only made sense when we were omitting values, so this returns to the previous `[[os, arch]]` array format (to align with the `OnSystem::ALL_OS_ARCH_COMBINATIONS` array format).
This also extracts the logic for generating the …
> bump-cask-pr: respect `depends_on arch`

- Library/Homebrew/bundle/commands/exec.rb
- Library/Homebrew/test/bundle/commands/exec_spec.rb
Reland #19703, with an additional check to make sure we are calling `services info --json` with a non-empty list.
Requires #19713
> Reland "bundle: handle simultaneous exec --services better"

- Library/Homebrew/utils/ruby.sh
This should ensure it's set to the correct path.
Fixes #19715
> utils/ruby: set HOMEBREW_BOOTSNAP_GEM_PATH after Ruby install.

- Library/Homebrew/download_strategy.rb
A bug introduced with #19460 is that if a redirection has a file size (for example, if it is a 302 that also has HTML content), Homebrew will invalidate the cached location.
-----
> fix: Don't invalidate the cached location if the response is a redirect

- Library/Homebrew/test/cmd/upgrade_spec.rb
-----
The "upgrades with asking for user prompts with dependants checks" test for `cmd/upgrade` has been failing on CI. The regex in the test doesn't match expected output because the negative lookaheads aren't working as expected. The intention is to make sure that the names aren't repeated (i.e., second shouldn't match first, third shouldn't match first or second) but the negative lookaheads should be _inside_ the second/third capture groups for this to work as intended.
This updated regex should work as expected. I manually tested it using the output from CI to make sure that it matches when no formula names are repeated (e.g., `Formulae (3): testball, testball4, testball5`) and does not match if formula names are repeated (e.g., `Formulae (3): testball5, testball4, testball5`).
> cmd/upgrade: fix output regex in test

- Library/Homebrew/dev-cmd/vendor-gems.rb
> dev-cmd/vendor-gems: fix incorrect Bundler version being used

- docs/Formula-Cookbook.md
-----
I am following the Formula Cookbook at https://docs.brew.sh/Formula-Cookbook#check-the-build-system but the "Check the build system" step did not run:
```
HOMEBREW_NO_INSTALL_FROM_API=1 brew install --interactive spacetimedb
Error: spacetimedb: no bottle available!
If you're feeling brave, you can try to install from source with:
brew install --build-from-source spacetimedb
This is a Tier 3 configuration:
https://docs.brew.sh/Support-Tiers#tier-3
Do not report any issues to Homebrew/* repositories!
Read the above document instead before opening any issues or PRs.
```
It believe it is simply missing the `--build-from-source` flag, unless that should be implicit with `--interactive`?
> docs: fix Formula Cookbook build command

- Library/Homebrew/bundle/commands/exec.rb
This should fix the flaky test failures in `exec_spec.rb`.
> bundle/commands/exec: add missing require.

- Library/Homebrew/bundle/commands/exec.rb
- Library/Homebrew/test/bundle/commands/exec_spec.rb
- Rather than maintaining a list of Homebrew environment variables to delete, delete all Homebrew (and Portable Ruby) internal variables that won't be used by other tools.
- When exporting variables, only export variables that have changed.
- When exporting PATH-like variables, ensure the PATH is appending to the existing path rather than replacing it and ensure we only include newly added paths.
> Improve `brew bundle exec`/`env`/`sh` environment handling

- Library/Homebrew/bundle/commands/exec.rb
We need to ensure that we keep around some `HOMEBREW_` variables so that the e.g. `git` shim still works in `brew bundle exec`.
> bundle/commands/exec: adjust environment variable handling (again)

- .github/workflows/tests.yml
These are almost 2x as slow as the next slowest tests and we'll be dropping them around September this year at the latest anyway.
There's still some basic coverage from the "default formula" tests which are much quicker to run on macOS 13.
> workflows/tests: drop macOS 13 tests.

- Library/Homebrew/dev-cmd/create.rb
-----
Using `brew create` without providing a standard input results in an internal error being returned, since `nil` isn't handled - as reported in #19043.
```shell
brew create --python https://files.pythonhosted.org/packages/e7/19/fad6f32d430ac1dc44d6cb49cd4245fdb51b840c338e092489463ba50635/baymesh-0.3.3.tar.gz --tap gtaylor/baymesh --verbose < /dev/null
```
```
Formula name [baymesh]: Error: undefined method `chomp' for nil
/opt/homebrew/Library/Homebrew/dev-cmd/create.rb:243:in `__gets'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11998/lib/types/private/methods/call_validation.rb:282:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11998/lib/types/private/methods/call_validation.rb:282:in `validate_call' …
```
> dev-cmd/create: Handle nil stdin

- Library/Homebrew/dev-cmd/edit.rb
-----
Before:
```sh
Warning: `brew install` ignores locally edited casks and formulae if
HOMEBREW_NO_INSTALL_FROM_API is not set.
```
After:
```sh
==> To test your local edits, run:
HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --verbose --debug p9ufs
```
> dev-cmd/edit: Actionable message about no API install

- Library/Homebrew/formula_cellar_checks.rb
-----
Sometimes the CPUID instruction exists in a dependency, e.g. `aws-checksums` performs CPU detection via `aws-c-common`.
Open to alternative names, e.g. `:missing_cpuid_allowlist`, `:no_cpuid_instruction_allowlist`, ...
> formula_cellar_checks: add no_cpuid_allowlist

- Library/Homebrew/test/dev-cmd/tap-new_spec.rb
-----
I keep getting 1Password prompts when running `brew tests`. This is because `brew tap-new` initializes a new git repo and tries to commit it. We only check for the presence of the generated files, so let's avoid the git operation.
> test/dev-cmd/tap-new_spec: use `--no-git` to avoid auth prompt

- Library/Homebrew/test/spec_helper.rb
Would have liked a nicer fix for this but: better than nothing.
> spec_helper: cleanup VSCode/Cursor test files.

- docs/Prose-Style-Guidelines.md
-----
This is causing CI failure with a 503 error. Let's remove it to further reduce 3rd party sites failing our CI.
> Prose-Style-Guidelines: remove Economist's Style Guide

- Library/Homebrew/aliases/alias.rb
This one is only loaded when running `brew (un)alias`
> aliases: fix missing require with Ruby 3.4

- Library/Homebrew/services/cli.rb
- Library/Homebrew/services/system.rb
Again should only be loaded with `brew services` is run.
> services: fix FileUtils usage in Ruby 3.4

- Library/Homebrew/cask/artifact/abstract_flight_block.rb
The existing line was overly complex anyway.
> cask/artifact/abstract_flight_block: fix warning in Ruby 3.4

- Library/Homebrew/global.rb
This errors in Ruby 3.4 due to a missing `require "fileutils"`.
So I guess we have two options:
* Add the require (safe)
* Drop the extend (as I think it's unneeded)
The latter is tempting as `brew tests` still passes with it dropped. It is however a breaking change for old-style commands that relied on this, so maybe a change best reserved for the next major/minor release where Ruby 3.4 will have minor breaking changes of its own.
This does not affect formulae - they continue to work as is.
> global: mark `extend FileUtils` for dropping

- Library/Homebrew/test/cask/dsl/container_spec.rb
After this everything should work.
> test/cask/dsl/container_spec: fix test failure with Ruby 3.4

- .github/workflows/vendor-version.yml
> workflows/vendor-version: fix handling of Ruby upgrades

- Library/Homebrew/standalone/init.rb
Note: this only does anything on Ruby 3.4 or later as it relies on new API.
> standalone/init: enable more warnings for developers

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/dev-cmd/bump.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/bump.rbi
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/bump_formula_pr.rbi
- Library/Homebrew/utils/github.rb
-----
This PR adds functionality to `brew bump` that allows Formula with synced versions to be bumped together.
If you pass the flag `--bump-synced` to `brew bump` it will automatically include any Formula that are marked as synced versions.
The diff is quite significant in some places, because existing code had to be moved into loops to iterate over the creation of commits and file changes. There isn't great test coverage for these commands as it stands, but some could be added here.
I will keep the branch checked out over the coming days to discover any issues.
------
Here is an example of a synced version PR opened from this branch:
https://github.com/Homebrew/homebrew-core/pull/219026
> bump: bump synced formula together

- .github/workflows/docker.yml
-----
We keep receiving `400 Bad request` when pushing images to Docker Hub. This PR adds a retry with exponential backoff.
> workflows/docker: add retry to image push

- Library/Homebrew/cask/dsl.rb
- Library/Homebrew/cask/dsl/depends_on.rb
-----
We're now seeing warnings related to the cask DSL surfaced by Ruby 3.4:
```
/opt/homebrew/Library/Homebrew/cask/dsl.rb:456: warning: The class Cask::DSL reached 8 shape variations, instance variables accesses will be slower and memory usage increased.
It is recommended to define instance variables in a consistent order, for instance by eagerly defining them all in the #initialize method.
```
I've been working on upgrading `Cask::DSL` to `typed: strict` and part of that involves defining all of the instance variables in the `initialize` method, so I've extracted this part of that work as a way of helping to resolve the aforementioned warning. This doesn't fully resolve the warning but it addresses what it was originally referencing, at least.
After the changes in this PR, the warning …
> Cask::DSL: define instance variables in initialize

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
@khipp noticed that the `bump-formula-pr` was no longer being applied in `homebrew-core`, after recent changes in #19798
This PR restores the previous wording.
> bump-formula-pr: restore pr message

- Library/Homebrew/cask/dsl.rb
-----
I recently updated `Cask::DSL` to define instance variables in `#initialize` (https://github.com/Homebrew/brew/pull/19806) to get us closer to resolving a "shape variation" warning from Ruby. The reason why we continued to receive this warning after the previous changes is because I overlooked the variables that are set using `set_unique_stanza`.
The tricky part about those instance variables is that we need to be able to identify if they've been set. I've handled this by using a `nil` initial value and updating the `instance_variable_defined?` condition to check for a non-`nil` value instead. This works for these variables but it would be a problem if we ever have a DSL method that accepts a `nil` argument.
> Cask::DSL: initialize more instance variables

- Library/Homebrew/cask/download.rb
- Library/Homebrew/downloadable.rb
- Library/Homebrew/resource.rb
- Library/Homebrew/retryable_download.rb
* Declare all instance variables in the constructor
* Make these files `typed: strict` (was useful for me to catch any stray variables)
* Fix some class type inconsistencies
> Cleanup Downloadable variables and types

- Library/Homebrew/completions.rb
- Library/Homebrew/test/completions_spec.rb
- completions/bash/brew
- completions/fish/brew.fish
- completions/zsh/_brew
- docs/Manpage.md
- manpages/brew.1
-----
There is a problem where `_arguments` can take up all memory when trying to autocomplete an argument with `*::` syntax. It works well for lightweight functions with subcommand logic but may crash the current shell session if a function returns a lot of values (f.e. `brew formulae`).
Right now, you can crash zsh with any command that uses `__brew_formulae` **and** `__brew_casks` for autocompletion. Steps to reproduce: type `brew install --build-from-source --dry-run ^ aaaa` or something similar in the prompt, go back to `^`, remove the caret, and press tab.
It can be fixed if `*::` are replaced with `*:`. We do not use complex autocomplete logic for named arguments, and it should work a bit faster and more reliably for large lists of packages.
Thanks to @rgoldberg for reporting the …
> fix: prevent Zsh crashes related to autocompletion

- Library/Homebrew/cask/auditor.rb
- Library/Homebrew/cask/dsl.rb
-----
I recently modified `Cask::DSL` to define instance variables in the `#initialize` method and this involved some changes to the `language`, `language_eval`, and `languages` methods. One of those was to initialize `@language_blocks` to an empty hash instead of using a `nil` default. I updated the related condition in the `language_eval` method but I missed that `language_blocks` is used in `Cask::Auditor` and it specifically relies on a false-y value to check if the variable is set. An empty hash isn't false-y, so this is causing issues for `brew audit`.
This updates the condition in `Cask::Auditor` to check for a non-empty hash instead, which resolves the issue. I'll review the other instance variables that use a non-`nil` default to make sure that I haven't introduced any other …
> Cask::Auditor: update language_blocks condition

- Library/Homebrew/bundle/commands/check.rb
- Library/Homebrew/bundle/commands/exec.rb
- Library/Homebrew/cmd/bundle.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/cmd/bundle.rbi
-----
`brew bundle exec` behaves correctly only after doing `brew bundle install`.
Running `brew bundle check` can be slow, so let's add a `--check` flag
to `brew bundle exec` which will also run `brew bundle check` before
`brew bundle exec` to ensure that the `Brewfile` has been installed
before proceeding.
Alternative to #19636 which makes `--check` the default behaviour. I have a mild
preference for this version since the additional `brew bundle check` makes
`brew bundle env` and `brew bundle exec true` 60% slower.
Another option is to merge #19636 while adding a `--no-check` flag for users who
already know their `Brewfile` is installed and don't want to incur the overhead
of `brew bundle check`.
> bundle/commands/exec: check that `Brewfile` is installed with `--check`

- Library/Homebrew/cask/artifact/abstract_uninstall.rb
-----
This is currently behaving incorrectly when calling `trash.swift` fails
due to lack of permissions. In this instance, `trash.swift` prints
error: permissionDenied
to stdout, and this is incorrectly parsed as having successfully trashed
a file named `error` and another named ` permissionDenied`.
Let's fix this by ensuring that:
- any paths in `trashed` are in the `paths` that we wanted to trash in
the first place
- define `untrashable` by removing the `trashed` paths from `paths`
> cask/artifact/abstract_uninstall: fix `trash_paths`

- Library/Homebrew/formula_installer.rb
Always show the error message rather than gating it to `--debug`. Instead, only gate the backtrace output to `--debug`.
> formula_installer: always output errors with fixing linkage

- Library/Homebrew/bundle/commands/exec.rb
Let's avoid having `exec` and `env`/`sh` subcommands have different environment variables logic. Instead, let's e.g. add `HOMEBREW_PATH` and remove `*/Homebrew/shims/*` from the `PATH` for all three subcommands.
This allows more consistency for users and easier to debug and reason about behaviour.
> bundle/commands/exec: make environment variables more consistent.

- Library/Homebrew/official_taps.rb
This has been archived and migrated to Homebrew/homebrew-cask.
> official_taps: deprecate homebrew-linux-fonts.

- Library/Homebrew/cmd/bundle.rb
If you set `HOMEBREW_BUNDLE_NO_UPGRADE=1`, `brew bundle check` will output:
```
Error: Parameter 'no_upgrade': Expected type T::Boolean, got type String with value "1"
Caller: /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12039/lib/types/private/methods/call_validation.rb:227
Definition: /opt/homebrew/Library/Homebrew/bundle/commands/check.rb:14 (Homebrew::Bundle::Commands::Check.run)
```
> cmd/bundle: fix no_upgrade type.

- .github/workflows/docker.yml
Opening this basically to show that #19832 is temporary.
We're at about 87% bottle coverage now. The main three items still TODO before tier 1 arm64 is:
* Finish upstreaming patchelf fixes (Ruby port nearly done)
* Finish glibc PR (next couple days hopefully)
* Qt
> workflow/docker: push tagged arm64 images

- Library/Homebrew/dev-cmd/tap-new.rb
-----
This PR ensures that taps created with `brew tap-new` can be private (private repo + private packages) by listing all required permissions and setting the correct `HOMEBREW_DOCKER_REGISTRY_TOKEN` for bottles.
An alternative approach would be to add a `--private` flag to `brew tap-new`, so that additional permissions are added when it is set.
I'm happy to follow that approach if we decide it is better. An argument for the initially proposed approach is that even for public repos, it makes sense to restrict permissions only to the required resources.
> dev-cmd/tap-new: support private repos

- Library/Homebrew/brew.sh
We want to keep testing 20.04 because of the glibc + gcc code coverage. The 20.04 image isn't going away until at least 4.7. In the longer term, what we should probably do is adjust the tests so we stub those code paths rather than rely on the host OS being < 22.04 - but I won't have time to change that today.
> Fix CI errors on 20.04

- Library/Homebrew/tap.rb
- Library/Homebrew/tap_auditor.rb
-----
`brew audit` on unofficial taps throws error because `autobump_packages` tries to audit all official packages in external tap. Package list should be empty if neither `core_tap?` nor `core_cask_tap?` are true
> tap: fix autobump logic for unofficial taps

- README.md
> README: add Bluesky link.

- Library/Homebrew/api.rb
For reasons not yet known, our attempt to force UTF-8 encoding by default in brew.sh doesn't always work for Linux users.
This is causing JSON parsing to fail on some Linux systems after 4.5.0 due to Ruby 3.4 now enforcing invalid encoding as errors properly.
Given we know/expect the JSON is UTF-8, let's just explicitly state it here when reading.
> api: force encoding to UTF-8

- Library/Homebrew/lazy_object.rb
`__getobj__` actually takes in a block. You call it when there isn't an object to delegate to but that never really is the case for our use case so we don't need to yield here.
Fixes:
```
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.3/lib/ruby/3.4.0/delegate.rb:101: warning: the block passed to 'LazyObject#__getobj__' defined at /opt/homebrew/Library/Homebrew/lazy_object.rb:12 may be ignored
```
Also remove the `private` specifier as it's incorrect given the superclass method is public. Fixes another error seen in `brew irb`:
```
An error occurred when inspecting the object: #<NoMethodError: private method '__getobj__' called for an instance of LazyObject>
```
> lazy_object: fix `__getobj__` signature

- Library/Homebrew/utils/github/actions.rb
Fixes:
```
/opt/homebrew/Library/Homebrew/utils/github/actions.rb:103: warning: string returned by :error.to_s will be frozen in the future
```
> utils/github/actions: fix frozen string handling

- Library/Homebrew/github_runner_matrix.rb
-----
Closes #19838
There is a problem when CI determines which runners it needs when testing formulae. If a formula has `on_linux do` block with `depends_on arch:` requirement, it'll be added to `formula.requirements` list, even if there's no such restriction on macOS. The opposite problem happens with `on_macos` block. Because CI runs on Linux, it is not able to check `depends_on arch:` there. To solve this problem, we need to simulate the specific platform when sending `#{arch}_compatible?` request.
Unfortunately, I don't know how to check if it works (I didn't find how to test `on_*` block in `github_runner_matrix_spec.rb`), but I hope it will work as expected
> github_runner_matrix: emulate plaform when sending `compatible?` requests

- Library/Homebrew/services/cli.rb
- Library/Homebrew/services/formula_wrapper.rb
- Library/Homebrew/services/system.rb
- Library/Homebrew/test/services/cli_spec.rb
When running on `sudo`, we force `user/` but the service might have started under `gui/`.
There are scenarios where `sudo` over `gui/` can work so when stopping we can try both domains and go with whatever works.
> services: try multiple domains when stopping

- Library/Homebrew/formula_auditor.rb
-----
Redis version 8 has added AGPLv3 as a licensing option.
Reference: https://redis.io/blog/agplv3/
> formula_auditor: remove redis version limit

- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/test/utils/shared_audits_spec.rb
- Library/Homebrew/utils/shared_audits.rb
-----
The endoflife.date API has been updated, so this modifies the URL in `SharedAudits.eol_data` to use the up to date URL and modifies the related logic in `FormulaAuditor.audit_eol` to work with the new response format. Specifically, there is now an `isEol` boolean value and the EOL date is found in `eolFrom`.
One wrinkle of the new setup is that 404 responses now return HTML content even if the request includes an `Accept: application/json` header. This handles these types of responses by catching `JSON::ParserError` but ideally we would parse the response headers and use `Utils::Curl.http_status_ok?` to check for a good response status before trying to parse the response body as JSON. [Edit: I worked on this but hit a wall because the tests return an `undefined method …
> Update eol_data for API changes

- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/test/version_spec.rb
-----
both kibana and elasticsearch got removed per https://github.com/Homebrew/homebrew-core/pull/138155 on Aug 2, 2023
> formula_auditor: remove elasticsearch and kibana refs

- docs/Taps.md
Because it was removed in `9ac3182`
This is for #19856
-----
> Remove the sentence referencing --force-auto-update from the documentation

- Library/Homebrew/brew.sh
This is necessary to avoid permission errors.
Fixes https://github.com/Homebrew/brew/issues/19904
> brew.sh: don't run `sudo brew services` with Bootsnap.

- docs/How-To-Open-a-Homebrew-Pull-Request.md
-----
As indicated in https://github.com/orgs/Homebrew/discussions/6150, the current wording makes it seem like this will be a lot of work when it does not have to be.
> fix: make the "Open Pull Request" doc less daunting

- Library/Homebrew/dev-cmd/prof.rb
-----
Fixes error when running `brew prof`: `uninitialized constant Homebrew::DevCmd::Prof::FileUtils`.
~~~
$ brew prof --prefix
Error: uninitialized constant Homebrew::DevCmd::Prof::FileUtils
/usr/local/Homebrew/Library/Homebrew/dev-cmd/prof.rb:26:in 'Homebrew::DevCmd::Prof#run'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in '<main>'
~~~
I was also able to reproduce this failure with `brew tests --only=dev-cmd/prof  --online`:
<details>
~~~
$ brew tests --only=dev-cmd/prof  --online
Randomized with seed 44002
1 process for 1 spec, ~ 1 spec per process
FF.
Failures:
1) Homebrew::DevCmd::Prof integration tests works using …
> dev-cmd/prof: require fileutils

- Library/Homebrew/bundle/cask_installer.rb
- Library/Homebrew/bundle/dsl.rb
- Library/Homebrew/test/bundle/dsl_spec.rb
Currently, calling `cask_args` a second time will completely override the first one. This PR switches it so it merges the two.
This is a behavioural change so does carry some risk of breaking some existing Brewfiles as a result. However looking at current Brewfiles in the wild, it seems like this behaviour change I'm proposing here might actually be what people thought it did all along: https://github.com/search?q=%22cask_args%20a%22%20%2Fcask_args%20%5B%5Ea%5D%2F&type=code
Given every other bundle DSL appends, I think it makes more intuitive sense for this to also append in a similar fashion.
This can make it nicer to do do things like this:
```rb
cask_args appdir: "/Applications", require_sha: true
cask "1password"
cask "firefox"
cask_args require_sha: false # retains appdir
cask …
```
> bundle/dsl: combine cask_args calls

- Library/Homebrew/bundle/adder.rb
This provides a nicer interface into using `brew bundle add` as a first command.
> bundle/adder: create Brewfile if it doesn't exist.

- Library/Homebrew/tap.rb
-----
Revert autobump logic (i.e. use `autobump.txt` file to get the list instead of sending requests to the Homebrew API).
Resolves current issues with the homebrew/core and homebrew/cask repositories without the need to revert recent PRs related to autobump (#19920, #19919).
> tap: get autobump list from `autobump.txt` file

- Library/Homebrew/cli/parser.rb
-----
Following up on https://github.com/Homebrew/brew/pull/19801#discussion_r2083232560, this slightly improves the readability message of a disabled command from:
```
Error: Calling `brew Homebrew.irb'. This command needs to be refactored, as it is 
written in a style that is disabled! Use inherits from `Homebrew::AbstractCommand' 
( see https://docs.brew.sh/External-Commands ) instead.
```
to
```
Error: Calling `brew Homebrew.irb'. This command needs to be refactored, as it is
written in a style that is disabled! Use subclassing of `Homebrew::AbstractCommand' 
( see https://docs.brew.sh/External-Commands ) instead.
```
(`irb` is not actually disabled, i just reverted it to an earlier state for demonstration purposes.)
> Improve readability of disabled command message

- Library/Homebrew/cask/installer.rb
- Library/Homebrew/download_strategy.rb
- Library/Homebrew/version.rb
Upstream suddenly plan to remove it in Ruby 3.5: https://bugs.ruby-lang.org/issues/21258.
There will be a `cgi/escape` but I think we can just avoid it entirely.
> Phase out using `cgi` library

- docs/Homebrew-on-Linux.md
-----
This PR introduces a number of changes to `Homebrew-on-Linux.md` regarding instructions for Fedora-based distributions:
- **Change CentOS to CentOS Stream**
- CentOS has been discontinued, and CentOS Stream now serves as the downstream of Fedora and the upstream of RHEL.
- **Change "Red Hat" to RHEL**
- Red Hat Enterprise Linux is commonly and officially referred to as RHEL, not "Red Hat". The former [Red Hat Linux](https://en.wikipedia.org/wiki/Red_Hat_Linux) has also been discontinued.
- **Change `yum` to `dnf`**
- `dnf` has been the default package manager on Fedora for over 10 years (since Fedora 22) and on RHEL for over 6 years (since RHEL 8).
-  More importantly, `yum groupinstall 'Development Tools'` no longer works on Fedora since its adoption of DNF5.
- This change also …
> docs/Homebrew-on-Linux: update instructions for Fedora-based distros

- Library/Homebrew/rubocops/patches.rb
- Library/Homebrew/test/rubocops/patches_spec.rb
-----
Following https://github.com/Homebrew/homebrew-core/pull/221961
I also added a corrector that I tested manually. I couldn't figure out how to test that part in `patches_spec.rb`.
> patches audit: bitbucket patches should use api

- Library/Homebrew/livecheck/strategy/bitbucket.rb
- Library/Homebrew/test/livecheck/strategy/bitbucket_spec.rb
-----
The `Bitbucket` strategy checks download or tag pages but the content is now fetched separately on page load, so the strategy is failing for all related formulae. This updates the generated strategy URLs to fetch the page content instead, which works as expected.
> Bitbucket: update generated urls

- Library/Homebrew/autobump_constants.rb
- Library/Homebrew/cask/dsl.rb
-----
Casks with `version :latest` do not require autobump for obvious reasons. Cask that use `:extract_plist` livecheck strategy can slow down CI
Thanks to @bevanjkay and @krehel for pointing that out
> cask/dsl: set `no_autobump!` automatically in some cases

- Library/Homebrew/utils/spdx.rb
Various places that use SPDX licenses specify them as downcased strings so let's be more permissive in our comparisons/validations.
> utils/spdx: do case insensitive comparison.

- Library/Homebrew/download_strategy.rb
Fixes #16669
Currently an Authorization header is added to all requests for CurlGithubPackageDownload.  It includes the contents of an `ARTIFACT_TOKEN` auth var or "A" which is used for access to ghcr.io.  This causes an issue though if you host a private mirror of GHCR where auth is optional.  This adds a conditional where for 7 of the 8 cases it adds the header, but for the 1 where you have a `DOMAIN` set and not `TOKEN`s it will skip adding the header.
I couldn't figure out a great way to test this given the environmental aspects, but I am up for suggestions and can tweak the PR to fit.
-----
> Anonymous OCI registry mirror support 

- Library/Homebrew/rubocops/shared/url_helper.rb
- Library/Homebrew/test/rubocops/urls_spec.rb
Inspired by curl's blog post, [Detecting malicious Unicode][1], this likely captures most if not all cases and nudges the user toward supplying IDNs with punycode.
A possible improvement would be telling the user exactly what punycode domain to use instead, but that may require another library as I can't quickly find something built into the Ruby stdlib that handles punycode encoding.
This also needs tests, to follow.
[1]: https://daniel.haxx.se/blog/2025/05/16/detecting-malicious-unicode/
-----
> Prohibit non-ASCII characters in URLs, nudge toward punycode

- Library/Homebrew/dev-cmd/update-maintainers.rb
- install the `man` gem group for `kramdown` so `Manpages.regenerate_man_pages` can run successfully
- hardcode the non-organisation PLC members so that they aren't missing from the GitHub team
- correctly populate the PLC members again
> dev-cmd/update-maintainers: various fixes.

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/requirements/macos_requirement.rb
- Library/Homebrew/test/requirements/macos_requirement_spec.rb
Addresses audit bug noted in https://github.com/Homebrew/homebrew-cask/pull/212798#issuecomment-2888846354, so that `requires_rosetta` is required only if the Intel-only binary might encounter an ARM-capable macOS version.
> cask/audit: skip audit_rosetta on Intel-only casks & OSes

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
- Fixes #19837.
- Some formula bumps have really long release notes which causes their bump PRs to exceed GitHub's 65k character limit for issue bodies.
> Truncate long release notes in formula PR descriptions

- .github/dependabot.yml
- update all dependabot types once a week on Friday so they can make it into the new release on (usually) Monday
- use dependabot groups for all changes so we can merge them all at once
- use the `directories` option to DRY things up
> dependabot: use more groups.

- Library/Homebrew/bundle/commands/exec.rb
In some `brew tests` runs (e.g. https://github.com/Homebrew/brew/actions/runs/15163308534/job/42634570735?pr=19991), `$CHILD_STATUS` can be `nil`. Let's handle this and avoid these flaky tests.
> bundle/commands/exec: fix exit code handling.

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/test/formatter_spec.rb
- Library/Homebrew/utils/formatter.rb
- docs/Rakefile
Add new `Formatter.truncate` method, tests and use it.
Fixes https://github.com/Homebrew/brew/issues/19994
> dev-cmd/bump-formula-pr: use `Formatter.truncate`.

- Library/Homebrew/cask/dsl.rb
-----
I did a mistake when adding `:extract_plist` no autobump reason, it tries to check livecheck strategy before livecheck block is evaluated. This PR fixes this problem
```shell
$ grep "\"autobump\": false" -r _data/cask | wc -l
2043
$ grep "\"autobump\": false" -r _data/cask | wc -l
2130
$ grep ":extract_plist" -r /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks | wc -l
87 # how many casks use `:extract_plist` strategy
```
> cask/dsl: set `no_autobump!` if livecheck uses `:extract_plist`

- Library/Homebrew/uninstall.rb
-----
Closes Homebrew/homebrew-core#177425
Because the check for the left configurational files in `etc` just matches any files that contain the name of the formula (`.*<formula name>.*`), sometimes it may suggest deleting files that 100% belong to another Homebrew formula.
F.e., because `sl` and `nss` formulae match `openssl`, if a user tries to uninstall them they see this message:
```
$ brew uninstall nss
Uninstalling /opt/homebrew/Cellar/nss/3.111... (216 files, 19.5MB)
Warning: The following may be nss configuration files and have not been removed!
If desired, remove them manually with `rm -rf`:
/opt/homebrew/etc/openssl@1.1
/opt/homebrew/etc/openssl@3
```
There's no doubt `/opt/homebrew/etc/openssl@3` belongs to the installed `openssl@3`, and we (probably) do not want to suggest …
> uninstall: exclude configurational filess that belong to other formulae

- .gitignore
- docs/.mdl_ruleset.rb
- docs/Acceptable-Casks.md
- docs/Brew-Bundle-and-Brewfile.md
- docs/Common-Issues.md
- docs/FAQ.md
- docs/Formula-Cookbook.md
- docs/Homebrew-and-Python.md
- docs/Homebrew-on-Linux.md
- docs/How-To-Open-a-Homebrew-Pull-Request.md
- docs/Installation.md
- docs/New-Maintainer-Checklist.md
- docs/Prose-Style-Guidelines.md
- docs/Tips-and-Tricks.md
- docs/vale-styles/Homebrew/README.md
Ensure that links to other pages in the docs use relative URLs for the Markdown files, rather than the full docs.brew.sh URL:
- allows anyone browsing the [docs tree on GitHub](https://github.com/Homebrew/brew/tree/master/docs) to stay there when clicking links
- avoids the situation in #19982 where `bundle exec rake test` missed a changed anchor name because the docs.brew.sh site still had the original value when the pre-commit test was run
> docs: localize internal URLs

- Library/Homebrew/formula.rb
-----
Based on https://github.com/Homebrew/homebrew-core/pull/224200, the powershell completion filename usually have _ prefix and so here I add it. There is no usage of `:pwsh` in the method `generate_completions_from_executable`, so we can change this without impact.
> feat: add _ to powershell completion filename

- .github/workflows/pkg-installer.yml
- Library/Homebrew/test/utils/github_spec.rb
- Get the release tag from the installer path.
- Remove unnecessary `gh` installation.
- Remove failing test that I can't fix.
> workflows/pkg-installer: fix release upload.

- .gitignore
- CODEOWNERS
- docs/Support-Tiers.md
Let's improve the wording of the Support Tiers document and add it to a (new) CODEOWNERS file to ensure that I or the TSC review changes.
From discussion in https://github.com/Homebrew/brew/pull/20007
> docs/Support-Tiers: tweak wording, add CODEOWNERS.

- Library/Homebrew/tap.rb
-----
I was messing around creating a new tap and tapped a git repo that was empty. I got this error because Homebrew can't figure out the branch (because there are no branches in my empty repo).
```
 ~/ brew tap --repair
Error: Passed `nil` into T.must
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12117/lib/types/_types.rb:222:in 'T.must'
/opt/homebrew/Library/Homebrew/tap.rb:594:in 'Tap#fix_remote_configuration'
/opt/homebrew/Library/Homebrew/cmd/tap.rb:57:in 'block in Homebrew::Cmd::TapCmd#run'
/opt/homebrew/Library/Homebrew/cmd/tap.rb:55:in 'Array#each'
/opt/homebrew/Library/Homebrew/cmd/tap.rb:55:in 'Homebrew::Cmd::TapCmd#run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12117/lib/types/private/methods/call_validati …
```
> tap: fix handling of `--repair` with no branches

- Library/Homebrew/brew.sh
- bin/brew
Let's move this from `bin/brew` to make things like e.g. `brew --prefix` or `brew shellenv` not reset the sudo timestamp.
This is still in a place that ensures that e.g. no untrusted formula or tap code has been run yet so should have no security implications but provide mild usability improvements.
Fixes https://github.com/Homebrew/brew/issues/20022
> brew.sh: move sudo reset timestamp.

- Library/Homebrew/api.rb
- Library/Homebrew/cask/cask.rb
- Library/Homebrew/dev-cmd/generate-cask-api.rb
- Library/Homebrew/dev-cmd/generate-formula-api.rb
- Library/Homebrew/extend/on_system.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/simulate_system.rb
- Library/Homebrew/test/formula_spec.rb
As a follow up to <https://github.com/Homebrew/brew/pull/20038>, I realized that we could probably simplify some of the logic here since the `OnSystem::ALL_OS_ARCH_COMBINATIONS` to valid bottle tag to `SimulateSystem` pattern is pretty common.
This PR just refactors some of the shared logic to make it more user-friendly.
> Refactor `OnSystem` and `SimulateSystem` bottle tag handling

- Library/Homebrew/dev-cmd/generate-cask-api.rb
- Library/Homebrew/dev-cmd/generate-formula-api.rb
Follow-up to <https://github.com/Homebrew/brew/pull/20038>
I realized that the original API an array at the top-level, but the new version was a hash. This PR fixes this so the new version has the same structure.
> Fix sharded API structure to match existing API

- Library/Homebrew/os/mac/pkgconfig/15/expat.pc
Seen in https://github.com/Homebrew/brew/pull/20046
```console
$ grep VERSION /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/usr/include/expat.h
#define XML_MAJOR_VERSION 2
#define XML_MINOR_VERSION 7
#define XML_MICRO_VERSION 1
```
> os/mac/pkgconfig/15: update `expat` version to 2.7.1

- Library/Homebrew/cask/cask_loader.rb
Handle weird edge cases where we try to read a cask from invalid paths.
Fixes https://github.com/Homebrew/brew/issues/19142
> cask_loader: improve error handling.

- Library/Homebrew/caveats.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/messages.rb
- Library/Homebrew/sorbet/rbi/dsl/caveats.rbi
- Library/Homebrew/test/caveats_spec.rb
Instead of repeatedly outputting the same identical messages across multiple packages and repeating them all for every package after they were all installed: just output the identical messages in the final caveats output instead.
Fixes https://github.com/Homebrew/brew/issues/16897
> Improve completions (and elisp) output in caveats

- .github/workflows/tests.yml
- Library/Homebrew/cask/installer.rb
- Library/Homebrew/dev-cmd/generate-analytics-api.rb
- Library/Homebrew/dev-cmd/tests.rb
- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/utils/backtrace.rb
- Remove a bunch of non-actionable/unnecessary noise in GitHub Actions CI.
- Limit number of threads used to generate analytics API data to avoid reproducible failures producing errors and requiring retries.
- Move to Debian Old Stable for testing non-system `glibc`.
- Remove unneeded core taps/updates.
- Improve naming of CI jobs to clarify purpose i.e. we're testing things work on Linux, not Ubuntu specifically.
- Remove dedicated non-online/non-generic Linux `brew tests` jobs from 3 to 1.
> Reduce Homebrew/brew CI warnings

- Library/Homebrew/dev-cmd/contributions.rb
Output messages to stderr when CSV output is enabled.
This allows doing `brew contributions --csv > contributions.csv` to save the output to a file.
> dev-cmd/contributions: improve CSV output.

- Library/Homebrew/rubocops/cask/no_overrides.rb
- Library/Homebrew/test/rubocops/cask/no_overrides_spec.rb
- Library/Homebrew/test/support/fixtures/cask/Casks/with-depends-on-macos-failure.rb
-----
Prevent `depends_on macos:` from appearing inside on_system blocks, which ensures the generated cask info displayed at https://formulae.brew.sh/ is accurate.
> rubocops/cask/no_overrides: avoid nested `depends_on macos:`

- Library/Homebrew/dev-cmd/tests.rb
- Library/Homebrew/extend/os/linux/dev-cmd/tests.rb
- Library/Homebrew/extend/os/mac/dev-cmd/tests.rb
This needs to happen after `setup_environment!` so that `HOMEBREW_TEST_GENERIC_OS` is set and `OS.linux?` and `OS.mac?` both `return false`.
Partially reverts Homebrew/brew#20079
> Revert "Filter `brew tests` spec files appropriately for each OS"

- .github/workflows/docs.yml
See https://github.com/Homebrew/formulae.brew.sh/pull/1918
I didn't realize that the `docs` workflow in formulae.brew.sh synced from here, so this PR just copies over the change I made in https://github.com/Homebrew/formulae.brew.sh/pull/1906.
I also added a comment at the top of the file marking this.
Eventually, the comments should probably be added automatically by the sync action in `.github`, but I'm going to hold off on figuring that out until https://github.com/Homebrew/.github/pull/309 and related work is done to avoid conflicts
CC @MikeMcQuaid
> Generate template API samples for `formulae.brew.sh` docs workflow

- .vscode/settings.json
I’m getting a message saying this option is deprecated and "was never used”, so may as well remove it to get rid of the message
> Remove deprecated vscode sorbet option

- Library/Homebrew/cask/artifact/abstract_artifact.rb
- Library/Homebrew/cask/artifact/relocated.rb
- Library/Homebrew/cask/dsl.rb
- Library/Homebrew/dev-cmd/tap-new.rb
-----
I previously added some instance variables in `Cask::DSL` to its `initialize` method (#19806, #19808) but I missed some last time, so we still see warnings like `The class Cask::DSL reached 8 shape variations, instance variables accesses will be slower and memory usage increased. It is recommended to define instance variables in a consistent order, for instance by eagerly defining them all in the #initialize method.`
This initializes more instance variables in `Cask` classes to resolve other situations where this warning may occur. I've been testing this for a while and haven't see any warnings with these changes but there's always a chance that there's still more work to be done.
> Cask: Initialize yet more instance variables

- .github/workflows/sync-default-branches.yml
This will allow us to migrate Homebrew/brew to `main` when we're ready while preserving `master` as a branch with the same contents.
Until we're ready to migrate, this will keep a `main` branch updated with `master`.
> Add `sync-default-branches` workflow

- Library/Homebrew/cmd/tap-info.rb
- Library/Homebrew/system_config.rb
These are basically as "default" as `master` now so we can hide them.
> Hide `main` branches from `brew tap-info` and `brew info`

- Library/Homebrew/api_hashable.rb
This fixes a significant performance issue with generating the API if git commands fail without particular settings you have in your ~/.gitconfig, causing each package to reattempt shelling out to git. We were setting `$HOME` to a fake value which would have blocked access to this config.
It is unlikely CI hit this but I did locally.
> api_hashable: retain access to global gitconfig

- Library/Homebrew/dev-cmd/tap-new.rb
- Library/Homebrew/formula_creator.rb
https://github.com/errata-ai/vale/issues/818 is fixed a year ago
-----
> Remove `vale` FIXME

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/dev-cmd/generate-cask-ci-matrix.rb
-----
Adds logic to `audit_min_os` for checking the load commands in an application's binary for its minimum macOS requirement if not specified by [`LSMinimumSystemVersion`](https://www.mothersruin.com/software/Apparency/faq.html#os-required) of its Info.plist. It does this by fetching from Info.plist the binary path, ensuring it exists and is not a shell script (e.g. `wings3d`), then looks in each slice for `LC_VERSION_MIN_MACOSX` (older SDKs) or `LC_BUILD_VERSION` (newer SDKs) for their minimum macOS version value, and returns the lowest value found. This will surface a few more minimum OS suggestions for casks that don't define any, e.g. `alacritty` (multi-arch download) and `contour` (arch-specific downloads).
Since this audit checks more than Info.plist, changed `plist_` references …
> cask/audit: also check binary for minimum OS

- Library/Homebrew/utils/github/api.rb
Let's not use `T.unsafe(nil)` but instead an empty hash.
Fixes https://github.com/Homebrew/brew/issues/20127
> utils/github/api: fix Sorbet types.

- Library/Homebrew/cmd/fetch.rb
- Library/Homebrew/cmd/info.rb
- Library/Homebrew/cmd/update-report.rb
> cmd: set `typed: strict`

- Library/Homebrew/cask/installer.rb
- Library/Homebrew/test/cask/reinstall_spec.rb
-----
This messaging is confusing, and doesn't feel helpful.
Currently:
```
╰─ brew uninstall --zap foo
==> Implied `brew uninstall --cask foo`
```
In my mind, I take that to be "Oh, it must have wanted me to `brew uninstall --cask --zap foo`".  `zap` only applies to casks, and running `brew uninstall --cask --zap foo` still emits the same message, so I'm not sure what this is trying to tell the user.
> cask/installer: remove confusing `zap` messaging

- Library/Homebrew/rubocops/caveats.rb
- Library/Homebrew/test/rubocops/caveats_spec.rb
This will avoid issues with the JSON API.
I expect this to fail CI but reveal problematic caveats that must be updated.
Fixes https://github.com/Homebrew/brew/issues/19327
> rubocops/caveats: check for dynamic caveats.

- Library/Homebrew/development_tools.rb
- Library/Homebrew/extend/os/linux/cask/quarantine.rb
- Library/Homebrew/extend/os/linux/compilers.rb
- Library/Homebrew/extend/os/linux/development_tools.rb
- Library/Homebrew/extend/os/linux/simulate_system.rb
- Library/Homebrew/extend/os/linux/system_config.rb
- Library/Homebrew/extend/os/mac/development_tools.rb
- Library/Homebrew/extend/os/mac/diagnostic.rb
- Library/Homebrew/extend/os/mac/extend/ENV/shared.rb
- Library/Homebrew/extend/os/mac/extend/ENV/super.rb
- Library/Homebrew/extend/os/mac/hardware/cpu.rb
- Library/Homebrew/extend/os/mac/language/java.rb
- Library/Homebrew/extend/os/mac/readall.rb
- Library/Homebrew/extend/os/mac/sandbox.rb
- Library/Homebrew/extend/os/mac/simulate_system.rb
- Library/Homebrew/extend/os/mac/utils/socket.rb
- Library/Homebrew/sandbox.rb
I found that there were several instances where class methods were not properly overidden by `extend/os` because there were either not prepended to the `singleton_class`, or they were prepended as class methods which does not work as expected.
While we’re here, I also migrated a few cases of monkey-patching in `extend/os` to use the prepend pattern used in the majority of the code.
Also, I standardized the structure of these to use a `ClassMethods` sub-module to define all class methods to be prepended. I think this makes the code much clearer since it is easy to tell that this module will be included onto a singleton class without needing to search for the line where the module is actually included.
I highly recommend reviewing with whitespace changes hidden: …
> Fix handling of class methods in `extend/os`

- Library/Homebrew/diagnostic.rb
- Library/Homebrew/extend/os/linux/diagnostic.rb
- Library/Homebrew/extend/os/mac/diagnostic.rb
Fixes #20148
This PR modifies the `check_cask_software_versions` diagnostic check so that it only reports SIP status on macOS, and displays the appropriate OS version on both macOS and Linux.
While we're here, let's move the check for deprecated cask taps to run on both macOS and Linux since you can now have casks on Linux
> Fix `brew doctor` cask handling on Linux

- Library/Homebrew/download_strategy.rb
URLs using `:fossil` checkouts haven't worked since `fossil` switched from printing [`uuid:` to `hash:`](https://fossil-scm.org/home/info/8ad5e4690854a81a) for `fossil info tip`.
Also, fix this error for CVS checkouts:
```console
$ brew fetch -s -v --HEAD mandoc
==> Cloning anoncvs@mandoc.bsd.lv:/cvs
/usr/bin/env PATH=/usr/bin:/opt/homebrew/opt/cvs/bin:/opt/homebrew/Library/Homebrew/shims/shared:/bin:/usr/sbin:/sbin cvs -d anoncvs@mandoc.bsd.lv:/cvs checkout -d /Users/eric/mandoc--cvs mandoc
Warning: Permanently added 'mandoc.bsd.lv' (ED25519) to the list of known hosts.
cvs [server aborted]: absolute pathname `/Users/eric/mandoc--cvs' illegal for server
Error: Failed to download resource "mandoc"
Failure while executing; `/usr/bin/env …
```
> download_strategy: fossil now outputs `hash:`

- Library/Homebrew/formula_creator.rb
To fix subsequent `brew audit` error:
* line 8, col 3: Version v0.38.1 should not have a leading 'v'
-----
> create: strip 'v' prefix from version

- Library/Homebrew/diagnostic.rb
Follow-up to #20151 and #20152
On Linux with a cask installed, `brew doctor` displays some unhelpful warnings about `xattr` and cask quarantine. This PR attempts to improve those.
Before:
```console
$ brew doctor 
Warning: No Cask quarantine support available: there's no working version of `xattr` on this system.
/usr/bin/env: ‘/usr/bin/xattr’: No such file or directory
Warning: unknown xattr error: /usr/bin/env: ‘/usr/bin/xattr’: No such file or directory
```
After:
```console
$ brew doctor
Warning: No Cask quarantine support available: not available on Linux.
Warning: Unable to find `xattr`.
```
Note: it might be better to not even run the `check_cask_xattr` if there is no quarantine support anyway, but I wasn’t 100% sure whether `xattr` was used for anything except quarantine.
Also, …
> Improve `brew doctor` warnings about `xattr` and cask quarantine

- Library/Homebrew/rubocops/caveats.rb
This doesn't really matter for non-API taps.
Apologies @Bo98 that you mentioned this in https://github.com/Homebrew/brew/pull/20135 and I applied it but it ended up reverted in a later version (despite me fixing the tests).
Note @ReenigneArcher that this is effectively a revert of https://github.com/Homebrew/brew/pull/20135 for non-core taps. Apologies for the confusion.
> rubocops/caveats: only apply dynamic logic check to core.

- Library/Homebrew/mcp_server.rb
- Library/Homebrew/test/mcp_server_spec.rb
We need to handle when `stdin` is closed but there's no interrupt signal.
Without this, the server will be stuck an in infinite busy loop.
> mcp_server: fix EOF handling.

- package/scripts/postinstall
This is automatic for `/usr/local/bin/brew` but let's do it manually for `/opt/homebrew/bin/brew` too.
See also https://github.com/Homebrew/install/pull/988
Fixes https://github.com/Homebrew/install/issues/986
> package/scripts/postinstall: add Homebrew to PATH.

- Library/Homebrew/cask/tab.rb
- Library/Homebrew/dev-cmd/bottle.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/tab.rb
I bailed before going all the way to `typed: strict` but this should at least improve things and fix:
`Library/Homebrew/tab.rb:111: warning: The class Tab reached 8 shape variations, instance variables accesses will be slower and memory usage increased.`
> tab, cask/tab: add more Sorbet types and signatures.

- Library/Homebrew/download_strategy.rb
> download_strategy: Add logging when a cached download is being ignored

- Library/Homebrew/formula_creator.rb
- Library/Homebrew/test/formula_creator_spec.rb
-----
When running `brew create https://github.com/buildpacks/pack` the version is not detected from the URL, so the version from the latest release is used. But the URL still doesn't point to the source code archive. This PR constructs the URL to point to the source archive for the detected release or tag.
> create: detect URL from latest release if it isn't archive

- Library/Homebrew/cmd/update.sh
Let's avoid people sticking on the `master` branch unnecessarily.
> cmd/update: improve Homebrew/brew and homebrew-cask `main` migration.

- Library/Homebrew/bundle/brew_dumper.rb
- Library/Homebrew/bundle/brew_dumper.rbi
- Library/Homebrew/bundle/checker.rb
- And `brew typecheck --update` this time to make sure Tapioca doesn't mess with the RBI file!
-----
- This reverts commit 68dbf12220f9a52ddf5ca5eb3aa1b356aa42da3a that was a revert of commit 68596ec720a50f44ae9c30c5806aa7f2d4bcc96f because I put the RBI file in the wrong place and Tapioca got rid of it, causing this week's release to be blocked.
> Reapply "Make some of the `bundle` commands Sorbet `typed: true`"

- Library/Homebrew/dev-cmd/bump-formula-pr.rb
The release notes link is not rendered as a proper hyperlink, this fixes it.
Few examples of PRs with unclickable links:
* https://github.com/Homebrew/homebrew-core/pull/228256
* https://github.com/Homebrew/homebrew-core/pull/228263
* https://github.com/Homebrew/homebrew-core/pull/228267
-----
> dev-cmd/bump-formula-pr: release notes as proper html link

- Library/Homebrew/extend/ENV/super.rb
---
Since https://github.com/PyO3/maturin/pull/2421, `maturin` will now download its own rust when missing. Let's disable that here since it affects a lot of python formulae and will otherwise go undetected.
> extend/ENV/super: set `MATURIN_NO_INSTALL_RUST`

- Library/Homebrew/install.rb
-----
- Fixes #20199.
- Because `name` is not a method on `FormulaInstaller`, instead `formula` shows the name.
Before:
```
$ brew install -n hello
Error: undefined method 'name' for an instance of FormulaInstaller
/opt/homebrew/Library/Homebrew/install.rb:330:in 'Array#map'
/opt/homebrew/Library/Homebrew/install.rb:330:in 'Homebrew::Install.install_formulae'
```
After:
```
$ brew install -n hello
==> Would install 1 formula:
hello
```
> Fix "undefined method 'name' for an instance of FormulaInstaller"

- docs/Homebrew-on-Linux.md
Tested on Fedora 42 and RHEL 10 (latest for both).
Note: Fedora 42 uses dnf5 while CentOS Stream/RHEL 10 use dnf4
See:
- https://github.com/Homebrew/install/pull/894
- https://github.com/Homebrew/install/blob/0fd28f83c8a60d8a8fc1d15a1f023d01aa4b7de5/install.sh#L1133
-----
> docs/Homebrew-on-Linux: update dnf5 syntax, centos/rhel section

- Library/Homebrew/cask/url.rb
- docs/Formula-Cookbook.md
Reorders "URL download strategies" and "Unstable versions" sections, improves the table of strategies, and fills some holes in what's documented.
> Formula-Cookbook: improve download strategy info

- Library/.rubocop.yml
- Library/Homebrew/bundle/brew_checker.rb
- Library/Homebrew/bundle/brew_service_checker.rb
- Library/Homebrew/bundle/checker.rb
- Library/Homebrew/bundle/commands/cleanup.rb
- Library/Homebrew/bundle/commands/dump.rb
- Library/Homebrew/bundle/commands/list.rb
- Library/Homebrew/bundle/dumper.rb
- Library/Homebrew/bundle/formula_dumper.rb
- Library/Homebrew/bundle/formula_installer.rb
- Library/Homebrew/bundle/installer.rb
- Library/Homebrew/bundle/lister.rb
- Library/Homebrew/bundle/skipper.rb
- Library/Homebrew/cmd/bundle.rb
- Library/Homebrew/extend/os/mac/diagnostic.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/cmd/bundle.rbi
- Library/Homebrew/test/bundle/brew_dumper_spec.rb
- Library/Homebrew/test/bundle/brew_installer_spec.rb
- Library/Homebrew/test/bundle/commands/check_spec.rb
- Library/Homebrew/test/bundle/commands/cleanup_spec.rb
- Library/Homebrew/test/bundle/commands/dump_spec.rb
- Library/Homebrew/test/bundle/commands/install_spec.rb
- Library/Homebrew/test/bundle/commands/list_spec.rb
- Library/Homebrew/test/bundle/dumper_spec.rb
-----
- Homebrew Bundle referred to formulae as "brews". But it referred to casks as "casks" and taps as "taps".
- Let's use the same terminology everywhere.
- (I know that `brew "hello"` is the formula syntax in the Brewfile, so I'm not changing that (though would be up for it, in a backwards compatible manner), just making the code more consistent.)
> bundle: Rename "brews" to "formulae" for consistency

- Library/Homebrew/style.rb
`shfmt` no longer allows using symlinks
> style: run shfmt on real brew

- .github/workflows/pkg-installer.yml
- Library/Homebrew/dev-cmd/tap-new.rb
Use the `secrets.GITHUB_TOKEN` instead of `github.token` which is kinda pointed out here: https://docs.github.com/en/actions/how-tos/security-for-github-actions/security-guides/use-github_token-in-workflows
> Replace `github.token` by `secrets.GITHUB_TOKEN`

- Library/Homebrew/formulary.rb
-----
Formulae can execute arbitrary Ruby code when being loaded. In
particular, they can print to stdout with methods like `puts`. This can
break the parsing of output of commands like `brew info --json=v2`.
Let's fix that by capturing the output to stdout, and then printing
those messages to stderr instead (using `opoo` to try to discourage
formula authors from doing this).
> formulary: prevent formulae from printing to stdout while being loaded

- Library/Homebrew/bundle/cask_dumper.rb
- Library/Homebrew/bundle/cask_installer.rb
- Library/Homebrew/bundle/commands/cleanup.rb
- Library/Homebrew/test/bundle/cask_dumper_spec.rb
- Library/Homebrew/test/bundle/commands/cleanup_spec.rb
This adds support for Cask old tokens used for renames of Casks.
We'll now correctly check these at installation time to avoid repeatedly installing renamed Casks and dump them in the Brewfile. We also use this logic to avoid cleaning up renamed Casks.
Fixes #20222
> Support Cask renames when installing/dumping

- Library/Homebrew/extend/pathname.rb
- Library/Homebrew/os/linux/elf.rb
- Library/Homebrew/os/mac/mach.rb
Will fix or at least partly address:
```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:225: warning: The class Pathname reached 8 shape variations, instance variables accesses will be slower and memory usage increased.
35
It is recommended to define instance variables in a consistent order, for instance by eagerly defining them all in the #initialize method.
```
> Improve some `Pathname` instance variable handling

- Library/Homebrew/rubocops/all.rb
- Library/Homebrew/rubocops/zero_zero_zero_zero.rb
- Library/Homebrew/test/rubocops/zero_zero_zero_zero_spec.rb
Add a new RuboCop to detect the use of 0.0.0.0 in formulae which indicates binding to all network interfaces, internally or externally, so is a bad default and potentially a security risk.
> Add ZeroZeroZeroZero cop

- Library/Homebrew/rubocops/text.rb
- Library/Homebrew/test/rubocops/text_spec.rb
-----
- I found a few occurrences of this pattern from https://github.com/orgs/Homebrew/projects/5?pane=issue&itemId=97021840, that is an automated style request for: `core: use / instead of + operator in e.g. (lib+"lv").install "lv.hlp"`, but for more than just `lib`.
/cc @EricFromCanada as you spotted this one!
> rubocops/text: Prefer `lib/"string"` over `lib+"string"`

- Library/Homebrew/test/support/fixtures/rubocop@x.x.x.rbi
At least for me locally: `brew style` complains about this and `brew style --fix` autocorrects it.
> `fixtures/rubocop@x.x.x.rbi`: fix style.

- Library/Homebrew/api.rb
- Library/Homebrew/api/cask.rb
- Library/Homebrew/api/download.rb
- Library/Homebrew/api/formula.rb
- Library/Homebrew/brew.rb
- Library/Homebrew/download_queue.rb
- Library/Homebrew/retryable_download.rb
- Library/Homebrew/tap.rb
This assumes that all should be downloaded (at least once) on `brew` commands being run.
Requires a certain amount of cleanup and refactoring around our API handling and Tap migration methods (which were both weirdly placed and in some cases broken).
Behaviour without `HOMEBREW_DOWNLOAD_CONCURRENCY` set should be unchanged.
Extracted from https://github.com/Homebrew/brew/pull/20245
> Optionally parallelise API file downloads

- docs/MCP-Server.md
- docs/index.md
Provide some basic instructions on how to use and configure it.
> docs: add Homebrew's MCP server documentation.

- Library/Homebrew/formula_installer.rb
Fixes dispatch-build-bottle in Homebrew/core being broken.
> formula_installer: ignore bottle_tab_runtime_dependencies errors

- Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
-----
This is really only used in Homebrew/core, so it should be safe to just
change `ref` here to `main`. Without this, `dispatch-build-bottle`
creates PRs that mistakenly target the `master` branch instead of the
`main` branch.
> dispatch-build-bottle: use `main` branch

- Library/Homebrew/extend/pathname.rb
Overwriting upstream content potentially causes major confusion at best, major breakage at worst.
> env_script_all_files: don't overwrite existing stuff

- Library/Homebrew/download_queue.rb
- Library/Homebrew/test/cmd/install_spec.rb
If `HOMEBREW_DOWNLOAD_CONCURRENCY` is set, every `brew` command calls `Tty::hide_cursor` and `Tty::show_cursor`, which prints invisible characters to `stdout`. This breaks things like `brew info --json=v2 wget | jq .` and also some of `brew tests`.
This PR modifies the `DownloadQueue#fetch` method to return early if there are no pending downloads, and to handle a single download as if `HOMEBREW_DOWNLOAD_CONCURRENCY` is set to 1. This means that we only enter the region that needs to hide and show the cursor if we actually need.
To avoid this regressing in the future, we should really have at least one integration test that has concurrency enabled, but I held off on that for now since we may get that for free if concurrent downloads ever become the default
> Fix some stdout issues with concurrence

- Library/Homebrew/api/cask.rb
- Library/Homebrew/api/formula.rb
- Library/Homebrew/brew.rb
- Library/Homebrew/cmd/fetch.rb
- Library/Homebrew/download_queue.rb
- ensure that the `brew.rb` downloads of the API files only happens when they are more stale (>1 day) and using the API is not disabled
- default `brew fetch` and `brew install` to a single download retry
> Improve Download Queue behaviour

- Library/Homebrew/retryable_download.rb
This is needed in case these files are e.g. corrupt.
> retryable_download: retry on bottle manifest errors.

- Library/Homebrew/cask/audit.rb
-----
Shell scripts cannot be codesigned, so we need to skip them in the audit.
> cask/audit: skip signing audit for shell scripts

- Library/Homebrew/install.rb
- Library/Homebrew/test/cmd/install_spec.rb
- Library/Homebrew/test/cmd/reinstall_spec.rb
- Library/Homebrew/test/cmd/upgrade_spec.rb
- Library/Homebrew/upgrade.rb
These were unfortunately non-functional after recent changes.
Will issue a new release with this once merged.
> Fix handling of formula install blocks

- Library/Homebrew/cask/audit.rb
-----
This PR proposes a change to use the newer `syspolicy_check` tool for Application codesign audit.
Also check notarization for binaries.
@Homebrew/cask the main discussion point here is whether we want to require notarization for binaries or not.
> cask/audit: refine codesign audits

- Library/Homebrew/tap.rb
-----
This will re-add casks that are deprecated as `unsigned` to autobump (as a special case).
The caveat here is that if they become signed, the autobump fails (because the audit will fail) - but we are regularly checking the failures in the CI job.
I'm open to not making this change if others disagree.
> tap: continue to autobump deprecated unsigned casks

- Library/Homebrew/formula_installer.rb
- Library/Homebrew/test/formula_installer_spec.rb
- Library/Homebrew/utils/spdx.rb
`HOMEBREW_FORBIDDEN_LICENSES=public_domain` is [documented](https://docs.brew.sh/License-Guidelines#specifying-forbidden-licenses) as supported but doesn't actually work. Unclear if it ever did but we can fix it trivially anyway.
Also fix some incorrect types in spdx.rb that we only don't notice because we use `T.untyped` too much.
> Fix forbidding special license refs

- Library/Homebrew/cask/audit.rb
-----
Running the audit differently here can result in conflicting audits.
https://github.com/Homebrew/homebrew-cask/pull/221395
> cask/audit: skip signing audit without gktool

- Library/Homebrew/cask/cask_loader.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/system_command.rb
- Library/Homebrew/test/system_command_spec.rb
The `Formulary` and `system_command` debug output is incredibly verbose by default and this is pretty annoying when all you want is to get better backtraces when there's an error.
Instead, let's require `--verbose` and `--debug` for the noisiest output message types.
> Make `--debug` output a bit quieter by default

- Library/Homebrew/extend/os/linux/development_tools.rb
This makes it easier to test the automatic installation of the libc and compiler formulae without having to change the code.
This is particularly useful now we don't have any official Docker images for this.
> linux/development_tools: add undocumented environment variables.

- .github/workflows/vendor-gems.yml
This should avoid maintainers needing to run with `workflow_dispatch` for dependabot PRs.
> workflows/vendor-gems: push to PRs from dependabot.

- Library/Homebrew/cmd/upgrade.rb
`brew upgrade --help` currently doesn't mention the existence of HOMEBREW_UPGRADE_GREEDY like e.g. `brew outdated --help` does.
-----
> `brew upgrade --help` missing HOMEBREW_UPGRADE_GREEDY

- Library/Homebrew/utils/gems.rb
Speculative fix for https://github.com/Homebrew/brew/issues/20339 as I haven't actually reproduced the problem to know whether this fixes it.
> utils/gems: use Homebrew-specific gem spec cache

- Library/Homebrew/api/cask.rb
- Library/Homebrew/api/formula.rb
`cache` is the directory containing the files so downloading one package would prevent any other package from fetching. Fix this by checking the file we use instead.
Fixes #20332
> api: fix handling of source downloads

- Library/Homebrew/bundle/whalebrew_dumper.rb
- Library/Homebrew/bundle/whalebrew_installer.rb
- Library/Homebrew/cask/audit.rb
- Library/Homebrew/cask/dsl.rb
- Library/Homebrew/cask/url.rb
- Library/Homebrew/dev-cmd/audit.rb
- Library/Homebrew/extend/pathname.rb
- Library/Homebrew/extend/time.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/git_repository.rb
- Library/Homebrew/resource.rb
- Library/Homebrew/tap.rb
- Library/Homebrew/utils/string_inreplace_extension.rb
The next minor release will be Homebrew 4.6.0 so let's do the usual deprecation/disable/remove code cycle.
> Deprecate/disable/remove code for Homebrew 4.6

- Library/Homebrew/extend/pathname/observer_pathname_extension.rb
> observer_pathname_extension: add strict Sorbet types.

- Library/Homebrew/dev-cmd/cat.rb
-----
Fixes
❯ HOMEBREW_BAT=1 brew cat xz
Error: uninitialized constant Kernel::Formula
/opt/homebrew/Library/Homebrew/extend/kernel.rb:445:in 'block in <module:Kernel>'
/opt/homebrew/Library/Homebrew/dev-cmd/cat.rb:33:in 'block in Homebrew::DevCmd::Cat#run'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/lib/ruby/3.4.0/fileutils.rb:241:in 'Dir.chdir'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/lib/ruby/3.4.0/fileutils.rb:241:in 'FileUtils#cd'
/opt/homebrew/Library/Homebrew/dev-cmd/cat.rb:29:in 'Homebrew::DevCmd::Cat#run'
/opt/homebrew/Library/Homebrew/brew.rb:113:in '<main>'
> dev-cmd/cat: add `require "formula"`

- Library/Homebrew/dev-cmd/bottle.rb
- Library/Homebrew/extend/kernel.rb
-----
This does the same as #20356 for `ensure_formula_installed!`. See
discussion at #20352.
Unfortunately, one must still `require "formula"` before using this
method because of the `returns(Formula)`, but tightening the type
signature is generally a good idea anyway.
Closes #20352.
> extend/kernel: tighten type sig for `ensure_formula_installed!`

- Library/Homebrew/dev-cmd/bottle.rb
- Library/Homebrew/dev-cmd/bump.rb
- Library/Homebrew/dev-cmd/cat.rb
- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/style.rb
- Library/Homebrew/test/utils/git_spec.rb
- Library/Homebrew/utils/git.rb
- Library/Homebrew/utils/pypi.rb
-----
`ensure_formula_installed!` requires the `Formula` class to be loaded
before being called to work properly.
Let's guarantee that instead by implementing it as an instance method of
the `Formula` class.
See discussion at #20358.
> Replace `ensure_formula_installed!` with `Formula#ensure_installed!`

- docs/Formula-Cookbook.md
-----
- The `bin.write_exec_script Dir[libexec/"bin/*"]` is used in core formulae, whereas the previously recommended syntax is not found at all. Let's make reality match the documentation.
- Part of https://github.com/orgs/Homebrew/projects/5?pane=issue&itemId=97021840.
> Formula-Cookbook: Recommend the in-use `write_exec_script` syntax

- Library/Homebrew/extend/pathname.rb
-----
There are single pathname not array for `write_exec_script`.
- https://github.com/search?q=repo:Homebrew/homebrew-core+write_exec_script+%22&type=code
I may change all the formula code but let just try to change type here first, to get others opinion.
> pathname: add type to `write_exec_script`

- Library/Homebrew/extend/kernel.rb
-----
`brew edit` no longer accepts multiple formula names to open:
```
$ brew edit vim mc
Error: wrong number of arguments (given 2, expected 1)
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12357/lib/types/private/methods/signature.rb:204:in 'T::Private::Methods::Signature#each_args_value_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12357/lib/types/private/methods/call_validation.rb:227:in 'T::Private::Methods::CallValidation.validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.5.12357/lib/types/private/methods/_methods.rb:277:in 'block in Kernel#_on_method_added'
/opt/homebrew/Library/Homebrew/dev-cmd/edit.rb:63:in 'Homebrew::DevCmd::Edit#run' …
```
> extend/kernel: allow exec_editor to open multiple files at once

- Library/Homebrew/livecheck/skip_conditions.rb
- Library/Homebrew/test/livecheck/skip_conditions_spec.rb
-----
We've been adding `disable!` calls with a future date to casks using an unsigned app. That implicitly deprecates the cask until it reaches the disable date, so we've been having to add simple `livecheck` blocks to casks that use a default check to ensure that livecheck continues to check them (e.g., https://github.com/Homebrew/homebrew-cask/pull/222471). It was suggested that it would be simpler to have livecheck not skip casks that have a `disable!` call with a `because: :unsigned` argument and I agree, so this modifies `SkipConditions` to add a special case for this scenario.
> SkipConditions: special case unsigned deprecations

- Library/Homebrew/cmd/update.sh
Following [McQuaid's suggestion](https://github.com/Homebrew/brew/pull/20323#issuecomment-3131943340), I chose a practical target: installing Homebrew on Alpine Linux. I understood each step and the current issues faced, then I wrote [an article](https://github.com/chirsz-ever/install-homebrew-on-alpine-linux) describing the installation process.
According to [the current tier policy](https://github.com/Homebrew/brew/blob/563d066821df890742a1d6961c47d6aa9d2d250a/docs/Support-Tiers.md), Alpine Linux should be considered Tier 2. Since Homebrew doesn't appear to be interested in migrating its images to Alpine, I didn't add CI tests running on Alpine Linux.
The current issues of installing and running Homebrew on Alpine Linux are:
- It needs to patch `ldd` for installation.
- This is …
> cmd/update: use short option in update.sh

- Library/Homebrew/api/json_download.rb
- Library/Homebrew/api/source_download.rb
- Library/Homebrew/bottle.rb
- Library/Homebrew/cask/download.rb
- Library/Homebrew/download_queue.rb
- Library/Homebrew/downloadable.rb
- Library/Homebrew/exceptions.rb
- Library/Homebrew/resource.rb
- Library/Homebrew/retryable_download.rb
- Library/Homebrew/software_spec.rb
Update the naming, presence and values for various download queue methods to improve the output for users while making the internal code a little easier to follow.
While we're here, also ensure that a single formula download still displays the download queue output and indirectly fix an issue with bottle manifests being named incorrectly (https://github.com/Homebrew/brew/pull/20353#issuecomment-3148363345)
> Improve Download Queue output

- Library/Homebrew/diagnostic.rb
While filing https://github.com/Homebrew/brew/issues/20379, I lost where I was because I followed the given instruction. Instead, let's use pushd/popd so the user is returned to their pwd if the git operations succeed.
-----
> diagnostic: Use pushd/popd in uncommited modifications nudge

- Library/Homebrew/service.rb
- Library/Homebrew/services/formula_wrapper.rb
This better matches other field and existing behaviour.
Fixes https://github.com/Homebrew/brew/issues/20387
> service: ensure JSON cron output can be `null`.

- Library/Homebrew/download_queue.rb
- Library/Homebrew/exceptions.rb
- Library/Homebrew/retryable_download.rb
- Library/Homebrew/test/exceptions_spec.rb
When not using concurrent downloads, the hash of the download is always displayed:
```
$ HOMEBREW_DOWNLOAD_CONCURRENCY= brew fetch -s hello
==> Downloading https://ftp.gnu.org/gnu/hello/hello-2.12.2.tar.gz
############################################################################################################################################################## 100.0%
Downloaded to: /Users/eric/Library/Caches/Homebrew/downloads/4de8a1c9a03acef91d6f2651328042790d8e4929f1d6bab9e097edb88d5846f3--hello-2.12.2.tar.gz
SHA-256: 5a9a996dc292cc24dcf411cee87e92f6aae5b8d13bd9c6819b4c7a9dce0818ab
==> Retrying download in 2s... (1 try left)
==> Downloading https://ftp.gnu.org/gnu/hello/hello-2.12.2.tar.gz
################################################################################################# …
```
> download_queue: display hash of rejected download

- Library/Homebrew/download_queue.rb
We use `Resource` in a few places here so need to require it.
> download_queue: add missing require.

- Library/Homebrew/rubocops/patches.rb
- Library/Homebrew/test/rubocops/patches_spec.rb
-----
Two correctors in the rubocop patches.rb were broken, which I found by adding tests. This PR also fix them. I removed redundant tests.
> patches audit: add tests for patches corrector

- Library/Homebrew/os/linux/ld.rb
-----
The system `/etc/ld.so.conf` may contain broken entries (e.g., exist but are not readable). If this scenario happens on a cloud machine while the users do not have `sudo` access, they cannot fix that, and `brew` always crashes.
Partial failure log from mine:
```text
Error: An exception occurred within a child process:
Errno::EACCES: Permission denied @ rb_sysopen - /etc/ld.so.conf.d/nvcr-1788820824.conf
/nfs-hg/prod/containers/panxuehai/dev/.linuxbrew/Homebrew/Library/Homebrew/os/linux/ld.rb:62:in 'File#initialize'
/nfs-hg/prod/containers/panxuehai/dev/.linuxbrew/Homebrew/Library/Homebrew/os/linux/ld.rb:62:in 'IO.open'
/nfs-hg/prod/containers/panxuehai/dev/.linuxbrew/Homebrew/Library/Homebrew/os/linux/ld.rb:62:in 'Pathname#open' …
```
> os/linux/ld: do not crash the program if the `ld.so.conf` entry is not readable

- Library/Homebrew/service.rb
-----
Following through on the discussion at https://github.com/Homebrew/brew/pull/20324#discussion_r2238048742
> Simplify Service attr helper methods

- Library/Homebrew/api.rb
- Library/Homebrew/api/cask.rb
- Library/Homebrew/api/formula.rb
- Library/Homebrew/dev-cmd/generate-cask-api.rb
- Library/Homebrew/dev-cmd/generate-formula-api.rb
- Library/Homebrew/utils/analytics.rb
This PR does a few cleanup things:
1. Removes references to `HOMEBREW_USE_INTERNAL_API` in `Homebrew::API::{Formula,Cask}`. This functionality will end up living in `Homebrew::API::Internal` (coming soon)
2. Move the `formula_aliases.txt` file generation to a helper method in `Homebrew::API`. This is only used in one place for now, but eventually will be used in `Homebrew::API::Internal`
3. Enable download queue support for individual formula/cask API fetches
4. Add alias, rename, and tap migration information to the internal API generation
A quick note on the last item: this means that the minimal JSON file now is in this format:
```json
{
"formulae": {
"name": ["pkg_version", rebuild, "sha256"],
...
},
"aliases": {
"alias_name": "real_name",
...
},
"renames": {
"old_name": "real_name", …
```
> Cleanup internal API handling

- Library/Homebrew/extend/os/linux/keg_relocate.rb
-----
This needs to be handled more carefully. It probably works fine for
bottles built *after* this change was added, but it breaks bottles built
before this exclusion was added.
Let's remove it for now to limit the extent of the breakage.
> os/linux/keg_relocate: remove `protodesc_cold` exclusion

- Library/Homebrew/shims/super/rustc_wrapper
-----
In #20424, we moved `HOMEBREW_RUSTFLAGS` to the end of the compiler
invocation, but didn't update the comment. Let's fix that.
While we're here, let's fix `shellcheck disable`s.
> shims/super/rustc_wrapper: fix comment

- Library/Homebrew/extend/os/linux/keg_relocate.rb
- Library/Homebrew/extend/os/mac/keg_relocate.rb
- Library/Homebrew/keg_relocate.rb
-----
We removed this exclusion in #20423 because it broke pouring of existing
bottles, which still need relocation.
Let's skip relocation only when bottling, to avoid breaking existing
bottles that need to be relocated when pouring.
> os/linux/keg_relocate: skip ELF files with `protodesc_cold` only when bottling

- Library/Homebrew/formulary.rb
- Library/Homebrew/test/formulary_spec.rb
- Allow cache paths in FromPathLoader when HOMEBREW_FORBID_PACKAGES_FROM_PATHS is set
- Fixes issue where HEAD installations fail due to temporary source downloads
- Add test case to verify cache paths are allowed when path restrictions are enabled
The issue occurred because HEAD installations download formula sources to cache directories, but HOMEBREW_FORBID_PACKAGES_FROM_PATHS only allowed paths from HOMEBREW_CELLAR and HOMEBREW_LIBRARY/Taps, causing the installation to fail.
Since #20414, `HOMEBREW_FORBID_PACKAGES_FROM_PATHS` is now enabled by default, which may cause `brew install --HEAD formula` to fail.
Closes: homebrew/brew#issue-number
-----
> Fix HEAD installations with HOMEBREW_FORBID_PACKAGES_FROM_PATHS

- .github/workflows/docs.yml
- .github/workflows/rubydoc.yml
-----
These aren't getting correctly updated by Dependabot, and are syncing these old versions out to our other repos. Let's manually bump them while debugging Dependabot.
> workflows: manually bump setup-ruby

- Library/Homebrew/formulary.rb
- Don't check if the `realpath` includes `/`: it always will. Instead, see if the originally user-passed `ref` includes `/` or ends with `.rb`.
- Always raise an error message, don't silently return.
Fixes https://github.com/Homebrew/brew/issues/20441
Fixes https://github.com/Homebrew/brew/issues/20448
Fixes https://github.com/Homebrew/brew/issues/20452
> formulary: improve/loosen path rejection logic.

- Library/Homebrew/cask/audit.rb
- Library/Homebrew/cask/dsl.rb
- Library/Homebrew/cask/dsl/rename.rb
- Library/Homebrew/cask/installer.rb
- Library/Homebrew/rubocops/cask/constants/stanza.rb
- Library/Homebrew/sorbet/rbi/dsl/cask/cask.rbi
- Library/Homebrew/test/cask/dsl/rename_spec.rb
- Library/Homebrew/test/cask/dsl_spec.rb
- Library/Homebrew/test/cask/installer_spec.rb
- docs/Cask-Cookbook.md
-----
*A majority of this code is written by claude, so it needs a more detailed read-through, which I will do before marking ready.*
Opening as a draft for any conceptual notes at this stage.
This PR introduces a new dsl `rename`.
There are some instances where we are required to rename files before installation because we cannot detect the path systematically. At present some casks are using `preflight` blocks.
This also allows us to make sure that we can correctly run `audit_rosetta` and `audit_signing` on these casks, as the paths can be found correctly.
Replaces:
```ruby
preflight do
staged_path.glob("RØDECaster App*.pkg")&.first&.rename(staged_path/"RØDECaster App.pkg")
end
```
With:
```ruby
rename "RØDECaster App*.pkg", "RØDECaster App.pkg"
```
> cask/dsl/rename: add new `rename` dsl

- Library/Homebrew/rubocops/shared/url_helper.rb
- Library/Homebrew/test/rubocops/urls_spec.rb
-----
Update the audit to prefer ftpmirror.gnu.org over ftp.gnu.org as suggested by GNU [^1]:
> We recommend using this generic ftpmirror.gnu.org address wherever possible in links, documentation, etc., to reduce load on the main GNU server.
The audit is temporarily disabled to allow migrating all homebrew/core formulae first.
Should help to address #20456.
[^1]: https://www.gnu.org/server/mirror.en.html
> Update and temporarily disable GNU mirror audit

- Library/Homebrew/rubocops/shared/url_helper.rb
- Library/Homebrew/test/rubocops/urls_spec.rb
-----
Follow-up to Homebrew/brew#20461 and Homebrew/homebrew-core#233493.
> Re-enable GNU mirror audit

- Library/Homebrew/formulary.rb
We need to handle symlinks in both directions for formulae in the cellar/taps/cache otherwise we can get the nonsensical situation of telling people a formula must me in a tap when it already is (but is symlinked from elsewhere).
Fixes https://github.com/Homebrew/brew/issues/20452
> formulary: tighter path rejection detection.

- Library/Homebrew/bottle_specification.rb
- Library/Homebrew/cleanup.rb
- Library/Homebrew/dependable.rb
- Library/Homebrew/dependency_collector.rb
- Library/Homebrew/downloadable.rb
- Library/Homebrew/extend/os/linux/formula.rb
- Library/Homebrew/resource.rb
- Library/Homebrew/software_spec.rb
`typed: strict` a few more places and fix other files necessarily to make that happen.
Should also resolve:
```
/opt/homebrew/Library/Homebrew/software_spec.rb:85: warning: The class SoftwareSpec reached 8 shape variations, instance variables accesses will be slower and memory usage increased.
It is recommended to define instance variables in a consistent order, for instance by eagerly defining them all in the #initialize method.
```
> Add more Sorbet types

- Library/Homebrew/download_strategy.rb
While fetch operations themselves do not need this, they might write to a credential helper that could.
> download_strategy: fix UID handling with credential helpers on fetch

- Library/Homebrew/extend/os/linux/diagnostic.rb
This avoids printing it every time a `brew install` is run.
Closes https://github.com/orgs/Homebrew/discussions/6350
> os/linux/diagnostic: make check_for_symlinked_home doctor-only.

- Library/Homebrew/diagnostic.rb
-----
- diagnostic: fix cask env var output
With `each`, we don't actually output the processed values. We should therefore be using `filter_map` instead.
- diagnostic: improve tilde expansion logic
This is a bit pedantic, but the tilde expansion only occurs if the tilde is at the beginning of the string (if we only take the current user into account) [^1].
[^1]: https://pubs.opengroup.org/onlinepubs/9799919799/utilities/V3_chap02.html#tag_19_06_01
- diagnostic: don't expand tildes in cask env vars
We double quote them so they don't get expanded. Also, use `sh_quote` to quote the variable values properly.
> diagnostic: miscellaneous fixes

- Library/Homebrew/formula.rb
- docs/Formula-Cookbook.md
- docs/Shell-Completion.md
Adds the `opt_` variants to the list of path variables available to formulae, with some explanation. Also, marks `prefix` and `pwsh_completion` methods as public.
> Formula-Cookbook: document stable path variables

- Library/Homebrew/dev-cmd/tests.rb
If HOMEBREW_NO_INSTALL_FROM_API was set, we hadn't fetched JSON API files so will need to fetch them for a valid test environment.
Fixes https://github.com/Homebrew/brew/issues/20519
> dev-cmd/tests: fetch JSON API files if needed.

- Library/Homebrew/cli/parser.rb
- Library/Homebrew/test/cli/parser_spec.rb
-----
Since switch values are boolean, we should be returning the environment variable's presence instead of its string value.
Fixes #20531.
> cli/parser: convert switch env values to boolean

- .vscode/settings.json
Not sure if other folks are having this issue, but the auto format on save feature in VSCode with the Ruby LSP extension stopped working for me. Changing to use `rubocop_internal` instead of `rubocop` seemed to fix it
> Use `rubocop_internal` formatter for Ruby LSP

- Library/Homebrew/formula_cellar_checks.rb
-----
This will allow us to avoid having to list multiple formula versions in
the universal binary allowlist (e.g. for `llvm`).
Needed for Homebrew/homebrew-core#234488.
> formula_cellar_checks: check unversioned name in `universal_binary_allowlist`

- .github/workflows/tests.yml
It's nicer and faster to not split these up and avoids needing to repeatedly rerun this workflow in order to get all the results.
> workflows/tests: run `brew style` on all taps at once.

- Library/Homebrew/manpages.rb
Otherwise `brew generate-man-completions` fails.
> manpages: fix type.

- Library/Homebrew/formulary.rb
- Library/Homebrew/missing_formula.rb
This PR adds strict typing to `Formulary`. Sorbet doesn’t allow using the `def method` syntax inside anonymous classes, so use `define_method` instead for those cases.
To help with typing, I’ve moved the factory cache to it’s own method, and it is initialized when that method is called and also when calling `enable_factory_cache!`.
While we’re here, I also modified the API Formula `install` method to raise a `NotImplementedError` instead of just a standard runtime error as we did in https://github.com/Homebrew/brew/pull/20489
> Enable strict typing in `Formulary`

- Library/Homebrew/cli/named_args.rb
- Library/Homebrew/cli/parser.rb
- Library/Homebrew/dependency.rb
- Library/Homebrew/test/utils/autoremove_spec.rb
This PR modifies the named argument handling to load formulae using the internal API when names are passed via command line arguments.
The general idea is that anytime someone runs `brew COMMAND FORMULA`, they probably need the fully loaded formula (except for cases where they actually want a keg or resolved formula). So, when converting named args to formulae, download the JSON data then and use it to return fully-loaded formulae. This means that, for most commands, there should be no need to worry about whether the `Formula` objects are from stubs or not.
For now, there is no bottle information in the manifest files, so use the individual formula JSON files from `formulae.brew.sh`. Eventually that will be changed to try the bottle first, and use `formulae.brew.sh` as a fallback.
This is …
> Load formulae from stubs in argument parser

- Library/Homebrew/PATH.rb
- Library/Homebrew/bundle.rb
- Library/Homebrew/dev-cmd/typecheck.rb
- Library/Homebrew/extend/ENV/shared.rbi
- Library/Homebrew/extend/kernel.rb
- Library/Homebrew/extend/os/mac/diagnostic.rb
- Library/Homebrew/git_repository.rb
- Library/Homebrew/utils.rb
- Library/Homebrew/utils/service.rb
-----
The various `Kernel.system` wrappers are best typed in lockstep, so this PR spans a couple of files (logically, we should also group them together, and move more core extensions out of Kernel, but I'll save that for a future PR).
> Enable strict typing in Kernel extensions + utils.rb

- Library/Homebrew/build.rb
- Library/Homebrew/extend/pathname/write_mkpath_extension.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/test/extend/pathname/write_mkpath_extension_spec.rb
Follow-up to https://github.com/Homebrew/brew/pull/20553
This PR moves the `PathnameWriteMkpath` refinement out of `Formulary` into its own `WriteMkpathExtension` under `extend/pathname`. To avoid monkey patching globally, this is only prepended onto `Pathname` within the `build.rb` script, since the monkey patch will be scoped to the isolated build process.
There was a mention in https://github.com/Homebrew/brew/pull/11307,  of deprecating this extension, which we could also do now. I think this would mean adding a `safe_write` method to `Pathname` everywhere in Homebrew, and then deprecating any uses of `WriteMkpathExtension#write` that require special handling in favor of `safe_write`. This could probably be done easily with a new RuboCop check as well.
> Extract `Pathname` refinement from `Formulary`

- Library/Homebrew/cask/reinstall.rb
- Library/Homebrew/cli/named_args.rb
- Library/Homebrew/cmd/install.rb
- Library/Homebrew/download_queue.rb
We use the following pattern a lot:
```ruby
download_queue = Homebrew::DownloadQueue.new if Homebrew::EnvConfig.download_concurrency > 1
```
So, this creats a helper to easily create one if concurrency is enabled
```ruby
download_queue = Homebrew::DownloadQueue.new_if_concurrency_enabled
```
Definitely open to a shorter name is anyone has ideas
> Create `DownloadQueue` helper to check concurrency and initialize

- Library/Homebrew/dev-cmd/bump.rb
-----
`brew bump` understands that some formulae/casks are skipped by livecheck but it doesn't use this information to avoid doing unnecessary or inappropriate work. This modifies related logic to not fetch PR information or try to open a version bump PR if livecheck is skipped. livecheck is our only source of version information these days, so we can't try to version bump a package if we don't have upstream version information.
This has been leading to an "Invalid usage: `--version` must not be empty" error (e.g., https://github.com/Homebrew/homebrew-cask/issues/224962) and this _should_ fix the issue under these particular circumstances. There's still plenty of room for improvement in how all of this is handled in bump but this is just a quick bug fix.
> bump: respect livecheck skipped status

- Library/Homebrew/test/extend/pathname/write_mkpath_extension_spec.rb
See https://github.com/Homebrew/brew/pull/20566#discussion_r2299781652
To avoid prepending `WriteMkpathExtension` to `Pathname` for all test runs, let’s create a dummy `PathnameCopy < Pathname` class to test the functionality of the extension without globally applying.
> Fix `WriteMkpathExtension` tests

- Library/Homebrew/formula_auditor.rb
- Library/Homebrew/resource_auditor.rb
- Library/Homebrew/test/formula_auditor_spec.rb
-----
- We don't mind if third-party taps have non-default HEAD branches - they have their reasons.
- But we want core formulae to be as consistent as possible, hence why there's the allowlist.
- https://github.com/Homebrew/brew/pull/20402#discussion_r2292366323
> Encourage using a default branch for HEAD core formulae

- Library/Homebrew/unversioned_cask_checker.rb
-----
This change runs the `rename` dsl for the `extract_plist` livecheck strategy.
Currently casks using the `extract_plist` strategy will fail because the app path cannot be found.
Unblocks: https://github.com/Homebrew/homebrew-cask/pull/225391
> unversioned_cask_checker: process rename operations

- Library/Homebrew/cask/artifact/abstract_uninstall.rb
-----
`Cask::Artifact::AbstractUninstall.uninstall_script` contains a `which` call that uses a `Pathname` argument instead of a `String` and this leads to a type error (`Parameter 'cmd': Expected type String, got type Pathname with value...`, as seen in https://github.com/Homebrew/homebrew-cask/pull/225744). This resolves the error by calling `#to_s` on the `executable_path` argument.
> AbstractUninstall: coerce which argument to String

- Library/Homebrew/formulary.rb
I noticed that we store `{deprecation,disable}_replacement_{formula,cask}` information in a formula’s JSON data, but when never use that information when loading a formula from the API.
> Load replacement formula/cask from formula API

- Library/Homebrew/api.rb
Fixes #20610
If the forked install process attempts to download new API files, it will try to overwrite the various `{formula,cask}_{names,aliases}.txt` files, but this will fail because the the `WriteMkpathExtension` is applied.
To solve this, let’s simply unlink the old files before writing the new contents.
> Unlink old `*_names.txt` and `*_aliases.txt` files before overwriting

- Library/Homebrew/resource_auditor.rb
-----
This removes the temporary `audit_download_strategy` exception for the `lsr` formula. This was necessary to be able to merge support for tangled.sh Git URLs (https://github.com/Homebrew/brew/pull/20599), as it made the `using: :git` argument in the `lsr` formula redundant and caused the "formula audit" check to fail in brew CI.
I've set this as a draft until the aforementioned `DownloadStrategy` change is available in a brew release.
> Remove temporary audit exception for lsr

- Library/Homebrew/os/linux.rb
-----
On the [beta Bluefin LTS](https://docs.projectbluefin.io/lts), `brew config` reports:
```console
OS: CentOS Stream release 10 (Coughlan)
```
This is due to the `/etc/redhat-release` file being prioritized over `::OS_VERSION` (`PRETTY_NAME` from `/etc/os-release`).
On Bluefin LTS, `PRETTY_NAME` is `Bluefin LTS`.
This commit reverses the order so `brew config` has better detection:
```
OS: Bluefin LTS
```
I tested on RHEL 10 and the OS line only changed in that the word "release" was omitted:
```
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 10.0 (Coughlan)
$ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="Red Hat Enterprise Linux 10.0 (Coughlan)"
```
- This is an improvement on my previous PR https://github.com/Homebrew/brew/pull/15788
> config: Remove use of `/etc/redhat-release`

- Library/Homebrew/dev-cmd/livecheck.rb
-----
I ran `brew livecheck` today to check the packages in my watchlist and realized that it wasn't checking one package because I had added a trailing comment after the name (and `package # Comment` isn't a valid package name). I thought we had added support for trailing comments when we originally added comment support years back but I must have been mistaken.
This adds support for trailing comments in livecheck watchlist files as part of refactoring the watchlist line parsing logic to only use one pass (instead of multiple `#map` and `#reject` calls). This maintains the existing behavior, where blank lines and lines starting with `#` are skipped, but does so in a more flexible manner. For example, the existing logic wouldn't skip a comment line that has one or more spaces before the …
> livecheck: support trailing comments in watchlist

- Library/Homebrew/utils/pid_path.rb
It seems a certain enterprise security tool flags this file for the `dlopen`. It's unclear why as it is a trusted, signed dylib shipped with macOS.
The symbol we need however also exists in `libSystem`, which we have successfully loaded elsewhere: https://github.com/Homebrew/brew/blob/43433244682cdc54bd7fe770577f102c9234bc3f/Library/Homebrew/linkage_checker.rb#L201
As such, it's a reasonable guess that `libSystem` might work here.
Ultimately, this PR is entirely a speculative fix as I have no way to verify if this fixes the issue or not.
> utils/pid_path: use libSystem

- Library/Homebrew/api.rb
- Library/Homebrew/api/cask.rb
- Library/Homebrew/api/formula.rb
- Library/Homebrew/api/internal.rb
- Library/Homebrew/api/json_download.rb
For consistency, we don’t want to download new API files mid-run, even if new data is available on the server. This PR modifies the API fetcher logic to only attempt to fetch the data once per execution.
To clarify why `mtime` and `--time-cond` are insufficient here: these checks simply ensure that enough time has passed in between fetches, and that a new fetch will actually yield a new file. However, when building from source, it's possible that an installation will take long enough that new data is available and enough time has passed that `Homebrew::API` considers the file to be stale. This means that future calls to API data will try to download the data once again, which is what this PR is attempting to prevent.
> Download new API files once per Homebrew instance

- Library/Homebrew/cmd/bundle.rb
- Library/Homebrew/cmd/info.rb
- Library/Homebrew/cmd/options.rb
- Library/Homebrew/cmd/search.rb
- Library/Homebrew/cmd/services.rb
- Library/Homebrew/cmd/uses.rb
- Library/Homebrew/dev-cmd/audit.rb
- Library/Homebrew/dev-cmd/bump-cask-pr.rb
- Library/Homebrew/dev-cmd/bump.rb
- Library/Homebrew/dev-cmd/livecheck.rb
- Library/Homebrew/test/cli/parser_spec.rb
- completions/zsh/_brew
-----
- remove a depends_on to fix `HOMEBREW_NO_INSTALL_FROM_API= HOMEBREW_EVAL_ALL= brew search --desc searchterm`
- improve usage error for `brew options`
- update references to `--all` and drop non-essential `=` in conflicts lists
> command options: various `--eval-all` fixes

- Library/Homebrew/formula_auditor.rb
Third party taps should be allowed to have head-only formulae, so let's only check for this in homebrew/core.
> Allow head-only formulae in third party taps

- Library/Homebrew/bundle/commands/cleanup.rb
- Library/Homebrew/bundle/formula_dumper.rb
- Library/Homebrew/commands.rb
- Library/Homebrew/description_cache_store.rb
- Library/Homebrew/style.rb
-----
The `&method` style undergoes type erasure, is disallowed at `typed: strict`, and (IMO) isn't idiomatic ruby: https://sorbet.run/#%23%20typed%3A%20strict%0A%0Anumbers%20%3D%20%5B1%2C2%2C3%5D%0A%0AT.reveal_type%28numbers.map%20%7B%20String%28_1%29%20%7D%29%0AT.reveal_type%28numbers.map%28%26method%28%3AString%29%29%29
> Use type-safe blocks

- Library/Homebrew/cask/artifact/abstract_uninstall.rb
- Library/Homebrew/cask/audit.rb
- Library/Homebrew/cask/caskroom.rb
- Library/Homebrew/extend/os/linux/system_config.rb
- Library/Homebrew/extend/pathname.rb
- Library/Homebrew/livecheck/strategy/git.rb
- Library/Homebrew/readall.rb
- Library/Homebrew/services/system/systemctl.rb
- Library/Homebrew/system_command.rb
- Library/Homebrew/system_config.rb
- Library/Homebrew/test/utils/user_spec.rb
- Library/Homebrew/unpack_strategy/dmg.rb
- Library/Homebrew/unpack_strategy/tar.rb
- Library/Homebrew/utils/curl.rb
- Library/Homebrew/utils/git.rb
- Library/Homebrew/utils/github/api.rb
- Library/Homebrew/utils/svn.rb
- Library/Homebrew/utils/tar.rb
- Library/Homebrew/utils/user.rb
-----
This one has some definite tradeoffs:
- No more implicit multiple assignment of the command result, need to call `to_a`
- I removed the kwargs splat to type them individually. I think this is also great for code completion, but there's a lot of duplicated type declarations as a resul.
> Enable strict typing in SystemCommand

- Library/Homebrew/system_command.rb
-----
Follow up to https://github.com/Homebrew/brew/pull/20613 to add a missing `must_succeed` parameter.
Discovered in https://github.com/Homebrew/homebrew-cask/actions/runs/17564639258/job/49888905675?pr=227110#step:16:18
Resolves https://github.com/Homebrew/homebrew-cask/issues/227138
> system_command: add missing `must_succeed`

- .github/workflows/tests.yml
This path has been wrong ever since we split this from a Ubuntu runner and moved it to macOS.
This fix could make the job as much as 7-9 minutes faster (but only after this has merged and it's run on `main`).
> workflows/tests: fix tap-syntax caching

- Library/Homebrew/cmd/update-report.rb
-----
When on a non-default branch (for e.g., testing), `Formula[formula]` can return an error. In that case let's silently ignore it.
> cmd/update-report: fix formula description display

- Library/Homebrew/cmd/update-report.rb
- Library/Homebrew/cmd/upgrade.rb
- Library/Homebrew/extend/os/mac/diagnostic.rb
- Library/Homebrew/extend/os/mac/pkgconf.rb
- Library/Homebrew/extend/os/mac/reinstall.rb
- Library/Homebrew/extend/os/reinstall.rb
- Library/Homebrew/reinstall.rb
- Library/Homebrew/test/cmd/shared_examples/reinstall_pkgconf_if_needed_spec.rb
- Library/Homebrew/test/cmd/update-report_spec.rb
- Library/Homebrew/test/cmd/upgrade_spec.rb
- Library/Homebrew/test/os/mac/reinstall_spec.rb
- [ x ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ x ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ x ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ x ] Have you successfully run `brew style` with your changes locally?
- [ x ] Have you successfully run `brew typecheck` with your changes locally?
- [ x ] Have you successfully run `brew tests` with your changes locally?
-----  
This PR follows up on #20418 by …
> feat: reinstall pkgconf automatically on macOS version mismatch

- Library/Homebrew/extend/pathname.rb
-----
There is usage of passing a `String` in e.g., https://github.com/Homebrew/homebrew-core/blob/138a870412d2c96c3c0c998ba1e1cdfcb01db3b5/Formula/r/reaver.rb#L33.
> extend/pathname: fix signature of `install_metafiles`

- Library/Homebrew/dev-cmd/contributions.rb
- Library/Homebrew/sorbet/rbi/dsl/homebrew/dev_cmd/contributions.rbi
-----
Resolves a misleading `brew contributions` error:
```
$ brew contributions
Warning: Repository Homebrew/homebrew-core not yet tapped! Tapping it now...
Error: Tapping homebrew/core is no longer typically necessary.
Add --force if you are sure you need it for contributing to Homebrew.
exit 1
```
However, the command did not support `--force`, which this PR introduces.
> Add --force switch for contributions command

- Library/Homebrew/extend/os/mac/reinstall.rb
- Library/Homebrew/test/cmd/shared_examples/reinstall_pkgconf_if_needed_spec.rb
- Library/Homebrew/test/os/mac/reinstall_spec.rb
-----
Before:
$ rm `brew --cache`/downloads/*pkgconf*
$ gsed -Ei 's/macOS [[:digit:]]+/macOS 14/g' `brew --prefix pkgconf`/INSTALL_RECEIPT.json
$ brew up
==> Updating Homebrew...
Already up-to-date.
Error: wrong number of arguments (given 2, expected 0)
/opt/homebrew/Library/Homebrew/reinstall.rb:67:in 'BasicObject#initialize'
/opt/homebrew/Library/Homebrew/reinstall.rb:67:in 'Class#new'
/opt/homebrew/Library/Homebrew/reinstall.rb:67:in 'Homebrew::Reinstall.build_install_context'
/opt/homebrew/Library/Homebrew/extend/os/mac/reinstall.rb:27:in 'OS::Mac::Reinstall::ClassMethods#reinstall_pkgconf_if_needed!'
/opt/homebrew/Library/Homebrew/cmd/update-report.rb:258:in …
> extend/os/mac/reinstall: fix pkgconf reinstall

- Library/Homebrew/cask/audit.rb
-----
This change remove the `--strict` guard for the audit that checks Cask application bundles for the minimum macOS version.
CC: @krehel
> cask/audit: always run min_os audit

- Library/Homebrew/test/github_runner_matrix_spec.rb
-----
We should bump `HOMEBREW_MACOS_OLDEST_SUPPORTED` first and make sure
that bump goes out into a release tag before dropping CI in
Homebrew/core. Otherwise, we end up with users getting errors about
missing bottles. See, for example, Homebrew/homebrew-core#240857.
We've made it very hard for users on OS versions newer than
`HOMEBREW_MACOS_OLDEST_SUPPORTED` to *not* use bottles (because only
bottles are supported), but that design assumes we have been building
bottles for them. We should therefore make sure that users we stop
building bottles for are always on a version older than
`HOMEBREW_MACOS_OLDEST_SUPPORTED`.
> test/github_runner_matrix: prevent dropping supported macOS versions from CI

- Library/Homebrew/extend/ENV/super.rb
-----
GCC -Os doesn't seem to have same performance/size balance as Clang. There are often serious performance loss compared to -O1 and it is less tested compared to Clang -Os (i.e. Apple usage of latter at least guarantees it is reasonable for desktop machines but GCC usage seems more oriented to microcontrollers).
GCC -O2 is what we use on Linux and has a more reasonable performance/size balance.
Since we don't support ENV.O2, it makes sense to use it as the default for GCC.
> extend/ENV/super: default to -O2 with GCC

- Library/Homebrew/cmd/shellenv.sh
-----
Fixes:
```console
$ eval `brew shellenv`
PATH_HELPER_ROOT=/opt/homebrew: Command not found.
```
While we're here, also apply the same fix for fallback shells to cover potential future issues.
Fixes #20724.
> cmd/shellenv: fix for tcsh

- Library/Homebrew/caveats.rb
-----
Inspired by Homebrew/homebrew-core#235513.
It doesn't quite fix that issue, because `libomp` does not ship CMake
config files, but this would probably still be useful for keg-only
formulae that do ship CMake config files.
While we're here, let's replace the `pkg-config` references with the
now-canonical name `pkgconf`.
> caveats: suggest setting `CMAKE_PREFIX_PATH` when appropriate

- Library/Homebrew/cask/dsl/base.rb
- Library/Homebrew/cask/dsl/caveats.rb
Make `cask/dsl/base` `typed: strict` and add some signatures to `cask/dsl/caveats`.
> cask/dsl: add some Sorbet types.

- Library/Homebrew/download_queue.rb
- Library/Homebrew/formula_installer.rb
- Library/Homebrew/utils/attestation.rb
-----
When both attestation check and concurrent download are enabled, attestation verification incorrectly starts right after the download is enqueued, rather than after the download completes. This sometimes leads to attestation verification failure. (It does not happen every time because attestation verification is slow compared to downloads, and it has a retry mechanism.)
Fix the issue by allowing `DownloadQueue#enqueue` to accept an optional callback that runs after the download future resolves, and then moving attestation verification into the callback. With that, attestation verification now correctly waits for download completion, whether using concurrent downloads or not.
By fixing the timing, we also have one extra substantial benefit: the existing enqueue-then-verify logic …
> Fix attestation check timing with concurrent downloads

- Library/Homebrew/cmd/update.sh
- Library/Homebrew/cmd/which-formula.rb
- Library/Homebrew/command-not-found/handler.fish
- Library/Homebrew/command-not-found/handler.sh
Now that `which-formula` lives in this repo, we should fetch `executables.txt` on `brew update` invocations. When a user runs `brew which-formula` for the first time, a setting is saved indicating that `executables.txt` should be downloaded on future `brew update` calls. If a user does not run `brew which-formula`, the file will not be fetched.
To make this easier, I've extracted the API file fetch logic to a helper function in `update.sh`. You can view that change in isolation in [`1f042a3` (#20739)](https://github.com/Homebrew/brew/pull/20739/commits/1f042a3a69b3d02e337dc14837e77f6ba064c7f4).
I've also added `--skip-update` to the shell handlers that call `which-formula` so no new files will be downloaded if a user types the wrong command in their shell.
> Update `executables.txt` in `brew update` when needed

- Library/Homebrew/cmd/command-not-found-init.rb
- Library/Homebrew/command-not-found/handler.fish
> command-not-found-init: match fish init behavior to *sh

- Library/Homebrew/cask_dependent.rb
- Library/Homebrew/cleanup.rb
- Library/Homebrew/cmd/install.rb
- Library/Homebrew/cmd/leaves.rb
- Library/Homebrew/cmd/outdated.rb
- Library/Homebrew/cmd/reinstall.rb
- Library/Homebrew/dependency.rb
- Library/Homebrew/diagnostic.rb
- Library/Homebrew/formula.rb
- Library/Homebrew/formulary.rb
- Library/Homebrew/installed_dependents.rb
- Library/Homebrew/test/cmd/leaves_spec.rb
- Library/Homebrew/test/formula_spec.rb
- Library/Homebrew/test/migrator_spec.rb
- Library/Homebrew/test/support/helper/formula.rb
- Library/Homebrew/test/utils/autoremove_spec.rb
- Library/Homebrew/utils/autoremove.rb
There are issues with bottling in `homebrew/core`. See https://github.com/Homebrew/homebrew-core/actions/runs/17918737406/job/50948240605?pr=245265 for example.
Reverts Homebrew/brew#20603
> Revert "Use installed keg formula files when referencing installed formulae/dependencies"

- Library/Homebrew/dev-cmd/determine-test-runners.rb
- Library/Homebrew/github_runner_matrix.rb
Handle missing `GITHUB_*` variables.
> `brew determine-test-runners`: allow running locally.

- Library/Homebrew/cask/cask_loader.rb
-----
When a cask is loaded via the API, if only a `disable!` stanza was provided with a date in the future, the "reason" was not being displayed correctly. This is because DeprecateDisable sees it as a "deprecation reason" until the disable date is reached. This PR should correctly re-assemble the cask to be read from the API.
Discovered in: https://github.com/orgs/Homebrew/discussions/6433#discussioncomment-14522001
> cask/cask_loader: fix future disable reason

- Library/Homebrew/dev-cmd/bottle.rb
-----
GNU tar fails to create a bottle if date before 1970 is passed to `--mtime=` parameter, f.e.:
```
/opt/homebrew/opt/gnu-tar/bin/gtar --numeric-owner --mtime=1677-09-20
19:12:43 --sort=name --owner=0 --group=0 --numeric-owner --format=pax
--pax-option=globexthdr.name=/GlobalHead.%n,exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime
--file
/Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/neo4j--2025.09.0.arm64_sequoia.bottle.tar
neo4j/2025.09.0
Error: integer -9223372037 too small to convert to 'unsigned int'
```
Related:
https://github.com/Homebrew/homebrew-core/pull/246155
https://github.com/Homebrew/homebrew-core/actions/runs/18090483016/job/51470097819?pr=246155
> dev-cmd/bottle: change mtime if the date is before 1970

- Library/Homebrew/test_bot/formulae.rb
- Library/Homebrew/test_bot/formulae_detect.rb
- Skip downloading existing portable Ruby bottles.
- Improve error handling when building portable Ruby alongside other formulae.
More attempts to get https://github.com/Homebrew/homebrew-core/pull/245971 🟢 and add some better error handling
> test_bot: more fixes for building portable Ruby.

- Library/Homebrew/test_bot/formulae_detect.rb
Ensure the custom logic only kicks in when there are added/modified formulae and not when there are none.
> test_bot/formulae_detect: fix portable ruby handling.

- Library/Homebrew/requirements/xcode_requirement.rb
-----
`@version = nil` is used to handle `depends_on :xcode` or `depends_on xcode: :build`.
Converting this to empty string (`""`) causes 
```
Error: Version must not be empty
/opt/homebrew/Library/Homebrew/version.rb:499:in 'Version#initialize'
/opt/homebrew/Library/Homebrew/requirements/xcode_requirement.rb:40:in 'Class#new'
/opt/homebrew/Library/Homebrew/requirements/xcode_requirement.rb:40:in 'XcodeRequirement#message'
```
> xcode_requirement: fix unversioned requirement

- Library/Homebrew/cmd/bundle.rb
This avoids printing the disabled message just because it's installed.
Fixes https://github.com/Homebrew/brew/issues/20758
> cmd/bundle: disable whalebrew dumping by default.

- Library/Homebrew/rubocops/cask/no_overrides.rb
- Library/Homebrew/test/rubocops/cask/no_overrides_spec.rb
-----
It is possible for Casks to have a different minimum os dependency on different architectures, as seen in https://github.com/Homebrew/homebrew-cask/blob/817d9b808ee39bdae5dab49b761f5570b5d54586/Casks/c/copyq.rb
In this instance the `arm` version of the cask requires `monterey`, and the `intel` version requires `ventura`, but we do not allow for this case with our current rubocop setup.
This PR allows for this specific instance to pass `brew style`.
> rubocop/cask: allow depends_on in `on_(arm|intel)` blocks

- Library/Homebrew/brew.sh
- Library/Homebrew/utils/wrapper.sh
`setup-ruby-path` calls `brew vendor-install` but that would just call `setup-ruby-path` again before installing.
Fixes #20770
> utils/wrapper: fix infinite loop installing Portable Ruby

- Library/Homebrew/cask/upgrade.rb
- Library/Homebrew/cmd/install.rb
- Library/Homebrew/upgrade.rb
- Don't download unnecessary casks with download queue
- Don't show "no outdated dependents to upgrade" message
- Skip some messages/work if there's no outdated casks
Fixes https://github.com/Homebrew/brew/issues/20745
> Improve Cask upgrades

- Library/Homebrew/dev-cmd/bump-cask-pr.rb
- Library/Homebrew/dev-cmd/bump-formula-pr.rb
- Library/Homebrew/utils/github.rb
-----
`--commit` argument has become useless since commit 97acfb9, because `--write-only` will no longer trigger `create_bump_pr` which contains `git commit` logic.
> bump-*-pr: fix issue that --commit argument has no effect

- Library/Homebrew/brew.rb
-----
Previously brew would return a 0 exit code and no output if someone
typos a command.
Before:
```console
❯ brew instlal
❯ echo $?
0
```
After:
```console
❯ brew instlal
Example usage:
brew search TEXT|/REGEX/
brew info [FORMULA|CASK...]
brew install FORMULA|CASK...
brew update
brew upgrade [FORMULA|CASK...]
brew uninstall FORMULA|CASK...
brew list [FORMULA|CASK...]
Troubleshooting:
brew config
brew doctor
brew install --verbose --debug FORMULA|CASK
Contributing:
brew create URL [--no-fetch]
brew edit [FORMULA|CASK...]
Further help:
brew commands
brew help [COMMAND]
man brew
https://docs.brew.sh
Error: Invalid usage: Unknown command: brew instlal
❯ echo $?
1
```
> Fail on unknown brew subcommand

- Library/Homebrew/keg.rb
-----
For similar reasons as Python along with share directory where user scripts are saved
- `share/pypy3.10/` https://github.com/Homebrew/homebrew-core/blob/main/Formula/p/pypy3.10.rb#L209
- `share/pypy/` https://github.com/Homebrew/homebrew-core/blob/main/Formula/p/pypy.rb#L207
Regex needs to match both `pypy` and `pypy3.X` so didn't include version part (it would need to be optional in which case it may as well be excluded).
If we want a more specific regex then maybe,
```ruby
%r{^pypy(3\.\d+)?(/|$)}
```
Would depend on how likely a non-Pypy formula uses a path like `lib/pypyfoo`.
> keg: retain pypy directories

- Library/Homebrew/formula.rb
-----
Performance can be very slow without the cache to prune the duplicate parts of the dependency tree so use the cache by default when running `Formula#recursive_dependencies`. All other usage of `Dependency#expand` in Homebrew/brew already uses the cache.
---
For blocks, I decided to create a temporary cache entry and purge it to avoid unnecessary memory consumption. Used the same naming scheme as FormulaInstaller. Not sure if any chance of collision (if so could add a `SecureRandom.uuid` or something else)
https://github.com/Homebrew/brew/blob/7c21e4163e7a3408f30f734023e2a4dc296b64fd/Library/Homebrew/formula_installer.rb#L762
This should help with another slow down seen in:
- https://github.com/Homebrew/homebrew-core/pull/246844
---
Even on macOS with smaller dependency tree, there …
> formula: default to cache for `Dependency#expand` usage
