Homebrew/brew

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
Library/Homebrew/README.md
Library/Homebrew/cmd/create.rb
Library/Homebrew/cmd/help.rb
Library/Homebrew/cmd/tap-readme.rb
Library/Homebrew/formula.rb
Library/Homebrew/manpages/brew.1.md
Library/Homebrew/os/mac/xcode.rb
Library/Homebrew/test/test_cmd_info.rb
README.md
share/doc/homebrew/Brew-Test-Bot-For-Core-Contributors.md
share/doc/homebrew/Brew-Test-Bot.md
share/doc/homebrew/Common-Issues.md
share/doc/homebrew/External-Commands.md
share/doc/homebrew/Formula-Cookbook.md
share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md
share/doc/homebrew/Installation.md
share/doc/homebrew/New-Maintainer-Checklist.md
share/doc/homebrew/Querying-Brew.md
share/doc/homebrew/Tips-N'-Tricks.md
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

Update documentation after repository split.

---

Library/Homebrew/blacklist.rb

This follows the info for LaTeX, which also mentions a cask.

Mention the haskell-platform cask

---

Library/Homebrew/utils/analytics.rb

Fix usage of undefined variable

---

etc/bash_completion.d/brew

Is using `find` here kosher? This is, like, unbelievably faster than what we had before, which was I think quadratic in the number of formulas when considering taps, which was pretty hilarious after we split out homebrew-core.
Fixes #20.

Speed up tab completion

---

Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/xcode.rb
share/doc/homebrew/Xcode.md

xcode: expect 7.3 on 10.11

---

Library/Homebrew/tap.rb

Use both an in-class and a `.git/config` cache for this so we can ensure that the `Tap#private?` check is fast. Also, make sure this cache value is set both when initially installing and updating a tap.
Needed for https://github.com/Homebrew/brew/pull/57
CC @xu-cheng

Cache `Tap#private?` checks.

---

.travis.yml

We have Jenkins to test the other versions.
CC @xu-cheng and @UniqMartin who talked about this.

.travis.yml: only build on latest OS X.

---

Library/Homebrew/cmd/update.sh

This is coming out of preview shortly so use the new API content-type.

update: use official GitHub SHA API.

---

Library/Homebrew/tap.rb
Library/Homebrew/test/test_tap.rb

* make `read_or_set_private_config` private
* add doc
* add test
cc @mikemcquaid

tap: various improvements

---

Library/Homebrew/manpages/brew.1.md
Library/Homebrew/manpages/footer.1.md
Library/Homebrew/utils/analytics.sh
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

Document disabling of opt-in Homebrew analytics.

---

Library/Homebrew/cmd/style.rb

Mostly bug-fixes and enhancements to the auto-correct feature.
I was a tad concerned about the new `Style/IfUnlessModifierOfIfUnless` feature but having tested a bunch of formulae and core files I haven't seen any warnings related to it so I'll leave it enabled by default until we hit anything problematic.

style: use rubocop 0.39

---

Library/Homebrew/utils/analytics.sh
share/doc/homebrew/Analytics.md

Going to merge this immediately as the final piece before https://github.com/Homebrew/brew/pull/78. Please feel free to leave comments anyway and I'll address them in the next week before we :ship:.

analytics: add more documentation, Linuxbrew ID.

---

Library/Homebrew/utils/analytics.sh

Someone else has been sending weird data to ours and it has bad initial test data so let's roll it before we ship it to everyone on Saturday.

analytics: roll tracking ID.

---

.github/CONTRIBUTING.md

The current one returns a 404.

fix link to troubleshooting checklist

---

Library/Homebrew/caveats.rb

It simplifies the number of commands and it's now an officially supported command again. CC @xu-cheng

caveats: recommend brew services for plists.

---

share/doc/homebrew/Formula-Cookbook.md

Make multiple replacements if using the block form.
Avoid confusion such as in https://github.com/Homebrew/homebrew-core/pull/464.
CC @DomT4

Formula-Cookbook: better `inreplace` example.

---

Library/Homebrew/cmd/update.sh
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

We want to always avoid merge commits being committed to Homebrew so this feels like a better fit.

update: rebase (rather than merge) by default.

---

Library/Homebrew/download_strategy.rb

https://github.com/Homebrew/brew/issues/81
Fix according to https://github.com/Homebrew/brew/pull/156#issuecomment-216014977

download_strategy: use svn info --xml

---

Library/Homebrew/cmd/update.sh

To be synced with the help flag list in brew.rb

update: more help flag

---

Library/Homebrew/extend/fileutils.rb

-----
Fixed a variable name that have not been followed at https://github.com/Homebrew/brew/commit/acc9a7ca8554bc2413dee2d6d0f407b3a59c628c

Fix a variable name in error message

---

Library/Homebrew/formula_installer.rb
Library/Homebrew/utils/analytics.rb
Library/brew.rb

Global namespaces are good to avoid when possible.

analytics: move to a class.

---

share/doc/homebrew/Maintainers-Avoiding-Burnout.md

CC @Homebrew/maintainers for thoughts.

Add "Maintainers: Avoiding Burnout" document.

---

Library/Homebrew/cmd/pull.rb

Fixes 1.8.7 compatibility bug in #132.

pull: fix polling code for Ruby 1.8.7 Net::HTTP

---

Library/Homebrew/test/test_utils.rb
Library/Homebrew/utils.rb

Moving this PR over from the old brew repo.
https://github.com/Homebrew/legacy-homebrew/pull/48871

Tty: Avoid truncating if not sensible

---

Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/xcode.rb
share/doc/homebrew/Xcode.md

-----
cc @DomT4 because I'm not sure whether our CI is ready yet. (I suspect not quite.)

xcode: expect 7.3.1 on 10.11

---

Library/Homebrew/cmd/tests.rb

Makes it easier to quickly do tests of the generic/cross-platform backend.

tests: add generic flag.

---

Library/Homebrew/cmd/fetch.rb
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

----
I think this option is generally useful and I just re-learned that it exists.

fetch: document --retry option

---

Library/Homebrew/cmd/pull.rb

-----
Adds retry logic to the "download bottle file with curl" step in the bottle verification method. 
Works around issue with GET and HEAD apparently acting differently, and bottle downloads failing even after successful polling completion. This is something @UniqMartin has been seeing.
I went with this implementation because it sticks with doing the main polling (which is expected to happen several times in the normal caes) using the lightweight HEAD and reused server connection, which is polite to Bintray's server, and produces concise "Waiting on Bintray....." progress output.
Uses exponential backoff instead of constant backoff for this step because it's using `curl` so it gets a new connection every time.
I also tried switching the polling to use a GET with byte ranges instead of …

cmd/pull: add retry to curl bottle download

---

Library/Homebrew/cmd/update.sh
Library/brew.sh

See git commit message for details.

various shell improvement

---

Library/Homebrew/compat/formula.rb
Library/Homebrew/formula.rb

formula: deprecate startup_plist.

---

Library/Homebrew/cmd/audit.rb

-----
GitHub’s code load and patch-diff URLs are the result of redirects and make it harder to modify the URL to reach the original repository.

audit: check more GitHub URLs.

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md

-----
Indicate that feature requests should go there rather than here. CC @DomT4

.github/*: point to Homebrew Evolution repository.

---

Library/Homebrew/cmd/audit.rb

-----
There are unnecessarily verbose, have been documented to be avoided and
it’s good to nudge people towards the other style.

audit: check for block inreplace with single sub.

---

Library/Homebrew/dev-cmd/mirror.rb

-----
Used for uploading imagemagick 6.9.4-3 in https://github.com/Homebrew/homebrew-core/pull/1308. CC @DomT4 
Going to merge quickly as it's actually working.

mirror: add command to mirror to Bintray.

---

Library/Homebrew/utils/lock.sh

-----
This avoids weird issues with custom Rubies.
CC @xu-cheng 
Closes #253.

utils/lock.sh: default to system Ruby if available

---

Library/Homebrew/cmd/search.rb
README.md
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

-----
* Include --desc in brew search help text.
* Update brew search --desc text in README.
* Remove mention of alias in brew search help text to avoid any
confusion.

Clarify brew search usage.

---

Library/Homebrew/cmd/bottle.rb
Library/Homebrew/cmd/pull.rb
Library/Homebrew/cmd/test-bot.rb
Library/Homebrew/formulary.rb

This means that we do not need to read formulae or evaluate Ruby at upload time.
CC @xu-cheng who I talked about this with. This will need some testing on our CI before it's definitely ready to merge.

Use JSON files for bottle upload data.

---

Library/Homebrew/cmd/test-bot.rb

-----
We're not really getting any more PRs here and this code makes this file harder to follow and refactor.

test-bot: remove support for legacy Homebrew repo.

---

Library/Homebrew/cmd/test-bot.rb

-----
This job takes almost a minute and it's not useful for all core taps to run this.
CC @xu-cheng

test-bot: only test --no-compat for Homebrew/brew.

---

Library/Homebrew/cmd/pull.rb

-----
There's no more pull requests left to pull on this repository. CC @xu-cheng

pull: remove legacy-homebrew support.

---

Library/Homebrew/cmd/test-bot.rb

-----
This adds >1m to every build on every node and it can't actually be affected/fixed by formula PRs.
CC @DomT4

test-bot: don't `brew tests` for formula PRs.

---

Library/Homebrew/cmd/tests.rb
Library/Homebrew/test/.simplecov

-----
This will almost certainly fail every time so let's disable this error.
CC @eirinikos as this came up during one of our conversations.

tests: no --only minimum coverage requirement.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Check the syntax for Homebrew/brew and don't bother for taps. As requested by @UniqMartin in https://github.com/Homebrew/brew/pull/286/files/f9cb2b36363fb55acccdb9834fff7199182b8164#r64994952.

test-bot: tweak readall behaviour.

---

Library/Homebrew/download_strategy.rb

-----
Some Git versions create absolute `gitdir:` pointers in a submodule's `.git` file, which can be problematic once the resource is staged and causes various Git operations for those submodules to fail. Work around this issue by fixing the submodule `.git` files after submodule update.
See Homebrew/homebrew-core#1520 for details and an affected formula.
Strictly speaking this is a Git bug and not a Homebrew bug, but since we have to deal with affected Git versions and clones created by them for the foreseeable future, this workaround seems warranted.
(This is a [known regression](http://thread.gmane.org/gmane.comp.version-control.git/290491) that was introduced in the Git 2.7 series and [has been fixed in Git 2.8.3](https://github.com/git/git/commit/f5e16b2a7ba0ed12e4674f111386643e16692 …

download_strategy: fix git submodule references

---

Library/Homebrew/os/mac/xquartz.rb

-----
**Maintainers:** Just getting this out to see the CI failure—do not merge yet. Will update XQuartz on all our machines and re-run the build before merging this.

xquartz: expect 2.7.9 on 10.6-10.11

---

share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

Minor documentation improvement.

Do not install bottle for test

---

share/doc/homebrew/External-Commands.md

- Documentation only hence not needed - I understand.
- Documentation only hence not needed - I understand.
-----

Update default HOMEBREW_CACHE following #292

---

Library/Homebrew/os/mac/version.rb

- macOS Sierra is our sierriest macOS ever
- You can't be Sierraious
- Now with Si(e)r(r)i(a) in the menu bar

os/mac/version: add macOS Sierra.

---

Library/Homebrew/test/.simplecov

-----
There is no good reason to configure the options specific to integration tests in a completely different location from all other options.
cc @eirinikos because you might be interested in PRs that touch test-related code.

tests: simplify SimpleCov configuration

---

Library/Homebrew/test/test_integration_cmds.rb

-----
PR #333 was merged a bit too soon. Sorry I failed to notice the issues there. Problems fixed:
- Broken and leaking test if run as part of `brew tests --coverage` due to the `cmd` call being nested in the `Pathname#cd` block (see 2nd transcript below).
- Output during `git clone` operation because of a missing `shutup do` (see 1st transcript below).
- Still incomplete coverage for `cmd/log.rb` because `brew log` is invoked on the formula in the origin instead of the shallow clone.
- Minor stylistic fixes:
- Superfluous parentheses around `core_tap.path.dirname`.
- Overly long lines.
cc @eirinikos
----
```
$ /usr/bin/time brew tests --no-compat
Run options: --seed 9768
................................................................................ …
```

tests: fix problems in 'log with formula' test

---

Library/Homebrew/keg.rb

-----
This should make more bottles relocatable e.g. ansible.
Ref https://github.com/Homebrew/homebrew-core/pull/2125#issuecomment-226987124

bottle: delete .pyo files as with .pyc

---

Library/Homebrew/cmd/update-report.rb

Additional logic for migration of deduplicated formulas ([Issue related](https://github.com/caskroom/homebrew-cask/issues/15603))
-----

cask migration logic

---

Library/Homebrew/blacklist.rb

-----
Two changes:
- updates URL for installing `pip`
- updates blacklist message for `macruby` since the project has been abandoned

Blacklist copy and url updates

---

Library/Homebrew/cmd/install.rb

-----
This is a developer-only option I created for testing purposes. It should not be used by end-users.

install: undocument --force-bottle.

---

Library/Homebrew/cleaner.rb
Library/Homebrew/extend/os/cleaner.rb
Library/Homebrew/extend/os/mac/cleaner.rb

cleaner: port to generic OS.

---

Library/Homebrew/cmd/install.rb
Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/os/mac/diagnostic.rb

diagnostic: more porting to generic OS.

---

Library/Homebrew/extend/ENV.rb

ENV: only check Superenv if necessary.

---

Library/Homebrew/extend/os/linux/hardware/cpu.rb
Library/Homebrew/extend/os/mac/hardware/cpu.rb
Library/Homebrew/hardware.rb

hardware: move generic logic from linux.

---

Library/Homebrew/dev-cmd/linkage.rb

See discussion in https://github.com/Homebrew/brew/commit/080ddd8804be14f4b18f9558b58270456ff313c2
Cf. https://github.com/Homebrew/brew/pull/470

linkage: don't conflate broken and undeclared

---

Library/Homebrew/cmd/install.rb

cmd/install: port to generic OS.

---

Library/Homebrew/emoji.rb
Library/Homebrew/extend/os/emoji.rb
Library/Homebrew/extend/os/mac/emoji.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/utils.rb

emoji: extract logic into generic OS classes.

---

Library/Homebrew/extend/os/formula_cellar_checks.rb
Library/Homebrew/extend/os/mac/formula_cellar_checks.rb
Library/Homebrew/formula_cellar_checks.rb

formula_cellar_checks: port to generic OS.

---

Library/Homebrew/cmd/bottle.rb
Library/Homebrew/extend/os/keg_relocate.rb
Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/keg_relocate.rb

keg_relocate: port to generic OS.

---

Library/Homebrew/cmd/update.sh

A temporary measure before we decide whether vendor git or not.
Related PR https://github.com/Homebrew/install/pull/47

update: git init for core tap as well

---

Library/Homebrew/blacklist.rb
Library/Homebrew/official_taps.rb
share/doc/homebrew/Acceptable-Formulae.md
share/doc/homebrew/Interesting-Taps-&-Branches.md

-----
We're moving more stuff to Homebrew Cask which is better maintained and run. CC @DomT4 and generally @Homebrew/maintainers for 💭

Deprecate homebrew/binary.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Not sure why this was removed by @xu-cheng in https://github.com/Homebrew/brew/commit/46c25d983359fedef509d18468d684abe46cff5b but re-adding as it would have caught https://github.com/Homebrew/brew/issues/519.

test-bot: re-add update-test.

---

Library/Homebrew/software_spec.rb

Fix HeadVersions

---

Library/Homebrew/test/test_integration_cmds.rb

-----
This change adds test coverage for `brew analytics`. 🎈

tests: add cmd/analytics integration test

---

README.md

-----
Also, explicitly welcome new/beginner contributors and give them a suggested starting point to contribute to Homebrew. Based on the boiler plate I tend to send people to for GSoC, Outreachy or generally people who say "I want to try and contribute to open-source".

README: add Contributing section.

---

.travis.yml
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/dev-cmd/test-bot.rb
Library/Homebrew/development_tools.rb
Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/ENV/shared.rb
Library/Homebrew/extend/os/linux/hardware/cpu.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/hardware.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/os.rb
Library/Homebrew/tab.rb
Library/Homebrew/test/test_formula.rb
Library/Homebrew/test/test_language_module_requirement.rb
Library/Homebrew/test/test_utils.rb
Library/Homebrew/test/testing_env.rb
Library/Homebrew/utils/bottles.rb

-----
This should verify that we're not breaking our generic tests on Linux.

travis.yml: run tests --generic on Linux.

---

Library/Homebrew/compat/.rubocop.yml
Library/Homebrew/compat/dependency_collector.rb
Library/Homebrew/compat/fails_with_llvm.rb
Library/Homebrew/compat/formula.rb
Library/Homebrew/compat/formula_specialties.rb
Library/Homebrew/compat/hardware.rb
Library/Homebrew/compat/keg.rb
Library/Homebrew/compat/language/haskell.rb
Library/Homebrew/compat/macos.rb
Library/Homebrew/compat/md5.rb
Library/Homebrew/compat/pathname.rb
Library/Homebrew/compat/sha1.rb
Library/Homebrew/compat/tap.rb
Library/Homebrew/compat/version.rb
Library/Homebrew/compat/xcode.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/test/test_cmd_audit.rb
Library/Homebrew/utils.rb

-----
Cleanup the style and warning text of `compat/` and fix a test that ended up printing compatibility warnings.

Cleanup compat/ style and warnings

---

Library/Homebrew/test/test_utils.rb
Library/Homebrew/utils.rb

-----
This should hopefully avoid Homebrew/brew or Homebrew/homebrew-core having these exceptions reported to us. CC @UniqMartin for thoughts.

utils: tell people to report deprecations to tap.

---

Library/Homebrew/language/python.rb

Allow virtualenvs to find Python bindings provided by deps

---

Library/Homebrew/cmd/audit.rb
Library/Homebrew/cmd/create.rb
Library/Homebrew/dev-cmd/test-bot.rb
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

-----
Rather than nudge people to run `--strict` and then ignore some of the results sometimes (e.g. GitHub repository notability) instead add a dedicated `--new-formula` option that implies this is a one-time advisory check. CC @DomT4 who has mentioned this.

audit: add --new-formula option.

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/tap.rb

-----
Added to `tap` methods needed for handling migration of casks

tap: add cask methods

---

Library/Homebrew/test/test_integration_cmds.rb

-----
This test gives 100% coverage to `brew migrate`. Many thanks to @UniqMartin for explaining how the command works.
It's 50 lines long, though -- sorry. 😬 
It's very likely there's a more efficient way to achieve the same test coverage.

tests: add cmd/migrate integration test

---

Library/Homebrew/cmd/search.rb

-----
e.g. Caskroom/homebrew-cask.
Thanks to @UniqMartin for the fix.
Fixes #655.

search: fix repositories with formulae and casks.

---

Library/Homebrew/formula_installer.rb
Library/Homebrew/utils/analytics.rb
Library/Homebrew/utils/analytics.sh

-----
Try to use `--data-urlencode` to fix e.g. `--c++11` handling (but I'm not sure if this is working quite right). Also, report `--HEAD` and `--devel`.
CC @UniqMartin @tdsmith @DomT4 
Fixes #631.

Analytics fixes

---

Library/Homebrew/cmd/outdated.rb
Library/Homebrew/cmd/upgrade.rb
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

-----
Fixes https://github.com/Homebrew/brew/pull/650#discussion_r73834082
CC @MikeMcQuaid

Update --fetch-HEAD documentation

---

Library/Homebrew/formula_versions.rb

Reverts Homebrew/brew#692
Closes #696.

Revert "formula_versions: also silence stderr."

---

etc/bash_completion.d/brew
share/zsh/site-functions/_brew

Add completions for --fetch-HEAD flag

---

Library/Homebrew/formula_installer.rb
Library/Homebrew/utils.rb

-----
See Homebrew/legacy-homebrew#48449

install_dependencies: Do not truncate dependencies

---

Library/Homebrew/cmd/search.rb

-----
Doesn't appear to affect the speed of `brew search`.
CC @ilovezfs to test if this fixes your issue.
Fixes #415.

search: remove thread-unsafe Hash cache.

---

Library/Homebrew/brew.sh
Library/Homebrew/manpages/brew.1.md.erb
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

-----
Roll this out to everyone (not just developers) and document the environment variables used for configuration.
Will give it a day or two to allow anyone who wants to test this to do so and for the dust to settle after the other auto-update PRs.
Fixes https://github.com/Homebrew/brew/issues/288.

Ship Homebrew auto-update support.

---

Library/Homebrew/dev-cmd/update-test.rb

-----
Loosen this a bit; we don't necessarily expect the end commit is the one we're looking for, just that it has changed from the start commit (i.e. some sort of update has occurred).

update-test: tweak master not updated check.

---

Library/Homebrew/cmd/vendor-install.sh
Library/Homebrew/manpages/brew.1.md.erb
Library/Homebrew/utils/ruby.sh
share/doc/homebrew/Common-Issues.md
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

-----
Not to be merged right not but this is what we'll need when we decide it's ready. CC @xu-cheng for thoughts.
I think I'm 👍 on the code as-is but would like to see slightly better docs on https://github.com/homebrew/homebrew-portable first. Anything else, folks?

Enable vendored Ruby 2.0.

---

Library/Homebrew/cmd/list.rb
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

-----
And arguments can be passed through to it.
Tweak produced out of conversation in https://github.com/Homebrew/brew-evolution/pull/8.
CC @ajlowndes for thoughts.

list: note that `ls` command is used.

---

Library/Homebrew/test/test_cmd_audit.rb

-----
This change adds unit tests for `brew audit`. I'd like to refactor `formula_auditor`, but I figured I'd save that for a later time.
I'm having trouble getting `test_audit_desc` to pass; I suspect it has to do with iterating over a collection of nested hashes, but for the life of me I can't figure out what the problem is.

tests: add cmd/audit unit tests

---

Library/Homebrew/diagnostic.rb

diagnostic: don't barf if HEAD is also a file.

---

Library/Homebrew/manpages/brew.1.md.erb
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

-----
This option does more than just print warnings so let's make a more generic description with a more specific example.
Closes #716.

Tweak HOMEBREW_DEVELOPER documentation.

---

Library/.rubocop.yml
Library/Homebrew/cmd/audit.rb
Library/Homebrew/descriptions.rb
Library/Homebrew/dev-cmd/test-bot.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/extend/fileutils.rb
Library/Homebrew/global.rb
Library/Homebrew/shims/super/cc
Library/Homebrew/test/Gemfile
Library/Homebrew/utils/curl.rb

-----
The day of rejoicing is here. Assume Ruby 2 everywhere.

Assume Ruby 2

---

Library/Homebrew/extend/ENV/shared.rb
Library/Homebrew/extend/os/extend/ENV/shared.rb
Library/Homebrew/extend/os/mac/extend/ENV/shared.rb
Library/Homebrew/extend/os/mac/extend/ENV/std.rb
Library/Homebrew/extend/os/mac/extend/ENV/super.rb
Library/Homebrew/shims/super/cc

-----
Implements the request in https://github.com/Homebrew/homebrew-core/issues/3727.
Currently untested as I wanted to get some review of the approach but then will check it out on a Sierra VM (or maybe just upgrade to Sierra).
CC @achivetta

Set -no_weak_imports linker flag for Xcode 8

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Another PR to aid https://github.com/Homebrew/brew/pull/725 being merged by making getting `brew cask-tests` easier.

test-bot: tap cask before cask-tests.

---

Library/Homebrew/cmd/audit.rb
Library/Homebrew/formula_versions.rb
share/doc/homebrew/Formula-Cookbook.md

-----
Follow-up from https://github.com/Homebrew/brew/pull/719 to check these with an `audit` rule and add Formula Cookbook documentation. CC @vladshablinsky and @DomT4 for review and thoughts.

Add Formula Cookbook entry and audit check for version_scheme

---

Library/Homebrew/os/mac/xcode.rb

xcode: update expected clang for macOS 10.12

---

share/doc/homebrew/Bottles.md

Bottles: bottle revision is now called rebuild.

---

Library/Homebrew/diagnostic.rb

-----
These are intentionally duplicated for now until the Cask migration is complete. CC @AnastasiaSulyagina

diagnostic: ignore duplicated `brew-cask` commands

---

.gitignore
Library/Homebrew/cask/Rakefile
Library/Homebrew/cmd/man.rb
share/man/man1/brew-cask.1

-----
Also, check in this manpage, adjust the Rakefile and remove the old one.
Fixes #731.

Make "brew man" also generate Cask's manpage.

---

share/doc/homebrew/Tips-N'-Tricks.md

Add atom language plugin to docs

---

Library/Homebrew/extend/os/mac/extend/ENV/super.rb

no_weak_imports: call ENV.append, not .add

---

Library/Homebrew/cask/lib/hbc/cli/cleanup.rb
Library/Homebrew/cask/spec/cask/cli/cleanup_spec.rb

--
Allows passing cask tokens to `brew cask cleanup`.
--
@Homebrew/cask 
--
Closes https://github.com/caskroom/homebrew-cask/issues/23398.

Allow per-cask `cleanup`.

---

Library/Homebrew/brew.rb
Library/Homebrew/config.rb
Library/Homebrew/test/lib/config.rb

-----
Print a better exception message and handle this in more cases rather than producing confusing errors when it’s unset.
@eirinikos hit this recently and @UniqMartin suggested it.

Improve HOMEBREW_BREW_FILE unset failure case.

---

Library/Homebrew/diagnostic.rb

-----
Highlight that the main reason for preferring /usr/local is because of bottles. There's been some confusion around this e.g. https://github.com/Homebrew/homebrew-core/issues/3968

diagnostic: tweak /usr/local messaging.

---

.github/ISSUE_TEMPLATE.md
README.md

- [ Y ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) document?
- [ Y ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ Y ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ n/a ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ Y ] Have you successfully run `brew tests` with your changes locally?
-----
For this bug: https://github.com/Homebrew/brew/issues/814 to improve the safety of the fix being applied. 
Fixes #814.

Replaced ; with && under Update Bug in README.md.

---

Library/Homebrew/cmd/audit.rb

-----
Working on replacing myself with CI so I can ride off into the sunset/be more useful around `brew` rather than `core`. Here's some changes.
You probably hate the `test` one, let me know. The change itself has been discussed between @MikeMcQuaid & I for a while, but I'm not promising the implementation will be to everyone's admiration.

Audit/Testing: various tweaks

---

Library/Homebrew/build_options.rb

docs: add missing </pre>

---

Library/Homebrew/cask/.simplecov
Library/Homebrew/cask/Rakefile
Library/Homebrew/cask/spec/spec_helper.rb
Library/Homebrew/cask/test/test_helper.rb
Library/Homebrew/dev-cmd/test-bot.rb
Library/Homebrew/test/.simplecov

Not actually sure if this is even possible with the current setup, so I might need some help with this.

Also report Cask coverage.

---

Library/Homebrew/cmd/bottle.rb

-----
It should refuse to change existing ones but it should allow them to be the same and silently ignore.
Follow up from https://github.com/Homebrew/brew/pull/856.

bottle: allow --keep-old to ignore same sha256s.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
If there's formulae changes or the specified argument is a formula then don't waste time running e.g. `brew tests`.

test-bot: don't run brew tests etc. when formulae.

---

Library/Homebrew/dev-cmd/test-bot.rb

test-bot: add missing @tap check.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
The test bot currently only focuses on doing cleanup on the current tap and the HOMEBREW_REPOSITORY. This should be extended to cover all repositories as e.g. a syntax error in homebrew/core can break the CI for all the other taps.
CC @javian who has seen this a few times.

test-bot: cleanup all repositories.

---

Library/Homebrew/cmd/update-report.rb

-----
CC @samdmarshall 
Fixes #858.

update-report: add newline if preinstall updated.

---

Library/Homebrew/cmd/bottle.rb

-----
I no longer think this is the best approach and will investigate another.

bottle: revert --keep-old changes.

---

Library/Homebrew/formula.rb
Library/Homebrew/utils/shell.rb

-----
cc @gregory-nisbet - this is an alternate approach to #876

Fix shell profile

---

share/doc/homebrew/Acceptable-Formulae.md
share/doc/homebrew/Formula-Cookbook.md
share/doc/homebrew/Installation.md
share/doc/homebrew/Interesting-Taps-&-Forks.md

-----
This document lists Tigerbrew and Linuxbrew as interesting forks, not branches (they used to be "Interesting Branches (aka forks)" but that changed in b745546), so "Interesting Taps & Branches" is a more fitting title.
The term "branches" is also presumably confusing to folks with a shallow understanding of GitHub and/or git who may not realize how GitHub forks and git branches are related.
---
By the way, I wonder if it's really a good idea to have an ampersand (`&`) in the title and filename. It used to be part of a wiki page title which is fine, but maybe we could sanitize it a bit when putting it on every user's filesystem?

doc/Interesting-Taps-&-Branches: rename to Interesting-Taps-&-Forks

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Otherwise weird things happen and formulae can't be found.

test-bot: never cleanup homebrew/core.

---

Library/Homebrew/cask/lib/hbc/cli/doctor.rb
Library/Homebrew/cask/lib/hbc/cli/search.rb
Library/Homebrew/cask/lib/hbc/scopes.rb
Library/Homebrew/tap.rb

Add `cask_files` method to `Tap` class.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
There's edge-cases which is breaking tap CI.

test-bot: git clean less in cleanup_*.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Always run `git clean -ffdx` on HOMEBREW_REPOSITORY. Also, ensure that if we can't find a formula that's logged.

test-bot: tweak cleaning behaviour again.

---

share/doc/homebrew/Analytics.md

-----
Fixed minor typo -- missing preposition.

minor typo

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/utils.rb

-----
These are more files in the HOMEBREW_REPOSITORY that we want to link to the HOMEBREW_PREFIX.
CC @chdiza as after this the only manual symlink you should need to create is `bin/brew`; everything else (including the `Cellar` creation) will be done for you so installation could be:
```bash
git clone https://github.com/Homebrew/brew /usr/local/Homebrew
mkdir /usr/local/bin
ln -sf /usr/local/Homebrew/bin/brew /usr/local/bin/brew
brew update
```

update-report: also link docs, completions.

---

Library/Homebrew/cmd/install.rb
Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/os/mac/diagnostic.rb

-----
Not only have several maintainers suggested this is a good idea, including myself repeatedly, but at least a handful of users have said they wouldn't hate the idea so let's follow up better late than never.
Obvious test is obvious:

xcode: die unless Xcode/CLT up-to-date on prerelease macOS

---

Library/Homebrew/brew.sh
Library/Homebrew/cmd/update.sh

-----
See #877 for motivation behind this.
Fixes #877.

Warn when changing branch on update

---

Library/Homebrew/cmd/bottle.rb
Library/Homebrew/cmd/man.rb
Library/Homebrew/cmd/postinstall.rb
Library/Homebrew/cmd/pull.rb
Library/Homebrew/cmd/readall.rb
Library/Homebrew/cmd/tap-readme.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/dev-cmd/aspell-dictionaries.rb
Library/Homebrew/dev-cmd/boneyard-formula-pr.rb
Library/Homebrew/dev-cmd/linkage.rb
Library/Homebrew/dev-cmd/mirror.rb
Library/Homebrew/dev-cmd/test-bot.rb
Library/Homebrew/dev-cmd/update-test.rb
Library/Homebrew/test/test_integration_cmds.rb
share/doc/homebrew/brew.1.html
share/man/man1/brew-cask.1
share/man/man1/brew.1

-----
Also, flag those that we never want to be in a manpage.

dev-cmd: add `--help` to all developer commands.

---

.github/ISSUE_TEMPLATE.md
README.md

Same as https://github.com/Homebrew/homebrew-core/pull/4580.

README and ISSUE_TEMPLATE: quote $(brew --repo)

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/test/test_diagnostic.rb

-----
Remove duplicate checks added in #896.

diagnostic: remove duplicate checks.

---

Library/Homebrew/dev-cmd/bottle.rb

-----
If fields have changed: tell the user what they were before and are afterwards. CC @zmwangx who hit this.

bottle: improve --keep-old failure output.

---

Library/Homebrew/dev-cmd/tests.rb

-----
Unit tests should be run consistently no matter who is running them and we can stub `ARGV.homebrew_developer?` if we need to change them.

tests: always set HOMEBREW_DEVELOPER=1.

---

Library/Homebrew/dev-cmd/bottle.rb

-----
- Make the code more similar between `bottle` and `bottle --merge`.
- Also output the mismatched values when using `--merge`.

bottle: further improve --keep-old mismatching.

---

Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/os/mac/pkgconfig/10.12/sqlite3.pc
share/doc/homebrew/Xcode.md

-----
* Tweak the messaging of the diagnostic check, including pointing out the current active developer directory.
* Update the `sqlite` pkg-config file.
* Document 10.12's Xcode since it isn't going to change from 8.0 at this point.

Sierra: update diagnostic message, pkg-config, Xcode doc

---

Library/Homebrew/dev-cmd/bottle.rb

-----
Consistent naming is good.

bottle: use key/value rather than field.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Look in the current directory rather than only allowing upload from Jenkins.

test-bot: --ci-upload can upload from current dir.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Be more selective with the `git clean` and remove the broken attempt to autotap if missing (as it'd be slow anyway).

test-bot: try again to fix homebrew/core untap.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Also, unify the cleanup code and be more careful and consistent with untapping.

test-bot: don't try to `git clean` any taps.

---

Library/Homebrew/language/haskell.rb
Library/Homebrew/language/node.rb
Library/Homebrew/language/python.rb
Library/Homebrew/language/python_virtualenv_constants.rb

Fix Library/Homebrew/language RuboCop warnings

---

Library/Homebrew/dev-cmd/bottle.rb

-----
Avoids issues when using `--keep-old`

bottle: set bottle block tap.

---

Library/Homebrew/cmd/commands.rb
Library/Homebrew/cmd/desc.rb
Library/Homebrew/cmd/doctor.rb
Library/Homebrew/cmd/fetch.rb
Library/Homebrew/cmd/help.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/list.rb
Library/Homebrew/cmd/log.rb
Library/Homebrew/cmd/missing.rb
Library/Homebrew/cmd/prune.rb
Library/Homebrew/cmd/search.rb
Library/Homebrew/cmd/tap-info.rb
Library/Homebrew/cmd/uninstall.rb
Library/Homebrew/cmd/unlinkapps.rb
Library/Homebrew/cmd/unpack.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/cmd/uses.rb

-----
Starting to fix all of these that can be done trivially.

Fix Library/Homebrew/cmd RuboCop warnings

---

Library/Homebrew/requirements/emacs_requirement.rb
Library/Homebrew/requirements/java_requirement.rb
Library/Homebrew/requirements/perl_requirement.rb
Library/Homebrew/requirements/ruby_requirement.rb
Library/Homebrew/requirements/x11_requirement.rb

Fix Library/Homebrew/requirements RuboCop warnings

---

Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/architecture_list.rb
Library/Homebrew/os/mac/cctools_mach.rb
Library/Homebrew/os/mac/linkage_checker.rb
Library/Homebrew/os/mac/sdk.rb
Library/Homebrew/os/mac/version.rb
Library/Homebrew/os/mac/xcode.rb
Library/Homebrew/os/mac/xquartz.rb

Fix Library/Homebrew/os* RuboCop warnings

---

Library/Homebrew/test/test_dependency_collector.rb
Library/Homebrew/test/test_formula.rb
Library/Homebrew/test/test_formula_installer.rb
Library/Homebrew/test/test_integration_cmds.rb
Library/Homebrew/test/test_os_mac_language.rb
Library/Homebrew/test/test_resource.rb
Library/Homebrew/test/test_shell.rb
Library/Homebrew/test/test_tab.rb

Fix Library/Homebrew/test RuboCop warnings

---

Library/Homebrew/utils.rb
Library/Homebrew/utils/curl.rb
Library/Homebrew/utils/github.rb
Library/Homebrew/utils/hash.rb
Library/Homebrew/utils/inreplace.rb
Library/Homebrew/utils/shell.rb

Fix Library/Homebrew/utils RuboCop warnings

---

Library/Homebrew/dev-cmd/aspell-dictionaries.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/dev-cmd/create.rb
Library/Homebrew/dev-cmd/edit.rb
Library/Homebrew/dev-cmd/man.rb
Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/dev-cmd/test-bot.rb
Library/Homebrew/test/test_cmd_audit.rb

Fix Library/Homebrew/dev-cmd RuboCop warnings

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Used in trying to use a `Jenkinsfile`.

test-bot: handle more Jenkins configurations.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Typo from https://github.com/Homebrew/brew/pull/929.

test-bot: fix regex placement.

---

Library/Homebrew/dev-cmd/bottle.rb

-----
Accidentally committed in https://github.com/Homebrew/brew/commit/9b5c45a7df6a9a170389d6045bf06803fe4bc78b. CC @zmwangx

bottle: remove debug statements.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Another typo from https://github.com/Homebrew/brew/pull/927. Note to self: make Homebrew/brew do `test-bot` on an actual C-compiling formula before doing refactoring of it again.

test-bot: fix multiline regex.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Need to handle when the `BOT_PARAMS` are `nil`. CC @ilovezfs https://github.com/Homebrew/brew/pull/941#issuecomment-246323128

test-bot: fix bottling non-testing jobs.

---

Library/Homebrew/extend/ARGV.rb
Library/Homebrew/extend/ENV/shared.rb
Library/Homebrew/extend/ENV/std.rb
Library/Homebrew/extend/ENV/super.rb
Library/Homebrew/extend/fileutils.rb
Library/Homebrew/extend/os/mac/development_tools.rb
Library/Homebrew/extend/pathname.rb

Fix Library/Homebrew/extend RuboCop warnings

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Check the repository directly rather than `@test_default_formula`. CC @zmwangx

test-bot: don't run Homebrew tests for taps PRs.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Move the test default formula handling to after all the other formulae additions are so it'll only be added if no formulae are detected already in a PR. CC @ilovezfs @zmwangx

test-bot: fix test default formula handling.

---

Library/Homebrew/os/mac/pkgconfig/10.12/zlib.pc

-----
It has actually been updated 😱.

pkg-config: update zlib for macOS Sierra

---

Library/Homebrew/cmd/commands.rb

-----
Per discussion in #900.
Closes #900.

cmd/commands: always show developer commands

---

share/doc/homebrew/Bottles.md
share/doc/homebrew/C++-Standard-Libraries.md
share/doc/homebrew/Common-Issues-for-Core-Contributors.md
share/doc/homebrew/Custom-GCC-and-cross-compilers.md
share/doc/homebrew/External-Commands.md
share/doc/homebrew/Formula-Cookbook.md
share/doc/homebrew/Maintainer-Guidelines.md
share/doc/homebrew/brew-tap.md

-----
Some of this stuff has been annoying me for a while.

Documentation Updates.

---

Library/Homebrew/utils.rb

-----
This can ask for you to remove directories (e.g. `/usr/local/share/homebrew`) so don’t call this files to avoid confusion.

utils: link_src_dst_dirs: paths not files.

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/keg.rb

-----
This is used in diagnostic (and will be used in other places later) rather than hard-coding other directories later.

keg: add ALL_TOP_LEVEL_DIRECTORIES constant.

---

Library/Homebrew/cmd/list.rb
Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/ARGV.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_lock.rb
Library/Homebrew/formula_pin.rb
Library/Homebrew/global.rb
Library/Homebrew/keg.rb
Library/Homebrew/migrator.rb
Library/Homebrew/test/test_formula.rb
Library/Homebrew/test/test_formula_installer.rb
Library/Homebrew/test/test_formula_lock.rb
Library/Homebrew/test/test_formula_pin.rb
Library/Homebrew/test/test_integration_cmds.rb
Library/Homebrew/test/test_migrator.rb

-----
These definitions are scattered throughout the codebase which makes it hard to refactor them later (my goal is to move them outside of `HOMEBREW_LIBRARY`). Unify their definitions for clearer code and easier movement later.

Use constants for LinkedKegs/PinnedKegs/Locks.

---

.travis.yml
Library/Homebrew/cask/Gemfile
Library/Homebrew/cask/Gemfile.lock
Library/Homebrew/cask/README.md
Library/Homebrew/cask/Rakefile
Library/Homebrew/dev-cmd/test-bot.rb
Library/Homebrew/test/Gemfile
Library/Homebrew/test/Gemfile.lock

-----
OS X Travis CI is particularly error-prone, slow and unnecessary for us when we're already running (fast) OS X builds on Jenkins so use it just for Linux testing.

Send coverage from Jenkins, don't run OS X Travis.

---

Library/Homebrew/dev-cmd/test-bot.rb
Library/Homebrew/dev-cmd/update-test.rb

-----
Ensure it's always created.
Also, re-order `update-test` in `test-bot` (and `readall`) so they are run before the test suites.

update-test: handle missing master branch.

---

Library/Homebrew/test/.codecov.yml

-----
These are annoying and the status check is sufficient.

.codecov.yml: disable GitHub comments.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
We may have two Sierra nodes available which could speed up this relatively slow operation.

test-bot: generate coverage reports on Sierra.

---

Library/Homebrew/os/mac.rb

-----
We have a GM, a bunch of bottles and CI setup.

os/mac: officially support Sierra.

---

Library/Homebrew/brew.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/config.rb
Library/Homebrew/utils.rb

-----
Move the `LinkedKegs` migration into `utils.rb` so it can also be called from `brew.rb` on startup.

Move LinkedKegs migration.

---

Library/Homebrew/cmd/update.sh

-----
Rather than repeating origin multiple times.
Extracted from https://github.com/Homebrew/brew/pull/998 as this can be merged (and is an improvement) now.

update.sh: turn origin/branch into a variable.

---

Library/Homebrew/cmd/update-report.rb

-----
Otherwise if they are created and empty they may be removed again before we try to create the `/usr/local/bin/brew` symlink.
Saw while migrating one of our bots.

update-report: create top-level directories later.

---

Library/Homebrew/dev-cmd/test-bot.rb

-----
Need to do this manually now that we can't rely on `git clean -xdf` to do it for us.

test-bot: uninstall all formula on cleanup.

---

Library/Homebrew/cmd/update-report.rb

-----
This shouldn't be possible to occur after #1013 but it makes sense to add it anyway.

update-report: handle directory not existing.

---

Library/Homebrew/cmd/update-report.rb

-----
Just on the off chance it doesn't exist (i.e. no-one has installed anything yet or you're a `test-bot` that's run `git clean -xdf` recently)

update-report: also create Cellar on migration.

---

Library/Homebrew/cmd/update-report.rb

-----
Before stashing also try to cancel any current merge, rebase and reset. This will prevent any data loss but also make the stash more likely to succeed.
CC @justinclift

update-report: cleanup git harder in migration.

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/keg_relocate.rb

-----
Now that the default from the installer, our CI and soon all users is `/usr/local/Homebrew` it's a lot easier to check if there's references to it (as we cannot look for `/usr/local` as it's a too commonly hardcoded path).
CC @ilovezfs who I talked about this with. This will be needed before we rebuild pkg-config: https://github.com/Homebrew/brew/pull/963#issuecomment-247676630

Relocate HOMEBREW_REPOSITORY when necessary.

---

Library/Homebrew/cmd/update-report.rb

-----
This will hang around otherwise due to e.g. running `bundle install` in here once.
CC @DomT4

update-report: remove cask dir after migration.

---

Library/Homebrew/cmd/update-report.rb

-----
Also migrate people without `HOMEBREW_DEVELOPER` set to the new location.
Will migrate CI before merging this.

update-report: migrate everyone to new repository.

---

Library/Homebrew/formula.rb
Library/Homebrew/tab.rb
Library/Homebrew/test/fixtures/receipt.json
Library/Homebrew/test/test_formula.rb
Library/Homebrew/test/test_tab.rb
Library/Homebrew/test/testing_env.rb

Save runtime dependencies in INSTALL_RECEIPT.json

---

Library/Homebrew/os/mac.rb
share/doc/homebrew/Installation.md

-----
Let's hold off 🚢ing this until the actual Sierra stable public release version drops.

os/mac: mark Mavericks as outdated.

---

Library/Homebrew/cmd/update-report.rb

-----
CC @viktorbenei who is likely interested in this.

No auto update migration

---

Library/Homebrew/dev-cmd/man.rb
Library/Homebrew/manpages/brew.1.md.erb
README.md
share/doc/homebrew/brew.1.html
share/man/man1/brew.1

-----
Add lead and new maintainers to README and manpages. Also add some `brew style` changes that mistakenly were omitted from a previous PR.

Readme tweaks

---

Library/Homebrew/dev-cmd/man.rb
Library/Homebrew/manpages/brew-cask.1.md
Library/Homebrew/manpages/brew.1.md.erb
docs/brew.1.html
manpages/brew-cask.1
manpages/brew.1

-----
Removed documentation for the `-l` option for  `brew cask list` and removed the notes about `brew cask uninstall` not working correctly.
Also simplified the `brew man` generation a bit, since the changes in https://github.com/Homebrew/brew/pull/1039 seem overly complex.
--
@Homebrew/cask

Update `brew-cask` man page and simplify `brew man`.

---

Library/Homebrew/cmd/update.sh

-----
Check if we have any tags and, if not, do the equivalent of `brew update --force` to ensure that they are all fetched.
Needed for https://github.com/Homebrew/brew/pull/998
CC @zmwangx who pointed this out.

Update: ensure tags are fetched

---

.github/PULL_REQUEST_TEMPLATE.md

PULL_REQUEST_TEMPLATE.md: Fix CONTRIBUTING.md link

---

docs/README.md

readme update: it's version 1.0 already

---

Library/Homebrew/cask/spec/support/Casks/.rubocop.yml
Library/Homebrew/cask/test/support/Casks/.rubocop.yml

-----
fix two soft links for `.rubocop.yml`

rubocop: fix soft links targets

---

README.md

-----
The previous URL for @vladshablinsky 404ed for me.
Out of curiosity, I checked a similar URL for an organisation I'm a member of, and it also 404ed. 🤔

readme: fix maintainer link

---

Library/Homebrew/sandbox.rb

-----
All the taps added to the sandboxed-by-default list were completely built with default options twice through from source prior to being added to the safe list.

sandbox: tweaks

---

Library/Homebrew/cmd/update.sh

-----
It’ll only get printed for people getting updated to tags now and these
are people who haven’t run a `dev-cmd` so we want to air on the side of
telling them less stuff that will confuse them and assume people who
have manually made another `git` branch will know how to get back to it.
See https://github.com/Homebrew/brew/issues/1062, https://github.com/Homebrew/brew/issues/1072,

update.sh: don't print "checkout branch" message.

---

Library/Homebrew/brew.sh

brew.sh: fix brew --version outside HOMEBREW_REPOSITORY.

---

Library/Homebrew/.simplecov
Library/Homebrew/cask/Gemfile
Library/Homebrew/cask/Gemfile.lock
Library/Homebrew/cask/spec/spec_helper.rb
Library/Homebrew/cask/test/test_helper.rb
Library/Homebrew/test/Gemfile
Library/Homebrew/test/Gemfile.lock

-----
This should make coverage reports more credible.

Fix coverage reporting.

---

Library/Homebrew/cmd/postinstall.rb
Library/Homebrew/sandbox.rb

-----
If we have a HOMEBREW_REPOSITORY and HOMEBREW_PREFIX mismatch (now the default) then we can block access to the whole of HOMEBREW_REPOSITORY rather than just the HOMEBREW_LIBRARY and `.git`.

sandbox: tweak HOMEBREW_REPOSITORY handling.

---

Library/Homebrew/cask/lib/hbc/installer.rb
Library/Homebrew/cask/test/cask/accessibility_test.rb

-----
See https://github.com/caskroom/homebrew-cask/issues/24519 and/or https://github.com/Homebrew/brew/issues/905
Feel free to suggest alternative wording and such.

Prevent Accessibility access for macOS >= 10.12

---

Library/.rubocop_rules.yml
Library/Homebrew/dev-cmd/test-bot.rb

-----
These tests will fail (hopefully) to demonstrate the issue described in https://github.com/Homebrew/brew/pull/1106#issuecomment-249270280 and stop it hitting us in future. CC @reitermarkus just FYI.

test-bot: check homebrew/core style.

---

Library/Homebrew/cmd/update.sh

-----
This avoids creating a new branch that’ll never be deleted for each tag and differentiates between the `master` and `stable` branches.

update.sh: always use stable branch for tags.

---

Library/.rubocop_todo.yml
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/extend/ARGV.rb
Library/Homebrew/extend/ENV/std.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_lock.rb
Library/Homebrew/formulary.rb
Library/Homebrew/migrator.rb
Library/Homebrew/test/test_formula.rb

-----
Rename methods flagged by the Style/AccessorMethodName cop.

RuboCop: Style/AccessorMethodName

---

Library/Homebrew/cmd/update.sh

-----
Otherwise if we've committed to `master` and someone `brew update`s before we cut the tag then they won't be updated to the latest version.

update.sh: use GitHub tags API.

---

Library/Homebrew/cmd/update.sh

-----
Only run for Homebrew developers so assume they don’t want to switch back to an old stable branch.
CC @zmwangx 
Fixes #1141.

update.sh: don't restore branch to stable.

---

docs/Tips-N'-Tricks.md

-----
add pcmpl-homebrew for homebrew emacs plugin in doc

add pcmpl-homebrew for homebrew emacs plugin

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

set sha256 automatically when possible
formula name guessing
handle explicit version DSL
handle gnu mirrors
add --write option
CC @MikeMcQuaid

bump-formula-pr: enhancements

---

Library/Homebrew/test/helper/integration_command_test_case.rb
Library/Homebrew/test/test_audit.rb
Library/Homebrew/test/test_create.rb
Library/Homebrew/test/test_custom_command.rb

-----
CC @reitermarkus for some reason these failed when they hit `master` even although the PR was green? https://travis-ci.org/Homebrew/brew/builds/163074310

Rubocop style fixups

---

Library/Homebrew/cmd/update.sh

-----
Will only happen once but could be confusing anyway.

update.sh: hide GITHUB_HEADERS missing output.

---

docs/Formula-Cookbook.md

- [ x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [ x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [ x] Have you successfully run `brew tests` with your changes locally?
-----

fix Formula path in Formula-Cookbook, support macOS

---

Library/Homebrew/cask/lib/hbc/cli/style.rb

Update `rubocop-cask` to 0.10.0.

---

Library/Homebrew/dev-cmd/man.rb

-----
Set the manpage date to the existing one if we're checking for changes. This avoids the only change being e.g. a new date.

man: set date when --fail-if-changed.

---

Library/Homebrew/cmd/list.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/test/test_formula_installer.rb

-----
Store the formula used to build the keg inside the keg in a
file named NAME/VERSION/.bottle/NAME.rb after removing the
bottle do ... end block.
See https://github.com/Homebrew/brew-evolution/pull/6.
Closes https://github.com/Homebrew/brew/issues/931.

Store the formula used to build the keg in the keg

---

Library/Homebrew/dev-cmd/man.rb
docs/brew.1.html
manpages/brew-cask.1
manpages/brew.1

-----
As requested in #1199 this updates the documentation accordingly for that change. 
CC @alyssais

man: note --fail-if-changed date behaviour change.

---

Library/Homebrew/dev-cmd/update-test.rb
docs/brew.1.html
manpages/brew-cask.1
manpages/brew.1

-----
This option is used to test updating between tags.

update-test: add --to-tag option.

---

Library/Homebrew/brew.sh
Library/Homebrew/utils/analytics.sh

analytics: don't report commands run by Homebrew

---

Library/Homebrew/dev-cmd/bottle.rb

-----
Fixes `undefined method 'Tty.gray'`.
Sorry, this was overlooked in https://github.com/Homebrew/brew/pull/823.
--
Fixes https://github.com/Homebrew/brew/issues/1209.

Fix `Tty.gray`.

---

Library/Homebrew/cmd/install.rb

-----
This is no longer relevant after moving to taps/tags and if ever re-added it should probably target homebrew/core.
Fixes #1194.

install: remove not updated warning.

---

Library/Homebrew/brew.rb
Library/Homebrew/cmd/help.rb

-----
CC @zmwangx 
Fixes https://github.com/Homebrew/homebrew-test-bot/issues/3

help: support `#:` help in external commands.

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/test/test_diagnostic.rb

-----
Update some messaging based on recent user confusion and the `/usr/local/Homebrew` and Ruby 2 migrations.

*/diagnostic: tweak messaging.

---

Library/Homebrew/manpages/brew.1.md.erb
docs/brew.1.html
manpages/brew.1

-----
These are the ones that are auto-installed without tapping and it makes sense to make them more prominent in our documentation as we've offloaded various functionality over the years to each of them.

Add official external commands to manpage.

---

Library/Homebrew/cask/lib/hbc/container/dmg.rb

Add `.com.apple.timemachine.supported` to DMG_METADATA_FILES.

---

Library/Homebrew/cask/lib/hbc/auditor.rb

-----
Previously `brew cask audit` would exit with `0`, even if some of the languages failed.
--
@Homebrew/cask

Fix exit code for multilingual cask audit.

---

Library/Homebrew/blacklist.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/requirement.rb

“Homebrew Cask” -> “Homebrew-Cask”

---

Library/Homebrew/locale.rb
Library/Homebrew/test/test_os_mac_language.rb

-----
Use `Locale.parse` to check if `OS::Mac.languages` returns valid languages.

Make parsing locales more robust.

---

Library/Homebrew/cask/lib/hbc/dsl.rb

Comment out `license` stanza deprecation warning.

---

Library/Homebrew/diagnostic.rb

diagnostic: handle HOMEBREW_TEMP mktmpdir failure.

---

Library/Homebrew/cask/lib/hbc/qualified_token.rb

-----
The homebrew/homebrew wiki no longer exists.

Update URL in qualified_token comment

---

Library/Homebrew/cask/lib/hbc/exceptions.rb

-----
Fixes "no implicit conversion of Array into String".

Fix CaskCommandFailedError.

---

Library/Homebrew/cask/lib/hbc/auditor.rb

-----
This allows for auditing a single language of a cask, so you don't have to re-download every language everytime.

Allow auditing of a single language of a cask.

---

Library/Homebrew/keg_relocate.rb

-----
This was omitted from #1258, incorrectly fixed in #1267, reverted in #1268 and re-applied in this commit. CC @jawshooah and @reitermarkus FYI and review.

keg_relocate: relocate text_executable? files.

---

Library/Homebrew/brew.sh

Fix warning for HOMEBREW_REPOSITORY at /usr/local

---

README.md
docs/FAQ.md
docs/Formula-Cookbook.md

-----
Addressing a few spots where I looked for terminology and did not find what I was looking for. Input based on a recent [podcast with Mike](https://changelog.com/podcast/223). Thanks for the inspiration @MikeMcQuaid - I would love to continue to help with my favorite macOS tool 👌.

Further terminology in docs + link on README

---

docs/New-Maintainer-Checklist.md

-----
Update to the latest status quo.

New-Maintainer-Checklist: update.

---

Library/Homebrew/dev-cmd/audit.rb

-----
It looks like a rebase/merge conflict remmenet. I'm not totally sure if I got it right, but it is definitely not right as is.

Fix wrong ordering on when clauses in audit.rb

---

Library/Homebrew/cask/lib/hbc/cli/style.rb

-----
Update required version of `rubocop-cask` for `brew cask style`.

hbc/cli/style: bump RUBOCOP_CASK_VERSION

---

Library/Homebrew/dev-cmd/audit.rb

-----
This is handled by `brew style` now.

audit: don't complain about trailing whitespace.

---

Library/Homebrew/cask/cmd/brew-cask-tests.rb
Library/Homebrew/cask/spec/spec_helper.rb
Library/Homebrew/cask/test/test_helper.rb

-----
Set environment variables in `cask-tests` rather than in the respective spec/test helpers.
--
@Homebrew/cask

Set `HOMEBREW_NO_EMOJI` and `HOMEBREW_CASK_OPTS` in `cask-tests`.

---

Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/cask/lib/hbc/container/cab.rb
Library/Homebrew/cask/lib/hbc/container/generic_unar.rb
Library/Homebrew/cask/lib/hbc/container/lzma.rb
Library/Homebrew/cask/lib/hbc/container/xz.rb
Library/Homebrew/cask/lib/hbc/utils.rb
Library/Homebrew/cask/test/cask/installer_test.rb
Library/Homebrew/cask/test/test_helper.rb

-----
Look for programs in PATH, not only in Homebrew's `bin`.
--
@Homebrew/cask

Look for container extraction programs in PATH.

---

Library/Homebrew/cask/lib/hbc/container/generic_unar.rb

-----
This was overlooked in https://github.com/Homebrew/brew/pull/1319.

Also use `which` to find `lsar` in PATH.

---

Library/Homebrew/cask/lib/hbc/cli/list.rb

-----
If the Caskroom hasn't been initialized yet, just say (correctly) that we have nothing to list.
Refs https://github.com/Homebrew/homebrew-core/issues/5905#issuecomment-254883697
@Homebrew/cask

hbc/cli/list: don't require Caskroom to be initialized

---

Library/Homebrew/cask/.rspec
Library/Homebrew/cask/cmd/brew-cask-tests.rb
Library/Homebrew/cask/spec/cask/artifact/binary_spec.rb
Library/Homebrew/cask/spec/cask/audit_spec.rb
Library/Homebrew/cask/spec/cask/cask_spec.rb
Library/Homebrew/cask/spec/cask/cli/cleanup_spec.rb
Library/Homebrew/cask/spec/cask/cli/doctor_spec.rb
Library/Homebrew/cask/spec/cask/cli/style_spec.rb
Library/Homebrew/cask/spec/cask/cli_spec.rb
Library/Homebrew/cask/spec/cask/download_strategy_spec.rb
Library/Homebrew/cask/spec/cask/dsl/version_spec.rb
Library/Homebrew/cask/spec/cask/macos_spec.rb
Library/Homebrew/cask/spec/cask/scopes_spec.rb
Library/Homebrew/cask/spec/cask/system_command_result_spec.rb
Library/Homebrew/cask/spec/cask/system_command_spec.rb
Library/Homebrew/cask/spec/cask/underscore_supporting_uri_spec.rb
Library/Homebrew/cask/spec/cask/verify/checksum_spec.rb
Library/Homebrew/cask/spec/cask/verify_spec.rb
Library/Homebrew/cask/spec/formatter_spec.rb
Library/Homebrew/cask/spec/locale_spec.rb
Library/Homebrew/cask/spec/spec_helper.rb

-----
This adds Homebrew's test config to the load path and gets rid of most of the directory overrides.
--
@Homebrew/cask

Refactor `spec_helper`.

---

Library/Homebrew/dev-cmd/release-notes.rb
docs/brew.1.html
manpages/brew.1

-----
Outputs the merged pull requests on Homebrew/brew between two Git refs.
Useful for creating release notes.

Add `brew release-notes` developer command.

---

Library/.rubocop.yml
Library/Homebrew/.rubocop.yml
Library/Homebrew/cmd/missing.rb
Library/Homebrew/cmd/style.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/extend/ENV/super.rb
Library/Homebrew/locale.rb
Library/Homebrew/tap.rb
Library/Homebrew/utils/formatter.rb

-----
Another look at the current Rubocop rules and how they fit with our existing and desired future style. Almost all of these changes were automatic. Split some rules between formulae/brew where brew doesn't have millions of cases that need fixed.

Update Rubocop style.

---

Library/.rubocop.yml
Library/Homebrew/.rubocop.yml

-----
- Don't enforce hash rockets on external commands (CC @ilovezfs)
- Enabled accidentally disabled ParenthesesAsGroupedExpression.

More Rubocop tweaks.

---

Library/Homebrew/cask/spec/spec_helper.rb
Library/Homebrew/cask/test/cask/url_checker_test.rb
Library/Homebrew/cask/test/test_helper.rb

-----
Use `test/lib/config` in cask's `test_helper`.
-- 
@Homebrew/cask

Use `test/lib/config` for tests.

---

Library/Homebrew/cask/test/cask/cli/create_test.rb
Library/Homebrew/cask/test/test_helper.rb

-----
`HOMEBREW_LIBRARY` is pointing to a path in `TEST_TMPDIR`.

Use proper path to `caskroom/cask` tap in `test_helper`.

---

Library/Homebrew/cask/test/cask/installer_test.rb

Refactor Installer test.

---

Library/Homebrew/cask/test/cask/dsl_test.rb

Refactor DSL test.

---

Library/Homebrew/cask/test/cask/cli/audit_test.rb

Refactor Audit test.

---

Library/Homebrew/cask/test/cask/accessibility_test.rb

Refactor accessibility test.

---

Library/Homebrew/cask/lib/hbc/dsl/depends_on.rb

Fix locally failing `depends_on` test.

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/test/test_diagnostic.rb
Library/Homebrew/test/test_exceptions.rb
Library/Homebrew/test/test_patch.rb
Library/Homebrew/test/test_string.rb

Don’t use bare percent literals.

---

Library/Homebrew/cask/lib/hbc/download_strategy.rb

-----
This PR fixes caskroom/homebrew-cask#26087.

Fix cask's restarting incomplete downloads

---

Library/Homebrew/dev-cmd/audit.rb

-----
Stable URLs should not use unstable versions.

audit: check for alpha/beta/rc usage in URLs.

---

Library/Homebrew/brew.sh
Library/Homebrew/utils/analytics.sh

-----
These invocations occur before we can actually automatically install git via
bottle, and as such their output isn't relevant.
ref: #729 
cc: @MikeMcQuaid

Redirect stderr output from git (shim) invocations to /dev/null.

---

Library/Homebrew/os/mac/xcode.rb

XCode 8.1 is stable

---

README.md
docs/brew.1.html
manpages/brew.1

docs: remove zmwangx from the list of maintainers

---

Library/Homebrew/cask/lib/hbc/auditor.rb

-----
Use instance methods to DRY things up, and fix a bug discovered in https://github.com/caskroom/homebrew-cask/pull/26067 where Casks with language blocks would always fail audit.
@Homebrew/cask

hbc/auditor: refactor and fix bug

---

Library/Homebrew/dev-cmd/update-test.rb

-----
Without this updating to a tag will always have the same start commit
and end commit as there's been no updates to `master` since the tag was
created.

update-test: fix --to-tag failure on new tag.

---

Library/Homebrew/dev-cmd/audit.rb

-----
This will prevent `brew upgrade` from working correctly. CC @zmwangx who talked about this.

audit: check the version does not decrease.

---

.gitignore
Library/Homebrew/cask/Gemfile.lock
Library/Homebrew/cask/cmd/brew-cask-tests.rb
Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/test/Gemfile
Library/Homebrew/test/Gemfile.lock

-----
This is to clean up the `test` directory a bit as per https://github.com/Homebrew/brew/pull/1364#issuecomment-255860189.

Move `test/vendor/bundle` to `vendor/bundle`.

---

Library/Homebrew/dev-cmd/audit.rb

Revert "audit: check the version does not decrease."

---

Library/Homebrew/dev-cmd/audit.rb

-----
These have unstable checksums and aren't the tagged, stable releases
we require.

audit: check for master branch tar/zipballs.

---

Library/Homebrew/dev-cmd/audit.rb

-----
This doesn't matter for everything but it does for the binaries that are installed. Have a limited name/alias check when not installed and a better one that iterates bin/sbin if installed.

audit: check test system calls are fully scoped.

---

Library/Homebrew/dev-cmd/audit.rb

---
This will prevent brew upgrade from working correctly (fixed version of https://github.com/Homebrew/brew/pull/1366 which was reverted in https://github.com/Homebrew/brew/pull/1406).
Also don't check new formulae for version decreases (from https://github.com/Homebrew/brew/pull/1404).

audit: check the stable version does not decrease.

---

Library/Homebrew/cmd/gist-logs.rb
Library/Homebrew/utils/github.rb

---
Improve the GitHub API scope and token related messaging by
autopopulating the scopes we need on the new scopes page and, in the
case of a lacking a scope we need, output what scope was required.
Also, DRY up the personal access token code.

Improve GitHub API scopes output.

---

Library/Homebrew/dev-cmd/boneyard-formula-pr.rb

---
Used to provide a user-facing reason why this formula was boneyarded.
CC @ilovezfs who talked about this.

boneyard-formula-pr: add reason argument.

---

Library/Homebrew/build.rb

---
These can be useful for later inspection or upload by `gist-logs` if
there's a failed install and it's unclear from logs alone what options
were used.
CC @zmwangx who was requesting this.

build: write options to file.

---

Library/Homebrew/dev-cmd/audit.rb

-----
Also check `def test`, `shell_output`, `pipe_output` and method calls using parentheses.

audit: check more unscoped test calls.

---

Library/Homebrew/cask/lib/hbc/utils.rb
Library/Homebrew/cmd/unpack.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/formula.rb
Library/Homebrew/migrator.rb
docs/brew.1.html
manpages/brew-cask.1
manpages/brew.1

-----
Fix a few minor typos I found, only in comments / error messages, starting with the "instuctions" error message that I saw the other day :)

Correct a few typos

---

Library/Homebrew/brew.sh

---
Auto update could be very slow in at least two cases:
1. Many taps are tapped (e.g., my primary brew installation on my primary machine);
2. brew is used infrequently (e.g., on many of my test VMs and numerous servers that I only install things on once in a long while).
And when auto update is slow, brew seems broken when you type `brew install foo` and no output appears for half a minute or longer. Many users don't know brew is silently updating itself.
Adding a brief message before `brew update --preinstall` communicates what's happening to the user and should greatly reduce user anxiety.
**Update**. Now the message is only printed when `brew update --preinstall` has been running for 3 seconds. Also, the message is not printed when `HOMEBREW_VERBOSE` is set, because the update …

brew.sh: display message when auto update runs for too long

---

Library/Homebrew/brew.sh

-----
1.1.0 release is imminent so let's bump this because: why not.

brew.sh: bump hardcoded minor version.

---

Library/Homebrew/os/mac/linkage_checker.rb
Library/Homebrew/os/mac/mach.rb
Library/Homebrew/os/mac/pathname.rb

-----
This allows us to filter out weak linkages during audits, preventing
a false error from occurring when the dylib cannot be found.
ref Homebrew/homebrew-core#6645
cc @MikeMcQuaid, @UniqMartin

os/mac: MachO.dynamically_linked_libraries filtering.

---

Library/Homebrew/os/mac/linkage_checker.rb
Library/Homebrew/os/mac/mach.rb
Library/Homebrew/os/mac/pathname.rb

Reverts Homebrew/brew#1460
Closes https://github.com/Homebrew/homebrew-core/issues/6755

Revert "os/mac: MachO.dynamically_linked_libraries filtering."

---

Library/Homebrew/cask/lib/hbc/exceptions.rb
Library/Homebrew/extend/os/mac/diagnostic.rb

---
Didn't add any tests - just a textual change.

`brew doctor` recommends using cask to upgrade XQuartz

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/utils/lock.sh

-----
And, if it isn't, print more helpful debugging messages.
Fixes #1456.

Check the lock directory is writable.

---

completions/zsh/_brew

-----
Fix typo in `--keep-tmp` option.

Typo: delet -> delete

---

Library/Homebrew/keg.rb
Library/Homebrew/test/test_keg.rb

-----
See #1496 for an explanation of the problem.
This PR removes the call to `Keg#to_formula` in `Keg.find_some_installed_dependents`. Rather than grouping kegs by formula, it instead groups them by tap and name, which should have the same result but be more robust.
Fixes #1496.

keg: don't rely on #to_formula

---

Library/Homebrew/shims/super/cc

cc: Add -frounding-math to list of ignored flags

---

Library/Homebrew/dev-cmd/audit.rb

-----
- output the max version and current version to make the message more obvious.
- Don't compare the development spec version to the formula version and then complain the formula version is lower (it should always be!)

audit: fix "version should not decrease" (again).

---

Library/Homebrew/test/test_uninstall.rb

-----
These will be fixed properly later but this will avoid causing unnecessary CI failures.
CC @alyssais just FYI.

uninstall: skip some flaky tests for now.

---

Library/Homebrew/cmd/uninstall.rb

-----
These shouldn’t get here in the first place so this is a bit of a hack pending a better fix.
Reported in https://github.com/Homebrew/homebrew-core/issues/3958#issuecomment-260632390 and I've been unable to reproduce.
CC @mankoff who hit this issue.
CC @alyssais FYI.

uninstall: remove nil requireds/dependents

---

Library/Homebrew/cask/lib/hbc/cli/style.rb

-----
Bump to pass the fix for caskroom/rubocop-cask#44 on to users.
@Homebrew/cask

hbc/cmd/style: bump rubocop-cask to 0.10.6

---

Library/Homebrew/formula.rb
Library/Homebrew/test/formula_test.rb

-----
Fix regression caused by #1364.
Example of the regression: https://bot.brew.sh/job/Homebrew%20Core/11621/version=any_sierra/testReport/junit/brew-test-bot/sierra/test_mpv/.

formula: update test_fixtures path

---

Library/Homebrew/dev-cmd/audit.rb

These are formulae-wide so doesn't make sense to iterate through these for specs and get weird results.
As seem in https://github.com/Homebrew/homebrew-core/pull/6952.
CC @ilovezfs

audit: don't check devel version_scheme/revision.

---

Library/Homebrew/test/support/fixtures/testbottest.rb

-----
This isn't defined for formulae.
CC @reitermarkus @ilovezfs

testbottest: don't use TEST_FIXTURE_DIR.

---

Library/Homebrew/dev-cmd/audit.rb

audit: check formula name against blacklisted names.

---

Library/Homebrew/development_tools.rb
Library/Homebrew/shims/super/cc
Library/Homebrew/version/null.rb

-----
Fixes issues mentioned by @ilovezfs in https://github.com/Homebrew/brew/pull/1130. CC @aw1621107 in case you're interested.

LLVM Clang fixes

---

Library/Homebrew/cask/lib/hbc/cli/reinstall.rb
Library/Homebrew/cask/lib/hbc/cli/uninstall.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/26630.

Load cask file in `.metadata` directory directly.

---

Library/Homebrew/dev-cmd/audit.rb

-----
As these may be migrations from another tap where we want to migrate options across correctly.

audit: allow deprecated options on new @ formulae.

---

Library/Homebrew/formula.rb

-----
The link to formula cookbook is linked to ruby doc, however, the cookbook isn't there. So I correct the link to the cookbook.
I didn't write a new test because my patch updates comment only, and I think that there is no need to write a test to test a comment

Fix broken link

---

Library/Homebrew/exceptions.rb

-----
Don’t fail on `OS::ISSUES_URL` being missing (which happens on unsupported macOS versions) and instead tell people to not file issues.

exceptions: better handle unsupported macOS versions.

---

docs/Kickstarter-Supporters.md

- ~~Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).~~
- ~~Have you successfully run `brew tests` with your changes locally?~~
-----
I no longer maintain my former site so it's better to link to my GitHub account.

Change my site address

---

Library/Homebrew/extend/os/mac/diagnostic.rb

-----
This doesn't add any value and stops us from testing `brew doctor` and others from running `brew doctor` on Travis CI.

diagnostic: silence outdated Travis Xcode warning.

---

Library/Homebrew/cmd/update-report.rb

-----
There were some bugs with the use of `HOMEBREW_NO_ANALYTICS_THIS_RUN` and some output glitches I missed with the previous PR (#1575).

update-report: further tweak analytics output.

---

Library/Homebrew/cmd/update-report.rb

-----
This is used by the install script so it can simplify it's logic and make the analytics messaging more prominent.

update-report: allow skipping analytics message.

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/test/diagnostic_test.rb

-----
Allow our Jenkins CI testing for Homebrew/brew to live outside of `/usr/local` without complaint (as it's not using any binary packages anyway).

diagnostic: silence a Jenkins doctor warning.

---

Library/Homebrew/test/uses_test.rb

uses_test: don't rely on output order.

---

Library/Homebrew/dev-cmd/tap-new.rb

-----
- Use macOS Sierra 10.12 and Xcode 8.
- Add indentation.

tap-new: cleanup and update Travis configuration.

---

Library/.rubocop.yml

-----
We never want to check these for any e.g. taps that use them.

rubocop: exclude more files.

---

docs/Checksum_Deprecation.md

-----
This document was out of date as of https://github.com/Homebrew/brew/pull/1451

docs/Checksum_Deprecation.md: Note that SHA-1 now blocks installation

---

Library/Homebrew/cmd/update.sh

update.sh: Use full path to pkill

---

Library/Homebrew/dev-cmd/tap-new.rb

-----
Pretty sure no-one cares about this except me but this works consistently across a variety of different taps and is faster than the old version.

tap-new: use latest Travis CI recommended config.

---

Library/Homebrew/test/support/helper/fs_leak_logger.rb

-----
This avoids a race condition occurring here.

fs_leak_logger: use more permissive mkpath.

---

Library/Homebrew/test/bash_test.rb

-----
Other tests may delete Bash files (e.g. `shcmd.sh`) while tests are ongoing so ensure this doesn't cause a test failure.

bash_test: handle race condition.

---

.travis.yml
Library/Homebrew/cask/cmd/brew-cask-tests.rb

-----
For code coverage from `brew test-bot`.

travis: use Xcode 8.1 on Sierra.

---

Library/Homebrew/cask/lib/hbc/artifact/moved.rb
Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb
Library/Homebrew/cask/lib/hbc/cli/install.rb
Library/Homebrew/cask/spec/cask/artifact/binary_spec.rb
Library/Homebrew/cask/test/cask/artifact/alt_target_test.rb
Library/Homebrew/cask/test/cask/artifact/app_test.rb
Library/Homebrew/cask/test/cask/artifact/generic_artifact_test.rb
Library/Homebrew/cask/test/cask/artifact/suite_test.rb
Library/Homebrew/cask/test/cask/artifact/two_apps_correct_test.rb

-----
Fail if the app which is to be installed already exists. Otherwise the application bundle will stay inside the `Caskroom` despite the installation completing successfully.
Fixes https://github.com/caskroom/homebrew-cask/issues/23377.
---
@Homebrew/cask

Fail if cask source already exists.

---

Library/Homebrew/os/mac/xcode.rb

-----
Don't wrap `MacOS.version` which does comparisons properly already and avoid stupidly long lines.

xcode: cleanup Xcode::Version usage.

---

Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb
Library/Homebrew/cask/test/cask/artifact/uninstall_test.rb
Library/Homebrew/cask/test/cask/artifact/zap_test.rb

-----
Addresses part of https://github.com/caskroom/homebrew-cask/issues/19076.
---
@Homebrew/cask

Use `launchctl` to get running processes by bundle ID.

---

Library/Homebrew/tab.rb

tab: include HOMEBREW_VERSION

---

Library/Homebrew/dev-cmd/boneyard-formula-pr.rb

-----
- Use ohai to print messages;
- Checkout last branch when done.

boneyard-formula-pr: make it more consistent with bump-formula-pr

---

Library/Homebrew/cask/lib/hbc/cli/reinstall.rb

-----
Closes: caskroom/homebrew-cask#27075

cask reinstall: download and verify cask before uninstall

---

Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/test/reinstall_test.rb

-----
This is both easier for debugging and to communicate with users what is being done.
Found this useful when working on https://github.com/Homebrew/homebrew-core/issues/7630.

reinstall/upgrade/install: always output options.

---

Library/Homebrew/formula_installer.rb

-----
This is no longer needed as the reason it was added (argument sanitisation) is now done properly.
Also, remove `skip_deps_check?` in favour of `ignore_deps?` as it too is no longer needed.

formula_installer: remove dependency_installer.

---

Library/Homebrew/brew.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/formulary.rb

-----
Rather than Homebrew/brew or Homebrew/homebrew-core.

Tell people to report URL/tap deprecations to the tap.

---

Library/Homebrew/keg.rb

-----
If there's dead symlinks in there they should be removed.

keg: also prune opt.

---

docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

-----
I've recently done a bit of work with Homebrew and found the How To Open a Homebrew Pull Request doc really useful. I've updated it slightly to make the create pull request section slightly less formula specific. Let me know if you have any further improvements!

Made the pull request guide slightly less formula specific

---

Library/Homebrew/formula.rb
Library/Homebrew/test/formula_test.rb

-----
Fixes #1554 (but only for new installations).
@ilovezfs I am fairly sure this will fix the issue you reported, but would be great if you could verify.

formula: runtime deps of build deps aren't runtime

---

Library/Homebrew/os/mac/xcode.rb

Updated `latest_version` and `prerelease`.

XCode 8.2 is stable

---

Library/Homebrew/formulary.rb

-----
https://github.com/Homebrew/brew/commit/598c5e36f910d2e14bb77fd3ae5c2f0155e156bd
Fixes #1668

formulary: call tap not formula

---

Library/Homebrew/cask/lib/hbc/installer.rb

-----
Fixes the exception raised when an exception is incorrectly initialized.

Fix error message when cask fails to install.

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md

- Note issues may be closed without comment if sufficient information is not provided.
- Deprecate Homebrew/brew-evolution, note new feature request flow
- Note some issues should be created on Homebrew/brew

Tweak issue template and contributing guidelines.

---

Library/Homebrew/dev-cmd/create.rb

Credit to @ilovezfs for the fix.
Fixes #1688.

create: handle Version::NULL correctly.

---

Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/os/mac/xcode.rb

-----
While we fake a CLT for these versions they never shipped with the CLT so cannot update it.
Requested in https://github.com/Homebrew/brew/issues/1651.

Never trigger too old CLT check on <10.7.

---

Library/Homebrew/dev-cmd/audit.rb

-----
CC @ilovezfs to check I'm not missing something with this check.

audit: handle a nil revision map.

---

docs/Interesting-Taps-&-Forks.md

Correct location of taps (doc)

---

Library/Homebrew/formula_installer.rb

Require `HOMEBREW_CHECK_RECURSIVE_VERSION_DEPENDENCIES` to be specified (which will be by `brew test-bot`) to avoid this being inflicted on end-users unnecessarily.

formula_installer: optional deps version check.

---

Library/Homebrew/cmd/uninstall.rb

-----
- Includes all specified kegs in the message
- Stops comma-separating the kegs in the example command included in the message, which is incorrect syntax

uninstall: a couple of dependency error/warning message improvements

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/development_tools.rb
Library/Homebrew/extend/os/mac/development_tools.rb
Library/Homebrew/global.rb
Library/Homebrew/utils/curl.rb

- Don't run on Yosemite where the system Curl is too old for some modern
HTTPS homepages
- Try up to 3 times in case of transient failures.
CC @broder for thoughts and so your new PR can behave similarly.
-----

audit: improve reliability of homepage audit.

---

Library/Homebrew/formula_versions.rb

Otherwise an uncommitted formula can trigger an invalid `brew audit` result.
CC @ilovezfs
Fixes #1731.

formula_versions: handle uncommitted formulae.

---

Library/Homebrew/keg.rb
Library/Homebrew/test/keg_test.rb
Library/Homebrew/test/uninstall_test.rb

-----
See #1525 for an explanation.

keg: update installed dependency resolution

---

docs/Acceptable-Formulae.md
docs/Custom-GCC-and-cross-compilers.md
docs/FAQ.md
docs/Formula-Cookbook.md
docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md
docs/Interesting-Taps-&-Forks.md
docs/Tips-N'-Tricks.md
docs/Versions.md

Mostly related to the newer ways we’re handling versions and the incoming deprecation of devel-only, head-only and versions.

General documentation updates.

---

Library/Homebrew/formula.rb

formula: correct grammar in comments

---

CONTRIBUTING.md
Library/Homebrew/README.md
Library/Homebrew/cmd/analytics.rb
Library/Homebrew/cmd/help.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/tap-info.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/dev-cmd/create.rb
Library/Homebrew/formula.rb
Library/Homebrew/manpages/brew.1.md.erb
Library/Homebrew/os.rb
Library/Homebrew/utils/analytics.rb
Library/Homebrew/utils/analytics.sh
README.md
docs/Formula-Cookbook.md
docs/Tips-N'-Tricks.md
docs/brew.1.html
manpages/brew.1

These are cleaner, shorter and more user-friendly.

Use docs.brew.sh links.

---

Library/Homebrew/cmd/uses.rb
Library/Homebrew/dependency.rb
Library/Homebrew/test/dependency_test.rb

Reverts Homebrew/brew#1784
CC @ilovezfs @alyssais

Revert "uses: properly handle untapped formulae in recursive dependency expansion"

---

Library/Homebrew/dev-cmd/audit.rb

also allow higher stable versions with the same version prefix

audit: whitelist unstable versions already in core

---

Library/Homebrew/cmd/install.rb
docs/brew.1.html
manpages/brew.1

These can now be done with just `brew upgrade`, like other upgrades.
Fixes #1818.

Fix documentation for HEAD upgrades.

---

Library/Homebrew/manpages/brew.1.md.erb
docs/brew.1.html
manpages/brew.1

brew.1: use uninstall instead of remove.

---

docs/Formula-Cookbook.md

resolves https://github.com/Homebrew/brew/issues/1821
- [ x ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [ x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ x ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [  ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
-----

clarify what should be in brew create url

---

Library/Homebrew/test/formula_test.rb

-----
I was hacking on `Requirement.expand` recently for an improvement I've since decided to handle a different way, but as part of that abandoned patch I wrote some tests for `Requirement.expand` (via `Formula#recursive_requirements`) because I wanted to make sure I didn't break anything and I noticed there currently weren't any.
So, here are some free tests. :D

tests: test Formula#recursive_requirements

---

Library/Homebrew/dev-cmd/create.rb

create: handle null versions.

---

Library/Homebrew/build.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/requirement.rb

If satisfy returns a `Pathname` from `which` then we can use that to infer a formula dependency from that `Requirement`.
CC @ilovezfs who I talked about this with.

requirement: get formula from satisfy.

---

Library/Homebrew/cask/test/cask/artifact/suite_test.rb

I've seen this test fail a few times with no relevant changes.
CC @jawshooah @vitorgalvao @reitermarkus

suite_test: skip flaky test.

---

Library/Homebrew/cmd/uses.rb
Library/Homebrew/dependency.rb
Library/Homebrew/test/dependency_test.rb

-----
This is a re-submit of #1784, but without the removal of the formula-level exception handler that required it to later be reverted. I still want that to be removed, but I'll leave it for now.
@MikeMcQuaid @ilovezfs @echosa
Fixes #1776.

uses: properly handle untapped formulae in recursive dependency expansion (again!)

---

Library/Homebrew/.rubocop_todo.yml
Library/Homebrew/dev-cmd/bottle.rb

-----
This would have eliminated the need for Homebrew/homebrew-core#9000, for instance.

bottle: add: improve regexp to recognize comments

---

Library/Homebrew/test/cleanup_test.rb
Library/Homebrew/test/formula_installer_test.rb
Library/Homebrew/test/support/helper/test_case.rb
Library/Homebrew/test/uninstall_test.rb

tests: reset ARGV in teardown

---

Library/Homebrew/dev-cmd/bottle.rb

Noted that this is intended for the revision of this formula instead of
rebuild of a bottle.
-----------------
Sorry of being missing for long time.
But, I think I should start to find some time to contribute Homebrew again
from next month or so.

bottle: fix regex

---

Library/Homebrew/cask/lib/hbc/cli/internal_dump.rb
Library/Homebrew/cask/lib/hbc/cli/internal_help.rb
Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb

-----
Nothing major, just making HBC’s internal stanzas consistent (always use `args` instead of `arguments`, and make help start with a capital letter).

Cask: cleanups internal stanzas

---

Library/Homebrew/cask/lib/hbc/installer.rb

-----
Fixes https://github.com/Homebrew/brew/issues/1785#issuecomment-271378674.
@jeremy, thank you for providing the diff in https://github.com/Homebrew/brew/issues/1785#issuecomment-274380422.

Fix installer deleting artifacts if they already exist.

---

Library/Homebrew/dev-cmd/audit.rb

-----
This can be reverted when wine's dependencies are all vendored.

audit: exempt wine's deps from the universal deprecation

---

Library/Homebrew/caveats.rb

Slim down the existing text and make it more obvious what's happening. Note specifically how to add it to your PATH to convince people to try that
instead of `brew link --force`.
CC @alyssais @ilovezfs for review and thoughts.

caveats: tweak keg-only messaging.

---

Library/Homebrew/cask/.gitattributes
Library/Homebrew/cask/Gemfile
Library/Homebrew/cask/Gemfile.lock
Library/Homebrew/cask/Rakefile
Library/Homebrew/cask/test/README.md

-----
Extracted from https://github.com/Homebrew/brew/pull/1314 for easier review.
Removes some unnecessary files and updates the Gemfile.

Cleanup Cask test directory.

---

Library/Homebrew/caveats.rb

CC @DomT4 is this what you were thinking? Thanks for the report.

caveats: add newline after keg only reason.

---

Library/Homebrew/formula_cellar_checks.rb

Reverts Homebrew/brew#1916
Reverting this for now until we figure out a better strategy CC @ilovezfs @nijikon

Revert "formula_cellar_checks: check for prefix/etc."

---

Library/Homebrew/manpages/brew-cask.1.md
manpages/brew-cask.1

-----
See discussion in https://github.com/caskroom/homebrew-cask/pull/29421 for the motivation behind this PR.
Pinging @vitorgalvao and @reitermarkus for review/approval.

Update brew-cask.1.md to include _stanza internal command

---

Library/Homebrew/cmd/update.sh
docs/brew.1.html
manpages/brew.1

As requested in https://github.com/Homebrew/homebrew-core/issues/9316.

update: note migrations may be performed.

---

Library/Homebrew/cask/lib/hbc/artifact/base.rb
Library/Homebrew/cask/lib/hbc/artifact/installer.rb
Library/Homebrew/cask/lib/hbc/artifact/nested_container.rb
Library/Homebrew/cask/lib/hbc/artifact/pkg.rb
Library/Homebrew/cask/lib/hbc/artifact/stage_only.rb
Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb
Library/Homebrew/cask/lib/hbc/artifact/zap.rb
Library/Homebrew/cask/lib/hbc/installer.rb
Library/Homebrew/cask/test/cask/artifact/pkg_test.rb
Library/Homebrew/cask/test/cask/artifact/uninstall_test.rb
Library/Homebrew/cask/test/cask/artifact/zap_test.rb

-----
Remove no-op `install_phase` and `uninstall_phase` methods and use `respond_to?` instead.

Refactor Cask `Artifact`s.

---

Library/Homebrew/cask/lib/hbc/cli/doctor.rb
Library/Homebrew/cask/spec/cask/cli/doctor_spec.rb

-----
Removed all variables that are also show when calling `brew config`.

Simplify `brew cask doctor`.

---

Library/Homebrew/cask/lib/hbc/artifact.rb
Library/Homebrew/cask/lib/hbc/cli/list.rb
Library/Homebrew/cask/lib/hbc/dsl.rb
Library/Homebrew/cask/lib/hbc/installer.rb
Library/Homebrew/cask/test/cask/installer_test.rb

-----
Refactor `Artifact.for_cask` to return instances of the according types instead of classes.

Refactor `Artifact`.

---

Library/Homebrew/cask/spec/cask/audit_spec.rb
Library/Homebrew/cask/spec/cask/verify/checksum_spec.rb
Library/Homebrew/cask/spec/support/sha256_helper.rb

-----
Only used in a few places and randomness is not crucial for the tests.

Remove `Sha256Helper`.

---

Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb

-----
Closes https://github.com/caskroom/homebrew-cask/issues/26637.

Display message when running `brew cask _stanza` without arguments.

---

Library/Homebrew/keg.rb
Library/Homebrew/test/bottle_test.rb
Library/Homebrew/test/options_test.rb
Library/Homebrew/test/support/helper/integration_command_test_case.rb

-----
Simplify `IntegrationCommandTestCase` by using `Open3`.

Use `Open3` for integration tests instead of manually forking.

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/test/audit_test.rb

Ref: https://sourceforge.net/blog/introducing-https-for-project-websites/
-----
I tested the new condition/suggestion in a minimised test source.

audit: enforce https://*.sourceforge.io/ homepages

---

Library/Homebrew/cmd/--prefix.rb

--prefix: use opt_prefix when available.

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

bump-formula-pr: block duplicate pull-requests

---

Library/Homebrew/cask/lib/hbc/installer.rb
Library/Homebrew/cask/spec/cask/cli/uninstall_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-script-app.rb

----
`uninstall` scripts my be contained inside the `app` they are uninstalling, or depend on it still being present.

Make sure `uninstall` is called before artifacts are removed.

---

Library/Homebrew/cask/lib/hbc/caskroom.rb
Library/Homebrew/cask/lib/hbc/cli/fetch.rb

Small fixes.

---

Library/Homebrew/extend/os/linux/requirements/java_requirement.rb
Library/Homebrew/extend/os/mac/requirements/java_requirement.rb
Library/Homebrew/extend/os/requirements/java_requirement.rb
Library/Homebrew/requirements/java_requirement.rb
Library/Homebrew/test/java_requirement_test.rb
Library/Homebrew/test/os/mac/java_requirement_test.rb

-----
Split the core requirement class into generic, Linux-specific,
and macOS-specific parts. The actual Mac code has only
been moved, not modified. The Linux code has been simplified.
\* Caveat here: the tests pass completely on Mac. On Linux, they have a single failure, but said failure is also reproducible on the master branch without my changes. Also note that it has nothing to do with the Java requirement.

java_requirement: port to Linux and refactor

---

Library/Homebrew/cmd/update-report.rb

update-report: unlink rather than uninstall --force formula when migrating a formula to a cask

---

Library/Homebrew/formula.rb

-----
Following a comment on my recent PR at Homebrew/homebrew-core#10122, wanted to update the docs to reflect the desired style for future contributors 😄

Docs for tag-based urls use preferred formatting

---

Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb
Library/Homebrew/cask/spec/cask/artifact/uninstall_spec.rb
Library/Homebrew/cask/spec/cask/artifact/zap_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-installable.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-delete.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-rmdir.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-trash.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-zap-delete.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-zap-rmdir.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-zap-trash.rb

Fixes https://github.com/caskroom/homebrew-cask/issues/12991
These are my first Ruby code lines so please be forgiving 😄 
-----

Expand glob patterns.

---

Library/Homebrew/formulary.rb

-----
`Formulary` cannot be `initialize`d, so it makes sense for it to be a `module`.

Make `Formulary` a `module`.

---

Library/Homebrew/test/compiler_failure_spec.rb

Use `alias_matcher` for `fail_with`.

---

Library/Homebrew/brew.sh
Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/global.rb

-----
If `brew instal` is permissible, `brew uninstal` should be, too.

brew uninstal alias for brew uninstall

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/readall.rb

Reverts Homebrew/brew#1850
See https://github.com/Homebrew/brew/issues/2087.
CC @MikeMcQuaid @alyssais

Revert "audit: check for version aliases."

---

Library/Homebrew/dev-cmd/audit.rb

Revert "audit: fix revision should be removed."

---

Library/Homebrew/formula_versions.rb

Revert "formula_versions: handle uncommitted formulae."

---

Library/Homebrew/dev-cmd/tests.rb

Exclude specs with `:needs_macos` tag when not on macOS.

---

docs/Acceptable-Formulae.md
docs/Brew-Test-Bot-For-Core-Contributors.md
docs/Brew-Test-Bot.md
docs/Common-Issues.md
docs/External-Commands.md
docs/FAQ.md
docs/Formula-Cookbook.md
docs/Gems,-Eggs-and-Perl-Modules.md
docs/Homebrew-and-Python.md
docs/How-To-Open-a-Homebrew-Pull-Request.md
docs/Interesting-Taps-&-Forks.md
docs/Node-for-Formula-Authors.md
docs/Prose-Style-Guidelines.md
docs/Python-for-Formula-Authors.md
docs/Querying-Brew.md
docs/Tips-N'-Tricks.md
docs/Versions.md
docs/brew-tap.md

Fixes for consistency in spelling, grammar, and fixes for links that I found while reading through the docs end to end. Some formatting changes apply only to how they display on http://docs.brew.sh/.
- (N/A) Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- (N/A) Have you successfully run `brew tests` with your changes locally?

Fix spelling, grammar, URLs in docs

---

Library/Homebrew/test/cmd/config_spec.rb
Library/Homebrew/test/config_test.rb

Convert `brew config` test to spec.

---

Library/Homebrew/test/cache_formula_test.rb
Library/Homebrew/test/cache_test.rb
Library/Homebrew/test/cmd/--cache_spec.rb

Convert `brew --cache` test to spec.

---

Library/Homebrew/test/ENV_test.rb
Library/Homebrew/test/cmd/--env_spec.rb

Convert `brew --env` test to spec.

---

Library/Homebrew/test/cat_test.rb
Library/Homebrew/test/cmd/cat_spec.rb

Convert `brew cat` test to spec.

---

Library/Homebrew/test/cmd/sh_spec.rb
Library/Homebrew/test/sh_test.rb

Convert `brew sh` test to spec.

---

Library/Homebrew/test/cleanup_test.rb
Library/Homebrew/test/cmd/cleanup_spec.rb

Convert `brew cleanup` test to spec.

---

Library/Homebrew/test/dev-cmd/formula_spec.rb
Library/Homebrew/test/formula_cmd_test.rb

Convert `brew formula` test to spec.

---

Library/Homebrew/test/cmd/options_spec.rb
Library/Homebrew/test/options_test.rb

Convert `brew options` test to spec.

---

Library/Homebrew/test/cmd/commands_spec.rb
Library/Homebrew/test/commands_test.rb

Convert `brew commands` test to spec.

---

Library/Homebrew/test/cmd/--version_spec.rb
Library/Homebrew/test/version_test.rb

Convert `brew --version` test to spec.

---

Library/Homebrew/test/cmd/--prefix_spec.rb
Library/Homebrew/test/prefix_formula_test.rb
Library/Homebrew/test/prefix_test.rb

Convert `brew --prefix` test to spec.

---

Library/Homebrew/test/dev-cmd/tap_spec.rb
Library/Homebrew/test/tap_test.rb

Convert `brew tap` test to spec.

---

Library/Homebrew/test/cmd/tap-new_spec.rb
Library/Homebrew/test/tap_new_test.rb

Convert `brew tap-new` test to spec.

---

Library/Homebrew/test/cmd/doctor_spec.rb
Library/Homebrew/test/doctor_test.rb

Convert `brew doctor` test to spec.

---

Library/Homebrew/test/cellar_formula_test.rb
Library/Homebrew/test/cellar_test.rb
Library/Homebrew/test/cmd/--cellar_spec.rb

Convert `brew --cellar` test to spec.

---

Library/Homebrew/test/cmd/uninstall_spec.rb
Library/Homebrew/test/uninstall_test.rb

Convert `brew uninstall` test to spec.

---

Library/Homebrew/test/cmd/info_spec.rb
Library/Homebrew/test/info_test.rb

Convert `brew info` test to spec.

---

Library/Homebrew/dev-cmd/audit.rb

-----
These were imported from homebrew/games.

audit: whitelist more unstable versions already in core

---

Library/Homebrew/test/spec_helper.rb
Library/Homebrew/test/support/helper/formula.rb

Add `formula` spec helper.

---

Library/Homebrew/formula.rb

CC @ilovezfs @alyssais to discuss this.

formula: clarify caveats usage.

---

Library/Homebrew/formula_installer.rb

Detect recursive dependencies and refuse to install them providing instruction on exactly what is depending on what.
Fixes #1933.

formula_installer: detect recursive dependencies.

---

Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb

Use `around` hook for shared "integration test" context.

---

Library/Homebrew/extend/ARGV.rb

-----
Wouldn't it be better if `include?` returned `true` or `false`?

ARGV.include? should return boolean

---

Library/Homebrew/test/spec_helper.rb

Use shorter `before` syntax to skip tests.

---

Library/Homebrew/test/audit_test.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb

Convert FormulaText test to spec.

---

Library/Homebrew/test/cmd/bundle_spec.rb
Library/Homebrew/test/cmd/commands_spec.rb
Library/Homebrew/test/cmd/custom-external-command_spec.rb
Library/Homebrew/test/cmd/linkapps_spec.rb
Library/Homebrew/test/cmd/unlinkapps_spec.rb
Library/Homebrew/test/cmd/unpack_spec.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb
Library/Homebrew/test/diagnostic_spec.rb
Library/Homebrew/test/gpg2_requirement_spec.rb
Library/Homebrew/test/gpg_spec.rb
Library/Homebrew/test/java_requirement_spec.rb
Library/Homebrew/test/language/go_spec.rb
Library/Homebrew/test/language/python_spec.rb
Library/Homebrew/test/os/mac/java_requirement_spec.rb
Library/Homebrew/test/pathname_spec.rb
Library/Homebrew/test/sandbox_spec.rb
Library/Homebrew/test/spec_helper.rb
Library/Homebrew/test/support/helper/mktmpdir.rb
Library/Homebrew/test/utils_spec.rb

Add `mktmpdir` helper method.

---

.github/ISSUE_TEMPLATE.md

-----
Quick grammar fix for the new issue template. Same change as Homebrew/homebrew-core#10452.

Fix typo in the new issue template

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

If it's not there, error out rather than fetching to avoid creating
versionless cache files, which cause `brew cleanup` to crash.

bump-formula-pr: check for version presence.

---

Library/Homebrew/utils.rb

Use `Gem.bindir` instead of `#{Gem.dir}/bin`.

---

Library/Homebrew/test/cmd/cask_spec.rb

---
Outputs `Warning: Nothing to list` to `STDERR`.

Silence `cmd/cask` test.

---

Library/Homebrew/.simplecov

Remove `dev-cmd/tests.rb` from test coverage.

---

Library/Homebrew/cask/lib/hbc/cli/style.rb

Use `--force-default-config` option for `brew cask style`.

---

Library/Homebrew/dev-cmd/tests.rb

---
This is now set in `.bundle/config`.

Remove `BUNDLE_PATH` from `brew tests`.

---

Library/Homebrew/test/cask/cli/doctor_spec.rb
Library/Homebrew/test/cask/cli/style_spec.rb
Library/Homebrew/test/cask/dsl/stanza_proxy_spec.rb
Library/Homebrew/test/cask/dsl/version_spec.rb
Library/Homebrew/test/cask/macos_spec.rb
Library/Homebrew/test/cask/verify/checksum_spec.rb

Add missing `:cask` metadata to specs.

---

Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/sh.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/dev-cmd/update-test.rb
Library/Homebrew/manpages/brew.1.md.erb
docs/brew.1.html
manpages/brew.1

- [N/A] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
-----
Adds some flags and command descriptions that were missing from the man pages. Descriptions are from what I could determine by running commands and reading the sources, but I may have missed some details.

Add more flags and descriptions to man pages.

---

Library/Homebrew/cask/lib/hbc/cli.rb

Use Homebrew’s `require?`.

---

Library/Homebrew/dev-cmd/bottle.rb

-----
There are two `odie` calls back to back. Extra-defensive programming. Really die. I mean it. :wink:

bottle: Remove superfluous odie

---

Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb

Refactor `brew cask _audit_modified_casks`.

---

Library/Homebrew/cask/lib/hbc/cask.rb

Make `timestamped_versions` return an array of strings.

---

Library/Homebrew/cask/lib/hbc.rb
Library/Homebrew/cask/lib/hbc/cache.rb
Library/Homebrew/cask/lib/hbc/caskroom.rb
Library/Homebrew/cask/lib/hbc/locations.rb
Library/Homebrew/compat/hbc.rb
Library/Homebrew/compat/hbc/cache.rb
Library/Homebrew/compat/hbc/caskroom.rb

Move legacy cache and caskroom code to `compat/*`.

---

Library/Homebrew/cask/lib/hbc/cli/cleanup.rb
Library/Homebrew/cask/lib/hbc/cli/style.rb
Library/Homebrew/cask/lib/hbc/utils.rb
Library/Homebrew/test/cask/cli/cleanup_spec.rb

Remove redundant `Utils`.

---

Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/test/cask/cli/options_spec.rb

Use `ArgumentError` instead of `CaskError` in `CLI`.

---

Library/Homebrew/cask/lib/hbc/artifact/binary.rb
Library/Homebrew/cask/lib/hbc/artifact/relocated.rb
Library/Homebrew/test/cask/artifact/binary_spec.rb

-----
Closes https://github.com/caskroom/homebrew-cask/issues/29533.

Always `chmod +x` `binary` stanzas.

---

Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/cask/lib/hbc/cli/--version.rb
Library/Homebrew/test/cask/cli/--version_spec.rb
Library/Homebrew/test/cask/cli/version_spec.rb
Library/Homebrew/test/cask/cli_spec.rb
Library/Homebrew/test/spec_helper.rb
Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb

Move `brew cask --version` into separate file.

---

Library/Homebrew/cask/lib/hbc/artifact/base.rb
Library/Homebrew/cask/lib/hbc/artifact/binary.rb
Library/Homebrew/cask/lib/hbc/artifact/moved.rb
Library/Homebrew/cask/lib/hbc/artifact/relocated.rb
Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb
Library/Homebrew/test/cask/artifact/app_spec.rb
Library/Homebrew/test/cask/cli/uninstall_spec.rb

Refactor artifacts.

---

Library/Homebrew/cask/lib/hbc/pkg.rb
Library/Homebrew/test/cask/artifact/uninstall_zap_shared_examples.rb
Library/Homebrew/test/cask/pkg_spec.rb

Fix `uninstall :pkgutil` leaving empty `.app` directories.

---

Library/Homebrew/test/cask/cli/--version_spec.rb

Fix “Hombrew” typo.

---

Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/linkapps.rb
Library/Homebrew/cmd/tap-info.rb
Library/Homebrew/cmd/unlinkapps.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/compat/utils.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/tap.rb
Library/Homebrew/test/formatter_spec.rb
Library/Homebrew/test/utils_spec.rb
Library/Homebrew/utils.rb
Library/Homebrew/utils/formatter.rb

Replace `#plural` by `Formatter::pluralize`.

---

Library/Homebrew/cask/lib/hbc/cask.rb
Library/Homebrew/cask/lib/hbc/installer.rb

Remove old metadata when installing with `--force`.

---

Library/Homebrew/cask/lib/hbc.rb
Library/Homebrew/cask/lib/hbc/cli/list.rb
Library/Homebrew/cask/lib/hbc/locations.rb
Library/Homebrew/cask/lib/hbc/url.rb
Library/Homebrew/compat/hbc.rb
Library/Homebrew/compat/hbc/caskroom.rb

Migrate legacy Caskroom.

---

Library/Homebrew/cask/lib/hbc/cli/home.rb
Library/Homebrew/cask/lib/hbc/url.rb
Library/Homebrew/manpages/brew-cask.1.md
Library/Homebrew/test/cask/cli/home_spec.rb
Library/Homebrew/test/cask/download_strategy_spec.rb
manpages/brew-cask.1

-----
After the last one [failed badly](https://github.com/Homebrew/brew/pull/2171), hopefully this time it works.
(Ping @reitermarkus)

Change instances of caskroom.io to caskroom.github.io

---

Library/Homebrew/cask/lib/hbc/auditor.rb

Use `CaskLoader.load_from_file` in `Auditor`.

---

Library/Homebrew/cask/lib/hbc/cask.rb
Library/Homebrew/cask/lib/hbc/cli/list.rb
Library/Homebrew/cask/lib/hbc/cli/reinstall.rb

Add `#installed_caskfile` method to `Cask` class.

---

Library/Homebrew/cask/lib/hbc/artifact/installer.rb
Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb
Library/Homebrew/test/cask/artifact/uninstall_zap_shared_examples.rb

-----
https://github.com/caskroom/homebrew-cask/issues/13608

Default to `sudo: false` for `installer/uninstall :script`.

---

docs/Querying-Brew.md

Querying-Brew.md: directors => directories

---

Library/Homebrew/constants.rb

Update RuboCop-Cask to 0.12.0.

---

Library/Homebrew/cask/lib/hbc/cask.rb

Remove `dsl` parameter from `Cask::new`.

---

Library/Homebrew/cask/lib/hbc/cli/search.rb
Library/Homebrew/cask/lib/hbc/utils.rb
Library/Homebrew/test/cask/cli/search_spec.rb

In response to https://github.com/caskroom/homebrew-cask/issues/30583
-----

Added highlighting of installed casks to cask search

---

Library/Homebrew/cask/lib/hbc/cli/home.rb
Library/Homebrew/cask/lib/hbc/url.rb
Library/Homebrew/dev-cmd/aspell-dictionaries.rb
Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/os/mac/hardware/cpu.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/manpages/brew-cask.1.md
Library/Homebrew/test/cask/cli/home_spec.rb
Library/Homebrew/test/cask/download_strategy_spec.rb
Library/Homebrew/vendor/macho/macho/utils.rb
Library/Homebrew/version.rb
docs/Gems,-Eggs-and-Perl-Modules.md
docs/Python-for-Formula-Authors.md
docs/_layouts/index.html
docs/brew.1.html
manpages/brew-cask.1
manpages/brew.1

-----
Use secure protocols where possible.

secure urls + remove -k from in-doc curl command

---

Library/Homebrew/cask/lib/hbc/artifact/relocated.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/30953.

Remove `sort` from `each_artifact`.

---

Library/Homebrew/cask/lib/hbc/cli/base.rb
Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb
Library/Homebrew/test/cask/cli_spec.rb

Add test for command help strings.

---

Library/Homebrew/extend/os/linux/system_config.rb
Library/Homebrew/extend/os/system_config.rb

Report the Linux kernel, OS, and gcc versions.

Add extend/os/linux/system_config.rb

---

Library/Homebrew/dev-cmd/audit.rb

-----
Previously, the http_content_headers_and_checksum method always
downloaded the entire url, including headers. These downloads make
the audit more likely to hang or output false positives. The only
time the entire file is actually used is when verifying that the url
can use the HTTPS protocol instead of HTTP. Therefore, pass curl the
-I flag to only fetch headers unless the protocol is HTTP. If it is,
maintain the old behavior by passing --include to download both the
headers and the file.

audit: online - limit download time based on HTTPS determination

---

Library/Homebrew/migrator.rb

-----
Lets us migrate a formula to a name that may have previously been used.
If gnupg 1.x is installed as "gnupg" and gnupg 2.x is installed as
"gnupg2," it's currently not possible to rename gnupg2 -> gnupg, since
the 1.4 keg will already be installed in the gnupg cellar, so in order
to reclaim the name "gnupg" to be used for 2.1, either 1.x must be
manually uninstalled, or the new cellar needs to be allowed to exist
already.
The other choice here would be to continue using the name "gnupg2" for
the 2.1 series, and not reclaim the name "gnupg" from 1.x, which,
incidentally, would open up the possibility of a gnupg -> gnupg@1.4
rename.

migrator: allow new cellar to exist already

---

README.md

For the current release, Travis CI and Coveralls status.

README: add some more shields.

---

docs/New-Maintainer-Checklist.md

Note some additional ways to help, gotchas and how to get started.
CC @Homebrew/maintainers if you have any thoughts, objections or if there's anything you wish had been in here when you joined.

New-Maintainer-Checklist: be more explicit.

---

docs/Acceptable-Formulae.md
docs/Bottles.md
docs/Brew-Test-Bot.md
docs/C++-Standard-Libraries.md
docs/Common-Issues.md
docs/Custom-GCC-and-cross-compilers.md
docs/External-Commands.md
docs/FAQ.md
docs/Formula-Cookbook.md
docs/Gems,-Eggs-and-Perl-Modules.md
docs/Homebrew-and-Python.md
docs/How-to-Create-and-Maintain-a-Tap.md
docs/How-to-build-software-outside-Homebrew-with-Homebrew-keg-only-dependencies.md
docs/Installation.md
docs/Interesting-Taps-&-Forks.md
docs/Migrating-A-Formula-To-A-Tap.md
docs/Node-for-Formula-Authors.md
docs/Python-for-Formula-Authors.md
docs/Querying-Brew.md
docs/Rename-A-Formula.md
docs/Tips-N'-Tricks.md
docs/Troubleshooting.md
docs/Versions.md
docs/brew-tap.md

Added labeled fences to most code blocks, monospaced terms where appropriate, and omitted "$" or replaced with angle brackets when referring to variables. (And caught some goofs from my last edit.)
- [N/A] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
-----

docs: code example reformatting

---

Library/Homebrew/dev-cmd/audit.rb

audit: bump whitelisted elm-format version to 0.6.0-alpha

---

Library/Homebrew/dev-cmd/audit.rb

-----
Now that ruby-macho is available, cctools should be invoked as little
as possible.

audit: Check for invocations of cctools.

---

Library/Homebrew/cask/lib/hbc/container.rb
Library/Homebrew/cask/lib/hbc/container/executable.rb

-----
This way we can eliminate the need for `container type: :naked` for many `binary` Casks.

Add `Container::Executable`.

---

Library/Homebrew/dev-cmd/audit.rb

If we're adding a versioned formulae we want to ensure that there's also an unversioned one too.
See https://github.com/Homebrew/homebrew-core/issues/11279 for motivation.

audit: check for unversioned formulae.

---

Library/Homebrew/formula.rb
Library/Homebrew/test/formula_spec.rb

Otherwise return `nil`.
Fixes https://github.com/Homebrew/brew/issues/2417
CC @alyssais

formula: check installed_alias_path exists.

---

Library/Homebrew/requirements/ruby_requirement.rb

ruby_requirement: fix path prepend

---

Library/Homebrew/missing_formula.rb

----
Homebrew/python is gone so this text should be updated.

missing_formula: pillow lives in homebrew/science

---

.github/ISSUE_TEMPLATE.md

Be clearer about what's expected and where to file things.
See also https://github.com/Homebrew/homebrew-core/pull/11972

ISSUE_TEMPLATE: tweak instructions.

---

.github/stale.yml

See https://github.com/probot/stale for more details.
CC @bkeepers for ❤️

Add probot-stale configuration.

---

Library/Homebrew/os/mac/xcode.rb

Our CI images are already updated with it.

xcode: 8.3.1 is latest version.

---

Library/Homebrew/cask/lib/hbc/scopes.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/31784.

Fix `brew cask audit` not working without argument.

---

Library/Homebrew/dev-cmd/audit.rb

As requested in #11462 by @neutric as this produces confusing, incorrect output.

audit: don't recommend version aliases on --devel.

---

Library/Homebrew/test/diagnostic_spec.rb

[WIP] Added test for check_access_lock_dir

---

Library/Homebrew/cmd/uses.rb

This is useful for seeing when formulae are deleted if they are going to leave behind any formulae that depend on them.
As a result, if there are any formulae returned return a non-zero/failed exit status.

uses: allow checking deleted formulae.

---

Library/Homebrew/cmd/install.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/formulary.rb

These formulae are detected as missing but exist in an unreadable form.
CC @DomT4 @chdiza
Fixes #2497

install: don't search when formula is unreadable.

---

Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/xcode.rb
docs/Xcode.md

-----
The Sierra CI will need to be updated accordingly.
Given the content of this PR: cc @MikeMcQuaid

xcode: 8.3.2 is latest version

---

docs/Acceptable-Formulae.md

-----
That’s four “be” instead of one *but* that “…must be have a homepage” was bugging me 😄

Acceptable-Formulae: reword 'niche stuff'

---

Library/Homebrew/cmd/search.rb
Library/Homebrew/official_taps.rb

---
It's actually `caskroom`, not `Caskroom`. Also added newly created Taps.

Lowercase `caskroom` and add missing Taps.

---

Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/extend/os/linux/requirements/osxfuse_requirement.rb
Library/Homebrew/extend/os/mac/requirements/osxfuse_requirement.rb
Library/Homebrew/extend/os/requirements/osxfuse_requirement.rb
Library/Homebrew/requirements/osxfuse_requirement.rb
Library/Homebrew/test/os/linux/osxfuse_requirement_spec.rb
Library/Homebrew/test/os/mac/osxfuse_requirement_spec.rb

-----
Next round of Linuxbrew upstreaming changes.
We've been getting a lot of requests recently for FUSE support, so it made sense to tackle this one next.

Port OsxfuseRequirement to Linux

---

Library/Homebrew/cask/lib/hbc/system_command.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/32364.

Fix `IO#select` blocking.

---

README.md
docs/Manpage.md
manpages/brew.1

README: Add Charlie to former maintainers.

---

README.md

Just a missing space in the `README.md` page.

[trifle] missing space

---

Library/Homebrew/cask/lib/hbc/container.rb
Library/Homebrew/cask/lib/hbc/dsl/container.rb

-----
Closes https://github.com/caskroom/homebrew-cask/issues/6070.

Validate `container :type`.

---

Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/test/cask/cli/style_spec.rb
Library/Homebrew/test/cask/cli/uninstall_spec.rb
Library/Homebrew/test/cmd/bundle_spec.rb
Library/Homebrew/test/dev-cmd/pull_spec.rb
Library/Homebrew/test/missing_formula_spec.rb
Library/Homebrew/test/spec_helper.rb

- Tweak the way offline skipping happens
- Skip more tests that break when offline
- Hide more stdout output from tests.

tests: reduce some noise.

---

Library/Homebrew/dev-cmd/audit.rb

This means that if e.g. the unversioned formulae exists in another tap this audit won't produce a false positive.

audit: lookup unversioned formulae with Formulary.

---

Library/Homebrew/brew.rb
Library/Homebrew/dependable.rb
Library/Homebrew/extend/ENV/std.rb
Library/Homebrew/extend/pathname.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/global.rb
Library/Homebrew/os/mac/xquartz.rb
Library/Homebrew/test/cmd/install_spec.rb
Library/Homebrew/utils/analytics.sh
bin/brew

Fix those that can be done so without tearing Homebrew to pieces and remove the comments for those that can never be done.

Fix and remove various TODOs.

---

Library/Homebrew/test/version_spec.rb
Library/Homebrew/version.rb

As suggested in https://github.com/Homebrew/brew/issues/2439 adds date-based versioning (RFC 3339).

add date-based versioning

---

Library/Homebrew/cask/lib/hbc/cli/search.rb
Library/Homebrew/cmd/search.rb
Library/Homebrew/test/cask/cli/search_spec.rb
Library/Homebrew/test/cmd/search_remote_tap_spec.rb
Library/Homebrew/test/utils/github_spec.rb
Library/Homebrew/utils/github.rb

-----
Adds functionality to `brew cask search` to search remote Taps.
Closes https://github.com/caskroom/homebrew-cask/issues/16732.

Add remote search to `brew cask search`.

---

.gitignore
docs/css/screen.css

Import new brew.sh CSS changes to improve the appearance of tables and links.

docs: tweak CSS.

---

Library/Homebrew/vendor/README.md
Library/Homebrew/vendor/plist/plist.rb
Library/Homebrew/vendor/plist/plist/generator.rb
Library/Homebrew/vendor/plist/plist/parser.rb
Library/Homebrew/vendor/plist/plist/version.rb

Update `plist` to 3.3.0.

---

Library/Homebrew/caveats.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb

-----
Follow up to https://github.com/Homebrew/brew/pull/2472.

caveats: tweak keg_only style

---

Library/Homebrew/formulary.rb

-----
This PR makes it possible to install a bottle from an URL. For example
```sh
brew install https://4574-56942570-gh.circle-artifacts.com/0/tmp/circle-artifacts.PaJXYOU/git-2.12.2.x86_64_linux.bottle.tar.gz
```

Install a bottle from an URL

---

.travis.yml
Library/Homebrew/dev-cmd/tap-new.rb
Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/test/Gemfile.lock

Attempt to improve Travis CI. This time without any vendoring gems nonsense.

Travis CI tweaks.

---

Library/Homebrew/dev-cmd/audit.rb

Check that a required versioned alias has a valid name (rather than
assuming it’s fine based on it’s existence alone) and check for
the presence of invalid version aliases.
This should handle the case where someone bumps a formula but forgets
to rename the alias that’s mentioned in #2596.

audit: more checks for versioned aliases.

---

Library/Homebrew/dev-cmd/audit.rb

Instead of trying to do this all with a single regex give up and do a two stage process. Eventually I'll end up implementing a full ruby parser here :trollface:.
CC @ilovezfs @DomT4 who hit this.

audit: fix dependency option detection.

---

Library/Homebrew/brew.rb
Library/Homebrew/cask/lib/hbc/artifact/relocated.rb
Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/cmd/style.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/tap_constants.rb
Library/Homebrew/test/cmd/--env_spec.rb
Library/Homebrew/test/cmd/--version_spec.rb
Library/Homebrew/test/support/helper/spec/shared_examples/hbc_staged.rb
Library/Homebrew/utils.rb
Library/Homebrew/utils/github.rb
Library/Homebrew/version.rb

Remove `to_s` from some `Pathname`s.

---

Library/Homebrew/brew.rb
Library/Homebrew/cask/lib/hbc/cli.rb

-----
This fixes https://github.com/Homebrew/brew/issues/2651 by explicitly converting `nil` values to an empty string.
cc @reitermarkus

Fix implicit conversion of nil into string error

---

Library/Homebrew/build_environment.rb
Library/Homebrew/formula.rb
Library/Homebrew/requirement.rb
Library/Homebrew/test/bash_spec.rb
Library/Homebrew/test/bottle_hooks_spec.rb
Library/Homebrew/test/build_environment_spec.rb
Library/Homebrew/test/build_options_spec.rb
Library/Homebrew/test/compiler_failure_spec.rb
Library/Homebrew/test/dependable_spec.rb
Library/Homebrew/test/dependency_collector_spec.rb
Library/Homebrew/test/dependency_spec.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb
Library/Homebrew/test/formula_installer_bottle_spec.rb
Library/Homebrew/test/formula_installer_spec.rb
Library/Homebrew/test/formula_spec.rb
Library/Homebrew/test/os/mac/dependency_collector_spec.rb
Library/Homebrew/test/requirement_spec.rb
Library/Homebrew/test/sandbox_spec.rb
Library/Homebrew/test/software_spec_spec.rb
Library/Homebrew/test/tab_spec.rb
Library/Homebrew/test/tap_spec.rb

Use scoped RSpec matchers.

---

Library/Homebrew/dev-cmd/audit.rb

-----
This fixes #2657 which in turn were caused by an oversight in https://github.com/Homebrew/brew/pull/2644.

audit: fix versioned alias errors in homebrew/core introduced in a7c6a57

---

Library/Homebrew/patch.rb

patch: clean up with Forwardable

---

Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb
Library/Homebrew/cask/lib/hbc/cli/internal_appcast_checkpoint.rb

-----
This was overlooked in https://github.com/Homebrew/brew/pull/2654.
---
Fixes https://github.com/caskroom/homebrew-cask/issues/34787.

Fix appcast checkpoint command.

---

Library/Homebrew/formula_versions.rb

-----
Fixes https://github.com/Homebrew/brew/issues/2665.

Fix `previous_version_and_checksum` method.

---

Library/Homebrew/manpages/brew-cask.1.md
manpages/brew-cask.1

Add `SUDO_ASKPASS` to `brew-cask` manpage.

---

Library/Homebrew/cask/lib/hbc/artifact.rb
Library/Homebrew/cask/lib/hbc/installer.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/32300.

Fix `uninstall` order.

---

Library/Homebrew/cask/lib/hbc/cli/options.rb
Library/Homebrew/test/cask/cli_spec.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/34831.

Fix cli default options.

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/test/diagnostic_spec.rb
Library/Homebrew/test/os/mac/diagnostic_spec.rb

Move some `brew doctor` checks that are pretty macOS specific so they are only run on macOS.

diagnostic: move some more macOS doctor checks.

---

Library/Homebrew/cask/lib/hbc/cli/style.rb
Library/Homebrew/cmd/style.rb
Library/Homebrew/utils/popen.rb

-----
Needed for https://github.com/Homebrew/brew/pull/2679  (https://github.com/Homebrew/brew/pull/2679#discussion_r118843467).

Use `XDG_CACHE_HOME` for RuboCop.

---

Library/Homebrew/cask/lib/hbc/cli/doctor.rb
Library/Homebrew/cmd/uninstall.rb
Library/Homebrew/utils/formatter.rb

Use `Formatter::pluralize` where possible.

---

Library/.rubocop.yml
Library/Homebrew/cask/lib/hbc/cli/internal_appcast_checkpoint.rb
Library/Homebrew/cmd/list.rb
Library/Homebrew/cmd/search.rb
Library/Homebrew/cmd/switch.rb
Library/Homebrew/debrew.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/edit.rb
Library/Homebrew/development_tools.rb
Library/Homebrew/diagnostic.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/extend/ARGV.rb
Library/Homebrew/extend/ENV/std.rb
Library/Homebrew/extend/os/mac/extend/ENV/std.rb
Library/Homebrew/extend/pathname.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_cellar_checks.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/keg.rb
Library/Homebrew/os/mac/architecture_list.rb
Library/Homebrew/requirements/java_requirement.rb
Library/Homebrew/rubocops/components_order_cop.rb
Library/Homebrew/sandbox.rb
Library/Homebrew/test.rb
Library/Homebrew/test/rubocops/formula_desc_cop_spec.rb
Library/Homebrew/utils.rb

Fix operator spacing.

---

Library/Homebrew/cask/lib/hbc/cli/info.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/25523.

Fix `brew cask info` for removed Casks.

---

Library/Homebrew/dev-cmd/audit.rb

CC @ilovezfs who talked about this.

audit: check pypi URLs

---

Library/Homebrew/missing_formula.rb

This avoids the user confusion on incomplete results seen in http://discourse.brew.sh/t/missing-formula-location/818/7

missing_formula: note on shallow clones.

---

Library/Homebrew/dev-cmd/release-notes.rb

release-notes: include PR author names.

---

Library/Homebrew/formula_versions.rb

-----
Do not load the same Formula twice.
https://github.com/Homebrew/brew/pull/2673

Refactor `FormulaVersions`.

---

Library/Homebrew/cmd/style.rb
Library/Homebrew/test/cmd/style_spec.rb

Fix `rubocop` in `brew audit`.

---

Library/Homebrew/os/mac/version.rb

-----
Even more Sierra than the current Sierra release.

mac/version: add High Sierra symbol

---

docs/Acceptable-Formulae.md

Remove duplicates repo from Acceptable formula doc

---

Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb
Library/Homebrew/cask/lib/hbc/cli/install.rb
Library/Homebrew/cask/lib/hbc/cli/search.rb
Library/Homebrew/cask/lib/hbc/scopes.rb
Library/Homebrew/test/cask/cli_spec.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/24924.

Fix parsing `--require-sha` and `HOMEBREW_CASK_OPTS`.

---

Library/Homebrew/brew.rb

Otherwise: you may be on an old enough version that we don't care.

brew: no issue report prompt unless autoupdating.

---

Library/Homebrew/dev-cmd/audit.rb

This makes using `HOMEBREW_CURL` significantly nicer as then the system `curl` (that, on old versions, sucks at SSL) can download a version of `curl` that it can build from source.
CC @ilovezfs @mistydemeo as we talked about this.

audit: ensure curl always has at least one HTTP url.

---

Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.high_sierra.bottle.tar.gz

Add symlink for High Sierra test bottle.

---

Library/Homebrew/brew.rb
Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/test/cask/cli_spec.rb
Library/Homebrew/utils.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/35448.

Fix `--language` option.

---

docs/Python-for-Formula-Authors.md

Remove reference to link_scripts.

---

Library/Homebrew/diagnostic.rb

-----
`git remote add origin ...` doesn’t work because there’s already a remote.

diagnostic: Fix suggested git remote commands

---

.gitignore

Added `/Library/Homebrew/bin` and `/Library/Homebrew/.npmignore` to gitignore

---

Library/Homebrew/cmd/switch.rb
Library/Homebrew/formula.rb
Library/Homebrew/test/formula_pin_spec.rb

-----
APFS does not sort lexicographically.

🔨  Fix sorting on APFS.

---

Library/Homebrew/formula_installer.rb

-----
See https://github.com/Homebrew/homebrew-core/issues/14857.
A formula's build-time dependencies' runtime requirements should be
treated as build-time requirements when we're pouring a bottle.
CC @MikeMcQuaid @Alyssais @JCount

formula_installer: make unsatisifed recursive build reqs non-fatal for bottles

---

Library/Homebrew/language/node.rb
Library/Homebrew/test/language/node_spec.rb

Added tests for language/node.rb

---

Library/Homebrew/test/language/java_spec.rb

-----
@mistydemeo Please review. Thanks! :)

[WIP] Added tests for language/java

---

Library/Homebrew/software_spec.rb

-----
See https://github.com/Homebrew/homebrew-test-bot/pull/14.

software_spec: define recursive deps and reqs

---

Library/Homebrew/os/mac/pkgconfig/10.13/libcurl.pc
Library/Homebrew/os/mac/xcode.rb

-----
Various changes per DP/Xcode/CLT updates released a couple days back.

High Sierra: update expected CLT/libcurl pkgconfig file.

---

Library/Homebrew/cask/lib/hbc/artifact/base.rb
Library/Homebrew/cask/lib/hbc/cask.rb
Library/Homebrew/cask/lib/hbc/cask_dependencies.rb
Library/Homebrew/cask/lib/hbc/cask_loader.rb
Library/Homebrew/cask/lib/hbc/checkable.rb
Library/Homebrew/cask/lib/hbc/download_strategy.rb
Library/Homebrew/cask/lib/hbc/dsl.rb
Library/Homebrew/cask/lib/hbc/dsl/depends_on.rb
Library/Homebrew/cask/lib/hbc/exceptions.rb
Library/Homebrew/cask/lib/hbc/installer.rb
Library/Homebrew/cask/lib/hbc/system_command.rb
Library/Homebrew/cask/lib/hbc/url.rb
Library/Homebrew/cask/lib/hbc/url_checker.rb
Library/Homebrew/cask/lib/hbc/utils.rb
Library/Homebrew/caveats.rb
Library/Homebrew/checksum.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/debrew.rb
Library/Homebrew/dependencies.rb
Library/Homebrew/dependency.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/extend/predicable.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/formula_support.rb
Library/Homebrew/global.rb
Library/Homebrew/resource.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/cask/depends_on_spec.rb

-----
Simplify some methods and classes, as well as add an `attr_predicate` helper.

Refactoring using `Forwardable` and `DelegateClass`.

---

docs/Installation.md

Fix a broken link

---

Library/Homebrew/cask/lib/hbc/cli/cleanup.rb

Also remove directories with `brew cask cleanup`.

---

Library/Homebrew/extend/fileutils.rb
Library/Homebrew/shims/super/make

-----
Updated version of #2495 - this should resolve the problems with that version. Was reminded when working in homebrew-portable again.
cc @xu-cheng - I believe this fixes the issue you noticed with that branch.

FileUtils.make: don't bypass superenv

---

docs/Acceptable-Formulae.md

- We no longer care about dupes, really
- Extend `.app` criteria to include GUI applications in general
- Note we want things to build with Clang
- Note we don't want users to have to faff too much

Acceptable-Formulae: general cleanup.

---

Library/Homebrew/os/mac/pkgconfig/10.13/sqlite3.pc
Library/Homebrew/os/mac/xcode.rb

High Sierra: updates for DB3 et al.

---

docs/Acceptable-Formulae.md
docs/README.md

fix link to Interesting-Taps-and-Forks.md

---

Library/Homebrew/extend/fileutils.rb
Library/Homebrew/shims/super/make

Reverts Homebrew/brew#2877
This caused https://github.com/Homebrew/homebrew-core/issues/15547

Revert "FileUtils.make: don't bypass superenv"

---

Library/Homebrew/dev-cmd/tests.rb

These issues were fixed by https://github.com/Homebrew/brew/pull/2872 and https://github.com/Homebrew/brew/pull/2823.

tests: unpin bundler.

---

Library/Homebrew/requirements/python_requirement.rb

-----
This avoids linkage to both system Python and Homebrew's python.

python_requirement: prefer Homebrew's Python

---

Library/Homebrew/cask/lib/hbc/cli/search.rb
Library/Homebrew/test/cask/cli/search_spec.rb
Library/Homebrew/test/spec_helper.rb
Library/Homebrew/test/support/helper/output_as_tty.rb

-----
Closes https://github.com/caskroom/homebrew-cask/issues/29596.

Output plain list when running `brew cask search` without a TTY.

---

Library/Homebrew/extend/os/linux/hardware/cpu.rb

cpu: fix SSE4 detection on Linux

---

Library/Homebrew/caveats.rb
Library/Homebrew/test/caveats_spec.rb

Increasing test coverage for caveats.rb

---

Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb

---
Clean up after each cask has been audited instead of cleaning up everything at the end.

Cleanup after each Cask.

---

Library/Homebrew/test/caveats_spec.rb

-----
@mansimarkaur, make sure to use `mktmpdir` in the future, otherwise the file will be created in the current directory.

Use `mktmpdir`.

---

Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb
Library/Homebrew/cask/lib/hbc/cli/zap.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/36162.

Fix trash script.

---

Library/Homebrew/formula_installer.rb
Library/Homebrew/requirement.rb
Library/Homebrew/test/formula_installer_spec.rb

This was the original, intended functionality before this was broken in fe117bf79b244c42b7e4049d353c3c003eae4880.
Fixes https://github.com/Homebrew/homebrew-core/issues/13680.

formula_installer: use default_formula for bottles

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/rubocops/extend/formula_cop.rb
Library/Homebrew/rubocops/urls_cop.rb
Library/Homebrew/test/rubocops/urls_cop_spec.rb

-----
#569 and continuation of #2932

audit: Port audit_urls strict rules to rubocop, add tests, autocorrect

---

Library/Homebrew/cask/lib/hbc/cask.rb
Library/Homebrew/cask/lib/hbc/cask_loader.rb
Library/Homebrew/compat/hbc/cask_loader.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/formula.rb
Library/Homebrew/tap.rb
Library/Homebrew/tap_constants.rb

-----
Should make https://github.com/Homebrew/brew/pull/2878 a bit easier.

Detect `Tap` in `CaskLoader`.

---

Library/Homebrew/cask/lib/hbc/download_strategy.rb

This was started in https://github.com/Homebrew/brew/pull/2568.

Fix parsing extension from URL.

---

Library/Homebrew/cask/lib/hbc/audit.rb
Library/Homebrew/cask/lib/hbc/cask_loader.rb
Library/Homebrew/cask/lib/hbc/container.rb
Library/Homebrew/cask/lib/hbc/container/criteria.rb
Library/Homebrew/cask/lib/hbc/container/directory.rb
Library/Homebrew/cask/lib/hbc/container/executable.rb
Library/Homebrew/cask/lib/hbc/container/svn_repository.rb
Library/Homebrew/cask/lib/hbc/download_strategy.rb
Library/Homebrew/cask/lib/hbc/dsl/appcast.rb
Library/Homebrew/cask/lib/hbc/system_command.rb
Library/Homebrew/cask/lib/hbc/url.rb
Library/Homebrew/cask/lib/hbc/verify/gpg.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/mirror.rb
Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/formulary.rb
Library/Homebrew/test/cask/download_strategy_spec.rb
Library/Homebrew/test/cask/dsl/appcast_spec.rb
Library/Homebrew/utils/curl.rb
Library/Homebrew/utils/github.rb

Refactor SVN and cURL download strategies.

---

Library/Homebrew/cask/lib/hbc/audit.rb
Library/Homebrew/cask/lib/hbc/cask_loader.rb
Library/Homebrew/cask/lib/hbc/container.rb
Library/Homebrew/cask/lib/hbc/container/criteria.rb
Library/Homebrew/cask/lib/hbc/container/directory.rb
Library/Homebrew/cask/lib/hbc/container/executable.rb
Library/Homebrew/cask/lib/hbc/container/svn_repository.rb
Library/Homebrew/cask/lib/hbc/download_strategy.rb
Library/Homebrew/cask/lib/hbc/dsl/appcast.rb
Library/Homebrew/cask/lib/hbc/system_command.rb
Library/Homebrew/cask/lib/hbc/url.rb
Library/Homebrew/cask/lib/hbc/verify/gpg.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/mirror.rb
Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/formulary.rb
Library/Homebrew/test/cask/download_strategy_spec.rb
Library/Homebrew/test/cask/dsl/appcast_spec.rb
Library/Homebrew/utils/curl.rb
Library/Homebrew/utils/github.rb

Let's try again. https://github.com/Homebrew/brew/pull/3018
Depends on and is depended on by https://github.com/Homebrew/homebrew-test-bot/pull/114.

Refactor download strategies.

---

Library/Homebrew/dev-cmd/audit.rb

audit: fix mismatch in versioned alias names in non-core taps

---

Library/Homebrew/os/mac/xcode.rb

mac/xcode: update expected Clang on 10.13

---

Library/Homebrew/utils/curl.rb

https://github.com/Linuxbrew/homebrew-developer/pull/60
Closes https://github.com/Homebrew/brew/issues/3041.

`curl_download`: Retry once on error `33`.

---

Library/Homebrew/formulary.rb
Library/Homebrew/test/formulary_spec.rb

Raise an exception when double loading a formula

---

Library/Homebrew/cask/lib/hbc/cli/search.rb
Library/Homebrew/utils/github.rb

Move fix from #3070 inside `GitHub` module.

---

Library/Homebrew/cask/lib/hbc/dsl/conflicts_with.rb
Library/Homebrew/cask/lib/hbc/exceptions.rb
Library/Homebrew/cask/lib/hbc/installer.rb
Library/Homebrew/test/cask/conflicts_with_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-conflicts-with.rb

Implement `conflicts_with :cask`.

---

Library/Homebrew/rubocops/patches_cop.rb
Library/Homebrew/rubocops/urls_cop.rb
Library/Homebrew/test/rubocops/patches_cop_spec.rb
Library/Homebrew/test/rubocops/urls_cop_spec.rb

- [] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
- [] Have you successfully run `brew tests` with your changes locally?
-----
https://github.com/Homebrew/brew/pull/2976#discussion_r131524468
`Homebrew #search_taps` test fails, when I run tests.

audit: In Cops and their tests convert all multiline strings to heredocs

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/test/download_strategies_spec.rb

-----
The changes in dc5a2c17 aren't fully formed. The array of arguments was appended to in the previously working code, but in the new code the string is appended to (so there's no space put between the arguments when passed to the shell.
`brew tests` fails a large number of tests without any changes, so I'm not going to go fix everything broken with it. My new test passes with the associated fix.

Fix curl --user flag being broken in dc5a2c17

---

Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/utils/curl.rb

Fix `pull`.

---

.github/ISSUE_TEMPLATE.md

Try to be even clearer that we need you to read this.

ISSUE_TEMPLATE: firm up language

---

Library/Homebrew/diagnostic.rb

Revert "Add check for HEAD ref in diagnostics"

---

Library/Homebrew/missing_formula.rb

-----
CC @fxcoudert.
Ref: https://github.com/Homebrew/homebrew-core/pull/17341

missing_formula: update for Pillow's brew demise.

---

Library/Homebrew/utils/github.rb

-----
Not sure whether this is the way you want to handle this problem but it's really darn irritating so here's a PR that handles it one way.
Fixes/hacks around: https://github.com/Homebrew/brew/pull/3086#issuecomment-324519156

github: limit PR search to Homebrew

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/rubocops/conflicts_cop.rb
Library/Homebrew/rubocops/extend/formula_cop.rb
Library/Homebrew/rubocops/lines_cop.rb
Library/Homebrew/test/rubocops/conflicts_cop_spec.rb
Library/Homebrew/test/rubocops/formula_desc_cop_spec.rb
Library/Homebrew/test/rubocops/lines_cop_spec.rb

-----
#569 and continuation of #2995 
Suggestions for any edge test cases are needed as I may not be aware of all of them.

audit: Port line_problems to rubocop and add tests part 3

---

Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/38486.

Fix uninstall with `:signal`.

---

Library/Homebrew/cask/lib/hbc/cli/internal_appcast_checkpoint.rb

-----
Fixes https://github.com/Homebrew/brew/commit/ef67b77d95c6cad9e1ba027189a44876119d1739#commitcomment-24243135 and closes https://github.com/caskroom/homebrew-cask/issues/38514.

Fix method name.

---

Library/Homebrew/cmd/irb.rb

Always load Cask in `brew irb`.

---

Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/38606.

Add missing `summarize` method.

---

Library/Homebrew/cmd/vendor-install.sh

Upgrade vendored Ruby to 2.3.3 for Linux.

---

Library/Homebrew/dev-cmd/audit.rb

audit: hack around El Capitan audit failure.

---

Library/Homebrew/dev-cmd/audit.rb

-----
https://github.com/Homebrew/brew/pull/3202 only skips them if homebrew/science is tapped.

audit: also skip homebrew/science duplicates found by search_taps

---

README.md

They host our physical hardware.

README: add Commsworld logo.

---

Library/Homebrew/extend/os/mac/keg_relocate.rb

Revert "keg_relocate: use correct number of arguments in call to change_install_name"

---

Library/Homebrew/extend/os/mac/keg_relocate.rb
Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/keg.rb
Library/Homebrew/os/mac/mach.rb

Revert "mach: Avoid reopening the file for relocation"

---

Library/Homebrew/test/os/mac/keg_spec.rb

Revert "Added tests for os/mac/keg"

---

Library/Homebrew/cask/lib/hbc/dsl/caveats.rb

-----
/cc @vitorgalvao @reitermarkus

Cask dsl caveats: bump java version to 9

---

Library/Homebrew/manpages/brew-cask.1.md
manpages/brew-cask.1
manpages/brew.1

-----
Fixes: https://github.com/caskroom/homebrew-cask/issues/31129
Add --language to various parts of manpage for brew-cask
Any feedback/criticism is appreciated :)

add --language to brew-cask manpage

---

Library/Homebrew/cask/lib/hbc/dsl.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/38593.

Fail if no default language is specified.

---

Library/Homebrew/locale.rb
Library/Homebrew/test/locale_spec.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/39061.

Support UN M.49 region codes.

---

Library/Homebrew/keg_relocate.rb

-----
Addresses https://github.com/Homebrew/brew/issues/3251

text_files: Skip the formula in .brew/formula.rb

---

Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb
Library/Homebrew/test/cask/artifact/uninstall_zap_shared_examples.rb

-----
Fixes https://github.com/Homebrew/brew/issues/2974#issuecomment-333296864.

Fix `brew tests` leaving last file in trash.

---

Library/Homebrew/cask/lib/hbc/artifact/pkg.rb

The `pkg` stanza has an option called `allow_untrusted`, which is supposed to cause `/usr/sbin/installer` to be called with the `-allowUntrusted` switch.
PR #3141 seems to have renamed the `pkg_install_opts` field to `options`. At the same time, it introduces an `options` parameter for the `run_installer` method, which shadows the `options` getter method, causing the `allow_untrusted` option to be silently ignored.
The issue affects just the `pkg` stanza because `Hbc::Artifact::Pkg` is the only artifact class that has an `options` method.
This PR removes the shadowing ~~by renaming the method parameters~~ by renaming the field to `stanza_options`; in one case, it uses ~~`ignored_install_options`~~ `_options` for a parameter name (instead of the more canonical `_`) for the sake of clarity. …

Unshadow `allow_untrusted` option for pkg artifact

---

Library/Homebrew/.rubocop.yml
Library/Homebrew/test/cask/cli/audit_spec.rb
Library/Homebrew/test/cask/cli/cat_spec.rb
Library/Homebrew/test/cask/cli/cleanup_spec.rb
Library/Homebrew/test/cask/cli/create_spec.rb
Library/Homebrew/test/cask/cli/doctor_spec.rb
Library/Homebrew/test/cask/cli/edit_spec.rb
Library/Homebrew/test/cask/cli/fetch_spec.rb
Library/Homebrew/test/cask/cli/home_spec.rb
Library/Homebrew/test/cask/cli/info_spec.rb
Library/Homebrew/test/cask/cli/install_spec.rb
Library/Homebrew/test/cask/cli/list_spec.rb
Library/Homebrew/test/cask/cli/options_spec.rb
Library/Homebrew/test/cask/cli/outdated_spec.rb
Library/Homebrew/test/cask/cli/reinstall_spec.rb
Library/Homebrew/test/cask/cli/search_spec.rb
Library/Homebrew/test/cask/cli/shared_examples/invalid_option.rb
Library/Homebrew/test/cask/cli/shared_examples/requires_cask_token.rb
Library/Homebrew/test/cask/cli/style_spec.rb
Library/Homebrew/test/cask/cli/uninstall_spec.rb
Library/Homebrew/test/cask/cli/zap_spec.rb
Library/Homebrew/test/cask/depends_on_spec.rb

Refactor `cask/cli` specs.

---

docs/Kickstarter-Supporters.md

- ~~Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).~~
-----

Update my name in Kickstarter-Supporters, add .mailmap

---

docs/Interesting-Taps-and-Forks.md

- [N/A] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
-----
Removed mention of two deprecated taps and added two other external maintained taps.

docs: update list of taps

---

Library/Homebrew/cask/lib/hbc/artifact/abstract_artifact.rb

-----
Refs: https://github.com/Homebrew/brew/pull/3267
Fixes `binary` running prior to `pkg`
> https://travis-ci.org/caskroom/homebrew-cask/builds/284640024
/cc @reitermarkus

Cask AbstractArtifact: fix install order

---

Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb

-----
Refs: 
- https://github.com/caskroom/homebrew-cask/pull/39391 
- https://travis-ci.org/caskroom/homebrew-cask/builds/284505240#L552
Allows `_audit_modified_casks ` to check Casks that have been renamed.

InternalAuditModifiedCask: audit renamed Casks

---

Library/.rubocop.yml
Library/Homebrew/cask/lib/hbc/container/dmg.rb
Library/Homebrew/cask/lib/hbc/system_command.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/39155.

Properly handle special characters in file names.

---

Library/Homebrew/cask/lib/hbc/system_command.rb

Refactor `SystemCommand`.

---

Library/Homebrew/utils/ruby.sh

-----
Fix the error:
```
/usr/local/Homebrew/Library/Homebrew/brew.sh: line 372: exec: : not found
```

setup-ruby-path: Ensure that Ruby is installed

---

docs/Checksum_Deprecation.md

Checksum_Deprecation: tweak phrasing/explanation/etc

---

Library/Homebrew/constants.rb

rubocop-cask: 0.15.1

---

Library/Homebrew/system_config.rb

This is the actual user path when env filtering is enabled.

system_config: get perl/ruby from HOMEBREW_PATH.

---

Library/Homebrew/brew.sh
Library/Homebrew/extend/fileutils.rb
Library/Homebrew/formula.rb
Library/Homebrew/test/utils_spec.rb
Library/Homebrew/utils.rb

- Use it in more places where it saves code
- Allow using symbolic keys for a cleaner interface
- Use `HOMEBREW_GEM_*` instead of `GEM_OLD_*`

Tweak use of with_env

---

Library/Homebrew/cask/lib/hbc/system_command.rb
Library/Homebrew/compat/hbc.rb
Library/Homebrew/compat/hbc/system_command.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/pull/39865.

Fix `SystemCommand` without arguments.

---

Library/Homebrew/rubocops/lines_cop.rb
Library/Homebrew/test/rubocops/lines_cop_spec.rb

-----
https://github.com/Homebrew/brew/pull/3382#issuecomment-340203380
@ilovezfs (or/and) @MikeMcQuaid  I think there are more, but I'm not sure which one 
Can you please checkout this PR locally and then run `brew audit --only-cops=FormulaAudit/Miscellaneous` and let me know which ones are false positives; I will update this PR with fixes.

lines_cop: Update regex patterns to prevent false positives

---

Library/Homebrew/os/mac/xquartz.rb

-----
I got rid of X11 locally about a year ago but I pulled these numbers from the `.pkg`. Figured they might as well be updated.

xquartz: add new versions + mark latest

---

Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/xcode.rb
docs/Xcode.md

Xcode 9.1 Updates.

---

CONTRIBUTING.md

Capitalized beginning of each bullet point to match style of README.md
-----

Capitalized words

---

Library/Homebrew/cask/lib/hbc/dsl/depends_on.rb

-----
Needed for a cleaner implementation of https://github.com/Homebrew/brew/pull/3258.

Refactor `DependsOn` with `DelegateClass`.

---

Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/extend/pathname.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/test/spec_helper.rb
Library/Homebrew/utils/curl.rb
bin/brew

We use these internally so let's map them to `HOMEBREW_` variables.

environment filtering: pass through TRAVIS vars.

---

completions/zsh/_brew_cask

-----
Both `outdated` and `reinstall` we're missing from the completion.

completions/zsh: Update `brew cask` completions.

---

Library/Homebrew/cmd/vendor-install.sh

-----
Suppress stderr unless `HOMEBREW_STDERR` is set.

vendor-install: Observe HOMEBREW_STDERR

---

Library/Homebrew/cask/lib/hbc/cli/internal_stanza.rb
Library/Homebrew/test/cask/cli/internal_stanza_spec.rb

improve 'brew cask _stanza' by checking for known stanzas

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

bump-formula-pr: fix for when hub isn't configured

---

Library/Homebrew/cask/lib/hbc/cli/doctor.rb

Cask doctor: add macOS & Java versions

---

Library/Homebrew/cask/lib/hbc/cli/install.rb

Installing casks is supported only on macOS

---

Library/Homebrew/cask/lib/hbc/system_command.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/40908.

Fix SystemCommand escaping.

---

Library/Homebrew/utils/analytics.sh

setup-analytics: Handle missing /proc/.../uuid

---

Library/Homebrew/dependency_collector.rb
Library/Homebrew/os/mac/xcode.rb
Library/Homebrew/requirements.rb
Library/Homebrew/test/dependency_collector_spec.rb

-----
Use these two requirements in DependencyCollector.
My primary intention for this PR is to install CVS and SVN when necessary on a Linux system.

Add CVSRequirement and SubversionRequirement

---

bin/brew

-----
Should also fix the cause for and the test failure in https://github.com/Homebrew/homebrew-command-not-found/pull/45.

Fix `Utils::Shell.parent`.

---

Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb
Library/Homebrew/cask/lib/hbc/dsl/caveats.rb

Only show `kext` caveat on High Sierra or above.

---

bin/brew

Whitelist `SUDO_ASKPASS` environment variable.

---

Library/Homebrew/cask/lib/hbc/cli.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/41398.

Fix external Cask commands.

---

Library/Homebrew/cmd/vendor-install.sh

vendor-install: Add ARM bottle for portable-ruby

---

Library/Homebrew/version/null.rb

version/null: add to_i method.

---

Library/Homebrew/extend/os/linux/hardware/cpu.rb
Library/Homebrew/extend/os/mac/hardware/cpu.rb
Library/Homebrew/hardware.rb

Hardware::CPU: Implement OS-agnostic methods

---

Library/Homebrew/test/utils/svn_spec.rb

Fix a test failure when svn is not installed

---

Library/Homebrew/extend/os/linux/system_config.rb

-----
Otherwise when the keg was installed but out-of-date, it would display "N/A".

config: Print the linked_version [Linux]

---

Library/Homebrew/test/utils/popen_spec.rb
Library/Homebrew/utils/popen.rb

-----
Ensure that `$CHILD_STATUS.success?` is false when the command does not exist.

Utils.popen_read: Nonexistent program should fail

---

Library/Homebrew/manpages/brew.1.md.erb
docs/Manpage.md
manpages/brew-cask.1
manpages/brew.1

Should have been in #3482 CC @RandomDSdevel.

Document HOMEBREW_FORCE_BREWED_CURL

---

Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb

-----
Add missing `to_s` to `each_resolved_path`.

Add missing `to_s`.

---

Library/Homebrew/extend/os/linux/system_config.rb
Library/Homebrew/os/linux/glibc.rb

config: Print host glibc version [Linux]

---

Library/Homebrew/brew.sh
bin/brew

This will ship as part of Homebrew 1.4.0.
Closes https://github.com/Homebrew/brew/issues/932

Default environment filtering to on for all users.

---

Library/Homebrew/caveats.rb

-----
Does what it says on the tin.

caveats: fix PKG_CONFIG_PATH nudge under env filtering

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

This is to address issue #3531
-----

Mentions how hub needs to be configured

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

- Be clearer about how URLs/tags/revisions/versions are specified in error messages.
- Give a better error message if `hub` isn't configured.
Followup from #3551.

bump-formula-pr: improve error messages.

---

Library/Homebrew/cmd/doctor.rb
docs/Manpage.md
manpages/brew.1

doctor: tell people not to file issues.

---

Library/Homebrew/brew.sh

Will merge just before 1.4.0 tag.

brew.sh: latest HOMEBREW_VERSION is 1.4.0

---

README.md

- Add links to more stuff people could contribute to
- Add back option for one-off donations (fixes #3565).

README: tweak contributing, donations sections.

---

Library/Homebrew/cask/lib/hbc/cli.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/41819.

Fix messed up parenthesis.
