Homebrew/brew

Library/Homebrew/language/python.rb

-----
It was added in https://github.com/Homebrew/legacy-homebrew/pull/37345 for a use case discussed in https://github.com/Homebrew/legacy-homebrew/pull/37340 that never seems to have actually emerged. I can find no reference of it ever having been used, despite it existing for 2+ years here.

python: remove package_available? logic

---

docs/New-Maintainer-Checklist.md

-----
- there are obligations on becoming a maintainer so firm these up a bit
- make clear there's a trial period after being invited to be a maintainer.

New-Maintainer-Checklist: make some tweaks.

---

Library/Homebrew/cask/lib/hbc/audit.rb

-----
https://github.com/Homebrew/brew/pull/3318 made changes to Cask and Formula `audit`, this reverts the changes that were made to Cask `audit` only.
cc @vitorgalvao @reitermarkus

Partially revert "Add audit check for URL schema"

---

Library/Homebrew/rubocops/text_cop.rb
Library/Homebrew/test/rubocops/text_cop_spec.rb

-----
CC @ilovezfs re https://github.com/Homebrew/homebrew-core/pull/19791#issuecomment-338984764.

go: various tweaks to recommendations

---

Library/Homebrew/brew.sh

-----
Move the use of git to determine HOMEBREW_VERSION below the definition of the function git.

brew.sh: Use shims/scm/git for HOMEBREW_VERSION

---

Library/Homebrew/development_tools.rb

-----
Use locate rather than which to search for clang or gcc.
locate searches both $HOMEBREW_PREFIX/bin and /usr/bin.

DevelopmentTools.installed?: Use locate

---

Library/Homebrew/shims/scm/git

Revert "shims/scm/git: Fix the search for brewed git"

---

Library/Homebrew/caveats.rb

-----
Can do a bunch of different things here but this seems like the simplest place to continue the discussion from https://github.com/Homebrew/homebrew-core/pull/21941.

caveats: correct completion/function paths for keg_only

---

Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/test/cask/cli_spec.rb

-----
Fixes https://github.com/Homebrew/brew/issues/3601.

cask: exit successfully when given no arguments.

---

Library/Homebrew/manpages/brew-cask.1.md
manpages/brew-cask.1

-----
Added initial documentation into [Library/Homebrew/manpages/brew-cask.1.md](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/manpages/brew-cask.1.md) for `brew cask upgrade`.

Add brew cask upgrade initial documentation

---

Library/Homebrew/manpages/brew-cask.1.md
manpages/brew-cask.1

cask manpage: upgrade

---

Library/Homebrew/language/python.rb

language/python: handle python@* in virtualenv_install_with_resources

---

Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/upgrade.rb
docs/Manpage.md
manpages/brew.1

To avoid user confusion e.g. #3606.

reinstall/upgrade: document use of options.

---

Library/Homebrew/official_taps.rb
Library/Homebrew/test/dev-cmd/tap_spec.rb
docs/How-To-Open-a-Homebrew-Pull-Request.md
docs/Interesting-Taps-and-Forks.md
docs/Migrating-A-Formula-To-A-Tap.md
docs/Python-for-Formula-Authors.md
docs/Troubleshooting.md

Deprecate Homebrew/homebrew-science

---

README.md

-----
Couple periods missing at the end of README.

add a few missing periods

---

Library/Homebrew/dev-cmd/audit.rb

This is a nicer experience than writing `Requirement`s by hand.

audit: allow env :std in custom taps.

---

Library/Homebrew/rubocops/extend/formula_cop.rb

e.g. match an array or symbol or string. CC @ilovezfs who mentioned this

formula_cop: match any values in hash match.

---

docs/Interesting-Taps-and-Forks.md

From the artist known as homebrew-science.

Interesting-Taps-and-Forks: add brewsci org taps.

---

Library/Homebrew/utils/curl.rb

Address some additional issues mentioned in #3624.

curl: handle more non-executable curl edge-cases.

---

Library/Homebrew/cask/lib/hbc/cli/doctor.rb

-----
cc @vitorgalvao @reitermarkus

cask doctor: sip status

---

Library/Homebrew/cmd/log.rb
Library/Homebrew/cmd/update-reset.sh
Library/Homebrew/cmd/update.sh
Library/Homebrew/download_strategy.rb
Library/Homebrew/gitconfig/.gitconfig
Library/Homebrew/tap.rb
Library/Homebrew/utils/git.rb

Git is a transport and storage mechanism for us so we don't want to allow arbitrary customisation of this due to user issues e.g. #3664 and #3561.
Fixes #3664.

Use Homebrew's gitconfig for various commands

---

Library/Homebrew/cask/lib/hbc/artifact/moved.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/42681

cask moved: check target writable for move_back

---

Library/Homebrew/utils.rb

Rather than just telling them to submit an issue as it's likely that as these folks will be able to submit a PR.

utils: tell developers to submit odeprecated PRs.

---

docs/Formula-Cookbook.md

Update some stuff that was deprecated or tweak wording.

Formula-Cookbook: various updates.

---

Library/Homebrew/compat/ENV/std.rb
Library/Homebrew/compat/ENV/super.rb
Library/Homebrew/compat/extend/string.rb
Library/Homebrew/compat/formula_support.rb
Library/Homebrew/compat/language/haskell.rb
Library/Homebrew/compat/utils/shell.rb
Library/Homebrew/formula_support.rb

These have all been deprecated/compat for a while.

Disable and add more deprecations.

---

README.md

README.md: secure two URLs

---

docs/Versions.md

Clarify further what's acceptable and what isn't.

Versions: update acceptable versioned formulae.

---

Library/Homebrew/cmd/linkapps.rb
Library/Homebrew/cmd/unlinkapps.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/compat/requirements.rb
Library/Homebrew/formula_support.rb
Library/Homebrew/test/cmd/linkapps_spec.rb
Library/Homebrew/test/cmd/unlinkapps_spec.rb
docs/Manpage.md
manpages/brew.1

Fix up various things I noticed (or were reported) since 1.5.0.

Deprecation fixes and cleanup

---

Library/Homebrew/diagnostic.rb

fix broken sentence

---

Library/Homebrew/cmd/fetch.rb
Library/Homebrew/patch.rb
Library/Homebrew/resource.rb
Library/Homebrew/test/patch_spec.rb
Library/Homebrew/test/patching_spec.rb
Library/Homebrew/test/resource_spec.rb

-----
Allow resource blocks to contain patch blocks so we can stop downloading
the resource patches as separate resources and applying them manually.

resource: allow patches to be applied

---

.travis.yml
Library/Homebrew/brew.sh
Library/Homebrew/dev-cmd/tap-new.rb
Library/Homebrew/utils.rb
Library/Homebrew/utils/ruby.sh

Read the docs and rethought bits of pieces to simplify, update and fix everything around the Travis CI build process.

.travis.yml: make configuration tweaks.

---

docs/External-Commands.md

Minor proposal

---

Library/Homebrew/cask/lib/hbc/cli/style.rb
Library/Homebrew/test/cask/cli/style_spec.rb

Fix `brew cask style` on Travis.

---

Library/Homebrew/cmd/--env.rb
Library/Homebrew/cmd/desc.rb
Library/Homebrew/cmd/doctor.rb
Library/Homebrew/cmd/gist-logs.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/list.rb
Library/Homebrew/cmd/outdated.rb
Library/Homebrew/cmd/readall.rb
Library/Homebrew/cmd/style.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/dev-cmd/linkage.rb
Library/Homebrew/dev-cmd/man.rb
docs/Brew-Test-Bot.md
docs/Interesting-Taps-and-Forks.md
docs/Manpage.md
manpages/brew-cask.1
manpages/brew.1

- [N/A] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
-----
Added more descriptions to the man page for command options not currently described and two more external taps, plus other random docs fixes.

docs: add more option descriptions

---

Library/Homebrew/cask/lib/hbc/installer.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/unpack.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/utils/git.rb

-----
I noticed a small inconsistency between `install` and `upgrade` commands. Note that `vim` is green while `gdb` is white.

Format identifiers in oh1

---

Library/Homebrew/os/mac/linkage_checker.rb

-----
Follows up on #2297 and https://github.com/Homebrew/homebrew-core/pull/23933#issuecomment-364633487.
This modifies `brew linkage` to separate out the "undeclared dependencies" in to two lists: an "indirect dependencies" list for linkage dependencies that are picked up transitively but not directly declared in the formula, and "undeclared dependencies" for those that are not in the recursive dependencies at all.
Before:
```
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula on ⇄ ad8a26413e]
$ brew linkage mldonkey
System libraries:
/usr/lib/libSystem.B.dylib
/usr/lib/libbz2.1.0.dylib
/usr/lib/libc++.1.dylib
/usr/lib/libcharset.1.dylib
/usr/lib/libiconv.2.dylib
/usr/lib/libz.1.dylib
Homebrew libraries:
/usr/local/opt/fontconfig/lib/libfontconfig.1.dylib (fontconfig) …
```

linkage_checker: Distinguish indirect deps from undeclared deps

---

Library/Homebrew/cask/lib/hbc/cli/doctor.rb

-----
Follow up to https://github.com/Homebrew/brew/pull/3631

cask doctor: check_cached_downloads

---

Library/Homebrew/brew.sh

-----
Closes https://github.com/caskroom/homebrew-cask/issues/43403.

Auto-update on `brew cask install/upgrade`.

---

Library/Homebrew/brew.sh

Result of discussion in #3809.

brew.sh: use system curl on Linux where possible.

---

Library/Homebrew/cask/lib/hbc/artifact/moved.rb
Library/Homebrew/test/cask/cli/reinstall_spec.rb
Library/Homebrew/test/cask/cli/uninstall_spec.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/42112 ~~(maybe)~~
cc @reitermarkus

cask move_back: copy / delete

---

docs/.well-known/acme-challenge/CgQNmjNTd6fUriinp4XpuRI5PBGp7zEXbEEsQceSD0k
docs/Common-Issues.md
docs/Formula-Cookbook.md
docs/Manpage.md
docs/New-Maintainer-Checklist.md
docs/_config.yml
docs/_layouts/base.html

- Remove no longer needed `acme-challenge` file
- Set title, description, social image, logo, etc. for SEO
- Cleanup `_config.yml`
- Import latest `_layouts/base` from https://brew.sh

docs.brew.sh updates

---

CONTRIBUTING.md
Library/Homebrew/README.md
Library/Homebrew/cmd/analytics.rb
Library/Homebrew/cmd/help.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/tap-info.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/dev-cmd/create.rb
Library/Homebrew/formula.rb
Library/Homebrew/manpages/brew.1.md.erb
Library/Homebrew/missing_formula.rb
Library/Homebrew/os.rb
Library/Homebrew/utils/analytics.rb
README.md
manpages/brew.1

Use more docs.brew.sh short links

---

Library/Homebrew/extend/os/mac/system_config.rb
Library/Homebrew/system_config.rb

-----
Adapting java detection code to work on Linux.
Moved current implementation to `extend/os/mac/system_config.rb`.
New default is based on `java -version` and works on both platforms.
CC @sjackman

Cross-platform java detection

---

.travis.yml
Library/Homebrew/dev-cmd/tap-new.rb

travis.yml: fix bundler caching.

---

Library/Homebrew/extend/ENV.rb
Library/Homebrew/test/ENV_spec.rb

Add tests for ENV#clear_sensitive_environment!

---

Library/Homebrew/migrator.rb
Library/Homebrew/test/cmd/migrate_spec.rb

- Make it clearer what the migrator is doing and why
- Recommend an unconditional brew upgrade

migrator: tweak more messaging.

---

Library/Homebrew/cmd/info.rb

This makes a lot more sense than sorting alphabetically by commit hash,
the previous behaviour.
-----

info: sort HEAD keys by install date

---

bin/brew

My guess is this will allow code coverage to be submitted again.

brew: pass through `TRAVIS_` variables.

---

Library/Homebrew/dev-cmd/create.rb

-----
- Fix indentation oddities
- Add empty lines where we expect them in submitted formulae

Fix style in `brew create`-generated formulae

---

Library/Homebrew/build.rb

-----
Fix #3883
Revert 2fb5ead38a7632ff6f941909474767883a9e0252
I'm not sure on how to write tests for it without introducing a new fixture Formula with deps layout needed for test.

build: do not skip runtime deps of buildtime deps

---

Library/Homebrew/constants.rb

-----
Removed accidentally committed debug statement and disabled `Security/Open`.

Update `rubocop-cask` to 0.17.3.

---

Library/Homebrew/keg.rb

Fix the issue described in https://github.com/Homebrew/homebrew-core/pull/25399#issuecomment-374019375.

keg: delete __pycache__ directory.

---

Library/Homebrew/cask/lib/hbc/dsl/caveats.rb
Library/Homebrew/extend/os/mac/requirements/java_requirement.rb

-----
JDK10 General Availability: 20th March

java_requirement, cask dsl caveats: java 10

---

Library/Homebrew/build.rb

Revert "build: do not skip runtime deps of buildtime deps"

---

Library/Homebrew/tab.rb

Use some newer Ruby syntax and improve readability.

tab: cleanup various methods.

---

Library/Homebrew/cask/lib/hbc/cli/doctor.rb

-----
cc @vitorgalvao 
```
==> Environment Variables
HOMEBREW_CASK_OPTS="--appdir=~/Applications --fontdir=/Library/Fonts"
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

cask doctor: add homebrew_cask_opts

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/formulary.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/download_strategies_spec.rb

Take just the bottle changes from https://github.com/Homebrew/brew/pull/3841 and get it into a mergeable state.

Allow bottles to use any DownloadStrategy

---

Library/Homebrew/dev-cmd/edit.rb

edit: Use Parser to parse args

---

Library/Homebrew/build.rb
Library/Homebrew/cmd/deps.rb
Library/Homebrew/cmd/uses.rb
Library/Homebrew/dependable.rb
Library/Homebrew/dependencies.rb
Library/Homebrew/formula_installer.rb

Reuse more code to avoid errors due to duplication.

Refactor dependencies usage

---

Library/Homebrew/dev-cmd/man.rb

man: Use Parser to parse args

---

Library/Homebrew/cli_parser.rb
Library/Homebrew/dev-cmd/irb.rb
Library/Homebrew/extend/ARGV.rb
Library/Homebrew/test/cli_parser_spec.rb
Library/Homebrew/utils/env.rb

irb: Use Parser to parse args

---

Library/Homebrew/dev-cmd/pull.rb

pull: Use Parser to parse args

---

Library/Homebrew/dev-cmd/update-test.rb

update-test: Use Parser to parse args

---

Library/Homebrew/cask/lib/hbc/audit.rb
Library/Homebrew/test/cask/audit_spec.rb

cask audit: various

---

Library/Homebrew/cask/lib/hbc/audit.rb
Library/Homebrew/test/cask/audit_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/with-allow-untrusted.rb

-----
cc @vitorgalvao @reitermarkus

cask audit: check for allow_untrusted within caskroom taps

---

Library/Homebrew/cask/lib/hbc/audit.rb
Library/Homebrew/test/cask/audit_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/github-with-appcast.rb
Library/Homebrew/test/support/fixtures/cask/Casks/github-without-appcast.rb

cask audit: check for appcast if the cask uses github releases

---

Library/Homebrew/cask/lib/hbc/audit.rb
Library/Homebrew/test/cask/audit_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/latest-with-appcast.rb

cask audit: check for :latest with appcast

---

Library/Homebrew/test/cask/audit_spec.rb

-----
Follow up to https://github.com/Homebrew/brew/pull/3981

cask audit_spec: rspec auto-corrects

---

Library/Homebrew/cli_parser.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/test/cli_parser_spec.rb

cli_parser: Add :quiet, :verbose, :debug common switches

---

Library/Homebrew/constants.rb

Update to RuboCop 0.54

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: update virtualenv to 15.2.0

---

Library/Homebrew/manpages/brew.1.md.erb
docs/Manpage.md
manpages/brew-cask.1
manpages/brew.1

Address the confusion in #4015.

Note environment variables need to have values.

---

docs/FAQ.md
docs/Installation.md

Make some miscellaneous updates to stuff I noticed was wrong.

docs: update FAQ and Installation.

---

Library/Homebrew/cli_parser.rb
Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/dev-cmd/update-test.rb
Library/Homebrew/test/cli_parser_spec.rb

-----
https://github.com/Homebrew/brew/pull/3987#discussion_r181551214
cc @ilovezfs

cli_parser: Refactor required argument for flag to '='

---

Library/Homebrew/constants.rb

---
Fixes https://github.com/caskroom/homebrew-cask/issues/44190.

Update `rubocop-cask` to 0.18.1.

---

Library/Homebrew/dev-cmd/audit.rb

-----
We almost always remove the HEAD spec from new formulae.

audit: new formulae should not have a HEAD spec

---

Library/Homebrew/cask/lib/hbc/metadata.rb
Library/Homebrew/cli_parser.rb
Library/Homebrew/constants.rb
Library/Homebrew/formula.rb
Library/Homebrew/keg.rb

RuboCop 0.55.0.

---

Library/Homebrew/download_strategy.rb

✅ Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
✅ Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
✅ Have you added an explanation of what your changes do and why you'd like us to include them? **Fixes #4087**
❌ Have you written new tests for your changes?
✅ Have you successfully run `brew style` with your changes locally?
✅ Have you successfully run `brew tests` with your changes locally?

AbstractDownloadStrategy#safe_system : Don't splat 2nd arg to ErrorDuringExecution::new

---

Library/Homebrew/formula.rb

Otherwise the ordering varies based on the filesystem.

formula: sort aliases in to_hash.

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb

-----
Refs https://github.com/Homebrew/brew/pull/4068#discussion_r181552125.
Closes https://github.com/Homebrew/brew/pull/4103.

Fix `MissingFormula` namespacing.

---

README.md

-----
When pointing to files within the repository, it is possible to use just the relative path to the file. Benefit: when browsing files in personal fork users won't be redirected to Homebrew/brew

Shorten some links in README.md

---

Library/Homebrew/rubocops/components_order_cop.rb
Library/Homebrew/test/rubocops/components_order_cop_spec.rb

-----
Also whitelist [`aspell`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/aspell.rb)

components_order_cop: make non-strict

---

Library/Homebrew/rubocops/urls_cop.rb
Library/Homebrew/test/rubocops/urls_cop_spec.rb

urls_cop pypiurls: make non-strict

---

Library/Homebrew/rubocops/components_redundancy_cop.rb
Library/Homebrew/test/rubocops/components_redundancy_cop_spec.rb

components_redundancy_cop: make non-strict

---

docs/Acceptable-Formulae.md

Address comments in https://github.com/Homebrew/brew/commit/27ec9dae5fa4c2c5b19f8bfafaefbdbb3e9a9c8c

docs/Acceptable-Formulae: address feedback.

---

Library/Homebrew/linkage_checker.rb

Fix upgrades of formulae with the same name in multiple taps.
As reported by @ilovezfs in https://github.com/Homebrew/brew/pull/3789#issuecomment-384890624
CC @ilovezfs for testing and review.

linkage_checker: correctly handle multiple taps.

---

Library/Homebrew/rubocops/components_order_cop.rb

-----
https://github.com/Homebrew/homebrew-core/pull/27153

components_order_cop: add post_install

---

Library/Homebrew/cask/lib/hbc/exceptions.rb

Fix CaskAlreadyCreatedError message output

---

README.md
docs/Manpage.md
manpages/brew.1

And thanks for all the ~fish~ commits, PRs and review! <3

README: goodbye Alyssa!

---

Library/Homebrew/cli_parser.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/test/cli_parser_spec.rb

bump-formula-pr: Use Parser to parse args

---

completions/bash/brew
completions/zsh/_brew

-----
These were deleted in cffa5a9864e771f19231537b812b9b32a1160be0.

Remove completions for (un)linkapps commands

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

This shadows the Homebrew variable so let's rename it for now so that `--force` works again.

bump-formula-pr: rename @args.

---

Library/Homebrew/cmd/vendor-install.sh

vendor-install: Add portable-ruby bottle for ARM

---

.github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md
docs/Troubleshooting.md

Depends on changes in https://github.com/Homebrew/homebrew-core/pull/27563.

Use new GitHub issue template format

---

Library/Homebrew/cask/lib/hbc/artifact/moved.rb
Library/Homebrew/cask/lib/hbc/cli/zap.rb
Library/Homebrew/manpages/brew-cask.1.md
manpages/brew-cask.1

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/46466

Fix `zap --force` for uninstalled casks

---

.github/ISSUE_TEMPLATE.md

-----
Basic template for when people choose "Open a regular issue"

add .github/issue_template.md

---

.github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md

reproducible-bug-report.md: update cask url

---

Library/Homebrew/cask/lib/hbc/cli/upgrade.rb

-----
Fixes https://github.com/caskroom/homebrew-cask/issues/46403

cask upgrade: ensure cache exists

---

Library/Homebrew/cask/lib/hbc.rb

Remove unused `include Utils`.

---

Library/Homebrew/brew.rb
Library/Homebrew/brew.sh
Library/Homebrew/cmd/--version.rb
Library/Homebrew/global.rb

-----
`time brew --version` is the same before and after.

Move `--version` logic into `cmd/--version.rb`.

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: update virtualenv to 16.0.0

---

Library/Homebrew/extend/git_repository.rb
Library/Homebrew/utils.rb

-----
Use the `chdir:` option of `Kernel.exec` instead.

Get rid of unnecessary `cd`s.

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/rubocops/options_cop.rb
Library/Homebrew/test/rubocops/options_cop_spec.rb

audit: new formulae should not have options

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/compat/tap.rb
Library/Homebrew/tap.rb
Library/Homebrew/test/cmd/update-report_spec.rb
Library/Homebrew/test/spec_helper.rb

Activate Homebrew-Cask tap migration.

---

Library/Homebrew/compat/tap.rb

Reset `repo_var` so it actually is re-computed.

---

.github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md
Library/Homebrew/cask/lib/hbc/audit.rb
Library/Homebrew/cask/lib/hbc/cli/search.rb
Library/Homebrew/cask/lib/hbc/dsl/caveats.rb
Library/Homebrew/cask/lib/hbc/locations.rb
Library/Homebrew/cask/lib/hbc/utils.rb
Library/Homebrew/cmd/search.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/manpages/brew-cask.1.md
Library/Homebrew/manpages/brew.1.md.erb
Library/Homebrew/missing_formula.rb
Library/Homebrew/requirements/java_requirement.rb
Library/Homebrew/test/cask/cli_spec.rb
Library/Homebrew/test/cask/dsl_spec.rb
Library/Homebrew/test/cmd/cask_spec.rb
Library/Homebrew/test/cmd/search_spec.rb
Library/Homebrew/test/spec_helper.rb
completions/bash/brew
completions/zsh/_brew_cask
docs/Acceptable-Formulae.md
docs/Formula-Cookbook.md
docs/Manpage.md
docs/Troubleshooting.md
manpages/brew-cask.1
manpages/brew.1

-----
Accidentally pushed https://github.com/Homebrew/brew/pull/4194 to `master` instead of rebasing.

Update Homebrew-Cask references.

---

Library/Homebrew/tap_constants.rb

Update Cask tap regex.

---

Library/Homebrew/test/cache_store_spec.rb
Library/Homebrew/test/spec_helper.rb

Fix `rspec` deprecations.

---

Library/Homebrew/cask/lib/hbc/caskroom.rb

-----
Closes https://github.com/Homebrew/homebrew-cask/issues/47617.

Fall back to `CaskLoader.load` to get a better error message.

---

Library/Homebrew/cmd/search.rb
Library/Homebrew/compat/tap.rb
Library/Homebrew/tap.rb

----
Addresses https://github.com/Homebrew/brew/pull/4210#discussion_r190975988 and https://github.com/Homebrew/brew/pull/4209#discussion_r190977979.

Refactoring

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

bump-formula-pr: improve bad argument handling.

---

Library/Homebrew/cask/lib/hbc/artifact/moved.rb

-----
Fixes https://github.com/Homebrew/brew/issues/4244.

Moving and copying must succeed.

---

Library/Homebrew/cli_parser.rb
Library/Homebrew/cmd/list.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/dev-cmd/edit.rb
Library/Homebrew/dev-cmd/irb.rb
Library/Homebrew/dev-cmd/man.rb
Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/dev-cmd/release-notes.rb
Library/Homebrew/dev-cmd/tests.rb
Library/Homebrew/dev-cmd/update-test.rb
Library/Homebrew/test/cli_parser_spec.rb

-----
https://github.com/Homebrew/brew/pull/3987#issuecomment-386190815

cli: Store parsed args in Homebrew.args and access @args everywhere else

---

Library/Homebrew/formula.rb

Ensure that all the necessary tools are accessible.
Fixes #4249.

Formula#update_head_version: fix PATH.

---

Library/Homebrew/rubocops/options_cop.rb
Library/Homebrew/test/rubocops/options_cop_spec.rb

options_cop: formula -> formulae

---

Library/Homebrew/test/dev-cmd/audit_spec.rb

Fix code style in `audit` spec.

---

Library/Homebrew/dev-cmd/linkage.rb

linkage: Use Parser to parse args

---

Library/Homebrew/dev-cmd/create.rb
Library/Homebrew/formula_creator.rb

-----
#1860
And also move `FormulaCreator` class inside Homebrew module

create: Use Parser to parse args

---

completions/zsh/_brew_cask

-----
Adds zsh completion for `brew cask upgrade`.
Fixes #4282.
Closes #4283.

zsh completions: add brew cask upgrade

---

Library/Homebrew/missing_formula.rb

-----
`haskell-platform` cask has been removed https://github.com/Homebrew/homebrew-cask/pull/47908

missing_formula: update haskell-platform message

---

Library/Homebrew/dev-cmd/audit.rb

-----
Follow up to https://github.com/Homebrew/brew/pull/4303

audit: fix typo

---

Library/Homebrew/cask/lib/hbc.rb
Library/Homebrew/cask/lib/hbc/cache.rb
Library/Homebrew/cask/lib/hbc/caskroom.rb
Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb
Library/Homebrew/cask/lib/hbc/cli/audit.rb
Library/Homebrew/cask/lib/hbc/cli/cleanup.rb
Library/Homebrew/cask/lib/hbc/cli/doctor.rb
Library/Homebrew/cask/lib/hbc/cli/fetch.rb
Library/Homebrew/cask/lib/hbc/cli/install.rb
Library/Homebrew/cask/lib/hbc/cli/internal_appcast_checkpoint.rb
Library/Homebrew/cask/lib/hbc/cli/internal_audit_modified_casks.rb
Library/Homebrew/cask/lib/hbc/cli/list.rb
Library/Homebrew/cask/lib/hbc/cli/upgrade.rb
Library/Homebrew/cask/lib/hbc/download_strategy.rb
Library/Homebrew/cask/lib/hbc/installer.rb
Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb

---
Move `Hbc.init` logic into more specific places.

Remove `Hbc.init`.

---

Library/Homebrew/rubocops/dependency_order_cop.rb
Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb

-----
Fixes https://github.com/Homebrew/homebrew-core/pull/28873.

Support constants in `DependencyOrder` cop.

---

completions/zsh/_brew

-----
Expands the zsh completion for `brew style` to complete file names as well as formula names, since they're valid arguments. For use with #4058.

brew style zsh completion: complete files

---

Library/Homebrew/.simplecov

Refactor `.simplecov`.

---

Library/Homebrew/brew.sh
Library/Homebrew/dev-cmd/tests.rb

This seems stable on CI so I think we can expose it to more people.
-----

brew.sh: enable linkage cache for developers.

---

Library/Homebrew/cask/lib/hbc/system_command.rb
Library/Homebrew/rubocops/extend/formula_cop.rb
Library/Homebrew/test/cask/download_strategy_spec.rb
Library/Homebrew/test/cask/dsl_spec.rb
Library/Homebrew/test/cask/pkg_spec.rb
Library/Homebrew/test/cask/system_command_spec.rb
Library/Homebrew/utils/tty.rb

-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/44835.

Fix `sudo` “Sorry, try again.” delay.

---

Library/Homebrew/cask/lib/hbc/dsl/version.rb
Library/Homebrew/test/cask/dsl/version_spec.rb

cask dsl versions: add minor_patch

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/extend/os/mac/formula_cellar_checks.rb
Library/Homebrew/rubocops/lines_cop.rb
Library/Homebrew/test/version_spec.rb
Library/Homebrew/version.rb

-----
As discussed in https://github.com/Homebrew/homebrew-core/pull/29040#issuecomment-397704661, this is needed for bottles that pin a specific version of Go as their dependency.
I'm happy to write tests, if that's required for a trivial change like this, and if there are tests covering this code path already.

Ignore any version of Go, when it is a dependency of a bottle

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/resource.rb

Revert "Fix SVN downloads of versioned formula by munging directory names"

---

Library/Homebrew/brew.sh

As of #4377 this is no longer used.
-----

brew.sh: remove unused variable.

---

Library/Homebrew/cask/lib/hbc/cask.rb
Library/Homebrew/cmd/search.rb
Library/Homebrew/compat/hbc/cli/search.rb
docs/Manpage.md
manpages/brew.1

-----
Listing all casks is needed for auto-completion, for example.
https://github.com/Homebrew/brew/issues/4254#issuecomment-399608100

Readd functionality to list all casks.

---

Library/Homebrew/rubocops/dependency_order_cop.rb

- [] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/homebrew/pull/49031).
-----
https://github.com/Homebrew/brew/issues/4395
cc @ilovezfs

DependencyOrder: Fix var initialization bug

---

Library/Homebrew/debrew.rb

Remove unneeded RuboCop comment.

---

Library/Homebrew/install.rb

This will be set if e.g. pinned packages aren't being upgraded.
Fixes #4388.
-----

install: don't exit on Homebrew.failed?

---

Library/Homebrew/test/Gemfile.lock
Library/Homebrew/test/support/lib/config.rb

 Update `Gemfile.lock` and use `Pathname#/`.

---

Library/Homebrew/cask/lib/hbc/audit.rb
Library/Homebrew/test/cask/audit_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/devmate-with-appcast.rb
Library/Homebrew/test/support/fixtures/cask/Casks/devmate-without-appcast.rb
Library/Homebrew/test/support/fixtures/cask/Casks/hockeyapp-with-appcast.rb
Library/Homebrew/test/support/fixtures/cask/Casks/hockeyapp-without-appcast.rb

-----
~~I need to fix the cask audit failures before this is merged.~~
Audit failures are fixed.

cask audit: check for devmate and hockeyapp appcasts

---

Library/Homebrew/dev-cmd/audit.rb

-----
And also disallow unstable specs for new formulae.
Mentioned in https://github.com/Homebrew/brew/pull/4408#issuecomment-401748629
cc @ilovezfs

audit: disallow unstable specs for versioned formulae

---

.travis.yml

travis.yml: update xcode to 9.4

---

Library/Homebrew/cask/lib/hbc/verify/checksum.rb
Library/Homebrew/extend/pathname.rb
Library/Homebrew/test/cask/verify/checksum_spec.rb

Remove unused `incremental_hash` method.

---

Library/Homebrew/cask/lib/hbc/system_command.rb
Library/Homebrew/test/cask/system_command_result_spec.rb
Library/Homebrew/test/spec_helper.rb

-----
Simplify and refactor `Hbc::SystemCommand::Result#plist`.

Simplify `Hbc::SystemCommand::Result#plist`.

---

Library/Homebrew/tab.rb
Library/Homebrew/test/tab_spec.rb

This should make it easier to debug and resolve things like #4439.
-----

tab: if parsing JSON fails output the filename.

---

Library/Homebrew/extend/os/mac/diagnostic.rb

And be even more explicit whose problem it is when things are broken.
-----

diagnostic: be clearer about what we support.

---

Library/Homebrew/extend/ENV/shared.rb
Library/Homebrew/extend/ENV/super.rb
Library/Homebrew/extend/os/mac/extend/ENV/super.rb

-----
I don't see anything wrong with having spaces (the default separator) in `HOMEBREW_CCCFG`, but for the sake of consistency....

Properly append values to HOMEBREW_CCCFG

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/extend/os/keg_relocate.rb
Library/Homebrew/extend/os/linux/keg_relocate.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/keg_relocate.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb
Library/Homebrew/test/formula_installer_bottle_spec.rb
Library/Homebrew/test/formulary_spec.rb
Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Library/Homebrew/utils/popen.rb

Ensure patchelf is installed to pour bottles on Linux
cmd/bottle: Ensure patchelf is installed on Linux
-----

Relocate bottles on Linux using patchelf

---

Library/Homebrew/dev-cmd/audit.rb

-----
A belated follow up to https://github.com/Homebrew/brew/pull/4170
cc @ilovezfs

audit: check for optional and recommended requirements on new formulae

---

Library/Homebrew/os/mac/xcode.rb

-----
This has been available for over a week now so it's probably safe to go ahead and nudge it onto users for consistency.

xcode: update expected Clang on 10.14

---

Library/Homebrew/requirement.rb

Addresses comments in #4465.
-----

requirement: add mktemp function.

---

Library/Homebrew/formulary.rb

This makes formulae unreadable.
See https://discourse.brew.sh/t/error-in-mpfr-2-formula/2575.
-----

formulary: handle missing methods.

---

Library/Homebrew/test/spec_helper.rb
Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb

---
Fixes random test failures.

Clear `Tap` cache before each example.

---

Library/Homebrew/cask/lib/hbc/artifact/nested_container.rb
Library/Homebrew/cask/lib/hbc/container.rb
Library/Homebrew/cask/lib/hbc/container/air.rb
Library/Homebrew/cask/lib/hbc/container/base.rb
Library/Homebrew/cask/lib/hbc/container/bzip2.rb
Library/Homebrew/cask/lib/hbc/container/cab.rb
Library/Homebrew/cask/lib/hbc/container/dmg.rb
Library/Homebrew/cask/lib/hbc/container/executable.rb
Library/Homebrew/cask/lib/hbc/container/generic_unar.rb
Library/Homebrew/cask/lib/hbc/container/gpg.rb
Library/Homebrew/cask/lib/hbc/container/gzip.rb
Library/Homebrew/cask/lib/hbc/container/lzma.rb
Library/Homebrew/cask/lib/hbc/container/naked.rb
Library/Homebrew/cask/lib/hbc/container/otf.rb
Library/Homebrew/cask/lib/hbc/container/pkg.rb
Library/Homebrew/cask/lib/hbc/container/rar.rb
Library/Homebrew/cask/lib/hbc/container/self_extracting_executable.rb
Library/Homebrew/cask/lib/hbc/container/seven_zip.rb
Library/Homebrew/cask/lib/hbc/container/sit.rb
Library/Homebrew/cask/lib/hbc/container/svn_repository.rb
Library/Homebrew/cask/lib/hbc/container/tar.rb
Library/Homebrew/cask/lib/hbc/container/ttf.rb
Library/Homebrew/cask/lib/hbc/container/xar.rb
Library/Homebrew/cask/lib/hbc/container/xz.rb
Library/Homebrew/cask/lib/hbc/container/zip.rb
Library/Homebrew/cask/lib/hbc/installer.rb

-----
Use same signatures for unpack strategies and containers.

Change `Container::me?` to `Container::can_extract?`.

---

Library/Homebrew/unpack_strategy.rb

-----
Add support for LuaRocks packages and Microsoft Office documents so they don't get treated as ZIPs and don't need `:nounzip`.

Add two new unpack strategies.

---

Library/Homebrew/test/unpack_strategy_spec.rb
Library/Homebrew/unpack_strategy.rb

-----
Allow extracting nested archives.

Add support for nested archives.

---

Library/Homebrew/cask/lib/hbc/installer.rb

-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/49711.

Move error to the right place.

---

Library/Homebrew/cask/lib/hbc/artifact/nested_container.rb
Library/Homebrew/cask/lib/hbc/container/air.rb
Library/Homebrew/cask/lib/hbc/container/base.rb
Library/Homebrew/cask/lib/hbc/container/bzip2.rb
Library/Homebrew/cask/lib/hbc/container/cab.rb
Library/Homebrew/cask/lib/hbc/container/dmg.rb
Library/Homebrew/cask/lib/hbc/container/generic_unar.rb
Library/Homebrew/cask/lib/hbc/container/gpg.rb
Library/Homebrew/cask/lib/hbc/container/gzip.rb
Library/Homebrew/cask/lib/hbc/container/lzma.rb
Library/Homebrew/cask/lib/hbc/container/naked.rb
Library/Homebrew/cask/lib/hbc/container/rar.rb
Library/Homebrew/cask/lib/hbc/container/seven_zip.rb
Library/Homebrew/cask/lib/hbc/container/svn_repository.rb
Library/Homebrew/cask/lib/hbc/container/tar.rb
Library/Homebrew/cask/lib/hbc/container/xar.rb
Library/Homebrew/cask/lib/hbc/container/xz.rb
Library/Homebrew/cask/lib/hbc/container/zip.rb
Library/Homebrew/cask/lib/hbc/installer.rb
Library/Homebrew/test/cask/container/naked_spec.rb
Library/Homebrew/test/cask/installer_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/container-bzip2.rb

-----
Further assimilate `Container`s with `UnpackStrategy`.

Assimilate `Container`s with `UnpackStrategy`.

---

Library/Homebrew/download_strategy.rb

-----
Fixes https://github.com/Homebrew/brew/issues/4492.

Use `extract_nestedly` for staging.

---

.github/PULL_REQUEST_TEMPLATE.md

Use non-legacy test example in PR template.

---

Library/Homebrew/formula.rb

formula: handle unavailable missing formulae.

---

Library/Homebrew/brew.rb
Library/Homebrew/config.rb
Library/Homebrew/dev-cmd/ruby.rb
Library/Homebrew/dev-cmd/test.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/global.rb
Library/Homebrew/test/spec_helper.rb
Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Library/Homebrew/test/support/lib/config.rb

-----
Move setup of `$LOAD_PATH` into `global` so we only have to do it once.

Refactor `$LOAD_PATH`.

---

Library/Homebrew/extend/pathname.rb

Revert "Explicitly chmod exec script files"

---

Library/Homebrew/unpack_strategy.rb

-----
Fixes 
https://github.com/Homebrew/homebrew-core/pull/30239#issuecomment-406084035.

Don't pass down basename when extracting nestedly.

---

Library/Homebrew/cask/lib/hbc/container/rar.rb

-----
https://github.com/Homebrew/brew/pull/4513

fix cask rar containers

---

Library/Homebrew/unpack_strategy.rb

-----
Fixes 
https://github.com/Homebrew/brew/commit/589c5b4e8dc4fab625868672d138e46290b19ecf#commitcomment-29783935.

Fix missing `super`.

---

Library/Homebrew/dev-cmd/bottle.rb
docs/Manpage.md
manpages/brew.1

bottle: add --json and --merge docs.

---

Library/Homebrew/dev-cmd/audit.rb

This should help debug when this fails to be created.
-----

audit: output new formula issue comment failure message.

---

Library/Homebrew/test/.codecov.yml
Library/Homebrew/unpack_strategy/cab.rb

-----
Fixes https://github.com/Homebrew/brew/pull/4541#issuecomment-408058867.

Don’t match `MZ` for `Cab`.

---

Library/Homebrew/cask/lib/hbc/cask.rb
Library/Homebrew/cask/lib/hbc/cask_loader.rb
Library/Homebrew/cask/lib/hbc/exceptions.rb
Library/Homebrew/test/cask/cask_loader/from__path_loader_spec.rb
Library/Homebrew/test/cask/dsl_spec.rb

-----
Fixes https://github.com/Homebrew/brew/issues/4562.

Raise error when file does not contain a cask.

---

Library/Homebrew/cask/lib/hbc/download_strategy.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/system_command.rb
Library/Homebrew/test/cask/download_strategy_spec.rb
Library/Homebrew/test/cask/pkg_spec.rb
Library/Homebrew/test/support/helper/cask/fake_system_command.rb
Library/Homebrew/test/system_command_result_spec.rb
Library/Homebrew/test/system_command_spec.rb
Library/Homebrew/test/utils/curl_spec.rb
Library/Homebrew/utils/curl.rb
Library/Homebrew/utils/github.rb

Revert "Use `SystemCommand` for `curl`."

---

Library/Homebrew/test/unpack_strategy/subversion_spec.rb

-----
Add spec for https://github.com/Homebrew/brew/pull/4551.

Add spec for SVN directory name containing `@`.

---

Library/Homebrew/cask/lib/hbc/download_strategy.rb
Library/Homebrew/download_strategy.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/system_command.rb
Library/Homebrew/test/cask/download_strategy_spec.rb
Library/Homebrew/test/cask/pkg_spec.rb
Library/Homebrew/test/support/helper/cask/fake_system_command.rb
Library/Homebrew/test/system_command_result_spec.rb
Library/Homebrew/test/system_command_spec.rb
Library/Homebrew/test/utils/curl_spec.rb
Library/Homebrew/utils/curl.rb
Library/Homebrew/utils/github.rb

-----
Fixes the errors in https://github.com/Homebrew/brew/pull/4561.

Use `SystemCommand` for `curl`.

---

Library/Homebrew/utils/curl.rb

Show `stdout` for `curl` commands.

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/download_strategy.rb

-----
These were removed and are also no longer in `compat/`.

Remove non-existent download strategies.

---

Library/Homebrew/utils/popen.rb

Fix `ErrorDuringExecution` initialization.

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/system_command.rb
Library/Homebrew/unpack_strategy/air.rb
Library/Homebrew/unpack_strategy/bzip2.rb
Library/Homebrew/unpack_strategy/cab.rb
Library/Homebrew/unpack_strategy/dmg.rb
Library/Homebrew/unpack_strategy/fossil.rb
Library/Homebrew/unpack_strategy/generic_unar.rb
Library/Homebrew/unpack_strategy/gzip.rb
Library/Homebrew/unpack_strategy/lha.rb
Library/Homebrew/unpack_strategy/lzip.rb
Library/Homebrew/unpack_strategy/lzma.rb
Library/Homebrew/unpack_strategy/mercurial.rb
Library/Homebrew/unpack_strategy/p7zip.rb
Library/Homebrew/unpack_strategy/rar.rb
Library/Homebrew/unpack_strategy/subversion.rb
Library/Homebrew/unpack_strategy/tar.rb
Library/Homebrew/unpack_strategy/xar.rb
Library/Homebrew/unpack_strategy/xz.rb
Library/Homebrew/unpack_strategy/zip.rb

Pass `verbose` to unpack strategies.

---

Library/Homebrew/download_strategy.rb

-----
Use `system_command` in `GitDownloadStrategy`.

Use `system_command` for `GitDownloadStrategy`.

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/formula.rb
Library/Homebrew/manpages/brew.1.md.erb
docs/Manpage.md

-----
Download strategy class names should be viewed as a private API (no Formula is using them directly anymore), so refer to them only with symbols.

Change docs to use symbols instead of class names.

---

Library/Homebrew/download_strategy.rb

Allow specifying cache directory for download strategies.

---

docs/New-Maintainer-Checklist.md

We've made these recommendations to current maintainers to update the
documentation so we don't forget to ask new maintainers to do the same
when we invite more in future.
-----

docs/New-Maintainer-Checklist: update best practises.

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/test/download_strategies_spec.rb

-----
Move specs for cask download strategies.

Merge download strategy specs.

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/test/cmd/update-report_spec.rb

-----
Fixes https://github.com/Homebrew/brew/pull/4601#issuecomment-410592455.

Fix `update-report` migration.

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/test/download_strategies_spec.rb

-----
Replace `popen_read` and `safe_system` with `system_command`/`system_command!`.

Use `system_command` for all download strategies.

---

Library/Homebrew/cleanup.rb
Library/Homebrew/test/cleanup_spec.rb

-----
Update regex to match `--`.

Fix cleanup for files with `--`.

---

Library/Homebrew/cmd/update-report.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/cmd/update-report_spec.rb

-----
The regex in `migrate_cache_entries_to_double_dashes` will never catch all edge cases.

Change migration to loop through formulae.

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/formula.rb
Library/Homebrew/software_spec.rb
Library/Homebrew/test/bottle_filename_spec.rb
Library/Homebrew/test/dev-cmd/bottle_spec.rb

-----
Use `--` for bottles so they can be dropped into the cache.
Fixes https://github.com/Homebrew/brew/pull/4601#issuecomment-410687384.

Use `--` for bottles.

---

Library/Homebrew/cask/lib/hbc/download.rb
Library/Homebrew/cask/lib/hbc/url.rb
Library/Homebrew/test/cask/cli/fetch_spec.rb

-----
Use normal download strategies for casks.
Depends on https://github.com/Homebrew/brew/pull/4608.

Use normal download strategies for casks.

---

Library/Homebrew/rubocops/formula_desc_cop.rb
Library/Homebrew/test/rubocops/formula_desc_cop_spec.rb

-----
Not sure why but this issue seems to have started creeping into PRs a bit lately and it's annoying having to manually point it out, so 🤷‍♂️.

formula_desc_cop: add unnecessary whitespace check

---

Library/Homebrew/test/cask/cask_loader/from_uri_loader_spec.rb
Library/Homebrew/test/rubocops/caveats_cop_spec.rb
Library/Homebrew/test/rubocops/checksum_cop_spec.rb
Library/Homebrew/test/rubocops/class_cop_spec.rb
Library/Homebrew/test/rubocops/components_order_cop_spec.rb
Library/Homebrew/test/rubocops/components_redundancy_cop_spec.rb
Library/Homebrew/test/rubocops/conflicts_cop_spec.rb
Library/Homebrew/test/rubocops/dependency_order_cop_spec.rb
Library/Homebrew/test/rubocops/formula_desc_cop_spec.rb
Library/Homebrew/test/rubocops/homepage_cop_spec.rb
Library/Homebrew/test/rubocops/lines_cop_spec.rb
Library/Homebrew/test/rubocops/options_cop_spec.rb
Library/Homebrew/test/rubocops/patches_cop_spec.rb
Library/Homebrew/test/rubocops/text_cop_spec.rb
Library/Homebrew/test/utils/svn_spec.rb

-----
Change some more URLs to use `https://`.

Use `https://` URLs.

---

Library/Homebrew/cmd/update-report.rb

-----
Unset `HOMEBREW_DISABLE_LOAD_FORMULA` during the migration.

Unset `HOMEBREW_DISABLE_LOAD_FORMULA` for migration.

---

Library/Homebrew/software_spec.rb

Remove trivial method.

---

Library/Homebrew/cmd/update-report.rb

-----
Output message when migrating cache entries, since this may take longer than a usual `brew update`.
Closes https://github.com/Homebrew/brew/issues/4624.

Output message when migrating cache entries.

---

Library/Homebrew/cask/lib/hbc/cli/cleanup.rb
Library/Homebrew/cleanup.rb
Library/Homebrew/test/cleanup_spec.rb

-----
Start refactoring `Cleanup`.

Refactor `Cleanup`.

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb
bin/brew

-----
As of #3870, this is no longer needed.

Remove environment variables used by `hub`.

---

Library/Homebrew/cleanup.rb
Library/Homebrew/cmd/cleanup.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/test/cleanup_spec.rb

-----
Use option parser for `brew cleanup` and convert `Cleanup` to a reusable class.

Use option parser for `brew cleanup`.

---

Library/Homebrew/cask/lib/hbc/cask_loader.rb
Library/Homebrew/cleanup.rb

-----
Add logic for cleaning up casks and for per-formula cache cleanup.

Add cask cleanup and per-formula cache cleanup.

---

Library/Homebrew/cleanup.rb
Library/Homebrew/lock_file.rb

-----
Clean up `.DS_Store` files on a per-cask/formula basis.
Depends on https://github.com/Homebrew/brew/pull/4639.

Per cask/formula `.DS_Store` cleanup

---

Library/Homebrew/brew.sh
Library/Homebrew/cmd/update-reset.sh
Library/Homebrew/cmd/update.sh

-----
Don't use `--depth 1`, but instead fetch all commits since the last tag.
Also fixes https://github.com/Homebrew/brew/issues/4652.

Always fetch at least the latest tag.

---

Library/Homebrew/brew.sh
Library/Homebrew/cmd/update-report.rb

-----
Fixes https://github.com/Homebrew/brew/issues/4652.

Set `initial_version` to `nil` when `git describe` fails.

---

Library/Homebrew/cleanup.rb
Library/Homebrew/extend/pathname.rb
Library/Homebrew/test/cleanup_spec.rb
Library/Homebrew/test/pathname_spec.rb
Library/Homebrew/test/version_spec.rb

-----
This fixes the regex to properly parse the version and to also match resources and patches. 
Fixes https://github.com/Homebrew/brew/issues/4650.

Fix `brew cleanup`.

---

Library/Homebrew/cleanup.rb

-----
Fixes https://github.com/Homebrew/brew/issues/4666.

Only clean up external patches.

---

Library/Homebrew/cask/lib/hbc/audit.rb

-----
https://github.com/Homebrew/homebrew-cask-versions/pull/6052

cask audit: GitHub `latest` casks shouldn't have an appcast

---

Library/Homebrew/compat/hbc/cli/search.rb

Disable `brew cask search` the same time as `brew cask cleanup`.

---

Library/Homebrew/os/linux.rb

-----
This code parallels the similar line of code in os/mac.rb

Warn if os/linux is loaded on generic OS

---

Library/Homebrew/brew.rb
Library/Homebrew/cask/lib/hbc/cli.rb
Library/Homebrew/test/utils_spec.rb
Library/Homebrew/utils.rb

-----
Only output the relevant file/line by default if called in a tap directory. Otherwise `--debug` will show the backtrace.
Closes https://github.com/Homebrew/brew/issues/4673.

Refactor `odeprecated`.

---

Library/Homebrew/os/mac/pkgconfig/10.14/sqlite3.pc
Library/Homebrew/os/mac/xcode.rb

-----
Assuming we don't cut a new `brew` tag today this can sit for a day or so to give people time to update.

10x/Mojave: update dev tool expected versions

---

Library/Homebrew/utils/github.rb

-----
Fixes https://github.com/Homebrew/brew/issues/4641
and 
https://github.com/Homebrew/brew/issues/4641#issuecomment-413188584 
Rate limit exceptions are already being handled so, I noticed that curl command's return code is 0 even when http response code is not 200

utils/github: Exception handling

---

Library/Homebrew/extend/os/linux/software_spec.rb
Library/Homebrew/extend/os/software_spec.rb
Library/Homebrew/software_spec.rb

-----
Bottles must be relocated on Linux to find the brewed glibc and gcc.

BottleSpecification: Do not skip bottle relocation on Linux

---

README.md
docs/Manpage.md
manpages/brew.1

README: add jonchang.

---

docs/Manpage.md
manpages/brew.1

This fixes the red master build.
-----

manpage: add `brew bundle check --verbose`

---

Library/Homebrew/rubocops/class_cop.rb

-----
https://github.com/Homebrew/brew/pull/4698#issuecomment-413671367 
https://github.com/Homebrew/homebrew-core/pull/31183
@DomT4
Verified by running `brew audit --only-cop=TestCalls` for all formulae in Homebrew/core.

audit: don't error when test block is missing

---

CONTRIBUTING.md

-----
The PR template suggests running `brew tests` but doesn't specify that this will only work if you're working out of the brew installed repo, as opposed to cloning your fork somewhere else (which requires `bin/brew tests`). 
I found this [confusing](https://github.com/Homebrew/brew/issues/4707#issuecomment-413706741) so I wanted to help other new contributors in the future by adding an explanation of "How to contribute" to `CONTRIBUTING.md`.

CONTRIBUTING: Add "How to contribute" section

---

Library/Homebrew/os/mac.rb

This code is only used on macOS.

OS::Mac.mdfind: No need to guard on OS.mac?

---

Library/Homebrew/rubocops/conflicts_cop.rb

-----
Versioned `node` formulae are `keg_only`.

conflicts_cop: remove `node@` from whitelist

---

Library/Homebrew/unpack_strategy/directory.rb

-----
Closes https://github.com/Homebrew/brew/issues/4699.

Use `cp` instead of `FileUtils.copy_entry`.

---

Library/Homebrew/cask/lib/hbc/dsl.rb

-----
Closes https://github.com/Homebrew/brew/issues/4718.

Ignore unparsable system languages.

---

Library/Homebrew/unpack_strategy/tar.rb

`.tar.lz` ≠ `.tar.lzma`

---

docs/Manpage.md
manpages/brew.1

manpage: update from latest homebrew-bundle docs.

---

Library/Homebrew/dev-cmd/audit.rb

-----
This is causing more problems than it solves. cc @DomT4 
https://github.com/Homebrew/homebrew-core/pull/31311#issuecomment-415240980, https://github.com/Homebrew/homebrew-core/pull/31193#issuecomment-415041743

audit: remove "`bottle` is not defined"

---

Library/Homebrew/dev-cmd/audit.rb

-----
https://github.com/Homebrew/homebrew-core/pull/31514#issuecomment-416227902

audit: Add null check on style results

---

Library/Homebrew/cask/lib/hbc/auditor.rb

-----
Closes https://github.com/Homebrew/homebrew-cask/issues/51289.

Don’t use `CLI::Cleanup` in `Auditor`.

---

Library/Homebrew/dev-cmd/audit.rb

-----
https://github.com/Homebrew/homebrew-core/pull/31514#issuecomment-416292746

audit: Use `to_i`during assignment to prevent NPE

---

Library/Homebrew/system_command.rb
Library/Homebrew/test/system_command_spec.rb

-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/51401#issuecomment-416927138.

Fix executable with spaces.

---

Library/Homebrew/rubocops/text_cop.rb
Library/Homebrew/test/rubocops/text_cop_spec.rb

-----
Update the `cargo build` cop to match the syntax in https://github.com/Homebrew/homebrew-core/pull/31567
cc @DomT4

text_cop: update `cargo build` cop

---

Library/Homebrew/update_migrator.rb

Skip migration if cache is empty or doesn’t exist.

---

.gitignore
Library/Homebrew/test/utils/svn_spec.rb
Library/Homebrew/utils/svn.rb

- Ignore files that are generated by `brew tests`
- Make the SVN tests work without prompting for GitHub's SSL certificate
-----

tests: handle file leaks and SVN test prompt.

---

Library/Homebrew/extend/os/mac/system_config.rb
Library/Homebrew/readall.rb
Library/Homebrew/requirements/java_requirement.rb
Library/Homebrew/system_command.rb
Library/Homebrew/system_config.rb
Library/Homebrew/test/cask/pkg_spec.rb
Library/Homebrew/test/java_requirement_spec.rb
Library/Homebrew/test/support/helper/cask/fake_system_command.rb
Library/Homebrew/test/system_command_result_spec.rb

-----
Replace some `#popen_read`s with `system_command`.

Remove some `#popen_read`s.

---

Library/Homebrew/shims/super/cc

It fails to accept any version < 10.6.
-----

super/cc: fix -mmacosx-version-min on Mojave.

---

Library/Homebrew/download_strategy.rb
Library/Homebrew/utils/curl.rb

-----
Fixes https://github.com/Homebrew/brew/issues/4820.

Fix `downloads` directory not being created.

---

Library/Homebrew/download_strategy.rb

Change regex to match `filename` if header also contains `filename*`.

---

Library/Homebrew/test/cache_store_spec.rb
Library/Homebrew/test/cask/artifact/installer_spec.rb

Use classes for instance doubles.

---

Library/Homebrew/extend/ENV/std.rb

Revert "std: use HOMEBREW_ARCH env var on Linux"

---

Library/Homebrew/os/mac.rb

I also just remembered this today so let’s add a comment reminder.
-----

os/mac: also update install on version bumps.

---

.gitignore

Remove a bunch of unneeded, old directories and generally cleanup.
-----

gitignore: general cleanup

---

docs/C++-Standard-Libraries.md

-----
This just fixes a minor typo from #4845 by @MikeMcQuaid

docs: fix typo from #4845.

---

Library/Homebrew/keg.rb

This isn't the case on our CI for now.
-----

keg: don't require Caskroom to be writable.

---

Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/test/download_strategies_spec.rb
Library/Homebrew/utils/curl.rb

Check for range support instead of rescuing error.

---

docs/Maintainer-Guidelines.md

After the discussions in https://github.com/Homebrew/brew/pull/4759 I've added more guidelines for @Homebrew/maintainers to discuss. This is based on trying to document (as was suggested) previous decisions I've made as lead maintainer so that they do not seem arbitrary in future. It should also help make maintainers more autonomous so it's clear what does and doesn't require approval from other maintainers.
Separated from https://github.com/Homebrew/brew/pull/4845 to make the content easier to discuss.
CC @Homebrew/maintainers for discussion. Please, folks, let's try and stick to the topic of what's being proposed in this PR specifically rather than unrelated gripes you may have.
-----

docs/Maintainer-Guidelines: add more guidelines.

---

Library/Homebrew/cmd/update.sh

cmd/update: follow GitHub API redirects.

---

Library/Homebrew/cask/audit.rb

---
Fixes the CI error here: https://github.com/Homebrew/homebrew-cask/pull/51795

Don’t add error when changing checksum to `:no_check`.

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/extend/ARGV.rb
Library/Homebrew/extend/string.rb
Library/Homebrew/linkage_checker.rb
Library/Homebrew/tap.rb
Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/backports-3.11.4/lib/backports/2.5.0/string/delete_prefix.rb
Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/backports-3.11.4/lib/backports/tools/arguments.rb

Add `String#delete_prefix` backport.

---

Library/Homebrew/constants.rb
Library/Homebrew/test/Gemfile.lock

---
Depends on https://github.com/Homebrew/homebrew-core/pull/32129.

Update RuboCop to 0.58.2.

---

Library/Homebrew/extend/pathname.rb
Library/Homebrew/global.rb
Library/Homebrew/test/pathname_spec.rb
Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/core_ext/file/atomic.rb

And delete our own implementation.
-----

Use ActiveSupport File.atomic_write

---

Library/Homebrew/utils/analytics.rb

Change generic-prefix to custom-prefix.
-----
Argh

Utils::Analytics.custom_prefix_label: Fix typo

---

Library/Homebrew/test/cmd/cat_spec.rb
Library/Homebrew/test/cmd/commands_spec.rb
Library/Homebrew/test/cmd/info_spec.rb
Library/Homebrew/test/spec_helper.rb

-----
I've added tests for a few commands to improve code coverage (issue #4763).

Improve code coverage

---

Library/Homebrew/system_command.rb
Library/Homebrew/test/system_command_result_spec.rb

Add `SystemCommand::Result#merged_output`.

---

Library/Homebrew/exceptions.rb
Library/Homebrew/utils/fork.rb

-----
Mind giving this a stab, @DomT4? I'm away from a Mac at the moment.

utils/fork: Check if error pipe is closed

---

Library/Homebrew/shims/super/cc

This is a follow-up to #4810, motivated by this comment: 
https://github.com/Homebrew/brew/pull/4810#issuecomment-422944940

super/cc: further bump -mmacosx-version-min on Mojave

---

Library/Homebrew/system_config.rb

This is `git` for most people.
-----

system_config: don't print default HOMEBREW_GIT value.

---

Library/Homebrew/cask/dsl/caveats.rb
Library/Homebrew/requirements/java_requirement.rb

-----
JDK 11 General Availability: 25th September

java_requirement, cask dsl caveats: JDK 11

---

.travis.yml
Library/Homebrew/cleanup.rb
Library/Homebrew/cmd/prune.rb
Library/Homebrew/diagnostic.rb
Library/Homebrew/install.rb
Library/Homebrew/keg.rb
Library/Homebrew/test/spec_helper.rb
azure-pipelines.yml

- ensure that `HOMEBREW_CELLAR` is always created on `install`.
- remove the need for a special `PRUNEABLE_DIRECTORIES` variable
- reuse values from existing variables and get `uniq`s.

keg: further tweak directory constants.

---

Library/Homebrew/extend/os/mac/diagnostic.rb

It hasn't been updated yet and we want to be able to update the Xcode versions for everyone else in https://github.com/Homebrew/brew/pull/4936.

os/mac/diagnostic: don't complain about Xcode version on Azure.

---

Library/Homebrew/extend/os/linux/development_tools.rb

-----
Prefer brewed tools over the host's tools, particularly `binutils` and `gcc`.

DevelopmentTools::locate: Prefer brewed tools [Linux]

---

Library/Homebrew/dev-cmd/mirror.rb
Library/Homebrew/formula.rb

-----
Fixes https://github.com/Homebrew/brew/issues/4972.

Fix `brew mirror`.

---

docs/How-To-Open-a-Homebrew-Pull-Request.md

- [N/A] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [N/A] Have you successfully run `brew style` with your changes locally?
-----
Moves sample commands into code blocks, plus some other rearrangements that make the instructions easier to follow.

docs/How-To-Open-a-Homebrew-Pull-Request: move sample commands into code blocks

---

azure-pipelines.yml

This makes debugging easier.
-----

azure-pipelines: always upload test results.

---

Library/Homebrew/compilers.rb
Library/Homebrew/extend/ENV/std.rb
Library/Homebrew/extend/ENV/super.rb
Library/Homebrew/extend/os/linux/hardware/cpu.rb
Library/Homebrew/hardware.rb

-march=native is default. Hardware::CPU: Add Skylake [Linux]

---

Library/Homebrew/cmd/vendor-install.sh

Update portable-ruby to verison 2.3.7 for ARM [Linux]

---

Library/Homebrew/exceptions.rb

"occured" -> "occurred"

---

Library/Homebrew/extend/os/mac/unpack_strategy/zip.rb

-----
Fixes Homebrew/homebrew-cask#52396.

zip: restore extended attributes when under MacOS

---

Library/Homebrew/cask/installer.rb

Remove unused `include`.

---

Library/Homebrew/dev-cmd/audit.rb

audit: Permit HEAD for non-official taps

---

docs/Maintainer-Guidelines.md

I'll step down on February 4th to better coincide with the Homebrew maintainers in-person conference. This will make it easier to resolve any logistical issues that arise.
CC @Homebrew/maintainers FYI. I'm sure you won't begrudge me another three days 😉
-----

docs/Maintainer-Guidelines: change lead maintainer date.

---

.travis.yml
azure-pipelines.yml

-----
https://github.com/Homebrew/homebrew-test-bot/pull/205

azure/travis: update to xcode 10

---

Library/Homebrew/cask/quarantine.rb

-----
Fixes Homebrew/homebrew-cask#53219.

Cask: fix quarantine check when xattr is broken 

---

Library/Homebrew/cleanup.rb
Library/Homebrew/download_strategy.rb

-----
Fixes https://github.com/Homebrew/brew/issues/5039.

Fix cleanup of incomplete downloads.

---

Library/Homebrew/cache_store.rb

-----
Hopefully fixes https://github.com/Homebrew/brew/issues/5083, which seems to be caused by an `atomic_write` inside a non-existent directory.

Ensure cache directory for `CacheStoreDatabase` exists.

---

Library/Homebrew/cask/cmd/style.rb
Library/Homebrew/test/cask/cmd/style_spec.rb

---
Fixes https://github.com/Homebrew/brew/pull/5118#issuecomment-430432851.

Fix `brew cask style` with relative paths.

---

Library/Homebrew/compat/download_strategy.rb

This should make it clearer how you can maintain this yourself (as well as being a better fit with `odeprecated`'s output).
-----

compat/download_strategy: improve messaging.

---

Library/Homebrew/dev-cmd/audit.rb

This was removed in https://github.com/Homebrew/homebrew-core/pull/33233.
-----

audit: remove heroku formula.

---

Library/Homebrew/cmd/gist-logs.rb
Library/Homebrew/utils/github.rb

-----
It's currently unclear how to fix the GitHub API Token, I've attempted to clarify the output message. Open to feedback!
Unfortunately I'm unable to figure out why the tests aren't passing, would appreciate some guidance.

Clarify how to set HOMEBREW_GITHUB_API_TOKEN

---

Library/Homebrew/download_strategy.rb

-----
Fixes https://github.com/Homebrew/homebrew-core/pull/32454.

Support `Content-Disposition: inline`.

---

Library/Homebrew/rubocops/urls_cop.rb
Library/Homebrew/test/rubocops/urls_cop_spec.rb

-----
The `deb.debian.org` mirror now supports HTTPS, so let's use it instead of various 3rd party mirrors.

audit: use debian canonical mirror

---

README.md

README: use Azure Pipelines badge.

---

Library/Homebrew/cmd/doctor.rb

- [] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
-----
#1860

doctor: Use CLI::Parser to parse args

---

Library/Homebrew/cask/artifact/abstract_uninstall.rb
Library/Homebrew/cask/installer.rb

---
Don't remove login items when upgrading an application.

cask: Don’t remove login items on upgrade.

---

Library/Homebrew/dev-cmd/audit.rb

-----
- angolmois
https://github.com/Homebrew/homebrew-core/commit/580fab01dec680802a16748a81cc19975d7c329a
- opensyobon
https://github.com/Homebrew/homebrew-core/commit/312884f5beaa3569e8aa3378a6bf3cc85d0dcdde
- pxz
https://github.com/Homebrew/homebrew-core/commit/f2e0ba245e0af198340180a098c0dba51f934e6e

audit: remove deleted formulae from unstable whitelist

---

Library/Homebrew/rubocops/options_cop.rb
Library/Homebrew/test/rubocops/options_cop_spec.rb

-----
No audit failures in `core`.

options_cop: make audits non-strict

---

Library/Homebrew/dev-cmd/audit.rb

-----
No audit failures in `core`.

audit: make `keg_only_style` non-strict

---

Library/Homebrew/cmd/diy.rb

Also print the path to put files into if no build system was determined.
-----

diy: add meson support

---

Library/Homebrew/test/support/fixtures/cask/Casks/compat/with-dsl-version.rb

Remove unused test cask.

---

Library/Homebrew/unpack_strategy/dmg.rb

Remove `-quiet` flag when verbose.

---

Library/Homebrew/cask/installer.rb

-----
Addresses the issue in https://github.com/Homebrew/homebrew-cask-drivers/pull/514.

Always make nested container readable and writable.

---

Library/Homebrew/cmd/desc.rb

-----
#1860 
This changes the help text considerably. Please check out locally to see if its acceptable.

desc: Use CLI::Parser to parse args

---

Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/xcode.rb

xcode: upgrade for Xcode 10.1 release

---

README.md
docs/Manpage.md
manpages/brew.1

https://github.com/Homebrew/brew/pull/5244#issuecomment-435727683

README: more maintainer updates.

---

Library/Homebrew/cmd/link.rb

link: Use CLI::Parser to parse args

---

Library/Homebrew/cmd/missing.rb

missing: Use CLI::Parser to parse args

---

Library/Homebrew/cmd/home.rb

home: Use CLI::Parser to parse args

---

Library/Homebrew/exceptions.rb

exceptions.rb: avoid failure if no arguments

---

Library/Homebrew/cmd/options.rb

options: Use CLI::Parser to parse args

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.1.0

---

Library/Homebrew/cli_parser.rb
Library/Homebrew/cmd/style.rb

style: Use CLI::Parser to parse args

---

Library/Homebrew/cask/artifact/abstract_uninstall.rb
Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb
Library/Homebrew/test/cask/artifact/uninstall_spec.rb
Library/Homebrew/test/cask/artifact/uninstall_zap_shared_examples.rb
Library/Homebrew/test/cask/artifact/zap_spec.rb

-----
Fixes the failure in https://github.com/Homebrew/homebrew-cask-drivers/pull/621, which is caused by the application still starting while we are already trying to quit it.

Improve application quitting.

---

Library/.rubocop.yml
Library/.rubocop_audit.yml
Library/.rubocop_cask.yml
Library/.rubocop_shared.yml
Library/Homebrew/.rubocop.yml
Library/Homebrew/cask/cmd/style.rb
Library/Homebrew/test/.rubocop.yml
Library/Homebrew/test/cmd/style_spec.rb

---
Split out RuboCop config used for Casks.

Fix RuboCop for Casks.

---

Library/Homebrew/cmd/reinstall.rb

reinstall: Add verbose flag

---

Library/Homebrew/cmd/unlink.rb

unlink: Use CLI::Parser to parse args

---

Library/Homebrew/cmd/unpack.rb

unpack: Use CLI::Parser to parse args

---

Library/Homebrew/cmd/unpin.rb

unpin: Use CLI::Parser to parse args

---

Library/Homebrew/cmd/leaves.rb

leaves: Use CLI::Parser to parse args

---

Library/Homebrew/manpages/brew.1.md.erb
docs/Manpage.md
manpages/brew.1

https://discourse.brew.sh/t/how-are-bottle-and-postinstall-related-is-it-safe-to-run-bottle-after-postinstall/3410/4 is the information source.
- [N/A] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
-----

docs: bottle is a valid formula specifier, too

---

Library/Homebrew/cmd/pin.rb

pin: Use CLI::Parser to parse args

---

Library/Homebrew/cmd/list.rb

list: Add help text

---

Library/Homebrew/cmd/reinstall.rb

reinstall: add build-from-source switch.

---

Library/Homebrew/cask/audit.rb

-----
Removes the check for `sha256`-only (i.e. `version` stayed the same) on the Cask side.
Refs https://github.com/Homebrew/homebrew-cask/issues/48862. In short, this check is a well-intentioned wrong solution to the problem. We’re currently tackling the situation in better ways, namely quarantining `app` bundles and not allowing unsigned `pkg`s to run (that was already in place).
We install other types of software, true, but in those this situation almost never arises, and they’re less dangerous (e.g. font files).

Cask: Remove check on sha-only change

---

Library/Homebrew/cmd/cleanup.rb

cleanup: Use CLI::Parser to parse args

---

docs/Maintainer-Guidelines.md

CC @Homebrew/maintainers FYI and for thoughts.
-----

docs/Maintainer-Guidelines: don't merge failing tests.

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/test/diagnostic_checks_spec.rb
Library/Homebrew/test/os/mac/diagnostic_spec.rb
azure-pipelines.yml

-----
requested by https://github.com/Homebrew/brew/pull/5447#discussion_r244200557
Shares the prefix check logic between macOS and Linux.

diagnostic: share prefix check

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/test/diagnostic_checks_spec.rb
Library/Homebrew/test/os/mac/diagnostic_spec.rb
azure-pipelines.yml

Revert "diagnostic: share prefix check"

---

Library/Homebrew/diagnostic.rb
Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/test/diagnostic_checks_spec.rb
Library/Homebrew/test/os/mac/diagnostic_spec.rb
azure-pipelines.yml

Reverts Homebrew/brew#5453
Take two on #5448

Revert "Revert "diagnostic: share prefix check""

---

Library/Homebrew/cask/auditor.rb

-----
Fixes CI failure in https://github.com/Homebrew/homebrew-cask/pull/57284.

Fix missing `require`.

---

docs/FAQ.md

Fix docs/FAQ.md typo

---

Library/Homebrew/utils.rb

This is needed for `compat/download_strategy` for now.
CC @sparta-developers https://github.com/Homebrew/brew/commit/efc3c0c4c02a85e00fb424a3d94f6276b38b988e#r31966181

utils: re-add install_gem! version argument.

---

.gitignore

gitignore: ignore pinned taps

---

Library/Homebrew/utils/github.rb

utils/github: display max 20 closed PRs.

---

docs/Common-Issues-for-Core-Contributors.md
docs/Formula-Cookbook.md

Use the nice homebrew-core ones instead.

docs: update some legacy-homebrew commit URLs.

---

Library/Homebrew/cmd/command.rb

command: Use CLI::Parser to parse args

---

Library/Homebrew/cmd/gist-logs.rb

gist-logs: add missing install require.

---

Library/Homebrew/style.rb

style: better handle file arguments.

---

Library/Homebrew/brew.rb

brew.rb: duplicate MissingEnvironmentVariables exception.

---

Library/Homebrew/cmd/gist-logs.rb

gits-logs: Use CLI::Parser to parse args

---

Library/Homebrew/cmd/search.rb

search: Add descriptions to option declarations

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.3.0

---

Library/Homebrew/extend/os/mac/diagnostic.rb

This has caused us multiple hard-to-diagnose issues so let's complain about it in `brew doctor`.
References https://github.com/Homebrew/brew/issues/5558
-----

os/mac/diagnostic: detect Bitdefender.

---

Library/Homebrew/cli_parser.rb
Library/Homebrew/cmd/deps.rb
Library/Homebrew/cmd/desc.rb
Library/Homebrew/cmd/fetch.rb
Library/Homebrew/cmd/info.rb
Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/options.rb
Library/Homebrew/cmd/outdated.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/unpack.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/cmd/uses.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/dev-cmd/create.rb
Library/Homebrew/dev-cmd/test.rb
Library/Homebrew/test/cmd/reinstall_spec.rb
docs/Manpage.md
manpages/brew.1

cmd/upgrade: Use CLI::Parser to parse args

---

Library/Homebrew/cmd/upgrade.rb

cmd/upgrade: Add call to parse options

---

Library/Homebrew/cmd/update-report.rb

cmd/update: Add quiet flag

---

Library/Homebrew/cask/artifact/moved.rb

---
Extracted from https://github.com/Homebrew/brew/pull/5685.

Automatically create parent directory for artifacts with `sudo` if necessary.

---

Library/Homebrew/cask/artifact/moved.rb

-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/58564.

Only create target directory if it doesn’t exist.

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.4.0

---

Library/Homebrew/cmd/--repository.rb
docs/Manpage.md
manpages/brew.1

-----
The `brew --repository --help` and man brew output say it can be called with a formula as an argument. The correct argument it `user/repo`.

cmd/repository: Fix man pages and help

---

Library/Homebrew/download_strategy.rb

download_strategy: more robust filename content encoding handling.

---

Library/Homebrew/brew.rb

This is long gone at this point so no need to keep this code around.
-----

brew.rb: don't try to uninstall brew-cask keg.

---

Library/Homebrew/cask/artifact/abstract_artifact.rb
Library/Homebrew/cask/cask.rb
Library/Homebrew/cask/cmd.rb
Library/Homebrew/cask/cmd/upgrade.rb
Library/Homebrew/cask/config.rb
Library/Homebrew/cask/dsl.rb
Library/Homebrew/cask/installer.rb
Library/Homebrew/test/cask/artifact/alt_target_spec.rb
Library/Homebrew/test/cask/artifact/app_spec.rb
Library/Homebrew/test/cask/artifact/binary_spec.rb
Library/Homebrew/test/cask/artifact/generic_artifact_spec.rb
Library/Homebrew/test/cask/artifact/installer_spec.rb
Library/Homebrew/test/cask/artifact/suite_spec.rb
Library/Homebrew/test/cask/artifact/two_apps_correct_spec.rb
Library/Homebrew/test/cask/cmd/audit_spec.rb
Library/Homebrew/test/cask/cmd/install_spec.rb
Library/Homebrew/test/cask/cmd/list_spec.rb
Library/Homebrew/test/cask/cmd/options_spec.rb
Library/Homebrew/test/cask/cmd/uninstall_spec.rb
Library/Homebrew/test/cask/cmd/upgrade_spec.rb
Library/Homebrew/test/cask/cmd/zap_spec.rb
Library/Homebrew/test/cask/cmd_spec.rb
Library/Homebrew/test/cask/config_spec.rb
Library/Homebrew/test/cask/dsl_spec.rb
Library/Homebrew/test/cask/installer_spec.rb
Library/Homebrew/test/cask/quarantine_spec.rb
Library/Homebrew/test/support/helper/spec/shared_context/homebrew_cask.rb

-----
Save the directories used for installing casks (like `--appdir`) and re-use them when reinstalling/uninstalling/upgrading.

Save cask config for reinstall/uninstall/upgrade.

---

Dockerfile

The default user is now `root`.

Dockerfile: Remove environment variable USER

---

Library/Homebrew/cask/cmd.rb
Library/Homebrew/cask/cmd/automerge.rb
Library/Homebrew/utils/github.rb

-----
A command to automatically merge “simple” version bump PRs.

Add `brew cask automerge` command.

---

Library/Homebrew/cask/cmd/edit.rb

-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/51907.

Allow editing broken casks.

---

Library/Homebrew/utils/github.rb

---
Allow more specific filtering of pull requests.

Pass additional options to `GitHub.pull_requests`.

---

Library/Homebrew/cmd/doctor.rb
Library/Homebrew/cmd/update.sh
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/diagnostic.rb

Recommend `brew untap` if tap doesn't exist on `brew update` or `brew doctor`.
-----

Improve handling of deleted taps.

---

Library/Homebrew/missing_formula.rb

Ensure consistent formatting and provide references to all MacTeX packages.
-----

Clean up blacklisted package messages

---

Dockerfile.test.yml
azure-pipelines.yml

azure-pipelines.yml: Build and test Docker image

---

Library/Homebrew/cmd/upgrade.rb

Fix Infinite Recursion in upgradable_dependents and broken_dependents

---

Library/Homebrew/utils/github.rb

-----
Needed for checking if a pull request has been merged: https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged

Let `GitHub::open_api` return `nil` when status is `204 No Content`.

---

Library/Homebrew/formula.rb

Regardless of the exception we don't want this method to blow up.
Fixes #5770.

Formula.installed: handle more exceptions.

---

docs/Shell-Completion.md

Fixes the issue noted in https://github.com/Homebrew/brew/pull/5625.
CC @maxim-belkin @ikatza
-----

Shell-Completion: fix redirection.

---

Library/Homebrew/hardware.rb

Fix Hardware::CPU.arm? for aarch64

---

docs/Formula-Cookbook.md

-----
This provides a minor formatting fix for recent changes in #5737 where the URLs were displayed verbatim and not as links.

Docs: fix formatting in Formula Cookbook

---

Library/Homebrew/dev-cmd/man.rb
README.md
docs/Homebrew-Governance.md
docs/Maintainer-Guidelines.md
docs/Manpage.md
docs/New-Maintainer-Checklist.md
docs/README.md
manpages/brew.1

Fourteen of the Homebrew maintainers met in person (and four video-called in) in Brussels on 4th February to discuss the future governance of Homebrew (and get to know each other better). A longer write-up of this event will appear on [the Homebrew blog](https://brew.sh/blog/) at a future date.
Several votes were had:
- A Technical Steering Committee (TSC) will be responsible for major technical decisions (passed: unanimously)
- Homebrew will have a yearly elected project lead role (passed: 17 in favour, 1 against)
- The PLC should be elected by the membership (i.e., by all members of the Homebrew organisation) annually (passed: unanimously)
- The Project Leadership Committee (PLC) should be Misty, Markus, Jonathan, Shaun and Mike (passed: unanimously)
- @MikeMcQuaid should be the project …

Add/link Homebrew Governance document.

---

Library/Homebrew/cmd/vendor-install.sh

vendor-install: Add portable-ruby for aarch64 (ARM64)

---

Library/Homebrew/utils/lock.sh

-----
see [linuxbrew/brew's PR](https://github.com/Linuxbrew/brew/pull/737)

use python flock firstly

---

Library/Homebrew/cmd/upgrade.rb

Reverts Homebrew/brew#5751
This introduced unhelpful/incorrect messaging unfortunately for a case affecting a single user so far so warrants a revert.
Fixes Homebrew/brew#5803

Revert "Fix Infinite Recursion in upgradable_dependents and broken_dependents"

---

Library/Homebrew/utils/gems.rb

Our Gemfile requires it and it will result in a more consistent configuration.
CC @alebcay who mentioned this.
-----

utils/gems: install Bundler 2.

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.4.3

---

docs/Releases.md

docs: linkify some links

---

docs/Installation.md

Improve wording

---

completions/bash/brew

-----
Remove Bash completion that is no longer necessary.

Brew: remove prune completion for Bash

---

Library/Homebrew/cmd/info.rb
docs/Manpage.md
manpages/brew.1

-----
- fix error when passing an invalid value to `--days` or `--category`
- fix no output from `brew info --analytics` by extending timeout to 5 seconds
- add `cask-install` as an option for `--category`
- improve help text

info: flag and doc fixes and updates

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

This means the help text will be output.
-----

bump-formula-pr: improve no formula output.

---

Library/Homebrew/brew.sh

It seems CI is failing intermittently when Docker isn't being detected as expected.

Debug Docker root issues

---

Library/Homebrew/dev-cmd/tap-new.rb
Library/Homebrew/test/dev-cmd/tap-new_spec.rb

Note the tap path.
References #5901.
-----

tap-new: improve output.

---

docs/Brew-Test-Bot.md
docs/Homebrew-on-Linux.md

Add the BrewTestBot and Linuxbrew logos to the relevant pages.
-----

docs: add logos.

---

Library/Homebrew/cmd/cat.rb
Library/Homebrew/cmd/list.rb
Library/Homebrew/cmd/log.rb
Library/Homebrew/cmd/sh.rb
Library/Homebrew/dev-cmd/prof.rb
Library/Homebrew/dev-cmd/ruby.rb
Library/Homebrew/utils.rb

This improves both test coverage, makes it easier to use a profiler and a debugger.
-----

*cmd/*: use *system instead of exec for easier testing.

---

Library/Homebrew/exceptions.rb

The code was removed but the exception was not.
-----

exceptions: remove unused scp exception.

---

Library/Homebrew/cask/cask.rb

Replace the use of HOME or HOMEBREW_PREFIX in the output strings with variable versions. This is particularly useful on formulae.brew.sh.
- [x Have you successfully run `brew tests` with your changes locally?
-----

cask: improve JSON output consistency.

---

Dockerfile

Otherwise Ruby complains which is causing failing tests.
-----

Dockerfile: unset work writable permission.

---

Library/Homebrew/diagnostic.rb

We previously did this somewhat unintentionally. `brew readall` does this for all formulae but takes way longer.
-----

diagnostic: report unreadable, installed formulae.

---

Library/Homebrew/diagnostic.rb

diagnostic: flag unreadable rather than unavailable formulae.

---

Library/Homebrew/requirements/xcode_requirement.rb

See discussion in https://github.com/Homebrew/brew/pull/5940.
-----

xcode_requirement: require macOS 10.14.4 for Xcode 10.2.

---

Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/xcode.rb

-----
From Xcode 10.2 Release Notes,
> Xcode 10.2 requires a Mac running macOS 10.14.3 or later.

xcode: upgrade for Xcode 10.2 release

---

docs/Homebrew-on-Linux.md

Redirect docs.brew.sh/linux to Homebrew on Linux

---

Library/Homebrew/cleaner.rb

Seems like auto-correct was a bit too eager to fix things :) ?
- [ X ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [ X ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ X ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ X ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [ X ] Have you successfully run `brew style` with your changes locally?
- [ X ] Have you successfully run `brew tests` with your changes locally?
-----

Fix typo in cleaner.rb

---

Library/Homebrew/test/cask/cmd/info_spec.rb

cask/cmd/info_spec: needs network connection.

---

Library/Homebrew/system_config.rb

This cuts down a bit on noise. While we’re here, optimise the checks too.
-----

system_config: don’t output default HOMEBREW_LOGS.

---

Library/Homebrew/brew.rb

except for "brew services" command
Sort of reverts #6010. Fixes #5865.
-----

brew: remove sudo call

---

Library/Homebrew/brew.rb

brew: remove sudo call only in docker context

---

Library/Homebrew/test.rb

test: kill all subprocesses on timeout.

---

Library/Homebrew/dev-cmd/extract.rb

extract: Replace ARGV.named with args.remaining

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.5.0

---

Library/Homebrew/cmd/info.rb

cmd/info: fix frozen pathname usage.

---

Library/Homebrew/utils/github.rb

See https://discourse.brew.sh/t/error-cant-modify-frozen-string/4691/4
-----

utils/github: fix frozen string usage.

---

Library/Homebrew/cask/exceptions.rb
Library/Homebrew/cmd/gist-logs.rb

-----
Fix exceptions caused by frozen strings.

Fix exception inception.

---

Library/Homebrew/cask/exceptions.rb
Library/Homebrew/cmd/gist-logs.rb

Freeze the results changed in #6072.
-----

Freeze more strings

---

Library/Homebrew/build_environment.rb

Fix bad mutable call on a frozen string.

---

Library/Homebrew/extend/ARGV.rb

ARGV: fix build_head? call.

---

docs/Taps.md

Addresses https://github.com/Homebrew/brew/issues/6110
-----

Taps: remove references to pinning.

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.6.0

---

docs/Homebrew-on-Linux.md

These are needed to build patchelf 0.10 with debian wheezy.
-----

Homebrew-on-Linux.md: update minimal requirements

---

Library/Homebrew/cask/artifact/abstract_uninstall.rb

-----
Fixes Homebrew/homebrew-cask#63583.

Skip :trash step if no paths exist

---

.github/issue-close-app.yml

It's not a good use of maintainer time to handle these manually.
-----

github/issue-close-app: autoclose missing issue template.

---

.github/issue-close-app.yml

Use the correct multiline syntax.
-----

issue-close-app.yml: fix YAML syntax (again)

---

Library/Homebrew/cask/cmd/upgrade.rb
Library/Homebrew/cask/installer.rb

-----
Closes https://github.com/Homebrew/homebrew-cask/issues/63578.

Output all upgradable casks before upgrading.

---

Library/Homebrew/os/mac/version.rb

10.15: macOS Catalina

---

Library/Homebrew/os/mac/pkgconfig/10.15/libcurl.pc
Library/Homebrew/os/mac/pkgconfig/10.15/libexslt.pc
Library/Homebrew/os/mac/pkgconfig/10.15/libxml-2.0.pc
Library/Homebrew/os/mac/pkgconfig/10.15/libxslt.pc
Library/Homebrew/os/mac/pkgconfig/10.15/sqlite3.pc
Library/Homebrew/os/mac/pkgconfig/10.15/uuid.pc
Library/Homebrew/os/mac/pkgconfig/10.15/zlib.pc

-----
Comparing to macOS Mojave, `libcurl` has been upgraded from `7.54.0` to `7.64.1`, `sqlite3` has been upgraded from `3.24.0` to `3.28.0`.

pkg-config: add initial support for macOS Catalina

---

docs/Troubleshooting.md

Correct the link to Homebrew on Linux GitHub issues

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.6.1

---

.github/issue-close-app.yml

This should hopefully make the experience a little more pleasant when users make an innocent mistake.
-----

.github/issue-close-app: make message friendlier.

---

Library/Homebrew/formula.rb
docs/Formula-Cookbook.md

-----
Add some info on the usage of caveats in Homebrew

Docs: add caveat info to cookbook

---

.github/issue-close-app.yml

Fix templates link in close bot

---

Library/Homebrew/brew.sh

Prompted by https://github.com/Homebrew/install/pull/213
As [suggested](https://github.com/Homebrew/install/pull/213#issuecomment-506968145) by @sjackman.
@MikeMcQuaid - I had a quick look at how to add a spec for this, but not totally sure. Any guidance on the best place to test this, ie unset `USER` and check that brew still works?
-----

Gracefully handle missing USER env var

---

Library/Homebrew/requirements/java_requirement.rb

-----
`openjdk` has been superseded by `adoptopenjdk`.

JavaRequirement: Change openjdk to adoptopenjdk

---

Library/Homebrew/cask/cask.rb

-----
This allows casks to be added to Repology.
Closes https://github.com/Homebrew/homebrew-cask/issues/65978.

Add `token` to `Cask#to_h`.

---

Library/Homebrew/cask/config.rb

-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/65296.

Don't treat non-directory arguments as paths.

---

Library/Homebrew/bottle_publisher.rb
Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/formula_info.rb
Library/Homebrew/test/bottle_publisher_spec.rb
Library/Homebrew/test/dev-cmd/pull_spec.rb
Library/Homebrew/test/formula_info_spec.rb

pull: allow to pull from merge commits

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.6.2

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.7.1

---

Library/Homebrew/cmd/install.rb

cmd/install: fix installing tap formulae with options.

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.7.2

---

Library/Homebrew/dev-cmd/ruby.rb

-----
Otherwise `brew ruby` cannot be used to skip GitHub Actions (exit status 78).

Make `brew ruby` exit with the status of the executed command.

---

Library/Homebrew/cmd/install.rb
Library/Homebrew/cmd/reinstall.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/manpages/brew.1.md.erb
Library/Homebrew/messages.rb
Library/Homebrew/test/messages_spec.rb
docs/Manpage.md
manpages/brew-cask.1
manpages/brew.1

Add HOMEBREW_DISPLAY_INSTALL_TIMES

---

Library/Homebrew/test/spec_helper.rb

Add similar logic to that for macOS.
-----

test/spec_helper: handle needs_linux.

---

Library/Homebrew/cask/cmd/upgrade.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/manpages/brew-cask.1.md
Library/Homebrew/test/cask/cmd/upgrade_spec.rb
Library/Homebrew/test/cmd/upgrade_spec.rb
docs/Manpage.md
manpages/brew-cask.1
manpages/brew.1

Add --dry-run to brew upgrade and brew cask upgrade

---

docs/FAQ.md

-----
The FAQ section about `brew cleanup` is a bit outdated given the new behavior.  This PR should help get the docs up to date.  Feel free to edit or amend this PR if you think it needs rewording or anything.

Update FAQ entry: Homebrew automatic `brew cleanup` behavior change

---

Library/Homebrew/cmd/link.rb

-----
Fix typo in `brew link --help`.

cmd/link: fix typo

---

Library/Homebrew/dev-cmd/audit.rb

Necessary for https://github.com/Homebrew/homebrew-core/pull/42851
-----

gnome_devel_whitelist: add gtk-doc 1.31

---

Library/Homebrew/utils.rb

utils: make redact_secrets handle `nil` secrets.

---

Library/Homebrew/cask/artifact/abstract_uninstall.rb

-----
Noticed this because of https://github.com/Homebrew/homebrew-cask/issues/67515.
Login items are actually localized, so removing e.g. `"Backup and Sync from Google"` would not work for me because it is localized as `"Back up & Sync von Google"`.
This adds support for 
```ruby
uninstall login_item: { path: '/Applications/Backup and Sync.app' }
```
which is now also automatically determined for all `app`s.

Support deleting login items by path.

---

Library/Homebrew/extend/os/mac/diagnostic.rb

We will be migrating Homebrew/brew to use this in the near future.
-----

os/mac/diagnostic: allow use of GitHub Actions CI.

---

.github/workflows/tests.yml
Dockerfile
Dockerfile.yml

-----
Retry https://github.com/Homebrew/brew/pull/6380 with another solution.

Try caching the Docker image.

---

Library/Homebrew/cmd/upgrade.rb

-----
Fixes Homebrew/brew#6386.

breadth-first search for dependents upgrade

---

Library/Homebrew/language/python_virtualenv_constants.rb

python_virtualenv_constants: upgrade virtualenv to 16.7.4

---

docs/New-Maintainer-Checklist.md

-----
Maintainers should generally be members, so add that to the checklist. Also add a checklist for new members, so they're properly recorded in all the places they ought to be.

New Maintainer Checklist: add guidelines for members

---

.github/workflows/apidoc.yml

-----
Update on Homebrew/brew#6418, which [needs work](https://github.com/Homebrew/brew/commit/f0f4142faae0bd43a26927c36fd2070b77b29e4a/checks).

workflows: revise `apidoc` workflow

---

Library/Homebrew/dev-cmd/pull.rb

Don't fail if we fail to parse an issue when pulling.
While we're here, do some general code cleanup of stuff that's hard to follow, named confusingly or duplicated unnecessarily.
-----

pull: fix Homebrew Testing pull regression.

---

docs/New-Maintainer-Checklist.md

-----
We just had our monthly call, but not all the maintainers are invited, so I've added it to the checklist.

New-Maintainer-Checklist: invite to monthly call

---

Library/Homebrew/cli/args.rb
Library/Homebrew/cli/parser.rb
Library/Homebrew/cmd/cat.rb
Library/Homebrew/cmd/list.rb
Library/Homebrew/cmd/log.rb
Library/Homebrew/dev-cmd/test.rb
Library/Homebrew/test/cli/parser_spec.rb

argv: move options_only to cli/args

---

Library/Homebrew/cask/pkg.rb

Add missing `require`.

---

docs/README.md

Docs: Add a link to the linuxbrew-core maintainer guide

---

Library/Homebrew/extend/os/linux/system_config.rb
Library/Homebrew/os/linux.rb

Similar to MacOS.version. A bit cleaner for us here but also plan on using this in Homebrew/homebrew-bundle.
-----

os/linux: add, use OS::Linux.os_version

---

Library/Homebrew/cask/audit.rb
Library/Homebrew/cask/blacklist.rb
Library/Homebrew/test/cask/audit_spec.rb
Library/Homebrew/test/cask/blacklist_spec.rb
Library/Homebrew/test/support/fixtures/cask/Casks/adobe-air.rb
Library/Homebrew/test/support/fixtures/cask/Casks/adobe-illustrator.rb
Library/Homebrew/test/support/fixtures/third-party/Casks/pharo.rb

-----
RE https://github.com/Homebrew/homebrew-cask/issues/58040
In some cases, certain Casks shouldn't be resubmitted for specific reasons: difficult to maintain, developers maintain their own version, ...
To make sure these cases are restricted - we can add them to a blacklist and have the blacklist checked as part of the `brew cask audit` steps.
Closes https://github.com/Homebrew/homebrew-cask/issues/58040.

Check blacklisted Casks when auditing.

---

Library/Homebrew/cli/args.rb
Library/Homebrew/cli/parser.rb
Library/Homebrew/cmd/cat.rb
Library/Homebrew/cmd/list.rb
Library/Homebrew/cmd/log.rb
Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/dev-cmd/test.rb
Library/Homebrew/reinstall.rb
Library/Homebrew/test/cli/parser_spec.rb

cli_args: Fix options_only and flags_only

---

Library/Homebrew/utils/curl.rb

-----
Fixes failure in https://github.com/Homebrew/homebrew-cask/pull/69612.

Add workaround for `curl: (56) Unexpected EOF`.

---

Library/Homebrew/dev-cmd/create.rb
Library/Homebrew/formula_creator.rb
docs/Manpage.md
manpages/brew.1

-----
PR adding `--perl` option to `create` command.
Build instructions taken from core tap and combined into somewhat universal.

create: add --perl option

---

.github/workflows/apidoc.yml

-----
This prevents the action being run in the fork, which will generate errors due to missing token.

github action: only run in the main repo

---

Library/Homebrew/cask/cmd/doctor.rb

-----
This pull request extends `brew cask doctor` to help users fix common issues with `xattr`.
CC: Homebrew/homebrew-cask#69660

Cask: add doctor check for xattr

---

Library/Homebrew/cask/cmd/style.rb
Library/Homebrew/cmd/style.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/style.rb
Library/Homebrew/system_command.rb
Library/Homebrew/test/cask/cmd/style_spec.rb
Library/Homebrew/test/cask/pkg_spec.rb
Library/Homebrew/test/cmd/style_spec.rb
Library/Homebrew/test/support/helper/cask/fake_system_command.rb
Library/Homebrew/test/system_command_result_spec.rb
Library/Homebrew/utils/gems.rb
Library/Homebrew/utils/tty.rb

-----
Added a helper function to get JSON output for `brew cask style`.

Refactor `brew style` and `brew cask style`.

---

Library/Homebrew/dev-cmd/audit.rb

audit: add gcab 1.3 to whitelist

---

Library/Homebrew/dev-cmd/man.rb
Library/Homebrew/extend/os/mac/diagnostic.rb
Library/Homebrew/system_command.rb
Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.catalina.bottle.tar.gz
Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
Library/Homebrew/test/system_command_spec.rb
Library/Homebrew/test/unpack_strategy/subversion_spec.rb

Extracted from https://github.com/Homebrew/brew/pull/6556 until Linux issues are
resolved.
-----

Ruby 2.6.3 fixes

---

.github/workflows/tests.yml
Dockerfile.yml

This has replaced the linuxbrew/brew one.
-----

.github/workflows/tests: use homebrew/brew docker image.

---

Library/Homebrew/exceptions.rb
Library/Homebrew/test/exceptions_spec.rb

-----
I ran into a frozen string literal bug.

Fix frozen string bug

---

Library/Homebrew/cmd/search.rb

-----
This PR fixes https://github.com/Homebrew/brew/issues/6584.

Remove uneeded warning when searching for a cask migrated from formula

---

Library/Homebrew/unpack_strategy/dmg.rb
Library/Homebrew/unpack_strategy/tar.rb

-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/69283.

Fix `Dmg` being detected as `Tar`.

---

Library/Homebrew/cask/cmd.rb

-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/70868.

Fix missing `command` method.

---

Library/Homebrew/cask/quarantine.rb

-----
We don't want to quarantine anything outside the scope of the directory we start quarantining from.
Fixes https://github.com/Homebrew/homebrew-cask/issues/70813.

Skip quarantining symlinks.

---

Library/Homebrew/dev-cmd/bottle.rb

bottle: do not install patchelf if --skip-relocation flag is passed

---

Library/Homebrew/cmd/vendor-install.sh

vendor-install: Add ruby bottle for aarch64

---

Library/Homebrew/rubocops/cask/homepage_url_trailing_slash.rb

-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/70949.

Fix `#match?` on `nil`.

---

Library/Homebrew/diagnostic.rb

-----
When `doctor` finds modified files, print a list of them.

doctor: list any uncommitted modified files in CI

---

Library/Homebrew/cmd/shellenv.sh

-----
Only append the current variable if it is already set.

Fix `shellenv` when using `-u`.

---

Library/Homebrew/utils/github.rb

-----
Add function for creating check runs.
@iMichka, you might also want to use this for https://github.com/Homebrew/linuxbrew-core/pull/15792.

Add `GitHub::create_check_run` function.

---

Library/Homebrew/formula_installer.rb
Library/Homebrew/utils/fork.rb

Fix RuboCop namespace.

---

Library/Homebrew/unpack_strategy/zip.rb

-----
Fixes homebrew/homebrew-cask#69879 by always keeping the last appended file.

zip: overwrite existing files

---

Library/Homebrew/cmd/vendor-install.sh

See https://github.com/Homebrew/homebrew-portable-ruby/pull/91#issuecomment-544109657

vendor-install: Update aarch64 and add armv6

---

Library/Homebrew/cask/artifact/abstract_uninstall.rb
Library/Homebrew/test/cask/artifact/shared_examples/uninstall_zap.rb
Library/Homebrew/utils/user.rb

-----
`User::automation_access?` is not working as expected, so let's print a warning after trying instead of skipping actions.

Remove `User::automation_access?`.

---

Library/Homebrew/cask/cmd/doctor.rb

-----
Fixes Homebrew/homebrew-cask#71209.

cask: fix xattr error detection

---

docs/Homebrew-on-Linux.md

-----
Just fixing a typo I noticed when reading the documentation today.

Fix a typo

---

.github/ISSUE_TEMPLATE/config.yml

ISSUE_TEMPLATE: add config.

---

Library/Homebrew/formula.rb

Don't add leading whitespace to `_JAVA_OPTIONS`.

---

completions/zsh/_brew

-----
Adds Zsh completion for `brew bump-revision`.

completions/zsh: add `brew bump-revision`

---

.github/ISSUE_TEMPLATE/New-Feature-Suggestion.md
.github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md
.github/ISSUE_TEMPLATE/config.yml

More some stuff from the templates to the chooser.
See https://github.blog/changelog/2019-10-28-new-issue-template-configuration-options/
-----

Issue template tweaks

---

Library/Homebrew/utils/curl.rb

-----
`SystemCommand` seems to choke on the binary output from `curl`, so redirect it to a file and generate the checksum from that. This also separates the header data from the actual file content.
Fixes https://github.com/Homebrew/brew/issues/6648, hopefully.

Use temp file for calculating hash.

---

docs/Homebrew-linuxbrew-core-Maintainer-Guide.md
docs/Prose-Style-Guidelines.md

-----
Wed Oct 30 17:03:48 GMT 2019
These are corrections to two typos found in the documentation.
Please clarify - most of the documents are written in American english.   Is is considered a misspelling  for  a British english spelled word?

Fix two typos

---

Library/Homebrew/cmd/--env.rb
Library/Homebrew/cmd/list.rb
docs/Bottles.md
docs/Formula-Cookbook.md
docs/Homebrew-and-Python.md
docs/Homebrew-linuxbrew-core-Maintainer-Guide.md
docs/Manpage.md
manpages/brew.1

-----
Wed Oct 30 18:05:17 GMT 2019
tl;dr:  -ize -> -ise
This PR replaces words spelt in American english with their British equivalents.

Replace American spelling with British spelling

---

Library/Homebrew/utils/gems.rb

Need to specify the executable name not variable here.
-----

utils/gems: fix finding bundler.

---

Library/Homebrew/cask/installer.rb

---
Needed for `brew cask ci` to uninstall installed dependencies.

Add helper method for cask installer to get dependencies.

---

Library/Homebrew/cask/installer.rb

-----
Fixes `brew cask ci` failures.

Ensure `@downloaded_path` is not nil.

---

Library/Homebrew/cask/macos.rb

---
These exist on a clean install.

Add `/Library/Java` subdirectories to `SYSTEM_DIRS`.

---

Library/Homebrew/dev-cmd/audit.rb

-----
Fixes https://github.com/Homebrew/brew/issues/6681

audit: improve check for forked Bitbucket repository

---

Library/Homebrew/cmd/deps.rb

We really don't need this now we've had the args refactoring.
-----

deps: refactor weird OpenStruct usage.

---

Library/Homebrew/cmd/upgrade.rb

Output more without requiring `--verbose` and update the messages to make clear what we're looking for and what we found/didn't find.
This is a little more noisy but it should help explain any delays to users and make it more obvious what's failed if something does.
-----

upgrade: tweak dependent messaging.

---

Library/Homebrew/test/cask/pkg_spec.rb
Library/Homebrew/test/spec_helper.rb
Library/Homebrew/test/unpack_strategy/subversion_spec.rb

Remove a repeatedly flaky test (https://github.com/Homebrew/brew/runs/290769077#step:5:341) and fix the subversion detection.
-----

Fix some tests

---

Library/Homebrew/cleanup.rb

This will avoid a wider degree of failures.
Fixes https://github.com/Homebrew/brew/issues/6112
-----

cleanup: rescue more cask errors.

---

Library/Homebrew/test/cmd/install_spec.rb
Library/Homebrew/test/cmd/migrate_spec.rb
Library/Homebrew/test/cmd/reinstall_spec.rb
Library/Homebrew/test/cmd/upgrade_spec.rb
Library/Homebrew/test/dev-cmd/ruby_spec.rb
Library/Homebrew/test/dev-cmd/test_spec.rb
Library/Homebrew/test/spec_helper.rb

Let's try to get these working again.
Fixes https://github.com/Homebrew/brew/issues/6579
-----

test: re-enable portable Ruby tests.

---

Library/Homebrew/dev-cmd/audit.rb

Allow `JAVA_HOME` in formulae depending on `openjdk`.

---

Library/Homebrew/cmd/upgrade.rb

'upradable' typo for 'upgradeable_dependents'

---

Library/Homebrew/cmd/upgrade.rb

I've been convinced idempotency is a good thing for this command so this would be a good thing to get out for 2.2.0.
-----

upgrade: don't error if already installed.

---

README.md

Let people know we support this now. Don't need a dedicated link because we have one at the top of the page.
-----

README: add GitHub Sponsors link.

---

Library/Homebrew/cmd/upgrade.rb

cmd/upgrade: fix exit logic.

---

Library/Homebrew/cask/cask_loader.rb

Thanks to @zachauten for https://github.com/Homebrew/brew/issues/6678#issuecomment-553696086 which was helpful in fixing this quicker.
Fixes #6678
-----

cask_loader: fix URI detection.

---

Library/Homebrew/cmd/info.rb

-----
To soIve https://github.com/Homebrew/brew/issues/6677, I add the check `args.days` and `args.category` for `brew info --analytics` to `handle extra args`.

work correctly info analysis args

---

docs/Homebrew-linuxbrew-core-Maintainer-Guide.md

-----
Updated documentation for `bump-formula-pr` changes (https://github.com/Homebrew/brew/pull/6718) and various Linuxbrew -> Linux changes that have happened (https://github.com/Homebrew/linuxbrew-core/pull/17344)

docs: New linuxbrew + bump-formula-pr changes

---

.github/workflows/tests.yml
Dockerfile.yml
Library/Homebrew/dev-cmd/install-bundler-gems.rb
Library/Homebrew/test/spec_helper.rb
docs/Manpage.md
manpages/brew.1

This will improve the output and ease of parsing while allowing code to be removed from brew-test-bot which relates only to a single repo (this one)
brew-test-bot companion PR: https://github.com/Homebrew/homebrew-test-bot/pull/299
-----

Move some brew-test-bot logic to GitHub Actions.

---

Library/Homebrew/cask/cmd/upgrade.rb

-----
This makes `brew cask upgrade` a little more robust in case of a single bad cask.

Rescue more errors during `cask upgrade`.

---

.github/workflows/tests.yml

Otherwise it can fail https://github.com/Homebrew/brew/commit/a5550aa9a9e3a7eee415981021ac1f75db34eaf2/checks

tests: set git user for update-test.

---

Library/Homebrew/utils/analytics.rb

Fixes a bug from #6639.
CC @fxcoudert @dawidd6

utils/analytics: fix refactoring rename.

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
This PR fixes `brew bump-formula-pr` for standard workflows involving forking. It's broken after the merge of this PR: https://github.com/Homebrew/brew/pull/6723
Also see this comment: https://github.com/Homebrew/brew/pull/6723#issuecomment-557796382
CC @chenrui333

bump-formula-pr: fix forking logic

---

Library/Homebrew/dev-cmd/audit.rb

audit: add libepoxy 1.5.4 to whitelist

---

Library/Homebrew/cask/audit.rb

-----
Sometimes the appcast check fails on CI (e.g. https://github.com/Homebrew/homebrew-cask/pull/73088) and we have no way of knowing why.

Show appcast contents if it doesn't contain the version.

---

.github/ISSUE_TEMPLATE/bug.md

- [n/a] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [n/a] Have you successfully run `brew style` with your changes locally?
- [n/a] Have you successfully run `brew tests` with your changes locally?
-----
Add a section for `brew config` and `brew doctor` output, which are frequently omitted from bug reports.

Issues: add section for brew config & doctor output

---

Library/.rubocop_cask.yml
Library/Homebrew/cask/cmd/style.rb
Library/Homebrew/test/cask/cmd/style_spec.rb

This was broken by a RuboCop update. As this was broken and not noticed: add tests to ensure that this can't happen in future and re-enable warnings so that users can better figure out what's gone wrong.
Fixes https://github.com/Homebrew/homebrew-cask/issues/73411
-----

Fix `brew cask style`.

---

README.md

-----
- We don't have a badge for other donation methods - this looked slightly out of place.

README: Remove Patreon badge for consistency amongst donation methods

---

Library/Homebrew/os/mac/xcode.rb

Sadly Apple don't seem to be providing these reliably.
Fixes #6796
-----

os/mac/xcode: add additional CLT download link.

---

README.md

- [y] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [y] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [y] Have you added an explanation of what your changes do and why you'd like us to include them?
- [n/a] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [n/a] Have you successfully run `brew style` with your changes locally?
- [n/a] Have you successfully run `brew tests` with your changes locally?
-----
Old link was broken. New link is the correct one.

Fixed "Project Leader" link

---

Library/Homebrew/build.rb
Library/Homebrew/cleaner.rb
Library/Homebrew/cmd/commands.rb
Library/Homebrew/cmd/doctor.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/create.rb
Library/Homebrew/dev-cmd/extract.rb
Library/Homebrew/formula_versions.rb
Library/Homebrew/os/mac/keg.rb
Library/Homebrew/os/mac/xcode.rb
Library/Homebrew/resource.rb

- [n/a] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
-----
Adds formatting to a few status messages to help distinguish them from regular output, plus some grammar fixes.

Update formatting of status messages

---

.github/workflows/tests.yml
Library/Homebrew/brew.sh
Library/Homebrew/test/dev-cmd/test_spec.rb

This should help with debugging why the `brew bundle` tests are now

.github/workflows/tests: run config, doctor.

---

Library/Homebrew/extend/os/linux/linkage_checker.rb

openjdk links against this library, which is provided by glibc.
-----

linkage_checker: whitelist libthread_db.so.1

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

fixes #6821
-----
> Have you written new tests for your changes?
Any more detailed pointers for how to do this? The command appears to have no tests at present except for argument parsing

Fix `bump-formula-pr` on a file with no tap

---

docs/Homebrew-on-Linux.md

docs/Homebrew-on-Linux: update Twitter.

---

Library/Homebrew/formula_installer.rb
Library/Homebrew/postinstall.rb

postinstall: Use CLI::Parser to parse args

---

Library/Homebrew/cmd/upgrade.rb

upgrade: make dry-run check dependents too.

---

Library/Homebrew/utils/gems.rb

This should avoid issues like those described in https://discourse.brew.sh/t/bump-pr-formula-bundler-version/6520/3
-----

utils/gems: hardcode bundler version.

---

Dockerfile

-----
The reason behind this change is described in this PR: https://github.com/Homebrew/linuxbrew-core/pull/18585.

Dockerfile: install tzdata apt package

---

Library/Homebrew/cmd/upgrade.rb

Ensure they aren't upgraded or reinstalled even if they are outdated.
Fixes #6898.
-----

cmd/upgrade: fix pinned dependent handling.

---

Library/Homebrew/diagnostic.rb

diagnostic: fix suggested origin URL.

---

Library/Homebrew/dev-cmd/test.rb
Library/Homebrew/postinstall.rb
Library/Homebrew/test.rb

Reuse `test_args` and `postinstall_args` methods

---

Library/Homebrew/dev-cmd/bottle.rb

Add environment variable to optionally run `sudo purge` a few times to potentially work around #6539.
-----

dev-cmd/bottle: add HOMEBREW_BOTTLE_SUDO_PURGE.

---

Library/Homebrew/dev-cmd/bottle.rb

This should avoid hanging if permissions are not granted.
-----

dev-cmd/bottle: run `sudo --purge` non-interactively.

---

Library/Homebrew/formula.rb

-----
Discussion [here](https://github.com/Homebrew/brew/pull/6923) and [here](https://github.com/Homebrew/homebrew-core/issues/47627).

formula: add std_go_args

---

Library/Homebrew/formula.rb

-----
Currently, we only have versions in the output. For introspection/integration reasons it'll be useful to have urls too.

Add stable url, tag and revision to json output

---

Library/Homebrew/brew.rb
Library/Homebrew/cli/parser.rb
Library/Homebrew/cmd/command.rb
Library/Homebrew/cmd/commands.rb
Library/Homebrew/commands.rb
Library/Homebrew/dev-cmd/man.rb
Library/Homebrew/global.rb
Library/Homebrew/help.rb
Library/Homebrew/test/cmd/commands_spec.rb
Library/Homebrew/test/commands_spec.rb
Library/Homebrew/utils.rb

Take two of https://github.com/Homebrew/brew/pull/6965
Reverts Homebrew/brew#6988

help: print cli/parser help message if used

---

docs/Homebrew-linuxbrew-core-Maintainer-Guide.md

[Linux] docs: We've got a new (automated) process for bottling!

---

Library/Homebrew/test/system_command_result_spec.rb

Noticed in tests for https://github.com/Homebrew/brew/pull/6996.
-----

system_command_result_spec: fix frozen objects.

---

Library/Homebrew/cmd/update.sh

This is needed for `brew test-bot` when no global Git configuration is present.
-----

update: allow setting Git name and email.

---

Library/Homebrew/cmd/upgrade.rb
Library/Homebrew/reinstall.rb

cmd/upgrade, reinstall: don't install on dry-run.

---

Library/Homebrew/formula.rb

-----
This makes non-verbose source builds a bit more informative for cmake and go formulae.

formula: don't emit standard args for cmake and go

---

Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/formula.rb
Library/Homebrew/utils/git.rb

Extract the code from `bottle.rb` into `utils/git.rb` and ensure it's run before we run tests.
Should resolve issues like in https://github.com/Homebrew/homebrew-core/pull/50328
-----

test: set Git name and email.

---

.github/workflows/tests.yml

This should avoid being spammed with failing CI runs on random forks.
-----

workflows/tests: restrict to Homebrew/brew.

---

Library/Homebrew/rubocops/urls.rb

-----
Fixes audit failure for Homebrew/homebrew-core#50604

Add ghc@8.6 to binary formula URLs whitelist

---

Library/Homebrew/dev-cmd/pull.rb

-----
Upload job on Jenkins runs on Linux and `HOMEBREW_FORCE_HOMEBREW_ON_LINUX` is set there.

pull: fix remote on jenkins

---

Library/Homebrew/cmd/upgrade.rb

- [+ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md) document?
- [+] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [+] Have you added an explanation of what your changes do and why you'd like us to include them?
- [-] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
- [+] Have you successfully run `brew style` with your changes locally?
- [+] Have you successfully run `brew tests` with your changes locally?
-----
Sometimes, when there are multiple upgraded formulae with large output, I'm confused which version will I receive after upgrade. …

Inline versions of upgraded formulae

---

Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/exceptions.rb
Library/Homebrew/formula.rb
Library/Homebrew/language/python.rb
docs/Gems,-Eggs-and-Perl-Modules.md
docs/Homebrew-and-Python.md
docs/Homebrew-homebrew-core-Merge-Checklist.md
docs/Python-for-Formula-Authors.md

brew: remove most traces of python@2

---

Library/Homebrew/language/python.rb

-----
Disclaimer: not tested at all.
Fixes #7115.

python: Fix error in virtualenv_install_with_resources

---

Library/Homebrew/keg.rb

Fixes https://github.com/Homebrew/brew/issues/7110
-----

keg: handle more exceptions on uninstall.

---

docs/Homebrew-on-Linux.md

docs/Homebrew-on-Linux.md: Use the bash installer

---

docs/README.md

-----
Case-sensitivity. :grin:

Fix broken link on docs front page

---

Library/Homebrew/patch.rb
Library/Homebrew/resource.rb

-----
Example: Homebrew/homebrew-core#51129 could be rewritten as
```rb
patch do
url "https://github.com/boostorg/boost_install/compare/52ab9149544bae82e54f600303f5d6d1dda9a4f5...a1b5a477470ff9dc2e00f30be4ec4285583b33b6.patch?full_index=1"
sha256 "fb168dd2ddfa20983b565ead86d4355c6d6e3e49bce9c2c6ab7f6e9cd9350bd4"
directory "tools/boost_install"
end
```

patch: add support for changing directory

---

docs/Rakefile

-----
Check the HTML for the usage of HTTPS.

add https checking for links

---

Library/Homebrew/language/python.rb

rewrite_python_shebang: make version part optional

---

Library/Homebrew/cmd/desc.rb

-----
Fixes the [non-working](https://discourse.brew.sh/t/cant-get-search-options-for-brew-desc-to-work/7149) `brew desc` options by changing them from flags (which take an argument) to switches (which don't) so that the search terms are always handled as named arguments.

desc: fix search options

---

Library/Homebrew/commands.rb
Library/Homebrew/dev-cmd/man.rb
Library/Homebrew/manpages/brew.1.md.erb
docs/Manpage.md
manpages/brew.1

Inspired by https://github.com/Homebrew/brew/issues/7148
Also: be more exact about global options. Make clear these don't necessarily apply to all subcommands (see https://github.com/Homebrew/brew/issues/7121).
-----

man: include full help from external commands.

---

Library/Homebrew/formulary.rb

Inspired by https://github.com/Homebrew/brew/issues/7154
-----

formulary: strengthen commit URL warning.

---

Library/Homebrew/formulary.rb

"an commit" is not valid English.
-----

formulary: fix typo.

---

Library/Homebrew/diagnostic.rb

Also look in Homebrew/homebrew-core for uncommitted files (in some ways we care about uncommitted stuff there more than Homebrew/brew). Also, list all the modified files even when on non-CI to make it easier for users to figure out their own issues and check the contents of the whole repos rather than just a subdirectory.
In general this is a cleanup that should have been done long ago (when we split Homebrew/brew and Homebrew/homebrew-core).
Inspired by https://github.com/Homebrew/brew/issues/7154.
-----

diagnostic: check homebrew-core git status.

---

Library/.rubocop.yml
Library/Homebrew/.rubocop.yml
Library/Homebrew/cask/audit.rb
Library/Homebrew/cask/cmd/list.rb
Library/Homebrew/cli/parser.rb
Library/Homebrew/cmd/gist-logs.rb
Library/Homebrew/cmd/sh.rb
Library/Homebrew/cmd/tap-info.rb
Library/Homebrew/cmd/update-report.rb
Library/Homebrew/dev-cmd/bottle.rb
Library/Homebrew/dev-cmd/bump-formula-pr.rb
Library/Homebrew/dev-cmd/bump-revision.rb
Library/Homebrew/dev-cmd/pull.rb
Library/Homebrew/extend/ENV/shared.rb
Library/Homebrew/extend/os/mac/extend/ENV/super.rb
Library/Homebrew/formula_creator.rb
Library/Homebrew/patch.rb
Library/Homebrew/requirements/java_requirement.rb
Library/Homebrew/rubocops/class.rb
Library/Homebrew/rubocops/extend/formula.rb
Library/Homebrew/style.rb
Library/Homebrew/tab.rb
Library/Homebrew/test/dev-cmd/audit_spec.rb
Library/Homebrew/utils/bottles.rb
Library/Homebrew/utils/github.rb

Update these based on autofixes and some manual fixes.
I have fixed all violations in homebrew/core (and it's caught one bug).
-----

rubocop: adjust rules.

---

Library/Homebrew/build.rb
Library/Homebrew/dev-cmd/update-test.rb
Library/Homebrew/extend/ARGV.rb
Library/Homebrew/formula.rb
Library/Homebrew/formula_installer.rb

ARGV: Deprecate ARGV.keep_tmp?

---

Library/Homebrew/build.rb
Library/Homebrew/extend/ARGV.rb

ARGV: Deprecate ARGV.ignore_deps?

---

docs/Brew-Test-Bot.md

-----
`brew-test-bot.rb` was renamed to `test-bot.rb`. This PR fixes the broken link.

docs: fix broken link

---

Library/Homebrew/dev-cmd/audit.rb

This PR addresses a [comment](https://github.com/Homebrew/homebrew-core/pull/52161#issuecomment-604616616) made by @Bo98.
-----

keg_only_whitelist: add libsigc++@2

---

Library/Homebrew/cli/args.rb
Library/Homebrew/extend/ARGV.rb
Library/Homebrew/formula_installer.rb

ARGV: Deprecate ARGV.collect_build_args

---

Library/Homebrew/os/mac/xcode.rb

-----
Fun fact: the 11.4 CLT contains the macOS 10.14 SDK despite 10.14 no longer being supported.

os/mac/xcode: support Xcode 11.4

---

Library/Homebrew/cmd/update-report.rb

-----
This occasionally caused bottle jobs to fail.

cmd/update-report: check for HOMEBREW_DISABLE_LOAD_FORMULA

---

Library/Homebrew/Gemfile.lock
Library/Homebrew/cli/args.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/extend/ARGV.rb

ARGV: Deprecate ARGV.build_stable?

---

Library/Homebrew/bintray.rb
Library/Homebrew/dev-cmd/pr-pull.rb
Library/Homebrew/utils/github.rb

pr-pull: update for GPG, various permission fixes

---

Library/Homebrew/dev-cmd/bottle.rb

Revert "bottle: author bottle commit as BrewTestBot"

---

Library/Homebrew/rubocops/urls.rb

This regex as-is will probably have too many false-positives but I think we need something that doesn't rely on x86_64 detection too.
CC @Bo98 as we talked about this for `gitversion`.
- [x Have you successfully run `brew style` with your changes locally?
-----

rubocops/urls: stricter binary URL requirements.

---

Library/Homebrew/shims/mac/super/xcrun

shims/mac/super/xcrun: set DEVELOPER_DIR less often

---

Library/Homebrew/rubocops/urls.rb

As explained in https://github.com/Homebrew/brew/pull/7256#issuecomment-607787949
Also, reorder whitelist for quicker scanning.
-----

rubocops/urls: whitelist cspice.

---

Library/Homebrew/cmd/update.sh

Fix regression from https://github.com/Homebrew/brew/pull/7260. CC @Bo98 
This code makes me sad.
-----

update: make git rebase quiet on Mojave system Git.

---

Library/.rubocop.yml

Closes https://github.com/Homebrew/brew/pull/7258
-----

rubocop.yml: enable non-default checks.

---

Library/Homebrew/cli/args.rb
Library/Homebrew/extend/ARGV.rb
Library/Homebrew/fetch.rb
Library/Homebrew/formula_installer.rb

ARGV: Deprecate ARGV.build_formula_from_source? and ARGV.build_from_source?

---

Library/Homebrew/extend/os/mac/extend/ENV/std.rb

-----
Discussion in #5068.
Related change: Homebrew/homebrew-core#52565

ENV/std: withdraw support for Homebrew supplied *.pc files

---

Library/Homebrew/cli/args.rb
Library/Homebrew/extend/ARGV.rb
Library/Homebrew/fetch.rb
Library/Homebrew/formula_installer.rb

Revert "ARGV: Deprecate ARGV.build_formula_from_source? and ARGV.build_from_source?"

---

Library/Homebrew/shims/mac/super/pkg-config

shims/mac/super/pkg-config: fix macOS <=10.13 compatibility

---

Library/Homebrew/os/mac/pkgconfig/10.14/libcurl.pc
Library/Homebrew/os/mac/pkgconfig/10.14/libexslt.pc
Library/Homebrew/os/mac/pkgconfig/10.14/libxml-2.0.pc
Library/Homebrew/os/mac/pkgconfig/10.14/libxslt.pc
Library/Homebrew/os/mac/pkgconfig/10.14/sqlite3.pc
Library/Homebrew/os/mac/pkgconfig/10.14/uuid.pc
Library/Homebrew/os/mac/pkgconfig/10.14/zlib.pc
Library/Homebrew/os/mac/pkgconfig/10.15/libcurl.pc
Library/Homebrew/os/mac/pkgconfig/10.15/libexslt.pc
Library/Homebrew/os/mac/pkgconfig/10.15/libxml-2.0.pc
Library/Homebrew/os/mac/pkgconfig/10.15/libxslt.pc
Library/Homebrew/os/mac/pkgconfig/10.15/sqlite3.pc
Library/Homebrew/os/mac/pkgconfig/10.15/uuid.pc
Library/Homebrew/os/mac/pkgconfig/10.15/zlib.pc

os/mac/pkgconfig: supply default homebrew_sdkroot

---

Library/Homebrew/dev-cmd/bump-formula-pr.rb

-----
Fix for "undefined method 'env_token' for GitHub:Module" in `bump-formula-pr` following #7285.

bump-formula-pr: use Homebrew::EnvConfig

---

Library/Homebrew/rubocops/uses_from_macos.rb

-----
See https://github.com/Homebrew/homebrew-core/pull/52658
And sort list alphabetically

Library/Homebrew/rubocops/uses_from_macos: add ssh-copy-id

---

Library/Homebrew/extend/os/mac/extend/ENV/super.rb
Library/Homebrew/formula.rb
Library/Homebrew/os/linux.rb
Library/Homebrew/os/mac.rb
Library/Homebrew/os/mac/sdk.rb

-----
Some refactoring of the SDK root selection code to allow it to be reused in `std_cmake_args`.

formula: make CMake SDK root choice consistent with superenv (+ SDK root refactoring)

---

Library/Homebrew/rubocops/lines.rb

-----
Just ran into this when bumping, nettle is a "Low-level cryptographic library"

Audit: allow make check for nettle

---

Library/Homebrew/env_config.rb
bin/brew
docs/Manpage.md
manpages/brew.1

Trying a revert to see if this resolves issues with the default configuration.
Reverts Homebrew/brew#7275

Revert "Set HOMEBREW_GITHUB_API_TOKEN from GITHUB_TOKEN."

---

Library/Homebrew/os/mac/xcode.rb

Explain when these various versions should (and should not) be bumped and provide a method to avoid people having to schlep through the Apple Developer site unless they really want to.
Also, while we're here, DRY things up and reorder to "newest first".
-----

os/mac/xcode: better document upgrade.

---

Library/Homebrew/extend/os/mac/extend/ENV/super.rb

-----
We'll have to think of another way to do this if build systems aren't able to pick our shim up.

ENV/super: don't set PKG_CONFIG

---

Library/Homebrew/test/spec_helper.rb

-----
Always restore `stdout/stderr` and complain about unwanted `SystemExit`s.

Improve spec helper.

---

Library/Homebrew/extend/os/mac/extend/ENV/std.rb

-----
This is just something I forgot to revert at the same time as Homebrew/homebrew-core#52641 a few days ago. This is separate from the other issues I dealt with today.

Revert "ENV/std: withdraw support for Homebrew supplied *.pc files"

---

Library/Homebrew/cmd/link.rb

Looks like a typo from previous commit.
-----

Fix KegOnlyReason property access.

---

Library/.rubocop.yml
Library/.rubocop_audit.yml
Library/.rubocop_rspec.yml
Library/Homebrew/cmd/style.rb
Library/Homebrew/dev-cmd/audit.rb
Library/Homebrew/rubocops/class.rb
Library/Homebrew/rubocops/formula_desc.rb
Library/Homebrew/rubocops/lines.rb
Library/Homebrew/rubocops/options.rb
Library/Homebrew/rubocops/patches.rb
Library/Homebrew/rubocops/text.rb
Library/Homebrew/style.rb
Library/Homebrew/test/.rubocop_todo.yml
Library/Homebrew/test/cmd/style_spec.rb
Library/Homebrew/test/rubocops/class_spec.rb
Library/Homebrew/test/rubocops/formula_desc_spec.rb
Library/Homebrew/test/rubocops/lines_spec.rb

I noticed that `brew style` wasn't actually running any of our custom cops. Fixed this and tweaked various cops so that (after my open PRs are merged) Homebrew/homebrew-core won't have any `brew style` violations.
-----

`brew style` fixes

---

docs/Releases.md

Update with and based on the release process video I recorded.
-----

docs/Releases: various updates.

---

Library/Homebrew/utils/github.rb

-----
`gtk+3` gets interpreted as `gtk 3`. Instead, let's send `gtk%2B3`.

utils/github: form encode workflow branch

---

Library/Homebrew/download_strategy.rb

-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/79499.

Delete trailing `;` in Content-Disposition header.

---

Library/Homebrew/dev-cmd/extract.rb

dev-cmd/extract: instruct users to run git fetch unshallow

---

Library/Homebrew/cmd/upgrade.rb

cmd/upgrade: handle nil runtime_dependencies.

---

Library/Homebrew/dev-cmd/audit.rb

-----
This PR adds a check whether a GitHub release is a draft or not (extends https://github.com/Homebrew/brew/pull/7231)

audit: add draft release detection

---

Library/Homebrew/formula_cellar_checks.rb

-----
I can't realistically test everything, but I ran `brew list | xargs -n 1 brew audit --only=installed` and got:
```
gcc:
* Files were found with references to the Homebrew shims directory.
The offending files are:
libexec/gcc/x86_64-apple-darwin18/9.3.0/install-tools/fixincl
Error: 1 problem in 1 formula detected
ilmbase:
* Files were found with references to the Homebrew shims directory.
The offending files are:
share/ilmbase/IexMath/CMakeFiles/IexMath.dir/link.txt
share/ilmbase/IexMath/CMakeFiles/IexMath.dir/build.make
share/ilmbase/IexMath/CMakeFiles/IexMath.dir/flags.make
share/ilmbase/IlmThread/CMakeFiles/IlmThread.dir/link.txt
share/ilmbase/IlmThread/CMakeFiles/IlmThread.dir/build.make
share/ilmbase/IlmThread/CMakeFiles/IlmThread.dir/flags.make …
```

formula_cellar_checks: check for shim dir references

---

.github/workflows/tests.yml

https://github.com/Homebrew/brew/runs/595913492
https://github.com/Homebrew/brew/pull/7379
-----

workflows: fix docker tag

---

.github/workflows/tests.yml

-----
This fixes issues with `brew update-tests` on GitHub Actions CI when clicking the "rerun" button rather than forcing a synchronize event via force-pushing.

workflows: don't use actions/checkout

---

Library/Homebrew/dev-cmd/pull.rb
README.md
docs/Manpage.md
manpages/brew.1

- remove Jenkins Testing support from `brew pull`
- update reference to MacStadium Orka
- remove reference to DigitalOcean
---
-----

Remove last Jenkins references

---

Library/Homebrew/cleanup.rb
Library/Homebrew/cmd/cleanup.rb
Library/Homebrew/env_config.rb
docs/Manpage.md
manpages/brew.1

cleanup: all configuring max age days.

---

Library/Homebrew/rubocops/uses_from_macos.rb
Library/Homebrew/test/support/helper/spec/shared_examples/formulae_exist.rb

Also, provide details on how to update this in future and split it into two.
Fixes #7396
-----

rubocops/uses_from_macos: update list.

---

Library/Homebrew/dev-cmd/pr-upload.rb
Library/Homebrew/test/dev-cmd/pr-upload_spec.rb
docs/Manpage.md
manpages/brew.1

As a replacement for `brew test-bot --ci-upload` and per suggestion on Slack.
-----

Add pr-upload command

---

.github/workflows/tests.yml

If it's not there: setup Linuxbrew but reuse the checkout.
-----

workflows/tests: allow missing system Linuxbrew.

---

Library/Homebrew/dev-cmd/audit.rb

dev-cmd/audit: fix false openssl@1.1 versioned formula audit

---

.github/workflows/tests.yml

This is failing `brew doctor` on GitHub Actions.
-----

workflows/tests: link old gettext.

---

Library/Homebrew/bintray.rb

-----
Minor code style fixed as suggested in https://github.com/Homebrew/brew/pull/7415#discussion_r412193959

bintray: fix style

---

completions/bash/brew

completions/bash: add missing flags for create

---

Library/Homebrew/cmd/list.rb

cmd/list: fix Hombrew typo

---

Library/Homebrew/dev-cmd/bump-revision.rb

-----
This PR reverts https://github.com/Homebrew/brew/pull/7316 and re-applies https://github.com/Homebrew/brew/pull/7431
Ref: https://github.com/Homebrew/brew/pull/7431#issuecomment-619556672

bump-revision: re-apply proper fix for handling stable block

---

Library/Homebrew/os/mac/pkgconfig/10.10/libedit.pc
Library/Homebrew/os/mac/pkgconfig/10.11/libedit.pc
Library/Homebrew/os/mac/pkgconfig/10.12/libedit.pc
Library/Homebrew/os/mac/pkgconfig/10.13/libedit.pc
Library/Homebrew/os/mac/pkgconfig/10.14/libedit.pc
Library/Homebrew/os/mac/pkgconfig/10.15/libedit.pc
Library/Homebrew/os/mac/pkgconfig/10.9/libedit.pc

-----
Needed for dnsdist 1.4.0.

os/mac/pkgconfig: add libedit.pc

---

Library/Homebrew/os/mac/pkgconfig/10.10/ncurses.pc
Library/Homebrew/os/mac/pkgconfig/10.10/ncursesw.pc
Library/Homebrew/os/mac/pkgconfig/10.11/ncurses.pc
Library/Homebrew/os/mac/pkgconfig/10.11/ncursesw.pc
Library/Homebrew/os/mac/pkgconfig/10.12/ncurses.pc
Library/Homebrew/os/mac/pkgconfig/10.12/ncursesw.pc
Library/Homebrew/os/mac/pkgconfig/10.13/ncurses.pc
Library/Homebrew/os/mac/pkgconfig/10.13/ncursesw.pc
Library/Homebrew/os/mac/pkgconfig/10.14/ncurses.pc
Library/Homebrew/os/mac/pkgconfig/10.14/ncursesw.pc
Library/Homebrew/os/mac/pkgconfig/10.15/ncurses.pc
Library/Homebrew/os/mac/pkgconfig/10.15/ncursesw.pc
Library/Homebrew/os/mac/pkgconfig/10.9/ncurses.pc
Library/Homebrew/os/mac/pkgconfig/10.9/ncursesw.pc

-----
Needed for Homebrew/homebrew-core#49410.

os/mac/pkgconfig: add ncurses.pc & ncursesw.pc

---

.github/workflows/tests.yml

This should save about a minute for each CI run.
-----

workflows/tests: cache RubyGems.

---

Library/Homebrew/os/mac/pkgconfig/10.10/expat.pc
Library/Homebrew/os/mac/pkgconfig/10.11/expat.pc
Library/Homebrew/os/mac/pkgconfig/10.12/expat.pc
Library/Homebrew/os/mac/pkgconfig/10.13/expat.pc
Library/Homebrew/os/mac/pkgconfig/10.14/expat.pc
Library/Homebrew/os/mac/pkgconfig/10.15/expat.pc
Library/Homebrew/os/mac/pkgconfig/10.9/expat.pc

-----
Could be used here: https://github.com/Homebrew/homebrew-core/blob/f8e1d07c165513eeeca97c7b75eda4d25e88f9ac/Formula/dbus.rb#L38-L40

os/mac/pkgconfig: add expat.pc

---

Library/Homebrew/os/linux.rb

This allows formulae with this to be read on Linux.
-----

os/linux: add MacOS::CLT.version.

---

.github/workflows/tests.yml

Doesn't need to be a separate step.
-----

workflows/tests: simplify PATH setup.

---

Library/Homebrew/hardware.rb

-----
I forgot to have this CPU family list in the last [PR](https://github.com/Homebrew/brew/pull/7465).

Update Hardware::CPU.oldest_family with ppc64

---

Library/Homebrew/dev-cmd/test.rb
Library/Homebrew/formula_installer.rb
Library/Homebrew/sandbox.rb
Library/Homebrew/test/sandbox_spec.rb

Remove unused code and methods.
-----

Cleanup Sandbox code

---

docs/Homebrew-on-Linux.md

docs/Homebrew-on-Linux.md: Requirements

---

Dockerfile

Dockerfile: restore git-core PPA

---

Library/Homebrew/test/.rubocop_todo.yml
Library/Homebrew/test/cmd/deps_spec.rb

This was added to (all, I checked) other specs but missing here.
-----

deps_spec: check args.

---

.github/workflows/docker.yml

docker.yml: Deploy the tagged image to Docker Hub

---

.github/workflows/docker.yml

-----
Typo introduced in PR #7494.

docker.yml: Fix a typo

---

Library/Homebrew/extend/os/mac/software_spec.rb
Library/Homebrew/test/os/mac/formula_spec.rb

-----
When applied to multiple specs, the bounds hash may be modified and cause errors for subsequent specs.
The other 6 tests weren't sufficient to catch this so I've added another 2.

os/mac/software_spec: fix argument error in valid  use case

---

Library/Homebrew/cli/args.rb

This got autofixed by RuboCop but looks weird.
-----

cli/args: cleanup weird style.

---

Library/Homebrew/cmd/shellenv.sh
docs/Manpage.md
manpages/brew-cask.1
manpages/brew.1

shellenv: recommend .bash_profile

---

Library/Homebrew/cli/args.rb
Library/Homebrew/cli/parser.rb
Library/Homebrew/test/cmd/install_spec.rb

Fix breaking options on taps again (second time in two weeks, sob).
To avoid doing this again: also add a test for this case (that I've verified would have caught these cases).
Fixes https://github.com/Homebrew/brew/issues/7517
-----

cli: fix options handling.

---

Library/Homebrew/development_tools.rb

-----
Double digit strikes again.

development_tools: fix GCC 10 version detection

---

Library/Homebrew/bintray.rb
Library/Homebrew/dev-cmd/mirror.rb
Library/Homebrew/software_spec.rb

-----
There is no guarantee that what we are passing here is URL safe. Therefore, we should URL encode the input.

bintray: url encode where needed

---

docs/How-to-Create-and-Maintain-a-Tap.md

Explain our policies around "Official Vendor Taps" and clarify the formulae naming section.
Inspired by discussion in https://discourse.brew.sh/t/maintenance-of-formulas-by-vendor/7649/.

docs/How-to-Create-and-Maintain-a-Tap: official vendor taps.

---

.github/workflows/docker.yml
.github/workflows/tests.yml

-----
Fix second `docker tag` in workflow.
#7543

workflows: fix docker hub pushing

---

docs/Formula-Cookbook.md

- [n/a; documentation] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
-----

Document how to use test fixtures

---

docs/New-Maintainer-Checklist.md

This is needed for @Bo98 to get access to GitHub Actions shared runners.
CC @Homebrew/plc FYI.
-----

docs/New-Maintainer-Checklist: clarify ops can get owner.

---

Library/Homebrew/utils/analytics.rb

Check we have a non-empty `options` and convert them all to human readable strings.
-----

utils/analytics: fix options reporting.

---

Library/Homebrew/os/linux/glibc.rb

-----
Syncing Homebrew/brew with https://docs.brew.sh/Homebrew-on-Linux#requirements

os/linux/glibc.rb: up minimum glibc version to 2.13

---

Library/Homebrew/formula_installer.rb
Library/Homebrew/utils/analytics.rb

This should improve the output in analytics.
-----

formula_installer: pass display_options to BuildError.
