Homebrew/brew

docs/Formula-Cookbook.md
=> docs: mention that bin.install can rename file

docs/Formula-Cookbook.md
=> Specify the stance on mocks in test blocks

Library/Homebrew/extend/ENV/shared.rb, Library/Homebrew/extend/os/linux/extend/ENV/shared.rb, Library/Homebrew/formula_installer.rb
=> bottle_arch: ensure a symbol is used when needed.

.github/workflows/tests.yml, Library/Homebrew/diagnostic.rb
-----
`brew doctor` shows installed and deleted formulae.
The related issue is https://github.com/Homebrew/brew/issues/7139
=> brew doctor shows deleted formulae

Library/Homebrew/cask/cmd/abstract_command.rb, Library/Homebrew/cask/cmd/info.rb, Library/Homebrew/test/cask/cmd/info_spec.rb, Library/Homebrew/utils/analytics.rb
- [] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/PATH_spec.rb).
-----
This PR contains that add analytics info to the `brew cask info` command.
Fixes #7566
=> Added analytics for cask info

Library/Homebrew/dev-cmd/audit.rb
This check can't really be in RuboCop (as it relies on the URL strategy logic).
-----
=> audit: remove incorrect TODO.

Library/Homebrew/extend/os/mac/diagnostic.rb
As seen in https://github.com/Homebrew/brew/issues/7605.
-----
=> os/mac/diagnostic: suggest untapping phinze/cask.

completions/zsh/_brew_cask
-----
Purpose is to increase the speed of brew cask install completions
=> add compsys cache for brew casks

Library/Homebrew/formula_installer.rb
-----
Another case where we want to evaluate the other `if` conditions.
Homebrew/homebrew-core#55001
=> formula_installer: fix already-satisfied test deps not being pruned

Library/Homebrew/formula_installer.rb
-----
This check doesn't have anything to do with whether the requirement itself is a build/test requirement so split it from that logic.
Summer project: write tests for all this.
Fixes #7618.
=> formula_installer: fix build/test reqs not being pruned correctly

Library/Homebrew/cask/cmd.rb, Library/Homebrew/cask/cmd/help.rb
-----
Needed to display the usage information being added in https://github.com/Homebrew/brew/pull/7427.
=> Implement `brew cask help <command>`.

.github/workflows/docker.yml
-----
This tag was unintentionally omitted.
=> docker.yml: Tag homebrew/brew:$brew_version

Library/Homebrew/cmd/info.rb
=> cmd/info: fix missing formula reference.

Dockerfile
=> Dockerfile: Unset gc.auto and homebrew.devcmdrun

Library/Homebrew/dev-cmd/tap-new.rb, Library/Homebrew/manpages/brew.1.md.erb, docs/Manpage.md, docs/Tips-N'-Tricks.md, manpages/brew.1
This is deprecated in #7660.
-----
=> manpage: no longer mention installing from a URL.

Library/Homebrew/dev-cmd/audit.rb
-----
Needed for Homebrew/homebrew-core#54912.
=> dev-cmd/audit: whitelist python@3.8 to be non-keg-only

README.md
-----
This PR renames a section in README.md from `Who Are You?` to `Who We Are`.
The current wording confuses me a bit (because it's not clear whether "you" refers to a reader or an author).
If it's only me, I'm ok with keeping it as it is 🙂
=> Readme: tweak wording

Library/Homebrew/dev-cmd/audit.rb
=> dev-cmd/audit: handle nil newest_committed_revision.

Library/Homebrew/formula.rb, docs/Formula-Cookbook.md, docs/How-To-Open-a-Homebrew-Pull-Request.md
Update the documentation to be consistent with #7688.
-----
=> Adjust documentation for `devel` deprecation.

Library/Homebrew/dev-cmd/pr-pull.rb
-----
Currently, when using `brew pr-pull`, `brew pr-publish` or the automerge workflow, git trailers such as Co-authored-by are not properly handled. This leads to a poor contributor experience as the GitHub UI doesn't properly credit a coauthored commit as such unless all the trailers occur in a block at the end of the commit message.
Proper attribution looks something like this message: https://github.com/Homebrew/homebrew-core/commit/96a529a2fac8a52a1f707c40d00c1440a41c791a
This commit had multiple authors, but only the initial author is credited in the interface: https://github.com/Homebrew/homebrew-core/commit/853d169e4bc0fc5214556de6e6226bcbbb9adf9a
This pull request modifies `brew pr-pull` to detect trailers and rearrange them so that they all occur at the end of the commit …
=> pr-pull: preserve trailers when signing off commit

Library/Homebrew/extend/os/linux/resource.rb, Library/Homebrew/extend/os/mac/resource.rb, Library/Homebrew/extend/os/resource.rb, Library/Homebrew/formula.rb, Library/Homebrew/resource.rb, Library/Homebrew/test/os/linux/formula_spec.rb, Library/Homebrew/test/os/mac/formula_spec.rb
=> on_os blocks: resources, patches

Library/Homebrew/utils/ruby.sh
-----
Update `test-ruby` function to match the version in Homebrew/install that evolved from the one here based on the received suggestions.
=> utils/ruby.sh: update `test-ruby` (and rename to test_ruby)

Library/Homebrew/tap.rb
=> tap: check for invalid fetched tap name.

Library/Homebrew/compat/language/java.rb, Library/Homebrew/extend/os/mac/language/java.rb, Library/Homebrew/extend/pathname.rb, Library/Homebrew/language/java.rb
-----
I've been meaning to do this for a while.
This modifies `Language::Java` to also search for the OpenJDK formulae. This thus fixes `Pathname#write_jar_script` to also work when depending on the OpenJDK formula.
=> language/java: add support for OpenJDK

Library/Homebrew/rubocops/uses_from_macos.rb
=> uses_from_macos: allow ed

Library/Homebrew/cask/audit.rb, Library/Homebrew/test/cask/audit_spec.rb
-----
This will make the audit command catch almost all cases described in https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md only the cases with vague exceptions are left out.
=> cask: codify the token rules

Library/Homebrew/cask/audit.rb, Library/Homebrew/test/cask/audit_spec.rb
-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/81802
=> Audit cask language locales

Library/Homebrew/bintray.rb, Library/Homebrew/dev-cmd/mirror.rb, Library/Homebrew/dev-cmd/pr-pull.rb
-----
Closes: https://github.com/Homebrew/brew/issues/7708
Don't know if it is the correct implementation here. The code is basically taken from `brew pull` source.
Also it isn't tested yet, don't know how to bite it.
=> bintray: automatically run brew mirror if needed

docs/Maintainer-Guidelines.md
-----
- Thanks to #7709, we've saved some maintainer time from doing this manually.
- To check that it's working, search for "Mirrored <formula_name>" in the CI log output for the publish bottles action for relevant formulae like ImageMagick in the future.
=> docs/Maintainer-Guidelines: Reflect `brew mirror` now being automatic

.gitignore, Library/Homebrew/Gemfile, Library/Homebrew/os/linux/elf.rb, Library/Homebrew/os/linux/global.rb
-----
~~0) `patchelf` is added to Gemfile.~~
1) if env variable  `HOMEBREW_PATCHELF_RB`  is set, 
then patchelf(library)  will be used to determine 
the required libraries and whether the ELF is a dynamic elf or not.
~~Tests will be added soon(lagging behind in time :( ~~
Adding tests in next pull request.
=> needed libraries and dynamic_elf? check using readelf.rb(patchelf gem).

Library/Homebrew/compat/language/java.rb, Library/Homebrew/extend/os/mac/language/java.rb, Library/Homebrew/extend/pathname.rb, Library/Homebrew/language/java.rb
-----
I'll try be around in the few days after merge this time round.
Tested with `jenkins` and `bnd`.
=> language/java: add support for OpenJDK formula

Library/Homebrew/os/mac/xcode.rb
=> os/mac/xcode: support Xcode 11.5

Library/Homebrew/formula.rb, Library/Homebrew/formula_creator.rb, Library/Homebrew/rubocops/text.rb, Library/Homebrew/test/rubocops/text_spec.rb
-----
The primary motivation behind this is reducing the effort required to create formulas for tools written in Rust in a similar vein with #6938
=> formula: add std_cargo_args

docs/FAQ.md
I propose changing 'Why haven’t you pulled my pull request?' to 'Why haven’t you merged my pull request?' as, unless I'm missing a trick, this wording would fit more appropriately with what the question trying to ask?
-----
=> 'Why haven’t you pulled my pull request?' change

Library/Homebrew/os/mac/version.rb
=> OS::Mac::Version: add Big Sur

Library/Homebrew/install.rb
-----
ARM Macs exist now! We need to permit those too.
=> Install: permit ARM-based Macs

Library/Homebrew/test/support/fixtures/cask/Casks/with-depends-on-macos-comparison.rb
=> Fix test cask macOS dependency

Library/Homebrew/os/mac/xcode.rb
https://github.com/Homebrew/brew/pull/7806#issuecomment-648154860
CC @Bo98
-----
=> os/mac/xcode: add Big Sur clang versions.

Library/Homebrew/extend/os/mac/extend/ENV/std.rb, Library/Homebrew/os/mac.rb, Library/Homebrew/shims/super/cc
-----
Just something I visually spotted.
=> os/mac: fix for major versions other than 10

Library/Homebrew/os/mac/pkgconfig/10.15/expat.pc
-----
This library was updated from 2.2.6 to 2.2.8 in a minor release: macOS 10.15.2.
=> os/mac/pkgconfig/10.15/expat: update version to 2.2.8

Library/Homebrew/os/mac/version.rb
-----
XCode checks for "11.0" not "11.00".
https://github.com/Homebrew/brew/blob/9788735eb2de07c175b4c99b1e51091dbec01c37/Library/Homebrew/os/mac/xcode.rb#L18
=> OS::Mac::Version: Change 11.00 to 11.0

Library/Homebrew/rubocops/lines.rb, Library/Homebrew/test/rubocops/lines_spec.rb
-----
Audit requires using `Utils.safe_popen_read` and `Utils.safe_popen_write` instead of `Utils.popen_read` and `Utils.popen_write` respectively.
Using the "safe" version means that an error will be shown if the command fails. Previously, when using `popen_read`, a failed command could go unnoticed and have negative consequences that go undetected (as seen in [pipenv](https://github.com/Homebrew/homebrew-core/pull/55682))
=> Use Utils.safe_popen_read instead of Utils.popen_read

Library/Homebrew/linkage_checker.rb
-----
From [macOS Big Sur 11 Beta Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes):
> New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)
=> linkage_checker: handle system libraries on Big Sur

Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.big_sur.bottle.tar.gz, Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.big_sur_arm.bottle.tar.gz
-----
https://github.com/davidfstr/rdiscount/pull/142 is still a blocker for actually running the tests (or anything else that that invokes an install of bundler gems), but this pull request will be needed once that upstream problem is fixed.
=> test/support/fixtures/bottles: add Big Sur fixtures

Library/Homebrew/dev-cmd/create.rb, Library/Homebrew/formula_creator.rb, completions/bash/brew, docs/Manpage.md, manpages/brew.1
-----
Enable easy creation of formula for tools implemented in Crystal.
=> create: add --crystal option

Library/Homebrew/cmd/--cache.rb, Library/Homebrew/dev-cmd/mirror.rb, Library/Homebrew/dev-cmd/pr-pull.rb, Library/Homebrew/dev-cmd/pr-upload.rb, Library/Homebrew/help.rb, Library/Homebrew/utils.rb, docs/Manpage.md, manpages/brew.1
-----
Relocated the trimming of leading whitespace to fix comment help output, plus some other minor text improvements.
=> docs: fixes for help output

Library/Homebrew/cmd/install.rb, Library/Homebrew/formulary.rb
The error message might be useless alone
-----
=> install: add backtrace on failure

Library/Homebrew/dev-cmd/bump-formula-pr.rb, Library/Homebrew/exceptions.rb, Library/Homebrew/utils/github.rb
-----
Related issue: https://github.com/Homebrew/brew/issues/7744
Example to test functionality: `brew bump-formula-pr fio --url https://github.com/axboe/fio/archive/fio-3.20.tar.gz -n`
=> bump-formula-pr: search for closed dupe PRs

Library/Homebrew/dev-cmd/audit.rb
Discussion in Homebrew/homebrew-core#57082
=> Throttle balena-cli version bumps

Library/Homebrew/cmd/readall.rb, Library/Homebrew/extend/os/linux/readall.rb, Library/Homebrew/extend/os/readall.rb, Library/Homebrew/readall.rb, Library/Homebrew/test/cmd/search_spec.rb, Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb, docs/Manpage.md, manpages/brew.1
-----
@MikeMcQuaid this should allow syntax checks for casks in CI
=> Support casks in readall

Library/Homebrew/extend/os/mac/diagnostic.rb, Library/Homebrew/os/mac.rb, Library/Homebrew/os/mac/sdk.rb, Library/Homebrew/os/mac/xcode.rb
-----
This should cover cases that would result in `NoMethodError: undefined method 'path' for nil:NilClass`.
The check ensures a supported SDK is available. If not, it advises the user to update or uninstall CLT/Xcode.
=> Add SDK availability diagnostic

Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/test/dev-cmd/audit_spec.rb
-----
relates to 
- https://github.com/Homebrew/homebrew-core/pull/57237
- https://github.com/Homebrew/homebrew-core/pull/57242
cc @Bo98
=> disable license check for new formulae

.github/codecov.yml, Library/Homebrew/test/.codecov.yml
>  the file must still be located in the root, dev/, or .github/ directories
https://docs.codecov.io/docs/codecov-yaml#can-i-name-the-file-codecovyml
CC @bo98
-----
=> Move .codecov.yml

Library/Homebrew/missing_formula.rb
relates to Homebrew/homebrew-core#57029, Homebrew/homebrew-core#57494
-----
cc @gromgit @alebcay
=> Remove cargo-completion formula

Library/Homebrew/formula.rb
=> formula: fix link_overwrite?

Library/Homebrew/rubocops/uses_from_macos.rb
=> uses_from_macos: allow cpio

Library/Homebrew/brew.sh, Library/Homebrew/style.rb, Library/Homebrew/utils/ruby.sh, bin/brew
Ensure that `shellcheck` is run by `brew style` again and fix the various failures.
-----
=> style: re-enable shellcheck.

.github/workflows/tests.yml
Investigated a full uninstall but it takes too long (>5m).
-----
=> workflows/tests: link python@3.8.

Library/Homebrew/rubocops/uses_from_macos.rb
=> uses_from_macos: move cpio to shadowed by macos list

Library/Homebrew/formula.rb
-----
Before:
```
[#<Pathname:/usr/local/Cellar/python@3.8/3.8.3_1>]
```
After:
```
[#<Pathname:/usr/local/Cellar/python@3.8/3.8.3_1>, #<Pathname:/usr/local/Cellar/python/3.7.8>]
```
=> formula: consider aliases in installed_prefixes

Library/Homebrew/keg.rb
We did these for opt symlinks already but not linkedkegs.
-----
=> keg: unlink alias linkedkegs.

Library/Homebrew/formula_installer.rb
-----
Fixes a cross-device link error if the two locations are on separate partitions.
=> formula_installer: mv rather than rename on link_overwrite

Library/Homebrew/formula.rb
Add and use a `possible_names` method to find a linked keg based on an old name or alias.
Use this both for `link_overwrite` and for `linked_keg` (which is what `brew upgrade` uses to find outdated kegs).
-----
=> formula: look harder for a linked keg.

Library/Homebrew/cleanup.rb
It may have been already cleaned up by an earlier step.
-----
=> cleanup: check path exists before cleanup.

Library/Homebrew/cask/cmd/list.rb, Library/Homebrew/test/cask/cmd/list_spec.rb
-----
This allows people to get a list of all installed casks through JSON and cleans up in the process
=> cask: add list --json

docs/Homebrew-linuxbrew-core-Maintainer-Guide.md
-----
Update some documentation for Homebrew/linuxbrew-core maintenance. Specifically:
* We don't really worry about CI timeouts now.
* CI checks on merge commits should succeed.
* `brew pull` is going away, so just recommend a friendly `git push`.
* If someone else has pushed, redo the merge iwth `git rebase --rebase-merges`, or just rerun `brew merge-homebrew --core`.
=> docs: Update Linux core merge guidelines.

Library/Homebrew/Gemfile, Library/Homebrew/os/linux/elf.rb
-----
`.elf` was introduced in gem release v1.1.0.
Resolves  https://github.com/Homebrew/brew/pull/7678#discussion_r442090941
=> Replace instance variable access with call to .elf.

Library/Homebrew/brew.rb, Library/Homebrew/brew.sh
-----
This changed recently for some reason.
=> Adjust container checks for GitHub Actions changes

Library/Homebrew/data/spdx.json
=> data/spdx.json: update

Library/Homebrew/formula.rb
-----
Previously RuboCop counted the class length as 1400 lines - right at the limit. I've reduced that slightly to 1373.
We still clearly need to do something bigger like #7984, but the intention of this PR is to unblock some other PRs in the meantime - particularly if we happen to need to land a bugfix.
=> formula: minor refactor to reduce line count

docs/Taps.md
Since shallow cloning is now neither recommended nor the default, I've removed all mentions of cloning type.
-----
=> Taps.md: Update cloning details

Library/Homebrew/sorbet/files.yaml
-----
Set the following files to true in sorbet/files.yaml:
- ./cleaner.rb
- ./compilers.rb
- ./dependency_collector.rb
- ./description_cache_store.rb
- ./descriptions.rb
- ./env_config.rb
=> sorbet/files.yaml: set multiple files to true

.github/workflows/spdx.yml, .github/workflows/tests.yml, Library/Homebrew/dev-cmd/update-license-data.rb, docs/Manpage.md, manpages/brew.1
-----
Like Dependabot, but for data/spdx.json.
Currently set up to run every 12 hours, with the commit author being BrewTestBot.
=> workflows: auto create PRs for license data updates

.github/workflows/spdx.yml
-----
The current crontab means "[At every minute past every 12th hour](https://crontab.guru/#*_*/12_*_*_*)". This changes it to be every 12 hours.
=> workflows: fix crontab

Library/Homebrew/cleanup.rb
-----
I noticed this wasn't getting cleaned in CI.
=> cleanup: clean go_mod_cache

Library/Homebrew/sorbet/files.yaml, Library/Homebrew/sorbet/rbi/homebrew.rbi
-----
Set the following files to true in sorbet/files.yaml:
- ./fetch.rb
- ./formula_pin.rb
- ./hardware.rb
- ./help.rb
- ./language/go.rb
- ./language/java.rb
- ./language/perl.rb
- ./messages.rb
=> sorbet: set multiple files to true

Library/Homebrew/Gemfile, Library/Homebrew/Gemfile.lock
-----
Includes patchelf.rb and its deps in Gemfile.lock .
Request @ 
https://github.com/Homebrew/brew/pull/7996#issuecomment-657922970
cc @jonchang @MikeMcQuaid @sjackman @woodruffw
=> include  patchelf.rb and its deps in Gemfile.lock

Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/test/dev-cmd/audit_spec.rb, Library/Homebrew/utils/notability.rb
-----
Since we require all software to be maintained we should avoid archived repos. This will warn about that.
=> audit: error on archived repos

Library/Homebrew/utils/notability.rb
=> notability: fix variable names

Library/Homebrew/cmd/update-report.rb
-----
This pull request disables verbose reporting of new formula versions when automatically updating before `brew install`.
Homebrew has a perceived reputation for being extremely slow, even when the cause is more likely the fault of inconsistent network connections or fundamental limitations on the speed of unpacking large tarballs to disk. A [quick search on Twitter](https://twitter.com/search?q=%22Updating%20Homebrew%22&src=typed_query&f=live) or this issue tracker (e.g. https://github.com/Homebrew/brew/issues/6490) confirms this perception.
When running `brew install wget` Homebrew will automatically run a `brew update` to ensure that users will get the newest packages, and often this is because maintainers have fixed an outstanding bug, so it's easy to see why this was implemented. …
=> update-report: speed up automatic updates

Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/test/dev-cmd/audit_spec.rb
-----
Required for Homebrew/homebrew-core#58190
=> dev-cmd/audit: add libressl to uses_from_macos allow list

Library/Homebrew/cmd/uses.rb, docs/Manpage.md, manpages/brew.1
=> cmd/uses: mention "dependents" in help text

Library/Homebrew/cask/audit.rb, Library/Homebrew/cask/auditor.rb, Library/Homebrew/cask/cmd.rb, Library/Homebrew/cask/config.rb, Library/Homebrew/cask/dsl.rb, Library/Homebrew/os/mac.rb, Library/Homebrew/test/cask/audit_spec.rb, Library/Homebrew/test/cask/cmd_spec.rb, Library/Homebrew/test/cask/dsl_spec.rb, Library/Homebrew/test/cmd/readall_spec.rb, Library/Homebrew/test/os/mac_spec.rb, Library/Homebrew/test/spec_helper.rb
=> Refactor `brew cask audit`.

Library/Homebrew/dev-cmd/create.rb, docs/Manpage.md, manpages/brew.1
=> create: use https rubydoc url

Library/Homebrew/os/linux/elf.rb
-----
Fixes the issue of 
`brew install go` failing with 
```sh
...
Error: DYNAMIC segment not found, might be a statically-linked ELF?
```
cc @jonchang  @sjackman @woodruffw
=> Bug Fix: "Error: DYNAMIC segment not found, might be a statically-linked ELF?" at linking stage

Library/Homebrew/cmd/install.rb, Library/Homebrew/reinstall.rb, Library/Homebrew/upgrade.rb
-----
re-enable build from source for install, reinstall, upgrade. see #8068
=> re-enable build from source for install, reinstall, upgrade

Library/Homebrew/dev-cmd/pr-upload.rb
-----
Part of https://github.com/Homebrew/brew/issues/7917. Ensure that the bottle being uploaded (as described by its JSON file) is the same version as the formula it's being uploaded for.
=> pr-upload: ensure bottle and formula version match

Library/Homebrew/dev-cmd/bottle.rb
-----
Fixes issue that popped up here: https://github.com/Homebrew/linuxbrew-core/pull/20803/checks?check_run_id=915097062
cc @vidusheeamoli
=> bottle: fix inreplace string

Library/Homebrew/build.rb, Library/Homebrew/cmd/--env.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/dev-cmd/sh.rb, Library/Homebrew/extend/ENV.rb, Library/Homebrew/extend/ENV/shared.rb, Library/Homebrew/extend/ENV/std.rb, Library/Homebrew/extend/ENV/super.rb, Library/Homebrew/extend/os/linux/extend/ENV/std.rb, Library/Homebrew/extend/os/linux/extend/ENV/super.rb, Library/Homebrew/extend/os/mac/extend/ENV/std.rb, Library/Homebrew/extend/os/mac/extend/ENV/super.rb, Library/Homebrew/requirement.rb, Library/Homebrew/test.rb, Library/Homebrew/test/ENV_spec.rb
-----
@mistydemeo, this should fix the `brew bundle` breakage you mentioned in https://github.com/Homebrew/homebrew-bundle/pull/745#issuecomment-664570304.
=> Pass individual args explicitly to `ENV` extensions.

Library/Homebrew/brew.sh, Library/Homebrew/cmd/update.sh, docs/Manpage.md, manpages/brew.1
This should help with cases like https://github.com/Homebrew/homebrew-bundle/issues/751 and is good practise in general.
-----
=> brew.sh: run `brew update` before `brew bundle`.

Library/Homebrew/cmd/info.rb
Fixes https://github.com/Homebrew/brew/issues/8132
-----
=> info: handle license array.

Library/Homebrew/dev-cmd/test.rb, docs/Manpage.md, manpages/brew.1
This should allow better handling flaky tests.
-----
=> test: add flag to retry.

Library/Homebrew/cmd/deps.rb
Fixes https://github.com/Homebrew/brew/pull/8126#issuecomment-666345260
-----
=> cmd/deps: add missing require.

Library/Homebrew/formula.rb
-----
We don't want to ignore errors that are actually resultant of the code in the block rather than the actual formula.
=> formula: don't catch errors in the Formula.each yield

.github/codecov.yml
-----
Bogus second commit to test changes.
=> codecov.yml: mark patch status as informational

Library/Homebrew/cmd/outdated.rb
-----
Fix after #8144
`brew outdated <formula>` would print all outdated formulae instead of only `<formula>` before this PR.
Also fixes `--verbose`
=> outdated: fix args

Library/Homebrew/cmd/deps.rb
-----
Fix after #8144
`--installed` and `--include-requirements`  would not work before this PR
=> deps: fix args

Library/Homebrew/cmd/update-report.rb
=> update-report: fix args

Library/Homebrew/dev-cmd/pr-publish.rb
=> dev-cmd/pr-publish: fix --tap and --workflow

Library/Homebrew/cmd/install.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/reinstall.rb, Library/Homebrew/upgrade.rb
-----
Tweak how arg passing works with `FormulaInstaller`.
=> Fix dependents building from source when not requested

Library/Homebrew/cmd/outdated.rb
=> cmd/outdated: restore sorting of formulae

Library/Homebrew/formula.rb
-----
So it is included in the JSON API etc.
=> formula: add deprecated/disabled info to hash

Library/Homebrew/system_config.rb
-----
Include the branch of the core tap in config output to assist in diagnosing issues like https://github.com/Homebrew/homebrew-core/issues/58749
=> config: include core branch in output

Library/Homebrew/dev-cmd/irb.rb
-----
`ARGV.dup.freeze` is no longer passed at `Homebrew::CLI::Parser.new`.
=> dev-cmd/irb: move comment

Library/Homebrew/formula.rb
-----
While shadowing formulae isn't really supported, sometimes it is unintentional so if we can use `full_name` without issue then we should.
=> formula: cache based on full_name

Library/Homebrew/cmd/list.rb
=> cmd/list: remove ARGV usage

Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
- Formulae are not being reset to their original state on `brew bump-formula-pr` failure with `--dry-run` and `--write`
- This adds a `read_only_run` variable that is `true` only if the current execution is a dry run without `--write`
- Also updates `inreplace_pairs` to check for `--write` in addition to `--dry-run`
- Related: #8167
=> bump-formula-pr: restore formula unless read only run

Library/Homebrew/cmd/uses.rb
-----
~~This also converts `use_runtime_dependents` into an instance variable, similar to `cmd/deps.rb`'s `@use_runtime_dependencies`~~
Confirmed working as before with `libzip`:
<details>
<summary><code>brew uses libzip</code></summary>
<br/>
```console
$ brew uses libzip | cat                            
ebook-tools
freedink
fuse-zip
huexpress
ideviceinstaller
katago
mgba
openrct2
osrm-backend
php
php@7.2
php@7.3
planck
ppsspp
tldr
ykneomgr
```
</details>
<details>
<summary><code>brew uses libzip --recursive</code></summary>
<br/>
```console
$ brew uses libzip --recursive | cat
deployer
easyengine
ebook-tools
freedink
fuse-zip
huexpress
ideviceinstaller
katago
mgba
openrct2
osrm-backend
php
php@7.2
php@7.3
phplint
planck
ppsspp
tldr
ykneomgr
```
</details>
(This was originally part 2 of …
=> cmd/uses: extract function `intersection_of_dependents`

Library/Homebrew/cmd/log.rb
=> cmd/log: fix args error

Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
This allows `brew bump-formula-pr` to work with e.g. [Brewsci/bio](https://github.com/brewsci/homebrew-bio) where pull requests should be opened for `develop` instead of `master`
Bumping a `homebrew/core` formula:
```console
$ brew bump-formula-pr balena-cli --version 12.10.1 --dry-run     
...
==> create pull request with GitHub API (base branch: master)
```
Bumping a `brewsci/bio` formula:
```console
$ brew bump-formula-pr brewsci/bio/busco --version 4.1.2 --dry-run
...
==> create pull request with GitHub API (base branch: develop)
```
-----
(Based on [`update-reset`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/update-reset.sh#L45))
=> bump-formula-pr: open PR on default branch

docs/Formula-Cookbook.md
-----
Add information about licenses to the docs.
=> docs: add license information

Library/.rubocop.yml, Library/.rubocop_cask.yml, Library/Homebrew/.rubocop.yml
We want to allow this class to grow larger still while still enforcing this on other classes.
-----
=> rubocop: adjust RuboCop metrics checks.

Library/Homebrew/rubocops/homepage.rb, Library/Homebrew/test/rubocops/homepage_spec.rb
-----
cc @SeekingMeaning, @jonchang
=> style: clarify GitHub .git error message

Library/Homebrew/cask/cmd/upgrade.rb, Library/Homebrew/cmd/upgrade.rb, Library/Homebrew/env_config.rb
-----
See https://github.com/Homebrew/homebrew-cask/issues/87045 and https://github.com/Homebrew/brew/pull/8214.
=> Fix https://github.com/Homebrew/homebrew-cask/issues/87045

Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
I'm not sure how this was able to work without this change 🤔
=> bump-formula-pr: fix check_all_pull_requests

Library/Homebrew/cmd/--cache.rb, Library/Homebrew/cmd/list.rb, Library/Homebrew/cmd/outdated.rb, Library/Homebrew/cmd/upgrade.rb, docs/Manpage.md, manpages/brew.1
- Ensure the usage documentation always mentions casks when appropriate
- Use --formulae or --casks consistently
- Provide --formulae and --casks switches to upgrade
- Mark more switches as conflicting
---
-----
=> Handle casks in commands more consistently.

.github/workflows/tests.yml, Library/Homebrew/dev-cmd/tap-new.rb
This allows more code reuse.
-----
=> workflows/tests: use setup-homebrew GitHub Action.

Library/Homebrew/cmd/tap-info.rb, Library/Homebrew/exceptions.rb, Library/Homebrew/tap.rb, Library/Homebrew/test/exceptions_spec.rb, Library/Homebrew/test/tap_spec.rb, completions/bash/brew, completions/fish/brew.fish, completions/zsh/_brew
This was deprecated and removed a while ago.
-----
=> Remove more tap pinning code.

Library/Homebrew/cmd/tap-info.rb
Broken in https://github.com/Homebrew/brew/pull/8230.
-----
=> cmd/tap-info: improve comma usage.

.github/workflows/tests.yml
Set up Homebrew should handle both the Git and Ruby setup for us (and do so faster).
-----
=> workflows/tests: cleanup steps.

Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
The set of PRs checked in `check_open_pull_requests` is a subset of those in `check_all_pull_requests`, so we only need to check closed PRs after checking the open ones.
This will help reduce spam when running `brew bump-formula-pr` with `--force` as it currently prints the same warning twice if there is an open duplicate PR.
~~Still needs to be tested~~ Tested with clib 2.1.12 and dvc 1.3.1 PRs
=> bump-formula-pr: only check closed PRs for exact match

Library/Homebrew/cask/cmd/create.rb, Library/Homebrew/test/cask/cmd/create_spec.rb
-----
This replaces single quotes with double quotes in the template for `brew cask create`
=> cask/create: update template to match new style

.github/workflows/docker.yml, .github/workflows/doctor.yml, .github/workflows/spdx.yml, .github/workflows/tests.yml, Library/Homebrew/dev-cmd/tap-new.rb
Increase consistency between workflows, use more of our actions and `@main`.
-----
=> Cleanup more GitHub Actions usage

Library/Homebrew/cmd/upgrade.rb
Fixes https://github.com/Homebrew/brew/issues/8228#issuecomment-670161766
-----
=> cmd/upgrade: fix cask/formula args (again).

bin/brew
Also: GitHub Actions already sets it.
-----
=> bin/brew: only export CI if not set.

.github/workflows/tests.yml
-----
Explicitly tap all official cask taps.
=> Actually run `brew cask style` on all taps.

Library/Homebrew/upgrade.rb
=> Fix `upgrade --build-from-source`.

Library/Homebrew/dev-cmd/prof.rb, docs/Manpage.md, manpages/brew-cask.1, manpages/brew.1
-----
So that `brew prof --prefix` to profile `brew --prefix` works.
https://github.com/Homebrew/brew/issues/8189#issuecomment-667745272
=> dev-cmd/prof: improve arg passing

Library/Homebrew/utils/pypi.rb
-----
See https://github.com/Homebrew/homebrew-core/pull/59404 for motivation
=> utils/pypi: add cdk8s to blocklist

Library/Homebrew/cask/audit.rb, Library/Homebrew/test/cask/audit_spec.rb
=> Ensure new casks have a description.

Library/Homebrew/reinstall.rb
-----
Fixes Homebrew/homebrew-core#59437.
=> reinstall: fix error when building from source

Library/Homebrew/download_strategy.rb
-----
This is used in external commands.
Fixes https://github.com/Homebrew/brew/pull/8187#issuecomment-672008506.
=> Reinstate `#shutup!`.

Library/Homebrew/cask/audit.rb, Library/Homebrew/test/cask/audit_spec.rb
-----
Fixes failure in https://github.com/Homebrew/homebrew-cask-versions/pull/9447.
=> Don't warn about version designation in `cask-versions` tap.

Library/Homebrew/sorbet/files.yaml, Library/Homebrew/sorbet/rbi/cli.rbi, Library/Homebrew/sorbet/rbi/homebrew.rbi, Library/Homebrew/sorbet/rbi/utils/spdx.rbi
-----
Add new files to the list of all files in `sorbet/files.yaml`.
following 8 files are added to false:
- ./cmd/--caskroom.rb
- ./rubocops/cask/mixin/on_desc_stanza.rb
- ./rubocops/shared/desc_helper.rb
- ./rubocops/shared/helper_functions.rb
- ./test/cmd/--caskroom_spec.rb
- ./test/dependencies_helpers_spec.rb
- ./test/rubocops/cask/desc_spec.rb
- ./test/utils/spdx_spec.rb
following 6 files are added to true:
- ./compat/cli/parser.rb
- ./compat/dependencies_helpers.rb
- ./context.rb
- ./dependencies_helpers.rb
- ./rubocops/cask/desc.rb
- ./utils/spdx.rb
=> sorbet/files.yaml: add new files

Library/Homebrew/cask/audit.rb, Library/Homebrew/cask/dsl.rb, Library/Homebrew/locale.rb, Library/Homebrew/test/cask/audit_spec.rb, Library/Homebrew/test/locale_spec.rb
-----
Use `Locale` class to validate languages.
=> Fix auditing of cask languages.

Library/Homebrew/rubocops/shared/desc_helper.rb
-----
Set instance variables needed for `problem` explicitly which are not automatically set in cask cops.
=> Fix `Desc` cop for casks.

Library/Homebrew/extend/os/mac/system_config.rb, Library/Homebrew/system_config.rb
-----
This avoids a heavier REXML dependency, and generally looks better.
=> os/mac/system_config: simplify JVM version parsing

.gitignore
-----
Previously, it was matching the entire `http` folder, which we do not want.
=> .gitignore: correct mechanize ignore matching

.github/workflows/docker.yml, .github/workflows/spdx.yml
This ensures they have access to the correct secrets.
-----
=> workflows: test on "push" not "pull_request".

Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
-----
update GitHub rate limit info to current documentation URL
=> docs: update GitHub rate limit URL

.github/workflows/docker.yml, .github/workflows/doctor.yml, .github/workflows/tests.yml, Library/Homebrew/dev-cmd/tap-new.rb
- Add consistent spacing
- Remove `pull_request: []` warning
- remove identical, implicit `name` usage
- use `actions/cache@v1` for compatibility
---
-----
=> GitHub Actions cleanup

Library/Homebrew/rubocops/shared/desc_helper.rb
-----
Fixes https://github.com/Homebrew/homebrew-cask/pull/87436#issuecomment-673532087.
=> Allow iOS and iPhone at the beginning of descriptions.

Library/Homebrew/cask/cmd.rb
=> Add missing `help` methods for external `cask` commands.

Library/Homebrew/manpages/brew.1.md.erb, docs/Manpage.md, manpages/brew.1
-----
Fix https://github.com/Homebrew/brew/pull/8239#issuecomment-673847397.
=> Remove references to `brew-cask` from `brew` man page.

Library/Homebrew/cli/parser.rb, Library/Homebrew/test/cli/parser_spec.rb
-----
Fixes https://github.com/Homebrew/brew/issues/8337.
=> Fix parsing of negative options.

Library/Homebrew/utils/ruby.sh
-----
Moved OS-specific logic to functions:
- `find_ruby`: returns (via echo) Ruby that can be used
- `usable_ruby`: checks whether Ruby satisfies Homebrew
Pre-create OS-specific error messages:
- `upgrade_fail`: message that is printed when Homebrew fails to upgrade vendored Ruby
- `install_fail`: message that is printed when Homebrew fails to install vendored Ruby
Unconditionally set `TERMINFO_DIRS` when installing/upgrading vendor Ruby **but** export it on Linux only.
**Motivation**: move OS-specific logic to functions so that it's easier to understand the logic in `setup-ruby-path`.
=> utils/ruby.sh: reoganize code

Library/Homebrew/dev-cmd/bump-revision.rb, docs/Manpage.md, manpages/brew.1
Closes: https://github.com/Homebrew/brew/issues/8357
-----
=> bump-revision: allow multiple formulae to be specified

Library/Homebrew/cask/cmd/list.rb, Library/Homebrew/test/cask/cmd/list_spec.rb
=> cask/list: fix artifact list

Library/Homebrew/cxxstdlib.rb
=> Refactor and document `CxxStdlib`.

Library/Homebrew/diagnostic.rb, Library/Homebrew/extend/os/mac/diagnostic.rb
=> Refactor and document `Homebrew::Diagnostic`.

Library/Homebrew/build_environment.rb, Library/Homebrew/cmd/--env.rb, Library/Homebrew/exceptions.rb, Library/Homebrew/formula.rb
=> Refactor and document `BuildEnvironment`.

Library/Homebrew/cask/cmd/audit.rb
-----
Without this change:
```console
$ brew cask audit --help
(…)
--new-cask                   Run various additional style checks to
determine if a new cask is eligible
for
Homebrew. This should be used when creating
new casks and implies
--strict
and --online
(…)
```
With this change:
```console
$ brew cask audit --help
(…)
--new-cask                   Run various additional style checks to
determine if a new cask is eligible for
Homebrew. This should be used when creating
new casks and implies --strict and
--online
(…)
=> Cask audit help: breakup desc string

Library/Homebrew/development_tools.rb, Library/Homebrew/extend/os/mac/development_tools.rb, Library/Homebrew/tab.rb, Library/Homebrew/test/caveats_spec.rb
-----
This currently fails generic OS tests because of the Xcode & CLT stuff. That needs to be handled a little differently.
=> tab: add built_on & arch information

Library/Homebrew/cleanup.rb, Library/Homebrew/test/cleanup_spec.rb
=> Refactor and document `Cleanup`.

Library/Homebrew/extend/os/linux/install.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/install.rb
=> Refactor and document `Install`.

Library/Homebrew/cask/artifact/stage_only.rb
-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/87763.
=> Add missing `summarize` method for `StageOnly`.

Library/Homebrew/os/mac/pkgconfig/11.0/sqlite3.pc
-----
The current version as of beta 4.
=> os/mac/pkgconfig/11.0/sqlite3: bump to 3.32.3

Library/Homebrew/dev-cmd/bump-formula-pr.rb, Library/Homebrew/utils/github.rb
=> utils/github: add `forked_repo_info!`

Library/Homebrew/cmd/info.rb, Library/Homebrew/cmd/options.rb, Library/Homebrew/options.rb
=> Refactor and document `Options`.

Library/Homebrew/pkg_version.rb
=> Refactor and document `PkgVersion`.

Library/Homebrew/dependency_collector.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/dev-cmd/extract.rb, Library/Homebrew/dev-cmd/pull.rb, Library/Homebrew/diagnostic.rb, Library/Homebrew/extend/git_repository.rb, Library/Homebrew/formula.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/system_config.rb, Library/Homebrew/tap.rb, Library/Homebrew/test/tap_spec.rb, Library/Homebrew/test/utils/git_spec.rb, Library/Homebrew/utils/git.rb
=> Refactor and document `Git`.

Library/Homebrew/dependency_collector.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/download_strategy.rb, Library/Homebrew/test/utils/svn_spec.rb, Library/Homebrew/utils/svn.rb
=> Refactor and document `Svn`.

Library/Homebrew/help.rb, Library/Homebrew/utils.rb
=> Move `command_help_lines` into `Help` module.

Library/Homebrew/diagnostic.rb, Library/Homebrew/extend/os/linux/diagnostic.rb, Library/Homebrew/os/linux/diagnostic.rb, Library/Homebrew/sorbet/files.yaml
-----
Move the method `alias` to the main module.
=> Remove `os/linux/diagnostic`.

Library/Homebrew/utils/git.rb
=> Call `clear_available_cache` after installing Git.

Library/Homebrew/test/utils/repology_spec.rb
-----
Also silence stdout from `parse_api_response`.
=> test/utils/repology_spec: mark as `:needs_network`

Library/Homebrew/test/cmd/bundle_spec.rb, Library/Homebrew/test/spec_helper.rb
---
The tap is automatically installed with the `setup_remote_tap` function.
=> Remove unused metadata from `bundle` spec.

Library/Homebrew/cmd/install.rb, Library/Homebrew/cmd/reinstall.rb, Library/Homebrew/cmd/upgrade.rb, Library/Homebrew/upgrade.rb
=> Refactor and document `Upgrade`.

Library/Homebrew/brew.sh
So we can see the logs better.
-----
=> brew.sh: colorize output on GitHub Actions

Library/Homebrew/cask/cmd/uninstall.rb, Library/Homebrew/cask/cmd/zap.rb
-----
Addresses the CI failure in https://github.com/Homebrew/homebrew-cask/pull/88126.
=> Use installed cask file for `brew cask zap`.

Library/Homebrew/utils/git.rb
=> Fix “Git is unavailable” error.

Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/dev-cmd/bump-formula-pr.rb, Library/Homebrew/formula_creator.rb, Library/Homebrew/resource.rb, Library/Homebrew/test/version_spec.rb, Library/Homebrew/version.rb, Library/Homebrew/version/null.rb
=> Refactor and document `Version`.

Library/Homebrew/.rubocop_todo.yml, Library/Homebrew/utils/repology.rb
=> Document `Repology`.

Library/Homebrew/.rubocop_todo.yml, Library/Homebrew/utils/spdx.rb
=> Document `SPDX`.

Library/Homebrew/.rubocop_todo.yml, Library/Homebrew/utils/shebang.rb
=> Document `Shebang`.

Library/Homebrew/.rubocop_todo.yml, Library/Homebrew/cask/audit.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/sorbet/files.yaml, Library/Homebrew/utils/shared_audits.rb
=> Document `SharedAudits`.

Library/Homebrew/.rubocop_todo.yml, Library/Homebrew/download_strategy.rb
=> Document download strategies.

Library/Homebrew/.rubocop_todo.yml, Library/Homebrew/utils/livecheck_formula.rb
=> Document `LivecheckFormula`.

Library/Homebrew/metafiles.rb
-----
Follow up for #8499 and #8256
Copy license files with licenses (e.g. `LICENSE-GPL`)
=> metafiles: copy license files with hyphens

Library/Homebrew/cli/named_args.rb
=> Don't output warning to `stdout`.

Library/Homebrew/test/utils/git_spec.rb, Library/Homebrew/utils/git.rb
=> Properly fix Git error in tests.

docs/Interesting-Taps-and-Forks.md
-----
Remove taps that are no longer maintained.
=> docs/Interesting-Taps-and-Forks.md: remove unsupported taps

Library/Homebrew/utils/pypi.rb
-----
See https://github.com/Homebrew/homebrew-core/pull/60285
=> pypi: add pulumi to the blocklist

Library/Homebrew/dev-cmd/pr-pull.rb, Library/Homebrew/dev-cmd/pull.rb
-----
`installed_prefix` does not actually return the installed version - see #8431
=> pull, pr-pull: use `opt_or_installed_prefix_keg`

Library/Homebrew/style.rb
-----
Also add JSON output for ShellCheck so we can output violations as annotations on GitHub Actions in the future.
=> Split `check_style_impl` into `run_rubocop` and `run_shellcheck`.

Library/Homebrew/os/linux.rb
Saw these on a random user report.
-----
=> os/linux: add more Xcode stubs.

docs/New-Maintainer-Checklist.md
-----
Adding and removing people from the calendar invite was a burden. So we rely on Slack reminders.
=> docs: The maintainer monthly call has a Slackbot now

Library/Homebrew/cask/cmd/style.rb, Library/Homebrew/style.rb, Library/Homebrew/test/cask/cmd/style_spec.rb
-----
Remove redundant code for running RuboCop.
=> Use `Homebrew::Style` for `brew cask style`.

Library/Homebrew/style.rb
-----
Progress dots are not really useful in CI output.
=> Adjust RuboCop formatter on CI.

docs/Acceptable-Formulae.md
=> Add note about vendoring dependencies

Library/Homebrew/cask/installer.rb
-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/72474
=> Update cask/installer.rb: check deps before download

.github/ISSUE_TEMPLATE/config.yml
Let's trial this and see how it goes.
=> ISSUE_TEMPLATE: direct people to GitHub Discussions

.github/workflows/docker.yml, .github/workflows/tests.yml
- Note GitHub Packages specifically in step names
- Use uppercase for Homebrew name/tag (in case it makes a difference)
- Use `--password-stdin` to avoid a warning
---
-----
=> workflows: tweak docker.

Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
-----
I think we had this at some point already. Anyways, this is pretty useful for debugging CI.
=> Re-add `HOMEBREW_DEBUG` environment variable.

Library/Homebrew/cmd/search.rb
-----
updates the fink url to use https
=> search: use https for fink query url

Library/Homebrew/cask/audit.rb, Library/Homebrew/cask/auditor.rb, Library/Homebrew/cask/cmd/audit.rb, Library/Homebrew/test/cask/audit_spec.rb, Library/Homebrew/test/cask/cmd/audit_spec.rb
-----
Allow passing `--no-appcast` to skip appcast check if `--online` is also passed.
=> Support `--no-appcast` for `brew cask audit`.

Library/Homebrew/cask/audit.rb
-----
See CI failure in https://github.com/Homebrew/homebrew-cask/pull/88642: https://github.com/Homebrew/homebrew-cask/pull/88642/checks?check_run_id=1070442761
=> Fix missing method `problem` in `Cask::Audit`.

.github/workflows/spdx.yml, .github/workflows/tapioca.yml
Once every 24h should be sufficient for both of these.
-----
=> workflows: reduce scheduled PR workflow's frequency.

Library/Homebrew/cask/audit.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/utils/shared_audits.rb
-----
Casks which only ever had pre-releases are currently failing CI, so allow specifying casks in `GITHUB_PRERELEASE_ALLOWLIST`
=> Move more common code into `SharedAudits`.

Library/Homebrew/utils/shared_audits.rb
-----
Some projects are technically forks but have evolved enough to be considered a separate project.
Needed to get https://github.com/Homebrew/homebrew-cask/pull/88692 passing CI.
=> Add `GITHUB_FORK_ALLOWLIST`.

Library/Homebrew/utils/shared_audits.rb
-----
Required for https://github.com/Homebrew/homebrew-cask/pull/88822 to pass the CI tests.
Thank you.
=> Add pock to GITHUB_PRERELEASE_ALLOWLIST

Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
- Require `--mirror` argument if `--url` is specified (and formula has mirrors)
- Otherwise, attempt to update the url and all mirrors by replacing the old version substring with the new version.
- This will make it easier to bump formulae that have mirrors
=> bump-formula-pr: update mirrors automatically

Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/test/sandbox_spec.rb, Library/Homebrew/test/spec_helper.rb, Library/Homebrew/test/support/github_formatter.rb
-----
Output annotations for test failures.
=> Add RSpec formatter for Github Actions.

docs/assets/img/docs/managing-pull-requests.drawio.svg
-----
Addresses https://github.com/Homebrew/brew/pull/8627#issuecomment-688966085.
=> Use monochrome ✔, which works better with filter

Library/Homebrew/test/support/github_formatter.rb
=> Remove colon from RSpec annotations.

Library/Homebrew/brew.rb, Library/Homebrew/commands.rb, Library/Homebrew/dev-cmd/man.rb
-----
Noticed in https://github.com/Homebrew/brew/issues/8633.
=> Pass `quiet` when tapping external commands.

Library/Homebrew/cask/cmd/audit.rb, Library/Homebrew/style.rb, Library/Homebrew/utils/github/actions.rb
-----
This was previously done in the `homebrew/cask` CI workflow.
=> Output annotations for `brew cask audit` (again).

Library/Homebrew/cli/named_args.rb, Library/Homebrew/dev-cmd/style.rb, Library/Homebrew/style.rb, Library/Homebrew/test/cli/named_args_spec.rb
-----
Also allow passing any combination of paths, taps, formulae or casks.
=> Support passing casks in `brew style`.

.github/workflows/tests.yml, Library/Homebrew/test/spec_helper.rb, Library/Homebrew/test/utils/git_spec.rb
- Don't skip Git installation tests on generic OS; remove it instead.
- Install Subversion for macOS Subversion tests.
---
-----
=> Tweak tests annotations

completions/zsh/_brew_cask
-----
Fixes https://github.com/Homebrew/brew/issues/8640
=> Replace the usage of outdated brew cask list in zsh completion

Library/Homebrew/diagnostic.rb, Library/Homebrew/extend/ENV.rb, Library/Homebrew/extend/os/mac/diagnostic.rb, Library/Homebrew/extend/os/mac/extend/ENV/std.rb, Library/Homebrew/extend/os/mac/extend/ENV/super.rb, Library/Homebrew/install.rb
Reuse code from `brew doctor` that checks and produces a fatal error and from `install.rb` that runs it.
Closes #8646
-----
=> ENV: check SDK exists when setting up.

Library/Homebrew/formula.rb
This will improve things for formulae.brew.sh.
-----
=> formula: use pretty license output in JSON.

Library/Homebrew/formula.rb
https://github.com/Homebrew/formulae.brew.sh/pull/328/checks?check_run_id=1102740199#step:6:5
-----
=> formula: add missing SPDX require.

Library/Homebrew/sorbet/files.yaml, Library/Homebrew/sorbet/rbi/homebrew.rbi, Library/Homebrew/sorbet/rbi/utils/utils.rbi
-----
This PR adds 12 new files to sorbet/files.yaml and solves 3 existing type errors.
=> sorbet: add new files and solve existing errors

Library/Homebrew/utils/curl.rb
-----
https://github.com/Homebrew/homebrew-cask/pull/89120 is currently failing because the homepage is protected by CloudFlare and returning a 403 code.
=> Check for CloudFlare protection on status code 403.

Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/style.rb, Library/Homebrew/test/dev-cmd/audit_spec.rb, Library/Homebrew/test/style_spec.rb
=> Output annotations for `brew audit`.

Library/Homebrew/utils/curl.rb
-----
https://github.com/Homebrew/homebrew-cask-drivers/pull/1753 is currently failing because of this.
=> Ignore URLs protected by Incapsula.

Library/Homebrew/os/mac/xquartz.rb
This is breaking stuff:
https://github.com/Homebrew/homebrew-core/pull/61156/checks?check_run_id=1118574438#step:4:48
-----
=> xquartz: unprivate prefix.

Library/Homebrew/cask/exceptions.rb, Library/Homebrew/test/cask/verify_spec.rb
-----
The test failures are unrelated, so I'll count that as a success.
=> cask/exceptions: Actually print actual hash

Library/Homebrew/dev-cmd/bump-formula-pr.rb, Library/Homebrew/utils/pypi.rb
-----
Add a message to PRs created by `bump-formula-pr` if the formula has resources that weren' checked for updates.
Relates to #8732
=> bump-formula-pr: add message to check resources

Library/Homebrew/rubocops/shared/desc_helper.rb, Library/Homebrew/test/rubocops/cask/desc_spec.rb
-----
Needed to get https://github.com/Homebrew/homebrew-cask/pull/89249 passing CI.
=> Allow “macOS virtual machines” in descriptions.

docs/New-Maintainer-Checklist.md
=> Add homebrew/cask to new maintainer checklist.

docs/Brew-Test-Bot-For-Core-Contributors.md, docs/Homebrew-homebrew-core-Merge-Checklist.md
-----
Part of https://github.com/Homebrew/brew/issues/8093. Update documentation so maintainers know how to use this new feature.
=> docs: update for autosquashing

Library/Homebrew/rubocops/shared/desc_helper.rb, Library/Homebrew/test/rubocops/cask/desc_spec.rb, Library/Homebrew/test/rubocops/formula_desc_spec.rb
-----
Disallow descriptions starting with any article.
=> Check for descriptions starting with “the”.

Library/Homebrew/dev-cmd/pr-pull.rb, Library/Homebrew/test/dev-cmd/pr-pull_spec.rb, Library/Homebrew/test/utils/git_spec.rb, Library/Homebrew/test/utils/github_spec.rb, Library/Homebrew/utils/git.rb, Library/Homebrew/utils/github.rb, docs/Manpage.md, manpages/brew.1
=> dev-cmd/pr-pull: refactor and add tests

Library/Homebrew/dev-cmd/pull.rb
`gh` is the official GitHub tool and better maintained at this point.
-----
=> dev-cmd/pull: recommend gh over hub.

Library/Homebrew/cask/audit.rb
Use `new_cask?` instead of`@new_cask`.
Addresses Mike's comment: https://github.com/Homebrew/brew/pull/8351/files#r471431141
-----
-----
=> cask/audit.rb: minor cleanup

README.md
Let's try to nudge more people over and see how it goes.
As discussed with @SMillerDev
=> README: point to Homebrew/discussions.

Library/Homebrew/cask/cmd/audit.rb
-----
Allows running audit in a specific tap to prevent audit failures in other taps from failing CI.
=> Allow passing tap to `brew cask audit`.

Library/Homebrew/tap.rb, docs/Manpage.md, manpages/brew.1
Don't raise an exception only to catch it.
-----
=> tap: remove redundant exception.

Library/Homebrew/dev-cmd/pr-pull.rb
=> pr-pull: fix signoff for linuxbrew-core

Library/Homebrew/options.rb
=> options: handle `nil` array.

Library/Homebrew/livecheck/strategy/pypi.rb
-----
Update to https://github.com/Homebrew/brew/pull/8832 for multi-digit post versions in PyPI.
=> livecheck/pypi: minor edit to PyPI post version

Library/Homebrew/utils/shared_audits.rb
-----
Required for https://github.com/Homebrew/homebrew-cask/pull/90294 to pass `audit`.
=> shared_audits: add freetube to GITHUB_PRERELEASE_ALLOWLIST

Library/Homebrew/cask/dsl/depends_on.rb, Library/Homebrew/os/mac/sdk.rb, Library/Homebrew/os/mac/version.rb, Library/Homebrew/test/os/mac/software_spec_spec.rb, Library/Homebrew/test/os/mac/version_spec.rb
-----
Closes https://github.com/Homebrew/homebrew-cask/pull/90326.
=> Refactor `OS::Mac::Version`.

Library/Homebrew/cmd/install.rb
Partially reverts f54b458cdaec5091cf7abfa3e09e9050a94a4a26.
-----
Re-add previous tapping logic.
Closes https://github.com/Homebrew/brew/issues/8830.
=> Fix installing taps in `brew install`.

completions/zsh/_brew
I found an error that was breaking my `brew upgrade ...` zsh completion
-----
=> Bug fix _brew_upgrade zsh completion function

Library/Homebrew/cli/named_args.rb, Library/Homebrew/cmd/upgrade.rb
-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/90236.
=> Force `brew upgrade` to treat arguments as casks if `--cask` is passed.

Library/Homebrew/dev-cmd/audit.rb
This applies to linuxbrew-core rather than Linux, really.
-----
=> audit: allow Linux checking Homebrew dependencies.

.github/dependabot.yml
-----
Using the same `package-ecosystem` and `directory` twice is sadly not supported, apparently.
=> Fix `dependabot.yml`.

Library/Homebrew/os/mac/sdk.rb
-----
Fixes https://github.com/Homebrew/brew/issues/8900.
=> Fix version comparison in `SDK#latest_sdk`.

manpages/README.md
I don't believe this is accurate following #1860 and #5650.
-----
cc @MikeMcQuaid
=> Update manpages readme to current practice

Library/Homebrew/utils/shared_audits.rb
-----
Required for https://github.com/Homebrew/homebrew-cask/pull/91310 to pass `audit`.
=> shared_audits: add nuclear to GITHUB_PRERELEASE_ALLOWLIST

Library/Homebrew/dev-cmd/update-test.rb
Output more information about the refs and commit message for the start, expected and actual end commits to ease debugging.
---
-----
=> update-test: improve debugging output.

Library/Homebrew/os/mac/xcode.rb
=> mac/xcode: version bumps for Xcode 12.1

Library/Homebrew/extend/os/linux/requirements/xcode_requirement.rb, Library/Homebrew/extend/os/requirements/xcode_requirement.rb, Library/Homebrew/requirements/xcode_requirement.rb
```
2020-10-12T21:29:03.7866574Z [31mError:[0m undefined method `latest_version' for OS::Mac::Xcode:Module
2020-10-12T21:29:03.7867686Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:33:in `message'
2020-10-12T21:29:03.7868902Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:199:in `map'
2020-10-12T21:29:03.7870227Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:199:in `satisfied_requirements?'
2020-10-12T21:29:03.7871547Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:593:in `formula!'
2020-10-12T21:29:03.7873156Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/f …
```
=> xcode_requirement: support linux

Library/Homebrew/utils/shared_audits.rb
-----
Required for https://github.com/Homebrew/homebrew-cask/pull/91477 to pass `audit`.
=> shared_audits: add syntax-highlight to GITHUB_PRERELEASE_ALLOWLIST

Library/Homebrew/language/python.rb
Update virtualenv to the latest version
=> python: update virtualenv

Library/Homebrew/dev-cmd/audit.rb
-----
This is causing all CI to fail due to our `brew audit` step.
https://github.com/Homebrew/homebrew-core/pull/63734#issuecomment-719926722
cc @fxcoudert @alebcay
=> audit: fdroidserver can have mixed python versions

Library/Homebrew/utils/shared_audits.rb
-----
Required for https://github.com/Homebrew/homebrew-cask/pull/91819 to pass `audit`.
=> shared_audits: add lidarr to GITHUB_PRERELEASE_ALLOWLIST

Library/Homebrew/cmd/link.rb, Library/Homebrew/cmd/switch.rb, Library/Homebrew/cmd/unlink.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/formula.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/keg.rb, Library/Homebrew/unlink.rb, docs/Manpage.md, manpages/brew.1
Re-applies https://github.com/Homebrew/brew/pull/9009
Reverts Homebrew/brew#9016
I'll push a fix to the issue @sjackman mentions in #9016.
=> Improve @-versioned formulae linking.

Library/Homebrew/dev-cmd/diy.rb
=> diy: downcase names.

Library/Homebrew/cli/parser.rb, Library/Homebrew/cmd/list.rb
- Remove incorrect `--formula` requirements.
- Fix bad `OptionConstraintError` output message.
Fixes #9037.
-----
=> list: more parameters fixes.

Library/Homebrew/extend/os/linux/formula.rb, Library/Homebrew/extend/os/mac/formula.rb, Library/Homebrew/formula.rb, Library/Homebrew/test/formula_spec.rb
=> formula: add on_linux and on_macos blocks

Library/Homebrew/cmd/link.rb
Needed for `brew diy`.
Fixes #9036
-----
=> link: link kegs without formulae.

Library/Homebrew/diagnostic.rb
=> diagnostic: improve deleted message.

docs/Formula-Cookbook.md
-----
add how to set environment variables anywhere to https://docs.brew.sh/Formula-Cookbook because of https://github.com/Homebrew/brew/issues/8648
=> how to set ENV in doc

Library/Homebrew/dev-cmd/audit.rb
References https://github.com/Homebrew/brew/pull/9027#issuecomment-722042589 CC @sjackman 
-----
=> audit: tweak versioned formulae logic (again).

.github/workflows/tests.yml, Library/Homebrew/extend/os/mac/diagnostic.rb, Library/Homebrew/test/os/mac/diagnostic_spec.rb, Library/Homebrew/test/spec_helper.rb
Let's try out GitHub Actions on Big Sur and see how broken it is (or, hopefully, isn't).
=> workflows/tests: use Big Sur.

Library/Homebrew/cask/audit.rb, Library/Homebrew/cask/dsl.rb, Library/Homebrew/cask/dsl/caveats.rb
-----
Fixes CI failure in https://github.com/Homebrew/homebrew-cask-fonts/pull/2561.
=> Only warn if repo of discontinued cask is archived.

Library/Homebrew/dev-cmd/pr-upload.rb
I accidentally committed an earlier version for this.
=> dev-cmd/pr-upload: fix brew audit arguments.

Library/Homebrew/extend/os/mac/software_spec.rb, Library/Homebrew/extend/os/software_spec.rb
=> Revert "uses_from_macos: fix force_homebrew_on_linux behaviour."

Library/Homebrew/dev-cmd/pr-upload.rb
-----
No need to read all available formulae on the machine and audit them. Only the changed ones.
=> pr-upload: audit only changed formulae

docs/Installation.md
-----
Fix a small typo in `docs/Installation.md`.
=> docs/Installation.md: Fix a small typo

Library/Homebrew/os/mac/xcode.rb
=> xcode: update for Xcode 12.2

Library/Homebrew/test/bintray_spec.rb
non-existant -> non-existent
-----
=> bintray: fix typo in it comment

Library/.rubocop.yml, Library/Homebrew/cask/caskroom.rb, Library/Homebrew/cask/cmd/upgrade.rb, Library/Homebrew/cli/args.rb, Library/Homebrew/cli/args.rbi, Library/Homebrew/cli/named_args.rb, Library/Homebrew/cmd/upgrade.rb, Library/Homebrew/test/cli/parser_spec.rb
-----
Mention `--greedy` flag when no casks were upgraded. Also add some type annotations related to upgrade.
Closes https://github.com/Homebrew/homebrew-cask/issues/92407.
=> Mention `--greedy` when no casks were upgraded.

Library/Homebrew/test/spec_helper.rb
This should help with flakiness on these tests.
=> spec_helper: increase needs_network timeout and retry.

Library/Homebrew/unpack_strategy/lzma.rb
-----
Refactor structure of `Lzma` to be the same as `Xz`.
=> Unify `Lzma` and `Xz`.

Library/.rubocop.yml
Fixes https://github.com/Homebrew/homebrew-test-bot/issues/522
-----
=> Fix brew style checks on Brewfiles

Library/Homebrew/utils/shared_audits.rb
-----
Required for https://github.com/Homebrew/homebrew-cask/pull/92983 to pass `audit`.
=> shared_audits: add haptickey to GITHUB_PRERELEASE_ALLOWLIST

Library/Homebrew/cli/named_args.rb
Fixes https://github.com/Homebrew/brew/issues/8966
=> cli/named_args: don't convert to taps.

Library/.rubocop.yml
=> Enable `Performance/ConstantRegexp` cop.

.github/workflows/tests.yml, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/extend/os/mac/diagnostic.rb, Library/Homebrew/test/utils/github_spec.rb
---
Allow tests to pass on Big Sur and fix the `sponsors_by_tier` test when token doesn't have the correct scopes.
=> Fix tests failing locally.

Library/Homebrew/test/language/node_spec.rb
=> Don't create `package.json` in current directory.

.github/workflows/tests.yml, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/extend/os/mac/diagnostic.rb
Remove `HOMEBREW_BIG_SUR_TESTING` variable as it is no longer needed.
=> Big Sur cleanup

Library/Homebrew/cask/cmd/audit.rb, Library/Homebrew/dev-cmd/audit.rb, docs/Manpage.md, manpages/brew.1
=> Support casks in `brew audit`.

Library/Homebrew/cli/named_args.rb, Library/Homebrew/cmd/uninstall.rb, docs/Manpage.md, manpages/brew.1
-----
Fixes https://github.com/Homebrew/homebrew-cask/pull/92998#issuecomment-729644356.
=> Support `--cask` flag in `brew uninstall`.

Library/Homebrew/dev-cmd/audit.rb
=> Fix `brew audit --tap=<tap>`.

.gitignore, Library/Homebrew/dev-cmd/vendor-gems.rb, docs/Manpage.md, manpages/brew.1
-----
Needed for a new `update-gems` workflow.
=> Add `--update` option to `brew vendor-gems`.

Library/Homebrew/extend/os/mac/requirements/java_requirement.rb, Library/Homebrew/test/language/java_spec.rb, Library/Homebrew/test/requirements/java_requirement_spec.rb, Library/Homebrew/test/spec_helper.rb
It would be possible to work around this but I'm not convinced it's worth it given https://github.com/Homebrew/homebrew-core/issues/63290
Fixes #9194
=> Disable Java requirement versions on Big Sur

Library/Homebrew/cli/named_args.rb, Library/Homebrew/dev-cmd/cat.rb, Library/Homebrew/test/cli/named_args_spec.rb, docs/Manpage.md, manpages/brew.1
=> Support casks in `brew cat`.

Library/Homebrew/cli/named_args.rb, Library/Homebrew/dev-cmd/edit.rb, docs/Manpage.md, manpages/brew.1
=> Support casks in `brew edit`.

Library/Homebrew/cli/named_args.rb, Library/Homebrew/cmd/info.rb, docs/Manpage.md, manpages/brew.1
=> Support `--cask` flag in `brew info`.

Library/Homebrew/extend/os/mac/diagnostic.rb
Addresses issue mentioned in #9215.
=> extend/os/mac/diagnostic: add more Xcode/CLT update instructions.

.github/workflows/sorbet.yml
=> Allow running `sorbet` workflow manually.

.github/workflows/triage.yml
-----
Partially implements 2. and 3. of https://github.com/Homebrew/brew/issues/9224.
=> Add `triage` workflow.

Library/Homebrew/dev-cmd/bump-cask-pr.rb
-----
Fixes https://github.com/Homebrew/homebrew-cask/issues/93256.
=> Fix checksum replacement in `bump-cask-pr`.

Library/Homebrew/brew.sh
=> brew.sh: add missing quotes

Library/Homebrew/sorbet/plugins/delegate.rb, Library/Homebrew/sorbet/triggers.yml
=> Add Sorbet plugin for `delegate`.

.github/workflows/triage.yml
=> Skip from Saturday/Sunday to end of Monday.

.github/workflows/triage.yml
---
The bot cannot approve itself, and pull requests by @BrewTestBot always have to be reviewed and merged by a human anyways.
=> Skip review for pull requests by BrewTestBot.

.github/workflows/triage.yml
=> Move logic for calculating date offset into separate function.

Library/Homebrew/rubocops/components_order.rb, Library/Homebrew/test/rubocops/components_order_spec.rb
=> on_macos/on_linux block: allow to use deprecate or disable

Library/Homebrew/cask/exceptions.rb, Library/Homebrew/dev-cmd/create.rb, docs/Manpage.md, manpages/brew.1
=> Allow creating casks with `brew create --cask`.

Library/Homebrew/dev-cmd/pr-pull.rb, Library/Homebrew/test/utils/github_spec.rb, Library/Homebrew/utils/github.rb, docs/Manpage.md, manpages/brew.1
=> pr-pull: allow to pull from multiple workflows

Library/Homebrew/unpack_strategy/dmg.rb
-----
See https://github.com/Homebrew/homebrew-cask/pull/93476.
=> Add debug information for empty BOM error.

Library/Homebrew/unpack_strategy/dmg.rb
=> Add more BOM debug information.

Library/Homebrew/extend/os/mac/extend/ENV/std.rb, Library/Homebrew/extend/os/mac/extend/ENV/super.rb, Library/Homebrew/os/mac.rb, Library/Homebrew/os/mac/version.rb, Library/Homebrew/os/mac/xcode.rb, Library/Homebrew/tap_constants.rb, Library/Homebrew/test/os/mac/diagnostic_spec.rb, Library/Homebrew/test/os/mac/pkgconfig_spec.rb, Library/Homebrew/test/os/mac/version_spec.rb, Library/Homebrew/utils/analytics.rb
=> Handle macOS versions >= 11.1 correctly.

Library/Homebrew/cmd/list.rb, docs/Manpage.md, manpages/brew.1
=> cmd/list: --formula is no longer a default.

Library/Homebrew/PATH.rb, Library/Homebrew/formula.rb, Library/Homebrew/resource.rb, Library/Homebrew/software_spec.rb, Library/Homebrew/sorbet/plugins/attr_rw.rb, Library/Homebrew/sorbet/plugins/def_delegator.rb, Library/Homebrew/sorbet/plugins/def_delegators.rb, Library/Homebrew/sorbet/rbi/upstream.rbi, Library/Homebrew/sorbet/triggers.yml
=> Add types for `Formula`.

Library/Homebrew/unpack_strategy/dmg.rb
=> Add debug output of `find` command when creating BOM.

Library/Homebrew/unpack_strategy/dmg.rb
=> Try retrying BOM `find` command.

Library/Homebrew/unpack_strategy/dmg.rb
---
Closes https://github.com/Homebrew/homebrew-cask/issues/93482.
=> Work around BOM `find` bug.

Library/Homebrew/diagnostic.rb
-----
This is relevant now that we have lots of Homebrew/cask taps that also need to have their branch checked, not just Homebrew/core.
=> diagnostic: check all tap branches, not just core

Library/Homebrew/global.rb
I think these are already implicitly included but let's do so just for inclusiveness.
=> global: add more active_support includes.

Library/Homebrew/test/cask/cmd/style_spec.rb
-----
Depending on the test seed, these may not be required in this file.
=> Add missing `require`s for `style` spec.

Library/Homebrew/extend/os/mac/hardware/cpu.rb, Library/Homebrew/formula.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/rubocops/livecheck.rb, Library/Homebrew/test/exceptions_spec.rb
-----
Split out from https://github.com/Homebrew/brew/pull/9302.
=> Fix RuboCop offenses.

Library/Homebrew/dev-cmd/irb.rb
-----
Fixes https://github.com/Homebrew/brew/issues/9362.
=> Add missing require in `dev-cmd/irb`.

Library/Homebrew/test/dev-cmd/audit_spec.rb
---
Avoid spurious network errors.
=> Mark some `audit` tests with `:needs_network`.

Library/Homebrew/test/rubocop_spec.rb
-----
Fix CI failure for new RuboCop versions.
=> Suppress `parser` warnings.

Library/Homebrew/cmd/fetch.rb
-----
Critical to unblock https://github.com/Homebrew/homebrew-cask/pull/94046.
=> Fix wrong `force` keyword.

.github/workflows/vendor-gems.yml
-----
Avoid diff constantly changing between Mojave/Big Sur.
Unblocks https://github.com/Homebrew/brew/pull/9378.
=> Run `vendor-gems` on Big Sur.

Library/Homebrew/test/dev-cmd/bump_spec.rb
-----
Avoid spurious network issues.
=> Mark `brew bump` test with `:needs_network.

Library/Homebrew/cmd/deps.rb, docs/Manpage.md, manpages/brew.1
=> Revert "add two flag to deps --installed"

Library/Homebrew/cmd/deps.rb, docs/Manpage.md, manpages/brew.1
=> add flags to deps --installed

Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
Set the label properly for ARM.
Tested with inputs `11-arm` and `arm64_big_sur`.
Fixes https://github.com/Homebrew/brew/issues/9434
=> dev-cmd/dispatch-build-bottle: set ARM labels.

Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
This was accidentally merged in https://github.com/Homebrew/brew/pull/9444.
=> dev-cmd/dispatch-build-bottle: remove testing code.

Library/Homebrew/cmd/update.sh
This should hopefully avoid getting more issues about this.
=> cmd/update: improve shallow clone message.

Library/Homebrew/extend/ENV/shared.rb
=> ENV/shared: widen type for append_path

Library/Homebrew/hardware.rb, Library/Homebrew/os/mac/version.rb
Should fix https://github.com/Homebrew/brew/issues/9449
=> Revert "Fix `:arm64_big_sur` bottle ordering."

Library/Homebrew/cask/audit.rb
=> Reuse `curl_http_content_headers_and_checksum` for appcast audit.

Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
-----
Avoid wasting CI time by also caching results for casks with timed out downloads instead of retrying them over and over again.
=> Add timeout in `bump-unversioned-casks`.

Library/Homebrew/dev-cmd/create.rb
-----
- allow --set-name & --set-version to be used when creating formulae
- fix --set-license
- split the autodetected formula name on an equal sign if present (for e.g. some [gitweb URLs](http://www.codesrc.com/gitweb/index.cgi?p=libzipper.git;a=summary))
- reorder mode selection list
- fix up messaging
=> create: fix options handling

Library/Homebrew/cmd/untap.rb, docs/Manpage.md, manpages/brew.1
=> Revert "untap: add --force switch"

Library/Homebrew/unversioned_cask_checker.rb
-----
Fixes wrong version bumps like the one fixed in https://github.com/Homebrew/homebrew-cask/pull/95136.
=> Ignore `Info.plist` for nested apps.

.github/workflows/sorbet.yml
---
Avoid diff changing back and forth between Catalina and Big Sur.
=> Run `sorbet` workflow on Big Sur.

Library/Homebrew/cask/audit.rb, Library/Homebrew/cask/dsl.rb, Library/Homebrew/cask/url.rb
-----
Closes https://github.com/Homebrew/homebrew-cask/issues/95081.
=> Ignore `verified` for `url do` blocks.

Library/Homebrew/cmd/home.rb, docs/Manpage.md, manpages/brew.1
-----
add two options ( `--formula` and `--cask` ) to `cmd/home`.
=> add two options to cmd/home

.github/stale.yml
-----
Follow up to #9514
Remove the `stale.yml` configuration file that is no longer needed.
=> Remove stale.yml

Library/Homebrew/dev-cmd/bump-unversioned-casks.rb
-----
Otherwise, failed checks will run again immediately, never giving outdated checks a chance.
=> Also cache failed version bump attempts.

Library/Homebrew/dev-cmd/edit.rb
-----
make `brew edit` error message the same as `brew edit --cask`
=> add path name to brew edit error message

Library/Homebrew/Gemfile, Library/Homebrew/Gemfile.lock, Library/Homebrew/unversioned_cask_checker.rb
-----
Fixes wrong versions being parsed, see https://github.com/Homebrew/homebrew-cask/pull/95284.
=> Fix parsing version from `PackageInfo` files.

Library/Homebrew/brew.rb
-----
On CI, `stdout` and `stderr` always get out of sync, rendering the logs pretty much unreadable.
=> Fix broken output on CI.

Library/Homebrew/cask/audit.rb, Library/Homebrew/cli/args.rbi, Library/Homebrew/dev-cmd/livecheck.rb, Library/Homebrew/livecheck/livecheck.rb, Library/Homebrew/test/livecheck/livecheck_spec.rb
-----
Check if casks with `livecheck` blocks have a version and if that version is the same as returned by the livecheck.
=> Add audit for `livecheck` in casks.

Library/Homebrew/unversioned_cask_checker.rb
-----
Allows guessing more versions.
=> Add `top_level_info_plists` helper method.

Library/Homebrew/cask/audit.rb, Library/Homebrew/test/cask/audit_spec.rb, Library/Homebrew/test/cask/cmd/cat_spec.rb, Library/Homebrew/test/cask/dsl_spec.rb, Library/Homebrew/test/support/fixtures/cask/Casks/adobe-air.rb, Library/Homebrew/test/support/fixtures/cask/Casks/adobe-illustrator.rb, Library/Homebrew/test/support/fixtures/cask/Casks/basic-cask.rb, Library/Homebrew/test/support/fixtures/cask/Casks/no-dsl-version.rb, Library/Homebrew/test/support/fixtures/third-party/Casks/pharo.rb
-----
Closes https://github.com/Homebrew/homebrew-cask/issues/94253.
=> Add audit for unversioned URLs with checksum.

Library/Homebrew/cmd/update-report.rb
-----
This mirrors what's currently done for formulae. No obvious speed advantage; more because the list of updated casks tends to be rather long in comparison. Also, show less output if `--quiet` is passed.
=> update-report: summarize updated casks for --preinstall

Library/Homebrew/formula_installer.rb
Use a better keyword argument rather than passing a hash.
=> formula_installer: refactor pour_bottle?

Library/Homebrew/os/mac/xcode.rb
The comment says "update when our CI is migrated", and we're not there yet for Intel Big Sur nodes.
=> xcode: 12.3 is the latest version

Library/Homebrew/dev-cmd/style.rb, docs/Manpage.md, manpages/brew.1
-----
add two options ( `--formula` and `--cask` ) to `dev-cmd/style`.
=> style: add two options

Library/Homebrew/utils/github.rb
As suggested by @reitermarkus in https://github.com/Homebrew/brew/pull/10055#discussion_r545829663
=> utils/github: tweak search_code style.

Library/Homebrew/style.rb
=> Hide `parser` warning.

Library/Homebrew/utils/shared_audits.rb
-----
Required for https://github.com/Homebrew/homebrew-cask/pull/95593 to pass `audit`.
=> shared_audits: add xit to GITHUB_PRERELEASE_ALLOWLIST

Library/Homebrew/language/haskell.rb
The referenced file no longer exists.
=> Remove language/haskell

Library/Homebrew/install.rb
=> install: switch Rosetta 2/Intel messaging order.

Library/Homebrew/test/dev-cmd/bottle_spec.rb, Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
In preparation for #9315
-----
=> bottle --merge: add more write tests

Library/Homebrew/dev-cmd/unbottled.rb
List formulas that are “ready to bottle”
=> unbottled: improve output

Library/Homebrew/exceptions.rb
This can sometimes be nil so handle that.
Fixes #10158
=> exceptions: fix ErrorDuringExecution status.

Library/Homebrew/extend/os/mac/hardware.rb
Expand on #10153 to provide an in-code comment (in case someone goes to change this in future).
=> os/mac/hardware: clarify Rosetta 2 situation with a comment.

Library/Homebrew/os/mac.rb
-----
This updates the code fragment shown below.
https://github.com/Homebrew/brew/blob/5521c76e663977f742d09fa03ca0f76fa250b15e/Library/Homebrew/os/mac.rb#L43-L46
=> os/mac: bump latest_sdk_version

Library/Homebrew/dev-cmd/unbottled.rb
Handle a few more edge cases beyond https://github.com/Homebrew/brew/pull/10110:
- improve the unbottled output heading so it makes sense when we're outputting bottles that are ready to bottle
- output already bottled formulae if named
- handle Linux/Mac requiring formulae and output if named
- output bottle unneeded/disabled formulae if named
- use green/yellow/red for bottles ready to be built now/later/never
=> dev-cmd/unbottled: improve output.

Library/Homebrew/cmd/--cache.rb
-----
refactor `cmd/--cache`  where args checked whether `formula?` or `cask?`.
=> cmd/--cache: refactor

docs/Installation.md
Now that the installer is available for ARM, we need to update the documentation.
=> Installation.md: update for ARM

Library/Homebrew/cmd/deps.rb
-----
refactor `cmd/deps` where `args` checked whether `formula?` or `cask?`.
=> cmd/deps: refactor about `formula?` and `cask?`.

Library/Homebrew/cmd/reinstall.rb
-----
refactor `cmd/reinstall` where `args` checked whether `formula?` or `cask?`.
=> cmd/reinstall: refactor about `formula?` and `cask?`.

Library/Homebrew/livecheck/strategy/apache.rb, Library/Homebrew/livecheck/strategy/cpan.rb, Library/Homebrew/livecheck/strategy/github_latest.rb, Library/Homebrew/livecheck/strategy/gnome.rb, Library/Homebrew/livecheck/strategy/gnu.rb, Library/Homebrew/livecheck/strategy/hackage.rb, Library/Homebrew/livecheck/strategy/launchpad.rb, Library/Homebrew/livecheck/strategy/npm.rb, Library/Homebrew/livecheck/strategy/pypi.rb, Library/Homebrew/livecheck/strategy/sourceforge.rb, Library/Homebrew/livecheck/strategy/xorg.rb, Library/Homebrew/test/livecheck/strategy/hackage_spec.rb, Library/Homebrew/test/livecheck/strategy/npm_spec.rb
-----
This updates `gnome`, `hackage`, `npm` & `pypi` livecheck strategies as discussed here: https://github.com/Homebrew/brew/pull/9510#discussion_r541326964
/cc @samford
=> livecheck: update URL patterns

Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/test/dev-cmd/bottle_spec.rb, Library/Homebrew/utils/ast.rb
-----
This PR restores some of the `brew bottle --merge --write --keep-old` logic that was removed in https://github.com/Homebrew/brew/pull/10102
Instead of checking for default spec values, we can check which methods were being called in the old `bottle` block
Supersedes https://github.com/Homebrew/brew/pull/10135
=> bottle: check actual bottle block contents when `--keep-old`

docs/Shell-Completion.md
Add the missing backtick noted in #10202
=> Add a missing backtick on docs Shell Completion page

Library/Homebrew/rubocops/uses_from_macos.rb
=> gperf: add to uses_from_macos allowlist

completions/zsh/_brew
-----
add cask options to commands( `info`, `audit` and `install` ) in `zsh/completions `
related https://github.com/Homebrew/brew/issues/10123
=> zsh/completions: add_cask_options

Library/Homebrew/dev-cmd/bump-revision.rb, Library/Homebrew/test/utils/ast_spec.rb, Library/Homebrew/utils/ast.rb
=> utils/ast: add `stanza_text` helper function

completions/zsh/_brew
-----
add the option `--pull-request` to`brew search`  in zsh completions
=> completions/zsh: add --pull-reques to search

.gitignore
-----
Needed for https://github.com/Homebrew/brew/pull/10214.
=> Ignore `racc` gem.

Library/Homebrew/cmd/info.rb
-----
refactor `def github_info` in `cmd/info` because if statement is hard to read.
=> cmd/info: refactor-github_info

Library/Homebrew/brew.sh, Library/Homebrew/cmd/casks.sh, Library/Homebrew/cmd/formulae.sh, Library/Homebrew/items.sh, completions/bash/brew, completions/fish/brew.fish, completions/internal_commands_list.txt, completions/zsh/_brew_cask, docs/Manpage.md, manpages/brew.1
-----
Per #10123, this is roughly made accroding to #8846.
=> Add brew casks command

Library/Homebrew/rubocops/uses_from_macos.rb
=> uses_from_macos: add netcat

Library/Homebrew/cmd/install.rb, Library/Homebrew/cmd/reinstall.rb
-----
Fixes https://github.com/Homebrew/brew/issues/9139.
=> Properly pass cask options in `reinstall`.

Library/Homebrew/dev-cmd/bump-formula-pr.rb
-----
This PR includes some general cleanup of `brew bump-formula-pr` and cleanup of https://github.com/Homebrew/brew/pull/10221
- Deleted `requested_spec` variable since its value is always `:stable`
- Moved the check for `stable` specification to happen earlier
- Added some missing `.present?`
- Fixed strange indentation of `check_closed_pull_requests` call
- Replaced duplicate file reads with `old_contents`
=> bump-formula-pr: cleanup

Library/Homebrew/utils/github.rb
-----
- Deleted unneeded `GitHub.` and `GitHub::`
- e.g. replaced `GitHub.api_credentials_type` with `api_credentials_type`
- Changed `api_errors` method to `API_ERRORS` constant
=> utils/github: cleanup

Library/Homebrew/extend/ENV/std.rb, Library/Homebrew/formula.rb, Library/Homebrew/utils/inreplace.rb, docs/Bottles.md
* Address bottle `prefix` deprecation
* Document some undocumented functions in formula.rb
* Add some type signatures in formula.rb
-----
=> Improve documentation and add type signatures.

Library/Homebrew/cask/audit.rb, Library/Homebrew/test/cask/audit_spec.rb
-----
`appcast` should be removed if a `livecheck` exists.
=> Improve audit for `livecheck` in casks.

Library/Homebrew/shims/super/cc
-----
`brew style` "skips" over `shims/super/cc` as it seems to see it as a shell script. I temporarily deleted the [`#!/bin/sh` section](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/shims/super/cc#L1-L8) and then ran `brew style --fix`. Since I'm not sure if `shims/super/cc` supports the same Ruby syntax as the rest of the repository, I'm marking this PR as a draft
Here are the remaning style errors: (The line numbers are all off by 8 since I deleted `#!/bin/sh`)
```
Library/Homebrew/shims/super/cc:1:1: C: [Correctable] Missing frozen string literal comment.
#!/usr/bin/env ruby -W0
^
Library/Homebrew/shims/super/cc:18:1: C: Missing top-level class documentation comment.
class Cmd
^^^^^
Library/Homebrew/shims/super/cc:122:5: W: Duplicate branch body detected.
when :cpp …
```
=> shims/super/cc: fix most style errors

Library/Homebrew/test/cask/cmd/info_spec.rb
-----
This test is currently breaking even on master, and has been for about eight hours. It's blocking us from merging new PRs. https://github.com/Homebrew/brew/pull/10312/checks?check_run_id=1696817416
=> Cask tests: temporarily disable broken test

Library/Homebrew/test/utils/popen_spec.rb
-----
These were introduced in #10305 but only started going red after that PR was merged. Since this is red in master and in every open PR that's up to date with master, I'd like to get this in ASAP.
cc @SeekingMeaning
=> Popen spec: ensure Rubocop is happy

Library/Homebrew/keg.rb
=> Revert "Keg: allow overwriting same-formula conflicts"

Library/Homebrew/utils/pypi.rb
-----
This PR allows `pipgrip` to resolve conflicts in versions of dependencies (if we have extra packages listed in `pypi_formula_mappings.json`).
Effectively it passes all required packages to `pipgrip` call instead of doing several consequent `pipgrip` calls one per package
Before:
```
$ brew update-python-resources salt
==> Retrieving PyPI dependencies for "salt==3002.2"...
==> Retrieving PyPI dependencies for "M2Crypto"...
==> Retrieving PyPI dependencies for "pygit2"...
Error: Conflicting versions found for the `cffi` resource: 1.14.3, 1.14.4
```
After:
```
$ brew update-python-resources salt
==> Retrieving PyPI dependencies for "salt==3002.2 M2Crypto pygit2"...
==> Getting PyPI info for "apache-libcloud==2.4.0"
==> Getting PyPI info for "cached-property==1.5.2"
==> Getting PyPI …
```
=> utils/pypi: allow pipgrip to resolve conflicts

Library/Homebrew/keg.rb
-----
refactor `def link` & `def unlink` in `keg.rb` to use keyword arguments instead of optional arguments.
=> keg: refactor to use keyword arguments

Library/Homebrew/sorbet/rbi/upstream.rbi
-----
Upstream merged PRs:
- https://github.com/sorbet/sorbet/pull/3722
- https://github.com/sorbet/sorbet/pull/3729
- https://github.com/sorbet/sorbet/pull/3887 (superseded https://github.com/sorbet/sorbet/pull/3730)
=> sorbet: delete local fixes that have been merged upstream

completions/bash/brew
-----
fixes https://github.com/Homebrew/brew/runs/1724830949
=> completions: remove link

Library/Homebrew/dev-cmd/install-bundler-gems.rb, docs/Manpage.md, manpages/brew.1
Needed for CI:
https://github.com/Homebrew/homebrew-core/pull/69460/checks?check_run_id=1740727396#step:6:32
=> install-bundler-gem: allow on ARM.

completions/zsh/_brew
-----
add cask options to commands( reinstall and upgrade ) in zsh/completions.
=> completions/zsh: add-cask-option

Library/Homebrew/exceptions.rb
=> exceptions: more handling of nil status.

Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/software_spec.rb
Extracted from https://github.com/Homebrew/brew/pull/10377
=> software_spec: change BottleSpecification#checksums to return array

Library/Homebrew/os/mac/version.rb
=> os/mac/version: update method signatures

completions/zsh/_brew
-----
Fixes https://github.com/Homebrew/brew/issues/10409
=> completions/zsh: fix broken zsh tab completion for `brew upgrade`

Library/Homebrew/cask/dsl/version.rb, Library/Homebrew/version.rb
-----
This PR marks methods used in `homebrew/core` and `homebrew/cask` as public
=> version: mark methods as public

Library/Homebrew/formula_installer.rb, Library/Homebrew/keg_relocate.rb, Library/Homebrew/software_spec.rb
-----
delete some variables because  Homebrew 2.7.0 was released.
=> delete some variables after Homebrew 2.7.0 is released.

Library/Homebrew/test/cli/named_args_spec.rb
-----
Follow-up to https://github.com/Homebrew/brew/pull/10405
I was going to include this in a different PR, but I thought I should first open this one, where I'm only adding tests. Once this is merged, the intent behind the PR I plan open will hopefully be more clear
=> named_args_spec: add tests for unreadable formulae/casks

Library/Homebrew/software_spec.rb, Library/Homebrew/test/software_spec_spec.rb, Library/Homebrew/test/support/fixtures/testball_bottle_cellar.rb
This new format was agreed in #10377
=> software_spec: reverse tag/digest for new bottles.

Library/Homebrew/rubocops/checksum.rb
Fixes:
1-01-28T17:17:10.7152456Z [31m==>[0m [1m[31mFAILED[0m[0m
2021-01-28T17:17:10.7163169Z [36mFormula/dhall-json.rb[0m:14:12: [33mC[0m: sha256 should be 64 characters
2021-01-28T17:17:10.7175011Z     sha256 cellar: :any_skip_relocation, big_sur: "a1e0cb4f7e4a7e0994b43ecd783240356631d36655cfbf59a903cc3f6a799242"
2021-01-28T17:17:10.7176620Z            ^^^^^^
2021-01-28T17:17:10.7178131Z [36mFormula/dhall-json.rb[0m:14:15: [33mC[0m: sha256 contains invalid characters
2021-01-28T17:17:10.7179886Z     sha256 cellar: :any_skip_relocation, big_sur: "a1e0cb4f7e4a7e0994b43ecd783240356631d36655cfbf59a903cc3f6a799242"
2021-01-28T17:17:10.7181198Z               ^^
2021-01-28T17:17:10.7182390Z [36mFormula/dhall-json.rb[0m:15:12: [33mC[0m: sha256 should be 64 characters
2021-01-28T17:17:10.7183801Z …
=> style: do not fail on sha256 lines with cellar information

Library/Homebrew/rubocops/checksum.rb, Library/Homebrew/rubocops/extend/formula.rb, Library/Homebrew/test/rubocops/checksum_spec.rb
=> style: re-enable sha256 checks for bottle blocks

Library/Homebrew/version.rb
-----
This PR adds constants for shared patterns among version regexes:
- Let `x`, `y`, `z`, etc. be strings containing only digits (i.e. integers)
- `DOT_OPTIONAL` - requires at least `x`, and accepts `x.y`, `x.y.z`, etc.
- Examples: `1`, `1.2`, `1.2.3`, `1.2.3.4`
- `DOT_REQUIRED` - requires at least `x.y`, and accepts `x.y.z`, etc.
- Examples: `1.2`, `1.2.3`, `1.2.3.4`
- `MINOR_OR_PATCH` - only accepts `x.y` or `x.y.z`
- Examples: `1.2`, `1.2.3`
- `BIN_SUFFIX` - `.`, `_`, or `-` followed by any of the following:
- `bin`, `dist`, `stable`, `src`, `source`, `sources`, `final`, `full`
- Examples: `.bin`, `_dist`
- `ALPHA_SUFFIX` - `.`, `_`, or `-` followed by any of the following along with an integer of at most two digits:
- `alpha`, `beta`, `pre`, `rc`
- Examples: `_alpha1`, `-beta.23` …
=> version: add constants for regexes

Library/Homebrew/cask/audit.rb
-----
This PR changes `brew audit --cask` to underline URLs in audit errors as it's sometimes hard to tell when the URLs begin and end, especially when they're long
=> cask/audit: underline URLs in audit errors

Library/Homebrew/formula_auditor.rb, manpages/brew.1
-----
change the command in `audit_postgresql`'s  error message
=> formula_auditor: repair audit_postgresql message

.github/ISSUE_TEMPLATE/feature.yml
Fixes https://github.com/Homebrew/brew/pull/10472#discussion_r567965249
=> ISSUE_TEMPLATE/feature.yml: add missing "you".

Library/Homebrew/extend/os/mac/language/java.rb, Library/Homebrew/test/language/java_spec.rb
- `Cask::Config#explicit` did not expect an `en-GB` language, so this test failed.
-----
Follow up to #10479.
=> java: improve tests

Library/Homebrew/utils/curl.rb
-----
refactor if statement in `utils/curl`
=> utils/curl: refactor curl_with_workarounds

Library/Homebrew/utils/github.rb
-----
This PR aims to fix `api_credentials_error_message` in `utils/github.rb` to prevent false positive credential errors from being raised.
The rationale behind these changes:
* `x-accepted-oauth-scopes` (or the `needed_scopes` parameter) provides the list of scopes needed for the action and `x-oauth-scopes` provides the list of scopes available to the API token.
* The set of needed scopes must be a subset of the API token's scopes.
* If this is not true, we must raise an error.
Hopefully, this handling is correct. If not, please do let me know! CC @MikeMcQuaid @carlocab
Note: `brew tests` fail locally for me, after #10462 (off topic, but thought I'd mention it).
<details>
<summary>Test Failure Output</summary>
<br>
<pre>
Failures:
1) Cask::Config#explicit returns string of explicit …
=> utils/github: fix false positive API credential error

.github/workflows/vendor-gems.yml
CC @reitermarkus more context in Slack.
=> workflows/vendor-gems: disable for pull requests.

Library/Homebrew/os/mac/xcode.rb
Don't merge this until our CI nodes have upgraded to Xcode 12.4.
-----
=> xcode: update for Xcode 12.4

.github/workflows/vendor-gems.yml
=> Re-enable `vendor-gems` for pull requests.

.github/workflows/doctor.yml
-----
This hasn't been working for months.
=> workflows/doctor: fix workflow not running

.github/workflows/tests.yml
=> workflows/tests: remove hadolint.

Library/Homebrew/rubocops/components_order.rb
Some conflicts are os-specific.
-----
=> on_os block: allow to contain conflicts_with

Library/Homebrew/formula.rb
Extract this method from `#to_hash` so it can be used in `brew bundle`.
=> formula: add bottle_hash method.

docs/Acceptable-Casks.md, docs/FAQ.md, docs/README.md
-----
First attempt at migrating https://github.com/Homebrew/homebrew-cask/tree/HEAD/doc/faq now that there is just a single brew command. I haven't changed any content, I just moved file content around.
=> Docs: Migrate casks FAQ

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml
This syntax is changing today and needs fixed CC @deniseyu and @Oneill38 for review.
=> .github/ISSUE_TEMPLATE/{bug,feature}.yml: update syntax.

docs/Acceptable-Casks.md
-----
Followup to https://github.com/Homebrew/brew/pull/10577#issuecomment-776826181:
> I’ve noticed some things I’d like to change, but that’s a later PR.
May have missed a few things I noticed at first.
=> Acceptable-Casks.md: first pass after moving

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml
This shouldn't have been merged until Friday.
Reverts Homebrew/brew#10607
Fixes https://github.com/Homebrew/brew/issues/10622
=> Revert ".github/ISSUE_TEMPLATE/{bug,feature}.yml: update syntax."

Library/Homebrew/dev-cmd/sponsors.rb, README.md, completions/fish/brew.fish, completions/zsh/_brew, docs/Manpage.md, manpages/brew.1
Also enhance the code to automatically update the README.
Rendered view: https://github.com/jonchang/brew/blob/enhance-sponsors/README.md#sponsors
-----
=> Update Github sponsor text and logos

Library/Homebrew/env_config.rb, docs/Manpage.md, manpages/brew.1
e.g. `brew bundle` so let's not claim to list them all.
=> env_config: auto update updates more commands.

.github/ISSUE_TEMPLATE/config.yml
-----
repair `about` of `New issue on Homebrew/homebrew-cask` in `ISSUE_TEMPLATE/config.yml` because `brew cask` is disabled.
=> ISSUE_TEMPLATE/config: repair issue on cask

Library/Homebrew/dev-cmd/sponsors.rb
- add named constants
- change an unless to if
=> dev-cmd/sponsors: tweak code.

Library/Homebrew/cmd/update-report.rb
-----
Before:
```
You have 1 outdated formula installed.
You can update them with brew upgrade.
```
After
```
You have 1 outdated formula installed.
You can update it with brew upgrade.
```
=> update-report: use appropriate pronoun in update message

Library/Homebrew/download_strategy.rb
-----
This is technically a functional change to a public API, but one that doesn't affect anything in `brew` apart from silencing some warnings.
https://github.com/Homebrew/brew/pull/10598#discussion_r581498395
=> download_strategy: don't chdir unless a block is passed

.github/workflows/update-manpage.yml
Follow-up from https://github.com/Homebrew/brew/pull/10673.
=> workflows/update-manpage: set token.

docs/Homebrew-Governance.md
This specifies the proposed voting mechanisms to be voted for in the 2021 AGM.
See also: https://github.com/Homebrew/homebrew-governance/pull/17
-----
=> Specify Meek STV election for PLC & Schulze Condorcet election for Project Leader

Library/Homebrew/formula_assertions.rb
=> formula_assertions: add assert_true compat method

Library/Homebrew/download_strategy.rb
-----
This is breaking `netris`.
=> download_strategy: only take basename of Content-Disposition

Library/Homebrew/utils/gems.rb
-----
Oversight by me to forget about `Homebrew.install_gem!`.
This fixes homebrew-cask's workflows.
Closes Homebrew/homebrew-cask#100423.
Closes Homebrew/homebrew-cask-versions#10460.
=> utils/gems: add installed gems to $LOAD_PATH

Library/Homebrew/cli/named_args.rb
-----
refactor if-statements in `def resolve_keg(name)`  because it was hard to read
=> cli/named_args: refactor if statements

docs/New-Maintainer-Checklist.md
-----
This PR removes steps in the New Maintainer Checklist that have been automated (adding new maintainers to the README and running `brew man`, updating PLC members).
=> docs/New-Maintainer-Checklist.md: remove automated steps

Dockerfile
This is needed to build glibc on CI
-----
See https://github.com/Homebrew/linuxbrew-core/pull/20575#issuecomment-670220605
=> Dockerfile: add gawk dependency

Library/Homebrew/dev-cmd/dispatch-build-bottle.rb
Supporting PR for: https://github.com/Homebrew/homebrew-core/pull/72351
-----
=> dispatch-build-bottle: support Linux

docs/Installation.md
-----
Update docs for installation from https://github.com/Homebrew/install/pull/534.
=> docs/Installation: add section for Git remote mirroring

Library/Homebrew/development_tools.rb
=> development_tools: fix LLVM Clang 10+ version detection

Library/README.md
-----
delete `brew cask` because it was deprecated.
=> delete brew-cask command

Library/Homebrew/formula_installer.rb, Library/Homebrew/test/formula_installer_spec.rb
-----
`recursive_dependencies` can be an expensive call. Let's try and reduce that as much as possible.
Previously we took the recursive dependencies of the root formula, and then the recursive dependencies of each of those. Then we took the recursive dependencies of the root formula once again.
This PR reduces this to a single-level direct dependency query with a recursive dependency query on each of those. Not quite as efficient as a single `recursive_dependencies` call (which avoids multiple expansions of subtrees duplicated as a direct and indirect dependency), but still substantially less than before.
#10784
=> formula_installer: further reduce dependency calculations

README.md, docs/Manpage.md, manpages/brew.1
- Add the new TSC to the README, manpage
- Fix linting complaints about whitespace in the README
=> README: update TSC, fix linting.

Library/Homebrew/download_strategy.rb
=> download_strategy: take basename of response-content-disposition query

Library/Homebrew/test/cask/audit_spec.rb
-----
We should be testing this, for security reasons.
=> test/cask/audit_spec: add test for slashes in versions

Library/Homebrew/cask/download.rb, Library/Homebrew/cask/installer.rb, Library/Homebrew/download_strategy.rb, Library/Homebrew/extend/time.rb, Library/Homebrew/sorbet/plugins/using.rb, Library/Homebrew/system_command.rb, Library/Homebrew/utils/curl.rb
---
Needed for https://github.com/Homebrew/brew/pulls.
=> Allow specifying timeouts for commands and downloads.

Library/Homebrew/github_packages.rb
- add more metadata to the images on upload
- stitch together images using Docker's CLI
- more code cleanup
Based on https://github.com/Homebrew/brew/pull/10835#issuecomment-797105530 (and lots of help in Slack) from @sjackman.
Example package: https://github.com/orgs/Homebrew/packages/container/package/homebrew-core%2Flibev
=> github_packages: improve metadata.

.github/workflows/doctor.yml, .github/workflows/triage-issues.yml
=> github/workflows: YAML cleanup.

Library/Homebrew/dev-cmd/bump-cask-pr.rb
-----
Supersedes https://github.com/Homebrew/brew/pull/10345
This PR allows ARM checksums to be updated from Intel Macs by temporarily replacing `Hardware::CPU.intel?` with `false`
=> bump-cask-pr: support separate downloads for Intel and ARM

Library/Homebrew/cmd/update.sh
-----
Fixes style errors that I introduced in https://github.com/Homebrew/brew/pull/10844.
=> Replace tab with spaces and align indent

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml
This will render nicer and use monospace in the form field.
=> Render shell in issue templates.

Library/Homebrew/utils/curl.rb
-----
Fixes audit failing for URLs where HTTPS is not available.
=> Ignore timeout when checking for HTTPS availability.

Library/Homebrew/cask/audit.rb
-----
Eventually all `appcast`s should be replaced by `livecheck`.
=> New casks should use `livecheck`.

Library/Homebrew/cmd/upgrade.rb
=> cmd/upgrade: fix --dry-run

Library/Homebrew/cmd/list.rb
-----
Listing everything without qualifying which is which is confusing for
some users.
Fixes #10897.
=> cmd/list: delineate formulae and casks

Library/Homebrew/cli/named_args.rb
This reverts commit 45066f91444730141c2262d761afee35af753a1b.
https://github.com/Homebrew/brew/pull/10925
-----
=> Revert "Fix `uninstall --force` for casks."

docs/Acceptable-Formulae.md
-----
This is pretty confusing since all these are deprecated in core. We should just remove this.
=> docs: no more cask exceptions

.gitignore, Library/Homebrew/github_packages.rb, Library/Homebrew/sorbet/rbi/todo.rbi
- validate all JSON files against their JSON schemas
- remove existing/lingering JSON files
- improve naming based on schema understanding
- add more (empty) annotations hashes where valid
- output prettier JSON
- fix non-SHA256 output filenames
Re-uploaded at https://github.com/orgs/Homebrew/packages/container/package/homebrew-core%2Flibev
=> github_packages: various improvements.

Library/Homebrew/utils/gems.rb
-----
This breaks testing of Ruby formulae.
=> utils/gems: don't leak BUNDLE_GEMFILE

.github/workflows/sorbet.yml, .github/workflows/spdx.yml, .github/workflows/update-manpage.yml, .github/workflows/vendor-gems.yml
-----
This PR changes occurrences of `GPG_PASSPHRASE` to `HOMEBREW_GPG_PASSPHRASE` as a result of Homebrew/actions#156, to prevent it from being filtered out of the environment and thus causing problems with workflows like `vendor-gems`.
=> workflows: fix commit signing

Library/Homebrew/formula_installer.rb
-----
While most of the benefits of caching have been where you expand dependencies multiple times (e.g. `brew uses` expands dependencies for every available formula), there is some value with adding limited internal caching that lasts for one expansion if no `cache_key` is passed. This PR adds that.
To be clear: to get the most benefits, one should still ideally pass a `cache_key` so that repeated calls will be cached - most slowdowns covered prior were because of repeated calls. However, this PR will help the cases where you do only care about expanding once (e.g. `FormulaInstaller`'s unique expansion) and you are dealing with a massive tree with lots of repeated subtrees. No core formula falls into this category, though some third party formulae do: #10550.
=> dependency: provide some limited internal caching by default

Library/Homebrew/dev-cmd/pr-upload.rb, Library/Homebrew/download_strategy.rb, Library/Homebrew/github_packages.rb
- cleanup comments from #10938
- fix download URL
- remove incorrect comment
=> GitHub Packages tweaks

Library/Homebrew/cask/dsl/version.rb
Related to https://github.com/Homebrew/homebrew-cask/pull/102854
=> cask/dsl/version: remove another invalid character

Library/Homebrew/cask/audit.rb, Library/Homebrew/test/cask/audit_spec.rb
-----
Fixes conflicting audit failure in https://github.com/Homebrew/homebrew-cask/pull/102681.
=> Don't suggest adding unnecessary `appcast`.

Library/Homebrew/dev-cmd/pr-pull.rb
-----
@nandahkrishna
Might be a fix for: https://github.com/Homebrew/homebrew-core/pull/74368
=> pr-pull: pass --committer to pr-upload

Library/Homebrew/dev-cmd/pr-pull.rb, Library/Homebrew/dev-cmd/pr-upload.rb
-----
Should fix:
https://github.com/Homebrew/homebrew-core/runs/2249865658?check_suite_focus=true
I tested it in a funky way, so I'm not sure it will actually resolve the problem.
=> pr-pull,upload: don't quote passed --committer value

Library/Homebrew/system_command.rb
-----
Discussion in #10834. `eof?` is a blocking call, and I don't think it's a call that's necessary to do.
=> system_command: improve EOF handling

Library/Homebrew/cmd/update-report.rb
-----
add the explanation of how to see outdated formulae and casks to`Homebrew#update_report`
=> update-report: add how to check the outdated

Library/Homebrew/cmd/fetch.rb, Library/Homebrew/software_spec.rb
Have to implement some custom logic here as there's two resources rather than one.
=> Fix `brew fetch --force` for GitHub Packages bottle tab download.

Library/Homebrew/github_packages.rb
This is an alternative to #11002.
=> github_packages: set github package type annotation.

Library/Homebrew/utils/github/api.rb
-----
When a 401 error occurs, we currently throw `GitHub::API::RateLimitExceededError: GitHub API Error: This endpoint requires you to be authenticated.`. This is incorrect as it shouldn't be a `RateLimitExceededError`.
I noticed this because accessing the keychain is currently broken in the test environment because we override `ENV["HOME"]`.
=> utils/github/api: fix incorrect error when unauthenticated

Library/Homebrew/github_packages.rb
-----
Add `glibc_version` to `os.version` so that `brew install` can verify that the host has sufficiently recent version of glibc, and install the brewed glibc if not.
=> github_packages: Add sh.brew.bottle.glibc.version

Library/Homebrew/cask/audit.rb, Library/Homebrew/cask/cmd/audit.rb, Library/Homebrew/dev-cmd/audit.rb, Library/Homebrew/test/cask/audit_spec.rb
-----
Annotations were not shown anymore since switching from `brew cask audit` to `brew audit`.
=> Fix audit annotations for casks.

Library/Homebrew/download_strategy.rb
Add HTTP header Accept: application/vnd.oci.image.index.v1+json
=> CurlGitHubPackagesDownloadStrategy: Add Accept

Library/Homebrew/software_spec.rb
Fix CurlGitHubPackagesDownloadStrategy for third party taps.
=> CurlGitHubPackagesDownloadStrategy: Fix third-party taps

Library/Homebrew/dev-cmd/tap-new.rb, Library/Homebrew/test/dev-cmd/tap-new_spec.rb, Library/Homebrew/test/support/helper/spec/shared_context/integration_test.rb
-----
This PR fixes #10992. We should `setup_gpg!` before committing.
=> dev-cmd/tap-new: use `Utils::Git.setup_gpg!`

README.md
1password logo was broken and then i just fixed this.
=> Update 1password logo

Library/Homebrew/utils/github/api.rb
These will start changing in the next few weeks.
https://github.blog/changelog/2021-03-04-authentication-token-format-updates/
-----
=> github/api: update personal access token format.

Library/Homebrew/github_packages.rb
=> GHCR: Use reject to remove empty hash values

Library/Homebrew/dev-cmd/pr-pull.rb
-----
We use this in the scenario where we are running two uploads in the same job.
=> dev-cmd/pr-pull: don't cherry-pick on --no-commit

Library/Homebrew/dev-cmd/pr-upload.rb, Library/Homebrew/github_packages.rb
- replace `+` in formula names (because it's an invalid character)
- do a `skopeo inspect` first to avoid overwriting existing packages
=> github_packages: fix more bulk upload errors.

Library/Homebrew/github_packages.rb
=> github_packages: fix typo.

Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/test/dev-cmd/bottle_spec.rb
-----
We shouldn't error about changes if there wasn't actually any changes.
=> dev-cmd/bottle: don't fail on --keep-old with unchanged values

Library/Homebrew/github_packages.rb
Addresses https://github.com/Homebrew/brew/pull/11056#issuecomment-815261503
=> github_packages: fix `source` for Linuxbrew bottles.

Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/test/dev-cmd/bottle_spec.rb
Addressing https://github.com/Homebrew/homebrew-core/pull/74815#issuecomment-815922580
=> dev-cmd/bottle: avoid outputting new default bottle domain.

Library/Homebrew/github_packages.rb
-----
The MacOS version conversion was erroring for me because we pass a string to `from_symbol`. I also missed this file in the `Utils::Bottles::Tag` refactoring.
The error only affects old bottles without a `built_on`.
=> github_packages: fix bottle tag handling

Library/Homebrew/cli/named_args.rb, Library/Homebrew/dev-cmd/bottle.rb
-----
If we pass multiple bottles from different OS versions, don't only deal with one of them. We want to read all bottles and produce a JSON for each one.
=> dev-cmd/bottle: don't take uniq of arguments

Library/Homebrew/dev-cmd/bottle.rb
-----
Ensure that `org.opencontainers.image.created` doesn't change for the existing bottles when adding a new bottle to an existing tag.
=> bottle: Set date to the mtime of the bottle file

Library/Homebrew/compat/early/download_strategy.rb, Library/Homebrew/livecheck/livecheck.rb
See https://github.com/Homebrew/brew/pull/11075#discussion_r610602507
=> Remove some premature `odisabled`

Library/Homebrew/github_packages.rb
-----
Addressing a couple of findings from my uploads:
* Don't assume an error always means the tag is missing. If connection failed, or credentials are wrong etc, then we don't want to treat it like the image is missing and disable `--keep-old` - we want to bail out.
* Pass `--raw` to `skopeo inspect` so that you can run it on Linux while inspecting a Darwin image.
=> github_packages: safer handling of `skopeo inspect`

Library/Homebrew/dev-cmd/bottle.rb
Fixes https://github.com/Homebrew/brew/pull/11057#issuecomment-817846023
=> dev-cmd/bottle: don't assume `desc` present.

Library/Homebrew/github_packages.rb
-----
This seems to be very similar to "name unknown".
=> github_packages: handle "manifest unknown"

Library/Homebrew/completions/bash.erb, Library/Homebrew/style.rb, completions/bash/brew
=> Use `shellcheck` on Bash completion file

.github/ISSUE_TEMPLATE/bug.yml
-----
See https://github.com/Homebrew/homebrew-core/pull/75049, https://github.com/Homebrew/homebrew-core/pull/75088.
=> bug.yml: update issue template

bin/brew
-----
repair `bin/brew` style for `brew style` with `--enable=all`
related https://github.com/Homebrew/brew/issues/11086
=> bin/brew: repair style

Library/Homebrew/service.rb, Library/Homebrew/test/service_spec.rb
-----
Slowly working my way to `brew services` support on Linux, let the holy-service-management-bike-shedding wars begin :smile:
=> Service: generate systemd unit file

Library/Homebrew/dev-cmd/bottle.rb
This is a more complete version of `--numeric-owner`.
Needed for https://github.com/Homebrew/homebrew-core/pull/75299
Part of https://github.com/Homebrew/brew/issues/11149
=> dev-cmd/bottle: set uid/gid.

Library/Homebrew/formula.rb
-----
We don't typically run unit tests, so we shouldn't waste time trying to build them.
=> formula: add `-DBUILD_TESTING=OFF` to `std_cmake_args`

Library/Homebrew/dev-cmd/bump-formula-pr.rb, Library/Homebrew/utils/github.rb
-----
Closes: https://github.com/Homebrew/brew/issues/11143
Tested here: https://github.com/dawidd6/homebrew-test/pull/396
=> bump-formula-pr: add --fork-org flag

Library/Homebrew/dev-cmd/bump-cask-pr.rb
-----
Closes: https://github.com/Homebrew/brew/issues/11180
=> bump-cask-pr: add --fork-org flag

Library/Homebrew/brew.sh
-----
repair `brew.sh` style for brew style with `--enable=all`
related #11086
=> brew.sh: repair style

Library/Homebrew/items.sh
-----
repair `items.sh` style for `brew style` with shellcheck `--enable=all` 
related #11086
=> items.sh: repair style

Library/Homebrew/prefix.sh
-----
repair `prefix.sh` style for `brew style` with shellcheck `--enable=all`
related #11086
=> prefix.sh: repair style

Library/Homebrew/shims/linux/super/make, Library/Homebrew/shims/mac/super/ant, Library/Homebrew/shims/mac/super/apr-1-config, Library/Homebrew/shims/mac/super/bsdmake, Library/Homebrew/shims/mac/super/make, Library/Homebrew/shims/mac/super/mig, Library/Homebrew/shims/mac/super/pkg-config, Library/Homebrew/shims/mac/super/pod2man, Library/Homebrew/shims/mac/super/ruby, Library/Homebrew/shims/mac/super/xcrun, Library/Homebrew/shims/scm/git, Library/Homebrew/shims/utils.sh
-----
repair style of bash files in `shims` for `brew style` with shellcheck `--enable=all`
related #11086
=> Shims repair style

Library/Homebrew/dev-cmd/rubocop.sh
-----
repair `dev-cmd/rubocop.sh` style for `brew style` with shellcheck `--enable=all` 
related #11086
=> dev-cmd/rubocop.sh: repair style

Library/Homebrew/dev-cmd/bottle.rb
Take 2 on #11165 but use newish `libarchive` consistently on macOS.
=> dev-cmd/bottle: set uid/gid, use libarchive on macOS.

Library/Homebrew/dev-cmd/bottle.rb
Used now-removed old method name.
=> dev-cmd/bottle: fix libarchive installed check.

Library/Homebrew/shims/linux/super/make, Library/Homebrew/shims/mac/super/make
-----
remove `HOMEBREW_MAKE` block because it was undocumented.
related https://github.com/Homebrew/brew/pull/11179#discussion_r616593702
=> remove HOMEBREW_MAKE

docs/Maintainer-Guidelines.md
-----
Removes references to `:optional` and `:recommended` dependencies for maintainers.
=> docs: remove recommended/optional from maintainer guidelines

Library/Homebrew/tap.rb, Library/Homebrew/test/tap_spec.rb
=> Fix bump-formula-pr for taps with ssh remote url.

Library/Homebrew/utils/analytics.sh, Library/Homebrew/utils/lock.sh, Library/Homebrew/utils/ruby.sh
-----
repair style of bash files in `utils` for `brew style` with shellcheck `--enable=all`
related #11086
=> Utils repair style

Library/Homebrew/dev-cmd/pr-upload.rb
Currently breaking CI: https://github.com/Homebrew/homebrew-core/pull/75299#issuecomment-825634072
=> dev-cmd/pr-upload: fix bad args reference.

Library/Homebrew/dev-cmd/pr-upload.rb
Another failure https://github.com/Homebrew/homebrew-core/pull/75299#issuecomment-825654120
=> dev-cmd/pr-upload: fix json_files handling.

Library/Homebrew/cleanup.rb
=> cleanup: ignore DS_Store access failures.

Library/Homebrew/dev-cmd/bottle.rb
Instead of using `libarchive` on macOS (which has a non-zero dependency tree) let's instead use `gnu-tar` because:
- it has no dependencies
- we're already using it on Linux
I tested this locally with `ack` (which was getting reproducible bottles with system and Homebrew `libarchive`) and saw a different checksum. A quick read of the `gtar` manpage indicated that it uses a GNU tar format by default which can be made consistent with BSD and GNU tar by using `--format=ustar` with both. Once this is done, the checksums are the same. This will hopefully ease the transition to having `all:` bottles be consistent on Linux, too, which will be useful when homebrew-core is fully merged/supporting Linux.
=> dev-cmd/bottle: tweak tar and tar arguments.

Library/Homebrew/dev-cmd/bottle.rb
-----
* `ustar` is too restrictive on file path lengths - we need PAX.
* The ordering of contents is non-deterministic, but `gnu-tar` provides a `--sort` option to solve this (`libarchive` does not but can be worked around)
* GNU Tar's implementation of PAX also has some non-deterministic data. In particular, the headers contain the PID for versions < 1.33. Also clear atime and ctime to be safe (the latter being something that's messy to control). Set `--pax-option` to deal with this.
System `libarchive` bsdtar could potentially be retained, but it'll need more testing.
=> dev-cmd/bottle: use gnu-tar universally, sort entries & use PAX

docs/Cask-Cookbook.md, docs/README.md
-----
Move docs from the cask repo to docs.brew.sh
CC @Homebrew/cask
=> docs: add Cask Cookbook

docs/Interesting-Taps-and-Forks.md
Still a work in progress, but I've gotten the release process pretty much worked out.
-----
=> Interesting-Taps-and-Forks.md: add gromgit/fuse

docs/Brew-Livecheck.md
-----
Reworded some things, unindented examples and added docs for `Sparkle` `strategy` blocks.
=> Improve livecheck docs.

Library/Homebrew/extend/os/mac/unpack_strategy/zip.rb, Library/Homebrew/unpack_strategy/zip.rb
-----
https://github.com/Homebrew/homebrew-core/pull/75961
=> unpack_strategy/zip: ensure consistent timezone management

Library/Homebrew/brew.sh, Library/Homebrew/cmd/--version.sh, Library/Homebrew/cmd/casks.sh, Library/Homebrew/cmd/shellenv.sh
-----
repair three bash files( `casks`, `--version` and `shellenv` ) style for `brew style` with `shellcheck`.
=> Cmd repair style

Library/Homebrew/dev-cmd/bottle.rb
These were added but didn't actually output anything...
=> dev-cmd/bottle: add missing verbose puts.

Library/Homebrew/dev-cmd/bottle.rb
More debugging for the bottle rebuild workflow.
=> dev-cmd/bottle: output more filenames when verbose.

Library/Homebrew/dev-cmd/bottle.rb
=> dev-cmd/bottle: fix `all` JSON filename

Library/Homebrew/dev-cmd/bottle.rb
Fixes https://github.com/Homebrew/homebrew-core/runs/2467738434?check_suite_focus=true#step:6:458
=> dev-cmd/bottle: handle empty collector tags.

Library/Homebrew/dev-cmd/bottle.rb
Fixes https://github.com/Homebrew/brew/pull/11283#discussion_r623181245
=> dev-cmd/bottle: remove double [tag].

Library/Homebrew/formula_installer.rb
=> formula_installer: don't require unpinning build deps when pouring.

Library/Homebrew/completions.rb, Library/Homebrew/completions/bash.erb, Library/Homebrew/test/completions_spec.rb, completions/bash/brew, manpages/brew.1
=> Fix `shellcheck` style errors on bash completion file

Library/Homebrew/caveats.rb, Library/Homebrew/extend/os/mac/caveats.rb, Library/Homebrew/test/caveats_spec.rb
=> services: replace plist_options :manual with service command

Library/Homebrew/github_packages.rb
-----
https://github.com/Homebrew/homebrew-core/runs/2501632606?check_suite_focus=true#step:10:77
=> github_packages: add missing root mkpath

Library/Homebrew/dev-cmd/bottle.rb, Library/Homebrew/formula_versions.rb
-----
Alternative version of https://github.com/Homebrew/brew/pull/11284 that considers only the latest rebuild
=> bottle: Only consider latest rebuild

docs/Common-Issues.md
Not sure why CI didn't catch this the first time.
=> docs/Common-Issues: remove Oxford comma.

Library/Homebrew/test/cask/installer_spec.rb
I see this failing every couple of days despite no changes.
=> cask/installer_spec: delete flaky test.

Library/Homebrew/formula.rb, Library/Homebrew/formula_installer.rb, Library/Homebrew/test/formula_installer_spec.rb
=> service: install linux service file

Library/Homebrew/cmd/update-report.rb, Library/Homebrew/cmd/update.sh
-----
repair `cmd/update.sh`style for `brew style `with shellcheck `--enable=all`
related #11086
=> cmd/update.sh: repair bash style

Library/Homebrew/formula_installer.rb
-----
This enables `RPATH` relocation upon pouring bottles.
Part of #11329.
=> formula_installer: set `HOMEBREW_RELOCATE_RPATHS`

Library/Homebrew/development_tools.rb, Library/Homebrew/os/mac/xcode.rb
-----
Also adjust Clang version handling to better differentiate patch versions. (Clang in Xcode 12.5 is Clang 12.0.5.)
=> os/mac/xcode: support Xcode 12.5

Library/Homebrew/dev-cmd/bottle.rb
-----
Apple gzip and GNU gzip differ in implementation and produce different gzips.
Instead, we can use the Ruby's `Zlib::GzipWriter` to produce consistent output across all platforms.
Note that the gzips produced here actually match what Apple gzip does, as Apple gzip also uses zlib internally. So this change should not result in any checksum change to macOS bottles.
=> dev-cmd/bottle: make gzip creation consistent across platforms

Library/Homebrew/cli/args.rbi, Library/Homebrew/cmd/leaves.rb, Library/Homebrew/test/cmd/leaves_spec.rb, completions/bash/brew, completions/fish/brew.fish, completions/zsh/_brew, docs/Manpage.md, manpages/brew.1
-----
Closes #10754. Still need to write tests. Also considering writing method(s) for some shared code between autoremove and leaves.
=> Add leaves --installed-on-request and --installed-as-dependency flags

Library/Homebrew/extend/os/mac/keg_relocate.rb
-----
See https://github.com/Homebrew/homebrew-core/issues/77797 and https://github.com/Homebrew/brew/issues/11275#issuecomment-846522409.
=> Fix perl shebang rewriting for `perl` formula

Library/Homebrew/service.rb, Library/Homebrew/test/service_spec.rb
-----
Adds some of the missing launchctl settings.
=> Service: add additional options

Library/Homebrew/service.rb, Library/Homebrew/test/service_spec.rb
=> service: ensure environment variables are strings

Library/Homebrew/diagnostic.rb
-----
add` homebrew/cask` tap to `Diagnostic::Checks#check_git_status` because we should check not only `brew` and `core` tap git status but also `cask` status.
=> add cask tap to Diagnostic::Checks#check_git_status

Library/Homebrew/extend/os/linux/linkage_checker.rb
=> linkage_checker: add libatomic

Library/Homebrew/utils/github.rb, Library/Homebrew/utils/github/api.rb
-----
change  `https://api.github.com` to const `API_URL` like the others in `utils/github.rb`.
=> change https://api.github.com to API_URL

Library/Homebrew/extend/ENV/super.rb
=> super: fix GCC linkage issue in Linux

Library/Homebrew/dev-cmd/vendor-gems.rb, Library/Homebrew/utils.rb, Library/Homebrew/utils/gems.rb
=> Revert "fix(vendor-gems): redirect bundler stdout to stderr"

Library/Homebrew/service.rb, Library/Homebrew/test/service_spec.rb
-----
Without this the generated service can't be enabled.
=> service: add install block to unit

Library/Homebrew/os/mac/pkgconfig/12/expat.pc, Library/Homebrew/os/mac/pkgconfig/12/libcurl.pc, Library/Homebrew/os/mac/pkgconfig/12/libedit.pc, Library/Homebrew/os/mac/pkgconfig/12/libexslt.pc, Library/Homebrew/os/mac/pkgconfig/12/libffi.pc, Library/Homebrew/os/mac/pkgconfig/12/libxml-2.0.pc, Library/Homebrew/os/mac/pkgconfig/12/libxslt.pc, Library/Homebrew/os/mac/pkgconfig/12/ncurses.pc, Library/Homebrew/os/mac/pkgconfig/12/ncursesw.pc, Library/Homebrew/os/mac/pkgconfig/12/sqlite3.pc, Library/Homebrew/os/mac/pkgconfig/12/uuid.pc, Library/Homebrew/os/mac/pkgconfig/12/zlib.pc, Library/Homebrew/os/mac/xcode.rb
Following up on partial support in https://github.com/Homebrew/brew/pull/11504
This is `do not merge` for now as I'm waiting for the installation of CLT to check the exact clang version numbers.
=> Updates for Monterey Xcode & CLT

Library/Homebrew/cmd/install.rb, Library/Homebrew/install.rb
-----
This PR extracts some methods out of the `install` command and places them into the `Install` module.
I think this cleanup makes the `install` command easier to read. Plus, it allows the methods to be used elsewhere (e.g. in the `homebrew/json` tap).
=> Refactor install methods

Library/Homebrew/utils/github.rb
=> github.rb: correct one dry-run message

docs/New-Maintainer-Checklist.md
-----
This PR fixes some minor punctuation typos and odd diction in the new maintainer checklist.
=> Fix diction and punctuation typos in new maintainer checklist

Library/Homebrew/cmd/doctor.rb, Library/Homebrew/diagnostic.rb
-----
add `sort` to `Diagnostic::Checks#all` because every `checks.all` in `cmd/doctor.rb` uses `sort`.
=> repair Diagnostic::Checks#all

.github/workflows/tests.yml
This pull request is a follow-up to https://github.com/Homebrew/brew/pull/11578 to address the discovery noted in https://github.com/Homebrew/brew/pull/11578#discussion_r657032173 regarding this conditional:
https://github.com/Homebrew/brew/blob/5379ff15b8414a6741895b27a9976bb86a5603d8/.github/workflows/tests.yml#L324-L327
We discovered that the conditional was preventing the step from running on pushes to the master branch. (It would also prevent the step from running on pushes to any other branches that don't have a pull request associated with them.)
With the changes in this pull request, the step will run in any of these scenarios:
- A push to a branch in Homebrew/brew (not a fork)
- A pull request where the head branch is in Homebrew/brew (not a fork)
Since this change is aimed at …
=> Upload test results to BuildPulse for non-PR pushes

Library/Homebrew/livecheck/strategy/sparkle.rb
-----
Some folks have had issues with the `nokogiri` gem in relation to the `Sparkle` strategy (as seen in #11486) and it was suggested that we simply replace `nokogiri` with `rexml`. This seemed like a good idea to me, as we were also having issues with the output from `Homebrew.install_bundler_gems!` on `brew livecheck --json` runs that involve the `Sparkle` strategy (i.e., the `bundle` output prevents livecheck's output from being exclusively JSON). Using `rexml` would fix both of those issues and that's the goal of this PR.
---
One challenge with this was replacing the behavior of `nokogiri`'s `#remove_namespaces!` method, as `rexml` doesn't have anything similar. From what I gathered in testing this and looking through the existing `Sparkle` code, the intention was to remove prefixes …
=> Sparkle: Replace Nokogiri with REXML

.github/workflows/tests.yml, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/test/utils/repology_spec.rb, Library/Homebrew/utils/repology.rb
- be more verbose with output to be clear when we're using/submitting to BuildPulse
- remove the duplicate BuildPulse submission step
=> Fix BuildPulse handling

Library/Homebrew/extend/os/linux/keg_relocate.rb
-----
This might cause trouble for us in homebrew-core.
=> keg_relocate: swap env var

Library/Homebrew/rubocops/components_order.rb
-----
Needed for: https://github.com/Homebrew/homebrew-core/pull/80555
=> components_order: allow ignore_missing_libraries in on_os

Library/Homebrew/cmd/--prefix.rb, Library/Homebrew/keg.rb
-----
Python 3.10 is due later this year, so I've adjusted some code that currently only applies to Python 3.9 or earlier.
=> keg, cmd/--prefix: handle python3.10

.github/workflows/tests.yml
Let's cancel in-progress builds on the same PR.
=> workflows/tests: enable concurrency limiting.

Library/Homebrew/formula_auditor.rb
-----
repair audit_specs because an `if` condition is hard to read.
=> formula_auditor: repair audit_specs

Library/Homebrew/formula_auditor.rb
-----
make the `return` syntax style the same as the others.
=> formula_auditor:repiar audit_versioned_keg_only

README.md
=> README: update sponsors.

docs/Bottles.md, docs/External-Commands.md, docs/FAQ.md, docs/Gems,-Eggs-and-Perl-Modules.md, docs/How-to-Build-Software-Outside-Homebrew-with-Homebrew-keg-only-Dependencies.md, docs/Installation.md, docs/Tips-N'-Tricks.md
Update or remove these based on our latest state.
=> docs: update /usr/local references.

Library/Homebrew/formula.rb
-----
See discussion at Homebrew/homebrew-core#81408.
=> formula: add `:default_prefix` as a standard `pour_bottle?` requirement

Library/Homebrew/cmd/search.rb
-----
See https://github.com/Homebrew/brew/pull/11736#discussion_r672233442.
=> cmd/search: tweak help text

Library/Homebrew/formula_cellar_checks.rb
-----
This will make the error more informative by showing the architecture a
binary was built for along with the error message.
Before:
foo:
* Binaries built for an incompatible architecture were installed into foo's prefix.
The offending files are:
/usr/local/Cellar/foo/1.0/lib/libbar.dylib
/usr/local/Cellar/foo/1.0/lib/libfoo.dylib
/usr/local/Cellar/foo/1.0/lib/libincompatible.dylib
Unexpected universal binaries were found.
The offending files are:
/usr/local/Cellar/foo/1.0/lib/liball.dylib
/usr/local/Cellar/foo/1.0/lib/libuniversal.dylib
After:
foo:
* Binaries built for a non-native architecture were installed into foo's prefix.
The offending files are:
/usr/local/Cellar/foo/1.0/lib/libbar.dylib        (i386)
/usr/local/Cellar/foo/1.0/lib/libfoo.dylib        (arm64) …
=> formula_cellar_checks: show mismatched arch in `check_binary_arches`

Library/Homebrew/formula.rb, Library/Homebrew/test/formula_installer_spec.rb, Library/Homebrew/test/formula_spec.rb
-----
Couldn't run tests because of a sorbet issue, so I'm having CI do it.
Fixes https://github.com/Homebrew/homebrew-services/issues/363
=> Formula: use opt_prefix for service helpers

docs/Formula-Cookbook.md, docs/Homebrew-homebrew-core-Maintainer-Guide.md, docs/How-To-Open-a-Homebrew-Pull-Request.md
- [] Have you successfully run `brew typecheck` with your changes locally? 
On M1, arch not supported.
-----
Some small doc tweaks, including more complete commands and removing legacy advices.
=> Doc tweaks

Library/Homebrew/formula_installer.rb
-----
Fix the issue created in https://github.com/Homebrew/brew/pull/11772
=> formula_installer: install service after linking

Library/Homebrew/extend/pathname.rb
=> extend/pathname: handle missing permissions on removal.

Library/Homebrew/env_config.rb, Library/Homebrew/software_spec.rb, Library/Homebrew/sorbet/rbi/hidden-definitions/hidden.rbi, docs/Manpage.md, manpages/brew.1
=> Revert "Remove HOMEBREW_BOTTLE_DOMAIN"

Library/Homebrew/cmd/gist-logs.rb
#11594 introduces _subdirectories_ for additional logs (e.g. CMake build logs), so `brew gist-logs` [can now throw errors like](https://github.com/Homebrew/linuxbrew-core/issues/24017):
```
$ brew gist-logs gcc
Error: Is a directory @ io_fread - /home/yz/.cache/Homebrew/Logs/gcc/build
```
This PR grabs log files recursively, but GitHub's gists can't deal with directory separators in relative paths. Therefore, I'm also replacing all `/` with `:`, since I assume Windows support is not on the cards any time soon. This means gists will now contain paths like `build:amalgamation:CMakeFiles:CMakeOutput.log`, which I find more-or-less readable, but I'm open to suggestions for directory separator replacements. (I didn't use `_` because that's already a common character in filenames.)
=> gist-logs: grab files in subdirectories too

Library/Homebrew/dependency_collector.rb, Library/Homebrew/download_strategy.rb, Library/Homebrew/exceptions.rb, Library/Homebrew/formula_auditor.rb, Library/Homebrew/resource_auditor.rb, Library/Homebrew/utils/curl.rb
=> Use Homebrew curl for audit when specified in the formula

Dockerfile
-----
The better fix was https://github.com/Homebrew/homebrew-test-bot/pull/654
=> Dockerfile: revert the revert of #11818 and #11819

Library/Homebrew/shims/utils.sh, bin/brew
=> bin/brew: actually quiet cd

Library/Homebrew/cmd/--cache.rb
=> cmd/cache: add `--HEAD` switch

README.md, docs/Homebrew-brew-Maintainer-Guide.md
This should be useful in helping people figure out 1) how to use BuildPulse and 2) why it's useful.
Thanks to @jasonrudolph for help with all this!
=> Add BuildPulse links, docs

Library/Homebrew/upgrade.rb
=> upgrade: revert renaming of create_formula_installer

Library/Homebrew/dev-cmd/pr-automerge.rb
=> pr-automerge: enable automerging linux-only PRs

Library/Homebrew/cmd/install.rb, Library/Homebrew/install.rb
=> install: fetch all formulae before install

Library/Homebrew/rubocops/uses_from_macos.rb, Library/Homebrew/test/support/helper/spec/shared_examples/formulae_exist.rb
=> rubocops: allow uses_from_macos `openssl@3`

Library/Homebrew/download_strategy.rb
`FossilDownloadStrategy` attempts to call `silent_command!` in two places; this does not exist.  From the context (i.e. other download strategies) it looks like these two calls should use `command!` rather than `silent_command` (which _does_ exist).
```
> brew install --HEAD libspatialite
==> Cloning https://www.gaia-gis.it/fossil/libspatialite
Error: undefined method `silent_command!' for #<FossilDownloadStrategy:0x00007fc4bea821b0>
Did you mean?  silent_command
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:1319:in `clone_repo'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:208:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:142:in `fetch' …
```
=> Replace two calls to undefined silent_command! in FossilDownloadStrategy with command!

Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.arm64_monterey.bottle.tar.gz, Library/Homebrew/test/support/fixtures/bottles/testball_bottle-0.1.monterey.bottle.tar.gz
-----
Needed for `brew tests` to pass on Monterey.
=> test/support/fixtures/bottles: add fixtures for Monterey

Library/Homebrew/shims/mac/super/swift
-----
Ensures the SDK used matches Homebrew's choice of SDK.
=> shims: set SDKROOT for Swift

Library/Homebrew/cask/cmd/install.rb, Library/Homebrew/cask/installer.rb, Library/Homebrew/cmd/install.rb
-----
solve https://github.com/Homebrew/brew/issues/12010
=> repair cask install quiet mode

Library/Homebrew/dev-cmd/bump-cask-pr.rb
-----
Working on this to fix #11645
Still WIP/POC as I haven't had much chance to try it out.
=> bump-cask-pr: use similar logic to `brew fetch`

Library/Homebrew/utils/ruby.sh
-----
`which` is a non-standard command for Bash ([shellcheck SC2230](https://github.com/koalaman/shellcheck/wiki/SC2230)). Besides, `which` command shows aliases as well but not in the desired format:
```console
$ which -a python
/usr/bin/python
$ alias python='python3'
$ which -a python
python: aliased to python3
/usr/bin/python
```
Remove dependency for `which` command, see Homebrew/install#574 and Homebrew/install#575 for more details.
=> utils/ruby.sh: remove dependency for `which` command

Library/Homebrew/install.rb, Library/Homebrew/upgrade.rb
=> Fix undefined method error following CannotInstallFormulaError

.github/workflows/triage.yml
-----
Not sure why it's not possible for syntax checking to occur before merging.
=> workflows/triage: fix syntax

Library/Homebrew/extend/os/mac/diagnostic.rb
=> os/mac/diagnostic: also check Xcode minimum version on env setup

Library/Homebrew/cmd/info.rb
-----
A one line message can often be not very useful in debugging.
=> cmd/info: print backtrace to developers for unreadable formulae/casks

Library/Homebrew/shims/mac/super/pkg-config
-----
https://github.com/Homebrew/brew/pull/12086#issuecomment-922454101
=> shims/mac/super/pkg-config: fix shebang

Library/Homebrew/language/python.rb
-----
Also, clean up one use of an `options` hash, because this is no longer
needed.
Closes #11885.
=> language/python: allow formulae to restrict access to system site packages

Library/Homebrew/language/python.rb
-----
Fixes a bug introduced in 09570fc7a66af8c43626a869888ebc484745c587.
=> language/python: bug fix

Library/Homebrew/formula_installer.rb
-----
Noticed homebrew-core CI was taking twice as long.
=> formula_installer: fix installation of local bottles

Library/Homebrew/os/mac/xquartz.rb
-----
This should go completely. We maybe need to properly deprecate `ENV.x11` first though, not entirely sure.
Fixes #12115.
=> os/mac/xquartz: fix handling of XQuartz 2.8.0+

.github/workflows/triage.yml
=> workflows/triage: fixes for github-script@v5

Library/Homebrew/utils/bottles.rb
-----
We do not currently include the rebuild number in the JSON filename, so this should be stripped.
=> utils/bottles: fix local JSON handling for bottle rebuilds

Library/Homebrew/os/mac/xcode.rb
-----
Xcode 13 is being installed in the CI as I speak.
=> os/mac/xcode: support Xcode 13

Library/Homebrew/utils/shfmt.sh
-----
The BSD version `diff` command on macOS does not support option `--color=auto`, which will cause failure for the CI tests (e.g. [Homebrew/install fails on `brew style *.sh` on macOS](https://github.com/Homebrew/install/runs/3720483166?check_suite_focus=true)).
This PR install `diffutils` (the GNU version `diff` command) as a dependency for `brew style`. This will make the `diff` command provide consistent functionality on both macOS and Linux.
=> utils/shfmt.sh: enable coloring only when brewed `diffutils` is installed

Library/Homebrew/cmd/readall.rb, Library/Homebrew/dev-cmd/tests.rb, Library/Homebrew/extend/ENV/super.rb, Library/Homebrew/extend/os/mac/keg_relocate.rb, Library/Homebrew/rubocops/bottle.rb, Library/Homebrew/tap.rb, Library/Homebrew/test/cask/cmd/uninstall_spec.rb, Library/Homebrew/test/cleanup_spec.rb, Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-script-app.rb, Library/Homebrew/test/support/fixtures/cask/Casks/with-uninstall-script-user-relative.rb, Library/Homebrew/test/utils_spec.rb, Library/Homebrew/utils/formatter.rb, Library/Homebrew/utils/repology.rb
Fixes for https://github.com/Homebrew/brew/pull/12152.
Extracted into a separate PR so this can be merged immediately.
=> Fix `brew style`

Library/Homebrew/cmd/info.rb
-----
repair `brew info --github` description because `brew info --github`  and `brew log` are for formula and cask.
=> repair brew info description

Library/Homebrew/utils.rb
=> Add VS Code to list of fallback editors

Library/Homebrew/cmd/update.sh
=> cmd/update.sh: don't absorb ca-certificates installation failure

Library/Homebrew/download_strategy.rb
-----
https://github.com/Homebrew/brew/pull/12172#pullrequestreview-770504656
=> download_strategy: remove redundant conditional

Library/Homebrew/utils/curl.rb
-----
https://github.com/Homebrew/homebrew-core/pull/86415#issuecomment-933651344
=> utils/curl: fix flag handling

Library/Homebrew/utils/curl.rb
-----
We're not compacting here so this can error.
=> utils/curl: fix false flag handling

Library/Homebrew/download_strategy.rb
-----
https://github.com/Homebrew/brew/pull/12172#pullrequestreview-770647004
=> download_strategy: adjust --insecure warning wording

Library/Homebrew/utils/curl.rb
-----
https://github.com/Homebrew/brew/pull/12177#pullrequestreview-771338658
=> utils/curl: add comment detailing options handling

Library/Homebrew/system_config.rb, Library/Homebrew/utils/curl.rb
-----
See discussion at #12191.
=> system_config: don't print path to curl shim

Library/Homebrew/keg_relocate.rb
-----
This is a continuation of #12334.
#12334 needs to land in a release tag before merging this.
=> keg_relocate: enable Java relocation for bottles

Library/Homebrew/extend/os/mac/search.rb
-----
`Cask.search` is extremely slow because it loads all casks. This PR reduces `/usr/bin/time brew search ruby` from `13.70 real` to  `4.76 real` (approximately). (`Tap#cask_tokens` is a misnomer because it actually returns full cask names.)
=> search: optimize cask search

Library/Homebrew/cmd/vendor-install.sh
Fixes https://github.com/Homebrew/brew/issues/12351
=> vendor-install: better handle /usr/local arm64 ruby.

Library/Homebrew/dev-cmd/bottle.rb
-----
Fix a small error in the rebuild logic for `all` bottle selection.
=> dev-cmd/bottle: correct `all` rebuild matching logic

Library/Homebrew/cmd/update.sh, Library/Homebrew/completions/bash.erb, Library/Homebrew/style.rb, bin/brew, completions/bash/brew
=> Fix shellcheck `brew style` errors

Library/Homebrew/cask/audit.rb, docs/Cask-Cookbook.md
---
This is an extension of #12377 based on https://github.com/Homebrew/brew/pull/12377#discussion_r742548329.
[homebrew-cask /doc/development/adding_a_cask.md](https://github.com/Homebrew/homebrew-cask/blob/de168df318e27883abf5d1c483860467ed169ec7/doc/development/adding_a_cask.md) also has references which will need to be updated (no other Homebrew repos or files have references to this section).
homebrew-cask PR: https://github.com/Homebrew/homebrew-cask/pull/113948
=> Docs: Update cask cookbook header

Library/Homebrew/os/mac.rb
-----
Should have probably done this a couple weeks ago.
=> os/mac: bump latest SDK

Library/Homebrew/brew.sh, Library/Homebrew/cmd/vendor-install.sh, Library/Homebrew/extend/os/mac/diagnostic.rb, Library/Homebrew/os/mac/xcode.rb, Library/Homebrew/utils/ruby.sh
=> os/mac/xcode: update latest Xcode to 13.1 on Big Sur

.github/workflows/tests.yml
-----
Revert edit made in #12296: still need to preinstall `svn` on this repository for all tests to run.
=> tests.yml: resume preinstalling subversion

Library/Homebrew/cmd/search.rb
=> search: split up command into multiple methods
